### ISSUE TITLE
Livechat Appearance page is corrupted.

### ISSUE THREAD

**Issue by chojunki** [RocketChat/Rocket.Chat#14520] opened 2019-05-16 03:06 UTC
### Description:

Just look at the screenshot:

![2019-05-16](https://user-images.githubusercontent.com/24218869/57823473-a06f5880-77d2-11e9-88d3-ab46149a2c0b.png)

### Steps to reproduce:

1. Install and run Rocket.Chat 1.0.3
2. Go to Livechat - appearance page.
3. Check.

### Expected behavior:

Livechat preview should be seen at the right place.

### Actual behavior:

Livechat preview is shown over configuration items, covering them.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: CentOS 7.5
- Deployment Method: As mentioned in Official Installation Procedure.
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6.12

**Comment by reetp** [comment] 2019-07-03 11:37
@rocket-cat close

Duplicate of #14715 and fixed in v1.2.1

**Closed by reetp** 2019-07-03 11:37 UTC
