### ISSUE TITLE
User as Room -> could not be found

### ISSUE THREAD

**Issue by Vilkaz** [RocketChat/Rocket.Chat#8850] opened 2017-11-13 09:47 UTC
### Description:

i can't write to one specific User in our team.

Others can write to him, and when he is sending me an message, the push notification in bottom right pops, but if im not fast enaugh and want to check our history, i only get 
"Room could not be found"
and 
"There was no user found with the name "name of the user"

![image](https://user-images.githubusercontent.com/8351796/32718850-ba0429f8-c85e-11e7-8663-d418ee1bc31d.png)

i have no problems with others users.

i reinstalled the RocketChat allready two times (without and with deleting all the local data)

IMPORTANT!
Before Installing RocketChat, he tried a rocketChat Plugin for pidgin.

i was triing tocomunicate with him, while he was testin gthis plugin.

I Assume, something was flaged wrong while that test, now i am unable to find him, others can write to him, his pushup messages comes true, but we have no chat channel/history .... 

Same in webClient.

### Server Setup Information:
Rocket.Chat+
Version 2.10.1
Windows 7

### Steps to Reproduce:

1. search user
2. room not found ...

### Expected behavior:

Uer Chat history

### Actual behavior:
2. room not found ...

**Comment by mrsimpson** [comment] 2017-11-14 14:44
May you have a server side exception mentioning a duplicate key in an index?
Please re-execute sending a message to him, then go to "show logs" in the administration area.

**Comment by TwizzyDizzy** [comment] 2017-11-14 14:59
possibly a dupe of #6535.

**Comment by TwizzyDizzy** [comment] 2018-02-07 13:17
@rocket-cat close

Closing this in favour of #6535. It is pretty likely, that this is the cause of your issue. If you do not agree, please say why and provide steps to reproduce your actual issue.

Also we would have to verify whether this is an actual Rocket.Chat issue or might be an issue in the Electron App.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-02-07 13:17 UTC
