### ISSUE TITLE
android app in f-droid o apk download

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#4838] opened 2016-11-03 07:24 UTC
Hello Devs.

Is it possible to push rocketchat to f-droid or make it possible to get the apk for all no google users among us?

thanks and cheers
t.

**Comment by knarf-hackatal2016** [comment] 2017-05-12 08:57
Having it on Aptoide would be nice too.

**Comment by geekgonecrazy** [comment] 2017-07-23 01:26
Duplicate of https://github.com/RocketChat/Rocket.Chat.Cordova/issues/104

**Closed by geekgonecrazy** 2017-07-23 01:26 UTC
Labels: subj: mobile, type: support
