### ISSUE TITLE
Add the field "Full name" to manually fill in the "fname" when creating the channel

### ISSUE THREAD

**Issue by cadetmsv** [RocketChat/Rocket.Chat#13019] opened 2018-12-21 13:31 UTC
We use a lot of channels in our work. When creating new channels we faced a problem in the channel names. In the channel name you can use only English letters, numbers and symbols "-", "_". It is impossible to create a channel with a name in the native language (Russian). The "UI_Allow_room_names_with_special_chars" parameter in "true" does not solve the problem. 

I have already reported about this problem in #12638
and on the forum https://forums.rocket.chat/t/readable-display-of-the-full-names-of-rooms-channels/2556
But there were no reactions. So I raise the question again.

Is it possible to add the "Full name" field related to "fname" in the database to the channel creation form?  When displaying the list of channels in the "Real Name" mode, the channel name will be taken from "fname". Requirements to the channel name as an identifier will not change, but it will be possible to display the full name in the desired format and language.

Such completion will improve the work in RocketChat.

**Comment by reetp** [comment] 2018-12-28 16:46
For New Feature Requests you should keep discussions in the forums and not here.
If they are popular the developers will consider them, but it does depend on their priorities. Please don't keep asking though. It won't get your request looked at any quicker.
Thank you.

**Comment by reetp** [comment] 2018-12-28 16:47
@rocket-cat close
Duplicate of #12638

**Closed by reetp** 2018-12-28 16:47 UTC
