### ISSUE TITLE
Login errors in 3.1.0

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#17259] opened 2020-04-11 10:22 UTC
### Description:
After upgrade to v3.1.0:
 - I can't login to RC from Android App (v4.5.2)
 - I lose login every time I close desktop app / firefox tab

### Steps to reproduce:

1. Open desktop app / web browser
2. Login to server
3. Close web browser RC tab / dekstop app
4. Reopen app / browser tab

### Expected behavior:
Login remains

### Actual behavior:
After loading page is shown login page and error `Invalid User`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 12.14.0
- MongoDB Version: 3.6.17

### Client Setup Information

- Desktop App or Browser Version: App 2.17.9-1, Browser firefox 75.0-1
- Operating System: Arch linux

#### Server
Nothing :confused: 

#### Browser
```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIFaviconService.replaceFaviconDataFromDataURL]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/PlacesUIUtils.jsm :: loadFavicon :: line 209"  data: no] PlacesUIUtils.jsm:209:28
    loadFavicon resource:///modules/PlacesUIUtils.jsm:209
    loadFavicon resource:///modules/PlacesUIUtils.jsm:362
    setIconFromLink resource:///actors/LinkHandlerParent.jsm:154
    receiveMessage resource:///actors/LinkHandlerParent.jsm:71
TypeError: window is null 2 WebRequestContent.js:143:7
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] network-response-listener.js:84
Sync encountered an error - see about:sync-log for the log file. policies.js:1008
    resetFileLog resource://services-sync/policies.js:1008
    InterpretGeneratorResume self-hosted:1156
    AsyncFunctionNext self-hosted:695
```

**Comment by DJeremyy** [comment] 2020-04-11 11:17
Since the update to 3.1.0 made yesterday, I have the same errors when connecting to the web application. It disconnects after closing the tab with "Invalid user".

iOS (4.6.3) and Android (4.5.2) application no longer works. Unable to connect when I reset the app.

**Comment by danielnachtrub** [comment] 2020-04-11 12:49
We've got the same issue here. Started with an image upgrade.

Rocketchat is running in a docker-environment with nginx as reverse-proxy and LDAP backend. Docker is using the official image from hub. 

- Client application running on Windows can login but loses session upon restart or server reload. Same on macOS. 
- Running in browser rocketchat is working but after reloading the page the same error occurs.
- iOS app cannot login at all.

**Comment by Shaverdoff** [comment] 2020-04-11 12:57
guys - Forget User Session on Window Close is enabled?

**Comment by danielnachtrub** [comment] 2020-04-11 12:58
> guys - option on Accoutn settigns - Forget User Session on Window Close is enabled?

Not enabled here.

**Comment by dusatvoj** [comment] 2020-04-11 13:02
> guys - option on Accoutn settigns - Forget User Session on Window Close is enabled?

Disabled

**Comment by Shaverdoff** [comment] 2020-04-11 13:17
Rc confgired with ldap?

Отправлено с iPhone

**Comment by DJeremyy** [comment] 2020-04-11 13:19
> guys - option on Accoutn settigns - Forget User Session on Window Close is enabled?

Disabled for me

**Comment by danielnachtrub** [comment] 2020-04-11 13:19
We're using LDAP authentication.

**Comment by DJeremyy** [comment] 2020-04-11 13:20
> Rc confgired with ldap? Отправлено с iPhone
> […](#)
> 11 апр. 2020 г., в 16:59, Daniel Nachtrub ***@***.***> написал(а): ﻿ guys - option on Accoutn settigns - Forget User Session on Window Close is enabled? Not enabled here. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, I'm use LDAP sync for accounts and authentication.

**Comment by Shaverdoff** [comment] 2020-04-11 13:33
Its strange. I use the same conf and set. No login errors

Отправлено с iPhone

**Comment by dusatvoj** [comment] 2020-04-11 13:43
I have LDAP enabled

**Comment by danielnachtrub** [comment] 2020-04-11 13:44
Checking the console output from devtools on client it states:

> Error logging in with token: Error: Login forbidden [403]
> E2E -> Stop Client

**Comment by danielnachtrub** [comment] 2020-04-12 08:16
I found a workaround in our environment:
By enabling **Login Fallback** the issues do not arise anymore.

Seems that there's an issue to recognize existing sessions here. Perhaps request is cancelled when login fallback is disabled and therefore even existing sessions using tokens can't be validated.

**Comment by DJeremyy** [comment] 2020-04-12 10:44
> I found a workaround in our environment:
> By enabling **Login Fallback** the issues do not arise anymore.

This is also the case for me @danielnachtrub, activating 'Login Fallback' in the LDAP section no longer causes connection problems on Android and iOS. I no longer have 'Invalid user' when I close the tab and open it again.

**Comment by Shaverdoff** [comment] 2020-04-12 10:46
On 3.1.0 developers attache able to login without ldap if ldap is enabled and configured. So localy account 

 

 

 

--

Gerasim Shaverdov | Deputy CTO | Altarix 

Mobile:  <tel:+7%20937%20070%2066%2084> +7 937 070 66 84 | Skype/email:  <mailto:gerasim@altarix.ru> gerasim@altarix.ru
Lenina av.25, Samara, Russia, 443068

**Comment by pierre-lehnen-rc** [comment] 2020-04-13 19:36
Did everyone who had this problem uses LDAP?
If so, this may have been caused by #16949

**Comment by nebulade** [comment] 2020-04-13 19:39
We at Cloudron hit this as well now in our package tests. Those instances also use LDAP.

**Comment by DJeremyy** [comment] 2020-04-13 19:52
> Did everyone who had this problem uses LDAP?
> If so, this may have been caused by #16949

For me @pierre-lehnen-rc, I use LDAP. it seems to me that this is the case for everyone here.

**Comment by spanchy** [comment] 2020-04-13 21:53
I have same problem. LDAP auth enabled.

**Comment by tiredofit** [comment] 2020-04-14 13:40
Same problem with LDAP, Also cannot use SAML.

**Closed** 2020-04-14 18:14 UTC
Labels: subj:  Auth - LDAP, type: bug

**Comment by photoninger** [comment] 2020-04-22 13:10
Upgraded from 3.0.12 to 3.1.1, now both mobile apps (ios and android) crash on login with ldap users.
ldap fallback is enabled (was all the time)

**Comment by sampaiodiego** [comment] 2020-04-22 21:26
the app just crash? no additional info? @diegolmello how can we track down what is happening in this case?

**Comment by diegolmello** [comment] 2020-04-22 21:29
@sampaiodiego There's a fix on the way [here](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2055)

**Comment by tiredofit** [comment] 2020-04-22 21:36
I am seeing it as well and referenced in #17318 where the Syncing process has failed thus locking out my users.
