### ISSUE TITLE
ARM64 Docker Image

### ISSUE THREAD

**Issue by henrywithu** [RocketChat/Rocket.Chat#28624] opened 2023-03-25 12:36 UTC
Thanks for the wonderful RocketChat. It will be much appreciated if you can build an ARM64 docker image.
Btw, the snap version in SnapCraft.io is super out-dated (only version 4.x).

**Comment by AlexG-Surevine** [comment] 2023-04-25 07:27
Seconded on the ARM64 docker images - this would be very useful!

**Comment by spkane** [comment] 2023-09-15 16:11
This is a duplicate of #27305.

**Closed** 2023-12-15 09:54 UTC
