### ISSUE TITLE
Menus (message action menu and room action menu) opens in left top corner when opened for the first time or after reload. Reproducible for all browsers, not stable.

### ISSUE THREAD

**Issue by kkovrizhenko** [RocketChat/Rocket.Chat#11149] opened 2018-06-14 13:16 UTC
### Steps to reproduce:
1. Open browser not in full screen 
2. Open any chat
3. Click message action button or room action button

### Expected behavior:

Menu popover is opened under/above clicked button

### Actual behavior:
Menus (person’s menu and chat menu) opens in left top corner when opened for the first time or after reload. Reproducible for all browsers, not stable.
![2018-06-13_1422](https://user-images.githubusercontent.com/9197041/41409610-75ecdc5a-6fdf-11e8-8d84-526ebfe35206.png)

**Comment by robertwessen** [comment] 2018-06-14 14:22
same issue here, appeared after 0.65.1 upgrade.

**Comment by kaiiiiiiiii** [comment] 2018-06-14 14:37
Duplicate of #10668, will be fixed in next release by PR #11113

//CC: @TwizzyDizzy

**Comment by graywolf336** [comment] 2018-06-14 14:57
Duplicate of #10668, closing.

**Closed by graywolf336** 2018-06-14 14:57 UTC
