### ISSUE TITLE
Weird chat grouping

### ISSUE THREAD

**Issue by c0fe** [RocketChat/Rocket.Chat#3540] opened 2016-06-13 13:04 UTC
I got weird chat grouping. Here is what I mean:

![rocketchat](https://cloud.githubusercontent.com/assets/10472646/16008321/08e40ac6-313d-11e6-84c8-f5f5fd04b038.png)

You see that it isn't publishing the talk as in a regular chat fashion

Person A: Blah Blah
Person B: Blah Blah Blah
Person A: Blah Blah Blah Blah
Person A: Blah Blah Blah

But it is grouping them strangely. How can I get it to show up in more regular format?

**Comment by klatys** [comment] 2016-06-14 09:07
There's a setting for that. See administration > Message > Grouping Period (in seconds)
Grouping Period (in seconds) ![grouping period](http://image.prntscr.com/image/f4760a0f7a5a41e3a840a50e6ae7b168.png)

**Comment by geekgonecrazy** [comment] 2016-06-14 19:34
See @klatys 's suggestion.  That will help with grouping.  

As far as the messages get out of order.  That might be a problem.  But we're going to need a bit more information.

* Browser
* Server Version
* Deployment method
* Steps to reproduce

**Comment by throll** [comment] 2016-07-13 08:16
Hi,

We experienced the same issue and even a worse behaviour because some messages were grouped on the wrong guy !

So we had three issues probably related to the same bug : 
- Some messages sent after another message appear before it.
- Some messages are getting grouped to the wrong sender.
- Two messages are getting grouped to the good sender even if someone has already posted a message between those two messages.

Reproduced on mac os client, with version 0.35 deployed with rancher (ie with docker)

**Comment by c0fe** [comment] 2016-07-13 12:33
Browser: Chrome (up to date)
Server: Debian 8 (all updates installed)
Deployment: Regular Node.JS, no Docker

**Comment by throll** [comment] 2016-07-13 15:21
I have just found that the issue came from our load balancer, with only one instance of rocket everything went back to normal.
Sorry for the inconvenience.

**Comment by geekgonecrazy** [comment] 2016-07-14 05:37
@throll this is very useful information.  @cofe are you running multiple instances as well?

**Comment by c0fe** [comment] 2016-07-25 13:27
No, only one instance. The server is dedicated to Rocket Chat

**Comment by geekgonecrazy** [comment] 2016-08-18 17:04
I've actually seen this several times as well lately.  I've sent messages after someone else, and it grouped my messages as if they came from the previous poster.  

I'm thinking this has something to do with timestamps.

**Comment by throll** [comment] 2016-08-18 17:36
FYI Our issue did not come from our load balancer but our 2 instances were not time synchronized.

**Comment by geekgonecrazy** [comment] 2016-08-18 17:50
@throll that makes perfect sense.  Would probably result in messages being in wrong order and etc also.  Your case is something we need to add in our high availability documentation.

**Comment by gdelavald** [comment] 2017-09-28 15:03
@geekgonecrazy can we close this issue then?

**Comment by geekgonecrazy** [comment] 2017-10-02 04:23
I still see this from time to time

**Comment by ggazzo** [comment] 2018-07-04 19:53
@c0fe I think we fixed this problem could you try again?

**Comment by ggazzo** [comment] 2018-08-14 13:33
I think this issue was closed by https://github.com/RocketChat/Rocket.Chat/pull/10472, if the problem persists please open again

**Closed by ggazzo** 2018-08-14 13:33 UTC
Labels: feat: message, subj: ui/ux, type: bug
