### ISSUE TITLE
Error when creating a new chat with a user in the general channel (createDirectMessage error)

### ISSUE THREAD

**Issue by IvanOpanasiuk** [RocketChat/Rocket.Chat#23041] opened 2021-08-26 08:24 UTC
### Description:

In the channel 'general' I press to create a chat with a user with whom there was no chat yet. And I get an error 'createDirectMessage'. 

### Steps to reproduce:

1. Go to channel general
2. Click on User (click on a user with whom there is no chat for the createDirectMessage method to work)
3. Click on 'Direct Message' button

<img width="545" alt="Снимок экрана 2021-08-26 в 11 09 35" src="https://user-images.githubusercontent.com/15374759/130926121-4c99ef8d-4223-4cce-a898-5c26abb1a785.png">

### Actual behavior:

I get a dark screen and the console shows that there is an error in the createDirectMessage method

<img width="1769" alt="Снимок экрана 2021-08-26 в 11 10 22" src="https://user-images.githubusercontent.com/15374759/130926258-b9306adc-0f3b-4ab6-a1e3-f53134a527cb.png">

After page reload everything works

I can assume that the problem is that in the 'createDirectMessage' method the 'Users.findOneByUsernameIgnoringCase()' is executed and returns 'undefined'

<img width="1045" alt="Снимок экрана 2021-08-26 в 11 20 31" src="https://user-images.githubusercontent.com/15374759/130928256-040f0a5c-2fd0-4e29-bd67-3b411e0f1f95.png">

https://user-images.githubusercontent.com/15374759/130930409-36fdfbcf-b63f-4514-9f89-7fdb2375707c.mov

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.1
- Operating System: mac macOS
- NodeJS Version: 14.16.1
- MongoDB Version: 4.4.0

### Client Setup Information

-  Browser Version:
- Operating System: macOS

### Relevant logs:

<img width="1157" alt="Снимок экрана 2021-08-26 в 11 15 19" src="https://user-images.githubusercontent.com/15374759/130927015-55196a3d-dddb-43bc-a6cf-0714a85a6445.png">

<img width="1790" alt="Снимок экрана 2021-08-26 в 11 16 28" src="https://user-images.githubusercontent.com/15374759/130927126-370c8f97-1d76-46e9-816b-849c81a02c3e.png">

**Comment by debdutdeb** [comment] 2021-08-30 06:32
I just tried to reproduce this on 3.17.2 and I couldn't reproduce this. @ankar84 have you seen this issue on your end?

**Comment by ankar84** [comment] 2021-08-30 08:23
> I just tried to reproduce this on 3.17.2 and I couldn't reproduce this. @ankar84 have you seen this issue on your end?

I'm still on 3.16.3 and waiting for 3.18.0 to release.

**Comment by debdutdeb** [comment] 2021-08-30 08:28
Ah ok. 

I'll wait for Ivan to respond.

**Comment by IvanOpanasiuk** [comment] 2021-08-30 10:34
Hi . thank you for your responses ! this is really weird. I cloned rocket chat (https://github.com/RocketChat/Rocket.Chat). switched to tag 3.17.2 . I tried a few more times on test users. And I still see an error when creating a chat with a person with whom there was no chat yet

**Comment by debdutdeb** [comment] 2021-09-02 07:19
Hmm, I just checked again on 3.18.0 - working just fine.

Can you walk me through how you're deploying rc? The configs (if-any)? 

Just noticed, why's node v14.16.1? We're still at 12.22.1.

**Comment by IvanOpanasiuk** [comment] 2021-09-02 08:03
Thanks for your reply . In these examples I just cloned the repository and launched the project with the command "meteor". I will switch to 12.22.1 and try again. Thank you @debdutdeb and @ankar84 !

**Comment by debdutdeb** [comment] 2021-09-08 10:37
Hi @IvanOpanasiuk , following up, have you tried this?Did it work for you?

**Comment by krenuser** [comment] 2022-03-10 15:01
Still experiencing this problem in 4.5.0
As I've investigated a reason, its source is still here:
![image](https://user-images.githubusercontent.com/32645945/157689138-c630bee4-bd53-4d96-b793-5f2381b28de4.png)

Fixed it temporarily by replacing selected line with 
```let to = Users.findOneById(username);```
but seems that it's a partial solution.

**Comment by debdutdeb** [comment] 2022-03-10 15:23
@krenuser yep we know. I even opened a PR but it just wasn't the right solution. `findOneById` will just work or this case, any other way you try to create a dm will fail.

**Comment by ankar84** [comment] 2022-03-11 08:58
That issue probably fixed by https://github.com/RocketChat/Rocket.Chat/pull/24623
Try develop branch to see if it fixed or not.

**Comment by dougfabris** [comment] 2023-07-20 14:44
> That issue probably fixed by #24623 Try develop branch to see if it fixed or not.

Closing because it's already fixed thanks @ankar84

**Closed as completed by dougfabris** 2023-07-20 14:44 UTC
