### ISSUE TITLE
Adding Webdav Share not working

### ISSUE THREAD

**Issue by kokotko1337** [RocketChat/Rocket.Chat#19245] opened 2020-10-14 12:54 UTC
### Description:
Can not add Webdav Account.

I got Nextcloud with WEBDAV enabled. I can access it with WEBDAV Plugin from Total Commander.

I tried to add Webdav wia Browser and Windows app but without success. Webdav share working - tried it with total commander.
URL has HTTPS.

### Steps to reproduce:

1. Go to Channel 
2. Click on +
3. Add new Wenbdav Account
4. Url + Username + Password
5. nothing happens- it says Please Wait

### Expected behavior:
1. Go to Channel 
2. Click on +
3. Add new Wenbdav Account
4. Url + Username + Password
5. Add my webdav share

### Actual behavior:

can not add Webdav share in Rocket Chat, In total commander working all great

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0
- Operating System: Debian 9
- Deployment Method: manual installed
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.18.3
- MongoDB Version: 3.6.20

### Client Setup Information

Rocket Chat Version
Server Version | 3.7.0 Apps Engine: 1.18.0
Client 3.0.3

NC Version - 19.0.3
HTTPS: ON
https://URL/remote.php/webdav/
Login + PW - tested with Total commander and working

### Additional context

Webdav is working on mz Nextcloud instance, but can not be added to Rocket Chat.

### Relevant logs:

none

**Comment by frdmn** [comment] 2020-10-15 18:28
Double check your log files (client and server side). If you don't see anything in the server log, you might need to increase the log level in the admin UI → Logs.

**Comment by kokotko1337** [comment] 2020-10-23 13:53
I20201023-15:52:42.369(2) API ➔ debug Success {   statusCode: 200,   body: {     message: '{"msg":"result","id":"1251","error":{"isClientSafe":true,"error":"could-not-access-webdav","reason":{"method":"addWebdavAccount"},"message":"[object Object] [could-not-access-webdav]","errorType":"Meteor.Error"}}',     success: true   } } 


this is in RC log when Im trying to add it ...

**Comment by frdmn** [comment] 2020-11-09 09:22
... `could-not-access-webdav`: looks like it can not access your webdav backend for some reason. 

Can you also enable the `Show package` option in the Logs section of the admin UI? _Maybe_ it'll expand the `[object Object]`, with a bit more descriptive root cause.

**Comment by poltrian** [comment] 2021-04-29 08:24
Same here, i can see my Nextcloud share, can add some file and get an undefined. Before there pop up many "To many requests"

**Comment by idominiki** [comment] 2021-06-11 09:52
Hi together,

I also can't access my webdav (Nextcloud) share.
I got the following debug output:

Exception while invoking method addWebdavAccount Error: [object Object] [could-not-access-webdav]
    at app/webdav/server/methods/addWebdavAccount.js:58:10
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
    at Server.call (packages/ddp-server/livedata_server.js:1607:17)
    at Object.post (app/api/server/v1/misc.js:262:26)
    at app/api/server/api.js:394:82
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:98:9

Would be great If anyone can help!

Greets
Dominik

**Comment by battosai30** [comment] 2021-06-24 09:21
Hi guys,

I just add the same issue and solved it (but maybe it's not the same reason as you) : I'm using Proxmox and NC and R.Chat are two separate virtual machines. I also have a firewall (Pfsense) and it dosen't like when requests go out and go back (it blocks them). So I add a DNS service to Pfsense so requests for "internal" machines stay in local area. But I forgot on my R.Chat machine to change default DNS address. So when I change it to firewall IP, things go well :)

So I suggest this simple test : wget (or curl) your webdav URL, it should answer something. If not, you may have a DNS issue (or any other possible IP issue) like me.

**Comment by dougfabris** [comment] 2022-08-18 21:46
Closing this issue, because it was fixed on this PR: #23924
Thanks for reporting it @kokotko1337 if you still having trouble after updating it, please let me know!

**Closed by dougfabris** 2022-08-18 21:46 UTC

**Comment by Jormodn** [comment] 2022-11-24 10:06
In Version 4.5.4 same Problem:

{"level":50,"time":"2022-11-24T09:37:38.118Z","pid":8,"hostname":"467d6e23efc4","name":"System","msg":"Exception while invoking method addWebdavAccount 'Could not access webdav [could-not-access-webdav]'"}
Exception while invoking method addWebdavAccount errorClass [Error]: Could not access webdav [could-not-access-webdav]
    at app/webdav/server/methods/addWebdavAccount.ts:65:10
    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at Server.apply (packages/ddp-server/livedata_server.js:1752:22)
    at Server.call (packages/ddp-server/livedata_server.js:1721:17)
    at Object.post (app/api/server/v1/misc.js:456:26)
    at app/api/server/api.js:425:96
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)
    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)
    at packages/rocketchat_restivus/lib/route.coffee:59:33
    at packages/simple_json-routes.js:100:9 {
  isClientSafe: true,
  error: 'could-not-access-webdav',
  reason: 'Could not access webdav',
  details: { method: 'addWebdavAccount' },
  errorType: 'Meteor.Error'
}

is it possible to check?

**Comment by dougfabris** [comment] 2022-11-24 13:50
@Jormodn could you make sure your WebDAV server credentials are correct? 
I just tried it here and it's working fine in `4.5.4`!

<img widht='420px' src='https://user-images.githubusercontent.com/27704687/203800084-9cc9a50b-7d9f-482b-be4b-06434fff2d79.gif' />
