### ISSUE TITLE
Embed processes markdown code blocks when it shouldn't

### ISSUE THREAD

**Issue by xenithorb** [RocketChat/Rocket.Chat#3467] opened 2016-06-05 22:13 UTC
Your Rocket.Chat version: (make sure you are running the latest)
0.32.0

It's my opinion that:
1. Rocket.Chat should not process markdown code block URLs with the AutoLinker
2. If #1 is a must, then perhaps have a preempt character so the user can turn off autolinker in-line?

Essentially it's an annoyance that after pasting a code block with URLs in it, the autolinker clutters the chat with more (probably unnecessary information) - otherwise I love the functionality when sharing regular links.

![screenshot_20160605_181419](https://cloud.githubusercontent.com/assets/10273878/15808606/626e63b0-2b49-11e6-9168-f05978bb7706.png)

**Comment by xenithorb** [comment] 2016-06-11 07:53
I think this is more of a bug not a feature, no?

**Comment by qk4l** [comment] 2016-08-19 22:20
> Rocket.Chat should not process markdown code block URLs with the AutoLinker

Agree. Another user case it is bot messages. I just wanted to improve visualizing for `hubot-jira` script by adding icons like on image below but it's not possible because autolinker always works.
![hipchat_jira_message](https://cloud.githubusercontent.com/assets/8394059/17825796/f3f768b4-667b-11e6-8e45-f1fec7e5eb6f.png)

**Comment by martinvonwittich** [comment] 2017-07-14 09:03
It would be nice if something could be done about this. The current behaviour is really annoying when you post `apt-get update` output in RC, which we do a lot in our company.

**Comment by Da-Juan** [comment] 2019-06-24 09:50
Ran into this issue today.
Are there any update?

**Comment by rodrigok** [comment] 2019-07-25 20:47
I can't reproduce this anymore.

@Da-Juan can you let me know what rocket.chat version are you using and what text you sent to reproduce the issue?

Mean while I'll close this issue.

**Closed by rodrigok** 2019-07-25 20:47 UTC
Labels: feat: message, type: improvement
