### ISSUE TITLE
Global Search

### ISSUE THREAD

**Issue by Shuario** [RocketChat/Rocket.Chat#22946] opened 2021-08-17 07:49 UTC
Hey,

We are experiencing issue with Rocket feature "Global Search". When you try to search in chat without checking box "Global search" it searchs globally anyway. You have to check and uncheck the box for it to work completely.

And second thing is when you search for string which been used multiple times it overloads server (high ram usage).

**Comment by ankar84** [comment] 2021-08-17 10:41
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/21659

**Comment by debdutdeb** [comment] 2021-08-18 08:09
As Anton has pointed out this issue has already been submitted in the past and also known internally. A fix is being worked on. 

I'll close this one, and if there's any additional information that needs to be shared, Shuario, please do so in the other issue. It's good to have everything in the same issue rather than have multiple ones referencing the same one. 

About the high RAM usage - I have not noticed it (probably because my single instance deployment is not exactly a challenge for the high-end server) personally. Can you please update the other issue with more details on this? Maybe some screenshots? 

Thanks you :)

**Closed by debdutdeb** 2021-08-18 08:09 UTC
