### ISSUE TITLE
Allow bot status force to online

### ISSUE THREAD

**Issue by haifengl** [RocketChat/Rocket.Chat#3292] opened 2016-05-18 19:52 UTC
Your Rocket.Chat version: latest

I have bot that logins with REST API. But in the app, my bot's @ icon doesn't show green. Is there anyway to change a user's status? Thanks!

**Comment by christianreiss** [comment] 2016-05-19 06:46
Not 100% sure, but:

Working as designed. Your bot is not online (ie, logged in). The webhooks does not count. A hubot for example that logins and stays online also stays green.

Webhooks are offline and only "triggered" uppon action.

-Chris.

**Comment by haifengl** [comment] 2016-05-19 14:37
So how hubot loving? Is there another set of API, like web socket? Thanks!

**Comment by niemeyer** [comment] 2016-09-05 03:29
> Webhooks are offline and only "triggered" uppon action.

That's not quite right either technically or socially.

Technically, webhooks happen to be the main way offered for custom bots to be implemented, and this is the nature of webhooks. If the outgoing webhook is working at all, it's supposed to _be online_ and take the message right then. Otherwise it's broken, much like hubot could be online and broken not answering someone's message.

Socially, these bots, implemented via webhooks, will be talking to people all the time, reading and writing into public channels. It's awkward to have that user, which is always there and communicating, being marked as offline.

I've just wished for the exact same feature: I'd like to mark a specific bot user as being online all the time.

**Comment by geekgonecrazy** [comment] 2016-09-08 15:56
I think this could be as simple as a toggle in the bot settings to appear online.  We let people force appearing offline... why not let the bot force online?

**Comment by SeanPackham** [comment] 2018-03-12 16:06
Since bots are currently tied to user accounts they rely on user presence. Closing as we won't support the ability for bots to permanently appear online in the near future, we will revisit once other priorities have been addressed.

**Closed by SeanPackham** 2018-03-12 16:06 UTC
Labels: feat: app settings, feat: webhooks, type: discussion

**Comment by dudanogueira** [comment] 2019-11-16 19:35
This would be very useful. Right now I am on the situation that my Rasa Bot only returns to a livechat if it is online. I need to log in as the bot user in order to it work. I know I could implement some workaround for it to stick to online. While live chat only works like that, while online, the same bot will work OK when triggered from channels or direct message, while showing offline. The toggle button would be a very good implementation. +1 for that.

**Comment by renatobecker** [comment] 2019-11-18 12:50
> This would be very useful. Right now I am on the situation that my Rasa Bot only returns to a livechat if it is online. I need to log in as the bot user in order to it work. I know I could implement some workaround for it to stick to online. While live chat only works like that, while online, the same bot will work OK when triggered from channels or direct message, while showing offline. The toggle button would be a very good implementation. +1 for that.

We provide a REST API endpoint to change the status of the users, have you tried it?
