### ISSUE TITLE
Automatic logouts in 0.58.3/Facebook

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#8366] opened 2017-09-30 17:37 UTC
### Description:

Since a few days (updating from 0.58.2 to 0.58.3?) I get signed out regulary on desktop (didn't looked at the clock, but something around 2 or 3 hours inactivity).

But beside updating to 0.58.3 I turned on Facebook login in the backend + created a second account with my Facebook Token (incognito/private tab, but Facebook session is also present in regular browser mode). The account just exists for testing purposes, for regular use the normal username + password account is used (and the logout happens here).
I'll check:
- [ ] Timing of the logouts (log just shows SyncedCron every hour)
- [ ] Deactivating Facebook Login
- [ ] Deleting Account linked to Facebook

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: CentOS 7
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: -
* Node Version: 4.5.0

**Comment by divergefx** [comment] 2017-10-02 02:25
My users are also reporting automatic logouts with 0.58.3, I had to rollback to 0.58.2.  (heroku deployment)

**Comment by MartinSchoeler** [comment] 2017-10-02 13:32
@soundstorm  The logouts were caused by a bug in meteor, already fixed on https://github.com/meteor/meteor/pull/9148. So this will be fixed on our next version. I am not sure if the facebook bug is related to the logouts though.

**Comment by TheReal1604** [comment] 2017-10-06 12:31
@MartinSchoeler can you say if this is fixed with 0.58.4?

**Comment by soundstorm** [comment] 2017-10-06 16:38
@MartinSchoeler as I just activated OAuth I couldn't exclude that :) So I was just guessing. But great that this is unrelated.

**Comment by alexweissman** [comment] 2017-10-06 22:47
The general problem with unexpected logouts seems to be resolved in 0.58.4.  Not sure about FB specifically.

**Closed** 2018-01-05 00:10 UTC
Labels: type: bug
