### ISSUE TITLE
Avatars missing after migration

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#7410] opened 2017-07-05 07:25 UTC
Rocket.Chat Version: 0.57.0
Running Instances: 1
DB Replicaset OpLog: yes

I have done the upgrade to 0.57.0 and at the migrations i found this errors in the logs:

```
2017-07-05T07:08:32.604305899Z [AVATAR] Migrating avatars. This might take a while.
2017-07-05T07:08:33.124281826Z {"line":"147","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 98","time":{"$date":1499238513123},"level":"info"}
2017-07-05T07:08:33.203992733Z {"line":"147","file":"rocketchat_migrations.js","message":"Migrations: Finished migrating.","time":{"$date":1499238513203},"level":"info"}
2017-07-05T07:08:34.018007118Z [AVATAR] Total users to migrate avatars -> 12
2017-07-05T07:08:34.023083965Z [AVATAR] Migrating 1 of 12
2017-07-05T07:08:34.034032130Z [AVATAR] Migrating 2 of 12
2017-07-05T07:08:34.039904573Z [AVATAR] Migrating 3 of 12
2017-07-05T07:08:34.056885854Z [AVATAR] Migrating 4 of 12
2017-07-05T07:08:34.074308719Z [AVATAR] Migrating 5 of 12
2017-07-05T07:08:34.096311414Z [AVATAR] Migrating 6 of 12
2017-07-05T07:08:34.118518754Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/2eGSMExxMPCuCx7nZ'
2017-07-05T07:08:34.118591439Z   at Error (native)
2017-07-05T07:08:34.118700900Z 
2017-07-05T07:08:34.120192320Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/hR9x9EykmhtvQu4JW'
2017-07-05T07:08:34.120255287Z   at Error (native)
2017-07-05T07:08:34.120336102Z 
2017-07-05T07:08:34.121247815Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/tfXKjEr3zrM8kx48H'
2017-07-05T07:08:34.121287025Z   at Error (native)
2017-07-05T07:08:34.121296123Z 
2017-07-05T07:08:34.149405321Z [AVATAR] Migrating 7 of 12
2017-07-05T07:08:34.175665372Z [AVATAR] Migrating 8 of 12
2017-07-05T07:08:34.183515631Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/RYsopwZj6jZLF9RvK'
2017-07-05T07:08:34.183558639Z   at Error (native)
2017-07-05T07:08:34.183568615Z 
2017-07-05T07:08:34.184678857Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/qhcbPdWyBqkCZMbsk'
2017-07-05T07:08:34.184733432Z   at Error (native)
2017-07-05T07:08:34.184794935Z 
2017-07-05T07:08:34.185967898Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/2GvK4nKfDuC8BLsmB'
2017-07-05T07:08:34.186021766Z   at Error (native)
2017-07-05T07:08:34.186078869Z 
2017-07-05T07:08:34.190606282Z [AVATAR] Migrating 9 of 12
2017-07-05T07:08:34.225185175Z [AVATAR] Migrating 10 of 12
2017-07-05T07:08:34.250033925Z [AVATAR] Migrating 11 of 12
2017-07-05T07:08:34.256561553Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/BvZRtaoDodxTB7NiW'
2017-07-05T07:08:34.256600698Z   at Error (native)
2017-07-05T07:08:34.256610031Z 
2017-07-05T07:08:34.257749064Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/XJzQGW5rPgJEw2CHo'
2017-07-05T07:08:34.257816863Z   at Error (native)
2017-07-05T07:08:34.257929172Z 
2017-07-05T07:08:34.266567861Z [AVATAR] Migrating 12 of 12
2017-07-05T07:08:34.339174099Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/PbQr5KLuNmgY3vrGu'
2017-07-05T07:08:34.340889440Z   at Error (native)
2017-07-05T07:08:34.341013900Z 
2017-07-05T07:08:34.341040419Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/XEK6FKpheE68hR5oY'
2017-07-05T07:08:34.341104682Z   at Error (native)
2017-07-05T07:08:34.341124384Z 
2017-07-05T07:08:34.369010550Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/BvZRtaoDodxTB7NiW': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.369091181Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.369184573Z convert: no images defined `jpeg:/tmp/ufs/BvZRtaoDodxTB7NiW' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.369204103Z ] code: 1, signal: null }
2017-07-05T07:08:34.370865946Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/BvZRtaoDodxTB7NiW'
2017-07-05T07:08:34.370937265Z   at Error (native)
2017-07-05T07:08:34.371109041Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.371153374Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.371307549Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.371376489Z 
2017-07-05T07:08:34.372189259Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/XJzQGW5rPgJEw2CHo': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.372237674Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.372321125Z convert: no images defined `jpeg:/tmp/ufs/XJzQGW5rPgJEw2CHo' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.372338903Z ] code: 1, signal: null }
2017-07-05T07:08:34.372580388Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/XJzQGW5rPgJEw2CHo'
2017-07-05T07:08:34.372604350Z   at Error (native)
2017-07-05T07:08:34.372614099Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.372620678Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.372626930Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.372632990Z 
2017-07-05T07:08:34.373618237Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/2GvK4nKfDuC8BLsmB': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.373678449Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.373768165Z convert: no images defined `jpeg:/tmp/ufs/2GvK4nKfDuC8BLsmB' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.373793631Z ] code: 1, signal: null }
2017-07-05T07:08:34.374477689Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/2GvK4nKfDuC8BLsmB'
2017-07-05T07:08:34.374510400Z   at Error (native)
2017-07-05T07:08:34.374519015Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.374525231Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.374541745Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.374548685Z 
2017-07-05T07:08:34.376342283Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/2eGSMExxMPCuCx7nZ': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.376384728Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.376394246Z convert: no images defined `jpeg:/tmp/ufs/2eGSMExxMPCuCx7nZ' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.376401649Z ] code: 1, signal: null }
2017-07-05T07:08:34.376851588Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/2eGSMExxMPCuCx7nZ'
2017-07-05T07:08:34.376879207Z   at Error (native)
2017-07-05T07:08:34.376887414Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.376893622Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.376900064Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.376906285Z 
2017-07-05T07:08:34.378172503Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/qhcbPdWyBqkCZMbsk': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.378216051Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.378229962Z convert: no images defined `jpeg:/tmp/ufs/qhcbPdWyBqkCZMbsk' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.378238024Z ] code: 1, signal: null }
2017-07-05T07:08:34.378538588Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/qhcbPdWyBqkCZMbsk'
2017-07-05T07:08:34.378561056Z   at Error (native)
2017-07-05T07:08:34.378569249Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.378575863Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.378585152Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.378591292Z 
2017-07-05T07:08:34.379473763Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/hR9x9EykmhtvQu4JW': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.379508551Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.379517591Z convert: no images defined `jpeg:/tmp/ufs/hR9x9EykmhtvQu4JW' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.379523907Z ] code: 1, signal: null }
2017-07-05T07:08:34.379880546Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/hR9x9EykmhtvQu4JW'
2017-07-05T07:08:34.379911349Z   at Error (native)
2017-07-05T07:08:34.379919567Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.379925774Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.379948575Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.379956578Z 
2017-07-05T07:08:34.381265446Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/RYsopwZj6jZLF9RvK': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.381294510Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.381300390Z convert: no images defined `jpeg:/tmp/ufs/RYsopwZj6jZLF9RvK' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.381305927Z ] code: 1, signal: null }
2017-07-05T07:08:34.381631676Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/RYsopwZj6jZLF9RvK'
2017-07-05T07:08:34.381651546Z   at Error (native)
2017-07-05T07:08:34.381658213Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.381662371Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.381666291Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.381670166Z 
2017-07-05T07:08:34.382429854Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/tfXKjEr3zrM8kx48H': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.382453996Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.382459262Z convert: no images defined `jpeg:/tmp/ufs/tfXKjEr3zrM8kx48H' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.382463469Z ] code: 1, signal: null }
2017-07-05T07:08:34.382749311Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/tfXKjEr3zrM8kx48H'
2017-07-05T07:08:34.382766657Z   at Error (native)
2017-07-05T07:08:34.382780297Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.382788193Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.382793106Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.382797058Z 
2017-07-05T07:08:34.387148514Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/F6SpEwwwc2wvdeFj9'
2017-07-05T07:08:34.387190613Z   at Error (native)
2017-07-05T07:08:34.387199961Z 
2017-07-05T07:08:34.388329757Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/PbQr5KLuNmgY3vrGu': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.388382881Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.388394329Z convert: no images defined `jpeg:/tmp/ufs/PbQr5KLuNmgY3vrGu' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.388402593Z ] code: 1, signal: null }
2017-07-05T07:08:34.388753093Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/PbQr5KLuNmgY3vrGu'
2017-07-05T07:08:34.388806818Z   at Error (native)
2017-07-05T07:08:34.388816932Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.388823997Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.388831334Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.388838008Z 
2017-07-05T07:08:34.389504957Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/XEK6FKpheE68hR5oY': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.389540044Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.389550247Z convert: no images defined `jpeg:/tmp/ufs/XEK6FKpheE68hR5oY' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.389557000Z ] code: 1, signal: null }
2017-07-05T07:08:34.390147731Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/XEK6FKpheE68hR5oY'
2017-07-05T07:08:34.390176948Z   at Error (native)
2017-07-05T07:08:34.390185257Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.390191016Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.390196837Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.390202631Z 
2017-07-05T07:08:34.407124626Z Exception in callback of async function: Error: ENOENT: no such file or directory, open '/tmp/ufs/Nw5rGSJ2m4Sgxyz3k'
2017-07-05T07:08:34.407158232Z   at Error (native)
2017-07-05T07:08:34.407164089Z 
2017-07-05T07:08:34.427879997Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/F6SpEwwwc2wvdeFj9': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.427933056Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.427943801Z convert: no images defined `jpeg:/tmp/ufs/F6SpEwwwc2wvdeFj9' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.427957914Z ] code: 1, signal: null }
2017-07-05T07:08:34.428761988Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/F6SpEwwwc2wvdeFj9'
2017-07-05T07:08:34.428797737Z   at Error (native)
2017-07-05T07:08:34.428807001Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.428813861Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.428820116Z   at runWithEnvironment (packages/meteor.js:1176:24)
2017-07-05T07:08:34.428826304Z 
2017-07-05T07:08:34.431465935Z { [Error: Command failed: convert: unable to open image `/tmp/ufs/Nw5rGSJ2m4Sgxyz3k': No such file or directory @ error/blob.c/OpenBlob/2712.
2017-07-05T07:08:34.431508826Z convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-05T07:08:34.431518472Z convert: no images defined `jpeg:/tmp/ufs/Nw5rGSJ2m4Sgxyz3k' @ error/convert.c/ConvertImageCommand/3210.
2017-07-05T07:08:34.431539364Z ] code: 1, signal: null }
2017-07-05T07:08:34.431791912Z Exception in callback of async function: Error: ENOENT: no such file or directory, lstat '/tmp/ufs/Nw5rGSJ2m4Sgxyz3k'
2017-07-05T07:08:34.431810799Z   at Error (native)
2017-07-05T07:08:34.431817730Z   at Object.fs.lstatSync (fs.js:839:18)
2017-07-05T07:08:34.431823622Z   at /app/bundle/programs/server/packages/rocketchat_file-upload.js:355:18
2017-07-05T07:08:34.431829683Z   at runWithEnvironment (packages/meteor.js:1176:24)
```
Now all avatars are missing.

Any idea how to resolve this?

**Comment by willihelm** [comment] 2017-07-05 12:47
I noticed that too. I started a Synchronization with the LDAP Active Directory and the avatars were correctly synced.

**Comment by TheReal1604** [comment] 2017-07-05 12:55
@willihelm but i had no LDAP connection, just the internal users database.

**Comment by KervyN** [comment] 2017-07-05 13:05
We have the same issue, but if we enable avatar sync via ldap the login is broken.

**Comment by MartinSchoeler** [comment] 2017-07-05 13:29
duplicate of #7385

**Closed by MartinSchoeler** 2017-07-05 13:29 UTC
