### ISSUE TITLE
LDAP-Import: Rocket.Chat creates Channel #General even when the Channel was deleted

### ISSUE THREAD

**Issue by Dalben96** [RocketChat/Rocket.Chat#10182] opened 2018-03-21 07:52 UTC
### Description:
If you delete the Channel #General and start your LDAP Userimport Rocket.Chat will create the Channel #General again and every new User becommes a member of these Channel.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: OpenSuse
* Deployment Method(snap/docker/tar/etc):  tar
* Number of Running Instances:  1
* Node Version: v8.9.4

### Steps to Reproduce:

1. Delete Channell #General
2. Configure LDAP-Userimport
3. Start syncronisation

### Expected behavior:

Synchronize user data and don't create new channels.

### Actual behavior:

Synchronize user data and create new channel #Gernerall.

**Comment by theorenck** [comment] 2018-04-11 17:03
Tanks for the feedback @Dalben96. @rodrigok can you confirm this as an erratic behavior? If you do so can you prioritize it accordingly?

**Comment by graywolf336** [comment] 2018-04-11 17:33
Sounds like when the channel is deleted it's not removed from the default servers? :thinking:

**Comment by Hudell** [comment] 2018-06-14 14:53
Duplicate of #3870.
While the description is not exactly the same, the solution proposed there will fix the problem. I'll add a note there to make sure we test this.

**Closed by Hudell** 2018-06-14 14:53 UTC
Labels: subj:  Auth - LDAP, type: bug
