### ISSUE TITLE
Bold channel title when changing name

### ISSUE THREAD

**Issue by jcardila** [RocketChat/Rocket.Chat#2098] opened 2016-02-01 21:51 UTC
Seems to be a bug that after changing a channel's name the sidebar title is left in bold as if there were unread messages. I can't find a way to unbold the channel title, tried: changing channels, reloading, logging out, and nothing works. The only way for it to unbold is for some other user to send a message in that channel.
This happens in both channels and private groups.
![screen shot 2016-02-01 at 4 38 49 pm](https://cloud.githubusercontent.com/assets/16345309/12732537/fc7a0980-c903-11e5-8b01-af33970320ec.png)

**Comment by rajatkumarpati** [comment] 2016-02-10 05:15
Same here also

**Comment by amayer5125** [comment] 2016-03-17 15:00
Version: 0.22.0

Pressing the ESC key does clear the bold name. Nothing else seems to clear it.
This also happens when changing the topic of the room.

Expected behavior: room is marked as read if you are still in the room or if you enter the room.

**Comment by MartinSchoeler** [comment] 2017-03-24 14:56
Hey @jcardila , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Closed by MartinSchoeler** 2017-03-24 14:56 UTC
Labels: feat: channel settings, subj: ui/ux, type: bug
