### ISSUE TITLE
Chats and DMs not displaying on iOS

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#7619] opened 2017-07-31 20:19 UTC
DESCRIPTION: 
I run a digital community for self-directed teens that don't go to school called the [Peer Unschooling Network](https://peerunschooling.net). We  just upgraded from RocketChat 0.53 to 0.57.  

On my own iPhone, I have issues where the sidebar doesn't display.  I assume this is only on my phone because I'm running a very old iOS and it's jailbroken and a mess.  This was mostly addressed in [issue 7547](https://github.com/RocketChat/Rocket.Chat/issues/7547). 

ISSUE:
I have a user who has issues on both his iPhone and iPad.  The chats are not displaying for both the channels and direct messages.  This screenshot should help illustrate this:

![unnamed](https://user-images.githubusercontent.com/12577122/28796314-ef049300-75f1-11e7-80c5-77daa78a3076.jpg)

### Server Setup Information:

* Version of Rocket.Chat Server:  0.57-develop
* Operating System: iOS
* Deployment Method(snap/docker/tar/etc):  Heroku Dyno
* Number of Running Instances:   1
* DB Replicaset Oplog:  mongodb://githubop:****@candidate.53.mongolayer.com:10061,candidate.52.mongolayer.com:10482/punchat2?replicaSet=set-560ab4eb75eea0f4a00007e6
* Node Version: not sure

**Comment by marco-aa** [comment] 2017-07-31 20:37
@flantascience i'm not sure but i guess you posted a password in DB Replicaset. If so you should edit your posting / change password.

**Comment by graywolf336** [comment] 2017-07-31 23:23
Duplicate of #7574

**Closed by graywolf336** 2017-07-31 23:23 UTC

**Comment by flantascience** [comment] 2017-07-31 23:49
Thanks @marco-aa    I thought I was supposed to because its a read-only replicaset.  Probably still unwise of me!
