### ISSUE TITLE
Users list sorting is case sensitive

### ISSUE THREAD

**Issue by ChristineBoersen** [RocketChat/Rocket.Chat#14735] opened 2019-06-04 13:27 UTC
### Description:

When using the Web client, users are sorted in a case sensitive manner (users with capital first letters appear [A-Z] appear before users with lover case first letters [a-z]

### Steps to reproduce:

1 - Loging
2 - Show the Directory
3 - Select Users
4 - View Users List

### Expected behavior:

Users to be sorted alphabetically  ([A-Za-z]) in a case insensitive manner

- Version of Rocket.Chat Server:  1.1.1
- Operating System: Linux Ubuntu Server 14.0.2
- Deployment Method: Manual Install (https://rocket.chat/docs/installation/manual-installation/ubuntu/)
- Number of Running Instances:  1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.10

**Comment by serviceman** [comment] 2019-06-05 23:29
i can confirm that this is an issue on 1.1.0 as well. I had to force user creation via the api to always start with a capital letter. Also, unless capitalization is exactly as the recorded name, private messages don't work if started by an external javascript file. In other words FlowRouter.go is also case sensitive.

**Comment by reetp** [comment] 2019-06-06 08:35
> 
>     * Operating System: Linux Ubuntu Server 14.0.2

Although it won't fix your issue, unless you have ESM it might be time to upgrade your OS.

Ubuntu 14.x was generally EOL in April 2019 :-)

**Comment by aditya-mitra** [comment] 2021-02-11 18:45
@sampaiodiego Can I work on this?

**Comment by sampaiodiego** [comment] 2021-02-11 18:48
for sure! :D what would be your solution for this @aditya-kumawat ?

**Comment by aditya-mitra** [comment] 2021-02-11 19:00
I will propose a nice solution tomorrow with a demo url on gitpod. 😄
Btw, you mentioned the wrong person!

**Comment by sampaiodiego** [comment] 2021-02-11 19:12
> I will propose a nice solution tomorrow with a demo url on gitpod. 
> Btw, you mentioned the wrong person in the above comment!

oopsie.. :see_no_evil: I was wondering if you'd like to discuss before implementing.. but ok then, go ahead, I'll wait for your nice solution

**Comment by aditya-mitra** [comment] 2021-02-12 12:33
@sampaiodiego I have thought of a *custom* sort of users rather than the sort done by mongoDB.

![the problem](https://user-images.githubusercontent.com/55396651/107768252-2f205900-6d5c-11eb-99f1-8adcac2e08d8.png)

The problem in mongoDB sort is that it is comparing the ASCII values of the characters (which is fine if looked from the normal case). Here, we need to compare the strings ignoring their case.

If we could use a function like this to sort our users,

```js
function sortAB(a, b, fields, orders, idx) {
    const field = fields[idx];
    const order = orders[idx];

    if (a[field]?.toLowerCase() < b[field]?.toLowerCase()) {
        return -order;
    } else if (a[field]?.toLowerCase() > b[field]?.toLowerCase()) {
        return order;
    } else if (idx <= fields.length) { // compare with the next field (if it exists)
        sortAB(a, b, fields, orders, idx + 1);
    } else {
        return 0;
    }

}

// we take in the list of users after the fetch and the sortQuery from the client
function sortUsers(users, sortQuery) {
    const fields = Object.keys(sortQuery);
    const orders = Object.values(sortQuery);

    users.sort((a, b) => sortAB(a, b, fields, orders, 0));
}
```

then we would be able to solve this scenario.

![using that function](https://user-images.githubusercontent.com/55396651/107768204-1b74f280-6d5c-11eb-8b59-1100d6f29480.png)


I have reproduced the above in [this gitpod url ](https://3000-coffee-bass-ad8wggjs.ws-us03.gitpod.io/admin/users) so that it will be easier for you to view and test.
(There is one corner case (i.e. when the field is an array) which I will surely handle)

---

gitpod username - superuser
gitpod password - admin@123

---

Thank you. :D

**Comment by aditya-mitra** [comment] 2021-02-12 16:47
There is another method that struck to my mind 🤩 (and this will be faster because it will be done by mongo itself).

If we could aggregate the results by first projecting an additional *nameInsensitive* field and then sort them in the next pipeline **based on *nameInsensitive* field**, then the original *name* (the whole result) would also be sorted.

Something like this:
```js
Users.aggregate([{
    "$project": {
        ...fields,
        "nameInsensitive": {
            "$toLower": "$name"
        }
    }
}, {
    "$sort": {
        ...sort // however, we need to remove the 'name' field from the sort query
        "nameInsensitive": order // (the provided order =-1,0,1)
    }
}]).toArray();
```

But the `aggregate` function isn't working when I tried it on the `Users` model. Is this solution better and will it work?

**Comment by KevLehman** [comment] 2021-02-15 15:51
Hey! Probably that query didn't work because you cannot specify returning fields and adding new ones in the same projection. Or because the `aggregate` function is not exposed in the model, you have to use `rawCollection`. What you can do is:
1. Create a projection with the fields you want to return
2. Add an `$addFields` pipeline to add the `nameInsensitive` field.

Remember to add a `$match` clause at first, so the search bar continues working. I tried and this query worked for me: 

```js
this.model.rawCollection().aggregate([
			{ $match: query },
			{ $project: fields },
			{
				$addFields: {
					sortable: {
						$toLower: "$name"
					}
				}
			},
			{ $sort: sort },
			{
				$facet: {
					paginatedResults: [{ $skip: pagination.skip }, { $limit: pagination.limit }],
					totalCount: [
						{
							$count: 'count'
						}
					]
				}
			}
		]).toArray()
```

**Comment by KevLehman** [comment] 2021-02-15 16:00
I've also tried the `collation` feature, but even with case insensitive indexes and other stuff, but for some reason it didn't work for me. I'll leave the link below if you want to try it in your own machine. If that works, that'd a very much better (and cleaner) solution than the aggregation pipeline.

https://docs.mongodb.com/manual/reference/collation/index.html

**Comment by KevLehman** [comment] 2021-02-15 16:23
@aditya-mitra , here's what I've made, you can take a look. I haven't tested it fully but can serve as inspiration for your changes 😄

**Comment by aditya-mitra** [comment] 2021-02-17 10:20
@KevLehman Thanks a lot !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! :grinning: 

I used both our solutions and did the sorting worked using the **aggregate pipeline**. 

Here is how my pipeline goes:
1. Match the users with the given `query`
2. Do a projection **with only the inclusive fields (having value 1)** and also add the `nameInsensitive` field which is lower-case of `user.name`
3. Skip the `offset` no. of documents
4. Limit the no. of documents by the `limit` provided
5. Do the sorting based on `nameInsensitive` field **`if`** sort query contains `sort.name` **`else`** based on the provided sort query

I have also opened pull request # which should resolve this issue. Please have a look once you are free!

Thanks once again !!!!!!!!!!!!!!!!!!!!!!! 🤩

**Closed** 2021-03-22 23:33 UTC
Labels: Triaged, type: improvement
