### ISSUE TITLE
Auto translate breaks room preview

### ISSUE THREAD

**Issue by billtt** [RocketChat/Rocket.Chat#6462] opened 2017-03-24 09:58 UTC
Rocket.Chat Version: 0.54.1
Running Instances: 1
DB Replicaset OpLog: true
Node Version: 0.45.0

1. Enable Auto Translate and input API Key
2. Grant auto-translate permission to all users
3. Click a channel that haven't opened before (from all channels list)
4. The room shows blank instead of preview messages, and reports the following error messages in console: `TypeError: Cannot read property 'autoTranslateLanguage' of undefined`

**Comment by marceloschmidt** [comment] 2017-03-24 11:59
Thanks @billtt this is duplicate of #6355 and I just found the origin of error. So this should be fixed by the next release.

**Closed by marceloschmidt** 2017-03-24 11:59 UTC
