### ISSUE TITLE
Make join/leave room messages optional

### ISSUE THREAD

**Issue by bwaide** [RocketChat/Rocket.Chat#3450] opened 2016-06-03 08:01 UTC
In popular rooms with lots of users the "xyz joined/left room" messages are more annoying than useful. I'd like to have a personal setting to hide those messages completely. Making them more subtle as suggested in #906 might help as well.

**Comment by soenkef** [comment] 2016-06-03 11:02
+1

**Comment by brentos** [comment] 2016-06-03 16:41
Similar to or same as #2959

**Comment by marceloschmidt** [comment] 2016-06-03 20:46
A duplicate of #2959

**Closed by marceloschmidt** 2016-06-03 20:46 UTC
