### ISSUE TITLE
A lot of 404 errors for GET /api/v1/users.presence

### ISSUE THREAD

**Issue by emikolajczak** [RocketChat/Rocket.Chat#18265] opened 2020-07-15 08:48 UTC
### Description:

In HAproxy logs I see a lot of requests with code 404 for `GET /api/v1/users.presence`. Example log below. Everything works fine, users not complaining, but may be there is something can be improved.

### Steps to reproduce:

1. Check proxy log for requests with code 404 and call `GET /api/v1/users.presence`

### Expected behavior:

No request with 404 code

### Actual behavior:

A lot of requests with code 404 and call `GET /api/v1/users.presence`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.4.0
- Operating System: Centos7
- Deployment Method: docker-compose
- Number of Running Instances: 25
- DB Replicaset Oplog: YES
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.16

### Client Setup Information

- Desktop App or Browser Version: 2.17.7
- Operating System: Windows 10

### Relevant logs:

```Jul 15 08:35:41 localhost haproxy[20707]: xxx  [15/Jul/2020:08:35:41.124] https_front~ chat_back/rocket03_3002 0/0/1/2/3 404 170 - - --VU 1804/1804/1777/61/0 0/0 "GET /api/v1/users.presence?ids=qSAw2KaZcCDTu5PPn,Tjsu8HSpoWxnkHsNN,zP5kschyTmRy4zY2R,aopw5r3pQpMHH9EE6,kADrRX6iC9vPvoHpC,XSaFTATnFDeYfuqBM,NutSDjnh8AdMuqRfW,4qqkz3kBrcFufsxRM,EdSZ5YvPS2xvCjkEQ,MchQJdcn7ihuR4zuj,QCERXNqBpnmD78Xo3,qxL2AnpoL8aYBTHSt,r6aqbahWZA8ofLPq7,BnAEAmRDBoqJE9cMX,XNHt5S62FZWuQ4MEu,KQBHeobhbtC8fKfyY HTTP/1.1"
Jul 15 08:35:42 localhost haproxy[20707]: xxx  [15/Jul/2020:08:35:42.511] https_front~ chat_back/rocket03_3002 0/0/1/3/4 404 170 - - --VN 1809/1809/1775/61/0 0/0 "GET /api/v1/users.presence?ids=qSAw2KaZcCDTu5PPn,Tjsu8HSpoWxnkHsNN,zP5kschyTmRy4zY2R,aopw5r3pQpMHH9EE6,kADrRX6iC9vPvoHpC,XSaFTATnFDeYfuqBM,NutSDjnh8AdMuqRfW,4qqkz3kBrcFufsxRM,EdSZ5YvPS2xvCjkEQ,MchQJdcn7ihuR4zuj,QCERXNqBpnmD78Xo3,qxL2AnpoL8aYBTHSt,r6aqbahWZA8ofLPq7,BnAEAmRDBoqJE9cMX,XNHt5S62FZWuQ4MEu,KQBHeobhbtC8fKfyY HTTP/1.1"
Jul 15 08:36:06 localhost haproxy[20707]: xxx  [15/Jul/2020:08:36:06.958] https_front~ chat_back/rocket03_3002 0/0/1/11/13 404 170 - - --VU 1804/1804/1782/60/0 0/0 "GET /api/v1/users.presence?ids=qSAw2KaZcCDTu5PPn,Tjsu8HSpoWxnkHsNN,zP5kschyTmRy4zY2R,aopw5r3pQpMHH9EE6,kADrRX6iC9vPvoHpC,XSaFTATnFDeYfuqBM,NutSDjnh8AdMuqRfW,4qqkz3kBrcFufsxRM,EdSZ5YvPS2xvCjkEQ,MchQJdcn7ihuR4zuj,QCERXNqBpnmD78Xo3,qxL2AnpoL8aYBTHSt,r6aqbahWZA8ofLPq7,BnAEAmRDBoqJE9cMX,XNHt5S62FZWuQ4MEu,KQBHeobhbtC8fKfyY HTTP/1.1"
Jul 15 08:36:38 localhost haproxy[20707]: xxx  [15/Jul/2020:08:36:38.192] https_front~ chat_back/rocket03_3002 0/0/3/10/13 404 170 - - --VU 1820/1820/1789/61/0 0/0 "GET /api/v1/users.presence?ids=qSAw2KaZcCDTu5PPn,Tjsu8HSpoWxnkHsNN,zP5kschyTmRy4zY2R,aopw5r3pQpMHH9EE6,kADrRX6iC9vPvoHpC,XSaFTATnFDeYfuqBM,NutSDjnh8AdMuqRfW,4qqkz3kBrcFufsxRM,EdSZ5YvPS2xvCjkEQ,MchQJdcn7ihuR4zuj,QCERXNqBpnmD78Xo3,qxL2AnpoL8aYBTHSt,r6aqbahWZA8ofLPq7,BnAEAmRDBoqJE9cMX,XNHt5S62FZWuQ4MEu,KQBHeobhbtC8fKfyY HTTP/1.1"
Jul 15 08:36:40 localhost haproxy[20707]: xxx  [15/Jul/2020:08:36:40.435] https_front~ chat_back/rocket03_3002 0/0/1/4/5 404 170 - - --VN 1822/1822/1794/61/0 0/0 "GET /api/v1/users.presence?ids=qSAw2KaZcCDTu5PPn,Tjsu8HSpoWxnkHsNN,zP5kschyTmRy4zY2R,aopw5r3pQpMHH9EE6,kADrRX6iC9vPvoHpC,XSaFTATnFDeYfuqBM,NutSDjnh8AdMuqRfW,4qqkz3kBrcFufsxRM,EdSZ5YvPS2xvCjkEQ,MchQJdcn7ihuR4zuj,QCERXNqBpnmD78Xo3,qxL2AnpoL8aYBTHSt,r6aqbahWZA8ofLPq7,BnAEAmRDBoqJE9cMX,XNHt5S62FZWuQ4MEu,KQBHeobhbtC8fKfyY HTTP/1.1"
Jul 15 08:36:46 localhost haproxy[20707]: xxx  [15/Jul/2020:08:36:46.794] https_front~ chat_back/rocket03_3002 0/0/1/5/6 404 170 - - --VU 1836/1836/1795/62/0 0/0 "GET /api/v1/users.presence?ids=qSAw2KaZcCDTu5PPn,Tjsu8HSpoWxnkHsNN,zP5kschyTmRy4zY2R,aopw5r3pQpMHH9EE6,kADrRX6iC9vPvoHpC,XSaFTATnFDeYfuqBM,NutSDjnh8AdMuqRfW,4qqkz3kBrcFufsxRM,EdSZ5YvPS2xvCjkEQ,MchQJdcn7ihuR4zuj,QCERXNqBpnmD78Xo3,qxL2AnpoL8aYBTHSt,r6aqbahWZA8ofLPq7,BnAEAmRDBoqJE9cMX,XNHt5S62FZWuQ4MEu,KQBHeobhbtC8fKfyY HTTP/1.1"
Jul 15 08:36:50 localhost haproxy[20707]: xxx  [15/Jul/2020:08:36:50.487] https_front~ chat_back/rocket03_3002 0/0/1/2/3 404 170 - - --VU 1823/1823/1792/61/0 0/0 "GET /api/v1/users.presence?ids=qSAw2KaZcCDTu5PPn,Tjsu8HSpoWxnkHsNN,zP5kschyTmRy4zY2R,aopw5r3pQpMHH9EE6,kADrRX6iC9vPvoHpC,XSaFTATnFDeYfuqBM,NutSDjnh8AdMuqRfW,4qqkz3kBrcFufsxRM,EdSZ5YvPS2xvCjkEQ,MchQJdcn7ihuR4zuj,QCERXNqBpnmD78Xo3,qxL2AnpoL8aYBTHSt,r6aqbahWZA8ofLPq7,BnAEAmRDBoqJE9cMX,XNHt5S62FZWuQ4MEu,KQBHeobhbtC8fKfyY HTTP/1.1"
Jul 15 08:36:52 localhost haproxy[20707]: xxx  [15/Jul/2020:08:36:52.293] https_front~ chat_back/rocket03_3002 0/0/1/7/8 404 170 - - --VN 1835/1835/1799/61/0 0/0 "GET /api/v1/users.presence?ids=qSAw2KaZcCDTu5PPn,Tjsu8HSpoWxnkHsNN,zP5kschyTmRy4zY2R,aopw5r3pQpMHH9EE6,kADrRX6iC9vPvoHpC,XSaFTATnFDeYfuqBM,NutSDjnh8AdMuqRfW,4qqkz3kBrcFufsxRM,EdSZ5YvPS2xvCjkEQ,MchQJdcn7ihuR4zuj,QCERXNqBpnmD78Xo3,qxL2AnpoL8aYBTHSt,r6aqbahWZA8ofLPq7,BnAEAmRDBoqJE9cMX,XNHt5S62FZWuQ4MEu,KQBHeobhbtC8fKfyY HTTP/1.1"

**Comment by sampaiodiego** [comment] 2020-07-21 16:56
do you have any kind of rules on haproxy that might be rewriting the URL? because that route is valid as you can see here:
https://github.com/RocketChat/Rocket.Chat/blob/022df828de7d79760453c55c05802a15d3ec7e93/app/api/server/v1/users.js#L713

also, can you try `curl` the same URL but directly into a rocket.chat backend (without going through haproxy)? that should work as well..

**Comment by emikolajczak** [comment] 2020-07-22 10:42
Hi I hav try curl direct to rocketchat
`curl x.x.x.x.:3000/api/v1/users.presence?ids=yDRCcrTdBFiaejJZN,4qqkz3kBrcFufsxRM,nTZQH2WqGaNberDH3,8Qvfi7nPNxufbbTuS,rkXQjYXpR6apATdXP,RghBL9P9fTZb3MCA5,by66C6oxc3dCRfcxK,ZxdrvHooDbca27ShK,H9YujbMqACFMWwkiZ,kADrRX6iC9vPvoHpC,XSaFTATnFDeYfuqBM,ivFionshQgYA883oB,mZYckPdinBRr47mvp,7HkB6uMLjDPmAZFtW,JfGAKzvxSNfEP5c6k,psJdB3NtKhuAPhwoq,FycBZn8fbuihdXKWt`
Nothing was returned.
On HAproxy we do not have any URL rewrites.

**Comment by sampaiodiego** [comment] 2020-07-22 19:04
thanks @emikolajczak .. from what I've found, the problem is related to this issue https://github.com/RocketChat/Rocket.Chat/issues/16174

**Comment by sampaiodiego** [comment] 2020-07-23 14:19
looking deeper into this issue, it is definitely the same problem as #16174 .. so I'll be closing this as duplicate and will schedule the other issue to fixed for next release.

**Closed by sampaiodiego** 2020-07-23 14:19 UTC
Labels: feat: rest, type: bug
