### ISSUE TITLE
Introduce History / storage time for messages in a channel

### ISSUE THREAD

**Issue by bott0r** [RocketChat/Rocket.Chat#2591] opened 2016-03-22 14:09 UTC
As usual, a picture to describe what i'd like to see.
The admin of a channel can decide via the admin panel how long messages and uploads in a given channel are supposed to be stored in your database. Ranging from infinite days to 1 day. 

![capture](https://cloud.githubusercontent.com/assets/17119942/13954124/b7336f20-f03f-11e5-9b0e-73a84d15ecf7.JPG)

In this case every message before Saturday, November 8, 2014 will be deleted

**Comment by Sing-Li** [comment] 2016-03-22 15:17
This is a duplicate of #795

Please relocate discussion to that ticket.  Closing this one.

**Closed by Sing-Li** 2016-03-22 15:17 UTC
