### ISSUE TITLE
Notifications not working in 3.9.2

### ISSUE THREAD

**Issue by nguiot** [RocketChat/Rocket.Chat#28879] opened 2023-04-12 09:36 UTC
Hello,

Just updated to 3.9.2 (had 3.9.0 earlier) : I'm using the desktop application, and I'm not receiving anymore notifications when new messages are sent on the channels.

I've checked my settings, and can't see any modifications to my config that would prevent them from displaying.

**Comment by hugocostadev** [comment] 2023-04-12 18:11
Hi @nguiot , did you try to clear the cache and storage data?

![image](https://user-images.githubusercontent.com/20212776/231546767-6a3dfda4-c154-4953-831b-df64485d5b39.png)

I could not reproduce it here...  Are you still facing this problem?

**Comment by nguiot** [comment] 2023-04-13 07:40
![image](https://user-images.githubusercontent.com/8997210/231685346-4bd43bc5-368e-4389-9f66-749b5896e790.png)
This is the french version, for Windows.

I tried to "reload" and "reload without using the cache", but notifications still don't show up.

I reinstalled an old 3.8.16 which was still in my archives, and notifications are working. I reinstalled 3.9.2, still KO
I checked the options, but nothing seems missing.

**Comment by nguiot** [comment] 2023-04-13 08:18
I found 3.9.1 and installed it : notifications are working fine.

**Comment by noobbbbb** [comment] 2023-04-13 09:20
So is it a client app issue?
https://github.com/RocketChat/Rocket.Chat.Electron/issues/2639

**Comment by nguiot** [comment] 2023-04-13 09:37
@noobbbbb yes, it's a client app issue. 
Sorry if I did not fill in correctly the first report, I just followed the link on the client GUI.

**Comment by hugocostadev** [comment] 2023-04-13 11:19
No Problem @nguiot ... I'll close this issue and let's follow up on this one: https://github.com/RocketChat/Rocket.Chat.Electron/issues/2639 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Closed by hugocostadev** 2023-04-13 11:19 UTC
Labels: stat: need more info, stat: waiting response
