### ISSUE TITLE
Latest direct messages should be on top in the list

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#5134] opened 2016-12-07 05:55 UTC
Your Rocket.Chat version: (0.47.0)
What if the latest direct messages should be on top in the list to avoid scrolling from searching the recent unread messages?

**Comment by MartinSchoeler** [comment] 2016-12-07 10:47
duplicate of #4821

**Closed by MartinSchoeler** 2016-12-07 10:47 UTC
