### ISSUE TITLE
Seen by for Direct Messages and Channels

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#5071] opened 2016-11-30 07:57 UTC
Seen by for Direct Messages and Channels

**Comment by TheReal1604** [comment] 2016-11-30 08:06
@zorenleo Thanks for that issue. I think that would be a feature request? Maybe you can go more into detail for issues in the future.. 

Thanks!

**Comment by MartinSchoeler** [comment] 2016-11-30 10:24
@zorenleo i think that is a duplicate of #4957, if not please reopen this issue

**Closed by MartinSchoeler** 2016-11-30 10:24 UTC
