### ISSUE TITLE
Working hours

### ISSUE THREAD

**Issue by sk044** [RocketChat/Rocket.Chat#17398] opened 2020-04-23 06:35 UTC
i think we can introduce a feature for working hours .. such that a user can only use that section in the mentioned period of time !! The admin can set the timings!! It would be useful for many people .. as it would remove the problem of messages at anytime (which sometimes can disturb a user)

**Comment by sk044** [comment] 2020-04-23 06:36
@kb0304 @Sing-Li Can i work on this??

**Comment by gabriellsh** [comment] 2020-04-24 22:32
Just to point out (maybe you already know this) we have that for livechat already. I think what you actually want is a timed notification suppression, am I right? (for ex. whatsapp mute for x time).

**Comment by cyrillbolliger** [comment] 2020-05-11 08:46
possible duplicate of #17301?

**Comment by gabriellsh** [comment] 2020-05-11 23:24
Thanks @cyrillbolliger! Duplicate of #17301, closing.

**Closed by gabriellsh** 2020-05-11 23:24 UTC
Labels: Feature: Request

**Comment by pedropilla** [comment] 2020-07-14 11:13
I think he mean 'add the ability to reproduce an office', I miss this ruleset too.
