### ISSUE TITLE
Verify Account with phone number 

### ISSUE THREAD

**Issue by bazarnew** [RocketChat/Rocket.Chat#3521] opened 2016-06-11 10:54 UTC
Your Rocket.Chat version: (make sure you are running the latest)

we can add another option for registering steps that get and verify their number instead of email
or get and verify both of them
this can be useful for future feature to find phone contacts that use a same rocketchat site too!
Need for this possibility
Price paid for making it possible

**Comment by geekgonecrazy** [comment] 2016-06-14 20:03
Duplicate of: #352

**Closed by geekgonecrazy** 2016-06-14 20:03 UTC
