### ISSUE TITLE
[MAJOR BUG]: Deletion of parent message leads to parentless message array.

### ISSUE THREAD

**Issue by ritvikjain99** [RocketChat/Rocket.Chat#16406] opened 2020-02-01 07:54 UTC
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34532173/73589039-fcac1100-44f6-11ea-89a4-ecd1efc47d2f.gif)
__BUG__:
On deletion of the initial message all the subsequent messages are left abruptly.
__SOLUTION__:
There has to be re-assigning of parent message and it's information should be displayed.
__STATUS__:
Working on it!
PS: It would be really helpful if you guide @MartinSchoeler

**Comment by ritvikjain99** [comment] 2020-02-02 20:03
@ggazzo I have some doubts related this issue, seek your guidance!

**Comment by gabriellsh** [comment] 2020-02-03 16:43
Duplicate of #16320.

**Closed by gabriellsh** 2020-02-03 16:43 UTC

**Comment by ritvikjain99** [comment] 2020-02-03 16:58
@gabriellsh 
It's not duplicate because if you see the root cause, there is no function that checks which message should be parent after deletion of a message.
The issue you mentioned talks about cascading the models related to message deleted.
Its to be decided on message deletion that the subsequent message would be parent or not. Which is not at all the case with the issue you mentioned.

**Comment by ritvikjain99** [comment] 2020-02-03 17:07
@gabriellsh I request you to reopen this issue !

**Comment by gabriellsh** [comment] 2020-02-03 18:39
Actually the problem is the same, but the symptoms are different. You see, it's not been defined what happens to parent messages when they are deleted. There's a setting that when you delete a message it shows "message deleted". If that is on, you'll have the same "problem" as the other issue.

I'd rather keep it localised so it's easier to fix.
