### ISSUE TITLE
Channel Notifications Preferences are ignored

### ISSUE THREAD

**Issue by jschirrmacher** [RocketChat/Rocket.Chat#14792] opened 2019-06-12 14:15 UTC
### Description:

When setting the notification preferences for a channel to mute @all and @here mentions or to hide the counter nothing changes: when using @here or @all by another user, the channel is still marked as changed and contains a "1" tag.

### Steps to reproduce:

1. As User 1 go to a channel and set the notification preferences to mute @all and @here mentions and to hide the counter.
2. Go to another channel or group
3. In another browser, log in as User 2, go to the previous channel and mention @all

### Expected behavior:

User 1 should not see any changes

### Actual behavior:

User 1 sees both, a highlighted channel name in the left channel bar and a "1" signaling a new mention in this channel

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Linuc
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.9

**Comment by tanc** [comment] 2019-06-20 08:53
We're also seeing this behaviour where `@here` messages get through despite the preference to not receive them in a channel.

```
Version: 1.1.2
Apps Engine Version: 1.4.2
Database Migration: 147
OS Type: Linux
OS Platform: linux
OS Arch: x64
OS Release: 4.15.0-52-generic
Node Version: v8.11.4
Mongo Version: 3.6.3
```

**Comment by jschirrmacher** [comment] 2019-11-08 10:31
Still not working in version 1.3.2.
Even when turning off ALL notifications, the channel name in the left sidebar gets marked.
Even when turning off the counter ("hide counter"), the numbers are still displayed.

**Comment by mrsimpson** [comment] 2019-11-08 11:15
@ggazzo can you please assign this to somebody or is this already addressed?

**Comment by mriedmann** [comment] 2019-11-19 11:05
We hit that problem on version 2.2.0 and it is really annoying. Any clue how to handle that until a proper fix is ready?

**Comment by DmytroPuzhay** [comment] 2019-12-05 10:56
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone

**Comment by dsgagi** [comment] 2020-03-12 08:35
Version 3.0.3 still affected by this.

**Comment by sampaiodiego** [comment] 2020-03-16 18:52
taking a deeper look into this issue I've found the current option ("hide counter") is misleading..

if you guys want to have a way to not show any updates of a channel we'll need a new option to do that.

wdyt?

**Comment by engelgabriel** [comment] 2020-03-19 18:28
Refs: https://github.com/RocketChat/Rocket.Chat/issues/11609
Refs: https://github.com/RocketChat/Rocket.Chat/issues/12689

**Comment by engelgabriel** [comment] 2020-03-20 20:19
We need to rethink this from a fresh start. The options are really confusing indeed. I'll add get our UX team to look into it for the next release.

**Comment by pascal1337** [comment] 2020-05-29 11:14
How about this feature? Also if in 3.3.0 notifications were fully rethinked, we have the problem, when every of the three notification options is disabled, we still receive notifications.

**Comment by piahoo** [comment] 2020-06-29 13:21
are we going to have any updates? this is really annoying

**Comment by michalpiasecki1** [comment] 2020-08-10 09:18
is there any chance to fix it?

**Comment by banoleb** [comment] 2020-09-25 14:20
> is there any chance to fix it? this bug is still in 3.5.1

also in 3.6.2

**Comment by tanc** [comment] 2021-03-09 15:55
Frustratingly still an issue. Is there any chance this can get looked at sooner than milestone 4.1?

My personal user story for this is:

As a rocket.chat user,
I want to remain part of channels but not be notified or have the channel indicator increment when `@all` or `@here` is used in channels
So that I can drop in and look at channel messages without thinking someone has notified me directly

At the moment when there is a channel indicator I'm not sure if its because someone has @'d me or the channel. I'd prefer to know if a message is directed at me so I can see at a glance which channel I need to respond on. Otherwise I have to check each one with an incremented indicator to see if they were talking to me.

**Comment by sampaiodiego** [comment] 2021-03-30 13:51
I'm really sorry the delay guys. as @engelgabriel we need to rethink the notification preferences from scratch.. unfortunately it didn't happen within the timeframe he would like to, but we're already talking about it internally.

in the mean time, I can say this is working as expected, I'd say it is a matter of an UX issue.. in order to get rid of the highlighted channel and the "notification counter", you should also turn off the option called "Show counter", so your options should look like this:
![image](https://user-images.githubusercontent.com/8591547/112999617-7bc1c700-9145-11eb-8ba5-1863e85e93ed.png)

this way the expected results from this issue can be achieved. so I'll be closing this issue since the options are working as designed. as I mentioned we'll be looking into how to improve the UX of this, so we may need to get rid of some of those preferences..

**Comment by tanc** [comment] 2021-03-30 18:19
@sampaiodiego I'm not sure it does work properly though, I have `Show counter` and `Mute @all and @here mentions` off yet I still see a counter whenever anyone uses `@here`

**Comment by sampaiodiego** [comment] 2021-03-30 18:46
hi @tanc .. so `Show counter` should be *off* and `Mute @all and @here mentions` should be *on*.. as you can see on this video:

https://user-images.githubusercontent.com/8591547/113040309-079c1900-916f-11eb-8117-ac4630c454d2.mp4

**Comment by tanc** [comment] 2021-03-30 20:41
@sampaiodiego sorry I made a mistake, I meant that I have `Mute @all and @here mentions` turned on and `Show counter` turned off. I was writing in a hurry. I'll confirm tomorrow when there is activity and will take some screenshots or a video.

**Comment by tanc** [comment] 2021-03-31 17:39
@sampaiodiego after today I can confirm I still see a channel notification icon even though my settings are configured to not show the counter and to mute mentions, as screenshots below:
 
![image](https://user-images.githubusercontent.com/76320/113187045-b0727300-9258-11eb-9c61-fec057a9c2ef.png)

![image](https://user-images.githubusercontent.com/76320/113187068-b700ea80-9258-11eb-8958-1395f8539726.png)

**Comment by tanc** [comment] 2021-03-31 17:45
The counter shown above was triggered by someone in that channel using `@here`. My expectation as a user is that if `Show counter` is off and `Mute @all and @here mentions` is on that I should _not_ see an icon indicating there is an unread message.

**Comment by tanc** [comment] 2021-03-31 17:48
```
Version
3.12.1
```
```
Apps Engine Version
1.23.0
```
```
Node Version
v12.18.4
```
```
Database Migration
218 (March 31, 2021 8:48 AM
```
```
MongoDB
3.6.3 / wiredTiger (oplog Enabled)
```

**Comment by tanc** [comment] 2021-03-31 17:49
I guess I should set up a test version and confirm its an issue there and if it isn't a bug then we need to figure out why this instance is not the same as a fresh instance and fix it

**Comment by DmytroPuzhay** [comment] 2021-04-01 09:19
@sampaiodiego it clearly does not work as expected. In case as you said "we'll be looking into how to improve the UX of this" than please open/link respective feature request so it's tracked somehow.

**Comment by sampaiodiego** [comment] 2021-04-01 17:12
thanks @tanc .. I tried it again on a fresh install and I could see the same behavior as you.. I agree it is not working as expected then.. I'll open the issue again and we'll take a deeper look for next release.. Thanks again for you commitment on testing it, really appreciated 👍 

@DmytroPuzhay we are tracking that on our internal systems only.. we'll let the community know when we have something public to share..

**Comment by sampaiodiego** [comment] 2021-04-01 20:37
hey guys, I did further testing on this and looks like it was indeed buggy on 3.12.x but it seems fixed on 3.13 release candidate.. maybe you test it out @tanc ? `3.13.0-rc.5` is the current latest release candidate for 3.13 release.. the final cut for 3.13 should be done today or tomorrow.

**Comment by tanc** [comment] 2021-04-02 06:49
I started having a go at installing locally but as there aren't docker images for prerelease versions it was proving too complex getting set up and I didn't want to install meteor locally. I'll trust that it is fixed in the next release and I'll report back once it's installed on our local server to confirm.

**Comment by sampaiodiego** [comment] 2021-04-06 16:17
oh, there is no official one, but you could have used the Docker image `rocketchat/rocket.chat:3.13.0-rc.5` .. anyways, the final release is out, you can already run it using the following Docker image `rocketchat/rocket.chat:3.13.0`..

the Official Docker image is waiting Docker folks merge https://github.com/docker-library/official-images/pull/9930

**Comment by tanc** [comment] 2021-04-07 06:27
> there is no official one, but you could have used the Docker image rocketchat/rocket.chat:3.13.0-rc.5

@sampaiodiego good to know for next time!

I tested the latest stable docker images and this time the counter toggle works as expected in that with the toggle off, no counter was shown.

Thank you (whoever did it) for fixing that!

I'll open a new issue now as it would be good to have the channel counter show in a certain circumstance: when someone directly addresses you with `@yourname` it might be nice to display a counter on a channel

**Comment by DmytroPuzhay** [comment] 2021-04-07 07:10
Nice!

**Comment by sampaiodiego** [comment] 2021-04-07 12:47
thanks guys.. I'll close the issue again, as it is fixed on latest release.

> I'll open a new issue now as it would be good to have the channel counter show in a certain circumstance: when someone directly addresses you with `@yourname` it might be nice to display a counter on a channel

thanks @tanc , you can ping me when you open it and I'll make sure we take that into consideration when thinking on better UX for those notification preferences.

**Closed by sampaiodiego** 2021-04-07 12:47 UTC
Labels: feat: notification, type: improvement
