### ISSUE TITLE
Websocket 

### ISSUE THREAD

**Issue by HewittJC** [RocketChat/Rocket.Chat#7563] opened 2017-07-24 20:15 UTC
### Description:

File upload doesn't work. Image upload, video send, voice send, and avatar image upload.

### Server Setup Information:

* Version of Rocket.Chat Server: latest (as of this post)
* Operating System: Ubuntu Server 16.04
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1

### Steps to Reproduce:

1. Login
2. Go to upload avatar and select image
3. Click use uploaded image
4. Check console for error

### Expected behavior:

Image is uploaded and the avatar changes

### Actual behavior:

Nothing in the GUI, only an error in the web inspector.

### Other Info

Here is the relevant error:

<img width="549" alt="screen shot 2017-07-24 at 4 12 07 pm" src="https://user-images.githubusercontent.com/28607855/28542711-26b7bafa-708b-11e7-90f5-39561045633d.png">

If you look at the above error you can see that the request URL doesn't included my modified location of rocket chat. We are hosting it at something like https://example.com/chat-url/ and if you look at the image its only going to https://example.com/ufs/... (lacking the /chat-url/)

Not sure where I can define this though.

Also for reference I followed the official docs Docker tutorial/setup in order to get this going. The only thing I did different was to add the /chat-url/ to the nginx proxy_pass section and added it to the ROOT_URL in the docker-compose file.

**Comment by MartinSchoeler** [comment] 2017-07-25 12:17
Duplicate of #4832

**Closed by MartinSchoeler** 2017-07-25 12:17 UTC
