### ISSUE TITLE
[Bug][Federation] Missing chats and messages

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#17828] opened 2020-06-05 04:49 UTC
### Description:

We have only one federation of two servers, both on version **3.1.1**, both servers has **success result of federation test**. 
![image](https://user-images.githubusercontent.com/4023037/83838335-908a2580-a701-11ea-8530-62cce0562d63.png)
Both servers use **DNS for Discovery Method**. For both servers created **_rocketchat._https.** and **_rocketchat._tcp. SRV** records and **TXT DNS records**, but no **_rocketchat._http.** records (both servers use **HTTPS** and not use **HTTP** to operate)
![image](https://user-images.githubusercontent.com/4023037/83838291-6e90a300-a701-11ea-8aba-4b76700a604e.png)

And in **general federation works good** - most of users on both servers can find each other and communicate.
But some users experience **critical problems** with federation.
- One user of server 2 was added to private chat on server 1 and that chat appeared in that user chat list on server 2, but that chat is empty - not messages. But on server 1 there is a lot of messages

- Second user of server 2 was added to other private chat - but that chat not appeared in that user chat list on server 2.
And in logs we see:
````

at app/federation/server/hooks/afterAddedToRoom.js:41:4
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
at app/federation/server/hooks/afterCreateRoom.js:43:9
=> awaited here:
at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
server.js:204 Federation ➔ client.error afterAddedToRoom => Could not add user: Error: Cannot federate rooms with more than 10 domains

````
**Could not add user: Error: Cannot federate rooms with more than 10 domains** but I repeat - we have only one federation with two servers

- Third users of server 2 have DM with me (I'm on server 1), and he see my messages, but I don't see his reply in that DM on my server 1.
Servers logs on server 1 is empty. but on server 2 we see this:

````
I20200605-06:28:23.987(0) Exception in defer callback: TypeError: Cannot read property 'filter' of undefined     
at RocketChatIntegrationHandler.getTriggersToExecute (app/integrations/server/lib/triggerHandler.js:505:16)     
at RocketChatIntegrationHandler.executeTriggers (app/integrations/server/lib/triggerHandler.js:576:34)     
at _wrapperFunction (app/integrations/server/triggers.js:6:38)     
at callbacks.runItem (app/callbacks/lib/callbacks.js:110:70)     
at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)     
at app/callbacks/lib/callbacks.js:39:35     
at app/callbacks/lib/callbacks.js:45:45     
at app/callbacks/lib/callbacks.js:45:47     
at app/callbacks/lib/callbacks.js:45:47     
at app/callbacks/lib/callbacks.js:45:47     
at app/callbacks/lib/callbacks.js:45:47     
at app/callbacks/lib/callbacks.js:45:47     
at app/callbacks/lib/callbacks.js:45:47     
at app/callbacks/lib/callbacks.js:45:47     
at app/callbacks/lib/callbacks.js:45:47     
at app/callbacks/lib/callbacks.js:45:47     
at app/callbacks/lib/callbacks.js:45:47     
at callbacks.run (app/callbacks/lib/callbacks.js:126:9)     
at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)     
at app/lib/server/functions/sendMessage.js:243:32     
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     
at packages/meteor.js:550:25     
at runWithEnvironment (packages/meteor.js:1286:24)

````

### Expected behavior:

All users of server 1 can fully communicate with all users of server 2 and vice versa 

### Actual behavior:

Some users have critical problems with federation, which a pain for them.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: 2.17.7 and Chrome 83
- Operating System: Windows 10 mostly

**Comment by ankar84** [comment] 2020-08-04 12:36
That's very important issue for us, and it's still not fixed.

**Comment by alansikora** [comment] 2020-09-22 19:06
Hey @ankar84!

> One user of server 2 was added to private chat on server 1 and that chat appeared in that user chat list on server 2, but that chat is empty - not messages. But on server 1 there is a lot of messages

I could not reproduce this specific error on my local, I tested with over 100 users on a single channel, exchanging messages, no issues. I will need more information on that.

> Could not add user: Error: Cannot federate rooms with more than 10 domains but I repeat - we have only one federation with two servers

This is probably fixed on the current version, it was added on this [commit and line](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/federation/server/hooks/afterAddedToRoom.js#L50).

> Third users of server 2 have DM with me (I'm on server 1), and he see my messages, but I don't see his reply in that DM on my server 1.

Who created the DM? The user on the server 1 or on the server 2? Also, are other DMs working?

**Comment by ankar84** [comment] 2020-09-23 04:51
Hey, Alan @alansikora 
And thanks a lot for your attention!

> This is probably fixed on the current version, it was added on this [commit and line](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/federation/server/hooks/afterAddedToRoom.js#L50).
Do I get this right, that this commit is merged in [version 3.4.0](https://github.com/RocketChat/Rocket.Chat/pull/18078) [here](https://github.com/RocketChat/Rocket.Chat/commit/1cfd8201112b654a1c53696e5ed6eb6b88b882a9)? So now we need to upgrade both servers to 3.4.0 minimum to get rid of that bug?

> Who created the DM? The user on the server 1 or on the server 2? Also, are other DMs working?

Actually I don't remember, all was done 3 month ago. But most of other DM worked fine. I write most, because maybe there is such problem DM users didn't report me.

**Comment by alansikora** [comment] 2020-09-24 19:35
@ankar84 yes, but I recommend that you wait a little and upgrade to the latest version, which is not live yet. There are some fixes to the current functionality. I'm verifying when the new version will be released and let you know.

**Comment by ankar84** [comment] 2020-09-25 01:08
> @ankar84 yes, 3.4.0, but I recommend that you wait a little and upgrade to the latest version, which is not live yet. There are some fixes to the current functionality. I'm verifying when the new version will be released and let you know.

Actually it is what I'm plan to do - upgrade to 3.7.0
And after you said that there is also fixes for federation - I'm getting stronger in my plans.
Thank you very much, Alan!

**Comment by alansikora** [comment] 2020-09-25 15:01
@ankar84 version 3.6.3 is already here, you can update to that one.

**Comment by ankar84** [comment] 2020-09-25 15:03
> @ankar84 version 3.6.3 is already here, you can update to that one.

Yes, I saw federation fixes in that version and now we are preparing to upgrade to 3.6.3

**Comment by ankar84** [comment] 2020-10-08 15:19
Problem chat now available for federated user, but for him chat is empty (without history, but in fact, there is message history)
All me conversations are visible to user.
So,issue is closed.
Thanks @alansikora

**Closed** 2020-10-09 03:28 UTC
Labels: feat: federation
