### ISSUE TITLE
CORS issue when using multiple domains and file upload.

### ISSUE THREAD

**Issue by serviceman** [RocketChat/Rocket.Chat#14815] opened 2019-06-15 20:28 UTC
### Description:

I am running in a sub directory, I am running the same instance on domain.com/chat as I am domain2.com/chat as an Alias with Apache. I use the same chat on multiple sites. Everything seems to work fine but when I try to upload a file it is stuck at 0% with a CORS error. If i put     Header set Access-Control-Allow-Origin "*" in my htaccess file everything works fine. This problem doesn't happen right away, sometimes I have to let the chat run for an hour or two before issues start to happen. I am sure this is a CORS issue because after setting the Access-Control-Allow-Origin in the .htaccess file I have had no issues for 24 hours.

I believe that there is a CORS issues when using multiple domains on the same instance.

### Steps to reproduce:

1. Install rocket chat in sub directory.
2. Access chat on two domains that are used as an alias of one install.
3. Attempt to upload file and it gets stuck on 0%.

### Expected behavior:

File upload should work on all domain Aliases of an install.

### Actual behavior:

File upload only works on URL that the original install was made on.

### Server Setup Information:

Version of Rocket.Chat Server: 1.0.3
Operating System: Centos 7
Deployment Method: manual tar install
Number of Running Instances: 3
DB Replicaset Oplog: yes

**Comment by reetp** [comment] 2019-06-16 20:47
I can't see where but this has already been asked and there is at least one Issue on it.

Please close this and follow up on the original Issue.

You can open a NFR and cross reference.

**Comment by reetp** [comment] 2019-06-16 20:51
@rocket-cat close

Duplicate of #13889

**Closed by reetp** 2019-06-16 20:51 UTC

**Comment by serviceman** [comment] 2019-06-16 23:30
I do not agree that this should be closed, this bug report has nothing to do with the API or the iframe login (both of which are working fine), it has to do with the file upload inside the rocket chat failing. There is no way to set a CORS header for this action.
