### ISSUE TITLE
Exception while invoking method autoTranslate.getSupportedLanguages Error: Auto-Translate is not allowed

### ISSUE THREAD

**Issue by larkinson** [RocketChat/Rocket.Chat#18782] opened 2020-09-02 23:03 UTC
### Description:

Suddenly, out of blue, I started getting the following error in the logs in the rocket.chat admin panel, even though I haven't changed any of the settings:

Exception while invoking method autoTranslate.getSupportedLanguages Error: Auto-Translate is not allowed [error-action-not-allowed] at MethodInvocation.autoTranslate.getSupportedLanguages (app/autotranslate/server/methods/getSupportedLanguages.js:11:10) at MethodInvocation.methodsMap. (app/lib/server/lib/debug.js:67:34) at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12) at packages/ddp-server/livedata_server.js:1689:15 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js123412) at packages/ddp-server/livedata_server.js:1687:36 at new Promise () at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12) at Server.apply (packages/ddp-server/livedata_server.js:1625:26) at Server.call (packages/ddp-server/livedata_server.js:1607:17) at Object.post (app/api/server/v1/misc.js:262:26) at app/api/server/api.js:388:82 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js123412) at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39) at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32) at packages/nimble_restivus/lib/route.coffee:59:33 at packages/simple_json-routes.js:98:9 => awaited here: at Promise.await (/snap/rocketchat-server/1440/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12) at Server.apply (packages/ddp-server/livedata_server.js:1638:22) at Server.call (packages/ddp-server/livedata_server.js:1607:17) at Object.post (app/api/server/v1/misc.js:262:26) at app/api/server/api.js:388:82 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js123412) at Object._internalRouteActionHandler [as action] (app/api/server/api.js:388:39) at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32) at packages/nimble_restivus/lib/route.coffee:59:33 at packages/simple_json-routes.js:98:9

### Steps to reproduce:

1. Go to admin panel
2. Click "view logs"
3. See the error

### Expected behavior:

There shouldn't be any errors.

### Actual behavior:

There is an error.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.2
- Operating System: Ubuntu 20.4
- Deployment Method: snap
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1 - x64
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Chrome 85
- Operating System: Irrelevant to the problem

### Additional context

Nothing.

### Relevant logs:

The log is in the description.

**Comment by sheuschkel** [comment] 2020-09-04 09:29
Same issue on 3.6.0

i get periodically this error message

> Exception while invoking method autoTranslate.getSupportedLanguages
> Error: Auto-Translate is not allowed [error-action-not-allowed] 
> at MethodInvocation.autoTranslate.getSupportedLanguages (app/autotranslate/server/methods/getSupportedLanguages.js:10:10)
> at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:67:34)
> at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12) 
> at packages/ddp-server/livedata_server.js:1689:15
> at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
> at packages/ddp-server/livedata_server.js:1687:36
> at new Promise (<anonymous>)
> at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)
>     at Server.apply (packages/ddp-server/livedata_server.js:1625:26)
>     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
>     at Object.post (app/api/server/v1/misc.js:262:26)
>     at app/api/server/api.js:394:82
>     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
>     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
>     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
>     at packages/nimble_restivus/lib/route.coffee:59:33
>     at packages/simple_json-routes.js:98:9
>  => awaited here:
>     at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
>     at Server.apply (packages/ddp-server/livedata_server.js:1638:22)
>     at Server.call (packages/ddp-server/livedata_server.js:1607:17)
>     at Object.post (app/api/server/v1/misc.js:262:26)
>     at app/api/server/api.js:394:82
>     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
>     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:394:39)
>     at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:150:32)
>     at packages/nimble_restivus/lib/route.coffee:59:33
>     at packages/simple_json-routes.js:98:9

**Comment by sheuschkel** [comment] 2020-10-05 20:09
Still an issue in 3.6.3

**Comment by Roemer** [comment] 2020-10-06 14:34
I have the same issue in 3.7.0 as well

**Comment by Nono-m0le** [comment] 2020-10-07 15:25
Same here (duplicate of https://github.com/RocketChat/Rocket.Chat/issues/18662 ?)

**Closed** 2020-10-23 22:13 UTC
