### ISSUE TITLE
System wide auto delete feature

### ISSUE THREAD

**Issue by RichGriese** [RocketChat/Rocket.Chat#8321] opened 2017-09-26 22:16 UTC
Would like to see a system wide setting available to owner/admin that would set a "drop dead date" / auto delete period for all message on the system. Public channels, private groups & private messages. Owner/admin could set entire environment to auto delete in 7, 30, etc... days.

I believe chat should be ephemeral like real conversations. I believe therefore that logs of chat should have the option of simply going away if the owner/admin wants to promote that kind of environment.

Cheers! Rich G

**Comment by localguru** [comment] 2017-09-28 22:00
Beside a system wide purge, a configuration for each channel would be nice, so that owners/moderators can decide per channel/room (if a global permission allows this).

**Comment by ulope** [comment] 2017-10-03 13:24
Duplicate of #2355

**Comment by TheMythPT** [comment] 2018-04-30 03:57
This is really an important feature, since not everyone is able to rent machines with tons of disk space.
And using snap to install Rocket.chat, makes impossible to query the MongoDB database to make some sort of hack to delete all the messages `older than X`.
Honestly, I think that an option like this should have been already implemented. It's an option lacking in almost every chat platform like Rocket.chat (HumHub, Zulip, etc), and I think that this would make the stacks go higher a bit and put Rocket.chat in the lead of innovation.

**Comment by vynmera** [comment] 2018-06-25 15:57
I'm making it happen! ---> #11236

**Closed** 2018-07-20 04:26 UTC
