### ISSUE TITLE
Invite links lead to error message if user is not logged in

### ISSUE THREAD

**Issue by wolbernd** [RocketChat/Rocket.Chat#24719] opened 2022-03-07 10:15 UTC
### Description:

If an invite Link to a channel/room is clicked and the user calling the link is currently not logged in an error message stating "Invalid or expired invite token" is shown.

The invite link exists and is not expired. 

### Steps to reproduce:

1. Create a channel/room or use an existing one
2. Create an invite link (resulting in something like this: https://go.rocket.chat/invite?host=my.rc.server&path=invite%2Fabcdef
3. Open link in a browser where you are logged in -> You join the channel
4. Open link in another browser/private tab -> error message

### Expected behavior:

For users who are not logged in a login dialogue should be shown

### Actual behavior:

Error message is shown: 
![Screenshot_20220307_110450](https://user-images.githubusercontent.com/24311754/157010294-b6ebeeb7-22ab-4326-8dba-ad5a50078873.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.0
- Operating System: Ubuntu 20.04
- Deployment Method: manual build
- Number of Running Instances: 4
- DB Replicaset Oplog: enabled
- NodeJS Version: v14.19.0
- MongoDB Version: 4.4.12 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Firefox 97/Chromium  99.0.4844.51
- Operating System: Arch Linux

### Additional context

When opening the link as a logged in user the error message can be seen for the split part of a second before redirecting to the invited channel.

### Relevant logs:

The server log show one line when this happens:
`{"level":50,"time":"2022-03-07T10:13:54.891Z","pid":9526,"hostname":"mychatserver","name":"","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"}  `

**Comment by ankar84** [comment] 2022-03-09 05:47
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/24444

**Closed** 2022-04-07 12:25 UTC
