### ISSUE TITLE
Cannot Hide Room when using Afrikaans language

### ISSUE THREAD

**Issue by Fscape** [RocketChat/Rocket.Chat#10772] opened 2018-05-15 08:20 UTC
### Description:
When Afrikaans is set as the user's language, the Hide buttons do nothing when clicked.
(Both in the left side "three dots" menu, and the room's "i" Room Info right side menu.)

In Chrome's console when clicked:
![on_click](https://user-images.githubusercontent.com/24841675/40045010-6e404a1e-5829-11e8-82a1-aa3750287af8.PNG)

Works fine with other languages
e.g. French and Dutch

### Server Setup Information:
* Version of Rocket.Chat Server: 0.63.3 (+ 0.64.1 candidate)
* Operating System: Ubuntu 16.04.4 LTS
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.4
* mongoDB Version: v3.2.7

### Steps to Reproduce:
1. Click the three dots next to a room name
2. Click "Hide Room" (aka "Versteek kamer")

A. Click the "i" Room Info icon
B. Click "Hide" button

### Expected behavior:
Popup confirming "Hide Room"

### Actual behavior:
Nothing

### Relevant logs:
--

**Comment by cmonjeau** [comment] 2018-05-15 14:54
Hi,

I observed the same problem with French / Spanish / Italy.

I'm in version 0.63.1.

**Comment by ggazzo** [comment] 2018-06-15 19:37
@Fscape could you try again? I couldnt reproduce you problem =/

**Comment by Fscape** [comment] 2018-06-15 20:02
Still the same deal for me, on both my servers (now 0.65.1).

Let me know if I can provide some info to assist.

**Comment by ggazzo** [comment] 2018-06-18 01:30
the channel's  name.. could you provide me? I changed my language and its working =/

**Comment by Fscape** [comment] 2018-06-18 07:47
Hi, it's not just a particular room - it's all of them.

Some examples: 
- general
- channel-hyphen
- private_underscore
- chris (Direct Message)

**Comment by ggazzo** [comment] 2018-06-18 13:34
@Fscape could you try here http://open.rocket.chat ? I will make more tests

**Comment by Fscape** [comment] 2018-06-18 14:54
It works fine for me on http://open.rocket.chat !
Quite strange.

So I just installed a fresh snap rocketchat-server 0.65.1 (clicked continue through the wizard leaving everything default).
Went straight to my Profile, and Afrikaans was showing as the Localization language (probably because it's at the top of the dropdown list) ... but everything is in English [Hide Room works]
Saved language as English [Hide Room works]
Saved language as Afrikaans [Hide Room does not work]

**Comment by ggazzo** [comment] 2018-06-18 16:50
we are using develop:latest on open... could you do more one more test? I after that I will search version by version to find which pr fixed the problem

**Comment by Fscape** [comment] 2018-06-19 08:22
Sure, do you mean test again on open.rocket.chat?
It works correctly on there for me

**Comment by ggazzo** [comment] 2018-06-20 19:49
opss, I didnt see the first part 
> It works fine for me on http://open.rocket.chat !

lets wait for 0.66

**Comment by ggazzo** [comment] 2018-07-04 19:17
what do you think @Fscape can I close the issue?

**Comment by Fscape** [comment] 2018-07-05 07:34
Yes, it definitely works on develop:latest
Thanks :+1:

**Closed** 2018-07-10 05:03 UTC
Labels: subj: ui/ux, type: bug
