### ISSUE TITLE
Push Notifications not working with Flutter

### ISSUE THREAD

**Issue by TobiasLenzEconix** [RocketChat/Rocket.Chat#24377] opened 2022-02-01 07:50 UTC
### Description:

I am using a flutter App with Firebase and want to receive push notifications on new messages.
I register the device tokens using the [REST-API](https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/push-token-endpoints/push-token). I configured the server with the Firebase Project data for GCM.

For Flutter push notifications the notification data needs to contain a click_action property:

"click_action": "FLUTTER_NOTIFICATION_CLICK",
see:
https://stackoverflow.com/questions/48403786/how-to-open-particular-screen-on-clicking-on-push-notification-for-flutter

### Steps to reproduce:

1. Using a Flutter project with Firebase and connection to backend
2. Trigger a push notification by sending a pm to the registered user.

### Expected behavior:

A push notification showing up with necessary data fields.

### Actual behavior:

No push notification at all.

### Server Setup Information:

Deployment
Version
4.1.2
Deployment ID
aMwtvdvFR5i923ASc
Apps Engine Version
1.28.1
Node Version
v12.18.4
Database Migration
243 (January 31, 2022 1:50 PM)
MongoDB
4.4.12 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (2aba8d2d8) 
Branch: HEAD
PID
706

### Client Setup Information

Flutter App

### Relevant logs:

{"msg":"ENAMETOOLONG: name too long, open 'MIIGWjCCBUKgAwIBAgIIW4Sk9vhfki0wDQYJKoZIhvcNAQELBQAwgZYxCzAJBgNV<br>BAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3Js<br>ZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3<br>aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw<br>HhcNMjIwMTI1MjA0MjQ4WhcNMjMwMjA3MjE0ODQ3WjCBqDEvMC0GCgmSJomT8ixk<br>AQEMH2RlLmVjb25peC5pbnRyYW5ldC5pbnN0YWxsYXRpb24xPTA7BgNVBAMMNEFw<br>cGxlIFB1c2ggU2VydmljZXM6IGRlLmVjb25peC5pbnRyYW5ldC5pbnN0YWxsYXRp<br>b24xEzARBgNVBAsMCjJGOVpEVlRTTjMxFDASBgNVBAoMC2Vjb25peCBHbWJIMQsw<br>CQYDVQQGEwJERTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKiQ0/x3<br>x3OJEWu4C7R08hTrCe7WPQRjI6Zx2goNX78zlCvJNTyboFNh95bcbzNGpsEWQhJl<br>DAWj+yuCGvl7Keq5psJpyBxvh11gHHeMrAhQVE/A1kAWrx2yXBK4CYpSi5FbGtPn<br>iGtL34GzNbPYfCQGg2M0b7LV57eWwbcDgs6/Cq7Ec8v7ZP9nZ8iSqWfjg4ZrUlJy<br>Y3fWmR0nBflVq4wllca4SX2v/QtFVPV4N2Ni4B9YvCQOOhWBQ7Xz2Jl314U8VTYS<br>pHw5UVNOEJChUDhdmVwrkWuPSes7Nl0CwcCaQn00hRcRCZFiXiUmxlkUux0v6NeD<br>A4FoVix8cGNFwHMCAwEAAaOCApYwggKSMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgw<br>FoAUiCcXCam2GGCL7Ou69kdZxVJUo7cwggEcBgNVHSAEggETMIIBDzCCAQsGCSqG<br>SIb3Y2QFATCB/TCBwwYIKwYBBQUHAgIwgbYMgbNSZWxpYW5jZSBvbiB0aGlzIGNl<br>cnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFjY2VwdGFuY2Ugb2YgdGhl<br>IHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBhbmQgY29uZGl0aW9ucyBv<br>ZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2VydGlmaWNhdGlvbiBwcmFj<br>dGljZSBzdGF0ZW1lbnRzLjA1BggrBgEFBQcCARYpaHR0cDovL3d3dy5hcHBsZS5j<br>b20vY2VydGlmaWNhdGVhdXRob3JpdHkwEwYDVR0lBAwwCgYIKwYBBQUHAwIwMAYD<br>VR0fBCkwJzAloCOgIYYfaHR0cDovL2NybC5hcHBsZS5jb20vd3dkcmNhLmNybDAd<br>BgNVHQ4EFgQUNpyZlV7UZykcCP+FinBbdgWV6jowDgYDVR0PAQH/BAQDAgeAMBAG<br>CiqGSIb3Y2QGAwEEAgUAMBAGCiqGSIb3Y2QGAwIEAgUAMIGmBgoqhkiG92NkBgMG<br>BIGXMIGUDB9kZS5lY29uaXguaW50cmFuZXQuaW5zdGFsbGF0aW9uMAUMA2FwcAwk<br>ZGUuZWNvbml4LmludHJhbmV0Lmluc3RhbGxhdGlvbi52b2lwMAYMBHZvaXAMLGRl<br>LmVjb25peC5pbnRyYW5ldC5pbnN0YWxsYXRpb24uY29tcGxpY2F0aW9uMA4MDGNv<br>bXBsaWNhdGlvbjANBgkqhkiG9w0BAQsFAAOCAQEAOX7sj/qH4qn9bg2qVImO+kZ0<br>ysFmy2TbrhW8AE6yFa7POPXHo2YV/Pp4cNmaK6rk+wRx5puf65xJKx7y0bz7RnsF<br>F6SlrcZtS7DOlMgfkZ+Ua8UihItyM37Ty+MF2rS86pCvUsY/TjGu+WFCotf23sNK<br>eyppbAOJNiNNmDQG/L9p13wq6kgSqyzgspcFwqKbiVWfVHxhts4jYbwyIm5NFmIw<br>NwWXp28jqoVL+2vjhuwLpFsLigsnwFwl3PBtTiSNbOP1oLIDu1RLDvRPpAeCe6gn<br>rhpIC74yfCdVb1m5h3mGsTL8tqKF0V6VuM0X612AcZ2eDkPh5BUdGShKZEFEKw=='"}

**Comment by debdutdeb** [comment] 2022-02-01 09:32
The flutter app is no longer officially supported. We can not help you with this. 

Closing this since it is not a bug of the product.

Feel free to continue the thread if you need additional information. Thanks

**Closed by debdutdeb** 2022-02-01 09:32 UTC

**Comment by TobiasLenzEconix** [comment] 2022-02-01 12:48
@debdutdeb I am not using any official Flutter App.
I am writing one by myself. And I can't get it to work if I can not add the click action data to the push notifications.

**Comment by debdutdeb** [comment] 2022-02-01 18:10
> I am writing one by myself

Awesome! 

Then I suggest you head over to https://open.rocket.chat/channel/dev and https://open.rocket.chat/channel/react-native 

People there may be able to help you out 🤗
