### ISSUE TITLE
DMs are not treated as a mention for notifiations 

### ISSUE THREAD

**Issue by fleaz** [RocketChat/Rocket.Chat#23693] opened 2021-11-11 13:25 UTC
### Description:
Hey,
I feel like direct messages are in the wrong "notification category". The three options for notifications are "All messages, Only mentions, Nothing". 
From my expectation  a message in a 1:1 direct channel with someone should have the same importance as a mention in a regular chat and be part of the "Mentions" options in the notification system. Especially on a bigger server you obviously don't want to have your notifications set to "All messages", but when set to "Mentions" you don't get an alert for a DM which is probably not what one would expect.

I'm not 100% sure if this is more of a feature request, but on the other hand treating DMs like mentions is from what I know the default in all other messengers and so most user probably expect that. If this is a FR in your eyes, I'm sorry for the spam and I will open a new one in the feature request repo.

Best,
Felix

### Steps to reproduce:

1. Go to your Profile Settings, and set Desktop or Push Notifications to "Mentions"
2. Let someone write you a DM
3. Set Notifications to "All messages"
4. Let someone write you a DM

### Expected behavior:
Messages in a 1:1 direct message should be treated like mentions regarding my push notifications.

### Actual behavior:
Messages in a 1:1 direct message are treated exactly like every other text message in a regular channel.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.17.2
- Deployment Method: RocketChat Cloud

### Client Setup Information

- Desktop App or Browser Version: 3.5.7
- Operating System: Arch Linux
- Mobile App: 4.12.0
- Mobile OS: Android 10

**Comment by ankar84** [comment] 2021-11-12 03:34
I guess it's a duplicate of my long term issue https://github.com/RocketChat/Rocket.Chat/issues/17844
@g-thome @sampaiodiego and it a prove that issue is here (not just me and my particular deployment)

**Comment by ankar84** [comment] 2021-11-12 05:20
Actually 4.1.2 looks better now. Maybe that issue is finally fixed.
In 4.1.0 user can't set `Mentions` to push notifications, I guess because of https://github.com/RocketChat/Rocket.Chat/pull/23487
But on 4.1.2 I set both desktop and mobile notifications to `Mentions` and test it.
![image](https://user-images.githubusercontent.com/4023037/141413754-e4cfe54a-d86d-4414-8880-6ea1bfac4bc1.png)
![image](https://user-images.githubusercontent.com/4023037/141413797-7f51a90c-1f91-423a-a6c3-9973aa4a0002.png)
![mentions](https://user-images.githubusercontent.com/4023037/141414012-da963f85-5160-4274-b31a-035c381c580a.gif)


One thing remain - I didn't test push notification itself, that planned on production server update to 4.x server version.

**Comment by fleaz** [comment] 2021-11-12 12:35
Nice to hear that there is progress reagarding this. Sadly I'm stuck with whatever version they give us because we use their hosted offering.

**Comment by hugocostadev** [comment] 2023-04-06 11:41
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Closed by hugocostadev** 2023-04-06 11:41 UTC
