### ISSUE TITLE
Cannot read property 'getUiText' of undefined

### ISSUE THREAD

**Issue by mlocati** [RocketChat/Rocket.Chat#11367] opened 2018-07-06 06:11 UTC
### Description:

Using a container with version 0.65.2 I was affected by #11079.
Now I fully reinstalled rocket.chat with a container having version 0.66: it worked for a few hours, but then it broke. It's a publicly visible setup (meaning that everybody can see channels), but the channel list is empty.
You can see it at http://rocketchat.locati.it.

Here's what I have in the browser console:
```
Exception in template helper: TypeError: Cannot read property 'getUiText' of undefined
    at e.noSubscriptionText (http://rocketchat.locati.it/0e5d9793a5021d02505478d7d091c6982c968da4.js?meteor_js_resource=true:437:60722)
    at http://rocketchat.locati.it/0e5d9793a5021d02505478d7d091c6982c968da4.js?meteor_js_resource=true:87:31314
    at http://rocketchat.locati.it/0e5d9793a5021d02505478d7d091c6982c968da4.js?meteor_js_resource=true:87:17160
    at http://rocketchat.locati.it/0e5d9793a5021d02505478d7d091c6982c968da4.js?meteor_js_resource=true:87:31947
    at Function.e._withTemplateInstanceFunc (http://rocketchat.locati.it/0e5d9793a5021d02505478d7d091c6982c968da4.js?meteor_js_resource=true:87:37671)
    at http://rocketchat.locati.it/0e5d9793a5021d02505478d7d091c6982c968da4.js?meteor_js_resource=true:87:31854
    at p.call (http://rocketchat.locati.it/0e5d9793a5021d02505478d7d091c6982c968da4.js?meteor_js_resource=true:147:1910)
    at p.mustacheImpl (http://rocketchat.locati.it/0e5d9793a5021d02505478d7d091c6982c968da4.js?meteor_js_resource=true:147:1182)
    at Object.p.mustache (http://rocketchat.locati.it/0e5d9793a5021d02505478d7d091c6982c968da4.js?meteor_js_resource=true:147:1241)
    at f.View._render (http://rocketchat.locati.it/0e5d9793a5021d02505478d7d091c6982c968da4.js?meteor_js_resource=true:437:30719)
```

### Steps to reproduce:

1.  Install with docker
```sh
docker run --name db -d mongo:3.0 --smallfiles
docker run --name rocketchat --link db -d -p 3000:3000 rocket.chat
```
2.  In my setup, rocket.chat is behind a nginx, which is configured like this:
```nginx
server {
    listen 80;
    listen [::]:80;
    server_name rocketchat.locati.it;
    access_log /path/to/rocketchat_nginx.access.log  main;
    error_log /path/to/rocketchat/rocketchat_nginx.error.log;
    location / {
        proxy_pass http://localhost:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }
}
```
3. allow unregistered users to read channels
4. wait a few hours

### Expected behavior:

rocket.chat should work.

### Actual behavior:

![immagine](https://user-images.githubusercontent.com/928116/42362529-0883a4de-80f4-11e8-85f9-fed83c1e7228.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66
- Operating System: docker
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by fais3000** [comment] 2018-08-03 09:57
Happening in 0.68.3 as well. Unable to login or create accounts. Form is not loading.

```Exception in template helper: TypeError: Cannot read property 'getUiText' of undefined
    at e.noSubscriptionText (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:4793234)
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2273040
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2258886
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2273673
    at Function.e._withTemplateInstanceFunc (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2279397)
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2273580
    at p.call (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2385253)
    at p.mustacheImpl (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2384525)
    at Object.p.mustache (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2384584)
    at f.View._render (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:4763028)
2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1 Exception in template helper: TypeError: Cannot read property 'getUiText' of undefined
    at e.noSubscriptionText (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:4793234)
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2273040
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2258886
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2273673
    at Function.e._withTemplateInstanceFunc (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2279397)
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2273580
    at p.call (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2385253)
    at p.mustacheImpl (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2384525)
    at Object.p.mustache (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2384584)
    at f.View._render (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:4763028)
2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1 Exception in template helper: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at n (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:3343052)
    at String.emojiList (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:3344952)
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2273040
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2258886
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2273673
    at Function.e._withTemplateInstanceFunc (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2279397)
    at https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2273580
    at p.call (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2385268)
    at p.mustacheImpl (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2384525)
    at Object.p.mustache (https://chat.talkwithstranger.com/2cfc727fdb8f3ced0d1a2eb501a97e615a9a68ff.js?meteor_js_resource=true:1:2384584)```

**Comment by winterstefan** [comment] 2018-12-10 07:49
Happening on `0.72.0` as well. Could there be some kind of workaround?

**Comment by winterstefan** [comment] 2019-02-21 09:45
**Any advice on this?**

To clarify the issue on _my_ side:
My goal is to be able to **fetch messages** from a certain room **without having a logged in user**. For this, I directly use the **Realtime API**.

The endpoint `loadHistory` only omits the authentication step if `Accounts_AllowAnonymousRead ` has been enabled (see [code](https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/loadHistory.js#L32)). But when doing so, the mentioned JS error appears: I'm not able to log in as admin in order to use the Rocket.Chat UI.

**So that's why I'm stuck**: Either I cannot read a room history (as anonymous) or the Rocket.Chat UI is broken. :-(

**Comment by MartinSchoeler** [comment] 2019-10-22 16:47
@mlocati @winterstefan @fais3000 Are you still having this issue on the latest releases? I could not reproduce this using the latest version. Thanks!

**Comment by mlocati** [comment] 2019-10-22 17:14
Sorry, I moved to another chat system because of this issue

**Comment by winterstefan** [comment] 2019-10-23 08:27
Thanks for reaching out @MartinSchoeler !

I'm running Rocket.Chat `1.3.0` right now. Testing anonymous read with this version, I _can confirm, that the mentioned use case now works_ for me.
I was able to open the Rocket.Chat UI, open e.g. the `#general` channel and read the existing messages.

👍

**Comment by MartinSchoeler** [comment] 2019-10-23 17:02
@winterstefan Awesome! Thanks for testing this out! I will close this issue then.

**Closed by MartinSchoeler** 2019-10-23 17:02 UTC
Labels: feat: anonymity / privacy, subj: ui/ux, type: bug
