### ISSUE TITLE
When the incoming notification is opened, the scroll of the message area goes to the top.

### ISSUE THREAD

**Issue by SkyVera** [RocketChat/Rocket.Chat#20189] opened 2021-01-13 10:06 UTC
### Description:
When a notification arrives or when clicking on the tray icon to read the incoming message, it scrolls to the middle or top of the screen instead of showing the last message.

### Steps to reproduce:

1. 
2. 
3. 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.3
- Operating System: Debian GNU/Linux 9 (stretch) Linux 4.9.0-14-amd64 x86-64
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 0
- NodeJS Version: v12.20.0
- MongoDB Version: v4.0.21

### Client Setup Information

- Desktop App or Browser Version: 3.1.1
- Operating System: Windows 10 x64

**Comment by ankar84** [comment] 2021-01-13 10:58
Could be duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1835

**Comment by SkyVera** [comment] 2021-01-13 14:30
Yes absolutely correct, I checked the list of current problems before but I overlooked.

That's why I'm closing this topic.

Thanks.

**Closed** 2021-01-13 14:31 UTC
