### ISSUE TITLE
Side Nav Bug : Big space between Side Nav and main-content v0.49.1

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5579] opened 2017-01-14 19:23 UTC
Your Rocket.Chat version: (0.50.0)
Today i catch this error in all browser 
![2017-01-14_211918](https://cloud.githubusercontent.com/assets/22897987/21957479/960b245a-da9f-11e6-8bb3-48454e2b363b.png)
i think this is in css ! any fix?

**Comment by engelgabriel** [comment] 2017-01-14 20:07
How can we replicate it? Do you have some custom CSS?

**Comment by Nemra1** [comment] 2017-01-14 20:42
yup but not contain .side-nav or .main-content class

**Comment by engelgabriel** [comment] 2017-01-14 21:14
We can only help if we see the server... as this is not happening in any other server.

**Comment by Nemra1** [comment] 2017-01-14 21:15
okey ..how i can give u My Data?

**Comment by engelgabriel** [comment] 2017-01-14 23:01
on the demo server

**Comment by Nemra1** [comment] 2017-01-14 23:08
Okey im come

**Comment by MartinSchoeler** [comment] 2017-01-16 13:08
Maybe related to #5225 ?

**Comment by engelgabriel** [comment] 2017-01-16 13:13
If this only happens on screen resize, this is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/5225

**Closed by engelgabriel** 2017-01-16 13:13 UTC
Labels: subj: ui/ux, type: bug
