### ISSUE TITLE
Upload two files at the same time and the file names get duplicated

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#9026] opened 2017-12-06 18:55 UTC
### Description:

When I upload two different files by drag and dropping them from Finder to the Rocket.Chat Electron App, both files get uploaded with the name of the first file.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.4
* Operating System: macOS High Sierra

### Steps to Reproduce:

1. Choose two files on Finder
2. Drag from finder onto Rocket.Chat Electron App
3. Drop on a room
4. Click Send on each of the file upload dialogs
5. Files get sent with equal names

![image](https://user-images.githubusercontent.com/1986378/33679554-359cfb86-daa6-11e7-91cd-f4a86fa0cb8d.png)

![image](https://user-images.githubusercontent.com/1986378/33679545-2fe25ee8-daa6-11e7-9282-434dd94386df.png)

**Comment by ledainam** [comment] 2017-12-07 06:47
+1 i have same issue with 0.59.3

**Comment by localguru** [comment] 2017-12-07 10:49
Might be duplicate of old and still unfixed bug #7291

**Comment by graywolf336** [comment] 2017-12-07 16:24
Closing as duplicate of: #7291

**Closed by graywolf336** 2017-12-07 16:24 UTC
