### ISSUE TITLE
Channel or username don't create links when followed by a period

### ISSUE THREAD

**Issue by maiki** [RocketChat/Rocket.Chat#7083] opened 2017-05-24 21:09 UTC
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.8.1

When I type a channel or username mid-sentence it links to the respective object, but if it is at the end of a sentence followed immediately by a period, it doesn't link. It works with commas and question marks, but not periods.

![rc-linking](https://cloud.githubusercontent.com/assets/74557/26425429/934f18e8-4089-11e7-96f8-8648528567db.png)

Expected behavior is for the links to work when ending with a period.

This is the same behavior on the demo instance. I tried looking for an existing issue but came up blank, so let me know if there is one.

**Comment by MartinSchoeler** [comment] 2017-05-25 12:41
duplicate of #956

**Closed by MartinSchoeler** 2017-05-25 12:41 UTC
