### ISSUE TITLE
MongoTimeoutError: Server selection Docker >3.0.12 in some cases 

### ISSUE THREAD

**Issue by hexeth** [RocketChat/Rocket.Chat#17350] opened 2020-04-17 19:30 UTC
### Description:

Docker versions of rocket.chat greater than 3.0.12 can produce a server selection timeout due to an inadequate timeout in `topology.js` on some hardware setups. 

### Steps to reproduce:

1. docker-compose pull latest images
2. docker-compose up

This issue occurs only on specific hardware regardless of fresh install, or existing setup: 

### Expected behavior:

Application should start, but instead throws `MongoTimeoutError: Server selection timed out after 10000 ms`

### Server Setup Information:

- Version of Rocket.Chat Server: any version above 3.0.12
- Virtual Machine Config:
-- Hyper-V
-- Memory: 4096mb
-- CPU: 1 vCPU
- Operating System: 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.18

### Additional context

**WORKAROUND**: Enter rocketchat container, change `serverSelectionTimeoutMS` to `10500` and rocketchat will start as expected.

### Relevant logs:

```
rocketchat_1          | /app/bundle/programs/server/node_modules/fibers/future.js:313
rocketchat_1          |                                                 throw(ex);
rocketchat_1          |                                                 ^
rocketchat_1          |
rocketchat_1          | MongoTimeoutError: Server selection timed out after 10000 ms
rocketchat_1          |     at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
rocketchat_1          |     at listOnTimeout (internal/timers.js:549:17)
rocketchat_1          |     at processTimers (internal/timers.js:492:7) {
rocketchat_1          |   name: 'MongoTimeoutError',
rocketchat_1          |   [Symbol(mongoErrorContextSymbol)]: {}
rocketchat_1          | }
rocketchat_1          | Tried 5 times. Waiting 5 secs...
```

**Comment by cutzenfriend** [comment] 2020-04-18 14:52
How can i exec into the container if it is restarting everytime...

**Comment by hexeth** [comment] 2020-04-18 15:01
The container won't restart as 'node main.js' is attempted 30 times in the default compose

**Comment by cutzenfriend** [comment] 2020-04-18 15:04
okay how can i change the file on a stopped container?

**Comment by hexeth** [comment] 2020-04-18 15:10
You run the image, make the changes while it is running and commit them to
a new image

**Comment by cutzenfriend** [comment] 2020-04-18 15:24
Mine does restart every 5 seconds or so.

**Comment by hexeth** [comment] 2020-04-18 15:29
You are not using a recent docker-compose provided by rocketchat if that is happening. Your container is likely only running `node main.js` command, it fails and then restarts, which would be every 10 seconds. The compose is here:

```
curl -L https://raw.githubusercontent.com/RocketChat/Rocket.Chat/develop/docker-compose.yml -o docker-compose.yml
```

and contains this command on the rocketchat service, which is what will keep the container running for 30 retries:
```   
 command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
```

As long as you are using the docker-compose mentioned above, the following steps would commit the increased timeout to a new container: 

1. `docker-compose up -d`
2. `docker exec --user="root" -it rocketchat_rocketchat_1 /bin/bash`
3. `apt-get update && apt-get install nano`
4. `nano /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sdam/topology.js`
5. find `serverSelectionTimeoutMS` and modify value to be higher. 10500 worked for me, but you could make it 20000 to be safe. Save and exit.
6. `exit` container
7. `docker commit rocketchat_rocketchat_1 rocketchat_new`

**Comment by cutzenfriend** [comment] 2020-04-18 15:35
Okay somehow my container has no access to the internet?

**Comment by cutzenfriend** [comment] 2020-04-18 15:48
Okay get the issue even with 20000ms

`rocketchat_1  | MongoTimeoutError: Server selection timed out after 20000 ms
rocketchat_1  |     at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/sdam/topology.js:773:16)
rocketchat_1  |     at listOnTimeout (internal/timers.js:549:17)
rocketchat_1  |     at processTimers (internal/timers.js:492:7) {
rocketchat_1  |   name: 'MongoTimeoutError',
rocketchat_1  |   [Symbol(mongoErrorContextSymbol)]: {}
rocketchat_1  | }
rocketchat_1  | Tried 9 times. Waiting 5 secs...`

**Comment by hexeth** [comment] 2020-04-18 16:10
You are having an issue unrelated to this bug report

**Comment by sampaiodiego** [comment] 2020-04-22 21:53
can you please testing adding the following environment variable instead of manually editing the file:

```
MONGO_OPTIONS='{ "serverSelectionTimeoutMS": 30000 }'

**Comment by hexeth** [comment] 2020-04-22 22:11
> can you please testing adding the following environment variable instead of manually editing the file:
> 
> ```
> MONGO_OPTIONS='{ "serverSelectionTimeoutMS": 30000 }'
> ```

I am admittedly shoddy at escaping quotes, so using the above option in the same format as the original docker compose as below results in an error.

```
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MONGO_OPTIONS='{ "serverSelectionTimeoutMS": 30000 }'
```

```
 The Compose file './docker-compose.yml' is invalid because:
services.rocketchat.environment contains {"MONGO_OPTIONS='{ \"serverSelectionTimeoutMS\"": "30000 }'"}, which is an invalid type, it should be a string
```

If I switch my compose to the below settings everything will start up

```
    environment:
      PORT: 3000
      ROOT_URL: http://localhost:3000
      MONGO_URL: mongodb://mongo:27017/rocketchat
      MONGO_OPLOG_URL: mongodb://mongo:27017/local
      MONGO_OPTIONS: '{ "serverSelectionTimeoutMS": 30000 }'
```

Removing the environment variable will go back to the same error as expected. This is definitely a better workaround

**Comment by sampaiodiego** [comment] 2020-04-23 13:50
> I am admittedly shoddy at escaping quotes, so using the above option in the same format as the original docker compose as below results in an error.

haha.. that's always a pain =P

thanks for testing it out.. I'd say that's actually the solution.. there is not much to do with Rocket.Chat, the issue is communication between rocket.chat and mongodb nodes.. I'll add this info as the solution in our docs and close the issue 👍

**Closed** 2020-05-13 18:47 UTC
