### ISSUE TITLE
2.4.2 : no message send

### ISSUE THREAD

**Issue by Sicoval31** [RocketChat/Rocket.Chat#16287] opened 2020-01-20 09:00 UTC
since new version autoupdate with snap package : no message can be send.
a part of the error message in the log section : 
server.js:204 System ➔ error Error sending message: Error: You are not authorized to change message properties     at validateUserIdentity (app/lib/server/functions/sendMessage.js:164:9)     at sendMessage (app/lib/server/functions/sendMessage.js:175:3)     at executeSendMessage (app/lib/server/methods/sendMessage.js:76:10)     at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:104:10)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by tuxmartin** [comment] 2020-01-20 09:22
I have the same problem.

Rocket.Chat SNAP. Version 2.4.2. App engine version 1.11.0. Debian 10.

**Comment by Sicoval31** [comment] 2020-01-20 09:30
The rocketchat-server.rocketchat-caddy is always inactive (but enable).
even after restart it by the command:  snap start rocketchat-server.rocketchat-caddy

**Comment by lewisf2001uk** [comment] 2020-01-20 09:33
Temporary workaround below
In the admin message settings (/admin/Message).
Turn off "Set a User Name to Alias in Message"
![image](https://user-images.githubusercontent.com/11738262/72715164-e2be1600-3b67-11ea-9287-6eba604a9dfe.png)

**Comment by tuxmartin** [comment] 2020-01-20 09:36
@lewisf2001uk thank you!

**Comment by AmShaegar13** [comment] 2020-01-20 09:47
See #16097

**Comment by krecik82** [comment] 2020-01-22 14:01
Hi.
We do have the same error, but on 2.4.0 version and when trying to add new poll. On client there is feedback: "An error occured when trying to send the gif " and in logs:

I20200122-14:43:18.881(1) server.js:204 System ➔ error Error sending message: 
Error: You are not authorized to change message properties     
at validateUserIdentity (app/lib/server/functions/sendMessage.js:164:9)     
at sendMessage (app/lib/server/functions/sendMessage.js:174:2)     
at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:86:11)     
at MethodInvocation.methodsMap.(anonymous function) (app/lib/server/lib/debug.js:67:34)     
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     
at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1689:15)     
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     
at resolve (packages/ddp-server/livedata_server.js:1687:36)     
at new Promise (<anonymous>)     
at Server.applyAsync (packages/ddp-server/livedata_server.js:1686:12)     
at Server.apply (packages/ddp-server/livedata_server.js:1625:26)     
at Server.call (packages/ddp-server/livedata_server.js:1607:17)     
at DDPCommon.MethodInvocation.Meteor.runAsUser (app/apps/server/bridges/messages.js:19:17)     
at packages/dispatch_run-as-user.js:211:14     
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     
at Object.Meteor.runAsUser (packages/dispatch_run-as-user.js:210:33)     
at Promise.asyncApply (app/apps/server/bridges/messages.js:18:10)     
at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 

Do you have any propositions or should we create completly new incident?

**Comment by krecik82** [comment] 2020-01-22 14:11
forgot to mention, that proposed parameter is disabled in our case. OS: Centos 7.7.

**Comment by ggazzo** [comment] 2020-01-27 11:37
I'm quite sure your problem is because we changed how the alias usage works, now only `bot` role can set the alias...

**Comment by sampaiodiego** [comment] 2020-01-28 21:25
closing as duplicate of https://github.com/RocketChat/Rocket.Chat/issues/16097

**Closed** 2020-01-29 18:05 UTC
