### ISSUE TITLE
Auto update fails across multiple versions

### ISSUE THREAD

**Issue by bsthinker** [RocketChat/Rocket.Chat#23147] opened 2021-09-08 16:00 UTC
This is a duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670.  Where is the link to manually download the  client

**Comment by apaarfus** [comment] 2021-09-08 19:26
The desktop client is available on the [Releases page of the Rocket.Chat.Electron repository](https://github.com/RocketChat/Rocket.Chat.Electron/releases) -- this is the server-side repository.

**Comment by ankar84** [comment] 2021-09-09 09:34
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670 so I'm closing that issue in favor of old one.
You always can download latest desktop release here - https://github.com/RocketChat/Rocket.Chat.Electron/releases/latest

**Closed by ankar84** 2021-09-09 09:34 UTC
