### ISSUE TITLE
Rocket Chat not Sync LDAP

### ISSUE THREAD

**Issue by kungaorn** [RocketChat/Rocket.Chat#12162] opened 2018-09-26 05:01 UTC
Connection.error connection { Error: read ECONNRESET     at _errnoException (util.js:1024:11)     at TCP.onread (net.js:615:25)  code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by piotrkochan** [comment] 2018-09-26 05:44
This may be your network issue, check that ldap is reachable from your RocketChat server

**Comment by reetp** [comment] 2018-09-26 14:44
Possibly a duplicate of #9276 but as the OP hasn't bothered to provide any real background information it is hard to tell.

If the OP wants anyone to look at this then they need to follow the bug reporting template found here: 
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

(Note the OP has asked about this on the https://open.rocket.chat/channel/support and been equally as elusive in supplying any sensible information)

They should also check the logs on their LDAP server and firewall to see what is going on there as well.

**Comment by kungaorn** [comment] 2018-09-27 02:05
OK I can sync account but cannot sync password
[34mI20180927-05:49:08.277(7) rocketchat_logger rocketchat_logger.js:278 [31mLDAPHandler ➔ error Error: User not in a valid group     at MethodInvocation.<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:654:15)     at /opt/Rocket.Chat/programs/server/packages/accounts-base.js:876:30     at tryLoginMethod (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:702:14)     at AccountsServer.Ap._runLoginHandlers (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:875:18)     at AccountsServer.Accounts._runLoginHandlers (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:3335:36)     at MethodInvocation.methods.login (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:933:27)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:875:23)     at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85
[34mI20180927-05:49:08.277(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAPHandler ➔ info Fallback to default account system { username: 'adsynctrust' }
[34mI20180927-05:49:18.160(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAPHandler ➔ info Init LDAP login adsynctrust@tks.co.th
[34mI20180927-05:49:18.161(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.info Init setup
[34mI20180927-05:49:18.162(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.info Connecting ldap://10.6.5.41,10.6.5.42:389
[34mI20180927-05:49:18.163(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.debug connectionOptions { url: 'ldap://10.6.5.41,10.6.5.42:389',   timeout: 6000,   connectTimeout: 1000,   idleTimeout: 10000,   reconnect: true,   log:     Logger {      domain: null,      _events: {},      _eventsCount: 0,      _maxListeners: undefined,      _level: 20,      streams: [ [Object] ],      serializers: null,      src: false,      fields:        { name: 'ldapjs',         component: 'client',         hostname: 'RocketChat',         pid: 13120 } } }
[34mI20180927-05:49:18.266(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.info LDAP connected
[34mI20180927-05:49:18.267(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Bind.info Binding UserDN CN=Adsynctrust,OU=Application Users,DC=tks,DC=co,DC=th
[34mI20180927-05:49:18.270(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.info Searching user adsynctrust@tks.co.th
[34mI20180927-05:49:18.271(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.debug searchOptions { filter: '(&(objectcategory=Person)(sAMAccountName=adsynctrust@tks.co.th))',   scope: 'sub',   sizeLimit: 1000,   paged: { pageSize: 250, pagePause: false } }
[34mI20180927-05:49:18.272(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.debug BaseDN DC=tks,DC=co,DC=th
[34mI20180927-05:49:18.276(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.info Search result count 0
[34mI20180927-05:49:18.277(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAPHandler ➔ info Search returned 0 record(s) for adsynctrust@tks.co.th
[34mI20180927-05:49:18.278(7) rocketchat_logger rocketchat_logger.js:278 [31mLDAPHandler ➔ error Error: User not Found     at MethodInvocation.<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_ldap.js:647:13)     at /opt/Rocket.Chat/programs/server/packages/accounts-base.js:876:30     at tryLoginMethod (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:702:14)     at AccountsServer.Ap._runLoginHandlers (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:875:18)     at AccountsServer.Accounts._runLoginHandlers (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:3335:36)     at MethodInvocation.methods.login (/opt/Rocket.Chat/programs/server/packages/accounts-base.js:933:27)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:875:23)     at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85
[34mI20180927-05:49:18.278(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAPHandler ➔ info Fallback to default account system { email: 'adsynctrust@tks.co.th' }
[34mI20180927-05:49:18.280(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.info Idle
[34mI20180927-05:49:18.280(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.info Disconecting
[34mI20180927-05:49:18.287(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.info Closed
[34mI20180927-05:49:28.275(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.info Idle
[34mI20180927-05:49:28.276(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Connection.info Disconecting
[34mI20180927-05:49:28.278(7) rocketchat_logger rocketchat_logger.js:278 [34mLDAP ➔ Search.info Closed
[34mI20180927-05:52:27.653(7) rocketchat_logger rocketchat_logger.js:278 [34mMeteor ➔ publish null -> userId: null , arguments:  []
[34mI20180927-05:52:27.654(7) rocketchat_logger rocketchat_logger.js:278 [34mMeteor ➔ method public-settings/get -> userId: null , arguments:  []
[34mI20180927-05:52:27.656(7) rocketchat_logger rocketchat_logger.js:278 [34mMeteor ➔ publish meteor_autoupdate_clientVersions -> userId: null , arguments:  []
[34mI20180927-05:52:28.009(7) rocketchat_logger rocketchat_logger.js:278 [34mMeteor ➔ method public-settings/get -> userId: null , arguments:  [ 2018-09-27T02:03:50.430Z ]

[cid:image001.png@01D2457B.9F820D00]
[LineFooter7]
[LineFooter7]




Prism Solutions Co., Ltd.
+66 2784 5888 ext. 8112
kunagorn.g@prism.co.th<mailto:kunagorn.g@prism.co.th>
www.prism.co.th<http://www.prism.co.th/>

**Comment by kungaorn** [comment] 2018-09-27 11:30
Dear John
            I can synced users and password but next step I want to sync in child domain user and domain users in forest trust.
Rocket Chat can do it ? and please tell me for how to.

[cid:image001.png@01D2457B.9F820D00]
[LineFooter7]
[LineFooter7]




Prism Solutions Co., Ltd.
+66 2784 5888 ext. 8112
kunagorn.g@prism.co.th<mailto:kunagorn.g@prism.co.th>
www.prism.co.th<http://www.prism.co.th/>

**Comment by reetp** [comment] 2018-10-15 15:41
I think this is a support issue rather than a bug (or possibly a NFR)

Please open a thread in the forums:

https://forums.rocket.chat/

**Comment by reetp** [comment] 2018-10-15 15:42
@rocket-cat close

**Closed by reetp** 2018-10-15 15:42 UTC
