### ISSUE TITLE
[Bug] No API access for first user 

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#8769] opened 2017-11-03 13:01 UTC
### Description:

The user who registers first is becoming Rocket.Chat admin. The user is thereby able to use the Rocket.Chat API to configure the system.

### Expected behavior:

The user is able to perform a `/login` via the API and can start using all API operations.

### Actual behavior:

The user (admin) gets the following response when performing `/login`

```
{
    "status": "error",
    "message": "Unauthorized"
}
```

Hence the user is not able to login via API. Logging in via the web interface is possible (setting all admin options is possible as well).

I found a work-around: 
Adding an additional user with the roles `user`, `bot` and `admin` and trying to use the API with this user, works fine. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.2
* Operating System: linux
* Node Version: v4.5.0

### Steps to Reproduce:

1. Set Up a new server
2. Register a user (lets call the user "A")
3. Test that API is working by performing `/info`
4. Try to `/login` with A => failure
5. Add new user (call "B") via web interface with user A. Make B an admin
6. Try to `/login` with B => success

**Comment by MartinSchoeler** [comment] 2017-11-03 13:31
When the first user is created he receives the `admin` role only, could be that the `user` role might be needed to use the `login` api method

**Comment by graywolf336** [comment] 2017-11-04 07:00
This throws a loop into the people who use the `users.register` and expect the returned information to be the first admin for an automated system. :thinking: I will look into this.

@janrudolph are you registering the first user via the web interface or the rest api?

**Comment by janrudolph** [comment] 2017-11-05 06:10
Via Web Interface

**Comment by janrudolph** [comment] 2018-03-07 07:08
@graywolf336 I think that I was able to find the root of the problem. 

This error occurs, if the password contains a backslash. In this case I get the response `bad request`.

**Comment by MarcosSpessatto** [comment] 2018-04-04 16:27
@janrudolph How are you doing the call to the endpoint? Because I tried to simulate the error that you reported, and I could not . You are sending by form-data or json?

**Comment by janrudolph** [comment] 2018-04-06 06:05
@MarcosSpessatto I used Postman to test the API

<img width="470" alt="postman-rc-login" src="https://user-images.githubusercontent.com/3596824/38405658-37bf3742-3971-11e8-9a33-b1cff819a73d.png">

**Comment by MarcosSpessatto** [comment] 2018-04-17 18:44
@janrudolph, I have tested here with all the cases you have told and they are working properly. The only thing I found and maybe could be an error is the backslash you reported, if it is not escaped. Just to make sure, are you escaping the backslash on password?

**Comment by graywolf336** [comment] 2018-04-18 03:30
I was able to reproduce this with Postman. Due to the login using json, if you have a string which contains a backslash then you will need to escape the backslash with another backslash.

Going to go ahead and close this.

**Closed by graywolf336** 2018-04-18 03:30 UTC
Labels: feat: api, feat: roles / permissions, type: bug
