### ISSUE TITLE
Attached Files Are Missing When A MongoDB Restore Is Performed

### ISSUE THREAD

**Issue by ml48603** [RocketChat/Rocket.Chat#7421] opened 2017-07-05 18:51 UTC
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: SANPS Build 671

For some reason the files contained in the MongoDB (GridFS file upload setting) that RC uses are not being restored after the RocketChat Server has been backed up.  What causes this?  How do I fix this behavior?

**Comment by TheReal1604** [comment] 2017-07-06 11:04
@ml48603 can you give us more information about the restore / Backup method used?

**Comment by ml48603** [comment] 2017-07-06 15:02
RC=RocketChat

I followed the procedure published in the RC online docs for backup after having uninstalled SNAPS with RC and reinstalling after experiencing RC server crash with attempted automatic update to Build 0.56.0 SNAPS Build 801.
1) # snap run rocketchat-server.backupdb
2) # cd /
3) # tar -zxvf /mnt/nfs/Backup-RocketChat/backup.tar.gz
Files are stored in /var/snap/rocketchat-server/671/dump/parties/
4) Verify DB name with
# /snap/rocketchat-server/current/bin/mongo
MongoDB shell version: 3.2.7
parties  0.002GB
5) Restore MongoDB
# /snap/rocketchat-server/current/bin/mongorestore --db parties /var/snap/rocketchat-server/671/dump/parties/
6) Restart Servers
# service snap.rocketchat-server.rocketchat-mongo  restart
# service snap.rocketchat-server.rocketchat-server restart

RC Linux Desktop Client rocketchat-desktop_2.7.0_amd64.deb running on Ubuntu Desktop 16.04.2 LTS  was not displaying any of the attached files during the 9 hours it was in use.  The desktop app had been manually stopped and restarted by the user with Ubuntu xkill frequently throughout the day along with Login and Logouts as Administrative settings were reconfigured throughout the period:  Administrative settings were not recovered by the backup.  The MongoDB and RC servers were stopped and started after Administrative settings were changed throughout the day. (Order Stop RC, Stop MongoDB, Start MongoDB, Start RC)

After the PC was shutdown I moved to the Android tablet for the evening and found all attached pics were visible from the RC android app.  The next morning attached files were found to be visible in the RC Desktop app.

It appears attached files under the GridFS upload method have been restored from the backup.  For some reason the Desktop app would not display them or download them.

Why does the Android app RC and RC+ not download attached file when download is selected?  Android 6 throws toast error message Can't write file.  What needs to be changed to allow the opening of files downloaded from RC?

**Comment by geekgonecrazy** [comment] 2017-07-14 16:47
Make sure you stop the rocket.chat server prior to doing an import.  This likely has some barring on it.  Just updated the document to add that missing step.

**Comment by geekgonecrazy** [comment] 2017-07-23 01:43
Please feel free to stop by [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap) on our community server if you would like to dig into this further.  Going ahead and closing this issue as its support related and not a bug or feature request.

**Closed by geekgonecrazy** 2017-07-23 01:43 UTC
Labels: deploy: snaps, feat: file sharing, type: support
