### ISSUE TITLE
Nested quotes show some Markdown code

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#28853] opened 2023-04-09 16:20 UTC
### Description:

Under certain circumstances, creating nested quotes unexpectedly show some Markdown code.

This only happens while composing a message. After submitting the message, everything looks as expected.

### Steps to reproduce:

1. Write a message.
2. Write another message quoting the one from step 1.
3. Write another message quoting the one from step 2.
4. Click on the symbol for quoting the message from step 3, but do not submit anything yet.

### Expected behavior:

![image](https://user-images.githubusercontent.com/404840/230784144-fbc95aed-99f9-4265-838d-acafb91f17ae.png)

### Actual behavior:

The message from step 2 is shown with some Markdown code:

![image](https://user-images.githubusercontent.com/404840/230784171-63a94908-7ea8-472e-999b-4fe44595312d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.1.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 6.0.5

### Client Setup Information

- Browser Version:
  - Chromium Version 112.0.5615.49 (Offizieller Build) Arch Linux (64-Bit)
  - Firefox 111.0.1 (64-bit)
- Operating System: Arch Linux

**Comment by hugocostadev** [comment] 2023-04-10 12:58
Hi there, thanks for raising this issue.

I tested here and I could not reproduce, can you check the `develop` branch, please? 

![image](https://user-images.githubusercontent.com/20212776/230905460-77d164f3-9747-4f6b-be74-09ac87d4d4da.png)

Maybe this was fixed in this PR: https://github.com/RocketChat/Rocket.Chat/pull/28579

please, let me know if this still happens

**Comment by jayesh-jain252** [comment] 2023-04-10 18:28
@paulchen and @hugocostadev, this was fixed in the PR: #28443

**Closed** 2023-04-10 18:46 UTC
Labels: type: bug, stat: waiting response

**Comment by paulchen** [comment] 2023-04-10 20:09
@jayesh-jain252 @hugocostadev Great, thanks!
