### ISSUE TITLE
Cannot run dev mode in 5.0.0 nor build and run

### ISSUE THREAD

**Issue by Cristian-Estevez** [RocketChat/Rocket.Chat#26444] opened 2022-08-02 14:34 UTC
### Description:
Hi, Im trying to customize RC version 5.0.0
So I got the source code from [here](https://github.com/RocketChat/Rocket.Chat/releases/tag/5.0.0).
And followed the instructions for development found [here](https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/linux).
When I run the app with the command “meteor yarn dev” its logs seem fine, just as when I did with previous versions. But when I try to access to the app with the browser I can only see a gray screen.
I also tried building the app and then running it with docker-compose and the same happens.
Is there a fix for this issue? Is there any additional step for developing with the new version?

### Steps to reproduce:

1. Download source code [release page](https://github.com/RocketChat/Rocket.Chat/releases/tag/5.0.0)
2. Follow instructions in  [RC dev docs](https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/linux)
3. Open in browser localhost:3000

### Expected behavior:

Being able to see the chat interact and customize it from source code.

### Actual behavior:

Get a gray screen and nothing else.
The app runs as for the logs displaying ok.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.0
- Operating System: Ubuntu 22.04.1 LTS
- Deployment Method: Development "yarn dev"
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.3 - x64
- MongoDB Version: 4.4.15

### Client Setup Information

- Desktop App or Browser Version: 
- Operating System: windows and linux

### Relevant logs:

Server logs are fine.

Browser console logs:

> 5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1124 Error: Cannot find module '../components/message/Attachments/providers/AttachmentProvider'
    at y (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:3:638)
    at d.resolve (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:3:3521)
    at d.a [as link] (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:5:5394)
    at module (/client/providers/MeteorProvider.tsx:1:107)
    at 5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1301:764
    at g (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:3:1094)
    at d.n [as require] (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:3:3652)
    at d.a [as link] (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:5:5473)
    at h (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1301:2055)
    at 5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1301:881
Ti @ 5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1124
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1142 Uncaught Error: Cannot find module '../components/message/Attachments/providers/AttachmentProvider'
    at y (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:3:638)
    at d.resolve (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:3:3521)
    at d.a [as link] (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:5:5394)
    at module (/client/providers/MeteorProvider.tsx:1:107)
    at 5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1301:764
    at g (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:3:1094)
    at d.n [as require] (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:3:3652)
    at d.a [as link] (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:5:5473)
    at h (5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1301:2055)
    at 5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1301:881
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
1134-190-229-210-9.sa.ngrok.io/api/v1/emoji-custom.list:1          Failed to load resource: the server responded with a status of 401 ()
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Error getting custom emoji Response
(anonymous) @ 5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
1134-190-229-210-9.sa.ngrok.io/api/v1/commands.list:1          Failed to load resource: the server responded with a status of 401 ()
home:1 Uncaught (in promise) Responsebody: (...)bodyUsed: falseheaders: Headers {}ok: falseredirected: falsestatus: 401statusText: ""type: "basic"url: "https://1134-190-229-210-9.sa.ngrok.io/api/v1/commands.list"[[Prototype]]: Response
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
1134-190-229-210-9.sa.ngrok.io/api/v1/banners?platform=web:1          Failed to load resource: the server responded with a status of 401 ()
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) Response
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1433 Uncaught (in promise) undefined
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) undefined
1134-190-229-210-9.sa.ngrok.io/api/v1/roles.list:1          Failed to load resource: the server responded with a status of 401 ()
5dce582f134b8e530c748fbc326889c1d09cc3e1.js?meteor_js_resource=true:1558 Uncaught (in promise) Response

**Comment by dudanogueira** [comment] 2022-08-02 17:23
Hi!

This is not a bug, so closing.

For help on how to spin up a development environment, please consider the following channels:

https://open.rocket.chat/channel/how-to-get-started
and
https://open.rocket.chat/channel/dev

**Closed by dudanogueira** 2022-08-02 17:23 UTC

**Comment by bl00mber** [comment] 2022-08-06 05:10
@dudanogueira there is absolutely nothing on the links you attached
