### ISSUE TITLE
I can't access the login form

### ISSUE THREAD

**Issue by KheireddineAzzez** [RocketChat/Rocket.Chat#22612] opened 2021-07-07 22:44 UTC
### Description:

The login form cannot be opened
### Steps to reproduce:

1.  Go to (localhost:3000)
2. click on(Sign in to start talking):
![Capture2](https://user-images.githubusercontent.com/59838139/124837538-ebcdbd80-df7c-11eb-81f3-3fab3b538abb.PNG)
3.

### Expected behavior:

The login form would be opened
### Actual behavior:

The login form cannot be opened

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15
- Operating System: **Ubuntu**
- Deployment Method: **local(meteor npm start)**
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: **14.17.0**
- MongoDB Version: **3.6.0**

### Client Setup Information

- Desktop App or Browser Version: **Browser Version**
- Operating System:

### Relevant logs:
![Capture](https://user-images.githubusercontent.com/59838139/124837168-3dc21380-df7c-11eb-9847-5006c0614709.PNG)

**Comment by johncrisp** [comment] 2021-07-08 11:29
Hi,

Have you modified the course code in anyway?

For support you need to ask in the forums https://forums.rocket.chat or https://open/rocket.chat #support

**Comment by KheireddineAzzez** [comment] 2021-07-08 11:31
No

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KheireddineAzzez** [comment] 2021-07-09 19:10
> Hi,
> 
> Have you modified the course code in anyway?
> 
> For support you need to ask in the forums https://forums.rocket.chat or https://open/rocket.chat #support

Do you know what the problem is?

**Comment by KheireddineAzzez** [comment] 2021-07-09 22:45
> Hi,
> 
> Have you modified the course code in anyway?
> 
> For support you need to ask in the forums https://forums.rocket.chat or https://open/rocket.chat #support

D20210709-23:44:38.380(1) (http.js:255) The http package has been deprecated, please migrate to the fetch package and new web standards.

**Comment by johncrisp** [comment] 2021-07-12 09:27
Kheireddine,

github is for bugs, not support requests.

You say the login form cannot be opened, but you are logged in.

I suspect this is a configuration issue and not a bug - check your root/server url.

Please ask your well documented question in the forums or on open as per the links above.

Have a read of this as well:

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98

I am closing this for now - if we see that there is a bug we can re-open later.

**Closed by johncrisp** 2021-07-12 09:27 UTC
