### ISSUE TITLE
language selection makes firefox unresponsive

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#941] opened 2015-09-30 15:08 UTC
in My Account -> Profile, there's a language selection menu. Clicking the rightmost bit, on the arrow, I would expect a list to appear, but instead my firefox gets 100% cpu and needs a hard kill.

**Comment by sinteur** [comment] 2015-09-30 15:41
Application Basics
------------------

Name: Firefox
Version: 40.0.3
Build ID: 20150826023504
Update Channel: release
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0
Multiprocess Windows: 0/3 (default: false)

Crash Reports for the Last 3 Days
---------------------------------

All Crash Reports

Extensions
----------

Name: Adblock Plus
Version: 2.6.11
Enabled: true
ID: {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}

Name: AdDetector
Version: 0.19
Enabled: true
ID: 19b15b40-23f9-11e4-8c21-0800200c9a66@jetpack

Name: FacebookBlocker
Version: 1.2.1
Enabled: true
ID: facebookBlocker@webgraph.com

Name: Firebug
Version: 2.0.12
Enabled: true
ID: firebug@software.joehewitt.com

Name: Flashblock
Version: 1.5.18.1-signed
Enabled: true
ID: {3d7eb24f-2740-49df-8937-200b1cc08f8a}

Name: Ghostery
Version: 5.4.8.1
Enabled: true
ID: firefox@ghostery.com

Name: Moderator toolbox for reddit
Version: 3.2.1
Enabled: true
ID: yes@jetpack

Name: Tab Mix Plus
Version: 0.4.1.9
Enabled: true
ID: {dc572301-7619-498c-a57d-39143191b318}

Name: TinEye Reverse Image Search
Version: 1.2.1
Enabled: true
ID: tineye@ideeinc.com

Name: User Agent Switcher
Version: 0.7.3.1-signed
Enabled: true
ID: {e968fc70-8f95-4ab9-9e79-304de2a71ee1}

Name: ADB Helper
Version: 0.8.0
Enabled: false
ID: adbhelper@mozilla.org

Name: HTTP UserAgent cleaner
Version: 0.6.0.6.1-signed
Enabled: false
ID: HTTPUserAgentcleaner@addons.8vs.ru

Name: Live HTTP headers
Version: 0.17.1-signed
Enabled: false
ID: {8f8fe09b-0bd3-4470-bc1b-8cad42b8203a}

Name: Privacy Badger
Version: 1.0.2
Enabled: false
ID: jid1-MnnxcxisBPnSXQ-eff@jetpack

Name: Reddit Enhancement Suite
Version: 4.1.2
Enabled: false
ID: jid1-xUfzOsOFlzSOXg@jetpack

Graphics
--------

Asynchronous Pan/Zoom: none
Device ID: 0x a26
GPU Accelerated Windows: 3/3 OpenGL (OMTC)
Supports Hardware H264 Decoding: false
Vendor ID: 0x8086
WebGL Renderer: Intel Inc. -- Intel HD Graphics 5000 OpenGL Engine
windowLayerManagerRemote: true
AzureCanvasBackend: skia
AzureContentBackend: quartz
AzureFallbackCanvasBackend: none
AzureSkiaAccelerated: 0

Important Modified Preferences
------------------------------

accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.smart_size_cached_value: 358400
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 4
browser.cache.memory.enable: false
browser.download.folderList: 2
browser.download.importedFromSqlite: true
browser.download.manager.closeWhenDone: true
browser.download.manager.showWhenStarting: false
browser.history_expire_days_min: 10
browser.history_expire_days.mirror: 180
browser.link.open_newwindow.override.external: 2
browser.places.createdDefaultQueries: true
browser.places.createdSmartBookmarks: true
browser.places.importBookmarksHTML: false
browser.places.importDefaults: false
browser.places.leftPaneFolderId: 316
browser.places.migratePostDataAnnotations: false
browser.places.smartBookmarksVersion: 7
browser.places.updateRecentTagsUri: false
browser.search.suggest.enabled: false
browser.search.update: false
browser.search.useDBForOrder: true
browser.sessionstore.restore_on_demand: false
browser.sessionstore.resume_from_crash: false
browser.sessionstore.upgradeBackup.latestBuildID: 20150826023504
browser.startup.homepage: about:blank
browser.startup.homepage_override.buildID: 20150826023504
browser.startup.homepage_override.mstone: 40.0.3
browser.tabs.onTop: false
browser.tabs.warnOnOpen: false
dom.apps.reset-permissions: true
dom.mozApps.used: true
dom.w3c_touch_events.expose: false
extensions.lastAppVersion: 40.0.3
font.internaluseonly.changed: true
gfx.blacklist.direct2d: 3
media.gmp-gmpopenh264.enabled: false
media.gmp-gmpopenh264.lastUpdate: 1433186988
media.gmp-gmpopenh264.version: 1.4
media.gmp-manager.buildID: 20150826023504
media.gmp-manager.lastCheck: 1443605374
media.webrtc.debug.aec_log_dir: /tmp/
media.webrtc.debug.log_file: /tmp/WebRTC.log
network.auth.allow-subresource-auth: 2
network.cookie.cookieBehavior: 1
network.cookie.prefsMigrated: true
network.http.pipelining: true
network.predictor.cleaned-up: true
places.database.lastMaintenance: 1443442542
places.history.expiration.transient_current_max_pages: 89077
places.history.expiration.transient_optimal_database_size: 161061272
places.last_vacuum: 1300035624
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
plugin.state.adobeaamdetect: 0
plugin.state.default browser: 0
plugin.state.sharepointbrowserplugin: 0
plugin.state.silverlight: 0
print.print_bgcolor: true
print.print_bgimages: true
print.print_colorspace:
print.print_command:
print.print_downloadfonts: true
print.print_duplex: 0
print.print_evenpages: true
print.print_footerleft:
print.print_footerright:
print.print_headerleft:
print.print_headerright:
print.print_in_color: true
print.print_margin_bottom: 0.5
print.print_margin_left: 0.5
print.print_margin_right: 0.5
print.print_margin_top: 0.5
print.print_oddpages: true
print.print_orientation: 0
print.print_page_delay: 50
print.print_pagedelay: 500
print.print_paper_data: 0
print.print_paper_height: 11.00
print.print_paper_name:
print.print_paper_size: 6881390
print.print_paper_size_type: 1
print.print_paper_size_unit: 0
print.print_paper_width: 8.50
print.print_plex_name:
print.print_printer:
print.print_resolution: 0
print.print_resolution_name:
print.print_reversed: false
print.print_scaling: 1.00
print.print_shrink_to_fit: true
print.print_to_file: false
print.print_unwriteable_margin_bottom: 17
print.print_unwriteable_margin_left: 17
print.print_unwriteable_margin_right: 17
print.print_unwriteable_margin_top: 17
privacy.clearOnShutdown.cookies: false
privacy.clearOnShutdown.offlineApps: true
privacy.cpd.cookies: false
privacy.donottrackheader.enabled: true
privacy.item.offlineApps: true
privacy.sanitize.migrateFx3Prefs: true
privacy.sanitize.timeSpan: 0
privacy.trackingprotection.enabled: true
security.disable_button.openCertManager: false
security.disable_button.openDeviceManager: false
security.enable_java: false
security.OCSP.signingCA: Builtin Object Token:Verisign Class 1 Public Primary OCSP Responder
security.OCSP.URL:
security.warn_viewing_mixed: false
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1442692402

Important Locked Preferences
----------------------------

JavaScript
----------

Incremental GC: true

Accessibility
-------------

Activated: false
Prevent Accessibility: 0

Library Versions
----------------

NSPR
Expected minimum version: 4.10.8
Version in use: 4.10.8

NSS
Expected minimum version: 3.19.2 Basic ECC
Version in use: 3.19.2 Basic ECC

NSSSMIME
Expected minimum version: 3.19.2 Basic ECC
Version in use: 3.19.2 Basic ECC

NSSSSL
Expected minimum version: 3.19.2 Basic ECC
Version in use: 3.19.2 Basic ECC

NSSUTIL
Expected minimum version: 3.19.2
Version in use: 3.19.2

Experimental Features
---------------------

**Comment by marceloschmidt** [comment] 2015-09-30 16:46
It works for me on Firefox 41.

![image](https://cloud.githubusercontent.com/assets/1986378/10199863/66b5c60a-6779-11e5-8a97-e3930ecbfb20.png)

**Comment by geekgonecrazy** [comment] 2015-09-30 16:48
Yeah worked for me in firefox 41.  If you want to catch up on the conversation around this issue take a look at #dev in the chat.

**Comment by gmsecrieru** [comment] 2015-10-02 11:17
I will close this one as I just tested on 40.0.3 and it works on my 5+ year old MacBook!
![languages](https://cloud.githubusercontent.com/assets/190883/10245445/f6990808-68dd-11e5-956c-1bf19ccbad86.gif)

**Closed by gmsecrieru** 2015-10-02 11:17 UTC
Labels: subj: ui/ux, type: support

**Comment by Sing-Li** [comment] 2015-10-02 11:45
@sinteur please re-open this if problem still exists.   @gmsecrieru  this may be network transport related.  Need to test with a server behind nginx with no websocket configured, thanks.

**Comment by gmsecrieru** [comment] 2015-10-02 11:50
In that case, please file up a new issue as the use case provided in this one is clearly working. Thanks!

**Comment by Sing-Li** [comment] 2015-10-02 11:57
:+1:  more descriptive title will help us isolate the problem faster :smile_cat:

**Comment by Sing-Li** [comment] 2015-10-02 12:07
Meanwhile, it could well be plugins related https://support.mozilla.org/en-US/questions/937462

Testing in Firebox safe mode can isolated the cause.
