### ISSUE TITLE
Add a custom background image to a channel

### ISSUE THREAD

**Issue by SamirSaidani** [RocketChat/Rocket.Chat#22592] opened 2021-07-06 18:58 UTC
### Description:

I'd like to add a custom background image to a channel, to theme the channel itself.

See for instance, chat background for discord here: 

![image](https://user-images.githubusercontent.com/842380/124652670-ab970e00-de9c-11eb-826e-3f4b560c931f.png)

### Steps to reproduce:
- click to room information
- edit room
- upload background image for the channel background

### Expected behavior:

- change the background image of the channel

See for instance, chat background for discord here: 
https://vsthemes.org/en/skins/discord/18192-great-mountain-site.html

### Actual behavior:

- not possible to change the background image

### Server Setup Information:

Version of Rocket.Chat Server: all.

See also: issue #19824

**Comment by prathamjagga** [comment] 2021-07-08 10:40
![bkgrd](https://user-images.githubusercontent.com/30550632/124908193-afdf3a80-e006-11eb-877d-d427be90892e.jpg)
See I have applied the background image exactly as you want,
but can you help me out to setup rocket.chat on my local pc so
I can edit the original app and pull the changes?

**Comment by yashovardhan** [comment] 2021-07-08 11:21
Hey Samir,

Thanks for reaching out.

This repository is reserved for bugs in Rocket.Chat and this appears to be a feature request. Please open a new issue in this repo:

https://github.com/RocketChat/feature-requests

If you're looking into more white labelling, you can also have a look at our [docs](https://docs.rocket.chat/guides/administrator-guides/misc.-admin-guides/white-labeling) on that

**Comment by yashovardhan** [comment] 2021-07-08 11:22
Hey Pratham,

Can you please ask your question/ find answer to your question in our [forums](forums.rocket.chat)? This GitHub repository is reserved for bugs.

**Comment by yashovardhan** [comment] 2021-07-08 11:24
Closing since this is duplicate of #19824

**Closed by yashovardhan** 2021-07-08 11:24 UTC

**Comment by SamirSaidani** [comment] 2021-07-08 15:45
@yashovardhan thanks for your answer, I've opened the feature request #478.

@prathamjagga nice, that was quick ! Is it possible to get rid of the blank rectangle ? It looks a little bit weird compare to the discord image, where discussion fits nicely with the background. Anyway, thanks for your work 👍
