### ISSUE TITLE
Custom OAuth isn't removed when pressing remove

### ISSUE THREAD

**Issue by jpasantos** [RocketChat/Rocket.Chat#9920] opened 2018-02-27 17:18 UTC
### Description:

Removing custom oauth record isn't working on a freshly deployed Rocket Chat. Issue wasn't happening with 0.59 if I'm not mistaken

### Server Setup Information:

* Version of Rocket.Chat Server:  0.61.2 (0.61.0 for snap)
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): tar and snap (tried both)
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version: 8.9.4
* mongoDB Version: 3.0.15 (and whatever comes with the snap)

### Steps to Reproduce:

* Login and go to administration 
* Create new custom OAuth. 
* After creating it try to remove it with REMOVE CUSTOM OAUTH button. 

### Expected behavior:

Custom oauth is removed

### Actual behavior:

 Nothing happens

**Comment by AFrangopoulosUpdox** [comment] 2018-03-05 21:46
Looks like in rocket-ui-admin/client/admin.js got busted on line: 456
Code looks like this: `click .rc-header__section-button .remove-custom-oauth'() {`

In the past it was this and verified it works:
`'click .submit .remove-custom-oauth'() { `

I am new to open source and have some local issues so I can't setup a PR right now. Maybe someone else will add this into their PR to push it?

**Comment by AFrangopoulosUpdox** [comment] 2018-03-05 22:09
UPDATE: I am not sure if this is a separate bug or part of this bug.
**Steps to Reproduce:**
- Login and go to administration
- Create a new custom OAuth
- Enable it and press Save
- Remove the custom OAuth you just created and then press save

**Expected Behavior:**
- Go to login page and the delete custom oauth should not be present

**Actual Behavior:**
- Go to Login page and this oauth button should not be present.

**Workaround:**
- Go to Admin, create a custom oauth named exactly what it was before.
- Set Enabled=false
- Delete custom oauth

**Comment by AFrangopoulos** [comment] 2018-03-07 22:54
I am new to meteor and this application, so I hacked this line inside removeOAuthService.js
`Accounts.loginServiceConfiguration.remove({ service });`

There also seems to be several existing client side exceptions being thrown upon Custom OAuth removal as well.  Not sure if this is a new bug from this version or before...

**Comment by sketch242** [comment] 2018-03-27 18:18
Still happens in 0.62.2

**Comment by DRON4eg** [comment] 2018-04-10 12:50
and at 0.63.1

**Comment by foxgoblin** [comment] 2018-06-04 08:58
Still happens in 0.64.2

**Comment by geekgonecrazy** [comment] 2020-09-17 03:55
This area fully changed to react.  Should be fixed

**Closed by geekgonecrazy** 2020-09-17 03:55 UTC

**Comment by mvanderwoerd** [comment] 2020-12-19 08:36
Hey @geekgonecrazy  & @pierre-lehnen-rc  thanks for working on this but I believe this might have been incorrectly closed. 
Was this verified before closing?

**Steps to reproduce:**
- Go to settings>  OAuth section (/admin/OAuth)
- Click: "add custom OAuth" & add placeholder text "test" into available fields & click "enable"
- Click: Save Changes
- Click: refresh OAuth Services
- Open newly added service named "test" by expanding it and click "remove custom OAuth"
- Click "save changes" (top of the page)
- Click: refresh OAuth Services

**Expected:** 
- Newly added OAuth Service named "test" is no longer available

**Encountered:**
- Newly added OAuth Service named "test" is still available
- Any newly added Oauth Service added later, will break (e.g.: no login button displayed on login page)

**Comment by geekgonecrazy** [comment] 2020-12-19 08:41
Can you open a new issue?  This one was reported back in 0.61 and seemed related to UI.  It was rewrote.  No reports on any newer issues since then

**Comment by mvanderwoerd** [comment] 2020-12-19 19:51
OK, will do - thanks for the quick follow-up.
