### ISSUE TITLE
Desktop Notifications not working on Windows 10

### ISSUE THREAD

**Issue by evangriff77** [RocketChat/Rocket.Chat#22412] opened 2021-06-18 18:28 UTC
I've installed Rocket.Chat on several computers, all on Windows 10. I can get notifications when I use RChat through the Chrome browser, but notifications don't work through the desktop app. The 'test desktop notifications' button doesn't do anything. I checked every Windows 10 notification related setting, and they're all set correctly.

If I run the desktop app on my Mac, desktop notifications work fine, as well as the iOS app. Just the Windows 10 desktop notifications won't work. Other Windows 10 desktop notifications work, just not Rocket Chat. 

I checked the notifications settings, and they're all enabled for Rocket Chat. I have v3.2.2 installed on like 8 or so Win 10 computers, and they're all doing the same thing. Any ideas? People not getting notifications through the Win10 desktop app is a major bummer

**Comment by ankar84** [comment] 2021-06-21 07:33
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/2027

**Comment by debdutdeb** [comment] 2021-07-08 11:44
Closing in favor of https://github.com/RocketChat/Rocket.Chat.Electron/issues/2027 (also this issue is not related to RC itself but the electron app on Windows)

Thanks Anton :)

**Closed by debdutdeb** 2021-07-08 11:44 UTC
