### ISSUE TITLE
image_url avoid adding ROOT_URL automatically

### ISSUE THREAD

**Issue by juliomac** [RocketChat/Rocket.Chat#14202] opened 2019-04-20 04:12 UTC
I am connecting to Rocket Chat from another Meteor app using DDP.connect and calling 'sendMessage' method as below. 

```var conn = DDP.connect( HOST );
      conn.apply('sendMessage',  [{
            _id: result.responseId,
            rid: message.rid,
            msg: result.fulfillmentText,
            attachments: [
                {
                title: "text",
                title_link: "https://link",
                text: "Rocket.Chat, the best open source chat",
                image_url:"https://myothersite.com/image.png"
                }
            ]
      }])
```

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0-rc.0
- Operating System: Ubuntu (AWS)
- Deployment Method: docker on Ubuntu AWS
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: 8.11.4 - x64 
- MongoDB Version: 3.6

### Description:

Message is sent correctly but image is not rendered. The browser inspector shows that ROOT_URL is being added automatically to the image_url.

Inspector is showing:
```<img class="message__attachment__fHKkc message__attachment--image__1Hqn2" src="https://myrocketchatinstance.com.brhttps://myothersite.com/image.png">```

### Expected behavior:

It should have been just
```<img class="message__attachment__fHKkc message__attachment--image__1Hqn2" src="https://myothersite.com/image.png">```

### Attempts:

I have disabled on Administration->General-> the CDN prefix on all assets and I have cleared Administration->General Site URL and rebooted server. Still same results.

How to disable method from automatically adding ROOT_URL to the image_url address?

Is there any other method for attaching external images to messages?

**Comment by reetp** [comment] 2019-04-22 16:32
Please test on the latest rc (currently 3) so you are using latest code. You can also try the devel version as well.

**Comment by juliomac** [comment] 2019-04-22 20:36
Thanks! Is There a docker image for rc3 ?

**Comment by reetp** [comment] 2019-04-22 21:38
> Thanks! Is There a docker image for rc3 ?

Yup - Just pulled it myself:

image: rocketchat/rocket.chat:1.0.0-rc.3

You can also use rocket.chat:latest (currently 0.74.3) or rocket.chat:develop for whatever is the latest docker image built

Things are moving at a very quick pace so things can be fixed (and broken again !) in a day.

**Comment by juliomac** [comment] 2019-04-23 20:42
Unfortunately issue continues with image: rocketchat/rocket.chat:1.0.0-rc.3. It is still adding ROOT_URL too image_url on sendMessage method.

Could be something else?

![Captura de tela 2019-04-23 17 29 29](https://user-images.githubusercontent.com/3759295/56613710-9603d980-65ed-11e9-9aaa-28e49c383e4e.png)

**Comment by juliomac** [comment] 2019-04-23 21:18
This is the HTML of the resulting response:

```
<li id="FsuNGdFCFJDDrGBjg" class="message-container__3plYK">
  <div class="message-avatars__2so-k">
     <div aria-label="User picture" class="avatar__2EzjE avatar--nobg__XAbXo message-avatars__avatar__2msz5">
         <img src="https://myrocketchatinstance.com.br/avatar/LibertasBot" alt="myalt" class="avatar__image__2g8Af">
      </div>
   </div>

<div class="message-content__3aoxV">
     <div class="message-bubble__1GudU message-bubble--nude__1DlEH">
       <div class="">
         <img src="https://myrocketchatinstance.com.brhttps://myothersite.com/image.png" class="image-attachment__inner__33czg">
       </div>
     </div>
     <div class="message-bubble__1GudU"><div class="">
        <div class="message-text__5cXOs">
           <p>Oi! Tudo bem? Posso ajudar?</p>
        </div>
      </div>
     </div>
    </div>
   <time datetime="2019-04-23T21:02:19.936Z" class="message-time__18le2">18:02</time>
</li>
```

**Comment by d-gubert** [comment] 2019-04-24 01:17
Hello @juliomac 

It is weird that the issue still persists for you in this version, since [this change should have solved this kind of problem](https://github.com/RocketChat/Rocket.Chat/blob/1.0.0-rc.3/app/utils/lib/getURL.js#L7).

I haven't been able to reproduce the problem in the `1.0.0-rc.3` tag with the following call:

```javascript
Meteor.call('sendMessage', {
    rid: 'GENERAL',
    msg: 'test',
    attachments: [
        {
        title: "text",
        title_link: "https://link",
        text: "Rocket.Chat, the best open source chat",
        image_url:"https://http.cat/429.jpg"
        }
    ]
});
```

Maybe I'm missing some step you did?

**Comment by juliomac** [comment] 2019-04-24 10:01
AHAAA!! I've found what is the issue!

It is working on the OLD version of Livechat. But it is not working working on the NEW Version of the LiveChat. The one that is called with ```'https://chat.libertas.tur.br/livechat?version=1.0.0'```

I tested both with same call and conditions and that's definitely the issue.

THANK YOU!

**Comment by d-gubert** [comment] 2019-04-24 13:55
Nice! :D

Do you mind creating an issue [on the new livechat repo](https://github.com/RocketChat/Rocket.Chat.Livechat)?

**Comment by geekgonecrazy** [comment] 2019-04-24 22:13
Closing this issue.  Please open issue over on livechat repo if you haven't already :)

**Closed by geekgonecrazy** 2019-04-24 22:13 UTC

**Comment by juliomac** [comment] 2019-04-25 11:46
> on the new livechat repo

Will do. Thanks!
