### ISSUE TITLE
Feature Requests: admin can see into private rooms

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#4068] opened 2016-08-19 17:39 UTC
Your Rocket.Chat version: 0.35.0

So I polled my user base and asked them what features they think are missing from our chat, and here our some ideas they came up with, I don't know which ones of these are already in or if none of them are.

Ability for admins to enter private rooms. (for moderation purposes, possibly requiring a majority vote of those active in said room?)

**Comment by alexandrezia** [comment] 2016-08-22 14:11
If you implement this feature, please add a toggle button so people can enable or disable it.
This is a big "no go" for us, we are subject to compliance rules, periodic auditing, etc.

**Comment by wargamesqcf** [comment] 2016-08-22 18:23
More options the better!

**Comment by jszaszvari** [comment] 2016-09-02 15:40
I agree with @alexandrezia - Any features that compromise a users privacy or inability to conduct private conversations is a big no go for the organisation I am deploying this for.

**Comment by Mte90** [comment] 2017-01-02 12:23
I think that a setting to enable it in the panel from the user that create the room itself will be the easiest way.

**Comment by elfrinjo** [comment] 2017-01-23 10:25
This might be a duplicate of #2869

**Comment by MartinSchoeler** [comment] 2017-03-28 17:59
Duplicate of #2869

**Closed by MartinSchoeler** 2017-03-28 17:59 UTC
Labels: feat: channel settings, type: new feature
