### ISSUE TITLE
Uploaded file cannot be deleted

### ISSUE THREAD

**Issue by yanke-guo** [RocketChat/Rocket.Chat#1776] opened 2015-12-29 11:13 UTC

**Comment by lvh1** [comment] 2015-12-29 11:34
+1, it would be nice to be able to delete attachments (maybe in batch with checkboxes?).

**Comment by geekgonecrazy** [comment] 2015-12-30 00:42
Agreed. You can delete the message but not the attachment with the message.  Would be good if at the very least deleting the message with the original attachment would delete the attachment also.

**Comment by internalfx** [comment] 2016-01-03 19:40
Duplicate of #1367 .....

But yeah, :+1:

**Comment by geekgonecrazy** [comment] 2016-01-06 17:56
@internalfx good catch!

Closing as duplicate. Please see #1367

**Closed by geekgonecrazy** 2016-01-06 17:56 UTC
Labels: feat: file sharing, type: improvement
