### ISSUE TITLE
Join button does not show on Read-Only channels

### ISSUE THREAD

**Issue by jordan808** [RocketChat/Rocket.Chat#15233] opened 2019-08-22 20:52 UTC
### Description: The blue "Join" button does not show on public, read-only channels

When I and my other workspace users search for a public, read-only channel (including broadcast channels) there is no blue "Join" button. It appears on public channel's on the bottom right, but not for public, read-only ones. 

### Steps to reproduce:

1. Go to search bar on a Rocket.Chat instance 
2. Search for a public, read-only channel that someone else made. (Ex: Search for #amajune2019 on open.rocket.chat)
3. Try to join channel. (For me, no blue "Join" button shows, so I can't join it.)

### Expected behavior:

Blue "Join" button shows on bottom right of browser, and if you click it, it adds you to the channel.

### Actual behavior:

No "Join" button appears on the bottom right.
<img width="604" alt="Screen Shot 2019-08-08 at 12 56 54 PM" src="https://user-images.githubusercontent.com/44143999/63547302-b29f1800-c4e0-11e9-8731-10c164543934.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.3
- Operating System: Linux x64 4.4.0-157-generic
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: 3.4.20

### Additional context

Asked about this on #support on open.rocket.chat: https://open.rocket.chat/channel/support?msg=oW5ZQKcTdd5tNvYiu

### Relevant logs:

Browser: 
[www.ucsb.nectir.io-1566506564721.log](https://github.com/RocketChat/Rocket.Chat/files/3531860/www.ucsb.nectir.io-1566506564721.log)

Server:
`I20190822-18:39:19.480(0) server.js:207 System ➔ error Error sending push to gateway (5 try) -> { Error: failed [400] {"code":108,"error":"bad request sent to apn","requestId":"8e9e22a4-15f9-4ded-b85e-63a4f9039e5b","status":400}     at Object.exports.makeErrorByStatus (packages/http.js:176:10)     at Request._callback (packages/http.js:140:24)     at Request.self.callback (/snap/rocketchat-server/1392/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)     at emitTwo (events.js:126:13)     at Request.emit (events.js:214:7)     at Request.<anonymous> (/snap/rocketchat-server/1392/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)     at emitOne (events.js:116:13)     at Request.emit (events.js:211:7)     at IncomingMessage.<anonymous> (/snap/rocketchat-server/1392/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)     at Object.onceWrapper (events.js:313:30)     at emitNone (events.js:111:20)     at IncomingMessage.emit (events.js:208:7)     at endReadableNT (_stream_readable.js:1064:12)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   response:     { statusCode: 400,      content: '{"code":108,"error":"bad request sent to apn","requestId":"8e9e22a4-15f9-4ded-b85e-63a4f9039e5b","status":400}',      headers:        { 'access-control-allow-headers': 'Content-Type, Authorization, Content-Length, X-Requested-With',         'access-control-allow-methods': 'GET, PUT, POST, DELETE, OPTIONS',         'access-control-allow-origin': '*',         'access-control-expose-headers': 'Content-Type, Authorization, Cache-Control, Expires, Pragma, X-powered-by',         'cache-control': 'private, no-cache, no-store, must-revalidate',         'content-length': '110',         'content-type': 'application/json; charset=utf-8',         date: 'Thu, 22 Aug 2019 18:39:19 GMT',         expires: '-1',         pragma: 'no-cache',         'x-powered-by': 'Rocket Fuel and Rocketeers',         connection: 'close' },      data:        { code: 108,         error: 'bad request sent to apn',         requestId: '8e9e22a4-15f9-4ded-b85e-63a4f9039e5b',         status: 400 } } } `

Not sure if this is relevant ^

**Comment by novacrazy** [comment] 2019-08-23 07:12
Duplicate of #14910

**Closed** 2019-10-10 17:17 UTC
Labels: subj: ui/ux, type: bug
