### ISSUE TITLE
Links inside an attachment's value are not opened in another browser tab

### ISSUE THREAD

**Issue by gsommavilla** [RocketChat/Rocket.Chat#27614] opened 2022-12-22 14:04 UTC
### Description:

While links inside the message text open in a new tab (as per
https://github.com/RocketChat/Rocket.Chat/issues/8564 for example), a
link inside an attachment's value is not opened in an external
browser.  The html of the link has no target="_blank" attribute.

### Steps to reproduce:

1. execute the following postMessage with curl:

   ```
   curl -XPOST -H "X-Auth-Token: iwIJwYC................................32HA" \
        -H "X-User-Id: eKN...........DmZ" \
        -H "Content-type:application/json" https://rocket.mycompany.com/api/v1/chat.postMessage \
        -d '{
     "channel": "@name.surname",
     "text": "message text",
     "attachments": [
       {
         "collapsed": true,
         "color": "#97AAB3",
         "title": "TITLE",
         "fields": [
           {
             "title": "URL",
             "value": "https://en.wikipedia.org/wiki/Main_Page",
             "short": false
           }]}]}'
   ```

2. look at the message on browser/client

### Expected behavior:

The wikipedia link should open in a different browser tab.

### Actual behavior:

The wikipedia link opens in the same tab of rocket.chat.

This behaviour is particularly troublesome in the rocket chat electron
client.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0
- Operating System: Ubuntu 18.04.6 LTS
- Deployment Method: snap
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version:
  - Firefox 102.6.0esr (64-bit)
  - Google Chrome Version 108.0.5359.124 (Official Build) (64-bit)
  - rocketchat-desktop electron client on linux (installed with snap) v. 3.8.13

- Operating System: Debian testing

**Comment by grape9292** [comment] 2022-12-23 14:46
I have a similar issue. I want to put a link in a channel announcement. But it opens in the same tab. It is not a big deal in a browser version. But it works in the same way in a desctop client.
Rocketchat version 5.4.1.

**Comment by dudanogueira** [comment] 2022-12-23 17:03
Hi! Thanks for pointing out!

I believe we got this fixed already by https://github.com/RocketChat/Rocket.Chat/pull/27554 in latest development branch as I was not able to reproduce it.

If you want to **test** (please, don't use it in production!!! :pray: ) the bleeding edge version of Rocket.Chat, you can set the image of your docker, instead of the version or latest to **develop** 

Also, if you want to help is find bugs and test release candidates, we hang around here:
https://open.rocket.chat/channel/beta-testers

And last but not least, join our [Monthly Community Open Call](https://open.rocket.chat/channel/Rocket-Chat-Open-Community) where you can ask or answer anything about Rocket.Chat or Open Source :)

I will close this issue for now, but feel free to reopen it if it doesn't get fixed at our next release.

Thanks!

**Closed by dudanogueira** 2022-12-23 17:03 UTC

**Comment by eengstrom** [comment] 2023-01-24 14:47
That's great that its fixed, but it's also been over a month since the last release and it would be really nice to see this rolled out in (presumably) 5.4.2 sooner rather than later.  Any status on when the next version will be released?

**Comment by dudanogueira** [comment] 2023-01-24 14:54
I believe 5.x will only receive security patches.

This should be released for sure in 6.x.

While it doesn't have an exact date, sometime mid Feb is a good guess.

**Comment by treebes** [comment] 2023-01-24 15:03
:)!!
