### ISSUE TITLE
Rocket.Chat Apps

### ISSUE THREAD

**Issue by karlprieb** [RocketChat/Rocket.Chat#9127] opened 2017-12-14 16:41 UTC

**Comment by graywolf336** [comment] 2017-12-19 00:00
Duplicate of #6890

**Comment by theorenck** [comment] 2017-12-22 17:17
It is a epic, just a wrapper.

**Comment by geekgonecrazy** [comment] 2020-09-16 22:33
The other issue is marked as an epic.  Going ahead and closing this.  Has no activity and the other PR has much more meaning

**Closed by geekgonecrazy** 2020-09-16 22:33 UTC
Labels: Epic
