### ISSUE TITLE
Blank/extra names under Read Receipt, causing Android app to crash

### ISSUE THREAD

**Issue by binarydad** [RocketChat/Rocket.Chat#18790] opened 2020-09-03 13:45 UTC
### Description:

Since the 3.6.0 update, I've noticed that on certain messages (not all), when viewing Info on the web client for the message, it will show the same avatar twice, one with a name, another without. Doing this (using Read Receipt) on the Android app brings up a white screen and going "back" exits the application. 

![image](https://user-images.githubusercontent.com/1760607/92122715-cfe01500-edc9-11ea-82b6-869371357364.png)

### Steps to reproduce:

1. Send some messages
2. Click "Info" or "Read Receipt" for a message
3. Note if the same user avatar is listed twice with a blank name

### Expected behavior:

Only unique names are listed, no app crash

### Actual behavior:

See above

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: Ubuntu 18.04
- Deployment Method: native/tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: latest Android version
- Operating System: Windows FF/Chrome/etc

### Relevant logs:

I see no error/warnings logged

**Comment by phriedrich** [comment] 2020-09-03 15:03
This is probably a duplicate of #18689

**Comment by sampaiodiego** [comment] 2020-09-03 15:14
yes, closing as duplicate of #18689

we're aware of the issue and taking a look already 👍

**Closed by sampaiodiego** 2020-09-03 15:14 UTC

**Comment by binarydad** [comment] 2020-09-03 15:32
Got it. Didn't see it on a search. Thanks!
