### ISSUE TITLE
Latest code is not working with IE 11

### ISSUE THREAD

**Issue by Wloa** [RocketChat/Rocket.Chat#366] opened 2015-07-29 17:59 UTC
Can not use IE 11 from the latest code. Chat is not showing and the chat input field is missing.
![ie bug](https://cloud.githubusercontent.com/assets/12832493/8965502/fd06dcea-35f9-11e5-9c0a-574923378f17.jpg)

**Comment by sampaiodiego** [comment] 2015-07-29 18:11
duplicated of #361 ?

**Comment by Wloa** [comment] 2015-07-29 19:02
I am not sure. 

On 29.07.2015 14:11, Diego Sampaio wrote: 

> duplicated of #361 [1] ? 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/RocketChat/Rocket.Chat/issues/361
[2]
https://github.com/RocketChat/Rocket.Chat/issues/366#issuecomment-126045543

**Comment by Wloa** [comment] 2015-07-29 22:17
@Marcelo, it still happening with IE and Safari. 

In IE - It needto refresh after registration and can not see any posting
nor do any posting 

In Safari - Registration is fine but can not see any posting nor post. 

On 29.07.2015 15:57, Marcelo Schmidt wrote: 

> Closed #366 [1]. 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/RocketChat/Rocket.Chat/issues/366
[2] https://github.com/RocketChat/Rocket.Chat/issues/366#event-368746321

**Comment by rodrigok** [comment] 2015-07-29 23:05
Why is this closed?

**Comment by marceloschmidt** [comment] 2015-07-29 23:35
Duplicate of #361

**Comment by sampaiodiego** [comment] 2015-07-29 23:48
I'm looking into IE 11 compatibility.. after that we can check if this and #361 have been fixed.

**Comment by sampaiodiego** [comment] 2015-07-30 01:22
@Wloa can you test with latest commit please?

**Comment by Wloa** [comment] 2015-07-30 02:16
IE is working, Now I can see the post and can post, but Safari still not
working. 

On 29.07.2015 21:22, Diego Sampaio wrote: 

> @Wloa [1] can you test with latest commit please? 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/Wloa
[2]
https://github.com/RocketChat/Rocket.Chat/issues/366#issuecomment-126147084

**Comment by sampaiodiego** [comment] 2015-07-30 11:41
ok, I'll take a look on safari

**Comment by marceloschmidt** [comment] 2015-07-30 11:44
@Wloa it works on my Safari, Version 8.0.7 (10600.7.12). Can you be more specific at which version it doesn't work, please? Thank you.

**Comment by Wloa** [comment] 2015-07-30 12:44
I am using Safari 5.1.7 for window and here the screen shot.

![safari](https://cloud.githubusercontent.com/assets/12832493/8983303/3a70ff32-3697-11e5-983a-3ee083505175.jpg)

**Comment by Wloa** [comment] 2015-07-30 12:49
Using my Ipad is fine, meaning I can see the post but no avatar.

**Comment by sampaiodiego** [comment] 2015-07-30 12:54
avatar issue is related to #367 

you can do this https://github.com/RocketChat/Rocket.Chat/issues/367#issuecomment-126058648

**Comment by engelgabriel** [comment] 2015-07-30 14:58
Hi @Wloa , @sampaiodiego has deployed a final fix for IE 11, can you reopen this issue if it doesn't work?

**Closed by engelgabriel** 2015-07-30 14:58 UTC
Labels: Bug

**Comment by sampaiodiego** [comment] 2015-07-30 16:27
@Wloa I'm not finding download of Safari for Windows.. is there an updated version? what version are you using?

**Comment by Wloa** [comment] 2015-07-30 16:27
IE now is working fort posting and read posted chat but the first time
user registration got a blank screen (after typing the username, email
and password). It require user to refresh the page to get the "Register
Username" page. 

On 30.07.2015 10:58, Gabriel Engel wrote: 

> Hi @Wloa [1] , @sampaiodiego [2] has deployed a final fix for IE 11, can you reopen this issue if it doesn't work? 
> 
> --
> Reply to this email directly or view it on GitHub [3].
 

Links:
------
[1] https://github.com/Wloa
[2] https://github.com/sampaiodiego
[3]
https://github.com/RocketChat/Rocket.Chat/issues/366#issuecomment-126359719

**Comment by Wloa** [comment] 2015-07-30 16:32
It said version 5.1.7 (7534.57.2) 

I think i got it from here - http://safari.en.softonic.com/ 

I am using Window 7 

On 30.07.2015 12:27, Diego Sampaio wrote: 

> @Wloa [1] I'm not finding download of Safari for Windows.. is there an updated version? what version are you using? 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/Wloa
[2]
https://github.com/RocketChat/Rocket.Chat/issues/366#issuecomment-126392962

**Comment by sampaiodiego** [comment] 2015-07-30 16:47
I think Safari 5 will not be supported, like IE 9.

We may check exactly what browser versions will be supported and plublish on Readme.
