### ISSUE TITLE
unable to change / save personal notification settings 0.64.2

### ISSUE THREAD

**Issue by himbeere** [RocketChat/Rocket.Chat#10844] opened 2018-05-22 09:17 UTC
### Description:

Just tried to change email notification setting to "disabled" and noticed after the page reloads the settings is back to "every mention / dm".

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.2
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 1
* DB Replicaset Oplog: no
* Node Version: 8.11.2
* mongoDB Version: 3.4

### Steps to Reproduce:

1. Go to My Account / Preferences
2. Change Offline Email Notifications to "Disabled"
3. Save

### Expected behavior:

Offline Email Notifications stays disabled

### Actual behavior:

Offline Email Notifications switches back to "Default / Every Mention / DM"

### Relevant logs:

Nothing in the logs.

**Comment by himbeere** [comment] 2018-05-22 09:20
Further testing reveals only "Offline Email Notifications" setting is affected.

**Comment by kaiiiiiiiii** [comment] 2018-05-22 09:45
Duplicate of #10787? Or at least related?

**Comment by antgel** [comment] 2018-05-22 09:46
@sampaiodiego Could this be related to PR #10686 ?

**Comment by himbeere** [comment] 2018-05-22 09:56
Another observation. If i set Administration -> Account -> Offline Email Notifications to disabled i can switch it on under Personal settings. But it's not possible to do it the other way around.

**Closed** 2018-05-23 17:30 UTC
