### ISSUE TITLE
Unable to scale ddp streamer in microservices k8s deployment with community edition 

### ISSUE THREAD

**Issue by Kot-o-pes** [RocketChat/Rocket.Chat#28447] opened 2023-03-16 18:06 UTC
### Description:
After 6.0 upgrade im no longer able to scale up number of ddp streamers for my deployment, as per docs https://docs.rocket.chat/deploy/scaling-rocket.chat/microservices-setup#prerequisites 
it was possible on 5.4.4 
logs are 
```
{"level":60,"time":"2023-03-16T17:58:15.927Z","pid":1,"hostname":"rocketchat-stage-ddp-streamer-8db7b8574-9kc64","nodeID":"rocketchat-stage-ddp-streamer-8db7b8574-9kc64-1","ns":"","mod":"broker","msg":"Enterprise license not found. Shutting down..."}
```

### Expected behavior:
scaling works as expected 

### Actual behavior:
scaled pods are failed to start

**Comment by debdutdeb** [comment] 2023-03-16 18:52
Hi, as the logs suggest, "scaling" any Rocket.Chat components require enterprise license starting 6.0. This is not a bug, so closing this issue.

But feel free to continue discussing :)

**Closed as completed by debdutdeb** 2023-03-16 18:52 UTC

**Comment by TBG-FR** [comment] 2023-05-22 13:00
That's a shame, nobody was warned, and now you just can't maintain a big Rocket.Chat instance without having to pay for an entreprise license. Looks like a good move to get your users to run away and find another alternative...
