### ISSUE TITLE
logs viewer doesnt load 

### ISSUE THREAD

**Issue by fifou17** [RocketChat/Rocket.Chat#6668] opened 2017-04-12 11:23 UTC
Rocket.Chat Version: rc3
Running Instances: 
DB Replicaset OpLog:yes
Node [Version:] 4.7
 
![capture d ecran 507](https://cloud.githubusercontent.com/assets/16228448/24955402/2220c53a-1f38-11e7-8dfa-02fe40c453df.png)

**Comment by Sing-Li** [comment] 2017-04-12 11:50
Confirmed currently on demo.

**Comment by Prakharsvnit** [comment] 2017-04-14 05:32
according to this image [here](https://cloud.githubusercontent.com/assets/534679/13824905/0b02959a-ebd6-11e5-8e44-293d395bd480.png), there must be a Debug Level settings in admin/General which seems to be missing.

**Comment by sampaiodiego** [comment] 2017-04-17 12:57
it should be fixed on `rc.4` via https://github.com/RocketChat/Rocket.Chat/pull/6682 .. @fifou17 can you try it please?

**Comment by rodrigok** [comment] 2017-04-17 13:48
Please reopen the issue if the problem persists on new versions.

**Closed by rodrigok** 2017-04-17 13:48 UTC
Labels: type: bug
