### ISSUE TITLE
Registration Authentication 

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#8076] opened 2017-09-09 21:36 UTC
hi, i embedded Rchat into my own website's page, my website has its own registration and login system, I want user to login my website and don't need to login Rchat again, in another words, is there a way to make RC registration not required? if this is not possible, then what will be the best or easiest way to make RC registration/login the same as my website's, when user login /register my website, RC will just auto register /login the user as well?

**Comment by Lawri-van-Buel** [comment] 2017-09-11 09:16
Please clarify what you want to accomplish.
 Also why is oauth2 not viable as login? (default part of rocket chat for external login providers)

**Comment by MartinSchoeler** [comment] 2017-09-11 13:05
Duplicate of #8044

**Closed by MartinSchoeler** 2017-09-11 13:05 UTC

**Comment by jy2008** [comment] 2017-09-14 23:24
if i understand it correctly, #8044 is just a proposal/request, but not  a solution, is it?
