### ISSUE TITLE
Adding user to private room - drop down list displays wrong user field

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1023] opened 2015-10-06 20:56 UTC
When adding user to private room, the list of available users is not displayed using the familiar 'user name'.  Instead, it appears to be showing 'full name' of the user - making selection quite difficult.

**Comment by geekgonecrazy** [comment] 2015-10-06 20:57
@Sing-Li possible duplicate of #700

**Comment by gmsecrieru** [comment] 2015-10-09 22:44
Closed by #1031

**Closed by gmsecrieru** 2015-10-09 22:44 UTC
Labels: contrib: easy, type: bug
