### ISSUE TITLE
The right hand conversation view changes scroll position randomly during the day

### ISSUE THREAD

**Issue by victorcassel** [RocketChat/Rocket.Chat#22981] opened 2021-08-20 07:18 UTC
I have version 3.2.2 

Error description: During my normal workday using the Rocket chat client constantly I click around between different different group conversations on the left side, and/or switch to/from the Rocket chat client windo, don't know when it exactly happens - I suddenly see the conversation scrolled up like one week earlier or a month earlier or whatever. Completely randomly.

Impact: This means that every time I step in to a new conversation view I need to make sure that the right hand scroll bar is scrolled to the bottom. Often I forget this and start reading conversations that are a month old, believing it is a fresh one. 

(By the way the automatic update does not work on our intranet, and if I press button <Check for updates> in the About-dialog, i get the messages "As error has occurred when looking for updates". (BTW level 2: It should say "An error..."))

**Comment by ankar84** [comment] 2021-08-20 08:11
related or duplicate of
https://github.com/RocketChat/Rocket.Chat.Electron/issues/2040
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1835
https://github.com/RocketChat/Rocket.Chat.Electron/issues/1266

**Comment by yashovardhan** [comment] 2021-08-24 13:46
Hey Victor,

Thanks for reporting this.

Can you fill up the template here as well please? If you see the issue related to the other ones mentioned by Anton in the above message, let us know. We will prioritise that while closing this one out.

**Comment by Vkat14** [comment] 2021-09-28 23:25
Is this issue still being worked on? 

@yashovardhan by template do you mean this:

```
**Describe the bug**
A clear and concise description of what the bug is.

What operating system and which version?
Which version of Rocket.Chat (Server)?
Which version of Rocket.Chat.Electron (Electron/Desktop)?
Is there any setting relevant changed?

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

```

**Comment by Vkat14** [comment] 2021-10-01 21:55
@ankar84 Do you see this problem as well? It seems not everyone is affected by this. Unless everyone is seeing this but not reporting the problem.  My chat client just lags. I have to wait to even scroll down.

**Comment by jeanfbrito** [comment] 2022-01-12 00:41
Please test if the latest release did solve this. If not please reopen the issue or create a new one and tell us. I will be closing this one for now.

Thank you!

**Closed by jeanfbrito** 2022-01-12 00:41 UTC
