### ISSUE TITLE
@mention autocomplete when inside Private Groups should show members only

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#2802] opened 2016-04-07 08:13 UTC
Currently, the autocomplete shows and searches the entire universe of users.

**Comment by cbajohr** [comment] 2016-04-07 11:03
That would be extremely useful.... it happens quiet often that you accidentally mention someone in a private channel, that is not on the channel and not allowed to see the message...

**Comment by soenkef** [comment] 2016-04-07 20:44
+1 - good feature

**Comment by geekgonecrazy** [comment] 2016-04-08 05:59
Probably a dupe of #2588

**Comment by mickeyclausen** [comment] 2016-04-13 05:11
+1

**Comment by marceloschmidt** [comment] 2016-05-02 22:21
Duplicate of #2588

**Closed by marceloschmidt** 2016-05-02 22:21 UTC
