### ISSUE TITLE
How to know the person had read the message or not.

### ISSUE THREAD

**Issue by 8754463964** [RocketChat/Rocket.Chat#4401] opened 2016-09-21 23:26 UTC
Your Rocket.Chat version: 0.40.
How could we will come to know the person had read the messages or not.? 
Is there any option will know it..?

**Comment by MartinSchoeler** [comment] 2016-09-22 13:10
@8754463964 i think that there is no option to do that, it would be a nice new feature though

**Comment by RichardFoxworthy** [comment] 2016-09-22 21:57
Duplicate of #3411

**Closed** 2017-03-28 17:47 UTC
Labels: feat: message, type: new feature
