### ISSUE TITLE
Feature Request: Support direct messages with multiple users.

### ISSUE THREAD

**Issue by tbtgspence** [RocketChat/Rocket.Chat#10881] opened 2018-05-25 23:26 UTC
This would most likely just result in the auto-creation of a private room, but something to more easily support DM'ing multiple people similar to how Slack handles it would be very user-friendly.

**Comment by JSzaszvari** [comment] 2018-05-26 19:37
@rocket-cat label add "Feature: Request"

**Comment by kaiiiiiiiii** [comment] 2018-05-26 19:44
Duplicate of #4489, PR #9106

**Comment by JSzaszvari** [comment] 2018-05-26 23:13
@rocket-cat close duplicate

**Comment by JSzaszvari** [comment] 2018-05-26 23:13
@rocket-cat close

**Closed by JSzaszvari** 2018-05-26 23:13 UTC
Labels: Feature: Request
