### ISSUE TITLE
Cannot delete files when using FileSystem

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7222] opened 2017-06-11 17:26 UTC
Hi guys.

I've set File Upload to use the FileSystem.  Whilst people can upload files, if they try to delete them, they get a confirmation that the file has been deleted, but nothing happens.

I'm running on Ubuntu 16.04 within a Snap.  The FileSystem path is set to:
 /var/snap/rocketchat-server/common/uploads

Anybody have any idea how I can get around this issue (I don't want to use GridFS as there's no easy way to manually delete unwanted files).

Thanks

Rocket.Chat Version: 	0.56.0
Running Instances: 1
Node Version: 4.8.1

**Comment by soundstorm** [comment] 2017-06-12 10:42
#5621

**Comment by MartinSchoeler** [comment] 2017-06-12 12:24
@waveyuk does this happens only with file uploads? Could be related to #6941

**Comment by waveyuk** [comment] 2017-06-12 12:53
@MartinSchoeler 
Changing the settings as described in #6941 now allows me to delete a file uploaded into a chat.  However, and I think this is the gist of what's being said in #6941 is that the image thumbnail isn't deleted from the chat and can still be downloaded.  Also, if the chat is a Direct Message, deleting the room also does not delete the file (nor does it clear down the chat history, which I would expect it to do!).

**Comment by geekgonecrazy** [comment] 2020-09-17 03:24
Closing since it does allow deleting as confirmed above

**Closed by geekgonecrazy** 2020-09-17 03:24 UTC
Labels: feat: file sharing
