### ISSUE TITLE
Rocketchat client doesn't show popup 

### ISSUE THREAD

**Issue by lsavio** [RocketChat/Rocket.Chat#5935] opened 2017-02-07 14:06 UTC
Rocket.Chat Version: 2.2.0
Running Instances: 1
DB Replicaset OpLog:
Node Version: 4.5

Hi,I installed Rochetchat (client on windows) version 2.2.0. In rocketchat, i did link to jitsi (with openfire meet plugin). When i open a videoconference by click on the icon of jitsi, the popup about login/password appears when the browser it's used, but if instead of browser i use the client of rocketchet, the popup don't appear, and this cause an unautorizated access (because login and password there aren't)
There is the possibility to show the popup in rocketchat client?

thanks
Luigi

**Comment by engelgabriel** [comment] 2017-02-07 20:47
Can you please try the 2.4.0?

**Comment by lsavio** [comment] 2017-02-08 11:53
Hi, 
i tried with the version 2.4.0 as suggest you, but there is the same problem, popups aren't visibile (then i get error of not authentication)...

**Comment by engelgabriel** [comment] 2017-02-10 17:06
If the problem is only on the Desktop app, can you please open this issue at https://github.com/RocketChat/Rocket.Chat.Electron ?

**Comment by TwizzyDizzy** [comment] 2018-03-03 14:46
@rocket-cat close

Has obviously been transferred to https://github.com/RocketChat/Rocket.Chat.Electron/issues/355 by @lsavio. Closing.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-03-03 14:46 UTC
Labels: feat: video conferencing, type: support
