### ISSUE TITLE
Allow custom directory for files with file system using Snaps

### ISSUE THREAD

**Issue by Xarkam** [RocketChat/Rocket.Chat#5948] opened 2017-02-08 11:06 UTC
Rocket.Chat Version: 0.51.0
Running Instances: 1

Hello, I try to define a custom directory for uploaded files but it doesn't work if the directory isn't /var/snap/rocketchat-server/common/uploads

If I define other directory (/mnt/RocketChatFiles) I recieve this error

```
Exception while invoking method 'ufsComplete' Error: EACCES: permission denied, open '/home/RocketChatFiles/cWZfyhRR7yjsB79RR'   
at Object.Future.wait (/snap/rocketchat-server/487/node_modules/fibers/future.js:449:15)   
at [object Object].ufsComplete (/snap/rocketchat-server/487/programs/server/packages/jalik_ufs.js:1298:24)   
at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/487/programs/server/packages/rocketchat_lib.js:1064:26)   
at maybeAuditArgumentChecks (/snap/rocketchat-server/487/programs/server/packages/ddp-server.js:2108:12)   
at /snap/rocketchat-server/487/programs/server/packages/ddp-server.js:1042:22   
at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   
at /snap/rocketchat-server/487/programs/server/packages/ddp-server.js:1041:43   
at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   
at /snap/rocketchat-server/487/programs/server/packages/ddp-server.js:1040:48   
at Session.method (/snap/rocketchat-server/487/programs/server/packages/ddp-server.js:1018:23)   
at /snap/rocketchat-server/487/programs/server/packages/ddp-server.js:880:89      - - - - -   
at Error (native)  
```
Disable the protected uploaded files doesn't work.

Any help to find a workaround ?

Thanks.

**Comment by engelgabriel** [comment] 2017-02-08 13:11
Are you sure the user running the Rocket.Chat process has permission to that folder?

**Comment by Xarkam** [comment] 2017-02-08 13:47
It's a snap application. User is root (cf. doc for installing with snap under ubuntu)
And I trying with 777 permissions on the directory but nothing. Always same error.

**Comment by engelgabriel** [comment] 2017-02-08 13:53
@geekgonecrazy can you help here?

**Comment by geekgonecrazy** [comment] 2017-02-08 15:03
@xarkam currently this is not possible.  Snaps are isolated for security.  So they have designated folders they are allowed to read and write from.  It's possible you might be able to symlink your folder to the /var/snap/rocketchat-server/common/uploads folder

**Comment by Xarkam** [comment] 2017-02-08 15:36
Hello @geekgonecrazy .
I have tried with a symlink but is same result.

I don't know enough about snap. It's possible to change the directory of /var/snap/rocketchat-server for another destination?

**Comment by geekgonecrazy** [comment] 2017-02-09 00:04
I'm not aware of a way.  looking into how we can solve this problem.  I think there might be a way we can add support

**Comment by louisemessage** [comment] 2018-03-13 15:10
As there haven't been any comments on this issue for over a year, I am closing it for the meantime.

**Closed by louisemessage** 2018-03-13 15:10 UTC
Labels: feat: file sharing, type: improvement

**Comment by robwent** [comment] 2019-01-05 21:34
This is possible with nextcloud using the removable media plugin.

https://github.com/nextcloud/nextcloud-snap/blob/master/README.md#removable-media

Allows access to anything mounted to /media

Possible to reopen this issue?

I like using snaps but my main drive is a small ssd so it's good to be able to store data somewhere else.

**Comment by geekgonecrazy** [comment] 2019-02-06 22:49
opened issue for that request specifically: https://github.com/RocketChat/Rocket.Chat/issues/13391

**Comment by nestorwheelock** [comment] 2021-10-10 01:26
I used the snap package when I originally deployed this as was recommended.  I"m not particularly ready to jump on the snapwagon myself because I think it can cause as many issues as it solves and my aggravation about the paths I chose not working out is mostly due to my own ignorance.  I think using a distributed block file storage is a good idea and appeals to my disinterest and laziness in learning how the snap sandboxes actually work. 

On a side note It looks like a PITA to build/package snaps which would explain why they don't get updated as quickly as the other packages as illustrated by the repetitive complaints I've been reading about the slow snap release cycle... I think the permissions error it's actually a feature of the snap, and not a bug so you can't just willy nilly put in your own file system path and break the security.

So I'm done tinkering with this.  But if anyone else is interested this is where I ended up before not caring anymore where the files live and switched for now over to s3. 

https://snapcraft.io/docs/snap-layouts

I'll do the pruning there.  I do notice for a few years now that file uploads will crash the instance.  We upped the memory on it and that seemed to resolve that issue most of the time but we do use the file sharing part of the application quite a bit and maybe now I'll be able to upload larger batches of files to share with my remote staff.

On a side note I"m usually a FreeBSD admin and prefer to run applications there in jails if I can.  The documentation for Rocketchat is for FBSD 10.3 and we're on 13 so maybe I can put my energy into updating the documentation instead.  Looks like on that forum someone got it to build a couple years ago once they figured out some other quirks.
