### ISSUE TITLE
Option to show More than one Active Chat window

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#4499] opened 2016-09-30 14:07 UTC
Someone asked me an interesting idea, worth looking, ability to have multi chat room open in the same time lets say two on top of each other? is this possible? to be implemented without impacting design? or stability?

Your Rocket.Chat version: 0.41

**Comment by wargamesqcf** [comment] 2016-10-01 21:24
Come from a multi window chat service, they suck and are all terrible.

**Comment by TwizzyDizzy** [comment] 2018-02-14 19:46
@rocket-cat close

Hi, I'll close this, as this is a feature request and not a bug. If you're still interested in having this implemented, please open a topic over at https://forums.rocket.chat.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-02-14 19:46 UTC
Labels: type: discussion, type: new feature
