### ISSUE TITLE
Multi server capability for mobile apps

### ISSUE THREAD

**Issue by schepely** [RocketChat/Rocket.Chat#1148] opened 2015-10-17 06:38 UTC
Currently I cannot select a server when running a mobile app. (Android in my case).
This is the main issue that is holding me back of using Rocket and replacing Slack everywhere.

**Comment by geekgonecrazy** [comment] 2015-10-17 06:40
This is a good issue to have open.  A lot of people want this.  So good idea to have a ticket to track the development

**Comment by gmsecrieru** [comment] 2015-10-20 14:24
I think this is a duplicate of #577

**Comment by geekgonecrazy** [comment] 2015-10-20 14:36
@gmsecrieru you're right we need to maybe rename that one so people can find it maybe?

**Comment by gmsecrieru** [comment] 2015-10-20 14:48
I will copy this title. 

@schepely could you please follow up on #577 ?

**Closed by gmsecrieru** 2015-10-20 14:48 UTC
Labels: subj: mobile, type: improvement
