### ISSUE TITLE
Deleting messages does not work

### ISSUE THREAD

**Issue by monspid** [RocketChat/Rocket.Chat#7182] opened 2017-06-07 12:07 UTC
Rocket.Chat Version: 0.56
Running Instances: 2.8.0

After setting the max period of deleting messages, deleting messages dose not work. Messages are hidden for person who deletes them, but they are still visible for others.

**Comment by MartinSchoeler** [comment] 2017-06-07 13:51
duplicate of #6941

**Closed by MartinSchoeler** 2017-06-07 13:51 UTC
