### ISSUE TITLE
RocketChat Client - Windows - 2.13.2 - On moving window over Desktop become Errorwindow

### ISSUE THREAD

**Issue by svalcken** [RocketChat/Rocket.Chat#12032] opened 2018-09-12 14:22 UTC
### Description:

RocketChat Client under Windows with Version 2.13.2

If moving the window, an error will be displayed in a new window.

The older one Version has no errors.

### Steps to reproduce:

1. Moving window over Desktop
2. Error window are Displayed
3. 

### Expected behavior:

A JavaScript error occurred in the main process

Uncaught Exception:
Error: EPERM: operation not permitted, rename

... windows-state-main.json ->
at Object.fs.renameSync (fs.js:766:18)
at writeAtomicSny
... resources\app.as...:6
at Object.writeSync [as sync]
... resources\app.as...:3
at ObjectWrite
... resources\app.as...:13
at Object.saveState
... resources\app.as...:21
at BrowserWindow.mainWindow.on.lodash.debunce
... resources\app.as...:25
at invokeFunc
... resources\app.as...:23
at trailingEdge
... resources\app.as...:18
at Timeout.timerExpired [as _onTimeout]
... resources\app.as...:18
at timeout (timer.js:475:11)
at tryOnTimeout (timer.js:310:5)
at Timer.listOnTimeout (timer.js:270:5)

### Server Setup Information:

I don't know this thinks over the server.

**Comment by tassoevan** [comment] 2018-09-12 14:27
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/876

**Closed by tassoevan** 2018-09-12 14:27 UTC
