### ISSUE TITLE
Channel avatar not appear in top bar

### ISSUE THREAD

**Issue by xi67** [RocketChat/Rocket.Chat#19083] opened 2020-09-30 13:43 UTC
### Description:

Channel avatar not appear in top bar.

### Expected behavior:
Like user chat top bar with avatar : 
![image](https://user-images.githubusercontent.com/12096081/94693058-8dabe400-0333-11eb-8313-e9e0677aa158.png)

### Actual behavior:
Channel with no avatar : 
![image](https://user-images.githubusercontent.com/12096081/94693113-9c929680-0333-11eb-9eab-df08688091c7.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0
- Operating System: Debian
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.14
- MongoDB Version: 4.2.9

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by ankar84** [comment] 2020-10-01 04:59
Yeah, I think channel avatar should be in channel header like users avatar.

**Comment by gabriellsh** [comment] 2020-10-01 18:17
This is not a bug per say, but I agree it should be there. It was left out of the feature on purpose for some reason I can't remember.

**Comment by bhavayAnand9** [comment] 2020-10-02 15:53
Hi! @gabriellsh, I would like to work on this one, seems like a good first-time issue.

**Comment by gabriellsh** [comment] 2020-10-05 16:10
@bhavayAnand9  Sure, go at it.

**Comment by ggazzo** [comment] 2020-11-08 17:38
closed by https://github.com/RocketChat/Rocket.Chat/pull/19132

**Closed by ggazzo** 2020-11-08 17:38 UTC
Labels: subj: ui/ux, type: improvement
