### ISSUE TITLE
rocket chat reloads and crashes in Safari IOS and OSX

### ISSUE THREAD

**Issue by sylvaint** [RocketChat/Rocket.Chat#13568] opened 2019-02-25 23:30 UTC
- Version of Rocket.Chat Server: 0.74.3 
- Operating System: linux x64
- Deployment Method: centos manual installation
- NodeJS Version: v8.11.3
- Browser Safari 12.0.3

rocket chat iframe auth
When accessing on Safari, page reloads twice before crashing.
"A problem repeatedly occurred on """

Safari Console error:
Failed to set referrer policy: The value 'origin-when-crossorigin' is not one of 'no-referrer', 'no-referrer-when-downgrade', 'same-origin', 'origin', 'strict-origin', 'origin-when-cross-origin', 'strict-origin-when-cross-origin' or 'unsafe-url'.

No issue in Chrome or Firefox on any OS
Was working in 0.74.2 but unsure if Safari was updated since.

rocket chat log:

[34mI20190225-18:25:16.607(-5) Exception in onLogin callback: TypeError: Cannot redefine property: loginAt     at Function.defineProperty (<anonymous>)     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)     at Array.forEach (<anonymous>)     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)     at packages/callback-hook/hook.js:130:22     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)     at Hook.each (packages/callback-hook/hook.js:108:15)     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by MarcosSpessatto** [comment] 2019-02-26 15:35
If the error is caused by this log that you are sharing, I think [this PR](https://github.com/RocketChat/Rocket.Chat/pull/13553) will correct the problem.

**Comment by alissonfpmorais** [comment] 2019-05-28 20:29
I have this same error too and update to version 1.0.0 has no effects.
Anything else to do?

**Comment by serviceman** [comment] 2019-06-10 07:23
Speaking from personal experience 1.0.0 had an entire host of problems with logging in with safari. They were resolved in 1.1.0

**Comment by ggazzo** [comment] 2019-10-17 21:48
thanks @serviceman , closing any new issue let me know (:

**Closed by ggazzo** 2019-10-17 21:48 UTC
Labels: type: bug
