### ISSUE TITLE
`\(.\)` shouldn't get mangled

### ISSUE THREAD

**Issue by quinox** [RocketChat/Rocket.Chat#8644] opened 2017-10-25 13:10 UTC
### Description:

When you send a message containing ``` `\(.\)` ``` the code block gets mangled.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v4.8.4

### Steps to Reproduce:

1. Send a user / channel a message containing ``` `\(.\)` ```

### Expected behavior:

* Everybody sees ``` `\(.\)` ```

### Actual behavior:

![The bug in action](https://ghost.qtea.nl/tmp/rocketchat_regex_group.png)!

* The codeblock containing ``` `\(.\)` ``` gets mangled with something like `=!=apPxzu...cje=!=` . A reload does not fix it
* This also goes for older messages sent before this bug was present.
* I think this bug wasn't present before 0.59.0

**Comment by MartinSchoeler** [comment] 2017-10-25 15:03
Duplicate of #8640

**Closed by MartinSchoeler** 2017-10-25 15:03 UTC
