### ISSUE TITLE
unread counter not working via rest api.

### ISSUE THREAD

**Issue by sinfosy** [RocketChat/Rocket.Chat#10592] opened 2018-04-26 14:49 UTC
Description:
"unreadNotLoaded" counter gives wrong result.
calling rest api via curl:
http://<server-url>/api/v1/groups.history?roomId='<roomId>.'&unreads=true&oldest=2018-01-01

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): extracting tarball, npm install
* Number of Running Instances: 1
* DB Replicaset Oplog: none
* Node Version: v8.9.3
* mongoDB Version: 3.6.3

### Steps to Reproduce:

1. call Api for goup history.

### Expected behavior:

give the current unread counter of that user.

### Actual behavior:

gives wrong result.

### Relevant logs:
 	`Array
	(
		[messages] => Array
		(
			[0] => Array
			(
				[_id] => j45whhD4xeXdGd9Ea
				[rid] => GENERAL
				[msg] => hi
				[ts] => 2018-04-26T11:27:26.696Z
				[u] => Array
				(
					[_id] => f98TLaJipwuR8MGjo
					[username] => admin
					[name] => Admin
				)
				
				[mentions] => Array
				(
				)
				
				[channels] => Array
				(
				)
				
				[_updatedAt] => 2018-04-26T11:27:26.698Z
			)
			
			[1] => Array
			(
				[_id] => Mt8xousnfPkPBhCK7
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-04-24T10:51:05.860Z
				[msg] => 37D250
				[u] => Array
				(
					[_id] => cExgNkci5mZ8Bj532
					[username] => 37D250
				)
				
				[groupable] => 
				[_updatedAt] => 2018-04-24T10:51:05.860Z
			)
			
			[2] => Array
			(
				[_id] => fjy9owoDisgYuLipo
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-04-24T10:41:44.621Z
				[msg] => Sourav_Golui
				[u] => Array
				(
					[_id] => kyTQDvbDmNRQJCgkr
					[username] => Sourav_Golui
				)
				
				[groupable] => 
				[_updatedAt] => 2018-04-24T10:41:44.621Z
			)
			
			[3] => Array
			(
				[_id] => hFhGkTg76umR6YfEb
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-04-24T10:37:30.640Z
				[msg] => 37D249
				[u] => Array
				(
					[_id] => Zv8a5vr8P4WSD5Zzx
					[username] => 37D249
				)
				
				[groupable] => 
				[_updatedAt] => 2018-04-24T10:37:30.640Z
			)
			
			[4] => Array
			(
				[_id] => aCRzjoSFHqkAvYyiH
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-04-24T10:37:25.474Z
				[msg] => 37D248
				[u] => Array
				(
					[_id] => zjiyreq2YqkwWpLej
					[username] => 37D248
				)
				
				[groupable] => 
				[_updatedAt] => 2018-04-24T10:37:25.474Z
			)
			
			[5] => Array
			(
				[_id] => 6Jzgx4R9S7RGN3mCp
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-04-24T10:37:20.228Z
				[msg] => 37D247
				[u] => Array
				(
					[_id] => 4iBSLjmc4jnnwwgJ5
					[username] => 37D247
				)
				
				[groupable] => 
				[_updatedAt] => 2018-04-24T10:37:20.228Z
			)
			
			[6] => Array
			(
				[_id] => snbdnZxcjnmujuT3r
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-04-24T10:37:15.116Z
				[msg] => 37D246
				[u] => Array
				(
					[_id] => 38e7w7KXHLMoJmLM4
					[username] => 37D246
				)
				
				[groupable] => 
				[_updatedAt] => 2018-04-24T10:37:15.116Z
			)
			
			[7] => Array
			(
				[_id] => H5jcDbdKL2jSbmWH6
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-04-24T10:37:11.682Z
				[msg] => Samim_Aktar
				[u] => Array
				(
					[_id] => JARxqLW2mGwdzWBGf
					[username] => Samim_Aktar
				)
				
				[groupable] => 
				[_updatedAt] => 2018-04-24T10:37:11.682Z
			)
			
			[8] => Array
			(
				[_id] => gYiZdHMXfnn2iLacf
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-03-28T06:54:23.866Z
				[msg] => 2D214
				[u] => Array
				(
					[_id] => 4RFtMNbwA8qfRK4dt
					[username] => 2D214
				)
				
				[groupable] => 
				[_updatedAt] => 2018-03-28T06:54:23.866Z
			)
			
			[9] => Array
			(
				[_id] => z3FyCKtY9m4eEEpST
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-03-28T06:52:45.036Z
				[msg] => Martin_Mustermann
				[u] => Array
				(
					[_id] => fphkQtj9XhHwJWgN5
					[username] => Martin_Mustermann
				)
				
				[groupable] => 
				[_updatedAt] => 2018-03-28T06:52:45.037Z
			)
			
			[10] => Array
			(
				[_id] => rmywcTA2r5Gnk8i7s
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-03-22T06:32:13.210Z
				[msg] => 2D213
				[u] => Array
				(
					[_id] => kaubMR35cb8kFSabx
					[username] => 2D213
				)
				
				[groupable] => 
				[_updatedAt] => 2018-03-22T06:32:13.210Z
			)
			
			[11] => Array
			(
				[_id] => 4fnfZRwQbr63QaDKN
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-03-21T12:04:09.717Z
				[msg] => 2D212
				[u] => Array
				(
					[_id] => GqfTSoL2weaKniscS
					[username] => 2D212
				)
				
				[groupable] => 
				[_updatedAt] => 2018-03-21T12:04:09.717Z
			)
			
			[12] => Array
			(
				[_id] => WXZSECygtFcYRzXcA
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-03-20T13:35:50.228Z
				[msg] => Biman_Maity
				[u] => Array
				(
					[_id] => bP8qJNvnDNaoXWev3
					[username] => Biman_Maity
				)
				
				[groupable] => 
				[_updatedAt] => 2018-03-20T13:35:50.228Z
			)
			
			[13] => Array
			(
				[_id] => FD8nTi4758TG7hmkk
				[rid] => GENERAL
				[msg] => hello
				[ts] => 2018-03-19T14:17:32.957Z
				[u] => Array
				(
					[_id] => B7s9PjNS6JmTZyfbi
					[username] => Koenigstein
					[name] => Dagmar Koenigstein
				)
				
				[mentions] => Array
				(
				)
				
				[channels] => Array
				(
				)
				
				[_updatedAt] => 2018-03-19T14:17:32.959Z
			)
			
			[14] => Array
			(
				[_id] => AqM2vxJFG9WjAAXY3
				[rid] => GENERAL
				[msg] => hi
				[ts] => 2018-03-19T14:16:19.876Z
				[u] => Array
				(
					[_id] => f98TLaJipwuR8MGjo
					[username] => admin
					[name] => Admin
				)
				
				[mentions] => Array
				(
				)
				
				[channels] => Array
				(
				)
				
				[_updatedAt] => 2018-03-19T14:16:19.878Z
			)
			
			[15] => Array
			(
				[_id] => v2D5QsDL7n9jWrXiQ
				[rid] => GENERAL
				[msg] => hello
				[ts] => 2018-03-19T14:15:39.949Z
				[u] => Array
				(
					[_id] => f98TLaJipwuR8MGjo
					[username] => admin
					[name] => Admin
				)
				
				[mentions] => Array
				(
				)
				
				[channels] => Array
				(
				)
				
				[_updatedAt] => 2018-03-19T14:15:39.951Z
			)
			
			[16] => Array
			(
				[_id] => 5bPK9PuxeXwHKeNLM
				[rid] => GENERAL
				[msg] => palim
				[ts] => 2018-03-01T13:41:21.376Z
				[u] => Array
				(
					[_id] => f98TLaJipwuR8MGjo
					[username] => admin
					[name] => Admin
				)
				
				[mentions] => Array
				(
				)
				
				[channels] => Array
				(
				)
				
				[_updatedAt] => 2018-03-01T13:41:21.407Z
			)
			
			[17] => Array
			(
				[_id] => 5CjGHpF3iNzCGLqDB
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-02-28T17:38:44.506Z
				[msg] => akraft
				[u] => Array
				(
					[_id] => iXvqRkymG83ZzYHNk
					[username] => akraft
				)
				
				[groupable] => 
				[_updatedAt] => 2018-02-28T17:38:44.507Z
			)
			
			[18] => Array
			(
				[_id] => 4aWny5PbunztkGzt7
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-02-16T13:22:27.833Z
				[msg] => 32D211
				[u] => Array
				(
					[_id] => RrRRang76KyvyvxMR
					[username] => 32D211
				)
				
				[groupable] => 
				[_updatedAt] => 2018-02-16T13:22:27.833Z
			)
			
			[19] => Array
			(
				[_id] => Q35fPPHa7FfjZwrBi
				[t] => uj
				[rid] => GENERAL
				[ts] => 2018-02-16T13:22:14.582Z
				[msg] => 32D210
				[u] => Array
				(
					[_id] => s5nJ9kHGj8Fw3TDAs
					[username] => 32D210
				)
				
				[groupable] => 
				[_updatedAt] => 2018-02-16T13:22:14.582Z
			)
		)
		
		[firstUnread] => Array
		(
			[_id] => hg9fFga5r8LgRRdPp
			[t] => uj
			[rid] => GENERAL
			[ts] => 2018-01-04T13:18:20.279Z
			[msg] => 26D175
			[u] => Array
			(
				[_id] => MzMF6uhuWxm7ArrSE
				[username] => 26D175
			)
			
			[groupable] => 
			[_updatedAt] => 2018-01-04T13:18:20.280Z
		)
		
		[unreadNotLoaded] => 67
		[success] => 1
	)`

**Comment by MarcosSpessatto** [comment] 2018-05-09 20:42
Hi @sinfosy, The `unreadNotLoaded` value is the total of messages that were not read and were not returned by the endpoint. Probably as you described in your call to the endpoint, you did not pass the `count` value, which defaults to 20 messages ([docs](https://rocket.chat/docs/developer-guides/rest-api/groups/history/)), then it would be the 20 that were brought, plus 67 unread, resulting in a total of 87 unread messages. I don't know if I understood the problem correctly, but I believe that is what I explained, if it is not, feel free to ask or [contact me](https://open.rocket.chat/direct/marcos.defendi).

**Comment by MarcosSpessatto** [comment] 2018-05-14 17:38
Hello @sinfosy, this endpoint counts as unread based on the date parameters that you pass, for example, you provide oldest, and latest, then the search will be done in that period, and will be considered as unread, and not based on the amount of messages unread that that user has with that channel. From what I understand, you want to show the unread message counter, so the correct endpoint would be [this](https://rocket.chat/docs/developer-guides/rest-api/subscriptions/getone/).

**Comment by sinfosy** [comment] 2018-05-15 08:10
Hi @MarcosSpessatto, I check the link and run that Api but unread never changing always at "0". the "alert" field is changing to "1" and "blank", for single message "1" and for multiple message also "1". so you please help me.

`Array
(
    [subscription] => Array
        (
            [_id] => aKYL43e8TSsCM8yyE
            [open] => 1
            [alert] => 
            [unread] => 0
            [ts] => 2017-06-15T07:20:34.240Z
            [rid] => 5TakLP79FFh3akRGy
            [name] => 6.2
            [t] => p
            [u] => Array
                (
                    [_id] => B7s9PjNS6JmTZyfbi
                    [username] => Koenigstein
                )

            [_updatedAt] => 2018-05-15T08:06:21.205Z
            [ls] => 2018-05-15T08:06:21.205Z
            [groupMentions] => 0
            [userMentions] => 0
            [f] => 1
            [meta] => Array
                (
                    [revision] => 19
                    [created] => 1524740356920
                    [version] => 0
                    [updated] => 1526371581211
                )

        )

    [success] => 1
)`

**Comment by MarcosSpessatto** [comment] 2018-05-18 14:19
I'm closing this issue, because the doubts have been clarified internally. @sinfosy contacted me through the chat and we talked about it.

**Closed by MarcosSpessatto** 2018-05-18 14:19 UTC
Labels: feat: api, feat: rest, stat: waiting response

**Comment by reyalpsirc** [comment] 2018-12-03 13:05
@MarcosSpessatto I also have the same problem with the counters. In brief, the unread does not update when someone creates a new message and instead, it only updates together with userMentions. Is that the intended behaviour? If so, how did @sinfosy solve is problem to show the amount of unread messages per channel to an user?

**Comment by reyalpsirc** [comment] 2018-12-05 16:56
Nevermind, I also spoke on the chat and found out that I needed to change the behaviour of unreads in Administration => General => Unread Count

**Comment by Sajadmhy** [comment] 2022-12-04 19:30
@MarcosSpessatto I also have the same problem with the counters. Can we have a chat about it?
