### ISSUE TITLE
Roles displayed regardless of Layout settings

### ISSUE THREAD

**Issue by luckenbach** [RocketChat/Rocket.Chat#14058] opened 2019-04-09 03:36 UTC
### Description:

Roles are always displayed in chat

### Steps to reproduce:

Login to a room with users that have roles assigned to them such as 'Owner'

### Expected behavior:

When Administration > Layout > User Interface > Display Roles is set to false roles will not be displayed

### Actual behavior:

Roles are displayed.
![image](https://user-images.githubusercontent.com/533852/55771677-a3965c80-5a4e-11e9-88bd-e7f731fe0c61.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  1.0.0-rc.1
- Operating System:  K8s
- Deployment Method:  docker
- Number of Running Instances: 3 
- DB Replicaset Oplog:  Yes
- NodeJS Version:  v8.11.4
- MongoDB Version: 3.6.9

**Comment by ixlandia** [comment] 2019-04-29 13:36
This is still an issue in the 1.0.0 release

**Comment by ggazzo** [comment] 2019-04-29 18:35
closed by #14313

**Closed by ggazzo** 2019-04-29 18:35 UTC

**Comment by karmaking** [comment] 2022-08-12 21:23
There seems to be a regression here - roles are always displayed in messages despite them being deactivated in settings.
v5.0.3 - Node v14.20.0

**Comment by dicer** [comment] 2022-09-10 14:26
Same here with 5.1.1
