### ISSUE TITLE
Unable to update the program

### ISSUE THREAD

**Issue by vokhlebalov** [RocketChat/Rocket.Chat#23183] opened 2021-09-13 07:53 UTC
Every time I launch the chat I get the notification about to update the program. I accept it and after this nothing happens. Version 3.2.2

**Comment by ankar84** [comment] 2021-09-13 09:14
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670

**Closed by ankar84** 2021-09-13 09:14 UTC
