### ISSUE TITLE
CSV import bug

### ISSUE THREAD

**Issue by SomebodyOdd** [RocketChat/Rocket.Chat#12655] opened 2018-11-19 10:41 UTC
### Description:

Importing CSV doesn't work if users.csv contains certain line

### Steps to reproduce:

1. Create users.csv with that line
`aaa.bbb.cccd,abc@aa.aa,aaa bbb ccc`

2. Package it in zip

3. Try to import that zip

### Expected behavior:

Importing should just go through

### Actual behavior:

Nothing happens

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: Linux
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v8.11.3
- MongoDB Version: ???

### Additional context

There is some strange error in JS console log ([rocket-browser.log](https://github.com/RocketChat/Rocket.Chat/files/2594883/rocket-browser.log)) in the moment of clicking "Start importing" button, that could be a place for bug.

### Relevant logs:
Nothing special in server log.

**Comment by reetp** [comment] 2018-11-21 19:51
From the looks  of you logs it seems the parser doesn't like your format, but as you have obscured that it is hard to tell why.

>Uncaught Error: Syntax error, unrecognized expression: [name=aaa_bbb.cccd]

I'd personally go and sort your https issues first as well:

>:3000/home:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.

https://developers.google.com/web/updates/2016/10/avoid-not-secure-warn

**Comment by reetp** [comment] 2018-11-21 19:54
PS - I would also generate a simple test file with some really basic dummy data and see if it works to narrow down your issue.

Use the few lines from here:
https://rocket.chat/docs/administrator-guides/import/csv/

**Comment by reetp** [comment] 2018-11-24 01:57
I presume you mean like:
`joe..blogs `

I am sure there is an issue somewhere on names containing two or more dots just recently. Can you have a search through issues please?

**Comment by frdmn** [comment] 2018-11-27 12:41
Can confirm.

Example `users.zip` attached below to reproduce the issue.

[users.zip](https://github.com/RocketChat/Rocket.Chat/files/2619930/users.zip)

**Comment by antkaz** [comment] 2019-10-29 07:40
Hello.
Import works very poorly. I'm trying to import a small file, but as a result I get an error. Even when I try to import the file above, I get an error. After several attempts, the file can be downloaded, but preparing is empty.
Also after import I tried to import again, but I see it
![image](https://user-images.githubusercontent.com/19654261/67746889-46ddac00-fa49-11e9-94cb-256ebc2b1f70.png)

Version RC 2.1.0

**Comment by igor523** [comment] 2019-10-29 07:51
It's really amusing to see, that bug, that i reported 11 months ago with really simple steps to reproduce (and in that time i already switched to another job where they don't use rocket chat, lol) is still there, open and beign confirmed by @antkaz ... Okay...

**Comment by pierre-lehnen-rc** [comment] 2019-10-30 16:46
@antkaz what version of Rocket.Chat are you using? I've tried the zip file attached in a comment above and it's working properly on the current version.

**Comment by antkaz** [comment] 2019-11-01 06:15
Okay, thanks. I will check import again. There may be a problem on my side, since locally everything works

**Comment by pierre-lehnen-rc** [comment] 2020-04-07 19:00
I'll close this issue since the problem has been fixed.

**Closed by pierre-lehnen-rc** 2020-04-07 19:00 UTC
