### ISSUE TITLE
Improve load time

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7602] opened 2017-07-30 15:24 UTC
Version: 0.57.2

The current load time is around 10-12 seconds. It would be great to get that down to 3-5 seconds.

**Comment by marco-aa** [comment] 2017-07-31 22:59
Hi @danieljhochman :)

Related to which system / setup / config ?
I have measured a base-line from the smallest Digital Ocean Droplet with 512 Ram running a new installed 0.57.2 rocket.chat on Ubuntu 16.0.4 located in FFM - this takes 3-5 seconds to load the login screen.

**Comment by danieljhochman** [comment] 2017-08-01 20:03
@marco-aa - what about when you are already logged in? My console in chrome shows a waterfall of about 10 seconds.

**Comment by marco-aa** [comment] 2017-08-01 20:34
@danieljhochman i gave it a try and logged in ;) what a did while i was logged in ->>i did a page-reload and used in the "developer console" the "performance" tab and i pressed "start profiling and reload page"
I did this 3-4 times and it took at max 4500 ms

**Comment by jszaszvari** [comment] 2017-08-01 23:09
. Mine is less than 5 seconds. Sound like the hardware you are running it on is causing the delays.

**Comment by marco-aa** [comment] 2017-08-02 00:07
@jszaszvari of course this is a good point ;) 
I would recommend to have a test against the same server so we have the same base line 
I tested against https://demo.rocket.chat/direct/-D-Ray ... a empty dialog for 3-4 time it took around 6,5 seconds.
I would recommend @danieljhochman do give some details about his setup and how we could measure in a (more) reproducible way

**Comment by danieljhochman** [comment] 2017-08-06 09:09
@marco-aa @jszaszvari  - I'm also testing with https://demo.rocket.chat . The first load in a fresh browser can take over 10 seconds. Subsequent loads take around 6-8 seconds.

**Comment by jszaszvari** [comment] 2017-08-06 09:10
Keep in mind though the demo server most likely has 10s of thousands of
users

**Comment by danieljhochman** [comment] 2017-08-06 09:12
OK, but that's bad design. It shouldn't load all the users until they are needed. We plan to use RC with 5 million users loaded in very soon.

**Comment by jszaszvari** [comment] 2017-08-06 15:12
It doesn't load them all until needed, but more a case of its a demo server that's used to test and play for things. 

5 million? Really? That seems a bit infeasible considering the largest and most active chat networks in in the world don't even top 100k active users at once.. 

freenode – around 99k users at peak hours.

IRCNet – around 44k users at peak hours.

QuakeNet – around 36k users at peak hours.

EFnet – around 26k users at peak hours.

Undernet – around 25k users at peak hours.

Rizon – around 25k users at peak hours

Where are these 5 million people coming from? 

I'm not really sure there's any product out there that would service 5 million people without heavy custom development and millions of dollars of investment in hardware to run it. 

We've got 2 to 3 seconds initial load times on a server with 1200 concurrent active users which is more than suitable. 

What other products are there that are free and out of the box would support that kind of load?

**Comment by danieljhochman** [comment] 2017-08-06 15:14
We won't have anywhere near that number of users concurrently. I was referring to total number of users in the DB who I can choose to possibly direct message. That's how many we have.

**Comment by marco-aa** [comment] 2017-08-06 15:22
Well @jszaszvari  i agree at your numbers.
@danieljhochman - i have a look at rocket.chat because we have up to 100k Users and at peak 250-500 in Chat - what i plan to do, is  to embed RC with REST-Api thats means i'll not fill up the system with 100k Users - the users will be added at login and removed over timer including the messages. Maybe this could be usefull for you too (if in your use-case the direct message can be deletet, same for direct rooms and user data in the mongo db) - So the system/service will only serve chat for the users wich are more or less active ...

**Comment by danieljhochman** [comment] 2017-08-09 14:34
@marco-aa - we will have around 100-200 chat rooms each having between 5-200 concurrent users. Then, we will also use RC as a direct messaging system (as you described) for a userbase of 5M, but not anywhere near that number of concurrent users. Probably somewhere in the 100s or 1000s of concurrent.

Anyways, this is getting off-topic from the main issue here which is load time. No idea why https://demo.rocket.chat takes us 6-8 seconds (on a clean load incognito) and it takes you much less.

**Comment by marco-aa** [comment] 2017-08-14 10:38
Dear @danieljhochman,

i checked my average ping time - it's around 120 ms to demo.rocket.chat.

I added a screen chrome incognito non cache sorted by time - it's around 4 second. Maybe you can do the same to compare. 1 Did the uncached reload a round 10 time max. was 6.5 seconds - average around 4.5 seconds for around 24 requests.

![perf-test-2017-08-13 22_38_14-rocket chat](https://user-images.githubusercontent.com/8101156/29253297-ec4f460a-8078-11e7-93eb-8ff86e1c4f68.png)

**Comment by danieljhochman** [comment] 2017-08-14 11:16
@marco-aa  - can you do the same thing when logged in and on a first time load (incognito) ?

**Comment by marco-aa** [comment] 2017-08-14 20:35
Hi @danieljhochman i did a login and did a reload https://demo.rocket.chat/home with cleard cache.

![perf-test-2nd-2017-08-13 22_38_14-rocket chat](https://user-images.githubusercontent.com/8101156/29290575-dee11c46-8140-11e7-9b31-ea5f7085a315.png)

**Comment by graywolf336** [comment] 2018-02-06 00:15
Linking for more detailed look: https://forums.rocket.chat/t/slow-client-load-time-an-analysis/55

**Comment by yevgenydevine** [comment] 2018-11-04 10:41
16 seconds before RC becomes usable.
![rc-performance](https://user-images.githubusercontent.com/42466951/47963056-3ada2c80-e037-11e8-8536-3a72b6a41a12.jpg)

**Comment by ggazzo** [comment] 2019-10-17 23:41
Just checking the issue, and I thinks I had better numbers... could you test again? thanks

![image](https://user-images.githubusercontent.com/5263975/67055365-41fe2b80-f11e-11e9-9cf4-da00263617ec.png)

**Comment by Sing-Li** [comment] 2019-11-28 18:31
Work is continuing to improve this. We are moving to React and dynamic imports to load only the modules that are needed.

Closing the issue for now.

**Closed by Sing-Li** 2019-11-28 18:31 UTC
Labels: subj: performance, subj: ui/ux, type: improvement
