### ISSUE TITLE
Error Page after clicking on user for direct message

### ISSUE THREAD

**Issue by hilite24** [RocketChat/Rocket.Chat#17300] opened 2020-04-14 14:56 UTC
### Description:

When clicking on a user profile to write a direct message you get the 404 Oops, page not found.
**Click to Create Direct Message** option, which disables the user profile tab, has to be enabled.

### Steps to reproduce:

1. Make sure **Click to Create Direct Message** option is enabled. Administration>Layout>User Interface
2. Click on any channel or direct message
3. Click on a user by searching one in the Members tab or click directly on a user from a written message in the channel

It happens in Web app and Windows Desktop App.

### Expected behavior:

Opens a direct message with the selected user.

### Actual behavior:

Opens the 404 page :
Oops, page not found
Sorry, page you requested does not exist or was deleted!

![image](https://user-images.githubusercontent.com/32393825/79238078-3aba9f00-7e6f-11ea-9cab-4220a3f478c9.png)

![image](https://user-images.githubusercontent.com/32393825/79238103-460dca80-7e6f-11ea-9f3f-7c5fdc28b391.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.0
- Operating System: Ubuntu 18.04.4 LTS
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Coulnd't find info except that it is enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Firefox 74.0
- Operating System: Windows 10 

### Additional context

If **Click to Create Direct Message** option is disabled, it works as intended.
You click on an user, it opens a profile tab and then after clicking on the **conversation** button it opens the direct message with that user.

**Comment by luixxiul** [comment] 2020-04-14 16:39
Is this same as https://github.com/RocketChat/Rocket.Chat/issues/17247 ? cc: @pierre-lehnen-rc (#17275)

**Comment by pierre-lehnen-rc** [comment] 2020-04-14 17:15
It is!
Closing as duplicate of #17247

**Closed by pierre-lehnen-rc** 2020-04-14 17:15 UTC
