### ISSUE TITLE
Unable to change avatar (after snapd auto-update to 6.2.1)  6.2.2 still the same

### ISSUE THREAD

**Issue by lawipac** [RocketChat/Rocket.Chat#29309] opened 2023-05-21 05:33 UTC
### Description:

Without any configuration changes, all of a sudden, the avatar cannot be updated.

### Steps to reproduce:

1.  upload a new image to a user
2.  click save changes
3.  it shows oops 

### Expected behavior:

successfully change avatar

### Actual behavior:

Mobile App client

![2023-05-21_15-23-34_IMG_1865](https://github.com/RocketChat/Rocket.Chat/assets/10069433/82faab47-299c-4370-8eeb-96d9a1547c8f)

Desktop Client

![Snag_52d8168](https://github.com/RocketChat/Rocket.Chat/assets/10069433/64643708-d35c-4ad8-8971-3166039c4078)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.2.2 (snap)
- Operating System:  ubuntu 22.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog:  unknown
- NodeJS Version: 14.21.2 -x64
- MongoDB Version: 5.0.15
```
|  Rocket.Chat Version: 6.2.2                    | 
|       NodeJS Version: 14.21.2 - x64            | 
|      MongoDB Version: 5.0.15                   | 
|       MongoDB Engine: wiredTiger               | 
|             Platform: linux                    | 
|         Process Port: 3000                     | 
|             Site URL: https://xxxx  | 
|     ReplicaSet OpLog: Enabled                  | 
|          Commit Hash: d2f54e5b88               | 
|        Commit Branch: HEAD  
```
### Client Setup Information

- Desktop App or Browser Version:  3.9.4
- Operating System: Windws 11

- ios app :  4.38.0.42195
- Operating System: ios 
### Relevant logs:

logfile shows

```
{
  "level": 50,
  "time": "2023-05-21T01:35:57.710Z",
  "pid": 19391,
  "hostname": "localost",
  "name": "System",
  "msg": "ENOENT: no such file or directory, stat '/media/chat/dQBXNHE78RHEs7TcA'",
  "err": {
    "type": "Error",
    "message": "ENOENT: no such file or directory, stat '/media/chat/dQBXNHE78RHEs7TcA'",
    "stack": "Error: ENOENT: no such file or directory, stat '/media/chat/dQBXNHE78RHEs7TcA'<br> => awaited here:<br>    at Function.Promise.await (/snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at server/ufs/ufs-local.ts:72:20<br>    at /snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/file-upload/server/lib/FileUpload.ts:677:4<br>    at /snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/lib/server/functions/setUserAvatar.ts:105:15<br>    at /snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/api/server/v1/misc.ts:557:17<br>    at /snap/rocketchat-server/1557/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "stat",
    "path": "/media/chat/dQBXNHE78RHEs7TcA"
  }
}
```

**Comment by jw1892626** [comment] 2023-05-21 23:14
Having same issue.  Have to manually remove entry in "rocketchat_avatars" collection and unset avatarOrigin and avatarETag properties on the user to be able to upload a new avatar.

**Comment by debdutdeb** [comment] 2023-05-22 10:16
Sorta duplicate of https://github.com/RocketChat/Rocket.Chat/issues/29266

**Comment by debdutdeb** [comment] 2023-05-22 10:16
Closing in favour of that, fixing that should fix this one as well.

**Closed by debdutdeb** 2023-05-22 10:16 UTC
