### ISSUE TITLE
Messages are not visible on the channel

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#19810] opened 2020-12-09 11:44 UTC
### Description:

In some circumstances with threads all or most messages disappear from the channel main view. Scroll bar disappears too so you cannot update the view.
You can still make searches to messages even when they are not visible, so data flows seem to be working just fine.

This looks like to be a pagination problem in the main channel view.

Sometimes F5 helps (actually this often makes it also worse), sometimes clearing browser client cache helps, sometimes leaving and rejoining the channel helps.

You can enforce the scrollbar / reload by zoom in your browser so that existing visible messages overflow available space. At this point scrollbar and scroll functionality gets activated and you can again see the missing messages.

Another workaround seems to be enabling threaded messages on the main view, scrolling up a bit so that more messages get loaded, and then setting threads back to normal mode under personal settings. After this you can scroll again for old messages in normal view. Note that if you don't load more messages, all previously missing messages disappear again.

It seems that the issue is triggered on any channels that have very long threads in them. We suspect that this happens when there are more new messages in the threads in total than there are on the actual main channel. These normally not rendered messages are still able to clean up the channel of most messages in it, and main view is getting handled like it had only few messages; not enough to activate loading of older messages.

And lastly, as a case confirming way of getting around the issue, spamming new messages on the main channel view eventually pushes a last triggering invisible threaded message out of the screen. This is easier to achieve when .load-more-element has been increased in size like in the workaround example mentioned below.

Screen sizes and scaling play greatly into this issue and it becomes active only on slightly bigger screens. Laptops are mostly not affected. There are always _some_ messages visible and on the small scale screens they are close enough to top to trigger the scrollbar and action to load more messages.

### Steps to reproduce:

1. Go into a threaded view of a thread with lots of messages
2. Visit other channels
3. Come back to original channel

### Expected behavior:

All messages are visible

### Actual behavior:

Only few messages are visible. You don't see scrollbar and cannot scroll up for more messages.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System:  CentOS7
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog: yes
- NodeJS Version: 12.18.4
- MongoDB Version: 3.6

### Client Setup Information

- Desktop App or Browser Version: Firefox, Chrome, Desktop client (macOS)
- Operating System: Linux, macOS

### Additional context

I spotted this error in the browser F12 console view:
![Screenshot from 2020-12-09 10-19-43](https://user-images.githubusercontent.com/6958942/101625563-407b7b00-3a24-11eb-8b4a-cc5219e85cb0.png)

**Comment by Gummikavalier** [comment] 2020-12-09 18:00
Workaround custom CSS to ease the use of malfunctioning channels. No need for zoom-in/zoom-out tricks.

This increases the size of message loading activation area on top of the channel so that scrollbar gets activated. Users can scroll up to load more messages, which then renders invisible messages visible again. 

```/* Trick */
.load-more {
  position: relative;
  height: 80rem !important;
}
```

**Comment by Gummikavalier** [comment] 2020-12-17 11:55
Probably related to the origin of this issue we have also detected somewhat rare another issue where the user's channel listing pane content immediately vanishes and also changes the icon frame on top of it black. Sorry for no pic for that, it was not my computer I used for testing.

This situation is not fully recoverable with ctrl-f5 or refresh, as it repeats immediately after it has started occurring in the first place when user enters some threads or scrolls up in the channel messages view.

Only clearing the browser cache helps to cure the condition. Changing zoom levels or window size did not have effect for its occurrence after it had started, implying that there is some kind of cache corruption or incompatibility occurring during loading of threaded messages.

I was able to trigger this behaviour twice by switching personal layout modes from normal -> compact -> cozy and scrolling around, and eventually switching back to normal mode, after which it triggered every time I scrolled around the channel messages view or visited a certain long tread.

**Comment by Gummikavalier** [comment] 2020-12-18 10:52
I got a test environment built so here are screenshots of the original issue of disappearing messages.

What you should see:
![Screenshot from 2020-12-18 12-44-41](https://user-images.githubusercontent.com/6958942/102606552-91c7f080-412f-11eb-821f-6aa3c4cf6090.png)

What you get:
![Screenshot from 2020-12-18 12-43-55](https://user-images.githubusercontent.com/6958942/102606567-97bdd180-412f-11eb-9334-4d3412f45f4a.png)

You get all messages visible again by simply zooming in and out as well as by momentarily resizing browser window to very small to trigger reloading messages.

**Comment by didierm** [comment] 2021-01-23 17:10
We *seem* to experience the same issue (**entirely** blank/empty channels, randomly irrespective of user account, browser or dedicated client, channel, etc.) for the past few weeks.
No server-side error messages are logged (RC v3.9.3).

Our workaround is to use the message search function, searching for an existing string from an older message.
This recovers/redraws the channel's messages history.

Very awkward, as this bug has a serious impact on UX.

**Comment by Gummikavalier** [comment] 2021-01-25 08:11
@ggazzo I just tested with 3.11.0-rc.0 and the issue is even worse; adjusting browser window size to trigger scroll bar does not work anymore and nor does the load-more element resize trick.

Above Didierm's search trick is the only way to get the missing messages visible, but jump to recent messages clears them up again. Using show threaded messages on the main channel works though, and will be the only way to go.

![Screenshot from 2021-01-25 10-07-44](https://user-images.githubusercontent.com/6958942/105677986-430f3280-5ef5-11eb-98f7-8b17a05d355c.png)

![Screenshot from 2021-01-25 10-06-25](https://user-images.githubusercontent.com/6958942/105677832-0b07ef80-5ef5-11eb-9ad1-974e367a7739.png)

**Comment by didierm** [comment] 2021-01-30 10:34
This issue might be related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/1859 ?

Off-topic : 

We are not only experiencing this quite serious UX issue, directly affecting a core functionality of RocketChat ; we also experience loss of another core functionality : OTR ( issue #20074 since 3.10.0 ; although we refrain from installing versions .01 and .1, issue is still present in current 3.10.5).

Such heavy-impact regressions (with no apparent attention of the devs) do not bode well for current and future stability, and might raise concerns with our users concerning continued deployment.

**Comment by Gummikavalier** [comment] 2021-01-30 13:21
I think it definitely could be related, especially if you have threads in those direct messages.

I'm in under the impression (just reading between lines) that the devs are rewriting whole threads implementation. That'd explain why there is so little visible activity on behalf of these layout issues of missing messages and sometimes even top toolbar buttons. Fixes will probably land in one big update and are not marked into milestones of coming versions.

What seems to be quite effective workaround for now is enabling all messages as visible on the channel main view in under the personal settings, and then clearing up cache (browser or client). When the cache gets poisoned the issues seem to stick regardless of the view settings, but after the cleanup I haven't been able to reproduce any of the issues so far.

**Comment by Gummikavalier** [comment] 2021-02-01 10:04
Issue still active in 3.11.0.

**Comment by Gummikavalier** [comment] 2021-02-03 08:30
We can confirm that personal option `Show thread messages in the main thread`
![Screenshot from 2021-01-22 07-50-21](https://user-images.githubusercontent.com/6958942/106718317-92e2ad80-6609-11eb-9b89-82b0c8ee3d75.png)
helps with all of the following issues:

1. All window top buttons disappear completely in both browser and desktop client after doing searches in certain conditions.
2. All channels disappear from the channel pane and top icons change their color
3. Longer threads than what current window size can contain on the screen prevent loading of older messages on the channel main view.

Please note that due to cache poisoning after the issues 1 and 2 have begun, user must clear the cache of the browser for the workaround to become effective.
Also on Mac desktop client the user may have to clear the cache of Safari along iwth the cache of desktop client (we suspect they might share some parts of the webkit browser engine/cache).

**Comment by Bengrunt** [comment] 2021-02-22 08:24
Hello there,

We're also experiencing this issue which is really detrimental to user experience.
Running v3.11.1 on Kubernetes.

**Comment by Gummikavalier** [comment] 2021-02-22 10:20
There seems to be quite a lot changes in threads and messages handling incoming in 3.12.0 so I'm hopeful. :)

**Comment by didierm** [comment] 2021-02-22 10:28
Indeed.
It would be nice for RC-developers to remove all doubt, and cofnirm or deny whether this blocker relates to their (past or currrent) changes.

**Comment by Gummikavalier** [comment] 2021-02-23 10:52
I tested RC 3.12.0-rc1 and this issue seems to be fixed in version 3.12.

**Comment by JoshMcCullough** [comment] 2021-02-23 16:12
> Workaround custom CSS to ease the use of malfunctioning channels. No need for zoom-in/zoom-out tricks.
> 
> This increases the size of message loading activation area on top of the channel so that scrollbar gets activated. Users can scroll up to load more messages, which then renders invisible messages visible again.
> 
> ```
> .load-more {
>   position: relative;
>   height: 60rem !important;
> }
> ```

This worked for me as a temporary workaround.

**Comment by ggazzo** [comment] 2021-02-25 13:19
I think we fixed that by 'mistake' here: https://github.com/RocketChat/Rocket.Chat/pull/20826/files so I will close this issue, but any problem, please let me know ;)

**Closed by ggazzo** 2021-02-25 13:19 UTC

**Comment by Gummikavalier** [comment] 2021-02-25 14:33
Thanks! :) We'll test next time with 3.11.2 when it is released. Then again with 3.12.x versions.
