### ISSUE TITLE
SlackBridge - Slack -> RC File Attachments not working

### ISSUE THREAD

**Issue by mrplow** [RocketChat/Rocket.Chat#10002] opened 2018-03-04 22:38 UTC
### Description:

Uploading a file from a synced private channel in slack isn't working. Messages sync 2-way fine 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Debian 8.10 64bit
* Deployment Method(snap/docker/tar/etc): docker-compose
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.3
* mongoDB Version: 3.4.13

### Steps to Reproduce:

1. Setup RC to sync with Slack by putting in your slack bot token 
2. Test by adding your bot to a channel in slack and send a message
3. Upload a file in slack, nothing comes across in RC

### Expected behavior:

The same file to show in RC

### Actual behavior:

Nothing

### Relevant logs:
`Exception in callback of async function: Error: Meteor.userId can only be invoked in method calls or publications.     at AccountsServer.userId (/app/bundle/programs/server/packages/accounts-base.js:516:35)     at AccountsServer.user (/app/bundle/programs/server/packages/accounts-base.js:125:23)     at Object.Meteor.user (/app/bundle/programs/server/packages/accounts-base.js:340:19)     at Filter.validateFileUpload [as onCheck] (/app/bundle/programs/server/packages/rocketchat_file-upload.js:95:25)     at Filter.check (/app/bundle/programs/server/packages/jalik_ufs.js:595:53)     at FileUploadClass.insert (/app/bundle/programs/server/packages/rocketchat_file-upload.js:590:14)     at requestModule.get.Meteor.bindEnvironment.stream (/app/bundle/programs/server/packages/rocketchat_slackbridge.js:857:17)     at runWithEnvironment (packages/meteor.js:1240:24)  `

I checked my bot's setting and it seems correct. I switched from external to internal hubot. I installed a fresh RC to check my Permissions settings (what a pain since the users aren't showing in the same order since anonymous and leader are newer) (also checking a permissions box by accident is very easy and not obvious if using a touch screen).
Anyways nothing helped and I always receive the same error.

**Comment by nedbase-jesse** [comment] 2018-05-24 08:10
I noticed that when I use /slackbridge-import it did import the pictures from slack to rocketchat. First I noticed that the Maximum File Upload Size (in bytes) at the File Upload settings section, was to small for certain pictures/files. I increased it and ran /slackbridge-import again and more pictures imported

**Comment by mmillioud** [comment] 2018-11-20 16:06
The problem is the same on the other side, meaning that if a file is uploaded on the Slack channel, it is not visible on the Rocket.Chat side. I suppose this bug was only making reference to file upload in Rocket.Chat not visible in Slack channel or was it both way ? Is it planned to fix those bugs because this is pretty annoying, we can't use Slack integration in this case, because file upload in channels is pretty common, still not working with 0.71.1. Any plan to fix this soon ?

**Comment by Hudell** [comment] 2018-11-20 16:14
When a file is uploaded on slack, you should be getting a link to download it on Rocket.Chat. Do you get any kind of error message on the logs?

**Comment by Hudell** [comment] 2018-11-20 16:48
No, that is unrelated. I'll run some tests here to see if I can find anything wrong.

**Comment by mmillioud** [comment] 2018-11-21 08:56
Did it run well with your tests ? Is there some more specific logs I can check except /var/log/syslog ?

**Comment by Hudell** [comment] 2018-12-03 20:16
I've confirmed the bug: it only happens with newer data. A few months ago slack change the structure in which they store their files, that is probably what is causing this issue.

**Comment by nylen** [comment] 2019-01-25 23:34
any update on this? what part of the code can we look in to help?

**Comment by L3nny5** [comment] 2019-04-12 10:48
Any idea when this will be fixed? It would really help us to migrate from Slack to Rocket.Chat.

**Comment by rodrigok** [comment] 2019-04-29 17:32
Closed via https://github.com/RocketChat/Rocket.Chat/pull/14273

**Closed by rodrigok** 2019-04-29 17:32 UTC
Labels: feat: slackbridge, stat: waiting PR merge, type: bug

**Comment by L3nny5** [comment] 2019-05-14 13:01
For me it does not seem to be fixed. Now I get a Link displayed in the channel, which is better. However it is not displaying it. Why can't Rocket.Chat import the file which is displayed in Slack?
