### ISSUE TITLE
[BUG] Spreading the text input line under certain conditions.

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat#12039] opened 2018-09-13 07:24 UTC
Version of Rocket.Chat Server: 0.69.0 - 0.69.2
Operating System: Debian 8
Deployment Method: tar
Number of Running Instances: 1
DB Replicaset Oplog: -
NodeJS Version: 8.11.3 - x64
MongoDB Version: 3.2.21

Under certain conditions, the text input line can expand from one line to several. There are specific conditions: 
1. If there are two consecutive calls to the user through @ in the channel, 
2. If the panel with the downloaded files from this channel is opened bottom in Сhrome.

![2](https://user-images.githubusercontent.com/18574776/45473236-38e2a400-b73f-11e8-9a6b-074b98070a88.png)

![1](https://user-images.githubusercontent.com/18574776/45473247-3ed88500-b73f-11e8-9139-f2fde60545d2.png)

**Comment by kaiiiiiiiii** [comment] 2018-09-13 08:06
Duplicate of #11904

// CC: @TwizzyDizzy

**Closed** 2018-09-13 08:12 UTC

**Comment by rsimai** [comment] 2018-10-24 08:13
for completeness, I can not duplicate the issue this way, but the issue https://github.com/RocketChat/Rocket.Chat/issues/11904 obviously persists.
