### ISSUE TITLE
File upload too slow / eating too much resources

### ISSUE THREAD

**Issue by ic5y** [RocketChat/Rocket.Chat#1519] opened 2015-11-30 09:35 UTC
When we try to send files to each other, a 90MB zip takes about 5-6 minute to send to the other person meanwhile eating constant 30-40% CPU. When another person at the same time try to send another one, the CPU goes up to 90%. Anythign we can do something about it?

**Comment by engelgabriel** [comment] 2015-11-30 12:59
We need to finish the S3 and FileSystem support for file sharing. Uploaded files currently are stored at MongoDB.

**Comment by engelgabriel** [comment] 2015-11-30 13:20
Just to be clear, we are talking about server resources here, right? What is your deployment configuration looks like, can you describe in more details your current environment?

**Comment by miscs** [comment] 2016-01-18 19:36
are you guys still working on filesystem for file-uploads? I can´t find any other ticket than this one here. Thanks!

**Comment by engelgabriel** [comment] 2016-02-16 18:05
This is a duplicate of #1622

**Closed by engelgabriel** 2016-02-16 18:05 UTC
Labels: feat: file sharing, type: support
