### ISSUE TITLE
Link/credentials not properly passed to browser when clicking from Rocket.Chat.Electron

### ISSUE THREAD

**Issue by xenithorb** [RocketChat/Rocket.Chat#4150] opened 2016-08-30 20:26 UTC
Your Rocket.Chat version: 0.38.0
#### Problem:
- Rocket.Chat.Electron is configured to open links in external browsers (as it should be)
- Right now, when uploading a file or picture ("media object") - the room is populated with both a link "File Uploaded: " - and a download button  
  ![image](https://cloud.githubusercontent.com/assets/10273878/18105384/2d8c8cea-6ecd-11e6-86d7-c00098c89ddf.png)
- The link (from Rocket.Chat.Electron) opens up the link without credentials to be able to access the file through (forgive my term here but I'll call the "rocketchat media gateway") the rocketchat media gateway and the user is presented with an error message:  
  ![image](https://cloud.githubusercontent.com/assets/10273878/18105475/83706fe6-6ecd-11e6-814b-8c201e7f4e6d.png)
- According to @engelgabriel, this is due to the fact that the web browser does not have the proper (I assume time-sensitive) credentials as the actual logged-in client does
- Currently both the "File Uploaded" link, and download button icon, present a new browser window (They do the same thing, effectively)
#### What currently works:
- Logging into demo.rocket.chat for example, and clicking on the media from within the browser opens up a tab correctly and displays the media, no problem
#### What should happen:
- I believe that the follow the consistency of the application, the **File Uploaded:** link, should, _when opened from Rocket.Chat.Electron_ still open up an **external** browser window, and properly display the media
  - This should be done in such a way that **login credentials are asked for if the browser is not already authenticated**
- The download icon should present the save dialog, whereas now both paths (link and download buttom - _from within Rocket.Chat.Electron_ open an external browser window)

**Comment by FibreFoX** [comment] 2016-09-13 07:32
Is this some kind of duplicate of this bug?? https://github.com/RocketChat/Rocket.Chat/issues/3947

**Comment by xenithorb** [comment] 2016-09-13 15:08
Yes. It's definitely related.

**Comment by khobbits** [comment] 2016-09-14 15:52
Just came across this bug myself.  I noticed that if i navigated my browser to the site root, it would automatically log me in, then the electron link worked.
We just need to bounce quickly through the login authentication system, long enough to create a new session cookie, or present a login page if credentials can't be found.

**Comment by pascalrobert** [comment] 2016-10-18 15:02
We have the same problem. If a session is not established in the Web interface, the download link/button will open a window in the default browser (Safari or Chrome in our case) and the download will get "stuck".

**Comment by mgohin** [comment] 2016-11-28 09:51
+1

**Comment by xenithorb** [comment] 2016-12-24 23:15
3205250f31d5b0a2eadc1a3a6aa7e1c6c30910bf this commit seems to have partially fixed this issue:

>  - [ ] * I believe that the follow the consistency of the application, the File Uploaded: link, should, when opened from Rocket.Chat.Electron still open up an external browser window, and properly display the media 
> - [x] * The download icon should present the save dialog, whereas now both paths (link and download buttom - from within Rocket.Chat.Electron open an external browser window)

I'm not sure if the first part is to be taken into consideration, but if it's *not*, then realize now from the user's perspective, the app now generates an un-actionable link for files and other media, thus:

- [ ] Remove the link tags around "File Uploaded: \<file\>" when rendering on electron due to the fact that otherwise it generates a clickable link that does nothing.

**Comment by pauloriply** [comment] 2017-03-27 11:17
Where can I find the answer to this question? A lot of copies, but not much use!
Why is not downloading files from the desktop client?

**Comment by martinvonwittich** [comment] 2017-05-11 12:54
Someone just posted a file in a channel in our RocketChat installation, and nobody with a desktop client (tested on both Windows and Ubuntu) is able to download the file. Nothing is happening at all when you click the link - it doesn't open anything in the browser, and it also doesn't produce any JS exceptions in the app devtool. It works fine in the webview in the browser though. Is this caused by this bug, or should I file a new one?

**Comment by FibreFoX** [comment] 2017-05-11 13:03
@martinvonwittich Do they have the latest desktop client version?

**Comment by martinvonwittich** [comment] 2017-05-11 13:17
@FibreFoX nope, I just noticed that too - I was using `rocketchat 2.5.0`. After I updated to `rocketchat-desktop 2.7.0`, the download button works now (though the `File Uploaded: filename.txt` still does nothing, which I find a bit confusing). Thanks for the tip!

**Comment by xenithorb** [comment] 2017-05-11 14:48
The link is "broken" because it produces two `<a>` tags as follows: 

```html
<a href="/file-upload/QZp6Poi9qNScHfjsA/Clipboard - April 26, 2017 4:27 PM" target="_blank">File Uploaded: Clipboard - April 26, 2017 4:27 PM</a>
<a class="icon-download attachment-download-icon" href="/file-upload/QZp6Poi9qNScHfjsA/Clipboard - April 26, 2017 4:27 PM" target="_blank" download=""></a>
```

Note the download attribute on the second one, that's for the button. 

I don't know enough about web development to explain why it doesn't behave like a normal link and pass it off to an external browser, but I can tell you that it doesn't behave the same as the button because it's missing the `download=""` attribute. My personal take on this from a UX perspective is that a link should open like a link (i.e. link stylized text that is clickable should open in a browser) and an obvious download button should download the file as it currently does. 

@engelgabriel @Sing-Li  Is there any way we can get this fixed to have consistent behavior on the desktop client so the button and the link do the same thing, or my suggestion in the last paragraph?

**Comment by mddvul22** [comment] 2017-05-15 14:35
I'm using version 2.7.0 of the desktop client (for linux), and this is still broken.  Somebody just sent me a jpg.  I have "File Uploaded: images.jpg".  The image isn't shown, and I can't download it either.

**Comment by jdoose** [comment] 2018-03-14 07:01
I think this can be closed.
Works in 2.10.5

**Comment by JSzaszvari** [comment] 2018-03-14 10:00
@jdoose just tested and this works . 

Will close. Thanks

**Comment by JSzaszvari** [comment] 2018-03-14 10:00
@rocket-cat close

**Closed by JSzaszvari** 2018-03-14 10:00 UTC
Labels: type: bug
