### ISSUE TITLE
Web client unusable on Safari/iPad

### ISSUE THREAD

**Issue by nmagedman** [RocketChat/Rocket.Chat#22905] opened 2021-08-11 13:27 UTC
### Description:

When loading the web client, many key elements are not rendered and the page is unusable.

Affects Safari on iPad.  Reproduces **consistently** on some devices and **not-at-all** on others.  I'm still trying to nail down the determining factors.  When we've reproduced it, it's been on _physical_ hardware; we have not been able to reproduce it on BrowserStack.

### Steps to reproduce:

1. Go to https://open.rocket.chat/
2. Log in if not already

### Expected behavior:

The client should show the main UI, including the left sidebar with the list of rooms.

### Actual behavior:

The left sidebar does not appear.  The main, white panel showing the messages of a chat room is heavily cropped, showing the top of the word "Home"

<img width="771" alt="RC bug iPad Air 3 open rocket chat Nina " src="https://user-images.githubusercontent.com/1042298/129037175-a899b099-b448-41d5-ab3c-6944f8529f66.png">

### Server Setup Information:

The problem exists even on open.rocket.chat, so let's focus on that.

It also manifests on our servers.  Problem first discovered after we upgraded from 3.12.1 to 3.16.3.  Now running 3.17.0.

### Client Setup Information

- Desktop App or Browser Version: Safari

Reproducible on:
* iPad Air 3, v14.4, Safari
* iPad Air 3, v14.4, Chrome
* iPad Pro iOS v14.4
* MacBookPro 13-inch, Safari v14.0.3

Not reproducible on:
* iPad Mini 4 iOS 13.4.1
* iPad Mini 4 iOS 14.7.1
* any iPad on BrowserStack
* iPad 2019 iOS 14.x [@geekgonecrazy]

**Comment by geekgonecrazy** [comment] 2021-08-11 17:57
I'll also add not reproducible so far on regular sized(I think 2019) iPad running iOS 14.x

**Comment by bruno-fontoura** [comment] 2021-08-11 19:18
> I'll also add not reproducible so far on regular sized(I think 2019) iPad running iOS 14.x
> 
> So I'm guessing this might have some relation to screen size

Reported internally for further investigation. 
Agree that screen size/resolution might be a player here.

**Comment by ankar84** [comment] 2021-08-12 00:47
**This is definitely a front-end bug and it should be fixed.**
But iPad it's kind of mobile device and RocketChat ReactNative application works perfect on that.
My idea - mobile client for mobile device. Web version on mobile device could be not so comfortable as on desktop computer.

**Comment by nmagedman** [comment] 2021-08-12 11:23
**UPDATE:** I thought the bug was on Safari only, however it also manifests using Chrome on affected iPads.

![Chrome on iPad](https://user-images.githubusercontent.com/1042298/129188688-de5990fa-d84c-4cc9-b6df-f83315e14ee1.PNG)

**Comment by nmagedman** [comment] 2021-08-12 12:02
**UPDATE:** And we have a report of an affected user who is using Safari in a **Mac** (**not** an iPad!)
But Chrome works fine for him.

MacBook Pro (13-inch, 2020)
macOS Big Sur 11.2.1
Safari v14.0.3 (16610.4.3.1.4)
Built-in Retina Display 13.3-inch (2560 x 1600)

![Safari on Mac](https://user-images.githubusercontent.com/1042298/129193207-01c76142-6495-4273-b1ac-9df6831942af.png)

**Comment by nmagedman** [comment] 2021-08-12 14:52
@bruno-fontoura @fdellwing We upgraded our iPad Air 3 from 14.4 to 14.7 and that **solved the problem**!  However, the AppleWebKit version did not change in the upgrade, so apparently that is not the determining factor.  (In fact, the _only_ change to the UA was that `14_4` became `14_7`)

User Agent before:
```
Mozilla/5.0 (iPad; CPU OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/92.0.4515.90 Mobile/15E148 Safari/604.1
```

User Agent after:
```
Mozilla/5.0 (iPad; CPU OS 14_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/92.0.4515.90 Mobile/15E148 Safari/604.1
```

**Comment by bruno-fontoura** [comment] 2021-08-12 20:04
> @bruno-fontoura @fdellwing We upgraded our iPad Air 3 from 14.4 to 14.7 and that 🎉 🎉 **solved the problem**! 🎉 🎉
> 
> However, the AppleWebKit version did not change in the upgrade, so apparently that is not the determining factor. In fact, the _only_ change to the UA was that `14_4` became `14_7`.
> 
> User Agent before:
> 
> ```
> Mozilla/5.0 (iPad; CPU OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/92.0.4515.90 Mobile/15E148 Safari/604.1
> ```
> 
> User Agent after:
> 
> ```
> Mozilla/5.0 (iPad; CPU OS 14_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/92.0.4515.90 Mobile/15E148 Safari/604.1
> ```
> 
> So, we now have a **workaround** -- have the user upgrade (assuming that will solve the problem in all cases). However, it would be good to determine and fix the underlying problem.

Thank you for the update.

Indeed, identifying the root cause will help us prevent it from happening again in future versions.

**Comment by nmagedman** [comment] 2021-08-18 21:23
Any progress?

**Comment by aaronelliotross** [comment] 2021-09-01 14:03
I'll try to get more details about our users over here - but this bug is affecting many of our users on iOS.

**Comment by bruno-fontoura** [comment] 2021-09-03 20:24
Hi Team!

Our team recently released mobile version 4.19 for iOS devices [https://apps.apple.com/us/app/rocket-chat/id1148741252]
While this update won't particularly fix this issue, we ask that you please try this update and get back to us.

This issue is still under investigation and we will keep you updated here.

Thank you.

**Comment by pierreozoux** [comment] 2021-09-08 17:19
One of our user told us that his issue was resolved, maybe safari resolved it?

**Comment by dougfabris** [comment] 2021-09-08 18:54
> Any progress?

@nmagedman We are trying to reproduce the issue but without success! At this moment we strongly believe there's some issue related to the WebKit version present in iOS 14.4 and macOS 14.0.x. A solution for that is to use the iOS 14.5 or the latest and MacOS 14.1.x or the latest

@pierreozoux Can you share the safari and iOS/macOS version to help our findings?

**Comment by nmagedman** [comment] 2021-09-09 11:48
> MacOS 14.1.x or the latest

I believe you mean **Safari** 14.1.x or the latest

**Comment by pierreozoux** [comment] 2021-09-10 14:29
```
- OS : 11.5.2
- Safari : 14.1.2
```

**Comment by dougfabris** [comment] 2021-09-11 00:54
> ```
> - OS : 11.5.2
> - Safari : 14.1.2
> ```

This comment reinforces our thoughts about the versions

**Closed by dougfabris** 2021-09-11 00:54 UTC
