### ISSUE TITLE
Rocket Chat Dev Script Error

### ISSUE THREAD

**Issue by thekavikumar** [RocketChat/Rocket.Chat#29330] opened 2023-05-23 07:35 UTC
Hey there,

I was setting up rocket chat and tried this command " yarn dsv "
this issue occurred. Please help to solve this issue and also is there any fastest way to reach out?
![image](https://github.com/RocketChat/Rocket.Chat/assets/50093149/c35a83ee-3e0c-43ac-bd5e-e98e313571e6)

**Comment by debdutdeb** [comment] 2023-05-23 08:25
Please use open.rocket.chat or the forum to post questions like these. Github is reserved for bug reports and not general support items. Check out the team channels under gsoc2023, and provide as much information as possible in those posts like your operating system, system resources, yarn command status, documentation followed, etc.

Closing this, as it's not a bug.

**Closed by debdutdeb** 2023-05-23 08:25 UTC

**Comment by thekavikumar** [comment] 2023-05-23 08:35
@debdutdeb  where can i access the gsoc23 team channel?

**Comment by debdutdeb** [comment] 2023-05-23 08:46
On open.rocket.chat server.

**Comment by thekavikumar** [comment] 2023-05-23 08:49
@debdutdeb but people are not responding there! I tried
Can you help me setting up the rocket chat please?

**Comment by debdutdeb** [comment] 2023-05-23 08:57
I responded just now.
