### ISSUE TITLE
Windows client not updating

### ISSUE THREAD

**Issue by armirol** [RocketChat/Rocket.Chat#23592] opened 2021-10-29 22:10 UTC
I have the version 3.2.2 installed and each time i start the computer i have a message to update the client, but it never updates. How do i do that ?
Thx

**Comment by TheDigitalEagle** [comment] 2021-11-01 21:44
It has never worked. Just download the installer from the client releases to  update manually.

**Comment by ankar84** [comment] 2021-11-03 07:54
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670

**Closed by ankar84** 2021-11-03 07:54 UTC
