### ISSUE TITLE
Sending a file twice doesn't work (even after deleting the message)

### ISSUE THREAD

**Issue by xenithorb** [RocketChat/Rocket.Chat#3683] opened 2016-07-04 17:33 UTC
Your Rocket.Chat version: 0.35.0

1. The modal for sending a file does not appear if you attempt to send the same file a second time. 
  - This is probably intentional, but I'm noting it here in case it's not

2. More importantly, if you delete the message first, you *still* cannot send the file, it requires a refresh or in the case of Electron, (ctrl+r), in order to send the file again.
  - I believe that deleting a message should clear whatever is preventing the modal from appearing a second time. Or block based on a hash instead of a filename.

**Comment by monarch** [comment] 2016-07-04 17:35
Encountered Same issue on the Electron client in Windows 10 Pro 64-bit

**Comment by wtsarchive** [comment] 2016-07-04 20:04
All of my users have this (or similar) issue, not only on Electron, but on browsers as well. Trying to upload two different files in succession fails (it uploads the first file twice).

**Comment by wtsarchive** [comment] 2016-07-04 20:08
From my observation the issue is in the event handler of the confirmation popover (possibly a scoping issue in the code). It's just like even though a new popover is shown to the user, when he clicks the button the previous handler is called. That's why two seemingly unrelated actions (deleting a message and uploading a file) affect each other - because they both use the popover (`swal`, or Sweet Alert).

**Comment by MartinSchoeler** [comment] 2016-08-19 18:21
This issue has been fixed in the latest's releases

**Closed by MartinSchoeler** 2016-08-19 18:21 UTC
