### ISSUE TITLE
Setting for default channel is broken

### ISSUE THREAD

**Issue by Rohlik** [RocketChat/Rocket.Chat#7004] opened 2017-05-17 18:33 UTC
Rocket.Chat Version: 0.56.0 
Running Instances: 1
DB Replicaset OpLog: True
Node Version: 4.7.2.

In `/admin/rooms` I can see room with **Direct message** type and default **False**, but on side pannel is opposite setting.
Next wierd I think is, that I have two room with **Default=True**.

So, version 0.56.0 contains two bugs:
1.) Set default channel should be forbiden for **Direct message**
2.) Rooms table show wrong informations - two rooms with  **Default=True**

![image](https://cloud.githubusercontent.com/assets/2051154/26169626/c1a7df2c-3b3e-11e7-8f75-ef7975d73224.png)

**Comment by rodrigok** [comment] 2017-06-30 19:47
Can you guys check if it is fixed in our develop version?

**Comment by MartinSchoeler** [comment] 2017-07-06 20:58
Tested on develop and it's working. @Rohlik please reopen this if this issue happens again. Thanks!

**Comment by andreas-bulling** [comment] 2017-10-25 10:54
Broken again in 0.59.1 - there is no button to save the change.

**Comment by HanniAbu** [comment] 2017-10-31 17:13
Can confirm, this feature is again broken

**Comment by Rohlik** [comment] 2017-10-31 18:31
@MartinSchoeler Can you reopen this issue? Because I can't.

**Comment by HanniAbu** [comment] 2017-11-01 09:50
Yes, will be doing that today

**Comment by crsCR** [comment] 2017-11-22 00:52
Why is this issue Closed?

**Comment by HanniAbu** [comment] 2017-11-29 10:52
Thank you for reopening this Martin. As stated, the option to change settings within the admin panel is not working. When you click the edit icon for  "Default" and "Read Only Channel", the radio buttons are cut off. For all of them there is no option to save changes.

Rocket.Chat Version: 0.59.3
Running Instances: 1
DB Replicaset OpLog: False?
Node Version: 4.8.4

**Comment by crsCR** [comment] 2017-12-23 13:23
Being able to choose what channels can be set as default would seem like a required basic feature... No?

**Comment by rodrigok** [comment] 2017-12-23 20:19
@HanniAbu and @crsCR Version 0.59.6 fixed this issue. Can you check?

**Comment by ggazzo** [comment] 2018-05-26 01:39
I'm closing this issue because I'm confident that have no more this problem. Fell free to reopen if I'm mistaken

**Closed by ggazzo** 2018-05-26 01:39 UTC
Labels: subj: ui/ux, type: bug

**Comment by Rohlik** [comment] 2018-05-28 09:52
I test this issue today with build 0.65.0 and I can still set 2 rooms as default, which is wrong.
![image](https://user-images.githubusercontent.com/2051154/40608903-535d9fdc-626d-11e8-94c6-379ed6f3a8eb.png)

@ggazzo Can you re-open this issue please? I don't have permission to do that.

**Comment by ggazzo** [comment] 2018-05-29 16:32
@Rohlik its not a problem if you have 2 or more default channels(if you disagree, please tell us more why)... but the inconsistence between the list/roominfo exist no more, or exist?

**Comment by cjhille** [comment] 2020-02-10 20:00
Is this currently broken again? AFAIK there currently is no option for setting a channel to default in `/admin/rooms`.

**Comment by RAurelian** [comment] 2020-02-13 11:14
Hi,

Has this been solved? I`m on version 2.4.2 (ubuntu snap) and cannot find any way to make a channel default.

**Comment by eliotb** [comment] 2020-04-18 03:32
Still apparently a problem in 3.1.1? Lacks editable setting for Default
![Screenshot from 2020-04-18 15-07-30](https://user-images.githubusercontent.com/421383/79627109-a3fd2380-8189-11ea-95d1-2933bbc77d8c.png)

**Comment by moonstash** [comment] 2020-04-28 18:49
No solution to setting default rooms since 2017?? If there is an update on this, I'd love to know about it!

**Comment by jamiscs** [comment] 2020-04-29 14:19
> No solution to setting default rooms since 2017?? If there is an update on this, I'd love to know about it!

I've just updated to version 3.2.0 and seems fixed

![image](https://user-images.githubusercontent.com/38479089/80606855-264bda00-8a0b-11ea-9fd0-5b83759c1c6f.png)

**Comment by rodrigok** [comment] 2020-04-29 15:05
@moonstash and @eliotb please describe if you have any problems and which version you are using, since it's **not** a problem for a long time. You may need to check if you have the permission `view-room-administration` which is required to see that option.

**Comment by eliotb** [comment] 2020-04-29 21:51
@rodrigok,  yes I have that permission. You can see from my post 12 days ago what the UI looks like for me.  Version is 3.1.1
When you say "not a problem for a long time",   since what version is that?

**Comment by eliotb** [comment] 2020-04-29 22:02
Over here https://github.com/RocketChat/Rocket.Chat/issues/7007#issuecomment-620571402 is an image from 3.2.0 illustrating that the problem is still present.

**Comment by moonstash** [comment] 2020-04-29 22:03
I have no updated to the very recent 3.2 release yet. I'm on version 3.1.1 on snap. I'm willing to move over to a manual install so I can get new versions sooner though.

**Comment by eliotb** [comment] 2020-04-30 01:56
I can confirm that the update to 3.2 fixed this issue for me.
![Screenshot from 2020-04-30 13-49-36](https://user-images.githubusercontent.com/421383/80664272-6df56300-8aea-11ea-85a4-652fc0c0a2a5.png)

**Comment by angeltonio** [comment] 2020-05-11 20:28
Yes but i dont understand you have 3.2 version but wen i put sudo snap refresh rocketchat-server, the message says "the snap rocket chat server is not upgrade"...

**Comment by loxK** [comment] 2020-05-12 07:37
@angeltonio u need to use another channel:

To list channels:
``` 
snap info rocketchat-server
```
To use a specific channel (3.2.2 is available in 3.x/candidate):
```
snap refresh rocketchat-server --channel=3.x/candidate
```
