### ISSUE TITLE
Firefox Button Bug

### ISSUE THREAD

**Issue by Dawsey21** [RocketChat/Rocket.Chat#3764] opened 2016-07-13 12:23 UTC
**Version:** Unknown, noticed this on a live installation and confirmed by finding another and replicating the bug. 
**Browser:** Firefox (does not work on Chrome). I've only tested on these two.

**Steps to reproduce:**
1. Be on the login page, click on "Forgot your password"
2. Put something random ("a" for example) in the "Email" field and hit enter or "Reset Password"
3. Click "Back to login", "Reset Password" should now be appended to the "Submit" button like so -
![Image of Successful Reproduction](https://i.gyazo.com/e81cde2a6bd335dd273ee422c4691ac5.png)

**Note**
This also works for the "Register a new account" page element.

**Comment by MartinSchoeler** [comment] 2017-03-27 19:33
Duplicate of #2137

**Closed by MartinSchoeler** 2017-03-27 19:33 UTC
Labels: subj: ui/ux, type: bug
