### ISSUE TITLE
Can't open channel - Hebrew

### ISSUE THREAD

**Issue by blumlinnovate** [RocketChat/Rocket.Chat#28192] opened 2023-02-27 16:10 UTC
By creating a private channel I get an error: bad request - this happens when the channel name is in Hebrew

**Comment by dudanogueira** [comment] 2023-02-27 19:04
Hi! I tested this on latest 6.0.0-rc.2 and was able to reproduce this

**Please, when reporting an issue, provide all the requested informations**

I tried this word: אבא

Other languages will work as expected:
حب
愛

**Comment by blumlinnovate** [comment] 2023-02-28 08:33
![image](https://user-images.githubusercontent.com/105427726/221797150-504fa190-efe6-4cb5-af24-024b683792ba.png)

![image](https://user-images.githubusercontent.com/105427726/221797534-d784dc5f-b6b9-4b54-99b5-474db1fc0d6e.png)

**Comment by krsuumar** [comment] 2023-03-05 11:57
> אבא

Hi,

I am trying to replicate this issue, but not able to replicate. I followed the below steps;
1. Go to /admin/settings and then disable the "UTF8 Names Slugify" but not able to replicate
  
<img width="289" alt="image" src="https://user-images.githubusercontent.com/25521962/222958586-074fd786-f9e5-40f7-a72c-10f971fec32c.png">

2. Also I deleted the regex but not able to replicate.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/25521962/222958816-ea2166fe-6ee9-463a-b139-62840bbaf14b.png">

<img width="444" alt="image" src="https://user-images.githubusercontent.com/25521962/222958890-fd35d555-bcc4-489e-a283-db5301b992f1.png">


Version detail:
<img width="194" alt="image" src="https://user-images.githubusercontent.com/25521962/222958941-84ad3b8b-7d49-4cdd-9686-92f60f257904.png">

@dudanogueira @blumlinnovate Please guide me if I am missing anything so that i can replicate this issue.

**Comment by blumlinnovate** [comment] 2023-03-05 13:57
I don't know how I can help here , I didn't touch the admin area.  the only thing I can say that my version is just 3.2.3 and I don't see there are available updates , so this is the most updated version to me. you can see my screenshots above.

**Comment by IllTamer** [comment] 2023-03-10 08:15
> > אבא
> 
> Hi,
> 
> I am trying to replicate this issue, but not able to replicate. I followed the below steps;
> 
> 1. Go to /admin/settings and then disable the "UTF8 Names Slugify" but not able to replicate
> 
> <img alt="image" width="289" src="https://user-images.githubusercontent.com/25521962/222958586-074fd786-f9e5-40f7-a72c-10f971fec32c.png">
> 
> 2. Also I deleted the regex but not able to replicate.
> 
> <img alt="image" width="481" src="https://user-images.githubusercontent.com/25521962/222958816-ea2166fe-6ee9-463a-b139-62840bbaf14b.png">
> 
> <img alt="image" width="444" src="https://user-images.githubusercontent.com/25521962/222958890-fd35d555-bcc4-489e-a283-db5301b992f1.png">
> 
> Version detail: <img alt="image" width="194" src="https://user-images.githubusercontent.com/25521962/222958941-84ad3b8b-7d49-4cdd-9686-92f60f257904.png">
> 
> @dudanogueira @blumlinnovate Please guide me if I am missing anything so that i can replicate this issue.

Go to `/admin/settings/General` and set the RegExp to `.*` to match other characters, then you can create channels with name `愛` and `حب`. It looks like this issue has been fixed in the `6.0.0` release.

![image](https://user-images.githubusercontent.com/78360471/224260169-d1551f97-5ab3-4449-bc12-55f901cd8b86.png)

![image](https://user-images.githubusercontent.com/78360471/224260554-df0cba21-79d1-4d56-ba8a-21ca2f97182e.png)

**Comment by hugocostadev** [comment] 2023-06-19 14:28
It was fixed in the latest releases with the correct setting.

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Closed by hugocostadev** 2023-06-19 14:28 UTC
Labels: type: bug
