### ISSUE TITLE
Cannot post file (picture, video, sound,..) on mobile browser & IE

### ISSUE THREAD

**Issue by Cikcak** [RocketChat/Rocket.Chat#8712] opened 2017-10-30 13:58 UTC
### Server Setup Information:

* Version of Rocket.Chat Server 0.59.x
* Operating System: linux
* Deployment Method(snap/docker/tar/etc): snap/docker
* Number of Running Instances: 1

### Steps to Reproduce:

Text box down for post not reackt when tap to icon for insert file in the iOS browsers, the icon will not be displayed at all in the Android browsers and in the windows IE browser file can be selected, but not sent.

**Comment by marceloschmidt** [comment] 2017-10-30 13:58
[GitMate.io](https://gitmate.io) thinks possibly duplicate or related issues are #7714 (Oneclick deployment not working for heroku ), and #8422 (Can we record screen share in Rocket chat like audio and video??).

**Comment by MartinSchoeler** [comment] 2019-10-28 14:33
I could not reproduce this in the latest release, so I am going to close this issue. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks!

**Closed by MartinSchoeler** 2019-10-28 14:33 UTC
Labels: feat: file sharing, subj: ui/ux, type: bug
