### ISSUE TITLE
'Drag to upload file' overlay gets stuck and makes channel unusable 

### ISSUE THREAD

**Issue by nmummau** [RocketChat/Rocket.Chat#3160] opened 2016-05-06 19:30 UTC
Your Rocket.Chat version: 1.3.1
Chrome: 50.0.2661.94 m
Windows 7 Professional

Often times while I'm reading something that somebody wrote, I will use my cursor to highlight what they are saying. I can get pretty "clicky" when doing this. If you click on a highlighted segment of words and then click and drag, you will get the 'Drag to upload file' overlay. Often times (like 10 times throughout the day) this overlay gets stuck and disables the current channel/direct message I'm currently in. It requires shutting down the app and restarting the app.

This has happened to me in both Chrome and the native Rocket.Chat application. I'm mainly using the app though so that's where it happens most to me.

![image](https://cloud.githubusercontent.com/assets/10524529/15084121/71064cd8-139f-11e6-9ec0-08c00c3a9d62.png)

**Comment by nmummau** [comment] 2016-05-18 20:04
What's the status of this bug?

**Comment by AJ-Acevedo** [comment] 2016-05-24 03:25
I've been unable to reproduce this on demo.rocket.chat today.

demo.rocket.chat version: 0.31.0
Chrome Version: 50.0.2661.102 (64-bit)
Mac OS X version: 10.9.5

**Comment by klatys** [comment] 2016-07-07 08:59
My users have been reporting same issue but on Windows electron client - not only channel gets stuck but basically whole application and they have to restart it...

**Comment by engelgabriel** [comment] 2016-09-02 18:54
This seems to be fixed now, can you please confirm?

**Comment by engelgabriel** [comment] 2016-09-02 18:57
@MartinSchoeler please check if this is still a problem?

**Comment by nmummau** [comment] 2016-09-08 18:47
Happened again to me today.
![20160908-144621-inbox - nmummau clarkinc biz - microsoft outlook](https://cloud.githubusercontent.com/assets/10524529/18362270/20234050-75d3-11e6-9151-84fedc8bef3b.png)

**Comment by marceloschmidt** [comment] 2016-09-08 19:34
This happens in both windows and linux, but not on a Mac.

**Closed** 2016-09-08 21:05 UTC
Labels: type: bug
