### ISSUE TITLE
The avatar is not showing after the uploaded in the profile without reloading browser cache

### ISSUE THREAD

**Issue by sdelfi** [RocketChat/Rocket.Chat#12098] opened 2018-09-18 20:07 UTC
### Steps to reproduce:

1. Login. Not from admin account. It's important
2. Go to My Account - Profile - Upload new avatar
3. Reload chat tab
4. The avatar is displayed as standard (in the url of the image _dc = undefined)

If you log in as an administrator, then the uploaded user avatars are displayed correctly.
Similar problem when loading via Rest API - /api/v1/users.setAvatar.

### Server Setup Information:

Server Setup Information:
Version of Rocket.Chat Server: 0.69.2
Operating System: Centos 7
Deployment Method(snap/docker/tar/etc): docker and tar
Number of Running Instances: 1
DB Replicaset Oplog: 
Node Version: 8,9.3
mongoDB Version: 3,4,14

### Additional context

I tested on the self hosted server - in the docker and on vds, the version of the chat is 0.69.2 in both cases.

The problem is reproduced on https://open.rocket.chat/

I tried to turn off the cache for avatars in the settings - it does not help

**Comment by sdelfi** [comment] 2018-09-21 11:37
Yes, I click on this button. I'm using Google Chrome latest version. Through API, the problem is similar.

**Comment by piotrkochan** [comment] 2018-09-21 11:40
Turn on logs, check that target storage is writeable

**Comment by sdelfi** [comment] 2018-09-21 13:40
> Turn on logs, check that target storage is writeable

I checked again, it turned out that it is the browser cache. If you make hard reload in Chrome, the new avatar appears. 
But users will not do a hard reset to see the new avatar.
As I understand, to reset the cache the image is passed with the  "_dc" parameter, but now it is "undefined" and only sometimes the numbers are passed there.

I've gone to all the chats where I've tested and see a new avatar everywhere. After downloading the new-I have to reset the browser cache, which is not very logical.

Thanks

**Comment by localguru** [comment] 2018-09-25 06:33
Can confirm here on 0.69.2

**Comment by balcsida** [comment] 2018-10-02 11:27
We experience this with 0.70.0
All the avatar URLs look like this:
`https://example.com/static/avatar/username?_dc=undefined`

Note: We have CDN prefix set to `/static`

**Comment by balcsida** [comment] 2018-10-25 21:02
Hi @sdelfi, @localguru,

#12365 is merged to master and included in release 0.71.0-rc.0.
It seems that it resolved the issue for me.
Do you experience the same?

**Comment by sdelfi** [comment] 2018-10-26 07:46
@balcsida Yes, it looks like it solves the problem. Thank you

**Comment by oguhpereira** [comment] 2019-09-19 21:16
@tassoevan I tested on  [Open Rocket.chat  Server](https://open.rocket.chat/)  looks like it was solved.

**Comment by karl-in-office** [comment] 2019-10-04 02:51
@oguhpereira
> @tassoevan I tested on [Open Rocket.chat Server](https://open.rocket.chat/) looks like it was solved.

I also confirmed that this issue was solved with version 2.1.0.

**Closed** 2019-10-22 17:16 UTC
