### ISSUE TITLE
[BUG] Searchbar more options menu is not working

### ISSUE THREAD

**Issue by Himanshu664** [RocketChat/Rocket.Chat#24588] opened 2022-02-23 03:04 UTC
### Description:

when we click on searchbar and then click on message menu it is not functioning.

### Steps to reproduce:

1.  Go to Search
2.  Click on message menu

### Expected behavior:

https://user-images.githubusercontent.com/76220055/155254795-b227276e-7349-48ea-9724-a1f870b61fbb.mp4

### Actual behavior:

https://user-images.githubusercontent.com/76220055/155254785-32a6e1b4-36c9-4355-823b-b8906dcc17fe.mp4

### Server Setup Information:
Version of Rocket.Chat Server: 4.5.0-develop
Operating System: Linux ubuntu 20.04
NodeJS Version: v14.18.2
MongoDB Version: 4.4.4 / wiredTiger (oplog Enabled)

### Client Setup Information
Desktop App or Browser Version: Chrome 97.0.4692.99 (Official Build) (64-bit)
Operating System: Linux Ubuntu 20.04

**Comment by ankar84** [comment] 2022-02-23 04:37
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/22146

**Comment by dougfabris** [comment] 2022-04-04 13:21
Closing because it's duplicated!

**Closed by dougfabris** 2022-04-04 13:21 UTC
