### ISSUE TITLE
In mobile browser, the last typed message remains in the text entry box in all channels even after submitting or clearing.

### ISSUE THREAD

**Issue by Sentinelrv** [RocketChat/Rocket.Chat#9223] opened 2017-12-22 00:03 UTC
### Description:

This has been reported to me on both Android Chrome and Safari mobile. Desktop browser (at least Edge) is fine. In every channel the text entry box displays the last message that was typed, even if that message was already submitted or cleared.

### Server Setup Information:

* RocketChat 0.59.6
* Latest Docker

### Expected behavior:

Text should only appear in text entry box if a draft was saved.

### Actual behavior:

Text appears in text entry box on all channels whether a draft was clear or submitted/posted. It only seems to happen through mobile browser chat.

**Comment by karlprieb** [comment] 2018-01-04 17:51
Sorry @Sentinelrv but I can't reproduce this behavior on latest release.

Take a look:
![2018-01-04 15 49 33](https://user-images.githubusercontent.com/9200155/34577038-0e523168-f167-11e7-9701-fd3ffc6eaeb3.gif)

Can you test again on latest release?

Thank you!

**Comment by danielbressan** [comment] 2018-02-16 00:28
We've had this reported too and I was able to reproduce it:
1) send message
2) Hit home, and kill Android Chrome
3) Reopen chrome, should auto load last page back to message
4) input box still contains message text (even though you can see the message you sent before is still there)

All that said, I diffed our version with the latest and one of these lines is what fixed the problem (not sure what version added them), most likely 384 is the fix:
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/client/lib/chatMessages.js#L259
https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ui/client/lib/chatMessages.js#L384

I added those lines to our version and now it works!

Thanks!
Daniel -

**Comment by gabriellsh** [comment] 2020-02-06 17:16
Tested on open.rocket.chat (3.0.0), Galaxy S10, Chrome 78.0. Still happens. Did it just as @danielbressan described.

**Comment by gabriellsh** [comment] 2020-09-08 16:51
Tested again, 3.7.0-develop, Galaxy S20 Ultra, Galaxy S9+, no success in reproducing it. I'm closing this, if someone can still reproduce it, please open a new issue or comment down below.

**Closed by gabriellsh** 2020-09-08 16:51 UTC
Labels: stat: waiting response, subj: ui/ux, type: bug

**Comment by hosimaz** [comment] 2023-02-22 10:23
We have the same issue in Mac client as well.
Server version : 5.4.3
Client version: 3.9.19
