### ISSUE TITLE
Add Gender selection and cutom fields

### ISSUE THREAD

**Issue by Ya-Ri** [RocketChat/Rocket.Chat#3523] opened 2016-06-11 18:20 UTC
Your Rocket.Chat version: 0.33

Ya-Ri commented 21 days ago • edited

Hi,

i find it will be nice to let users select fields (gender,age,country...) during signup and existing users can select it by editing their profile and also make the username color for female and male, 
we use rocket chat at the french "nuit debout" movement
https://chat.nuitdebout.fr/
Many have subscribed but there is a lack of informations on their profile.

By the way, jarvis bot has been replaced by aiva.

thanks you for rocket.chat

Regards,

YaRi

**Comment by geekgonecrazy** [comment] 2016-06-14 19:45
Dupe of: #2046

**Closed by geekgonecrazy** 2016-06-14 19:45 UTC

**Comment by engelgabriel** [comment] 2016-08-18 15:02
@Ya-Ri @vetash @Molle500  lets use the issue #2304 to track this.
