### ISSUE TITLE
Push limit message sent multiple times

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#19877] opened 2020-12-17 01:48 UTC
### Steps to reproduce:

1. Open my rocket.chat client
2. It's always show reached mobile push message on top.
3. I go to cloud.rocket.chat to see my usage.It's only use 2674/10000 month.

### Expected behavior:

It's not reached limit.And even reached limit it's no need still notification.

### Actual behavior:

![圖片](https://user-images.githubusercontent.com/6081927/102427601-a2536a80-404c-11eb-9b38-733b84c68355.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: on
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: 3.0.7
- Operating System: Win10

**Comment by jhewt** [comment] 2020-12-17 02:12
I also have to close the attention banner multiple times each time I start my rocket.chat client.

Exactly at 23:00 (GTM-3) I received more than 300 PMs in less than 5 secs from the Rocket.chat bot, repeating the attention banner as a message.

![image](https://user-images.githubusercontent.com/3622160/102434738-1e6d9400-3ff4-11eb-9463-6ed212779571.png)

**Comment by geekgonecrazy** [comment] 2020-12-17 04:37
https://twitter.com/rocketchatcloud/status/1339395918664257544 we unfortunately hit a bit of a snag and some alerts incorrectly sent out.  The pushes caused by alerts will be removed usage. Sorry for the noise!

**Comment by kaiiiiiiiii** [comment] 2020-12-17 08:22
> https://twitter.com/rocketchatcloud/status/1339395918664257544 we unfortunately hit a bit of a snag and some alerts incorrectly sent out. The pushes caused by alerts will be removed usage. Sorry for the noise!

I'm not using the official rocket.chat push gateway. why do I still receive warnings? Are there still messages send to the official push gateway despite I completely removed it from the settings? If so, this is a GDPR violation ...

**Comment by tspaeth** [comment] 2020-12-17 09:21
"Some" is a nice description for 200 mail + in-client notifications by the cat :-)

**Comment by TheWrongGuy** [comment] 2020-12-17 09:48
I can confirm this unfortunately. Is there a know why to make the bot silent and remove the attention banner from the top of the client?

**Comment by adewes** [comment] 2020-12-17 13:06
+1 we're also getting hammered with the message even though we have disabled the push message service.

**Comment by makibras** [comment] 2020-12-17 14:01
> I can confirm this unfortunately. Is there a know why to make the bot silent and remove the attention banner from the top of the client?

to remove the banners, as a quick fix, run a script for automatic dismissal like this one:

```
banners = Object.values(Meteor.user().banners).filter((b) => !b.read && b.id.startsWith('alert-'));
function dismiss() {
	if (!banners.length) {
		console.log('Finished, you may need to refresh to stop seeing the banners')
		return;
	}

	const banner = banners.shift();
	Meteor.call('banner/dismiss', {id: banner.id}, (error, result) => {
		if (!error) {
			return dismiss();
		}
		// console.log(error);
		console.log('Too many requests, waiting', Math.round(error.details.timeToReset / 1000), 'seconds to continue.')
		banners.unshift(banner);
		setTimeout(dismiss, error.details.timeToReset);
	})
}
dismiss();
```
in your browser console. then refresh. this should do the trick. you have to do it for each admin user though who received the banners.

to turn the bot silent, go under: admin settings --> general --> updates --> enable the update checker
turn that one off to not receive messages via Rocket.Cat anymore. I recommend to keep it on though since it is an important way for admins to receive alerts. (yes, this one time it went wrong unfortunately...) If you dont have that setting, you are probably below v3.5. in which the setting was introduced.
we will add a description in the admin UI asap, that this is the setting that triggers important alerts (like new versions, but also true threshold exceed alerts) to workspaces.

as mentioned above, these messages were sent out on error. Apologies for that and we will share more details soon what went wrong to make sure it doesnt happen again.

**Comment by guidtz** [comment] 2020-12-18 15:01
Hello, there is a solution to remove notification on server ?

**Comment by makibras** [comment] 2020-12-18 15:04
> Hello, there is a solution to remove notification on server ?

yes, there is:

> to turn the bot silent, go under: admin settings --> general --> updates --> enable the update checker
turn that one off to not receive messages via Rocket.Cat anymore. I recommend to keep it on though since it is an important way for admins to receive alerts. (yes, this one time it went wrong unfortunately...) If you dont have that setting, you are probably below v3.5. in which the setting was introduced.

**Comment by guidtz** [comment] 2020-12-18 15:09
@makibras yes I always do that : 
![rocketchat-update](https://user-images.githubusercontent.com/952410/102629346-50453e80-414b-11eb-95ef-31efebd0820f.png)

I restart RocketChat also, I update to latest also and I always had the message

**Comment by makibras** [comment] 2020-12-18 15:10
please see also this forum post: https://forums.rocket.chat/t/faulty-messages-about-mobile-push-limits/9757/2
with more technical details.

bottom line: bug causing this was found and rolled bag. moving forward, we will make it more transparent how admins can control alerts in their workspaces.

sorry again for the hassle. i will close this for now.

**Closed by makibras** 2020-12-18 15:10 UTC

**Comment by makibras** [comment] 2020-12-18 15:12
> @makibras yes I always do that :
> ![rocketchat-update](https://user-images.githubusercontent.com/952410/102629346-50453e80-414b-11eb-95ef-31efebd0820f.png)
> 
> I restart RocketChat also, I update to latest also and I always had the message

ah ok, you mean the blue banner?
for this you have to run the script I mentioned here: 
https://github.com/RocketChat/Rocket.Chat/issues/19877#issuecomment-747456044 
Does this work?

**Comment by jhewt** [comment] 2020-12-18 18:31
For now, it was simpler for me to just completely hide the top blue banner with custom CSS:

```css
.rc-alerts {
  display: none !important
}
```
While this is not recommended, for me it was simpler since I already have tons of custom scripts and adding more is... harder to mantain.

**Comment by guidtz** [comment] 2020-12-19 13:07
@makibras yes it seems to work thanks

**Comment by huko600rr** [comment] 2020-12-26 09:15
> For now, it was simpler for me to just completely hide the top blue banner with custom CSS:
> 
> ```css
> .rc-alerts {
>   display: none !important
> }
> ```
> 
> While this is not recommended, for me it was simpler since I already have tons of custom scripts and adding more is... harder to maintain. Also the rocket.cat bot repeats the same message, so I don't truly miss on important announcements.

THANK YOU!!

**Comment by NicoHaase** [comment] 2021-01-06 08:05
Is there any way to fix this properly? I'm logged in to my RC app daily, and receive such alerts daily. This morning, I had to confirm 13 of these blue messages in a row, for a single server instance...

**Comment by xi67** [comment] 2021-01-15 13:05
Same here. Have to close notification multiple times and the push limit is not reached (2000/10000)
