### ISSUE TITLE
Direct messages are not visible to the receiver

### ISSUE THREAD

**Issue by ryangilbert** [RocketChat/Rocket.Chat#853] opened 2015-09-22 18:18 UTC
When a direct message is received, it is not displayed in the message window for the receiver. Sometimes it appears after reloading the page.

Steps to reproduce:
1. User A send Direct Message to User B
2. User B sees new message notification and clicks on Direct Message with User A

Result:
User A's message is not displayed to User B.
After User B reloads the page, message is displayed.

**Comment by marceloschmidt** [comment] 2015-09-22 18:46
Is this 100% reproducible? If yes, we need more information:

What platform are you testing on:
OS:
Browser:

Your own instance, or demo instance?

If own instance, what are the details of your installation.

Thanks for your feedback.

**Comment by soonahn** [comment] 2015-09-23 19:22
@marceloschmidt happens often, but we haven't found a set of steps that reproduces this 100% of the time.

Platforms vary from Linux (Ubuntu/Arch), to OSX(Mavericks and Yosemite).  Firefox, Chrome (all varients).

We have our own instance, updated from your master fairly often.
Running on AWS (t2.medium), Running straight up Node (no Nginx, or Apache).
Replicate Set as written in your instructions.

**Comment by soonahn** [comment] 2015-09-25 16:21
Still happening, this is the biggest pain point in the entire product.  Messages just sometimes will not show up.

**Comment by Sing-Li** [comment] 2015-09-25 17:19
How about network topology?  Are all browsers on the same LAN when this happens? 

Are all browsers using DNS resolved hostname to access servers?

Or some based on /etc/hosts ?  Or some using IP address?

**Comment by soonahn** [comment] 2015-09-25 17:35
@Sing-Li 

I think I've fixed it, however...

All clients were on the same LAN, the Server was NOT on the same LAN.
Browsers using DNS resolved hostname, DNS was not an issue.

I believe it was a websockets issue.

**Comment by Sing-Li** [comment] 2015-09-25 17:37
You have routers that block websockets?

**Comment by geekgonecrazy** [comment] 2015-09-25 17:38
If you're using reverse proxy in front like nginx / apache make sure you're upgrading your websockets.

**Comment by soonahn** [comment] 2015-09-25 17:38
ELB has to be configured to pass TCP through, not just HTTP/HTTPS through.

@geekgonecrazy what do you mean by "upgrading"

**Comment by geekgonecrazy** [comment] 2015-09-25 17:41
@soonahn each websocket starts out as a normal http(s) request.  It has a header indicating that it wishes to be upgraded to a websocket.

![image](https://cloud.githubusercontent.com/assets/51996/10107733/b02aaeea-6382-11e5-9c87-820d05cca247.png)

**Comment by Sing-Li** [comment] 2015-09-25 17:44
ELB ... yes!  That is a super common gotcha. They never officially supported websocket. Just dealt with it the other day.  And lee faus the week before. Make sure you still have round robin!

**Comment by soonahn** [comment] 2015-09-25 17:59
@Sing-Li I think we're okay, but not 100% sure yet.  Some people haven't refreshed their browser and are still on polling so I've seen some dropped messages here and there.

I'm getting everyone to refresh their clients, so we should all be on websockets, will let you know the status then.

**Comment by soonahn** [comment] 2015-09-25 18:34
Is not a websocket issue.  People are still getting dropped messages :(

**Comment by Sing-Li** [comment] 2015-09-25 18:50
So .. I think we should rule out first  ... two browsers on different networks ... both accessing server via DNS resolved address;  because that would be the config for 90+ % of our current users.

**Comment by marceloschmidt** [comment] 2015-11-05 17:02
Any news on this?

**Comment by engelgabriel** [comment] 2015-12-03 05:21
I believe this issue was fixed by @rodrigok when a error on the logic to retrieve messages sent while disconnected. Let us know otherwise.

**Closed by engelgabriel** 2015-12-03 05:21 UTC
Labels: type: support

**Comment by maik28** [comment] 2018-08-21 13:13
I've got the same bug in v0.68.3 #11516

**Comment by rohitmyaim** [comment] 2019-01-08 06:31
I am running Rocketchat .73 version and facing this issue for only one user  but permanantly on his system.
User is using Windows 10 and have tried on both Chrome and IE browser.
Anyone fixed this issue ?

**Comment by billynoah** [comment] 2021-03-12 15:53
having this same problem in Version 3.12.1.  Some users are fine.  One user in particular can not receive my DMs.  Sends notification and shows snippet in the left hand pane but room fails to retrieve messages when clicked.  Also never properly loads if I do a hard refresh - simply continues showing animation icon until I leave the channel and go back in.
