### ISSUE TITLE
Login in firefox blocked by validation

### ISSUE THREAD

**Issue by fimdomeio** [RocketChat/Rocket.Chat#1433] opened 2015-11-18 09:39 UTC
When I try to login to rocket.chat in Firefox I get a message on the top left corner saying "Please enter an email address". My best guess is that this is being cause by an hidden input of type email and that the parent form tag is missing the novalidate atribute

**Comment by geekgonecrazy** [comment] 2015-11-23 05:57
Did you ever have it save your login information?  Does this work from like in private browsing in firefox?

**Comment by fimdomeio** [comment] 2015-11-23 11:10
Yes. Everything works correctly on private browsing.
Removed saved password everything working correctly. firefox asked again to save my password. In the information to be saved it says that it will save the password no username. It keeps working when I leave the username empty or when I add my email to it, but it never prefills the username on the login page.

I was guessing this happened when I registered and firefox askeded me for the first time if I wanted to saved the password, but even after cleaning all the passwords and registering a new account I can't replicate the bug. Maybe because the first user goes through a different process.

**Comment by geekgonecrazy** [comment] 2015-11-23 15:31
@fimdomeio I'll see if I can replicate.  I think this has something to do with the field names for username and password changing though.  But that's just a hunch.

**Comment by marceloschmidt** [comment] 2016-02-04 19:26
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/905

**Closed by marceloschmidt** 2016-02-04 19:26 UTC
Labels: type: need more info
