### ISSUE TITLE
Links dont open in new tab with marked parser

### ISSUE THREAD

**Issue by Lemmmy** [RocketChat/Rocket.Chat#8115] opened 2017-09-13 15:53 UTC
When using the Marked markdown parser, left clicking links opens in the current tab instead of a new one.

**Comment by ulope** [comment] 2019-10-30 13:25
Duplicate of #8564

**Comment by gabriellsh** [comment] 2020-09-08 15:35
Closed, duplicate as said up on top.

**Closed by gabriellsh** 2020-09-08 15:35 UTC
Labels: feat: message, type: bug
