### ISSUE TITLE
Global search as default even it's not checked

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#23538] opened 2021-10-22 11:42 UTC
### Description:

When I open the search bar, there's unchecked checkbox `Global Search` but when I start searching, it searches globally. Workaround is to check and uncheck checkbox and then it starts searching in this channel (not globally).

### Steps to reproduce:

Described above

### Expected behavior:

When I open the search bar, there's
 a) Checked `Global search` and searching is global
 b) Unchecked `Global search` and search is **not** global
_(not smth in between)_

### Actual behavior:

Searches globally (sometimes even after check and uncheck global search)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.2
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.23

### Client Setup Information

- Desktop App or Browser Version: 3.5.7-1 (AUR)
- Operating System: Arch linux

### Additional context

N/A

### Relevant logs:

N/A

**Comment by ankar84** [comment] 2022-01-27 04:06
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/21659

**Closed by ankar84** 2022-01-27 04:06 UTC
