### ISSUE TITLE
Can't change username as admin in 0.37.1

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat#4081] opened 2016-08-22 10:05 UTC
Your Rocket.Chat version: 0.37.1
When I try to change username as admin it just hang on error:

I20160822-12:01:33.507(2) Exception while invoking method 'insertOrUpdateUser' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: usernames.$     at Object.Future.wait (/home/rocket/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15)     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)     at _Class.update (server/models/_Base.js:78:29)     at _Class.RocketChat.models.Rooms._Class.replaceUsername (packages/rocketchat_lib/server/models/Rooms.coffee:344:11)     at RocketChat._setUsername (packages/rocketchat_lib/server/functions/setUsername.coffee:42:27)     - - - - -     at Object.toError (/home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)     at /home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27     at /home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7     at /home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9     at Server.Base._callHandler (/home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)     at /home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18     at [object Object].MongoReply.parseBody (/home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)     at [object Object].<anonymous> (/home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)     at [object Object].emit (events.js:95:17)     at [object Object].<anonymous> (/home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)

**Comment by Venomen** [comment] 2016-08-22 22:11
Moreover: when this user (which I tried to rename) login to rocket again, he don't see any channels and possibility to join to them. He also can't open chat to other users. 

I had to remove his account and add it again.

**Comment by JohnCrist1988** [comment] 2016-08-22 23:39
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/4073

**Closed** 2016-08-23 11:48 UTC
Labels: feat: user settings, type: bug

**Comment by graywolf336** [comment] 2016-08-31 17:51
Duplicate of #3940
