### ISSUE TITLE
[REFACTOR] Todo comments in the code

### ISSUE THREAD

**Issue by kulkarnigaurav38** [RocketChat/Rocket.Chat#23637] opened 2021-11-05 11:47 UTC
### Description:

 TODO comments in the codebase e.g. (app->logger->server->index.js), would it be fine if I make changes according to them? Would be helpful in understanding the codebase as well :)

### Steps to reproduce:

1.  Go to app/logger/server/index.js

### Expected behavior:

 Refactor code according to the comments given. @sampaiodiego wrote this code!

### Actual behavior:

 
![Screenshot 2021-11-05 162109](https://user-images.githubusercontent.com/59637086/140505321-05f4fd2e-f647-41b7-9204-e618939c7a1b.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.0-develop
- Operating System: Linux (WSL2 on Windows)
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1 -x64
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version: Chrome latest (95.0.4638.69)
- Operating System: Windows 10 version 21H1

**Comment by debdutdeb** [comment] 2021-11-11 21:55
Hi.

Please ask these kinds of questions in [#dev](https://open.rocket.chat/channel/dev). 

We really appreciate you wanting to contribute! Again, please ask in the dev channel at our open server, and I can check with Diego and the others if someone is already working on it or not. 

Closing since this is not a bug.

**Closed by debdutdeb** 2021-11-11 21:55 UTC
