### ISSUE TITLE
Room not found error when initiating a new direct conversation

### ISSUE THREAD

**Issue by panpomaly** [RocketChat/Rocket.Chat#24727] opened 2022-03-07 18:42 UTC
### Description:

We just upgraded to 4.5.0 and now have the following problem. When using the search to start a new direct message room with another user, that was never talked to, we get an error message:

> Room not found
> This room does not exist or you may not have permission to access

But strangely enough this works when not using the search, but starting the direct message using the directory.

### Steps to reproduce:

This can be reproduced on our instance after upgrading to 4.5.0

1. Search for a new user with whom you never talked before 
1. Click on him to start a new DM
1. You should see the error message right now.

### Expected behavior:

A new room with "You have joined a new direct message with ..." should open.

### Actual behavior:

A room not found error is shown.

<img width="665" alt="Screenshot 2022-03-07 at 19 20 48" src="https://user-images.githubusercontent.com/5050073/157094326-2366ac8c-6799-4a39-8748-93277d3fd6be.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.0
- Operating System: Ubuntu 20.04
- Deployment Method: Manual installation
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version:  v14.18.3
- MongoDB Version: 5.0.6 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Tested in Desktop App 3.7.8, but same problem appears in browser version and for all users I talked to
- Operating System: macOS 11.6.4, Ubuntu Linux 20.04

### Additional context

We updated from 3.0.7 -> 3.18.x -> 4.5.0 and did not had any problems, except initially an issue with db indexes, but that is fixed and rocket chat starts without any problems.

This error and log messages seem to be similar to  #21735 (at least the initial question). 
And I found #16822, which is old and seems to be another problem, but someone added a screenshot with the same error message and rocket chat version, so I hope we are not the only ones who are affected. 

### Relevant logs:

```
Mär 07 19:10:57 rocket-22 rocketchat[35171]: {"level":35,"time":"2022-03-07T18:10:57.666Z","pid":35171,"hostname":"rocket-22","name":"","name":"Meteor","method":"getRoomByTypeAndName","userId":"QRbhbuPStQhzLYJRn","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.7.8 Chrome/98.0.4758.102 Electron/17.1.0 Safari>
Mär 07 19:10:57 rocket-22 rocketchat[35171]: {"level":50,"time":"2022-03-07T18:10:57.668Z","pid":35171,"hostname":"rocket-22","name":"","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"}
Mär 07 19:10:57 rocket-22 rocketchat[35171]: Exception while invoking method getRoomByTypeAndName errorClass [Error]: Invalid room [error-invalid-room]
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at MethodInvocation.getRoomByTypeAndName (server/publications/room/index.js:53:10)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:74:34)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/ddp-server/livedata_server.js:1803:15
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/ddp-server/livedata_server.js:1801:36
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at new Promise (<anonymous>)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Server.applyAsync (packages/ddp-server/livedata_server.js:1800:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Server.apply (packages/ddp-server/livedata_server.js:1739:26)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Server.call (packages/ddp-server/livedata_server.js:1721:17)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Object.post (app/api/server/v1/misc.js:456:26)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at app/api/server/api.js:425:96
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/rocketchat_restivus/lib/route.coffee:59:33
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/simple_json-routes.js:100:9
Mär 07 19:10:57 rocket-22 rocketchat[35171]:  => awaited here:
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Server.apply (packages/ddp-server/livedata_server.js:1752:22)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Server.call (packages/ddp-server/livedata_server.js:1721:17)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Object.post (app/api/server/v1/misc.js:456:26)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at app/api/server/api.js:425:96
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/rocketchat_restivus/lib/route.coffee:59:33
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/simple_json-routes.js:100:9 {
Mär 07 19:10:57 rocket-22 rocketchat[35171]:   isClientSafe: true,
Mär 07 19:10:57 rocket-22 rocketchat[35171]:   error: 'error-invalid-room',
Mär 07 19:10:57 rocket-22 rocketchat[35171]:   reason: 'Invalid room',
Mär 07 19:10:57 rocket-22 rocketchat[35171]:   details: { method: 'getRoomByTypeAndName' },
Mär 07 19:10:57 rocket-22 rocketchat[35171]:   errorType: 'Meteor.Error'
Mär 07 19:10:57 rocket-22 rocketchat[35171]: }
Mär 07 19:10:57 rocket-22 rocketchat[35171]: {"level":35,"time":"2022-03-07T18:10:57.668Z","pid":35171,"hostname":"rocket-22","name":"","name":"API","method":"POST","url":"/api/v1/method.call/getRoomByTypeAndName","userId":"QRbhbuPStQhzLYJRn","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.7.8 Chrome/98.0.4>
Mär 07 19:10:57 rocket-22 rocketchat[35171]: {"level":35,"time":"2022-03-07T18:10:57.712Z","pid":35171,"hostname":"rocket-22","name":"","name":"Meteor","method":"createDirectMessage","userId":"QRbhbuPStQhzLYJRn","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat/3.7.8 Chrome/98.0.4758.102 Electron/17.1.0 Safari/>
Mär 07 19:10:57 rocket-22 rocketchat[35171]: {"level":50,"time":"2022-03-07T18:10:57.722Z","pid":35171,"hostname":"rocket-22","name":"","name":"System","msg":"Exception while invoking method createDirectMessage 'Invalid user [error-invalid-user]'"}
Mär 07 19:10:57 rocket-22 rocketchat[35171]: Exception while invoking method createDirectMessage errorClass [Error]: Invalid user [error-invalid-user]
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at server/methods/createDirectMessage.js:45:11
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Array.map (<anonymous>)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at createDirectMessage (server/methods/createDirectMessage.js:36:4)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at MethodInvocation.createDirectMessage (server/methods/createDirectMessage.js:96:10)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:74:34)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/ddp-server/livedata_server.js:1803:15
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/ddp-server/livedata_server.js:1801:36
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at new Promise (<anonymous>)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Server.applyAsync (packages/ddp-server/livedata_server.js:1800:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Server.apply (packages/ddp-server/livedata_server.js:1739:26)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Server.call (packages/ddp-server/livedata_server.js:1721:17)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Object.post (app/api/server/v1/misc.js:456:26)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at app/api/server/api.js:425:96
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/rocketchat_restivus/lib/route.coffee:59:33
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/simple_json-routes.js:100:9
Mär 07 19:10:57 rocket-22 rocketchat[35171]:  => awaited here:
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Server.apply (packages/ddp-server/livedata_server.js:1752:22)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Server.call (packages/ddp-server/livedata_server.js:1721:17)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Object.post (app/api/server/v1/misc.js:456:26)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at app/api/server/api.js:425:96
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Object._internalRouteActionHandler [as action] (app/api/server/api.js:425:39)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/rocketchat_restivus/lib/route.coffee:59:33
Mär 07 19:10:57 rocket-22 rocketchat[35171]:     at packages/simple_json-routes.js:100:9 {
Mär 07 19:10:57 rocket-22 rocketchat[35171]:   isClientSafe: true,
Mär 07 19:10:57 rocket-22 rocketchat[35171]:   error: 'error-invalid-user',
Mär 07 19:10:57 rocket-22 rocketchat[35171]:   reason: 'Invalid user',
Mär 07 19:10:57 rocket-22 rocketchat[35171]:   details: { method: 'createDirectMessage' },
Mär 07 19:10:57 rocket-22 rocketchat[35171]:   errorType: 'Meteor.Error'
Mär 07 19:10:57 rocket-22 rocketchat[35171]: }
```

**Comment by TheWrongGuy** [comment] 2022-03-08 09:10
I also experienced this issue!

**Comment by devadattas** [comment] 2022-03-08 10:19
Same here!

**Comment by devadattas** [comment] 2022-03-08 11:36
It seems to be getting triggered from here: 

https://github.com/RocketChat/Rocket.Chat/blob/develop/server/methods/createDirectMessage.js#L15

From front-end userId is being sent as the first parameter without the usernames.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/56180/157230805-f1f4b480-dadd-4eca-b4d1-3d696e004a05.png">

@sampaiodiego Please look into this as this blocking functionality on production upon upgrading to 4.5.0

**Comment by devadattas** [comment] 2022-03-08 12:16
It's a Web Front-end issue for sure as accessing the user from the Mobile App once creates the direct channel and it will start working after that. @panpomaly you can use this work around till there is a proper fix for this.

**Comment by dudanogueira** [comment] 2022-03-08 19:08
Fix is coming in 4.5.1

**Comment by ankar84** [comment] 2022-03-09 05:48
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/24669

**Comment by panpomaly** [comment] 2022-03-09 10:22
> It's a Web Front-end issue for sure as accessing the user from the Mobile App creates the direct channel and it will start working after that. @panpomaly you can use this work around till there is a proper fix for this.

Thanks for the workaround, but we already found out that it works using the directory (see description). 

> Fix is coming in 4.5.1

Thanks! Good to hear.

> duplicate of #24669

I looked at all issue titles since the last release and would have never thought that the LDAP issue is related, but it is. thanks. I will still leave this issue open, since the pr is added here.

**Comment by ankar84** [comment] 2022-03-09 12:34
> would have never thought that the LDAP issue is related, but it is

Actually, I don't believe that it's a LDAP related issue. because I saw a lot of facts about that issue with local accounts and other authentication services like Google OAuth. It's just some race condition, that I hope will be fixed by Tasso's PR.

**Comment by devadattas** [comment] 2022-03-10 02:09
Just upgraded to `4.5.1` and seems this issue is still not fixed!

**Comment by raczkow** [comment] 2022-03-10 07:58
4.5.1 - issue not solved

**Comment by txwheeler** [comment] 2022-03-10 17:32
Why was this issue closed, if users are reporting it broken still in 4.5.1? @tassoevan

**Comment by panpomaly** [comment] 2022-03-10 18:46
I can confirm that it is still not working for us.

But I also can't reopen the issue, since it was closed automatically with the PR. Could someone with the permission please reopen it.

**Comment by sampaiodiego** [comment] 2022-03-10 20:43
the PR fixing the issue is scheduled to land on release 4.5.2 .. meanwhile, are you guys able to help testing it? if you're using Docker you can use the container `registry.rocket.chat/rocketchat/rocket.chat:develop` or you can build from source using the `develop` branch

**Comment by ankar84** [comment] 2022-03-11 04:38
> meanwhile, are you guys able to help testing it? if you're using Docker you can use the container `registry.rocket.chat/rocketchat/rocket.chat:develop`

Hey, Diego!
Testing that issue on develop branch in Docker and looks like it is fixed finally!
I only test case starting DM from magnifying glass search - works perfect.

**Comment by panpomaly** [comment] 2022-03-11 14:16
Tested it in a local docker env, with real data from production ... and it works!

Thanks!

**Comment by devadattas** [comment] 2022-03-14 02:10
Upgraded to `4.5.2` and the issue still persists!

**Comment by degewo** [comment] 2022-03-14 05:58
Upgraded to 4.5.2 and the issue still persists!

**Comment by ankar84** [comment] 2022-03-14 07:41
> Upgraded to 4.5.2 and the issue still persists!

I will check that today.

But @devadattas @degewo can you try to refresh your client after upgrade with **CTRL+R** and try again?

**Comment by degewo** [comment] 2022-03-14 07:50
@ankar84 
Thank you for investigating. I rebooted the whole server after update, furthermore i deleted the whole cache from chrome and reloaded the server from Rocket.Chat Client. Nothing hleps.

I also opened the developer console from Rocket.Chat client and by trying to open an direct chat with a new user the following appears multiple times:

> 58de905f702f31abd70f879c5c38e0099f8c6364.js?meteor_js_resource=true:1498 Deprecated: RoomCoordinator.getRouteData received a room object

Thank you so much for your help

**Comment by devadattas** [comment] 2022-03-14 07:51
@ankar84 I tried it by clearing the browser as well as the CDN Caches. Also, tried by logging out and logging in again. Still same issue.

**Comment by debdutdeb** [comment] 2022-03-14 10:52
Thanks for confirming Anton.

**Comment by panpomaly** [comment] 2022-03-14 18:15
Same here. Does not work after updating to 4.5.2 on prod, but it worked with the docker:develop image on Friday.

**Comment by brendoncarvalho** [comment] 2022-03-15 00:52
**Temporary Alternative:** If you access https://[your-rocket-domain]/direct/[username] through the browser, it works and you can chat with the user. 😅

I'm on version 4.5.2 and the problem still exists. 🤦🏻‍♂️

**Comment by cuongnn-smartosc** [comment] 2022-03-16 18:04
When you create an direct message, the URL is `http://localhost:3000/direct/JG9iuAbCcMEdvd9kx` and the server code will look up the username  instead of rid therefore it unable to find the "to" user

`let to = Users.findOneByUsernameIgnoringCase(username);` in class server/methods/createDirectMessage.js

Fix is you need to change the rid in `/lib/rooms/roomTypes/direct.ts`

```
link(sub): Record<string, string> {
    return { rid: sub.name || '' };
},
```

**Comment by ankar84** [comment] 2022-03-17 03:57
Main question to me right now is why all worked perfect in develop branch and stop working when same PR was merged in 4.5.2 release. Can someone explain it tp me?

**Comment by holzfelix** [comment] 2022-03-17 06:50
same issue here!

**Comment by toppermitz** [comment] 2022-03-17 21:37
I upgrade today from 4.5.1 to 4.5.2 and this issue still existing

**Comment by cYzzie** [comment] 2022-03-21 12:35
we upgraded from 3.X to 4.5.2 and are having the same problem

**Comment by devadattas** [comment] 2022-03-22 02:08
Upgraded to `4.5.3` and the issue still persists!

**Comment by ankar84** [comment] 2022-03-22 02:58
@tassoevan @ggazzo Please consider to fix that issue.
Fox some reason https://github.com/RocketChat/Rocket.Chat/pull/24623 didn't fix that issue.

**Comment by kitich** [comment] 2022-03-22 05:42
4.5.3 still there

**Comment by holzfelix** [comment] 2022-03-22 07:08
yep still there

**Comment by cole99simpson** [comment] 2022-03-23 14:04
Any update on this issue? Its been a pain for new employees in the office, luckily it isn't affecting iOS or iPad OS

**Comment by Franc3x** [comment] 2022-03-24 09:45
possible not to have a resolution of the problem?
We consider switching to other company chats?

**Comment by tars21** [comment] 2022-03-24 14:42
I'm just here to say: same here

**Comment by Franc3x** [comment] 2022-03-24 16:34
will the next version be 5.4.3? I'm stuck at 4.5.1  thanks

**Comment by txwheeler** [comment] 2022-03-25 14:20
> Hi guys, we already tracking this issue and a fix will be sent on the next release.

4.5.4 came out last night, does anyone know if this was fixed with this latest release? The release notes don't seem to indicate that it was.

**Comment by AntoineHugo** [comment] 2022-03-25 14:44
Hi, 

I just upgraded to 4.5.4 and after a server reboot, the problem is still there.

For information,
Version
4.5.4
Deployment ID
HGtRPE7bvg5bQKC3G
Apps Engine Version
1.31.0
Version of Node
v14.18.3
Database update
256 (March 25, 2022 3:39 PM)
MongoDB
5.0.6/wiredTiger (oplog Enabled)




Thank you for advancing this point because this problem remains blocking for us

**Comment by cole99simpson** [comment] 2022-03-25 14:57
That's the 2nd time that someone said the new release will have a fix for this issue... and it has been over 3 weeks now... I guess we need to shop for other chat systems. This is a large problem (could be much worse since the majority of my users are on iOS but I imagine it is for others). How are they going to release 4 new versions without addressing the issue?

**Comment by holzfelix** [comment] 2022-03-25 15:37
for me, the matter is also quite clear. we will soon migrate to office365 and teams.

**Comment by dudanogueira** [comment] 2022-03-25 20:43
Hi! We are sorry for this delay. A fix is coming soon.

As you probably noticed, we are refactoring some ui components and this is causing some unexpected behavior.

We appreciate all your inputs! Thanks!

**Comment by maiconbaum** [comment] 2022-03-28 13:46
Same here. [just to not let it die :-)]

**Comment by Franc3x** [comment] 2022-03-29 07:59
news? we are unable to carry out normal work

**Comment by teach404W** [comment] 2022-03-29 12:29
The support told us to use the directory instead the search to contact users as workaround. Its working. They told us that they are working on fixing the problem
![direct](https://user-images.githubusercontent.com/94044406/160611441-bf3d2fae-c82a-4ef7-9d82-438d8ac21f89.png)
.

**Comment by pierre-lehnen-rc** [comment] 2022-03-31 03:37
There were actually two different issues that resulted on the same error message. One was a race condition that was fixed on 4.5.2 and the other was an error on the spotlight search results creating invalid links (that's why it worked when accessing from the directory). This second error was fixed very quickly on our develop branch but the fix was accidentally left out of the patch releases that followed (patch releases only include fixes that were explicitly merged to it).

I've looked through the whole history now to understand what happened at each point in time and I also made a better fix on #24955, which was included on the [4.5.5 patch](https://github.com/RocketChat/Rocket.Chat/releases/tag/4.5.5) released today.

**Comment by ankar84** [comment] 2022-03-31 05:13
Tested 4.5.5 and can tell for sure that this bug is fixed now.
But to be 100% sure I want to ask everybody else to test 4.5.5 to check fix.

**Comment by nickerber** [comment] 2022-03-31 06:29
> Tested 4.5.5 and can tell for sure that this bug is fixed now. But to be 100% sure I want to ask everybody else to test 4.5.5 to check fix.

Can confirm this issue is fixed in 4.5.5.

**Comment by onigoetz** [comment] 2022-03-31 06:34
Yep, working as well on my side with 4.5.5

**Comment by BlackBeretEH** [comment] 2022-03-31 09:12
Working on Ubuntu snap 4.5.5 !

**Comment by cendudu** [comment] 2022-03-31 12:36
Unresolved issue with 4.5.5 update on Ubuntu snap!

**Comment by nickerber** [comment] 2022-03-31 13:28
> Unresolved issue with 4.5.5 update on Ubuntu snap!

Do you use Rocket.chat Desktop Client? If so, try a „Reload ignoring cache“. That worked for me.

**Comment by cendudu** [comment] 2022-03-31 13:37
> > Problema não resolvido com a atualização 4.5.5 no Ubuntu snap!
> 
> Você usa o Rocket.chat Desktop Client? Em caso afirmativo, tente um „Recarregar ignorando o cache“. Isso funcionou para mim.

Thanks, working perfectly

**Comment by WesleydosReis** [comment] 2022-03-31 13:49
Working on Ubuntu Snap 4.5.5

**Comment by sampaiodiego** [comment] 2022-04-01 12:34
thanks everyone for the feedback.. I'll be closing the issue as everyone is reporting it has been fixed now..

**Closed by sampaiodiego** 2022-04-01 12:34 UTC
Labels: bug

**Comment by Franc3x** [comment] 2022-04-04 09:32
it's ok
