### ISSUE TITLE
Uploaded files are corrupted upon download

### ISSUE THREAD

**Issue by galmok** [RocketChat/Rocket.Chat#2547] opened 2016-03-18 11:03 UTC
Your Rocket.Chat version: 0.22

I uploaded a small txt file (12 bytes) and then downloaded it again. The downloaded file was 32 bytes and contained seemingly random bytes. GridFS is configured. I checked the uploaded data in mongodb and it is stored correctly (I think). I found the json array with the file data and it was 12 bytes long and contained ASCII as the original file did.

rocketchat_uploads has this record:

{
    "_id": "ZBaz3RhhttunLghYX",
    "name": "windowsupdatereverting.txt",
    "size": 12,
    "type": "text/plain",
    "rid": "GENERAL",
    "store": "rocketchat_uploads",
    "complete": true,
    "extension": "txt",
    "progress": 1,
    "uploading": false,
    "userId": "StnDDarBaHeBtTv2X",
    "token": "68b9b9ebAB",
    "uploadedAt": ISODate("2016-03-18T10:22:49.564Z"),
    "url": "/ufs/rocketchat_uploads/ZBaz3RhhttunLghYX/windowsupdatereverting.txt"
}

rocketchat_uploads.files has this record:

{
    "_id": "ZBaz3RhhttunLghYX",
    "filename": "ZBaz3RhhttunLghYX",
    "contentType": "text/plain",
    "length": 12,
    "chunkSize": 261120,
    "uploadDate": ISODate("2016-03-18T10:22:49.559Z"),
    "aliases": null,
    "metadata": null,
    "md5": "d67d4c345fcdcd51ca7ab70a2040fa45"
}

rocketchat_uploads.chunks has this record:

{
    "_id": ObjectID("56ebd6f9a388f464a08475a5"),
    "files_id": "ZBaz3RhhttunLghYX",
    "n": 0,
    "data": "LWtiMzA0MzgxMg0K"
}

The above chunk.data expanded:

{
    "_bsontype": "Binary",
    "sub_type": 0,
    "position": 12,
    "buffer": ⊖{
        "0": 45,
        "1": 107,
        "2": 98,
        "3": 51,
        "4": 48,
        "5": 52,
        "6": 51,
        "7": 56,
        "8": 49,
        "9": 50,
        "10": 13,
        "11": 10
    }
}

The downloaded file converted to HEX:

1F8B082020202020200BD3CD4E323630
31B63034E2E502204E484DBC0C202020

**Comment by galmok** [comment] 2016-03-18 11:08
Looking at issue #2545 I tested:

$ cat windowsupdatereverting.txt| gzip -d
-kb3043812

The downloaded file needs an extra gzip decompress cycle (or one less compress cycle).

**Comment by engelgabriel** [comment] 2016-03-18 13:11
Is this problem something new to version 0.22.0? Was it working on before?

**Comment by galmok** [comment] 2016-03-18 13:13
I cannot say. Never managed to try this feature in 0.21.

**Comment by engelgabriel** [comment] 2016-03-18 13:22
OK, I'll close this as it is a duplicate of #2545, ok?

**Closed by engelgabriel** 2016-03-18 13:22 UTC
Labels: type: bug
