### ISSUE TITLE
Add option to delete logs

### ISSUE THREAD

**Issue by iangilfillan** [RocketChat/Rocket.Chat#10495] opened 2018-04-18 14:17 UTC
It would be useful to add an option to delete the logs. After uncovering a privacy issue in that all direct messages between anyone were available for viewing to all admins in the logs, it would have been simplest to just delete the logs and alert everyone that their messages were not private going forward (the actual privacy is another issue).

**Comment by TwizzyDizzy** [comment] 2018-04-18 14:56
You have not stated which logs you refer to. I have had a similar case... that's why I'm asking this: In my case this was actually MongoDB that was logging queries that were executed slower than `100ms`.

Your can get the value of `slowms` via `db.getProfilingStatus()` in mongo-shell.

You can check my theory by setting the `slowms` value to 2 seconds (`db.setProfilingLevel(0,2000)`) and check whether private messages are still logged.

So if I'm right, this is nothing that can be fixed by Rocket.Chat itself. What we/you could do is to do a PR for the Docker files and every deployment mechanism to somehow set the `slowms` value to something bigger than 100ms.

Cheers
Thomas

**Comment by iangilfillan** [comment] 2018-04-18 15:03
The logs that are viewed via "View Logs" in the Administration menu. We are trialling the hosted solution.

**Comment by TwizzyDizzy** [comment] 2018-04-18 15:11
@rocket-cat close

Well, I can confirm this in my setup when enabling log level "debug". This seems to be the case in cloud instances then. It is also what you would expect of a "debug" loglevel. You can edit your settings regarding the log level here: https://your.server.address/admin/Logs

As this is no bug but rather working as expected, I'm going to close this issue.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-04-18 15:11 UTC
