### ISSUE TITLE
Firefox save username / password doesn't get correct username from form.

### ISSUE THREAD

**Issue by Surfoo** [RocketChat/Rocket.Chat#905] opened 2015-09-26 12:00 UTC
Hello,

I saved my login and password into Firefox, but Rocket.chat display only the password, not the login.

![login](https://cloud.githubusercontent.com/assets/553659/10117435/da3e3c4a-6456-11e5-98fd-0638b53b0e31.jpg)
##

**Comment by geekgonecrazy** [comment] 2015-09-27 04:28
Just out of curiosity if you click register is the username populated in one of those fields?

**Comment by AdrianoCahete** [comment] 2015-09-27 07:19
You saved in register or first login?

**Comment by gmsecrieru** [comment] 2015-10-13 15:41
@Surfoo is this something you are still experiencing? Could you please provide more information so we can work on it?

**Comment by marceloschmidt** [comment] 2016-02-04 18:00
I confirmed this happens in Firefox, on login. When you try to login, it will ask to save your username and password, but username is empty. That's because it's trying to save the e-mail field, which is hidden and displayed only on registration. See this:

![username_and_password](https://cloud.githubusercontent.com/assets/1986378/12824426/4d1a5722-cb58-11e5-8ae5-05721f10eb4c.gif)

**Comment by TwizzyDizzy** [comment] 2018-02-16 12:55
@rocket-cat close

Closing, since not reproducible anymore in 0.61.1 on FF 58.0.2.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-02-16 12:55 UTC
Labels: subj: ui/ux, type: improvement
