### ISSUE TITLE
Allow selected users to invite others to private group

### ISSUE THREAD

**Issue by defib** [RocketChat/Rocket.Chat#2127] opened 2016-02-04 04:17 UTC
Currently I can't find a way to allow someone else to invite users to a private group I made.  @paulproteus and I tried making a user a group moderator or owner and it did not work.

**Comment by jasperla** [comment] 2016-02-04 12:54
Running into the same issue. It's confusing that even making someone else owner or moderator doesn't work.

**Comment by pcarn** [comment] 2016-02-04 20:56
+1

**Comment by mrogaski** [comment] 2016-02-13 16:21
+1 This is a big one for us.  The creator/owner of a channel should be able to assign moderator roles to allow others to invite.

**Comment by Lochemage** [comment] 2016-03-02 20:38
+1 Absolutely critical, also an admin user should be able to control this even if they are not the creator of the channel.

**Comment by mrogaski** [comment] 2016-03-02 23:41
Agreed, the fact that an admin must be a member of a channel to modify permissions is problematic.

**Comment by pcarn** [comment] 2016-03-03 01:01
It's worse than that. The admin has to be the creator of the channel.

**Comment by Lochemage** [comment] 2016-03-03 01:55
Right, the only user that can invite people to a channel is the creator of that channel, no way to change it once the channel has been created.

**Comment by mylesw-luma** [comment] 2016-04-13 02:02
+1 This seems like an oversight to not have

**Comment by mylesw-luma** [comment] 2016-04-13 02:45
This seems to be fixed in 0.26

**Comment by sampaiodiego** [comment] 2016-04-25 20:54
Any user with the `add-user-to-room` permission (room owners and room moderators by default) can add an user to a room.

**Closed by sampaiodiego** 2016-04-25 20:54 UTC
Labels: feat: roles / permissions, type: bug

**Comment by oceatoon** [comment] 2017-09-06 08:37
Hi I'm using the API to invite users to channels or groups
works fine on channels, but not on groups
I then ran into this post 
activated add-user-to-room permission
But I still don't have access to the roomId of the group using groups.info
 and cannot groups.invite through the api 
is this implemented for this usage ?

**Comment by ganesh-at-wiw** [comment] 2018-04-16 14:07
Hi, I'm also facing same problem. Through API, I can add/remove users to and from channels, but not to private groups.
Our rocket chat version is: 2.10.5.

**Comment by ganesh-at-wiw** [comment] 2018-04-17 06:56
I confirm now that the problem is resolved and that, that I can add/remove members to/from private groups via api.
