### ISSUE TITLE
Rocketchat App window becomes blank after opening a Jitsi Conference

### ISSUE THREAD

**Issue by JohnLukeP** [RocketChat/Rocket.Chat#19505] opened 2020-11-11 13:18 UTC
### Description:

When opening a videocall from the Rocketchat windows desktop app (tested on 3.0.2 and 3.0.6), having "always open on a new windows" option enabled for video calls, the server/chat windows becomes blank  (grey) and unusable.
This happens since I've updated Jitsi Docker from 4857 (working properly) to 5142 (having this bug).
No problems, instead, if I use Rocketchat from web browser.

### Steps to reproduce:

1. Having Jitsi Meet Docker Stable 5142 configured as videoconference system (with JWT auth), start a new video call

### Expected behavior:

The conference opens in a a new window and works properly, the rocketchat's main windows has no problem

### Actual behavior:

Rocketchat's main server windows becomes blank (screenshot attached)
![rocket-problem](https://user-images.githubusercontent.com/59082800/98816233-a4f8e980-2428-11eb-80cc-110b0111edfd.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.1
- Operating System:  Linux Ubuntu 18.04.4
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v12.16.1
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: 3.0.2 and 3.0.6 
- Operating System: Windows 10

**Comment by ankar84** [comment] 2020-11-11 13:55
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1841

**Comment by MartinSchoeler** [comment] 2020-11-11 20:10
🔝

**Closed by MartinSchoeler** 2020-11-11 20:10 UTC
