### ISSUE TITLE
Improve rocketchat-irc plugin

### ISSUE THREAD

**Issue by haosdent** [RocketChat/Rocket.Chat#216] opened 2015-06-22 15:31 UTC
Current rocketchat-irc plugin just a prototype, I need do more works to improve it.
- [ ] Add config to enable or disable this plugin
- [x] Reconnect when connection failed between irc server
- [x] Remove unused logs
- [x] Show member status
##

**Comment by engelgabriel** [comment] 2015-06-22 16:39
Is this going to achieve something like https://www.irccloud.com/ ?

**Comment by haosdent** [comment] 2015-06-22 16:53
No sure, I just do it for fun. But I need to make this plugin reliable for other users which want to use it

**Comment by haosdent** [comment] 2015-06-22 16:55
For @posix4e 's question, I think it could replace irccloud finally.

**Comment by engelgabriel** [comment] 2015-06-22 19:48
That's the spirit @haosdent ! :+1:

**Comment by Sing-Li** [comment] 2015-06-26 07:22
Interesting read (try to read to the end - I know its a little dry): 

http://thenextweb.com/insider/2015/03/24/slack-is-quietly-unintentionally-killing-irc/

Then read the *real*, zero-hype account of the very same need/trend referenced by Pierre above.

This is no longer a technology looking for a solution; but an identified trending market void.  

Rocket.Chat can service this niche better than Slack, and give them the forever-FREE, forever-in-their-control promise that they are looking for.

**Comment by engelgabriel** [comment] 2015-06-30 18:33
Depends on #222

**Comment by phillip-white-sociomantic** [comment] 2015-09-28 11:15
Hi All. Are there any instructions on how to get IRC working? I would like to connect to the channels with Pidgin.

**Comment by haosdent** [comment] 2015-09-28 11:25
Hi, this plugin is used for connect irc server. Not provide irc server and wait other client connect it through irc protocol.

**Comment by pierreozoux** [comment] 2016-01-27 14:28
Hi @haosdent and thanks for your work :) Do you have some sort of doc on how to install it? Thanks!

**Comment by simison** [comment] 2016-02-05 08:05
https://www.bountysource.com/issues/22748500-improve-rocketchat-irc-plugin

**Comment by pierreozoux** [comment] 2016-03-06 21:35
Ok, I figured out:
You have to uncomment this line: https://github.com/RocketChat/Rocket.Chat/blob/develop/.meteor/packages#L96

I have a working example here: https://chat.indie.host/channel/indiehosters

I have various remarks on the way it is working and the way we could improve it.

 - [ ] disable auto-join for users
 - [ ] disable auto join for channels
 - [ ] add possibility for admin/moderator to link a channel to irc
 - [ ] when a user join this channel, make him join irc
 - [ ] add possibility for a user to specify nick/pass on irc
 - [ ] admin should be able to specify irc server (I'm fine with freenode at the beginning)

@simison do you to try? (You could create a channel #trustroots and it will auto join the irc channel)

I could work on thess features, but I need ca$h :) Do you think we could run a mini crowdfunding between IndieHosters/Hitchwiki for that? Or is it good enough as this?

**Comment by bott0r** [comment] 2016-03-26 14:26
I actually love IRC have been using it for almost 18 years, how much money is needed, to write a reliable plugin that can be toggeld on/ off if needed.

**Comment by ragesoss** [comment] 2016-04-03 16:36
I came looking for the same thing as @pierreozoux: instructions on how to enable this. The readme for the package is unhelpful: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-irc/Readme.md

Is it possible to enable this from a Sandstorm grain?

**Comment by cpitman** [comment] 2016-07-27 03:13
Looking at the implementation, this could be both simpler and more robust as a server-to-server based plugin. In servet-to-server IRC, a single connection is made to a peer IRC server, and Rocket chat would send a password and identify itself as a server. Over that single connection Rocket Chat and the IRC server would communicate joins/leaves/messages/etc.

That also means that messages to channels are only sent once over a single connection instead of once per client. There wouldn't be any need for caches and deduplication. I'm also assuming this would scale better for a large number of users/messages.

I'd like to take a stab at this, but wanted to see what your reaction is.

**Comment by engelgabriel** [comment] 2016-07-28 16:58
@marceloschmidt can we base this at the slack-bridge package?

**Comment by mpetersen42** [comment] 2016-08-05 17:19
Is anyone still working on this plugin?

**Comment by engelgabriel** [comment] 2016-08-09 21:24
@mpetersen42 no one from the @RocketChat/core team. But @marceloschmidt have been working on the new version of SlackBridge https://github.com/RocketChat/Rocket.Chat/pull/3962 and I believe there is a lot that can be re-used from it.

**Comment by bott0r** [comment] 2016-09-22 08:58
I am looking forward to an update :D

**Comment by toxicgumbo** [comment] 2016-10-06 15:13
I, too, am looking forward to an update.  IRC capability & stability adds substantial usage value.

**Comment by toxicgumbo** [comment] 2016-10-06 17:16
To test out the pros and cons that @pierreozoux mentioned, I cloned the repo, uncommented the IRC package, and used meteor to build a working copy.  

Without any further changes, it appears that the users's first name and not username is used as an IRC username.  Since my first name was taken on Freenode, I was stuck at the login screen while the backend showed repeated attempts to auth on Freenode.  Once I changed my name to something obscure and restarted RocketChat (to interrupt the continued attempts to log in on the backend), I was able to log into both RocketChat locally and IRC.  If one wants to use an authenticated IRC username, your RocketChat password has to match what your Freenode password.

However, I found that I had to first create the channel locally that I wanted to connect to in IRC.  Things got strange from there.  The channel let me enter and only show my attendance, but would alert that the channel didn't exist. I could post comments and embedded material which would show up on the IRC channel, but not vice-versa.  On the backend, I could see all the users in the IRC room as well as room chatter.  RocketChat griped because I had disabled automatic user creation and it appeared that it wanted to create users for all the channel members as actions involving usernames happened (user commenting, user leaving, etc.)  I performed some accounting issues and the room disappeared, so I re-joined and it was read-only (and I was still in the IRC room regardless).  I also can't go into the rooms or users administration screens at all...they just remain white on the settings side of the page (Edit: by going to those URLs directly, something gets resolved and it starts to work again from the admin page, at least for a little while).

Some of this might be tweakable, but that's my first impressions from using the IRC plugin in case someone runs into the same issues.

**Comment by toxicgumbo** [comment] 2016-10-06 22:12
I also recommend making the following change in order for the nick's real name to be a _real name_ and not a placeholder.
```
                # @socket.write "USER #{@user.username} 0 * :Real Name\r\n"
                @socket.write "USER #{@user.username} 0 * :#{@user.name}\r\n"
```

**Comment by toxicgumbo** [comment] 2016-10-12 13:34
As a head's up to those of you interested in this project, some minor development changes have occurred to rocketchat-irc over the past year.  You can view the development branch commit history here:

https://github.com/RocketChat/Rocket.Chat/commits/develop/packages/rocketchat-irc

**Comment by toxicgumbo** [comment] 2016-10-20 21:52
The Rocket.Chat team merged a pull request I made last week into the develop branch.  These changes include:

- An "IRC" settings page for administrators with haosdent's values mapped in as defaults.  An admin can now change the IRC server, port, message cache size, and behavioral regular expressions via the web frontend. 
- A very crude Enable/Disable switch through the admin frontend.
- The username and real name have been remapped properly to the Rocket.Chat user credentials as the previous method was neither ideal nor reliable.  Once user-level settings are added, users will be able to override the username, real name, and password in their settings page.  This is especially useful in environments where a user must use a pre-existing Rocket.Chat account which doesn't match their IRC account(s).
- Performed some housecleaning to prep the package for future growth.
- Added a README.md file with information on how to build Rocket.Chat with IRC support for testing.

I find that this package, for now, is very unstable and don't recommend anyone use it in a production environment.  For instance, the legacy design adds remote IRC users as local Rocket.Chat users, room dynamics are glitchy and can affect Rocket.Chat functionality, and there aren't any robust checks and balances on IRC activity.  In other words, things start to somewhat work, then break, then don't recover until restarting and reversing actions, etc.  I'm going to do what I can to make the functionality at least a bit more predictable while maintaining the core vision of simply grafting IRC capabilities onto existing, similar, Rocket.Chat functionality.  In the meantime, the process for building in IRC support remains obfuscated so nobody accidentally screws up their pre-existing environment.

As an active user of IRC Cloud, Slack, Rocket.Chat, and app-based IRC clients, Rocket.Chat with IRC capabilities will simplify my life and improve the IRC experience.  All of the concerns people mentioned in this issue have been added to a to-do list (for review).  I haven't looked into the Slackbridge suggestion for IRC, however, as I don't see bots as an option for all demographics and I think haosdent made a good foundation to grow from.

**Comment by pierreozoux** [comment] 2016-11-02 12:20
@toxicgumbo There is a pull request here, I'm not sure you saw it.
https://github.com/RocketChat/Rocket.Chat/pull/4667

It looks like the PR is bringing some significant improvement.

**Comment by toxicgumbo** [comment] 2016-11-02 13:26
@pierreozoux Sincere gratitude for the notice on #4667!  I'm thrilled to see added momentum and increased interest, especially when it excites core developers.  Looks like substantial work and I'm glad to see you've been involved in the discussion.

**Comment by Hostile** [comment] 2016-11-05 07:56
In latest rocket chat update irc option is in settings not sure it works tho

**Comment by Syirrus** [comment] 2016-11-07 09:16
How do you use this plugin? Once you connect to an IRC server, do you join channels on IRC through Rocket.Chat?

**Comment by xenithorb** [comment] 2016-12-29 15:43
Being that this is now present in the stable releases... I tried to use it and all it seems to do is crash the server by entering into a loop that consumed 100% cpu. I haven't been able to use this successfully yet. Will work on getting more debug information.

**Comment by geekgonecrazy** [comment] 2016-12-30 05:34
I don't believe the new work to it from: https://github.com/RocketChat/Rocket.Chat/pull/4667 has been merged.  I'm guessing some of those changes might fix the issue you are having

**Comment by Mte90** [comment] 2017-01-11 16:52
Uhm there is a way to move a specific channel to another one inside rocketchat?

**Comment by bott0r** [comment] 2017-02-03 07:32
For me the IRC plugin worked great, what would be great if one could decide which channel/channels should join the IRC network.

**Comment by toxicgumbo** [comment] 2017-02-03 15:31
I bumped pull request https://github.com/RocketChat/Rocket.Chat/pull/4667 in hopes of some movement. @cpitman has taken this in such a (hopeful) direction that it's more or less prohibitive for anyone else to make incremental changes to the current source.

**Comment by Dracozny** [comment] 2017-03-07 08:16
A bit of profile snooping on my part. @cpitman  seemed to take a vacation at the beginning of the year.

**Comment by rikmendes** [comment] 2017-05-16 13:01
Eager to test this, but wondering how to join a channel once connected to the server..

**Comment by brhellman** [comment] 2017-06-21 18:26
I've enabled this through the admin panel, I can see it connecting in the logs, however I'm not sure how to join an existing irc channel or make it actually do anything?  The readme isn't helpful.  I'm more than happy to update it if someone can give me direction.

**Comment by toxicgumbo** [comment] 2017-06-21 19:26
The Readme was just to get something in print so people could even get IRC working at all.  You should be able to change rooms like you would normally in RocketChat and that sends the proper IRC commands on the backend to put you in a channel of the same name.  During the last time I tried this and worked on it, the mapping between the two left a lot to be desired and often led to errors.  That is, if it worked, it worked just well enough; if it didn't work and an error was produced, you pretty much were stuck in a situation where you had to quite RocketChat and restart.  I haven't tried the most recent changes yet, so perhaps this has been improved through something subtle.

**Comment by brhellman** [comment] 2017-06-22 13:37
If the scope of the bounty can be more clearly defined, including getting a working bi-directional plugin that also allows PMs in both ways I'm more than happy to throw in $100

**Comment by geekgonecrazy** [comment] 2018-04-04 19:10
What do those here think of #10113 basically would allow deploying of a small ircd that would federate with Rocket.Chat.  Then allowing irc users to talk via irc/rocket.chat

This would be more seamless.  Users connected on irc would be real users of Rocket.Chat.  They could take their same login and connect to Rocket.Chat.

**Comment by rikmendes** [comment] 2018-04-04 19:41
I like the idea.. But Real users? What if the rocket.chat instance users are fuelled by a LDAP user base ie: cloudron? On Apr 4, 2018 9:11 PM, Aaron Ogle <notifications@github.com> wrote:What do those here think of #10113 basically would allow deploying of a small ircd that would federate with Rocket.Chat.  Then allowing irc users to talk via irc/rocket.chat
This would be more seamless.  Users connected on irc would be real users of Rocket.Chat.  They could take their same login and connect to Rocket.Chat.

**Comment by toxicgumbo** [comment] 2018-04-04 19:41
Based on the comments in #1259, now closed, and the last paragraph in your comments, I read that as if this means IRC users who have a matching username in Rocket.Chat will be able to connect in from IRC and chat with Rocket.Chat users.  Is this correct?  Does this approach abandon the desire expressed in this thread where Rocket.Chat users wish to render IRC channels as rooms within Rocket.Chat and dialogue with IRC-only users?  The advantage to this latter approach is where shops are running Rocket.Chat, but employees might also require IRC interactions and prefer the modernized handling of content that Rocket.Chat provides while still allowing for viewing/setting permissions, etc.

**Comment by geekgonecrazy** [comment] 2018-04-05 01:54
For sure doesn't mean that we are abandoning.  Just was curious if helped solve some peoples use cases.

**Comment by misse** [comment] 2018-05-03 07:05
I have two feature requests for this integration which I can't find any information about, 
When connecting rocketchat to an IRC server

- [ ] SSL support
- [ ] Password support

**Comment by realrill** [comment] 2018-09-10 20:52
Any update for this feature? I just tried to use it but I could not reach any success. To be honest I could not find a proper documentation about the IRC setting page as well as how it should act after a proper setup.

I am happy to help in debugging as much as I can. The latest log, hope it helps.
`[irc][server] Unhandled peer message: {"prefix":"barjavel.freenode.net","server":"barjavel.freenode.net","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Looking up your hostname..."]}
[irc][server] Unhandled peer message: {"prefix":"barjavel.freenode.net","server":"barjavel.freenode.net","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Checking Ident"]}
[irc][server] Unhandled peer message: {"prefix":"barjavel.freenode.net","server":"barjavel.freenode.net","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Found your hostname"]}
[irc][server] Unhandled peer message: {"prefix":"barjavel.freenode.net","server":"barjavel.freenode.net","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** No Ident response"]}
[irc][server] Unhandled peer message: {"prefix":"barjavel.freenode.net","server":"barjavel.freenode.net","command":"err_needmoreparams","rawCommand":"461","commandType":"error","args":["*","SERVER","Not enough parameters"]}
[irc][server] Unhandled peer message: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Closing Link: 127.0.0.1 (Connection timed out)"]}
[irc][server] Connection Closed
`

Version:
`➔ System ➔ startup
➔ +----------------------------------------------------+
➔ |                   SERVER RUNNING                   |
➔ +----------------------------------------------------+
➔ |                                                    |
➔ |  Rocket.Chat Version: 0.68.5                       |
➔ |       NodeJS Version: 8.11.3 - x64                 |
➔ |             Platform: linux                        |
➔ |         Process Port: 3000                         |
➔ |             Site URL: xxxxxxxxxxxxxxxxxxxx  |
➔ |     ReplicaSet OpLog: Disabled                     |
➔ |          Commit Hash: e412d018f8                   |
➔ |        Commit Branch: HEAD                         |
➔ |                                                    |
➔ +----------------------------------------------------+
`

**Comment by RickvLeeuwen** [comment] 2019-02-20 22:12
Hi,
I could not get the IRC Federation working. After some debugging and reading the RFC, i found the following solution:

```  
onConnect() {
    this.log('Connected! Registering as server...');
    this.write({
      command: 'PASS',
      parameters: [this.config.passwords.local] //Removed the other parameters since these should not be passed from client to server. According to the RFC. When these are passed, you will always get an authorisation failed on the IRC link
    });
    this.write({
      command: 'SERVER',
      parameters: [this.config.server.name, '1'], \\Added the 1 because it needs this as <hops> value, according to the RFC. If not, you will see an error that the SERVER command does not have enough parameters.
      trailer: this.config.server.description
    });
  }
```

**Comment by primozc** [comment] 2019-06-05 12:45
Hello,

I am trying to connect my IRCd (UnrealIRCd v.4) to Rocket.Chat. Unfortunately it is not working. Error (log file) is attached below this post. Any idea how to solve this issue?

Kind regards,


### Steps to reproduce:

IRC Federation settings:
Enabled: True
Protocol: RFC2813
Host: irc.server.si
Port: 65520
Name: irc.server.si
Description: Chat.si IRC Bridge
Local Password: Empty
Peer Password: IRCD password I guess?

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Debian 9
- Deployment Method: Manual Debian Installation (https://rocket.chat/docs/installation/manual-installation/debian/)
- Number of Running Instances: 1
- DB Replicaset Oplog: mmapv1
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.10

### Relevant logs:

I20190605-13:58:43.787(2) Updating process.env.MAIL_URL 
I20190605-13:58:44.070(2) [irc][server] Connecting to @irc.server.si:65520 
I20190605-13:58:44.076(2) [irc][server] Connected! Registering as server... 
I20190605-13:58:44.078(2) [irc][server] Sending Command: PASS  0210 ngircd 
I20190605-13:58:44.078(2) [irc][server] Sending Command: SERVER irc.server.si :server.si IRC Bridge 
I20190605-13:58:44.082(2) [irc][server] Unhandled peer message: {"prefix":"irc.server.si","server":"irc.server.si","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Looking up your hostname..."]} 
I20190605-13:58:44.082(2) [irc][server] Unhandled peer message: {"prefix":"irc.server.si","server":"irc.server.si","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Found your hostname (cached)"]} 
I20190605-13:58:46.226(2) [irc][server] Unhandled peer message: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Not enough SERVER parameters"]} 
I20190605-13:58:46.227(2) [irc][server] Unhandled peer message: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Closing Link: [94.130.225.252] (Not enough parameters)"]} 
I20190605-13:58:46.233(2) [irc][server] Connection Closed 
I20190605-13:58:46.657(2) ➔ server.js:207 System ➔ startup

**Comment by primozc** [comment] 2019-06-05 12:46
Hello,

I am trying to connect my IRCd (UnrealIRCd v.4) to Rocket.Chat. Unfortunately it is not working. Error (log file) is attached below this post. Any idea how to solve this issue?

Kind regards,


### Steps to reproduce:

IRC Federation settings:
Enabled: True
Protocol: RFC2813
Host: irc.server.si
Port: 65520
Name: irc.server.si
Description: Chat.si IRC Bridge
Local Password: Empty
Peer Password: IRCD password I guess?

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Debian 9
- Deployment Method: Manual Debian Installation (https://rocket.chat/docs/installation/manual-installation/debian/)
- Number of Running Instances: 1
- DB Replicaset Oplog: mmapv1
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.10

### Relevant logs:

I20190605-13:58:43.787(2) Updating process.env.MAIL_URL 
I20190605-13:58:44.070(2) [irc][server] Connecting to @irc.server.si:65520 
I20190605-13:58:44.076(2) [irc][server] Connected! Registering as server... 
I20190605-13:58:44.078(2) [irc][server] Sending Command: PASS  0210 ngircd 
I20190605-13:58:44.078(2) [irc][server] Sending Command: SERVER irc.server.si :server.si IRC Bridge 
I20190605-13:58:44.082(2) [irc][server] Unhandled peer message: {"prefix":"irc.server.si","server":"irc.server.si","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Looking up your hostname..."]} 
I20190605-13:58:44.082(2) [irc][server] Unhandled peer message: {"prefix":"irc.server.si","server":"irc.server.si","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Found your hostname (cached)"]} 
I20190605-13:58:46.226(2) [irc][server] Unhandled peer message: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Not enough SERVER parameters"]} 
I20190605-13:58:46.227(2) [irc][server] Unhandled peer message: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Closing Link: [94.130.225.252] (Not enough parameters)"]} 
I20190605-13:58:46.233(2) [irc][server] Connection Closed 
I20190605-13:58:46.657(2) ➔ server.js:207 System ➔ startup

**Comment by primozc** [comment] 2019-06-05 12:56
> Hi,
> I could not get the IRC Federation working. After some debugging and reading the RFC, i found the following solution:
> 
> ```
> onConnect() {
>     this.log('Connected! Registering as server...');
>     this.write({
>       command: 'PASS',
>       parameters: [this.config.passwords.local] //Removed the other parameters since these should not be passed from client to server. According to the RFC. When these are passed, you will always get an authorisation failed on the IRC link
>     });
>     this.write({
>       command: 'SERVER',
>       parameters: [this.config.server.name, '1'], \\Added the 1 because it needs this as <hops> value, according to the RFC. If not, you will see an error that the SERVER command does not have enough parameters.
>       trailer: this.config.server.description
>     });
>   }
> ```
> 
> Now still the bridge is not working, but at least the connection is setup now...
> 
> ```
> Received PASS command, continue registering...
> Handling peer message: SERVER irc.xxx.nl 1 : IRC Server 
> Received SERVER command, waiting for first PING...
> [JOIN and MODE and such....]
> [irc][server] Handling peer message: PING :irc.xxx.nl 
> [irc][server] Sending Command: :xxx.yyy.nl PONG irclink.xxx.nl 
> ```

Did you change this in /opt/Rocket.Chat/programs/server/app/app.js ?

**Comment by primozc** [comment] 2019-06-05 14:44
Ok, how I finally managed to connect Rocket.Chat and IRCd. Just like @RickvLeeuwen it is necessary to edit the app.js file:

`onConnect() {
    this.log('Connected! Registering as server...');
    this.write({
      command: 'PASS',
      parameters: [this.config.passwords.local] //Removed the other parameters since these should not be passed from client to server. According to the RFC. When these are passed, you will always get an authorisation failed on the IRC link
    });
    this.write({
      command: 'SERVER',
      parameters: [this.config.server.name, '1'], \\Added the 1 because it needs this as <hops> value, according to the RFC. If not, you will see an error that the SERVER command does not have enough parameters.
      trailer: this.config.server.description
    });
  }`

In addition, the link block must be enabled in the IRCd config file, so that the servers can connect to one another.

My unrealircd.conf:
`listen {
         ip 127.0.0.1;
         port 6900;
         / * options {serversonly; }; * /
};

link www.yourdomain.com
{
         incoming {
                 mask *;
         };
 
         outgoing {
                 bind-ip *;
                 hostname 127.0.0.1;
                 port 6900;
         };
 
         password "pass";
 
         class servers;
};`

**Comment by JoKneeMo** [comment] 2019-07-03 23:30
I haven't found a way to edit the snapd locally.
It looks like the file would be [app/irc/server/servers/RFC2813/index.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/irc/server/servers/RFC2813/index.js)

Is there a pull request to update this?

**Comment by Sing-Li** [comment] 2019-10-31 18:17
We have merged https://github.com/RocketChat/Rocket.Chat/pull/10113  

If there are additional concerns or problems, let's open new tickets against the new feature.  Thanks.

**Closed by Sing-Li** 2019-10-31 18:17 UTC
Labels: Triaged, feat: irc, feat: protocols
