### ISSUE TITLE
Enhancement : Add a 1 Hour time out chat session timer to end an in-progress chat that has been left idle.

### ISSUE THREAD

**Issue by nitinsonawane234** [RocketChat/Rocket.Chat#33458] opened 2024-10-04 10:28 UTC
Add a (1 Hour) time out chat session timer to end an in-progress chat that has been left idle.

**Comment by reetp** [comment] 2024-10-04 12:55
Closing as this is not a bug in Rocket.Chat

Please open in the correct repository

https://github.com/RocketChat/feature-requests

**Closed by reetp** 2024-10-04 12:55 UTC
