### ISSUE TITLE
Do rocketchat has functionality of showing that a message has been seen or delivered to the user?

### ISSUE THREAD

**Issue by KulshresthJangid** [RocketChat/Rocket.Chat#27033] opened 2022-10-09 05:36 UTC

**Comment by debdutdeb** [comment] 2022-10-09 05:53
Yes, we have read receipts https://docs.rocket.chat/guides/administration/admin-panel/settings/message

Closing since not a bug.

**Closed by debdutdeb** 2022-10-09 05:53 UTC
