### ISSUE TITLE
Poison message

### ISSUE THREAD

**Issue by Janevski** [RocketChat/Rocket.Chat#7086] opened 2017-05-25 07:57 UTC
**Description:**
If a user posts a poison message the chat room becomes permanently unavailable to everyone that reads it because whoever tries to open it via Firefox, Chrome or even desktop client app gets 100% CPU usage and memory bloat until the process is killed.
This is JavaScript client bug.

**Prerequisites:**
Poison message attached.
[poison.msg.txt](https://github.com/RocketChat/Rocket.Chat/files/1028332/poison.msg.txt)

**Scenario:**
- Open a chat room.
- type in the poison message
- press enter to send it
- watch the world burn
This is replicable 100% of the times.

**Note:**
A multitude of text variation poison messages exist.

**Info:**
Rocket.Chat Version: 0.56.0; 0.53.0 is affected too
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.8.2

**Comment by lucasvanhalst** [comment] 2017-05-25 11:08
The server also gets in a 100% cpu usage loop, so this issue is quite severe.

**Comment by MartinSchoeler** [comment] 2017-05-25 12:37
duplicate of #6814

**Closed by MartinSchoeler** 2017-05-25 12:37 UTC
