### ISSUE TITLE
Almost all Icon missing in firefox 52.4.1 (latest version of firefox that support windows XP)

### ISSUE THREAD

**Issue by aredean** [RocketChat/Rocket.Chat#8755] opened 2017-11-02 03:17 UTC
### Description:
I have rocket.chat server deployed using snap. So, when my server connected to the Internet, the snap refresh and update automatically. And the problem happen, all my client that using firefox 52.4.1 saw no icons. I cannot update the firefox because almost all client are using windows XP.

### Server Setup Information:
* Version of Rocket.Chat Server: 0.59.2
* Operating System: Linux x64
* Deployment Method: snap
* Node Version: v4.8.4

### Steps to Reproduce:
Client side (firefox 52.4.1)
1. Access rocket chat
2. All icon (icon that using svg tag i think) are missing. From all sidebar icons, reply icon, emoticon icon, text bold, italic icon, account management icon and in administration also. 

### Expected behavior:
All icon show like a charm.

### Actual behavior:
All icon missing.

**Comment by exagon** [comment] 2017-11-02 16:24
I have the same problem with firefox and Google Chrome : 49.0.2623.112 on Windows XP.

**Comment by MartinSchoeler** [comment] 2017-11-03 10:33
Duplicate of #7980

**Closed by MartinSchoeler** 2017-11-03 10:33 UTC
Labels: subj: UI Redesign, type: bug
