### ISSUE TITLE
Send messages from livechat agent to livechat client does not work

### ISSUE THREAD

**Issue by MIKNOTAURO** [RocketChat/Rocket.Chat#8591] opened 2017-10-22 13:32 UTC
### Description:

Live Chat | Send messages from livechat agent to livechat client does not work

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Linux 4.4.0-93-generic Ubuntu x86_64 x86_64 x86_64 GNU/Linux
* Deployment Method: meteor/source code
* Number of Running Instances: 2
* DB Replicaset Oplog: Disabled
* Node Version: 4.8.4

### Steps to Reproduce:

Just run my build without any change

### Relevant logs:

Exception while invoking method 'sendMessage' TypeError: Cannot read property 'blocker' of undefined
  at [object Object].Meteor.methods.sendMessage (/vagrant/bundle/programs/server/packages/rocketchat_lib.js:15629:59)
  at [object Object].methodsMap.(anonymous function) (/vagrant/bundle/programs/server/packages/rocketchat_lib.js:1276:26)
  at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at maybeAuditArgumentChecks (/vagrant/bundle/programs/server/packages/ddp-server.js:1857:12)
  at /vagrant/bundle/programs/server/packages/ddp-server.js:903:20
  at [object Object].EVp.withValue (packages/meteor.js:1134:15)
  at /vagrant/bundle/programs/server/packages/ddp-server.js:902:47
  at [object Object].EVp.withValue (packages/meteor.js:1134:15)
  at /vagrant/bundle/programs/server/packages/ddp-server.js:901:46
  at [object Object]._.extend.protocol_handlers.method (/vagrant/bundle/programs/server/packages/ddp-server.js:874:21)
  at /vagrant/bundle/programs/server/packages/ddp-server.js:753:85

![image](https://user-images.githubusercontent.com/2102746/31862392-d6afcfb6-b702-11e7-81a0-c4ec570f4333.png)

![image](https://user-images.githubusercontent.com/2102746/31862401-ee23dd7c-b702-11e7-9543-290a2d5198ad.png)

**Comment by MartinSchoeler** [comment] 2017-10-23 13:33
Duplicate of #8557

**Closed by MartinSchoeler** 2017-10-23 13:33 UTC
Labels: feat: livechat, type: bug
