### ISSUE TITLE
Can't login with  sAMAccountName

### ISSUE THREAD

**Issue by nORKy54** [RocketChat/Rocket.Chat#7405] opened 2017-07-04 22:06 UTC
Rocket.Chat Version:  0.57
Running Instances:  1
DB Replicaset OpLog: false
Node Version: 4.8.1

After update 0.57, I can't login using my sAMAccountName. I need to use my email.
If the Active directory account does not have email, login with sAMAccountName works.
In logs, I can see the search works:

`LDAP ➔ Search.info Search result count 1
[... my user info printed are ok]`

And after, I can see this:
`[LDAPSync ➔ debug user { email: undefined, _id: 'ktb98PyMhbst8jFn5' } `

**Comment by willihelm** [comment] 2017-07-05 12:53
Same for me. Only Email works after the update.

**Comment by paulrobello** [comment] 2017-07-06 03:48
Same here.

**Comment by maxdwit** [comment] 2017-07-06 07:13
Same here.

**Comment by KervyN** [comment] 2017-07-06 10:37
Try to disable LDAP Avatar Sync, worked for us.

**Comment by nORKy54** [comment] 2017-07-06 11:21
Thanks @KervyN ! it works

**Comment by maxdwit** [comment] 2017-07-06 11:46
Confirmed @KervyN  Disable avatar sync fixed it for the moment.

**Comment by rodrigok** [comment] 2017-07-06 19:42
Anyone can provide a LDAP server for tests?

**Comment by rodrigok** [comment] 2017-07-06 19:43
What happens if you enable the Avatar Sync again?

**Comment by KervyN** [comment] 2017-07-06 19:53
We were not able to log in

**Comment by paulrobello** [comment] 2017-07-06 20:02
Disabling avatar Sync worked for us

**Comment by geekgonecrazy** [comment] 2017-07-07 01:17
Ok worked a case that also has this issue.  Sync worked fine.  Brought accounts over, logging with email worked.  But logging in with username did not.  Disabling avatar sync was the magic bullet that got it working.

**Comment by sc10n** [comment] 2017-07-07 22:00
I have disabled Avatar sync and my ldap users are still unable to log in. I am getting the following in my log:
```
rocketchat_logger rocketchat_logger.js:377 [31mLDAPHandler ➔ error [Error: invalid nested parens] 
```
I am on 0.57.1.

**Comment by pedroxim** [comment] 2017-07-10 13:39
After disabling avatar, it works but lost our pictures :-(

**Comment by frdmn** [comment] 2017-07-11 14:11
[`@ranga`](https://demo.rocket.chat/channel/support?msg=nrBKj8oxFBaWY5EE3) in the demo platform was affected by this as well: 

<img width="882" alt="bildschirmfoto 2017-07-11 um 16 07 46" src="https://user-images.githubusercontent.com/944459/28072399-261bd19a-6653-11e7-8f7c-588eac06892b.png">

As well as [`@bad-bb`](https://demo.rocket.chat/channel/support?msg=iEsSbKHHoPqGnhQZL):

<img width="1156" alt="bildschirmfoto 2017-07-11 um 16 08 43" src="https://user-images.githubusercontent.com/944459/28072427-4535f7f4-6653-11e7-8b3e-1a1745c45c0d.png">

and [`@t.m.andersen`](https://demo.rocket.chat/channel/support?msg=fk4zFAmCvDtckfhJr) ... : 

<img width="424" alt="bildschirmfoto 2017-07-11 um 16 09 24" src="https://user-images.githubusercontent.com/944459/28072455-5e591374-6653-11e7-9872-325938d6d698.png">

and [`@sk.siv`](https://demo.rocket.chat/channel/support?msg=CbNvJcs8p7T7eBQGD):

<img width="608" alt="bildschirmfoto 2017-07-11 um 16 10 24" src="https://user-images.githubusercontent.com/944459/28072498-7e2ecebe-6653-11e7-8c6d-3b62296f4fa1.png">

**Comment by sampaiodiego** [comment] 2017-07-11 21:07
@nORKy54 can you please try please enabling `Merge existing users`?
![image](https://user-images.githubusercontent.com/8591547/28090729-b1064dca-6663-11e7-97d9-5095529c2394.png)

**Comment by rodrigok** [comment] 2017-07-14 14:19
Closed by #7472
Please reopen it if the problem persists after the release of version 0.57.2

**Comment by KervyN** [comment] 2017-07-16 13:46
It still persists.

**Comment by TwizzyDizzy** [comment] 2017-07-17 09:13
For me too, the issue stands as mentioned above:

    Rocket.Chat Version: 0.57.2
    Database Version: 99
    Running Instances: 1
    DB Replicaset OpLog: false
    Node Version: 4.8.3

* LDAP login **not possible**, when avatar sync is enabled
* LDAP login **possible**, when avatar sync is disabled, no avatars though (quite obvious)

**Comment by KervyN** [comment] 2017-07-17 09:17
The workaround we use: Activate avatarsync, sync ldap data, disable avatarsync. I began to do this as a morning routine

**Comment by TwizzyDizzy** [comment] 2017-07-17 09:20
Just to be clear: by `sync ldap data` your mean the option `Import LDAP users` in `Administration > LDAP`, right?

**Comment by KervyN** [comment] 2017-07-17 09:22
Yes

**Comment by maxdwit** [comment] 2017-08-01 08:54
@KervyN  Your daily workaround is now mandatory here, until this is fixed.

**Comment by maxdwit** [comment] 2017-08-09 13:25
Problem persists in 0.57.3 turning "Sync Profile Pictures / Profilbilder synchronisieren" on.
`validateLogin ->  ....  message: 'Forbidden [forbidden]',      errorType: 'Meteor.Error' ....`

**Comment by TwizzyDizzy** [comment] 2017-08-09 13:29
Problem was not supposed to be fixed in 0.57.3 (see changelog). Issue #7472 is scheduled for 0.58.0 (currently there are RC versions available, see https://github.com/RocketChat/Rocket.Chat/releases).

Cheers
Thomas

**Comment by TwizzyDizzy** [comment] 2017-08-22 16:15
As I see it, this issue hasn't been resolved in 0.58.1, has it?

So the state at my end is as before:

    Rocket.Chat Version: 0.58.1
    Database Version: 99
    Running Instances: 1
    DB Replicaset OpLog: false
    Node Version: 4.8.4

* LDAP login **not possible**, when avatar sync is enabled
* LDAP login **possible**, when avatar sync is disabled, no avatars though (quite obvious)

**Comment by TwizzyDizzy** [comment] 2017-08-28 18:21
Is this issue gone for others? I'm asking, because I guess this has an impact an virtually everybody who uses LDAP (usually companies). Or is everybody using the "workaround"?

Cheers
Thomas

**Comment by KervyN** [comment] 2017-08-28 18:46
No, Issue still there. Check https://github.com/RocketChat/Rocket.Chat/issues/7773

**Comment by TwizzyDizzy** [comment] 2017-09-05 09:05
Can I somehow help debugging to fix this rather urgent issue as it blocks us from upgrading from 0.56.0 to a recent release of RC.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment] 2017-09-11 13:59
In accordance with [this](https://demo.rocket.chat/channel/support?msg=FAJb23wYMzsgHmXks) feedback by @sampaiodiego I will again summarize the current situation in the hopes of providing valuable information in order to fix this problem:

**Issue**

Beginning with Rocket.Chat 0.57.0 (my LIVE instance is on 0.56.0, my DEV instance is currently on 0.59.0-rc.4.), there is an issue concerning the authentication against an ActiveDirectory. Also every release after 0.57.0 has this issue.

**Tried mitigations**

**1)** [PR 7472](https://github.com/RocketChat/Rocket.Chat/pull/7472) implies, that activating the LDAP setting `Merge existing users` can mitigate the problem. This is not the case with my problem. It may also be the case that I'm misreading the information over there.

**2)** it was suggested above, that disabling `Avatar Sync` in `LDAP` settings would somehow mitigate this issue. **That is true in my case**. Though, quite obviously, avatars won't get synced anymore. **Side note**: one might argue, that the issue isn't "that bad", if only avatars are missing, yet I find avatars to be a central part of the overall user experience that helps users finding their way around Rocket.Chat.

**Logs**
[rocket.txt](https://github.com/RocketChat/Rocket.Chat/files/1292662/rocket.txt)

This is a logfile of a failing login with the `sAMAccountName` as login username. Log level is Debug (2)

Interesting enough, there is the following error, when I login with the local administrator account:

    rocketchat_logger rocketchat_logger.js:375 LDAPHandler ➔ error [Error: User not Found]

Yet when I login with `sAMAccountName`, there is the UI feedback "user not found", but no log message as the above.

**Speculation about where this error might have come from**

The Rocket.Chat [changelogs of 0.57.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/0.57.0) my give a clue as to what commits/pull requests may (!) have caused the issue (those are issues that involve the keywords `avatar` or `LDAP`:

https://github.com/RocketChat/Rocket.Chat/pull/6921
https://github.com/RocketChat/Rocket.Chat/pull/7030
https://github.com/RocketChat/Rocket.Chat/pull/7055
https://github.com/RocketChat/Rocket.Chat/pull/6788
https://github.com/RocketChat/Rocket.Chat/pull/7045
https://github.com/RocketChat/Rocket.Chat/pull/6972
https://github.com/RocketChat/Rocket.Chat/pull/7352

Please don't hesitate to ask for further details.

Cheers
Thomas

**Comment by sampaiodiego** [comment] 2017-09-11 19:57
Guys I just submitted the PR https://github.com/RocketChat/Rocket.Chat/pull/8099 which I think solves this issue.

I do not have an LDAP server with avatars for testing, so I had to hack the [sync.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-ldap/server/sync.js) file to read the avatar from a file instead the AD.

So if you guys can please test the PR and give some feedback that would be more than welcome.

**Comment by TwizzyDizzy** [comment] 2017-09-12 09:23
For those of you who want to test the change: it seems as though the file path from the PR doesn't reflect on the filesystem location of that code passage. I'm on `0.59.0-rc.4` and the code passage from the PR seems to be contained in the file `/opt/rocketchat/bundle/programs/server/packages/rocketchat_ldap.js` (beginning from line 677). I guess there is some node packaging or compiling foo done that combines several files to form this file in the end.

Be that as it may, I just tested that piece of fixed code **and I'm now able to login in again with sAMAccountName!**. The avatar seems to be set correctly (at least I see the correct avatar that seems to be drawn from AD/LDAP).

Great job! :)

I would love to see this confirmed by others ASAP so this can maybe make it's way to 0.59.0-rc.5 (or final release).

Cheers & Thanks to @sampaiodiego 
Thomas

**Comment by TwizzyDizzy** [comment] 2017-09-13 09:18
Would love to hear of @KervyN @maxdwit @pedroxim @paulrobello @nORKy54 @willihelm 

Cheers
Thomas

**Comment by KervyN** [comment] 2017-09-13 09:20
Hi, 
currently no spare time to check that. Sorry.

**Closed** 2017-09-13 22:32 UTC
Labels: feat: accounts, subj:  Auth - LDAP, type: bug

**Comment by mauricio-sonegatti** [comment] 2017-09-21 22:55
I just tested, I spent yesterday half a day trying to understand why I could login with the user mail but not the  sAMAccountName.
Today after reading this, everything is working as intended, I first tried to just disable the avatar sync and started working perfectly.
Afterwards, I installed the RC7 through snap  (something I didn't saw anywhere how to do it, and I was not familiar with snap... maybe put an article about the "sudo snap refresh rocketchat-server --candidate" somewhere).
Everything is working now, Avatar correctly synced and  sAMAccountName working as intended.
@TwizzyDizzy @sampaiodiego  thanks!!

**Comment by KervyN** [comment] 2017-09-28 08:04
Hi, 
we updated to 0.58.3 today and the issue still persists. We are not able to login via LDAP credentials when profile picture sync is enabled.

**Comment by TwizzyDizzy** [comment] 2017-09-28 08:16
A pity you didn't read the thread. Because otherwise you would've gathered from [this](https://github.com/RocketChat/Rocket.Chat/issues/7405#issuecomment-328795696) comment, that the issue might be fixed only from 0.59.0-rc.5 on.

Not being rude here - happens to everybody, so just take it as a friendly reminder ;)

Cheers
Thomas

**Comment by KervyN** [comment] 2017-09-28 08:55
Oh man, you are right. Haven't thought about the possibility that the RC fixes are not by default included in the normal updates (non RC) I do. My bad, sorry.

**Comment by r4nc0r** [comment] 2020-09-03 11:48
Rocket.Chat Version: 3.6.0
Running Instances: 4
DB Replicaset OpLog: true

After our recent update to 3.6.0 this issue is back! I cant login with my samaccountname when Profilepicture sync is activated. 

Please Help
