### ISSUE TITLE
User status is not being updated

### ISSUE THREAD

**Issue by leitmori** [RocketChat/Rocket.Chat#25194] opened 2022-04-06 19:01 UTC
**Describe the bug**
The user status remains unchanged in the desktop app.

What operating system and which version? macOS 12.3.1
Which version of Rocket.Chat (Server)? 4.6.0
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.8.2

**To Reproduce**
Open the desktop app. Even after 5 minutes the status in the DM section was not updated.

**Expected behavior**
The status of users is updated periodically.

**Screenshots**
Desktop app:
<img width="53" alt="Screen Shot 2022-04-06 at 20 48 02" src="https://user-images.githubusercontent.com/29522608/162047589-a6bd2980-fe21-499b-8c98-296975cd20a4.png">
Browser:
![Screen Shot 2022-04-06 at 20 48 13](https://user-images.githubusercontent.com/29522608/162047605-cdc5de75-2ecf-49c2-a9dd-c734b877eb73.png)

**Additional context**
Server log contains many entries with
`{"level":50,"time":"2022-04-06T19:20:31.100Z","pid":357,"hostname":"DOMAIN.COM","name":"StreamBroadcast","section":"Stream","msg":"Stream broadcast from 'undefined:3002' to 'localhost:3001' with name local does not exist"} `

**Comment by sampaiodiego** [comment] 2022-04-19 18:02
the `StreamBroadcast` message is actually related to desktop notifications and will be fixed by #25220

I couldn't reproduce this issue though

**Comment by sampaiodiego** [comment] 2022-04-19 18:36
ok.. a bit trickier to reproduce, but it is totally related to https://github.com/RocketChat/Rocket.Chat/issues/25163 and will also be fixed by https://github.com/RocketChat/Rocket.Chat/pull/25220

**Closed** 2022-04-19 18:47 UTC

**Comment by ankar84** [comment] 2022-04-20 04:00
Test 4.6.3 and can tell that presence statuses exchange works again!
Thanks, Diego!
