### ISSUE TITLE
Bots are not tagged as bots when using the REST API

### ISSUE THREAD

**Issue by ruberVulpes** [RocketChat/Rocket.Chat#7718] opened 2017-08-10 21:07 UTC
### Description:

I have a bot to use outgoing webhooks. When it processed the outgoing response it's properly tagged as a bot and I can filter by that to prevent a loop. However when I post a message to the same channel saying that the message was processed at the server the bot is no longer tagged as a bot and I can no longer filter by it causing a loop.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.3
* Operating System: Linux Mint
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: unsure
* Node Version: 4.2.6

### Steps to Reproduce:

1. Post using a bot account in a channel that a webhook looking for message sent listens on. 

### Expected behavior:

Incoming message from bot account be tagged as a bot

### Actual behavior:

Incoming message is not tagged as a bot account

### Relevant logs:
Response from Server Log:

{ params: {},   method: 'POST',   url: 'http://localhost:4000/',   data:     { token: '3NBykpc697FrcqdSvCnRF3EQ',      bot: { i: 'WJcdvWfgER8ivdiYX' },      channel_id: 'WSvMeS2ZXR9yddEk6',      channel_name: 'testChannel',      message_id: 'MWad4vX6Q3tvQuPjM',      timestamp: Thu Aug 10 2017 13:54:14 GMT-0700 (PDT),      user_id: 'HPw5KSRjfaCW8qYqE',      user_name: 'Rob.Bot',      text: [removed] },   auth: undefined,   npmRequestOptions: { rejectUnauthorized: true, strictSSL: true },   headers: { 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36' } } 

Rest API Message Log:
{ params: {},   method: 'POST',   url: 'http://localhost:4000/',   data:     { token: '3NBykpc697FrcqdSvCnRF3EQ',      bot: false,      channel_id: 'WSvMeS2ZXR9yddEk6',      channel_name: 'testChannel',      message_id: 'pGBLd52cgsFY5QG9L',      timestamp: Thu Aug 10 2017 13:54:19 GMT-0700 (PDT),      user_id: 'HPw5KSRjfaCW8qYqE',      user_name: 'Rob.Bot',      text: [removed] }, auth: undefined,   npmRequestOptions: { rejectUnauthorized: true, strictSSL: true },   headers: { 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36' } }

**Comment by graywolf336** [comment] 2017-08-16 14:56
The `bot` property is working as intended, it only marks the integration messages as bots with the `i` property being the integration. Bot accounts are typically marked with the role `bot` and then filtered that way.

@RocketChat/core Do we actually want to mark each individual message as `bot` when a user with the role `bot` sends a message?

**Comment by jszaszvari** [comment] 2017-08-16 15:04
@graywolf336 out of curiosity, is there a way to Override the i tag on a message using the incoming webhooks to remove the bot tag. 

I think there used to be a way as I remember making the tag go away but I've forgotten.

**Comment by graywolf336** [comment] 2017-08-16 16:46
@jszaszvari I am not sure, I actually only recently found out about that tag so I don't know much about it.

**Comment by sampaiodiego** [comment] 2017-09-18 14:43
> Do we actually want to mark each individual message as bot when a user with the role bot sends a message?

I'm not sure.. I would say no, since we tag `BOT` from the role already.

**Comment by timkinnane** [comment] 2018-03-20 06:47
Closing this because it works as intended. Message sent by bot are visually marked by setting the user role to Bot. The only issue would be if an integration is sending messages using a user's account, where that message should be specifically tagged, but I don't know if that's a thing anyone needs. If so, please comment and we can re-open.

**Closed by timkinnane** 2018-03-20 06:47 UTC
Labels: feat: api, feat: rest, subj: Bots
