### ISSUE TITLE
PDF preview produces errors

### ISSUE THREAD

**Issue by mmrvelj** [RocketChat/Rocket.Chat#18829] opened 2020-09-08 14:38 UTC
### Description:

I have upgraded v3.0.7 to v3.6.0, and after upgrade PDF document preview is not working anymore, instead I see following errors in browser console:

```
Uncaught (in promise) Error: Removed API method: PDFDocumentLoadingTask.then, use the `promise` getter instead.
    at r.then (/node_modules/pdfjs-dist/build/pdf.js:23)
```

### Steps to reproduce:

* Try to preview any uploaded PDF file in chat by clicking on the right arrow 

### Expected behavior:

* document preview is shown

### Actual behavior:

* document is not shown and spinner spins forever
* above mentioned error is shown in browser console

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: CentOS 7.7
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: Chrome 85.0.4183.83 (Official Build) (64-bit) & Firefox 80.0.1 (64-bit)
- Operating System: Windows 10 Pro

### Additional context

* Server is upgraded from version 3.0.7 . Server is working without issues for more than 2 years now. All data is preserved and everything else seems to be working fine.
* PDF file download works fine, just preview is affected

### Relevant logs:

* No relevant logs on server

**Comment by ayr-ton** [comment] 2020-09-09 01:05
Maybe related to #18323?

**Comment by phriedrich** [comment] 2020-09-09 14:05
This looks like a duplicate of #18740

**Comment by mmrvelj** [comment] 2020-09-09 18:38
> This looks like a duplicate of #18740

Yes, I agree, this is a duplicate of #18740

**Closed** 2020-09-18 19:55 UTC
