### ISSUE TITLE
Mapping user in channels based on LDAP groups?

### ISSUE THREAD

**Issue by Abraka** [RocketChat/Rocket.Chat#5252] opened 2016-12-18 17:09 UTC
Your Rocket.Chat version: latest

Hello,
Its possible with latest version of rocket chat make connection between user channels and LDAP groups?
Main idea is, adding user in AD to specific group like ROCKETCHAT-HR, ROCKETCHAT-MANAGERS etc. and base on this user will be automatically joined into channel-s lets say with the same name(or group of channels) - ROCKETCHAT-HR. So I will have control over what default channel-s user will be joined at start.

**Comment by o-jans** [comment] 2018-06-21 11:18
That feature would be very useful.

**Comment by lucassmacedo** [comment] 2018-08-16 15:50
Please!! This feature would be very useful.

**Comment by adanielvv** [comment] 2018-09-26 14:58
duplicate of #2759

**Comment by wreiske** [comment] 2019-04-29 07:58
Pull request is in: #14278

**Closed** 2019-08-21 01:58 UTC
Labels: subj:  Auth - LDAP, type: support
