### ISSUE TITLE
After renaming a user, it didn't update the membership of the department

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#2283] opened 2016-02-18 21:07 UTC
![image](https://cloud.githubusercontent.com/assets/1000217/13158138/b62f2c5e-d672-11e5-9170-4db527224fe5.png)

**Comment by sampaiodiego** [comment] 2016-02-19 11:56
duplicate of #2115

**Closed by sampaiodiego** 2016-02-19 11:56 UTC
Labels: feat: livechat
