### ISSUE TITLE
Pinned message can be unpinned by anyone

### ISSUE THREAD

**Issue by johnypeterson** [RocketChat/Rocket.Chat#21822] opened 2021-04-27 13:55 UTC
### Description:

Once a user pinned a message - it can be unpinned by any other user, which causes a mess in rooms. Wouldn't it be more logical that only a user who made a pin could unpin it (except room owner) ?
Also, there is no mention of who unpinned a message.

### Steps to reproduce:

1. Log in to a server with simple user permissions
2. Open any room and find pinned messages there
3. Unpin any message which was not pinned by you

### Expected behavior:

Simple user shouldn't be able to unpin messages pinned by another user

### Actual behavior:

Simple user can unpin messages pinned by another user

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.3
- Operating System: Windows, Mac, Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.0
- MongoDB Version: 3.6.20

**Comment by KevLehman** [comment] 2021-05-03 17:32
Hey! After a conversation with the product team, we decided this was not a bug and as a result, we won't attempt to modify the current behavior :)

Thanks for submitting this as it gave us the opportunity to settle the behavior. For now, I'm closing this & the PR.

**Closed by KevLehman** 2021-05-03 17:32 UTC
