### ISSUE TITLE
Rocket.Chat opens LDAP connections but never closes them

### ISSUE THREAD

**Issue by inty** [RocketChat/Rocket.Chat#3982] opened 2016-08-11 09:06 UTC
Your Rocket.Chat version: 0.34

I know I'm not running the latest version but I couldn't find any commits that should have fixed the issue I'm having so I'm going to assume it's still there in 0.36.

Anyway, it seems like Rocket.Chat is opening connections to our OpenLDAP server (2.4.40 running on Debian Jessie) but never closing them. Not sure when it's opening them, doesn't seem to be on every login at least when I tested that. I discovered this because when it had been running for a month or so it was using something like 650 connections to our LDAP server whereupon slapd reached the 1024 limit and got "too many open files" making all hell break loose.

In any case, it is running now. However, while it started out with a reasonable 5 connections it's been steadily increasing and is now at 74 connections after running for 4 days.

**Comment by MartinSchoeler** [comment] 2016-08-11 14:21
Thank you for the bug report @inty! Unfortunately, we have no access to an OpenLDAP server. Please keep us updated of the situation, and let us know if you can reliably reproduce the problem. Watching for error messages on the console when disconnection is expected may also help.

**Comment by engelgabriel** [comment] 2016-08-11 14:44
Hi @inty can you check if the server is opening a new connection on every LDAP authentication? How many users have authenticated on this 4 days, around 74?

@rodrigok can we check ou our code if we are opening a new connection on every auth?

**Comment by inty** [comment] 2016-08-11 14:52
It doesn't seem to be doing that. Tested it again now I observe the same behaviour (e.g. the same amount of open connections before and after login).

It has however grown from 74 to 80 since I reported this bug :)

**Comment by engelgabriel** [comment] 2016-08-11 14:56
@rodrigok can we add a log for overtime we open a LDAP connection?

**Comment by inty** [comment] 2016-08-11 14:57
Hmm, I'm getting this in the logs

```
I20160811-14:55:22.268(0) ldap.js:316 LDAP ➔ Search.error { [AssertionError: 0 == true]   name: 'AssertionError',   actual: 0,   expected: true,   operator: '==',   message: '0 == true' } 
I20160811-14:55:22.270(0) sync.js:179 LDAPSync ➔ error { [AssertionError: 0 == true] stack: [Getter] } 
```

If I test the LDAP connection in the admin it succeeds however "sync users" fails with an "Internal Server Error".

**Comment by inty** [comment] 2016-08-23 08:19
Any progress on this? Don't know if this helps but this the conntrack of the last 7 days of our rocket chat server. The dip you see is when I restarted when I upgraded to 0.37.1. The peaks are obviously weekdays and should mostly be HTTP connections.

![rocketchat](https://cloud.githubusercontent.com/assets/10284/17884671/ca9e8628-6919-11e6-90dd-d69228eaa6f2.png)

**Comment by FibreFoX** [comment] 2016-08-29 07:17
At the weekend our AD-server crashed due to OOM, I suspect LDAP-connections running wild, because the server terminated itself with OOM-messages due to "smbd"-threads hogging on the memory. Its a samba-system managed through [Zentyal](http://www.zentyal.com/), they are using Samba 4.

We are running on Rocket.Chat server 0.37.0 with LDAP configured.

Is it possible to make some logging of "opening" and "closing"? Instead of connection-counting via native tools it should be possible using the normal logfile provided by RC (this should be the fastest way to find it out).

**Closed** 2017-10-03 00:31 UTC
Labels: subj:  Auth - LDAP, type: support
