### ISSUE TITLE
[Feature Request] Threading messages

### ISSUE THREAD

**Issue by punkr0ck** [RocketChat/Rocket.Chat#7041] opened 2017-05-21 09:11 UTC
In Slack this feature is called "[Start a thread". ](https://api.slack.com/docs/message-threading)It is a very useful feature and I hope to see it in RocketChat, too.

**Comment by madguy02** [comment] 2017-05-21 12:01
@rodrigok

**Comment by lucasvanhalst** [comment] 2017-05-21 18:56
See #1112

**Comment by MartinSchoeler** [comment] 2017-05-22 12:18
This is a duplicate of #1112

**Closed by MartinSchoeler** 2017-05-22 12:18 UTC

**Comment by xereda** [comment] 2019-06-06 12:29
See https://rocket.chat/2019/05/13/rocket.chat-1-0/
:100:  :+1: :smile: :laughing:

**Comment by makhoff** [comment] 2019-07-10 06:10
Hello.

When I delete thread message, all other sub-messages are moved to top.
If the author of thread wants to delete his 1st message, there are too much messages will be appeared in the channel.
