### ISSUE TITLE
Oauth2 Login style "redirect" stopped working @ 6.4

### ISSUE THREAD

**Issue by dusatvoj** [RocketChat/Rocket.Chat#30956] opened 2023-11-14 15:06 UTC
### Description:
I did an upgrade from 6.3.x to 6.4.4 rocketchat. After upgrade I started facing issue that Login style redirect not working (nothing special in logs but I'm redirected back to login page) but popup style is working fine.

### Steps to reproduce:

1. Upgrade to RC 6.4.4
2. Setup custom oauth with login style redirect
3. Try to login

### Expected behavior:

Successful login

### Actual behavior:

Redirect back to login screen

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.4
- Operating System: Linux 
- Deployment Method: Tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.15

### Client Setup Information

- Desktop App or Browser Version: any (browser, app, ...)
- Operating System: any (linuxes, macos, ...)

### Relevant logs:
```
TypeError: userSettings.serverConfig is undefined
notificationBar.js:97:44
TypeError: userSettings.serverConfig is undefined
notificationBar.js:97:44
MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call MessageTypes.ts:20:11
strict mode: missing type "object" for keyword "additionalProperties" at "#" (strictTypes) /node_modules/ajv/dist/compile/util.js:1:3034
strict mode: missing type "object" for keyword "properties" at "#" (strictTypes) /node_modules/ajv/dist/compile/util.js:1:3034
strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes) /node_modules/ajv/dist/compile/util.js:1:3034
strict mode: "items" is 1-tuple, but minItems or maxItems/additionalItems are not specified or different at path "#/properties/matrixIds" /node_modules/ajv/dist/compile/util.js:1:3034
Object { stack: "r@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:1:4644\nn@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:92:18922\n_livedata_nosub@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:92:18994\nonMessage@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:92:21749\nt/_launchConnection/this.socket.onmessage/<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:2679\nforEachCallback@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:3735\nt/_launchConnection/this.socket.onmessage@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:2648\ne/</</<[5]</r.prototype.dispatchEvent@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:8437\ne/</</<[14]</</</_.prototype._transportMessage/<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:18870\ne/</</<[14]</</</_.prototype._transportMessage@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:18821\ne/</</<[3]</s.prototype.emit@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:7321\ne/</</<[38]</l/this.ws.onmessage@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:44885\nEventHandlerNonNull*l@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:44827\ne/</</<[14]</</</_.prototype._connect@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:18058\ne/</</<[14]</</</_.prototype._receiveInfo@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:17320\ni@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:7117\ne/</</<[3]</s.prototype.emit@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:7321\ne/</</<[12]</f.prototype.doXhr/<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:13278\ni@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:7117\ne/</</<[3]</s.prototype.emit@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:7321\ne/</</<[9]</a/<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:10837\ni@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:7117\ne/</</<[3]</s.prototype.emit@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:7321\ne/</</<[17]</</</l.prototype._start/this.xhr.onreadystatechange@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:26232\nEventHandlerNonNull*e/</</<[17]</</</l.prototype._start@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:25866\ne/</</<[17]</</</l/<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:25134\nsetTimeout handler*l@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:25110\ns@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:44304\na@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:10678\ne/</</<[12]</f._getReceiver@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:12903\ne/</</<[12]</f.prototype.doXhr@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:13094\ne/</</<[12]</f/<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:12830\nsetTimeout handler*f@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:12806\n_@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:16290\n_launchConnection@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:62:2417\ne/n.prototype.allowConnection@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:64:375\ne@/ee/client/ecdh.ts:1:241\nmodule@/ee/client/ecdh.ts:1:1178\nd/o.fetch/s/<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:52:864\ng@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:3:1500\nr@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:3:3596\nx@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:5:4709\nd/s.prototype.dynamicImport/b<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:52:583\nn.bindEnvironment/<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:1:8769\npromise callback*e/o.makeCompatible/e.prototype.then@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:48:1051\nd/s.prototype.dynamicImport@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:52:548\ne/<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:246:329879\nn.bindEnvironment/<@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:1:8769\npromise callback*e/o.makeCompatible/e.prototype.then@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:48:1051\ne@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:246:329868\ng@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:3:1500\nr@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:3:3596\nt@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:3:1131\n@https://im.domain.tld/c0263954182b6f4904b8af8fb7f8743884fa6bfe.js?meteor_js_resource=true:246:382060\n", isClientSafe: true, error: "not-allowed", reason: undefined, details: undefined, message: "[not-allowed]", errorType: "Meteor.Error" }
SDKClient.ts:86:13
```

**Comment by TimmiORG** [comment] 2023-11-16 19:39
@dusatvoj 
6.4.6 is fixing the issue. So you can close this ticket.

**Comment by pierre-lehnen-rc** [comment] 2023-12-05 21:18
The errors in the logs shared by @dusatvoj are caused by a script injected into rocekt.chat by the bitwarden browser extension.

**Closed by pierre-lehnen-rc** 2023-12-05 21:18 UTC
