### ISSUE TITLE
Jump to post from Search not working

### ISSUE THREAD

**Issue by rebeld** [RocketChat/Rocket.Chat#3026] opened 2016-04-25 14:17 UTC
Your Rocket.Chat version: 0.27.0 (and demo.rocket.chat)

In the search results, clicking on the gear does not invoke the context menu so it's impossible to jump to the specific post.

Occurs in desktop app and web. Mobile (iOS) has different issues (I'll file as a separate ticket).

**Comment by sampaiodiego** [comment] 2016-04-25 14:49
duplicate of #2945

**Closed by sampaiodiego** 2016-04-25 14:49 UTC
Labels: type: bug
