### ISSUE TITLE
Live Chat isn't showing on the website

### ISSUE THREAD

**Issue by pradsdev** [RocketChat/Rocket.Chat#10907] opened 2018-05-28 13:56 UTC
### Description:

Rocket.Chat window isn't showing up.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.0
* Operating System: Mac OS X High Sierra
* Deployment Method(snap/docker/tar/etc): Docker version 18.03.1-ce, build 9ee9f40
* Number of Running Instances: 4
* DB Replicaset Oplog: Present
* Node Version: v10.2.1
* mongoDB Version: 3.2

### Steps to Reproduce:

1. Installed Rocket.Chat through docker-compose using https://rocket.chat/docs/installation/docker-containers/docker-compose/.
2. Enabled livechat option(followed official documentation)
3. Copied and pasted the widget snippet on to my website

### Expected behavior:
Rocket.Chat livechat window

### Actual behavior:
Rocket.Chat livechat window is not showing up
### Relevant logs:
console log: 
(livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:63)
Uncaught TypeError: r._launchConnection is not a function
    at new e (livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:63)
    at new t (livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65)
    at Object.c.connect (livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65)
    at client_convenience.js (livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65)
    at k (livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:7)
    at e (livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:7)
    at client.js (livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65)
    at k (livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:7)
    at e (livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:7)
    at livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65
e @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:63
t @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65
c.connect @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65
client_convenience.js @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65
k @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:7
e @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:7
client.js @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65
k @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:7
e @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:7
(anonymous) @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65
(anonymous) @ livechat.js?_dc=a21eea6acefc5ed6836549f02e278df65ac1416c:65

**Comment by carloshperes** [comment] 2018-05-28 16:19
I'm having the same problem...

**Comment by carloshperes** [comment] 2018-05-28 23:04
Hi everybody,

For me the way was to follow the steps of this link https://hub.docker.com/_/rocket.chat/

And now it works!
=D

**Comment by gnat42** [comment] 2018-05-29 04:07
@carloshperes what steps? What's the difference? That seems to just setup the docker instances. shouldn't docker-compose create a similar setup?

**Comment by pradsdev** [comment] 2018-05-29 08:00
@RocketChatApp Please update the docker-compose file and the official documentation.

@gnat42 docker-compose example code uses mongo 3.2. And the following link setup uses mongo 3.0.  https://hub.docker.com/_/rocket.chat/

@carloshperes please share us the docker-compose.yml if you've.

**Comment by cmonjeau** [comment] 2018-05-29 09:55
Hi,

I have exactly the same problem since my upgrade to version 0.65.0.

**Comment by rmundel** [comment] 2018-05-29 12:22
Same problem here after snap automagically updated from 0.64 to 0.65.

**Comment by gnat42** [comment] 2018-05-29 14:56
I can confirm that specifying 0.64.2 for the rocket chat docker image version and the live chat js integration works.

**Comment by stevenhfotofix** [comment] 2018-05-29 16:39
Same issue, upgrade from 0.64.1 to 0.65.0 now kills the live chat - CentOS Linux release 7.2.1511, Ansible deployment.

**Comment by sampaiodiego** [comment] 2018-05-29 18:59
guys, we're aware of the issue and we expect to have a fix for 0.65.1 which will be released today.

**Comment by rmundel** [comment] 2018-05-29 19:01
Sweet!

**Closed** 2018-05-30 00:13 UTC
