### ISSUE TITLE
When I create a channel and open private operation，then I close the channel's private operation，but another people can't join the channel！

### ISSUE THREAD

**Issue by rockjins** [RocketChat/Rocket.Chat#6548] opened 2017-03-31 11:32 UTC
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version:v4.7.3

1. create a new channel,and choose the privatte operation:

![image](https://cloud.githubusercontent.com/assets/17586155/24548291/075365e0-1647-11e7-928a-9af1bb0dac33.png)

2. close the private

![image](https://cloud.githubusercontent.com/assets/17586155/24548320/24397d70-1647-11e7-9f65-42834887327e.png)

3. another people can't join the channel
![image](https://upload-images.jianshu.io/upload_images/2859850-4038fea4079ab024.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

I don't know why, I Looking for the bug all day, but I can't fix it, please.

**Comment by MartinSchoeler** [comment] 2017-03-31 12:22
Duplicate of #6533

**Closed by MartinSchoeler** 2017-03-31 12:22 UTC
