### ISSUE TITLE
"User is typing" indicator in the wrong place

### ISSUE THREAD

**Issue by vinniefalco** [RocketChat/Rocket.Chat#26027] opened 2022-06-27 17:03 UTC
In Dark Mode, when a user is typing, the indicator appears over the Message edit box:
![image](https://user-images.githubusercontent.com/1503976/175996150-ca286485-380b-44b1-b18f-d5ac187b1bf1.png)

**Comment by sdarwin** [comment] 2022-06-27 17:24
@vinniefalco in the standard rocket interface there's a lot of whitespace above the message edit box.  On our chat instance we have been customizing the layout. One of the changes was to reduce that space for aesthetic reasons.   And it appears to be triggering the bug.  Not a rocket issue. Will mention to our devs.

**Comment by Adarsh9306** [comment] 2023-04-02 16:57
Hello @vinniefalco is the issue still open? I want to work on this issue please assign it to me. issue #26027

**Comment by hugocostadev** [comment] 2023-04-06 19:09
Hi there, this is probably caused by a custom CSS/JS added to your instance, I'll close the issue for now, if you have any other considerations about the issue, please, reopen it

**Closed by hugocostadev** 2023-04-06 19:10 UTC
