### ISSUE TITLE
Up Arrow edit only works until someone replies

### ISSUE THREAD

**Issue by jdavis7718** [RocketChat/Rocket.Chat#14757] opened 2019-06-06 18:56 UTC
### Description:

Up Arrow to edit is not functioning as it was in previous releases

### Steps to reproduce:

1. Send a message
2. click up arrow to edit previous message
3. send message and then get a reply 
4. hit up arrow, can't edit any previous message.
5.  To edit you have to click the individual edit button by your message

### Expected behavior:

That always clicking the up arrow lets you scroll through previous X messages to edit them, even after someone replies

### Actual behavior:

After someone replies, you can no longer use the up arrow to edit

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: CentOS Linux release 7.6.1810 (Core) 
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.12

**Comment by reetp** [comment] 2019-06-07 10:48
@rocket-cat label add duplicate

Please always search for duplicates before opening a new Issue eg

https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+arrow

#14239 
#14240

**Comment by reetp** [comment] 2019-06-07 10:54
I think 14688 is the the duplicate of this but possibly is affected by 14369

If this is a duplicate of that then please close this in favour of the original and follow up there (you can +1 to say 'me too')

**Comment by zdumitru** [comment] 2019-06-07 11:01
For the reference - possible duplicate of #14369

**Comment by MartinSchoeler** [comment] 2019-07-11 19:11
As @reetp said, this is a duplicate, closing this issue.

**Closed by MartinSchoeler** 2019-07-11 19:11 UTC
Labels: duplicate
