### ISSUE TITLE
Add option to limit account name length

### ISSUE THREAD

**Issue by pfunks** [RocketChat/Rocket.Chat#7729] opened 2017-08-12 21:53 UTC
### Description:

The Accounts/Registration subpanel could use a setting to limit account name lengths. As it is, people can register disruptively long names by default. These names can be changed but it would be ideal if they could not be made in the first place.

**Comment by aditya19496** [comment] 2017-08-13 15:52
I will work on it.

**Comment by MartinSchoeler** [comment] 2017-08-14 12:35
Duplicate of #3192

**Closed by MartinSchoeler** 2017-08-14 12:35 UTC
