### ISSUE TITLE
[4.3.2 - 4.6.0] Writing indicator mixes English and German

### ISSUE THREAD

**Issue by Weuxel** [RocketChat/Rocket.Chat#25045] opened 2022-04-04 10:20 UTC
### Description:

Writing indicator mixes English and German. Sometimes the usernames are missing.

### Steps to reproduce:

1. Type something.
2. Watch the writing indicator.

### Expected behavior:

Output:
"A user" schreibt...
"Several users" schreiben...

### Actual behavior:

Output:
"User" is schreibt...
"Several users" are schreibt...

<img width="257" alt="Writing_Bug" src="https://user-images.githubusercontent.com/1791989/161524056-351aafc5-57e5-4a8a-bdf9-7095c28b4326.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.2 - 4.6.0
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: 12.18.4 and 14.19.1
- MongoDB Version: 4.0.27 and 4.4.13

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: Linux and Mac

**Comment by dudanogueira** [comment] 2022-04-04 12:48
Related: https://github.com/RocketChat/Rocket.Chat/issues/23593

**Comment by chotaire** [comment] 2022-09-07 16:59
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/23593

**Closed** 2022-11-22 15:20 UTC
