### ISSUE TITLE
Log failed login attempts

### ISSUE THREAD

**Issue by coders-kitchen** [RocketChat/Rocket.Chat#13479] opened 2019-02-14 08:31 UTC
In order to be able to use fail2ban or similar tools we need the option to see failed login attempts in the logs.

This is related at least to #2885 and #2737

**Comment by reetp** [comment] 2019-02-14 09:40
@rocket-cat label add duplicate

Please follow up on existing Issues rather than opening a duplicate.

**Comment by reetp** [comment] 2019-02-14 09:40
@rocket-cat close
Closing as duplicate of 13387

**Closed by reetp** 2019-02-14 09:41 UTC
Labels: duplicate

**Comment by coders-kitchen** [comment] 2019-04-18 06:48
hi!

having this feature not available is a blocker for us using RocketChat in production. 

In theory we could make our own distro out of it and patch all the time when a new version is released. but we definitely would like to see this available in the shipped version.

From the issue linked we understood that the whole topic is a heated discussion which makes it hard to find a solution there. Our proposal would be to take this issue as a step into the direction of solving the linked one.

Is this fine for you?
