### ISSUE TITLE
Remove channel count

### ISSUE THREAD

**Issue by iegik** [RocketChat/Rocket.Chat#13219] opened 2019-01-22 10:42 UTC
## My Setup
- Operating System: macOS
- App Version: 2.14.7
- Installation type: dmg

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
![screenshot 2019-01-22 at 13 32 03](https://user-images.githubusercontent.com/175293/51529876-ba171980-1e4a-11e9-9e0f-c4fc92b16084.png)

### Current Behavior
Shows channel count

### Expected Behavior
Show unread message count for each channel

In Slack  behavior badges with numbers means unread messages
In Rocket.Chat badges with numbers are not useful at all. In small groups of channels - you can count channels by fingers but white text on highlight background looks like unread notification :(

**Comment by engelgabriel** [comment] 2019-04-06 07:32
I agree this is not useful anymore.

**Comment by sudipt1999** [comment] 2019-05-01 09:26
@engelgabriel  can I work on this, seems like I need to remove it from template.

**Comment by ggazzo** [comment] 2019-08-20 14:12
duplicate of #8616 :)

**Comment by ggazzo** [comment] 2019-10-17 21:57
closing to keep the track in only one issue 🔝 , thanks

**Closed by ggazzo** 2019-10-17 21:57 UTC
Labels: design
