### ISSUE TITLE
Unable to view avatars since 3.8.1 where rocket is on a different path than /

### ISSUE THREAD

**Issue by asarubbo** [RocketChat/Rocket.Chat#19636] opened 2020-11-20 12:24 UTC
### Description:

Unable to view avatars since 3.8.1 where rocket is on a different path than /

### Steps to reproduce:

1. Setup rocket.chat to be accessible to e.g. rocket.example.com/rocket 
2. Unable to view the avatar
3. The console shows 403

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.1
- Operating System: Gentoo
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 1
- NodeJS Version: 12.8.4
- MongoDB Version: 4.2

### Client Setup Information

- Desktop App or Browser Version: Chrome-87
- Operating System: Gentoo

### Relevant logs:

Chrome console:
GET https://rocket.mycompany.com/avatar/ago 403

It should be https://rocket.mycompany.com/rocket/avatar/ago

**Comment by bellegarde-c** [comment] 2020-11-25 08:17
Duplicated I guess: https://github.com/RocketChat/Rocket.Chat/issues/19542

**Comment by graywolf336** [comment] 2020-12-11 19:55
Closing as a duplicate of #19542. And I do not believe the sub directory installation is officially supported anymore. I could be wrong here though.

**Closed by graywolf336** 2020-12-11 19:55 UTC
Labels: feat: subdir
