### ISSUE TITLE
Quoted Message Should be deleted  too when if original message is being deleted 

### ISSUE THREAD

**Issue by Vishv07** [RocketChat/Rocket.Chat#21054] opened 2021-03-10 07:12 UTC
### Description:

Whenever you send any message and Quote it to reply in the context of that message and if you delete that original message then that quote message panel should be closed after the message is being deleted.

here are some Screenshots So You guys can have a 
clear idea

1)  ![RocketChatBug1](https://user-images.githubusercontent.com/37216460/110589266-2aed2d00-819c-11eb-9c8b-8ec8e578eb16.JPG)

2)When You delete the message
 
![RChatBug2](https://user-images.githubusercontent.com/37216460/110589314-3d676680-819c-11eb-9045-75f63bec6818.JPG)

3)Now Look the Quote message panel should be closed. hence if you type any message in the Type bar and send it. it doesn't work. Because the original message has been deleted.

![Rcbug3](https://user-images.githubusercontent.com/37216460/110589524-8e775a80-819c-11eb-9237-6e33927db4b7.JPG)

### Steps to reproduce:

1. Send a demo message
2. Then quote it and delete the original message.

### Expected behavior:

When You delete the original message. that quote should be deleted. You can Check **Discord** for this functionality.

### Actual behavior:

I have attached the screenshots.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Google chrome 89.0.4389.82
- Operating System: Windows 10

**Comment by ABHAYJAIN2601** [comment] 2021-03-11 13:21
Hey @Vishv07 I think it's not a bug but more of feature many platform don't delete them some do!

**Comment by Vishv07** [comment] 2021-03-11 15:31
Have you checked discord?

**Comment by ABHAYJAIN2601** [comment] 2021-03-12 07:50
Yeah i use discord if you see whatapps don't delete quote message

**Comment by Vishv07** [comment] 2021-03-12 09:59
But It also allows you to at least send the msg. But here that penal sticks and until and unless you won't close that you won't be able to send the message you'll have to close this. It's a tiny thing but I think it should be resolved.

**Comment by shrinish123** [comment] 2021-03-15 13:57
Hey @Vishv07  do you want that quoted message box should go off after the message is deleted ?

**Comment by Vishv07** [comment] 2021-03-19 05:53
Yes

**Comment by johncrisp** [comment] 2021-08-11 18:57
Actually this is effectively a duplicate of:

https://github.com/RocketChat/feature-requests/issues/464

Please follow up there.

It isn't actually a bug as nothing is broken. It just doesn't do what you might want.

It may have unintended consequences too.

**Closed by johncrisp** 2021-08-11 18:57 UTC
