### ISSUE TITLE
Screen Sharing  

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1378] opened 2015-11-11 15:59 UTC
Ability to have Screen sharing and option to be (private or public) :) not sure if this is even possible to broadcast similar to gotomeeting or google hangout (youtube)

**Comment by graywolf336** [comment] 2015-11-11 18:33
Duplicate of #1349 it seems...

**Comment by engelgabriel** [comment] 2015-11-11 20:18
Implemented via https://github.com/RocketChat/Rocket.Chat/issues/933

**Closed by engelgabriel** 2015-11-11 20:18 UTC
