### ISSUE TITLE
The new Lazy load image attachments doesn't work

### ISSUE THREAD

**Issue by teamsoo** [RocketChat/Rocket.Chat#10895] opened 2018-05-28 03:33 UTC
### Description:

According to #10608, our instance of RC doesn't show the image when we point at it. Is there a way to disable this Lazy load feature?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.65.0
* Operating System: Ubuntu 16.04.1 LTS
* Deployment Method(snap/docker/tar/etc): docker (official rocketchat/rocket.chat)
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: n/a
* mongoDB Version: n/a

### Steps to Reproduce:

1. Upload image

### Expected behavior:

Point at the preview image to see the real image

### Actual behavior:

Nothing happened when pointing the preview image
<img width="495" alt="screen shot 2561-05-28 at 10 25 55" src="https://user-images.githubusercontent.com/9608690/40595990-4499490c-6262-11e8-9d7f-2c18f8f9e321.png">

### Relevant logs:
n/a

**Comment by teamsoo** [comment] 2018-05-28 05:29
@ggazzo Hi, thanks for the response. I'm seeing this error when scrolling pass the preview image. Not sure if it's related.

<img width="1440" alt="screen shot 2561-05-28 at 12 28 57" src="https://user-images.githubusercontent.com/9608690/40598588-c7604a74-6272-11e8-9601-8cdad3e99c93.png">

**Comment by teamsoo** [comment] 2018-05-28 05:32
yeah. I believe they're related.

`a=e.firstNode.getBoundingClientRect();if(a.top>=-100&&a.left>=0&&a.top<=(window.innerHeight||document.documentElement.clientHeight))return l(e)})};window.addEventListener("resize",window.lazyloadtick);`

**Comment by ppcat** [comment] 2018-05-28 06:46
got same error after upgrade to 0.65.0

**Comment by JSzaszvari** [comment] 2018-05-28 08:08
I saw this issue too. I did a bunch of testing and it seems to work fine up until the point that this PR is merged - https://github.com/RocketChat/Rocket.Chat/pull/10887

It seems to work OK, but then once you merge that particular PR in, the images will not fully load and stay blurry 

@ggazzo FYI

**Comment by JSzaszvari** [comment] 2018-05-28 08:08
@rocket-cat add label bug

**Comment by JSzaszvari** [comment] 2018-05-28 08:09
@rocket-cat label add bug

**Comment by JSzaszvari** [comment] 2018-05-28 08:09
@rocket-cat label add "type: bug"

**Comment by traxanos** [comment] 2018-05-28 10:10
i can confirm this

**Comment by ggazzo** [comment] 2018-05-28 11:50
sorry guys, nrr template I'm working to fix it

**Comment by IQ2022** [comment] 2018-05-28 22:26
I have same issue on my site..  please fix  - I can't even roll back to 64
![image](https://user-images.githubusercontent.com/12454319/40630881-a0dc6518-62a4-11e8-879d-0898fb8f422d.png)

**Comment by IQ2022** [comment] 2018-05-28 22:36
i have docker build  and the above still an issue

**Comment by earlng** [comment] 2018-05-29 09:15
Can confirm. I updated from 0.64.2 to 0.65.0, I'm also getting this issue.

**Comment by muhv7** [comment] 2018-05-29 09:59
Is there any way to put in the fix while being on snap without waiting for the next candidate release?

**Comment by vynmera** [comment] 2018-05-29 10:19
Editing Snaps is usually difficult. You can try these tips: https://askubuntu.com/questions/919091/why-snap-files-cannot-be-modified-in-any-way
Otherwise, you'll have to clone the fixed branch and import your data.

This should _really_ be a hotfix though. Not every team can afford having to switch to a local build...

**Comment by IQ2022** [comment] 2018-05-29 11:43
can we confirm on the ETA for next release please???

**Comment by alvarow** [comment] 2018-05-29 19:37
I also see this on 0.65.0 since I upgraded it last night.

**Comment by muhv7** [comment] 2018-05-29 19:57
I agree on the hotfix part. Can't roll back to 64.2 either, site wont come up with it.

**Closed** 2018-05-29 22:48 UTC
Labels: type: bug

**Comment by teamsoo** [comment] 2018-05-30 04:49
My workaround is adding this script to `Custom Script for Logged In Users` in `Layout`

```
setInterval(function() {
	document.querySelectorAll(".attachment-image .lazy-img").forEach(function(el) { 
    	el.src = el.dataset.src;
		el.removeAttribute('data-src');
		el.className = el.className.replace('lazy-img', '');
	})
}, 1000)
```

<img width="1243" alt="screen shot 2561-05-30 at 11 39 32" src="https://user-images.githubusercontent.com/9608690/40699395-30d3a154-63fe-11e8-99bf-3cd932149d85.png">
