### ISSUE TITLE
No E-Mail Notification for Channels

### ISSUE THREAD

**Issue by charlyrock** [RocketChat/Rocket.Chat#28113] opened 2023-02-22 06:36 UTC
### Description:

We have the problem that no email notifications are sent when messages are written in a channel. E-mail notifications are switched on under the profile settings and also for the channel . But if a new message has been written in the channel and you are currently offline, you will not receive an email notification. In contrast to direct chats, that works.

### Steps to reproduce:

1.  My Account > Settings > Notifications > Offline EMail Notification > Every Mention/DM
2.  Channel > Notification Preferences > Email > Alert: All messages
3.  A user write a message at the channel > no Email Notification

### Expected behavior:

To get a Email Notification, that a new message is in the channe. 

### Actual behavior:

 No E-Mail Notifications. Only for direct messages.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.0
- Operating System: Ubuntu 22.04
- Deployment Method: 
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.17

### Client Setup Information

- Desktop App or Browser Version: Browser and Desktop (3.8.16)
- Operating System: Windows 11

**Comment by dudanogueira** [comment] 2023-02-22 22:11
Hi! Thanks for reporting this issue.

I was not able to reproduce this on latest 6.0.0.rc-0:

![image](https://user-images.githubusercontent.com/1761174/220770908-67f7d740-3161-4543-8a16-37c02acd0702.png)

I noticed that the email will not be sent if the user email is not verified. Maybe that's your case?

Some improved steps for testing:
configure all that settings on a specific user, in my case, agent1. Notice that the notification configuration on a channel is user specific.

then, with another user, mention, send a direct. Also, you can try doing a @all in order to check if it's triggering the email too.

I will close this for now, and as will ask you to try reproducing this on latest 6.0.0 release candidate.

if that's the case, pelase, let me know so we can investigate it further.

Thanks!

Thanks!

**Closed by dudanogueira** 2023-02-22 22:11 UTC

**Comment by charlyrock** [comment] 2023-02-23 06:24
The mail is verified. And if we mentioned the user or write an direct message, then a email will send. 
But we want to get a mail, for any new message in a channel, also without mentioned the user.
