### ISSUE TITLE
[Bug at open.rocket.chat too]  Uncaught (in promise) undefined: registration form broken

### ISSUE THREAD

**Issue by sleeplessnight2** [RocketChat/Rocket.Chat#27670] opened 2022-12-30 11:42 UTC
### Description:

In the registration form there is no action/reaction after the button is pressed. Only in the browser console there is the feedback.
Likewise, the buttons are without function as soon as a channel is public and you want to log in or write anonymously.

Possibly the cause is in the message of the browser: Uncaught (in promise) undefined

### Steps to reproduce:

1. Just open https://open.rocket.chat/home 
2. Check Browser Console Log: You will find "Uncaught (in promise) undefined" 
3. Try Register with a really weak password. No Response after clicking the button.

### Expected behavior:

That all the functions that are supposed to be public worked that way. 

### Actual behavior:

Many functions do not work as long as you are not logged in.

Also the message Uncaught (in promise) undefined disappears as soon as logged in.

### Server Setup Information:

Knows only the Rocket.chat team.

I took your server as an example. (open.rocket.chat)

### Client Setup Information

Latest Firefox, Latest Chrome. Without any addons...

### Relevant logs:

Uncaught (in promise) undefined 5f520deb281655fa607e03b2b204933f90bafa80.js:1481:3274
    onStop https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1481
    _livedata_nosub https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1389
    onMessage https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1389
    onMessage self-hosted:1115
    onmessage https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1359
    forEach self-hosted:164
    forEachCallback https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1359
    onmessage https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1359
    (Async: EventHandlerNonNull)
    _launchConnection https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1359
    allowConnection https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1361
    s https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1606
    n https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1606
    g https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:3
    n https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:3
    a https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:5
    n https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1606
    g https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:3
    n https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:3
    t https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:3
    <anonym> https://open.rocket.chat/5f520deb281655fa607e03b2b204933f90bafa80.js?meteor_js_resource=true:1606

**Comment by dudanogueira** [comment] 2023-01-03 10:24
Hi! Thanks for pointing it out!

**Comment by dudanogueira** [comment] 2023-01-04 17:55
Also noticed that whenever the registration fails (for example, invalid email domain) it will not report back to the UI

**Comment by Aashray446** [comment] 2023-01-07 15:36
> Also noticed that whenever the registration fails (for example, invalid email domain) it will not report back to the UI

And even if the registration fails and doesn't show any feedback for failing if we try multiple times, the email somehow gets registered and we get a confirmation mail on our email id. Afterward, trying again shows email already exists feedback.

**Comment by Aashray446** [comment] 2023-01-08 09:57
I am looking forward to working on this bug, @dudanogueira  Can you assign it to me?

**Comment by Aashray446** [comment] 2023-01-10 09:40
> Also noticed that whenever the registration fails (for example, invalid email domain) it will not report back to the UI

@dudanogueira 
Hi, I went through the problem and found that by default the password policy is false, settings.watch() function is changing its value to false and thus the password is not being validated, it's a serious issue I guess, Can you show me the way to find the solution for it? The default setting is being fetched from the cached setting and I don't know from there what's happening.. :sweat_smile: 

Thanks!

**Comment by sleeplessnight2** [comment] 2023-01-10 13:23
Can someone with appropriate permissions on the open.rocket.chat server also confirm my guess about the buttons @public channel?
I can't try this out there myself....

When I call such a channel, I get this error message 5 more times in the browser console.

The buttons are completely without function. Nothing happens in the console, nor in the UI etc....
![2023-01-10_13-56-55](https://user-images.githubusercontent.com/8561601/211562898-57c3f98e-8cbe-498f-a8ad-b5f8410a4e58.jpg)

**Comment by Aashray446** [comment] 2023-01-19 13:12
> Also noticed that whenever the registration fails (for example, invalid email domain) it will not report back to the UI

@dudanogueira Can I create a new issue for this particular problem and start solving it, I already got a good understanding of the root cause of this issue. If I get a green signal I can start doing it. 
This is the issue that is there during the password change as well. 
:-)

**Comment by PavloKandyba** [comment] 2023-01-30 08:58
Hi @sleeplessnight2  Looks like the described issue is going to be resolved with the following PR ( it is merged already) 
https://github.com/RocketChat/Rocket.Chat/pull/27551

Regarding the registration form, did you mean that the issue is when you fulfilled all the information but for example specified the non-existing email provider or address so then once you click on the "Join your team" button, there is no visible reaction from the UI in order to let you know about your mistake right?

**Comment by Aashray446** [comment] 2023-01-30 14:13
Yeah and about the weak password as well , there is no feedback

**Comment by sleeplessnight2** [comment] 2023-01-31 13:13
@PavloKandyba The mentioned problem exists (at least for me) also in the latest release. In order to rule out a bug in my case, I would like to find out if it is the same in the official instance.

But the problem with the registration has nothing to do with a form check.
Even if I fill in all the information correctly, I don't get any feedback in the UI. Even a welcome email is sent - although nothing happened in the UI.

**Comment by meinrecht** [comment] 2023-02-01 12:52
We are currently setting up rocketchat (current docker-compose with 5.4.2) for some users that are mostly not too experienced internet users, so the problems described affect us considerably.

I can confirm, that the registration form does not provide any feedback after clicking "Join". The user has to know that an email will arrive to confirm the user email account.

Also, confirming @Aashray446: if the password does not match the policy the UI experience is exactly the same. 
But in this case no confirmation mail will arrive.  So there is actually no way to know what's happening for the user.

On the other hand, if the password and the confirmation password differ, I do get a hint concerning this.

Furthermore, if the username provided in the form is incorrect (for example, if it contains spaces) the confirmation mail is sent, but the user is asked to chose another one (a suggestion is made) after clicking on the confirmation link. However, this username is not used by rocketchat and the new user ends up having an empty username.
Why not check the correctness and availability of the username in the registration form directly?

**Comment by Aashray446** [comment] 2023-02-01 13:05
@meinrecht Yeah we can check the password policy at the frontend, not much in the way that the backend does, but we can avoid at least some issues with the way. But the issue with the policy matcher extends up to changing password action too, and it might affect more features. 
So I guess we need to fix the what I have mentioned above , I will solve both while registration and as well as updation of user details

**Comment by dudanogueira** [comment] 2023-02-22 22:16
Hi @sleeplessnight2 !!

I just tested and can confirm this was fixed in 6.0.0-rc.0 (right now on release candidate 0)

**Now** is the perfect time for testing, as we are on the release candidate phase. 

Every help is much appreciated :hugs: 
**Join us here**: https://open.rocket.chat/channel/beta-testers

**Comment by dudanogueira** [comment] 2023-02-22 22:18
By the way, this is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/27149

I'll close this issue, then :)

**Comment by sleeplessnight2** [comment] 2023-02-23 07:24
Sorry, but there is still no feedback from the registration form in the RC. Just tested.

The user is created, an email is sent - but the UI still does nothing. To the user it looks like nothing is happening.

**Comment by Aashray446** [comment] 2023-02-23 07:26
Yeah, I have confirmed that too... The feedback is not there ... The reason is because of Security policies

**Comment by sleeplessnight2** [comment] 2023-02-24 08:20
Hi @dudanogueira

Can you reopen this case?

Would be nice so that it does not go lost until it is solved.

**Comment by PavloKandyba** [comment] 2023-03-02 09:22
Hi, the fix for email validation is here:

https://github.com/RocketChat/Rocket.Chat/pull/28143

**Closed** 2023-05-24 06:53 UTC
Labels: type: bug, subj: ui/ux
