### ISSUE TITLE
rocket.chat UI Broken in iOS Safari browser

### ISSUE THREAD

**Issue by faziloub** [RocketChat/Rocket.Chat#9968] opened 2018-03-01 23:39 UTC
### Description:
rocket.chat doesn't load in ios 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62
* Operating System: ubuntu
* Deployment Method(snap/docker/tar/etc): 
* Number of Running Instances: 
* DB Replicaset Oplog: yes
* Node Version: 
* mongoDB Version: 

![9f6c791b-0603-43c4-959f-ef34c5b29775](https://user-images.githubusercontent.com/16228448/36875802-fe295826-1db1-11e8-806c-91633b76d972.jpg)

**Comment by alexey-boyko** [comment] 2018-03-02 06:23
Same stuff after upgrade to 0.62,  on  android  app  same

**Comment by lostdesign** [comment] 2018-03-02 08:42
Logs? I just updated yesterday and working fine for me on 0.62.0 same system.

**Comment by alexey-boyko** [comment] 2018-03-02 09:07
I don't have any useful logs on server and problem only on ios and some android devices

**Comment by fifou17** [comment] 2018-03-02 19:32
in android its works fine for me only in ios

**Comment by apmilen** [comment] 2018-03-07 11:05
I'm also experiencing this issue in iOS using both Chrome and Safari :(

![img_1875](https://user-images.githubusercontent.com/2745728/37089128-7607dc48-21f7-11e8-92b0-325e1876a310.PNG)

**Comment by lcharette** [comment] 2018-03-08 12:02
Similar issue using electron iOS app. Messages are not showing.

**Comment by chrisbennight** [comment] 2018-03-17 02:08
Clicking on another channel (which will also be blank) - then clucking back to the original channel restores text (for the original channel) iOS ipad and iphone, latest safari

**Comment by cybergrunge** [comment] 2018-04-16 15:09
> Clicking on another channel (which will also be blank) - then clicking back to the original channel restores text (for the original channel) on iOS ipad and iphone, latest safari

Same with Firefox beta for iOS.

**Comment by chrisbennight** [comment] 2018-05-18 01:15
Is there any additional info/logs/debug info I can provide to help here?  I still have the same symptoms on 0.63.3  (latest snap release).

**Comment by fifou17** [comment] 2018-05-19 19:38
any news about this bug ??

**Comment by ggazzo** [comment] 2018-06-26 20:03
@fifou17 do you know what is your version of iOS?

**Comment by MartinSchoeler** [comment] 2024-07-23 16:59
Closing this as I could not reproduce the issue anymore, feel free to open a new issue in case of this surfacing again, thanks!

**Closed by MartinSchoeler** 2024-07-23 16:59 UTC
Labels: ui/ux
