### ISSUE TITLE
Issues OAuth Rocket.chat and Jitsimeet

### ISSUE THREAD

**Issue by hallo43** [RocketChat/Rocket.Chat#34042] opened 2024-11-24 05:00 UTC
### Description:

I want to use Rocket.chat to logon Jitsimeet if user not login Jitsimeet before.

### Steps to reproduce:

1. Go to: http://localhost:3000/admin/settings/OAuth
2. Add custom OAuth
3. Named: "jitsimeet" and then setting for it as below:
```
URL: https://localhost:8443/oauth/callback
Token Path: /oauth/token
Id: demojitsi
Secret: EE3793E7797DCBF1A2D4AF2DD5889
others: keep default
```
4. setting .env of "docker-jitsi-meet" (i cloned from github of Rocket.chat):

 ```
ENABLE_AUTH=1
 ENABLE_GUESTS=0
 AUTH_TYPE=jwt
 JWT_AUTH_TYPE=token
 JWT_APP_ID=demojitsi
 JWT_APP_SECRET=EE3793E7797DCBF1A2D4AF2DD5889
 TOKEN_AUTH_URL=http://localhost:3000/_oauth/jitsimeet
```

5. Add settings to "prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua"
```
----START ADD
VirtualHost "auth.localhost"
    authentication = "oauth"
    oauth_provider_url = "http://localhost:3000/_oauth/jitsimeet"
    app_id = "demojitsi"
    app_secret = "EE3793E7797DCBF1A2D4AF2DD5889"
    allow_unencrypted = true

VirtualHost "localhost"
    authentication = "token"
    app_id = "demojitsi"
    app_secret = "EE3793E7797DCBF1A2D4AF2DD5889"
    allow_empty_token = false
    enable_domain_verification = false
    modules_enabled = {
        "bosh";
        "websocket";
        "smacks"; -- Stream management
        "speakerstats";
        "conference_duration";
        "muc_lobby_rooms"; -- Lobby support
    }
-------END ADD
```
6. docker compose up -d

### Expected behavior:

1. If use have been not login Jitsimeet yet, so will redirect to Rocket.chat to login. 
2. login Rocket.chat success then Redirect to Jitsimeet and join meeting room

### Actual behavior:
```
Not redirect to login screen of Rocket.chat and there is error log in Rocket.chat:
Exception in changedobserveChanges callback: Error: Could not find element with id -6742a6ab73b5c73d92fa2dfb to change     at SessionCollectionView.changed (packages/ddp-server/livedata_server.js:266:13)     
at Session.changed (packages/ddp-server/livedata_server.js:490:12)     
at Subscription.changed (packages/ddp-server/livedata_server.js:1416:19)     
at changed (packages/mongo/collection.js:576:17)     
at packages/meteor.js:1401:24     
at packages/meteor.js:765:17     
at AsyncLocalStorage.run (node:async_hooks:346:14)     
at Object.Meteor._runAsync (packages/meteor.js:762:14)     
at runWithEnvironment (packages/meteor.js:1394:21)     
at Object.changed (packages/meteor.js:1421:14)     
at server/services/meteor/service.ts:156:7     
at Set.forEach (<anonymous>)     
at EventEmitter.<anonymous> (server/services/meteor/service.ts:155:29)     
at EventEmitter.emit (node:events:519:28)     
at EventEmitter.emit (node:domain:488:12)     
at LocalBroker.broadcastLocal (/Users/john/Rocket.Chat/packages/core-services/src/LocalBroker.ts:96:15)     
at LocalBroker.broadcast (/Users/john/Rocket.Chat/packages/core-services/src/LocalBroker.ts:90:8)     
at Api.broadcast (/Users/john/Rocket.Chat/packages/core-services/src/lib/Api.ts:49:22)     
at app/lib/server/lib/notifyListener.ts:157:12     
at app/lib/server/lib/notifyListener.ts:174:8     
at processTicksAndRejections (node:internal/process/task_queues:95:5) 

W20241124-11:36:23.287(7) (oauth_server.js:70) Unable to base64 decode state from OAuth query: undefined

```
### Server Setup Information:

- Version of Rocket.Chat Server: 7.1.0
- License Type: Starter
- Number of Users: 10
- Operating System: MACOS
- Deployment Method: Rocket.chat run from source code(clone from github of Rocket.chat)
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v20.18.0
- MongoDB Version: 

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: MACOS

**Comment by reetp** [comment] 2024-11-24 12:15
This seems a support issue, not a bug.

I'm not sure you understand what Oauth in Rocket does?

It makes Rocket use authentication from another source.

If you try to logon to Jitsi and a user doesn't exist in Jitsi, then when you try to logon to Rocket with Custom Oauth Rocket just refers back to Jitsi for Auth, where the user doesn't exist.....

You have a nice loop.

Also note you should not be using localhost to access Rocket unless you are actually developing code for Rocket itself.

Set up your Rocket & Jitsi properly with a reverse proxy, https etc etc before attempting this.

Please follow up on your post on open.rocket.chat

https://open.rocket.chat/channel/support?msg=CQdDpSZ5tZ6YiCd6L

Closing for now. We can re-open if we actually find a bug.

**Closed** 2024-11-24 12:15 UTC
Labels: type: support
