### ISSUE TITLE
Input text at bottom of page

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#7824] opened 2017-08-21 19:19 UTC
Version of Rocket.Chat Server: 10499e02cef140bfc7a57e52b6b194489498f2f3

In Firefox, at the very bottom of the page, the text you input in the message field is shown.

![](https://i.imgur.com/LSjXp3a.png)

**Comment by Lemmmy** [comment] 2017-08-25 14:34
Bump - having the same issue

**Comment by zardyh** [comment] 2017-08-25 14:34
I'm having the same issue in Chrome 60.

**Comment by Nabile-Rahmani** [comment] 2017-08-25 18:20
Happens on Firefox Nightly 57.0a1, too.

Reproduction steps:
1. Click on the left pane.
2. Press `Page Down`/`End`.

**Comment by Lemmmy** [comment] 2017-08-25 18:27
Reproduction steps work if the pane isn't full. If the pane is showing a scrollbar, then the issue doesn't happen.

**Comment by Lemmmy** [comment] 2017-08-25 18:30
The element that shows the duplicate message is .autogrow-shadow. However, upon setting it to `display: none`, theres still ~4 pixels of white gap below the page.

**Comment by ggazzo** [comment] 2018-05-25 04:14
i'm closing because its nice now ;)

**Closed by ggazzo** 2018-05-25 04:14 UTC
