### ISSUE TITLE
Customize rocketcat

### ISSUE THREAD

**Issue by glebPo** [RocketChat/Rocket.Chat#14440] opened 2019-05-09 18:14 UTC
Hello! Can you help me? I add custom button to tab bar actions. And now i want update rocketchat to new release. How can i do this without loosing my custom button?

**Comment by wreiske** [comment] 2019-05-10 00:05
Probably a better question for https://open.rocket.chat/channel/dev or https://forums.rocket.chat/ 

Essentially, You'll want to `git pull`, fix any merge conflicts, and rebuild your Rocket.Chat.

**Comment by krakozzabr** [comment] 2019-05-10 07:05
Thanks!

**Comment by reetp** [comment] 2019-05-10 08:01
@rocket-cat close

Closing notabug.

This is a a support issue not a bug.

**Closed** 2019-05-10 08:01 UTC
