### ISSUE TITLE
Archive + Freeze Channel

### ISSUE THREAD

**Issue by Megatronic79** [RocketChat/Rocket.Chat#752] opened 2015-09-10 12:38 UTC
Can we add the ability to archive and freeze a channel - for QA and Legal compliance reasons?

**Comment by Sing-Li** [comment] 2015-09-10 13:44
:+1:   @Megatronic79  really knows what business users need !  :smile:

**Comment by geekgonecrazy** [comment] 2015-09-10 17:08
@Megatronic79 we've got the base methods in place.  We'll get the rest of the logic built out and get this in place :)

**Comment by Megatronic79** [comment] 2015-09-10 17:09
good work guys!

**Comment by Theaxiom** [comment] 2015-10-12 21:28
#722 should be merged maybe?

**Comment by graywolf336** [comment] 2016-01-21 20:39
Duplicate of #722.

**Closed by graywolf336** 2016-01-21 20:39 UTC
Labels: feat: channel settings, type: new feature
