### ISSUE TITLE
Rocketchat version 6.2.2 user adding error

### ISSUE THREAD

**Issue by mertomert** [RocketChat/Rocket.Chat#29399] opened 2023-05-30 08:59 UTC
I can't add user after Rocketchat version upgrade. I get the error "usersInRole.toArray(...).forEach is not a function" while adding it.

**Comment by hugocostadev** [comment] 2023-05-30 11:38
Hi there, thanks for raising the issue! 🚀 💯 

I could not reproduce it, can you share more details? Try to follow the Issue template, please

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Comment by hugocostadev** [comment] 2023-05-30 11:44
closing due to duplicate of https://github.com/RocketChat/Rocket.Chat/issues/29387

**Closed by hugocostadev** 2023-05-30 11:44 UTC
Labels: stat: need more info, stat: can't reproduce

**Comment by hugocostadev** [comment] 2023-05-30 11:54
FYI fixed in this PR: https://github.com/RocketChat/Rocket.Chat/pull/29293
