### ISSUE TITLE
Ability to delete multiple messages at once

### ISSUE THREAD

**Issue by thomasphilibert** [RocketChat/Rocket.Chat#1861] opened 2016-01-12 08:02 UTC
Hi all,

I suggest to add a button for clean all (or partial?) messages in group : There is not necessarily need to archive some discussions

Thomas

**Comment by geekgonecrazy** [comment] 2016-01-12 17:55
@thomasphilibert so this would purge messages from the channel / group?

**Comment by thomasphilibert** [comment] 2016-01-13 07:30
Yes exactly ! For exemple, on my rocketchat we have a group called "cool stuff". I thinks is not important to store these messages indefinitely.

Thomas

**Comment by graywolf336** [comment] 2016-01-21 20:46
@thomasphilibert So, it actually removes the messages from the database or just removes them from being visible?

**Comment by marceloschmidt** [comment] 2016-02-04 19:31
Deleting multiple messages at once could be useful. Maybe we can use the same UI for sending messages to an e-mail:

![selectmessages](https://cloud.githubusercontent.com/assets/1986378/12827063/1cef214c-cb65-11e5-97af-dad686f65226.gif)

**Comment by geekgonecrazy** [comment] 2016-02-04 19:40
:+1: this could be very useful

**Comment by Sing-Li** [comment] 2016-02-04 19:57
OH.  Please make sure the _selection mechanism_ is mobile friendly.   There are a lot of problems associated with mapping shfit-click-drag style of select to a mobile touch interface.

**Comment by thomasphilibert** [comment] 2016-02-04 23:11
Nice feature Marcelo !

@graywolf336 Deleting from the database. A bit like the trash in your PC. If you want free space for one reason or another, it's a simple solution. We do not always need to store messages, no? 

Thomas

**Comment by graywolf336** [comment] 2016-02-04 23:19
Unless you need to comply with some compliance out there. So, it should be a setting for the admins.

**Comment by benmcnelly** [comment] 2016-02-23 18:33
I am pinging this, because I think we really need to be able to just do a one button "clean" that dumps a channel.

**Comment by andreas-bulling** [comment] 2016-03-22 13:46
I think what we actually want/need is, in general, a mechanism to easily select multiple messages for subsequently deleting, moving, sending them etc. Maybe using some checkbox-like interface that only shows when the user clicks on a corresponding button somewhere. Or, even better, just by clicking on the message itself. At the moment, the message the mouse is hovering over is only highlighted. Could instead be used for selection if the user also clicks on individual messages.

**Comment by RichardFoxworthy** [comment] 2016-04-09 00:26
When I delete a Channel, then recreate a new channel with same name, all the old messages reappear in the new chanel

**Comment by graywolf336** [comment] 2016-04-11 04:12
@RichardFoxworthy That's a whole other issue and not really related to this issue, mind creating a new one if there isn't another out there for that? Thanks!

**Comment by nemolivier** [comment] 2016-05-24 15:47
More on this would be the hability to delete all messages of one user (think about troll). I may be wrong but I remember that kicking a member don't delete his messages.

**Comment by 78c59635bdd8** [comment] 2016-07-06 19:57
Are there drawbacks to truncating the rocketchat_message collection in the database?  For an admin who didn't want a record of any messages (group or direct) stored for long in the database, would this work as a crude solution to this issue?  Would this break other parts of the database and/or Rocket Chat?

**Comment by harrv** [comment] 2017-06-07 15:48
I see that there is already a great UI mechanism for selecting multiple messages in the Mail Messages feature. Please use the same UI mechanism to allow us to select multiple messages for deletion.

**Comment by jvacek** [comment] 2018-04-03 14:46
@MartinSchoeler this ticket as well as #6000 have been marked as duplicate of each other and both closed, has this been resolved elsewhere?

**Comment by marceloschmidt** [comment] 2018-04-19 14:44
We discussed it and think it would be good to have a button that would nuke all room messages, instead of selecting which ones would be deleted.

**Comment by c0dzilla** [comment] 2018-04-19 16:52
There is a method for this called `cleanChannelHistory` ([here](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/methods/cleanChannelHistory.js)) that can delete all messages in a room. It can be accessed at the API route `channels.cleanHistory`. A UI option can be also be added that uses this.

**Comment by prohde** [comment] 2018-04-21 08:30
I think there is also a need to delete multiple messages in a channel but not all. On my Rocket.Chat instance we have some channels where we discuss things. Some of the messages are important and we want to keep them but several messages could be deleted after some time.

**Closed** 2018-07-20 04:26 UTC
Labels: Feature: Planned, feat: message

**Comment by nopynoop** [comment] 2020-04-03 09:39
Deleting messages 1 by 1 can be very time-consuming. Hopefully, this gets done in 2020.
