### ISSUE TITLE
Login API response format

### ISSUE THREAD

**Issue by dmeziere** [RocketChat/Rocket.Chat#6779] opened 2017-04-24 15:57 UTC
Rocket.Chat Version: 0.55.0-develop
Running Instances: 1
DB Replicaset OpLog: active
Node Version: v4.7.3

When login is successfull via the API, the resulting json feed contains a success attribute:
{status: 'success'}

But when an error message is returned, the answer's structure changes :
{body: {status: 'error'}}

Preventing to handle properly the status attribute

NB: This doesn't happen on a bad password error, the password parameter did contain invalid data. This lowers the criticity of the bug, but not the bug itself I guess.

**Comment by graywolf336** [comment] 2017-04-24 16:47
Kind of a duplicate of this comment: https://github.com/RocketChat/Rocket.Chat/issues/5316#issuecomment-269027879 however this error is because we are using a tool developed by someone else for the rest api backend piece, so it is tough to change.

**Comment by MarcosSpessatto** [comment] 2018-09-18 18:17
@dmeziere I think this issue was solved, please upgrade your server, and if the problem persists, feel free to reopen this. Thanks.

**Closed by MarcosSpessatto** 2018-09-18 18:17 UTC
Labels: feat: api, stat: waiting response, type: improvement
