### ISSUE TITLE
Gitlab API URL is not used

### ISSUE THREAD

**Issue by kakawait** [RocketChat/Rocket.Chat#861] opened 2015-09-23 09:14 UTC
Using last commit 1875e331422be22f71dd461e1f8b060f363df829 when setting `API_Gitlab_URL` (I checked on mongo setting is persisted) Gitlab authentication still redirect on https://gitlab.com.

I need to edit https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-gitlab/common.coffee#L2 in order to work

**Comment by Sing-Li** [comment] 2015-09-23 09:42
@kakawait 

You do not need to edit the code.

As administrator.    Change it from the GUI **Administration -> Accounts -> GITLAB**  and then **SAVE CHANGES** ; and you're done.

**Comment by kakawait** [comment] 2015-09-23 09:56
@Sing-Li Yeah *Accounts* section is to set Oauth2 credentials, that is Ok but my problem (on my env) is *API* section with `API_Gitlab_URL`.

When setting my own gitlab url aka http://my.local.host/gitlab and save. When I try to login with Gitlab popup is redirected to gitlab.com and not mine

**Comment by kakawait** [comment] 2015-09-23 10:05
Configuration
![screen shot 2015-09-23 at 12 01 01](https://cloud.githubusercontent.com/assets/275609/10042404/fb0047ca-61ea-11e5-9015-fd8a9bea7168.png)

![screen shot 2015-09-23 at 12 01 59](https://cloud.githubusercontent.com/assets/275609/10042414/0dd646ce-61eb-11e5-9e45-bae99318d9a2.png)

Inside mongodb

```
> db.rocketchat_settings.find()
{ "_id" : "API_Gitlab_URL", "value" : "http://anakin/gitlab/", "i18nLabel" : "rocketchat-gitlab:API_Gitlab_URL", "i18nDescription" : null, "type" : "string", "group" : "API", "public" : true }
```

result

![screen shot 2015-09-23 at 12 01 23](https://cloud.githubusercontent.com/assets/275609/10042449/55392018-61eb-11e5-8074-525471b068bd.png)

**Comment by Sing-Li** [comment] 2015-09-23 11:00
cool !  :smile:    Thanks for the detailed extended information!

I've just confirmed the bug on a brand new install.  Hopefully @marceloschmidt  will see this in the morning.

**Comment by marceloschmidt** [comment] 2015-09-23 13:33
It's not that this is a bug. I think we should make this clearer:

The `API_Gitlab_URL` setting doesn't do anything if you don't have a custom oauth setting.

In Administration / Accounts, the GitLab section will always point to `gitlab.com`. 

If you want to enable logging in with your custom gitlab server, you must add a Custom OAuth with the following settings:

`Authorize Path: /oauth/authorize (default)`
**`Identity Path: /api/v3/user`**
`Token Path: /oauth/token (default)`

Don't forget to add your rocket.chat instance application in your gitlab server. The Callback URL must be `http(s)://[your_rocket_chat_server]/_oauth/[your_custom_oauth_id]`.

**IMPORTANT**
When adding your custom oauth, you'll need to first insert an ID for this oauth. We have to work on that dialog, but while we don't, just so you know, the ID must be all lowercase without any spaces.

**Comment by rodrigok** [comment] 2015-09-23 13:47
It's a bug @marceloschmidt, I fixed now

You can use the GitLab oAuth setting the API url to point to your server

**Comment by kakawait** [comment] 2015-09-23 13:48
but callback url should be `http(s)://[your_rocket_chat_server]/_oauth/[your_custom_oauth_id]` or `http(s)://[your_rocket_chat_server]/_oauth/gitlab`?

Actually I'm using second.

**Comment by rodrigok** [comment] 2015-09-23 13:52
@kakawait if you setup the gitlab oauth using the section *GitLab* you should use `http(s)://[your_rocket_chat_server]/_oauth/gitlab`, if you setup the oauth via a new Custom oAuth, you need to use the name you give to the custom o auth at the end of the url `http(s)://[your_rocket_chat_server]/_oauth/[your_custom_oauth_id]`

**Comment by kakawait** [comment] 2015-09-24 11:56
@rodrigogs I just pull lasted version and yes the popup now redirect to my custom Gitlab. However I got an error and inside log I saw something like

```
W20150924-11:54:52.487(0) (oauth_server.js:398) Error in OAuth Server: Failed to complete OAuth handshake with gitlab at https://gitlab.com/oauth/token. failed [401] {"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}
I20150924-11:54:52.636(0)? Exception while invoking method 'login' Error: Failed to complete OAuth handshake with gitlab at https://gitlab.com/oauth/token. failed [401] {"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}
I20150924-11:54:52.637(0)?     at CustomOAuth.getAccessToken (packages/rocketchat:custom-oauth/custom_oauth_server.coffee:70:16)
I20150924-11:54:52.637(0)?     at Object.handleOauthRequest (packages/rocketchat:custom-oauth/custom_oauth_server.coffee:95:23)
I20150924-11:54:52.637(0)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)
I20150924-11:54:52.637(0)?     at middleware (packages/oauth/oauth_server.js:173:1)
I20150924-11:54:52.637(0)?     at packages/oauth/oauth_server.js:146:1
```

Some trace of https://gitlab.com/oauth/token? May just log error ?

**Comment by kakawait** [comment] 2015-09-24 12:33
If it can help I add log on server `console.log options` just before https://github.com/RocketChat/Rocket.Chat/blob/master/packages/rocketchat-custom-oauth/custom_oauth_client.coffee#L18

```
I20150924-12:18:39.365(0)? { serverURL: 'https://gitlab.com',
I20150924-12:18:39.366(0)?   identityPath: '/api/v3/user',
I20150924-12:18:39.366(0)?   addAutopublishFields: 
I20150924-12:18:39.366(0)?    { forLoggedInUser: [ 'services.gitlab' ],
I20150924-12:18:39.366(0)?      forOtherUsers: [ 'services.gitlab.username' ] } }

I20150924-12:18:39.370(0)? { serverURL: '',
I20150924-12:18:39.370(0)?   identityPath: '/oauth/me',
I20150924-12:18:39.370(0)?   addAutopublishFields: 
I20150924-12:18:39.370(0)?    { forLoggedInUser: [ 'services.wordpress' ],
I20150924-12:18:39.370(0)?      forOtherUsers: [ 'services.wordpress.user_login' ] } }

I20150924-12:18:39.971(0)? { serverURL: 'http://anakin.ux.dsone.3ds.com/gitlab/',
I20150924-12:18:39.971(0)?   identityPath: 'https://gitlab.com/api/v3/user',
I20150924-12:18:39.971(0)?   addAutopublishFields: 
I20150924-12:18:39.971(0)?    { forLoggedInUser: [ 'services.gitlab' ],
I20150924-12:18:39.971(0)?      forOtherUsers: [ 'services.gitlab.username' ] },
I20150924-12:18:39.971(0)?   tokenPath: 'https://gitlab.com/oauth/token' }
```

**Comment by marceloschmidt** [comment] 2015-09-24 12:34
Did you restart your server after that? I had a similar issue with github integration, and it worked after a restart.

**Comment by kakawait** [comment] 2015-09-24 12:39
@marceloschmidt rocketchat server or gitlab?

**Comment by kakawait** [comment] 2015-09-24 12:45
@marceloschmidt 

```
docker rm -f rocketchat-db
docker rm -f rocketchat
docker run --name rocketchat-db -p 27018:27017 -d mongo
docker run -d --name rocketchat -p 3000:3000 -v "$(pwd)":/app --net host -e "MONGO_URL=mongodb://localhost:27018" -e "ROOT_URL=http://some.url.here:3000" -e "MAIL_URL=smtp://smtp.paris.exalead.com" danieldent/meteor
```

Same problem with 100% fresh installation

**Comment by marceloschmidt** [comment] 2015-09-24 12:47
After changing your gitlab api url in administration/settings, restart your rocket.chat server, so it can read the settings again. We'll fix that on #849.

**Comment by kakawait** [comment] 2015-09-24 12:49
@marceloschmidt Thank, I'm stupid because I was author of #849.. Forget that :)

**Comment by kakawait** [comment] 2015-09-24 12:57
@marceloschmidt even after restarting server 

```
docker restart rocketchat
```

or 

```
docker rm -f rocketchat
docker run -d ...
```

error persists

**Comment by marceloschmidt** [comment] 2015-09-24 12:58
Sorry then! I thought it could be related to what I'm having with wordpress... If I find a fix for WP, I'll let you know, so you can re-test...

**Comment by kakawait** [comment] 2015-09-24 15:17
@rodrigok if you are ok to reopen issue?

**Comment by marceloschmidt** [comment] 2015-09-24 15:19
@kakawait do you have access to the main repo? can you pull my changes from a minute ago and give it another try?

**Comment by clenemt** [comment] 2015-09-24 15:45
very nice @kakawait :+1:

**Comment by marceloschmidt** [comment] 2015-09-24 17:58
@kakawait can you please test again? Thanks

**Comment by kakawait** [comment] 2015-09-25 07:43
Using last commit 51c242c7b21d5186aa35ecb9cafab72c14501574 it works except from fresh install. I must restart server else I have this error

```
W20150925-07:37:05.845(0) (oauth_server.js:398) Error in OAuth Server: Failed to complete OAuth handshake with gitlab at /oauth/token. url must be absolute and start with http:// or https://
I20150925-07:37:05.987(0)? Exception while invoking method 'login' Error: Failed to complete OAuth handshake with gitlab at /oauth/token. url must be absolute and start with http:// or https://
I20150925-07:37:05.987(0)?     at CustomOAuth.getAccessToken (packages/rocketchat:custom-oauth/custom_oauth_server.coffee:69:16)
I20150925-07:37:05.988(0)?     at Object.handleOauthRequest (packages/rocketchat:custom-oauth/custom_oauth_server.coffee:94:23)
I20150925-07:37:05.988(0)?     at OAuth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:8:1)
I20150925-07:37:05.988(0)?     at middleware (packages/oauth/oauth_server.js:173:1)
I20150925-07:37:05.988(0)?     at packages/oauth/oauth_server.js:146:1
```

**Comment by rodrigok** [comment] 2015-09-25 14:23
@kakawait is it working now?

**Comment by kakawait** [comment] 2015-09-25 15:56
using 20e768c03a5340fcc29cac8ca68e9e7dd7ef4502 same error as https://github.com/RocketChat/Rocket.Chat/issues/861#issuecomment-143150905 using fresh install (aka empty db)

```
docker rm -f rocketchat-db
docker rm -f rocketchat
docker run -d --name rocketchat-db ...
docker run -d --name rocketchat ...
```

**Comment by pavankumarkatakam** [comment] 2015-11-18 15:10
Same issue for me, using custom gitlab server but getting the "Internal server error
"

**Comment by goocastro** [comment] 2015-11-26 21:23
It's happening here with me too, I believe it's something related to the port. I'm running Rocket in port 80 but it stills build the redirect URI with :3000 port

**Comment by dalenoe** [comment] 2015-11-30 18:47
I subscribed. I am dealing with something similar...

**Comment by marceloschmidt** [comment] 2015-12-14 16:09
I've made a few more tests and it seems to be working now. Please, whoever was having problem with it, can you test again? Thanks.

**Closed by marceloschmidt** 2015-12-14 16:09 UTC
Labels: feat: docker, type: bug

**Comment by jmatsushita** [comment] 2016-02-21 14:13
Using 0.18.1 I encountered the exact same error message than [this comment](https://github.com/RocketChat/Rocket.Chat/issues/861#issuecomment-143150905) and restarting the server also solved it.

**Comment by 0r** [comment] 2016-05-11 02:24
Any tips for getting oauth working where Rocket.Chat and Gitlab are installed on the same server with Gitlab installed in the root url and Rocket.Chat in url/chat ?

I have set chat/oauth/token and chat/oauth/authorize for the token and authorize paths in Rocket.Chat, and https://gitlabserver.com/chat/_oauth/someauthname for the Callback Url in Gitlab but haven't gotten it to work. I left the Identity Path in Rocket.Chat set to /me.

The log says:
[error] 22432#0: *245 upstream prematurely closed connection while reading response header from upstream, client: x.x.x.x., server: gitlabserver.com request: "POST /chat/sockjs/628/tusywapa/xhr HTTP/1.1", upstream: "http://127.0.0.1:8000/chat/sockjs/628/tusywapa/xhr", host: "http://someserver.com", referrer: "http://someserver.com/chat"

**Comment by askannon** [comment] 2016-08-01 11:32
FYI: the issue outlined in https://github.com/RocketChat/Rocket.Chat/issues/861#issuecomment-143150905 still persists in version 0.35.0. It gets fixed by a server restart tho.
IMHO if it can't be fixed it should at least be documented that OAuth with a private GitLab instance only works after a Rocket.Chat server restart.
