### ISSUE TITLE
Non-GridFS attached file preview not working after upgrade to 7.0.0

### ISSUE THREAD

**Issue by bonarae** [RocketChat/Rocket.Chat#33926] opened 2024-11-09 12:09 UTC
### Description:

File preview on non-GridFS uploaded attachments not working after upgrade from 6.13.0 to 7.0.0

### Steps to reproduce:

1. Open an existing conversation
2. Select an uploaded file that was not uploaded to GridFS, more specifically the said file's preview
3. Download works, but file preview is not working. (please see actual behavior for screenshot)

### Expected behavior:

File preview works as expected for all files

### Actual behavior:

![file preview not working 7 0 0](https://github.com/user-attachments/assets/31376517-7423-48d8-882e-f397485ffeea)

Whenever I click on Retry, file preview of any Minio-uploaded file does not appear; however, after I fixed a small issue with our Minio configuration, file download of Minio-uploaded files is working again. There are no issues with GridFS-uploaded files.

### Server Setup Information:

- Version of Rocket.Chat Server: 7.0.0
- License Type: Community
- Number of Users: 352
- Operating System: Debian 12
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 20.17.0
- MongoDB Version: 6.0.13

### Client Setup Information

- Desktop App or Browser Version: Desktop App 4.1.1
- Operating System: Windows 11

### Additional context

Prior to Rocket.Chat upgrade to version 7.0.0 and MongoDB upgrade to 6.0.13, every file preview was working well.

Prior to opening this issue, I did several workarounds to help pinpoint the root cause:

1. Checked AmazonS3 settings in File Upload (we are using Minio here for our bucket.) I found an issue with our region set in Rocket.Chat (I customized the region of our Minio bucket, hence an error was detected that I later fixed.)
2. Toggled proxy file transmission related settings under AmazonS3 settings (all three), nothing happens, hence this bug report.

### Relevant logs:

Preview of files uploaded using Minio always returns HTTP 500 (Internal Server Error)

`Failed to load resource: the server responded with a status of 500 ()`

**Comment by bonarae** [comment] 2024-11-09 12:16
In addition, upon further inspection, stale cache issue caused this to happen in the desktop app. I checked using a web browser using a fresh session (Firefox 132.0.1) and it currently works.

**Comment by reetp** [comment] 2024-11-10 09:47
> and it currently works.

If it's not a bug then close it please.

**Comment by esnutd** [comment] 2024-11-10 10:00
hello.
Your total number of users was 352. Considering the 50-user limit in this version, are you experiencing any issues with your current user count?

Is the limit only for the number of users online at the same time?

**Comment by reetp** [comment] 2024-11-10 10:07
> Your total number of users was 352. 

>> License Type: Community

Community has no limit. Just the ability of the code to cope.

> stale cache issue
> and it currently works.

So likely notabug and can be closed.

**Closed** 2024-11-10 10:26 UTC

**Comment by mitexleo** [comment] 2025-08-21 10:19
I'm facing this issue after configuring FileSystem as storage. Clearing the browser cache didn't help. Is there any other way? 


data:image/png;base…:1  Failed to load resource: net::ERR_INVALID_URL

data:image/png;base64,undefined
