### ISSUE TITLE
Wrong download link for uploaded files

### ISSUE THREAD

**Issue by ralfbecker** [RocketChat/Rocket.Chat#22708] opened 2021-07-20 10:47 UTC
### Description:

RC creates wrong download links for uploaded files for some domains:
https://tutorial.egroupware.net/rocketchat/ --> https://tutorial.egroupware.n/rocketchat/file-upload/...
https://bb-trunk.egroupware.de/rocketchat/ --> https://bb-trunk.egroupware.d/rocketchat/file-upload/...

while others are ok using the same configuration:
https://pole.egroupware.org/rocketchat/ --> https://pole.egroupware.org/rocketchat/file-upload/...

Other then the wrong download URL Rocket.Chat is working fine, same is always true for the links in the list of uploaded files. 

Alle three domains have apart from the domain-name and URL identical configuration and are running on the same infrastructure using the same MongoDB cluster.

### Steps to reproduce:

1. You need to have an affected domain, otherwise it works fine :(
2. Upload an image eg. into #general 
3. If your domain is affected you see the Retry circle, otherwise the image is displayed

### Expected behavior:

Uploaded image should always use the correct / not garbled URL, independent of the domain-name (correctly configured in RC of course).

### Actual behavior:

For some domain-names the download URL is garbled, some chars cut of the end of the domain name.

Not working domain tutorial.egroupware.net:

![rocketchat-download-link](https://user-images.githubusercontent.com/972180/126308407-59aaa687-3c13-4975-9e1c-9855bc316598.jpg)

Working domain pole.egroupware.org:

![rocketchat-download-link3](https://user-images.githubusercontent.com/972180/126308435-8b668286-c046-46df-9fc2-c7416ad008ef.jpg)

### Server Setup Information:

- Version of Rocket.Chat Server: tested with current maintained versions: 3.16.3, 3.15.4 (screenshots) and 3.14.6
- Operating System: Linux
- Deployment Method: official docker container on Kubernetes, also got a report from a user with docker-compose
- Number of Running Instances: 1 per domain
- DB Replicaset Oplog: yes
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.13 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Lastest Chrome 91.0.4472.164
- Operating System: Mac, Windows and Linux tested

### Additional context

I can supply login credentials for one of the affected public accessible domains, as it's kinda hard to debug otherwise.

### Relevant logs:

- Wrong/garbled domain names make is obviously not into the webserver log
- Docker logs of the container show now errors when it happens
- Browser reports: Failed to load resource: net::ERR_NAME_NOT_RESOLVED https://tutorial.egroupware.n/rocketchat/file-upload/45K3ehP42YdKZSeJe/share%20link.jpg

**Comment by johncrisp** [comment] 2021-07-20 13:07
Hi,

I think I have seen this before but we haven't been able to pin it down.

I think this must be the scenario Stefan mentioned? Can you contact me on https://open.rocket.chat and we can try and figure this one out?

**Comment by johncrisp** [comment] 2021-07-20 16:50
Looks like a duplicate of this.

OK, we need to track this down.

https://github.com/RocketChat/Rocket.Chat/issues/22604

**Comment by ralfbecker** [comment] 2021-07-20 18:42
Missed that one, because it's closed :(

Ralf

**Comment by johncrisp** [comment] 2021-07-22 10:57
This seems to be a frontend issue. The db record seems to be intact -

```
{
	"_id" : "ngbdQLQczoF2pcwCz",
	"name" : "Screenshot from 2021-07-22 14-23-00.png",
	"size" : 361128,
	"type" : "image/png",
	"rid" : "GENERAL",
	"userId" : "o6xYK5SbXa4oat8oR",
	"store" : "GridFS:Uploads",
	"_updatedAt" : ISODate("2021-07-22T09:10:50.438Z"),
	"instanceId" : "sg4Azs32DxPFRWmyt",
	"identify" : {
		"format" : "png",
		"size" : {
			"width" : 2560,
			"height" : 1600
		}
	},
	"complete" : true,
	"etag" : "EXzoMeYrd3Xo2mMCQ",
	"path" : "rocketchat/ufs/GridFS:Uploads/ngbdQLQczoF2pcwCz/Screenshot%20from%202021-07-22%2014-23-00.png",
	"progress" : 1,
	"token" : "891AEaEA8a",
	"uploadedAt" : ISODate("2021-07-22T09:10:50.494Z"),
	"uploading" : false,
	"url" : "http://localhost/rocketchat/ufs/GridFS:Uploads/ngbdQLQczoF2pcwCz/Screenshot%20from%202021-07-22%2014-23-00.png",
	"typeGroup" : "image"
}

```

But the generated HTML for the download button has the wrong hyperlink.

`<a target="_blank" href="http://localhos/rocketchat/file-upload/ngbdQLQczoF2pcwCz/Screenshot%20from%202021-07-22%2014-23-00.png?download" download="Screenshot from 2021-07-22 14-23-00.png" class="rcx-box rcx-box--full rcx-box--animated rcx-button--mini-square rcx-button--square rcx-button--ghost rcx-button rcx-css-1k1r0f9" data-title="Download"><i aria-hidden="true" class="rcx-box rcx-box--full rcx-icon--name-download rcx-icon rcx-css-1g87xs3"> </i></a>`


Note how the domain has been shortened and lost the 't'

`http://localhos/`

**Comment by EmTeedee** [comment] 2021-07-26 14:26
We have the same issue with a truncated domain name.
Installation is running in a subfolder.
Frontend is Apache 2.4

Rocket.Chat Version: 3.15.4
Node-Version: v12.22.1
MongoDB: 4.0.26 / mmapv1 (oplog Aktiviert)

Database records show the correct urls, copying them into the browser downloads the correct attachment.

Unfortunately I can't share screenshots, but I'm happy to try running stuff to debug.

**Comment by gonzole** [comment] 2021-07-30 09:26
We have the same problem. Interesting, that on a mobile device the URL appears correct. The wrong URL is only on a desktop-client or on the Browser...

**Comment by ostjen** [comment] 2021-08-02 17:48
@ralfbecker could you help me to reproduce this issue?

**Comment by Sicoval31** [comment] 2021-08-04 06:36
Hi, same problem with .fr domain name since a few day, download link works but since last update, we don't have the preview image.
Nor video playing :(

RC version 3.16.4 SNAP
Ubuntu 18.04
Node 12.22.1
MongoDB 3.6.14 / wiredTiger (oplog Activé)

**Comment by ostjen** [comment] 2021-08-04 16:33
Hi @Sicoval31, we already found what was causing this issue and we're working to commit a fix asap :slightly_smiling_face:

**Comment by ralfbecker** [comment] 2021-08-06 06:34
Pull-request: https://github.com/RocketChat/Rocket.Chat/pull/22848

**Comment by ostjen** [comment] 2021-08-09 11:31
the fix has just been merged :-)

**Closed by ostjen** 2021-08-09 11:31 UTC

**Comment by Paragenerator** [comment] 2023-10-12 07:40
![rocket link error fix](https://github.com/RocketChat/Rocket.Chat/assets/70489418/027987ac-47d0-4f2b-ad77-b36af23d74fb)

I had a similar problem on Ubuntu server 22.04.3 LTS, it was solved only by correcting the link in the file
/var/snap/rocketchat-server/currrent/OVERWRITE_SETTING_Site_Url.env

you need to edit this string: OVERWRITE_SETTING_Site_Url="link to your rocketchat server"

also in this file there is a command for this solution: sudo snap set rocketchat-server siteurl=${Site_Url}

**Comment by Anguel** [comment] 2024-05-24 10:42
Maybe not the same but very similar problem where old URLs got hardcoded in the database and my solution, hopefully helpful for others:
https://forums.rocket.chat/t/images-served-from-different-server-url-after-migrating-to-another-server-domain-name/17382/2?u=anguel
