### ISSUE TITLE
Using dollar ($) sign in chat causes KaTeX rendering

### ISSUE THREAD

**Issue by bt** [RocketChat/Rocket.Chat#3327] opened 2016-05-22 12:18 UTC
Your Rocket.Chat version: 0.30.0

I'm experiencing an issue where when I use dollar signs in chat, it will try to render it as KaTeX.

For example, the following text:
`$1000 vs $4000`

will render as:
![screen shot 2016-05-22 at 10 16 18 pm](https://cloud.githubusercontent.com/assets/1100843/15453919/26b6b3f6-206b-11e6-9afd-c3515a6951cc.png)

**Comment by xenithorb** [comment] 2016-05-23 16:19
I can confirm, I came here to file this bug. 

Essentially talking about money is broken if you mention two or more dollar values on the same line.

The immediate fix for me is to disable KaTeX rendering, since most people won't use it anyway. (though a neat feature!)

**Comment by stickboy06** [comment] 2016-05-26 16:09
I also see this when users use multiple variable names in one line.  Everything between the two dollar signs is formatted in KaTeX.

**Comment by engelgabriel** [comment] 2016-05-29 14:59
Closed via #3386

**Closed by engelgabriel** 2016-05-29 14:59 UTC
Labels: feat: regex / katex, type: bug
