### ISSUE TITLE
Links on Files List does not open the files

### ISSUE THREAD

**Issue by zookah** [RocketChat/Rocket.Chat#11341] opened 2018-07-04 16:55 UTC
### Description:
Tested on Mac and Linux clients version: 2.11.0
Links on "Files List" does not open the files on desktop clients. It seems as if there is not a link, just the file name.

If I connect via browser, it works.

### Steps to reproduce:

1.  Any room, click on the clip icon (Files list)
2.  Try to click on any listed file, does not matter the extension (e.g. docx, pdf...)
3. 

### Expected behavior:
The file open.

### Actual behavior:
Nothing happens.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.0
- Operating System: Ubuntu server X64 (4.4.0-62-generic)
- Deployment Method:  docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version:
- MongoDB Version: 

### Additional context

It works when I connect via browser so I think the bug is on the client side.

**Comment by tassoevan** [comment] 2018-07-19 18:09
Duplicate of #9557.

**Closed by tassoevan** 2018-07-19 18:09 UTC
