### ISSUE TITLE
Project on developer or docker not starting

### ISSUE THREAD

**Issue by fbsis** [RocketChat/Rocket.Chat#25373] opened 2022-05-02 20:32 UTC
### Description:

After some month without start the project, the npm install and build is not working.

In windows, everything goes fine (npm install), but later, after the build, the port 3000 is not initializate
On Mac, is showing only a grey screen, and the front-end is not started (but port 3000 is working)

Anyone can more with that?

### Steps to reproduce:

1 - Clone the project
2 - Try to start using the process described on documention
3 - After that the process goes forever and dont star
4 - This happen on Docker compose too (in both windows and macOS

### Expected behavior:

The rocket chat must start on developer mode

### Actual behavior:
Dont start and goes forever

### Server Setup Information:

- Version of Rocket.Chat Server: last
- Operating System: windows and macOS
- Deployment Method: Docker or npm run start
- Number of Running Instances:  1
- DB Replicaset Oplog: yes
- NodeJS Version: v14.18.3, v16.14.2 and docker container
- MongoDB Version: embed

### Client Setup Information

- Desktop App or Browser Version:browser version
- Operating System:windows and macOS

### Relevant logs:

```
=> Started proxy.                             
=> Meteor 2.7.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
/Users/braga/.meteor/packages/meteor-tool/.2.5.6.14hs31j.vmzl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Broken symbolic link encountered at /Users/braga/dev/kobe/yalo/Rocket.Chat/node_modules/.bin/node-which
    at isWithinProdPackage (/tools/isobuild/bundler.js:497:19)
    at /tools/isobuild/builder.js:724:15
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at /tools/isobuild/builder.js:734:11
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at Builder._copyDirectory (/tools/isobuild/builder.js:788:5)
    at Builder.copyNodeModulesDirectory (/tools/isobuild/builder.js:550:17)
    at /tools/isobuild/bundler.js:2548:17
    at Function.each (/Users/braga/.meteor/packages/meteor-tool/.2.5.6.14hs31j.vmzl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at JsImage.write (/tools/isobuild/bundler.js:2505:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2760:13)
    at /tools/isobuild/bundler.js:2928:30
    at /tools/isobuild/bundler.js:3067:11
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3062:26
    at /tools/isobuild/bundler.js:3428:22
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3241:31)
    at /tools/isobuild/bundler.js:3184:32
    at Slot.withValue (/Users/braga/.meteor/packages/meteor-tool/.2.5.6.14hs31j.vmzl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/Users/braga/.meteor/packages/meteor-tool/.2.5.6.14hs31j.vmzl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1503:39)
    at Object.bundle (/tools/isobuild/bundler.js:3184:16)
    at /tools/runners/run-app.js:581:24
    at Function.run (/Users/braga/.meteor/packages/meteor-tool/.2.5.6.14hs31j.vmzl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:580:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:949:28)
    at /tools/runners/run-app.js:410:12
docker-compose
```

```
/Users/braga/.meteor/packages/meteor-tool/.2.5.6.14hs31j.vmzl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Broken symbolic link encountered at /Users/braga/dev/kobe/yalo/Rocket.Chat/node_modules/.bin/node-which
    at isWithinProdPackage (/tools/isobuild/bundler.js:497:19)
    at /tools/isobuild/builder.js:724:15
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at /tools/isobuild/builder.js:734:11
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at Builder._copyDirectory (/tools/isobuild/builder.js:788:5)
    at Builder.copyNodeModulesDirectory (/tools/isobuild/builder.js:550:17)
    at /tools/isobuild/bundler.js:2548:17
    at Function.each (/Users/braga/.meteor/packages/meteor-tool/.2.5.6.14hs31j.vmzl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at JsImage.write (/tools/isobuild/bundler.js:2505:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2760:13)
    at /tools/isobuild/bundler.js:2928:30
    at /tools/isobuild/bundler.js:3067:11
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3062:26
    at /tools/isobuild/bundler.js:3428:22
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3241:31)
    at /tools/isobuild/bundler.js:3184:32
    at Slot.withValue (/Users/braga/.meteor/packages/meteor-tool/.2.5.6.14hs31j.vmzl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/Users/braga/.meteor/packages/meteor-tool/.2.5.6.14hs31j.vmzl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1503:39)
    at Object.bundle (/tools/isobuild/bundler.js:3184:16)
    at /tools/runners/run-app.js:581:24
    at Function.run (/Users/braga/.meteor/packages/meteor-tool/.2.5.6.14hs31j.vmzl++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:580:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:949:28)
    at /tools/runners/run-app.js:410:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rocket.Chat@4.6.1 start: `meteor`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Rocket.Chat@4.6.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

On windows:
![image](https://user-images.githubusercontent.com/10360885/166323473-e940a212-494c-43d0-9c62-7a931ee09bd8.png)

**Comment by fbsis** [comment] 2022-05-02 20:56
Docker (docker-compose up) using macOS
```

mongo_1               | 2022-05-02T20:53:26.683+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=70422063f25f
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten] db version v4.0.28
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten] git version: af1a9dc12adcfa83cc19571cb3faba26eeddac92
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten] modules: none
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten] build environment:
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten]     distarch: aarch64
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten]     target_arch: aarch64
mongo_1               | 2022-05-02T20:53:26.702+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, replication: { oplogSizeMB: 128, replSet: "rs0" }, storage: { engine: "mmapv1", mmapv1: { smallFiles: true } } }
mongo_1               | 2022-05-02T20:53:26.705+0000 I STORAGE  [initandlisten] 
mongo_1               | 2022-05-02T20:53:26.705+0000 I STORAGE  [initandlisten] ** WARNING: You have explicitly specified 'MMAPV1' storage engine in your
mongo_1               | 2022-05-02T20:53:26.705+0000 I STORAGE  [initandlisten] **          config file or as a command line option.  Support for the MMAPV1
mongo_1               | 2022-05-02T20:53:26.705+0000 I STORAGE  [initandlisten] **          storage engine has been deprecated and will be removed in
mongo_1               | 2022-05-02T20:53:26.705+0000 I STORAGE  [initandlisten] **          version 4.2. See http://dochub.mongodb.org/core/deprecated-mmapv1
mongo_1               | 2022-05-02T20:53:26.705+0000 I STORAGE  [initandlisten] 
mongo_1               | 2022-05-02T20:53:26.724+0000 I STORAGE  [initandlisten] exception in initAndListen: Location18656: Cannot start server with an unknown storage engine: mmapv1, terminating
mongo_1               | 2022-05-02T20:53:26.724+0000 I CONTROL  [initandlisten] Shutdown started
mongo_1               | 2022-05-02T20:53:26.724+0000 I REPL     [initandlisten] Stepping down the ReplicationCoordinator for shutdown, waitTime: 10000ms
mongo_1               | 2022-05-02T20:53:26.724+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
mongo_1               | 2022-05-02T20:53:26.724+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
mongo_1               | 2022-05-02T20:53:26.724+0000 I NETWORK  [initandlisten] Shutting down the global connection pool
mongo_1               | 2022-05-02T20:53:26.724+0000 I -        [initandlisten] Killing all operations for shutdown
mongo_1               | 2022-05-02T20:53:26.724+0000 I NETWORK  [initandlisten] Shutting down the ReplicaSetMonitor
mongo_1               | 2022-05-02T20:53:26.724+0000 I CONTROL  [initandlisten] Shutting down free monitoring
mongo_1               | 2022-05-02T20:53:26.724+0000 I FTDC     [initandlisten] Shutting down full-time data capture
mongo_1               | 2022-05-02T20:53:26.724+0000 I STORAGE  [initandlisten] Shutting down the HealthLog
mongo_1               | 2022-05-02T20:53:26.724+0000 I -        [initandlisten] Dropping the scope cache for shutdown
mongo_1               | 2022-05-02T20:53:26.724+0000 I CONTROL  [initandlisten] now exiting
mongo_1               | 2022-05-02T20:53:26.724+0000 I CONTROL  [initandlisten] shutting down with code:100
mongo-init-replica_1  | MongoDB shell version v4.0.28
mongo-init-replica_1  | connecting to: mongodb://mongo:27017/rocketchat?gssapiServiceName=mongodb
mongo-init-replica_1  | 2022-05-02T20:53:27.388+0000 E QUERY    [js] Error: couldn't connect to server mongo:27017, connection attempt failed: SocketException: Error connecting to mongo:27017 (172.28.0.2:27017) :: caused by :: Connection refused :
mongo-init-replica_1  | connect@src/mongo/shell/mongo.js:356:17
mongo-init-replica_1  | @(connect):2:6
mongo-init-replica_1  | exception: connect failed
mongo-init-replica_1  | Tried 1 times. Waiting 5 secs...
rocketchat_mongo_1 exited with code 100
mongo_1               | 2022-05-02T20:53:28.100+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_1               | 2022-05-02T20:53:28.104+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=70422063f25f
mongo_1               | 2022-05-02T20:53:28.105+0000 I CONTROL  [initandlisten] db version v4.0.28
mongo_1               | 2022-05-02T20:53:28.105+0000 I CONTROL  [initandlisten] git version: af1a9dc12adcfa83cc19571cb3faba26eeddac92
mongo_1               | 2022-05-02T20:53:28.105+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongo_1               | 2022-05-02T20:53:28.105+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1               | 2022-05-02T20:53:28.106+0000 I CONTROL  [initandlisten] modules: none
mongo_1               | 2022-05-02T20:53:28.106+0000 I CONTROL  [initandlisten] build environment:
mongo_1               | 2022-05-02T20:53:28.106+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo_1               | 2022-05-02T20:53:28.109+0000 I CONTROL  [initandlisten]     distarch: aarch64
mongo_1               | 2022-05-02T20:53:28.109+0000 I CONTROL  [initandlisten]     target_arch: aarch64
mongo_1               | 2022-05-02T20:53:28.109+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, replication: { oplogSizeMB: 128, replSet: "rs0" }, storage: { engine: "mmapv1", mmapv1: { smallFiles: true } } }
mongo_1               | 2022-05-02T20:53:28.110+0000 I STORAGE  [initandlisten] 
mongo_1               | 2022-05-02T20:53:28.111+0000 I STORAGE  [initandlisten] ** WARNING: You have explicitly specified 'MMAPV1' storage engine in your
mongo_1               | 2022-05-02T20:53:28.111+0000 I STORAGE  [initandlisten] **          config file or as a command line option.  Support for the MMAPV1
mongo_1               | 2022-05-02T20:53:28.111+0000 I STORAGE  [initandlisten] **          storage engine has been deprecated and will be removed in
mongo_1               | 2022-05-02T20:53:28.111+0000 I STORAGE  [initandlisten] **          version 4.2. See http://dochub.mongodb.org/core/deprecated-mmapv1
mongo_1               | 2022-05-02T20:53:28.111+0000 I STORAGE  [initandlisten] 
mongo_1               | 2022-05-02T20:53:28.111+0000 I STORAGE  [initandlisten] exception in initAndListen: Location18656: Cannot start server with an unknown storage engine: mmapv1, terminating
mongo_1               | 2022-05-02T20:53:28.111+0000 I CONTROL  [initandlisten] Shutdown started
mongo_1               | 2022-05-02T20:53:28.111+0000 I REPL     [initandlisten] Stepping down the ReplicationCoordinator for shutdown, waitTime: 10000ms
mongo_1               | 2022-05-02T20:53:28.112+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
mongo_1               | 2022-05-02T20:53:28.112+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
mongo_1               | 2022-05-02T20:53:28.112+0000 I NETWORK  [initandlisten] Shutting down the global connection pool
mongo_1               | 2022-05-02T20:53:28.112+0000 I -        [initandlisten] Killing all operations for shutdown
mongo_1               | 2022-05-02T20:53:28.112+0000 I NETWORK  [initandlisten] Shutting down the ReplicaSetMonitor
mongo_1               | 2022-05-02T20:53:28.112+0000 I CONTROL  [initandlisten] Shutting down free monitoring
mongo_1               | 2022-05-02T20:53:28.112+0000 I FTDC     [initandlisten] Shutting down full-time data capture
mongo_1               | 2022-05-02T20:53:28.112+0000 I STORAGE  [initandlisten] Shutting down the HealthLog
mongo_1               | 2022-05-02T20:53:28.112+0000 I -        [initandlisten] Dropping the scope cache for shutdown
mongo_1               | 2022-05-02T20:53:28.112+0000 I CONTROL  [initandlisten] now exiting
mongo_1               | 2022-05-02T20:53:28.112+0000 I CONTROL  [initandlisten] shutting down with code:100
mongo_1               | 2022-05-02T20:53:28.896+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_1               | 2022-05-02T20:53:28.901+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=70422063f25f
mongo_1               | 2022-05-02T20:53:28.902+0000 I CONTROL  [initandlisten] db version v4.0.28
mongo_1               | 2022-05-02T20:53:28.902+0000 I CONTROL  [initandlisten] git version: af1a9dc12adcfa83cc19571cb3faba26eeddac92
mongo_1               | 2022-05-02T20:53:28.902+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongo_1               | 2022-05-02T20:53:28.902+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1               | 2022-05-02T20:53:28.902+0000 I CONTROL  [initandlisten] modules: none
mongo_1               | 2022-05-02T20:53:28.903+0000 I CONTROL  [initandlisten] build environment:
mongo_1               | 2022-05-02T20:53:28.903+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo_1               | 2022-05-02T20:53:28.903+0000 I CONTROL  [initandlisten]     distarch: aarch64
mongo_1               | 2022-05-02T20:53:28.903+0000 I CONTROL  [initandlisten]     target_arch: aarch64
mongo_1               | 2022-05-02T20:53:28.903+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, replication: { oplogSizeMB: 128, replSet: "rs0" }, storage: { engine: "mmapv1", mmapv1: { smallFiles: true } } }
mongo_1               | 2022-05-02T20:53:28.904+0000 I STORAGE  [initandlisten] 
mongo_1               | 2022-05-02T20:53:28.905+0000 I STORAGE  [initandlisten] ** WARNING: You have explicitly specified 'MMAPV1' storage engine in your
mongo_1               | 2022-05-02T20:53:28.905+0000 I STORAGE  [initandlisten] **          config file or as a command line option.  Support for the MMAPV1
mongo_1               | 2022-05-02T20:53:28.905+0000 I STORAGE  [initandlisten] **          storage engine has been deprecated and will be removed in
mongo_1               | 2022-05-02T20:53:28.905+0000 I STORAGE  [initandlisten] **          version 4.2. See http://dochub.mongodb.org/core/deprecated-mmapv1
mongo_1               | 2022-05-02T20:53:28.905+0000 I STORAGE  [initandlisten] 
mongo_1               | 2022-05-02T20:53:28.905+0000 I STORAGE  [initandlisten] exception in initAndListen: Location18656: Cannot start server with an unknown storage engine: mmapv1, terminating
mongo_1               | 2022-05-02T20:53:28.905+0000 I CONTROL  [initandlisten] Shutdown started
mongo_1               | 2022-05-02T20:53:28.905+0000 I REPL     [initandlisten] Stepping down the ReplicationCoordinator for shutdown, waitTime: 10000ms
mongo_1               | 2022-05-02T20:53:28.906+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
mongo_1               | 2022-05-02T20:53:28.906+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
mongo_1               | 2022-05-02T20:53:28.906+0000 I NETWORK  [initandlisten] Shutting down the global connection pool
mongo_1               | 2022-05-02T20:53:28.906+0000 I -        [initandlisten] Killing all operations for shutdown
mongo_1               | 2022-05-02T20:53:28.906+0000 I NETWORK  [initandlisten] Shutting down the ReplicaSetMonitor
mongo_1               | 2022-05-02T20:53:28.906+0000 I CONTROL  [initandlisten] Shutting down free monitoring
mongo_1               | 2022-05-02T20:53:28.906+0000 I FTDC     [initandlisten] Shutting down full-time data capture
mongo_1               | 2022-05-02T20:53:28.906+0000 I STORAGE  [initandlisten] Shutting down the HealthLog
mongo_1               | 2022-05-02T20:53:28.906+0000 I -        [initandlisten] Dropping the scope cache for shutdown
mongo_1               | 2022-05-02T20:53:28.906+0000 I CONTROL  [initandlisten] now exiting
mongo_1               | 2022-05-02T20:53:28.906+0000 I CONTROL  [initandlisten] shutting down with code:100
rocketchat_mongo_1 exited with code 100
mongo_1               | 2022-05-02T20:53:30.194+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_1               | 2022-05-02T20:53:30.197+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=70422063f25f
mongo_1               | 2022-05-02T20:53:30.198+0000 I CONTROL  [initandlisten] db version v4.0.28
mongo_1               | 2022-05-02T20:53:30.198+0000 I CONTROL  [initandlisten] git version: af1a9dc12adcfa83cc19571cb3faba26eeddac92
mongo_1               | 2022-05-02T20:53:30.200+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongo_1               | 2022-05-02T20:53:30.200+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1               | 2022-05-02T20:53:30.200+0000 I CONTROL  [initandlisten] modules: none
mongo_1               | 2022-05-02T20:53:30.200+0000 I CONTROL  [initandlisten] build environment:
mongo_1               | 2022-05-02T20:53:30.201+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo_1               | 2022-05-02T20:53:30.201+0000 I CONTROL  [initandlisten]     distarch: aarch64
mongo_1               | 2022-05-02T20:53:30.201+0000 I CONTROL  [initandlisten]     target_arch: aarch64
mongo_1               | 2022-05-02T20:53:30.201+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, replication: { oplogSizeMB: 128, replSet: "rs0" }, storage: { engine: "mmapv1", mmapv1: { smallFiles: true } } }
mongo_1               | 2022-05-02T20:53:30.201+0000 I STORAGE  [initandlisten] 
mongo_1               | 2022-05-02T20:53:30.202+0000 I STORAGE  [initandlisten] ** WARNING: You have explicitly specified 'MMAPV1' storage engine in your
mongo_1               | 2022-05-02T20:53:30.202+0000 I STORAGE  [initandlisten] **          config file or as a command line option.  Support for the MMAPV1
mongo_1               | 2022-05-02T20:53:30.202+0000 I STORAGE  [initandlisten] **          storage engine has been deprecated and will be removed in
mongo_1               | 2022-05-02T20:53:30.202+0000 I STORAGE  [initandlisten] **          version 4.2. See http://dochub.mongodb.org/core/deprecated-mmapv1
mongo_1               | 2022-05-02T20:53:30.202+0000 I STORAGE  [initandlisten] 
mongo_1               | 2022-05-02T20:53:30.202+0000 I STORAGE  [initandlisten] exception in initAndListen: Location18656: Cannot start server with an unknown storage engine: mmapv1, terminating
mongo_1               | 2022-05-02T20:53:30.202+0000 I CONTROL  [initandlisten] Shutdown started
mongo_1               | 2022-05-02T20:53:30.203+0000 I REPL     [initandlisten] Stepping down the ReplicationCoordinator for shutdown, waitTime: 10000ms
mongo_1               | 2022-05-02T20:53:30.203+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
mongo_1               | 2022-05-02T20:53:30.203+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
mongo_1               | 2022-05-02T20:53:30.203+0000 I NETWORK  [initandlisten] Shutting down the global connection pool
mongo_1               | 2022-05-02T20:53:30.203+0000 I -        [initandlisten] Killing all operations for shutdown
mongo_1               | 2022-05-02T20:53:30.203+0000 I NETWORK  [initandlisten] Shutting down the ReplicaSetMonitor
mongo_1               | 2022-05-02T20:53:30.203+0000 I CONTROL  [initandlisten] Shutting down free monitoring
mongo_1               | 2022-05-02T20:53:30.203+0000 I FTDC     [initandlisten] Shutting down full-time data capture
mongo_1               | 2022-05-02T20:53:30.203+0000 I STORAGE  [initandlisten] Shutting down the HealthLog
mongo_1               | 2022-05-02T20:53:30.203+0000 I -        [initandlisten] Dropping the scope cache for shutdown
mongo_1               | 2022-05-02T20:53:30.203+0000 I CONTROL  [initandlisten] now exiting
mongo_1               | 2022-05-02T20:53:30.203+0000 I CONTROL  [initandlisten] shutting down with code:100
```

**Comment by fbsis** [comment] 2022-05-02 21:14
On Windows (WSL2)
```

2022-05-02T21:12:37.987+0000 E QUERY    [js] Error: couldn't connect to server mongo:27017, connection attempt failed: SocketException: Error connecting to mongo:27017 (172.21.0.2:27017) :: caused by :: No route to host :
mongo-init-replica_1  | connect@src/mongo/shell/mongo.js:356:17
mongo-init-replica_1  | @(connect):2:6
mongo-init-replica_1  | exception: connect failed
mongo-init-replica_1  | Tried 1 times. Waiting 5 secs...
mongo_1               | 2022-05-02T21:12:39.221+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=54c739283602
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten] db version v4.0.28
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten] git version: af1a9dc12adcfa83cc19571cb3faba26eeddac92
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten] modules: none
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten] build environment:
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1               | 2022-05-02T21:12:39.227+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, replication: { oplogSizeMB: 128, replSet: "rs0" }, storage: { engine: "mmapv1", mmapv1: { smallFiles: true } } }
mongo_1               | 2022-05-02T21:12:39.232+0000 I STORAGE  [initandlisten]
mongo_1               | 2022-05-02T21:12:39.232+0000 I STORAGE  [initandlisten] ** WARNING: You have explicitly specified 'MMAPV1' storage engine in your
mongo_1               | 2022-05-02T21:12:39.232+0000 I STORAGE  [initandlisten] **          config file or as a command line option.  Support for the MMAPV1
mongo_1               | 2022-05-02T21:12:39.232+0000 I STORAGE  [initandlisten] **          storage engine has been deprecated and will be removed in
mongo_1               | 2022-05-02T21:12:39.232+0000 I STORAGE  [initandlisten] **          version 4.2. See http://dochub.mongodb.org/core/deprecated-mmapv1
mongo_1               | 2022-05-02T21:12:39.232+0000 I STORAGE  [initandlisten]
mongo_1               | 2022-05-02T21:12:39.242+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
mongo_1               | 2022-05-02T21:12:39.246+0000 I JOURNAL  [initandlisten] recover begin
mongo_1               | 2022-05-02T21:12:39.247+0000 I JOURNAL  [initandlisten] info no lsn file in journal/ directory
mongo_1               | 2022-05-02T21:12:39.247+0000 I JOURNAL  [initandlisten] recover lsn: 0
mongo_1               | 2022-05-02T21:12:39.247+0000 I JOURNAL  [initandlisten] recover /data/db/journal/j._0
mongo_1               | 2022-05-02T21:12:39.248+0000 I JOURNAL  [initandlisten] recover info /data/db/journal/j._0 has zero length
mongo_1               | 2022-05-02T21:12:39.248+0000 I JOURNAL  [initandlisten] recover cleaning up
mongo_1               | 2022-05-02T21:12:39.248+0000 I JOURNAL  [initandlisten] removeJournalFiles
mongo_1               | 2022-05-02T21:12:39.249+0000 I JOURNAL  [initandlisten] old journal file will be removed: /data/db/journal/j._0
mongo_1               | 2022-05-02T21:12:39.255+0000 I JOURNAL  [initandlisten] recover done
mongo_1               | 2022-05-02T21:12:39.273+0000 I JOURNAL  [initandlisten] info preallocateIsFaster couldn't run due to: couldn't open file /data/db/journal/tempLatencyTest for writing Bad file descriptor; returning false
mongo_1               | 2022-05-02T21:12:39.294+0000 I STORAGE  [initandlisten] exception in initAndListen: Location13516: couldn't open file /data/db/journal/j._0 for writing Bad file descriptor, terminating
mongo_1               | 2022-05-02T21:12:39.294+0000 I CONTROL  [initandlisten] Shutdown started
mongo_1               | 2022-05-02T21:12:39.294+0000 I REPL     [initandlisten] Stepping down the ReplicationCoordinator for shutdown, waitTime: 10000ms
mongo_1               | 2022-05-02T21:12:39.294+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
mongo_1               | 2022-05-02T21:12:39.294+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
mongo_1               | 2022-05-02T21:12:39.294+0000 I NETWORK  [initandlisten] Shutting down the global connection pool
mongo_1               | 2022-05-02T21:12:39.294+0000 I REPL     [initandlisten] Shutting down the ReplicationCoordinator
mongo_1               | 2022-05-02T21:12:39.294+0000 I REPL     [initandlisten] shutting down replication subsystems
mongo_1               | 2022-05-02T21:12:39.294+0000 W REPL     [initandlisten] ReplicationCoordinatorImpl::shutdown() called before startup() finished.  Shutting down without cleaning up the replication system
mongo_1               | 2022-05-02T21:12:39.294+0000 I SHARDING [initandlisten] Shutting down the ShardingInitializationMongoD
mongo_1               | 2022-05-02T21:12:39.294+0000 I COMMAND  [initandlisten] Killing all open transactions
mongo_1               | 2022-05-02T21:12:39.294+0000 I -        [initandlisten] Killing all operations for shutdown
mongo_1               | 2022-05-02T21:12:39.294+0000 I NETWORK  [initandlisten] Shutting down the ReplicaSetMonitor
mongo_1               | 2022-05-02T21:12:39.294+0000 I CONTROL  [initandlisten] Shutting down free monitoring
mongo_1               | 2022-05-02T21:12:39.294+0000 I FTDC     [initandlisten] Shutting down full-time data capture
mongo_1               | 2022-05-02T21:12:39.294+0000 I STORAGE  [initandlisten] Shutting down the HealthLog
mongo_1               | 2022-05-02T21:12:39.294+0000 I STORAGE  [initandlisten] Shutting down the storage engine
mongo_1               | 2022-05-02T21:12:39.294+0000 I STORAGE  [initandlisten] shutdown: waiting for fs preallocator...
mongo_1               | 2022-05-02T21:12:39.294+0000 I STORAGE  [initandlisten] shutdown: final commit...
mongo_1               | 2022-05-02T21:12:39.294+0000 I STORAGE  [initandlisten] shutdown: closing all files...
mongo_1               | 2022-05-02T21:12:39.294+0000 I STORAGE  [initandlisten] closeAllFiles() finished
mongo_1               | 2022-05-02T21:12:39.294+0000 I -        [initandlisten] Dropping the scope cache for shutdown
mongo_1               | 2022-05-02T21:12:39.294+0000 I CONTROL  [initandlisten] now exiting
mongo_1               | 2022-05-02T21:12:39.294+0000 I CONTROL  [initandlisten] shutting down with code:100
```

**Comment by dudanogueira** [comment] 2022-05-03 19:30
Hi!!

This is certainly not a bug, rather a config/environment problem. closing this issue :see_no_evil: 

I suggest you to hang on our #dev channel:
https://open.rocket.chat/channel/dev

Also, we have a lot of contributors from the GSoC program that are setting up their environment on [Mac](https://open.rocket.chat/channel/working-on-linux-or-mac), [Windows](https://open.rocket.chat/channel/working-on-windows-wsl2) and [Linux](https://open.rocket.chat/channel/working-on-linux-or-mac) and you can use those channels to get some help too.

**Closed by dudanogueira** 2022-05-03 19:30 UTC
