### ISSUE TITLE
Styling for email verifications

### ISSUE THREAD

**Issue by RichardFoxworthy** [RocketChat/Rocket.Chat#5006] opened 2016-11-22 04:31 UTC
Your Rocket.Chat version: (make sure you are running the latest) 0.47-develop

The emails that are automatically sent for email verification do not get the styling/formatting applied like the other system emails do.

These emails should also be subject to the same styles, formats, and custom message content options configurable for other kinds of emails under Admin-->Email

**Comment by MartinSchoeler** [comment] 2016-11-22 10:53
Duplicate of #876

**Closed by MartinSchoeler** 2016-11-22 10:53 UTC
