### ISSUE TITLE
Display Avatars switch:  unable to disable showing avatars in messages

### ISSUE THREAD

**Issue by vnavna01** [RocketChat/Rocket.Chat#26741] opened 2022-08-30 14:36 UTC
User Preference:
Display Avatars: Hides avatars on the channels, showing only the users' usernames.

This setting since version 5 does not disable the viewing of user's avatars in messages.

**Comment by dudanogueira** [comment] 2022-10-13 12:50
Hi! Thanks for pointing out. Another user also pointed it here:
https://forums.rocket.chat/t/various-settings-not-saved-after-rc-server-upgrade/15075/17

i will raise awareness internally. THanks!

**Comment by drewch34** [comment] 2022-10-14 14:03
@dudanogueira  - Howdy - I wouldn't mind working on this issue if it hasn't been assigned. :)

**Comment by tejaskh3** [comment] 2023-01-17 12:01
Hii am new to open source please assign this issue to me.

**Comment by kunals131** [comment] 2023-01-18 18:15
I want to work on this issue, please assign me.

**Comment by Srishti-j18** [comment] 2023-01-23 19:20
I am very interested in this issue. Can you please assign me this issue?

**Comment by akash19coder** [comment] 2023-01-25 17:36
@dudanogueira I have gone through [https://developer.rocket.chat/rocket.chat/rocket-chat-environment-setup/gitpod](url) and set up everything on my computer. I am not sure where should I begin in order to resolve this issue so could you please help me out?

**Comment by akash19coder** [comment] 2023-01-25 19:21
### When the **Display Avatar** is toggled on
![displayOn](https://user-images.githubusercontent.com/72060440/214662447-16a38be6-cd39-4d68-baff-3870dde7745b.JPG)
Avatar appears which indeed is right
![display](https://user-images.githubusercontent.com/72060440/214663243-7b98ba9f-2bce-4e45-8210-4d6753c1e7af.JPG)

 ___
### When **Display toggle** is off 
![displayOFf](https://user-images.githubusercontent.com/72060440/214663529-dbbf1e11-92e0-4515-88eb-e259e9dd599f.JPG)
Avatar still appears instead of not appearing
![display2](https://user-images.githubusercontent.com/72060440/214664012-3828a65b-db6c-46dd-9d87-89d6f1742cc3.JPG)
 

**Is this what needs to fixed in this issue**

**Comment by akash19coder** [comment] 2023-01-26 09:53
@dudanogueira I play around with the codebase and found out the piece of code related to this issue.
![handleDisplayAvatar](https://user-images.githubusercontent.com/72060440/214806744-876e8ffa-1450-4f93-818c-6df36b3f778b.JPG)

### I am struggling to find the implementation of this function. Please help

**Comment by Abhishek7Tech** [comment] 2023-01-31 07:02
@akash19coder Hi,
have you managed to solve the issue?

**Comment by akash19coder** [comment] 2023-01-31 08:55
@Abhishek7Tech Nope, not yet I am struggling to find out the message component

**Comment by ShadyResurrected** [comment] 2023-02-03 18:58
Can i be assigned this issue?

**Comment by Keerthivardhan1** [comment] 2023-02-04 17:44
I Have tried this .. its working fine . 
i think this issue was resolved 
<img width="268" alt="Screenshot 2023-02-04 231052" src="https://user-images.githubusercontent.com/110013820/216781752-e64b8351-e2f6-40fb-8f8c-de11fbfa8fd6.png">
I have disabled avatars

**Comment by depleur** [comment] 2023-02-09 14:25
@Keerthivardhan1 The avatar is still showing though. I don't think the issue is resolved yet.

**Comment by roy9495** [comment] 2023-02-13 11:12
Is this the solution![rocket_chat](https://user-images.githubusercontent.com/98920199/218442633-00fc88e3-fb5b-48f0-b57d-198d545e1e67.PNG)

**Comment by depleur** [comment] 2023-02-14 04:00
@roy9495 Yes, I think that works.

**Comment by shashank-jain2605** [comment] 2023-02-18 21:02
Hi, If this issue is open, please assign it to me.
I would like to contribute.

**Comment by Sandhya58** [comment] 2023-02-21 16:03
Hello, I can see the issue is still open. I can resolve this issue, please assign it to me.

**Comment by dudanogueira** [comment] 2023-02-22 22:20
great work on https://github.com/RocketChat/Rocket.Chat/pull/28069 @roy9495 !!

Thanks!

**Comment by roy9495** [comment] 2023-02-27 05:37
> great work on #28069 @roy9495 !!
> 
> Thanks!

Thank younsir

**Comment by ASHUTOSH-309** [comment] 2023-03-12 07:00
> [Oct 13, 2022](#event-7580989486)

HOW DO YOU CHECK WHETHER AVATAR IS STILL SHOWING UP OR NOT. I AM NEW PLEASE HELP

**Comment by B1TSH3LL** [comment] 2023-03-12 14:34
i want to work on this issue please assign this to me.!

**Closed** 2023-03-15 18:44 UTC
Labels: type: bug, hacktoberfest, type: regression, contrib: good first issue

**Comment by Mdkaif-123** [comment] 2023-04-06 11:02
If the issue is still pending I'll be glad to fix it .

**Comment by Shibn2** [comment] 2023-07-12 13:35
If the issue is still pending, I 'd like contribute.

**Comment by dougfabris** [comment] 2023-07-20 14:24
@gabepettus it was fixed and available on `6.2.0` release
