### ISSUE TITLE
Grey screen on Chrome and Firefox

### ISSUE THREAD

**Issue by tcoupin** [RocketChat/Rocket.Chat#27529] opened 2022-12-13 16:11 UTC
### Description:

Since v5.4.0, when I open RocketChat in Firefox or Chrome, it starts to load but stop after a few second on grey screen. No problem with electron client.

### Steps to reproduce:

1. Just open rocketchat

### Expected behavior:

Rocketchat working :)

### Actual behavior:

![image](https://user-images.githubusercontent.com/7457386/207383330-5b6bb7bf-0b1a-4097-baaa-c20ba939d8ac.png)

### Server Setup Information:

- Version of Rocket.Chat Server: registry.rocket.chat/rocketchat/rocket.chat:5.4.0
- Operating System: k8s node with ubuntu 20.04.5 LTS
- Deployment Method: kubernetes (helm)
- Number of Running Instances: 1
- DB Replicaset Oplog:  Enabled
- NodeJS Version: 14.19.3
- MongoDB Version: docker.io/bitnami/mongodb:4.4.11-debian-10-r12

### Client Setup Information

My laptop
- Browser Version: Chrome 108.0.5359.98 or Firefox 107.0.1
- Operating System: MacOS Ventura 13.0.1

and other users on windows with firefox

### Relevant logs:

```
fuselage: 0.31.22 [5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js:5:666224](https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true)
MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call [5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js:1583:927930](https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true)
strict mode: use allowUnionTypes to allow union type keyword at "#/properties/value" (strictTypes) [5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js:1046:30998](https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true)
La permission de notification ne peut être demandée que depuis un gestionnaire d’évènements généré par l’utilisateur et en cours d’exécution. [home](https://tchat.ird.fr/home)

Uncaught (in promise) undefined [5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js:1458:3274](https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true)
    onStop https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1458
    _livedata_nosub https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1366
    onMessage https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1366
    onMessage self-hosted:1356
    onmessage https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    forEach self-hosted:203
    forEachCallback https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    onmessage https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    dispatchEvent https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    _dispatchMessage https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    _didMessage https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    onmessage https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    (Asynchrone : EventHandlerNonNull)
    websocket https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    _try_next_protocol https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    _didClose https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    onfinish https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    emit https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    onfinish https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    emit https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    onreadystatechange https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    (Asynchrone : EventHandlerNonNull)
    <anonyme> https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    XHRLocalObject https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    (Asynchrone : setTimeout handler)
    delay https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    XHRLocalObject https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    <anonyme> https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    J https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    (Asynchrone : setTimeout handler)
    delay https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    J https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    q https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    k https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    _launchConnection https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1336
    allowConnection https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1338
    s https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1583
    n https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1583
    g https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:3
    n https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:3
    a https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:5
    n https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1583
    g https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:3
    n https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:3
    t https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:3
    <anonyme> https://tchat.ird.fr/5d1a78ba52d9bb103bf9c4380b56ed853a114e29.js?meteor_js_resource=true:1583

**Comment by tcoupin** [comment] 2022-12-13 20:16
I found a strange behavior..
Before 5.4.0: users log in using CAS server, default login form is hide. But CAS button login was displayed.
Now: I need to display default login form to display CAS button.

**Comment by Gummikavalier** [comment] 2022-12-14 07:29
Possibly a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/27490

Should be fixed in the next version.

**Comment by lyz-code** [comment] 2022-12-15 09:42
Please @sampaiodiego can you do a release with the fix? there are a lot of instances being broken right now. This problem is specially difficult to catch when you upgrade because you won't see the error until your session is expired. That may happen days after the upgrade is done, so the monitorization systems won't catch the issue and the users will be the ones calling the operations teams

**Comment by sampaiodiego** [comment] 2022-12-15 14:26
a patch release including https://github.com/RocketChat/Rocket.Chat/issues/27490 will be shipped later today

**Closed** 2022-12-16 15:07 UTC
