### ISSUE TITLE
Setting Up Rocket Chat locally failed

### ISSUE THREAD

**Issue by thekavikumar** [RocketChat/Rocket.Chat#29314] opened 2023-05-22 14:30 UTC
Hey there,

I was setting up the rocket chat locally to contribute, but when I use yarn many deps get installed and it ultimately failed.
I don't know why it failed. Can anyone help me set up rocket chat?
![image](https://github.com/RocketChat/Rocket.Chat/assets/50093149/9471c540-ccac-467a-bfb0-429414adb9b4)

**Comment by debdutdeb** [comment] 2023-05-22 17:38
Please use wsl2.

Closing as not a bug.

**Closed by debdutdeb** 2023-05-22 17:38 UTC

**Comment by thekavikumar** [comment] 2023-05-23 07:30
Please help me this issue 
![image](https://github.com/RocketChat/Rocket.Chat/assets/50093149/544310b5-1390-4395-8df5-4e9f12b23002)
