### ISSUE TITLE
Snap version doesnt update -> 0.63.3

### ISSUE THREAD

**Issue by Maqsyo** [RocketChat/Rocket.Chat#10842] opened 2018-05-22 05:36 UTC
![image](https://user-images.githubusercontent.com/19644698/40343891-67b9283c-5d92-11e8-86d7-79681dbce46a.png)

The last Versions (0.64.0/0.64.1/0.64.2) where only in the candidate state on snap, so we haven't got an update.

Could you please bring them to the stable channel, so we can get an update?
Or how does your stable-policity works?

Greets :)
~ Maqs

**Comment by TwizzyDizzy** [comment] 2018-05-22 08:33
@rocket-cat close

Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/10656

Cheers
Thomas

**Closed** 2018-05-22 08:33 UTC
