### ISSUE TITLE
Message read confirmation on Direct Message

### ISSUE THREAD

**Issue by dmoldovan123** [RocketChat/Rocket.Chat#8370] opened 2017-10-02 14:52 UTC
### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2
* Operating System: ubuntu 16.04
* Deployment Method(snap/docker/tar/etc):tar
* Number of Running Instances: 8
* DB Replicaset Oplog: yes
* Node Version: 4.5.0

### Steps to Reproduce:
I whant to know if has read  direct message and display time read message. Showing blue double ticks inside the message bubble same as WhatsApp

**Comment by MartinSchoeler** [comment] 2017-10-03 12:16
Duplicate of #4957

**Closed by MartinSchoeler** 2017-10-03 12:16 UTC
