### ISSUE TITLE
Can not find a cancel command when accidantally showing "Drop to upload file"

### ISSUE THREAD

**Issue by victorcassel** [RocketChat/Rocket.Chat#22339] opened 2021-06-14 07:36 UTC
Around 10 times during 4 weeks (novice with rocket chat) I have drag-slipped the mouse and gotten to the chat-covering "Drop to upload file". 

The only way I have found to get out of this overlay is (hard close)  to logout of rocket chat, and login again.

It is frankly horrible.

**Comment by johncrisp** [comment] 2021-06-14 10:04
Hi and thanks for reporting this.

Can you please use a bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines:

https://rocket.chat/docs/contributing/reporting-issues

That includes testing on the latest version of Rocket.Chat - you can test on open.rocket.chat in the sandbox channel.

Note also that for general questions and help you are better off asking in https://forums.rocket.chat or https://open.rocket.chat #support as github is reserved for bugs.

In most instances when doing this just hit escape to cancel. But that may depend on your version and client.

**Comment by ankar84** [comment] 2021-06-15 02:52
Next issue https://github.com/RocketChat/Rocket.Chat/issues/22343 is a bit more fulfilled, so that can be closed as duplicate I guess.

**Comment by debdutdeb** [comment] 2021-07-01 11:44
Duplicate of #22343. Closing this one in favor of that. Thanks.

**Closed by debdutdeb** 2021-07-01 11:44 UTC
