### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [RocketChat/Rocket.Chat#29305] opened 2023-05-19 22:17 UTC
Is the enterprise feature part of rocket chat closed source? Or is there a way I can self host the full version?

**Comment by jw1892626** [comment] 2023-05-21 23:49
It appears enterprise features are still open source, they just require an encrypted license to enable.

**Comment by debdutdeb** [comment] 2023-05-22 10:05
Hi @dillfrescott - our whole codebase is 100% open for anyone to see. But only part of it is under the MIT license, and can be used for free. Anything under the `ee/` folder is under our propreitary license, and requires a purchased license to use.

If you are interested, please talk to our sales team for the enterprise edition pricing as per your needs (mail to sales@rocket.chat).

I'll close this issue, as it's not a bug.

**Closed by debdutdeb** 2023-05-22 10:05 UTC
