### ISSUE TITLE
error in unarchive private group 

### ISSUE THREAD

**Issue by hussamEddinAlhendi** [RocketChat/Rocket.Chat#5582] opened 2017-01-15 14:54 UTC
I'm trying to unarchive a group
<img width="726" alt="screen shot 2017-01-15 at 4 51 32 pm" src="https://cloud.githubusercontent.com/assets/19620859/21963431/49c67780-db43-11e6-81f9-3dc5fd4369a1.png">

**Comment by graywolf336** [comment] 2017-01-15 15:19
Duplicate of #5578

**Closed by graywolf336** 2017-01-15 15:19 UTC
