### ISSUE TITLE
Can not relogin as LDAP user

### ISSUE THREAD

**Issue by xadcoh** [RocketChat/Rocket.Chat#4155] opened 2016-08-31 12:36 UTC
Your Rocket.Chat version: (0.38.0)

Hi. Steps to reproduce:
1. Fresh install with docker-compose
2. Register new local user (creating admin user)
3. Configure LDAP (ldapserver as FQDN or IP (different subnet from rocket.chat server), domain base as top level of catalog, Domain Search User, Domain Search Password, save, test) - OK
4. Login as LDAP user - OK
5. Logout
6. Login as same LDAP user again - Failed

No errors in logs, if logs set to debug, there is a lot of messages, but no errors, just LDAP information about user. Then if login as local admin page will show endless "loading circle", until i press F5. Sometimes i see local admin user without "Administration" menu entry, sometimes it's ok. "Users" menu have an a LDAP user in it (but "Name" field is empty).

OS: Debian 8.5
Docker: 1.11.2
Docker-compose: 1.6.2

Thank you

**Comment by askannon** [comment] 2016-09-07 09:57
Same issue here. After enabling LDAP integration users can log in one time only. After they have logged out they won't be able to login again.

**Comment by askannon** [comment] 2016-09-07 10:11
It only works when I set Merge existing users=True

**Comment by Jamie-Owen** [comment] 2016-09-08 14:39
This is because the `ldap` field is not set in the user document:

[Offending code here](https://github.com/RocketChat/Rocket.Chat/blob/0.39.0/packages/rocketchat-ldap/server/loginHandler.js#L104)

I believe it must have previously been set in this [function](https://github.com/RocketChat/Rocket.Chat/blob/0.39.0/packages/rocketchat-ldap/server/sync.js#L154)

`userData.ldap` is returned by a function, but never set in the DB.

**Comment by ghamed** [comment] 2016-09-09 13:02
same issue

**Comment by gazzerh** [comment] 2016-09-15 11:33
We're seeing this issue as well! This has broken a significant amount of users for us. Please can we have an update on this?

**Comment by windsource** [comment] 2017-03-29 12:10
I have the same issue.

**Comment by bbrauns** [comment] 2017-03-30 14:49
duplicate of #5165 ? We absolutely need a fix for that bug

**Comment by Devact** [comment] 2017-04-19 08:26
The same problem here.

**Comment by kassanmoor** [comment] 2017-06-23 15:50
Need some workaround or patch please

**Comment by xadcoh** [comment] 2017-06-26 06:57
Hi, i just installed 0.56.0 and seems like it works now.

**Comment by kassanmoor** [comment] 2017-07-19 21:32
I am using 0.57.2 and this issue still happening, first times works well, but eventually one user logs out and never can enter again, logs display correct access, only error is:

`rocketchat_logger rocketchat_logger.js:377 LDAP ➔ Connection.error connection { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }`
--

**Closed** 2017-10-03 00:31 UTC
Labels: subj:  Auth - LDAP, type: support
