### ISSUE TITLE
What is the "Document Domain" setting in the General tab? Is it possible to serve attachment of a second domain?

### ISSUE THREAD

**Issue by CrestApps** [RocketChat/Rocket.Chat#23021] opened 2021-08-24 17:08 UTC
By default, rocket.chat appends the uploaded file name to the Site URL which is how the users are able to download/view attached documents. I have a need to service all attachments on a separate subdomain than the site URL.

I did see an option called "Documents Domain" under the General tab in the setting. I thought that would do the trick.... but did not!

First, what is "Documents Domain" option is used for? I find no document for this value.

Second, is there a way to service the attachments on a subdomain which isn't the site URL?

I am running version 3.16.2 locally.

**Comment by debdutdeb** [comment] 2021-08-30 10:09
Hi CrestApps.

Right now I don't have an answer, let me get back to you. 

Thanks.

**Comment by debdutdeb** [comment] 2021-08-30 10:11
Also, github is reserved for only potential bugs :) can you please ask this question on our forum or the open community server?

https://forum.rocket.chat
https://open.rocket.chat/channel/support

I'm closing this now since it's not a bug. But feel free to ask it in one of the other places mentioned above. I'll be there as well (debdut.chakraborty). 

Thank you.

**Closed by debdutdeb** 2021-08-30 10:11 UTC

**Comment by y377** [comment] 2021-12-13 16:44
It should be you say that rocket_url is inserted into an ifarme (another domain name) to solve browser cross-domain access. Document Domain is not a button or function for uploading attachments.
