### ISSUE TITLE
Slack files fail to import due "exceeds allowed size of 0 B" error

### ISSUE THREAD

**Issue by 2wheeladdict** [RocketChat/Rocket.Chat#9792] opened 2018-02-20 21:39 UTC
### Description:

Slack files fail to import into Rocket.Chat.  I have re-created the Rocket.Chat container with the default file size specified in Admin | File Upload, as well as both 20MB and 20GB to further isolate, but all attempts fail to import any files from Slack.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.2
* Operating System: Ubuntu 16.04.3 LTS
* Deployment Method(snap/docker/tar/etc): docker (17.12.0-ce, build c97c6d6), docker-compose version 1.19.0, build 9e633ef
* Number of Running Instances: 1
* DB Replicaset Oplog: (not sure)
* Node Version: 8.9.3

### Steps to Reproduce:

1. Following the guide at https://rocket.chat/docs/administrator-guides/import/slack/#slack-import, request Slack Export
2. Download ZIP
3. Browse to https://[my_rocketchat]/admin/import/prepare/slack
4. Select Slack Export ZIP from Step #2
5. Review items to import (unchecked Deleted Users and Archived Channels)
6. Import completes

### Expected behavior:

Slack files uploaded to Rocket.Chat server.

### Actual behavior:

Slack files are not uploaded.  Further investigation of the Rocket.Chat container logs shows a slew of the following error:

```
Exception in callback of async function: Error: File exceeds allowed size of 0 B. [error-file-too-large]
    at Filter.validateFileUpload [as onCheck] (/app/bundle/programs/server/packages/rocketchat_file-upload.js:119:10)
    at Filter.check (/app/bundle/programs/server/packages/jalik_ufs.js:558:57)
    at FileUploadClass.insert (/app/bundle/programs/server/packages/rocketchat_file-upload.js:587:11)
    at res.on.Meteor.bindEnvironment (/app/bundle/programs/server/packages/rocketchat_importer.js:366:15)
    at runWithEnvironment (packages/meteor.js:1240:24)
```

### Relevant logs:

Rocket Chat container log attached.
[rocketchat.log](https://github.com/RocketChat/Rocket.Chat/files/1741949/rocketchat.log)

**Comment by twardnw** [comment] 2018-02-21 22:03
also reported in #9577

**Comment by graywolf336** [comment] 2018-02-22 05:05
Duplicate of #9577

**Closed by graywolf336** 2018-02-22 05:05 UTC
Labels: feat: import
