### ISSUE TITLE
Purged threads still  show as unread

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#18419] opened 2020-07-29 09:46 UTC
### Description:

When threads were introduced, we played around with it a bit and disabled it. I had two unread comments in a thread, but after disabling threads the unread  counter for the channel was gone. Many releases later, suddenly there was an unread counter for a channel despite the fact that I had read all messages in the channel. Some experimenting later it turned out that when I re-enabled threading, the thread icon had a two unread messages marker. However, since we also have pruning enabled, the old messages were gone, and could not  be read, so I am stuck with a "2" badge on the channel that I cannot get rid of.

### Steps to reproduce:

1. enable threading
2. have unread messages in a thread
3. disable threading
4. wait until after pruning.

### Expected behavior
Unread badges disappear along with pruned messges/threads.

### Actual behavior
Unread badges are kept after pruning and cannot be removed as the messages/threads no longer exists.

- Version of Rocket.Chat Server:  3.5.0
- Operating System:  linux 3.16.0-10-amd64
- Deployment Method: docker
- Number of Running Instances: 2
- DB Replicaset Oplog:  enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 4.0.16

- Desktop App or Browser Version: Any browser. Safari and firefox tested
- Operating System: Mac OS Catalina

**Comment by caesarcxiv** [comment] 2020-07-31 02:58
Docker 3.5.0

Similar: We have unread thread counts on channels that we cannot clear. 

When clicking the channel, selecting threads and filtering for unread, threads appear however opening them does not clear the counter leaving a permanent unread count.

**Comment by lyz-code** [comment] 2020-08-17 15:16
We have a similar problem with 3.5.1. Now you are forced to jump into the thread so the notifications are marked as read

**Comment by caesarcxiv** [comment] 2020-09-02 11:14
Is there a plan to hotfix this? The issue is more noticeable for our user base on 3.6. The rooms with phantom unread counts stay in unread rooms or highlighted on mobile now . Mark as read does nothing creating a lot of confusion on new messages.

**Closed** 2020-09-21 22:44 UTC
Labels: Triaged, feat: prune messages, type: bug

**Comment by caesarcxiv** [comment] 2020-09-30 02:12
Issue still exists - this is the counter after pruning channel to empty. Prior to 3.7 prune did not work on rooms with stuck unread counters.

![image](https://user-images.githubusercontent.com/13050060/94635532-dc5c6e00-02a0-11eb-8632-e1187d0198d1.png)

**Comment by NotACreativeUsername** [comment] 2020-10-15 17:53
Issue is effecting my end users as well. Windows 10 enterprise, Rocket chat version 2.17.11/3.0/3.0.1 and server version Version 3.6.3
