### ISSUE TITLE
client starts jitsi calls

### ISSUE THREAD

**Issue by holzfelix** [RocketChat/Rocket.Chat#16992] opened 2020-03-24 15:50 UTC
Hi Together, the rocket client starts jitsi calls again and again at irregular intervals. it is not reproducible, it is sporadic and it always calls other participants. 

does anyone know the problem?

**Comment by Levesque7** [comment] 2020-03-24 19:11
Same issue here. When an active call is going on, the users in the call are constantly triggering new calls.

**Comment by holzfelix** [comment] 2020-03-25 07:32
Is there a solution for this? Or any other Voice call System to ingetrage?

**Comment by mreitinger** [comment] 2020-03-25 07:33
Probably a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/14106

**Comment by gabriellsh** [comment] 2020-03-25 17:15
Duplicate of #14106

**Closed by gabriellsh** 2020-03-25 17:15 UTC
