### ISSUE TITLE
3.11.0 needs a long time to open large rooms

### ISSUE THREAD

**Issue by fdellwing** [RocketChat/Rocket.Chat#20553] opened 2021-02-02 06:24 UTC
### Description:

After updating to 3.11.0 its feels very slow to open a room with a lot of messages. Like 3-5s waiting time slow. This does not happen when you simple switch between 2 large rooms, but after a while it happens again. There might be caching in place.

### Steps to reproduce:

1. Click on room or private message with a lot of messages
2. For some time nothing happens (2-3s)
3. The room opens and after a short while later the messages appear (1-2s)

### Expected behavior:

Opening a room the first time will always need longer, but something changed in the newest update that increased the time.

### Actual behavior:

The time is to long, it feels slugish.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: Ubuntu 20.04
- Deployment Method: docker-compose
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.9

### Client Setup Information

- Desktop App or Browser Version: both
- Operating System: Kubuntu 18.04/Win 10

### Additional context

None

### Relevant logs:

No relevant logs.

**Comment by error418** [comment] 2021-02-02 12:33
Can confirm this behaviour on a similar setup hosted on k8s after upgrading from `3.10.5` to version `3.11.0`

**Comment by nebulade** [comment] 2021-02-03 10:47
We see the same issue with version 3.11.0 
Additionally the memory usage is a magnitude higher since the update. So possibly this is related. As far as I can tell the cpu usage is not as heavily impacted.

**Comment by joseluisq** [comment] 2021-02-03 14:04
We are facing the same issue when we switch across rooms/channels.
Additionally if we switch too fast we get a too-many-requests alert on the App and then the room/channel keeps just loading.

**Specs:**
Rocket Chat Version: 3.11.0
Apps Engine Version: 1.22.1
Node Version: v12.18.4
MongoDB: 3.4.24

**Comment by fdellwing** [comment] 2021-02-04 17:17
Anyone has an idea whats the cause?

**Comment by fjalade** [comment] 2021-02-05 00:32
Same issue with version 3.11.0
Our mongodb engine is mmapv1 : 4.0.22 / mmapv1 Oplog: enabled
The problem is it the same on wiredTiger engine ? Do we must migrate to wiredTiger, if not ?

**Comment by tars21** [comment] 2021-02-05 05:30
same here with 3.11.0 and MongoDB 3.6.21 / wiredTiger (oplog Enabled).
So far not really reproduceable for me, but it is several times a day sluggish. CPU load / memory / etc appears normal.

**Comment by error418** [comment] 2021-02-05 07:37
Just ran the Profiler in the Electron-App. Maybe this will help to investigate the issue (no sourcemaps configured)

![image](https://user-images.githubusercontent.com/7716544/107003593-563fbf00-678d-11eb-9c8c-f7772c24a187.png)


```js
function v(t) {
  if (1 === _(t) && !(t.metaKey || t.ctrlKey || t.shiftKey || t.defaultPrevented)) {
      for (var e = t.target; e && "A" !== e.nodeName; )
          e = e.parentNode;
      if (e && "A" === e.nodeName && !e.hasAttribute("download") && "external" !== e.getAttribute("rel")) {
          var r = e.getAttribute("href");
          if ((p || e.pathname !== o.pathname || !e.hash && "#" !== r) && !(r && r.indexOf("mailto:") > -1) && !e.target && b(e.href)) {
              var n = e.pathname + e.search + (e.hash || "");
              n = "/" !== n[0] ? "/" + n : n,
              "undefined" != typeof process && n.match(/^\/[a-zA-Z]:\//) && (n = n.replace(/^\/[a-zA-Z]:\//, "/"));
              var i = n;
              0 === n.indexOf(u) && (n = n.substr(u.length)),
              p && (n = n.replace("#!", "")),
              u && i === n || (t.preventDefault(),
              h.show(i))
          }
      }
  }
}
```

**Comment by xi67** [comment] 2021-02-05 07:41
Same here : 
Version : 3.11.0
Version du moteur d'applications : 1.22.1
Version de Node : v12.20.1
Mise à jour de la base de données : 215 (3 février 2021 18:12
MongoDB : 4.2.11 / wiredTiger (oplog Activé)
Détails du commit : HEAD: (62aa68d71)
Branche: HEAD

**Comment by wojciechkepka** [comment] 2021-02-05 16:08
Can confirm the same after upgrade:

Version
3.11.0
Apps Engine Version
1.22.1
Node Version
v12.20.1
Database Migration
215 (February 5, 2021 2:07 AM
MongoDB
4.0.22 / mmapv1 (oplog Enabled)
Commit Details
HEAD: (62aa68d71)
Branch: HEAD

**Comment by rockneverdies55** [comment] 2021-02-17 03:01
Switching between the rooms turned out to be a pain on the neck. Please fix this.

**Comment by robbsie** [comment] 2021-02-17 07:42
> Switching between the rooms turned out to be a pain on the neck. Please fix this.

Yes, thats pure pain. Need to restart the Electron client a few times a day because changing rooms takes up to 30 seconds.

**Comment by habnux** [comment] 2021-02-17 08:11
We also have this problem with version 3.11.1. MongoDB is 4.0.4 / wiredTiger (oplog Enabled). We have around 400 users online. 
The problem also occurs when the administration panel is opened. The load on the DB does not look different to the old version with was 2.4.11.

**Comment by sgoetsch** [comment] 2021-02-17 08:18
Same here. Found out, that it is only slow if you switch between different types of channels. Public to public seems normal, as does switching between private channels or direct messages. Anyways it's quite annoying. Is it possible to roll back to 3.10.x without problems?

**Comment by lehrhardt-tarent** [comment] 2021-02-17 08:22
Can you please increase the priority of this issue? Waiting till 3.12 to fix this is a rather long time for this annoying issue.

**Comment by habnux** [comment] 2021-02-17 08:34
> Same here. Found out, that it is only slow if you switch between different types of channels. Public to public seems normal, as does switching between private channels or direct messages. Anyways it's quite annoying. Is it possible to roll back to 3.10.x without problems?

Nope:
```
Exception in callback of async function: errorClass [Error]: [Can't find migration version 215]
    at Object.Migrations._findIndexByVersion (app/migrations/server/migrations.js:403:8)
    at Object.Migrations._migrateTo (app/migrations/server/migrations.js:254:24)
    at Object.Migrations.migrateTo (app/migrations/server/migrations.js:179:20)
    at module (server/startup/migrations/xrun.js:6:13)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
    at module (server/startup/migrations/index.js:1:4672)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/app/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
    at module (server/main.js:1:210)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /app/bundle/programs/server/app/app.js:190426:15
    at /app/bundle/programs/server/boot.js:401:38
    at Array.forEach (<anonymous>)
    at /app/bundle/programs/server/boot.js:226:21
    at /app/bundle/programs/server/boot.js:464:7
    at Function.run (/app/bundle/programs/server/profile.js:280:14)
    at /app/bundle/programs/server/boot.js:463:13 {
  isClientSafe: true,
  error: "Can't find migration version 215",
  reason: undefined,
  details: undefined,
  errorType: 'Meteor.Error'
}
```

**Comment by habnux** [comment] 2021-02-17 10:04
There's seems a difference between switching from one kind of a channel/room to another. For example, switching between private rooms and public channels is slow. Switching from one public channel to another public channel is okey.

**Comment by araujorm** [comment] 2021-02-17 10:48
Using Firefox as a client seems to be a bit better regarding this recent slowness than chromium based clients (like the rocket chat client). Can anyone confirm, or it's just me?

**Comment by bseclier** [comment] 2021-02-18 10:35
Hello,
Same here, from 3.8.1 to 3.11.1 and the GUI is sooo laggy, specially while switching between rooms and conversations !

**Comment by hartois** [comment] 2021-02-18 14:56
> Using Firefox as a client seems to be a bit better regarding this recent slowness than chromium based clients (like the rocket chat client). Can anyone confirm, or it's just me?

Cannot confirm.
Firefox 83, x86_64, Linux - same lags, very slow

**Comment by r-souza** [comment] 2021-02-19 16:39
Same behavior here

**Comment by r-souza** [comment] 2021-02-19 17:04
Same behavior here

Version
3.11.1
Apps Engine Version
1.22.2
Node Version
v12.18.4
Database Migration
215 (February 11, 2021 7:48 AM
MongoDB
4.0.18 / mmapv1 (oplog Enabled)
Commit Details
HEAD: (7c5d6ae)
Branch: HEAD

**Comment by archiekennedy** [comment] 2021-02-22 11:43
Same behavior using web browser. Instance details:
```
Version
3.11.1
Apps Engine Version
1.22.2
Node Version
v12.18.4
Database Migration
215 (February 11, 2021 15:50
MongoDB
4.0.13 / mmapv1 (oplog Enabled)
Commit Details
HEAD: (7c5d6ae2a)
Branch: HEAD
```

**Comment by gramakri** [comment] 2021-02-22 18:04
Does 3.12 fix this?

**Comment by habnux** [comment] 2021-02-23 09:28
> Does 3.12 fix this?

Who knows? It's not released yet :-)

**Comment by nebulade** [comment] 2021-02-23 09:57
I assume he meant the already released 3.12 release candidates.

**Comment by joseluisq** [comment] 2021-02-23 15:20
We have realized that switching from a private room to a public one (or vice versa) is very slow rather than same type ones (private only or public only).

**Comment by ggazzo** [comment] 2021-02-24 13:35
closed by https://github.com/RocketChat/Rocket.Chat/pull/20860

**Closed** 2021-02-24 17:41 UTC

**Comment by joseluisq** [comment] 2021-03-02 08:15
It's no more slow in 3.12.0
