### ISSUE TITLE
cannot upload files

### ISSUE THREAD

**Issue by oinirio** [RocketChat/Rocket.Chat#4289] opened 2016-09-13 14:45 UTC
cannot upload any kind of files either with drag & drop or with open file

Running latest version of rocketchat/rocket.chat:develop created 26 minutes ago

**Comment by Lucky21110** [comment] 2016-09-13 15:11
same issue for me using develop

**Comment by engelgabriel** [comment] 2016-09-13 16:39
This is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/4235 and @rodrigok is working on it.

**Closed by engelgabriel** 2016-09-13 16:39 UTC
