### ISSUE TITLE
Unable to clone the repo

### ISSUE THREAD

**Issue by pammiraju** [RocketChat/Rocket.Chat#27479] opened 2022-12-07 09:00 UTC
### Description:

Tried to clone the git repo using command provided in installation instructions, unable to clone the same
git clone https://github.com/RocketChat/Rocket.Chat.git

### Steps to reproduce:

1. On windows 11 system, open command prompt
2. Paste the following command - git clone https://github.com/RocketChat/Rocket.Chat.git

### Expected behavior:

Expected to clone to complete successfully

### Actual behavior:

Getting error - (error: invalid path 'apps/meteor/definition/externals/meteor/jparker:gravatar.d.ts')
![image](https://user-images.githubusercontent.com/105298098/206134388-ab6c3da9-4b65-4c44-b5d7-eb541635ce74.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Windows

**Comment by WeOpenChat** [comment] 2022-12-09 01:24
Please use ubuntu or WLS
https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview
You can use Virtualbox to install machine Ubuntu
https://www.virtualbox.org/wiki/Downloads
Or you can download release
https://github.com/RocketChat/Rocket.Chat/releases
https://github.com/RocketChat/Rocket.Chat/archive/refs/tags/5.4.0.zip
https://github.com/RocketChat/Rocket.Chat/archive/refs/tags/5.4.0.tar.gz

**Comment by debdutdeb** [comment] 2022-12-09 15:33
> Please use ubuntu or WLS https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview You can use Virtualbox to install machine Ubuntu https://www.virtualbox.org/wiki/Downloads Or you can download release https://github.com/RocketChat/Rocket.Chat/releases https://github.com/RocketChat/Rocket.Chat/archive/refs/tags/5.4.0.zip https://github.com/RocketChat/Rocket.Chat/archive/refs/tags/5.4.0.tar.gz

Thanks @WeOpenChat : )

WSL2 is a better option than wsl1 or a vm. 

Nonetheless, using pure windows environment is not recommended.

Closing, since it is not a bug.

**Closed by debdutdeb** 2022-12-09 15:33 UTC
