### ISSUE TITLE
Configurable Mentions

### ISSUE THREAD

**Issue by Kpudlo** [RocketChat/Rocket.Chat#2135] opened 2016-02-04 17:13 UTC
I was talking briefly in the support team about the idea of configurable mentions and custom profile fields. 

The configurable mentions would allow admins to assign users to a team, for example the support team, and assign a mention tag to the team, such as @supportteam. 

Then when a member wants to notify just that team within a channel or what not they could simply mention @supportteam and notify anyone assigned to that team.

The custom profile fields is pretty self explanatory, admins could create custom fields that users can enter info into, this could later on be used in things like slash commands or api if wanted.

**Comment by engelgabriel** [comment] 2016-03-09 21:05
There is an issue for the second part of this issue, so I'll edit the title. https://github.com/RocketChat/Rocket.Chat/issues/2046

**Comment by gpoudrel** [comment] 2016-08-23 10:24
would be awesome to get this feature ;)

**Comment by alexandre-zia-movile** [comment] 2016-11-09 13:54
Most wanted here

**Comment by eiti-kimura-movile** [comment] 2016-11-29 16:44
This feature would be great!

**Comment by eduardo-redoschi-movile** [comment] 2016-11-29 18:56
This would be really helpful!

**Comment by engelgabriel** [comment] 2017-02-14 15:44
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2192

**Closed by engelgabriel** 2017-02-14 15:44 UTC
Labels: feat: notification, feat: roles / permissions, type: new feature
