### ISSUE TITLE
RocketChat api/v1/livechat/sms-incoming/twilio always returns BadRequest when department is specified in querystring since PR (#33062)

### ISSUE THREAD

**Issue by btcpbordeaux** [RocketChat/Rocket.Chat#33318] opened 2024-09-19 04:50 UTC
### Description:

Since https://github.com/RocketChat/Rocket.Chat/pull/33062/commits was introduced a month ago, the incoming sms endpoint for twilio (api/v1/livechat/sms-incoming/twilio) returns

400
{"success":false,"error":"Invalid request"}

when a querystring is present

No relevant logs are represent.

Likely related to https://github.com/RocketChat/Rocket.Chat/issues/33194 as this issue could appear to only happen sometimes (if the signature on twilio's is not created with exactly https://[site_url]/api/v1/livechat/sms-incoming/twilio)

See additional context for the cause and potential solution.

### Steps to reproduce:

1. Setup a number in twilio to send request to the incoming sms endpoint handled by twilio service
2. Add querystring for department (department=[departmentId | url encoded department name]
3. Text that number
4. Go to error logs in twilio to see failed request

You could also reproduce in unit tests by considering this case (it is currently not considered in the unit tests)
1. Create unit test in which the requested url contains querystring
2. Build hash for said request
3. Compare this signature against one with url missing querystring
4. Validation will fail
### Expected behavior:

Rocketchat responds to twilio with 200 and empty `<Response>` twiml
The message is received in rocketchat in the correct department

### Actual behavior:

Rocketchat responds with 400 {"success":false,"error":"Invalid request"}

### Server Setup Information:

- Version of Rocket.Chat Server: 6.12.0
- License Type: Enterprise
- Number of Users: 64
- Operating System: Linux x64 release 5.4.0-60-generic
- Deployment Method: docker
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.25

### Client Setup Information

- Desktop App or Browser Version: Chrome 128.0.0
- Operating System: Window 11 Enterprise 23H2 (OS build 22631.4169)

### Additional context

400s from incoming sms for twilio service when query string params are present.

Sorry I am not following the guidelines but do something like the following in

isRequestFromTwilio
validateRequest

make sure the url requested is used when calling twilio's validation functionality:

```
isRequestFromTwilio(signature: string, request: Request): boolean {
	const authToken = settings.get<string>('SMS_Twilio_authToken');

	if (!authToken) {
		SystemLogger.error(`(Twilio) -> URL or Twilio token not configured.`);
		return false;
	}

	const twilioUrl = `${request.protocol}://${request.get('host')}${request.originalUrl}`;
	return twilio.validateRequest(authToken, signature, twilioUrl, request.body);
}

validateRequest(request: Request): boolean {
	// We're not getting original twilio requests on CI :p
	if (process.env.TEST_MODE === 'true') {
		return true;
	}
	const twilioHeader = request.headers['x-twilio-signature'] || '';
	const twilioSignature = Array.isArray(twilioHeader) ? twilioHeader[0] : twilioHeader;
	return this.isRequestFromTwilio(twilioSignature, request.body);
}
```

i dont like nor use node so sorry if that isnt 100% right but I think the reader will get the gist.

### Relevant logs: 
Unfortunately, there are none from where the request handler fails.

**Comment by btcpbordeaux** [comment] 2024-09-19 04:57
If you want you can also grab the siteurl from storage and use that instead:

```
isRequestFromTwilio(signature: string, request: Request): boolean {
	const authToken = settings.get<string>('SMS_Twilio_authToken');
        const siteUrl = settings.get<string>('Site_Url');

	if (!authToken || !siteUrl) {
		SystemLogger.error(`(Twilio) -> URL or Twilio token not configured.`);
		return false;
	}

	const twilioUrl = `${siteUrl}${request.originalUrl}`;
	return twilio.validateRequest(authToken, signature, twilioUrl, request.body);
}

validateRequest(request: Request): boolean {
	// We're not getting original twilio requests on CI :p
	if (process.env.TEST_MODE === 'true') {
		return true;
	}
	const twilioHeader = request.headers['x-twilio-signature'] || '';
	const twilioSignature = Array.isArray(twilioHeader) ? twilioHeader[0] : twilioHeader;
	return this.isRequestFromTwilio(twilioSignature, request.body);
}
```

that should work as well

**Comment by reetp** [comment] 2024-09-19 08:00
> Sorry I am not following the guidelines

Well start doing so please.

ALWAYS fill out a bug template so we know your version etc.

We have no idea if you are on 0.24 or 6.12.1

This stuff is important, not for fun.

You will simply get ignored without it.

Read this and the links on "How to report bugs effectively" and How to ask smart questions" It will help you a lot.

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#how-to-ask-for-help-1

Is this the same as this? Bearing in mind both involve Twilio and seemed to start at the same time (but you have not fully documented that) I imagine they probably have a similar root cause.

https://github.com/RocketChat/Rocket.Chat/issues/33194

**Comment by btcpbordeaux** [comment] 2024-09-19 15:22
Is the above better?

**Comment by reetp** [comment] 2024-09-19 16:32
> Is the above better?

Almost perfect thanks :-)

See the other bug where I mentioned this PR and 6.12.2. Please check if this fixes your issue - I am not sure if it will but worth testing.

https://github.com/RocketChat/Rocket.Chat/pull/33306

**Comment by reetp** [comment] 2024-09-19 16:33
> License Type: Enterprise

You have got a ticket open on this?

**Comment by btcpbordeaux** [comment] 2024-09-19 17:09
Awesome! Sorry I wasn't really being helpful in my first few posts. I was in pretty heavy panic-mode and a little frantic. I will definitely adhere to best practices (yall's and general issue reporting) next time I have an issue. Totally understand how providing only partial info does not help the devs fix the issue.

Yes a ticket was opened (#99097). I will test 6.12.2 (or have another engineer as I am about to catch a flight) and let yall know!

Thank you so much for your help!

**Comment by btcpbordeaux** [comment] 2024-09-19 17:20
After a quick glance at that PR, I think the issue will still be present but we will confirm by updating a test instance of RC to 6.12.2

**Comment by reetp** [comment] 2024-09-19 17:31
Please do.

If it persists I'll try and get some eyes on it.

**Comment by btcpbordeaux** [comment] 2024-09-20 16:05
Unfortunately that PR was fixing another issue related outbound webhooks. Still had the issue but we found a solution:

1. We setup a default Department for our omnichannel livechat
2. We removed all of the department routing from our twilio sms webhook registrations (removed the query string defining the department)
3. We create a small service that polls our rocketchat instance for livechats in the default "queue" department
4. If any chats are in that queue department, we transfer them to the correct department based off of the from number (have a mapping between our twilio numbers and our RC departments so just used that to route ourselves)

Figured I would share in case anyone is experiencing the same issue

**Comment by julio-cfa** [comment] 2024-09-25 19:52
I've just opened a PR to fix this issue here: https://github.com/RocketChat/Rocket.Chat/pull/33364. Thanks a lot for the thorough analysis and suggestions, btcpbordeaux. Much appreciated.

**Comment by reetp** [comment] 2024-10-14 15:27
Can the OP confirm that this is fixed in 6.13.x ?

Be nice to close it off.

**Comment by julio-cfa** [comment] 2024-10-14 20:16
The PR with the fix hasn't been merged yet, but I'll be merging it tonight so it goes into the next release - which will either be 6.14.0 or 7.0.0. I was waiting for QA to finish their tests.

**Comment by julio-cfa** [comment] 2024-10-15 23:27
The PR has been merged and will be in the next release.

**Closed by julio-cfa** 2024-10-15 23:27 UTC
Labels: type: bug, Tasked, in qa
