### ISSUE TITLE
Grey screen after joining channel when using Safari on IOS

### ISSUE THREAD

**Issue by tstafford** [RocketChat/Rocket.Chat#27172] opened 2022-11-02 15:07 UTC
### Description:

Grey screen after joining channel when using Safari on IOS

### Steps to reproduce:

1.  login to rocketchat
2.  click the hamburger in the top left
3.  click any channel

### Expected behavior:

the channel loads and is visible

### Actual behavior:

the channel momentarily appears and then the entire screen is grey

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 5.3.0
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.9 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version:  Safari
- Operating System:  iOS 15.6.1

### Relevant logs:

Server log:
{"level":40,"time":"2022-11-02T14:58:46.819Z","pid":876,"hostname":"x","name":"VoIPService","msg":"Voip is not enabled. Cant start the service"} 
{"level":40,"time":"2022-11-02T14:58:51.456Z","pid":876,"hostname":"x","name":"VoIPService","msg":"VoIP service already stopped"} 
{"level":51,"time":"2022-11-02T14:58:51.832Z","pid":876,"hostname":"x","name":"Migrations","msg":"Not migrating, already at version 281"} 
[DatabaseWatcher] Using change streams 
{"level":40,"time":"2022-11-02T14:58:53.182Z","pid":876,"hostname":"x","name":"StreamBroadcast","msg":"You are operating multiple instances... some features will not behave as designed."} 
+-----------------------------------------+ 
|              SERVER RUNNING             | 
+-----------------------------------------+ 
|                                         | 
|  Rocket.Chat Version: 5.3.0             | 
|       NodeJS Version: 14.19.3 - x64     | 
|      MongoDB Version: 5.0.9             | 
|       MongoDB Engine: wiredTiger        | 
|             Platform: linux             | 
|         Process Port: 3000              | 
|             Site URL: https://x.org  | 
|     ReplicaSet OpLog: Enabled           | 
|          Commit Hash: eb122008e0        | 
|        Commit Branch: HEAD              | 
|                                         | 
+-----------------------------------------+ 
Loaded the Apps Framework and loaded a total of 5 Apps!

**Comment by phriedrich** [comment] 2022-11-02 16:54
Same here on macOS 13.0 with Safari 16.1 and on iPad OS 16.

**Comment by tstafford** [comment] 2022-11-02 20:46
Console from testing on IOS device...
![image](https://user-images.githubusercontent.com/960359/199599158-cda5f738-9731-458f-ab2b-27e19b7f9e6f.png)

**Comment by MaxWaldorf** [comment] 2022-11-03 13:14
confirmed for iOS users here as well...

**Comment by FF-Ibb-PD** [comment] 2022-11-03 15:56
Confirmed for my users also. It also seems to be a Problem on Firefox on Iphone.

**Comment by phriedrich** [comment] 2022-11-03 16:16
@FF-Ibb-PD Firefox on iOS uses Webkit as required by Apple's policies. So it's probably an issue with Webkit.

**Comment by teach404W** [comment] 2022-11-07 09:43
+1 same problem here

**Comment by Sonnenfleck** [comment] 2022-11-14 21:59
Same here. Updated from 4.8.6 to 5.3.0 and upon entering any channel in Safari (iOS or Mac OS 13.0.1), the screen goes blank almost immediately. The log didn't show any errors (except the usual "autotranslate not available"). 

Firefox and Edge on Mac OS worked fine.

**Comment by phriedrich** [comment] 2022-11-14 22:18
Still broken on 5.3.1.

<img width="1237" alt="broken promise" src="https://user-images.githubusercontent.com/470153/201779806-3cdf74ca-8a40-42ef-a068-ffcc74111d02.png">

This is the line where it fails. It seems to iterate through the user/channel list and if one is selected, it breaks.

**Comment by phriedrich** [comment] 2022-11-15 00:05
Found something: I believe it's line 60 in `apps/meteor/client/views/room/MessageList/components/UrlPreview/PreviewList.tsx`:

```javascript
const normalizedUrl = imgURL.replace(/(?<!:)\/+/gm, '/');
```

This was introduced #27159 (5.3.0 release) and fails if I test it in Safari's JS console.

**Comment by ggazzo** [comment] 2022-11-18 12:15
closed by https://github.com/RocketChat/Rocket.Chat/pull/27294

**Closed by ggazzo** 2022-11-18 12:15 UTC

**Comment by phriedrich** [comment] 2022-11-19 09:01
Great, it’s been fixed in 5.3.2. Thanks @filipemarins
