### ISSUE TITLE
Enhancement : New customer chat should generate a POP-UP notification to all logged in agents

### ISSUE THREAD

**Issue by nitinsonawane234** [RocketChat/Rocket.Chat#33455] opened 2024-10-04 10:23 UTC
New chat Pop-up:  
Any new Chat which comes in should generate a POP-UP window to all signed in agents

**Comment by reetp** [comment] 2024-10-04 12:55
Closing as this is not a bug in Rocket.Chat

Please open in the correct repository

https://github.com/RocketChat/feature-requests

**Closed by reetp** 2024-10-04 12:55 UTC
