### ISSUE TITLE
How to see all user's conversation on rocketchat from admin panel or server?

### ISSUE THREAD

**Issue by williamturner845** [RocketChat/Rocket.Chat#13749] opened 2019-03-16 12:31 UTC
Hi, is it possible to see conversation between two users? from my rocketchat admin panel or server?

**Comment by reetp** [comment] 2019-03-18 23:46
This is most likely a duplicate of something like this:
https://github.com/RocketChat/Rocket.Chat/issues/12305

There may be other similar bugs if you search.

**Comment by reetp** [comment] 2019-03-18 23:48
@rocket-cat label add duplicate

**Comment by reetp** [comment] 2019-03-18 23:48
@rocket-cat close
Closing as duplicate.

**Closed by reetp** 2019-03-18 23:48 UTC
Labels: duplicate
