### ISSUE TITLE
[REQUEST-FEATURE] Support github markdowns in chat !

### ISSUE THREAD

**Issue by sudipt1999** [RocketChat/Rocket.Chat#13883] opened 2019-03-24 07:10 UTC
Since Rocket.Chat is a wide community and is used by all type of people, even developer use it a quite lot so it will be really great feature if we support github markdowns.

**Comment by dersvenhesse** [comment] 2019-03-24 12:21
Here are informations about the current Markdown support: https://rocket.chat/docs/contributing/documentation/markdown-styleguide/. For the the extended support exists #918.

**Comment by geekgonecrazy** [comment] 2019-03-28 01:13
Dupe of: #918 

Closing

**Closed by geekgonecrazy** 2019-03-28 01:13 UTC
