### ISSUE TITLE
Multiline code blocks are completely destroyed

### ISSUE THREAD

**Issue by tamasgal** [RocketChat/Rocket.Chat#8839] opened 2017-11-10 18:08 UTC
### Description:

Posting a code block like

```
A=$B
C=$
```

It will be turned int

```
A==!=5FPX7zEERG4Jebxbe=!=
```

This bug makes it impossible to post things where such character combinations are present (like shell scripts).

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Debian Linux 3.16.0-4-amd64
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: ?
* Node Version: v4.8.4

### Steps to Reproduce:

1. post a multi line message with "```" like
```
A=$B
C=$
```

### Expected behavior:

The posted in the chat should be
```
A=$B
C=$
```

### Actual behavior:

The message is turned into
```
A==!=5FPX7zEERG4Jebxbe=!=
```

**Comment by tamasgal** [comment] 2017-11-10 19:19
I just found out that this is caused by KaTeX. Is there a default way to prevent KaTeX from parsing "```" blocks?

**Comment by cyclops24** [comment] 2017-11-12 07:29
You can completely disable KaTeX from admin panel.

**Comment by MartinSchoeler** [comment] 2017-11-13 15:19
Duplicate of #8640

**Closed by MartinSchoeler** 2017-11-13 15:19 UTC
