### ISSUE TITLE
OPLOG / REPLICASET missing error Heroku

### ISSUE THREAD

**Issue by helloTherem8** [RocketChat/Rocket.Chat#14435] opened 2019-05-09 02:57 UTC
### Description: 

I just installed Rocket Chat on Heroku and ended up with the OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT error.  
![imagem](https://user-images.githubusercontent.com/16846752/57424187-c6af5a00-720e-11e9-945f-1bc697ccd002.png)

On https://go.rocket.chat/i/oplog-required, the solutions listed are for if you access to a VPS server, which makes me thing this error should not be occuring with Heroku.

### Steps to reproduce:

Set up the install manually via Heroku CLI using the exact instuctions here: https://rocket.chat/docs/installation/paas-deployments/heroku/

(Under Customized command line for developers. Use the meteor buildpack.)

### Actual behavior:
Cannot find version, or engine. OPLOG / REPLICASET missing error.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.2
- Operating System: Unknown (Heroku)
- Deployment Method: Heroku
- Number of Running Instances: 1
- DB Replicaset Oplog: ? 
- NodeJS Version: 8.11.4
- MongoDB Version: mLab MongoDB 

### Relavent Logs
`2019-05-09T02:43:02.953113+00:00 app[web.1]: ==================================
2019-05-09T02:43:02.956308+00:00 app[web.1]: ➔ server.js:199 System ➔ error
2019-05-09T02:43:02.958279+00:00 app[web.1]: ➔ +---------------------------------------------------------------------------+
2019-05-09T02:43:02.958689+00:00 app[web.1]: ➔ |                                SERVER ERROR                               |
2019-05-09T02:43:02.959058+00:00 app[web.1]: ➔ +---------------------------------------------------------------------------+
2019-05-09T02:43:02.959426+00:00 app[web.1]: ➔ |                                                                           |
2019-05-09T02:43:02.959827+00:00 app[web.1]: ➔ |  Rocket.Chat Version: 1.0.2                                               |
2019-05-09T02:43:02.960203+00:00 app[web.1]: ➔ |       NodeJS Version: 8.11.4 - x64                                        |
2019-05-09T02:43:02.960577+00:00 app[web.1]: ➔ |      MongoDB Version: Error getting version                               |
2019-05-09T02:43:02.961293+00:00 app[web.1]: ➔ |       MongoDB Engine: undefined                                           |
2019-05-09T02:43:02.961665+00:00 app[web.1]: ➔ |             Platform: linux                                               |
2019-05-09T02:43:02.962028+00:00 app[web.1]: ➔ |         Process Port: 31531                                               |
2019-05-09T02:43:02.962384+00:00 app[web.1]: ➔ |             Site URL: https://rocketbox.herokuapp.com/                    |
2019-05-09T02:43:02.962731+00:00 app[web.1]: ➔ |     ReplicaSet OpLog: Disabled                                            |
2019-05-09T02:43:02.963055+00:00 app[web.1]: ➔ |                                                                           |
2019-05-09T02:43:02.963380+00:00 app[web.1]: ➔ |  OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT, MORE INFORMATION AT:  |
2019-05-09T02:43:02.963725+00:00 app[web.1]: ➔ |  https://go.rocket.chat/i/oplog-required                                  |
2019-05-09T02:43:02.964053+00:00 app[web.1]: ➔ |                                                                           |
2019-05-09T02:43:02.964408+00:00 app[web.1]: ➔ +---------------------------------------------------------------------------+
2019-05-09T02:43:03.355070+00:00 heroku[web.1]: State changed from starting to up
2019-05-09T02:43:09.805191+00:00 heroku[web.1]: Process running mem=518M(101.3%)
2019-05-09T02:43:09.805318+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2019-05-09T02:43:29.690753+00:00 heroku[web.1]: Process running mem=518M(101.3%)
2019-05-09T02:43:29.690753+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2019-05-09T02:43:49.932878+00:00 heroku[web.1]: Process running mem=518M(101.4%)
2019-05-09T02:43:49.932988+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2019-05-09T02:44:09.713038+00:00 heroku[web.1]: Process running mem=518M(101.4%)
2019-05-09T02:44:09.713143+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2019-05-09T02:44:29.599670+00:00 heroku[web.1]: Process running mem=518M(101.4%)
2019-05-09T02:44:29.599788+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2019-05-09T02:44:33.000000+00:00 app[api]: Build succeeded
2019-05-09T02:45:21.283851+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=rocketbox.herokuapp.com request_id=86629b2f-da66-416c-8775-d8a966e0d17c fwd="158.69.25.151" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
2019-05-09T02:45:34.744812+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=rocketbox.herokuapp.com request_id=9a8ad0bf-d325-4991-980b-01ac1a9c0fec fwd="37.189.135.143" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 protocol=https
2019-05-09T02:46:01.140281+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/" host=rocketbox.herokuapp.com request_id=0b609c5d-675a-4e86-99a6-870262b0ab67 fwd="158.69.25.151" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 protocol=https2019-05-09T03:14:33.511446+00:00 heroku[web.1]: Idling
2019-05-09T03:14:33.517407+00:00 heroku[web.1]: State changed from up to down
2019-05-09T03:14:34.351257+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2019-05-09T03:14:34.514922+00:00 heroku[web.1]: Process exited with status 143`

Full install log:
https://privatebin.net/?e2395695bd78ebfc#GQX/e+zehhsr4acBE5KWcepmE/Pblr3qY3ZLt8jrqGk=

**Comment by DarkHollow** [comment] 2019-08-14 13:03
I am having just the same problem.

**Comment by reetp** [comment] 2019-08-14 13:11
@rocket.cat label add duplicate

Duplicate of #13198

**Comment by reetp** [comment] 2019-08-14 13:12
@rocket-cat close

**Closed by reetp** 2019-08-14 13:12 UTC
