### ISSUE TITLE
Supercomper is required for fluid operation of the web chat interface on Firefox.

### ISSUE THREAD

**Issue by rfreemobile** [RocketChat/Rocket.Chat#9310] opened 2018-01-02 17:08 UTC
### Description:

Supercomper is required for fluid operation of the web chat interface on Firefox.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.4
* Operating System: debian
* Deployment Method(snap/docker/tar/etc):
* Number of Running Instances:  1
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

Just use the chat, have a room with some text in it, perhaps more text, images etc too.

0. Be an user or 4-8 core intel linux on firefox.
1. Join such chat
2. Start typing, type a "/" character or ":" character or scroll the text
3. The web gui will freeze for 1 to 5 seconds, sometimes more.

### Expected behavior:

It should not freeze

### Actual behavior:

It freezes ;(

100% use of 1 core, by firefox.

### Relevant logs:

Reproduced on dozen of computers.

Some other users report problems too.

**Comment by AmShaegar13** [comment] 2018-01-03 12:18
I've got an Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz with Gnome on Arch Linux using Firefox 57.0.3 (64-bit).

I do not agree with you. https://open.rocket.chat/ runs smooth and I am getting not mor than 20% CPU usage when I enter `/` or `:` or scroll the text in [#general](https://open.rocket.chat/channel/general).

**Comment by TwizzyDizzy** [comment] 2018-03-11 15:29
@rocket-cat close

I'm closing this, as I, too, cannot reproduce it. This might be related to some custom CSS or JS or to the content of some of your rooms.

I'm happy to re-open, if you can provide additional details / logs.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-03-11 15:29 UTC
