### ISSUE TITLE
Feature Request: Global setting to control the default clock format for sidebar time render

### ISSUE THREAD

**Issue by larsziegelmann** [RocketChat/Rocket.Chat#15857] opened 2019-11-25 15:42 UTC
### Description:

Currently viewing the sidebar with an admin account and the last message is shown in the 12h format. The messages in the chat however are in the 24h format. You can change it to the 24h format(by changing Time Format in the My Account section), however only one user at a time. It would be convenient, to have one setting for all the users.

### Steps to reproduce:

1. Go to my account, by clicking on the profile photo.
2. Change the Time Format setting to "24-Hour clock".
3. Start a conversation with one of the users
4. Observe the last message shown in the sidebar
5. Log in with another user
6. Observe the last message shown in the sidebar

### Expected behavior:

Every user has the last message shown in the 24-hour format.

### Actual behavior:

The last message is shown in the 12h format for all the users, without steps 1 and 2.

![image](https://user-images.githubusercontent.com/54264704/69554369-fe5ed300-0fa1-11ea-8ba6-73eb4d8c8727.png)

**Comment by ritwizsinha** [comment] 2019-11-30 06:25
@MartinSchoeler can I work on this ?

**Comment by reetp** [comment] 2019-11-30 09:59
You don't need to ask. Anyone can work on anything.

Just say 'I'll have a go at this'

**Comment by kdubss** [comment] 2019-11-30 18:22
I'd like to have a go at this!

**Comment by ritwizsinha** [comment] 2019-11-30 18:29
@kdubss I have already asked for it please find some other issue

**Comment by kdubss** [comment] 2019-11-30 18:31
@ritwizsinha - Sure thing!  Don't mean to step on any toes. :)

**Comment by ritwizsinha** [comment] 2019-11-30 18:32
Thank you @kdubss for understanding .

**Comment by MartinSchoeler** [comment] 2019-12-02 13:16
For anyone working on this, the fix should be similar to the one done in https://github.com/RocketChat/Rocket.Chat/pull/15385

**Comment by nishantwrp** [comment] 2019-12-02 19:57
Hey @larsziegelmann @MartinSchoeler, I'm unable to reproduce this error. Help!

**Comment by larsziegelmann** [comment] 2019-12-03 14:04
Hey @nishantwrp could you describe what you did to reproduce this issue?

**Comment by nishantwrp** [comment] 2019-12-03 16:49
Set the clock format to 24h
    Start a conversation with one of the users
    Observe the last message shown in the sidebar

**Comment by nishantwrp** [comment] 2019-12-03 16:50
@larsziegelmann Can you record your screen while reproducing this issue and send me the link.

**Comment by ritwizsinha** [comment] 2019-12-04 05:39
@nishantwrp 
I have reproduced the error as follows , 
![image](https://user-images.githubusercontent.com/43509699/70115615-4d81c380-1686-11ea-8f3e-4ded78f91060.png)
The time on sidebar is still 12 hour format while on the chat is 24 hour format
(It's not showing in the morning time , but as the AM/PM aren't there)
This format was enabled by changing clock format to HH:mm in clock format property

**Comment by nishantwrp** [comment] 2019-12-05 18:07
@ritwizsinha I am again not able to reproduce this error

![Screenshot_20191205_233547](https://user-images.githubusercontent.com/36989112/70261258-114e8000-17b8-11ea-80a0-3a5d1214917b.png)

Can you please record your screen while you reproduce this issue.

**Comment by ritwizsinha** [comment] 2019-12-06 02:42
@ggazzo I have work on the function setLastMessageTs in the app/ui-sidenav/sidebaritem.js to fix this issue right ?

**Comment by ritwizsinha** [comment] 2019-12-06 04:56
@ggazzo  Please review

**Comment by rodrigok** [comment] 2019-12-09 12:30
@larsziegelmann you can change the setting **Time Format** in **My Account** page to 24h format:

![image](https://user-images.githubusercontent.com/234261/70435771-79c28900-1a66-11ea-957f-751f175ad3b9.png)

Would this solve your problem?

**Comment by larsziegelmann** [comment] 2019-12-10 11:50
@rodrigok I was first surprised that, that worked. But the issue with this, is that you have to go and change this setting on every user - if my thinking is correct.
It would be much more practical to have one setting for it, which applies to every user. Like a policy, in that matter.

**Comment by rodrigok** [comment] 2019-12-10 12:06
@larsziegelmann that setting is a personal thing to change the render only, as you can see it will not remove the roles from the user's info panel.

If you want a global setting to hide any role information for security purposes or any other reason I suggest you close this issue and open a new issue of Feature Request at https://github.com/RocketChat/feature-requests describing this behavior.

Thanks

**Comment by rodrigok** [comment] 2019-12-10 12:08
@larsziegelmann sure, we can create a global setting to define the default behavior. Would that work? If yes, can you change the title and improve the description on that matter?

Thanks

**Comment by larsziegelmann** [comment] 2019-12-10 12:35
Yes, of course. Thank you for your help.

**Comment by ritwizsinha** [comment] 2019-12-10 13:15
I will try and work again on this

**Comment by ggazzo** [comment] 2019-12-10 14:55
Actually we have this setting, but we are not using at the sidebar... we made a proper fix here: https://github.com/RocketChat/Rocket.Chat/pull/15930 (thank @ritwizsinha)

btw: @larsziegelmann if you are changing an user preference, we expect only the user will see the changes... to reflect for all users you should look for admin settings

**Comment by larsziegelmann** [comment] 2019-12-10 15:41
@ggazzo Of course, but I didn't find any setting for changing the time format for the last message in the sidebar.

**Comment by ggazzo** [comment] 2019-12-20 20:10
now if the user didnt change the option, it will render `Message_TimeFormat ` that you set

**Closed** 2019-12-20 20:11 UTC
Labels: contrib: easy, subj: ui/ux
