### ISSUE TITLE
Proposal: add a thumbnail picture to the channels

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat#3998] opened 2016-08-14 20:52 UTC
Like in Snapchat, it would be nice to have the possibility of adding a photo thumbnails on the channels

**Comment by tgxn** [comment] 2016-08-14 23:51
I like the sound of this!
I believe TG has the same config option so you can have an image per channel.

Would be nice to see it under channel info, and possible in the header-bar.

**Comment by tgxn** [comment] 2016-08-16 04:15
Duplicate Issue found: Issue #3582

**Comment by graywolf336** [comment] 2016-08-29 20:07
Closing as it is a duplicate of #3582

**Closed by graywolf336** 2016-08-29 20:07 UTC
Labels: subj: ui/ux, type: new feature
