### ISSUE TITLE
One-click install for heroku is not working

### ISSUE THREAD

**Issue by kareemcoding** [RocketChat/Rocket.Chat#14531] opened 2019-05-16 17:07 UTC
The one-click install for Heroku is not working

### Steps to reproduce:

1. Go to the one-click install for rocket chat
2. Follow instructions
3. As Heroku builds the app it fails

### Expected behaviour:

Use the app

### Actual behaviour:

Heroku build errors

### Server Setup Information:

- Version of Rocket.Chat Server: latest version for the Heroku build

### Additional context

Tried multiple times all lead to the same result

### Relevant logs:

See logs.txt attached
[logs.txt](https://github.com/RocketChat/Rocket.Chat/files/3188189/logs.txt)

**Comment by jaredmoody** [comment] 2019-05-21 06:12
Duplicate of #13198

**Comment by reetp** [comment] 2019-08-14 13:10
@rocket-cat label add duplicate

**Comment by reetp** [comment] 2019-08-14 13:10
@rocket-cat close

**Closed by reetp** 2019-08-14 13:10 UTC
Labels: duplicate
