### ISSUE TITLE
Avatar (top-left where user menu is) does not show for RC hosted in subdirectory

### ISSUE THREAD

**Issue by JoshMcCullough** [RocketChat/Rocket.Chat#22311] opened 2021-06-10 17:33 UTC
### Description:

The `url` attribute on the `<span>` which contains the current user's avatar (the top-left user menu) is incorrect. The URL does not include the current subdomain. In our case RC is hosted at `/chat` but the avatar is fetched from `/avatar/<username>` when it should be `/chat/avatar/<username>`.

### Steps to reproduce:

1. login to RC
2. observe the top-left user menu avatar is missing

### Expected behavior:

Avatar shows up.

### Actual behavior:

Avatar does not show up:

![image](https://user-images.githubusercontent.com/4859660/121570766-2da42c00-c9f0-11eb-95bd-48213e543063.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: RHEL 7
- Deployment Method: RPM / source
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.2.5

### Client Setup Information

- Desktop App or Browser Version: N/A (all -- Chrome for instance)
- Operating System: N/A (all -- Linux, Mac OS for instance)

**Comment by johncrisp** [comment] 2021-06-10 23:27
Hi,

> • Version of Rocket.Chat Server: 3.9.1

Please follow our guidelines for reporting issues:

https://rocket.chat/docs/contributing/reporting-issues

Can you please test this on the latest release? Your version is not supported so any issues you have will not be fixed.

https://docs.rocket.chat/getting-support

Bugs are often fixed on the latest release so please test it there first and see if it still occurs. You can also test on the development version, or try on open.rocket.chat which is usually the latest development code.

Thanks.

**Comment by johncrisp** [comment] 2021-06-11 08:51
OK, I just realised more here.

As an additional piece of context Rocket.Chat was going to drop sub directory support - there are Issues here and comments in the forums as to why.

However, after much discussion we are going to continue it, and as a result there are some subdirectory issues that had arisen that were not going to be fixed, but are now.

This is a duplicate of

https://github.com/RocketChat/Rocket.Chat/issues/18759
https://github.com/RocketChat/Rocket.Chat/issues/19542

It should be fixed with this PR:

https://github.com/RocketChat/Rocket.Chat/pull/22290

That will be released in the forthcoming 3.16 release, if not before.

I am going to close this as a duplicate in favour of the other two existing Issues.

**Closed by johncrisp** 2021-06-11 08:51 UTC

**Comment by JoshMcCullough** [comment] 2021-06-12 13:02
Thank you for the info!
