### ISSUE TITLE
Feature Request: Self-destructing messages

### ISSUE THREAD

**Issue by SeMeKh** [RocketChat/Rocket.Chat#14782] opened 2019-06-11 06:06 UTC
We use RocketChat as our internal organization communication platform. It'd be great to be able to set a self-destruction timer for sensitive messages (e.g. passwords, personal information, etc.) in cases where those information needs to be communicated right away.

A similar feature that has been proposed before: https://github.com/RocketChat/Rocket.Chat/issues/2196

**Comment by reetp** [comment] 2019-06-12 10:51
@rocket-cat close

Going to close this as it is a feature request, not a bug. Please re-open here:

https://github.com/RocketChat/feature-requests

**Closed** 2019-06-12 10:51 UTC
