### ISSUE TITLE
Deleting messages not propagated to other users

### ISSUE THREAD

**Issue by koen-serneels** [RocketChat/Rocket.Chat#7204] opened 2017-06-09 09:02 UTC
Rocket.Chat Version: .57-rc1
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version:

Hi. I want to allow that each user is able to edit or delete their own messages. When I enable the "delete message" permission, the user is able to do this, but it seems that the message is only deleted for that user and not for others, this is very weird as other users keep seeing the deleted message (I cannot believe this would ever be intended behavior). 

Enabling the permission "force delete message" seems to fix this (message is instantly deleted for all other users as well). However, when this permission is enabled it seems that a user can delete messages not owned by them as well, so everyone can delete every other user's message which is off course not what I want.  Is this a bug or am I missing something?

**Comment by MartinSchoeler** [comment] 2017-06-09 13:07
duplicate of #6941

**Closed by MartinSchoeler** 2017-06-09 13:07 UTC

**Comment by dmoldovan123** [comment] 2017-12-05 08:46
+1
