### ISSUE TITLE
Explain how to set/use `Accounts_AvatarStoreType` 

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#978] opened 2015-10-02 20:43 UTC
When running through docker-compose, I can't upload an image as an avatar. I'm not sure how to ssh into the docker vm to see if that directory exists but happy to help debug. I *do* get a notification that the upload and image change was successful, however.

**Comment by mhkeller** [comment] 2015-10-02 20:45
Changing the type to `FileSystem` works now. Could this be documented on why this works / maybe a dropdown menu to choose between options:

**Comment by geekgonecrazy** [comment] 2015-10-03 20:52
> When running through docker-compose, I can't upload an image as an avatar. I'm not sure how to ssh into the docker vm to see if that directory exists but happy to help debug. I do get a notification that the upload and image change was successful, however.

So using the docker-compose setup out of the box i'd for sure not recommend using fileSystem storage at all.

If it actually works it'll be in the container.  When you goto upgrade the rocket.chat container for a new version your files will be gone.

You need to add a volume in your docker-compose file and map a folder inside the container to outside.

Something like:
```
volumes:
   - ./files:/var/www/uploads
```

As far as the types of storage used I agree these do need documented or a dropdown.

**Comment by mhkeller** [comment] 2015-10-05 19:25
Got it. Is using `GridFS` what you would recommend? Does that route require any additional configuration?

**Comment by royalaid** [comment] 2015-10-05 19:54
I just want to echo that out of the box the GridFS setup for avatars and docker does not work for me either.

**Comment by amcdawes** [comment] 2015-10-11 21:50
Running out-of-the box with docker-compose I don't see avatar changes with GridFS (default) or with FileSystem. Is there anything else you changed mhkeller?

**Comment by mhkeller** [comment] 2015-10-11 22:31
after updating the latest neither are working for me either.

On Sun, Oct 11, 2015 at 5:51 PM, Andrew M. C. Dawes <
notifications@github.com> wrote:

> Running out-of-the box with docker-compose I don't see avatar changes with
> GridFS (default) or with FileSystem. Is there anything else you changed
> mhkeller?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RocketChat/Rocket.Chat/issues/978#issuecomment-147249331>
> .
>



-- 
@mhkeller
mhkeller.com

**Comment by MuhClaren** [comment] 2015-10-13 07:16
>after updating the latest neither are working for me either.

Confirmed. 

Upload appears to have worked, Rocket.Chat renders the balloon notification stating the avatar change was successful, and I can see the changed avatar. However, the change doesn't persist through a reboot of the server. 

Before (I can see the avatar): <div class="avatar-image" style="background-image:url(/avatar/admin.jpg?_dc=478);"></div>

After (I cannot see the avatar image, only the initials): <div class="avatar-image" style="background-image:url(/avatar/admin.jpg?_dc=0);"></div>

Running default docker-compose out of the box, auto-starting on boot with init script.

**Comment by Dbzman** [comment] 2015-10-15 10:48
We also noticed the exact same problem with avatars today. (using docker, too)
Avatar settings in RocketChat are configured like this:
*Accounts_AvatarStorePath:* /var/www/rocket.chat/uploads/avatar/
*Accounts_AvatarStoreType:* GridFS (we tried FileSystem also)

Then I mounted "/var/www/rocket.chat/uploads/avatar/" to the host system (also because this default path did not exist in the docker container) and checked the if the avatars are uploaded there (container and host). There were not.

**Comment by royalaid** [comment] 2015-10-15 17:29
I had to change the path that RocketChat uses, current I am mounting $PWD/avatarstore:/avatarstore and using /avatarstore inside rocketchat for the avatar storage path.

**Comment by MuhClaren** [comment] 2015-10-15 22:24
I saw a commit related to avatars yesterday (or was it two days ago), and launched a new instance of the docker image, which seems to have fixed the issue for me.

Avatars are sticking now, and surviving reboots, logouts, etc.

**Comment by Dbzman** [comment] 2015-10-16 06:16
That didn't fix it for me. Now when I upload an avatar the App crashes with this.
```
[methods] setAvatarFromService ->  userId: P4FdQnrRgn7bt8FRm contentType: image/jpeg service: upload

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by MuhClaren** [comment] 2015-10-17 12:16
**UPDATE / WORK-AROUND:**

I have found a way to get avatars working consistently using docker-compose, nginx SSL reverse proxy, Ubuntu 14.04 (64 bit).

1. First, and foremost: TURN OFF CLOUDFLARE! If you have cloudflare in the middle, go into your DNS settings and click the orange cloud to bypass your chat traffic around cloudflare. As long as I failed to do this, the avatar upload behaviors are very janky at best, and don't work properly.

2. In the chat admin panel, click on Accounts. find "Accounts_AvatarStorePath" and remove any path in the field. Save it empty. Currently, rocketchat looks for *any* string in this field, and sets it as the avatar store path. Since we now know that the pre-populated string in that field is buggy due to permissions, by removing all content and saving it, it causes rocketchat to use by default ~/uploads in the container, which does indeed have proper permissions.

3. Finally, if you are using a self-signed SSL cert, either go buy a commercial cert and install it, or abandon HTTPS completely, lieu HTTP. During my tests, using only HTTP the system performed MUCH faster than all other testing periods I've done. Everything (well mostly) seems to magically begin working, and performing with no lag. I opted to buy a commercial cert (a comodo wildcard SSL) and have installed it on the chat server. What a difference! Once again, things seem to start working again, including avatars. performance is much, much better, too.

I'm finishing up a deployment guide for Docker-Ubuntu 14.04 with Nginx SSL Reverse Proxy, Hubot, with Automated start-up and crash recovery. If you get stuck even after trying these suggestions, check the wiki later this evening for the guide which will include all of my configurations. Good luck!

**Comment by Dbzman** [comment] 2015-10-17 18:51
@MuhClaren 
Thanks for investigating! :)
I played around with that a bit (dev version, no docker) and see similar issues.
* AvatarResize causes the server to crash with boths store types
* with GridFS the avatars are at least persisted but not overwritable (see #1150)
* with FileSystem and a folder with correct permissions I can see the files are placed there but after a site refresh the avatar is not shown again (but laying around on the filesystem)

**Comment by MuhClaren** [comment] 2015-10-17 21:19
@Dbzman 

I too had every single one of those problems, using the docker automated build image, which is basically bleeding edge code that is built into a docker image every time a repository commit is made.

After performing the steps I've illustrated above, every one of those problems is gone, including the crashing when avatar resize is on. The images display as they should now, and persist when changed by the user. I'm finishing up my guide and will have it published to the wiki in a few hours. I encourage anyone struggling with these issues to check it out.

Kind regards.

**Comment by Dbzman** [comment] 2015-10-17 21:40
@MuhClaren 

That's interesting. I even tried to empty the "Accounts_AvatarStorePath" you mentioned and had the 3 issues I described in the post above.

Some minutes ago I just tried it again with this configuration:
```
AvatarResize: true
AvatarStorePath:
AvatarStoreType: FileSystem
```
And now it seems to work correctly, so I can
* upload avatars without crashing the server
* see the current avatar on the filesystem
* see the current avatar even after a page refresh

I don't know why this works now (Maybe there were some broken caches?) but your workaround seems to be working perfectly!  I'll try this on our docker environment on Monday to see if this can be fixed there as well. (probably using your guide) :)

Many thanks and best regards

**Comment by MuhClaren** [comment] 2015-10-18 05:43
@Dbzman Glad it's working for you! 

Guide: https://github.com/RocketChat/Rocket.Chat/wiki/Docker-Ubuntu-14.04-%2864-bit%29-VPS-with-Nginx-SSL-and-Hubot

**Comment by mhkeller** [comment] 2015-10-18 21:58
Has anyone been using the heroku deploy method and running into issues? I just spun one up and can't set custom avatars.

**Comment by Dbzman** [comment] 2015-10-19 05:55
I just tried it again on our docker environment. (Using this docker image: "https://hub.docker.com/r/rocketchat/rocket.chat/")
The problem is that $HOME is pointing to the none existing folder "/home/rocketchat" and I cannot find any folder which is accessible by the rocketchat user. (besides "/tmp/ufs" which also leads to crashes when I upload an avatar using this folder) If I mount a folder to the host system it is still owned by root:root. I think for now I'll fall back to GridFS and live with the issue that I cannot overwrite avatars.

**Comment by royalaid** [comment] 2015-10-19 17:08
Check to make sure your root_url is set.

**Comment by Dbzman** [comment] 2015-10-20 06:29
@mhkeller 
Do you see anything in the logs when you set an avatar?

**Comment by blaskovicz** [comment] 2015-10-22 21:01
I was able to get the avatar upload working with the following settings

```
resize: false
size: 20000
path: /home/username/some/dir/that/exists
type: FileSystem
```

**Comment by Dbzman** [comment] 2015-10-22 21:42
@blaskovicz 
I tried it with the docker container again using your settings. Only Safari currently reverts back to the initials. Probably the fix from @MuhClaren works better than I thought because I always used Safari which seems to have caching issues here.

I also have to find a writable folder which can be used. (I don't like to use "/tmp") I guess in the Dockerfile such a folder should be created.

**Comment by Dbzman** [comment] 2015-10-23 06:04
Again I tried it with the docker container.
FileSystem seems to reliably store avatars and delete them. The only issue I have is:
After resetting the avatar I have to open the image directly to get a non-cached version. (Even Force-Reload multiple times does not help; affects Safari and Chrome so far)
And as soon as I mount the folder to my host system the folder is owned by root again and I cannot write to it anymore. :(

**Comment by mhkeller** [comment] 2015-10-23 16:44
I'm using heroku deploy now with `FileSystem` and `/var/www/rocket.chat/uploads/avatar/` as the path. Uploads work, but similar to the above, they don't persist for the user on refresh.

**Comment by Porco-Rosso** [comment] 2015-10-31 18:22
using the below configuration does indeed allow me to upload the image, and I can find it stored under ~/uploads
however, refreshing breaks this, and the image goes back to displaying the username initials despite the file still being under ~/uploads and having the correct permissions.

```
resize: false
size: 500
path: 
type: FileSystem
````
PS: on Ubuntu 14.04

**Comment by Porco-Rosso** [comment] 2015-11-02 12:07
Somehow the issue has resolved itself.
Under chrome I had to check `Disable cache (while DevTools is open)` from the developer tools options and refresh the page to get it to work.

**Comment by engelgabriel** [comment] 2015-11-17 20:18
The `?_dc` is the main problem here. We don't store the file version anywhere, we just increment the number when people change avatar to get the new file, and we were expecting the cache to be small enough that the `?_dc=0` would be re-fetched next time the person login.

We need to fine tune this setting, so the cache only persist for that session, so by the time the `?_dc=x` is reset, so is the cache.

**Comment by engelgabriel** [comment] 2015-11-18 01:31
We fixed the cache problem :) can anyone test it?

**Comment by k0nsl** [comment] 2015-11-18 01:54
@engelgabriel: I can confirm it to be fixed on my own instance. :+1:

**Comment by engelgabriel** [comment] 2015-11-18 03:07
Added
```
apt-get install -y graphicsmagick
```
and
```
USER rocketchat
RUN mkdir ~/uploads
```
to Dockerfile and made it the default path

**Closed by engelgabriel** 2015-11-18 03:07 UTC
Labels: type: improvement

**Comment by Sing-Li** [comment] 2015-11-18 05:35
Please test the latest docker image   rocketchat/rocket.chat  

It now should save avatar files across restart, even if you changed to FileSystem for storage.

Let us know if it works for you.  Thanks.

**Comment by MuhClaren** [comment] 2015-11-29 08:19
@Sing-Li Tested in a freshly rolled docker instance on Ubuntu 14.04 - x64, using all default settings, including GridFS and no path defined in the admin UI. After I purged the browser cache, it worked as intended. Avatars stuck and survived session changes, reboots, etc. :+1: 

Nice work!
