### ISSUE TITLE
Right side panel is not open in IE with size more than 1600 px

### ISSUE THREAD

**Issue by Cikcak** [RocketChat/Rocket.Chat#8711] opened 2017-10-30 13:27 UTC
### Description:

Right side panel is not open in IE with size more than 1600 px

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.2
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap/docker
* Number of Running Instances: 1
* Node Version: v4.8.4

### Steps to Reproduce:

Open Internet Explorer, load rocket.chat, open room, click to icon on right side,

### Expected behavior:
Than right side the panel should be open.

### Actual behavior:

When width IE windows is more than 1600 px, right side pannel is not open.

**Comment by MartinSchoeler** [comment] 2018-10-23 16:47
@Cikcak  This has probably been fixed on the latest release as I couldn't reproduce this in it. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Closed by MartinSchoeler** 2018-10-23 16:47 UTC
Labels: subj: ui/ux, type: bug
