### ISSUE TITLE
Message attachments not collapsed when 'collapsed: true' provided in v6.2.0

### ISSUE THREAD

**Issue by PapaAAnthony** [RocketChat/Rocket.Chat#29276] opened 2023-05-17 19:14 UTC
### Description:

We recently upgraded to to v6.2.0 of RocketChat, however it seems like in this release message attachments do not initially appear collapsed when `collapsed: true` is provided in the message request body.

### Steps to reproduce:

1. Using curl as below to make a request containing a test message with an example message attachment containing fields:
`curl -H "X-Auth-Token: my-token" \
     -H "X-User-Id: my-id" \
     -H "Content-type:application/json" \
     https://localhost:3000/api/v1/chat.postMessage \
     -d '{"channel":"#general","emoji":":smirk:","text":"Sample message","attachments":[{"collapsed":true,"color":"#abcdef","fields":[{"title":"test 1","value":"test 1 value"},{"title":"test 2","value":"test 2 value"}],"text":"test text","title":"test title","title_link":"https://youtube.com","ts":"2016-12-09T16:53:06.761Z"}]}'`
2. observe message in specified channel and it is not collapsed.

### Expected behavior:
In previous releases message attachments with `collapsed: true` would appear as below:
<img width="221" alt="Screenshot 2023-05-17 at 19 56 07" src="https://github.com/RocketChat/Rocket.Chat/assets/89987320/7eb50d93-4c58-4d25-b714-8f08a457ca5e">

### Actual behavior:

In v6.2.0 attachments are appearing expanded even if `collapsed: true` is provided:
<img width="277" alt="Screenshot 2023-05-17 at 19 56 22" src="https://github.com/RocketChat/Rocket.Chat/assets/89987320/6e8682f1-b37f-42a3-a672-fd2a9a161ae4">

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.0
- Operating System: Debian GNU/Linux
- Deployment Method: Helm
- Number of Running Instances: 1
- NodeJS Version: v14.21.3
- MongoDB Version: 6.0.5

**Comment by c4risw** [comment] 2023-05-19 10:17
We can confirm this is an issue to. Its quite frustrating.
A fix would be welcome.

**Comment by naivecoder8080** [comment] 2023-05-19 19:38
Hi!
Looks like an interesting issue!
Can I get a little bit more information on how to reproduce it
Thank You!

**Comment by c4risw** [comment] 2023-05-22 11:29
When using integrations, you should be able to specify collapsed being true or false. 
the functionality is mentioned here in the API documentation  https://developer.rocket.chat/reference/api/rest-api/endpoints/core-endpoints/chat-endpoints/postmessage#attachments-detail
you should be able to specify collapsed as a parameter for an attachment as bellow 

<img width="777" alt="Screenshot 2023-05-22 at 12 26 38" src="https://github.com/RocketChat/Rocket.Chat/assets/134055806/2edadb74-abee-439e-be81-4f2b0f8dae13">

This used to work fine until the latest release, now the value is being ignored and all messages being received when viewed in client are always open / uncollapsed 

hope this helps you to track it down.

**Comment by naivecoder8080** [comment] 2023-05-23 11:04
Thank You!
Just one more question.
How do I get Auth token for myself

**Comment by Kishn0109** [comment] 2023-05-28 13:22
![image](https://github.com/RocketChat/Rocket.Chat/assets/85572761/5ac9edc3-3802-47e5-acd8-4e693c84318e)
I tried creating a webhook and hit the URL but it gives 503 internal server error it. Am I missing something?

**Comment by ChrisJBurns** [comment] 2023-06-09 16:41
Just to add, we'd like this with a bit of urgency. We have bot channels that house alerts for the project and we're finding that it's crashing some peoples browsers when they try and load the channel because of the amount of increase text being pushed into the history. We're having to purge all of the channels every day to stop this from happening.

**Comment by muckelba** [comment] 2023-06-09 16:46
+1, that bug renders our alerting channel useless because it takes minutes to load. I have to re-start the desktop application once a day to keep it responsive

**Comment by SparksFlyx3** [comment] 2023-06-29 11:42
We are also experiencing some trouble with our alerting channel because of this. Please fix it soon!

**Comment by mil7** [comment] 2023-07-07 05:56
I have one more insight: Even if I collapse messages manually in my struggle to gain some overview, the next time I enter the chat all messages are reverted to be open. So it might not be an issue with the handling of the incoming message but with the UI state itself.

**Comment by gsommavilla** [comment] 2023-08-04 10:15
I just want to add that we are not experiencing this issue with the android app;
i.e., in the android app the messages are correctly collapsed.

**Comment by wcalkins** [comment] 2023-08-04 19:43
The issue seems to be caused by a null value in the `collapsed` variable. This may not be the correct fix, but falling back to using `attachment.collapsed` when `collapsed` is null in [Attachments.tsx](https://github.com/RocketChat/Rocket.Chat/blob/19aec23cdae33c08cacc8c20d26dda7be4eae178/apps/meteor/client/components/message/content/Attachments.tsx#L16C63-L16C72) seems to solve the problem.
```
<AttachmentsItem key={index} attachment={{ ...attachment, collapsed: collapsed ?? attachment.collapsed }} />
```
Hopefully this helps @hugocostadev

**Comment by hoppedmalt** [comment] 2023-09-04 10:04
This is a really annoying bug, as simple automated notification (having three informative lines of text in the attachment) hogs easily 1/7 of the vertical space from chat area (that is already crowded with excessive amount of empty space, message header lines, etc).

**Comment by shiryov** [comment] 2023-09-18 03:31
still not fixed in 6.3.3. this is critical for installations with a large number of integrations (Zabbix, Grafana, etc.)

**Comment by hoppedmalt** [comment] 2023-09-20 09:03
I can't find any fix propopsals from pull requests either and this issue is not (yet) assigned to anyone. This is a quite big rock in a shoe though.

**Comment by casalsgh** [comment] 2023-10-06 21:14
The problem still happening. We believe it might be related to: https://github.com/RocketChat/Rocket.Chat/pull/28579.

Steps to Reproduce still: 
-Using API/webhook integration to make a request containing a test message with an example message attachment.
-Observe message in specified channel and it is not collapsed.

Expected Behavior
-In previous releases message attachments with collapsed: true would appear as collapsed

Actual Behavior
-In v6.2.0 attachments appear expanded even if collapsed: true is provided

**Comment by casalsgh** [comment] 2023-11-03 12:18
@naivecoder8080 still want to be assigned to tackle this one?

**Comment by hardikbhatia777** [comment] 2023-12-25 13:41
@casalsgh This should be fixed by #31318 :)

**Comment by debdutdeb** [comment] 2023-12-26 22:33
hm this may be one fix .. but probably not the ideal one. IIRC when i looked at this, there was an inconsistency in how collapsed was passed at different stages vs how it was read. Just a comment for now

**Closed** 2024-01-03 17:49 UTC
Labels: type: bug, type: regression, need help

**Comment by casalsgh** [comment] 2024-01-03 18:39
@hardikbhatia777 thanks for another great fix for rocket.chat! =) 
The PR will be released on 6.6.0 (date to be defined, most likely end on January).

**Comment by asule90** [comment] 2024-02-15 05:41
after upgraded to 6.6.0 , message attachment with `collapsed: true` is not visible.. only showing small attachment color (in my case: red)
![image](https://github.com/RocketChat/Rocket.Chat/assets/10544636/1c54e222-2b14-47ad-8f36-2636b547f3e1)

**Comment by hardikbhatia777** [comment] 2024-02-15 06:32
> after upgraded to 6.6.0 , message attachment with `collapsed: true` is not visible.. only showing small attachment color (in my case: red) ![image](https://private-user-images.githubusercontent.com/10544636/304962125-1c54e222-2b14-47ad-8f36-2636b547f3e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5Nzg3NzksIm5iZiI6MTcwNzk3ODQ3OSwicGF0aCI6Ii8xMDU0NDYzNi8zMDQ5NjIxMjUtMWM1NGUyMjItMmIxNC00N2FkLThmMzYtMjYzNmI1NDdmM2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA2Mjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOThiNDViMWJlMTQ2OWFiMDMwZjE1NTc5YzMxMjA3NmVlYmVlNzcxZDlhMjBhNzk2NDg2YjRkZGY4OTA4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JbmDzhP_cj45gBuZkaxH-YaL93H1eanJ3CwAoMOeXxg)

@asule90 I'm sorry to hear that. I'll look into the problem once more. As far as I remember, this was properly tested before being merged (by me and QA staff as well). Thank you for reporting the issue!
