### ISSUE TITLE
reacting to an old message brings new message indicator

### ISSUE THREAD

**Issue by pranavpandey1998official** [RocketChat/Rocket.Chat#14549] opened 2019-05-18 11:15 UTC
### Description:

reacting to an old message brings new message indicator

### Steps to reproduce:

1. Go to any old message in channel
2. React on it

### Expected behavior:
No new message indicator unless there is a new message

### Actual behavior:

new message indicator comes up

### Server Setup Information:
tested on open.rocket.chat

**Comment by geekgonecrazy** [comment] 2019-05-22 23:15
seems to have to do with the dom growing in height.

**Comment by zdumitru** [comment] 2019-08-21 09:47
Still happening in the latest stable version `1.3.0`

**Comment by ggazzo** [comment] 2019-10-17 23:12
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/10219

**Closed by ggazzo** 2019-10-17 23:12 UTC
Labels: subj: ui/ux, type: bug
