### ISSUE TITLE
avatars in the user profile or the user overview link to a wrong path

### ISSUE THREAD

**Issue by krautbernd** [RocketChat/Rocket.Chat#19151] opened 2020-10-06 17:30 UTC
### Description:

avatars in the user profile or the user overview link to a wrong path instead of the giving `ROOT_URL=https://foo.bar/rocket/` via .enf-file

### Steps to reproduce:

use sub-url as root

### Expected behavior:

avatars shown properly

### Actual behavior:

linking to `https://foo.bar/avatar/%40userbar` instead of `https://foo.bar/rocket/avatar/userbar`

![nothing](https://user-images.githubusercontent.com/39069188/95236701-8c812800-0807-11eb-83e6-fba2365fc265.PNG)
![wrongpath](https://user-images.githubusercontent.com/39069188/95236709-9014af00-0807-11eb-9130-6f6177cbe413.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1-x64
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: FF81 GC85
- Operating System: Win/Linux

**Comment by ggazzo** [comment] 2020-10-07 17:45
duplicate of : https://github.com/RocketChat/Rocket.Chat/issues/18759

**Closed by ggazzo** 2020-10-07 17:45 UTC
Labels: feat: subdir
