### ISSUE TITLE
Forbidden file Upload after install Nginx

### ISSUE THREAD

**Issue by juanpowerplanet** [RocketChat/Rocket.Chat#15449] opened 2019-09-26 11:45 UTC
Hi:
I had a installation of Rocket Chat under http and all works ok. But then, we decided to configure under https with nginx. I follow that instructions:
https://rocket.chat/docs/installation/manual-installation/configuring-ssl-reverse-proxy/
After that, everything works ok, except the file upload. It tries to upload and after a seconds, it's say "forbidden".
In the logs I didn't saw anything. Can anyone help me?
Thank you.

**Comment by reetp** [comment] 2019-09-26 12:18
You have told us virtually nothing about your situation - no one can help you unless you prepare a proper bug report.

In this instance it would appear almost certainly this is a configuration issue and not a bug.

Please read and fill in this:
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

Particularly read these links:
> Please see our guide for opening issues: https://rocket.chat/docs/contributing/reporting-issues
> If you have questions or are looking for help/support please see: https://rocket.chat/docs/getting-support

Unless you can provide any evidence that there is a bug in Rocket then please close this Issue and ask for help in the forums or open.rocket.chat - just make sure you provide some proper information about your setup.

**Closed** 2019-09-26 12:43 UTC
