### ISSUE TITLE
[BUG] 2FA Challenge is not provided with LDAP authentication

### ISSUE THREAD

**Issue by lennartgrunau** [RocketChat/Rocket.Chat#11570] opened 2018-07-26 07:35 UTC
### Description:

When enabling 2FA with LDAP the Challenge isn't being provided and 2FA is just passed.

### Steps to reproduce:

1. Enable 2FA
2. Log in

### Expected behavior:

RocketChat asks for the 2FA token.

### Actual behavior:

RocketChat isn't asking for the 2FA token.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.3
- Operating System: Ubuntu 16.04
- Deployment Method:  snap
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: As shipped 
- MongoDB Version: As shipped

### Additional context

No additional context

### Relevant logs:

No relevant logs

**Comment by metalcated** [comment] 2018-08-16 14:06
Yes this is also happening to our instance, I noticed my 2FA hasn't worked for a while and I chalked it up to cached logins but that is definitely not the case. Thanks

**Comment by marcinkorzycki** [comment] 2018-09-20 12:43
Still waiting for implement this.

**Comment by metalcated** [comment] 2018-10-31 21:35
Any progress on this by chance? Thanks

**Comment by lennartgrunau** [comment] 2018-11-12 15:09
This was reported in July and is still an issue. Any progress?

**Comment by igeorgie** [comment] 2019-01-15 08:11
We have the same problem! We really need this option for production.
Great product b.t.w. Thanks!

**Comment by marcinkorzycki** [comment] 2019-01-30 14:00
Any news here?

**Comment by metalcated** [comment] 2019-02-02 04:31
Yeah, I feel like this really needs some attention.

Thanks

**Comment by rjozwiak** [comment] 2019-02-07 12:15
Any updates on it? The feature is critical for companies I think.

**Comment by shakalandy** [comment] 2019-02-13 08:03
Is it possible to sponsor this one? If so, how?

**Comment by Shaverdoff** [comment] 2019-03-16 14:25
0.7.4.3 version RC&LDAP. still the same bug... or maybe we do not correclty undersutd that functional? 2fa login or 2fa works by itself..? becauze 2fa works by itself well, ask code from Goo-2fa app... but whats the point ot them? %)

**Comment by Shaverdoff** [comment] 2019-03-16 14:27
> 
> 
> Is it possible to sponsor this one? If so, how?

in release tread - https://github.com/RocketChat/Rocket.Chat on bottom page yellow button donate. press here and you surf to paypal donates-service

**Comment by theorenck** [comment] 2019-04-09 16:08
@MarcosSpessatto can you take a look in this one?

**Comment by MarcosSpessatto** [comment] 2019-04-09 17:10
@theorenck please see: https://github.com/RocketChat/Rocket.Chat/pull/11731#issuecomment-454132142

**Comment by marcinkorzycki** [comment] 2019-04-28 10:46
1.0.0 released - still no 2fa ldap fixed...

**Comment by rjozwiak** [comment] 2019-05-21 14:28
Really hope this will be fixed in 1.1.0

**Comment by Yures** [comment] 2019-06-17 19:46
Docker image v 1.1.1, still not working.

**Comment by kbabioch** [comment] 2019-08-16 07:14
Running version 1.3.2, this is still an issue. Even though 2-FA is enabled in my account, I'm not being presented with the challenge during login.

This essentially renders this feature broken, and make Rocket.Chat as a whole less secure. Authentication that is behaving unexpectedly is **really bad**.

Since this used to work fine a lot of versions ago, this should be considered as regression. People that have previously enabled this security feature, might not notice that it is no longer working.

**Comment by Falco20019** [comment] 2019-08-26 06:55
It's in the 2.0.0 milestone now. Hope it arrives there since that one contains a lot of LDAP features we have also waited for.

**Comment by stbc** [comment] 2019-10-17 20:37
Oh...moved to 2.2.0. This is disappointing... :/

**Comment by darkpal** [comment] 2019-10-29 16:22
Still not implemented? pfff

**Comment by waiting-for-rocketchat-fixes** [comment] 2019-11-06 19:52
2.20 is here but no changes still not fixed, It look like they just moving this bug every new milestone without plan to work on it.  If you guys have no plans to touch it why you add to every new milestone ?

**Comment by reetp** [comment] 2019-11-07 11:11
> 2.20 is here but no changes still not fixed, It look like they just moving this bug every new milestone without plan to work on it. If you guys have no plans to touch it why you add to every new milestone ?

Because the bug still exists, but for whatever good reason it has not net fixed yet. Milestone is just a target. This is Open Source - there are no guarantees. Developers may have different priorities with their existing paying customers. It may be important to you, but not the developers.

There are a number of other things that also have to be fixed first to enable this (follow the PR links above)

You have a number of available options:

You can fix it yourself and contribute the PR.
You could employ a developer to fix it for you and contribute the PR. 
You can pay for support and ask for it to be fixed.
You can Donate https://github.com/RocketChat/Rocket.Chat#donate
You have to wait quietly and patiently and hope that the developers decide to fix it.

**Comment by Shaverdoff** [comment] 2019-11-07 11:14
And you quick you make confirm PR?

 

 

 

--

Gerasim Shaverdov | Deputy CTO | Altarix 

Mobile:  <tel:+7%20937%20070%2066%2084> +7 937 070 66 84 | Skype/email:  <mailto:gerasim@altarix.ru> gerasim@altarix.ru
Lenina av.25, Samara, Russia, 443068

**Comment by mddvul22** [comment] 2019-11-07 13:37
> Because the bug still exists, but for whatever good reason it has not net fixed yet. Milestone is just a target. This is Open Source - there are no guarantees. Developers may have different priorities with their existing paying customers. It may be important to you, but not the developers.

I think people understand that there might be other priorities.  But if 2FA is broken, it should be shipped with the feature disabled.

**Comment by greatfireball** [comment] 2019-12-10 15:02
Interestingly, I need to provide a code for authentication via REST API. Neither the web front end nor the Linux client are asking for the 2FA, but REST will...

**Comment by Shaverdoff** [comment] 2019-12-25 15:34
2.3.2 version...but still not working in electron and web client

**Comment by Venomen** [comment] 2020-01-31 08:49
Any news about this issue?

**Comment by JargeZ** [comment] 2020-05-15 20:21
Maybe someone was able to solve this problem indirectly
And are there any workarounds to get this working now?

**Comment by jwilczek** [comment] 2020-05-18 15:52
Anyone aware of an update or work-around for this?

**Comment by MarcosSpessatto** [comment] 2020-06-03 16:14
Guys, we need to have [this](https://github.com/RocketChat/Rocket.Chat/pull/11726) PR merged before.

**Comment by rodrigok** [comment] 2020-06-03 17:04
Just a quick note, the PR mentioned by @MarcosSpessatto is scheduled to this month release.

**Comment by jocelynthode** [comment] 2020-09-24 06:35
@rodrigok Hey, do you know if there is another ETA for the PR mentionned by @MarcosSpessatto ?

**Comment by watchtiger** [comment] 2020-11-04 14:49
any update on this? It's still not working in version 3.7.0. 
That's a critical bug in an company environment

**Closed** 2020-11-21 01:34 UTC
Labels: feat: api, subj:  Auth - LDAP, type: bug
