### ISSUE TITLE
Reaction emote

### ISSUE THREAD

**Issue by kakawait** [RocketChat/Rocket.Chat#864] opened 2015-09-23 15:44 UTC
Another useless features but really cool, on *Slack* you can ask reaction using emote (call *reaction emote*) with following syntax:

`+:emote:` like (my favorite) `+:+1:` in order to upvote my *supra-funny* gif or question I just posted!

example

![screen shot 2015-09-23 at 17 43 12](https://cloud.githubusercontent.com/assets/275609/10050043/9f3191bc-621a-11e5-9707-eef84d0010cc.png)

**Comment by marceloschmidt** [comment] 2015-09-23 16:04
Duplicate of #505

**Closed by marceloschmidt** 2015-09-23 16:04 UTC
