### ISSUE TITLE
Top left icons disappear with FF ESR

### ISSUE THREAD

**Issue by magicbelette** [RocketChat/Rocket.Chat#10117] opened 2018-03-13 08:47 UTC
### Description:

Top left icons disappear with FF ESR (52.6) by clicking on them.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Debian
* Deployment Method(snap/docker/tar/etc): Tar
* Number of Running Instances: 3
* DB Replicaset Oplog: Enabled
* Node Version: 8.9.3
* mongoDB Version: 3.2.12

### Steps to Reproduce:

1. Randomly click on top left icons
2. Icons disappear (see below)
![capture d ecran - 13032018 - 09 23 28](https://user-images.githubusercontent.com/6803105/37331083-337a9f90-26a3-11e8-9935-8e07a889209d.png)

### Relevant logs:

No logs on the server, FF doesn't give anything in the console either.

**Comment by theorenck** [comment] 2018-03-13 21:48
Hi @magicbelette, can you give us a little more context on the problem? Did it happens all the time? Did you tested it in any other browser?

**Comment by magicbelette** [comment] 2018-03-14 09:46
Reproducible with FF 45.9, FF 52.6, most of the time this combination leads to hide top left icons :
- in a Channel like `#general`
- click `Search`, then `Directory`, then ` View mode`
- icons disappear

No problem with Chrome 64.

**Comment by karlprieb** [comment] 2018-04-11 19:42
@magicbelette Ouch, you're right. I tested here and it's happen. We will change all our icons on the next releases and with that we will change our icon system too, so when we do that this problem will be fixed too.

Thank you for your report!

**Comment by MartinSchoeler** [comment] 2018-10-23 17:53
This issue was probably fixed in the latest releases, as I couldn't reproduce this bug anymore. If you happen to experience this again please reopen this. Thanks!

**Closed by MartinSchoeler** 2018-10-23 17:53 UTC
Labels: stat: need more info, subj: ui/ux, type: bug
