### ISSUE TITLE
Deleted Messages Disappear for User but Not Deleted

### ISSUE THREAD

**Issue by cpitman** [RocketChat/Rocket.Chat#6941] opened 2017-05-10 22:32 UTC
Rocket.Chat Version: 0.56.0-rc1
Running Instances: 4
DB Replicaset OpLog: On
Node Version: v4.8.1

We recently upgraded to the latest RC, and noticed today that when a user deletes a message it isn't *really* deleted. All other users continue to see the message, it only disappears from the deleting user's chat. If the original user refreshes, the message is there again.

**Comment by MartinSchoeler** [comment] 2017-05-11 14:18
I confirmed this on a local latest develop branch. However Admins can still delete messages, i could be wrong but this looks like a issue with permissions

**Comment by marceloschmidt** [comment] 2017-05-11 16:22
@cpitman can you please confirm you are trying to delete with an unprivileged user, and please check who has permissions for `delete-message` and check also `Allow Message Deleting` and `Block Message Deleting After (n) Minutes` settings under Messages section.

**Comment by nORKy54** [comment] 2017-05-17 14:55
same issue on 56.0.
For me, delete-message is for owner and user. Allow Message deleting is OK and Block message after (n) minutes are 120min (and I try to delete a new message).
You must know that I have others roles with nothing checked. Only to print a user role near its name.
permissions are merged ?

**Comment by adam-kulagowski** [comment] 2017-05-25 12:02
Same issue on 0.56 on Yours codilime.rocket.chat cloud. Nothing was changed in permission at our side.

**Comment by geekgonecrazy** [comment] 2017-05-26 16:27
Just checked with a new 0.56.0 instance. Seems to be fine on new instances.  So this must be an issue due to upgrading.  

I know @adam-kulagowski instance has upgraded several times.  

@nORKy54 i assume you upgraded as well.  What version did you come from?  0.55.0?

**Comment by geekgonecrazy** [comment] 2017-05-26 16:30
@adam-kulagowski @nORKy54 also can you test with a new user and see if they are also unable to?  Or if its only existing users effected

**Comment by skbach** [comment] 2017-05-30 19:46
I'm getting the same bug.  No upgrade, just new install.  It happens if you set the Admin -> Message Permissions to Block Message Deleting After (n) Minutes.  I set it to 5 minutes, but then immediately delete the message.  It deletes for my user account, but for all other accounts remains in the system.  If I reset Admin setting to 0 (disable (n) minutes), I can then delete again and it deletes for all users.

**Comment by geekgonecrazy** [comment] 2017-06-01 02:46
@adam-kulagowski @nORKy54 do you guys also have this setting enabled?

**Comment by nORKy54** [comment] 2017-06-01 07:30
@geekgonecrazy yes, I have a delay for deleting option

**Comment by adam-kulagowski** [comment] 2017-06-01 18:53
@geekgonecrazy We are also using this feature (time limited edit and delete)

**Comment by geekgonecrazy** [comment] 2017-06-02 05:02
@MartinSchoeler or @ggazzo either of you guys have an idea here? Possible regression from coffee to js?

**Comment by MartinSchoeler** [comment] 2017-06-09 14:23
@geekgonecrazy i think the problem is on [this](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/methods/deleteMessage.js#L13) query, it doesn’t ask for the original message time stamp that is needed later in [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/server/methods/deleteMessage.js#L38), thus causing a return without errors. Adding a `ts: 1` on the query fixed this for me

**Comment by geekgonecrazy** [comment] 2017-06-09 19:16
Makes sense! :+1:  Glad you were able to find it!

**Closed** 2017-06-27 17:04 UTC
Labels: feat: message, feat: roles / permissions, type: bug
