### ISSUE TITLE
Heroku one click script cant work

### ISSUE THREAD

**Issue by pty819** [RocketChat/Rocket.Chat#19562] opened 2020-11-16 18:46 UTC
### Description:
after click the one click heroku button:

Something went wrong:
The addon "mongolab" does not exist. Please ensure that the addon is spelled correctly.

### Steps to reproduce:

click the one-click heroku install button

### Expected behavior:

rocket chat can be installed well

### Actual behavior:

mongolab has been removed from heroku so the installation cant continue.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by chaim-chv** [comment] 2020-11-18 01:04
Duplicate of  #18855

**Closed** 2024-06-12 18:56 UTC
