### ISSUE TITLE
Close Livechat conversation (From Visitor) raise an error!

### ISSUE THREAD

**Issue by MIKNOTAURO** [RocketChat/Rocket.Chat#9673] opened 2018-02-10 14:14 UTC
### Description:
I'm getting an error when we try to close livechat room (client side) 
### Server Setup Information:
* Version of Rocket.Chat Server: 0.61.0
* Operating System: Linux Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): Fresh Build from tag 0.61.0
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: 8.9.3
### Steps to Reproduce:
Just start livechat and then try to close 
### Expected behavior:
Close conversation
### Actual behavior:
Nothing happens
### Relevant logs:
Exception while invoking method 'livechat:closeByVisitor' TypeError: Cannot read property '_id' of undefined
    at Object.closeRoom (/home/ubuntu/bundle/programs/server/packages/rocketchat_livechat.js:3882:15)
    at DDPCommon.MethodInvocation.livechat:closeByVisitor (/home/ubuntu/bundle/programs/server/packages/rocketchat_livechat.js:635:30)
    at DDPCommon.MethodInvocation.methodsMap.(anonymous function) (/home/ubuntu/bundle/programs/server/packages/rocketchat_lib.js:2134:26)
    at DDPCommon.MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
    at maybeAuditArgumentChecks (/home/ubuntu/bundle/programs/server/packages/ddp-server.js:1826:12)
    at DDP._CurrentMethodInvocation.withValue (/home/ubuntu/bundle/programs/server/packages/ddp-server.js:892:126)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at DDPServer._CurrentWriteFence.withValue (/home/ubuntu/bundle/programs/server/packages/ddp-server.js:892:98)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Promise (/home/ubuntu/bundle/programs/server/packages/ddp-server.js:892:46)
    at new Promise (<anonymous>:null:null)
    at Session.method (/home/ubuntu/bundle/programs/server/packages/ddp-server.js:865:23)
    at /home/ubuntu/bundle/programs/server/packages/ddp-server.js:744:85

**Comment by mrsimpson** [comment] 2018-02-13 18:48
@sampaiodiego may this have something to do with the separation of the livechat-users?
I can see a `user` being passed to `RocketChat.Livechat.closeRoom`. Where are the new livechat users actually managed?

**Comment by sampaiodiego** [comment] 2018-02-14 11:55
thanks guys for the information.. I'll close this as duplicate of #9558

**Closed by sampaiodiego** 2018-02-14 11:55 UTC
