### ISSUE TITLE
Deleted messages are not removed from the count of messages in a room.

### ISSUE THREAD

**Issue by Drexl** [RocketChat/Rocket.Chat#15509] opened 2019-10-04 18:18 UTC
I can't imagine this hasn't been discovered yet, but I couldn't find an issue about it so here goes...

### Description:

Deleted messages are not removed from the count of messages in a discussion. Potentially of note, this does not happen with threads.

### Steps to reproduce:

1. Start a discussion.
2. Send a few messages.
3. Delete a message.
4. Observe that the message count printed on the button in the parent channel does not decrement. 

### Expected behavior:

The button in the parent thread to a discussion should show the number of messages in the discussion sans deleted messages.

### Actual behavior:

The button erroneously includes deleted messages.

### Server Setup Information:
(copy/paste)

Rocket.Chat
Version	1.3.2
Apps Engine Version	1.5.2
Deployment ID	ynxA87PoxsduKuv8c
PID	1
Running Instances	1
OpLog	Enabled

**Comment by ggazzo** [comment] 2019-10-04 21:42
actually its not a discussion problem, its even worst. Any kind of room doesnt decrement their count messages, as a discussion room has the same behavior of the other rooms, you can see this problem.

look:
![image](https://user-images.githubusercontent.com/5263975/66241888-8c22ee00-e6d6-11e9-8d63-a3adfccdc9f0.png)


![image](https://user-images.githubusercontent.com/5263975/66241907-9644ec80-e6d6-11e9-8549-2b16543fb646.png)

**Comment by ggazzo** [comment] 2019-10-17 23:02
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/11323

**Closed by ggazzo** 2019-10-17 23:02 UTC
Labels: type: bug
