### ISSUE TITLE
Self-destructable messages

### ISSUE THREAD

**Issue by 9203948** [RocketChat/Rocket.Chat#1785] opened 2015-12-30 19:46 UTC
A feature to send text messages with a very short time, maybe 30 seconds or customized, would be grate. Once read, the messages automatically get erased from one’s phone and the server. For privacy reasons. Similar to https://www.cyberdust.com/.

**Comment by marceloschmidt** [comment] 2015-12-31 10:19
Duplicate of #1591

**Closed by marceloschmidt** 2015-12-31 10:19 UTC
