### ISSUE TITLE
[UI/UX] Scroll issue in sidebar

### ISSUE THREAD

**Issue by XshubhamX** [RocketChat/Rocket.Chat#28334] opened 2023-03-08 20:03 UTC
Description:
Once reaching the finish, scrolling the sidebar causes the sidebar to shake.. Below video will make more sense.

Steps to reproduce:

https://user-images.githubusercontent.com/63532716/223834416-3cc553d1-4f39-4bb6-ae64-b8874d8b8b8b.mov

1. Scroll through the sidebar until you get to the end.
2. After that, attempt to scroll; it will begin to shake.

Expected behaviour:

1. Sidebar should not shake.

Desktop App or Browser Version: Chrome

Operating System: macOS

Version - 5.4.3

**Comment by dudanogueira** [comment] 2023-03-09 11:32
Strange. I was not able to reproduce this on latest chrome on Linux =\

**Comment by AdityaSingh-02** [comment] 2023-03-09 14:19
i was also not able to reproduce it on 6.0.0-develop on ubuntu

**Comment by AdityaSingh-02** [comment] 2023-03-09 14:19
#28255 found similar issue

**Comment by hugocostadev** [comment] 2023-03-10 12:26
This was fixed in our [latest release 6.0.0](https://github.com/RocketChat/Rocket.Chat/pull/28345) most likely by this PR https://github.com/RocketChat/Rocket.Chat/pull/27571

**Closed by hugocostadev** 2023-03-10 12:26 UTC
