### ISSUE TITLE
Issue with deployment on Heroku.

### ISSUE THREAD

**Issue by shaileshpatel91** [RocketChat/Rocket.Chat#8838] opened 2017-11-10 11:44 UTC
Hi,

I pulled latest Rocket.Chat code and deploying on heroku but having the issue with livechat package.

### Server Setup Information:

* Version of Rocket.Chat Server: **0.59.3**
* Operating System: **Heroku**
* Deployment Method(snap/docker/tar/etc): **Heroku CLI**
* Number of Running Instances: **1**
* Node Version: **8.8.1**

### Steps to Reproduce:

1. Pull the latest code
2. Go to Heroku CLI. Create the app with buildpack: https://github.com/RocketChat/meteor-buildpack-horse.git
3. Push on heroku master

### Expected behavior:

It should deploy without any error.

### Actual behavior:

It is having build error.

### Relevant logs:
sh: 0: Can't open /tmp/build_f2ea275ef5751acb3133e88d7b58425b/packages/rocketchat-livechat/plugin/build.sh
remote: /app/tmp/cache/meteor/.meteor/packages/tap_i18n/.1.8.2.2c4fvl.9so0b++os+web.browser+web.cordova/plugin.tap-i18n-compiler.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
remote: throw error;
remote: ^
remote:
remote: Error: Builder can not write without either data or a file path or a symlink path: os/packages/rocketchat_livechat/public/head.html
remote: at Builder.write (/tools/isobuild/builder.js:258:13)
remote: at Builder.writeToGeneratedFilename (/tools/isobuild/builder.js:389:10)
remote: at /tools/isobuild/isopack.js:1392:21
remote: at Array.forEach ()
remote: at Function..each..forEach (/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
remote: at /tools/isobuild/isopack.js:1385:11
remote: at Array.forEach ()
remote: at Function..each..forEach (/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
remote: at Isopack.saveToPath (/tools/isobuild/isopack.js:1275:9)
remote: at /tools/isobuild/isopack-cache.js:380:23
remote: at /tools/utils/buildmessage.js:359:18
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:352:34
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:350:23
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at Object.enterJob (/tools/utils/buildmessage.js:324:26)
remote: at IsopackCache.loadLocalPackage (/tools/isobuild/isopack-cache.js:317:18)
remote: at Profile.time (/tools/isobuild/isopack-cache.js:251:16)
remote: at Function.time (/tools/tool-env/profile.js:305:10)
remote: at /tools/isobuild/isopack-cache.js:250:17
remote: at /tools/utils/buildmessage.js:359:18
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:352:34
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:350:23
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at Object.enterJob (/tools/utils/buildmessage.js:324:26)
remote: at IsopackCache.ensurePackageLoaded (/tools/isobuild/isopack-cache.js:241:20)
remote: at /tools/isobuild/isopack-cache.js:77:14
remote: at /tools/packaging/package-map.js:57:7
remote: at Function..each..forEach (/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
remote: at exports.PackageMap.eachPackage (/tools/packaging/package-map.js:49:7)
remote: at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:76:24)
remote: at /tools/project-context.js:847:25
remote: at /tools/utils/buildmessage.js:359:18
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:352:34
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:350:23
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at Object.enterJob (/tools/utils/buildmessage.js:324:26)
remote: at ProjectContext._buildLocalPackages (/tools/project-context.js:846:18)
remote: at /tools/project-context.js:285:9
remote: at /tools/utils/buildmessage.js:359:18
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:352:34
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:350:23
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at Object.enterJob (/tools/utils/buildmessage.js:324:26)
remote: at ProjectContext._completeStagesThrough (/tools/project-context.js:275:18)
remote: at Profile.run (/tools/project-context.js:267:12)
remote: at Function.run (/tools/tool-env/profile.js:490:12)
remote: at ProjectContext.prepareProjectForBuild (/tools/project-context.js:266:13)
remote: at /tools/cli/commands.js:928:20
remote: at /tools/utils/buildmessage.js:271:13
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:264:29
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:262:18
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at /tools/utils/buildmessage.js:253:23
remote: at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
remote: at Object.capture (/tools/utils/buildmessage.js:252:19)
remote: at Object.main.captureAndExit (/tools/cli/main.js:274:29)
remote: at buildCommand (/tools/cli/commands.js:927:8)
remote: at Command.func (/tools/cli/commands.js:876:12)
remote: at /tools/cli/main.js:1522:15
remote: ! Push rejected, failed to compile Node.js app.

**Comment by amonemian** [comment] 2017-11-13 14:18
I have the same problem. 
I found out that there exist another [issue ](https://github.com/RocketChat/Rocket.Chat/issues/7583)(for about 3 months ago) and the issue has not been solved yet.

**Comment by MartinSchoeler** [comment] 2017-11-13 15:38
Duplicate of #8640

**Closed by MartinSchoeler** 2017-11-13 15:38 UTC
