### ISSUE TITLE
Windows desktop app 3.3.0 extreme sluggishness

### ISSUE THREAD

**Issue by NathanAdored** [RocketChat/Rocket.Chat#22471] opened 2021-06-25 20:41 UTC
I have been having an issue for days where the desktop app on Win10 64 will not scroll in the chat in a timely manner, GUI elements don't respond, and the program otherwise behaves very, very sluggishly or not at all.  Other times, it seems to behave normally, but then eventually goes back to being sluggish and the GUI not responding.  I was forced to go back to 3.2.2 version for the time being.

**Comment by ankar84** [comment] 2021-06-26 09:39
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/2068
3.3.0 was revoked, don't use it, downgrade to 2.2.0

**Comment by johncrisp** [comment] 2021-06-28 10:06
Closing.

**Closed by johncrisp** 2021-06-28 10:06 UTC
