### ISSUE TITLE
users in role not updated

### ISSUE THREAD

**Issue by birkb** [RocketChat/Rocket.Chat#5898] opened 2017-02-03 12:12 UTC
Rocket.Chat Version: 0.50.1
Running Instances: 9
DB Replicaset OpLog: enabled
Node Version: 4.7.2

I have created a channel as admin and i want to configure a normal user as moderator for that channel. I go to /admin/permissions/moderator/edit, i choose the room name and i add the username. The UI responds with "User added", but the user does not appear in the list and he also not moderator of that channel.

**Comment by engelgabriel** [comment] 2017-02-03 13:52
Did you invite the user to the channel? Was the user already a member?

**Comment by birkb** [comment] 2017-02-03 14:15
No the user was not member of the channel. Even after adding the user to the channel it does not work.

**Comment by rodrigok** [comment] 2017-02-03 15:01
I did some investigation here.

The user was in the channel, I added the user as moderator as @birkb described and the user received the `moderator` badge correctly but the list below was not updated.

The problem is related with subscriptions and the changes we did with client cache. The client receives the subscriptions and users but our current subscription model is not related with `rocketchat_subscription` via `publications/subscriptions`

**Comment by birkb** [comment] 2017-02-03 15:15
You are right. After switching from compact to normal view mode i see the badges and the user has the moderator badge. This means the user has received the permissions, but is not listed in the permissions UI. Because of that i'm not able to revoke the permissions.

**Comment by rodrigok** [comment] 2017-02-03 16:43
@birkb Yeap. But, inside the room, you can click on the user's username to see more details and there exists a button to add/remove that user as moderator.

**Comment by birkb** [comment] 2017-02-03 18:06
@rodrigok Thank you for the clarification. This means the problem only affects the permissions UI.

**Comment by Jannibal** [comment] 2017-04-10 07:52
Is this related to #5446 ?

**Comment by mikt** [comment] 2017-05-05 11:19
Is there a work-around for this problem in the meantime? 
I have some custom roles assigned to some of my users, which does not require the role anymore, and I find myself unable to do anything about it.

**Comment by ggazzo** [comment] 2019-10-25 22:03
fixed

**Closed by ggazzo** 2019-10-25 22:03 UTC
Labels: feat: roles / permissions, subj: ui/ux, type: bug
