### ISSUE TITLE
logging with oauth destroys current account

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#2055] opened 2016-01-28 07:49 UTC
Step to reproduce:

- register with your email
- have some chats
- logout
- register with oauth (which contains the same email, in my case, I tried with GitHub)
- logout
- login with your email again: you can't the oauth registration just destroyed your previous account.

expected behaviour:
The oauth login should not create a new account but attach it to your current account (same email).

**Comment by marceloschmidt** [comment] 2016-02-01 18:42
I can confirm this is happening!

**Comment by sampaiodiego** [comment] 2016-02-29 20:11
just explaining: this was the expected behaviour because the first user have not confirmed their email address.. 

imagine if a unkown user register using your email address.. what would be the expected result when you (the real owner of that email address) log in?

@pierreozoux you'll get your _expected behaviour_ if you confirm the email address of the first registered user, ok?

**Comment by philipwhiuk** [comment] 2016-02-29 20:26
Is there a warning that this occurs @sampaiodiego ?

**Comment by sampaiodiego** [comment] 2016-02-29 20:31
@philipwhiuk no.. this is done silently..

**Comment by engelgabriel** [comment] 2016-02-29 21:04
I guess we should have a warning.

**Comment by rodrigok** [comment] 2016-02-29 23:14
@engelgabriel should we show this warning before or after the login?

**Comment by engelgabriel** [comment] 2016-03-01 00:11
I believe after.. would that be possible?

**Comment by rodrigok** [comment] 2016-03-01 14:14
Maybe we can set a flag inside the user's record to show this warning.

**Comment by marceloschmidt** [comment] 2016-03-04 13:13
This is how we plan on fixing it: when logging in via OAuth, if the e-mails already exists but is not verified, the accounts will be merged, the password of the existing account will be reset and the user will be requested to input a new password. If the e-mail was verified, account will be merged as usual.

**Comment by royalaid** [comment] 2016-03-04 19:10
Will this provide the option to merge the old account messages into the new account?

**Closed** 2016-03-04 19:38 UTC
Labels: feat: oauth / sso, type: bug
