### ISSUE TITLE
Unable to install with DOCKER

### ISSUE THREAD

**Issue by syrrro** [RocketChat/Rocket.Chat#26351] opened 2022-07-25 00:38 UTC
>+----------------------------------------------+
>|                SERVER RUNNING                |
>+----------------------------------------------+
>|                                              |
>|  Rocket.Chat Version: 5.0.0                  |
>|       NodeJS Version: 14.19.3 - x64          |
>|      MongoDB Version: 4.4.15                 |
>|       MongoDB Engine: wiredTiger             |
>|             Platform: linux                  |
>|         Process Port: 3000                   |
>|             Site URL: http://localhost:3000  |
>|     ReplicaSet OpLog: Enabled                |
>|          Commit Hash: 59cae12108             |
>|        Commit Branch: HEAD                   |
>|                                              |
>+----------------------------------------------+

![QQ截图20220725110208](https://user-images.githubusercontent.com/60288144/180689335-972fa753-5d65-406c-8ca6-44217a56c645.png)

**Comment by dudanogueira** [comment] 2022-07-25 11:36
Hi! Please, refer to our [Community Support Channel](https://open.rocket.chat/channel/support) or our [Forums](https://forums.rocket.chat/) for deployment support.

This is not a bug nor follow the issue template. closing.

**Closed by dudanogueira** 2022-07-25 11:36 UTC
