### ISSUE TITLE
Disappearing chats / Chats not being received

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#966] opened 2015-10-02 17:56 UTC
The following gif shows an error we're seeing where chats aren't being received if the window isn't in the front and an issue where chats are lost on page refresh.

The starting frame of the gif (since it's a little hard to tell) is the screen where the most recent chat is "testing again" by "MK". 

Next, the page is refreshed and a number of newer chats are now displaying, as they should have been before. The most recent chat is "new message" by "MK".

"MK" then types two messages, of the word "test". When the page is refreshed those chats are not visible anymore.

![disappearing](https://cloud.githubusercontent.com/assets/498744/10253731/f93e8c20-690c-11e5-89d5-99ad71f9d51c.gif)

This is the network panel in Firefox:

![screen shot 2015-10-02 at 1 46 05 pm](https://cloud.githubusercontent.com/assets/498744/10253800/67d89e28-690d-11e5-9333-ca4d33c25e5c.png)

**Comment by geekgonecrazy** [comment] 2015-10-03 20:47
Just as a note, I asked him to post the network panel as well.  

Basically we've seen several people have this issue, but usually we do a bit of inquiry and it turns out websockets aren't working.  Usually just simply getting websockets working for them has solved this problem. 

But here its happening with even websockets.  So we need to figure out what exactly is happening here.  Very small percentage of people see this.  But enough we for sure want to track it and try and reproduce.

**Comment by mhkeller** [comment] 2015-10-07 13:41
hi @marceloschmidt I noticed you added the `need more info` tag. I can be in the chat today if you have questions or if we're not online at the same time, I can answer them if posted here.

**Comment by marceloschmidt** [comment] 2015-10-07 16:37
Closing this for this is probably related to deployment settings and not a bug per se. If you think this should be reopened, please advise.

**Closed by marceloschmidt** 2015-10-07 16:37 UTC
Labels: subj: core, type: bug, type: need more info
