### ISSUE TITLE
Mark as Read button not showing even with unread messages

### ISSUE THREAD

**Issue by pcarn** [RocketChat/Rocket.Chat#2305] opened 2016-02-22 19:44 UTC
In one of my channels, I cannot get the unread notification to go away. The Mark as Read button should always be shown when the channel is unread.

Your Rocket.Chat version: 0.19.0

**Comment by engelgabriel** [comment] 2016-03-30 17:54
@pcarn can you check this with the latest version: 0.24.0 ?

**Comment by rodrigok** [comment] 2016-04-06 01:14
@pcarn can you test with the latest version: 0.25.0?

**Comment by pcarn** [comment] 2016-04-06 14:02
I'm not using rocketchat much anymore, so I haven't had a chance to.

**Comment by engelgabriel** [comment] 2016-04-06 14:52
Why have you not used more? :)

-- 
Sent from Mobile

**Comment by telmich** [comment] 2016-11-25 16:57
It seems this problem still exists

**Comment by Hudell** [comment] 2018-06-06 14:14
This doesn't seem to happen in normal situations for the current version, so I'll be closing this. If the problem is still present we will need more information about how to trigger it.

**Closed by Hudell** 2018-06-06 14:14 UTC
Labels: subj: ui/ux, type: bug
