### ISSUE TITLE
[Regression] login with resumeToken fails: FlowRouter.getQueryParam is undefined inside loginViaQuery.ts

### ISSUE THREAD

**Issue by m7913d** [RocketChat/Rocket.Chat#22098] opened 2021-05-20 23:58 UTC
### Description:

Trying to login a user using `https://yourown.rocket.chat/home?resumeToken=abcd123456789` fails due to `FlowRouter.getQueryParam('resumeToken');` returning `undefined` inside `loginViaQuery.ts`.

I think the regression is introduced in commit [d8a24b044](https://github.com/RocketChat/Rocket.Chat/commit/d8a24b044ebe0a5d93ab2dc1e16d101be6552146).

### Steps to reproduce:

1. Go to https://yourown.rocket.chat/home?resumeToken=abcd123456789

### Expected behavior:

User should be automatically logged in, or at least `FlowRouter.getQueryParam('resumeToken');` should not return undefined in `loginViaQuery.ts`.

### Actual behavior:

Normal login screen is presented. `FlowRouter.getQueryParam('resumeToken');` returns undefined inside `loginViaQuery.ts`.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14 and develop branch
- Operating System: Ubuntu 20.04
- Deployment Method: docker (latest, 3.14) and developer build (from git branch develop)

### Client Setup Information

- Desktop App or Browser Version: browser (firefox, chrome)
- Operating System: Ubuntu 20.04

## Possible solution:

`FlowRouter.getQueryParam('resumeToken');` returns undefined because `FlowRouter.wait();` is called, but `FlowRouter.initialize();` is not yet called when startup script of `loginViaQuery.ts` is executed (by Meteor.startup).

`FlowRouter.wait();` and `FlowRouter.initialize();` are called inside `client/startup/routes.ts`, which is now imported after `loginViaQuery.ts`. Previously `client/routes.ts` (old location of routes.ts file) was imported before `loginViaQuery.ts`.

So, changing the import order inside `client/startup/index.ts` to import `routes.ts` before `loginViaQuery.ts` resolves this issue:

    ....
    + import './routes';
    import './loginViaQuery';
    ...
    - import './routes';

However, I'm not familiar enough with Rocket.Chat to judge whether this would introduce another bug and the culprit, commit [d8a24b044](https://github.com/RocketChat/Rocket.Chat/commit/d8a24b044ebe0a5d93ab2dc1e16d101be6552146), does not explain well why this order is changed (the commit contains many changes).

**Comment by johncrisp** [comment] 2021-05-21 11:48
Thanks for reporting this.

We'll need someone to take a look at it.

**Comment by paulobernardoaf** [comment] 2021-06-01 19:31
I'm also facing this issue. 
Any news for a solution?

**Comment by m7913d** [comment] 2021-06-01 21:29
@paulobernardoaf if you are able to patch it yourself, you can apply the fix mentioned under possible solution.

**Comment by pythoneer** [comment] 2021-06-02 06:38
To what version of Rocket.Chat do i need to rollback before this regression was introduced? The mentioned commit is tagged with `3.15.0xx` and `3.14.xx` so i think its safe to assume its version `3.13.x` ?

**Comment by m7913d** [comment] 2021-06-02 12:55
> To what version of Rocket.Chat do i need to rollback before this regression was introduced? The mentioned commit is tagged with `3.15.0xx` and `3.14.xx` so i think its safe to assume its version `3.13.x` ?

Indeed 3.14.0 seems to be the first affected release.

**Comment by PSFILM** [comment] 2021-06-07 14:59
We attempted to revert back to 3.14.5 and the db is not compatible. what is the time frame for the fix for 3.15?

and ERROR! SERVER STOPPED                        |
Jun  7 01:08:33 cs3621 rocketchatnew: |                                                                      |
Jun  7 01:08:33 cs3621 rocketchatnew: |              Your database migration control is locked.              |
Jun  7 01:08:33 cs3621 rocketchatnew: |  Please make sure you are running the latest version and try again.  |
Jun  7 01:08:33 cs3621 rocketchatnew: |           If the problem persists, please contact support.           |
Jun  7 01:08:33 cs3621 rocketchatnew: |                                                                      |
Jun  7 01:08:33 cs3621 rocketchatnew: |                   This Rocket.Chat version: 3.14.5                   |
Jun  7 01:08:33 cs3621 rocketchatnew: |                    Database locked at version: 225                   |
Jun  7 01:08:33 cs3621 rocketchatnew: |                     Database target version: 222                     |
Jun  7 01:08:33 cs3621 rocketchatnew: |                                                                      |
Jun  7 01:08:33 cs3621 rocketchatnew: |           Commit: 07b29666c7ade013802381453e004cd6b8e059af           |
Jun  7 01:08:33 cs3621 rocketchatnew: |                  Date: Sun Jun 6 21:59:01 2021 -0300                 |
Jun  7 01:08:33 cs3621 rocketchatnew: |                             Branch: HEAD                             |
Jun  7 01:08:33 cs3621 rocketchatnew: |                              Tag: 3.14.5

**Comment by pythoneer** [comment] 2021-06-07 15:42
@PSFILM what was the latest version you had migrated to before trying to revert back? Where you already on the 3.15 release? Unfortunately it looks like the issue was introduced on the early 3.15.0 release, so there is no 3.15 release without that error. Would be really helpful to know if there is a way to migrate back from 3.15 to earlier versions because this bricks installations.

**Comment by PSFILM** [comment] 2021-06-07 15:50
@pythoneer we are at 3.15 and can't revert the new 3.15 DB to an earlier version. We can restore from a backup but will lose 2 day of data

**Comment by m7913d** [comment] 2021-06-07 21:57
@PSFILM You can also try to patch your current installation. I don't know which deployment method you use, but try to find import './loginViaQuery' in your deployment files and reorder the import statements as done in my PR. I'm not sure whether a restart is needed.

**Comment by PSFILM** [comment] 2021-06-09 18:46
@m7913d we added the client/startup/index.ts in the corrected order and had success login via ios and android. But, it created another issue of our desktop  app and windows web version to fail

**Comment by m7913d** [comment] 2021-06-09 19:04
@PSFILM What kind of issue did you encounter?

**Comment by PSFILM** [comment] 2021-06-09 21:09
@m7913d after building the routes.ts  as mentioned above. The developer guide is for Linux and tested with Ubuntu 18.04 and doesn't seem to work with  CentOS.  After applying the fix-it resolved our mobile app issue but, created an issue with our windows desktop app and web application. We had to revert back

**Comment by m7913d** [comment] 2021-06-09 21:11
Could you elaborate on the issue with your desktop/web client you encounter after applying the fix?

**Comment by m7913d** [comment] 2021-06-09 21:15
@johncrisp Do you know when this regression will be fixed or when my provided PR will be evaluated?

**Comment by PSFILM** [comment] 2021-06-09 21:20
@m7913d I   I have forwarded a request for additional  details from our team - will elaborate when they respond 
@m7913d we welcome and will pay for any direct help you could provide, We want this fixed without having to restore it from backups

View Ticket #291310 
Subject: Update Rockletchat to Last Release: 3.15.0 [MERGED]

Posted by Gary  on 06/09/2021 (17:13)Owner
Could you elaborate on the issue with your desktop/web client you encounter after applying the fix? The developers are inquiring so they can figure out the fix.

Posted by Nikita  on 06/09/2021 (10:26)Operator
Hello Gary,

"I was able to build and start the version with the updated index.ts file.

However, it looks like those changes are not the only thing required to make Rocket.Chat work properly because, even though the new version allowed me to log in on Android, login stopped working on my PC with Windows 10 so I've reverted the installation to the regular version 3.15.0.

It is not reliable to build such complicated applications on our end as we are not familiar with the code well enough to completely understand the consequences of the changes we make.

As Sergey mentioned before, we have 2 options right now:

Keep everything as is and wait until developers fix the issue on their end and release a proper version 3.15.1.
Revert the installation to version 3.14.4 and revert the database to the backup created on Sunday (all the data added after Sunday will be lost in the process, though).
Please, let us know which option is preferred".

**Comment by m7913d** [comment] 2021-06-09 21:32
@PSFILM I doubt this error will be fixed by reverting to 3.14.4, as this error seems to be introduced in 3.14.0.

**Comment by PSFILM** [comment] 2021-06-13 17:48
@m7913d have you had any updates on this issue?

**Comment by m7913d** [comment] 2021-06-13 17:54
@PSFILM No, I have not received any update from you nor from the Rocket.Chat team. Have you received more information from your team about the issue you encounter when applying my proposed fix #22253?

**Closed** 2021-06-17 20:59 UTC
Labels: stat: triaged, type: bug
