### ISSUE TITLE
Server error when i will sending selected messages by email

### ISSUE THREAD

**Issue by athossouza** [RocketChat/Rocket.Chat#6402] opened 2017-03-20 21:21 UTC
Hi
Server error when i will sending selected messages by email, but when I will test the smtp it work normally, I did this video for better explanation.

![sending mail error rocket chat](https://cloud.githubusercontent.com/assets/16904054/24122990/a54b7fa2-0d9c-11e7-9af8-e7bf0a442d98.gif)

[See Vídeo](https://youtu.be/36uNfyuceVA)

[Sending mail error Rocket Chat.zip](https://github.com/RocketChat/Rocket.Chat/files/856387/Sending.mail.error.Rocket.Chat.zip)

![image](https://cloud.githubusercontent.com/assets/16904054/24122045/34b1f576-0d99-11e7-96b7-acc938f040bb.png)

**Comment by pkgodara** [comment] 2017-03-21 07:27
Mine is working fine. I'm not able to reproduce this. Are you using docker? What does console output?

**Comment by athossouza** [comment] 2017-03-21 11:50
I use this command `snap install rocketchat-server` when I installed, this information is relevant for you?

**Comment by athossouza** [comment] 2017-04-20 15:43
Now I'm using the 0.55.1 version and also not work this

**Comment by athossouza** [comment] 2017-05-05 01:06
This problem happen with someone more?

**Comment by localguru** [comment] 2017-05-30 08:21
Same here with 0.56.0. Sending email e.g. for offline notifications works fine.

```
May 30 10:11:33 server rocketchat[31233]: Sending messages to e-mails:  [ 'myemailaddress@mydomain.de' ]
May 30 10:11:33 server rocketchat[31233]: Exception while invoking method 'mailMessages' TypeError: Cannot read property 'defineLocale' of undefined
May 30 10:11:33 server rocketchat[31233]:   at eval (<anonymous>:30:20)
May 30 10:11:33 server rocketchat[31233]:   at format.m (<anonymous>:12:4)
May 30 10:11:33 server rocketchat[31233]:   at eval (<anonymous>:13:2)
May 30 10:11:33 server rocketchat[31233]:   at [object Object].Meteor.methods.mailMessages (/var/www/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_channel-settings-mail-messages.js:125:23)
May 30 10:11:33 server rocketchat[31233]:   at [object Object].methodsMap.(anonymous function) (/var/www/rocketchat/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1021:26)
May 30 10:11:33 server rocketchat[31233]:   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
May 30 10:11:33 server rocketchat[31233]:   at maybeAuditArgumentChecks (/var/www/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:1823:12)
May 30 10:11:33 server rocketchat[31233]:   at /var/www/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:905:20
May 30 10:11:33 server rocketchat[31233]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
May 30 10:11:33 server rocketchat[31233]:   at /var/www/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:904:41
May 30 10:11:33 server rocketchat[31233]:   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
May 30 10:11:33 server rocketchat[31233]:   at /var/www/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:903:46
May 30 10:11:33 server rocketchat[31233]:   at [object Object]._.extend.protocol_handlers.method (/var/www/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:876:21)
May 30 10:11:33 server rocketchat[31233]:   at /var/www/rocketchat/Rocket.Chat/programs/server/packages/ddp-server.js:755:85
```

**Comment by localguru** [comment] 2017-05-30 08:39
seems to be the same error like in #6611

**Comment by rasos** [comment] 2017-06-15 08:27
Problem only occurs when language is set to non-EN. 
Patch has been submitted, waiting for accepting pull request.

**Comment by sampaiodiego** [comment] 2017-07-03 14:03
@athossouza do you still have this issue?

**Comment by sampaiodiego** [comment] 2017-07-03 14:20
thanks for the info guys.. looks this is a duplicate of #5797 .. also there is an open pull request aiming to fix it already (#7245)

**Closed by sampaiodiego** 2017-07-03 14:20 UTC
Labels: feat: email, type: bug

**Comment by athossouza** [comment] 2017-07-03 15:36
@sampaiodiego great, when I change language to English this work
Now it work with any language?

**Comment by sampaiodiego** [comment] 2017-07-03 16:03
not yet.. please follow #7245
