### ISSUE TITLE
Android official app no notification sound

### ISSUE THREAD

**Issue by Jafar412** [RocketChat/Rocket.Chat#22445] opened 2021-06-22 15:52 UTC
I noticed there are an issue when receiving notifications on android app , there is no sound tested on multiple devices same result , is there any option I'm missing ?

Thanks

**Comment by ankar84** [comment] 2021-06-23 07:11
Hi and thanks for reporting this.

Can you please use a bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines:

https://rocket.chat/docs/contributing/reporting-issues

That includes testing on the latest version of Rocket.Chat - you can test on open.rocket.chat in the sandbox channel.

Note also that for general questions and help you are better off asking in https://forums.rocket.chat or https://open.rocket.chat #support as github is reserved for bugs.

I believe that right repo for your issue is https://github.com/RocketChat/Rocket.Chat.ReactNative/issues

And I guess there is no any sound files implemented in application itself, you just can set any sound you want in Android system properties of RCRN application. I did so and it works perfect.

**Comment by Jafar412** [comment] 2021-06-23 08:36
Found it later alter many tries , therr is a hidden settings where
notification by default sound is none , changed it to default and now there
is a sound , this is really not practical thing

**Comment by johncrisp** [comment] 2021-06-23 11:38
Thanks for reporting this.

Closing not a bug.

**Closed by johncrisp** 2021-06-23 11:38 UTC
