### ISSUE TITLE
Channel deletion leads to empty page

### ISSUE THREAD

**Issue by paulchen** [RocketChat/Rocket.Chat#27833] opened 2023-01-24 20:20 UTC
### Description:

When deleting a channel, the url in the browser's address bar changes to `<host>/home`, but an empty page is shown.

### Steps to reproduce:

1. Navigate to a channel that you want to delete.
2. Click on the "i" symbol to show the channel information.
3. Click "Delete" and confirm.

### Expected behavior:

The channel is deleted and the user is taken to the home page of the Rocket.Chat instance.

### Actual behavior:

The channel is deleted, the browser's address bar changes to `<host>/home`, but an empty page is shown. To continue using Rocket.Chat, the page must be reloaded.

https://user-images.githubusercontent.com/404840/214399234-5eb5439b-1552-4bbc-9cb4-f993e1655fa1.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1
- Deployment Method: Docker
- Number of Running Instances: 1
- MongoDB Version: 5.0.14

### Relevant logs:

The browser console shows a bunch of errors as soon as the issue happens:

```
TypeError: Cannot read properties of undefined (reading 't')
    at I (RoomInfoWithData.js:1:15055)
    at Pi (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:59696)
    at bc (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:69176)
    at Rs (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:112577)
    at nu (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:98840)
    at ru (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:98768)
    at eu (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:98631)
    at Gs (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:95485)
    at a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:45604
    at t.unstable_runWithPriority (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1175:3778)
Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at r.e [as render] (react-error-boundary.umd.js:1:1763)
    at hc (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:72209)
    at gc (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:72008)
    at Rs (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:112659)
    at nu (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:98840)
    at ru (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:98768)
    at eu (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:98631)
    at Gs (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:95485)
    at a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:45604
    at t.unstable_runWithPriority (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1175:3778)
Uncaught Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at r.e [as render] (react-error-boundary.umd.js:1:1763)
    at hc (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:72209)
    at gc (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:72008)
    at Rs (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:112659)
    at nu (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:98840)
    at ru (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:98768)
    at eu (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:98631)
    at Gs (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:95485)
    at a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1139:45604
    at t.unstable_runWithPriority (a86fdcee20cb2c4da8e5ac8c08c3c5f8b6199d9f.js?meteor_js_resource=true:1175:3778)
```

![image](https://user-images.githubusercontent.com/404840/214399835-5d305551-34ca-4c41-af03-30f6cc4173b6.png)

**Comment by dudanogueira** [comment] 2023-01-26 17:41
Hi! Thanks for this issue.

I was not able to reproduce this on latest 6.0.0-develop.

**Comment by paulchen** [comment] 2023-01-26 21:39
> I was not able to reproduce this on latest 6.0.0-develop.

I just checked it using the latest `develop` image from Docker Hub (f17427a50dcd). I'm afraid the issue occurs with that version as well.

The steps for reproducing the image are:

1. Pull the latest image of MongoDB 5.0.14: `docker pull mongo:5.0.14`
2. Pull the latest image of Rocketchat 6.0.0-develop: `docker pull rocketchat:develop`
3. Start up MongoDB: `docker run --name mongo_test mongo:5.0.14 mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger`
4. Set up the MongoDB replica set: `docker exec -it mongo_test mongo localhost/rocketchat --eval "rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'localhost:27017' } ]})"`
5. Fire up Rocket.Chat: `docker run --name rocketchat_test -e MONGO_OPLOG_URL=mongodb://mongo:27017/local?directConnection=true -e MONGO_URL=mongodb://mongo:27017/rocketchat?directConnection=true --link mongo_test:mongo -p 127.0.0.1:3000:3000 rocketchat/rocket.chat:develop`
6. Point the browser to http://localhost:3000
7. Set up the admin account, configure the community details and configure the Rocket.Chat instance as a stand-alone instance.
8. Create a new channel named #test.
9. Navigate to the channel #test.
10. Click on the "i" symbol to show the channel information.
11. Click "Delete" and confirm.

**Comment by paulchen** [comment] 2023-03-10 16:55
> > I was not able to reproduce this on latest 6.0.0-develop.
> 
> I just checked it using the latest `develop` image from Docker Hub (`f17427a50dcd`). This image reports as version `6.0.0-develop` upon startup:

... and in Rocket.Chat 6.0.0 (also deployed via Docker) this problem is still present as well.

**Comment by shevchukma** [comment] 2023-04-06 13:52
We have this problem reproduced on three different installations with versions 6.1.0, 5.4.5 and 6.1.1.
Everywhere a multi-instance monolith launched via docker.
Please help me find and fix the issue.

**Comment by hugocostadev** [comment] 2023-04-11 10:24
Fixed by: https://github.com/RocketChat/Rocket.Chat/pull/28554

**Closed by hugocostadev** 2023-04-11 10:24 UTC
Labels: type: bug, stat: can't reproduce
