### ISSUE TITLE
No Avatars appearing

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#928] opened 2015-09-29 09:21 UTC
Running Rocket.chat via docker-compose works great with the exception of no avatars. I have tired the fixes purposed on https://github.com/RocketChat/Rocket.Chat/issues/916 which do not appear to fix the issue.

Example:
<img width="260" alt="screenshot 2015-09-29 02 21 06" src="https://cloud.githubusercontent.com/assets/2439803/10160190/d27c91ae-6650-11e5-94e1-a1f262314bc9.png">

**Comment by marceloschmidt** [comment] 2015-09-29 12:06
Duplicate of #916

**Closed by marceloschmidt** 2015-09-29 12:06 UTC
