### ISSUE TITLE
Chat does not parse whole URL with special characters ("ü")

### ISSUE THREAD

**Issue by lambdabundesverband** [RocketChat/Rocket.Chat#26736] opened 2022-08-30 11:06 UTC
### Description:

An URL with special character **ü** is not parsed correctly in chat, but cut.

### Steps to reproduce:

1. Go to any conversation
2. paste a link with the letter "ü", e.g. `https://yopad.eu/p/nütesturl-365days`

### Expected behavior:

to parse the whole URL

### Actual behavior:

cuts the URL at letter "ü" and parses only the part `https://yopad.eu/p/n`

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.4 
- Operating System: Debian 11
- Deployment Method: Yunohost
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: v14.20.0
- MongoDB Version:5.0.9

### Client Setup Information

- Desktop App or Browser Version: Chrome Version 104.0.5112.101
- Operating System: Linux

**Comment by xmedeko** [comment] 2022-08-30 15:20
Probably duplicate to #26661, #26405, #26648, #26475, #26485, #26555, #23020, #26624

So many complaints from 5.0.0 release and still no fix.

**Comment by dudanogueira** [comment] 2022-08-31 17:40
Hi @xmedeko Thanks for pointing it and collecting all them here :speak_no_evil: 

We are indeed doing a lot of changes in message parsing, as discussed here:
https://www.youtube.com/watch?v=zhPF9LpTR94

While you can still use the old parser, we are moving fast to deliver a better parser.

I would also like to invite anyone interested on feeding us back in our [Beta Testers Channel](https://open.rocket.chat/channel/beta-testers)

**Comment by xmedeko** [comment] 2022-08-31 18:31
@dudanogueira First of all, I am afraid I have not collected them all, I've done just a quick scan of the issues. 

How can I use the old parser? Do you mean Marked vs. Original parser setting? I've tried the Original, but have not seen improvement (have not restarted the server, though). 

Also note, when we start thread, a then the URLs are rendered **OK in the thread only**, as in the 4.x version.  (Even messages from the main chat are OK in a thread). So, it seems to me you can just use the same parser/renderer from thread in the main channel (or elsewhere).

Or, please 🙏   , return back 4.x markdown parser/renderer to the 5.0 and release the new message parsing when it will be ready (you have a good collection of testcases in these issues 😉  .)

**Comment by dudanogueira** [comment] 2022-09-01 20:23
Yeah. We hear you!

Hopefully we will fix this soon.

Thanks again :)

**Comment by chotaire** [comment] 2022-09-02 11:14
Releasing this buggy, untested mess in a major stable version was a catastrophic idea.

It is beyond me how this could possibly have passed QA, as if nobody had invested 5 minutes for testing. Sending a simple image link in chat would already have proven that there is something really, really broken to a point it should never end up as default in a stable version. And this is not a bug that slipped in, it was a rewrite of the entire parser so why was it not tested before releasing it as a major version?

@dudanogueira "You can simply use the old parser" as a reply in a github issue is not the stategy to go. You haven't even mentioned how to do it. You guys are losing an enormous amount of trust in updating your software. In this current catastrophic state the only common sense action to be taken is to release an update that reverts to the old parser by default, leaving the new parser as an option. As soon as possible! A stable major version is NOT a buggy feature beta-test, this is not how any open source software should be released.

@xmedeko Obviously the only way to revert to the old behavior is by going to Settings, Account, Default User Preferences and [x] Use legacy message template.

**Comment by xmedeko** [comment] 2022-09-02 12:29
@chotaire Thanks, you have save my day. Just seems to me Settings > Default User Preferences are for new users only. Existing users must set their own My Account > Preferences > Global > Use legacy message template.

**Comment by chotaire** [comment] 2022-09-02 12:46
@xmedeko That is what you think it would be, because that is what a default user preference is for. But no, it also works for any existing user that haven't changed their default settings, in this case "Use legacy message template". So it still works.

**Comment by xmedeko** [comment] 2022-09-02 13:24
@chotaire Yes, I've told that to the users 😁  , since the Settings ... > Use legacy message template has not worked for me (maybe I've been playing with My Account setting earlier.) (But it's not so important for me, we are a small company, so I can talk to each user easily when necessary.) Thanks for the valuable details.

**Comment by chotaire** [comment] 2022-09-02 13:57
@xmedeko I had to CTRL+SHIFT+R to hard-reload the webpage for the old message parser layout to be displayed, did you try that? ;)

**Comment by xmedeko** [comment] 2022-09-02 14:16
@chotaire Nope, I have not tried. You are right, that could be the issue with the changed Settings.

**Comment by urosino** [comment] 2022-09-03 14:12
If all the messaging options from GitHub were integrated into the chat platform, it would be beyond my expectations.

**Comment by chotaire** [comment] 2022-09-03 18:37
⚠️ Careful everyone! If you update to 5.1.0, the legacy message parser is no longer available. All channels will be empty unless you revert the setting to use the new parser again.

Imagine forcing the user to a new parser that is still a buggy mess and the best idea to come up with for the next big version is to actually remove the old parser that saved people's butts. Good job! At least there is new spam on the homepage which can only be removed when upgrading to Enterprise, looks like that was more important to work on.

Sorry to say, but I think I lost trust into the project management of Rocket.Chat for good.

**Comment by xmedeko** [comment] 2022-09-04 17:41
@chotaire I've reported that in #26801

**Comment by engelgabriel** [comment] 2022-09-09 13:54
> ⚠️ Careful everyone! If you update to 5.1.0, the legacy message parser is no longer available. All channels will be empty unless you revert the setting to use the new parser again.
> 
> Imagine forcing the user to a new parser that is still a buggy mess and the best idea to come up with for the next big version is to actually remove the old parser that saved people after updating!

This have been fixed on 5.1.1

**Comment by chotaire** [comment] 2022-09-09 16:46
Thanks for the progress and I apologize for the harsh wording, it usually takes a while until I get so "candid".

**Comment by hugocostadev** [comment] 2022-09-28 11:22
Fixed on [Release 5.1.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/5.1.0) But I recommend keeping the product updated with the last stable release.

**Closed by hugocostadev** 2022-09-28 11:22 UTC
Labels: subj: ui/ux, subj: message rendering
