### ISSUE TITLE
Ability to set scope in Custom OAuth module

### ISSUE THREAD

**Issue by howellsd** [RocketChat/Rocket.Chat#3623] opened 2016-06-24 14:46 UTC
Your Rocket.Chat version: 0.30.0

The custom oauth module allows for setting a lot of parameters to supporting using oauth providers that it doesn't currently have dedicated modules for (i.e. github, google, facebook) but it doesn't allow the user to set the scope. Its a problem in particular when using Oracle Access Manager (OAM) as the provider, which has a unique scope definition (i.e. scope=User.me User.Profile). Need the ability to set it as another configuration parameter.

**Comment by geekgonecrazy** [comment] 2016-06-25 20:00
Dupe of #3429

**Closed by geekgonecrazy** 2016-06-25 20:00 UTC
