### ISSUE TITLE
Sometimes RC runs very slow, maybe while LDAP syncing

### ISSUE THREAD

**Issue by willihelm** [RocketChat/Rocket.Chat#6949] opened 2017-05-11 14:42 UTC
Rocket.Chat Version: 0.55.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.5.0
Somtimes RC is very slow and nearly unusable. I think it occures when it is syncing with the LDAP server.

**Comment by geekgonecrazy** [comment] 2017-05-11 19:54
related to and maybe duplicate of: #6930

**Comment by TwizzyDizzy** [comment] 2018-03-21 23:08
@rocket-cat close

Closing this, as the above is not enough information to even try replicating this. Please have a look at https://github.com/RocketChat/Rocket.Chat/issues/6930 for a way to approach this. If you come up with additional information (and have tested whether there is still an issue on the latest stable version of Rocket.Chat) I'll happily reopen.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-03-21 23:08 UTC
