### ISSUE TITLE
[BUG] Photos in gallery not visible 

### ISSUE THREAD

**Issue by kulkarnigaurav38** [RocketChat/Rocket.Chat#23702] opened 2021-11-12 15:16 UTC
### Description:

 On clicking the files toolbar icon, after selecting any picture, the website stops functioning and needs to be reloaded. The issue according to the console.logs is about the photoswipe.js library failing to build.

### Steps to reproduce:

1.  Upload a few pngs and click on the files icon in the room navigation at the top.
2.  In the list below select any picture and the photos are not visible and user cannot click anything else.

### Expected behavior:
All the photos should be visible in a gallery view with left and right arrow to toggle between them.

### Actual behavior:

https://user-images.githubusercontent.com/59637086/141489186-d38aab3b-e1a5-4927-b061-2806c9919d55.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.0-develop
- Operating System: Linux (WSL2 on Windows)
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1 -x64
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version: Chrome latest (95.0.4638.69)
- Operating System: Windows 10 version 21H1

### Relevant logs:
Logs from BROWSER:
![image](https://user-images.githubusercontent.com/59637086/141489885-a4fc94dc-41a7-47e8-9816-2878f824aadc.png)

**Comment by dudanogueira** [comment] 2021-11-12 17:32
I can confirm this bug.

**Comment by kulkarnigaurav38** [comment] 2021-11-12 17:43
In the npm website, it shows that photoswipe.js library itself is failing to build
[Link to its npm page](https://www.npmjs.com/package/photoswipe).

**Comment by aadarsh-kumar-tiwari** [comment] 2022-02-21 08:26
As I see the reference above, the issue is resolved, @kulkarnigaurav38  can you close this issue.

**Closed** 2022-02-22 03:47 UTC
Labels: subj: ui/ux, bug
