### ISSUE TITLE
Adding Oauth and registering a user with an email that already exsists hijacks that user

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#2424] opened 2016-03-03 23:04 UTC
Your Rocket.Chat version: 0.20
I recently enabled oauth and wanted to link my google login to RC, it turns out that registering with Oauth seems to have made my only admin account unaccessable because using a login with a correct password does not login and resetting the password via email only resets the new regular user account.

**Comment by engelgabriel** [comment] 2016-03-03 23:08
Can you look ad the users collection and check if there is 1 or 2 users?

**Comment by royalaid** [comment] 2016-03-03 23:35
It appears when searching via sending a DM that there is only the new user. Is there another way to search?

**Comment by engelgabriel** [comment] 2016-03-03 23:48
If the ADMIN user did not verify his email, yes, the new user will have deleted the previews one. This is the expected behaviour, but we should give a confirmation button first.

https://github.com/RocketChat/Rocket.Chat/issues/2055

**Comment by engelgabriel** [comment] 2016-03-03 23:49
If you restart your RC server.. the oldest user will me made admin in case you dont have any other admins.

**Comment by royalaid** [comment] 2016-03-03 23:49
Is there a way to merge users?

**Comment by engelgabriel** [comment] 2016-03-03 23:51
Not manually, but if a user has a verified email, and logs in using oAuth with the same verified email, they will be merged.

**Comment by royalaid** [comment] 2016-03-03 23:52
Okay, I think my admin account never had a verified email so I am guess that account is just kinda stuck in limbo until/if user merging is made?

**Comment by engelgabriel** [comment] 2016-03-03 23:54
The old account was deleted.

**Comment by royalaid** [comment] 2016-03-04 00:03
:cry: Okay, I am guessing there isn't a way to unify the messages by that user and this new one then similar to the request in #2311?

**Comment by engelgabriel** [comment] 2016-03-04 00:07
Let me do some teste. @marceloschmidt do we really delete the original user or do we just remove the email form that account?

**Comment by marceloschmidt** [comment] 2016-03-04 12:11
Duplicate of #2055

**Closed by marceloschmidt** 2016-03-04 12:11 UTC

**Comment by marceloschmidt** [comment] 2016-03-04 13:06
Yes, the account is deleted. I'm working on it right now, please follow up on issue #2055
