### ISSUE TITLE
Unify GraphQL API endpoint to application port

### ISSUE THREAD

**Issue by frdmn** [RocketChat/Rocket.Chat#13431] opened 2019-02-11 07:29 UTC
At the moment our GraphQL API listens on a separate port (`3100` by default) which in turn (usually) has to be separately proxied to be available from the outside.

Especially for our Cloud environment it's important to have the GraphQL API listen on the regular Rocket.Chat application port, to be easily available for every customer.

/cc @geekgonecrazy

**Comment by MarcosSpessatto** [comment] 2019-02-12 16:44
@frdmn Currently the GraphQL server runs on the same port of RocketChat application, what runs separated is the subscriptions port(which is even configurable in the admin panel) :thinking: Do you think that we should change this behavior?

**Comment by geekgonecrazy** [comment] 2019-02-12 20:47
@MarcosSpessatto can it be set to 3000 and actually work?  The issue is that's another port some how have to be able to proxy through an LB.  

I mean either way its single threaded so do we get any real benefit from another port?

**Comment by MarcosSpessatto** [comment] 2019-02-14 19:00
Actually it is not possible to run on the same server port because it causes some inconsistencies in the DDP causing it to not works correctly.

**Comment by MarcosSpessatto** [comment] 2019-03-28 14:02
@geekgonecrazy can we close this issue?

**Comment by geekgonecrazy** [comment] 2019-03-28 16:52
If it’s a can’t fix sort of deal I guess so

**Closed by geekgonecrazy** 2019-03-28 16:52 UTC

**Comment by engelgabriel** [comment] 2019-07-11 19:17
https://github.com/RocketChat/Rocket.Chat/issues/14959
