### ISSUE TITLE
Rocket.Chat after restart sends all old push notifications

### ISSUE THREAD

**Issue by phidlipus** [RocketChat/Rocket.Chat#11813] opened 2018-08-17 07:46 UTC
### Description:

When I restarted Rocket.Chat server, all old (already sent) push notifications were send again to all mobile devices (ios and android).

### Steps to reproduce:

Enable push notificationsRestart the Rocket.Chat server. Regular restart or restart when upgrade the server application.

### Expected behavior:

Rocket.Chat shouldn't send old push notifications after server restart.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.65.1
- Operating System: Debian Stretch, 64bit, kernel 4.4.112
- Deployment Method: manual installation from downloaded tar
- Number of Running Instances: 1
- DB Replicaset Oplog: disabled
- NodeJS Version: 8.9.4
- MongoDB Version: 3.6.6

**Comment by graywolf336** [comment] 2018-08-24 15:37
@sampaiodiego has this been fixed in the latest release candidate?

**Comment by sampaiodiego** [comment] 2018-08-24 16:45
kind of.. the issue that prevented push notifications from being sent at the right time was fixed.

we'll keep sending old push notifications if any other problem happen though. which I don't think is bad at all. maybe we should not send **too** old, like more than a day.

**Comment by reetp** [comment] 2018-10-16 10:50
@rocket-cat label add enhancement

This is a duplicate of #3359 Closed that in favour of this.

Any developer input ?

**Comment by geekgonecrazy** [comment] 2018-12-01 08:18
Going to go ahead and close this.  Should no longer be getting stuck.  Probably ok that it keeps trying to send pushes that it hasn’t got confirmation on delivery 👍

**Closed by geekgonecrazy** 2018-12-01 08:18 UTC
Labels: enhancement
