### ISSUE TITLE
Update non installable

### ISSUE THREAD

**Issue by edouarddiep** [RocketChat/Rocket.Chat#22383] opened 2021-06-17 05:58 UTC
Rocket.Chat keeps noticing me about a new update ready for download and installation. When I click on "download and install" button, RC shows a dialog window that mention : "when ready, the update will start installation.". Unfortunately, nothing happens and the update never occur. In addition, the direct messages don't show up directly and I have to restart RC frequently to make it work... This is kinda annoying.

**Comment by ankar84** [comment] 2021-06-17 07:55
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670

**Comment by johncrisp** [comment] 2021-06-17 08:45
Closing as duplicate

**Closed by johncrisp** 2021-06-17 08:45 UTC
