### ISSUE TITLE
REST API does not have a way to access messages in unjoined private channels

### ISSUE THREAD

**Issue by cloudsandladders** [RocketChat/Rocket.Chat#10752] opened 2018-05-13 02:31 UTC
### Description:

There is no way to access and delete messages in unjoined private channels via REST API, but with permissions like 'View Private Room' and 'View History' or some combination of admin permissions should allow this.

There already is a way to get messages from direct messages that the user is not a part of via the REST API setting 'Enable Direct Message History Endpoint' being set to true and using the REST API '/api/v1/im.messages.others'  Maybe add something similar to all private messages or the ability to access private channel history with certain permissions.

### Server Setup Information:
* Version of Rocket.Chat Server:  0.63.3
* Operating System: Ubuntu 16.04.4 x64
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.4
* mongoDB Version: 3.2.7
* StorageType: FileSystem

**Comment by graywolf336** [comment] 2018-05-13 16:29
Closing as this is working as intended. Private rooms are private for a reason.

@RocketChat/core feel free to open again if this aligns with anything on the roadmap.

**Closed by graywolf336** 2018-05-13 16:29 UTC

**Comment by cloudsandladders** [comment] 2018-05-13 19:10
Direct messages are not private?

**Comment by gituser3000** [comment] 2022-09-12 14:16
While unjoined channels can't be accessed, it's easy to add your user and listen to messages
