### ISSUE TITLE
Broken Screen on Mobile app

### ISSUE THREAD

**Issue by defib** [RocketChat/Rocket.Chat#2275] opened 2016-02-18 02:01 UTC
After putting in the server URL, this error pops up: http://i.imgur.com/omfcoVx.jpg

Happens on Android and iOS, but not for everyone.

**Comment by marceloschmidt** [comment] 2016-05-02 18:17
What version are you on? Could you run the latest version and try again?

**Comment by krimdomu** [comment] 2016-06-22 14:58
@marceloschmidt 
Hi, i have the same problem but on my android device. I'm using the docker image `bd2e44fdc078` which is version 0.34.0 and which is the latest version.

```
# docker pull rocket.chat:latest
Status: Image is up to date for rocket.chat:latest
```

**Comment by MartinSchoeler** [comment] 2017-03-28 19:28
duplicate of #1106

**Closed by MartinSchoeler** 2017-03-28 19:28 UTC
Labels: subj: mobile, type: bug
