### ISSUE TITLE
Read reciept for messages

### ISSUE THREAD

**Issue by sbaheti56** [RocketChat/Rocket.Chat#4957] opened 2016-11-16 14:15 UTC
Your Rocket.Chat version: (0.38)

Hello Rocket Chat Team,
We are using this platform for team communication since 6 months. It's good but getting useless due to lack of below features, 
- Read receipt for each message (Personal chat as well group)  
- Desktop app with enabled notifications & that notification shall not be removed till the time user clicks on it as read receipt

Requesting you to provide your updates if such features will be available in further versions of rocket chat. Would be great if we can have it.

**Comment by nickbroon** [comment] 2017-11-22 10:50
Close this as a duplicate of #3411?

**Comment by sampaiodiego** [comment] 2018-01-31 00:04
this is not really duplicated of #3411 since it describes a different behavior for desktop notifications.

**Comment by engelgabriel** [comment] 2018-02-21 23:38
Closed via https://github.com/RocketChat/Rocket.Chat/pull/9717

**Closed by engelgabriel** 2018-02-21 23:38 UTC
Labels: feat: message, type: new feature

**Comment by GoetheG** [comment] 2019-10-25 01:24
Well. I guess that issue has to be reoened since it‘s not working anymore.

**Comment by reetp** [comment] 2019-10-25 08:34
> Well. I guess that issue has to be reoened since it‘s not working anymore.

Please search all the issues both and closed:

https://github.com/RocketChat/Rocket.Chat/pull/15656
https://github.com/RocketChat/Rocket.Chat/issues/15484

**Comment by GoetheG** [comment] 2019-11-22 09:29
Shouldn't this issue be merged with all the other same isses? Cause this error still occurs with the latest version.
