### ISSUE TITLE
Android keyboard automatically pops up upon entering a channel.

### ISSUE THREAD

**Issue by Rodriq** [RocketChat/Rocket.Chat#13758] opened 2019-03-18 00:39 UTC
This issue seem to have been closed previously without any solution.

# Steps to reproduce
1. Visit Rocket Chat on Android browser.
2. Click to enter any Chanel.
OR
Start up RC and visit locally through LAN on Android, and do above.

**Comment by geekgonecrazy** [comment] 2019-03-28 02:37
Which browser?  Is this Chrome on Android or what?

**Comment by Rodriq** [comment] 2019-03-28 03:18
Yes Android 8.1.0 Oreo. Chrome browser.

**Comment by MartinSchoeler** [comment] 2019-10-23 17:31
I cannot reproduce this using 2.1.0, this was probably fixed by the messagebox refactor. I will close this for now, if you see this issue again, please reopen this. Thanks!

**Closed by MartinSchoeler** 2019-10-23 17:31 UTC
Labels: subj: mobile, subj: ui/ux, type: improvement
