### ISSUE TITLE
OAuth: Twitter integration broken 

### ISSUE THREAD

**Issue by andpiazza** [RocketChat/Rocket.Chat#11239] opened 2018-06-24 01:50 UTC
### Steps to reproduce:
1. on an existing user profile, go to My Account → Profile
2. click on the Twitter button

### Expected behavior:
Twitter oauth added to existing user profile. Login to existing user profile profile on the RC home/login page.

### Actual behavior:
A new user is created.
The new user can't access the "My Profile" option on the menu (https://open.rocket.chat/account/profile) so it can't delete that profile /user. In fact, even the RC Support team can't delete that user. 
This issue is reproduced consistently, so the issue is scaling.

### Server Setup Information:
- Version of Rocket.Chat Server: 0.65.1 and previous
- Operating System: Win 10 64-bits
- Deployment Method: 
- Number of Running Instances: 1+
- DB Replicaset Oplog: active (?)
- NodeJS Version: v8.9.3 and previous
- MongoDB Version: 121 (?)
Operating System / Version / Architecture: Win 10 64-bits 
Browser type and version, including any add-ons: Chrome. Same behavior on RC desktop

**Comment by Hudell** [comment] 2018-07-02 16:43
Duplicate of #8496

**Closed by Hudell** 2018-07-02 16:43 UTC
Labels: feat: oauth / sso, type: bug
