### ISSUE TITLE
Unread Tray Icon Alert cannot be set to on

### ISSUE THREAD

**Issue by xgdgsc** [RocketChat/Rocket.Chat#16288] opened 2020-01-20 09:29 UTC
### Description:

Whenever I set Unread Tray Icon Alert to on in my profile settings (in linux client or webpage), it will reload the page and it would turn to off. The default preference in admin settings is on.

### Steps to reproduce:

1.  go to my profile settings,
2.  set Unread Tray Icon Alert to on
 

### Expected behavior:

It keeps on and ever.

### Actual behavior:

The page reloads and it is turned off.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.4.1  
- Operating System: Linux centos 3.10.0-957.el7.x86_64
- Deployment Method:  docker compose
- Number of Running Instances:  1
- DB Replicaset Oplog:  enabled
- NodeJS Version: v8.17.0
- MongoDB Version: 4.0.10

### Client Setup Information

- Desktop App or Browser Version: linux desktop 2.17.2
- Operating System: Ubuntu 16.04

 
### Relevant logs:
 
didn' t see any relevant

**Comment by sketch242** [comment] 2020-02-06 18:43
It would be nice if we could get this fix into 3.0.0...

**Comment by novoid** [comment] 2020-02-07 10:53
Same here: Xubuntu 1910 (xfce 4.14), Rocket.Chat version 2.17.2-1555.

Although I never see the Rocket.Chat panel icon. the app "Rocket.Chat" is enabled in the list of applications in the notifications panel plugin. In the Rocket.Chat settings, notifications are enabled.

Whatever happens in Rocket.Chat, the icon does not get shown in the panel.

When I re-visit the Rocket.Chat preferences (My Account - Preferences - Messages), the setting for "Unread Tray Icon Alert" is set to "off" again.

**Comment by ankar84** [comment] 2020-02-11 10:41
I found another moment with that bug. 
User can successfully change **Unread Tray Icon Alert** option by changing **Require Interaction to Dismiss Desktop Notification** option.
![Unread Tray Icon Alert](https://user-images.githubusercontent.com/4023037/74229825-37226480-4cd4-11ea-9877-74f3572851a2.gif)

**Comment by novoid** [comment] 2020-02-11 11:20
> User can successfully change **Unread Tray Icon Alert** option by changing **Require Interaction to Dismiss Desktop Notification** option.

I can confirm that the "Unread Tray Icon Alert" settings stays active in this case. I don't receive any unread notification in my panel (except the working libnotify popup notification).

**Comment by Donal-Goggin** [comment] 2020-03-19 11:44
Both of the fields have the same ID... Someone made a whoopsie :)  

![sameID](https://user-images.githubusercontent.com/32106124/77064043-9dd32600-69d6-11ea-82d0-a5e6a06e1c05.png)

**Comment by Donal-Goggin** [comment] 2020-03-30 19:35
If you just change the name of the unreadAlert ID in the notifications section before you submit the form it will set your preferences correctly. 
It looks like the fix for this is already done it just hasn't been released.

**Comment by xgdgsc** [comment] 2020-03-31 08:34
It is not merged yet. Don' t know why 1 line takes so long.

**Closed** 2020-04-14 13:49 UTC

**Comment by novoid** [comment] 2020-07-30 12:24
FYI:

Xubuntu 20.04 LTS with Rocket.Chat 2.17.7: The corresponding setting can now be enabled independent from the "Require Interaction to Dismiss Desktop Notification" setting.

However, I still got no notifications within the tray or the notification widget. The latter also does not show any "Rocket.Chat" source but this could be disguised behind some Java stuff I can not interpret myself.

The only notification I got for new messages is the changing Icon in the workspace window list.
