### ISSUE TITLE
Ampersand in URLs being incorrectly escaped as an HTML entity

### ISSUE THREAD

**Issue by kurji** [RocketChat/Rocket.Chat#10461] opened 2018-04-16 04:43 UTC
### Description:

When using Markdown-style links in Rocket Chat, the link generated escapes the ampersands as html entities incorrectly, meaning that clicking on the link will navigate the browser to a modified version of the link, not the actual link intended. The link preview seems correct, but the actual link is not.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Ubuntu 16.04 LTS  (4.4.0-119-generic)
* Deployment Method(snap/docker/tar/etc): SNAP
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled?
* Node Version: v8.9.4
* mongoDB Version: v3.2.7

### Client Binary

* Rocket.Chat+ Version 2.10.5
* Windows 7 Professional x64 Service Pack 1

### Steps to Reproduce:

1. Send the message ```[Test](https://appdb.winehq.org/objectManager.php?sClass=version&iId=34726)```
2. Click on the link (not the preview link)
![Rocket.Chat link bug](https://user-images.githubusercontent.com/22146019/38790395-63e9256a-4184-11e8-84e7-b41185e64fbd.png)

### Expected behavior:

Browser should navigate to https://appdb.winehq.org/objectManager.php?sClass=version&iId=34726

### Actual behavior:

Browser navigates to https://appdb.winehq.org/objectManager.php?sClass=version&amp;iId=34726 (note **&amp;amp;** in link) which is actually an entirely different page.

**Comment by TwizzyDizzy** [comment] 2018-04-16 18:36
@rocket-cat close

Closing this, since - if I'm not mistaken - this is a duplicate of #6719.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-04-16 18:36 UTC
