### ISSUE TITLE
Custom CSS not working

### ISSUE THREAD

**Issue by brxshncy** [RocketChat/Rocket.Chat#24858] opened 2022-03-17 11:16 UTC
### Description:

I made some tweaks in the Custom CSS and it's not working on a Self Hosted RocketChat. 

### Steps to reproduce:

1. Go to Administration > Layout  > Custom CSS Section
2.  tweaking sidebar CSS property,   CSS code below:
```
body .wrapper {
	background-color: #062d33 !important;
}
```
4. Save Changes

### Expected behavior:

Wrapper content should change color background

### Actual behavior:

CSS not working

**Comment by Shivansh2287** [comment] 2022-03-19 06:43
I am unable to reproduce the issue

![Screenshot from 2022-03-19 12-12-06](https://user-images.githubusercontent.com/54775060/159110602-966cd2aa-4c0a-439a-8aa0-28945453aa14.png)
![Screenshot from 2022-03-19 12-11-40](https://user-images.githubusercontent.com/54775060/159110604-44d67eed-0d30-4d10-9126-a4b9ad3f8244.png)

**Comment by vetash** [comment] 2022-03-21 11:06
```
+-------------------------------------------------+
|                  SERVER RUNNING                 |
+-------------------------------------------------+
|                                                 |
|  Rocket.Chat Version: 4.5.2                     |
|       NodeJS Version: 14.18.3 - x64             |
|      MongoDB Version: 4.0.28                    |
|       MongoDB Engine: mmapv1                    |
|             Platform: linux                     |
|         Process Port: 3000                      |
|             Site URL: https://chat.kirensk.net  |
|     ReplicaSet OpLog: Enabled                   |
|          Commit Hash: ed2cb3fe61                |
|        Commit Branch: HEAD                      |
|                                                 |
+-------------------------------------------------+
```
Same issue in 4.5.2. Css does not apply on any changes.

**Comment by TBG-FR** [comment] 2022-06-17 12:18
Could this be related to #19405 ? Try adding a fake rule at the end and tell me if it works now !

**Comment by Pushpendra766** [comment] 2022-06-29 10:21
Custom CSS is not working in mine too, can you help if you got the solution.

**Comment by Pushpendra766** [comment] 2022-06-29 10:23
> I am unable to reproduce the issue
> 
> ![Screenshot from 2022-03-19 12-12-06](https://user-images.githubusercontent.com/54775060/159110602-966cd2aa-4c0a-439a-8aa0-28945453aa14.png) ![Screenshot from 2022-03-19 12-11-40](https://user-images.githubusercontent.com/54775060/159110604-44d67eed-0d30-4d10-9126-a4b9ad3f8244.png)

Which version are you using

**Comment by billynoah** [comment] 2022-09-13 17:40
I am having this issue.  If I update the CSS in the settings panel it does get saved but the file theme.css (or css-theme.css) is not updated and still shows my old custom css.  

```
+----------------------------------------------------------------+
|                         SERVER RUNNING                         |
+----------------------------------------------------------------+
|                                                                |
|  Rocket.Chat Version: 5.1.1                                    |
|       NodeJS Version: 14.19.3 - x64                            |
|      MongoDB Version: 5.0.11                                   |
|       MongoDB Engine: wiredTiger                               |
|             Platform: linux                                    |
|         Process Port: 3000                                     |
|     ReplicaSet OpLog: Enabled                                  |
|          Commit Hash: 39baddf44d                               |
|        Commit Branch: HEAD                                     |
|                                                                |
+----------------------------------------------------------------+

**Comment by dudanogueira** [comment] 2022-09-14 18:09
Hi.

Some steps to help troubleshoot this:

Try the following css snippet in [ADMIN > LAYOUT > CUSTOM CSS:](http://localhost:3000/admin/settings/Layout)


```
[data-own|="true"]{
  background: yellow !important;
}
```
this will set a yellow background to your own messages. :smile: 

Can you see the same css content on this file?
http://localhost:3000/css-theme.css

if you hard reload your browser (ctrl+shit+r), you should see your own messages like this:
![image](https://user-images.githubusercontent.com/1761174/190229985-59d81170-9044-4b9a-8d57-42cf5046ab72.png)

**Comment by billynoah** [comment] 2022-09-14 18:53
@dudanogueira - in my case this does not work.  I am able to successfully save the CSS to the settings but the theme css does not get updated.  If I curl `http://localhost:3000/css-theme.css` from a terminal I can still see my old CSS but the changes are not present.

**Comment by dudanogueira** [comment] 2022-09-15 12:24
Closing. 

I contacted @billynoah and after removing/editing the css contents and saving it again, it worked.

As this was not reproducible issue, we'll need a not working environment to analyze it.

**Closed by dudanogueira** 2022-09-15 12:24 UTC
Labels: stat: need more info

**Comment by tempo22** [comment] 2023-01-14 19:51
Sorry to reopen this, but I just had the issue and found dirty quickfix, I had to update the value directly in the mongodb document. For some reason, I had a "css" & "theme-custom-css" settings in the database and only the "css" setting was being used to generate the "css-theme.css" file while the "theme-custom-css" was the one used in the admin panel.
