### ISSUE TITLE
[BUG] readonly/broadcast "moderators" can see members list but cannot post messages

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#10769] opened 2018-05-14 22:03 UTC
### Description:

![screen shot 2018-05-14 at 19 00 54](https://user-images.githubusercontent.com/551004/40025851-57764322-57a9-11e8-97ea-6d70abb0d237.png)

In the screenshot, user can see the members list but cannot write messages to the room. The room is a Broadcast room and the user is `moderator`.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.2.-rc.0
* Operating System: Linux

**Comment by ggazzo** [comment] 2018-05-25 20:39
@rafaelks could you test again? I think its working....

**Comment by rafaelks** [comment] 2018-05-28 10:37
@ggazzo In `unstable.rocket.chat`, still not working...

![screen shot 2018-05-28 at 07 36 43](https://user-images.githubusercontent.com/551004/40610726-e9c511e0-6249-11e8-9491-59cb939eba49.png)

**Comment by ggazzo** [comment] 2018-05-28 13:17
@rafaelks actually its not a broadcast problem, the problem is with readonly rooms (broadcast its kind of readonly).

![image](https://user-images.githubusercontent.com/5263975/40616086-fa4fbcd4-625f-11e8-8472-cc1333a0375a.png)

obs: if you add a user and promote him to "moderator/owner" he keeps "muted"

**Comment by bhardwajaditya** [comment] 2019-03-12 13:27
@ggazzo @rafaelks if this issue still requires a fix , may I work on this?

**Comment by Hudell** [comment] 2019-08-22 19:54
This bug has already been fixed on the current version of Rocket.Chat, so I'll be closing this issue.

**Closed by Hudell** 2019-08-22 19:54 UTC
Labels: type: bug
