### ISSUE TITLE
Snap not on newest version

### ISSUE THREAD

**Issue by RogerSik** [RocketChat/Rocket.Chat#12869] opened 2018-12-06 11:24 UTC
Snap  is not on the newest version (since 8 days) and other installation method like Dockers are.

**Comment by tassoevan** [comment] 2018-12-06 11:52
@RogerSik I agree. Could you file an issue on [the documentation repository](https://github.com/RocketChat/docs/issues), please?

**Comment by geekgonecrazy** [comment] 2018-12-06 20:39
This is not a bug.  Feel free to open a bug as mentioned above.  0.72.1 will be released in a few hours

**Closed by geekgonecrazy** 2018-12-06 20:39 UTC
