### ISSUE TITLE
Loading mixed (insecure) display content

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/Rocket.Chat#2731] opened 2016-04-01 09:07 UTC
Your Rocket.Chat version: 0.22.0

Let's say I run Rocket.Chat behind https, and I share a link to a resource that is served under http.
Rocket.Chat will embed a remote picture.

And the browser will complain!

Here an example with firefox:
```
Loading mixed (insecure) display content "http://photos1.meetupstatic.com/photos/event/2/4/9/2/highres_348129362.jpeg" on a secure page[Learn More]
```

The solution is to cache locally the embeded media.
Here is how github is solving the issue for instance. (From your README.md)
```
<img src="https://camo.githubusercontent.com/facf0bfc4bd872a0a7fbb097b542a07c4321752b/68747470733a2f2f696e6469652e686f73742f7369676e75702e706e67" alt="Rocket.Chat on IndieHosters" data-canonical-src="https://indie.host/signup.png" style="max-width:100%;">
```

They use a proxy for their images.

**Comment by engelgabriel** [comment] 2016-04-01 19:37
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/971

**Closed by engelgabriel** 2016-04-01 19:37 UTC
