### ISSUE TITLE
[Bug] Profile update does not work in Internet Explorer

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#10869] opened 2018-05-24 14:14 UTC
### Description:

When changing profile properties, like name, you cannot store the information. Clicking the SAVE button does not have any effect

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3

### Steps to Reproduce:

1. Open Internet Explorer and Login
2. Edit user name
3. Save 

### Expected behavior:

Saving should work...

### Actual behavior:

Saving does not work.

**Comment by MartinSchoeler** [comment] 2018-10-23 16:50
Duplicate of #10701

**Closed by MartinSchoeler** 2018-10-23 16:50 UTC
