### ISSUE TITLE
Livestream setting save issue - Match error: Unknown key in field id

### ISSUE THREAD

**Issue by CodeFunta** [RocketChat/Rocket.Chat#12060] opened 2018-09-14 10:22 UTC
### Description:
Error (400) while clicking save button for livestream settings in private channel

### Steps to reproduce:

1. Go to some private channel and open menu (aka more)
2. Click on livestream setting
3. Input youtube livestream url
4. Click save 

### Expected behavior:
Successfull saved livestream url for channel

### Actual behavior:
After click save button the 400 error red box was appeared

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2
- Operating System: linux (x64) 4.15.0-30-generic
- Deployment Method: snap
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3
- MongoDB Version: 

### Relevant logs:

Exception while invoking method 'saveRoomSettings' Error: Match error: Unknown key in field id     at check (/snap/rocketchat-server/1324/programs/server/packages/check.js:68:17)     at EventEmitter.RocketChat.saveStreamingOptions (/snap/rocketchat-server/1324/programs/server/packages/rocketchat_livestream.js:62:3)     at Object.keys.forEach.setting (/snap/rocketchat-server/1324/programs/server/packages/rocketchat_channel-settings.js:460:22)     at Array.forEach (<anonymous>:null:null)     at MethodInvocation.saveRoomSettings (/snap/rocketchat-server/1324/programs/server/packages/rocketchat_channel-settings.js:405:27)     at MethodInvocation.methodsMap.(anonymous function) (/snap/rocketchat-server/1324/programs/server/packages/rocketchat_lib.js:2496:36)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at DDPServer._CurrentWriteFence.withValue (/snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)     at Promise (/snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:875:23)     at /snap/rocketchat-server/1324/programs/server/packages/ddp-server.js:754:85  
[34mI20180914-10:01:15.312(0) Sanitized and reported to the client as: Match failed [400] 
[34mI20180914-10:01:15.312(0) undefined undefined

**Comment by reetp** [comment] 2018-11-08 15:05
Think this is most likely a duplicate of #12201 
Marking as duplicate and closing

**Comment by reetp** [comment] 2018-11-08 15:06
@rocket-cat label add duplicate

**Comment by reetp** [comment] 2018-11-08 15:06
@rocket-cat close

Please follow up on #12201 if you have anything further to add

**Closed by reetp** 2018-11-08 15:06 UTC
Labels: duplicate
