### ISSUE TITLE
[BUG] New version converting doesn't work

### ISSUE THREAD

**Issue by Kowjako** [RocketChat/Rocket.Chat#23749] opened 2021-11-18 11:00 UTC
### Description:
I'm opening Rocket Chat desktop application on Windows and got message that i can update my Rocket but it doesn't do anything
### Steps to reproduce:

1. Open Rocket Chat windows client
2. After got message about updates click install
3. Version is still the same as previous

### Expected behavior:

Version of application must be the same as the update version

### Actual behavior:

Vesrion of application doesn't changed

### Client Setup Information

- Desktop App or Browser Version: Dekstop App
- Operating System: Windows 10

**Comment by ankar84** [comment] 2021-11-19 04:01
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670
Closing this in favor of original issue.
You can comment there.

**Closed by ankar84** 2021-11-19 04:01 UTC
