### ISSUE TITLE
Snap not updating (still 0.72.3)

### ISSUE THREAD

**Issue by sloslo4** [RocketChat/Rocket.Chat#13128] opened 2019-01-11 13:44 UTC
tracking:     edge
refresh-date: 28 days ago, at 17:33 UTC
channels:                        
  stable:    0.72.3 (1356) 224MB -
  candidate: 0.72.3 (1356) 224MB -
  beta:      ↑                   
  edge:      0.72.3 (1355) 224MB -
installed:   0.72.3 (1355) 224MB -

### Description:
Perhaps you forgot to upgrade to the latest version, because 28 days have passed and there is not even an in edge.

Please update snap version

**Comment by tassoevan** [comment] 2019-01-11 16:20
Duplicate of #13082.

**Closed by tassoevan** 2019-01-11 16:20 UTC
