### ISSUE TITLE
[Bug] URL-part containing ":/" sometimes converted to confused smiley

### ISSUE THREAD

**Issue by jatoko** [RocketChat/Rocket.Chat#26648] opened 2022-08-22 11:15 UTC
**Description:**

Depending on whether a URL contains a minus-sign "-", it is displayed incorrectly in a chat message.

For the URL "https://u-rl.de" a "confused smiley" is inserted.
The URL "https://url.de" works as expected.

![grafik](https://user-images.githubusercontent.com/17083784/185907439-8ea26174-fb3b-4084-914a-0d1873ee7d05.png)

Bug appears to happen only on Web and Desktop Client. Mobile Client (Android) works fine.

**Expected behavior:**

Do not show "confused smiley"

**Server Setup Information:**

    Version of Rocket.Chat Server: 5.0.4
    Operating System: Linux
    Deployment Method: Docker Compose
    Number of Running Instances: 1
    DB Replicaset Oplog: MongoDB 4.4
    MongoDB Version: 4.4

**Comment by Vaarlion** [comment] 2022-08-22 11:29
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/26475 sadly

**Comment by kekefreedog** [comment] 2022-08-22 15:14
Same problem for me with url which doesn't have `.com` or dot something...
![image](https://user-images.githubusercontent.com/70959083/185956419-483ce199-0e3f-4fbe-b33c-09bbea27e31a.png)

**Comment by xdelatour** [comment] 2022-08-22 17:43
duplicate of #26475, #26485, #26555, #23020

**Comment by xmedeko** [comment] 2022-08-24 12:05
Probably similar bug to #26661

**Comment by hugocostadev** [comment] 2022-09-28 11:22
Fixed on [Release 5.1.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/5.1.0) But I recommend keeping the product updated with the last stable release.

**Closed by hugocostadev** 2022-09-28 11:22 UTC
Labels: subj: message rendering
