### ISSUE TITLE
Can we disable Member List View in a private Group

### ISSUE THREAD

**Issue by chamarat-wso2** [RocketChat/Rocket.Chat#3904] opened 2016-08-03 09:44 UTC
Your Rocket.Chat version: (0.35.0)

When having Chat (Private Group) with Customers ,he can list all the members in the group  where we need to list only active members who are chatting with him or  not list at all. Do we have option for that?

**Comment by MartinSchoeler** [comment] 2017-07-21 13:50
duplicate of #2588

**Closed by MartinSchoeler** 2017-07-21 13:50 UTC
Labels: type: support
