### ISSUE TITLE
Avatars in "Threads" and "Profile" views not using context path

### ISSUE THREAD

**Issue by fitzyjoe** [RocketChat/Rocket.Chat#22416] opened 2021-06-18 20:59 UTC
### Description:

Avatars in "Threads" are not using our deployment's context path.

### Steps to reproduce:

Deploy rocketchat without a subdomain but with a context path.  Ours is "/chat"
Notice that chats in a channel display the avatar and have links like this "/chat/avatar/{username}"
View a Thread, which opens up a list of messages in a thread in a panel on the right side and notice that avatars result in 404 errors and the links are like this "/avatar/{username}"
Click on a username in a chat channel and see the Profile modal.  Notice that this avatar results in a 404 error and the link is like this "/avatar/{username}"

### Expected behavior:

I expect that all URL requests from RocketChat will respect the context path.

### Actual behavior:

Lots of 404's when avatars are being requested... improper URLs that do not include the context path.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.1
- Operating System: RHEL 7
- Deployment Method: RPM
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v12.18.4
- MongoDB Version: 4.2.5

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: MacOS 11.4

**Comment by johncrisp** [comment] 2021-06-21 21:36
I believe this is a duplicate of several similar bugs and is fixed here:

https://github.com/RocketChat/Rocket.Chat/pull/22432

And you really need to upgrade - please see release notes for why.

**Closed by johncrisp** 2021-06-21 21:36 UTC

**Comment by fitzyjoe** [comment] 2021-06-22 14:20
Thanks @johncrisp
