### ISSUE TITLE
Allow emoji in channel topic

### ISSUE THREAD

**Issue by alexbrazier** [RocketChat/Rocket.Chat#6305] opened 2017-03-09 12:10 UTC
Rocket.Chat Version: 0.53.0

When setting a topic to `:thumbsup:` it should convert it into emoji, rather that just showing `:thumbsup:` in the channel topic.

**Comment by jszaszvari** [comment] 2017-03-11 16:23
This would be awesome. 

+1

**Comment by amelieq-c** [comment] 2017-04-19 20:37
+1 approuved

**Comment by RAJAGOPALAN-GANGADHARAN** [comment] 2018-12-01 13:46
@alexbraizer can i work on this

**Comment by alexbrazier** [comment] 2018-12-01 13:49
@RAJAGOPALAN-GANGADHARAN yes, go for it. I currently don't have plans to work on it.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment] 2018-12-01 14:15
@alexbrazier lemme understand the codebase rocket chat is pretty amazing
and try to implement it. You might have to help me in this process as i am a beginner thank you 😄

**Comment by alexbartsch** [comment] 2019-01-01 20:52
@sampaiodiego Duplicate of #12696. See also pull request #12858.

**Comment by sampaiodiego** [comment] 2019-01-02 12:47
thanks @alexbartsch .. I'll actually close the other one, as this is older.

**Comment by alexbartsch** [comment] 2019-01-05 20:30
thanks @sampaiodiego. But what happens with the open pull request for the older issue? It will also fix this issue. How can we link it? https://github.com/RocketChat/Rocket.Chat/pull/12858

**Comment by sampaiodiego** [comment] 2019-01-07 14:47
saw you update the comment referencing this issue @alexbartsch .. so everything is fine =)

**Closed** 2019-01-19 20:16 UTC
Labels: Feature: Planned, challenge, contrib: easy, feat: channel settings, subj: ui/ux
