### ISSUE TITLE
Unable to use or install apps after upgrading to 6.11.1

### ISSUE THREAD

**Issue by Mal0815** [RocketChat/Rocket.Chat#33188] opened 2024-08-30 09:45 UTC
### Description:

I updated RocketChat from 6.6.X (iirc) to 6.11.1 directly without going to 6.10.
I ran the additional steps mentioned in https://docs.rocket.chat/docs/updating-rocketchat vor version 6.10.

After the update, my installed apps were deactivated uand couldn't be activated anymore. Actual GIPHY and Poll.
I tried to deinstall them but couldn't reinstall.
I got different error messages:
"Apps_Error_App already has an associated runtime" &
"Timeout: app process not ready"

### Steps to reproduce:

1. Go to market place
2. try to install an app

### Expected behavior:

success on installation

### Actual behavior:

error

### Server Setup Information:

Version
6.11.1
Version der Anwendungs-Engine
1.44.0
Node-Version
v14.21.3
Datenbankmigration
304 (30. August 2024 10:57)
MongoDB
5.0.28 / wiredTiger (oplog Deaktiviert)
Details festschreiben
HEAD: (12e000d88)
Zweig: HEAD
Release 6.11.1

Starter license
1 instance
approx. 10 Users
OS: Debian 11
DEployment on Debian

### Additional context

I tried to run rocketchat with DEBUG option "DEBUG=appsEngine:runtime:*" mentioned in https://github.com/RocketChat/Rocket.Chat/issues/33140
Log below:

### Relevant logs:

{"level":35,"time":"2024-08-30T09:11:31.423Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/apps/count","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/marketplace/explore/list","remoteIP":"192.168.2.34","status":200,"responseTime":1} 
{"level":35,"time":"2024-08-30T09:11:31.436Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/apps/installed","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/marketplace/explore/list","remoteIP":"192.168.2.34","status":200,"responseTime":1} 
{"level":35,"time":"2024-08-30T09:11:31.719Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/apps/app-request/stats","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/marketplace/explore/list","remoteIP":"192.168.2.34","status":200,"responseTime":275} 
{"level":35,"time":"2024-08-30T09:11:31.730Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/apps/categories","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/marketplace/explore/list","remoteIP":"192.168.2.34","status":200,"responseTime":296} 
{"level":20,"time":"2024-08-30T09:11:32.367Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"No more registered queues. Refreshing"} 
{"level":20,"time":"2024-08-30T09:11:32.369Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"Executing queue Public with timeout of 5000"} 
{"level":20,"time":"2024-08-30T09:11:32.369Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"Processing items for queue Public"} 
{"level":20,"time":"2024-08-30T09:11:32.370Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"No more items for queue Public"} 
{"level":35,"time":"2024-08-30T09:11:32.468Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/apps/marketplace?isAdminUser=true","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/marketplace/explore/list","remoteIP":"192.168.2.34","status":200,"responseTime":1036} 
{"level":35,"time":"2024-08-30T09:11:33.091Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/apps/featured-apps","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/marketplace/explore/list","remoteIP":"192.168.2.34","status":200,"responseTime":456} 
{"level":20,"time":"2024-08-30T09:11:37.372Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"No more registered queues. Refreshing"} 
{"level":20,"time":"2024-08-30T09:11:37.374Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"Executing queue Public with timeout of 5000"} 
{"level":20,"time":"2024-08-30T09:11:37.374Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"Processing items for queue Public"} 
{"level":20,"time":"2024-08-30T09:11:37.375Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"No more items for queue Public"} 
{"level":20,"time":"2024-08-30T09:11:42.378Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"No more registered queues. Refreshing"} 
{"level":20,"time":"2024-08-30T09:11:42.379Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"Executing queue Public with timeout of 5000"} 
{"level":20,"time":"2024-08-30T09:11:42.380Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"Processing items for queue Public"} 
{"level":20,"time":"2024-08-30T09:11:42.381Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"No more items for queue Public"} 
{"level":20,"time":"2024-08-30T09:11:47.384Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"No more registered queues. Refreshing"} 
{"level":20,"time":"2024-08-30T09:11:47.385Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"Executing queue Public with timeout of 5000"} 
{"level":20,"time":"2024-08-30T09:11:47.385Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"Processing items for queue Public"} 
{"level":20,"time":"2024-08-30T09:11:47.387Z","pid":2202,"hostname":"webserver","name":"OmnichannelQueue","msg":"No more items for queue Public"} 
{"level":35,"time":"2024-08-30T09:11:47.559Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/info","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/admin/info","remoteIP":"192.168.2.34","status":200,"responseTime":11} 
{"level":35,"time":"2024-08-30T09:11:47.565Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/v1/statistics?refresh=false","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/admin/info","remoteIP":"192.168.2.34","status":200,"responseTime":8} 
{"level":35,"time":"2024-08-30T09:11:47.571Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/v1/instances.get","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/admin/info","remoteIP":"192.168.2.34","status":200,"responseTime":9} 
{"level":35,"time":"2024-08-30T09:11:47.608Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/v1/licenses.info?loadValues=true","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/admin/info","remoteIP":"192.168.2.34","status":200,"responseTime":13} 
{"level":35,"time":"2024-08-30T09:11:47.609Z","pid":2202,"hostname":"webserver","name":"API","method":"GET","url":"/api/v1/cloud.registrationStatus","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","host":"chat.chat.de","referer":"https://chat.chat.de/admin/info","remoteIP":"192.168.2.34","status":200,"responseTime":8} 
{"level":35,"time":"2024-08-30T09:11:52.365Z","pid":2202,"hostname":"webserver","name":"API","method":"POST","url":"/api/apps","userId":"ID","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","length":"85","host":"chat.chat.de","referer":"https://chat.chat.de/marketplace/explore/list","remoteIP":"192.168.2.34","err":{"type":"Error","message":"[8b882242-0cb7-419f-87d8-93b1d09e1ec2] Timeout: app process not ready","stack":"Error: [8b882242-0cb7-419f-87d8-93b1d09e1ec2] Timeout: app process not ready<br>    at Timeout._onTimeout (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/server/runtime/deno/AppsEngineDenoRuntime.js:216:55)<br>    at listOnTimeout (internal/timers.js:557:17)<br>    at processTimers (internal/timers.js:500:7)<br> => awaited here:<br>    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at ee/server/apps/communication/rest.ts:402:15<br>    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at packages/meteor.js:367:22<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)<br>    at app/api/server/api.ts:649:39<br>    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"},"status":400,"responseTime":11938,"msg":"[8b882242-0cb7-419f-87d8-93b1d09e1ec2] Timeout: app process not ready"}

**Comment by Mal0815** [comment] 2024-08-30 10:18
Another log...
[debug_rocketchat_2.txt](https://github.com/user-attachments/files/16815486/debug_rocketchat_2.txt)

**Comment by reetp** [comment] 2024-08-30 10:37
Closing as this is almost certainly a duplicate of  #33140

**Closed by reetp** 2024-08-30 10:37 UTC
Labels: duplicate
