### ISSUE TITLE
Show accounts_ CustomFieldsToShowInUserInfo from Users collection field

### ISSUE THREAD

**Issue by DuJiming** [RocketChat/Rocket.Chat#23992] opened 2021-12-20 09:02 UTC
### description

We connected to LDAP and set up synchronization
The `employeeNum` field is synchronized to users
Is there any way to show `employeeNum` in account custom fields

Please forgive my poor translation

https://github.com/RocketChat/Rocket.Chat/issues/9763

**Comment by dudanogueira** [comment] 2021-12-20 13:01
Hi! The latest version will sync only basic LDAP information.

If you want to map other information from LDAP into the user account (like a custom field), you can create a script that will read from LDAP and use the REST APIs for that.

**Comment by DuJiming** [comment] 2021-12-21 02:12
> Hi! The latest version will sync only basic LDAP information.
> 
> If you want to map other information from LDAP into the user account (like a custom field), you can create a script that will read from LDAP and use the REST APIs for that.

thinks
I have synchronized employeenum to the users collection, I know accounts_ Customfieldstoshowinuserinfo is entered by the user himself.
**What I want to do is display the `employeeNum` key and value of users collection in accounts_ CustomFieldsToShowInUserInfo**

![image](https://user-images.githubusercontent.com/36750680/146858648-6ade3eff-4b9b-4e6b-b4dd-b38daa555dc9.png)

As shown in the figure above, `111` is entered by the user himself. I want to take the `employeeNum` in the users collection by default

**Comment by dudanogueira** [comment] 2022-02-03 16:16
This feature is for the Enterprise version only.

You can also accomplish that using the REST APIs.

As this is not a bug, closing.

Also, refere to this documentation for more information about custom user field and how to display it:
https://docs.rocket.chat/guides/administration/settings/account-settings/custom-fields

**Closed by dudanogueira** 2022-02-03 16:16 UTC

**Comment by DuJiming** [comment] 2022-02-07 04:18
> This feature is for the Enterprise version only.
> 
> You can also accomplish that using the REST APIs.
> 
> As this is not a bug, closing.
> 
> Also, refere to this documentation for more information about custom user field and how to display it: https://docs.rocket.chat/guides/administration/settings/account-settings/custom-fields

OK, thinks
