### ISSUE TITLE
Default test cases failing

### ISSUE THREAD

**Issue by vedant-pandey** [RocketChat/Rocket.Chat#28859] opened 2023-04-10 14:14 UTC
### Steps to reproduce:

1.  Setup the repository
2.  Run `yarn testunit`

### Expected behavior:

Tests should run successfully in default scenario

### Actual behavior:

Tests are failing

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.0-develop
- Operating System: Mac
- Deployment Method:  local
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.3
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:
```
@rocket.chat/meteor:testunit:   1) parseMessageSearchQuery
@rocket.chat/meteor:testunit:        should parse "before:01-01-2023":
@rocket.chat/meteor:testunit: 
@rocket.chat/meteor:testunit:       AssertionError: expected { Object (ts) } to deeply equal { Object (ts) }
@rocket.chat/meteor:testunit:       + expected - actual
@rocket.chat/meteor:testunit: 
@rocket.chat/meteor:testunit:        {
@rocket.chat/meteor:testunit:          "ts": {
@rocket.chat/meteor:testunit:       -    "$lte": [Date: 2022-12-31T12:30:00.000Z]
@rocket.chat/meteor:testunit:       +    "$lte": [Date: 2022-12-31T13:30:00.000Z]
@rocket.chat/meteor:testunit:          }
@rocket.chat/meteor:testunit:        }
@rocket.chat/meteor:testunit:       
@rocket.chat/meteor:testunit:       at Context.<anonymous> (tests/unit/server/lib/parseMessageSearchQuery.spec.ts:111:26)
@rocket.chat/meteor:testunit:       at processImmediate (internal/timers.js:464:21)
@rocket.chat/meteor:testunit: 
@rocket.chat/meteor:testunit:   2) parseMessageSearchQuery
@rocket.chat/meteor:testunit:        should parse "after:01-01-2023":
@rocket.chat/meteor:testunit: 
@rocket.chat/meteor:testunit:       AssertionError: expected { Object (ts) } to deeply equal { Object (ts) }
@rocket.chat/meteor:testunit:       + expected - actual
@rocket.chat/meteor:testunit: 
@rocket.chat/meteor:testunit:        {
@rocket.chat/meteor:testunit:          "ts": {
@rocket.chat/meteor:testunit:       -    "$gte": [Date: 2023-01-01T12:30:00.000Z]
@rocket.chat/meteor:testunit:       +    "$gte": [Date: 2023-01-01T13:30:00.000Z]
@rocket.chat/meteor:testunit:          }
@rocket.chat/meteor:testunit:        }
@rocket.chat/meteor:testunit:       
@rocket.chat/meteor:testunit:       at Context.<anonymous> (tests/unit/server/lib/parseMessageSearchQuery.spec.ts:111:26)
@rocket.chat/meteor:testunit:       at processImmediate (internal/timers.js:464:21)
@rocket.chat/meteor:testunit: 
@rocket.chat/meteor:testunit:   3) parseMessageSearchQuery
@rocket.chat/meteor:testunit:        should parse "on:01-01-2023":
@rocket.chat/meteor:testunit: 
@rocket.chat/meteor:testunit:       AssertionError: expected { ts: { …(2) } } to deeply equal { ts: { …(2) } }
@rocket.chat/meteor:testunit:       + expected - actual
@rocket.chat/meteor:testunit: 
@rocket.chat/meteor:testunit:        {
@rocket.chat/meteor:testunit:          "ts": {
@rocket.chat/meteor:testunit:       -    "$gte": [Date: 2022-12-31T12:30:00.000Z]
@rocket.chat/meteor:testunit:       -    "$lt": [Date: 2023-01-01T12:30:00.000Z]
@rocket.chat/meteor:testunit:       +    "$gte": [Date: 2022-12-31T13:30:00.000Z]
@rocket.chat/meteor:testunit:       +    "$lt": [Date: 2023-01-01T13:30:00.000Z]
@rocket.chat/meteor:testunit:          }
@rocket.chat/meteor:testunit:        }
@rocket.chat/meteor:testunit:       
@rocket.chat/meteor:testunit:       at Context.<anonymous> (tests/unit/server/lib/parseMessageSearchQuery.spec.ts:111:26)
@rocket.chat/meteor:testunit:       at processImmediate (internal/timers.js:464:21)
```

**Comment by hugocostadev** [comment] 2023-04-10 14:33
Did you run the script in the latest `develop` branch and in an empty DB?

**Comment by vedant-pandey** [comment] 2023-04-10 14:46
Yes

**Comment by hugocostadev** [comment] 2023-04-10 17:45
I ran the `yarn testunit` script in the `develop` branch and everything passed... 
![image](https://user-images.githubusercontent.com/20212776/230959861-156db8d4-0ab2-48ea-a95f-27b3dd6f089e.png)

Check your node and meteor versions, please. 

I'll close this for now since it's not an issue. 

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Closed by hugocostadev** 2023-04-10 17:45 UTC

**Comment by AdityaRaut13** [comment] 2023-10-04 11:45
The problem is related to timezones and when I changed by timezone to UTC it works !

**Comment by MeethDavda** [comment] 2023-10-05 05:48
Can you explain where did you change it to UTC ?

**Comment by AdityaRaut13** [comment] 2023-10-05 06:36
The system timezone if you are on debian :
then you can use this command `sudo timedatectl set-timezone UTC`.
But I think your error was different.

**Comment by AdityaRaut13** [comment] 2023-10-05 06:36
sorry I just checked the error, I think this will work !
