### ISSUE TITLE
Autorepeat on starting video calls

### ISSUE THREAD

**Issue by jschirrmacher** [RocketChat/Rocket.Chat#12148] opened 2018-09-25 14:34 UTC
After doing a video call and leaving the side bar open, it seems to repeat initiating calls every few minutes:

![bildschirmfoto 2018-09-25 um 16 28 23](https://user-images.githubusercontent.com/2821879/46021254-8a484700-c0e0-11e8-89ba-050c00879fc8.png)

To make sure: I didn't really initiate these calls. In fact, I wasn't even at my computer because it was a Saturday and I only stopped it in the afternoon of the next day.

**Comment by jschirrmacher** [comment] 2018-10-08 11:08
It seems, that this is independent of the sidebar being opened. I had a call in a channel last week, and it kept sending "Started a Video Call - Click to join" the whole weekend although the sidebar was closed on both sides.

**Comment by jwmann** [comment] 2018-10-11 17:32
I'm having this exact issue as well

**Comment by jwmann** [comment] 2018-10-12 21:59
Updated to Version 2.14, still happening.

**Comment by cahi** [comment] 2019-01-30 09:22
We're having the same issue here...
Rocketchat: 0.73.2
Client MacOS 2.14.6

**Comment by cnvx** [comment] 2019-11-14 16:40
This is happening in our instance too but only for one user, they happen to be the only user running Windows.

Details:
RocketChat version: 2.0.0 (self-hosted Docker container)
Client OS: Windows 10
Video chat solution: Jitsi Meet

![image](https://user-images.githubusercontent.com/33325976/68876970-342bce00-06fd-11ea-84a8-1e2a8caa9cf9.png)

**Comment by cnvx** [comment] 2020-01-09 10:11
This is possibly a duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1234.
As far as I know the Windows / MacOS client is using Electron, I've not seen this happen using the browser version or Linux client.

**Comment by rsjr** [comment] 2020-02-13 21:03
related to #14508

**Comment by ggazzo** [comment] 2020-02-14 16:58
closed by https://github.com/RocketChat/Rocket.Chat/pull/16601

**Closed by ggazzo** 2020-02-14 16:58 UTC
Labels: feat: video conferencing, sla, type: bug

**Comment by AntouanK** [comment] 2020-04-28 06:38
@ggazzo 
seems like this issue is still happening! :/
![Screenshot from 2020-04-28 08-36-49](https://user-images.githubusercontent.com/4569111/80455167-8ff4b700-892b-11ea-8ef5-39876c22231c.png)

running Rocket.Chat 3.2.0
Any idea how to fix it?

**Comment by luixxiul** [comment] 2020-05-01 07:20
Another report on this issue: https://github.com/RocketChat/Rocket.Chat/pull/16601#issuecomment-622229591

**Comment by hever** [comment] 2020-05-05 12:34
> seems like this issue is still happening! :/

I confirm

**Comment by Kamp11** [comment] 2020-05-07 06:57
There is the same problem
Rocket Chat 3.1.1

**Comment by AlexandreBeaudoin** [comment] 2020-05-22 15:55
One of our users indicates that this seems to occur after her machine wakes up from standby.  One avenue to check might be how Rocketchat behaves after network failure.

**Comment by cjpabloL** [comment] 2020-05-23 15:08
We're having the same issue here...
Rocketchat: 1.3.2
Client Windows

**Comment by satkunas** [comment] 2020-05-26 14:05
Same issue using rocketchat-2.17.7-1634.x86_64 on Linux 5.5.16-100.fc30.x86_64

**Comment by AmatorPhasma** [comment] 2020-06-25 05:58
Same problem on:
Server: Rocket Chat 3.3.0
Client: Desktop App 2.17.9 (Windows)

**Comment by grimuz** [comment] 2020-07-07 16:03
Same problem on:
Server: Rocket Chat 3.4.0
Client: Windows

**Comment by grimuz** [comment] 2020-07-07 16:07
would like to ask, if there is a possible Workaround until its fixed?

**Comment by satkunas** [comment] 2020-07-07 16:24
> One of our users indicates that this seems to occur after her machine wakes up from standby. One avenue to check might be how Rocketchat behaves after network failure.

This appears to be part of the cause. However, updating the server appears to have resolved this issue.

**Comment by nadjaheitmann** [comment] 2020-10-22 07:23
Hi, I am still experiencing the same issue. 
Platform: Linux (x64)
Electron: 7.2.4
I am using RocketChat inside Rambox (Version 0.7.7).

![Screenshot from 2020-10-22 09-17-57](https://user-images.githubusercontent.com/71487468/96838009-92058180-1447-11eb-8225-e8f32b4b5de8.png)

**Comment by ofrzeta** [comment] 2020-12-16 10:30
We have the same problem with the Rocket Chat App on Mac.

**Comment by bellegarde-c** [comment] 2021-03-19 10:57
Same issue with 3.12.0

**Comment by rasos** [comment] 2021-03-20 11:29
This is a regression. Even when it was fixed a year ago with #16601 it still appears in 3.7.1 in the web browser and app. Likely the other user has put the laptop in hibernation.  Very annoying and makes integration of Jitsi Calls unusable.
