### ISSUE TITLE
New users not automatically added to default channel

### ISSUE THREAD

**Issue by drasbeck** [RocketChat/Rocket.Chat#7663] opened 2017-08-06 09:57 UTC
### Description:

New users are not added to a servers default channel.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Operating System: Rasbian
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 1
* Node Version: 4.8.2

### Steps to Reproduce:

1. New user registers.
2. Logs in.

### Expected behavior:

The new user is automatically added to (any) channel with the "default" flag set to true.

### Actual behavior:

The new user is not added to said channel.

**Comment by MartinSchoeler** [comment] 2017-08-07 12:01
@drasbeck I could not reproduce this issue. Could you give us more info on what are you doing? Like the steps how you add the channel to the default ones? Thanks!

**Comment by drasbeck** [comment] 2017-08-07 18:19
The channel is, if I recollect correctly, the original #general which has been renamed. Thus it's default status has not been altered.

**Comment by geekgonecrazy** [comment] 2017-08-10 20:12
if you try removing those and adding on a couple of other channels and then register do you see any changed behaviour?

**Comment by drasbeck** [comment] 2017-08-20 10:23
I have just:
1. Removed any default channel on the server
2. Created a new channel.
3. Through admin panel changed default to true.
4. And finally registered a new user, who sadly is not automatically added to the channel.

**Comment by geekgonecrazy** [comment] 2017-12-20 20:29
@drasbeck I think this one shouldn't be an issue any more can you confirm?

**Comment by drasbeck** [comment] 2017-12-20 20:53
I can confirm this. =) New users are now added to the default channels.

**Comment by geekgonecrazy** [comment] 2017-12-20 20:55
Perfect!  Found this again while creating this: #9205 so just wanted to be sure.

I'll go ahead and close this one.

**Closed by geekgonecrazy** 2017-12-20 20:55 UTC
Labels: feat: app settings, stat: need more info
