### ISSUE TITLE
Reply button not opening thread 

### ISSUE THREAD

**Issue by PriyaBihani** [RocketChat/Rocket.Chat#21542] opened 2021-04-13 11:26 UTC
### Description:

When i click on reply button in Rocket.Chat a thread should open, but instead nothing happens.

### Steps to reproduce:

1. Go to "open.rocket.chat"
2. Go to any message with replies.
3. Click on reply

### Expected behavior:

A thread should open

### Actual behavior:

Nothing happens

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by PriyaBihani** [comment] 2021-04-13 11:26
I'm working on this issue

**Comment by Darshilp326** [comment] 2021-04-13 13:42
@PriyaBihani Hey I am not able to reproduce the issue on localhost. I know it's on our open server.

https://user-images.githubusercontent.com/55157259/114562345-0ea54a00-9c8c-11eb-9907-fe2cacf7d642.mp4

**Comment by shrinish123** [comment] 2021-04-13 13:46
Yes @PriyaBihani even  I am not able to replicate this issue on my localhost server

**Comment by johncrisp** [comment] 2021-04-13 23:31
I think this was an issue with an update on open.rocket.chat earlier today which has been  resolved.
Please confirm & close accordingly.
Thanks.

**Comment by PriyaBihani** [comment] 2021-04-14 02:21
@johncrisp it hasn't been resolved yet

**Comment by ankar84** [comment] 2021-04-14 08:33
Confirm that issue on open
![thread](https://user-images.githubusercontent.com/4023037/114679715-18bf5b00-9d15-11eb-8723-922dfa9c1ec9.gif)

**Comment by johncrisp** [comment] 2021-04-14 17:03
FYI I understand that there is a fix being worked on.
Not sure whether this Issue will be linked but I'll keep an eye out.

**Comment by ggazzo** [comment] 2021-04-16 18:21
closed by https://github.com/RocketChat/Rocket.Chat/pull/21567

**Closed by ggazzo** 2021-04-16 18:21 UTC
