### ISSUE TITLE
Delete icon still shows for messages after set to false

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat#8040] opened 2017-09-05 03:35 UTC
* Version of Rocket.Chat Server: 0.58.2

I have set the delete message to block after 1 minute, but the messages still have the delete icon showing up and can successfully delete the messages.

After that i tried to disable it completely and see if it works, still the same.  
Administration -> Message -> Allow Message Deleting.

**Comment by mmarif4u** [comment] 2017-09-05 13:34
Is this related to **ui redesign**?, as we are using 0.58.2 and i did not see any ui changes so far compare to 0.59 rc.

**Comment by mmarif4u** [comment] 2017-09-09 16:48
Just to update here, normal users cant see the button after 1 minute(which is set to 1) or if disable it. Which is fine so far.

But the strange part is Admin cant see the Edit button, but can see the Delete. Maybe i was too early to it, as i guess Admin should always see both buttons if i am getting it right. But in this case Edit is missing for Admins. Or should it behave the same for users and Admins(hide)?

**Comment by cyclops24** [comment] 2017-10-03 03:42
Part of #8175

**Comment by ggazzo** [comment] 2018-07-04 20:41
hey @mmarif4u I cant reproduce this problem on > 0.65, I will close this issue, any problem let me know

**Closed by ggazzo** 2018-07-04 20:41 UTC
Labels: subj: ui/ux, type: bug
