### ISSUE TITLE
Rocket Chat deployment with custom modifications

### ISSUE THREAD

**Issue by distlibs** [RocketChat/Rocket.Chat#8513] opened 2017-10-17 12:39 UTC
### Description:
How to deploy Rocket Chat with own modifications? When I developing i run `meteor npm start` command.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-develop
* Operating System: Ubuntu 16.04.2
* Deployment Method(snap/docker/tar/etc): git clone
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: 4.8.4 - x64

**Comment by MartinSchoeler** [comment] 2017-10-17 17:48
Duplicate of RocketChat/Rocket.Chat.Docs#375

**Closed by MartinSchoeler** 2017-10-17 17:48 UTC
