### ISSUE TITLE
Add user groups support - "@support / @admins"

### ISSUE THREAD

**Issue by tuxmartin** [RocketChat/Rocket.Chat#11926] opened 2018-09-01 22:32 UTC
Please add `User group` feature as in Slack. It is very useful.

https://get.slack.help/hc/en-us/articles/212906697-Create-a-user-group

For example: I have channel with 20 users. 5 users are customers, 10 developers and 5 supports. If customer need to quickly solve problem only select `@support`. In `@support` group will be all 5 users from support and mention to `@support` notified everyone in this group.

**Comment by kaiiiiiiiii** [comment] 2018-09-02 07:29
Duplicate of #7043

**Closed** 2018-09-02 09:26 UTC
