### ISSUE TITLE
[BUG][API] sendMessage API is returning a non-related developer warning

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#9054] opened 2017-12-08 20:07 UTC
### Description:

New **sendMessage** API is returning a **developerWarning** property that's not related.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.0-develop

### Expected behavior:

- Should not return the **developerWarning**;

### Actual behavior:

```
:method: POST
:scheme: https
:path: /api/v1/chat.sendMessage
:authority: foo.rocket.chat
accept: */*
content-type: application/json
x-auth-token: foobar
content-length: 102
accept-encoding: br, gzip, deflate
user-agent: Rocket.Chat/127 CFNetwork/893.14 Darwin/17.3.0
accept-language: en-us
x-user-id: Xx6KW6XQsFkmDPGdE

{
  "message" : {
    "rid" : "GENERAL",
    "_id" : "yoL7lV0jU6F41moLfi",
    "msg" : "Message text."
  }
}

:status: 200
access-control-allow-origin: *
cache-control: no-store
content-encoding: gzip
content-type: application/json
date: Fri, 08 Dec 2017 20:00:10 GMT
pragma: no-cache
vary: Accept-Encoding
x-instance-id: xSRJaNFk2Gt2tTbmr
content-length: 351

{
  "message": {
    "rid": "GENERAL",
    "_id": "yoL7lV0jU6F41moLfi",
    "msg": "Niiice!",
    "ts": "2017-12-08T20:00:10.575Z",
    "u": {
      "_id": "Xx6KW6XQsFkmDPGdE",
      "username": "rafael.kellermann",
      "name": "Rafael Kellermann Streit"
    },
    "mentions": [],
    "channels": [],
    "_updatedAt": "2017-12-08T20:00:10.576Z"
  },
  "success": true,
  "developerWarning": "[WARNING]: The \"usernames\" field has been removed for performance reasons. Please use the \"*.members\" endpoint to get a list of members/users in a room."
}
```

**Comment by VibhorCodecianGupta** [comment] 2017-12-11 19:39
#9072 Resolves the issue. Detailed discussion at #9037

**Comment by graywolf336** [comment] 2017-12-11 20:50
Duplicate of #9037

**Closed by graywolf336** 2017-12-11 20:50 UTC
Labels: feat: api
