### ISSUE TITLE
Hide counter setting does not work

### ISSUE THREAD

**Issue by piotrkochan** [RocketChat/Rocket.Chat#12689] opened 2018-11-21 10:18 UTC
### Description:

Room setting "Hide counter" does not work because counter is always visible regardless of the configured toggle:

![](https://i.imgur.com/FpapWfp.png)

And yes, I'm using not the latest version but I don't see any fix in the changelog related to this bug.

### Steps to reproduce:

1. Toggle Hide Counter in room 1.
2. Go to other room
3. Wait for message in room 1.

### Expected behavior:

No counter in room 1.

### Actual behavior:

Counter is visible. There is no notification in "unread messages" section though

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.2
- Operating System: ubuntu
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: no
- NodeJS Version: 8.11
- MongoDB Version:

**Comment by bregolin** [comment] 2019-01-25 18:34
Same bug here. I'm on server v0.73.2 and client v2.14.7. Client runs on Arch Linux, server runs on Linux 4.15.0-1026-gcp

**Comment by aspiers** [comment] 2019-01-28 16:42
Same here with server 0.73.2 running on SUSE Linux Enterprise Server 12.  I'm not sure how to find out my client version.

**Comment by aspiers** [comment] 2019-08-16 08:16
I think this is a duplicate of #11609.

**Comment by dusatvoj** [comment] 2019-12-09 16:00
Any updates here?

**Comment by engelgabriel** [comment] 2020-03-19 18:26
Closing this one in favor of #11609.

**Closed by engelgabriel** 2020-03-19 18:26 UTC
Labels: stat: triaged, subj: ui/ux, type: bug
