### ISSUE TITLE
gateway.rocket.chat dosen't work 

### ISSUE THREAD

**Issue by netdevfighter** [RocketChat/Rocket.Chat#4929] opened 2016-11-12 22:50 UTC
Your Rocket.Chat version: 0.45.0

I get no push notification to my phone. :( I have it already tried with the test button at the admin page.
Has someone any idea why?

**Comment by Nemra1** [comment] 2016-11-13 16:10
same issu her

**Comment by maxlinux2000** [comment] 2016-11-13 20:14
I think that the problem is in the core that can't send push message at all.
Same problem using my own google gcm certificate and rocket.chat.cordova app and following the docs for the configuration.
This summer the push messages was working.

Note that the Logs tell me that the push messages was send without errors, but the message never arrived to my phone.
There are a lot of people whit same problem in rocket.chat.cordova.

**Comment by maxlinux2000** [comment] 2016-11-14 13:28
ok, push notifications are now working  in 0.46.0-develop.... in  rocket.chat.cordova app usign gcm

I'm waiting for the new release :)

I think that gateway.rocket.chat problem is fixed but I cannot test it now with official app and the gateway.

**Comment by Nemra1** [comment] 2016-11-14 13:35
Push notifications never work with me..since  using Rocket Chat...

**Comment by g0ldstrike** [comment] 2016-11-14 15:22
Thanks again for the info @maxlinux2000 . According to the [push notifications docs](https://rocket.chat/docs/administrator-guides/push-notifications/) page, setting the Enable Gateway option to False, will cause your own server to function as its own gateway, instead of using the https://rocket.chat server. Do you know whether this will also work then?

**Comment by maxlinux2000** [comment] 2016-11-14 17:48
If you are using the gateway, you need to use the official app from Google playstore. 

If you want to build your own app you need to setup rocket chat server with gcm API keys of Google console and copy them to the 2 config files in the Rocket.chat.Cordova.

**Comment by Nemra1** [comment] 2016-11-14 18:09
@maxlinux2000 im using official app and push Notifications  works 2 day from 40 day..to now icant get any Notifications any more

**Comment by Nemra1** [comment] 2016-11-14 18:16
Like u see
Send push notifications to 3 device and nothing happend
![screenshot_2016-11-14-20-12-11](https://cloud.githubusercontent.com/assets/22897987/20276916/1db284e4-aaa7-11e6-865f-a9efc44ba2ba.png)

**Comment by g0ldstrike** [comment] 2016-11-14 19:16
@Nemra1 Have you cloned the latest server version (0.46.0-develop), and built it using the [instructions](https://github.com/RocketChat/Rocket.Chat#quick-start-for-code-developers)?

**Comment by maxlinux2000** [comment] 2016-11-14 19:31
The 45 is bugged. Try the 46 development

**Comment by Nemra1** [comment] 2016-11-14 19:32
@maxlinux2000 any documents for how to install it?

**Comment by g0ldstrike** [comment] 2016-11-14 20:00
@Nemra1 Yes, see the link in my previous comment.

**Comment by Nemra1** [comment] 2016-11-14 20:07
Sorry i wass not see that..im try now and back after testing

**Comment by Nemra1** [comment] 2016-11-15 13:28
I get many error when run developed version so i think must waite v4.6

**Comment by maxlinux2000** [comment] 2016-11-15 13:30
Ate you in Ubuntu 16.04?

**Comment by Nemra1** [comment] 2016-11-15 13:38
@maxlinux2000 Centos 6 -64x
And this commands git branch --set-upstream-to=origin/develop develop ..givme unkown parameters

**Comment by maxlinux2000** [comment] 2016-11-15 13:41
I'm to dentists now. When I come back to my house y will send you my script. I'm downloading the last .tar instead using git.

**Comment by Nemra1** [comment] 2016-11-15 13:44
Me too and this error come back from git script
https://github.com/RocketChat/Rocket.Chat#quick-start-for-code-developers

**Comment by maxlinux2000** [comment] 2016-11-16 11:51
sorry for delay....

```
#!/bin/bash

# this is only for debian based linux versions
#update system
#apt-get update
#apt-get -y upgrade

rm rocket.chat.tgz
rm -rf Rocket.Chat.old 2> /dev/null
mv Rocket.Chat Rocket.Chat.old

# if your sistem doesn't have curl installed, you can use wget instead
# release version
#curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tgz

# development version
curl -L https://rocket.chat/releases/develop/download -o rocket.chat.tgz

tar zxvf rocket.chat.tgz

mv bundle Rocket.Chat
cd Rocket.Chat/programs/server
npm install
cd ../..
echo "DONE!!"
```

**Comment by Nemra1** [comment] 2016-11-16 16:41
@maxlinux2000  nice back max..this script work with centos 6.4 or only debian?
and if this script work with centos . i think started from her
# development version
curl -L https://rocket.chat/releases/develop/download -o rocket.chat.tgz

tar zxvf rocket.chat.tgz

mv bundle Rocket.Chat
cd Rocket.Chat/programs/server
npm install
cd ../..
 export PORT=3000
export ROOT_URL=http://cdn.nemra-1.com:3000/
export MONGO_URL=mongodb://localhost:27017/rocketchat

 node main.js
====================================
only this??? nothing more or i need another command?

**Comment by Nemra1** [comment] 2016-11-16 17:58
hubot still not workin 
![2016-11-16_073020](https://cloud.githubusercontent.com/assets/22897987/20359072/efa0dea2-ac36-11e6-9599-6e0aabd46023.png)

**Comment by maxlinux2000** [comment] 2016-11-16 19:02
1. Yes... centos is a linux, so  the script must to works.
2. well... hubot is not important for me.

**Comment by Nemra1** [comment] 2016-11-16 19:05
I KNOW its not important but i need to fix if u have any tips pls told me

**Comment by maxlinux2000** [comment] 2016-11-16 23:14
Sorry, but I don't know how to fix it.

**Comment by Mte90** [comment] 2017-01-24 20:05
Often there are no notifications on desktop and mobile with that gateway but in the log there are no errors, I am using also the latest version.

**Comment by MartinSchoeler** [comment] 2017-07-14 18:47
The hubot issue should be resolved by now, and @maxlinux2000 solution should work. I will close this issue. If the problem persist, please reopen this

**Closed by MartinSchoeler** 2017-07-14 18:47 UTC
Labels: feat: notification, subj: mobile, type: bug
