### ISSUE TITLE
[Bug] LDAP users with umlauts get broken names

### ISSUE THREAD

**Issue by boldt** [RocketChat/Rocket.Chat#8507] opened 2017-10-16 10:08 UTC
### Description:

Since we're located in Germany, we have plenty of users with umlauts. Our rocketchat is configured with LDAP. If an user loggs in with LDAP, his name gets broken, as an example: `ö` get `Ã¶`.

If the user changes this manually, and logs in again, the name is synchronized and breaks up again.

I installed version 0.58.4 via docker.

**Comment by MartinSchoeler** [comment] 2017-10-16 11:47
Duplicate of #3451

**Closed by MartinSchoeler** 2017-10-16 11:47 UTC
