### ISSUE TITLE
Emoji selector persistence and readability/off-screen errors in Cordova

### ISSUE THREAD

**Issue by mccambridge** [RocketChat/Rocket.Chat#3843] opened 2016-07-22 19:09 UTC
Your Rocket.Chat version: 0.35

On the mobile app (iOS 9.3.2), in a message, I click the emoji icon to display the emoji menu and then select the happy face and click (return). The emoji is then submitted as my message. But then the emoji menu won't go away (dismiss) so I can see the message area anymore. Navigating to another channel and then returning to the original channel where you saw the error doesn't make the error disappear.

And when you trigger the emoji menu by typing a colon ':', you see a list but cannot scroll. Now maybe the intent was not for the user to scroll but rather type more characters, but even if that was the case, its poor UX for our users, try ':s' and see what happens. Users will not know the shorthand for every emoji to narrow down the list. Maybe its better if mobile emoji works like it does over the R.C web client?

**Comment by mccambridge** [comment] 2016-07-25 21:33
Can anyone confirm this behavior?

**Comment by timkinnane** [comment] 2016-07-28 02:47
I had a similar error on the mac desktop app with demo.rocket.chat. Screen attached.

The Search Emoji menu appears on first load. Reloading the window gets rid of it, but it comes back sometimes and I've seen it in the past too, only currently is it so persistent.

![screenshot 2016-07-28 12 20 43](https://cloud.githubusercontent.com/assets/1774379/17199601/678f65d2-54c1-11e6-8c99-7bfae991bbfb.png)

**Comment by timkinnane** [comment] 2016-07-28 02:49
Dupe of #3835, #3570

**Comment by lochiiconnectivity** [comment] 2016-08-12 14:56
+1 , we experienced this with users, and suspect the EmojiOne meteor package, in the debugger users get errors in the console at or around [here](https://github.com/RocketChat/Rocket.Chat/blob/f5cde50dd4702651ef68b3d32c220382bd1e5c05/packages/rocketchat-emojione/lib/EmojiPicker.js#L95), the object being null (and this is not handled), which makes me think that we don't reach close()

**Comment by mccambridge** [comment] 2016-08-15 18:02
Just looked further into this. What I thought was a scroll issue is really just the app only returning 10 suggestions. So I guess it's not really a bug for me. So the second part of the bug probably isn't really a bug so much as a design decision.

And I can no longer reproduce what is described in the first paragraph. I'm going to close this. Looks like the rest of the commenters were seeing something different, but I suggest filing as its own bug

**Comment by lochiiconnectivity** [comment] 2016-08-15 18:07
Don't be too hasty to close, we reproduced it exactly as shown previously ![3843](https://cloud.githubusercontent.com/assets/4155305/17673979/672c1d2a-631b-11e6-852b-e4024b5a4785.png)

**Comment by mccambridge** [comment] 2016-08-15 18:07
That wasn't the bug I reported

**Comment by lochiiconnectivity** [comment] 2016-08-15 18:09
you originally said in the first part of your report 
"On the mobile app (iOS 9.3.2), in a message, I click the emoji icon to display the emoji menu and then select the happy face and click (return). The emoji is then submitted as my message. But then the emoji menu won't go away (dismiss) so I can see the message area anymore." , that's exactly what is happening here.

**Comment by mccambridge** [comment] 2016-08-15 18:10
Interesting. What I was seeing was actually happening in a different context. Okay, I'll reopen for you guys! ;)

**Comment by mixrat** [comment] 2016-09-01 21:31
Same issue here in Rocket.Chat 0.37.1
Problem goes away when I restart the Rocket.Chat instance.
Happens about once a week.

**Comment by engelgabriel** [comment] 2017-01-13 12:58
This was fixed long time ago :)

Also improved by #5531

**Closed by engelgabriel** 2017-01-13 12:58 UTC
Labels: subj: ui/ux, type: bug
