### ISSUE TITLE
Unread status on channel list

### ISSUE THREAD

**Issue by savikko** [RocketChat/Rocket.Chat#9894] opened 2018-02-26 09:35 UTC
Version 0.62.rc-2.

Seems that default channel list does not show channel unread-status (by emphasizing it). All channels seem to be on "all read" -mode.
Channel search shows that correctly.

**Comment by karlprieb** [comment] 2018-02-28 22:05
Hey @savikko thank your for your report. Can you add a screenshot, it will be easier to us to identify this bug.

**Comment by karlprieb** [comment] 2018-04-15 04:29
@savikko I can't reproduce this behavior, so I'll close this issue.

**Closed by karlprieb** 2018-04-15 04:29 UTC
Labels: stat: waiting response, subj: ui/ux, type: bug
