### ISSUE TITLE
Cannot reload app in Firefox

### ISSUE THREAD

**Issue by timkinnane** [RocketChat/Rocket.Chat#10003] opened 2018-03-05 03:17 UTC
### Description:

I've had this issue a couple times in open.rocket.chat since I think the 0.62 update.
Today it happened after my sidebar rooms list disappeared (which has also happened in Android), I tried to reload the app and client errors prevent it from loading, even opening a new tab doesn't bring it back. The only way I've found to resolve it is use Chrome for a while, until Firefox forgets the session and I can start again. I've tried it every few days and I can only ever manage to use Rocket.Chat in FF for a few hours at best before it breaks again.

### Server Setup Information:

open.rocket.chat - since ~v0.62

### Steps to Reproduce:

Can't say exactly, try using the app in Firefox consistently for a few hours. If it can't be reproduced by anyone, maybe its my browser, but I only have a few very widely used extensions and my browser and OS are up to date.

### Expected behavior:

Reload should re-render and fix any client bugs, like rooms list disappearing.

### Actual behavior:

Reload fails and can no longer use app in any Firefox tab.

### Relevant logs:

```
Exception from Tracker recompute function: undefined
85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js:1:6367

TypeError: r.initialSubviews is null undefined
85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js:1:6367

changedAt/<@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:87:29706
e.nonreactive@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:43:4492
changedAt@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:87:29612
p/<@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:81:2002
A.forEach@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:71:996
p@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:81:1895
observe/u</<@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:81:846
e.nonreactive@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:43:4492
observe/u<@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:81:646
e.Computation.prototype._compute@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:43:2346
e.Computation.prototype._recompute@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:43:2599
e._runFlush@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:43:3796
a@https://open.rocket.chat/85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js?meteor_js_resource=true:1:2690
 undefined
85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js:1:6367

TypeError: chatMessages[u.openedRoom] is undefined
```

**Comment by timkinnane** [comment] 2018-03-05 06:37
Yes, white screen, with the logged errors in console. Firefox 58.0.2

**Comment by rodrigok** [comment] 2018-03-08 12:14
@timkinnane can you test now? We are running version 0.62.1

**Comment by timkinnane** [comment] 2018-03-08 12:37
@rodrigok - Just tested and had the same issue. Errors like:

```
Exception from Tracker recompute function: undefined
TypeError: e.getDate is not a function undefined
...
Exception from Tracker recompute function: undefined
TypeError: r.initialSubviews is null undefined
```

and

```
Error getting your geolocation 
PositionError { code: 3, message: "Position acquisition timed out" }
```

It figured it was something cached from before the update, so I tried a "forget about site" and it worked, although was quite slow to load and still had errors in console.

```
Exception from Tracker afterFlush function: undefined
85b95b6c461d9ea5aa30e778b6ec375dfd1e080c.js:1:6367
TypeError: e is null undefined
```

**Comment by rodrigok** [comment] 2018-03-08 16:59
Can you execute `RocketChat.CachedCollectionManager.clearAllCache()` and reload to test?

**Comment by ggazzo** [comment] 2018-06-11 18:23
@timkinnane can you reproduce the problem? because I tried here again and again (and over some time), and looks good now...

**Comment by ggazzo** [comment] 2018-06-14 22:06
@timkinnane I will be closing this issue because I could't reproduce and I think its fixed, any problem please open again

**Closed by ggazzo** 2018-06-14 22:06 UTC
Labels: stat: board-postponed, subj: ui/ux, type: bug

**Comment by timkinnane** [comment] 2018-06-15 08:10
Yep, not having issues in FF now but I haven't used it much, will reopen if it comes back. Thanks.
