### ISSUE TITLE
LDAP sync of usernames with umlaut ist not correct

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat#9087] opened 2017-12-12 12:50 UTC
### Description:

Usernames with umlauts are not correct while been created via LDAP sync.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Ubuntu LTS 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances:  1
* DB Replicaset Oplog: active
* Node Version: 4.8.4

### Steps to Reproduce:

1. Create a new User via LDAP sync - username setting is: #{givenName}.#{sn}
2. Username should be dirk.wöhler
3. Username is dirk.wohler
4. Real Name is correct 

### Expected behavior:

The username should be dirk.wöhler or dirk.woehler

### Actual behavior:

The username is dirk.wohler

![image](https://user-images.githubusercontent.com/26709898/33885308-43416672-df43-11e7-9c74-74f983320738.png)

**Comment by MartinSchoeler** [comment] 2017-12-13 11:37
duplicate of #3451

**Closed by MartinSchoeler** 2017-12-13 11:37 UTC
