### ISSUE TITLE
admin can't join a guest-user to a channel via API, if he(admin) isn't in that channel

### ISSUE THREAD

**Issue by maxdwit** [RocketChat/Rocket.Chat#5744] opened 2017-01-24 13:19 UTC
Rocket.Chat Version:  0.50.0 ( Ubuntu/snapd)
Running Instances:  1
DB Replicaset OpLog: disabled
Node Version: v4.6.2

_admin with full rights can't join a user to a channel via API, if he (the admin) isn't in the channel._

Guest role: create-d  / view-I-room ( nothing else)
Steps:
1. login as admin via api/v1/login as admin. Token and userID is used for subsequent steps
2. create a user via API whilst putting him into the role "guest". verified=yes, joinDefaultChannels=false
3. Read _id from channel "test" via API channels.list. This is a not protected/private chat.
4. call channels.invite with  userid, channelid
`{
  "success": false,
  "error": "Not allowed [error-not-allowed]",
  "errorType": "error-not-allowed"
}
`
Second test:
1. logged in as administrator via api
2. read _id from channel  "test" via API channels.list.
3. invited user "admin" whos is currently logged in via api to a channel. 
4. This worked.

Expected behaviour:  admin can join any user to a channel and/or private channel. 

I did not test what would happen if I a new created user is in the group "user", as this is no use case for me.

**Comment by MartinSchoeler** [comment] 2017-01-24 14:11
duplicate of #5683

**Closed by MartinSchoeler** 2017-01-24 14:11 UTC
