### ISSUE TITLE
Google OAuth not working on mobile app

### ISSUE THREAD

**Issue by LauraHilliger** [RocketChat/Rocket.Chat#6876] opened 2017-05-04 10:56 UTC
Rocket.Chat Version: 2.5.0
Running Instances: 
DB Replicaset OpLog:
Node Version:

My colleague and I both just download rocket.chat from the google play store and are hitting the same error. We can't login to the app with OAuth. 

See image for full error:

![oauth-error](https://cloud.githubusercontent.com/assets/539017/25700636/d21b2c90-30c8-11e7-89a9-b91e53bce53f.png)

**Comment by MartinSchoeler** [comment] 2017-05-04 12:51
Hey @LauraHilliger are you using the cordova app (Rocket.Chat) or the native app (Rocket.Chat+)?

**Comment by LauraHilliger** [comment] 2017-05-04 13:02
apparently cordova - installing the other one...

**Comment by ericzolf** [comment] 2017-05-18 06:56
I can confirm the issue on Rocket.Chat whereas Rocket.Chat+ works. I have now both apps installed, but getting back Rocket.Chat would be good as long as Rocket.Chat+ isn't on par in terms of features.

**Comment by RichardFoxworthy** [comment] 2017-06-30 00:41
Confirm this issue on Cordova app. Its a big problem for us...

**Comment by RichardFoxworthy** [comment] 2017-09-20 00:44
Bump this issue. Prevents use of Google OAuth via Cordova app

**Comment by kkumaresan** [comment] 2018-04-09 18:49
Hi, we at Mongrov have developed a react-native mobile client library for Rocket.Chat. Please check this url: https://github.com/mongrov/roverz . Works both on iOS and Android. If you get a chance, do check this project for a comprehensive native mobile app using Rocket.Chat. We welcome your feedback 😃

**Comment by Hudell** [comment] 2018-06-06 20:12
I'll be closing this since it is related to the old Cordova app. If necessary, please open the issue again on the app's repository.

**Closed by Hudell** 2018-06-06 20:12 UTC
Labels: subj: mobile, type: bug
