### ISSUE TITLE
emojis are not rendered properly when used with markdown symbols.

### ISSUE THREAD

**Issue by Ablesius** [RocketChat/Rocket.Chat#14638] opened 2019-05-27 08:45 UTC
### Description:

When I use the `/me` command and add an emoji (either custom or builtin), the emoji is rendered as its text representation instead, e. g. `:D` instead of the grin smiley.

### Steps to reproduce:

1. type `/me uses emoji :D`

### Expected behavior:

I see italic _@ablesius uses emoji (emoji here)_

### Actual behavior:

I see italic _@ablesius uses emoji :D_

**Comment by Hudell** [comment] 2019-05-27 17:11
Rocket.Chat changes the `/me uses emoji :D` to `_uses emoji :D_`. And that is failing to render the emoji because of the markdown italic symbol. The same thing happens when writing bold text.

Emojis that follow the "colon name colon" pattern  (for example: `:thinking:`) do not have this problem.

**Comment by Ablesius** [comment] 2019-05-27 17:50
> Emojis that follow the "colon name colon" pattern (for example: `:thinking:`) do not have this problem.

That is nice to know, but some emojis are not written this way :) is there some way to fix the issue?

**Comment by Ablesius** [comment] 2020-10-17 20:38
Well, the problem is not resolved yet!

**Comment by Ablesius** [comment] 2020-12-04 15:23
any updates on when this will be tackled?

**Comment by PapsOu** [comment] 2021-03-03 14:05
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/11214 ?

**Comment by ggazzo** [comment] 2021-09-18 04:42
duplicated

**Closed by ggazzo** 2021-09-18 04:42 UTC
Labels: type: bug, subj: ui/ux
