### ISSUE TITLE
LDAP "bind" paramater ignores users in the subgroups that are members of the bound group (no recursive user import)

### ISSUE THREAD

**Issue by finius** [RocketChat/Rocket.Chat#1914] opened 2016-01-14 13:59 UTC
Only ActiveDirectory/LDAP users that are directly added to the bound RocketChat access ldap group are getting access to RocketChat. Users within groups that are menbers of the bound acces Group are ignored/not imported. So there seems to be no recursive user Import, even if the "sub" param is set to the "filter sting" of the bind search.

**Comment by engelgabriel** [comment] 2016-01-14 20:25
@finius can you help to fix this?

**Comment by finius** [comment] 2016-01-14 23:03
I must confess, I am no LDAP/AD expert at all. Maybe this can be solved by simply modifying the filter string. Maybe the developers take a look at ownCloud and it's LDAP integration. Meanwhile it works like a charm and has already a long evolution behind itself.

**Comment by finius** [comment] 2016-01-18 16:06
I haven't made any progress in this matter. Any AD/LDAP experts in here?

**Comment by rodrigok** [comment] 2016-02-12 19:11
@Megatronic79 Can you help us here?

**Comment by Megatronic79** [comment] 2016-02-12 19:21
So the issue is with users that say belong to a group within a group not authenticating?

Such as domain.com (OU) > groups (OU) > ROCKET_CHAT > SUBGROUP (users live here) ?

**Comment by finius** [comment] 2016-02-12 20:22
Right. Say, ldap authentification is enabled for a group ROCKETCHAT. Users that belong to that group (are direct members of this group) can authenticate. If you now add a group VIPUSER as a member to the group ROCKETCHAT, the members of VIP can't authenticate...

**Comment by Megatronic79** [comment] 2016-02-12 20:25
Ok thanks for the confirmation @finius we can look at that one.

**Comment by engelgabriel** [comment] 2016-03-04 16:15
Hi guys, do we know if this is still an issue?

**Comment by plutz** [comment] 2016-05-24 15:18
This is not a problem with RocketChat, but with the LDAP search. To correct this you can use Matching Rule OID. For this case change `MemberOf=SG` to `MemberOf:1.2.840.113556.1.4.1941:=SG` Where SG is the parent security group.

See https://msdn.microsoft.com/en-us/library/aa746475(VS.85).aspx for more information.

I found this from http://stackoverflow.com/questions/6195812/ldap-nested-group-membership

**Comment by EmmanuelTsouris** [comment] 2016-06-14 15:24
@plutz thanks for the info, will review and see i it helps our issue.

**Comment by rndmh3ro** [comment] 2017-05-03 10:29
@plutz solution worked for me.

**Comment by MartinSchoeler** [comment] 2017-07-12 16:07
Closing this for @plutz solution. If the problem persists, please reopen this with updated details. Thanks!

**Closed by MartinSchoeler** 2017-07-12 16:07 UTC
Labels: subj:  Auth - LDAP, type: support
