### ISSUE TITLE
Bug in the attachment text parsing

### ISSUE THREAD

**Issue by ShiroDN** [RocketChat/Rocket.Chat#22867] opened 2021-08-05 10:51 UTC
### Description:

If attachment text with specific characters is sent to the incoming webhook then part of the text is not shown in the channel. It looks like there is a problem with some parsing. I checked to see if the message was saved right in the mongo and the message was complete, so the problem is not there.

`"attachments":[{"text":"```First line that will not be shown.\n Second line that is fine.\n Third line that is fine too.\n```"}]`

The problem is in a combination of "\`\`\`" and first "\n". If either "\`\`\`" or "\n" is removed, then everything is fine.

### Steps to reproduce:

1. Send webhook message:
`curl -X POST -H 'Content-Type: application/json' --data '{"text":"Test message","attachments":[{"text":"```First line that will not be shown.\n Second line that is fine.\n Third line that is fine too.\n```"}]}' https://rocket.domain.com/hooks/xxxxx`
2. Verify message in the channel

### Expected behavior:

3 lines of text should be shown in the channel.

### Actual behavior:

Only the second and third line is shown in the channel.

![image](https://user-images.githubusercontent.com/36225991/128334901-171a47bb-9dc6-4d09-b177-e1ab73b00ea5.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.13.2,  3.17.0 (tested versions) 
- Operating System: Debian 10
- Deployment Method: docker
- Number of Running Instances: 5
- DB Replicaset Oplog: yes
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: chrome, chromium, firefox...
- Operating System: Linux, Windows

**Comment by fdellwing** [comment] 2021-08-06 05:49
This is not a bug, but how Markdown works. There should be a newline after the opening and before the closing backticks.

**Comment by ShiroDN** [comment] 2021-08-06 08:19
Ou, I see... But this is actually how the papertrail is generating alerts with their slack webhook integration. I don't see a way, how to change it without globally disabling markdown in rocketchat administration.

**Comment by fdellwing** [comment] 2021-08-06 08:29
Open an upstream ticket, RC is working as intended here. You can confirm this in GitHub too:

```First line that will not be shown.
Second line that is fine.
Third line that is fine too.
```

**Comment by debdutdeb** [comment] 2021-08-10 09:22
Thanks for the assist Fabian!! 

Hi Tomas 👋🏼 

Fabian is right, rocketchat is working as expected. 

>  I don't see a way, how to change it without globally disabling markdown in rocketchat administration.

Use an incoming webhook script to parse and change the data i.e. add a newline after "```". I don't know the structure of the incoming data, if you can provide me the json structure, I can potentially help you with a script.

**Comment by debdutdeb** [comment] 2021-08-12 05:28
Great! Glad you figured it out :D 

Closing the issue then. If you have any more problems in the future, do not hesitate to ask in our forum or the open server :)

**Closed by debdutdeb** 2021-08-12 05:28 UTC
