### ISSUE TITLE
Webhook integration showing extra "<br />" elements

### ISSUE THREAD

**Issue by lurch89** [RocketChat/Rocket.Chat#22812] opened 2021-07-29 16:01 UTC
### Description:

As of an upgrade to 3.16.3, a webhook integration shows extra `<br />` tags after elements of an attachment. Previously these were hidden/not present.

### Steps to reproduce:

Send call to incoming webhook to generate message in a channel.

### Expected behavior:

No `<br />` tags after attachment data.

### Actual behavior:

Extra `<br />` added to attachments.

![image](https://user-images.githubusercontent.com/7109596/127525731-3db3a223-1316-4bfb-a81e-bb1a35d48630.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: Ubuntu 18.04
- Deployment Method: Snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.14

### Client Setup Information

- Desktop App or Browser Version: Desktop 3.2.3
- Operating System: Win 10 Pro
- Also present on web-based app, Chrome91 on Win10

### Additional context

No changes have been made to the calling app, which uses Slack's .NET library. Calling app is not recompiling or auto-updating.

**Comment by johncrisp** [comment] 2021-07-29 16:20
Please search open and closed issues before opening a new one.

Just change the filter from:

`is:issue is:open `

to 

`is:issue`

Closing as a duplicate of #22701 and 22734 amongst others.

**Closed by johncrisp** 2021-07-29 16:20 UTC
