### ISSUE TITLE
How to update Rocket.Chat on Docker without Docker compose installed

### ISSUE THREAD

**Issue by real1900** [RocketChat/Rocket.Chat#15370] opened 2019-09-15 06:16 UTC
How can I  update existing Rocket.Chat instance on Docker? I don't have Docker compose installed. I am not so well versed with Docker , so please bear that in mind during your response. 

Thanks

**Comment by reetp** [comment] 2019-09-15 09:44
@rocket-cat close

Closing notabug.

This seems to be a setup/support issue, not a bug.

Please ask in the forums https://forums.rocket.chat/ or # support at https://open.rocket.chat/

(You ought to have a thorough read of the generic docker documentation)

**Closed** 2019-09-15 09:44 UTC
