### ISSUE TITLE
[Bug] legacy message template diplays nothing

### ISSUE THREAD

**Issue by xmedeko** [RocketChat/Rocket.Chat#26801] opened 2022-09-04 17:40 UTC
### Description:

When i switch Use legacy message template in 5.1.0, then **nothing** is displayed in a chat room.

### Steps to reproduce:

1. Switch My Prefrences > Global > Use legacy message template

### Expected behavior:

See chat messages as in 5.0.5

### Actual behavior:

**Nothing** is displayed.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.1.0

**Comment by ankar84** [comment] 2022-09-06 04:41
Totally confirm that issue on our test 5.1.0 environment.
New template
![image](https://user-images.githubusercontent.com/4023037/188548264-3873525d-a212-457a-9d57-93b2cc839b13.png)
Legacy template
![image](https://user-images.githubusercontent.com/4023037/188548311-e9c1707b-1709-41b3-b0bd-638a92776725.png)

**Comment by Gummikavalier** [comment] 2022-09-06 06:22
I confirm this too. Clearing caches did not help either.

**Comment by fne007** [comment] 2022-09-06 09:17
We are having exactly the same problem using the latest 5.1.0 release. With legacy mode we got empty channels and without Legacy mode we got more or less broken Webhooks. It Would be really great if someone could address this problem.

**Comment by treebes** [comment] 2022-09-06 09:25
Same here.

If legacy off, i can see the messages, but the code view of webhooks gets broken.

**Comment by hugocostadev** [comment] 2022-09-06 12:03
Hi guys, the fix is in progress...

Besides the webhook issue that @treebes mentioned, are you found any other restrictions to start using the new Message Parser? 

It is important to know because our idea is for to everyone use the new Message parser feature. Thanks

**Comment by treebes** [comment] 2022-09-06 12:13
@hugocostadev for us was the onlyone we detected so far, this issue began on the 5.0 realease.

I belive is the same issue from here.
https://github.com/RocketChat/Rocket.Chat/issues/26388

**Comment by Gummikavalier** [comment] 2022-09-06 14:32
For what these are worth, here is my current list of issues with the new template I've been trying to track. Not sure if all not listed fixed are still active issues. Some may have been fixed.
```
The list of problems with the new template:
 * Emoji size issue between web client and mobile client, betraying user being on mobile
 * Resolving reaction names is even worse than in the old template
 * Some links may break depending on characters used (that did not break with the old template)
 * :+1: emoji issue (is translated as a phone number regardless that tel.nos are disabled globally
 * Sometimes after switching the channel the new messages you write, or new reactions you set, just don't appear on the channel until you refresh the window
 * [NEW] Messages don't show at all in legacy message template
 
Ok:
 * [Obsolete] Cozy / Compact did not work, using too much space by default. Likely to be obsolete, use top bar display settings or web client zoom out instead.
 * [Works as intended] Old code blocks break if they don't have a line ending after the triple-` (the original way of operation may have been a bug though)
 * [Fixed] Bridged messages nicks are broken (this is the real no-go for the new template)
 * [Fixed]  : -character issue that always transforms any :'s into emojis after pressing enter
 * [Likely fixed] Link preview content size rendering issues. Could not reproduce anymore.

**Closed** 2022-09-06 14:42 UTC

**Comment by xmedeko** [comment] 2022-09-06 19:54
@hugocostadev Just check this issue tracker, there are **many** problem with the new messge parser, see #26736 and https://github.com/RocketChat/Rocket.Chat/issues/26736#issuecomment-1231816223 for a humble list of **some** of them.

Note: seems to me you have a poor management of issues - some of them are left without reaction, some are duplicate, some has been fixed but not closed, etc.

**Comment by chotaire** [comment] 2022-09-07 08:24
I question the project management as a whole. They release an entirely broken message parser in a new stable major version (is there actually a QA?) and break everyone's installations. They refuse to revert to a previously working state (downgrade is not spuported btw) but take weeks for "we fix it until it works". Then they mention people can just switch to the old message parser, which leaves countless installations in a state of using deprecrated components (how many admins will likely keep an eye on development to revert since the legacy message parser actually works?) instead of simply releasing an update with a revert until the new message parser actually works. Then they even break the legacy message parser, leaving everyone who updated to 5.x with problems. Is any developer actually really testing the message parser, which means using their own software? 

Really guys, a stable version is not a public beta-test. There are currently 2800+ open issues, it looks many of them are never read or cleaned up. And I am getting the idea everyone is just coding random features, someone merges and releases them without actually testing them, and voila there is your stable release, let's hope it works. And if not, instead of fixing it let's release another new version with a new feature no user has asked for (that new homepage in 5.1.0 for example, which can only be disabled with an enterprise license).

The Rocket.Chat project was severely damaged with the new message parser, more specifically, how it was handled. It's absolutely ok to release something buggy, we're humans, but it's not ok not to revert!

PS. Just for the list that doesn't exist: Image previews of external URLs are often cropped and when clicked to enlarge nothing happens.

**Comment by chotaire** [comment] 2022-09-07 08:41
Oh and because nobody else mentions it: The legacy message parser will work again in version **5.1.1**, see https://github.com/RocketChat/Rocket.Chat/pull/26819

**Comment by hugocostadev** [comment] 2022-09-07 14:53
Hi, @chotaire I appreciate your feedback, we will address the issues mentioned in this discussion and discuss internally better ways to maintain and ship new features.

**Comment by chotaire** [comment] 2022-09-07 15:12
Thanks @hugocostadev that is good news.

**Comment by dudanogueira** [comment] 2022-09-08 13:16
Hi there!

Just to let you know, we are aware of those issues, and working to fixing them. 

As we discussed in our [monthly Open Call](https://go.rocket.chat/i/community-open-call), we are refactoring a lot of code from JS to TS, and the focus for the next quarters are all about QA and code test coverage.

We also would like to invite you to help us testing all this **before the release**. For that, please join our [Beta Testers program/channel](https://open.rocket.chat/channel/beta-testers)

Thanks!

**Comment by Gummikavalier** [comment] 2022-09-08 15:02
Confirmed fixed in RC 5.1.1.

**Comment by engelgabriel** [comment] 2022-09-09 11:01
I appreciate your candid feedback @chotaire, and indeed, we must learn a few lessons from all this. We have been on a mission to improve code quality and stability by refactoring so many components into TypeScript, this makes it hard to reverse back just a component, but we should have been extra careful to get it right in that case. We will do some post-mortem of the situation to ensure we address the mistakes that led to this. I am sorry for all the inconvenience.

**Comment by chotaire** [comment] 2022-09-09 11:23
@engelgabriel I have good feedback too: Your team has done a good job allowing users to switch back to using the legacy message parser in both system and user preferences. This was foresightful. I would have hoped it were the other way around though, because the new message parser wasn't ready yet and should not have become default.

Here is another one for the list: https://github.com/RocketChat/Rocket.Chat/issues/26838

**Comment by engelgabriel** [comment] 2022-09-09 17:23
I've added to https://github.com/RocketChat/Rocket.Chat/projects/57

**Comment by LevyCosta** [comment] 2022-09-12 21:05
Hey @Gummikavalier .
I'm part of the Quality Assurance team here at Rocket, nice meeting you. 
I'm trying to replicate some of the issues you listed but I have some questions. If you could please give me some more info so I can properly reproduce the issues, I may be able to advocate adding them to our Development Cycle. :)

>  * Emoji size issue between web client and mobile client, betraying user being on mobile

1. What exactly is the issue here? Are you saying the sizes are simply "different" and that messes with user expectation? Or are you saying that you are able to get some weirdly sized emoji?

>  * Resolving reaction names is even worse than in the old template

2. I simply don't understand what you mean by "resolving". I'm trying to make sense of it thinking about some kind of "behavior" but I guess you are probably describing a more "code-related" issue. If you could please clarify it in a way I can reproduce it, I'd be grateful.

>  * Some links may break depending on characters used (that did not break with the old template)

3. Could you please exemplify better which links would break? Were you able to recognize why?

>  * Sometimes after switching the channel the new messages you write, or new reactions you set, just don't appear on the channel until you refresh the window

4. I am aware of this issue. I have experienced it myself a few times but unfortunately have not been able to reproduce it consistently. That makes it very hard to work on it for now. If you ever recognize some specific step to reproduce it, do share it with me.

  
Thanks in advance. :)

**Comment by xmedeko** [comment] 2022-09-13 05:47
@LevyCosta Details of issues are described elsewhere, just search all issues from 5.0 release. For a not-complete list see my comment above. (Note, the comment is not list of just two issues, but links to list of issues elsewhere.)

**Comment by LevyCosta** [comment] 2022-09-13 16:49
@xmedeko 
I'll take a look at it. Thanks! :)

**Comment by Gummikavalier** [comment] 2022-09-13 16:51
> Hey @Gummikavalier . I'm part of the Quality Assurance team here at Rocket, nice meeting you. I'm trying to replicate some of the issues you listed but I have some questions. If you could please give me some more info so I can properly reproduce the issues, I may be able to advocate adding them to our Development Cycle. :)
> 
> > * Emoji size issue between web client and mobile client, betraying user being on mobile
> 
>     1. What exactly is the issue here? Are you saying the sizes are simply "different" and that messes with user expectation? Or are you saying that you are able to get some weirdly sized emoji?
> 
> 
> > * Resolving reaction names is even worse than in the old template
> 
>     2. I simply don't understand what you mean by "resolving". I'm trying to make sense of it thinking about some kind of "behavior" but I guess you are probably describing a more "code-related" issue. If you could please clarify it in a way I can reproduce it, I'd be grateful.
> 
> 
> > * Some links may break depending on characters used (that did not break with the old template)
> 
>     3. Could you please exemplify better which links would break? Were you able to recognize why?
> 
> 
> > * Sometimes after switching the channel the new messages you write, or new reactions you set, just don't appear on the channel until you refresh the window
> 
>     4. I am aware of this issue. I have experienced it myself a few times but unfortunately have not been able to reproduce it consistently. That makes it very hard to work on it for now. If you ever recognize some specific step to reproduce it, do share it with me.
> 
> 
> Thanks in advance. :)

Hi!

The issue 1: This seems to have been fixed by now. The issue was that the size of single emojis in a message differed in the new template in the web client depending on whether the single emoji message had been sent with the phone client versus web client.

The issue 2. of "resolving usernames into the real names in reactions". Because of this bug every single reaction to message shows only the incomprehensible username (username we cannot choose, it comes from our account provisioning source) instead of their real names (which is provisioned of course). Because of this bug our users cannot know the names of people who react to their messages. The bug has been around for 3 to 4 years now and hasn't been fixed. Refreshing the web client screen helped for this momentarily with the old template, but with the new template the username remain the only visible clue in all conditions.

The issue 3: I just copypasted my at-the-time-current-gripe-list from month or so ago, so this was only reported to me like this. I assume most links work again as they should. Haven't seen issues since RC 5.1.0 myself, and some of them were caused by the already fixed `https:// translated as emoji in the :/` issue.

The issue 4: Yeah, this seems to have been fixed by now too. I haven't seen it happen anymore since RC 5.1.0.

**Comment by Gummikavalier** [comment] 2022-09-14 12:37
@LevyCosta One more issue in the new template showing the names that contain @-character in the usernames:
https://github.com/RocketChat/Rocket.Chat/issues/26869
