### ISSUE TITLE
User Data Download not working

### ISSUE THREAD

**Issue by rmsmgaspar** [RocketChat/Rocket.Chat#14455] opened 2019-05-10 13:58 UTC
### Description:

When a user select "Download My Data" or "Export My Data" the client comment that an email will be sent and nothing happens

### Steps to reproduce:

1.  Go to "My Account" - "Preferences"
2.  Click on "Download My Data" or "Export My Data"
3.  A popup opens commenting that an email will be sent

### Expected behavior:

Receive email with data

### Actual behavior:

Nothing happens

### Server Setup Information:

- Version of Rocket.Chat Server:  0.74.3
- Operating System: Linux x64
- Deployment Method: docker
- Number of Running Instances: 5
- DB Replicaset Oplog: Enable
- NodeJS Version: v8.11.4
- MongoDB Version: 

### Relevant logs:

34mI20190510-13:30:00.523(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:30:00.547(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:30:00.568(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:30:00.584(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:30:00.600(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:30:00.606(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:42:00.305(0) rocketchat:logger server.js:199 SyncedCron ➔ info Starting "Generate and save statistics". 
[34mI20190510-13:42:00.398(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate and save statistics" again. 
[34mI20190510-13:42:00.625(0) rocketchat:logger server.js:199 SyncedCron ➔ info Finished "Generate and save statistics". 
[34mI20190510-13:42:00.943(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate and save statistics" again. 
[34mI20190510-13:42:00.950(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate and save statistics" again. 
[34mI20190510-13:43:00.983(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate and save statistics" again. 
[34mI20190510-13:44:00.485(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate and save statistics" again. 
[34mI20190510-13:45:00.531(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:45:00.564(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:45:00.575(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:45:00.591(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:45:00.606(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again. 
[34mI20190510-13:45:00.611(0) rocketchat:logger server.js:199 SyncedCron ➔ info Not running "Generate download files for user data" again.

**Comment by zdumitru** [comment] 2019-05-15 09:12
Duplicate of #14143

**Comment by jcatarino** [comment] 2019-05-21 11:21
This needs urgent fix.

**Comment by Hudell** [comment] 2019-05-22 18:12
Duplicate of #14143

**Closed by Hudell** 2019-05-22 18:12 UTC
