### ISSUE TITLE
following reply link twice results in cleaning room view

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#8057] opened 2017-09-06 12:56 UTC
### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.3
* Operating System: Ubuntu 64bit
* Deployment Method(snap/docker/tar/etc): self build bundle
* Number of Running Instances: 1
* DB Replicaset Oplog: Yes
* Node Version: 4.8.4

### Steps to Reproduce:

1. create an answer to a message
2. in the thread click on the link to the old message (jumped to the old message), URL is set to `/channel/test123?msg=eXsawGFZTc7HGqyJ5`
3. scroll down again and again click on on the link to the old message, URL is set to `/channel/test123?msg=eXsawGFZTc7HGqyJ5?msg=eXsawGFZTc7HGqyJ5`

### Expected behavior:

Jump to the old message

### Actual behavior:

room view is clean when doing this twice, because the msg parameter appended two times.

![bug](https://user-images.githubusercontent.com/8544984/30113022-937acbf0-9313-11e7-8ed2-6486dd2cb94b.gif)

**Comment by MartinSchoeler** [comment] 2017-09-06 13:07
Duplicate of #7558

**Closed by MartinSchoeler** 2017-09-06 13:07 UTC
