### ISSUE TITLE
Rocketchat should not send email to cloud without clear approval

### ISSUE THREAD

**Issue by kelvinhammond** [RocketChat/Rocket.Chat#14467] opened 2019-05-11 05:38 UTC
### Description:

Related: https://github.com/RocketChat/Rocket.Chat/issues/14466

When I clicked the authorize button rocketchat sent the email address of the logged in admin user to rocketchat's cloud marketplace. At which point an email was sent.

### Steps to reproduce:

1. Go to marketplace
2. Click show marketplace apps
3. Click on a free app and then click the free button to install it.

### Expected behavior:

Personally Identifiable Information is not sent to rocketchat's cloud server

### Actual behavior:

Personally identifiable information was sent and an email was sent for registration.

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Additional context
- Version of Rocket.Chat Server: 1.0.3
- Operating System: debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.4

**Comment by geekgonecrazy** [comment] 2020-09-17 03:39
I’ll leave the other issue open this seems like duplicate of it

**Closed by geekgonecrazy** 2020-09-17 03:39 UTC
