### ISSUE TITLE
Very slow start up time (takes ~10 minutes)

### ISSUE THREAD

**Issue by miguelmota** [RocketChat/Rocket.Chat#14302] opened 2019-04-29 07:14 UTC
### Description:

Starting up rocket chat for development is very slow and takes about 10 minutes. 

### Steps to reproduce:

```bash
$ meteor 
```

### Expected behavior:

Rocket chat to start up immediately.

### Actual behavior:

Takes 10 minutes to start up server. Here you can see the start and end timestamps.

```bash
┌─[mota:/Volumes/hd2/Sandbox/rocket.chat]
│ (develop) 2019-04-29T06:59:08Z
└─❯❯❯ meteor
[[[[[ /Volumes/hd2/Sandbox/rocket.chat ]]]]]

=> Started proxy.
up to date in 1.474sd package rocketchat...  /
=> A patch (Meteor 1.8.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
Node#before is deprecated. Use Node#raws.before
I20190429-00:03:56.936(-7)? Updating process.env.MAIL_URL
I20190429-00:03:57.434(-7)? Starting Email Intercepter...
I20190429-00:04:53.131(-7)? LocalStore: store created at
I20190429-00:04:53.132(-7)? LocalStore: store created at
I20190429-00:04:53.133(-7)? LocalStore: store created at
I20190429-00:04:53.792(-7)? Setting default file store to GridFS
I20190429-00:04:56.323(-7)? Setting default file store to GridFS
I20190429-00:04:58.301(-7)? Setting default file store to GridFS
I20190429-00:05:00.680(-7)? Setting default file store to GridFS
I20190429-00:05:03.071(-7)? Setting default file store to GridFS
I20190429-00:05:06.216(-7)? Setting default file store to GridFS
I20190429-00:05:08.679(-7)? Setting default file store to GridFS
I20190429-00:05:09.902(-7)? LocalStore: store created at
I20190429-00:05:09.903(-7)? LocalStore: store created at
I20190429-00:05:09.903(-7)? LocalStore: store created at
I20190429-00:05:10.401(-7)? Setting default file store to GridFS
I20190429-00:05:11.610(-7)? Setting default file store to GridFS
I20190429-00:05:12.975(-7)? Setting default file store to GridFS
I20190429-00:05:15.215(-7)? Setting default file store to GridFS
W20190429-00:07:00.428(-7)? (STDERR) Mon, 29 Apr 2019 07:07:00 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at ../../../../../node_modules/connect/lib/middleware/bodyParser.js:56:20
W20190429-00:07:00.428(-7)? (STDERR) Mon, 29 Apr 2019 07:07:00 GMT connect deprecated limit: Restrict request size at location of read at ../../../../../node_modules/connect/lib/middleware/multipart.js:86:15
I20190429-00:07:02.703(-7) (rocketchat_migrations.js:185) Migrations: Not migrating, already at version 135
I20190429-00:07:06.587(-7)? Updating process.env.MAIL_URL
jI20190429-00:07:37.564(-7)? Using GridFS for custom sounds storage
I20190429-00:07:38.118(-7)? Using GridFS for custom emoji storage
I20190429-00:08:49.732(-7)? Loaded the Apps Framework and loaded a total of 0 Apps!
I20190429-00:09:14.220(-7)? Tries the settings
=> Started your app.

=> App running at: http://localhost:3000/
I20190429-00:09:29.960(-7)? ➔ System ➔ startup
I20190429-00:09:29.960(-7)? ➔ +-----------------------------------------------+
I20190429-00:09:29.961(-7)? ➔ |                 SERVER RUNNING                |
I20190429-00:09:29.961(-7)? ➔ +-----------------------------------------------+
I20190429-00:09:29.961(-7)? ➔ |                                               |
I20190429-00:09:29.961(-7)? ➔ |  Rocket.Chat Version: 0.72.0-develop          |
I20190429-00:09:29.961(-7)? ➔ |       NodeJS Version: 8.11.4 - x64            |
I20190429-00:09:29.961(-7)? ➔ |             Platform: darwin                  |
I20190429-00:09:29.961(-7)? ➔ |         Process Port: 26667                   |
I20190429-00:09:29.962(-7)? ➔ |             Site URL: http://localhost:3000/  |
I20190429-00:09:29.962(-7)? ➔ |     ReplicaSet OpLog: Disabled                |
I20190429-00:09:29.962(-7)? ➔ |          Commit Hash: 063af1d7f8              |
I20190429-00:09:29.962(-7)? ➔ |        Commit Branch: develop                 |
I20190429-00:09:29.962(-7)? ➔ |                                               |
I20190429-00:09:29.962(-7)? ➔ +-----------------------------------------------+
^C

┌─[mota:/Volumes/hd2/Sandbox/rocket.chat]
│ (develop) 2019-04-29T07:10:04Z
└─❯❯❯
```

### Server Setup Information:

- Version of Rocket.Chat Server: latest
- Operating System: macOS Mojve 16gb ram
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8
- MongoDB Version:

**Comment by geekgonecrazy** [comment] 2019-04-29 21:24
I’m going to close this.  This is not a bug.

Also starting up immediately in development mode is not feasible it is compiling the entire app and setting things up to watch all the files for changes. 

10 minutes is a while... but after the first time it should be faster.  Also while developing you don’t need to start again just keep it running

**Closed by geekgonecrazy** 2019-04-29 21:24 UTC

**Comment by coleea** [comment] 2023-05-30 09:14
this is bug that should be fixed. no any apps takes this long
