### ISSUE TITLE
Feature: Status Message

### ISSUE THREAD

**Issue by giray** [RocketChat/Rocket.Chat#2845] opened 2016-04-12 10:06 UTC
Your Rocket.Chat version: 0.26.0

Would be nice if it would be possible to add a status message, definable by the user.  Allow
users to set what they are working on .... why they are "Busy" or where they are working from
(home, office 1 , office 2...)

**Comment by engelgabriel** [comment] 2016-04-12 12:42
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2422

**Closed by engelgabriel** 2016-04-12 12:42 UTC
