### ISSUE TITLE
Chinese input method issue when typing text in livechat widget

### ISSUE THREAD

**Issue by LanceloteHK** [RocketChat/Rocket.Chat#18165] opened 2020-07-06 03:26 UTC
### Description:
In order to type a single Chinese character, some Chinese Input method such as quick and pingyin need to press several keys to combine to a single character. But when typing in the input text area in the web widget, when you press the first key, the input will be interrupted and a character will be typed by 1 key only. This happens with both physical keyboard typing or on-screen keyboard, It only happens with the first key press and the later typing will become normal. I think it may be due to the first key press it will trigger the onchange event to show up the arrow button at the input text div and this break the input. 

### Steps to reproduce:

1. Click the input text area in the web browser livechat widget
2. Switch to a Chinese input method, eg. quick. Press a key by keyboard

### Expected behavior:
Typing can be continued until you choose a word. Only the chosen character will be typed in the area.

### Actual behavior:
Input interrupted and a single character is typed in the text area.

### Server Setup Information:

- Version of Rocket.Chat Server:  3.0.0 or 3.3.0
- Operating System: CentOS 7
- Deployment Method:  docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Edge, Chrome
- Operating System: Windows 10 
- Chinese Input Method: Quick, Pingyin, Cangjie

**Comment by LanceloteHK** [comment] 2020-07-06 08:32
I found that this happens to Japanese Input method too, which is similar to Chinse input method which need several keys to form a character. Will there be any quick fix on modifying the source code or any hints on where should I modify to fix this issue?

**Comment by luixxiul** [comment] 2020-09-07 05:52
I think this is exactly a duplicate of https://github.com/RocketChat/Rocket.Chat.Livechat/issues/403#issuecomment-625109185 right?

**Comment by tassoevan** [comment] 2020-10-27 12:40
Closing in favor of https://github.com/RocketChat/Rocket.Chat.Livechat/issues/403

**Closed by tassoevan** 2020-10-27 12:40 UTC

**Comment by xkungfu** [comment] 2021-01-01 20:01
same issue!
hi. did you resolve this issue?
