### ISSUE TITLE
Avatar wrong path

### ISSUE THREAD

**Issue by shadowsberg** [RocketChat/Rocket.Chat#15098] opened 2019-08-02 22:23 UTC
Good afternoon, I have RC installed and configured in a subdomain and it works fine, but when I place the livechat script the avatar of the agent points directly to the main domain and the image does not load, how can I solve this please

**Comment by reetp** [comment] 2019-08-05 10:42
Please fill in the template with your server information, and also your proxy setup etc.
https://github.com/RocketChat/Rocket.Chat/issues/new?template=bug_report.md

This might be related:
https://github.com/RocketChat/Rocket.Chat/issues/14519

**Comment by TwizzyDizzy** [comment] 2019-08-17 15:06
Closing as dupe of #15131

**Closed by TwizzyDizzy** 2019-08-17 15:06 UTC

**Comment by shadowsberg** [comment] 2019-08-20 14:07
No fix
