### ISSUE TITLE
intermittant login hang, refresh to proceed

### ISSUE THREAD

**Issue by kattekrab** [RocketChat/Rocket.Chat#3979] opened 2016-08-11 01:17 UTC
Your Rocket.Chat version: (make sure you are running the latest)
~~Sorry I don't know how to find out what version we're running. I'll try and find out, and report back.~~
Edit: **Version 0.36.0**

We are using LDAP.

Occasionally, after login, the loading animation just loops. Refreshing the browser takes you straight into rocketchat.

A couple of colleagues have confirmed the same behavior.

A gif.

![rocketchat-loading-onlogin](https://cloud.githubusercontent.com/assets/172755/17576341/f501bd86-5fb4-11e6-8df2-b7e6431c549a.gif)

**Comment by MartinSchoeler** [comment] 2016-08-11 13:33
Thanks for the feedback! This bug is a duplicate of #3761 and we will be soon working on that bug.

**Closed by MartinSchoeler** 2016-08-11 13:33 UTC
Labels: type: bug
