### ISSUE TITLE
About section not working on Mac OS Sierra

### ISSUE THREAD

**Issue by grchis** [RocketChat/Rocket.Chat#7495] opened 2017-07-14 14:49 UTC
Rocket.Chat Version: 
Running Instances: 
DB Replicaset OpLog:
Node Version:
<img width="433" alt="screen shot 2017-07-14 at 5 47 52 pm" src="https://user-images.githubusercontent.com/12933308/28217133-b79f898e-68bc-11e7-9e54-dad426a7dfd0.png">

**Comment by gdelavald** [comment] 2017-07-14 15:03
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/467

**Closed by gdelavald** 2017-07-14 15:03 UTC
