### ISSUE TITLE
Attachment links have truncated domain name

### ISSUE THREAD

**Issue by rmaksimov** [RocketChat/Rocket.Chat#22663] opened 2021-07-13 20:46 UTC
It is impossible to use latest versions of RC due to the broken attachment display functionality, so I reopened the issue #22604

### Description:

Files attached to the messages get a broken link with the last character of the domain name removed, e.g. my.host.com -> my.host.co. If I go to the tab which lists all attachments of this page then the links are correct however.

### Steps to reproduce:

1. Go to a discussion or a channel
2. Upload a file
3. Verify the link of the attached file

### Expected behavior:

Link should include correct domain name and should be displayed correctly

### Actual behavior:

Last character of the domain name is truncated

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.4, 3.16.1, 3.16.2, 3.16.3 (3.14.6 works as expected)
- Operating System: Ubuntu 20
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog:
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.25 / mmapv1 (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Chrome 91.0.4472.114
- Operating System: Mac OS Catalina

**Comment by johncrisp** [comment] 2021-07-14 11:45
Hi.

> It is impossible to use latest versions of RC due to the broken attachment display functionality, so I reopened the issue #22604

So this is just a duplicate of #22604 which you have not 're-opened' - you have just added a comment.

I will close this and follow up there.

**Closed by johncrisp** 2021-07-14 11:45 UTC
