### ISSUE TITLE
Add "more" to show a window of more emojis

### ISSUE THREAD

**Issue by fduraibi** [RocketChat/Rocket.Chat#1599] opened 2015-12-08 18:23 UTC
Add a "more..." link at the bottom of the basic emoji list that opens up a tabbed window with all available emojies, similar to how Discourse does it:

![cqmh7lpuaaefk-a](https://cloud.githubusercontent.com/assets/432460/11664265/b7152dbe-9dae-11e5-9dcd-43aca5662b91.png)

**Comment by wtsarchive** [comment] 2015-12-09 11:50
Isn't this a duplicate of #480?

**Comment by sampaiodiego** [comment] 2015-12-09 11:56
yes =\
I'll copy @fduraibi suggestion to that #480 
thanks @wtsarchive

**Closed by sampaiodiego** 2015-12-09 11:56 UTC
Labels: feat: message, subj: ui/ux, type: improvement
