### ISSUE TITLE
Ability to disable offline email notifications when using mobile client.

### ISSUE THREAD

**Issue by drasbeck** [RocketChat/Rocket.Chat#6995] opened 2017-05-17 09:47 UTC
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

Under "My Account -> Preferences -> Offline Email Notifications" add a choice to only trigger a mail when no mobile client with enabled push notifications are available. I don't know how this is feasible, but something like a mobileClientLastSeen token to guide the choice whether to send a mail or rely on the push notification reaching the user.

I love the idea of getting an email when mentioned/DM'ed while offline, albeit one for every such message is a little much to my taste, luckily there's already an issue for that: #6079. Anyways this idea could make communication less intrusive in various use cases, when the user is not online with a desktop client.

**Comment by sampaiodiego** [comment] 2018-07-16 13:41
is this a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2839?

I liked your idea of having an additional option to only send an email when no mobile client with enabled push notifications are available. my only concern is if your device isn't available anymore, in this case the server doesn't know if the push notification was delivered or not, leading to lost notifications.

**Comment by marceloschmidt** [comment] 2019-10-10 18:32
Closing in favor of #2839.

**Closed by marceloschmidt** 2019-10-10 18:32 UTC
Labels: feat: email, feat: notification, subj: mobile, type: improvement
