### ISSUE TITLE
Push notifications not working - communicate with directly google for push notification for while labeling app without any gateway?

### ISSUE THREAD

**Issue by kishanbh** [RocketChat/Rocket.Chat#33124] opened 2024-08-22 11:19 UTC
### Description:

Push notifications aren't being sent. Successfully sent on my end but the notification doesn't arrive.

### Expected behavior:

Push notifications working

### Actual behavior:

Notifications are not received.

=====================================================================

i'm also facing this issue. Any solution for that to communicate with directly google for push notification for while labeling app without any gateway?

**Comment by reetp** [comment] 2024-08-22 11:59
This looks like a support issue and not a bug.

We can't help you without you completing a bug template.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&projects=&template=bug_report.md

If you go here you can read this on how to report issues effectively:

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98

> Any solution for that to communicate with directly google for push notification for while labeling app without any gateway?

I think you should try and understand more about push notifications in general.

A thorough read of the documentation may help you.

https://developer.rocket.chat/docs/mobile-app-white-labeling
https://developer.rocket.chat/docs/configuring-push-notifications

Closing this for now unless you can show evidence of a bug.

Please ask for help in the appropriate places:

https://open.rocket.chat/channel/support
https://open.rocket.chat/channel/react-native

Thnaks.

**Closed by reetp** 2024-08-22 11:59 UTC
