### ISSUE TITLE
Allow incoming webhook scripts to perform http calls

### ISSUE THREAD

**Issue by ulope** [RocketChat/Rocket.Chat#4776] opened 2016-10-28 17:44 UTC
Your Rocket.Chat version: 0.43.0

It would be great to have the option of performing HTTP calls from within an incoming webhook script. 

This is necessary to support webhook senders that don't provide enough information in the payload to display a meaningful message (e.g. google calendar). Currently those have to be implemented as external services which feels rather unnecessary.

**Comment by cdhowie** [comment] 2016-10-31 14:07
This might be considered a duplicate of my request #4775?  I believe you can make HTTP requests, but you must do so asynchronously, and the integration script methods don't support asynchronous resolution.

**Comment by ulope** [comment] 2016-10-31 14:24
No, only outgoing hooks can perform http calls right now. The incoming ones lack the `HTTP` global. However I agree that #4775 is also quite important.

**Comment by cdhowie** [comment] 2016-10-31 14:46
Hmm... is `require` not exposed to scripts?

**Comment by ulope** [comment] 2016-10-31 14:59
At least it's not documented...

**Comment by graywolf336** [comment] 2017-02-03 15:29
https://github.com/RocketChat/Rocket.Chat/pull/5876 closed this issue. `HTTP('get', 'url', optionsObj)`

**Closed by graywolf336** 2017-02-03 15:29 UTC
Labels: feat: webhooks, type: improvement

**Comment by cdhowie** [comment] 2017-02-05 02:44
@graywolf336 How does this play with the requirement that hook functions be synchronous (return their result)?  See my request #4775.

**Comment by graywolf336** [comment] 2017-02-05 02:57
The `HTTP` runs synchronously, so using this in an incoming webhook to gather information is what we actually use on the demo server currently. However your request is about being asynchronous, which I will take a look in more detail about your request the first of this week.

**Comment by cdhowie** [comment] 2017-02-06 14:41
Ah, interesting.  I assume then that this blocks the entire Rocket server while the request is pending?  Or do hooks get executed in a new runtime?

**Comment by seanf** [comment] 2018-02-22 04:06
> Ah, interesting. I assume then that this blocks the entire Rocket server while the request is pending? Or do hooks get executed in a new runtime?

That's an excellent question, @cdhowie. I'd love to know the answer. @graywolf336 ?

**Comment by graywolf336** [comment] 2018-02-22 04:11
As mentioned earlier, yes currently calls are synchronously called and there is not a way to do an asynchronously do an HTTP call via the integration scripts. @seanf

**Comment by seanf** [comment] 2018-02-22 04:35
@graywolf336 For those of us unfamiliar with the server implementation, do these synchronous calls (and indeed any rogue webhook script which busy-waits) block the entire Rocket server?

**Comment by graywolf336** [comment] 2018-02-22 04:59
@seanf yes, when I say it is synchronous I mean that it waits until that http request returns before continuing the execution of the rest of the integration and therefore the rest of that instance of the Rocket.Chat server. However, there is a timeout applied to the execution of the integration scripts but I am not sure if HTTP calls are included in that execution counter or not.
