### ISSUE TITLE
New message parser fails to render markdown-formatted links with underscores in the description

### ISSUE THREAD

**Issue by ebyrne242** [RocketChat/Rocket.Chat#27484] opened 2022-12-07 19:46 UTC
### Description:

New message parser fails to render markdown-formatted links with underscores in the description.  This does not occur with the legacy message parser.

### Steps to reproduce:

1. Enter a message such as `[google_search](https://www.google.com)`

### Expected behavior:

Link is rendered with the link text **google_search**

### Actual behavior:

The text is displayed as entered.  This is the rendered output of:
```
[google_search](https://www.google.com)
[google search](https://www.google.com)
```
<img width="298" alt="image" src="https://user-images.githubusercontent.com/5010790/206279219-5be8492f-3545-43e7-8cb8-b349d0400137.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 5.3.3
- Operating System: Rocky Linux 8.7
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog:  yes
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.14 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.8.12 (Linux) and 3.8.13 (MacOS)
- Operating System: Linux and MacOS

**Comment by hugocostadev** [comment] 2022-12-16 15:16
@ebyrne242 thanks for your contribution, this will be addressed soon!

**Comment by viniciused26** [comment] 2022-12-19 23:34
Hey, can I work on this? @hugocostadev

**Comment by hugocostadev** [comment] 2022-12-20 12:53
Sure @viniciused26 , it's not so trivial, but if you like a challenge you can check it out the repository and package that we build our parser.

Our parser is built in PEGjs library for reference.

Package/Repo:  https://github.com/RocketChat/fuselage/tree/develop/packages/message-parser

**Comment by viniciused26** [comment] 2022-12-20 12:57
Ok, I'll take a look to see if I can help. I was hoping to contribute with the project, but the issues labeled as "good first issue" seemed outdated, if you have good issues for begginers I would love to take a look at them. Thanks.

**Comment by dusatvoj** [comment] 2022-12-20 13:14
It's not just underscores.... It's also 3 types of brackets, star operators, etc.

Plz @ebyrne242 update the description.
![image](https://user-images.githubusercontent.com/11560794/208675279-942019ce-9f19-49bf-aa8a-e3d30fd9bc3f.png)

(RC version 5.3.5)

**Comment by Toledodev** [comment] 2022-12-29 17:52
This error is not happening on my machine
![Screenshot_5](https://user-images.githubusercontent.com/87545086/209990733-fb2c0f5a-687a-42b9-8069-c9233504c06a.png)

**Comment by dusatvoj** [comment] 2022-12-29 19:13
> Hey @ebyrne242 @dusatvoj @viniciused26 This error is not happening on my machine
> ![Screenshot_5](https://user-images.githubusercontent.com/87545086/209990733-fb2c0f5a-687a-42b9-8069-c9233504c06a.png)
> 

Weird, which version?

**Comment by Toledodev** [comment] 2022-12-29 20:24
Hey @dusatvoj,
- Version of Rocket.Chat Server: 6.0.0
- Operating System:  Ubuntu
- Deployment Method:  docker
- NodeJS Version: v14.19.3
- MongoDb Version: 5.0.5

**Comment by dusatvoj** [comment] 2022-12-29 21:20
@Toledodev what? RocketChat server 6.0.0? :thinking: :grinning:

**Comment by debdutdeb** [comment] 2022-12-30 04:27
I guess that means the issue is fixed on the latest develop ;)

**Comment by Toledodev** [comment] 2022-12-30 21:52
@dusatvoj @debdutdeb 
![Screenshot_1](https://user-images.githubusercontent.com/87545086/210113984-d7fd438c-399c-4b07-9369-7baf00aa8599.png)

**Comment by dusatvoj** [comment] 2023-01-15 19:38
Today I've upgraded to 5.4.1 (latest stable) and there's very tricky behavior. Different inside and outside of a thread.

![image](https://user-images.githubusercontent.com/11560794/212563282-44281af8-fa0d-4892-820b-1d501a209c73.png)
![image](https://user-images.githubusercontent.com/11560794/212563286-bd8537d0-f2ab-43f7-949e-863bfa1e8b08.png)

**Comment by hugocostadev** [comment] 2023-01-16 18:21
I'm working on this issue, soon we will have a fix for that!

**Closed** 2023-02-08 19:17 UTC
Labels: subj: message rendering
