### ISSUE TITLE
Extend user info

### ISSUE THREAD

**Issue by Shikaka** [RocketChat/Rocket.Chat#3692] opened 2016-07-05 14:17 UTC
Your Rocket.Chat version: 0.35.0

Improvement.

It will be great, if users can fill additional information in theirs profiles (if they want)
or possibility to specify field's and syncronize them with LDAP ...

For example Work tel, Location, department... etc...

**Comment by vetash** [comment] 2016-07-07 23:40
Or custom fields.

**Comment by engelgabriel** [comment] 2016-08-18 12:45
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2046

**Closed by engelgabriel** 2016-08-18 12:45 UTC
