### ISSUE TITLE
Editing a message within live-chat has no effect on the live-chat client

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat#8089] opened 2017-09-11 07:17 UTC
### Description:
When editing a message in Rocket.Chat the message is not updated on the clients side.

### Server Setup Information:
* Version of Rocket.Chat Server: v0.58.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2
* DB Replicaset Oplog: Yes
* Node Version: v4.5.0

### Steps to Reproduce:

1. Edit a message within a live-chat

### Expected behavior:

Either prevent/disable editing messages in a live-chat or transfer the changes to the client.

**Comment by MartinSchoeler** [comment] 2017-09-11 12:53
This is a duplicate of #7698 since the problem is the same with message deletions

**Closed by MartinSchoeler** 2017-09-11 12:53 UTC

**Comment by ruKurz** [comment] 2017-09-11 12:55
agree!
