### ISSUE TITLE
Unable to disable caddy service in SNAP-deplyoment

### ISSUE THREAD

**Issue by botboe** [RocketChat/Rocket.Chat#25186] opened 2022-04-14 04:55 UTC
### Description:

Even if I disable caddy via `snap set rocketchat-server caddy=disable` it gets restarted with every start / restart of `snap.rocketchat-server.rocketchat-server.service`

### Steps to reproduce:

1. `snap set rocketchat-server caddy=disable`
2. `systemctl stop snap.rocketchat-server.rocketchat-caddy.service`
3. Check and see that caddy is stopped
4. `systemctl stop snap.rocketchat-server.rocketchat-server.service`
5. Check and see that rocketchat-server is stopped
6. `systemctl start snap.rocketchat-server.rocketchat-server.service`
7. Check and see that caddy is running again even though it was disabled in step 1

### Expected behavior:

Caddy should stay down

### Actual behavior:

Caddy comes up with every start / restart of `snap.rocketchat-server` and spams our syslog with errors because it is unable to retrieve SSL-certificates.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.5
- Operating System: SLES15
- Deployment Method: snap

**Comment by fdellwing** [comment] 2022-04-14 10:11
Did you try masking `snap.rocketchat-server.rocketchat-caddy.service`?

**Comment by botboe** [comment] 2022-04-14 10:45
@fdellwing what do you mean by masking?

**Comment by fdellwing** [comment] 2022-04-14 11:08
1. `snap set rocketchat-server caddy=disable`
3. `systemctl stop snap.rocketchat-server.rocketchat-caddy.service`
4. Check and see that caddy is stopped
4. `systemctl stop snap.rocketchat-server.rocketchat-server.service`
5. Check and see that rocketchat-server is stopped
6. `systemctl mask snap.rocketchat-server.rocketchat-caddy.service`
7. `systemctl start snap.rocketchat-server.rocketchat-server.service`
8. Check and see if caddy is running again

**Comment by botboe** [comment] 2022-04-14 11:14
Ah, ok! I Thought this was a feature of snap and not of systemd. I will give it a try!

**Comment by fdellwing** [comment] 2022-04-14 11:15
Even if it works, its only a workaround though.

**Comment by dudanogueira** [comment] 2022-04-22 19:23
While we offer a variety of deployment methods, we strongly recommend docker or k8s.

Also, please consider using our [Support Channel](https://open.rocket.chat/channel/support) or [Forums](https://forums.rocket.chat/) for community support

closing as this is not a bug, but a deployment config.

**Closed by dudanogueira** 2022-04-22 19:23 UTC
