### ISSUE TITLE
Rocketchat crashes after login attempt

### ISSUE THREAD

**Issue by stoficek** [RocketChat/Rocket.Chat#13147] opened 2019-01-14 15:16 UTC
### Description:

After upgrading mongodb to 3.4.18 and rocketchat to 0.73.2 every time when I try to login a server crashes and I have to manually start it again. We use LDAP as a login mechanism.

### Steps to reproduce:

1.  Upgrade mongodb to 3.4.18
2.  Upgrade rocketchat to 0.73.2
3.  Restart rocketchat (via systemctl in my case)
4. Try to log in via webpage

### Expected behavior:

I am able to login and use rocketchat

### Actual behavior:

Server crashes

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2
- Operating System: Centos 7.6.1810
- Deployment Method:  tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.9.4
- MongoDB Version: 3.4.18

### Relevant logs:

LDAPHandler ➔ info Init LDAP login XXX
LDAP ➔ Connection.info Init setup
LDAP ➔ Connection.info Connecting ldap://1.1.1.1:389
LDAP ➔ Connection.info LDAP connected
LDAP ➔ Search.info Searching user XXX
LDAP ➔ Search.info Search result count 1
LDAP ➔ Auth.info Authenticating uid=XXX,ou=People,dc=yyy,dc=com
LDAP ➔ Search.info Search result count 1
LDAP ➔ Auth.info Authenticated uid=XXX,ou=People,dc=yyy,dc=com
LDAPHandler ➔ info Querying user
LDAPHandler ➔ info Logging user
LDAPSync ➔ info Syncing user data
 /usr/local/bin/node: symbol lookup error: /opt/Rocket.Chat/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE
rocketchat.service: main process exited, code=exited, status=127/n/a
Unit rocketchat.service entered failed state.
rocketchat.service failed.

**Comment by esolix** [comment] 2019-01-15 06:07
Update: I upgraded to NPM 6.4.1 and it works now

**Comment by stoficek** [comment] 2019-01-15 07:36
Mine version of NPM is 6.5.0

**Comment by esolix** [comment] 2019-01-15 07:38
Try 6.4.1

**Comment by stoficek** [comment] 2019-01-15 08:37
6.4.1 didnt help in my case

**Comment by l8nites** [comment] 2019-01-17 03:44
Similar issue here. We don't use LDAP, crashes seem to occur around user administration.

**Comment by tctovsli** [comment] 2019-01-17 09:57
I have the same issue. We use LDAP.

Is there a way to downgrade? When I tried spinning up the previous image, I got a `Can't find migration version 137`

**Comment by kuluev** [comment] 2019-01-17 10:53
Try to update your NodeJS. Mine worked after v8.11.4 update.

**Comment by tctovsli** [comment] 2019-01-17 10:57
Will do.
Also, found this: https://github.com/kelektiv/node.bcrypt.js/issues/656
I think perhaps this dependency update might have caused this issue: #12624 since bcrypt is updated from v2 to 3.

**Comment by DoM1niC** [comment] 2019-01-18 02:32
I had the same Problem, Update NodeJS using NVM to switch between the Versions :+1:

**Comment by reetp** [comment] 2019-01-18 22:22
And the next one to try is getting your node more up to date.
The docker version runs node v8.11.4 so I'd take a look at that next.
FWIW docker also runs npm 5.6.0

**Comment by zeled** [comment] 2019-01-23 13:07
downgrade bcrypt to 3.0.0 solved the problem

**Comment by stoficek** [comment] 2019-01-23 13:54
Yes thanks all. Upgrading to node v8.11.4 helped. But after upgrading I have another problem. After one day of usage server runs out of memory and I have to reboot rocketchat.

**Comment by abyrne55** [comment] 2019-01-28 21:00
I'm experiencing the same issue on my snap installation, also using LDAP for auth. All packages on my host machine are up to date, but I'm not sure how to upgrade the version of node inside the snap since it's on a read-only filesystem. Here's my server's info:

Version of Rocket.Chat Server: 0.73.2
Operating System: Ubuntu 18.04
Deployment Method: snap
Number of Running Instances: 1
NodeJS Version: 8.11.3 - x64 
MongoDB Version: v3.2.7

And here's what keeps getting printed to the log every time rocket.chat restarts (which is every 5-10 seconds)
```
Jan 28 15:53:51 trout systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
Jan 28 15:53:51 trout rocketchat-server.rocketchat-server[30584]: Checking if oplog has been enabled, and enabling if not
Jan 28 15:53:51 trout rocketchat-server.rocketchat-server[30584]: MongoDB shell version: 3.2.7
Jan 28 15:53:51 trout rocketchat-server.rocketchat-server[30584]: connecting to: test
Jan 28 15:53:51 trout rocketchat-server.rocketchat-server[30584]: /snap/rocketchat-server/1362/bin/startRocketChat: line 28: /var/snap/rocketchat-server/common/*.env: No such file or directory
Jan 28 15:53:54 trout rocketchat-server.rocketchat-server[30584]: Updating process.env.MAIL_URL
Jan 28 15:53:55 trout rocketchat-server.rocketchat-server[30584]: Starting Email Intercepter...
Jan 28 15:53:56 trout rocketchat-server.rocketchat-server[30584]: Warning: connect.session() MemoryStore is not
Jan 28 15:53:56 trout rocketchat-server.rocketchat-server[30584]: designed for a production environment, as it will leak
Jan 28 15:53:56 trout rocketchat-server.rocketchat-server[30584]: memory, and will not scale past a single process.
Jan 28 15:53:56 trout rocketchat-server.rocketchat-server[30584]: Setting default file store to FileSystem
Jan 28 15:53:59 trout rocketchat-server.rocketchat-server[30584]: {"line":"121","file":"migrations.js","message":"Migrations: Not migrating, already at version 137","time":{"$date":1548708839781},"level":"info"}
Jan 28 15:54:00 trout rocketchat-server.rocketchat-server[30584]: Using GridFS for custom sounds storage
Jan 28 15:54:00 trout rocketchat-server.rocketchat-server[30584]: Using GridFS for custom emoji storage
Jan 28 15:54:00 trout rocketchat-server.rocketchat-server[30584]: Updating process.env.MAIL_URL
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: The App 22236eb7-1786-42bc-846c-a086dd072c2e is checking if "math" command exists.
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: The App 22236eb7-1786-42bc-846c-a086dd072c2e is registering the command: "math"
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: Loaded the Apps Framework and loaded a total of 1 Apps!
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ System ➔ startup
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ +-------------------------------------------------+
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |                  SERVER RUNNING                 |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ +-------------------------------------------------+
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |                                                 |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |  Rocket.Chat Version: 0.73.2                    |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |       NodeJS Version: 8.11.3 - x64              |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |             Platform: linux                     |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |         Process Port: 3000                      |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |             Site URL: https://chat.burpg.space  |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |     ReplicaSet OpLog: Enabled                   |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |          Commit Hash: 8ff0e3da16                |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |        Commit Branch: HEAD                      |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ |                                                 |
Jan 28 15:54:02 trout rocketchat-server.rocketchat-server[30584]: ➔ +-------------------------------------------------+
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]: Bugsnag:  Encountered an uncaught error, terminating…
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]: TypeError: err.stack.split is not a function
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at Object.exports.parse (/snap/rocketchat-server/1362/programs/server/npm/node_modules/stack-trace/lib/stack-trace.js:26:25)
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at new Error (/snap/rocketchat-server/1362/programs/server/npm/node_modules/bugsnag/lib/error.js:69:28)
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at Function.Error.buildErrors (/snap/rocketchat-server/1362/programs/server/npm/node_modules/bugsnag/lib/error.js:82:20)
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at notify (/snap/rocketchat-server/1362/programs/server/npm/node_modules/bugsnag/lib/bugsnag.js:37:34)
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at Object.Bugsnag.notify (/snap/rocketchat-server/1362/programs/server/npm/node_modules/bugsnag/lib/bugsnag.js:174:10)
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at notify (packages/rocketchat:lib/server/lib/bugsnag.js:22:21)
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at Object.Meteor._debug (packages/rocketchat:lib/server/lib/bugsnag.js:32:2)
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at Object.Meteor._debug (packages/rocketchat:error-handler/server/lib/RocketChat.ErrorHandler.js:41:32)
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at wrapInternalException (packages/ddp-server/livedata_server.js:1737:12)
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at promise.then.exception (packages/ddp-server/livedata_server.js:745:25)
Jan 28 15:54:06 trout rocketchat-server.rocketchat-server[30584]:     at /snap/rocketchat-server/1362/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Jan 28 15:54:06 trout systemd[1]: snap.rocketchat-server.rocketchat-server.service: Main process exited, code=exited, status=1/FAILURE
Jan 28 15:54:06 trout systemd[1]: snap.rocketchat-server.rocketchat-server.service: Failed with result 'exit-code'.
```

I tried reverting the snap to the last revision (1356), but this only caused Rocket.Chat to refuse to start at all with the repeated error `Not migrating, control is locked. Attempt 6/30. Trying again in 10 seconds`. So I reverted back to the current version (1362).

**Comment by nunofernandes** [comment] 2019-01-31 10:30
I also have this problem.... Any timeline on when you think this will be fixed?

**Comment by reetp** [comment] 2019-02-01 12:31
> Yes thanks all. Upgrading to node v8.11.4 helped. But after upgrading I have another problem. After one day of usage server runs out of memory and I have to reboot rocketchat.

How much memory do you have on your server?

**Comment by reetp** [comment] 2019-02-01 12:33
> I also have this problem.... Any timeline on when you think this will be fixed?

There is more than one issue here. Which one are you talking about ? Updating node (you can do that yourself if using CentOS/tar install) or running out of memory (how much have you got?)

**Comment by stoficek** [comment] 2019-02-01 12:37
> > Yes thanks all. Upgrading to node v8.11.4 helped. But after upgrading I have another problem. After one day of usage server runs out of memory and I have to reboot rocketchat.
> 
> How much memory do you have on your server?

Now its 3GB and 8VCPUs

**Comment by zolbayars** [comment] 2019-02-04 02:33
For me, updating npm version from 5.5.1 to 6.7.0 resolved this issue.

**Comment by ryguy222** [comment] 2019-03-01 02:36
I can confirm this is still an issue in Rocket.Chat 0.74.3
NodeJS 8.9.4  and MongoDB 3.4.18

Downgrading to bcrypt 3.0.0 did not fix the issue. Logins that are handled via SAML worked fine, but local accounts immediately crashed the server.

**Comment by nielsk** [comment] 2019-04-29 10:12
After updating to 1.1.0 rocketchat crashes.
I updated npm to 6.9.0 and this didn't help
This is what I get: /usr/local/bin/node: symbol lookup error: /opt/Rocket.Chat/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE

**Comment by reetp** [comment] 2019-04-29 11:08
https://github.com/RocketChat/Rocket.Chat/releases

Here are the recommended versions:

1.0.1 2019-04-28
Engine versions

    Node: 8.11.4
    NPM: 6.4.1
    MongoDB: 3.2, 3.4, 3.6, 4.0

**Comment by MartinSchoeler** [comment] 2024-08-01 20:20
Closing this due lack of updates, if you experience this on the latest release, feel free to open a new issue.

Thanks!

**Closed by MartinSchoeler** 2024-08-01 20:20 UTC
