### ISSUE TITLE
Ability forward messages into other chat rooms

### ISSUE THREAD

**Issue by pupaxxo** [RocketChat/Rocket.Chat#396] opened 2015-08-04 11:07 UTC
##

**Comment by sampaiodiego** [comment] 2015-08-04 14:08
the "answer" feature was discussed in #167

but what you mean "forward messages" ? like a share by e-mail?

**Comment by pupaxxo** [comment] 2015-08-04 14:12
I mean sending(sharing/forwarding) received or sent message in other chats. Like telegram

**Comment by sampaiodiego** [comment] 2015-08-04 14:27
I see.. we could do this..

if you could provide some thoughts on UI we can discuss about it.

**Comment by fduraibi** [comment] 2015-12-08 18:53
I think the best way is to add it to the `message-dropdown` menu, something like this

![acc-chat4](https://cloud.githubusercontent.com/assets/432460/11664813/d194ba94-9db1-11e5-86a1-0582f33bd8e2.png)

* Forward is more suitable if it just to forward the message locally like between rooms on the same server, while sharing is better if the intention is to share it with other platforms/apps (e.g. twitter)

* Note: the screenshot is from an Arabic interface (RTL), for LTR interface like English the arrows should face the other direction, so in case it was implemented, these icons need to be placed in Unicode locations with mirror property (see https://github.com/RocketChat/Rocket.Chat/issues/1577 and here https://github.com/RocketChat/Rocket.Chat/pull/1594#issuecomment-162671579)

**Comment by localguru** [comment] 2017-06-16 23:17
Is this in development?

**Comment by sampaiodiego** [comment] 2017-06-19 12:05
@localguru it's not. at least by the core team.

**Comment by lindoelio** [comment] 2017-12-19 12:36
Hey guys! This has been delivered on PR #9180.

Let me know if it works for you. :-)

**Comment by cmrd-senya** [comment] 2018-04-09 09:33
Why is the issue is closed when the corresponding PR is still not merged?

**Comment by sampaiodiego** [comment] 2018-04-09 13:05
you're right @cmrd-senya .. reopening

**Comment by maha-ghoneim** [comment] 2018-08-30 09:01
did u reach anything?

**Comment by dj301** [comment] 2019-03-18 09:31
Any status update on this feature?

**Comment by knrt10** [comment] 2019-04-21 17:21
On it, will try to add this feature.

**Comment by pcbarbassa** [comment] 2019-06-28 12:29
Any status update on this feature?

**Comment by krasgang** [comment] 2019-07-02 04:02
It's a killer feature.

**Comment by pcbarbassa** [comment] 2019-07-02 14:57
it is possible by pasting the link of the message, but it is not usual.

**Comment by ceefour** [comment] 2020-09-07 01:59
@lindoelio hi, how is the progress of this?

Currently only Share link is available, but cannot Forward message to other room/user.

**Comment by hugorn** [comment] 2020-11-03 19:57
Currently only Share as link is available, but cannot Forward message to other room/user.

**Comment by dunggnguyen** [comment] 2021-12-22 02:06
Any status update on this feature? Thanks!

**Comment by MrPoint1400** [comment] 2022-04-10 08:33
+1

**Comment by lawipac** [comment] 2022-07-24 11:37
Still unavailable?  It's been 5 years since the PR https://github.com/RocketChat/Rocket.Chat/pull/9180 was created.

**Comment by vins345** [comment] 2022-09-08 06:37
+1

**Comment by Si-Richards** [comment] 2022-09-28 09:23
seems bizarre this isnt here yet !

**Comment by MrPoint1400** [comment] 2022-09-28 14:33
+1

**Comment by MrPoint1400** [comment] 2023-01-08 10:39
Duplicate of #11179

**Closed** 2023-03-15 22:34 UTC
Labels: feat: message, Feature: Planned, stat: triaged
