### ISSUE TITLE
Specific rooms crash after the 0.59.1 update.

### ISSUE THREAD

**Issue by nerfe** [RocketChat/Rocket.Chat#8556] opened 2017-10-20 03:06 UTC
### Description:

Specific rooms crash after the 0.59.1 update.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Ubuntu 16
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: 

### Steps to Reproduce:
We just received an update on our rocket chat with the version 0.59.1, and i have 2 rooms crashing once clicked, i searched for solutions in your issues and i think the same problem occurs here https://github.com/RocketChat/Rocket.Chat/issues/6814 except that i found out that our 2 rooms has the same current message with a multi-line quote with dots inside. I'm not sure if this caused the room to crash, but after i deleted those messages, the room worked well again.

**Comment by N4IR0** [comment] 2017-10-20 05:04
We have also tried this in our test environment (RC 0.59.1) and it seems to be the same bug as in #6814.

**Our server setup:**
- Version of Rocket.Chat Server: 0.59.1
- Operating System: Ubuntu 16.04
- Deployment Method(snap/docker/tar/etc): docker
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- Node Version: v4.8.4

**Comment by TomaszDom** [comment] 2017-10-20 08:12
Reproduced it on the official demo server just by typing \`\`\`U ..\`\`\`

**Comment by N4IR0** [comment] 2017-10-26 06:35
Any news here? We need the bugfix in order to deploy the newest version of RC, because we could not accept responsibility, that some chat rooms may crash after the update.

**Comment by N4IR0** [comment] 2017-11-06 07:36
This bug seems to be fixed in 0.59.3, can anyone confirm this?

**Comment by nerfe** [comment] 2017-12-12 05:40
This bus isn't fixed in 0.59.4, i tested ` ```U...``` ` in the sandbox rocket chat made the room crash.

**Comment by TwizzyDizzy** [comment] 2018-04-05 12:48
@rocket-cat close

Cannot reproduce this on 0.63.0 (neither Firefox nor Chromium). If somebody can still reproduce this, please get back to me!

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-04-05 12:48 UTC
Labels: subj: ui/ux, type: bug

**Comment by maik28** [comment] 2018-08-01 12:36
Bug is still there on 0.66.0.
