### ISSUE TITLE
Composer on the web (Safari, Chrome and Electron) increases for no reason

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#11904] opened 2018-08-30 11:57 UTC
### Description:

![2018-08-30 08 56 56](https://user-images.githubusercontent.com/551004/44850152-b92ee280-ac32-11e8-8e95-e476a971679b.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: Linux

**Comment by goobersmooch** [comment] 2018-08-30 12:40
I'm seeing this issue as well when using the macOS client.

**Comment by rafaelks** [comment] 2018-09-11 16:39
Still happens in 0.69.1.

**Comment by lehrhardt** [comment] 2018-09-13 17:42
Seeing this as well under Linux.

**Comment by FaizanZahid** [comment] 2018-09-18 15:40
I am seeing the same issue for chrome mobile version of site on my android.

**Comment by ggazzo** [comment] 2018-09-27 19:10
closed by #12138

**Comment by rafaelks** [comment] 2018-10-01 16:27
Bug is not fixed.

![screen shot 2018-10-01 at 13 26 43](https://user-images.githubusercontent.com/551004/46301783-be5ab680-c57d-11e8-83dd-6e74c9317e04.png)

**Comment by rsimai** [comment] 2018-10-24 08:04
I can confirm this to still happen in 0.70.4. Not sure how to provoke it, it's however gone if the user reloads the page.

**Comment by rafaelks** [comment] 2018-10-24 14:09
Still happens in `0.71.0-rc.0` as well.

**Comment by JanZerebecki** [comment] 2018-10-26 13:30
Happend to me on Firefox. Part of the HTML read `<textarea class="rc-message-box__textarea js-input-message autogrow-short" style="height: 155px;" autofocus="" placeholder="Message" rows="1" dir="ltr">`. Once I go to a different channel the problem is gone. After a restart of Firefox and logging in again to this RockChat, at one point it will happen again.

**Comment by moonwolf-github** [comment] 2018-11-09 10:16
I just started to happen on my 0.69.2. At least in desktop client.

**Comment by FaizanZahid** [comment] 2018-11-20 15:18
+1

**Comment by FaizanZahid** [comment] 2018-11-26 15:49
Agree it happens sometimes on mobile DM or channels

**Comment by dj301** [comment] 2019-03-18 09:22
Any status update on this issue? @tassoevan  @ggazzo

**Comment by tassoevan** [comment] 2019-03-18 14:55
@dj301 We did some adjustments in the `develop` branch version which should fix it.

**Comment by ggazzo** [comment] 2019-04-29 17:06
we changed the messagebox code a lot since this issue was opened, I'm very confident we already fixed it, please reopen if I'm wrong.

**Closed by ggazzo** 2019-04-29 17:06 UTC
Labels: subj: ui/ux, type: bug
