### ISSUE TITLE
A toggle to hide join/leave messages

### ISSUE THREAD

**Issue by GamerTime69** [RocketChat/Rocket.Chat#15521] opened 2019-10-06 23:49 UTC
A lot of rooms have a lot of people joining and/or leaving and having just a wall of "xX_RocketUser_Xx has joined the channel" doesn't look nice, isn't info most users care about, and can lead to some very dead discussions because you can't see the last time somebody said something. 

It would be much appreciated to see a toggle to hide them under 
My Account > Settings > Messages

**Comment by reetp** [comment] 2019-10-11 12:49
@rocket-cat close

Please search issue before creating a new one eg
https://github.com/RocketChat/Rocket.Chat/issues?page=2&q=is%3Aissue+join+notification&utf8=%E2%9C%93

In this instance it is a feature request and should have been opened here
https://github.com/RocketChat/feature-requests

Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/7900

May be others too.

**Closed by reetp** 2019-10-11 12:49 UTC
