### ISSUE TITLE
Start Direct Message By First And Last Name

### ISSUE THREAD

**Issue by amayer5125** [RocketChat/Rocket.Chat#2632] opened 2016-03-24 13:58 UTC
Your Rocket.Chat version: 0.23.0

If I click the + beside "Direct Messages" to start a new conversation I can not search by persons name, only by their handle. While I understand this it may be hard for less technical users to start a direct message with a co-worker.

**Comment by engelgabriel** [comment] 2016-03-25 01:00
This is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/324

**Closed by engelgabriel** 2016-03-25 01:00 UTC
