### ISSUE TITLE
E-Mail verification settings do not work 

### ISSUE THREAD

**Issue by janrudolph** [RocketChat/Rocket.Chat#8007] opened 2017-09-01 11:47 UTC
### Description:

Rocket.Chat is able to sent an email to a new user in order to verify the email address. The admin can switch this option on and off via the setting "Accounts_EmailVerification".

### Expected behavior:

When setting "Accounts_EmailVerification" to false in the admin panel, no email verification is in place (meaning: sending no email to an user, asking for a click on the provided link). 

### Actual behavior:

If "Accounts_EmailVerification" is false, an verification email is sent anyway.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.1
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): AWS
* Number of Running Instances: 2
* Node Version: v4.5.0

### Steps to Reproduce:

0. Configure SMTP
1. Set  "Accounts_EmailVerification" = false 
2. Register a new user with a valid email adress
3. The user will receive a verification link

You can set in (1) the value "true", try it, and make another iteration with "Accounts_EmailVerification" = false. Every time, an email will be sent.

**Comment by madguy02** [comment] 2017-09-04 20:26
try updating the version to the most recent version i.e 0.59.0 @janrudolph

**Comment by rodrigok** [comment] 2017-12-05 19:54
@janrudolph Take a look at my comment here https://github.com/RocketChat/Rocket.Chat/pull/8110#issuecomment-330199295

Currently we don't have an option to not send the confirmation email, that option define if users will be allowed to login without verified emails. We need to improve the label description.

Please open a new issue if you want a new setting to control if we should send the confirmation email, that will affect some internal logics like the sending of offline messages that we only send to verified emails.

Thanks

**Comment by janrudolph** [comment] 2017-12-14 07:15
@rodrigok Oh okay, then updating the label is fine for me. Thanks for your reply. Do you open a new issue for that?

**Comment by Gandalf-the-Grey** [comment] 2018-02-09 07:33
Is there a way to have obligatory e-mail verification while using OAuth?
ie. I'd like to have OAuth as required but not sufficient (forcing people to verify e-mail, that they - independently from OAuth provide)

**Comment by SeanPackham** [comment] 2018-03-12 12:20
Closing as this feature is not on our short term roadmap, we will revisit once other priorities have been addressed.

**Comment by janrudolph** [comment] 2018-03-13 06:31
@SeanPackham okay, but how will you ensure that is issue is handled if you close it?

**Comment by SeanPackham** [comment] 2018-03-14 12:25
@jangmarker sorry if I misunderstood but it sounded like you were saying that now versification email is sent went it is turned off in the settings. Is this correct? If so this is the expected behaviour of the feature.

**Comment by ci5ic** [comment] 2018-04-16 15:58
Yes we really need a way to turn off e-mail verification entirely!

#1. We do NOT want to send offline messages to our users' email!!!
#2. In the case of invitation by e-mail, they are already verifying the e-mail that they've provided to us so that we could send them an invitation!
#3. We require that new users be approved. When they receive the verification e-mail before the account is approved, the verification login won't work because they haven't been approved. This is confusing for the users!

**Closed** 2020-04-30 12:59 UTC
Labels: feat: accounts, feat: email, type: bug
