### ISSUE TITLE
direct room names disappear from Dashboard after update

### ISSUE THREAD

**Issue by Nemra1** [RocketChat/Rocket.Chat#5583] opened 2017-01-16 03:19 UTC
Your Rocket.Chat version: ( latest)
After update to 49.1 icant get any direct room
![2017-01-15_053647](https://cloud.githubusercontent.com/assets/22897987/21970043/94bb6e18-dbab-11e6-883c-f8f752c60d39.png)

**Comment by engelgabriel** [comment] 2017-01-16 13:00
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/5538

**Closed by engelgabriel** 2017-01-16 13:00 UTC
