### ISSUE TITLE
Faulty YouTube preview

### ISSUE THREAD

**Issue by MichaelSavin** [RocketChat/Rocket.Chat#3138] opened 2016-05-05 10:57 UTC
On https://demo.rocket.chat if you paste YouTube share-link you can see different results:

https://www.youtube.com/watch?v=SWxvEbp1NjE - normal preview:
![02](https://cloud.githubusercontent.com/assets/1640229/15041986/9d09b6ce-12d9-11e6-9815-5d0f02db671f.png)

https://youtu.be/SWxvEbp1NjE - same video, but faulty prewiew:
![01](https://cloud.githubusercontent.com/assets/1640229/15042006/c4a7f52e-12d9-11e6-9e89-604623d60627.png)

**Comment by zxweed** [comment] 2016-05-06 11:06
This is ok, I don't need the big preview anytime and can choose now, please, leave this behavior.

**Comment by MichaelSavin** [comment] 2016-05-06 11:58
This behavior is confusing ordinary users (we made a small focus group). The interface needs consistency.

**Comment by zxweed** [comment] 2016-05-06 12:17
@MichaelSavin, for perfect consistency we need to disable the youtube preview, because the short preview format is default for all types of urls;

**Comment by MichaelSavin** [comment] 2016-05-06 13:06
@zxweed I've checked in Slack - both links give full preview. 
IMHO this:
1) Consistently
2) Follow the rules of usability - to avoid unnecessary clicks / referrals
I have not tested the behavior in mobile- and desktop clients

**Comment by antn89** [comment] 2016-05-11 17:00
Hi guy,
I install rocked.chat v 0.30, but when i send a youtube link, it doesn't show preview,
Here is config from: Rocket.Chat/programs/server/packages/rocketchat_oembed.js
```
providers.registerProvider({                                                                                   // 1
  urls: [new RegExp('https?://www.youtube.com/\\S+'), new RegExp('https?://youtu.be/\\S+')],                   // 33
  endPoint: 'https://www.youtube.com/oembed?maxheight=200'                                                     // 33
});
```

**Comment by MichaelSavin** [comment] 2016-05-16 10:15
@marceloschmidt Please, reopen issue. In demo.rocketchat.com youtu.be links doesn't working. Try it: https://youtu.be/YlUKcNNmywk?list=RDYlUKcNNmywk

**Comment by k0nsl** [comment] 2016-06-09 17:07
I can confirm this and it has been like this for three or four versions back, if not more.

**Comment by lucasvanhalst** [comment] 2016-09-03 21:13
Bump, this is still happening but it's worse now, no preview at all for youtu.be links.
This is the error that occurs
```
Exception in defer callback: SyntaxError: Unexpected end of input
     at Object.parse (native)     at packages/rocketchat_oembed/server/providers.coffee:74:19
     at packages/rocketchat_lib/lib/callbacks.coffee:73:21
     at Array.reduce (native)
     at Object.RocketChat.callbacks.run (packages/rocketchat_lib/lib/callbacks.coffee:68:103)
     at Object.OEmbed.getUrlMeta (packages/rocketchat_oembed/server/server.coffee:135:30)
     at Object.OEmbed.getUrlMetaWithCache (packages/rocketchat_oembed/server/server.coffee:148:16)
     at packages/rocketchat_oembed/server/server.coffee:195:18
     at Array.forEach (native)
     at OEmbed.RocketUrlParser (packages/rocketchat_oembed/server/server.coffee:184:16)
```
version 072c5b0a

**Comment by maxdwit** [comment] 2017-01-27 15:08
In Version 0.50.1 still an issue  http://youtu.be/SWxvEbp1NjE 
Short youtu.be links fail to preview

**Comment by maxdwit** [comment] 2017-06-15 09:24
In Version 0.51.0 still no preview for youtu.be Links.

**Comment by geekgonecrazy** [comment] 2017-06-15 22:25
Its working on demo server on 0.57.0-rc.2 i'll go ahead and close this.

**Closed by geekgonecrazy** 2017-06-15 22:25 UTC
