### ISSUE TITLE
Sidebar is blank on mobile

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#7547] opened 2017-07-23 04:07 UTC
### Description:

Just made a new install of RocketChat and have an issue that the sidebar shows up as blank on mobile devices.  I realize this is also happening at demo.rocket.chat !    Anyone else have this?

(My site)   https://punchattool.peerunschooling.net

![img_5610](https://user-images.githubusercontent.com/12577122/28496473-409b6784-6f21-11e7-84d8-e5bd8667485d.jpg)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Operating System: iOS 7   iPhone 5
* Deployment Method(snap/docker/tar/etc): Heroku
* Number of Running Instances:   1
* DB Replicaset Oplog:  yes
* Node Version: Enabled

### Steps to Reproduce:

Opening the sidebar on my mobile device causes a blank sidebar.  Happens on my site and also on demo.rocket.chat

### Expected behavior:

I expected it to list the channels, direct message chats, etc.

**Comment by teamsoo** [comment] 2017-07-23 17:31
@flantascience There is nothing wrong on my mobile. Have you try restarting your phone? Can you check your network connectivity?

**Comment by MartinSchoeler** [comment] 2017-07-24 13:05
@flantascience @teamsoo I couldn't reproduce this either on android using chrome and desktop chrome on a small resolution. I don't have a IOS device to test this though.

**Comment by teamsoo** [comment] 2017-07-25 02:19
@MartinSchoeler Both my server and demo server work fine on my iPhone. Can't test on iPad cuz I can't afford one.

**Comment by flantascience** [comment] 2017-07-30 20:18
Well I am in a bad place now... I checked with a few other people who claimed no issue, so I assumed it was an issue for my own device.   I did the upgrade.   Now I've got a user complaining they have this same issue.   Is it really just me and one of my users?

**Comment by geekgonecrazy** [comment] 2018-12-01 10:19
Cordova app fully deprecated.  Closing

**Closed by geekgonecrazy** 2018-12-01 10:19 UTC
Labels: subj: mobile
