### ISSUE TITLE
Windows desktop app automatic updates not working

### ISSUE THREAD

**Issue by JohnLukeP** [RocketChat/Rocket.Chat#19506] opened 2020-11-11 13:23 UTC
Rocketchat app correctly notifies the user for a new version available, but when chosing to update it, nothing happens.
Same situation by trying to update from Help -> About Rocketchat.

### Steps to reproduce:

1. Choose to update the Windows desktop app when the update available notification appears OR from the "About Rocketchat" 
section

### Expected behavior:

The app is automatically updated

### Actual behavior:

Nothing at all happens, forcing user to manually download the newer installer, install the new version and re-add the various Rocketchat servers

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.1
- Operating System:  Linux Ubuntu 18.04.4
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v12.16.1
- MongoDB Version: 4.0

### Client Setup Information

- Desktop App or Browser Version: 3.0.2 
- Operating System: Windows 10

**Comment by ankar84** [comment] 2020-11-11 13:53
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670

**Comment by MartinSchoeler** [comment] 2020-11-11 20:07
🔝

**Closed by MartinSchoeler** 2020-11-11 20:07 UTC
