### ISSUE TITLE
Linux client generates high CPU load

### ISSUE THREAD

**Issue by dmitrijnikolajev** [RocketChat/Rocket.Chat#6415] opened 2017-03-22 07:27 UTC
When rocket.chat linux client is running (even when not chatting) it constantly consumes CPU resources (~ 40% in my case). Using Ubuntu Gnome 16.10 (asus ux306ua hidpi screen 3200x1800).

Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.3

![screenshot from 2017-03-21 16-34-24](https://cloud.githubusercontent.com/assets/23337957/24186201/e54eafe0-0edf-11e7-81e8-a214443e2efd.png)
![screenshot from 2017-03-21 16-34-40](https://cloud.githubusercontent.com/assets/23337957/24186202/e54f1750-0edf-11e7-8c04-77e59b939a29.png)
![screenshot from 2017-03-22 09-17-11](https://cloud.githubusercontent.com/assets/23337957/24186366/a5ae4f7a-0ee0-11e7-8c66-f92960fd047d.png)
![screenshot from 2017-03-22 09-18-12](https://cloud.githubusercontent.com/assets/23337957/24186371/acc7adf6-0ee0-11e7-9679-96db29a695eb.png)

**Comment by localguru** [comment] 2017-03-22 12:22
I can confirm such a behavior. The linux client seems to be very hungry at all and from time to time eats up CPU and memory.

**Comment by Rohlik** [comment] 2017-03-23 13:17
I think this is problem with node.js itself.
https://rocket.chat/docs/installation/manual-installation/multiple-instances-to-improve-performance#running-multiple-instances-per-host-to-improve-performance

**Comment by dmitrijnikolajev** [comment] 2017-03-23 15:18
No problems with CPU load if I use rocket.chat via web browser on my Linux laptop. With Linux client the CPU cores are constantly loaded.

**Comment by TwizzyDizzy** [comment] 2018-05-03 21:41
@rocket-cat close

Closing this, as you are obviously referring to the [Electron Client](https://github.com/RocketChat/Rocket.Chat.Electron). Please open an issue over there, if the problem still exists. Also have a look at those issues before: https://github.com/RocketChat/Rocket.Chat.Electron

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-05-03 21:42 UTC
Labels: subj: performance
