### ISSUE TITLE
voice and video call on channels

### ISSUE THREAD

**Issue by djeber** [RocketChat/Rocket.Chat#1789] opened 2016-01-01 00:08 UTC
currently rocket.chat have video and audio call for channels but its complicated its good for one on one situations but for like 1000 one its not so my suggestion is to make an option to enable only a mic and only one at a time can use it and the others listen to it and when he over he let the mic free so another one can use it just like on camfrog and yahoo messenger

**Comment by Sing-Li** [comment] 2016-01-01 04:29
Duplicate of #1118

**Closed by Sing-Li** 2016-01-01 04:29 UTC
