### ISSUE TITLE
Deployment error: Direct installation of an App is disabled

### ISSUE THREAD

**Issue by SimonTheCat** [RocketChat/Rocket.Chat#18154] opened 2020-07-04 02:23 UTC
### Description:

Can't deploy self-created app.

### Steps to reproduce:

```
~/zero# rc-apps deploy --url http://localhost:3000 --username rocket_admin --password password123
packaging your app... packaged!
deploying your app... !
    Error: Deployment error: Direct installation of an App is disabled.

```

### Expected behavior:

Install self-created apps.

### Actual behavior:

Error: Deployment error: Direct installation of an App is disabled.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.0
- Operating System: Debian 10
- Deployment Method: manual installation
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

How to enable installation apps for server?

**Comment by graywolf336** [comment] 2020-07-13 22:20
Closing because this is working as intended.

https://github.com/RocketChat/Rocket.Chat/blob/292a7c3b30e1946f65680c62a41b6771a6acfabb/app/apps/server/communication/rest.js#L220-L222

**Closed by graywolf336** 2020-07-13 22:20 UTC

**Comment by zeealik** [comment] 2020-12-11 12:21
How can we enable the direct installation of an app?

**Comment by zeealik** [comment] 2020-12-11 12:22
> Closing because this is working as intended.
> 
> https://github.com/RocketChat/Rocket.Chat/blob/292a7c3b30e1946f65680c62a41b6771a6acfabb/app/apps/server/communication/rest.js#L220-L222

is there any option so we can install directly from the server?

**Comment by graywolf336** [comment] 2020-12-11 19:23
Yes, see here: https://docs.rocket.chat/apps-development/getting-started#testing-the-app

**Comment by aditya-mitra** [comment] 2021-04-02 18:37
The Error *`Deployment error: Direct installation of an App is disabled`* is there because **the setting** for development needs to enabled in the **Apps** section inside **General**.

1. First go to the general tab

2. Scroll down to the **`Apps`** section
3. Enable the options for **`Enable development mode`**

![image](https://user-images.githubusercontent.com/55396651/113443913-7a77ef00-9410-11eb-8195-e96582ba7dff.png)

I have added this because the search was indexed on Google.

**Comment by varunsh17** [comment] 2022-11-15 17:03
The general section is not there !
How can I start dev mode now ??

**Comment by DeviaVir** [comment] 2022-12-20 18:06
Settings > General > Apps
