### ISSUE TITLE
[Feature request] Google meet integration

### ISSUE THREAD

**Issue by rjozwiak** [RocketChat/Rocket.Chat#14526] opened 2019-05-16 10:58 UTC
It would be nice to have Google Meet integration that would allow to create a google meet with the everyone in the room, channel or DM. The desired integration would add button in the room panel or custom command like “/meet” that would trigger new google meet and send link to current chat.

**Comment by zdumitru** [comment] 2019-05-16 11:03
Probably a duplicate of https://github.com/RocketChat/feature-requests/issues/65

**Comment by geekgonecrazy** [comment] 2019-05-22 06:35
Yes this is a duplicate.  Please see rules when opening an issue.  Feature requests all live in the other repo

**Closed by geekgonecrazy** 2019-05-22 06:35 UTC
