### ISSUE TITLE
High CPU ON webclient or Aplication desktop

### ISSUE THREAD

**Issue by kurrepa** [RocketChat/Rocket.Chat#24987] opened 2022-03-29 17:49 UTC
**Describe the bug**

What operating system and which version?
windows 10 / windows server 2016
Which version of Rocket.Chat (Server)?
4.5.4
Versión de Motor de Aplicaciones
1.31.0
Versión de Node
v14.18.3
MongoDB
4.0.21 / mmapv1 (oplog Habilitado)

Is there any setting relevant changed?
i am not secure

**To Reproduce**

1. When open the aplication rocketchat.exe the consume is over 5% and is stable
![image](https://user-images.githubusercontent.com/61122110/160665063-c7d9dc0c-bcd2-43bb-ab20-b0d649a3b001.png)

but when open rocketchat.exe is the same problem, the cpu is over 40%

![image](https://user-images.githubusercontent.com/61122110/160675271-31129f3e-2ce1-4f1c-8744-bfae973dda17.png)

but when the user login the consume is normal... over 5%

2 When put my url server chat (example https:chat.xxxx.com ) to cpu to up (i dont loging yet)
![image](https://user-images.githubusercontent.com/61122110/160665452-c11473d0-e4b2-433c-80ca-70ab8bd6e125.png)

3 When open webaplication in any navigator the consume increase too high to up 33%
![image](https://user-images.githubusercontent.com/61122110/160673359-9830bd5d-a0a3-4b00-8c94-fe6152642876.png))

![image](https://user-images.githubusercontent.com/61122110/160670190-48234497-d897-4f6a-aba3-9cf41dc2dec2.png)

4. In the windows server 2016 with various user the cpu server is over 100%

Finally when the user login whit credential in any cases the cpu is normal

**Comment by toppermitz** [comment] 2022-03-29 22:37
Same problem with mac app.  MacOS 12.3 on M1 chip.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/13020454/160717987-6c5cc0b2-58bc-43c1-9e7e-4258a3077ed5.png">

**Comment by ankar84** [comment] 2022-03-30 05:37
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/24970

**Closed by ankar84** 2022-03-30 05:37 UTC
Labels: feat: omnichannel, feat: voip
