### ISSUE TITLE
PDF filles appear upside down

### ISSUE THREAD

**Issue by mikeaer** [RocketChat/Rocket.Chat#15012] opened 2019-07-17 12:34 UTC
### Description:

When I send an pdf files, in some cases, pdf preview appear upside down

### Steps to reproduce:

1. Drag&drop an pdf file

### Expected behavior:

PDF  preview appear normally

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: CentOS
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: yes
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.9

**Comment by stleitner** [comment] 2019-07-18 09:35
We have the same problem on our server.

**Comment by ChrissW-R1** [comment] 2019-08-14 10:55
Same here. This is very annoying. The preview uses many space in a chat and could read from the most of our users.

**Comment by rwhorton66** [comment] 2020-01-16 15:01
Is there any update on this issue?

**Comment by engelgabriel** [comment] 2020-05-01 20:27
@mikeaer can you still replicate but on the open.rocket.chat server?

**Comment by aermike** [comment] 2020-05-02 17:54
On version3.0.11 this isssue apprear to be fixed

**Comment by ChrissW-R1** [comment] 2020-05-04 13:33
This error couldn't reproduced in version 3.2.0.

**Comment by rodrigok** [comment] 2020-05-25 15:47
I'll close this since we can't reproduce the issue anymore. Please open a new issue if it still persists.

**Closed by rodrigok** 2020-05-25 15:47 UTC
Labels: subj: ui/ux, type: bug
