### ISSUE TITLE
Uploaded image URLs should open browser instead of downloaded

### ISSUE THREAD

**Issue by tacman** [RocketChat/Rocket.Chat#1180] opened 2015-10-20 15:02 UTC
This is likely a system overload or configuration issue, as I believe the code already supports this.

When I upload an image, it doesn't display inline, and when I go to the link, it attempts to download the png rather than display it.  The picture is at

https://demo.rocket.chat/ufs/rocketchat_uploads/8hXZQfD34nXHKA8fH
##

**Comment by jonbaer** [comment] 2015-10-20 18:35
You may need to adjust your firewall settings (because on links your server will go out + fetch it after upload) ... ie:

iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp -m state --state NEW --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp -m state --state NEW --dport 443 -j ACCEPT

**Comment by gmsecrieru** [comment] 2015-10-21 16:18
@tacman could you please provide reproducible steps for this issue?

**Comment by tacman** [comment] 2015-10-21 16:26
It must have been a network issue, because now it works as expected.

Related feature request, though.  I'd prefer that clicking on

https://demo.rocket.chat/ufs/rocketchat_uploads/8hXZQfD34nXHKA8fH 

display the image in the browser, rather than prompting me to download it.

**Comment by gmsecrieru** [comment] 2015-10-21 16:33
In that case I will update the title to reflect your more-than-welcome suggestion for image downloads. Thanks!

**Comment by marceloschmidt** [comment] 2015-10-22 16:32
Is this an issue? Uploaded image files show a preview and if you click on it it will open  as a "popup" thing... if you click the actual link it will download it. That's by design.

**Comment by gmsecrieru** [comment] 2015-10-22 16:36
Yeah that's much of the conversation that is running on #1192 - For now I think this is not going to be supported.

**Comment by geekgonecrazy** [comment] 2015-10-24 02:04
If we added zoom to the preview or an option to show full size, then this wouldn't be an issue at all.

**Comment by flarehl** [comment] 2016-04-28 01:18
I'm new to open source but was assigned a project to contribute to one, I'd be interested in seeing if I can manage to get it working.

**Comment by geekgonecrazy** [comment] 2016-04-28 17:25
@flarehl we welcome pull requests.  Feel free to take a crack at it :+1:

**Comment by joeltello** [comment] 2016-07-15 01:35
what's the status of this issue? I want to start contributing to this project...

**Comment by geekgonecrazy** [comment] 2016-07-18 02:15
@joeltello no one is currently working on this.  Feel free to take a stab 👍

**Comment by joeltello** [comment] 2016-07-18 02:59
is there a diagram or some docs that could help me understand how the app is structured?

**Comment by geekgonecrazy** [comment] 2016-07-18 03:02
Not yet... :(  We're looking at doing that before long though.

**Comment by joeltello** [comment] 2016-07-19 15:13
ok I'll work on it, you can change it to WIP 💪

**Comment by tacman** [comment] 2016-07-19 18:20
This issue can be closed or renamed.  I believe the underlying cause of the
initial post was an overloaded server or poor network connection.

Tac

**Comment by joeltello** [comment] 2016-07-19 18:42
so the current behavior is that when you click on the link, a new tab pops up and shows you the systems' save dialog. I think this issue is about changing that behavior to only display the asset in a new tab, that's why I thought it could just be configuration, like a content header or something like that.

![image](https://cloud.githubusercontent.com/assets/6600095/16962214/85b21de8-4da5-11e6-8487-8cf22136ab5e.png)

new tab:

![image](https://cloud.githubusercontent.com/assets/6600095/16962288/c9a5371a-4da5-11e6-9248-0684a2e59869.png)

not sure how much benefit you can get from this change, but this is what I understood so far.

**Comment by geekgonecrazy** [comment] 2016-07-20 16:38
@joeltello likely you'll want to make this configurable.  So you'd want a setting to toggle this behaviour.  And then you're looking for a header that forces a download.  

Typically those headers are in the form of something like:
`'Content-Disposition: attachment; filename=copaamericalogo.jpg'`

I'm not 100% off hand what we're using here. But I know you'll want to look around the ufs stuff.  :smile:

**Comment by joeltello** [comment] 2016-07-20 17:14
Awesome @geekgonecrazy I'll give it a try!

**Comment by patrickemuller** [comment] 2017-02-13 17:21
Tried to change this line
https://github.com/RocketChat/Rocket.Chat/blob/develop/lib/fileUpload.js#L69 but this isn't the right thing, since didn't work ...
I spent a few hours searching for header and some configuration for this behavior, but didn't find any yet.

**Comment by AakarSharma** [comment] 2018-02-15 09:41
I want to solve this issue but I am not able to find where to start. Can someone guide me in which directory I should look into to solve the error?

**Comment by sudipt1999** [comment] 2019-03-13 22:44
I will give it a try as mentioned in comments we need to change the configuration of how it works , I guess we just need to show the img in browser and disabling its auto download pop up! @geekgonecrazy  I would like to start working on this!

**Comment by geekgonecrazy** [comment] 2019-03-14 00:34
feel free :) Its not currently in progress by anyone that I know of.

**Comment by sudipt1999** [comment] 2019-03-20 23:16
@geekgonecrazy, now the image is not auto downloaded, How can I reproduce the bug !
I guess we need to change `https://github.com/RocketChat/Rocket.Chat/blob/develop/app/file-upload/server/config/FileSystem.js#L20`

**Comment by sudipt1999** [comment] 2019-03-20 23:30
![Screenshot from 2019-03-21 04-57-04](https://user-images.githubusercontent.com/38929617/54725742-3d789100-4b96-11e9-8494-85cbd098d0d4.png)
![Screenshot from 2019-03-21 04-57-57](https://user-images.githubusercontent.com/38929617/54725745-3fdaeb00-4b96-11e9-87b9-8cf360de2ccc.png)

**Comment by geekgonecrazy** [comment] 2019-03-21 00:24
actually rereading I don’t think this has been an issue for a while.  Closing

**Closed by geekgonecrazy** 2019-03-21 00:24 UTC
Labels: contrib: easy
