### ISSUE TITLE
no response on clicking unpin message option

### ISSUE THREAD

**Issue by saurabhkanswal** [RocketChat/Rocket.Chat#16449] opened 2020-01-31 18:46 UTC
## My Setup
- Operating System: windows 10
- App Version: 2.18.0-develop
- Installation type: 

## Description
when pin a message then the message doesn't unpin by clicking unpin option /
when deleting a original message, pin message doesn't delete.

### Current Behavior
What actually happens?
     when we pinned a message and then try to unpin message. then the message doesn't unpin.
also when we delete a message(which was pin earlier), then also there is no option to delete pin message. 

### Expected Behavior
there should be delete option on pin message or unpin message option should work properly

**Comment by gabriellsh** [comment] 2020-02-04 13:02
Duplicate of #16061

**Closed by gabriellsh** 2020-02-04 13:02 UTC
