### ISSUE TITLE
When changing username, password and roles, the user update is not allowed.

### ISSUE THREAD

**Issue by Anish-addweb** [RocketChat/Rocket.Chat#11959] opened 2018-09-05 10:34 UTC
After snapd upgrading to version 0.69.0, when changing username password and roles, the user update is not allowed by admin role.

Rocket.Chat v0.69.0
Operating System: Ubuntu 16.04
Deployment Method: snapd packages.
![screenshot from 2018-09-05 15-56-13](https://user-images.githubusercontent.com/35479743/45088014-674ff600-b125-11e8-9db7-dc2058a64e8b.png)

**Comment by kaiiiiiiiii** [comment] 2018-09-05 10:54
Duplicate of #11884

Fixed in PR #11955

//CC: @TwizzyDizzy

**Closed** 2018-09-05 11:00 UTC
