### ISSUE TITLE
Error while renaming user

### ISSUE THREAD

**Issue by subesokun** [RocketChat/Rocket.Chat#4156] opened 2016-08-31 12:46 UTC
Hi,

for some reason I get the following error when trying to rename a user (i.e. change the username):

```
2016-08-31T12:32:33.250905172Z Exception while invoking method 'insertOrUpdateUser' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username
|2016-08-31T12:32:33.250983456Z     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
e2016-08-31T12:32:33.250996701Z     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
2016-08-31T12:32:33.251007217Z     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)
2016-08-31T12:32:33.251015357Z     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)
2016-08-31T12:32:33.251023912Z     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
2016-08-31T12:32:33.251063722Z     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
2016-08-31T12:32:33.251076781Z     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)
S2016-08-31T12:32:33.251085754Z     at _Class.update (server/models/_Base.js:78:29)
2016-08-31T12:32:33.251093753Z     at _Class.RocketChat.models.Messages._Class.updateUsernameAndMessageOfMentionByIdAndOldUsername (packages/rocketchat_lib/server/models/Messages.coffee:226:11)
h2016-08-31T12:32:33.251102017Z     at packages/rocketchat_lib/server/functions/setUsername.coffee:40:31
-2016-08-31T12:32:33.251110432Z     - - - - -
2016-08-31T12:32:33.251118191Z     at Object.toError (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
2016-08-31T12:32:33.251126321Z     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27
~2016-08-31T12:32:33.251134444Z     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7
~2016-08-31T12:32:33.251142373Z     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
2016-08-31T12:32:33.251150279Z     at Server.Base._callHandler (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
2016-08-31T12:32:33.251158468Z     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
2016-08-31T12:32:33.251167366Z     at [object Object].MongoReply.parseBody (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
2016-08-31T12:32:33.251175472Z     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
M2016-08-31T12:32:33.251183988Z     at [object Object].emit (events.js:95:17)
2016-08-31T12:32:33.251191991Z     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
```

After the error occurred the user won't see any channels as all roles have been remove from his user.

Your Rocket.Chat version: 0.37.1

**Comment by graywolf336** [comment] 2016-08-31 17:51
Duplicate of #3940

**Closed by graywolf336** 2016-08-31 17:51 UTC
