### ISSUE TITLE
Hint text under the "Read Only" option is not consistent with user's choice in the ”Create Channel“ dialog

### ISSUE THREAD

**Issue by lovelykd** [RocketChat/Rocket.Chat#22894] opened 2021-08-10 09:55 UTC
### Description:

When the "Read Only" option is turned on, the hint text is still "All users in the channel can write new messages"

### Steps to reproduce:

1. Go to home page
2. Create New -> Channel
3. Switch on the "Read Only" option

### Expected behavior:

The hint text should be something like "only the authorized users can write new messages" when the option is turned on

### Actual behavior:

![image](https://user-images.githubusercontent.com/2628956/128846929-02e7ce7c-584a-48a0-9790-572262a11c9d.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0-develop
- Operating System: Ubuntu 18.04 LTS
- Deployment Method: meteor npm start
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1 - x64
- MongoDB Version: 4.4.4

### Client Setup Information

- Desktop App or Browser Version: Microsoft Edge(92.0.902.67)
- Operating System: Windows

**Comment by johncrisp** [comment] 2021-08-10 16:56
Hi and thanks for reporting this.

I have raised it with the Product Team.

**Comment by johncrisp** [comment] 2021-08-10 17:59
I can confirm that this has been added to the next sprint for a fix. 

That will probably land in 3.18

Thank you very much!!

**Comment by lovelykd** [comment] 2021-08-11 03:06
@johncrisp Thank you for your quick response and it's my pleasure to contribute to this project. 
In fact i have raised a [PR](https://github.com/RocketChat/Rocket.Chat/pull/22895) for this issue. Is it possible for your team to review it?

**Comment by jbisinotti** [comment] 2021-08-11 21:51
I'm contributing in RC for a college subject. Can I do this fix?

**Comment by lovelykd** [comment] 2021-08-13 02:41
@jbisinotti Sure. Go ahead.

**Comment by matheusbsilva137** [comment] 2021-08-17 20:57
Thanks for reporting this issue 🤗 
I'll close this issue since it's been fixed in #21868

**Closed by matheusbsilva137** 2021-08-17 20:57 UTC
