### ISSUE TITLE
Directmessages show username and not the real name

### ISSUE THREAD

**Issue by charlyrock** [RocketChat/Rocket.Chat#23777] opened 2021-11-23 11:11 UTC
### Description:
If the person "Anna" writes to the person "Elsa", the direct message chat for "Elsa" is only displayed with Anna's username "a123". Up until the previous version this problem worked, but the new version now has this bug. This should be addressed urgently.

### Steps to reproduce:

1. Search for User
2. write a direct message to user
3. it will be shown the username and not the full name

### Expected behavior:

The full name will be shown.
### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.2 
- Operating System:  Ubuntu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version:4.2.17

### Client Setup Information

- Desktop App or Browser Version: Desktop App 3.6.0, Webbrowser Google Chrome
- Operating System: Windows 10

**Comment by ali-alhaidary** [comment] 2021-11-23 11:16
It would be even better to use 'alternate name' that is used with front ends like moodle...

**Comment by Gummikavalier** [comment] 2021-11-23 15:59
Linking as a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/23093

There is a workaround script to fix the wrong ones in the channel list too in it.

**Comment by hugocostadev** [comment] 2023-04-05 17:43
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there

**Closed by hugocostadev** 2023-04-05 17:43 UTC
