### ISSUE TITLE
Channels search not overlaps livechat and has weird margins

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#7870] opened 2017-08-25 02:30 UTC
### Description:
![overlaps](https://user-images.githubusercontent.com/8591547/29697204-1f391dc6-8924-11e7-969c-6cee437eda88.PNG)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.0
* Operating System: Windows

**Comment by engelgabriel** [comment] 2017-08-25 02:34
Caused by https://github.com/RocketChat/Rocket.Chat/pull/7865

**Comment by geekgonecrazy** [comment] 2017-08-25 02:58
Also related the status icon bleeds off the side when searching

![image](https://user-images.githubusercontent.com/51996/29697857-4b25c7ac-8917-11e7-919b-c7203bbbbcbe.png)

**Comment by gdelavald** [comment] 2017-08-25 05:15
@geekgonecrazy that last commend was fixed by #7880

**Closed** 2017-08-25 06:00 UTC
Labels: subj: UI Redesign, type: bug
