### ISSUE TITLE
Make the list of oembed providers configurable

### ISSUE THREAD

**Issue by srdjan-catalyst** [RocketChat/Rocket.Chat#8521] opened 2017-10-18 03:13 UTC
### Description:
Enable admin to add custom OEmbed providers and store them permanently

**Comment by brendanheywood** [comment] 2017-10-19 00:51
fyi duplicate of https://github.com/RocketChat/Rocket.Chat/issues/3898

**Comment by MartinSchoeler** [comment] 2017-10-23 10:38
Duplicate of #3898

**Closed by MartinSchoeler** 2017-10-23 10:38 UTC
