### ISSUE TITLE
[3.6.0]The users can't change public or private channel avatar.

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#18785] opened 2020-09-03 02:58 UTC
### Description:

rocket.chat 3.6.0 add change public or private channel avatar.I has upgrade it.The admin role can change it but users can't.I already enable users permission about edit room avatar.And I got error message like follow.

`Sep  3 10:41:07 chat rocketchat[1662]: Error: Error deleting file on webdav
Sep  3 10:41:07 chat rocketchat[1662]:     at app/webdav/server/lib/webdavClientAdapter.js:41:10
Sep  3 10:41:07 chat rocketchat[1662]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Sep  3 10:41:07 chat rocketchat[1662]: Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined
Sep  3 10:41:07 chat rocketchat[1662]:     at app/lib/server/functions/setRoomAvatar.js:34:46
Sep  3 10:41:07 chat rocketchat[1662]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Sep  3 10:41:07 chat rocketchat[1662]:     at packages/meteor.js:550:25
Sep  3 10:41:07 chat rocketchat[1662]:     at runWithEnvironment (packages/meteor.js:1286:24)`

I haven't enable webdav.I store type is gridfs.Could I miss another settings?Please help me.

### Steps to reproduce:

1. Click channel and click Room information
2. Click edit and click upload and choose I want change avatar
3. click save but not change avatar

### Actual behavior:

![圖片](https://user-images.githubusercontent.com/6081927/92066260-10449080-edd4-11ea-86f3-fc2fada8e714.png)
![圖片](https://user-images.githubusercontent.com/6081927/92066345-3833f400-edd4-11ea-9b5a-9957ca9f86b4.png)
![圖片](https://user-images.githubusercontent.com/6081927/92066404-5dc0fd80-edd4-11ea-9178-2bac060dc2f0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: enable
- NodeJS Version: 12.16
- MongoDB Version: 4.0.20

### Client Setup Information

- Desktop App or Browser Version: 2.17.11
- Operating System: Win10

**Comment by ankar84** [comment] 2020-09-03 10:19
I confirm that but for not administrator user that owner of room.

**Comment by klepptor** [comment] 2020-09-03 12:53
Same here, I store the file in the filesystem. Only the admin account can change the avatar.

**Comment by capricorn72** [comment] 2020-09-03 15:26
Seems to be a general avatar problem.
1. User avatars cannot be uploaded, too.
2. LDAP login fails with "wrong password" message (sic!) when thumbnail sync is activated.

**Comment by larkinson** [comment] 2020-09-03 19:17
Since when rooms can have avatars in Rocket.Chat? I don't see that feature in any of my Rocket.Chat installations and haven't seen it since the year 2018.

**Comment by klepptor** [comment] 2020-09-03 20:39
@larkinson Check the Release notes of 3.6.0 ;)

**Comment by charlyrock** [comment] 2020-09-04 10:23
Same here Version 3.6.0
Try to change Profile avatar I get the error message "The formData parameter MUSTbe an instance of the FormData class."

If I try to change the avatar of a channel, the "hide system message" option is reset.
And I get the following message in the error log: Exception in setTimeout callback: TypeError: Cannot read property 'etag' of undefined at app/lib/server/functions/setRoomAvatar.js:34:46 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12) at packages/meteor.js:550:25 at runWithEnvironment (packages/meteor.js:1286:24)

Need urgent a solution to fix it

**Comment by prigal** [comment] 2020-09-04 14:48
Possible duplicate of #18736

**Comment by frdmn** [comment] 2020-09-09 08:17
Will close this in favour or #18736. There is a PR in place to fix this problem, more information in the main issue.

**Closed by frdmn** 2020-09-09 08:17 UTC

**Comment by cprice-kgi** [comment] 2020-10-22 17:46
Even with this change integrated, I'm still seeing the issue in 3.6.0 when trying to change channel avatars. However, the good news is I think I have a fix. The bad news is I've never done a PR to contribute before, so I'll give it a shot.
