### ISSUE TITLE
User still muted in read only group after role update (with permission [post-readonly])

### ISSUE THREAD

**Issue by driesmeyers** [RocketChat/Rocket.Chat#11029] opened 2018-06-07 12:29 UTC
Description:
I created a read-only private group where only users with a specific role (with permission [post-readonly]) can add messages to the group. When adding this role (REST API) to a user who was muted before, nothing changes. He is still unable to talk. Only when I unmute him personally from the right-hand menu he is able to post messages.
(When removing the role the user can still talk so it's the same problem in both directions)
I'm not sure if it's intended to work this way.

Server Setup Information:
Version of Rocket.Chat Server: 0.65.1
Operating System: macOS 10.13.4 High Sierra
Deployment Method(snap/docker/tar/etc):
Number of Running Instances: 1
DB Replicaset Oplog: Enabled
Node Version: v8.11.1
mongoDB Version: 3.4.10

Steps to Reproduce:
Create Read-only private group 
Add any user to the group
Give him a role with permission [post-readonly]

Expected behavior:
User is now able to post messages in the private group

Actual behavior:
User is still muted and sees "This room is read only" message at the bottom of the message box

**Comment by Hudell** [comment] 2018-06-07 15:59
Duplicate of #4769

**Closed by Hudell** 2018-06-07 15:59 UTC
