### ISSUE TITLE
Scrollbars are hard to see

### ISSUE THREAD

**Issue by ans-artal** [RocketChat/Rocket.Chat#32492] opened 2024-05-23 12:04 UTC
The scroll bar can be really hard to see.

This was an issue on the server version of rocket chat :
https://github.com/RocketChat/Rocket.Chat/pull/32341
https://github.com/RocketChat/Rocket.Chat/issues/32367

It have been improved on the server version.

Why this isn't the case in the application version ?

**Comment by ans-artal** [comment] 2024-05-28 15:46
![Screenshot from 2024-05-28 17-45-02](https://github.com/RocketChat/Rocket.Chat/assets/92530185/bcad517c-b913-4414-8b6a-a395b10fbaad)
I'm on version 3.9.14

**Comment by reetp** [comment] 2024-05-29 13:25
Closing as duplicate of #32367

https://github.com/RocketChat/Rocket.Chat/issues/32367#issuecomment-2104614119

> I'm sorry, maybe I wasn't clear enough. This change is already on our latest development version.
> It will be released on 6.9.0

Please test on open.rocket.chat to see if it still appears.

You should see the change on your own server on upgrade to 6.9.x

**Closed by reetp** 2024-05-29 13:25 UTC
Labels: duplicate

**Comment by ans-artal** [comment] 2024-05-29 13:54
It's weird, I'm sure I put this issue on the "Electron" part of the rocket.chat repo


I'm aware that this issue is fixed in the last server version of rocket.chat.
That is the third sentence I wrote :
> It have been improved on the server version.


But that does not help me know why this change is not in the "Electron" version of rocket.chat

3.9.14 is the “Electron” version, not the server version.
3.9.14 is supposed to be close to the latest

**Comment by reetp** [comment] 2024-06-06 10:59
> It's weird, I'm sure I put this issue on the "Electron" part of the rocket.chat repo

Nope :-)

> 3.9.14 is the “Electron” version, not the server version.

Yes we are aware.

> 3.9.14 is supposed to be close to the latest

Currently 3.9.15 and 4.0.0 are released.

But IIRC  the Electron client is really just a Chromium browser wrapper to Rocket so what you see is determined by the server, not the client.

You can test it on open.rocket.chat and see.

**Comment by ans-artal** [comment] 2024-06-06 12:25
> But IIRC the Electron client is really just a Chromium browser wrapper to Rocket so what you see is determined by the server, not the client.

Mmm ok yes. I was wrong about the cause of the problem, it's not related to the desktop application.
I just tried with Google Chrome and got the same issue.
Whereas with Firefox, the scrollbar is visible.

I tried with "https://open.rocket.chat/" and it work on both browsers

Then it's our server admin settings I guess..
No ?


-----

>     _It's weird, I'm sure I put this issue on the "Electron" part of the rocket.chat repo_
> Nope :-)

What does this mean ?

![Screenshot from 2024-06-06 14-15-58](https://github.com/RocketChat/Rocket.Chat/assets/92530185/23641bd4-0f97-4c6e-bdc7-012fc41e3d95)

**Comment by reetp** [comment] 2024-06-11 11:37
> Then it's our server admin settings I guess..

Nope - it is the version of Rocket.Chat server that you are using. When you upgrade to 6.9.x the problem will resolve.

> It's weird, I'm sure I put this issue on the "Electron" part of the rocket.chat repo_

Actually my bad  - you did but this:

> jeanfbrito transferred this issue from RocketChat/Rocket.Chat.Electron

means it was in the wrong repo and was transferred here because it is a Rocket.Chat issue, not an Electron issue.

**Comment by ans-artal** [comment] 2024-06-11 12:08
Ok thank you
