### ISSUE TITLE
[BUG] Cannot use deleted user's username for creating new user

### ISSUE THREAD

**Issue by himanshumalviya664** [RocketChat/Rocket.Chat#24427] opened 2022-02-06 16:59 UTC
### Description:
Cannot use username of deleted user while creating new user through that username through error 'User already in use'

### Steps to reproduce:

1. Go to Admin
2. Click on Users
3. Create New User

### Expected behavior:

New User can use the username of deleted user.

### Actual behavior:

https://user-images.githubusercontent.com/76220055/152691624-f3923722-314e-488c-83c5-7bac09be0191.mp4

### Server Setup Information:
Version of Rocket.Chat Server: 4.5.0-develop
Operating System: Linux ubuntu 20.04
NodeJS Version: v14.18.2
MongoDB Version: 4.4.4 / wiredTiger (oplog Enabled)

### Client Setup Information
Desktop App or Browser Version: Chrome 97.0.4692.99 (Official Build) (64-bit)
Operating System: Linux Ubuntu 20.04

**Comment by eduardofcabrera** [comment] 2022-02-07 12:54
Hi @Himanshu664, I will check this issue.

**Comment by eduardofcabrera** [comment] 2022-02-07 13:14
@Himanshu664 I tested here with the last develop and seems to be working fine.

**Comment by Himanshu664** [comment] 2022-02-07 13:22
Okay I will try again thanks for verifying.

**Comment by Kunalvrm555** [comment] 2022-03-06 14:07
LGTM
I followed the steps mentioned above but the bug wasn't reproduced.
Kindly close this issue.

https://user-images.githubusercontent.com/67605729/156926725-bfd52899-8a48-408e-b03f-6367fb712d60.mp4

**Comment by hugocostadev** [comment] 2023-04-06 11:33
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Closed by hugocostadev** 2023-04-06 11:33 UTC
