### ISSUE TITLE
Rocket chat doesn't open to the specified url

### ISSUE THREAD

**Issue by Jacxon** [RocketChat/Rocket.Chat#34005] opened 2024-11-19 23:38 UTC
I'm part of the day trade learning community but am not able to get into the chat area. I tried support from day trading center and they said it has to be rectified from the rocket chat people. I've attached a screenshot of what I get

https://github.com/user-attachments/assets/d0efeda3-9154-4c4a-8e72-067f88f9ac33

Thanks
Jack

**Comment by reetp** [comment] 2024-11-20 11:10
This is not a bug.

Rocket.Chat has no access to your system - you need to contact the adminsitrators of your system.

If it is hosted by Rocket.Chat or they have a licence then the admins will need to speak to Rocket.Chat support themselves.

This cannot be resolved in github.

Closing not a bug.

**Closed by reetp** 2024-11-20 11:10 UTC
Labels: type: support
