### ISSUE TITLE
Api create user

### ISSUE THREAD

**Issue by wangcc57** [RocketChat/Rocket.Chat#24910] opened 2022-03-22 15:55 UTC
call interface create user,timeout
but the user created successful

**Comment by wangcc57** [comment] 2022-03-22 17:10
yes

**Comment by aman-simplycool** [comment] 2022-03-22 17:15
hey please can you be more clear about the issue you raised because I am unable to find and get this issue.

**Comment by wangcc57** [comment] 2022-03-23 01:15
rocketChatClient.getUsersApi().create(createUserRequest);

call this api,you will found the issue

**Comment by dudanogueira** [comment] 2022-03-24 16:50
Hi! This is probably something on the library side or deployment.

Please, try the curl command as the documentation so you can eliminate as a server bug:
https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/users-endpoints/create-user-endpoint

Closing for now. 
Please reopen if necessary, providing more information and how to reproduce.

**Closed by dudanogueira** 2022-03-24 16:50 UTC

**Comment by wangcc57** [comment] 2022-03-26 02:06
install Rocket.Chat server by docker, https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml
call the API  users.create by curl, still timeout, but the user created success.

[root@iZwz9ee5ye356hitr5k9okZ ~]# curl -H "X-Auth-Token: Ro3TxvYieJH4OqyKTlaznvHqlABjrRhQf84fPyRXfVW" \
>      -H "X-User-Id: jGAmPLygEzsFvnsK4" \
>      -H "Content-type:application/json" \
>      http://localhost:3000/api/v1/users.create \
>      -d '{"name": "2222", "email": "2222@user.tld", "password": "22222222", "username": "2222"}'

curl: (52) Empty reply from server
