### ISSUE TITLE
Win32 App shows 'black screen' when focused after being out of focus for a few minutes

### ISSUE THREAD

**Issue by Instinct64** [RocketChat/Rocket.Chat#2982] opened 2016-04-21 11:34 UTC
Your Rocket.Chat version: 1.2.0 (win32)

**Summary:** When the rocket chat desktop app is left minimised or out of focus connection to the server is lost. If re-focused within a minute or so you see the status message at the top of the client "Connection failed, retrying in X seconds". If left minimised long enough the web area is just black and never recovers.

This issue has been witnessed on two seperate PC's running Windows 10.

**Reproduction Steps:**
1. Launch Rocket Chat on Win32 & Connect to a Server
2. Minimise the Rocket Chat Client to taskbar
3. Maximise the Rocket Chat Client from the taskbar after 10 minutes.
4. Observe the issue.

![rc-connect-1](https://cloud.githubusercontent.com/assets/7610500/14707440/ba25806c-07bc-11e6-8ede-3db8fab1760b.JPG)
![rc-connect-2](https://cloud.githubusercontent.com/assets/7610500/14707441/ba378460-07bc-11e6-9907-16211615e3d3.JPG)
![rc-connect-3](https://cloud.githubusercontent.com/assets/7610500/14707442/ba5b71cc-07bc-11e6-8d74-ec1a2ee409fd.JPG)

**Comment by lunitic** [comment] 2016-04-21 11:48
I have also notice this issue on one PC. The PC is a Win 10 64bit. 

The PC has dual graphic cards  
GTX 960 and a onboardIntel graphic card.

**Comment by Instinct64** [comment] 2016-04-21 12:29
This has been observed on Windows 10 64-bit and on machines with both just on-board (Intel), and on-board as well as discrete (Nvidia GTX960M) graphics.

**Comment by stevenhfotofix** [comment] 2016-04-21 15:22
Reported on the repo for the app itself:

https://github.com/RocketChat/Rocket.Chat.Electron/issues/150

We have been eagerly waiting for a fix.

**Comment by twhiting** [comment] 2016-04-21 17:38
This has been posted multiple times on the Electron project (Over two weeks ago), for some reason the development on that has stagnated a bit.

I actually spent the time to build a release for 1.3.1 myself and this issue went away for me and all the people in our company, I followed the docs for how to build a release.  I'm not entirely sure why the issue went away but maybe it will work for you guys as well :)

**Comment by Sing-Li** [comment] 2016-04-21 17:42
If you or your company is experiencing this problem, and have not made a comment yet - but waiting for its resolution.   Please add a comment !  

Open source projects like Rocket.Chat depends on community feedback to gauge priority of work.

**Comment by DavidDyran** [comment] 2016-04-21 17:47
I have the same issue, but it also happens during active use. There is no real pattern to this. Sometimes I can use it for 10 minutes, sometimes it doesn't even survive 1 minute after the application reload. I did not try the new version, just the current release.

**Comment by stevenhfotofix** [comment] 2016-04-21 17:53
Our company is staying on 1.1.0 - since that one has no problems at this time.  The problem was introduced in 1.2.0, and continues in 1.3.0 and 1.3.1

**Comment by Sing-Li** [comment] 2016-04-21 19:26
Main ticket on this issue is RocketChat/Rocket.Chat.Electron#173  and MANY OTHER similar tickets on the Rocket.Chat.Electron project repository.

**Comment by danielcandea** [comment] 2016-04-22 08:31
It happens to me on two different machines and some colleagues as well, all on Windows 10 64 bit.
I can't reproduce it as it seems to happen randomly.

**Comment by MrDragon** [comment] 2016-04-25 14:57
We have the same issue (posting because if Sing-Li's comment) - and I've almost convinced everyone to drop that Sl*ck thing... :(
I'm trying to use twhiting's approach in following the "build your own" instructions as to appease the relevant people where I work - possibly with killing the spellcheck libraries off (if i figure out how to do that)

**Comment by twhiting** [comment] 2016-04-25 15:32
@MrDragon I didn't disable spellcheck, just built my own build and its working great for us.  Still wish we could get an official fix though its been weeks since the last release

**Comment by MrDragon** [comment] 2016-04-25 17:14
Sorry, the spellcheck idea was from a different ticket. But yes, I did manage to fumble my way through creating my own installer and, well, if I continue the sentence I'll jinx it. But so far I'd say I owe you a beverage for your tip ;)

**Comment by geekgonecrazy** [comment] 2016-04-25 17:30
@MrDragon so removing the spellcheck stuff seems to have helped?

**Comment by Sing-Li** [comment] 2016-04-25 17:35
Very likely to be a problem of Chromium compositor GPU optimization.

Can we please report some information on the Video Card hardware and Video driver version on the system(s) that have this problem. Thanks.

**Comment by stevenhfotofix** [comment] 2016-04-25 17:37
Nvidia Quadro K620 - Driver version: 10.18.13.5382

**Comment by twhiting** [comment] 2016-04-26 04:35
@geekgonecrazy Don't have to disable spellcheck.  Seems building a build myself fixed the issue, looks like it worked for @MrDragon as well

**Comment by Sing-Li** [comment] 2016-04-27 14:16
Good news.    Please help test this version with GPU optimization disabled. 

Please uninstall existing version, install this one, and run it for a few days on problematic system(s).

Please let us know if it solves the problem on those systems.

[installer for test solution to black squares problem](https://cdn-download.rocket.chat/build/rocketchat-v1.3.1-nogputest-win32-ia32.exe)

**Comment by geekgonecrazy** [comment] 2016-04-28 17:29
@twhiting I think which ever computer was used to build had the spellcheck module left over from a previous npm install.   Because I noticed building my self I also didn't have this problem.

**Comment by twhiting** [comment] 2016-04-28 18:01
@geekgonecrazy glad we found a fix :+1:

**Comment by geekgonecrazy** [comment] 2016-04-28 19:21
Going to close this issue in favor of: https://github.com/RocketChat/Rocket.Chat.Electron/issues/150  I think this is resolved, but lets consolidate so we can update one issue.

Thanks!

**Closed by geekgonecrazy** 2016-04-28 19:21 UTC

**Comment by geekgonecrazy** [comment] 2016-04-29 18:36
Just to close the loop:  Please download the new Windows installer from the release page: [here](https://github.com/RocketChat/Rocket.Chat.Electron/releases/tag/1.3.1)

If you're seeing graphical glitches other then just full blackout try out the build @Sing-Li Posted: [GPU-Accel Disabled Windows Build](https://cdn-download.rocket.chat/build/rocketchat-v1.3.1-nogputest-win32-ia32.exe)

In the future we're going to add the option to disable into the main installer.  Please let us know if you have any issues here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/150
