### ISSUE TITLE
[BUG] [UI] Message menu position is incorrect on Firefox 55.0.2

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#8086] opened 2017-09-10 15:01 UTC
Hi guys,
Message menu position is incorrect on Firefox 55.0.2. See below gif for more info:

![menu position issue](https://user-images.githubusercontent.com/25859075/30250117-77353ff4-965e-11e7-9eaa-c0dcb438bd15.gif)

**Comment by MartinSchoeler** [comment] 2017-09-11 12:42
Duplicate of #

**Closed** 2017-09-11 12:42 UTC
