### ISSUE TITLE
Assets labels not showing

### ISSUE THREAD

**Issue by dval** [RocketChat/Rocket.Chat#26901] opened 2022-09-19 22:09 UTC
### Description:

I just installed rocketchat-server via snap package on Ubuntu 22.04.
I setup Apache as a proxy all following[ guide on rocketchat](https://docs.rocket.chat/quick-start/environment-configuration/configuring-ssl-reverse-proxy) site.
Everything connects as expected. I have no errors in Apache logs.

When I navigate to Administration -> Settings -> Assets  the form is just repeating input boxes void of all labels.
![Screenshot 2022-09-19 174731](https://user-images.githubusercontent.com/1014630/191125709-f9742e54-79a7-40f0-bb23-25ea6bce447a.png)

I can see in the source that each input label has a unique title that is filled in. But the text value that would be displayed to end-user is empty.
```
...
<label for="Assets_logo" title="Assets_logo" class="rcx-box rcx-box--full rcx-label  rcx-box rcx-box--full rcx-field__label"></label>
...
...
<label for="Assets_background" title="Assets_background" class="rcx-box rcx-box--full rcx-label  rcx-box rcx-box--full rcx-field__label"></label>
...
...
<label for="Assets_favicon_ico" title="Assets_favicon_ico" class="rcx-box rcx-box--full rcx-label  rcx-box rcx-box--full rcx-field__label"></label>
...
```
etc.

### Steps to reproduce:

1. Start a new instance of Ubuntu22.04.
2. Install Apache2.4.
3. Configure Apache2.4 per [guide](https://docs.rocket.chat/quick-start/environment-configuration/configuring-ssl-reverse-proxy).
4. Setup rocketchat by creating the first admin user.
5. Navigate to Administration > Settings > Assets and see a nondescript form.

### Expected behavior:

I would expect the form labels to have values that would be readable without having to view source code.

### Actual behavior:

The Assets form offers no hints or information as to what any of the assets are. All the labels are blank. There are no tooltips or popups.

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.6
- Operating System: Ubuntu 22.04
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.3
- MongoDB Version: 4.4.1

### Client Setup Information

- Desktop App or Browser Version:  Chrome, Firefox, Edge
- Operating System: Client OS: Win10. Server OS: Ubuntu 22.04

### Relevant logs:
There are no errors in the browser. What logs would you need from chrome?
The only error in rocketchat logs should have nothing to do with this issue:
`I20220919-20:39:22.530(0) Exception in defer callback: Error: You have not provided a mail URL. You can provide it by using the environment variable MAIL_URL or your settings. You can read more about it here: https://docs.meteor.com/api/email.html.     at Object.Email.send (packages/email/email.js:259:11)     at AccountsServer.Accounts.sendEnrollmentEmail (packages/accounts-password/password_server.js:553:9)     at app/lib/server/functions/setUsername.ts:47:14     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)     at packages/meteor.js:555:25     at runWithEnvironment (packages/meteor.js:1320:24)`

Is there somewhere else I should look?

**Comment by ankar84** [comment] 2022-09-20 06:16
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/26502

**Closed by ankar84** 2022-09-20 06:16 UTC
