### ISSUE TITLE
Channel page blank maybe because of messages being in the wrong order

### ISSUE THREAD

**Issue by jmatsushita** [RocketChat/Rocket.Chat#2294] opened 2016-02-21 18:05 UTC
Your Rocket.Chat version: 0.18.1

I was playing with integrations and re-sending payloads to the incoming webhook which resulted in some messages appearing earlier in the timeline (either because of resending the payloads or time differences between my client and server). Before the channel became blank I deleted a couple of recent messages and then the channel started appearing blank.

The javascript console outputs this error:

```
Exception from Tracker recompute function: 90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js:3:5763
Error: {{#each}} currently only accepts arrays, cursors or falsey values. 90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js:3:5763
s@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:79:944
c.observe/c</<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:79:704
t.nonreactive@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:4260
c.observe/c<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:79:537
t.Computation.prototype._compute@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:2366
t.Computation@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:1298
t.autorun@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:4079
c.observe@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:79:506
d.Each/<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:28231
n@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:19819
t.nonreactive@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:4260
d._fireCallbacks/<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:19734
d._withCurrentView@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:22533
d._fireCallbacks@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:19702
d._createView@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:20003
d._expandView@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:20954
.visitObject@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:21343
.visit@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:77:1079
.visitArray@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:77:1888
.visitChildren@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:77:2311
.visitTag@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:77:2102
.visit@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:77:712
.visitArray@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:77:1888
.visitChildren@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:77:2311
.visitTag@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:77:2102
.visit@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:77:712
d._expand@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:21871
d._expandView@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:21075
.visitObject@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:21343
.visit@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:77:1079
d._expand@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:21871
d._expandView@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:21075
d.toHTMLWithData@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:24304
r.toHTMLWithDataNonReactive/<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:327:528
t.nonreactive@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:4260
r.toHTMLWithDataNonReactive@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:327:488
r.renderNonReactive/</a<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:327:834
l@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:20508
l/</<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:18463
e._withTemplateInstanceFunc@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:84:4982
l/<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:18406
d._withCurrentView@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:22533
l@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:18364
t.Computation.prototype._compute@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:2366
t.Computation@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:1298
t.autorun@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:4079
d.View.prototype.autorun@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:18543
d._materializeView/<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:20445
t.nonreactive@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:4260
d._materializeView@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:20420
e@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:14911
d._materializeDOM@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:14145
d._materializeDOM@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:14189
d._materializeView/<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:20871
t.nonreactive@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:4260
d._materializeView@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:20420
d.render@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:83:23491
this.RoomManager</c@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:251:16375
this.openRoom/</n<@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:180:8639
t.Computation.prototype._compute@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:2366
t.Computation.prototype._recompute@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:2601
t._runFlush@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:35:3564
e@https://im.example.org/90eb095829ef4ecc01915a8bbdcb1ae51e8ae8de.js?meteor_js_resource=true:3:2033
```

**Comment by Sing-Li** [comment] 2016-02-24 13:46
Thanks @jmatsushita !   We've observed this previously in conjunction with incoming webhooks but were never able to reproduce.

If you can provide a reproducible test case - it would be golden.

**Comment by jmatsushita** [comment] 2016-02-24 14:11
Wish I had time... If I did, this is what I would do:
 - setup an incoming hook with a hubot account as the posting user
 - setup Huginn or Zapier to post to the endpoint
 - send a few events
 - re-deliver an older payload and see if that posts out of order.

Bonus:
 - Delete some messages and see if it reproduces the blank channel screen

Wish I could help more!

**Comment by MartinSchoeler** [comment] 2017-07-13 14:30
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Closed by MartinSchoeler** 2017-07-13 14:30 UTC
Labels: type: bug, type: need more info
