### ISSUE TITLE
Update to 3.8.0 is not updating to 3.8.0 

### ISSUE THREAD

**Issue by gcommit** [RocketChat/Rocket.Chat#19587] opened 2020-11-18 10:03 UTC
### Description:

I downloaded 3.8.0 with `curl -fSL "https://releases.rocket.chat/3.8.0/download" -o rocket.chat.tgz`
But when i start up, version 3.7.2 with Commit Tag 3.8.0 is installed. WHY

### Steps to reproduce:

1. curl -fSL "https://releases.rocket.chat/3.8.0/download" -o rocket.chat.tgz
2. install it. 

### Expected behavior:

Version 3.8.0 is installed

### Actual behavior:

3.7.2 is installed with commit tag 3.8.0

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8.0 - but not, but yes, but no. 
- Operating System: Debian ) / Docker image node:12.18-slim
- Deployment Method: docker
- Number of Running Instances: 40
- NodeJS Version: 12.18
- MongoDB Version: 3.6.13

### Client Setup Information

- Desktop App or Browser Version: Browser Version what ? 
- Operating System: not even necessary to know. 

### Additional context

-

### Relevant logs:

-

![Bildschirmfoto 2020-11-18 um 10 57 57](https://user-images.githubusercontent.com/18714033/99515729-a167e400-298d-11eb-9244-433db3cfa811.png)

**Comment by bjozet** [comment] 2020-11-19 13:06
duplicate of #19553?

**Comment by sampaiodiego** [comment] 2020-11-19 19:34
yes.. both are fixed.

**Closed by sampaiodiego** 2020-11-19 19:34 UTC
