### ISSUE TITLE
Move unread messages above livechat list

### ISSUE THREAD

**Issue by xvonabur** [RocketChat/Rocket.Chat#10443] opened 2018-04-13 13:35 UTC
### Description:

Hello!

I'm using Rocket.Chat as livechat server. Unread messages list is very handy, but unfortunately it is below live messages list:

![screen shot 2018-04-13 at 16 22 30](https://user-images.githubusercontent.com/616857/38737414-c6dcda12-3f37-11e8-9c27-85b771dbc5d8.png)

I would like to see it above like with incoming livechats:

![screen shot 2018-04-13 at 16 22 13](https://user-images.githubusercontent.com/616857/38737450-ea6d5182-3f37-11e8-81d4-a5629b7e8e13.png)

Can we move it to the top of sidebar?  

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.0
* Operating System: Ubuntu 16
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1

**Comment by kaiiiiiiiii** [comment] 2018-04-13 13:41
Duplicate of #10022 I think :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by theorenck** [comment] 2018-04-13 16:40
Thanks @xvonabur for reporting the issue. @renatobecker as @kaiiiiiiiii mentioned this issues are close related, but how close they are? Can you confirm this as duplicate?

**Comment by xvonabur** [comment] 2018-06-19 08:02
@renatobecker I saw that #10734 was merged, but I still experiencing this behaviour on latest docker image (0.65.2).

**Comment by renatobecker** [comment] 2018-07-02 20:40
@theorenck, It's not duplicated. The fix on #10734 is not related to this issue.
@xvonabur is asking for changing the `unread on top` section when Livechat is enabled.
We need to analyze the current behaviour, planning to move the `unread on top` section above the Livechat queue.
I agree that it would provide a better user experience, but we need to discuss this question.

**Comment by xvonabur** [comment] 2018-08-28 17:45
@renatobecker any news?

**Comment by xvonabur** [comment] 2018-09-05 08:33
Hi @renatobecker!

I don't mind changing sorting of `Open Livechats`, but we do have already separate section of `Unread` messages. In my opinion it's crucial to move `Unread` section above anything else, because it's most important one.

I think It can be achieved by using [flex order attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items#The_order_property) and some JS code. Maybe it's not ideal solution, but working one.

**Comment by renatobecker** [comment] 2020-02-27 17:54
Closed by https://github.com/RocketChat/Rocket.Chat/pull/16437.

**Closed by renatobecker** 2020-02-27 17:54 UTC
Labels: feat: livechat, type: improvement
