### ISSUE TITLE
stuck at login page by refresh once per second

### ISSUE THREAD

**Issue by beanslee2011** [RocketChat/Rocket.Chat#15866] opened 2019-11-27 09:01 UTC
Server Setup Information:
Version of Rocket.Chat Server: 1.0.3   [ **now upgrade to 2.2.1 ,but problem is same** ]
Operating System: centos 7.4
Deployment Method: Manual by official doc
Number of Running Instances: 1
DB Replicaset Oplog: true
NodeJS Version: 8.11.3
MongoDB Version: 3.6.12

=====
After a server machine reboot, I can't login to rocketchat,and start log is:
{"line":"121","file":"migrations.js","message":"Migrations: Not migrating, already at version 144","time":{"$date":1568616267114},"level":"info"}
Loaded the Apps Framework and loaded a total of 0 Apps!
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Updating process.env.MAIL_URL
➔ System ➔ startup
➔ +--------------------------------------------------+
➔ | SERVER RUNNING |
➔ +--------------------------------------------------+
➔ | |
➔ | Rocket.Chat Version: 1.0.3 |
➔ | NodeJS Version: 8.11.3 - x64 |
➔ | MongoDB Version: 3.6.12 |
➔ | MongoDB Engine: wiredTiger |
➔ | Platform: linux |
➔ | Process Port: 3000 |
➔ | Site URL: http://x.x.x.x:3000 |
➔ | ReplicaSet OpLog: Enabled |
➔ | Commit Hash: f19473c |
➔ | Commit Branch: HEAD |
➔ | |
➔ +--------------------------------------------------+
![rc](https://user-images.githubusercontent.com/3379460/69708643-f08e8680-1136-11ea-895b-fe91d2cbc04d.gif)

======at the version of 2.2.1,the start log is:
 {"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 166","time":{"$date":1574831509250},"level":"info"}

thanks~~

**Comment by reetp** [comment] 2019-11-27 15:11
@rocket.cat close

First this is likely a duplicate of #15373 

Second it is almost certainly a support issue rather than a bug.

You are not being very clear about what you are doing.

> Not migrating, already at version 144
> Not migrating, already at version 166

These mean that when you run a particular version of Rocket.Chat it will check for the DB schema version. If the schema is at the correct version (caused by a previous upgrade) the upgrader will not run again. These are not errors.

If you see this in your logs it means your server is running:

➔ System ➔ startup
➔ +--------------------------------------------------+
➔ | SERVER RUNNING |
➔ +--------------------------------------------------+
➔ | |
➔ | Rocket.Chat Version: {version} |

So you have provided no evidence that anything is actually broken, Your issues are more likely to be a failed upgraded procedure. Probably worth restoring a good working backup and then trying to upgrade incrementally with backups in between eg 1.0.x - 1.3.x -> 2.0.x etc

Please follow these carefully.

https://rocketchat.github.io/docs/contributing/reporting-issues/
https://rocketchat.github.io/docs/getting-support/

**Closed** 2019-11-27 16:44 UTC
