### ISSUE TITLE
Block code hides parts of the code

### ISSUE THREAD

**Issue by sanbor** [RocketChat/Rocket.Chat#536] opened 2015-08-21 14:10 UTC
Post the following message: `(three backticks)from .finance import (commission, slippage)(three backticks)`

Observe how the word `from` dissapears when the message is posted.

**Comment by graywolf336** [comment] 2015-08-21 17:34
Here's a screenshot:
![2015-08-21_12-34-06](https://cloud.githubusercontent.com/assets/850391/9414824/f3c88c46-4800-11e5-802d-eba73f011b3a.png)

**Comment by geekgonecrazy** [comment] 2015-08-21 17:36
Code snippet:
```
 ```from .finance import (commission, slippage)```
```
Just have to include a space in front here on github

**Comment by rodrigok** [comment] 2015-08-22 00:05
The first word after three backticks without spaces before is used as the language name to render the block.

Because this we have line breaks in the example below of the message field.
Single line quote must use a single backtick.

I will close this issue why this is the expected behavior, but if someone have any idea to improve this tell us and we will reopen the issue.

**Comment by graywolf336** [comment] 2015-08-22 00:25
An idea I just got for this to prevent the reported item is to detected if
there are any line breaks and if so then treat the first word as the
language otherwise treat it as a single line for format.

**Comment by geekgonecrazy** [comment] 2015-08-22 01:01
That seems to be how github is handling this.  If a single line it doesn't even try to check for a language.

**Comment by rodrigok** [comment] 2015-08-22 01:13
Very good solution :D

**Closed** 2015-08-22 01:42 UTC
Labels: Enhancement

**Comment by sanbor** [comment] 2015-08-25 15:56
I'd also add the case that if is not a valid language name, don't use it as language name.

Sometimes what I do is to type three backticks and paste a chunk of code, so maybe the first line is touching the three backticks. Github plays nice in this situation.
