### ISSUE TITLE
[Feature] Message Forwarding 

### ISSUE THREAD

**Issue by MrPoint1400** [RocketChat/Rocket.Chat#27688] opened 2023-01-04 14:06 UTC
The user must be able to forward the message to another user or groups or channels. Now the user can use "Get Link" and send a link to another user or a channel or a group manually.

![Clipboard - January 4, 2023 5_30 PM](https://user-images.githubusercontent.com/81944770/210571648-c0b51b80-8952-4cde-bb83-1d235a00facf.png)

![image](https://user-images.githubusercontent.com/81944770/210572957-0794aa43-6fb4-47b2-afdb-bb7bbc594261.png)

**Comment by ratika-12** [comment] 2023-01-05 16:44
Hey @MrPoint1400 I am new here and want to work on this. 
please assign me:-)

**Comment by tassoevan** [comment] 2023-01-06 13:31
Duplicate of #396.

**Closed by tassoevan** 2023-01-06 13:31 UTC
