### ISSUE TITLE
Infinite Scroll without DOM manipulation slows rocket chat down exponentially

### ISSUE THREAD

**Issue by rquast** [RocketChat/Rocket.Chat#5111] opened 2016-12-05 11:35 UTC
Your Rocket.Chat version: (make sure you are running the latest)

0.42

First of all, thanks for Rocket Chat. It's a fantastic project! Well done!

I've been using the Electron client (Mac 10.12) for a few days and have found that as the chat messages grow in the infinite scroller, the whole thing becomes very sluggish.

I took a look at the dom and notice that all chat lines are still in the dom and not manipulated (removed or added dynamically while scrolling, like with what infinity.js and other scrollers do).

Without either setting a sliding window for infinite scroll (load up to say, 100 at a time), similar to what gitter.im, slack, etc do, or doing what infinity.js does by using a custom scroller and loading dom nodes in and out of view on scroll, then it becomes unusable without restarting it.

Possible solutions: Either implement a window load (go to top, go to bottom) like what slack/gitter do, or implement a solution like infinity.js... some other kind of infinite scroll virtualization (like Aurelia's ui-virtualization, React Virtualized or many others) .

https://clusterize.js.org/ (vanilla js)

http://sergimansilla.com/blog/virtual-scrolling (vanilla js)

http://airbnb.io/infinity/?utm_source=tuicool (jquery)

https://bvaughn.github.io/react-virtualized/#/components/List (react)

https://github.com/aurelia/ui-virtualization (aurelia)

**Comment by rquast** [comment] 2016-12-05 11:37
To easily replicate, find a channel that has a lot of chat, the scroll up until the scroller slows everything down.

**Comment by birchcode** [comment] 2016-12-05 12:46
Yeah this is a bit of a killer app killer 😞  Makes one not want to ever look at past messages. This is rocket.chat, not snapchat.

**Comment by MartinSchoeler** [comment] 2016-12-05 14:39
Kind of a duplicate of #31 but i will keep this issue open since it has some nice ideas on it.

**Comment by rquast** [comment] 2016-12-05 23:29
@MartinSchoeler oops, sorry about the dupe.

I think the sliding window is the easiest option (as at the time of writing this). IMO, the virtualization libraries seem to have a lot of different issues owing to the complexity of emulating a scroller properly (item height calculations, aria, etc).

**Comment by graywolf336** [comment] 2016-12-07 18:50
What do you mean by "the sliding window"? @rquast

**Comment by lucasvanhalst** [comment] 2016-12-07 20:44
@graywolf336 he means that when you scroll up and there are say more than for example 100 messages in the DOM, the previous messages get removed to make the scrolling smoother. And just like how it is when you go to a specific message using the search function, it should show 'go to newest messages' at the bottom

**Comment by rquast** [comment] 2016-12-07 21:15
@graywolf336 what @lucasvanhalst said. The best way to have a look at what I'm talking about is to jump on gitter.im or slack and start scrolling up in a channel. You'll start to notice the size of the list from the bar on the right hits a maximum (stays the same length). When you reach the maximum window size on gitter, it says things like "77 unread messages" or "go to bottom" ... you keep clicking the bottom but as you do it, watch the size of the scroll bar on the right. Slack does it differently, but similar concept.

**Comment by engelgabriel** [comment] 2016-12-14 14:49
this  is related to https://github.com/RocketChat/Rocket.Chat/issues/31

**Closed** 2023-03-30 15:04 UTC
Labels: subj: performance
