### ISSUE TITLE
Internal Hubot documentation missing

### ISSUE THREAD

**Issue by TomaszDom** [RocketChat/Rocket.Chat#8025] opened 2017-09-03 12:24 UTC
I would like to start using the Internal Hubot, but there is no documentation for it, are there any plans for documenting this?

**Comment by madguy02** [comment] 2017-09-04 20:28
@TomaszDom  can you please elaborate on the issue

**Comment by TomaszDom** [comment] 2017-09-04 20:38
This website is empty:

https://rocket.chat/docs/administrator-guides/internal-hubot

Moreover, there are no hints or help text in the rocketchat server Internal Hubot page.

**Comment by madguy02** [comment] 2017-09-04 20:43
@geekgonecrazy

**Comment by Steve-MP** [comment] 2017-11-02 13:31
Agreed with OP - it is not clear how to add new scripts to rocket.cat and this would be very useful.

**Comment by MohamedAmineB** [comment] 2017-11-28 20:59
+1

**Comment by timkinnane** [comment] 2018-03-20 02:31
Have put this on the Bots Roadmap update, but there's also a range of issues that would involve updates to the internal hubot, so I think the documentation will stay in the backlog until there's more clarity there, otherwise it's effort wasted.

**Comment by Wirone** [comment] 2018-04-04 07:03
Personally I think the lack of this documentation is a problem for all people who want to use Internal Hubot. Of course everything can be done without it (we are currently working on our scripts) but it would be just helpful to get basic information there, especially for non-developers. I don't think that basics of Internal Hubot will change (how it can be enabled, from where and which scripts should be loaded), so documenting this would be a good thing.

If something will change (for example #10216), documentation should be updated.

Minimal documentation is always better than none ;-)

**Comment by timkinnane** [comment] 2018-04-04 07:51
Thanks @Wirone - I totally agree but we are currently in the process of launching a new adapter for *external* hubot installations and working on that documentation. There' actually a lot of changes on the way for bots and we don't want to waste time updating docs that will be out of date within weeks. We'll put up some of those changes as discussions very soon, with docs to come from that discussion.

**Comment by JSzaszvari** [comment] 2018-04-04 07:57
@rocket-cat close

Closing as per @timkinnane comments. Stay tuned people. Great things on the way for bots.

**Comment by timkinnane** [comment] 2018-04-16 03:34
As @JSzaszvari hinted, we have plans to replace the way most people use the internal Hubot with the Rocket.Chat apps model. See linked discussion #10458.

This won't be immediate, but we'd like to take any further discussion on requirements of "internal" bots over there. The other immediately viable option is to run an _external_ Hubot instance. We've just updated our adapter for Hubot v3 and the following repo provides an example of a functioning boilerplate example.

In many cases the repurposing of the system bot entity for custom logic is both confusing for users and inconsistently implemented in code. We strongly recommend pursuing one of the above options and have no plans to improve or encourage support for the internal Hubot at this stage. It's best to follow the docs in the boilerplate, the adapter and Hubot's own documentation from now on.

https://github.com/RocketChat/hubot-rocketchat-boilerplate

**Closed by timkinnane** 2018-04-16 03:34 UTC
Labels: feat: hubot, subj: Bots, type: documentation, type: improvement

**Comment by Wirone** [comment] 2018-04-16 06:04
Too bad it wasn't clear before we chose Internal Hubot as implementation for our scripts, with custom alias (we have customized Rocket instance) and wrote our deploy playbooks and docs. It will require changes in several places (Rocket repo, docs, installers) and new actions (deploying and configuring custom Hubot) from us, simply because you thought it's not important to write 2-3 sentences in your docs.

**Comment by timkinnane** [comment] 2018-04-16 06:17
@Wirone - your scripts should work with an external Hubot just as well, if not better.

The issue is not as simple as writing the docs. Implementation with the internal Hubot has always been fraught and I think the documentation was not forthcoming because there was never really a clear recommendation for a good solution. Now we are working on that solution and have provided lots of documentation on the Hubot boilerplate and adapter projects, linked above.

**Comment by Wirone** [comment] 2018-04-16 13:44
@timkinnane but we currently use `RocketChat` or `Meteor` methods in our scripts (because of #10267 we had to implement custom method for determining private channel between bot and user). Will it work with external Hubot?

**Comment by timkinnane** [comment] 2018-04-17 10:33
Yes, the Hubot adapter can [call methods](https://github.com/RocketChat/hubot-rocketchat/blob/develop/index.js#L192-L194) <-- See develop branch, for Hubot v3 compatibility, it's even async! The [Hubot v2 adapter](https://github.com/RocketChat/hubot-rocketchat/blob/master/src/rocketchat.coffee#L251-L252) also had that method but it wasn't async.

**Comment by Wirone** [comment] 2018-04-17 11:34
@timkinnane I did not mean "methods" registered with Meteor API, but calls like `Meteor.users.findOne()` or `RocketChat.getRoomByNameOrIdWithOptionToJoin()`. But ok, I'll look at it, probably we will have to adapt our bot (or maintain custom RocketChat even more customized that it's now).

**Comment by timkinnane** [comment] 2018-04-17 11:55
There is a `bot-helpers` package that exposes user query methods specifically for bots, also adding admin settings to control the fields the bots have access too. It's in core now, but my original external repo has the [docs for calling those methods](https://github.com/timkinnane/rocketchat-bot-helpers). Those will be refactored as more obvious and documented features of the new SDK and Hubot adapter soon.

We're getting off topic now though for this issue. Please see the discussion about [the future of internal bot solutions here](https://github.com/RocketChat/Rocket.Chat/issues/10458) or open a new issue on the [Hubot adapter](https://github.com/RocketChat/hubot-rocketchat) if you find it can't do something you need.
