### ISSUE TITLE
Can't edit usernames anymore

### ISSUE THREAD

**Issue by wargamesqcf** [RocketChat/Rocket.Chat#4146] opened 2016-08-30 10:53 UTC
Your Rocket.Chat version: 0.37.1

I upgraded from .35 to .37.1 recently and encountered a weird error, I can't seem to edit usernames for people.

http://i.imgur.com/qW4W4s4.png?1

**Comment by Valiantiam** [comment] 2016-08-30 14:59
Also have this issue as well.

@wargamesqcf are you having similar issues with permissions by chance? Such as people not showing up in channel roles that you know they are?

**Comment by wargamesqcf** [comment] 2016-08-30 16:33
I don't think, or atleast not yet? we just upgraded 2 days ago, and just ran into this problem.

**Comment by Saelvarath** [comment] 2016-08-31 05:55
@Valiantiam I'm working with @wargamesqcf on the same chat and we do have an issue with people not showing up on the list of users in a permissions group if the group is over a certain size. On the Users page when you scroll to the bottom it will load more but here it just stops.

![untitled](https://cloud.githubusercontent.com/assets/11372109/18117547/864a975a-6f1d-11e6-9272-2aaa989ebd00.png)

**Comment by Venomen** [comment] 2016-08-31 12:57
Same situation in 0.38.0 (its related to #4081 ):

I20160831-14:54:06.211(2) Exception while invoking method 'insertOrUpdateUser' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username at Object.Future.wait (/home/rocket/Rocket.Chat/programs/server/node_modules/fibers/future.js:398:15) at [object Object].<anonymous> (packages/meteor/helpers.js:119:1) at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1) at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1) at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1) at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1) at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1) at _Class.update (server/models/_Base.js:78:29) at _Class.RocketChat.models.Messages._Class.updateUsernameAndMessageOfMentionByIdAndOldUsername (packages/rocketchat_lib/server/models/Messages.coffee:226:11) at packages/rocketchat_lib/server/functions/setUsername.coffee:40:31 - - - - - at Object.toError (/home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11) at /home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27 at /home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7 at /home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9 at Server.Base._callHandler (/home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41) at /home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18 at [object Object].MongoReply.parseBody (/home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5) at [object Object].<anonymous> (/home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20) at [object Object].emit (events.js:95:17) at [object Object].<anonymous> (/home/rocket/Rocket.Chat/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)

**Comment by wargamesqcf** [comment] 2016-08-31 13:07
Ours is.

I20160831-05:42:03.601(0) Exception while invoking method 'saveUserProfile' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)     at _Class.update (server/models/_Base.js:78:29)     at _Class.RocketChat.models.Messages._Class.updateUsernameAndMessageOfMentionByIdAndOldUsername (packages/rocketchat_lib/server/models/Messages.coffee:226:11)     at packages/rocketchat_lib/server/functions/setUsername.coffee:40:31     - - - - -     at Object.toError (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9     at Server.Base._callHandler (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18     at [object Object].MongoReply.parseBody (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)     at [object Object].emit (events.js:95:17)     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)

**Comment by wargamesqcf** [comment] 2016-08-31 14:20
this is what i have after going to v38

I20160831-14:20:09.451(0) Exception while invoking method 'insertOrUpdateUser' MongoError: The positional operator did not find the match needed from the query. Unexpanded update: mentions.$.username     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)     at _Class.update (server/models/_Base.js:78:29)     at _Class.RocketChat.models.Messages._Class.updateUsernameAndMessageOfMentionByIdAndOldUsername (packages/rocketchat_lib/server/models/Messages.coffee:226:11)     at packages/rocketchat_lib/server/functions/setUsername.coffee:40:31     - - - - -     at Object.toError (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/collection/core.js:577:27     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1197:7     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9     at Server.Base._callHandler (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18     at [object Object].MongoReply.parseBody (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)     at [object Object].emit (events.js:95:17)     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)

**Comment by graywolf336** [comment] 2016-08-31 17:51
Duplicate of #3940

**Closed by graywolf336** 2016-08-31 17:51 UTC
Labels: feat: user settings, type: bug
