### ISSUE TITLE
When using new "mark as unread" feature, view is changed to page-home after marking

### ISSUE THREAD

**Issue by xenithorb** [RocketChat/Rocket.Chat#3903] opened 2016-08-03 09:19 UTC
Your Rocket.Chat version: 0.36.0

Steps to reproduce: 
1. Mark any message as unread through the "Gear" -> "Flag" icon menu
2. Observe that the right-hand view changes from the channel/direct message you're in, to the home view (as if you just logged in) 
   - Changes from: `<div class="room-container">`
   - To:  `<section class="page-container page-home page-static">`

Notes: 
1. I have not tested on a fresh server
2. Consequently this is on an upgraded server with already-existing messages, of which I'm sure is the majority of use cases. 

---

Edit: As it turns out, @graywolf336 has correctly pointed out that this was an original intention of #3632 due to the way automatic read marking works. I think the bug should stand because I don't believe anyone is actually going to expect it to take them to a different page when they click the flag icon.

**Comment by graywolf336** [comment] 2016-08-03 15:22
This is a feature and not a bug. Please see @marceloschmidt's comments on the pull request which implemented the mark as unread: https://github.com/RocketChat/Rocket.Chat/pull/3632#issuecomment-231164051

**Comment by xenithorb** [comment] 2016-08-03 16:54
I see. It appears it was merged in with this hack due to automatic marking of the message as read after marking it unread. 

One would think this is still a hack (sending the user /home) and should thus be fixed by temporarily turning off said "automatic marking" until another event or action is taken upon the room/channel 

I consider this an unfinished aspect to the feature (obviously who wants the thing sending them to the home screen) so I think the bug should stand as-is.

**Comment by xenithorb** [comment] 2017-05-11 14:57
@MartinSchoeler Do you think this can get re-categorized as a bug? It's still a jarring experience and looks like a bug to the user because it produces an undesirable effect.

**Comment by danieljhochman** [comment] 2017-08-27 13:24
+1 - We have had user feedback that this makes no sense. Also, when running RC in a narrow window, going back to the homepage is actually broken and the whole window turns white.

Why not use the same behavior as Slack? You mark as unread and all that changes in the Unread count (or bolding) next to the DM/Room Name. You stay in the same room/DM.

**Comment by xenithorb** [comment] 2017-10-21 17:43
This issue is still present in `0.59.1`, although now after the UI change it's "Click three dots (menu) option" -> "Mark as unread", still unintuitively brings you back to the home page.

**Comment by TwizzyDizzy** [comment] 2018-03-03 16:45
@rocket-cat close

IIRC, this has been fixed in some of the last releases. If you can still reproduce this on current stable (0.62.1) please let me know and I'll reopen.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-03-03 16:45 UTC
Labels: sponsored, subj: ui/ux, type: bug
