### ISSUE TITLE
Uncaught Exception: Error: Cannot find module '@bugsnag/js'

### ISSUE THREAD

**Issue by Fraer** [RocketChat/Rocket.Chat#15150] opened 2019-08-09 09:19 UTC
On mac after last update

```
Uncaught Exception:
Error: Cannot find module '@bugsnag/js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/Applications/Rocket.Chat.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Applications/Rocket.Chat.app/Contents/Resources/app.asar/app/main.js:10:31
    at Object.<anonymous> (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/app/main.js:1579:3)
    at Object.<anonymous> (/Applications/Rocket.Chat.app/Contents/Resources/app.asar/app/main.js:1582:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
```

**Comment by reetp** [comment] 2019-08-09 09:27
@rocket-cat label add duplicate

Duplicate of RocketChat/Rocket.Chat.Electron#1288

**Comment by reetp** [comment] 2019-08-09 09:27
@rocket-cat close

**Closed by reetp** 2019-08-09 09:27 UTC
Labels: duplicate
