### ISSUE TITLE
Node.js update

### ISSUE THREAD

**Issue by asarubbo** [RocketChat/Rocket.Chat#16555] opened 2020-02-11 12:05 UTC
### Description:

Node.js update

### Steps to reproduce:

The latest release(2.4.9) uses node.js 8.17.0. The support for this version ended on Jan 2020 (see https://nodejs.org/en/about/releases/ )

Can you use a more recent and up-to-date node.js version?

**Comment by TwizzyDizzy** [comment] 2020-02-11 12:24
@rocket-cat label add duplicate

**Comment by TwizzyDizzy** [comment] 2020-02-11 12:25
@rocket-cat close

Duplicate of #16024, Upgrade to nodejs 12 is already incorporated into the RCs of Rocket.Chat 3.0.

Cheers
Thomas

**Closed by TwizzyDizzy** 2020-02-11 12:25 UTC
Labels: duplicate
