### ISSUE TITLE
GUI very slow since 3.11 upgrade

### ISSUE THREAD

**Issue by bb2k** [RocketChat/Rocket.Chat#20659] opened 2021-02-09 15:13 UTC
### Additional context

Just upgraded server from 3.7 to 3.11

### Relevant logs:
I've no error logs 

### Description:
Since i updated Our Rocket.Chat server, the Gui is very slow and even slower in admin menu.
I've tried in Rocket.Chat snap app and in firefox 85.

### Steps to reproduce:
just open the client and it's slow

### Expected behavior:
to run smoothless as it was in 3.4

### Actual behavior:
this is slow

### Server Setup Information:

- Version of Rocket.Chat Server: 3.11.0
- Operating System: Debian  9
- Deployment Method: tar (install from source solution)
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v12.20.1
- MongoDB Version: 4.0.18 / mmapv1 (oplog Activated)

### Client Setup Information

- Desktop App or Browser Version:  Snap 3.0.1 / Firefox 85
- Operating System:  Ubuntu 20.04
- 
### Additional context
The CPUs (4 cores) and Ram (4Gb) are ok. 
Installed on a 25Gb SSD disk under vmware esxi 6.7

### Relevant logs:
No error shown in logs

**Comment by Vkat14** [comment] 2021-02-09 18:02
It actually goes back to 3.9.7. I was hoping this would be improved in 3.11. 

Posted about my experience here with the lags:https://github.com/RocketChat/Rocket.Chat/issues/20543#issuecomment-773758359

**Comment by ankar84** [comment] 2021-02-10 02:04
[this](https://open.rocket.chat/channel/support?msg=Tsr4HuiqJEhzTkXrC) could be an answer for that issue

**Comment by Vkat14** [comment] 2021-02-10 03:15
> 
> 
> [this](https://open.rocket.chat/channel/support?msg=Tsr4HuiqJEhzTkXrC) could be an answer for that issue

You always come through @ankar84 . Thanks
Never checked the Community channel.

**Comment by mr-karan** [comment] 2021-02-10 04:54
Possible dupe of https://github.com/RocketChat/Rocket.Chat/issues/20553

**Comment by bb2k** [comment] 2021-02-10 07:13
> Possible dupe of #20553

yep,even if the symptoms are not the same, this could be the same origin

**Comment by ankar84** [comment] 2021-02-10 07:38
@ggazzo could it be related to blaze template in codebase?

**Comment by ggazzo** [comment] 2021-02-11 03:54
about the room rendering, as soon as we finish the rewrite to react, we should notice a huge improvement... it will not be on the 3.12 (we are focusing in some old issues) but for sure on the 3.13

about the admin.... I have no good explanation, we didn’t change anything from 3.7 from 3.1x I need to check

**Comment by jsanchezba** [comment] 2021-02-15 07:16
I noticed this too. Seems very laggy to switch between rooms and conversations.
Hope with that refactor fixes that

**Comment by bseclier** [comment] 2021-02-18 10:34
Hello,
Same here, from 3.8.1 to 3.11.1 and the GUI is sooo laggy, specially while switching between rooms and conversations !

**Comment by pehlert** [comment] 2021-02-18 10:49
I can only confirm, we really regret the upgrade but can't find a way back. In my opinion this needs to be a top priority especially because it was perfectly fine pre-3.11

**Comment by mr-karan** [comment] 2021-02-18 10:52
Based on an observation:

- Switching between individual chats and groups is decently fast.
- Switching between individual chats and another individual chat OR a group and another group is **extemely slow**.

> In my opinion this needs to be a top priority

:100:

**Comment by binboum** [comment] 2021-02-18 20:37
> Based on an observation:
> 
> * Switching between individual chats and groups is **extremely slow**. It takes 4s at the bare minimum and sometimes even 10s+ for me.
> * Switching between individual chats and another individual chat OR a group and another group is decently fast.
> 
> > In my opinion this needs to be a top priority

I confirm after a switch from 3.8.1 to 3.8.11 on large servers, it is very slow, a rollback was mandatory.

**Comment by RC685** [comment] 2021-02-19 21:33
I'd also request that this be given priority. It's a pretty big issue, especially since downgrades aren't that easy.

**Comment by ankar84** [comment] 2021-02-20 04:20
> I'd also request that this be given priority. It's a pretty big issue, especially since downgrades aren't that easy.

More to say - **downgrades are impossible** if new version have a migration which for major version almost always true.
Only restore from old version backup - **but always lose messages** in that case.

**Comment by mikemkm** [comment] 2021-02-22 13:58
Same on our server. Severe slowdown while switching rooms after last update (3.11). 
Kindly please release a fix.

**Comment by bernhardberger** [comment] 2021-02-23 15:49
Yeah, it's unbearable. Channel switch basically freezes the whole UI and I have to wait several seconds after typing to see the outcome of my fingers hitting the keyboard..

**Comment by no-trick-pony** [comment] 2021-02-23 18:21
We upgraded recently to 3.11 to escape the reaction bug #20151 and found ourselves having to wait for up to 12 seconds to switch conversations (meanwhile the whole interfaces completely freezes). Would be great if this issue could be fixed earlier than later since it's simply not workable if you have to switch conversations often.

**Comment by Vkat14** [comment] 2021-02-23 21:31
> 
> 
> about the room rendering, as soon as we finish the rewrite to react, we should notice a huge improvement... it will not be on the 3.12 (we are focusing in some old issues) but for sure on the 3.13
> 
> about the admin.... I have no good explanation, we didn’t change anything from 3.7 from 3.1x I need to check

Since my last interaction here, SNAP moved to 3.10.5. Can the team hold off from pushing 3.11 to SNAP? It would be best to jump from 3.10 to 3.12/3.13

Thanks

**Comment by BigMayo** [comment] 2021-02-23 21:53
Definitely having same issues. This is causing a total revolt within the company and will easily effect any decision to purchase the Enterprise licenses

**Comment by ggazzo** [comment] 2021-02-24 03:25
Please anybody can check if is everything ok on https://open.rocket.chat ?  This should be fixed here https://github.com/RocketChat/Rocket.Chat/pull/20860 and released at 3.12.0. 


And good news: we still have space to improvements, we are moving to react from blaze, the messages are currently written in blaze and react 50/50b and make both work together cost us some performance, so as soon as we finish the rewrite you will see/feel/notice huge improvements I promise. But for now I just can offer you the same performance you are used before 3.11.x anything else please, let me know

**Comment by bb2k** [comment] 2021-02-24 13:01
I confirm, that it seems better

**Comment by adocampo** [comment] 2021-02-24 13:20
Yes, is blazing fast compared to our self-hosted versions... please release 3.12 ASAP!!!

**Comment by ggazzo** [comment] 2021-02-24 13:27
the release 3.12.0 is scheduled for february 27.

**Comment by ggazzo** [comment] 2021-02-24 13:34
closed by https://github.com/RocketChat/Rocket.Chat/pull/20860

**Closed by ggazzo** 2021-02-24 13:34 UTC

**Comment by bb2k** [comment] 2021-02-24 13:35
Thx for your  reactivity !

**Comment by mr-karan** [comment] 2021-02-28 03:15
@ggazzo Is the 3.12 release gonna be delayed? Was eagerly waiting to upgrade :)

**Comment by RC685** [comment] 2021-02-28 10:00
> @ggazzo Is the 3.12 release gonna be delayed? Was eagerly waiting to upgrade :)

Same, was going to upgrade this weekend if it out.

**Comment by mr-karan** [comment] 2021-03-01 08:07
Upgraded to 3.12 and chat switching is pretty fast. :heart: this!

**Comment by pehlert** [comment] 2021-03-01 08:09
Thank you so much @ggazzo and the rest of the RocketChat team. The 3.12 release is a silver lining for RocketChat support within the company. ;-) We'll be more conservative with upgrades next time.

**Comment by mlongmiresqa** [comment] 2021-03-01 15:29
Just upgraded and the channel switching slowness appears to be gone. Thanks for the fix.

**Comment by Vkat14** [comment] 2021-03-03 23:16
@ggazzo 

Can Rocket Chat team skip 3.11 for SNAP Installers and go straight to 3.12 ?

**Comment by HoldOffHunger** [comment] 2022-03-15 14:33
Is there any chance this will be addressed?
