### ISSUE TITLE
UI Icons Missing (Chromium Browsers)

### ISSUE THREAD

**Issue by beanpole135** [RocketChat/Rocket.Chat#9431] opened 2018-01-17 12:39 UTC
All the icons on the sidebar buttons, channels, emoticon button, and chat buttons are missing in Chromium-based browsers (Chrome, Chromium, Blink, QtWebengine). Those icons do show up properly in Firefox.

Our hosted server just got updated last night (new colored icons for the channels on the left), so I am not sure exactly which version of Rocket.chat is running, but it should be fairly recent.

![image](https://user-images.githubusercontent.com/4172864/35043051-1aa1d422-fb59-11e7-960e-4c099213c84f.png)

**Comment by propertunist** [comment] 2018-02-07 18:09
i'm seeing the same thing here in chromium on windows 10 64bit. i've looked through the inspector to try to identify the cause of the issue and i'm not seeing any files failing to load or dodgy CSS.

**Comment by beanpole135** [comment] 2018-02-07 18:16
Note: Upgrading the chromium backend to a newer version (Chrome/56.0.2924.122 right now) fixes this issue. Might be something very specific to old chromium versions.

**Comment by propertunist** [comment] 2018-02-07 20:09
ah yes. i updated and the issue is resolved - thanks

**Comment by TwizzyDizzy** [comment] 2018-03-31 20:46
@rocket-cat close

Closing this then...

Cheers
Twizzy

**Closed by TwizzyDizzy** 2018-03-31 20:46 UTC
