### ISSUE TITLE
iFrame click events not firing

### ISSUE THREAD

**Issue by spfautz** [RocketChat/Rocket.Chat#7579] opened 2017-07-26 13:42 UTC
### Description:

Click events are not triggered from Rocket.Chat when iFrame integration is enabled. 

* click-user-card-message
* click-mention-link
* click-message-link
* click-action-link

The other events (notification, room-opened, new-message, etc.) work as expected.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.57.2
* Operating System: Linux (x64)
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1

### Steps to Reproduce:

1. Embed Rocket.Chat in to iFrame
2. Add event listener:
window.addEventListener('message', function(e) {
    console.log(e.data.eventName); // event name
    console.log(e.data.data); // event data
});
3. Send a message with a link (http://www.google.com) and click on it, or click on a username or mention link.

### Expected behavior:

The event listener is fired with a "click-message-link" eventName (or action/mention/user-card) and associated event data.

### Actual behavior:

The event listener is not triggered.

### Other:

Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by mikewakid** [comment] 2017-08-25 12:30
I am having the same issue with the click events not triggering, the others are working as expected.

**Comment by kieran-rocks** [comment] 2017-08-25 13:53
+1

**Comment by kieran-rocks** [comment] 2017-10-05 15:37
Looks like the problem is in Rocket.Chat/packages/rocketchat-ui-master/client/main.js:
@karlprieb 

`if (link.origin === s.rtrim(Meteor.absoluteUrl(), '/') && /msg=([a-zA-Z0-9]+)/.test(link.search))`

Both `link.origin` and `link.search` are undefined, so this check is false and does not even get to the following check:

`if (RocketChat.Layout.isEmbedded()) {`

which is also returning false. All three of these checks should be true, which would result in:

`return fireGlobalEvent('click-message-link',`

but as it stands it never gets there to send the message, and instead the message is propagated and the browser just does its thing (opens link in new tab). Perhaps `link.baseURI` should be used for that check in place of `link.origin`, if it is necessary at all. I'm not sure what the purpose of testing `link.search` is.

**Comment by Fred-grais** [comment] 2019-01-13 20:48
still an issue on the latest version

**Comment by gabriellsh** [comment] 2023-09-19 14:42
Fixed in https://github.com/RocketChat/Rocket.Chat/pull/16771

**Closed by gabriellsh** 2023-09-19 14:42 UTC
Labels: type: bug, subj: ui/ux
