### ISSUE TITLE
Livechat setDepartment does not appear to work

### ISSUE THREAD

**Issue by vincebuilderwire** [RocketChat/Rocket.Chat#9421] opened 2018-01-16 19:34 UTC
### Description:

 I've tried and cant get it working. i've seen a few others ask about it but have not seen the solution: 
```
RocketChat(function() {
this.setDepartment('Department Name OR _id');
});
```
In speaking with Aaron Ogle in the #Support room, he suggested i open an issue.  I have attempted both Name and ID and neither one set the department as expected.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.60.3
* Operating System:  CentOS7
* Deployment Method(snap/docker/tar/etc): Tar
* Number of Running Instances:  1
* DB Replicaset Oplog:
* Node Version:  v8.9.3

### Steps to Reproduce:

1.  I setup the server end and verified it works using the basic installation javascript in an empty webpage.  
2.  I logged in as admin and setup 2 departments (neither shown on registration page)
3.  I set one agent per department
4.  i set the setting in livechat to allow user to switch departments  (tested this with and without this set)
5.  i specified a department name (or id) in the script and logged in as an agent from a different department so that no one was logged in from the selected department.
6.  the chat shows online and messages are sent directly to the logged in agent for the incorrect department.

below is the exact script i am using.  Note that i have tried this as is and with the two RocketChat(function()) scripts combined:

```
<!-- Start of Rocket.Chat Livechat Script -->

<script type="text/javascript">

(function(w, d, s, u) {
	w.RocketChat = function(c) { w.RocketChat._.push(c) }; 
w.RocketChat._ = []; 
w.RocketChat.url = u;
	
var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
	
j.async = true; j.src = 'http://livechat.local:3000/packages/rocketchat_livechat/assets/rocketchat-livechat.min.js?_=201702160944';
	h.parentNode.insertBefore(j, h);
})
(window, document, 'script', 'http://livechat.local:3000/livechat');

RocketChat(function() {
    
this.setTheme({
        color: '#04436A', // widget title background color
        fontColor: '#FFFFFF' // widget title font color
    });


});

RocketChat(function() {
    
this.setDepartment('t3A3NXfnGN8j2k947');

});


</script>

<!-- End of Rocket.Chat Livechat Script -->
```

### Expected behavior:

I expected that when i used this.setDepartment('Name') or this.setDepartment('id') in the javascript code of the website that the chat window would see that department and if that department had no online agents, the chat would show offline.  if a user was online for that department and a message was sent it would go to the specified department and not to any department that was online using the round robin method.

### Actual behavior:

It seems as if the this.setDepartment('') setting isnt actually doing anything.  I have searched the internet as well as seeking out support from the community to verify this was a bug and not a setup issue on my part.

**Comment by alf-FS** [comment] 2018-10-16 11:53
@1dot44mb for the record - and temporary workaround - with several departments configured and agents assigned to each one the LiveChat user can select which department they want to be connected to when they first start the chat. Not ideal but with some additional information on the website at least you could ensure that users know which department they should be joining (perhaps you can use url-based triggers to give some hints rather than changing the website). Department can be switched in the chat via the options button.

Definitely will be good to have a fix though as the widget customisation is a really useful feature generally

**Comment by rohanlad** [comment] 2018-10-18 14:37
@1dot44mb For me, setDepartment does not work at all and the live chat does not get initiated with a default department - the user has to select a department themselves like normal.

**Comment by 1dot44mb** [comment] 2018-10-19 16:56
I think the reason of the problem is that RocketChat assigns a token to a visitor. After assigning token, i think a department id is assigned to that token. So even if the department changes in another section of our web app, the initally bound department id is not updated. 

I have temporarily solved the problem by setting guest token with department id. This way i update the visitor token for each section by using department id. After this, if the user navigates to other departments URL, a new chat session is initiated with the correct department.

Here is how i solved it:

        RocketChat(function () {
            this.clearDepartment();
            this.setDepartment('@ViewBag.departmentId');
            this.setGuestName('@ViewBag.userFullName');
            this.setGuestToken('@(ViewBag.departmentId)-@(ViewBag.userId)');
        });


I wanted to create a PR to solve the bug however i spent 4 hours trying to run Rocket.Chat in my local development environment without success. There are countless errors with `meteor npm start`. It just can't install all packages and run the project. I solve one issue and later it can't start mongodb, etc. I gave up trying. I followed the default documentation with a clean ubuntu dev environment but it didn't work. 

Anyways i think the problem can be solved in this line:
https://github.com/RocketChat/Rocket.Chat/blob/b7b73a911f3fdaed38fb3d280ab2c6d132350d04/packages/rocketchat-livechat/.app/client/views/livechatWindow.js#L140-L142
You see, it automatically sets the department id from the visitor object (which is built depending on token). But this line should also look if the `setDepartment` is called or not. 

I think it should work if you change the if condition like the following;
```
      //If setDepartment is not called and visitor is assigned to a department before
      if (!Livechat.department && result.visitor.department) { 
            Livechat.department = result.visitor.department;
      }
```

**Comment by renatobecker** [comment] 2018-10-19 17:49
The issue related to `setDepartment` method, on Livechat iFrame API (https://rocket.chat/docs/developer-guides/livechat-api/#assign-chats-to-a-specific-department ) has been fixed.
Please, take a look at here: https://github.com/RocketChat/Rocket.Chat/pull/12161.

Thanks.

**Closed by renatobecker** 2018-10-19 17:49 UTC
Labels: feat: livechat, type: bug

**Comment by vincebuilderwire** [comment] 2018-11-01 20:47
@1dot44mb I did a preliminary test with the newest build today.  Some things I've noticed:  It appears so far that set department is working.  When I signed in as two different agents for two different departments, the correct agent received the message. if one department has an agent logged in but not the desired department, the user receives a message saying "no more agents available" so that is working as expected.  I did notice that the "chat" is online regardless of what departments have agents online: ex. Test1 department has no agent online, Test2 department does have an agent online.  chat is hard coded for Test1 department.  chat still shows online.  Its not a major issue though because one a message is sent, it notifies the chat user that there are no agents online.  so while its not "pretty" to the user, it does its job and thus solves my problem.
