### ISSUE TITLE
0.58.3 several issues - autologout, fake notifications, login problems

### ISSUE THREAD

**Issue by adamdziedzic** [RocketChat/Rocket.Chat#8380] opened 2017-10-03 09:37 UTC
### Explanation
Hi, I am sorry for this multiple-bug issue, but it just started to happen in new version and I didn't want to report several issues, which can have similar reason. 

### Description:

First of all, I have problem with login. Sometimes it takes 3-4 attempts to login correctly. Error looks like I would type wrong login or password, but I don't. I just click "Login" more times and succeed after a while.

Second issue is constant logout - I am using Rocket for ~8-10 hours/day and I am logged out about 3-4 times. Locking the screen logs me out, connecting with VPN logs me out, switching between networks logs me out. And sometimes Rocket logs me out without this things, just like that.

Third issue is fake notifications. I get a lot of notifications about new message, and when I open the channel, there is nothing there and channel name gets "unbold". 

Fourth issue, similar to the third one is desktop notification issue. There is a lot of them. Duplicated, fake, always coming after login. I had to stop using desktop app because of them.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.3
* Operating System: macOS 10.12.6
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 2
* DB Replicaset Oplog: 128MB
* Node Version:

**Comment by neurolabs** [comment] 2017-10-03 20:47
I see similar things with the desktop/electron client v2.9.0.

Especially very frequent logouts and no auto-login. I need to enter my credentials 3-4 times a day.

**Comment by Endareth** [comment] 2017-10-04 02:12
Also experiencing the autologout issue on Rocket.Chat+ 2.9.0 client on macOS 10.12.6, server 0.58.3 on Debian 4.4.0-93-generic.

**Comment by RELD** [comment] 2017-10-04 21:50
Same here unfortunately.

**Comment by pcholt** [comment] 2017-10-05 05:57
Every time MacOS is locked, I'm logged out.

**Comment by KervyN** [comment] 2017-10-05 07:07
Hi,
we also have those issues. The Autologout appears when the network connection to the chatserver is lost.

**Comment by sebastianhegge** [comment] 2017-10-05 08:28
Same issue here.
Fake notifications (third issue) caused by messages which are not visible until chat client restart.

**Comment by axeloz** [comment] 2017-10-05 16:28
Same issue here with 0.58.3 and mac desktop 2.9.0.
thanks

**Comment by OtavioCapila** [comment] 2017-10-05 20:04
Same issue here with version 0.58.3 Windows 7 Pro x64

**Comment by OtavioCapila** [comment] 2017-10-05 20:12
@KervyN So, if i disable "profile picture sync", the autologout issue will stop?

**Comment by alexweissman** [comment] 2017-10-05 22:19
Logout issue is already explained in #8366.  Notifications issue might already be fixed in #8027.  Basically, I'm just looking forward to the 0.59 release 😁

**Comment by geekgonecrazy** [comment] 2018-12-01 10:08
from what I know all are solved but an occasional logout.  This one is tracked several other places.

Closing

**Closed by geekgonecrazy** 2018-12-01 10:08 UTC
Labels: type: bug
