### ISSUE TITLE
Component vibrates when clicked on vertical dots on Thread's lower most messages.

### ISSUE THREAD

**Issue by akash19coder** [RocketChat/Rocket.Chat#27904] opened 2023-01-31 12:10 UTC
### Description: 
When the vertical dots button is clicked in a thread, the component displayed vibrates if it doesn't get enough space. to show up

### Steps to reproduce:

1. Enter into any channel
3. Click on Threads
4. Open a Thread
5. Go to the lower most message and click the vertical dots.

### Expected behavior:

It is expected to display the component as follow
![ExpectedBehaviour](https://user-images.githubusercontent.com/72060440/215725865-2ec9c9c2-cabf-4214-a828-d8cc12c08649.JPG)

### Actual behavior:
When the component doesn't get enough space to show up it vibrates. 

 
[RocketchatIssue.webm](https://user-images.githubusercontent.com/72060440/215753334-34bb3011-4da3-4415-8d69-b73cb13579bb.webm)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

I inspected using Chrome. This happens when the dimension(width) exceeds 780. and the component doesn't get enough space on screen to show up.

**Comment by dudanogueira** [comment] 2023-01-31 12:48
Hi! Thanks for poiting it out.

This is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/26506

**Closed by dudanogueira** 2023-01-31 12:48 UTC
Labels: duplicate
