### ISSUE TITLE
Important! LDAP Parser error in Sync

### ISSUE THREAD

**Issue by knokio** [RocketChat/Rocket.Chat#23714] opened 2021-11-14 22:54 UTC
### Description:

LDAP sync is failing 100% of the times.
Test Connection works with success, and Test LDAP Search also works, so the connection to LDAP server is okay.

### Steps to reproduce:

1. Go to Admin > LDAP
2. Click "Sync now"
3. Sync does not work. Check logs and see the errors.

### Expected behavior:

LDAP sync to work and new users be created automatically.

### Actual behavior:

No sync happens, and errors show in the logs.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.1.2
- Operating System: Ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: 128
- NodeJS Version:  v12.22.1
- MongoDB Version: 4.2.17

### Additional context

It was working correctly in v3.x before the 4.x upgrade.

### Relevant logs:

```
rocketchat_1  | {"level":50,"time":"2021-11-14T22:48:46.642Z","pid":1,"hostname":"f92f5fe1f25e","name":"LDAP","section":"Connection","err":{"type":"VError","message":"Parser error for 19__ldap://ldap.ldapserver:389: Expected 0x2: got 0x72","stack":"VError: Parser error for 19__ldap://ldap.ldapserver:389: Expected 0x2: got 0x72\n    at Parser.onParseError (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:890:26)\n    at Parser.emit (events.js:314:20)\n    at Parser.EventEmitter.emit (domain.js:483:12)\n    at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:103:10)\n    at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:873:22)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)","jse_shortmsg":"Parser error for 19__ldap://ldap.ldapserver:389","jse_cause":{"type":"Error","message":"Expected 0x2: got 0x72","stack":"InvalidAsn1Error: Expected 0x2: got 0x72\n    at newInvalidAsn1Error (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/errors.js:7:13)\n    at Reader._readTag (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/reader.js:230:11)\n    at Reader.readInt (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/reader.js:146:15)\n    at Parser.getMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:116:25)\n    at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:96:20)\n    at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:873:22)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)","name":"InvalidAsn1Error"},"jse_info":{},"name":"VError"},"msg":"Parser error for 19__ldap://ldap.ldapserver:389: Expected 0x2: got 0x72"}
```

```
rocketchat_1  | {"level":50,"time":"2021-11-14T22:48:46.644Z","pid":1,"hostname":"f92f5fe1f25e","name":"LDAP","section":"Connection","err":{"type":"VError","message":"Parser error for 19__ldap://ldap.ldapserver:389: Expected 0x2: got 0x84","stack":"VError: Parser error for 19__ldap://ldap.ldapserver:389: Expected 0x2: got 0x84\n    at Parser.onParseError (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:890:26)\n    at Parser.emit (events.js:314:20)\n    at Parser.EventEmitter.emit (domain.js:483:12)\n    at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:103:10)\n    at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:873:22)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)","jse_shortmsg":"Parser error for 19__ldap://ldap.ldapserver:389","jse_cause":{"type":"Error","message":"Expected 0x2: got 0x84","stack":"InvalidAsn1Error: Expected 0x2: got 0x84\n    at newInvalidAsn1Error (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/errors.js:7:13)\n    at Reader._readTag (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/reader.js:230:11)\n    at Reader.readInt (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/reader.js:146:15)\n    at Parser.getMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:116:25)\n    at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:96:20)\n    at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:873:22)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)","name":"InvalidAsn1Error"},"jse_info":{},"name":"VError"},"msg":"Parser error for 19__ldap://ldap.ldapserver:389: Expected 0x2: got 0x84"}
```
```
rocketchat_1  | {"level":50,"time":"2021-11-14T22:48:46.650Z","pid":1,"hostname":"f92f5fe1f25e","name":"LDAP","section":"Connection","err":{"type":"VError","message":"Parser error for 19__ldap://ldap.ldapserver:389: Expected 0x2: got 0x32","stack":"VError: Parser error for 19__ldap://ldap.ldapserver:389: Expected 0x2: got 0x32\n    at Parser.onParseError (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:890:26)\n    at Parser.emit (events.js:314:20)\n    at Parser.EventEmitter.emit (domain.js:483:12)\n    at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:103:10)\n    at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:873:22)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)","jse_shortmsg":"Parser error for 19__ldap://ldap.ldapserver:389","jse_cause":{"type":"Error","message":"Expected 0x2: got 0x32","stack":"InvalidAsn1Error: Expected 0x2: got 0x32\n    at newInvalidAsn1Error (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/errors.js:7:13)\n    at Reader._readTag (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/reader.js:230:11)\n    at Reader.readInt (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/reader.js:146:15)\n    at Parser.getMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:116:25)\n    at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:96:20)\n    at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:873:22)\n    at Socket.emit (events.js:314:20)\n    at Socket.EventEmitter.emit (domain.js:483:12)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)\n    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)","name":"InvalidAsn1Error"},"jse_info":{},"name":"VError"},"msg":"Parser error for 19__ldap://ldap.ldapserver:389: Expected 0x2: got 0x32"}
```

**Comment by ankar84** [comment] 2021-11-15 04:12
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/23423 and few others

**Comment by knokio** [comment] 2021-11-15 10:15
> duplicate of #23423 and few others

@ankar84 this is not about the button mising. It's about the sync not working.

**Comment by ankar84** [comment] 2021-11-15 10:21
> > duplicate of #23423 and few others
> 
> @ankar84 this is not about the button mising. It's about the sync not working.

You have Enterprise Edition licence?

**Comment by knokio** [comment] 2021-11-16 08:30
> > > duplicate of #23423 and few others
> > 
> > 
> > @ankar84 this is not about the button mising. It's about the sync not working.
> 
> You have Enterprise Edition license?

We have paid for Pro. Why? @ankar84

**Comment by ankar84** [comment] 2021-11-16 08:41
> > > > duplicate of #23423 and few others
> > > 
> > > 
> > > @ankar84 this is not about the button mising. It's about the sync not working.
> > 
> > 
> > You have Enterprise Edition license?
> 
> We have paid for Pro. Why? @ankar84

Oh, in that case it is indeed a bug and not related to #23423
So we better ping @pierre-lehnen-rc and @sampaiodiego in that case.

**Comment by knokio** [comment] 2021-11-24 22:34
@ankar84 any news?

**Comment by ankar84** [comment] 2021-11-25 02:16
> @ankar84 any news?

I'm just community member, not a dev. 
I have ping proper persons in previous comment.

**Closed** 2023-01-21 23:34 UTC
