### ISSUE TITLE
Channels cannot be deleted anymore

### ISSUE THREAD

**Issue by rchikballapur** [RocketChat/Rocket.Chat#2369] opened 2016-02-29 10:49 UTC
Your Rocket.Chat version: (0.19)

Admins can't delete channels anymore, only archive it. Is this normal behaviour? There are no more buttons to do this? I checked the permission and the delete-c is set for the admin.

**Comment by sampaiodiego** [comment] 2016-02-29 11:57
duplicate of #2351

I'll be fixing this today and releasing in 0.20

**Closed by sampaiodiego** 2016-02-29 11:57 UTC
