### ISSUE TITLE
Unable to mention user with username ending with dot

### ISSUE THREAD

**Issue by wtsarchive** [RocketChat/Rocket.Chat#1583] opened 2015-12-06 21:21 UTC
It is possible to create a username like this: `test.`. When mentioning this user in the room by writing `@test.: something` the nickname isn't highlighted and the user is not notified.
We should either fix the regular expression that matches mentions, or prohibit users from creating such usernames :).

**Comment by sarahabrahamson** [comment] 2015-12-07 05:28
There's a similar issue to this already opened, #956. I don't know if anyone has worked on finding a solution since then.

**Comment by marceloschmidt** [comment] 2015-12-07 11:53
I'll close this for being a duplicate of #956.

**Closed by marceloschmidt** 2015-12-07 11:53 UTC
