### ISSUE TITLE
user-names instead of "real names" are shown

### ISSUE THREAD

**Issue by ffambri** [RocketChat/Rocket.Chat#23326] opened 2021-10-01 12:19 UTC
this is an issue that is visivle only (probably) in the desktop application.
In the browser I see the correct names (Name and Family Name)
while in the desktop application I see only the user-names, e.g.
I see "paolo.rossi"  instead of "Paolo Rossi"

and even worse, for those that does not have a standard user.name I only see an alphanumeric string, e.g.
"serviceAcc.5ejjk429gnfgj..." instead of "Paolo Rossi"

Probably a Duplicate of #23093

**Comment by reetp** [comment] 2021-10-02 15:23
Please, fill out a bug template.

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

> Probably a Duplicate of #23093

In which case follow up there unless you are sure that it is a different issue

Closing as duplicate of #23093 unless there is more information and it proves to be different in which case it can be re-opened.

**Closed by reetp** 2021-10-02 15:23 UTC
