### ISSUE TITLE
Pasting a screenshot into a message doesn't work on the first attempt if you paste very fast

### ISSUE THREAD

**Issue by nmummau** [RocketChat/Rocket.Chat#3156] opened 2016-05-06 14:34 UTC
Your Rocket.Chat version: 1.2.0

I use greenshot as a tool to capture screenshots. On a development team I often send these screenshots to developers to better show UI issues of our application.

When I paste a clipboard image into Rocket.Chat, and then quickly press enter it often doesn't paste the image. It takes a second attempt for it to work OR if I just slow down between my Ctrl+v and my enter keystroke it will work on the first attempt. 

Steps to reproduce
1. Use a snipping tool (I use Greenshot) to get an image in your clipboard
2. Attempt to paste it in in Rocket.Chat by pressing Ctrl+V and then _**quickly**_ pressing enter.
BUG: the little upload file dialog goes away but the image doesn't get pasted into the message
3. Again, attempt to paste it in in Rocket.Chat by pressing Ctrl+V and then _**quickly**_ pressing enter.
**notice that now it works

**Comment by Molle500** [comment] 2016-05-06 15:15
Noticed this alot as well.

**Comment by marceloschmidt** [comment] 2016-05-06 16:34
That's a bug that happens in other places as well, and it's related to the sweetalert plugin we use. If you try to hide or leave a room and quickly press enter, you'll also experience this.

**Comment by AndyCoach** [comment] 2017-05-02 23:44
Has this bug been solved? I have just recently installed RocketChat and the same persists.

**Comment by nmummau** [comment] 2017-05-03 17:33
@AndyCoach I just tried to reproduce and it seems _much_ harder to reproduce than it had been in the past. So if you're still having trouble, I would list your Rocket.Chat version, Chrome version, Operating System, etc.

**Comment by AndyCoach** [comment] 2017-05-03 17:41
Hi Neal, here is the info

Rocket.Chat version 0.54.2
OS Win 7 Pro SP 1 64 bit
Chrome Version 57.0.2987.133

Andy

Wednesday, May 3, 2017, 12:34:14 PM, you wrote:


@AndyCoach I just tried to reproduce and it seems much harder to reproduce than it had been in the past. So if you're still having trouble, I would list your Rocket.Chat version, Chrome version, Operating System, etc.

**Comment by geekgonecrazy** [comment] 2017-05-23 21:27
Its for sure still hanging around.  I've experienced a few times in the last couple of days.

Typically its only with paste though.  So its quick to just hit ctrl+v once again.  Still kind of annoying :)

**Comment by Hudell** [comment] 2018-06-06 13:53
I'm gonna close this because it seems to have been fixed (the animation that prevented the image from being sent is no longer active). If anybody is still running into this issue it can be opened again.

**Closed by Hudell** 2018-06-06 13:53 UTC
Labels: subj: ui/ux, type: bug
