### ISSUE TITLE
The application GUI just crashed.

### ISSUE THREAD

**Issue by aukfood** [RocketChat/Rocket.Chat#33462] opened 2024-10-04 14:27 UTC
### Steps to reproduce:

1. Go to rocketchat web url
2. Login
3. The application GUI just crashed.

### Expected behavior:

A working Rocketchat :)

### Actual behavior:
The application GUI just crashed.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.12.1
- License Type: non
- Number of Users: I don't know 
- Operating System: Debian 11
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: replSetName: rs01
- NodeJS Version: v14.21.3
- MongoDB Version: v5.0.29

### Client Setup Information

- Desktop App or Browser Version: Firefox and Edge
- Operating System: Linux and Windows

### Relevant logs:

```
Oct  4 16:18:36 myrocketserver rocketchat[4040860]: Some indexes for collection 'rocketchat_uploads' could not be created:
Oct  4 16:18:36 myrocketserver rocketchat[4040860]: #011An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, key: { rid: 1 }, name: "rid_1", sparse: true }, existing index: { v: 2, key: { rid: 1 }, name: "rid_1" }
Oct  4 16:18:36 myrocketserver rocketchat[4040860]: (node:4040860) UnhandledPromiseRejectionWarning: MongoServerError: An existing index has the same name as the requested index. When index names are not specified, they are auto generated and can cause conflicts. Please refer to our documentation. Requested index: { v: 2, key: { rid: 1 }, name: "rid_1", sparse: true }, existing index: { v: 2, key: { rid: 1 }, name: "rid_1" }
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at Connection.onMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:231:30)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at MessageStream.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:61:60)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at MessageStream.emit (events.js:400:28)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at MessageStream.emit (domain.js:475:12)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at writeOrBuffer (internal/streams/writable.js:358:12)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at Socket.ondata (internal/streams/readable.js:731:22)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at Socket.emit (events.js:400:28)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at Socket.emit (domain.js:475:12)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at addChunk (internal/streams/readable.js:293:12)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at readableAddChunk (internal/streams/readable.js:267:9)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]: (Use `node --trace-warnings ...` to show where the warning was created)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]: (node:4040860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Oct  4 16:18:36 myrocketserver rocketchat[4040860]: (node:4040860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Oct  4 16:18:50 myrocketserver rocketchat[4040860]: (node:4040860) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Oct  4 16:18:50 myrocketserver rocketchat[4040860]: Please migrate your code to use AWS SDK for JavaScript (v3).
Oct  4 16:18:50 myrocketserver rocketchat[4040860]: For more information, check the migration guide at https://a.co/7PzMCcy
Oct  4 16:18:50 myrocketserver rocketchat[4040860]: LocalStore: store created at
Oct  4 16:18:50 myrocketserver rocketchat[4040860]: LocalStore: store created at
Oct  4 16:18:50 myrocketserver rocketchat[4040860]: LocalStore: store created at
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: {"level":40,"time":"2024-10-04T14:18:51.757Z","pid":4040860,"hostname":"myrocketserver.aukfood.net","name":"VoIPAsteriskService","msg":"Voip is not enabled. Cant start the service"}
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: {"level":51,"time":"2024-10-04T14:18:51.788Z","pid":4040860,"hostname":"myrocketserver.aukfood.net","name":"Migrations","msg":"Not migrating, already at version 304"}
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.798Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/BROKER: Moleculer v0.14.31 is starting...
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.798Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/BROKER: Namespace: <not defined>
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.799Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/BROKER: Node ID: 397de9ca-e9bf-4554-8e79-cbdbc419f957
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.800Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/REGISTRY: Strategy: RoundRobinStrategy
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.800Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/REGISTRY: Discoverer: LocalDiscoverer
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.802Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/BROKER: Serializer: EJSONSerializer
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.817Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/BROKER: Validator: FastestValidator
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.820Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/BROKER: Registered 13 middleware(s).
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.821Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/BROKER: Transporter: TcpTransporter
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: {"level":51,"time":"2024-10-04T14:18:51.846Z","pid":4040860,"hostname":"myrocketserver.aukfood.net","name":"DatabaseWatcher","msg":"Using change streams"}
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.854Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/TRANSIT: Connecting to the transporter...
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.859Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/TRANSPORTER: TCP server is listening on port 43931
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.859Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/TRANSPORTER: UDP Discovery is disabled.
Oct  4 16:18:51 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:51.860Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/TRANSPORTER: TCP Transporter started.
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: (node:4040860) [MONGODB DRIVER] Warning: cursor.count is deprecated and will be removed in the next major version, please use `collection.estimatedDocumentCount` or `collection.countDocuments` instead
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: +--------------------------------------------------------+
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |                     SERVER RUNNING                     |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: +--------------------------------------------------------+
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |                                                        |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |  Rocket.Chat Version: 6.12.1                           |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |       NodeJS Version: 14.21.3 - x64                    |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |      MongoDB Version: 5.0.29                           |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |       MongoDB Engine: wiredTiger                       |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |             Platform: linux                            |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |         Process Port: 3000                             |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |             Site URL: https://myrocket.mydomain.com  |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |     ReplicaSet OpLog: Enabled                          |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |          Commit Hash: e22ea8f18a                       |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |        Commit Branch: HEAD                             |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: |                                                        |
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: +--------------------------------------------------------+
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:52.371Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/REGISTRY: '$node' service is registered.
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:52.372Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/REGISTRY: 'matrix' service is registered.
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:52.373Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/$NODE: Service '$node' started.
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:52.373Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/MATRIX: Service 'matrix' started.
Oct  4 16:18:52 myrocketserver rocketchat[4040860]: [2024-10-04T14:18:52.374Z] INFO  397de9ca-e9bf-4554-8e79-cbdbc419f957/BROKER: ✔ ServiceBroker with 2 service(s) started successfully in 536ms.
Oct  4 16:18:58 myrocketserver rocketchat[4040860]: Some indexes for collection 'rocketchat_read_receipts' could not be created:
Oct  4 16:18:58 myrocketserver rocketchat[4040860]: #011Index build failed: 796b8854-bae8-4834-812d-8a56f4f78ae6: Collection rocketchat.rocketchat_read_receipts ( 920afa39-49b9-4e32-aee1-2127de548bf8 ) :: caused by :: E11000 duplicate key error collection: rocketchat.rocketchat_read_receipts index: roomId_1_userId_1_messageId_1 dup key: { roomId: "2TPkJrRZwATbLkkNay2BbBF8bjKAzQ9ktR", userId: "2TPkJrRZwATbLkkNa", messageId: "Ru4raGY4e53zCq6Ap" }
Oct  4 16:18:58 myrocketserver rocketchat[4040860]: === UnHandledPromiseRejection ===
Oct  4 16:18:58 myrocketserver rocketchat[4040860]: MongoServerError: Index build failed: 796b8854-bae8-4834-812d-8a56f4f78ae6: Collection rocketchat.rocketchat_read_receipts ( 920afa39-49b9-4e32-aee1-2127de548bf8 ) :: caused by :: E11000 duplicate key error collection: rocketchat.rocketchat_read_receipts index: roomId_1_userId_1_messageId_1 dup key: { roomId: "2TPkJrRZwATbLkkNay2BbBF8bjKAzQ9ktR", userId: "2TPkJrRZwATbLkkNa", messageId: "Ru4raGY4e53zCq6Ap" }
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at Connection.onMessage (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:231:30)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at MessageStream.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:61:60)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at MessageStream.emit (events.js:400:28)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at MessageStream.emit (domain.js:475:12)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at processIncomingData (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at MessageStream._write (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at writeOrBuffer (internal/streams/writable.js:358:12)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at MessageStream.Writable.write (internal/streams/writable.js:303:10)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at Socket.ondata (internal/streams/readable.js:731:22)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at Socket.emit (events.js:400:28)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at Socket.emit (domain.js:475:12)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at addChunk (internal/streams/readable.js:293:12)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at readableAddChunk (internal/streams/readable.js:267:9)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:   ok: 0,
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:   code: 11000,
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:   codeName: 'DuplicateKey',
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:   keyPattern: { roomId: 1, userId: 1, messageId: 1 },
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:   keyValue: {
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     roomId: '2TPkJrRZwATbLkkNay2BbBF8bjKAzQ9ktR',
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     userId: '2TPkJrRZwATbLkkNa',
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     messageId: 'Ru4raGY4e53zCq6Ap'
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:   },
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:   '$clusterTime': {
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     clusterTime: new Timestamp({ t: 1728051538, i: 3 }),
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     signature: {
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:       hash: new Binary(Buffer.from("0000000000000000000000000000000000000000", "hex"), 0),
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:       keyId: 0
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:     }
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:   },
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:   operationTime: new Timestamp({ t: 1728051538, i: 3 }),
Oct  4 16:18:58 myrocketserver rocketchat[4040860]:   [Symbol(errorLabels)]: Set(0) {}
Oct  4 16:18:58 myrocketserver rocketchat[4040860]: }
Oct  4 16:18:58 myrocketserver rocketchat[4040860]: ---------------------------------
Oct  4 16:18:58 myrocketserver rocketchat[4040860]: Errors like this can cause oplog processing errors.
Oct  4 16:18:58 myrocketserver rocketchat[4040860]: Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
Oct  4 16:18:58 myrocketserver rocketchat[4040860]: Future node.js versions will automatically exit the process
Oct  4 16:18:58 myrocketserver rocketchat[4040860]: =================================
```

Thanks for you're help

**Comment by zaraquer** [comment] 2024-10-04 16:04
Same issue here with rocketchat version 6.7.2 and 6.7.8 too.
No error in the logs, except this one:
`Oct  4 17:59:03 Rocket rocketchat[1788]: Exception while invoking method autoTranslate.getSupportedLanguages errorClass [Error]: Auto-Translate is disabled [error-autotranslate-disabled]
Oct  4 17:59:03 Rocket rocketchat[1788]:     at app/autotranslate/server/methods/getSupportedLanguages.ts:20:10
Oct  4 17:59:03 Rocket rocketchat[1788]:     at /opt/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Oct  4 17:59:03 Rocket rocketchat[1788]:  => awaited here:
Oct  4 17:59:03 Rocket rocketchat[1788]:     at Function.Promise.await (/opt/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Oct  4 17:59:03 Rocket rocketchat[1788]:     at packages/meteor.js:367:22
Oct  4 17:59:03 Rocket rocketchat[1788]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
Oct  4 17:59:03 Rocket rocketchat[1788]:     at packages/ddp-server/livedata_server.js:1854:36
Oct  4 17:59:03 Rocket rocketchat[1788]:     at new Promise (<anonymous>)
Oct  4 17:59:03 Rocket rocketchat[1788]:     at Server.applyAsync (packages/ddp-server/livedata_server.js:1853:12)
Oct  4 17:59:03 Rocket rocketchat[1788]:     at Server.callAsync (packages/ddp-server/livedata_server.js:1779:17)
Oct  4 17:59:03 Rocket rocketchat[1788]:     at app/api/server/v1/misc.ts:561:33
Oct  4 17:59:03 Rocket rocketchat[1788]:     at /opt/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Oct  4 17:59:03 Rocket rocketchat[1788]:  => awaited here:
Oct  4 17:59:03 Rocket rocketchat[1788]:     at Function.Promise.await (/opt/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Oct  4 17:59:03 Rocket rocketchat[1788]:     at app/api/server/v1/misc.ts:561:17
Oct  4 17:59:03 Rocket rocketchat[1788]:     at /opt/rocket/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 {
Oct  4 17:59:03 Rocket rocketchat[1788]:   isClientSafe: true,
Oct  4 17:59:03 Rocket rocketchat[1788]:   error: 'error-autotranslate-disabled',
Oct  4 17:59:03 Rocket rocketchat[1788]:   reason: 'Auto-Translate is disabled',
Oct  4 17:59:03 Rocket rocketchat[1788]:   details: undefined,
Oct  4 17:59:03 Rocket rocketchat[1788]:   errorType: 'Meteor.Error'
Oct  4 17:59:03 Rocket rocketchat[1788]: }`

**Comment by reetp** [comment] 2024-10-07 10:22
FYI. Backup your DB and manually clean up your indexes.

Closing as duplicate of these - please follow up there:

https://github.com/RocketChat/Rocket.Chat/issues/33263

https://github.com/RocketChat/Rocket.Chat/issues/31893


Also note for this:

> Same issue here with rocketchat version 6.7.2 and 6.7.8

Always use the newest version of a particular release - in your case 6.7.9 

Also note 6.7.x is EOL at the end of this month. You need to start upgrading.

https://docs.rocket.chat/docs/version-durability

**Closed by reetp** 2024-10-07 10:22 UTC
Labels: duplicate

**Comment by zaraquer** [comment] 2024-10-07 11:48
> FYI. Backup your DB and manually clean up your indexes.
> 
> Closing as duplicate of these - please follow up there:
> 
> #33263
> 
> #31893
> 
> Also note for this:
> 
> > Same issue here with rocketchat version 6.7.2 and 6.7.8
> 
> Always use the newest version of a particular release - in your case 6.7.9
> 
> Also note 6.7.x is EOL at the end of this month. You need to start upgrading.
> 
> https://docs.rocket.chat/docs/version-durability

Man, in our case the issue just come and go, I didn't do anything. So I dont think it was a database issue, because I tried with an 6 months old database just to check, and it had the same issue. So its not a duplicate. Also it hardly depends on the rocketchat version, because the update didn't help either.

The issue was not on our side FYI, and I want to know what happened.

**Comment by reetp** [comment] 2024-10-07 12:09
I suggested cleaning up your indexes as advice - it is easier to see your logs.

I advised regarding upgrading as it is again just good sysadmin and it is easier to debug thereafter.

As far as your 'crash' issue goes if you had searched you would have found several duplicates

https://github.com/RocketChat/Rocket.Chat/issues?q=is%3Aissue+application+GUI+just+crashed

I saved you the trouble by linking to the two important issues.

Note the devs comments here:

https://github.com/RocketChat/Rocket.Chat/issues/33263#issuecomment-2361928585

Also note your comment and then see above:

> only users with admin rights experience this login issue

As per those issues.

Please don't open another.

**Comment by geidsonc** [comment] 2024-10-07 12:29
I have the same problem.

![image](https://github.com/user-attachments/assets/724951ce-5206-47f9-a099-8f626246760d)

**Comment by reetp** [comment] 2024-10-07 13:14
> I have the same problem.

You have given zero information on your server so there is absolutely no way of knowing it really is a duplicate or just a coincidence.

"#Metoo" helps no one.

Commenting on a duplicate is just as pointless.

See the previous comments and links on how to properly assist the developer.

I have detailed it, and so has he.

It will also help you all to read this on how to report bugs effectively.

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#rocketchat---asking-for-help

See the links here as well:

https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#still-stuck

Please don't add any more to this issue. Fully document your situation and add to the existing ones.

Thanks.

**Comment by geidsonc** [comment] 2024-10-08 14:39
For anyone who comes here with the same issue, I solved it using this solution from the community: https://github.com/RocketChat/Rocket.Chat/issues/33263#issuecomment-2352775592
