### ISSUE TITLE
If an admin leaves a private group, it seems there is no way to reenter without asking another person to add them back

### ISSUE THREAD

**Issue by bgupta** [RocketChat/Rocket.Chat#2084] opened 2016-01-29 20:49 UTC
This is clearly not by design.

**Comment by vetash** [comment] 2016-01-30 05:28
+1

**Comment by graywolf336** [comment] 2016-01-30 20:07
What's the expected result?

**Comment by bgupta** [comment] 2016-01-30 20:48
Well, two parts.

1) leaving channels/groups should have a confirmation dialog
2) admins should be able to see private groups even if they aren't in them.
(Or at least that's what seems logical)

-Brian

**Comment by vetash** [comment] 2016-01-30 21:48
@graywolf336 i mean i confirm this bug, so, there should be ability to view all private groups like open channels. e.g. by click button "more private channel" in bottom of pg

**Comment by jasperla** [comment] 2016-02-01 08:36
I ran into exactly this because of #2056 . The proposed solution by @bgupta sounds good to me.

**Comment by mstred** [comment] 2016-02-08 02:29
@jasperla's fix was marvelous. Thank you. But then again, I guess that wouldn't solve the confusing issue about setting a random admin in place of the previous one, right after he/she leaves the room (on his/her own).
Could we get something like Slack's no-admin policy for private groups (configurable, as it should be) or even WhatsApp's multiple admin feature for groups?

**Comment by engelgabriel** [comment] 2016-02-26 18:19
1) leaving channels/groups should have a confirmation dialog - DONE

**Comment by engelgabriel** [comment] 2016-02-26 18:37
We should add the respective permission to the admin role, create the security checks, and amend the UI so admin can have a button to open/join private room.

**Comment by marceloschmidt** [comment] 2016-04-07 19:42
Do you guys think that admins should be able to see/join private groups? By design, we decided they wouldn't be possible to, but that's changeable, of course. @RocketChat/core what do you think?

**Comment by sampaiodiego** [comment] 2016-04-07 19:55
I have mixed fellings about this..
If I was an admin, I would like to be able to see/join private groups.
But if I am just an user, I don't know if I like the idea of someone reading my messages on privates groups.

For the project, I think it should be possible (to an admin see/join private groups), also we should have a permission to allow others to do so.

**Comment by marceloschmidt** [comment] 2016-04-07 20:03
I think that defeats the purpose of **private** groups... I think we should protect users privacy on this one.
Although I'm not convinced this is a good thing to have, I'd accept it **if** admins could **not** see the contents of the room prior to entering. This way, if they wanted to read the messages, they'd be announcing they joined (through system messages).

**Comment by engelgabriel** [comment] 2016-04-27 07:17
Shall we close this issue?

**Comment by bgupta** [comment] 2016-04-27 12:04
At the end of the day it will be very difficult to block a (sys)admin from seeing the details of something he manages. I like the confirmation dialog, as it does help, but at the end of the day, one needs to trust the admins, and they should have a way to deal with this. e.g. - I could see in some orgs where admins put people in their appropriate groups without being member of the groups themselves. 

I think I am in agreement with @sampaiodiego and I'm ok with @marceloschmidt's suggestion that admins not being able to see the content of rooms, prior to entering.

**Comment by marceloschmidt** [comment] 2016-04-27 12:07
We have decided to keep admins from getting into private groups (and direct messages). This issue solves the question about assigning a new room owner before the last owner leaves a room. Thanks @bgupta.

**Closed by marceloschmidt** 2016-04-27 12:07 UTC
Labels: subj: ui/ux, type: improvement

**Comment by developerlaoz** [comment] 2016-08-02 10:14
I create a private group as admin, and there is no other member in the group yet. 
I leave the group, and how could I reenter the group.

**Comment by marceloschmidt** [comment] 2016-08-02 16:08
@developerlaoz when you create a private group, the user who created it becomes owner. The owner cannot leave the group unless he/she sets another user as owner.

**Comment by engelgabriel** [comment] 2016-08-02 22:56
@developerlaoz did it work as @marceloschmidt explained?

**Comment by developerlaoz** [comment] 2016-08-04 03:21
Create a private group -> show the member list -> select owner (myself) -> delete from the group -> select confirm to delete the user.

Now I lost the group, and never enter it again. 
And I can not create the private group with the same name again.

I use the Rocket.Chat+ app in mac installed from app store.

**Comment by engelgabriel** [comment] 2016-08-09 22:32
Got it. We have added the check on LEAV THE ROOM method, but forgot to add the same check on DELETE and REMOVE user methods.

**Comment by engelgabriel** [comment] 2016-08-09 22:42
@developerlaoz I have opened the issue https://github.com/RocketChat/Rocket.Chat/issues/3965 for that.

**Comment by developerlaoz** [comment] 2016-08-10 06:14
I got it, thanks and wait for the new release.

Is there any way to get my private group back?

**Comment by rodrigok** [comment] 2016-08-10 12:48
@developerlaoz Do you have access to your DB?

**Comment by developerlaoz** [comment] 2016-08-11 10:23
What is the suggestion if I can access the DB?
Is there admin role to manage all the data in any management tool?

**Comment by flaviovs** [comment] 2018-04-26 19:42
A super-admin (the guy who installed and manages RC) can always go to the DB and see the messages, so I guess everyone agrees that at this level privacy nonexistent, right?

All that said, the _admin can manage private groups_ use case is a legitimate one, and I also guess that the mixed opinions are because many RC admins are OS admins, and many are not (and I suppose some may not want to give superpowers to their RC admins).

But again, RC admin superpower is a legitimate use case, IMHO. My example: I am now an admin of a RC instance in which employees created a bunch of channels. Those persons left the company, and now nobody is able to add anyone to those channels anymore, not even me. We cannot see the messages that got exchanged either, and I cannot tell who created the channels at first place (a missing feature of desktop app?). To make things worst, another RC admin (mistakenly) have deleted some of those former employee accounts. Lastly, I cannot just delete and recreate the channels, because I want the content on them to be preserved.

Now to get a peek at the messages I need to go straight to the DB which, beside being a lot of work, defeats the purpose of privacy of **all** channels in my RC, including DMs.

Maybe one way to solve this would be to provide a server-level argument that tells the app that RC admin privacy enforcement should be turned off?  Something like `node main.js --no-admin-privacy`?

**Comment by geekgonecrazy** [comment] 2018-05-30 05:55
I hate to leave your argument on a closed ticket unseen.  Might be best posting on an open ticket or opening one requesting some sort of feature or permission to allow what you desire.  There might be a request already open

**Comment by juice99** [comment] 2019-01-17 10:20
I totally agree with flaviovs suggestions and we have similar problem, this issue should be re-opened or new one created

**Comment by rpannek** [comment] 2019-08-06 09:51
I have the same problem too. Sure I can go into the DB and try to understand the relations between the tables but that's like open heart surgery when the patient is awake.
