### ISSUE TITLE
Can no longer find the 'Group Video Call' capability

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#11004] opened 2018-06-05 06:35 UTC
I used to be able to do a group video call for an entire Group or Public Channel... now that I've updated to 0.64.1, I don't see that button anywhere.   Am I missing something?   Where should it be for a group?

**Comment by kaiiiiiiiii** [comment] 2018-06-05 07:20
Duplicate of #9632

**Comment by TwizzyDizzy** [comment] 2018-06-06 07:51
@rocket-cat close

**Closed by TwizzyDizzy** 2018-06-06 07:51 UTC
