### ISSUE TITLE
Duplicate Key Error - Can't write any direct message

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat#7364] opened 2017-06-29 06:22 UTC
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: active
Node Version: 4.8.2

We have a Problem with an old local Rocket.Chat-User. I deleted the local user because it was broken and reimported it via LDAP-Sync with the same E-Mail but another username. I can write private Messages to this user because i wiped the Chat before i deleted the user. Others cant write any direct message because of an duplicate key error:

[34mI20170628-08:20:03.254(2) Exception while invoking method 'createDirectMessage' MongoError: E11000 duplicate key error collection: parties.rocketchat_subscription index: u.id_1_name_1_t_1_code_1 dup key: { : "QwhRFRbzvAA6hHXFa", : "katharina.schmidt", : "d", : null } at Object.Future.wait (/snap/rocketchat-server/653/node_modules/fibers/future.js:449:15) at [object Object]. (packages/meteor.js:213:24) at [object Object].MongoConnection.(anonymous function) [as update] (/snap/rocketchat-server/653/programs/server/packages/mongo.js:836:49) at Object. (packages/matb33_collection-hooks.js:504:27) at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21) at [object Object].update (/snap/rocketchat-server/653/programs/server/packages/mongo.js:3899:31) at ModelsBaseDb.update (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:9640:32) at ModelsBaseDb.upsert (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:9715:16) at ModelSubscriptions.upsert (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:4192:36) at [object Object].Meteor.methods.createDirectMessage (/snap/rocketchat-server/653/programs/server/app/app.js:6142:35) at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30) at [object Object].methodsMap.(anonymous function) (/snap/rocketchat-server/653/programs/server/packages/rocketchat_lib.js:1021:26) at maybeAuditArgumentChecks (/snap/rocketchat-server/653/programs/server/packages/ddp-server.js:1823:12) at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:905:20 at [object Object]..extend.withValue (packages/meteor.js:1122:17) at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:904:41 at [object Object]..extend.withValue (packages/meteor.js:1122:17) at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:903:46 at [object Object]..extend.protocol_handlers.method (/snap/rocketchat-server/653/programs/server/packages/ddp-server.js:876:21) at /snap/rocketchat-server/653/programs/server/packages/ddp-server.js:755:85 - - - - - at Function.MongoError.create (/snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11) at toError (/snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22) at /snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1049:67 at /snap/rocketchat-server/653/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18 at nextTickCallbackWith0Args (node.js:489:9) at process._tickDomainCallback (node.js:459:13)

![clipboard - 29 juni 2017 08-18](https://user-images.githubusercontent.com/26709898/27673982-ec3cf57a-5ca3-11e7-857a-eb5e848e623a.png)

Seems linked to #1227

**Comment by MartinSchoeler** [comment] 2017-07-28 12:33
Duplicate of #6535

**Closed by MartinSchoeler** 2017-07-28 12:33 UTC
Labels: feat: accounts, type: bug
