### ISSUE TITLE
Update_user no está permitido

### ISSUE THREAD

**Issue by peroda** [RocketChat/Rocket.Chat#11886] opened 2018-08-28 09:56 UTC
### Description:

Unable to update user's properties in version 0.69

### Steps to reproduce:

1. Go to 'admin/users' 
2. Click on 'save button'
3. Update_user no está permitido

### Expected behavior:

Save user

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69
- Operating System: Centos 7.4
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

**Comment by kaiiiiiiiii** [comment] 2018-08-30 15:05
As @peroda said, it's a duplicate of #11884.

// CC: @TwizzyDizzy

**Closed** 2018-08-30 15:51 UTC

**Comment by zzeesstt** [comment] 2018-08-31 10:57
A similar problem. I confirm!

**Comment by JEREYMNO** [comment] 2018-09-03 10:44
SAME PROBLEM!!! URGENT
