### ISSUE TITLE
sort users by their last activity in admin panel

### ISSUE THREAD

**Issue by si90** [RocketChat/Rocket.Chat#14599] opened 2019-05-22 19:45 UTC
Rocket.Chat should have the ability, to sort users by their "last message" or their "last activity".

This information should be displayed in the user overview (Administration --> Users), because it makes deletion of unused accounts much easier.

Even better would be the possibility to automatically disable unused accounts after a configurable amount of time, but for the first step displaying the last activity would be fine.

**Comment by reetp** [comment] 2019-05-22 21:41
@rocket-cat close

Please open this in Feature requests (if you search thoroughly I think there is a duplicate of this Issue somewhere)

https://github.com/RocketChat/feature-requests/issues

**Closed by reetp** 2019-05-22 21:41 UTC
