### ISSUE TITLE
[Feature request] Add an option to bring all unread private chats to top of list, regardless of other sorting options

### ISSUE THREAD

**Issue by wildy** [RocketChat/Rocket.Chat#22906] opened 2021-08-11 14:01 UTC
Hi there.

I often find it very annoying when unread private chats scroll to bottom of conversation list, when you have a large number of chats open. Often it leads to people asking some work questions and scrolling down before I can notice it, if I didn't happen to be around to catch the notification right away.

Right now I'm using Favorites to manage most important contacts, but it would have been ideal to implement the following logic: bring up any and all __unread__ private messages before all other chats, regardless of other sorting settings (by activity, or by type). That would ensure any PMs wouldn't be missed in the usual organizational chaos :).

**Comment by johncrisp** [comment] 2021-08-11 19:10
Closing as this is a duplicate of this issue:

https://github.com/RocketChat/feature-requests/issues/480

**Closed by johncrisp** 2021-08-11 19:10 UTC
