### ISSUE TITLE
Show "name" next to "username" when inviting users to a channel

### ISSUE THREAD

**Issue by EddEdw** [RocketChat/Rocket.Chat#10491] opened 2018-04-18 09:35 UTC
### Description:

At the moment, when you invite someone to a channel or you want to reference someone in text, who has not yet "written" in this channel, you only see his username and not the "name" field. 

#### Add-Users-Tab:
![image](https://user-images.githubusercontent.com/6577198/38923506-02c468ee-42fb-11e8-89ae-ea2740498781.png)

#### Referencing users in text:
![image](https://user-images.githubusercontent.com/6577198/38923644-637a9690-42fb-11e8-86da-f1bfe89462e2.png)

In our company we can only use identifiers as username (since they are unique) and RocketChat does not allow full email as username. Unfortunately this makes it very hard to invite colleagues to channels. Interestingly does the search consider the name. So if I type a name, say "Tim", I get shown a list of IDs that have "Tim" in their name - but I dont get this shown as seen in the screens above. How much effort would it take to integrate this feature?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.1
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.11.1
* mongoDB Version: -

### Steps to Reproduce:

1. click "add Users" or type "@" symbol in chat
2. the search result show up

### Expected behavior:

.... usernames should show up but also with the user's name behind it. --> interesting is, that the search result actually considers the user's name but doesn't show it like it does for people who already wrote in the chat recently.

![image](https://user-images.githubusercontent.com/6577198/38924187-8d6e806e-42fc-11e8-8ab8-38492e376d8f.png)

### Actual behavior:

.... and only usernames are shown but not the "real name" :-(

**Comment by neverpanic** [comment] 2018-05-09 16:04
Duplicate of #9890, solved in #10444, released in 0.64.0.

**Closed** 2018-05-28 03:47 UTC
