### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by UniPAYNINJA** [RocketChat/Rocket.Chat#23084] opened 2021-09-01 09:35 UTC
we have updated the RC but still getting this error 

Cannot read property 'length' of undefined

using client version 3.1.1 and even same result on new version

**Comment by ankar84** [comment] 2021-09-01 09:40
Hi and thanks for reporting this.

Can you please use a bug template if you are reporting an issue - this information is extremely important for triage:

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Make sure you follow the guidelines:

https://rocket.chat/docs/contributing/reporting-issues

That includes testing on the latest version of Rocket.Chat - you can test on open.rocket.chat in the sandbox channel.

Note also that for general questions and help you are better off asking in https://forums.rocket.chat or https://open.rocket.chat #support as github is reserved for bugs.

**Comment by UniPAYNINJA** [comment] 2021-09-01 09:51
its not easy to submit such report, I am not a bug tester .....

just check my image and explore more. 

we have found this issue posted by others as well

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1768

**Comment by debdutdeb** [comment] 2021-09-02 06:15
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/23085

Closing in favor of that.

**Closed by debdutdeb** 2021-09-02 06:15 UTC
