### ISSUE TITLE
Color issues

### ISSUE THREAD

**Issue by sampaiodiego** [RocketChat/Rocket.Chat#5040] opened 2016-11-24 13:45 UTC
Your Rocket.Chat version: 0.47.0-develop

After the merge of #4803 I've found many color issues, so I'll try to gather them all here.

- [x] Missing borders on _My Account_ page: [image](https://cloud.githubusercontent.com/assets/8591547/20600190/7b2e97c2-b239-11e6-8ed9-79a4df4e3920.png)
- [x] Date divider white: [image](https://cloud.githubusercontent.com/assets/8591547/20600368/77dccfb6-b23a-11e6-8700-e8deb1c09890.png)
- [x] Favorite icon without gray border: [image](https://cloud.githubusercontent.com/assets/8591547/20600346/55075eac-b23a-11e6-99b2-606bcf7326cb.png)
- [x] Message text box without border: [image](https://cloud.githubusercontent.com/assets/8591547/20600384/8dd1e2de-b23a-11e6-97a1-ed9f0168078e.png)
- [x] white and transparent "unread bar": [image](https://cloud.githubusercontent.com/assets/8591547/20604664/b5f63ec2-b24e-11e6-8eb8-1b2d2481fc1b.png)
- [x] Room's list hover too white: [image](https://cloud.githubusercontent.com/assets/8591547/20600244/c8e30296-b239-11e6-874f-1d6da08b376a.png)
- [x] Livechat menu has a lighter background: [image](https://cloud.githubusercontent.com/assets/8591547/20600291/ff916314-b239-11e6-8a28-bacaf021f31c.png)
- [x] "unread messages" bar at the very top disappears whenever the scroll event is triggered and completed (thanks @frdmn - [post](https://github.com/RocketChat/Rocket.Chat/issues/5040#issuecomment-262800382)): [image](https://cloud.githubusercontent.com/assets/944459/20603634/b9e89818-b262-11e6-906e-9679a219243c.gif)
- [x] It used to have a line above the "unread messages" divider: [image](https://cloud.githubusercontent.com/assets/8591547/20678317/6492a408-b57d-11e6-8f7a-444f738f5886.png)
- [x] Code styles: [image](https://cloud.githubusercontent.com/assets/8591547/20600516/3034427e-b23b-11e6-9497-0cf4de991cea.png)
- [x] the background of what before was a grayish-white is now full-white: [image](https://cloud.githubusercontent.com/assets/1986378/20608752/ccde0b2a-b26b-11e6-9c38-675a5b976fef.png)
- [x] Attachment buttons darker then before: [image](https://cloud.githubusercontent.com/assets/8591547/20600384/8dd1e2de-b23a-11e6-97a1-ed9f0168078e.png)
- [x] `@all` changed to red; `@mention` changed to a darker blue; darker _role tag_ background: [image](https://cloud.githubusercontent.com/assets/8591547/20600456/e93cdcf0-b23a-11e6-9d42-4d1adadcc78d.png)
- [x] Other's `@mention` changed to gray: [image](https://cloud.githubusercontent.com/assets/1986378/20603350/54fe2a5e-b248-11e6-95c1-71a73b48b8e9.png)
- [x] Message action buttons styles: [image](https://cloud.githubusercontent.com/assets/8591547/20600532/4a820ed6-b23b-11e6-82e0-3c6dcb3fa74d.png)
- [x] emoji picker search box background used to be white: [image](https://cloud.githubusercontent.com/assets/8591547/20605065/9a624032-b250-11e6-854e-2946f62fc7a5.png)
- [x] message editing highlight got red and the text field got white: [image](https://cloud.githubusercontent.com/assets/8591547/20608410/d9c74caa-b268-11e6-8e6a-696e8a31ff27.png)
- [x] Expand/collapse button on admin are got white (gray only on hover): [image](https://cloud.githubusercontent.com/assets/8591547/20720312/d2114782-b645-11e6-8003-3e356cd42d33.png)
- [x] File upload got a more transparent background and it's not perfectly aligned: [image](https://cloud.githubusercontent.com/assets/1986378/20603684/c591119a-b249-11e6-9524-dd9548976d91.png)
- [x] "user is typing" is breaking line if you're editing some message: [image](https://cloud.githubusercontent.com/assets/8591547/20603786/49734d52-b24a-11e6-95e1-54e7a02ade94.png)
- [x] messages scrollbar got white: [image](https://cloud.githubusercontent.com/assets/8591547/20604923/097cacec-b250-11e6-86b2-80ef57e60212.png)
- [x] Login form auto-fill sets a background on text fields (thanks @MartinSchoeler - [post](https://github.com/RocketChat/Rocket.Chat/issues/5040#issuecomment-263251130)): [image](https://cloud.githubusercontent.com/assets/20868078/20667231/5e59f4ca-b54f-11e6-9177-3ebccc923ed1.png)
- [x] Background no changing on hovering attachment buttons: [image](https://cloud.githubusercontent.com/assets/8591547/20600412/bbce5474-b23a-11e6-9072-414277dccaad.png)
- [x] Server connection status: [image](https://cloud.githubusercontent.com/assets/8591547/20603102/1ea22f7e-b247-11e6-9270-52b00a98f754.png)
- [x] light blue buttons got white: [image](https://cloud.githubusercontent.com/assets/8591547/20604713/ef79b6b0-b24e-11e6-9ca9-10728dda0c1e.png)
- [ ] First lines of a multi-line message increases the size down: [image](https://cloud.githubusercontent.com/assets/8591547/20668930/878397e4-b558-11e6-8727-8180cd33452e.png)

**Comment by frdmn** [comment] 2016-11-24 14:09
Also @TheReal1604 told me that the loading spinners (pulsing dots) are gone, which I can confirm.

**Comment by frdmn** [comment] 2016-11-24 15:26
And the "unread messages" bar at the very top disappears whenever the scroll event is triggered and completed:

![test](https://cloud.githubusercontent.com/assets/944459/20603634/b9e89818-b262-11e6-906e-9679a219243c.gif)

**Comment by engelgabriel** [comment] 2016-11-24 20:16
Initial fix via https://github.com/RocketChat/Rocket.Chat/commit/82847dacfc11122dd00ac03fe8095fb4935ba900

**Comment by MartinSchoeler** [comment] 2016-11-28 11:45
This happens if you use the auto complete in the login page 
![screenshot from 2016-11-28 09-41-01](https://cloud.githubusercontent.com/assets/20868078/20667220/4fb1aa08-b54f-11e6-990a-22d8edf7b034.png)
![screenshot from 2016-11-28 09-39-56](https://cloud.githubusercontent.com/assets/20868078/20667231/5e59f4ca-b54f-11e6-9177-3ebccc923ed1.png)

**Comment by timkinnane** [comment] 2016-11-29 05:59
Thanks @sampaiodiego for finding all those issues. I knew about some of them, but thought the effort to get a more consistent baseline was a net improvement, even with some bugs. My PR had to survive merges with multiple versions too, so I think some of those issues are the result of conflicts being resolved without noticing all the details they impact. Hopefully I'll get some time to help resolve the remaining ones.

**Comment by karlprieb** [comment] 2016-11-29 06:12
@timkinnane if you get some time call me on Rocket.Chat :) I'm fixing these errors.

**Comment by timkinnane** [comment] 2016-11-30 00:43
@karlprieb nice work, thanks. I find it hard to match up with you guys time zone for calls outside work hours, but will try and catch you online in demo.rc.
My main concern is just that the color scheme variables are used to resolve any issues. Not worried if the colors themselves need changing or we use one instead of another. Just wanted to avoid any hard coded colors in the less files, to achieve the main object of letting people set their own color scheme without having fixed colors they can't change ruining the application of their scheme.

**Comment by Sing-Li** [comment] 2016-12-08 19:18
More unintended CSS changes due to the PR continues to pour in. 

Not all impact has been addressed.  Re-opening this case.

**Comment by karlprieb** [comment] 2016-12-08 20:16
I will look these changes.

**Comment by IQ2022** [comment] 2016-12-08 20:31
Unread messages stays longer than it should, also it has wrong place it overlays the username, so if you want to change or react to a msg, it wont allow you to click on the setting wheel..

**Comment by engelgabriel** [comment] 2016-12-09 19:41
![image](https://cloud.githubusercontent.com/assets/1000217/21062163/ae1bf590-be36-11e6-8f73-7f110946e3e9.png)

**Comment by engelgabriel** [comment] 2016-12-12 17:58
@IQ2022 can you open a new issue for the "Unread messages stays longer than it should, also it has wrong place it overlays the username"?

**Closed** 2016-12-12 17:57 UTC
