### ISSUE TITLE
Search mark breaks links

### ISSUE THREAD

**Issue by microsoft-sucks** [RocketChat/Rocket.Chat#18696] opened 2020-08-27 10:38 UTC
### Description:

Links in search results are broken because `<mark>` is inserted to highlight the search key.

**Highlighting is great**, a broken link isn't

### Steps to reproduce:

1. send link `test.com`
2. search "test"
3. click link in search result

### Expected behavior:

`http://test.com`

### Actual behavior:

`http://<mark>test</mark>.com`

![image](https://user-images.githubusercontent.com/67187266/91432559-6902af00-e851-11ea-9448-5ba56714ed51.png)

only the link text should include `<mark>`, not `href`

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.2
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System:

### Relevant logs:

cc https://github.com/RocketChat/Rocket.Chat/pull/16166

**Comment by TBG-FR** [comment] 2020-08-28 12:26
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/18456

**Comment by MartinSchoeler** [comment] 2020-10-06 18:11
Please move this discussion to https://github.com/RocketChat/Rocket.Chat/issues/18770 Thanks!

**Closed by MartinSchoeler** 2020-10-06 18:11 UTC
