### ISSUE TITLE
rocket depends on mongo db 5.0+ not working on synology

### ISSUE THREAD

**Issue by 55thdt** [RocketChat/Rocket.Chat#25202] opened 2022-04-16 03:12 UTC
rocket chat depends on mongodb 5.0+ but isn't supported on synology nas because of avx any way to get around this

**Comment by dudanogueira** [comment] 2022-04-20 12:32
Hi!

Please, check [Rocket.Chat's MongoDB requirements Matrix](https://docs.rocket.chat/getting-support#mongodb-support)

It supports 4.0, 4.2, 4.4, 5.0 on the current major (4.X)

Closing as this is not a bug on Rocket.Chat's side, but a CPU incompatibility with Mongo 5.X

**Closed by dudanogueira** 2022-04-20 12:32 UTC
