### ISSUE TITLE
Does rocket chat has a DBA account of mongo db?

### ISSUE THREAD

**Issue by kyle-kai** [RocketChat/Rocket.Chat#8673] opened 2017-10-27 03:41 UTC
- I am now learning how to use rocket chat, and when I type "meteor npm start", I find rocket chat use a local mongo db on my server, so I have two questions:

- The first question is that the  rocket chat connect to mongo db use a account with username and password? And how and where can I change the password?

- If I want to let rocket chat connect to another mongo db on the other server, which configuration file should I modify?

**Comment by jszaszvari** [comment] 2017-10-27 09:48
> The first question is that the rocket chat connect to mongo db use a account with username and password? And how and where can I change the password?

When starting it this way it's usually for testing purposes only, so it does not have a username or password. 

> If I want to let rocket chat connect to another mongo db on the other server, which configuration file should I modify?

It depends on the deployment method, but for most of them you need to set the MONGO_URL environment variable. The format is like this:

MONGO_URL=[username]:[password]@mongo:27017/rocketchat

**Comment by exagon** [comment] 2017-10-27 14:04
I've used mongobooster to access at rocketchat db without user and password

**Comment by antgel** [comment] 2017-10-27 19:55
@MartinSchoeler This is a support question, not a bug.

**Comment by kyle-kai** [comment] 2017-10-30 02:36
So if I want to start with the "meteor npm start" commond, and I want to connect mongo db with account verify, what shuold I do?

**Comment by MartinSchoeler** [comment] 2017-10-30 13:37
We aim to keep our Github issues for bugs and feature requests. This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request

**Closed by MartinSchoeler** 2017-10-30 13:37 UTC
