### ISSUE TITLE
[Bug] New message parser

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#22280] opened 2021-06-08 04:57 UTC
### Description:

In that issue I will try to accumulate some issues with new message parser
![image](https://user-images.githubusercontent.com/4023037/121124112-094c2200-c82d-11eb-8918-53556523c0e5.png)

### Steps to reproduce:

1. Create some complex text
2. Check how it parsed

### Expected behavior:

All should parsed properly

### Actual behavior:

`_italic message followed by some letter_A` not become italic

This
![image](https://user-images.githubusercontent.com/4023037/121124962-71e7ce80-c82e-11eb-8f9f-4d4f3ae7c4e2.png)
not parsed
![image](https://user-images.githubusercontent.com/4023037/121124921-65fc0c80-c82e-11eb-8350-c123a7dd3737.png)
But this
![image](https://user-images.githubusercontent.com/4023037/121125007-7f9d5400-c82e-11eb-926f-8de0a0a9f61b.png)
do
![image](https://user-images.githubusercontent.com/4023037/121125028-86c46200-c82e-11eb-96cf-b2dddddd1eb9.png)

So, for now we found 2 bugs:
- `_italic message followed by some letter_A` not become italic
- code block not transform to code block in there is new line before bottom apostrophes 

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 25
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.2.14 WiredTiger

### Client Setup Information

- Desktop App or Browser Version: 3.2.2
- Operating System: Windows 10

### Additional context

https://open.rocket.chat/channel/support?msg=StXKYkq3DbL4GQ2RE

### Relevant logs:

No

**Comment by ankar84** [comment] 2021-06-08 07:25
Another interesting issue with new parser - ascii emoji become graphic emoji and again transform in ascii
![new_parser](https://user-images.githubusercontent.com/4023037/121141676-e8db9200-c843-11eb-98ea-c2cd1fe3cb8f.gif)

**Comment by johncrisp** [comment] 2021-06-08 08:53
Thanks for reporting this Anton.

Good we have someone testing it!!

**Comment by ankar84** [comment] 2021-06-09 03:52
Another issue.
We have Lotus Notes client and all that Lotus Domino infrastructure, so I added `notes,Notes` to **Markdown Support Schemes for Link** in **Admin UI - Message**
![image](https://user-images.githubusercontent.com/4023037/121289008-f7ca4f00-c8ec-11eb-95ed-f87d2db8b69a.png)
And in legacy parser all looks fine (link works fine)
![image](https://user-images.githubusercontent.com/4023037/121289129-2c3e0b00-c8ed-11eb-873e-fde0da8f781c.png)
And with new parser it's only text

**Comment by ankar84** [comment] 2021-06-09 09:35
Another issue - when you edit message, with new parser you need to reload app (CTRL+R) to get edited version of message
![new_parser1](https://user-images.githubusercontent.com/4023037/121330928-1c3f1f00-c91f-11eb-8e69-2e4a4f326b2c.gif)

**Comment by ankar84** [comment] 2021-07-20 10:21
Mention not open profile on click (click do nothing)
![mention01](https://user-images.githubusercontent.com/4023037/126308113-b88ecbd1-4593-43ec-af35-ccb6efd8ec68.gif)

**Comment by ggazzo** [comment] 2021-09-17 21:29
the first "bug" its not a bug, it was defined in the gramar
_italic message followed by some letter_A

I'm currently working to fix the others

**Comment by ggazzo** [comment] 2021-09-21 16:38
I will try to explain but its quite tricky , I know you want the previous behavior "working"

_but check t_his
_and this_
*and check t*his

the raw text: 
```
_but check t_his <--- your case
_and this_
*and check t*his
```
Looks the last case is what you are looking for, but Github fails on your specific case as well. Since we use `_` to delimit our italic and `*` to define bolds we dont have a smart way on your grammar to allow what you are asking for (without changing the whole meaning of each code).

Somehow "_" are considered "text" (its not only a markup character), Imagine a case, some slugfied conversion or whatever, and then we have this sentence "imagine_that im writing_something"  based on the previous behavior we would render "imagine*that im writing*something" that is odd and there no such way to prevent that.

I will try to consider you case, but to me the best choice would be interpret *  _ the same ways github does, but imagine how many people would complain about this change

**Comment by ankar84** [comment] 2022-01-11 05:22
> I'm currently working to fix the others

Hey, @ggazzo 
Thank you for your great job!

Now most important issue for us is [this](https://github.com/RocketChat/Rocket.Chat/issues/22280#issuecomment-857350715)
We have this settings in **Admin UI - Messages - Markdown**
![image](https://user-images.githubusercontent.com/4023037/148885604-e1448e4e-1564-4d89-9ac5-4cf809326bc5.png)

But with new parser `notes` and `e1s` protocols not parse as a links
![image](https://user-images.githubusercontent.com/4023037/148885772-5bed5fc5-1676-4bcc-9f1f-af9fdac6ad9b.png)
![image](https://user-images.githubusercontent.com/4023037/148885813-37d2ec6a-2abe-4013-9c32-6b4a0522d590.png)

@dudanogueira can you prioritize that to FE team, please?

**Comment by ankar84** [comment] 2022-01-19 02:42
@ggazzo What do you think maybe new parser ignores `Markdown Support Schemes List` parameter?

**Comment by ankar84** [comment] 2022-01-19 04:49
> Mention not open profile on click (click do nothing) ![mention01](https://user-images.githubusercontent.com/4023037/126308113-b88ecbd1-4593-43ec-af35-ccb6efd8ec68.gif)

That issue also still persist in most recent 4.3.1 version.
Old parser opens modal windows on click.

**Comment by ankar84** [comment] 2022-01-19 04:50
> Another issue - when you edit message, with new parser you need to reload app (CTRL+R) to get edited version of message ![new_parser1](https://user-images.githubusercontent.com/4023037/121330928-1c3f1f00-c91f-11eb-8e69-2e4a4f326b2c.gif)

And that issue not fixed in 4.3.1

**Comment by ankar84** [comment] 2022-01-19 04:50
> Another interesting issue with new parser - ascii emoji become graphic emoji and again transform in ascii ![new_parser](https://user-images.githubusercontent.com/4023037/121141676-e8db9200-c843-11eb-98ea-c2cd1fe3cb8f.gif)

And that one

**Comment by ankar84** [comment] 2022-01-19 07:50
Actually looks like new parser ignores lots of Admin UI - Message parameters
Another example
![image](https://user-images.githubusercontent.com/4023037/150086984-01103f3b-b717-4bba-afd4-4d724dea161e.png)
![image](https://user-images.githubusercontent.com/4023037/150087067-1788c5eb-e251-4a12-ab7d-e2e9d8ceffe7.png)

**Comment by franck-eyraud** [comment] 2022-02-21 10:11
Hello, I encountered an issue with this option, maybe you already know it.

I enabled it without knowing what it was supposed to do, and the result was that OTR sessions were not working for me. All the messages (even mine) were shown as encrypted. I spent some time to find out that it was due to this option enabled days ago and which I didn't notice what it was doing.

Is there a link where to understand what the new message parser is supposed to offer ?

Thank you

**Comment by ankar84** [comment] 2022-04-25 06:34
Guess [4.7 will totally remove](https://github.com/RocketChat/Rocket.Chat/releases/tag/4.7.0-rc.0) old (pretty) message parser and all that mentioned here issues are still not resolved in any way.
Here is a screen from early RC of 4.7
![image](https://user-images.githubusercontent.com/4023037/165032919-ce5a5613-0f26-485c-89fe-e9385eb411e1.png)
And here is a 4.6.3 screen
![image](https://user-images.githubusercontent.com/4023037/165032998-b8249c9c-9ffd-4ad0-9753-5b1221407073.png)
@ggazzo what to do with all new message parser issues? 
I critically need this feature in new parser https://github.com/RocketChat/Rocket.Chat/issues/22280#issuecomment-1009610000

**Comment by ggazzo** [comment] 2022-04-25 12:10
Well, we plan to keep the support for the old message for a while until the next major, meanwhile improve and solve some open issues related with parser, I cannot guarantee all the old behaviours will remain since some make no sense. B

**Comment by ankar84** [comment] 2022-04-26 05:00
Hey, Guilherme!
Thanks for a quick response!

> we plan to keep the support for the old message for a while until the next major

That is good. 
How can I enable it to my deployment since 4.7? As you san see since 4.7 there is no user option to enable old parser. There is an option for legacy messages instead.

> meanwhile improve and solve some open issues related with parser

That's totally what need to be done, thank you!
As a recall - most important for us is this issue https://github.com/RocketChat/Rocket.Chat/issues/22280#issuecomment-857350715


> I cannot guarantee all the old behaviours will remain since some make no sense

I understand that and agree with you!

**Comment by ankar84** [comment] 2022-09-06 09:46
Legacy template broken in 5.1.0 https://github.com/RocketChat/Rocket.Chat/issues/26801

**Comment by hugocostadev** [comment] 2022-10-13 13:58
The most important issues mentioned here were already fixed in the past releases, because of this I'm closing this issue.

If you find any other issues, please, create a separate issue to make it easier to track. Thank you so much!

**Closed by hugocostadev** 2022-10-13 13:58 UTC
Labels: subj: message rendering

**Comment by hugocostadev** [comment] 2022-10-13 15:57
> @hugocostadev how about that issue?
> https://github.com/RocketChat/Rocket.Chat/issues/22280#issuecomment-857350715

That issue it's fixed too, the new message parser is protocol agnostic :)

**Comment by ankar84** [comment] 2022-10-14 00:39
> > @hugocostadev how about that issue?
> > https://github.com/RocketChat/Rocket.Chat/issues/22280#issuecomment-857350715
> 
> That issue it's fixed too, the new message parser is protocol agnostic :)

Guess you didn't get the main point of that issue. Please read that actual whole issue to get it.

**Comment by hugocostadev** [comment] 2022-10-14 00:44
> > > @hugocostadev how about that issue?
> > > https://github.com/RocketChat/Rocket.Chat/issues/22280#issuecomment-857350715
> > 
> > That issue it's fixed too, the new message parser is protocol agnostic :)
> 
> Guess you didn't get the main point of that issue. Please read that actual whole issue to get it.

Sorry, I didn't realized that the path didn't have the URI structure. 

Could you open a separated issue for that please? Appreciate it.

I'll bring this issue internally and see if we can support it.

**Comment by ankar84** [comment] 2022-10-14 01:02
> > > > @hugocostadev how about that issue?
> > > > https://github.com/RocketChat/Rocket.Chat/issues/22280#issuecomment-857350715
> > > 
> > > That issue it's fixed too, the new message parser is protocol agnostic :)
> > 
> > Guess you didn't get the main point of that issue. Please read that actual whole issue to get it.
> 
> Sorry, I didn't realized that the path didn't have the URI structure. 
> 
> Could you open a separated issue for that please? Appreciate it.
> 
> I'll bring this issue internally and see if we can support it.

Sure! I will do it today, and leave here a link.
Thank you!!

**Comment by ankar84** [comment] 2022-10-14 01:17
Here it is @hugocostadev 
https://github.com/RocketChat/Rocket.Chat/issues/27065
I eill add some details in a few hours.
