### ISSUE TITLE
Cannot create any new direct channels using search

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#24819] opened 2022-03-14 06:37 UTC
### Description:

Creating new direct channels is not possible using the the search.

### Steps to reproduce:

1. Select search
2. Search for a user that does not have a direct channel with you
3. Select the user in search, by enter or mouse

### Expected behavior:

A new direct channel is initialized.

### Actual behavior:
![Screenshot from 2022-03-14 08-27-32](https://user-images.githubusercontent.com/6958942/158117576-13e7fefa-ebea-472b-8392-79454a82e7d6.png)

![Screenshot from 2022-03-14 08-27-58](https://user-images.githubusercontent.com/6958942/158117587-0b3315ad-70a7-4ba6-8722-6b257bc14070.png)

Instead of creating new direct channel you get error screen that tells you that `Room not found`.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.2
- Operating System: RHEL8
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: 14.18.3
- MongoDB Version: 4.2

### Client Setup Information

- Desktop App or Browser Version: Firefox and Chrome

### Additional context

You can still create new direct channels using Directory and choosing other users there.

**Comment by MightyGoldenOctopus** [comment] 2022-03-14 08:03
Can reproduce on our `4.5.2` docker compose community deployment, using MongoDB `4.2.17 / wiredTiger (oplog enabled)` and NodeJS `v14.18.3`.

**Comment by ankar84** [comment] 2022-03-14 09:44
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/24727 and plenty of issues here
But still in 4.5.2

**Comment by Gummikavalier** [comment] 2022-03-14 16:42
@ankar84 Thanks, I missed that one. Late to the 4.5.x. :+1:

**Closed** 2022-03-14 16:54 UTC
