### ISSUE TITLE
[BUG] Mention parsing doesn't work when ending with a dot (.)

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#10563] opened 2018-04-23 19:01 UTC
### Description:

Mentions aren't working when sending messages and the mention follows a ".".

It does affect the RealTime and REST APIs.

Example:

![img_0061](https://user-images.githubusercontent.com/551004/39147218-71432946-470f-11e8-8a72-931ed2c77043.jpg)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.0-rc1
* Operating System: Linux

**Comment by TwizzyDizzy** [comment] 2018-04-24 07:38
@rocket-cat close

Hi @rafaelks,

no offense, but your issue is a dupe of https://github.com/RocketChat/Rocket.Chat/issues/956 tuat already has some discussion in it, so I'm gonna close yours.

Cheers
Thomas

**Closed** 2018-04-24 07:38 UTC
Labels: type: bug
