### ISSUE TITLE
Enhancement : Any new chat should keep flashing on the left-hand side queue until it's picked up by an agent

### ISSUE THREAD

**Issue by nitinsonawane234** [RocketChat/Rocket.Chat#33456] opened 2024-10-04 10:24 UTC
New Chat Flashing:
Any new chat should keep flashing on the left-hand side queue until it's picked up by an agent.

**Comment by reetp** [comment] 2024-10-04 12:55
Closing as this is not a bug in Rocket.Chat

Please open in the correct repository

https://github.com/RocketChat/feature-requests

**Closed by reetp** 2024-10-04 12:55 UTC
