### ISSUE TITLE
Hash in Links doesn't work

### ISSUE THREAD

**Issue by jschirrmacher** [RocketChat/Rocket.Chat#27397] opened 2022-11-29 06:54 UTC
### Description:

Links containing hashes ignore hashes.

### Steps to reproduce:

Write a message like

    [Doesn't work](http://example.com#foo)

### Expected behavior:

A link should be generated, containing the complete URL `http://example.com#foo`

### Actual behavior:

A link is generated, but the hash is missing: `http://example.com`

**Comment by joeshajan** [comment] 2022-11-29 09:01
Hey, @jschirrmacher I would like to fix this can you assign this to me?

**Comment by jschirrmacher** [comment] 2022-11-29 09:35
@joeshajan That's great, but I cannot assign you because I'm no maintainer.

**Comment by jschirrmacher** [comment] 2022-11-29 09:37
It seems, that ":" is also removed from URLs. They are used in paths of links e.g. links from Sharepoint. ":" are normally allowed in URL paths.

**Comment by joeshajan** [comment] 2022-11-29 10:05
So where do you face this issue

**Comment by dudanogueira** [comment] 2022-11-29 13:09
Hi, Thanks for opening this issue!

it's ideal to always provide the information required on the template, as this helps us to reproduce the issue.

I pasted:

`[Doesn't work](http://example.com#foo)`

in release candidate 5.4.0.rc1 and in 4.8.1 and was not able to reproduce it.

Closing for now.

**Closed by dudanogueira** 2022-11-29 13:09 UTC
