### ISSUE TITLE
GDPR - Userdata zip-file is missing

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#11116] opened 2018-06-13 06:49 UTC
### Description:

Since the addition of the new gdpr features - I find several log lines in my RC logs where the user zip file could not be found.

### Steps to reproduce:

1. Try to generate a zip-file of your data as a user

### Expected behavior:

The zip-files should be generated.

### Actual behavior:

2018-06-13T06:35:07.317730869Z { Error: ENOENT: no such file or directory, stat '/tmp/zipFiles/ebgowS4756TJRnm941.zip'
2018-06-13T06:35:07.317812540Z
2018-06-13T06:35:07.317820724Z
2018-06-13T06:35:07.317826388Z   errno: -2,
2018-06-13T06:35:07.317831605Z   code: 'ENOENT',
2018-06-13T06:35:07.317836068Z   syscall: 'stat',
2018-06-13T06:35:07.317840566Z   path: '/tmp/zipFiles/ebgowS4756TJRnm941.zip' }

### Server Setup Information:

- Version of Rocket.Chat Server:  0.65.1
- Operating System: Ubuntu Server 16.04 LTS
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: YES
- MongoDB Version: 3.6.3

### More Logs

Ahh, if I try to generate it (if I click in the Interface "please generate the zip-file.."

It logs this:

2018-06-13T06:45:00.329787566Z { Error: ENOENT: no such file or directory, mkdir '/tmp/userData/ebgowS4756TJRnm941/partial'
2018-06-13T06:45:00.329909295Z     at Object.fs.mkdirSync (fs.js:885:18)
2018-06-13T06:45:00.329954153Z     at createDir (/app/bundle/programs/server/packages/rocketchat_user-data-download.js:109:8)
2018-06-13T06:45:00.329965606Z     at continueExportingRoom (/app/bundle/programs/server/packages/rocketchat_user-data-download.js:259:3)
2018-06-13T06:45:00.329974417Z     at exportOperation.roomList.forEach.exportOpRoomData (/app/bundle/programs/server/packages/rocketchat_user-data-download.js:497:9)
2018-06-13T06:45:00.329995083Z     at Array.forEach (<anonymous>:null:null)
2018-06-13T06:45:00.330007350Z     at continueExportOperation (/app/bundle/programs/server/packages/rocketchat_user-data-download.js:496:32)
2018-06-13T06:45:00.330012157Z     at cursor.forEach.exportOperation (/app/bundle/programs/server/packages/rocketchat_user-data-download.js:544:5)
2018-06-13T06:45:00.330039433Z     at SynchronousCursor.forEach (/app/bundle/programs/server/packages/mongo.js:1060:16)
2018-06-13T06:45:00.330044124Z     at Cursor.(anonymous function) [as forEach] (/app/bundle/programs/server/packages/mongo.js:902:44)
2018-06-13T06:45:00.330048500Z     at Object.processDataDownloads [as job] (/app/bundle/programs/server/packages/rocketchat_user-data-download.js:539:10)
2018-06-13T06:45:00.330052937Z     at packages/percolate_synced-cron.js:242:26
2018-06-13T06:45:00.330057073Z     at scheduleTimeout (packages/percolate_synced-cron.js:290:7)
2018-06-13T06:45:00.330062921Z     at packages/percolate_synced-cron.js:338:42
2018-06-13T06:45:00.330069028Z     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:12)
2018-06-13T06:45:00.330073191Z     at packages/meteor.js:502:25
2018-06-13T06:45:00.330077097Z     at runWithEnvironment (packages/meteor.js:1238:24)
2018-06-13T06:45:00.330081060Z
2018-06-13T06:45:00.330087913Z   errno: -2,
2018-06-13T06:45:00.330121143Z   code: 'ENOENT',
2018-06-13T06:45:00.330134206Z   syscall: 'mkdir',
2018-06-13T06:45:00.330138961Z   path: '/tmp/userData/ebgowS4756TJRnm941/partial' }

**Comment by TwizzyDizzy** [comment] 2018-06-13 07:49
Closing this, as it is a duplicate of #11082.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-06-13 07:49 UTC
Labels: duplicate
