### ISSUE TITLE
Emoticons not displayed in room topic

### ISSUE THREAD

**Issue by tsr-caubry** [RocketChat/Rocket.Chat#12696] opened 2018-11-22 08:44 UTC
Emoticons are not displayed in rooms topic when used, only the name or alias surrounded by period is displayed.

**Comment by reetp** [comment] 2018-11-22 17:41
Can you go back and fill in this template properly.
https://github.com/RocketChat/Rocket.Chat/issues/new?template

 https://rocket.chat/docs/contributing/reporting-issues

**Comment by tsr-caubry** [comment] 2018-11-23 09:05
### Description:

Emoticons are not rendered as image on room topic field in the room header instead the emoticon name or alias is displayed surrounded by period (problem seems occur in Description and Announcement too)

### Steps to reproduce:

Select a room and click on "Room Info"
Select "Topic" field and start typing text
Add some emoticons by calling theme with their name or alias (":police_car:")
Click on save and close the "Room Panel"

### Expected behavior:

Emoticons rendered as image in the room header.

### Actual behavior:

Emoticons rendered as text.

![image](https://user-images.githubusercontent.com/44467383/48935109-bf1d2280-ef06-11e8-95a5-e46325e5acb1.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: CentOS 7
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: no
- NodeJS Version: 8.11.3
- MongoDB Version: 3.6.7

### Additional context

### Relevant logs:

**Comment by sampaiodiego** [comment] 2019-01-02 12:48
closing as duplicate of https://github.com/RocketChat/Rocket.Chat/issues/6305

**Closed by sampaiodiego** 2019-01-02 12:48 UTC
Labels: Feature: Request, contrib: easy, subj: ui/ux
