### ISSUE TITLE
0.68 snap release

### ISSUE THREAD

**Issue by ccfiel** [RocketChat/Rocket.Chat#11720] opened 2018-08-09 01:59 UTC
Any plans to push the last update to snap? Seems the update has been out for 10 days now and snap is still on 0.66

**Comment by tuxmartin** [comment] 2018-08-09 07:15
:+1:

**Comment by TheReal1604** [comment] 2018-08-09 13:42
@geekgonecrazy is probably the right man for this.

**Comment by kaiiiiiiiii** [comment] 2018-08-09 14:29
Please see #11540. @geekgonecrazy explained why snaps are not up-to-date in this issue.

**Comment by tassoevan** [comment] 2018-08-09 17:32
Duplicate of #11594.

**Closed by tassoevan** 2018-08-09 17:33 UTC

**Comment by Droner147** [comment] 2018-08-15 12:10
Any plans to push the last update to snap till version 0.68.4?

**Comment by geekgonecrazy** [comment] 2018-08-15 19:57
Feel free to stay tuned in #ubuntu-snap on open.rocket.chat
