### ISSUE TITLE
error-invalid-room error when user open DM with deactivated user

### ISSUE THREAD

**Issue by ankar84** [RocketChat/Rocket.Chat#24146] opened 2022-01-12 01:34 UTC
### Description:

When user open DM with deactivated user (from chat history for example) then `error-invalid-room` error appears in Rocket Chat logs

Root cause of that issue is https://github.com/RocketChat/Rocket.Chat/issues/21237
I believe that user shouldn't have ability to start DM with disabled user with some warning like `That user is deactivated, you can't DM with him` or at least team must return previous behavior - DM room with deactivated user simply should be read only for users.

### Steps to reproduce:

1. Go to chat with deactivated user
2. Click on deactivated user and choose Start conversation button
3. Full feature DM with deactivated user is started
4. `error-invalid-room` error appears in logs

### Expected behavior:

I believe that user shouldn't have ability to start DM with disabled user with some warning like `That user is deactivated, you can't DM with him` or at least team must return previous behavior - DM room with deactivated user simply should be read only for users.

### Actual behavior:

Full feature DM with deactivated user is started - users write messages to ghosts and don't know about that

### Server Setup Information:

- Version of Rocket.Chat Server: 4.2.2
- Operating System: CentOS7
- Deployment Method: docker
- Number of Running Instances: 20
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.4.11

### Client Setup Information

- Desktop App or Browser Version: 3.5.7
- Operating System: Windows 10

### Additional context

Other related issue https://github.com/RocketChat/Rocket.Chat/issues/21869

### Relevant logs:

`{"level":50,"time":"2022-01-12T01:21:33.911Z","pid":9,"hostname":"d7e073bc5698","name":"System","msg":"Exception while invoking method getRoomByTypeAndName 'Invalid room [error-invalid-room]'"}`

**Comment by varunbankar** [comment] 2022-01-12 10:23
I'd like to work on this issue!

**Comment by ArchitJain1201** [comment] 2022-01-12 13:21
@ankar84 Can you please assign me this issue

**Comment by ankar84** [comment] 2022-01-12 13:43
> @ankar84 Can you please assign me this issue
> 

I'm not a dev team member.
Let's ask @dudanogueira and @debdutdeb

**Comment by ArchitJain1201** [comment] 2022-01-12 13:53
@dudanogueira @debdutdeb Can you please assign me this issue?

**Comment by debdutdeb** [comment] 2022-01-12 14:26
@ArchitJain1201 thanks for showinng interest, but, please read [this])(https://open.rocket.chat/channel/how-to-get-started?msg=XyExC9Fvn3ByQD49a before moving forward :)

**Comment by wilsonfurtado2000** [comment] 2022-01-15 07:15
> 
do u mean blocked users ??

**Comment by ankar84** [comment] 2022-01-15 14:34
> > 
> do u mean blocked users ?? 

Exactly. But in Rocket Chat terminology it called deactivated.

**Comment by debdutdeb** [comment] 2022-01-15 14:45
I previously brought this up internally, I'll see if I caj find the thread again. 

Fwiw the mobile app handles it nicely by showing the room as "read only".

**Comment by debdutdeb** [comment] 2022-01-15 14:48
> > > 
> > 
> > 
> > do u mean blocked users ??
> 
> Exactly. But in Rocket Chat terminology it called deactivated.

Blocked and deactivated are different things 😬 but some indication for both would be good additions.

**Comment by ankar84** [comment] 2022-01-15 15:18
> > > > 
> > > 
> > > 
> > > do u mean blocked users ??
> > 
> > Exactly. But in Rocket Chat terminology it called deactivated.
> 
> Blocked and deactivated are different things 😬 but some indication for both would be good additions.

Yeap. My bad!
User deactivated by admin can't connect whole server.
User can block DM of other user and that blocked user can't write in that DM.

**Comment by sidmohanty11** [comment] 2022-01-20 15:45
hi @ankar84 , I tried to find out the root cause of this and it seems like `_id: 'post-readonly', roles: ['admin', 'owner', 'moderator']`, due to this permission, an admin / owner / moderator can still chat with the deactivated user but not other users.

As you can see here,
**In case of admin:**
![deactivate-admin](https://user-images.githubusercontent.com/73601258/150371861-efddaa7d-6f92-4f0e-a224-608e78eb4a66.png)

**In case of any other user:**
![deactivate-user](https://user-images.githubusercontent.com/73601258/150371902-d1551322-dab8-43f0-9477-1fff55a76756.png)

Can you check?

**Comment by ankar84** [comment] 2022-01-21 05:01
> Can you check?

Guess you are right!
![image](https://user-images.githubusercontent.com/4023037/150468939-3b8d82c4-14ff-4d2d-a81e-3ba24cf82238.png)

**Comment by dudanogueira** [comment] 2022-10-18 18:20
closing, if needed, please, repoen :)

**Closed by dudanogueira** 2022-10-18 18:20 UTC
Labels: contrib: good first issue, bug
