### ISSUE TITLE
Livechat rooms cannot be opened

### ISSUE THREAD

**Issue by internalfx** [RocketChat/Rocket.Chat#8851] opened 2017-11-13 17:58 UTC
### Description:

Livechat rooms cannot be opened

### Server Setup Information:

➔ System ➔ startup
➔ +--------------------------------------------------------+
➔ |                     SERVER RUNNING                     |
➔ +--------------------------------------------------------+
➔ |                                                        |
➔ |  Rocket.Chat Version: 0.59.3                           |
➔ |       NodeJS Version: 4.6.2 - x64                      |
➔ |             Platform: linux                            |
➔ |         Process Port: 3000                             |
➔ |             Site URL: ******************  |
➔ |     ReplicaSet OpLog: Disabled                         |
➔ |          Commit Hash: 21c4efa08a                       |
➔ |        Commit Branch: HEAD                             |
➔ |                                                        |
➔ +--------------------------------------------------------+

### Relevant logs:
Invalid streamRoom eventName: "odXmcLcHQffZf66sM/deleteMessage"
Invalid streamRoom eventName: "jZmDjZjjeQEgiZn8x/deleteMessage"
Invalid streamRoom eventName: "jZmDjZjjeQEgiZn8x/deleteMessage"
Invalid streamRoom eventName: "as8yr99iSXWCbuwQM/deleteMessage"
Exception while invoking method 'sendMessage' TypeError: Cannot read property 'blocker' of undefined
  at [object Object].Meteor.methods.sendMessage (/home/sysadmin/rocketchat/programs/server/packages/rocketchat_lib.js:15629:59)
  at [object Object].methodsMap.(anonymous function) (/home/sysadmin/rocketchat/programs/server/packages/rocketchat_lib.js:1276:26)
  at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at maybeAuditArgumentChecks (/home/sysadmin/rocketchat/programs/server/packages/ddp-server.js:1857:12)
  at /home/sysadmin/rocketchat/programs/server/packages/ddp-server.js:903:20
  at [object Object].EVp.withValue (packages/meteor.js:1134:15)
  at /home/sysadmin/rocketchat/programs/server/packages/ddp-server.js:902:47
  at [object Object].EVp.withValue (packages/meteor.js:1134:15)
  at /home/sysadmin/rocketchat/programs/server/packages/ddp-server.js:901:46
  at [object Object]._.extend.protocol_handlers.method (/home/sysadmin/rocketchat/programs/server/packages/ddp-server.js:874:21)
  at /home/sysadmin/rocketchat/programs/server/packages/ddp-server.js:753:85

**Comment by MartinSchoeler** [comment] 2017-11-14 12:40
Duplicate of #8773

**Closed by MartinSchoeler** 2017-11-14 12:40 UTC
