### ISSUE TITLE
Can't upload ovpn file

### ISSUE THREAD

**Issue by emoxam** [RocketChat/Rocket.Chat#31692] opened 2024-02-08 08:30 UTC
Can't send ovpn file
### Steps to reproduce:

1. try to send ovpn file
2. see "media types not accepted"

### Expected behavior:

i can send it as it was before.

### Actual behavior:

"media types not accepted" error

### Server Setup Information:

- Version of Rocket.Chat Server:  installed:          6.6.0             (1602) 361MB -
- Operating System:  ubuntu 
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: 3.9.12
- Operating System: Windows

**Comment by dolohow** [comment] 2024-02-14 10:19
Same problem here with 6.6.0, can't send gpg files and in admin settings I am not blocking any file type. In previous version (6.5.x) it did work.

**Comment by IgorOhrimenko** [comment] 2024-02-16 09:19
Not only ovpn file does not upload. You can try create emty file with name `1` and gave the same problem "Media Type Not Accepted:"

**Comment by roman-bergman** [comment] 2024-02-27 09:49
I got the following mimetype for *.ovpn: text/plain.
I added this mimetype to "Accepted Media Types" but i get the same error: "media types not accepted".

See my comment https://github.com/RocketChat/Rocket.Chat/pull/31346#issuecomment-1966163365

**Comment by IvanBadikovJoyrun** [comment] 2024-02-27 15:40
Check `mimeTypes.ts` in the `app/utils/lib`. 

The extension of your file is not defined in the [mime-db](https://www.npmjs.com/package/mime-db?activeTab=code) repo, so the type of your file should become undefined during lookup in the `app/client/views/room/body/hooks/useFileUploadDropTarget.ts` file line 57. 

I guess you should define your own type in the `mimeTypes.ts` in `app/utils/lib` in order to make it work.

**Comment by emoxam** [comment] 2024-02-29 08:14
How to define it ?

**Comment by roman-bergman** [comment] 2024-02-29 09:08
> Перевірте `mimeTypes.ts`в `app/utils/lib`.
> 
> Розширення вашого файлу не визначено в [ репозиторії mime-db ](https://www.npmjs.com/package/mime-db?activeTab=code) , тому тип вашого файлу має стати невизначеним під час пошуку в `app/client/views/room/body/hooks/useFileUploadDropTarget.ts`рядок файлу 57.
> 
> Я думаю, вам слід визначити свій власний тип у `mimeTypes.ts`в `app/utils/lib`щоб це працювало.
mime type ovpn file is text/plain. Mime-db have next extensions: "txt","text","conf","def","list","log","in","ini"
![Screenshot from 2024-02-29 11-05-23](https://github.com/RocketChat/Rocket.Chat/assets/89276354/eabda8c2-a3f5-4b80-83c8-130332831c1d)
It seems to me that the check goes not only on the ьшьуензу but also on its extension. If i change extension .ovpn to .txt my file is load to rocketchat.
![Screenshot from 2024-02-29 11-07-59](https://github.com/RocketChat/Rocket.Chat/assets/89276354/b6a1c1e0-159b-4e81-a036-83af7fd7878d)

**Comment by emoxam** [comment] 2024-02-29 09:28
Ok, can we make changes at the mime db ?

**Comment by emoxam** [comment] 2024-02-29 12:56
> Not only ovpn file does not upload. You can try to create the empty file with name `1` and gave the same problem "Media Type Not Accepted:"

Can you send ovpn file via web interface ?

**Comment by roman-bergman** [comment] 2024-02-29 13:47
> > Not only ovpn file does not upload. You can try to create the empty file with name `1` and gave the same problem "Media Type Not Accepted:"
> 
> Can you send ovpn file via web interface ?

only if rename file from .ovpn to .txt

**Comment by IvanBadikovJoyrun** [comment] 2024-02-29 15:20
> > Check mimeTypes.ts in the app/utils/lib.
> > The extension of your file is not defined in the [mime-db](https://www.npmjs.com/package/mime-db?activeTab=code) repo, so the type of your file should become undefined during lookup in the app/client/views/room/body/hooks/useFileUploadDropTarget.ts file line 57.
> > I guess you should define your own type in the mimeTypes.ts in app/utils/lib in order to make it work.
> 
> mime type ovpn file is text/plain. Mime-db have next extensions: "txt","text","conf","def","list","log","in","ini" ![Screenshot from 2024-02-29 11-05-23](https://private-user-images.githubusercontent.com/89276354/308862334-eabda8c2-a3f5-4b80-83c8-130332831c1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTk3MjcsIm5iZiI6MTcwOTIxOTQyNywicGF0aCI6Ii84OTI3NjM1NC8zMDg4NjIzMzQtZWFiZGE4YzItYTNmNS00YjgwLTgzYzgtMTMwMzMyODMxYzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE1MTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMTA1NjlmY2MzMjNhNTliNzg5ZTZjYzA4YTgxYmVlODhhYTcyYWEwM2MwN2EwYmI4ZGJjZmM0OWZmN2RmODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.43fmEMgveGbPEIpqCZoDb-2J6zHjB_DtfzjKtM4fRMw) It seems to me that the check goes not only on the mimetype but also on its extension. If i change extension .ovpn to .txt my file is load to rocketchat. ![Screenshot from 2024-02-29 11-07-59](https://private-user-images.githubusercontent.com/89276354/308863124-b6a1c1e0-159b-4e81-a036-83af7fd7878d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTk3MjcsIm5iZiI6MTcwOTIxOTQyNywicGF0aCI6Ii84OTI3NjM1NC8zMDg4NjMxMjQtYjZhMWMxZTAtMTU5Yi00ZTgxLWEwMzYtODNhZjdmZDc4NzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE1MTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NWRkZWYwNTU4OWZkYmNlNGRhYjdhNjhkZjA5ZTkzODgyNGM1YWNjOGNhZTQ1ZWNlN2E2NzA4OWVhYjk0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LSg04sgrNuua_vi77VRjjFmSFri9ttfgz6qmmkIlCBE)

I guess, it throws a media type alert due to extension check, as type is left undefined since checking if there's no such extension in the mime-db. So, in order to allow the media type, there are two ways to upload files that don't consume mime-db:
* Append allowed extension and require the receiver to rename the file 
* Modify mime-db or define it directly in the sources
* Pack the file into a zip-archive... I prefer this way personally :)) 

![image](https://github.com/RocketChat/Rocket.Chat/assets/88749136/03361785-d8d8-4a19-93a0-0e2b015944fa)

**Comment by IvanBadikovJoyrun** [comment] 2024-02-29 15:27
> Not only ovpn file does not upload. You can try to create the empty file with name `1` and gave the same problem "Media Type Not Accepted:"

It's because the file does not pass the extension check as the extension is not defined in the mime-db. The error occurs on the Rocket.Chat frontend side. You can check my first answer.

**Comment by emoxam** [comment] 2024-03-01 14:10
Then - I did unsquashfs rocketchat-server_1603.snap
added ovpn to
```
/home/gsys/222/squashfs-root/programs/server/npm/node_modules/mime-db/db.json
/home/gsys/222/squashfs-root/programs/web.browser/dynamic/node_modules/mime-db/db.json
/home/gsys/222/squashfs-root/programs/web.browser.legacy/dynamic/node_modules/mime-db/db.json
```
and then 
mksquashfs squashfs-root rocketchat-server_1603.snap -noappend -comp lzo -no-fragments
somehow i can send ovpn via the web, but now via the windows desktop app...

**Comment by Thanush19** [comment] 2024-03-13 08:09
@emoxam  ,if the issue is not resolved yet , i can work on this...

**Comment by emoxam** [comment] 2024-03-13 08:12
> @emoxam ,if the issue is not resolved yet , i can work on this...

I will be very appreciate this!

**Comment by Thanush19** [comment] 2024-03-13 08:52
can u assign it to me.. @emoxam ...

**Comment by emoxam** [comment] 2024-03-13 09:33
@Thanush19 I  am an ordinary user, i don't have such rights. Or i just don't know how ?

**Comment by crose-project** [comment] 2024-04-22 10:39
We have the same problems with .py, .drawio, .r and .rmd files in RocketChat App and Browser. None of the named have official MIME types assigned (as far as I know). I my experience as a web developer: relying on MIME types creates a lot of headaches. Finally, we check for MIME types (where possible) and if this fails, we check for filename extensions.

**Closed** 2024-06-14 11:09 UTC
