### ISSUE TITLE
More Unreads indicator should be clickable

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#18958] opened 2020-09-18 19:27 UTC
### Description:

When having a large list of DMs, a message may be received from one of the users that are not currently in the scroll area. When this happens, an indicator (which looks like a button) shows up, saying "More Unreads":

![image](https://user-images.githubusercontent.com/14616851/93636074-e46f0080-f9b8-11ea-828e-1e1a76a4948a.png)

This item should probably be clickable, and cause the DM list to scroll to the user that has the unread message (latest one, if multiple). Currently, one has to manually scroll the DM list to find the unread message.

### Steps to reproduce:

1. Have a list of DMs longer than the height of the window.
2. Have one of the users at the bottom of your DM list send you a message.
3. The "More Unreads" notice will appear.
4. You might try to click it to go to the unreads, but it is not clickable.
5. You have to scroll down the DM list to see the unread DM.

### Expected behavior:

"More Unreads" should be clickable, and should scroll down to the last unread DM.

### Actual behavior:

You have to scroll down manually to see the DM. This is cumbersome with large lists.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.0-develop
- Operating System: Ubuntu 20.04 (docker)
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version:  v12.18.3
- MongoDB Version: 4.0.20

**Comment by wreiske** [comment] 2020-09-18 19:37
https://github.com/RocketChat/feature-requests/issues/384

**Comment by bkraul** [comment] 2020-09-18 20:33
Excellent. I have implemented the workaround, and it works as expected. It'll have to do until a proper fix is done. So, I suppose this needs to be closed in lieu of the feature request?

**Comment by MartinSchoeler** [comment] 2020-09-30 18:39
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/18958

**Closed by MartinSchoeler** 2020-09-30 18:39 UTC
Labels: subj: ui/ux, type: improvement

**Comment by bkraul** [comment] 2020-09-30 18:41
Hmmmm...the "duplicate of" and this issue are exactly the same....

**Comment by MartinSchoeler** [comment] 2020-09-30 19:34
Oops, my bad 😁 Fixed the comment
