### ISSUE TITLE
Changing the progress/loading logo

### ISSUE THREAD

**Issue by capensisma** [RocketChat/Rocket.Chat#1634] opened 2015-12-11 06:53 UTC
Hi

Can we have an option to change the progress/loading logo in the settings please? just one field for it! pretty simple?

If not possible Can I know were is it stored ? the absolute path?

Thanks a lot

**Comment by capensisma** [comment] 2015-12-11 16:21
Ok got it!

You can change the loading logo from `<template name="loading">` which is in RocketChat ui master package it's an SVG logo which is cool :)

**Comment by engelgabriel** [comment] 2015-12-21 19:58
But we should have an upload field on the admin for people to overwrite it without having to touch the source code.

**Comment by engelgabriel** [comment] 2016-02-22 23:08
This is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/613

**Closed by engelgabriel** 2016-02-22 23:08 UTC
Labels: feat: app settings, subj: ui/ux, type: new feature
