### ISSUE TITLE
Media Type Not Accepted

### ISSUE THREAD

**Issue by DustpaN-Spb** [RocketChat/Rocket.Chat#31906] opened 2024-03-06 06:51 UTC
Look like a last change is a error
Because
Was:				invalidContentType: Boolean(file.type && !fileUploadIsValidContentType(file.type)),
Now:			invalidContentType: !(file.type && fileUploadIsValidContentType(file.type)),
If we can't detrminate a MIME type of a file (file.type) it will return a false and all not recognised types will be not work at all even if "Accepted Media Types" is empty.
Please revert
https://forums.rocket.chat/t/cant-upload-ovpn-file/19455

_Originally posted by @DustpaN-Spb in https://github.com/RocketChat/Rocket.Chat/issues/31346#issuecomment-1975862098_

**Comment by Visbhavesh** [comment] 2024-03-22 05:37
I wanted to work in thus issue please Assign this issue to me.

**Comment by DustpaN-Spb** [comment] 2024-03-25 06:56
I do not have a permissions to assign a issue.
Who can do it?

**Comment by richardturnerfos** [comment] 2024-04-02 23:56
I don't understand why more people aren't complaining. All sort of files are being rejected suddenly and we have no way of allowing them.

**Comment by ggazzo** [comment] 2024-04-15 13:12
Considering security, if we cannot identify the mime type, I believe we should block it, otherwise this validation is useless. Don't you agree?


feel free to work on a proposal, there is no need to sign anyone for this, however I believe that simply inverting the boolean is not a safe option

**Comment by DustpaN-Spb** [comment] 2024-04-15 15:49
If a user can't send a file in a custom format because the file doesn't have a mime type, it doesn't look right.
If the "Accepted Media Types" in the admin panel is empty, I think the user should be able to send any file and it is not security related.

**Comment by unwnstr** [comment] 2024-04-16 05:26
> Considering security, if we cannot identify the mime type, I believe we should block it, otherwise this validation is useless. Don't you agree?
> 
> feel free to work on a proposal, there is no need to sign anyone for this, however I believe that simply inverting the boolean is not a safe option

This is purely client only file type check. User can just edit js code in f12 browser debugger and remove file type check. So there is no security anyway.
But when your team is working with CAD files, or some code, it is really annoying to rename file extension every time you need to upload it.

**Comment by reetp** [comment] 2024-04-22 14:55
> Considering security, if we cannot identify the mime type, I believe we should block it, otherwise this validation is useless. Don't you agree?

Nope, I don't unless RocketChat can validate correctly, which it does not appear to do. Mime detection seems broken.

Desktop test:

`xdg-mime query filetype  OVPN_John.ovpn`

text/plain

Upload to Rocket:

> Media Type not accepted

If I rename it to OVPN_John.ovpn.txt it fools the MIME checks completely making it look pretty stupid - but it's worse than useless because then it won't OPEN correctly into the OpenVPN app.

Mime types:

text/plain,image/*,audio/*,video/*,application/csv,text/csv,application/zip,application/x-rar-compressed,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text,application/vnd.oasis.opendocument.spreadsheet,application/vnd.oasis.opendocument.presentation

qv 
https://github.com/RocketChat/Rocket.Chat/issues/31692

That means the type should be identified and permitted, but *Rocket* can't do it. Is that admins fault? Is that a reason to block it?

Rocket itself becomes useless if you need to upload files that can't be detected.....

It does quite clearly say in 6.6.6 

"Leave it blank for accepting all media types."

But that doesn't work. 

If Rocket can't can't detect mime types properly - which it clearly cannot - then it should not block them for those who need to upload them.

Rocketchat champions 'security' but is forcing users to send plain text ovpn files with embedded certificates  via Whatsapp, or email. Great.

This should be changed to 'Fix', and re-thought.

**Comment by BitMonster1010** [comment] 2024-04-28 12:22
I just had this issue as well, and it seems very stupid that even though I have set it to allow all MIME types, if it doesn't recognize the MIME type it won't allow it and I can't change that setting from anywhere.
Running on Rocket Chat 6.7.1
I'm trying to upload a filename.sample file to give to someone, which is actually just a JSON file, but I'm just getting this error and it's just annoying. Ended up uploading it on our Nextcloud instance because of this.

**Comment by BitMonster1010** [comment] 2024-04-28 12:22
> Considering security, if we cannot identify the mime type, I believe we should block it, otherwise this validation is useless. Don't you agree?
> 
> feel free to work on a proposal, there is no need to sign anyone for this, however I believe that simply inverting the boolean is not a safe option

It would be useless if I wanted it enabled on my instance to do that. But I don't want this enabled on the instance, I want it to allow unknown MIME types as well.

**Comment by awillenbuecher-xq-tec** [comment] 2024-05-17 06:22
> Considering security, if we cannot identify the mime type, I believe we should block it, otherwise this validation is useless. Don't you agree?
> 
> feel free to work on a proposal, there is no need to sign anyone for this, however I believe that simply inverting the boolean is not a safe option

This doesn't make any sense at all. Not only can this "security" check be trivially disabled using the browser's developer console, it can also be fooled by simply renaming the file to `*.txt` before uploading it. You can even restore the extension in the **File Upload** dialog!

![image](https://github.com/RocketChat/Rocket.Chat/assets/102217656/ccc052e9-fb18-45ab-a44d-0ce8a222d874)

![image](https://github.com/RocketChat/Rocket.Chat/assets/102217656/bbcbc681-3650-4084-8e46-cdf369739886)

Please re-open this issue. It's a real bug, it doesn't add any security, and it's just annoying.

**Comment by hugocostadev** [comment] 2024-05-22 15:19
Hey guys, I understand the points raised here... 

If we guarantee that all file uploads are accepted when the field is empty, does that fix the issue?

**Comment by D34DC3N73R** [comment] 2024-05-22 15:33
> Hey guys, I understand the points raised here...
> 
> If we guarantee that all file uploads are accepted when the field is empty, does that fix the issue?

It would definitely be better than the current state. MIME type detection can always be improved upon in a later PR. But in the meantime, it would fix the issue of not being able to upload unrecognized MIME types when no restrictions are set.

**Comment by ggazzo** [comment] 2024-05-22 16:36
I was reviewing the whole thread, and I made a mistake:
if the extension list is empty, it really doesn’t matter if the browser can detect the extension or not, it should not prevent the submission because the admin mentioned that “they don’t care.”

However, if there is a list and the browser cannot detect it, I’m not sure what should happen. Maybe we should allow the submission and perform some validation on the server that checks the bytes or some other type of information.
This worsens the user experience a bit, but sometimes there is nothing that can be done.

The number of MIME types can be infinite, so maybe something via the app engine where you can install the mechanism would be the case.

**Comment by richardturnerfos** [comment] 2024-05-22 19:40
> Hey guys, I understand the points raised here...
> 
> If we guarantee that all file uploads are accepted when the field is empty, does that fix the issue?

That would be fantastic, and fit with the configuration message: "Leave it blank for accepting all media types." If a MIME type manager was available, we could have added in unhandled extensions but the issue is that we're completely stuffed if unknown mime types are rejected.

**Comment by tassoevan** [comment] 2024-05-23 15:24
@ggazzo 

> if there is a list and the browser cannot detect it, I’m not sure what should happen

If understand correctly, most of the complaints here work under the assumption that the MIME detection is made on the server, which is not true today. Browser/client-side detection is implementation/system-dependent (as we know, the same goes with pasted and drag-n-dropped content) and it's necessary to respect it when it comes to the end user configuration (e.g. we should show a video preview if the browser have needed codecs available). If the user tries to override the MIME type of a malicious file, the best we can do is to force the file extension to NOT be renamed (in opposition to what @awillenbuecher-xq-tec had commented is our current scenario).

However, heavier security measures should be applicable with some kind of server security extensions, like Rocket.Chat apps, due to the overhead (and the legal implications) of performing heuristic checks on the file contents to determine a "real MIME type". IMHO _Accepted Media Files_ should not be understood as a security feature, but as content moderation.

**Closed** 2024-06-14 11:09 UTC
