### ISSUE TITLE
Cannot find module @bugsnap/js

### ISSUE THREAD

**Issue by 0x1ad2** [RocketChat/Rocket.Chat#15149] opened 2019-08-09 07:45 UTC
### Description:

When updating the MacOS client to the latest version of Rocket chat (1.3.1) it will prompt an error when re-opening the client.

### Steps to reproduce:

1. Update Rocket Chat MacOS client to 1.3.1
2. Restart

### Expected behavior:

The application will open itself.

### Actual behavior:

<img width="532" alt="Screenshot 2019-08-09 at 09 21 14" src="https://user-images.githubusercontent.com/1705904/62762760-2a555780-ba8a-11e9-95cd-7b0a591a83bd.png">

**Comment by vgrossmann** [comment] 2019-08-09 07:49
Same error with a fresh install of 2.15.4 on Windows

**Comment by RobertDeniszczyc** [comment] 2019-08-09 08:17
Same error on OSX 10.12.3

**Comment by reetp** [comment] 2019-08-09 08:30
@rocket-cat close

Looks like a duplicate of

https://github.com/RocketChat/Rocket.Chat.Electron/issues/1288

**Closed by reetp** 2019-08-09 08:30 UTC

**Comment by reetp** [comment] 2019-08-09 09:27
@rocket-cat label add duplicate

Duplicate of RocketChat/Rocket.Chat.Electron#1288
