### ISSUE TITLE
Messages received via an incoming webhook are displayed out of order

### ISSUE THREAD

**Issue by saqura** [RocketChat/Rocket.Chat#2111] opened 2016-02-02 23:09 UTC
When sending messages using an incoming webhook to a Rocket.Chat-channel (with a messaging gateway, for example), the messages are displayed out of order. New messages are appended somewhere on the top. This only seems to happen when the payload contains an _attachments_-item, like this:

```
payload = {
    "attachments": [{
        "title": "some title",
        "title_link": "some link",
        "text": "some text"
    }]
}
```

Normal messages (where the payload does not contain an _attachments_-item, but a _text_-item) are displayed correctly.

**Comment by rodrigok** [comment] 2016-02-03 18:33
@saqura I can't reproduce

**Comment by Sing-Li** [comment] 2016-02-03 18:44
@rodrigok - you'll probably need a heavily loaded, multi-instances system - like demo.rocket.chat

We're using async-deferred - so out-of-order, especially since some messages have attachment processing required, is totally possible, right?

**Comment by rodrigok** [comment] 2016-02-03 18:55
@Sing-Li Is possible to have messages that are sent at the same time to be out of order. We can allow to pass the message `ts` field within the message payload so you can generate the order at your side and then send to us.

**Comment by saqura** [comment] 2016-02-03 19:42
In the private channel I'm currently testing with I can't reproduce it either.

On the old channel new messages with _attachments_ would appear in reverse order (with no noticeable time delay), with newest on the top. If I then tried to send new messages without _attachments_, they would be appended correctly at the bottom. New messages with _attachments_ again would appear on top of the other messages with _attachments_, but after normal messages. This channel seems to be inaccessible now though.

**Comment by rodrigok** [comment] 2016-02-03 20:17
@saqura very strange, please let me know if you can reproduce that again.

**Comment by MartinSchoeler** [comment] 2017-03-24 14:47
@rodrigok can this issue be closed?

**Comment by MartinSchoeler** [comment] 2017-07-13 14:30
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Closed by MartinSchoeler** 2017-07-13 14:30 UTC
Labels: feat: webhooks, stat: waiting response, type: bug
