### ISSUE TITLE
rocket.cat / bots no longer have permission to post to Private Channels / Direct Messages

### ISSUE THREAD

**Issue by thrakks** [RocketChat/Rocket.Chat#24375] opened 2022-02-01 05:35 UTC
### Description:

rocketchat throws the error:

```
Exception in callback of async function: Error: error-not-allowed
```
When trying to post to a private channel as the default bot **rocket.cat** as the result of an outgoing webhook.

**EDIT/UPDATE**: Bot will no longer post within direct messages between users. This is also especially annoying as our outgoing webhook used to provide heaps of quick info depending on a reference number between users.

```Exception in callback of async function: Error: Not enough permission```

### Steps to reproduce:

1. Be at version 4.3.3
2. Perform action to trigger outgoing webhook that would result in information being posted to the private channel you are in as rocket.cat or within a Direct Message between users.
3. See that nothing is posted. Check logs and see a stacktrace with that error

### Expected behavior:

rocket.cat posts result of outgoing webhook correctly to private channel or in DM between two users.

### Actual behavior:

Nothing is posted by rocket.cat. Error immediately appears in log.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.3.3
- Operating System: Centos7.9
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 12.22.1
- MongoDB Version: 4.4.12

### Client Setup Information

- Desktop App or Browser Version: App: 3.7.5 / Issue occurs in latest chrome/firefox too
- Operating System: Windows 10 20H2

### Relevant logs:

More of the error stacktrace:
```
Feb 01 12:13:34 bne-dev-rocketchat rocketchat[5810]: {"level":30,"time":"2022-02-01T02:13:34.491Z","pid":5810,"hostname":"bne-dev-rocketchat","name":"Integrations","section":"Outgoing WebHook","msg":"Will be executing the Integration \"JIRA Issue Info\" to the url: http://bne-prod-utility:11081/rocketchatJira"}
Feb 01 12:13:34 bne-dev-rocketchat rocketchat[5810]: {"level":30,"time":"2022-02-01T02:13:34.693Z","pid":5810,"hostname":"bne-dev-rocketchat","name":"Integrations","section":"Outgoing WebHook","msg":"Status code for the Integration JIRA Issue Info to http://bne-prod-utility:11081/rocketchatJira is 200"}
Feb 01 12:10:50 bne-dev-rocketchat rocketchat[5810]: Exception in callback of async function: Error: error-not-allowed
Feb 01 12:10:50 bne-dev-rocketchat rocketchat[5810]: at app/authorization/server/functions/canSendMessage.js:19:9
Feb 01 12:10:50 bne-dev-rocketchat rocketchat[5810]: at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Feb 01 12:10:50 bne-dev-rocketchat rocketchat[5810]: => awaited here:
Feb 01 12:10:50 bne-dev-rocketchat rocketchat[5810]: at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Feb 01 12:10:50 bne-dev-rocketchat rocketchat[5810]: at validateRoomMessagePermissions (app/authorization/server/functions/canSendMessage.js:48:101)
Feb 01 12:10:50 bne-dev-rocketchat rocketchat[5810]: at processWebhookMessage (app/lib/server/functions/processWebhookMessage.js:82:3)
Feb 01 12:10:50 bne-dev-rocketchat rocketchat[5810]: at RocketChatIntegrationHandler.sendMessage (app/integrations/server/lib/triggerHandler.js:196:13)
Feb 01 12:10:50 bne-dev-rocketchat rocketchat[5810]: at app/integrations/server/lib/triggerHandler.js:772:29
Feb 01 12:10:50 bne-dev-rocketchat rocketchat[5810]: at runWithEnvironment (packages/meteor.js:1286:24)
```

**Comment by emikolajczak** [comment] 2022-02-01 06:37
Hi,
Did you add Rocket.Cat as member of this channel?

**Comment by fdellwing** [comment] 2022-02-01 13:38
Since RC 4.x the bot needs to be a member of the channel it is supposed to post to.

**Comment by thrakks** [comment] 2022-02-01 22:41
> Since RC 4.x the bot needs to be a member of the channel it is supposed to post to.
> Did you add Rocket.Cat as member of this channel?

Oh, I figured that was just a workaround. 

Is there no way to grant special overriding permission to bots to post to private channels?

Unfortunately I have some problem users in my company that would rather complain about the small task of adding rocket.cat than just do it. Or need help with the adding. I was hoping to continue avoiding all that.

**Comment by thrakks** [comment] 2022-02-02 06:40
As per edit in description:

Bot will no longer post within direct messages between users. This is also especially annoying as our outgoing webhook bot used to provide heaps of quick info depending on a reference number between users. It's really frustrating to have lost this capability entirely. 

Is there a way to allow bots access to posting in DMs, or otherwise impersonate the user calling the webhook and posting on their behalf?

**Comment by thrakks** [comment] 2022-02-03 00:13
Workaround posted in #23433 by aboire "fixes" this issue for me and allows rocket.cat to correctly post the result of an outgoing webhook in direct messages between two users as well as within private channels.

Workaround is to change rocket.cat's type to "app" from "bot" in the mongo db:
```
# mongo

> use rocketchat

> db.users.update({"username": "rocket.cat"}, {$set: {"type": "app"}});
```

**Comment by ImaCrea** [comment] 2022-02-21 13:39
> Since RC 4.x the bot needs to be a member of the channel it is supposed to post to.

Thanks, it fixed it for us <3

**Comment by dudanogueira** [comment] 2022-03-04 18:29
Closing, as this is not a bug, rather an expected behavior.

**Closed by dudanogueira** 2022-03-04 18:29 UTC

**Comment by ulope** [comment] 2022-09-27 18:04
I'm sorry but this is not acceptable. 
Users can't and shouldn't be aware that they need to invite a bot user. 

This is entirely an implementation detail.
