### ISSUE TITLE
Channel Name in other languages other than English should be supported

### ISSUE THREAD

**Issue by MRYingLEE** [RocketChat/Rocket.Chat#1013] opened 2015-10-06 06:40 UTC

**Comment by brylie** [comment] 2015-10-06 11:55
What behavior have you noticed with room names? Does this issue relate to non-ASCII characters in room names? Will you please clarify this feature request?

**Comment by gmsecrieru** [comment] 2015-10-06 12:24
Closing as possible duplicate of #713 and #640 and #892

**Closed by gmsecrieru** 2015-10-06 12:24 UTC
