### ISSUE TITLE
Unable to view user's profile

### ISSUE THREAD

**Issue by hkpanchani** [RocketChat/Rocket.Chat#22753] opened 2021-07-24 10:39 UTC
### Description:

When I try to view users profile it shows my own profile in all users profile

### Steps to reproduce:

1. Click on user's conversation 
2. than click on profile image

### Expected behavior:

Should show me the users profile

### Actual behavior:

Shows my own profile

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15.0
- Operating System: debian
- Deployment Method: snap
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 3.6.14

### Client Setup Information

- All clients, desktop web, mobile

### Relevant logs:

![Screenshot 2021-07-24 at 4 17 47 PM](https://user-images.githubusercontent.com/35301566/126866187-3abe1eaf-4f62-4749-a553-736004c08095.png)

![Screenshot 2021-07-24 at 4 06 31 PM](https://user-images.githubusercontent.com/35301566/126866098-6529a610-308e-4d44-8097-56df1985aed1.png)

**Comment by ankar84** [comment] 2021-07-26 03:03
It fixed in 3.16.X
Please update to latest release 3.16.3

**Comment by hkpanchani** [comment] 2021-07-26 04:23
Snap update not yet available i think

**Comment by johncrisp** [comment] 2021-07-26 08:51
> Snap update not yet available i think

Yes I'm not sure why there has been a delay but the upgrade will fix this.

This bug is a duplicate of a number of others. I will close it for now. Please open another Issue if you notice it on an updated version - you can test it with a docker image.

**Closed** 2021-07-26 08:51 UTC
