### ISSUE TITLE
Can't create new direct messages or channels

### ISSUE THREAD

**Issue by flantascience** [RocketChat/Rocket.Chat#6098] opened 2017-02-19 03:12 UTC
Rocket.Chat Version:  0.52.0
Running Instances:    1
DB Replicaset OpLog:  (says Disabled though I thought it was enabled)
Node Version: v4.7.3

Screenshot should explain.  There used to be a PLUS sign next to CHANNELS and DIRECT MESSAGES.  Clicking on it would let you create a new.  This is no longer there.  My previous version was 0.44.0 where this worked.

![image](https://cloud.githubusercontent.com/assets/12577122/23098862/16ab16cc-f627-11e6-97df-c53ad0fd4727.png)

**Comment by saram-kon** [comment] 2017-02-19 12:45
The plus sign is now next to the search bar. For a new direct message you can just type the name in the search field.

**Comment by saram-kon** [comment] 2017-02-19 12:48
If you leave the name field free, an error pops up though, that the field "undefined" is required. I guess the field should be named "channel name" or something like this, but I don't want to create an issue for this, because it is not of enough importance imo.

**Comment by flantascience** [comment] 2017-02-19 16:51
It seems to be a lot more intuitive when there was a + next to channel to
add a new channel and a + next to DM to add a new direct message.  When I
saw "search" I initially assumed it was letting me search through my
messages.  It didn't occur to me until your post that the function was to
search for channels and people to message.

Jim Flannery

jim-flannery.com
p. 860-578-4966
e. jim@jim-flannery.com
s. jim_flannery

**Comment by reetp** [comment] 2017-02-19 19:58
+1

It threw me too. The new system is nowhere near as intuitive or logical and much prefer the older version.

**Comment by graywolf336** [comment] 2017-02-20 19:33
@karlprieb @engelgabriel :top:

**Comment by wlahti** [comment] 2017-05-26 14:28
I don't even see the + sign next to my search bar in the app for Mac. I'm currently unable to create new direct messages without searching for a person, hoping they've chatted in a channel, and then creating a message if I can find them. Otherwise, I'm out of luck with the current design.

**Comment by karlprieb** [comment] 2017-05-26 15:52
@wlahti It happen on RocketChat web client too?

**Comment by rebeld** [comment] 2017-05-26 16:28
Mac version 2.8, server 0.56.0, same here.

Web browser, my server:
<img width="278" alt="screen shot 2017-05-26 at 12 24 16 pm" src="https://cloud.githubusercontent.com/assets/329962/26503429/a613d3de-420e-11e7-8219-88a84c2f0aeb.png">

Mac client, my server:
<img width="348" alt="screen shot 2017-05-26 at 12 24 27 pm" src="https://cloud.githubusercontent.com/assets/329962/26503458/bf1a1a50-420e-11e7-856c-22eb6bc250b1.png">

Mac client, RC demo server:
<img width="357" alt="screen shot 2017-05-26 at 12 24 42 pm" src="https://cloud.githubusercontent.com/assets/329962/26503477/caf1fdf2-420e-11e7-872e-cb61e69fa8cd.png">

**Comment by karlprieb** [comment] 2017-05-26 17:12
@rebeld if you login with your SSAdmin on your server through the mac client the error persist?

**Comment by wlahti** [comment] 2017-05-31 14:42
@karlprieb I see the same behavior in the web client.

**Comment by rebeld** [comment] 2017-05-31 15:03
@karlprieb OK, I think I see. I looks like if the user doesn't have create_p or create_c perms then the + doesn't display even though they have create_d. Creating a direct message then simply requires searching for a username and clicking the result (or return). Maybe not the most obvious UI, but technically not a bug.

**Comment by wlahti** [comment] 2017-05-31 15:11
Ah ok, yes, the search in the top left does indeed work. Not the most intuitive UI as the ability to start a new direct message is kind of hidden in plain sight.

**Comment by MartinSchoeler** [comment] 2017-08-03 17:18
Closing this since its not really a bug but is a change of ui.

**Closed by MartinSchoeler** 2017-08-03 17:18 UTC
Labels: type: support
