### ISSUE TITLE
Sidebar channel and user menu dropdown not working in 3.8

### ISSUE THREAD

**Issue by rusty1281** [RocketChat/Rocket.Chat#19544] opened 2020-11-15 11:52 UTC
### Description:

Since version 3.8, in the main channel sidebar (left side) I am unable to call the channel or PM dropdown menu using the 3 dots

### Steps to reproduce:

1. clicking on the channel/user/discussion menu icon in the sidebar

### Expected behavior:

Menu with actions (Hide, leave, etc)

### Actual behavior:

Clicking on the menu icon nothing happens (multiple browsers, including the desktop app)

<img width="256" alt="Screenshot 2020-11-15 at 12 51 52" src="https://user-images.githubusercontent.com/5110408/99184155-58bbeb00-2741-11eb-91c4-4411df83ed79.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 3.8
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: yes
- NodeJS Version: v12.18.4
- MongoDB Version: 4.4.0

### Client Setup Information

- Desktop App or Browser Version: Desktop app version 3.0.7
- Operating System: macOS 11 (BigSur)

**Comment by bhdung** [comment] 2020-11-16 06:19
Same error

**Comment by damian-centrone** [comment] 2020-11-16 14:33
couldn't reproduce, tested on  macOS 11 Big sur, desktop and browser app

**Comment by desser-code** [comment] 2020-11-17 10:33
> couldn't reproduce, tested on macOS 11 Big sur, desktop and browser app

Why do you close this? This error isn't solved. I've the same problem with multiple system since server update to 3.8.0.

**Comment by phriedrich** [comment] 2020-11-17 10:54
@desser-code I too can't reproduce this problem. Do you maybe have something set in "Layout → Custom CSS"?

I had another problem with high load on idle in Safari, and while searching for a solution, I noticed that when I set `transition: none;` for the wrong class, this menu stopped working.

**Comment by desser-code** [comment] 2020-11-17 12:00
There are custom css entries. However, I removed it and the problem still occurs. I have noticed that the event flag is not set on a system when it is clicked and the required function is not performed.
Function:
onTransitionEnd

function() {
  for (var e, n = [], r = 0; r < arguments.length; r++) n[r] = arguments[r];
  return (e = t.current).call.apply(e, v([void 0], n))
}

**Comment by rusty1281** [comment] 2020-11-17 12:07
> @desser-code I too can't reproduce this problem. Do you maybe have something set in "Layout → Custom CSS"?
> 
> I had another problem with a high load on idle in Safari, and while searching for a solution, I noticed that when I set `transition: none;` for the wrong class, this menu stopped working.

I have also tried that even before opening this issue, but the problem remains. To make things more strange, other users of the same server (also with BigSur for example) using the same desktop and/or web clients have no problems at all.

Option to leave or hide the channel on mobile (iOS) with the same server, works fine and the result is immediately visible. So really not sure what to make of this.

**Comment by desser-code** [comment] 2020-11-18 08:43
Can someone please open it again? I think this is a serious problem.

**Comment by MartinSchoeler** [comment] 2020-11-19 17:13
Indeed there are more reports of this happening, needs more investigation. Re opening

**Comment by charlyrock** [comment] 2020-11-20 06:14
same problem with windows 10.
Problem occurs in the webbrowser and the desktop client. 
Why get every new version a lot of new bugs? Why would the bugs not fixed first, before any new changes come in the new version? So that we can update to a stabilized version without new problems. 
I can´t update the system, because every version brings new bugs. That is frustrating the users.

**Comment by MartinSchoeler** [comment] 2020-11-20 20:44
Just an update to everyone with this issue. This bug is tied to a OS setting `Reduce Screen Motion` So a workaround for now is to disable that setting on your Operating System.

<img width="670" alt="Screen Shot 2020-11-20 at 5 41 14 PM" src="https://user-images.githubusercontent.com/20868078/99848124-f9eadd00-2b57-11eb-855e-75b4e48c832d.png">
(Example on MacOS)

I'm working on a fix for that.

**Comment by rusty1281** [comment] 2020-11-20 21:40
> Just an update to everyone with this issue. This bug is tied to a OS setting `Reduce Screen Motion` So a workaround for now is to disable that setting on your Operating System.
> 
> <img alt="Screen Shot 2020-11-20 at 5 41 14 PM" width="670" src="https://user-images.githubusercontent.com/20868078/99848124-f9eadd00-2b57-11eb-855e-75b4e48c832d.png">
> 
> (Example on MacOS)
> I'm working on a fix for that.

Tnx @MartinSchoeler ! Just tested it and sure enough, I had reduced motion active for years now. Turning it off, fixed the menu.

Tnx again.

**Closed** 2020-11-21 03:05 UTC
Labels: subj: ui/ux, type: bug

**Comment by charlyrock** [comment] 2020-11-23 06:36
Why do you close it? The error is not solve!
In all browsers and Windows 10 Client I get this error!!!!

**Comment by rusty1281** [comment] 2020-11-23 07:02
> Why do you close it? The error is not solve!
> In all browsers and Windows 10 Client I get this error!!!!

It is in the pipeline for the 3.9 version release that it already out as a release candidate. It will be pushed soon.

**Comment by akong77** [comment] 2020-11-24 02:59
Please fix it error quickly.
