### ISSUE TITLE
iphone app needs reinstallation after server upgrade

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#5774] opened 2017-01-25 11:45 UTC
Rocket.Chat Version: 0.50.1 
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.7.2

Hello Devs.

I have complains from users regarding the iphone app. Everytime I upgrade the server they need to reinstall the app. Otherwise they are not able to login anymore. They only see the 3 little dots indicating something is happen but it isn't.

Is that a know issue?

thanks and cheers

**Comment by TheReal1604** [comment] 2017-01-25 18:30
Got this also sometimes, mostly on demo when a new develop build is tested on demo. Not occurred on my systems yet.

**Comment by dmkjr** [comment] 2017-01-27 02:43
We are having this same issue on all iPhones after each release.  The phone will update (download files) but then that's it.  Must remove application from phone and add back to allow it to function.

**Comment by himbeere** [comment] 2017-02-15 09:28
Release 0.52.0 seem to fix this.

**Comment by himbeere** [comment] 2017-03-03 07:56
Another customer complained about this problem. Now with 0.53.0. Is this officially addressed?

thanks and cheers
t.

**Comment by rasos** [comment] 2017-03-12 15:44
Still an issue for the iOS App with RC 0.52. 
Andorid app 2.5 is extremely long laoding and then has a time out. Reinstall did not help.

**Comment by danielbressan** [comment] 2017-05-10 22:30
We have this same issue, and the PR to fix #181 doesn't fix it as far as we can tell. 
 
Just to be clear, the three dots blinking is where we see the stall (after all server files have been downloaded):
![image](https://cloud.githubusercontent.com/assets/19559527/25923990/a5861634-359d-11e7-8081-30e7790166bf.png)

I'm convinced this is a server code issue, not a cordova app code issue. We've set break points and console logs all throughout the cordova code, and we hit them all before the issue pops up. It would also seem that since we're seeing the 3 dot loading, we're on server code at that point. 

So far, it's not 'every' time the server is updated or restarted, but anytime we do a more major code update (more than just a file or two) our users see this. 
@geekgonecrazy any help on this would be appreciated, we'll keep looking at it too. Thanks!

**Comment by geekgonecrazy** [comment] 2017-05-10 23:09
@rodrigok any idea what we could do to trace the cause further?

**Comment by danielbressan** [comment] 2017-05-12 15:42
@himbeere @rasos @dmkjr We're trying to track this down and think it might have something to do with our CAS handoff. Anyone using CAS, LDAP, or any other initial auth (not normal rocket sign in)? Thanks!

**Comment by himbeere** [comment] 2017-05-12 15:45
Yes. We use LDAP authentication.

**Comment by danielbressan** [comment] 2017-05-12 23:16
@geekgonecrazy @rodrigok 
We have come full circle...after a day of changing code, logging things and repeating we now think the update in https://github.com/RocketChat/Rocket.Chat.Cordova/pull/182 probably does fix the issue. Sorry we doubted!

As far as we could tell the local server files were getting corrupted or not there, and trying to download them twice right after each other could cause that - which this PR fixes. Going to implement and watch on prod.

**Comment by geekgonecrazy** [comment] 2017-05-15 16:22
Please let us know how testing goes!  Hopefully it does solve this

**Comment by maxsdw** [comment] 2018-01-30 19:04
For me the problem still happening with the update in RocketChat/Rocket.Chat.Cordova#182. It doesn't solve the situation.

**Comment by Hudell** [comment] 2018-06-06 18:45
Since this is related to the old Cordova app, I'll be closing the issue here. If any of the apps run into this  problem please open an issue on the corresponding repository.

**Comment by geekgonecrazy** [comment] 2018-06-13 05:53
Closing per reason given above 🙂

**Closed** 2018-06-13 05:52 UTC
Labels: subj: mobile, type: bug

**Comment by Syirrus** [comment] 2019-04-16 06:56
> For me the problem still happening with the update in [RocketChat/Rocket.Chat.Cordova#182](https://github.com/RocketChat/Rocket.Chat.Cordova/pull/182). It doesn't solve the situation.

Did you ever come up with a solution to this issue?

**Comment by KirbySSmith** [comment] 2019-04-16 10:51
Support for the Cordova app was dropped in the latest versions. The custom autoupdate package was removed in v0.72. If you are using a version lower than that the issue could be related to the .meteor/.id file being removed. https://github.com/RocketChat/Rocket.Chat/commit/27413c69afe9271659edf1d97322875e43ddd704#diff-cf6323754c6dfa68e897ce35d9845ceb
You can add that file back with the same id to be backwards comparable or create a new id. Not having it set causes a new random .id to be generated which messes with autoupdate.
