### ISSUE TITLE
Fail with Heroku deployment

### ISSUE THREAD

**Issue by lazbog** [RocketChat/Rocket.Chat#6452] opened 2017-03-23 19:07 UTC
I want to deploy Rocket.Chat to Heroku. I Press button, it gets me to Heroku dashboard where I input app name and click Deploy btn. Here is the log:

-----> Node.js app detected
-----> Listing HEROKU_ environment variables
HEROKU_APP_ID:           
HEROKU_APP_NAME:         
HEROKU_DYNO_ID:          
HEROKU_RELEASE_VERSION:  
HEROKU_SLUG_COMMIT:      
HEROKU_SLUG_DESCRIPTION: 
-----> Installing meteor
Downloading Meteor distribution
Meteor 1.4.3.2 has been installed in your home directory (~/.meteor).
Now you need to do one of the following:
  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/app/tmp/cache/meteor/.meteor/packages/meteor-tool/1.4.3_2/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
-----> Target Meteor version: Meteor 1.4.3.1
-----> Checking if this meteor version supports --server-only
-----> Using node: v4.7.3
----->    and npm: 4.1.2
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> bcrypt@1.0.2 install /tmp/build_6417bb6c42b93faacee73382b1af5961/RocketChat-Rocket.Chat-976dcef/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.7.3 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory `/tmp/build_6417bb6c42b93faacee73382b1af5961/RocketChat-Rocket.Chat-976dcef/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /tmp/build_6417bb6c42b93faacee73382b1af5961/RocketChat-Rocket.Chat-976dcef/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/tmp/build_6417bb6c42b93faacee73382b1af5961/RocketChat-Rocket.Chat-976dcef/node_modules/bcrypt/build'
> Rocket.Chat@0.54.0 postinstall /tmp/build_6417bb6c42b93faacee73382b1af5961/RocketChat-Rocket.Chat-976dcef
> cd packages/rocketchat-katex && npm i
rocketchat-katex@1.0.0 /tmp/build_6417bb6c42b93faacee73382b1af5961/RocketChat-Rocket.Chat-976dcef/packages/rocketchat-katex
└─┬ katex@0.7.1 
  └── match-at@0.1.0 
Rocket.Chat@0.54.0 /tmp/build_6417bb6c42b93faacee73382b1af5961/RocketChat-Rocket.Chat-976dcef
├─┬ babel-runtime@6.23.0 
│ ├── core-js@2.4.1 
│ └── regenerator-runtime@0.10.3 
├─┬ bcrypt@1.0.2 
│ ├── bindings@1.2.1 
│ ├── nan@2.5.0 
│ └─┬ node-pre-gyp@0.6.32 
│   ├─┬ mkdirp@0.5.1 
│   │ └── minimist@0.0.8 
│   ├─┬ nopt@3.0.6 
│   │ └── abbrev@1.1.0 
│   ├─┬ npmlog@4.0.2 
│   │ ├─┬ are-we-there-yet@1.1.2 
│   │ │ ├── delegates@1.0.0 
│   │ │ └── readable-stream@2.2.6 
│   │ ├── console-control-strings@1.1.0 
│   │ ├─┬ gauge@2.7.3 
│   │ │ ├── aproba@1.1.1 
│   │ │ ├── has-unicode@2.0.1 
│   │ │ ├── object-assign@4.1.1 
│   │ │ ├── signal-exit@3.0.2 
│   │ │ ├─┬ string-width@1.0.2 
│   │ │ │ ├── code-point-at@1.1.0 
│   │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
│   │ │ │   └── number-is-nan@1.0.1 
│   │ │ ├─┬ strip-ansi@3.0.1 
│   │ │ │ └── ansi-regex@2.1.1 
│   │ │ └── wide-align@1.1.0 
│   │ └── set-blocking@2.0.0 
│   ├─┬ rc@1.1.7 
│   │ ├── deep-extend@0.4.1 
│   │ ├── ini@1.3.4 
│   │ ├── minimist@1.2.0 
│   │ └── strip-json-comments@2.0.1 
│   ├─┬ request@2.81.0 
│   │ ├── aws-sign2@0.6.0 
│   │ ├── aws4@1.6.0 
│   │ ├── caseless@0.12.0 
│   │ ├─┬ combined-stream@1.0.5 
│   │ │ └── delayed-stream@1.0.0 
│   │ ├── extend@3.0.0 
│   │ ├── forever-agent@0.6.1 
│   │ ├─┬ form-data@2.1.2 
│   │ │ └── asynckit@0.4.0 
│   │ ├─┬ har-validator@4.2.1 
│   │ │ ├─┬ ajv@4.11.5 
│   │ │ │ ├── co@4.6.0 
│   │ │ │ └─┬ json-stable-stringify@1.0.1 
│   │ │ │   └── jsonify@0.0.0 
│   │ │ └── har-schema@1.0.5 
│   │ ├─┬ hawk@3.1.3 
│   │ │ ├── boom@2.10.1 
│   │ │ ├── cryptiles@2.0.5 
│   │ │ ├── hoek@2.16.3 
│   │ │ └── sntp@1.0.9 
│   │ ├─┬ http-signature@1.1.1 
│   │ │ ├── assert-plus@0.2.0 
│   │ │ ├─┬ jsprim@1.4.0 
│   │ │ │ ├── assert-plus@1.0.0 
│   │ │ │ ├── extsprintf@1.0.2 
│   │ │ │ ├── json-schema@0.2.3 
│   │ │ │ └── verror@1.3.6 
│   │ │ └─┬ sshpk@1.11.0 
│   │ │   ├── asn1@0.2.3 
│   │ │   ├── assert-plus@1.0.0 
│   │ │   ├── bcrypt-pbkdf@1.0.1 
│   │ │   ├─┬ dashdash@1.14.1 
│   │ │   │ └── assert-plus@1.0.0 
│   │ │   ├── ecc-jsbn@0.1.1 
│   │ │   ├─┬ getpass@0.1.6 
│   │ │   │ └── assert-plus@1.0.0 
│   │ │   ├── jodid25519@1.0.2 
│   │ │   ├── jsbn@0.1.1 
│   │ │   └── tweetnacl@0.14.5 
│   │ ├── is-typedarray@1.0.0 
│   │ ├── isstream@0.1.2 
│   │ ├── json-stringify-safe@5.0.1 
│   │ ├─┬ mime-types@2.1.14 
│   │ │ └── mime-db@1.26.0 
│   │ ├── oauth-sign@0.8.2 
│   │ ├── performance-now@0.2.0 
│   │ ├── qs@6.4.0 
│   │ ├── safe-buffer@5.0.1 
│   │ ├── stringstream@0.0.5 
│   │ ├─┬ tough-cookie@2.3.2 
│   │ │ └── punycode@1.4.1 
│   │ ├── tunnel-agent@0.6.0 
│   │ └── uuid@3.0.1 
│   ├─┬ rimraf@2.5.4 
│   │ └─┬ glob@7.1.1 
│   │   ├── fs.realpath@1.0.0 
│   │   ├── inflight@1.0.6 
│   │   ├── minimatch@3.0.3 
│   │   ├── once@1.4.0 
│   │   └── path-is-absolute@1.0.1 
│   ├─┬ tar@2.2.1 
│   │ ├── block-stream@0.0.9 
│   │ ├─┬ fstream@1.0.11 
│   │ │ └── graceful-fs@4.1.11 
│   │ └── inherits@2.0.3 
│   └─┬ tar-pack@3.3.0 
│     ├─┬ debug@2.2.0 
│     │ └── ms@0.7.1 
│     ├── fstream-ignore@1.0.5 
│     ├─┬ once@1.3.3 
│     │ └── wrappy@1.0.2 
│     ├─┬ readable-stream@2.1.5 
│     │ ├── buffer-shims@1.0.0 
│     │ ├── core-util-is@1.0.2 
│     │ ├── isarray@1.0.0 
│     │ ├── process-nextick-args@1.0.7 
│     │ ├── string_decoder@0.10.31 
│     │ └── util-deprecate@1.0.2 
│     └── uid-number@0.0.6 
├── codemirror@5.25.0 
├── file-type@4.1.0 
├── highlight.js@9.10.0 
├── jquery@3.2.1 
├── mime-db@1.27.0 
├─┬ mime-type@3.0.4 
│ ├── media-typer@0.3.0 
│ ├─┬ minimatch@2.0.10 
│ │ └─┬ brace-expansion@1.1.6 
│ │   ├── balanced-match@0.4.2 
│ │   └── concat-map@0.0.1 
│ ├─┬ path.js@1.0.7 
│ │ ├── escape-string-regexp@1.0.5 
│ │ └── inherits-ex@1.1.6 
│ └─┬ util-ex@0.3.15 
│   └── xtend@4.0.1 
├── moment@2.18.1 
├── moment-timezone@0.5.11 
├── photoswipe@4.1.1 
├─┬ prom-client@7.2.0 
│ ├─┬ tdigest@0.1.1 
│ │ └── bintrees@1.0.1 
│ └── util-extend@1.0.3 
├── semver@5.3.0 
└── toastr@2.1.2 
-----> Building Meteor app with ROOT_URL: https://freepe-chat.herokuapp.com
=> Errors while initializing project:
While loading emojione:emojione@2.2.6...:
error: Command failed:
/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.b0o1n7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --update-binary
Phantom installation failed { [Error: EACCES: permission denied, open
'/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
errno: -13,
code: 'EACCES',
syscall: 'open',
path:
'/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
} Error: EACCES: permission denied, open
'/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
at Error (native)
at Object.fs.openSync (fs.js:549:18)
at Object.fs.writeFileSync (fs.js:1156:15)
at writeLocationFile
(/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:108:6)
at Promise._successFn
(/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:80:5)
at nextTickCallback
(/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
at nextTickCallbackWith0Args (node.js:436:9)
at process._tickCallback (node.js:365:13)
npm ERR! Linux 3.13.0-112-generic
npm ERR! argv
"/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.b0o1n7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.b0o1n7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--update-binary"
npm ERR! node v4.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/mt-1hcoq9a/npm/node_modules/.temp-1g9quph/npm-debug.log
Phantom installation failed { [Error: EACCES: permission denied, open
'/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js']
errno: -13,
code: 'EACCES',
syscall: 'open',
path:
'/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
} Error: EACCES: permission denied, open
'/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/location.js'
at Error (native)
at Object.fs.openSync (fs.js:549:18)
at Object.fs.writeFileSync (fs.js:1156:15)
at writeLocationFile
(/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:108:6)
at Promise._successFn
(/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/install.js:80:5)
at nextTickCallback
(/tmp/mt-1hcoq9a/npm/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
at nextTickCallbackWith0Args (node.js:436:9)
at process._tickCallback (node.js:365:13)
npm ERR! Linux 3.13.0-112-generic
npm ERR! argv
"/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.b0o1n7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.b0o1n7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--update-binary"
npm ERR! node v4.7.3
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/mt-1hcoq9a/npm/node_modules/.temp-1g9quph/npm-debug.log
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by pixelbacon** [comment] 2017-03-24 19:59
++

**Comment by lazbog** [comment] 2017-03-26 21:55
I have just noticed the similar issue #6444. Is there a possibility to merge issues?

**Comment by Syirrus** [comment] 2017-03-31 21:02
I'm getting the following:

└── toastr@2.1.2 
-----> Building Meteor app with ROOT_URL: https://<URL>.herokuapp.com
rocketchat:lib: updating npm dependencies -- bad-words, object-path,
node-dogstatsd, localforage, lokijs, bugsnag, prom-client...
rocketchat:2fa: updating npm dependencies -- speakeasy, yaqrcode...
rocketchat:file: updating npm dependencies -- mkdirp, gridfs-stream, gm...
rocketchat:assets: updating npm dependencies -- image-size...
rocketchat:theme: updating npm dependencies -- less, less-plugin-autoprefix...
/app/tmp/cache/meteor/.meteor/packages/less/.2.7.9.uu0ttb++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
Error: ENOENT: no such file or directory, open '/tmp/build_b6a98558544d2b9104f08cd3942dce27/Syirrus-Rocket.Chat-86bf0f8/packages/rocketchat-ui/client/views/app/help.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at wrapper (/tools/fs/files.js:1535:35)
    at wrap.makeCacheKey._len2 (/tools/fs/optimistic.js:22:15)
    at Entry._reallyRecompute (/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.1stmgiw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:215:26)
    at Entry._recomputeIfDirty (/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.1stmgiw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:179:17)
    at Entry.recompute (/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.1stmgiw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/entry.js:46:20)
    at optimistic (/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.1stmgiw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/optimism/lib/index.js:50:18)
    at /tools/isobuild/compiler.js:558:22
    at Array.forEach (native)
    at /tools/isobuild/compiler.js:494:21
    at /tools/isobuild/compiler.js:184:28
    at Object.withCache (/tools/fs/files.js:1601:12)
    at /tools/isobuild/compiler.js:183:11
    at Array.forEach (native)
    at Function._.each._.forEach (/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.1stmgiw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compile (/tools/isobuild/compiler.js:178:5)
    at /tools/isobuild/isopack-cache.js:360:30
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._loadLocalPackage (/tools/isobuild/isopack-cache.js:315:18)
    at /tools/isobuild/isopack-cache.js:249:16
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/isopack-cache.js:248:17
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at ensureLoaded (/tools/isobuild/isopack-cache.js:213:12)
    at /tools/isobuild/isopack-cache.js:241:11
    at Array.forEach (native)
    at Function._.each._.forEach (/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.1stmgiw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/isopack-cache.js:240:11
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at IsopackCache._ensurePackageLoaded (/tools/isobuild/isopack-cache.js:239:20)
    at /tools/isobuild/isopack-cache.js:76:14
    at /tools/packaging/package-map.js:57:7
    at Function._.each._.forEach (/app/tmp/cache/meteor/.meteor/packages/meteor-tool/.1.4.3_1.1stmgiw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at [object Object]._.extend.eachPackage (/tools/packaging/package-map.js:49:7)
    at IsopackCache.buildLocalPackages (/tools/isobuild/isopack-cache.js:75:24)
    at /tools/project-context.js:841:25
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._buildLocalPackages (/tools/project-context.js:840:18)
    at /tools/project-context.js:283:9
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ProjectContext._.extend._completeStagesThrough (/tools/project-context.js:273:18)
    at /tools/project-context.js:265:12
    at Function.run (/tools/tool-env/profile.js:490:12)
    at ProjectContext._.extend.prepareProjectForBuild (/tools/project-context.js:264:13)
    at /tools/cli/commands.js:881:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:273:29)
    at buildCommand (/tools/cli/commands.js:880:8)
    at Command.func (/tools/cli/commands.js:829:12)
    at /tools/cli/main.js:1483:23
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
Build finished
heroku.com Blogs

**Comment by engelgabriel** [comment] 2017-04-27 03:21
More info at https://github.com/AdmitHub/meteor-buildpack-horse/issues/169

**Comment by engelgabriel** [comment] 2017-04-27 03:28
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/6444

**Closed by engelgabriel** 2017-04-27 03:28 UTC
Labels: feat: heroku, type: support

**Comment by jourdanrodrigues** [comment] 2017-07-28 18:44
I changed the branch to be installed to `develop` and it FINALLY worked!

The link I used was:

https://heroku.com/deploy?template=https://github.com/RocketChat/Rocket.Chat/tree/develop
