### ISSUE TITLE
Livechat Internal server error

### ISSUE THREAD

**Issue by majidfathi69** [RocketChat/Rocket.Chat#2170] opened 2016-02-09 08:39 UTC
I clone master branch in my local and load Rocket.Chat and everything work good but I have problem with Livechat.
I want to START CHAT with Livechat 
First step: Enable Livechat 
Next Step: Register a new account 
Last Step: In 'Livechat Users' section add the user to 'LIVECHAT AGENTS' list.
Now by using Installation code I expect that I can chat with another user. But when I fill name and email and press 'START CHAT' button I face Internal server error.
What is the problem? Any help will be appreciated

**Comment by majidfathi69** [comment] 2016-02-10 06:54
In livechat when I enter an email that dose not exist in users email, a new user created and I considered as a guest. But when I enter an email that same other emails that exist in users, an new user without name and email created and I face Internal server error. And if I repeatedly do that, many user creating with same issue.

**Comment by Lochemage** [comment] 2016-02-18 06:35
I am also getting this when I try to chat as a guest using the same browser that is already logged into our rocket chat account. If I use a different browser it works.

**Comment by mrkrumhausen** [comment] 2016-04-10 00:09
I get an Internal server error message when I try to login a second time with the same guest e-mail

**Comment by 7KjN3mHq** [comment] 2016-05-18 02:47
When I use same email address and different name in livechat also return Internal server error .

**Comment by sampaiodiego** [comment] 2017-02-16 12:08
this is supposed to be fixed on https://github.com/RocketChat/Rocket.Chat/pull/5201 and available from [0.49.0 version](https://github.com/RocketChat/Rocket.Chat/releases/tag/0.49.0) .. can you guys please confirm if it is still a problem?

**Comment by sampaiodiego** [comment] 2017-02-16 12:10
I'm closing this since it is a duplicate of #1864

**Closed by sampaiodiego** 2017-02-16 12:10 UTC
Labels: feat: livechat
