### ISSUE TITLE
The slash can't show

### ISSUE THREAD

**Issue by akong77** [RocketChat/Rocket.Chat#27373] opened 2022-11-28 00:54 UTC
### Description:

I upgrade to 5.3.2.If I post full directory path.It's just show some slash.
The correct path is "v:\Software\Tools\Remote_Control\"
Input to rocketchat is show v:\SoftwareToolsRemote_Control\

### Steps to reproduce:

1. Input directory path
2. send it.
3. The path is miss some slash.

### Expected behavior:

It's must show correct directory path.

### Actual behavior:

![圖片](https://user-images.githubusercontent.com/6081927/204169972-ede5f144-bfb2-4434-acd9-6031f3021e56.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 5.3.2
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.15

### Client Setup Information

- Desktop App or Browser Version: 3.8.14
- Operating System: Win11

**Comment by shevchukma** [comment] 2022-11-28 08:50
I confirm on 5.3.3 in the docker installation.

**Comment by matthias4217** [comment] 2022-11-28 09:34
This is a duplicate of #27071 and #26907.

**Comment by dudanogueira** [comment] 2022-11-28 19:59
Hi! Thanks for pointing it out!

This should be fixed in the upcoming 5.4.0 version.

You can test this both on our open server (http://open.rocket.chat) or spinning a docker instance with the [5.4.0-rc.1](https://github.com/RocketChat/Rocket.Chat/releases/tag/5.4.0-rc.1) as the image tag.

I'll be closing this issue for now, let me know if we should repoen.

**Closed by dudanogueira** 2022-11-28 19:59 UTC
