### ISSUE TITLE
[iOS hybrid] Scrolling issue

### ISSUE THREAD

**Issue by raulfiru** [RocketChat/Rocket.Chat#485] opened 2015-08-17 20:50 UTC
While in a channel open Members List -> scroll - result: the channel messages scroll below. 

i have not seen a channel with enough members to enable scrolling - but i suspect both lists would scroll.
##

**Comment by engelgabriel** [comment] 2015-08-18 11:05
@rodrigok I think we should copy the behaviour you implemented for the left nav to the right flextab. Make it fixed behind, and the messages box to slide over. That would be a nicer UX, and would fix this bug too.

**Comment by rodrigok** [comment] 2015-08-18 12:33
@engelgabriel only for mobile?

**Comment by engelgabriel** [comment] 2015-08-18 12:37
both

**Comment by rodrigok** [comment] 2015-08-19 02:57
Don't seems to be an emergency issue, we can delay to after 1.0

**Comment by gmsecrieru** [comment] 2015-10-04 17:49
I could not reproduce this error with iOS app, is that still an issue for you @raulfiru ?

**Comment by klatys** [comment] 2016-05-05 15:03
This is still happening. Additionaly if members list is long enough to be scrolled, channel messages do not scroll underneath

**Comment by engelgabriel** [comment] 2017-01-13 12:59
@karlprieb please verify if the problem still exists?

**Comment by MartinSchoeler** [comment] 2017-07-11 14:05
@engelgabriel managed to reproduce this bug on the cordova app for android

**Comment by MartinSchoeler** [comment] 2019-10-28 14:23
With the new UI this problem was fixed, If you think I'm closing this in error, please reopen this. Thanks!

**Closed by MartinSchoeler** 2019-10-28 14:23 UTC
Labels: subj: mobile, type: bug
