### ISSUE TITLE
"meteor npm start " error on mac book pro

### ISSUE THREAD

**Issue by aleebaba** [RocketChat/Rocket.Chat#5073] opened 2016-11-30 15:06 UTC
Your Rocket.Chat version:  the latest version cloned on 2016-11-30

/Users/lijie/Documents/meteor/Rocket.Chat/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/Users/lijie/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node',
1 verbose cli   '/Users/lijie/.meteor/packages/meteor-tool/1.4.2_3/mt-os.osx.x86_64/dev_bundle/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.9
3 info using node@v4.6.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Rocket.Chat@0.47.0-develop~prestart: Rocket.Chat@0.47.0-develop
6 silly lifecycle Rocket.Chat@0.47.0-develop~prestart: no script for prestart, continuing
7 info lifecycle Rocket.Chat@0.47.0-develop~start: Rocket.Chat@0.47.0-develop
8 verbose lifecycle Rocket.Chat@0.47.0-develop~start: unsafe-perm in lifecycle true
9 verbose lifecycle Rocket.Chat@0.47.0-develop~start: PATH: /Users/lijie/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/bin/node-gyp-bin:/Users/lijie/Documents/meteor/Rocket.Chat/node_modules/.bin:/Users/lijie/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin:/Users/lijie/.meteor/packages/meteor-tool/1.4.2_3/mt-os.osx.x86_64/dev_bundle/bin:/Users/lijie/.meteor/packages/meteor-tool/1.4.2_3/mt-os.osx.x86_64/dev_bundle/lib/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/bin:/usr/sbin:/sbin:/Users/lijie/.meteor:/Users/lijie/Library/Android/sdk/tools:/Users/lijie/Library/Android/sdk/platforms
10 verbose lifecycle Rocket.Chat@0.47.0-develop~start: CWD: /Users/lijie/Documents/meteor/Rocket.Chat
11 silly lifecycle Rocket.Chat@0.47.0-develop~start: Args: [ '-c', 'meteor npm i && meteor' ]
12 silly lifecycle Rocket.Chat@0.47.0-develop~start: Returned: code: 1  signal: null
13 info lifecycle Rocket.Chat@0.47.0-develop~start: Failed to exec start script
14 verbose stack Error: Rocket.Chat@0.47.0-develop start: `meteor npm i && meteor`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/lijie/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/lijie/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:854:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
15 verbose pkgid Rocket.Chat@0.47.0-develop
16 verbose cwd /Users/lijie/Documents/meteor/Rocket.Chat
17 error Darwin 15.6.0
18 error argv "/Users/lijie/.meteor/packages/meteor-tool/.1.4.2_3.1rd9djy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/lijie/.meteor/packages/meteor-tool/1.4.2_3/mt-os.osx.x86_64/dev_bundle/bin/npm" "start"
19 error node v4.6.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error Rocket.Chat@0.47.0-develop start: `meteor npm i && meteor`
22 error Exit status 1
23 error Failed at the Rocket.Chat@0.47.0-develop start script 'meteor npm i && meteor'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Rocket.Chat package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     meteor npm i && meteor
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Rocket.Chat
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Rocket.Chat
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by rodrigok** [comment] 2016-12-01 00:52
I can't reproduce the problem.

Can you paste the logs (not the debug file) here?

Which macOS version are you using?
Which meteor version are you using?

**Comment by aleebaba** [comment] 2016-12-01 05:15
Thanks , dear rodrigok.
Mac os version:10.11.6
meteor version:Meteor 1.4.2.3.

I run "meteor npm start" just now,somehow, it's ok now,the log is as below， I didn't do anything!

[rimasarus-MBP:Rocket.Chat lijie$ meteor npm start

> Rocket.Chat@0.47.0-develop start /Users/lijie/Documents/meteor/Rocket.Chat
> meteor npm i && meteor

[[[[[ ~/Documents/meteor/Rocket.Chat ]]]]]    

=> Started proxy.                             
=> Started MongoDB.                           
I20161201-13:03:10.995(8)? Updating process.env.MAIL_URL
W20161201-13:03:14.331(8)? (STDERR) ufs: permissions are not defined for store "fileSystem"
I20161201-13:03:14.341(8)? ufs: store created at 
I20161201-13:03:22.804(8)? Updating process.env.MAIL_URL
I20161201-13:03:23.188(8)? Using GridFS for custom emoji storage
I20161201-13:03:23.191(8)? ufs: temp directory created at "/tmp/ufs"
I20161201-13:03:23.286(8)? [Thu Dec 01 2016 13:03:23 GMT+0800 (CST)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
I20161201-13:03:23.290(8)? Loaded hubot-help/src/help.coffee
I20161201-13:03:23.307(8)? Loaded hello.coffee
I20161201-13:03:23.313(8)? Loaded zen.coffee
W20161201-13:03:24.771(8)? (STDERR) ufs: permissions are not defined for store "rocketchat_uploads"
I20161201-13:03:24.778(8)? Using GridFS for Avatar storage
=> Started your app.

=> App running at: http://localhost:3000/
I20161201-13:03:24.963(8)? ➔ System ➔ startup
I20161201-13:03:24.964(8)? ➔ +----------------------------------------+
I20161201-13:03:24.964(8)? ➔ |             SERVER RUNNING             |
I20161201-13:03:24.965(8)? ➔ +----------------------------------------+
I20161201-13:03:24.965(8)? ➔ |                                        |
I20161201-13:03:24.966(8)? ➔ |       Version: 0.47.0-develop          |
I20161201-13:03:24.966(8)? ➔ |  Process Port: 26849                   |
I20161201-13:03:24.967(8)? ➔ |      Site URL: http://localhost:3000/  |
I20161201-13:03:24.967(8)? ➔ |         OpLog: Enabled                 |
I20161201-13:03:24.968(8)? ➔ |                                        |
I20161201-13:03:24.968(8)? ➔ +----------------------------------------+

**Comment by MartinSchoeler** [comment] 2016-12-01 10:44
@aleebaba can i close this issue?

**Comment by rodrigok** [comment] 2016-12-01 17:52
@aleebaba Awesome, maybe it was a little problem with meteor. I will close this issue, feel free to reopen it if you need.

Thanks

**Closed by rodrigok** 2016-12-01 17:52 UTC
Labels: type: support

**Comment by aleebaba** [comment] 2016-12-05 01:08
Sorry for late reply.It's ok.  Close the issue please!



87092979@qq.com
 
From: Martin Schoeler
Date: 2016-12-01 18:44
To: RocketChat/Rocket.Chat
CC: aleebaba; Mention
Subject: Re: [RocketChat/Rocket.Chat] "meteor npm start " error on mac book pro (#5073)
@aleebaba can i close this issue?
