### ISSUE TITLE
not able to login with APP in Version 0.47

### ISSUE THREAD

**Issue by Againstreality** [RocketChat/Rocket.Chat#5128] opened 2016-12-06 14:34 UTC
Your Rocket.Chat version: 0.47
After Updating to 0.47 User who havent loged in with the app Android and iOs newest Version. Are hanging in a Loop with message: Downloading files.
I can reproduce this in two instances. We have a lxc Setup with Reverse Proxy on Host. 
The Server logs show no errors. A user who has been loged in with the App in Version 0.46 can still Login and update.

**Comment by mrplow** [comment] 2016-12-06 15:20
Dupe of #5014

**Closed** 2016-12-06 17:01 UTC
