### ISSUE TITLE
"offline chat notification" setting is not taken into account

### ISSUE THREAD

**Issue by yfoelling** [RocketChat/Rocket.Chat#8619] opened 2017-10-24 08:28 UTC
### Description:

Chat setting for offline notifications was not taken into account. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Chat App for OSX
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 4
* DB Replicaset Oplog: active
* Node Version: v4.8.4

### Steps to Reproduce:

1. go to "my account" page 
2. deactivate offline notification and press apply
3. go offline and let someone mention you

### Expected behavior:

I will not get any Email for the mention, but i will get notifications on my iPhone app.

### Actual behavior:

I get emails and notifications of the IPhone app

**Comment by maximecharron** [comment] 2017-11-02 02:38
We are also having this issue with a Docker deployment on version 0.59.3. Any idea when it will be fixed?

**Comment by maximecharron** [comment] 2017-11-02 03:13
@MartinSchoeler @rodrigok I took a bit of time to check and it seems that the logic change introduced in PR #7639 is the source of this problem. If it is a direct message, user settings are not checked and the email is sent every time. I'll try to take some time tomorrow to submit a PR, unless you beat me to it.

**Comment by JonathanSidego** [comment] 2017-11-03 00:36
Awesome. Also discussed in #8568

**Comment by cy4n** [comment] 2017-11-22 07:46
any news on this? 20 days in on "ill try to take some time tomorrow" 

bug still reproducable in 0.59.3, getting DM notification emails even when notification turned off

**Comment by cy4n** [comment] 2017-11-22 07:48
oh looks like PR https://github.com/RocketChat/Rocket.Chat/pull/8810 fixes the Problem, has  been merged 14d ago, we're still waiting for a release.

**Closed** 2017-12-04 20:30 UTC
Labels: feat: notification, type: bug

**Comment by dmoldovan123** [comment] 2017-12-05 08:37
+1
