### ISSUE TITLE
[BUG][API] /api/v1/settings.oauth identifier field inconsistency

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#10546] opened 2018-04-22 00:52 UTC
Getting inconsistent results from our new REST API.

Identifier comes as _id:
```
{"services":[{"_id":"ooGRhWvEPrLx9vPFB","service":"open","clientId":"h8K3pqagWgqxBE2cp","custom":true,"serverURL":"https://open.rocket.chat","tokenPath":"/oauth/token","identityPath":"/api/v1/me","authorizePath":"/oauth/authorize","scope":"openid","buttonLabelText":"open","buttonLabelColor":"#FFFFFF","loginStyle":"popup","buttonColor":"#13679A","tokenSentVia":"payload","identityTokenSentVia":null,"usernameField":"username","mergeUsers":true}],"success":true}
```

Identifier comes as id:
```
{"services":[{"id":"eEYuSPY7KpjtFeCrY","name":"facebook","clientId":"835103589938459","buttonLabelText":"","buttonColor":"","buttonLabelColor":"","custom":false},{"id":"pC7Ye83eYPgRz9yXm","name":"github","clientId":"886a7b2a1fb067b10d3a","buttonLabelText":"","buttonColor":"","buttonLabelColor":"","custom":false},{"id":"R6x57fMdjLfSJCKHi","name":"gitlab","clientId":"ad37be86b2fe45ab494ea51cffffa673c89c240e9fa6addfbedd06a587707731","buttonLabelText":"","buttonColor":"","buttonLabelColor":"","custom":false},{"id":"antN9dgpGFNjYq3Gi","name":"google","clientId":"662030055877-uma7qar29ji84gopa740fasv2f6rfj1v.apps.googleusercontent.com","buttonLabelText":"","buttonColor":"","buttonLabelColor":"","custom":false},{"id":"WcJkBdR2FGQc2asbt","name":"linkedin","clientId":"77j932xbl3gl62","buttonLabelText":"","buttonColor":"","buttonLabelColor":"","custom":false},{"id":"ZLdFDrMkEiJMnDQQY","name":"meteor-developer","clientId":"LDGYjcX2knskEP8HR","buttonLabelText":"","buttonColor":"","buttonLabelColor":"","custom":false},{"id":"9S5Q7d7An5iwJRzHK","name":"twitter","buttonLabelText":"","buttonColor":"","buttonLabelColor":"","custom":false}],"success":true}
```

Perhaps when it's a custom oauth it's coming as "_id" and when it's a built-in oauth it's coming as "id".

**Let's make everything "_id". Other v1 endpoints are using "_id" like /api/v1/custom-emoji.**

**Comment by cardoso** [comment] 2018-04-22 00:57
Causing this bug on iOS: https://github.com/RocketChat/Rocket.Chat.iOS/issues/1577

**Comment by graywolf336** [comment] 2018-04-22 14:34
@MarcosSpessatto let's for this and get it merged this week, as it's a regression due to the newly added endpoint

**Closed** 2018-04-24 20:37 UTC
