### ISSUE TITLE
Code Block Highlighting Broken for Python, C++, Diff, and Many Other Popular Languages in Versions 3.9.0+

### ISSUE THREAD

**Issue by mohammad-matini** [RocketChat/Rocket.Chat#19933] opened 2020-12-22 08:52 UTC
### Description:

https://github.com/RocketChat/Rocket.Chat/pull/19533 disables code highlighting for many target languages, including the `diff` target, starting with version 3.9.0.

### Steps to reproduce:

Send a code block with a `diff` highlight type in versions 3.9.0+

### Expected behavior:

`diff` code blocks should be highlighted.

### Actual behavior:

`diff` code blocks are not highlighted in versions 3.9.0+, unlike previous versions of Rocket Chat.

![2020-12-22-rocket-chat-diff-broken](https://user-images.githubusercontent.com/44205473/102868327-1b86ff00-444b-11eb-94eb-f939c9cb4dcf.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.9.0
- Operating System: Ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.0.12

### Client Setup Information

- Desktop App or Browser Version: Firefox 78.6.0esr (64-bit)
- Operating System: Debian 10

### Additional context

Users at our company make extensive use of the `diff` highlighter for sharing patches and discussing changes over Rocket Chat channels. Starting with release version 3.9.0 our workflow was significantly hindered by the missing highlighting feature. The popularity of patch-style diffs as a software development tool easily exceeds that of targets like `go` and `rust` and even `vimscript` all of which are currently still enabled.

### Relevant logs:

The browser logs show the following error:
```
Could not find the language 'diff', did you forget to load/include a language module?
```

**Comment by sushant52** [comment] 2021-01-24 20:11
@dougfabris was the syntax highlighting removed simply to reduce the number of imports and overall file size? Will this be added in future or is there a workaround that is needed for this?

**Comment by ggazzo** [comment] 2021-01-29 02:02
we removed a "few" languages, most of them were not very usual or even used. we have plans to reintroduce those languages, maybe loading in a lazy load, or asking for some action from some admin

**Comment by mohammad-matini** [comment] 2021-02-09 09:52
> we removed a "few" languages, most of them were not very usual or even used.

I understand the need to reduce the bundle size, but I think some removed languages are very popular and important and should not have been removed. There were more than 160 languages removed, including: typescript, python, java, php, r, objectivec, swift, kotlin, ruby, lua, haskell, cpp, xml, asciidoc, basic, clojure, cmake, crystal, cs, diff, elixir, erlang, fortran, fsharp, lisp, makefile, perl, nginx, scheme, sql, tcl, tex, and x86asm among many others.

I don't understand how making bundle size smaller by a few Kilobytes is worth unexpectedly breaking code highlighting, in a minor release, for all deployments at companies that develop using Python or Java or TypeScript or C++, or as is in our case, share diff snippets and patches and code in Lisp. Even XML and SQL were removed. On the other hand, things like vimscript and SCSS were kept in. I don't think vimscript should ever take priority over something like Python.

I urge you to reconsider the removal of those popular languages, even if it means a slightly larger bundle size. Highlighting for many important languages has been broken for multiple versions now. The whole hljs library is 40K gzipped, that's like nothing in terms of size. It's smaller than the smallest of images that might be shared in any typical chat room.

Thank you guys for your work on Rocket Chat by the way, it's been a pleasure to work with it since we moved off Slack :]

**Comment by LazyDodo** [comment] 2021-02-18 17:45
Hate to pile on, but what's more disconcerting about the sheer volume of languages removed in a minor release is the complete lack of corrective actions, this has been broken since 3.9.0 (nov 2020) it's February now and it is still broken.

Ever since this update any (usually C++) code we post is looking like a seemingly randomized Christmas tree, at this point time I'd take a "off" option, it doesn't even have to match the language, being able to tag a block of code with "please don't" would be better than whatever is going on currently.  off is good... i'd be delighted with off at this point.

**Comment by kloetpatra** [comment] 2021-02-24 10:38
> we removed a "few" languages, most of them were not very usual or even used
You removed 9 from the top 10 languages according to tiobe index.

**Comment by notatallshaw** [comment] 2021-03-01 14:48
Is there any traction on this? Is there a way for server admins to manually add them back? This was a great feature for a Python channel I run. Removing 90% of the most popular languages seems like an odd move.

**Comment by slhck** [comment] 2021-05-03 11:20
What can we do to get this feature back into RocketChat?

I don't want to repeat previous arguments posted here, but could you please provide some roadmap as to when these are going to get reintroduced?

Perhaps there could be a setting in the administration panel, allowing admins to toggle which languages to load, with a sensible default.

Or at least re-introduce the top *N* languages.

I'm willing to provide a PR for this, but I'd like some guidance from the maintainers first.

**Comment by vlebourl** [comment] 2021-05-10 13:51
Is there any update on this? Same as above, that's quite a huge regression...

**Comment by Matt-something** [comment] 2021-05-28 08:53
What's the plan to resolve this? How can I tell if this is being looked at?
I agree with slhck, there should be a plan to either turn over control to the administration panel and/or reintroduce the top _N_ languages. The current limited selection doesn't make much sense.

**Comment by bitzl** [comment] 2021-06-10 07:21
Anything we can do to help? We are using code snippets with Java, Python and Diff a lot, and syntax highlighting makes a huge difference for effective communication.

Using Rocket.Chat for work is otherwise a great experience, thank you for creating it!

**Comment by abbluiz** [comment] 2021-06-11 17:22
I thought it was some kind of bug, or syntax highlighting was not supported at all. But thanks to this issue, at least I know it is a recognized problem.

However, there is something I'd like to ask. Is the syntax highlighting feature documented anywhere, I don't even know which languages I can highlight right now?

**Comment by 3ter** [comment] 2021-06-11 20:15
@abbluiz I wouldn't quite call it documented but I suppose this list shows all of the omissions and the supported languages for highlighting:
https://github.com/RocketChat/Rocket.Chat/blob/157b882d38b34b7b79dea527316554fe33f70891/app/markdown/lib/hljs.js

**Comment by parannoide** [comment] 2021-06-25 19:23
Any updates on this regression?

**Comment by sybrenstuvel** [comment] 2021-07-22 13:42
> @abbluiz I wouldn't quite call it documented but I suppose this list shows all of the omissions and the supported languages for highlighting:
> https://github.com/RocketChat/Rocket.Chat/blob/157b882d38b34b7b79dea527316554fe33f70891/app/markdown/lib/hljs.js

Thanks for the info, it makes it clear how specific to a small set of users this "optimization" was. It's really confusing, though.

Can we at least get an acknowledgement from the Rocket.Chat devs that this is an actual issue? It's been 7 months now.

**Comment by 3ter** [comment] 2021-07-22 14:11
> It's been 7 months now.

It's also 2.3k issues wanting to be fixed, unfortunately. I suppose this issue just isn't very visible to the active devs.
I remember @slhck offered a PR regarding the issue but was asking about (further) guidance, though I think @ggazzo already made some suggestions even before that:

> we have plans to reintroduce those languages, maybe loading in a lazy load, or asking for some action from some admin

I take this as "Yes, this is an issue which we want to fix. If somebody provides a non-detrimental way of getting them back, a PR will gladly be accepted".

**Comment by slhck** [comment] 2021-07-22 14:38
> It's also 2.3k issues wanting to be fixed, unfortunately. I suppose this issue just isn't very visible to the active devs.

There have been repeated questions from multiple users without *any* response from the maintainers. I doubt that this is the same for all issues here, most of which may be small bugs that are hard to reproduce, or already outdated.

> I take this as "Yes, this is an issue which we want to fix. If somebody provides a non-detrimental way of getting them back, a PR will gladly be accepted".

I wouldn't interpret it that way. I don't think it's worth to spend time on a PR if it is not according to how the maintainers have planned to integrate the feature. Consider that there are > 500 PRs open, too.

There are multiple ways this can be done, e.g. by integrating X *other* languages, or making it switchable from an admin panel, or making it a build-time option, etc. That's why I asked for guidance which solution they're looking at. That'll improve the chances for a PR to get looked at and merged eventually.

**Comment by 3ter** [comment] 2021-07-22 14:56
Thanks for the swift reaction. All your points are valid in my opinion.

I suppose though that you can only be subscribed to so many issues and still be productive. So that's why I'm trying pinging people directly (if there's a good reason for it).

So I do hope @ggazzo is going to chime in again.

**Comment by yevgenpa** [comment] 2021-09-06 10:12
> we removed a "few" languages, most of them were not very usual or even used. we have plans to reintroduce those languages, maybe loading in a lazy load, or asking for some action from some admin

Python is I guess the second most used programming language worldwide. We would be apperciate if you could put that in again.

**Closed** 2021-09-23 22:07 UTC
Labels: subj: markdown
