### ISSUE TITLE
Formatting gets lost when a message is copied

### ISSUE THREAD

**Issue by jschirrmacher** [RocketChat/Rocket.Chat#14858] opened 2019-06-24 09:33 UTC
### Description:

When copying a message containing formatting, only the text part without the formatting is copied into the clipboard. This was not the case in earlier (pre-1.0) versions and seems to be still a feature, because the formatting is marked in html with a `<span class="copyonly">` tag.

However, the css for `copyonly` has `user-select: none`, so it doesn't work any more.

### Steps to reproduce:

1. Write and send a message with formatting, for example `*bold text*`
2. select the message text with the mouse and copy it to the clipboard
3. paste as a new message

### Expected behavior:

Formatting is copied as well.

### Actual behavior:

Formatting is lost, only text part is copied.

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.3
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 2
- NodeJS Version: v8.11.4
- MongoDB Version: 3.4.21

**Comment by MartinSchoeler** [comment] 2019-07-11 18:35
Hello @jschirrmacher Can you test this issue on the latest version? I could not reproduce this on version `1.2.1`. This was probably fixed by now. If the issue persists please reopen this with updated details. Thanks!

**Closed by MartinSchoeler** 2019-07-11 18:35 UTC
Labels: subj: ui/ux, type: bug

**Comment by jschirrmacher** [comment] 2019-07-29 06:31
Yes, thanks, it seems so that it is already fixed.

**Comment by MrBS13** [comment] 2021-01-07 16:17
Hey!
What about enabling copy part of the message?
right now, when you copy part of the message, it will copy it without any formatting
