### ISSUE TITLE
Shortcut to add a reaction

### ISSUE THREAD

**Issue by fabioperrella** [RocketChat/Rocket.Chat#5433] opened 2017-01-05 12:41 UTC
Hi, it would be nice if it was possible to add a reaction using only the keyboards. (at least, the last message)

I looked in docs and I didn't find anything about this.

So this is a feature-request!

**Comment by Kiran-Rao** [comment] 2017-01-05 16:40
Slack implements this using `+:emoji:`.

This seems like a good approach.

**Comment by marceloschmidt** [comment] 2017-04-17 18:22
Duplicate of #3756

**Closed by marceloschmidt** 2017-04-17 18:22 UTC
Labels: feat: message, type: new feature
