### ISSUE TITLE
Automatic file cleanup after a period of time

### ISSUE THREAD

**Issue by cbajohr** [RocketChat/Rocket.Chat#2777] opened 2016-04-05 13:00 UTC
Over time the disk space is running low on the server because of file uploads. 
An administration option to automatically clean up old files after a period of time could help to save a lot of disk space in long term.

Your Rocket.Chat version: 0.25.0

**Comment by engelgabriel** [comment] 2016-04-05 21:47
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2196

**Closed by engelgabriel** 2016-04-05 21:47 UTC
