### ISSUE TITLE
Rocket.Chat 0.73 hang up Updating process.env.MAIL_URL

### ISSUE THREAD

**Issue by ochbob** [RocketChat/Rocket.Chat#13044] opened 2018-12-28 10:13 UTC
### Description:

Since update to 0.73, when I start the server, it hang up to:  Updating process.env.MAIL_URL
No issue with 0.72.3.

### Steps to reproduce:

 Starting the server with 0.73 version.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73
- Operating System: Debian Stretch 9.6
- Deployment Method: Manual
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  8.11.4
- MongoDB Version: 3.6

### Relevant logs:

> Dec 28 09:58:22 systemd[1]: Started The Rocket.Chat server.
> Dec 28 09:58:25 rocketchat[21510]: Updating process.env.MAIL_URL
> Dec 28 09:58:25 rocketchat[21510]: Starting Email Intercepter...
> Dec 28 09:58:25 rocketchat[21510]: LocalStore: store created at
> Dec 28 09:58:25 rocketchat[21510]: LocalStore: store created at
> Dec 28 09:58:25 rocketchat[21510]: LocalStore: store created at
> Dec 28 09:58:26 rocketchat[21510]: Setting default file store to GridFS
> Dec 28 09:58:26 rocketchat[21510]: Warning: connect.session() MemoryStore is not
> Dec 28 09:58:26 rocketchat[21510]: designed for a production environment, as it will leak
> Dec 28 09:58:26 rocketchat[21510]: memory, and will not scale past a single process.
> Dec 28 09:58:29 rocketchat[21510]: {"line":"121","file":"migrations.js","message":"Migrations: Not migrating, already at version 136","time":{"$date":1545987509969},"level":"info"}
> Dec 28 09:58:30 rocketchat[21510]: Using GridFS for custom sounds storage
> Dec 28 09:58:30 rocketchat[21510]: Using GridFS for custom emoji storage
> Dec 28 09:58:30 rocketchat[21510]: Exception in callback of async function: { Error: EACCES: permission denied, mkdir '/home/rocketchat'
> Dec 28 09:58:30 rocketchat[21510]:     at Object.fs.mkdirSync (fs.js:885:18)
> Dec 28 09:58:30 rocketchat[21510]:     at sync (/opt/Rocket.Chat/programs/server/npm/node_modules/mkdirp/index.js:71:13)
> Dec 28 09:58:30 rocketchat[21510]:     at Function.sync (/opt/Rocket.Chat/programs/server/npm/node_modules/mkdirp/index.js:77:24)
> Dec 28 09:58:30 rocketchat[21510]:     at new RocketChatFile.FileSystem (packages/rocketchat:file/server/file.server.js:154:10)
> Dec 28 09:58:30 rocketchat[21510]:     at packages/rocketchat:importer/server/startup/store.js:16:33
> Dec 28 09:58:30 rocketchat[21510]:     at Function.time (/opt/Rocket.Chat/programs/server/profile.js:309:28)
> Dec 28 09:58:30 rocketchat[21510]:     at /opt/Rocket.Chat/programs/server/boot.js:427:13
> Dec 28 09:58:30 rocketchat[21510]:     at /opt/Rocket.Chat/programs/server/boot.js:472:5
> Dec 28 09:58:30 rocketchat[21510]:     at Function.run (/opt/Rocket.Chat/programs/server/profile.js:510:12)
> Dec 28 09:58:30 rocketchat[21510]:     at /opt/Rocket.Chat/programs/server/boot.js:470:11
> Dec 28 09:58:30 rocketchat[21510]:   errno: -13,
> Dec 28 09:58:30 rocketchat[21510]:   code: 'EACCES',
> Dec 28 09:58:30 rocketchat[21510]:   syscall: 'mkdir',
> Dec 28 09:58:30 rocketchat[21510]:   path: '/home/rocketchat' }
> Dec 28 09:58:30 rocketchat[21510]: Updating process.env.MAIL_URL

Roll back to 0.72.3 just working fine

> .
> .
> .
> Dec 28 11:00:51 rocketchat[2897]: Updating process.env.MAIL_URL
> Dec 28 11:00:52 rocketchat[2897]: The App c33fa1a6-68a7-491e-bf49-9d7b99671c48 is checking if "poll" command exists.
> Dec 28 11:00:52 rocketchat[2897]: The App c33fa1a6-68a7-491e-bf49-9d7b99671c48 is registering the command: "poll"
> Dec 28 11:00:52 rocketchat[2897]: Loaded the Apps Framework and loaded a total of 1 Apps!
> Dec 28 11:00:53 rocketchat[2897]: #033[32m➔#033[39m #033[32mSystem ➔ startup#033[39m
> Dec 28 11:00:53 rocketchat[2897]: #033[32m➔#033[39m #033[32m+-----------------------------------------------------+#033[39m
> Dec 28 11:00:53 rocketchat[2897]: #033[32m➔#033[39m #033[32m|                    SERVER RUNNING                   |#033[39m
> Dec 28 11:00:53 rocketchat[2897]: #033[32m➔#033[39m #033[32m+-----------------------------------------------------+#033[39m

thank you

**Comment by himpierre** [comment] 2018-12-28 10:42
`Dec 28 09:58:30 rocketchat[21510]: Exception in callback of async function: { Error: EACCES: permission denied, mkdir '/home/rocketchat'
`

Maybe thats the problem?

**Comment by ochbob** [comment] 2018-12-28 11:15
I don't know to be honest, I did not change anything from 0.72.3 to 0.73, but maybe you right.

My user "rocketchat" is a system user with home directory:  "/home/rocketchat"

**Comment by sampaiodiego** [comment] 2018-12-28 20:13
right.. closing as this is a duplicate of #13042

**Closed by sampaiodiego** 2018-12-28 20:13 UTC
