### ISSUE TITLE
Cannot upgrade from v4.3.3

### ISSUE THREAD

**Issue by YanChii** [RocketChat/Rocket.Chat#26175] opened 2022-07-07 14:53 UTC
### Description:

Hi.

We have a problem upgrading RC server to anything newer than `4.3.3`. We are trying docker and tar install with the same outcome. The server seemingly starts (doesn't fail) but it does not print any logs or errors. The mongodb is external on the other server. The database migration version is not changed even after we keep it running for a long time.

How can we find out what's going on?

Thank you for your help.

Jan

### Steps to reproduce:

```
#RC_IMG="rocketchat/rocket.chat:4.3.3"
RC_IMG="rocketchat/rocket.chat:4.4.5"

docker pull "${RC_IMG}"

docker stop rocketchat
docker rm -f rocketchat
docker run --name rocketchat -d -p 3000:3000 \
        -v /opt/uploads:/app/uploads \
        --restart unless-stopped \
        -e ROOT_URL=http://localhost:3000 \
        -e MONGO_URL="mongodb://someuser:somepass@10.x.y.z:27017/rocketchat?authSource=admin" \
        "${RC_IMG}"

docker logs -f rocketchat
<nothing is printed after this point>
```

-- or --
```
export MONGO_URL=...
export MONGO_OPLOG_URL=...
export ROOT_URL=...
export CREATE_TOKENS_FOR_USERS=true
export PORT=3000
node main.js
<nothing is printed after this point>
```

### Expected behavior:

Start printing some starting messages, applying migrations, etc.

### Actual behavior:

Process is not printing anything. We cannot squeeze any info what's going on. I can see some tcp connections to mongodb but it stays like this forever. Versions `4.3.3` and lower don't have this problem. We've tried all newer versions, including the latest one but the outcome is the same.

### Server Setup Information:

- Version of Rocket.Chat Server: anything newer than `4.3.3`
- Operating System: Ubuntu 20.04
- Deployment Method: docker and tar
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: docker-embedded or 14.0.0 and 14.19.x
- MongoDB Version: 4.4

### Relevant logs:

None.

**Comment by dudanogueira** [comment] 2022-07-08 19:09
Hi! Have you tried this in another server to see if the outcome is the same? This may be caused because of CPU and/pr dependencies?

Also, check this other issue, that can be related:
https://github.com/RocketChat/Rocket.Chat/issues/25396

I'll close this one here as this is not a bug, but an upgrade issue.

Feel free use our [Community  Support Channel](https://open.rocket.chat/channel/support) or [forums](https://forums.rocket.chat/) for further assistance

**Closed by dudanogueira** 2022-07-08 19:09 UTC

**Comment by YanChii** [comment] 2022-07-12 12:41
Hi. Upgrade process is part of the software so I'd consider this to be a bug (app is not printing what's going on).

Anyway, I've figured it out so I'm leaving some hints here in case someone else hits the problem.

The new app version has connected to the database after start but it wasn't able to print what's wrong. I had to disable replica in `/etc/mongod.conf` like this:
```
#replication:
#  replSetName: "rs01"
```

RocketChat requires replica so the next start fails... however this way it printed out errors about the indexes it didn't like. I had to manually drop the mentioned indexes, e.g:
```
# mongo mongodb://user:<pass>@db01.example.com:27017/rocketchat?authSource=admin
> db.runCommand( { dropIndexes: "rocketchat_room", index: "t_1_departmentId_1_closedAt_1" } )
> db.runCommand( { dropIndexes: "rocketchat_room", index: "createdOTR_1" } )
> db.runCommand( { dropIndexes: "users", index: "bio_1" } )
...
```
After that, return the `mongod.conf` to the original state and restart mongo and RocketChat app.
I had to repeat the process two times but after dropping all conflicting indexes, the migration went through.

Jan
