### ISSUE TITLE
UI issue with edit room info

### ISSUE THREAD

**Issue by hungtienvu** [RocketChat/Rocket.Chat#8897] opened 2017-11-18 18:11 UTC
### Server Setup Information:

* Version of Rocket.Chat Server:0.59.3
* Operating System:Linux
* Deployment Method(snap/docker/tar/etc):snap
* Number of Running Instances: 1
* DB Replicaset Oplog:Enabled
* Node Version:v4.8.4

### Steps to Reproduce:

1. Administration
2. Romms
3. Edit room

### Expected behavior:
User can save their settings

Save button. Channel type is not cut-off
### Actual behavior:
Could not save channel info

Could not save channel info
![](https://i.imgur.com/uAwYczV.png)

**Comment by DRON4eg** [comment] 2017-11-20 05:26
use search...

[8562](https://github.com/RocketChat/Rocket.Chat/issues/8562)

**Comment by MartinSchoeler** [comment] 2017-11-20 10:48
Duplicate of #8562

**Closed by MartinSchoeler** 2017-11-20 10:48 UTC
