### ISSUE TITLE
Ctrl-P ... our homage-to-sublime-text  'secret special hot key'  search is broken

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#1127] opened 2015-10-16 13:50 UTC
The search-results list is now often all blanks.  Seems that the field used has been changed recently but not updated in the code.

![screen shot 2015-10-16 at 9 46 22 am](https://cloud.githubusercontent.com/assets/122633/10543199/071c990c-73eb-11e5-9944-1dc598a9d308.png)

**Comment by gmsecrieru** [comment] 2015-10-16 13:52
Duplicate of #938

**Closed by gmsecrieru** 2015-10-16 13:52 UTC
Labels: subj: ui/ux, type: bug
