### ISSUE TITLE
Text "hufs" causes api url to 404

### ISSUE THREAD

**Issue by tomplaskon** [RocketChat/Rocket.Chat#18670] opened 2020-08-25 14:49 UTC
### Description:

Go to directory (channel or user), type 'hufs' and you will get a toast that says 'undefined'. A quick inspection shows that the call to /api/v1/directory has failed with a 404.

### Steps to reproduce:

1. Go to directory (channel or user)
2. type 'hufs'
3. you will get a toast that says 'undefined'.

### Expected behavior:

You should see any channels/users that contain the text 'hufs'.

### Actual behavior:

You see a toast that says 'undefined'

### Server Setup Information:

- Version of Rocket.Chat Server: 3.1.1
- Operating System: Mac OS 10.15.2
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.16.1 - x64
- MongoDB Version: 4.0.6

This is reproducible on https://open.rocket.chat/

### Client Setup Information

- Desktop App or Browser Version: Chrome 84.0.4147.135
- Operating System: Mac OS 10.15.2

### Additional context

Seems to affect any /api/v1 url that contains the string 'hufs'

E.g.,
https://open.rocket.chat/api/v1/hufs -> gives you the expected 404 page
https://open.rocket.chat/api/v1/hufs -> gives unexpected 404 error

E..g,
You can had ?hufs=1 to any valid call and it will now fail.

**Comment by sampaiodiego** [comment] 2020-08-25 20:16
Closing as duplicate of https://github.com/RocketChat/Rocket.Chat/issues/16174

We'll work on this soon

**Closed by sampaiodiego** 2020-08-25 20:16 UTC
