### ISSUE TITLE
sound status goes out of window on popout mode

### ISSUE THREAD

**Issue by GauravBurande** [RocketChat/Rocket.Chat#28115] opened 2023-02-22 08:02 UTC
### Description:

When hovering over the bell icon in rocket.chat's popout mode the sound status goes out the window area

### Steps to reproduce:

1. Access: https://open.rocket.chat/livechat?mode=popout
2. Click on rocket.chat button at the bottom right
3. Click on expand chat
4. hover over bell icon

### Expected behavior:

the sound status should be visible in the window area

### Actual behavior:

the sound status which shows on hovering over bell icon goes out of the tab window

![rocket chat bot](https://user-images.githubusercontent.com/100035026/220558426-79094fdb-53a1-46d6-b9ff-96d418d0c363.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: browser
- Operating System: windows

**Comment by dudanogueira** [comment] 2023-02-22 20:03
Thanks!! I was able to reproduce this.

**Comment by XshubhamX** [comment] 2023-02-22 21:13
@dudanogueira Can I work on this?

**Possible Solution**
<img width="909" alt="image" src="https://user-images.githubusercontent.com/63532716/220760073-17635b39-40ee-4d94-acea-231c59c81ab5.png">
This is happening because white spaces are overflowing, a simple  and reliable fix would be to just add below styling to the div.
```
div {
  white-space: normal;
}
```

**Comment by JayashTripathy** [comment] 2023-02-23 11:51
@GauravBurande hey can you please assign me this issue ?
 
what i can fix is -
1.  I think its better if we move that tooltip div(which displays sound status) inside of its parent immediate button(classname ="header__action__Xiqxc") and style according to that button .
![image](https://user-images.githubusercontent.com/76092296/220897484-72fc3507-a0de-428a-905a-a61e8e5d533d.png)

2. the over flowing tooltip div(classname="tooltip__1MCkK ") can be reposition from bottom to left side and it'll work without overflowing

**Comment by dudanogueira** [comment] 2023-02-23 13:13
Sure thing!

I was not aware of that popout mode, and looks like it's not documented (or I was not able to find it, anyway)

**Comment by priyanshu-kun** [comment] 2023-02-23 15:26
should padding-left and padding-right in .header__Ma8Sh class get the jobs done?

**Comment by Nilmohon** [comment] 2023-02-23 15:36
Please assign me to work with this issue

**Comment by GauravBurande** [comment] 2023-02-23 17:11
If not assigned for a long time, is it okay to make a pull request?

**Comment by HETARTH7** [comment] 2023-02-23 17:32
I want to work on it. Please assign me this issue.

**Comment by lohargaurav00** [comment] 2023-02-24 14:12
i found out the issue and its solution can i work on this issue this is my 1st contribution though😁

**Comment by aniruddhapw** [comment] 2023-02-24 17:21
Can i work on this issue

**Comment by ishaan9006** [comment] 2023-02-26 20:36
Hey! In which file is the code present?

**Comment by Apu655** [comment] 2023-02-27 04:28
This problem can be fixed in multiple ways. We can use text-wrapping to fix this or we can move the bell notification icon a little bit so that the tooltip text gets adjusted whenever we hover. I would love to contribute to this issue if I am assigned to it.
Thank you.

**Comment by lohargaurav00** [comment] 2023-02-27 04:34
> @dudanogueira Hey! I can surely fix this issue but I'm new to open source and don't know which file the code is present in. Please help.

this is the file path where you can find the source code -packages > livechat > src > components > Tooltip >index.js

this is the function 
![image](https://user-images.githubusercontent.com/114788180/221474832-f1430f0c-b346-4feb-abe8-3fb0e7255f15.png)

i think this enough to help you and getting started dont forget to setup dev environment.

**Comment by XpertWebApp** [comment] 2023-02-27 05:24
I have solved this problem and pushed code to new branch ,
![Screenshot from 2023-02-24 14-52-29](https://user-images.githubusercontent.com/68045060/221481146-9deb81b4-3769-4170-84f5-6883940370f5.png)

**Comment by lohargaurav00** [comment] 2023-02-27 06:16
> I have solved this problem and pushed code to new branch ,
> ![Screenshot from 2023-02-24 14-52-29](https://user-images.githubusercontent.com/68045060/221481146-9deb81b4-3769-4170-84f5-6883940370f5.png)
> 

Actually your pr check is failed you didn't **signed contract** and aslo you need to **add issue tag**

**Comment by SanaSultana1234** [comment] 2023-03-01 17:58
Please assign me this issue I have got just a one liner fix for this code.

**Comment by garvitkhandelwal** [comment] 2023-03-10 08:53
Is this issue still open or resolved?

**Comment by nitishsh1** [comment] 2023-03-10 13:45
@dudanogueira i am new to open source projects and i want to work on this issue. can you assign me this?

**Comment by AdityaLahane-2003** [comment] 2023-03-10 14:14
I want to work on this issue. 
 Please assign me this issue !

**Comment by garvitkhandelwal** [comment] 2023-03-10 18:21
@hugocostadev Can we directly work on an issue if it's not assigned to anyone and has been open for long?

**Comment by lohargaurav00** [comment] 2023-03-15 15:44
> Hi guys! Feel free to work on whatever issues you find interesting! Thanks for your contribution
> Anyone can assign itself in the issue

I can't develop development environment it saying some packages are missing

**Comment by vaibhavchobisa** [comment] 2023-03-21 03:50
Hi @dudanogueira , @hugocostadev 

I am getting the following error while running `yarn testunit`:
ERROR: command finished with error: command (apps/meteor) yarn run testunit exited (3)
command (apps/meteor) yarn run testunit exited (3)

Kindly help me with the same.

**Comment by vaibhavchobisa** [comment] 2023-03-21 03:51
Hi @dudanogueira , @hugocostadev

I am getting the following error while running `yarn testunit`:
ERROR: command finished with error: command (apps/meteor) yarn run testunit exited (3)
command (apps/meteor) yarn run testunit exited (3)

It would great of you if you could help me with the same.

**Comment by vaibhavchobisa** [comment] 2023-04-18 13:15
Hi @dudanogueira, @hugocostadev

Can you please provide the required **_'1 approving review'_** so that my PR can be accepted and the fix can go live?

Thanks.

**Comment by hugocostadev** [comment] 2023-06-19 14:37
> Hi @dudanogueira, @hugocostadev
> 
> Can you please provide the required **_'1 approving review'_** so that my PR can be accepted and the fix can go live?
> 
> Thanks.

Sorry... just did

**Comment by hugocostadev** [comment] 2023-06-19 18:04
let's follow up on this: https://github.com/RocketChat/Rocket.Chat/pull/28181

**Closed** 2023-07-04 17:45 UTC
Labels: type: bug, subj: ui/ux, contrib: good first issue, subj: livechat
