### ISSUE TITLE
RTL .main-content gets wrong position after closing toolbar

### ISSUE THREAD

**Issue by samuelgozi** [RocketChat/Rocket.Chat#3893] opened 2016-08-02 12:10 UTC
I just tested the chat in your homepage, and i'm using an rtl language.
A small issue happens when i open a menu item from the left(in RTL) toolbar and then close it.
the .main-content class gets a "right: 40px" instead of "left: 40px", it breaks the app for all rtl users, since you can't see messages and the beginning of your messages.

**Comment by SafaAlfulaij** [comment] 2016-08-06 15:16
Duplicate of #3714

**Closed** 2016-08-08 13:36 UTC
