### ISSUE TITLE
 4.4.0 Upgrade: http(s)_proxy env variables not working anymore

### ISSUE THREAD

**Issue by bellegarde-c** [RocketChat/Rocket.Chat#24350] opened 2022-01-30 14:22 UTC
### Description:

RocketChat is unable to use a http proxy anymore.

May be related to Meteor upgraded from v2.2 to v2.5.

### Steps to reproduce:

RocketChat started with configured env (http_proxy/https_proxy)

```
[Unit]
Description=The Rocket.Chat server
After=network.target mongod.service
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=http_proxy=http://srv-proxy-1.********************:3128 https_proxy=http://srv-proxy-1.********************:3128 MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=https://rocket****************** PORT=3001
[Install]
WantedBy=multi-user.target
```

### Expected behavior:

Application store is working, external image downloader is working.

### Actual behavior:

Connection error

### Server Setup Information:

- Version of Rocket.Chat Server:  4.4.0
- Operating System: Debian 11
- Deployment Method: manual
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: 14.18.3
- MongoDB Version:4.2.17

### Client Setup Information

- Desktop App or Browser Version: Firefox last version
- Operating System: Linux

### Additional context

Worked with 4.3.x

### Relevant logs:
```
{"level":50,"time":"2022-01-30T14:19:01.133Z","pid":10159,"hostname":"srv-rocket","name":"","name":"System","err":{"type":"FetchError","message":"request to https://cloud.rocket.chat/api/oauth/token failed, reason: connect ECONNREFUSED 51.81.11.198:443","stack":"FetchError: request to https://cloud.rocket.chat/api/oauth/token failed, reason: connect ECONNREFUSED 51.81.11.198:443\n    at ClientRequest.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/fetch/node_modules/node-fetch/lib/index.js:1444:11)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","errno":"ECONNREFUSED","code":"ECONNREFUSED","name":"FetchError"},"msg":"request to https://cloud.rocket.chat/api/oauth/token failed, reason: connect ECONNREFUSED 51.81.11.198:443"}
{"level":50,"time":"2022-01-30T14:19:01.136Z","pid":10159,"hostname":"srv-rocket","name":"","name":"System","err":{"type":"FetchError","message":"request to https://cloud.rocket.chat/api/oauth/token failed, reason: connect ECONNREFUSED 51.81.11.198:443","stack":"FetchError: request to https://cloud.rocket.chat/api/oauth/token failed, reason: connect ECONNREFUSED 51.81.11.198:443\n    at ClientRequest.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/fetch/node_modules/node-fetch/lib/index.js:1444:11)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","errno":"ECONNREFUSED","code":"ECONNREFUSED","name":"FetchError"},"msg":"request to https://cloud.rocket.chat/api/oauth/token failed, reason: connect ECONNREFUSED 51.81.11.198:443"}
{"level":40,"time":"2022-01-30T14:19:01.173Z","pid":10159,"hostname":"srv-rocket","name":"","name":"Rocket.Chat Apps","msg":"Unable to access Marketplace. Does the server has access to the internet? 'request to https://marketplace.rocket.chat/v1/apps failed, reason: connect ECONNREFUSED 51.81.11.138:443'"}
```

**Comment by ankar84** [comment] 2022-01-31 09:49
I can confirm that issue.
We are using http_proxy and https_proxy env vars in docker deployment and link preview don't work in 4.4.0
![image](https://user-images.githubusercontent.com/4023037/151771990-3311a864-2c73-48e8-a3a8-db22db9272f7.png)

**Comment by binarydad** [comment] 2022-02-02 21:23
Same exact issue here.

**Comment by sampaiodiego** [comment] 2022-02-07 21:17
I'm having a hard time on how to test this issue.. I don't have a proper environment behind a proxy to test this and make sure the fix is good..

any hint on how to easily get an environment to test?

**Comment by bellegarde-c** [comment] 2022-02-07 22:01
IMO, the simplest way is to install tinyproxy and configure it on localhost.

**Comment by bombaata** [comment] 2022-02-23 11:31
Same issue here.
Push notifications are also unavailable.

```
{"level":30,"time":"2022-02-23T10:47:46.318Z","pid":5050,"hostname":"xxxxxx","name":"","name":"Push","msg":"Trying sending push to gateway again in 120000 'milliseconds'"}
{"level":50,"time":"2022-02-23T10:47:47.449Z","pid":5050,"hostname":"xxxxxx","name":"","name":"Push","msg":"Error sending push to gateway (4 try) -> {\"message\":\"network timeout at: https://gateway.rocket.chat/push/gcm/send\",\"type\":\"request-timeout\"}"}
```

RC 4.4.2

**Comment by ankar84** [comment] 2022-03-03 04:54
Still an issue in 4.5.0
```
I20220302-08:56:31.072(0) Exception in defer callback: FetchError: request to https://ya.ru/ failed, reason: connect ETIMEDOUT 87.250.250.242:443     at ClientRequest.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/fetch/node_modules/node-fetch/lib/index.js:1444:11)     at ClientRequest.emit (events.js:400:28)     at ClientRequest.emit (domain.js:475:12)     at TLSSocket.socketErrorListener (_http_client.js:475:9)     at TLSSocket.emit (events.js:400:28)     at TLSSocket.emit (domain.js:475:12)     at emitErrorNT (internal/streams/destroy.js:106:8)     at emitErrorCloseNT (internal/streams/destroy.js:74:3)     at processTicksAndRejections (internal/process/task_queues.js:82:21)  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/oembed/server/server.js:104:16     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Object.OEmbed.getUrlMeta (app/oembed/server/server.js:152:26)     at app/oembed/server/server.js:216:22     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/oembed/server/server.js:269:14     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/oembed/server/server.js:302:25     at Callbacks.runOne (lib/callbacks.ts:214:11)     at lib/callbacks.ts:257:11     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)     at packages/meteor.js:555:25     at runWithEnvironment (packages/meteor.js:1320:24) {   type: 'system',   errno: 'ETIMEDOUT',   code: 'ETIMEDOUT' } 
```

**Comment by m4z** [comment] 2022-03-04 13:46
Might be related: after restart, 4.4.1 throws multiple errors like this:
```
Mar  4 12:33:46 trolls.stage.mydomain.example rocketchat[20746]: Warning: language  is not supported in this project, fallback language (en)                                                                           
Mar  4 12:33:47 trolls.stage.mydomain.example rocketchat[20746]: Warning: language  is not supported in this project, fallback language (en)                                                                           
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]: Exception in defer callback: FetchError: request to https://go.rocket.chat/i/mongodb-deprecated failed, reason: connect ECONNREFUSED 51.81.11.198:443 
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at ClientRequest.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/fetch/node_modules/node-fetch/lib/index.js:1444:11)        
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at ClientRequest.emit (events.js:400:28)                                                                                                          
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at ClientRequest.emit (domain.js:475:12)                                                                                                          
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at TLSSocket.socketErrorListener (_http_client.js:475:9)                                                                                          
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at TLSSocket.emit (events.js:400:28)                                                                                                              
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at TLSSocket.emit (domain.js:475:12)                                                                                                              
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at emitErrorNT (internal/streams/destroy.js:106:8)                                                                                                
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at emitErrorCloseNT (internal/streams/destroy.js:74:3)                                                                                            
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at processTicksAndRejections (internal/process/task_queues.js:82:21)                                                                              
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:  => awaited here:                                                                                                                                     
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)  
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at app/oembed/server/server.js:104:16                                                                                                             
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40                               
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:  => awaited here:                                                                                                                                     
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)  
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at Object.OEmbed.getUrlMeta (app/oembed/server/server.js:152:26)                                                                                  
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at app/oembed/server/server.js:216:22                                                                                                             
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40                               
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:  => awaited here:                                                                                                                                     
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)  
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at app/oembed/server/server.js:269:14                                                                                                             
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40                               
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:  => awaited here:                                                                                                                                     
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at Function.Promise.await (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)  
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at app/oembed/server/server.js:302:25                                                                                                             
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at Callbacks.runOne (lib/callbacks.ts:214:11)                                                                                                     
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at lib/callbacks.ts:257:11                                                                                                                        
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)                                                                          
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at packages/meteor.js:555:25                                                                                                                      
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:     at runWithEnvironment (packages/meteor.js:1320:24) {                                                                                              
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:   type: 'system',                                                                                                                                     
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:   errno: 'ECONNREFUSED',                                                                                                                              
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]:   code: 'ECONNREFUSED'                                                                                                                                
Mar  4 12:33:49 trolls.stage.mydomain.example rocketchat[20746]: }
```

My suspicion is that it is trying to use the http proxy, not the separately defined https proxy.

(Might also be related to RocketChat/install.sh/issues/57)

**Comment by bellegarde-c** [comment] 2022-03-08 16:05
> I'm having a hard time on how to test this issue.. I don't have a proper environment behind a proxy to test this and make sure the fix is good..
> 
> any hint on how to easily get an environment to test?

Did you find time to fix this ? Do you have a patch I can test ? We are locked to 4.3 for now.

**Comment by ankar84** [comment] 2022-03-09 04:00
> We are locked to 4.3 for now.

Same for us.
We can't upgrade with not working proxy functionality.

**Comment by bellegarde-c** [comment] 2022-03-10 12:25
I used https://packages.debian.org/source/bullseye/proxychains-ng until this one is fixed.

**Comment by ankar84** [comment] 2022-03-15 08:31
@dudanogueira @debdutdeb please check this issue. It without attention for a month now. Please escalate it to back-end team.

**Comment by sampaiodiego** [comment] 2022-03-15 18:55
I give this a try again but I still cannot get an environment with internet access only via proxy..

I tried setting up `tinyproxy` as suggested by @bellegarde-c but I couldn't get it to work as I was expecting (maybe I had the wrong expectations)..

any hints on how to get this env up? anyways I'll try to come up with a PR with a possible fix, but I may rely on someone else to validate it, which is not ideal :/

**Comment by bellegarde-c** [comment] 2022-03-15 19:24
@sampaiodiego It's proxychains4, not tinyproxy.

proxychains4.conf mandatory part:
```
...
localnet 127.0.0.0/255.0.0.0
localnet YouLocalNetwork/YouLocalNetworkMask
....
[ProxyList]
http  proxy_ip proxy_port
```

and rocket service:
```
[Unit]
Description=The Rocket.Chat server
After=network.target mongod.service
[Service]
ExecStart=/usr/bin/proxychains /usr/local/bin/node /opt/Rocket.Chat/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat?replicaSet=rs01 MONGO_OPLOG_URL=mongodb://localhost:27017/local?replicaSet=rs01 ROOT_URL=https://******************* PORT=3001
[Install]
WantedBy=multi-user.target
```

**Comment by ankar84** [comment] 2022-03-16 08:06
> Hey have you guys tried `HTTP[S]_PROXY` - basically capitalizing the variable?

Hey @debdutdeb 
I confirm @stefan7018 information - capitalized variable not a fix
![image](https://user-images.githubusercontent.com/4023037/158544444-bcfdf140-9e7e-4f33-82cd-c80402823c97.png)

**Comment by stefan7018** [comment] 2022-03-22 23:03
Still an issue in RC 4.5.3.
Any news when it will be fixed? Or is an patch available for some testing?

**Comment by ankar84** [comment] 2022-03-23 03:51
@sampaiodiego that issue is a blocker to upgrade to new versions of Rocket.Chat. I'm still on 4.3.3 and have no ways to upgrade while proxy not supported.
I'm sure that many companies around the World have managed Internet access via proxy servers, so it is a really critical problem for a wide amount of Rocket.Chat community.
Please fix that.

**Comment by ankar84** [comment] 2022-03-23 04:16
> any hints on how to get this env up? anyways I'll try to come up with a PR with a possible fix, but I may rely on someone else to validate it, which is not ideal :/

Diego, I can test some docker image with possible fix. I'm ready for that in any time. You can ping me at open server.

**Comment by ankar84** [comment] 2022-03-23 04:57
Hey, community!
What do you think if it could be related to [changes in meteor 2.3](https://docs.meteor.com/changelog.html#breakingchanges-10)
```
Meteor Changelog, v2.3, 2021-06-24, Breaking changes

Internally http has been replaced by fetch, should still work as previous version, but edge cases might be different. This is to aid you in transition to fetch. Note that this means that the npmRequestOptions parameter to [HTTP.call](http://http.call/) has been removed, as request is no longer used internally.
```
And if so, if that [fetch-with-proxy package](https://www.npmjs.com/package/fetch-with-proxy) could be a fix for that issue?

@debdutdeb what do you think?

**Comment by debdutdeb** [comment] 2022-03-23 04:59
This indeed is related to meteor update, we're aware. But, if you look at Diego's messages here, the problem is that he hasn't been able to reliably test this.  

I'll have a quick chat with him tonight as soon as I get back.

**Comment by ankar84** [comment] 2022-03-23 05:12
Here is a issue about proxy support in node-fetch module https://github.com/node-fetch/node-fetch/issues/195

**Comment by ankar84** [comment] 2022-03-23 05:29
> But, if you look at Diego's messages here, the problem is that he hasn't been able to reliably test this.

Hey, Deb!

You have a few test deployments. Can you reconfigure one if them to use proxy, and Diego can test his fix there?

**Closed** 2022-04-07 12:40 UTC
Labels: bug

**Comment by danel1** [comment] 2022-04-07 12:46
@sampaiodiego @pierre-lehnen-rc Could you please backport this fix for 4.5.6? We want to stay on 4.5.x for stability issues and really need that fix. Would be much appreciated!

**Comment by sampaiodiego** [comment] 2022-04-07 12:57
sure @danel1 .. 👍

**Comment by ankar84** [comment] 2022-04-08 03:37
@sampaiodiego @pierre-lehnen-rc issue still not fixed actually

On link preview get error:
```
I20220408-03:33:50.754(0) Exception in defer callback: FetchError: request to https://github.com/RocketChat/Rocket.Chat/issues/24350 failed, reason: write EPROTO 139838169614208:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:      at ClientRequest.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/fetch/node_modules/node-fetch/lib/index.js:1444:11)     at ClientRequest.emit (events.js:400:28)     at ClientRequest.emit (domain.js:475:12)     at onerror (/app/bundle/programs/server/npm/node_modules/agent-base/dist/src/index.js:115:21)     at callbackError (/app/bundle/programs/server/npm/node_modules/agent-base/dist/src/index.js:134:17)     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/oembed/server/server.js:103:16     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Object.OEmbed.getUrlMeta (app/oembed/server/server.js:152:26)     at app/oembed/server/server.js:216:22     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/oembed/server/server.js:269:14     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at app/oembed/server/server.js:302:25     at Callbacks.runOne (lib/callbacks.ts:221:11)     at lib/callbacks.ts:264:11     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)     at packages/meteor.js:555:25     at runWithEnvironment (packages/meteor.js:1320:24) {   type: 'system',   errno: 'EPROTO',   code: 'EPROTO' } 

```

On open Marketplace

```
{"level":40,"time":"2022-04-08T03:31:15.361Z","pid":9,"hostname":"4b292c2b68a4","name":"Rocket.Chat Apps","msg":"Unable to access Marketplace. Does the server has access to the internet? 'request to https://marketplace.rocket.chat/v1/apps failed, reason: write EPROTO 140224724293504:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:<br>'"} 


```
