### ISSUE TITLE
Improvement: Hiding all direct messages with a single button

### ISSUE THREAD

**Issue by Myrthian** [RocketChat/Rocket.Chat#14003] opened 2019-04-04 07:27 UTC
Description:
- Currently it's only possible to hide direct messages one at a time to prevent the Direct Messages list from getting large

Use case:
- I constantly chat with different people to ask questions/give feedback etc., but those conversations are finished rather quickly, and yet to get them out of the list of Direct Messages I have to manually hide every single chat

Expected result:
- I want a button to be able to hide every chat at the end of the day to start the next day with a "clean slate" as far as Direct Messages are concerned, especially considering a chat will be visible again if something new is happening in it

**Comment by mohamedar97** [comment] 2019-04-07 01:39
working on it

**Comment by engelgabriel** [comment] 2020-05-25 17:39
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/14003

**Closed by engelgabriel** 2020-05-25 17:39 UTC
