### ISSUE TITLE
Message Info box (read receipts) no longer working

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#22305] opened 2021-06-10 06:41 UTC
### Description:

Info box blank, no longer working

![read](https://user-images.githubusercontent.com/1122344/121476813-749f1b00-ca0a-11eb-9ac3-9459088c37c8.PNG)

Previously:

![info](https://user-images.githubusercontent.com/1122344/121476853-7d8fec80-ca0a-11eb-9953-19f6224fdd1e.PNG)
![example](https://user-images.githubusercontent.com/1122344/121476871-81237380-ca0a-11eb-8ecc-c43b9ed1721e.PNG)

### Steps to reproduce:

1. Click on "Info"

### Expected behavior:

Details read info

### Actual behavior:

Box blank

### Server Setup Information:

- Version of Rocket.Chat Server: 3.14.5
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method: TAR
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.22.1
- MongoDB Version: 4.0.24

### Client Setup Information

- Desktop App or Browser Version: N/A
- Operating System: N/A

### Additional context

N/A

### Relevant logs:

None

**Comment by urosino** [comment] 2021-06-10 08:57
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/22268.

**Comment by ankar84** [comment] 2021-06-10 09:21
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/21861 and fixed by https://github.com/RocketChat/Rocket.Chat/pull/22203

**Comment by johncrisp** [comment] 2021-06-10 09:47
And closing as a duplicate

**Closed by johncrisp** 2021-06-10 09:47 UTC
