### ISSUE TITLE
[BUG] [OTR] Message notification print wrong message text in OTR mode in Firefox 55 

### ISSUE THREAD

**Issue by mnlbox** [RocketChat/Rocket.Chat#7924] opened 2017-08-27 13:04 UTC
I test Rocket.Chat Version: 0.59.0-develop and in OTR message find this issue.
When I used Firefox 55 it's notification shows like this:
![otr1](https://user-images.githubusercontent.com/25859075/29750036-c401558c-8b4d-11e7-95cc-7246796dff37.png)
for this message:
![otr2](https://user-images.githubusercontent.com/25859075/29750039-cb4e2d10-8b4d-11e7-8b29-eb08e28c59d0.png)
But it's same output for I used Rocket.Chat Version: 0.59.0-develop:
![otr3](https://user-images.githubusercontent.com/25859075/29750048-e3b6074c-8b4d-11e7-8870-42d1043fe600.png)
for this message:
![otr4](https://user-images.githubusercontent.com/25859075/29750049-e9b1a62e-8b4d-11e7-8ddc-03670aa0a859.png)

**Comment by MartinSchoeler** [comment] 2017-08-29 19:20
@mnlbox could you try to refresh your keys and see if the problem persists?

**Comment by mnlbox** [comment] 2017-08-31 10:12
@rodrigok I'm using Linux. @MartinSchoeler It's fixed now. What is the related PR.
I can't found it :thinking:

**Comment by MartinSchoeler** [comment] 2017-08-31 19:13
@mnlbox this can be caused by changing browsers having the user logged on both browser, since the keys are in the browser session, changing to another browser will remove your ability to decrypt messages in that browser. I will close this for now, if this starts to happens again, please reopen this.

**Closed by MartinSchoeler** 2017-08-31 19:13 UTC
Labels: stat: waiting response, type: bug
