### ISSUE TITLE
Overlapping views

### ISSUE THREAD

**Issue by Julime** [RocketChat/Rocket.Chat#1906] opened 2016-01-14 08:41 UTC
im on room general > click on my name > administration > permissions (same effect with rooms etc.) > click on administation to close the menu > general > click on my name > administration > permissions > screenshot

![capturfiles_1](https://cloud.githubusercontent.com/assets/7944656/12319470/d6c89982-baa2-11e5-8034-984484909d33.png)

**Comment by marceloschmidt** [comment] 2016-01-14 11:41
This has been accompanying us for a long time already, but we haven't succeeded on tracking it down. It usually happens when you switch views too fast. We have to figure out why the previous room was not cleared from screen,.

**Comment by Julime** [comment] 2016-01-14 12:07
ive seen it some times mith switching views fast, but this one does not seem to be time related

**Comment by marceloschmidt** [comment] 2016-01-14 12:31
Duplicate of #1221

**Closed by marceloschmidt** 2016-01-14 12:31 UTC
Labels: subj: ui/ux, type: bug
