### ISSUE TITLE
Jitsi call ends when opening another chat window

### ISSUE THREAD

**Issue by panholzerp** [RocketChat/Rocket.Chat#9495] opened 2018-01-25 07:32 UTC
### Description:
When in a Jitsi call, the call ends when the user clicks on another chat.

### Steps to Reproduce:

1. Start a Jitsi call with user A
2. Click on Chat with user B

### Expected behavior:

Prefered: Call continues, it is possible to keep talking to user A while reading information from user B. Call status is available when in chat window of user B.

Alternative: At least rocket.chat warns that the call will end. Additionally there is a button to move the call to another tab so that the call can be continued.

### Actual behavior:

Call ends when opening the chat with user B. As a work around, users can manually open a second rocket.chat window, but this is not satisfying.

**Comment by tassoevan** [comment] 2019-01-12 19:38
Duplicate of #4586.

**Closed by tassoevan** 2019-01-12 19:38 UTC
