### ISSUE TITLE
Voice message has no audio

### ISSUE THREAD

**Issue by vibhi19** [RocketChat/Rocket.Chat#14032] opened 2019-04-07 19:52 UTC
I setup rocket chat on my server using snap. I am trying to send voice msg but there is no voice can someone tell me how to fix it

**Comment by reetp** [comment] 2019-04-18 17:25
@rocket-cat close

Please, always search for existing issues.

Probably a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/10530

The likely fix is wait for the release of v1.0.0

**Closed by reetp** 2019-04-18 17:25 UTC
