### ISSUE TITLE
After update to 7.0.0 Jitsi does not work

### ISSUE THREAD

**Issue by djfroggy81** [RocketChat/Rocket.Chat#33987] opened 2024-11-19 07:04 UTC
### Description:

After upgrading from 6.13 to 7.0.0 with Jitsi installed, jitsi stopped working.
Uninstalled jitsi.
Trying to reinstall leads to an error in the log:
ubprocess stderr error: TypeScript files are not supported in npm packages: file:///opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts

### Steps to reproduce:

1. update using official upgrade instructions
2. Start call, get error
3. Go to market and delete jitsi
4. Install jitsi, installation does not finish
5. Go to journal ctl and get error

### Expected behavior:

The application should work and the call should be made.

### Actual behavior:

Call not started after upgrade

### Server Setup Information:

- Version of Rocket.Chat Server: 7.0.0
- License Type: Community
- Number of Users: 10
- Operating System: Ubuntu 22.04
- Deployment Method: local install https://docs.rocket.chat/docs/deploy-with-ubuntu
- Number of Running Instances: 1
- DB Replicaset Oplog: rocket
- NodeJS Version: v20.18.0
- MongoDB Version: 6.0.19

### Client Setup Information

- Desktop App or Browser Version: Chrome 130.0.6723.119
- Operating System: Windows 10

### Relevant logs:
ubprocess stderr error: TypeScript files are not supported in npm packages: file:///opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/apps-engine/deno-runtime/main.ts

**Comment by reetp** [comment] 2024-11-19 13:37
Did you add Deno as per the docs?

Why don't you name life easier on yourself and use docker or snaps?

You will have far less problems.

**Comment by djfroggy81** [comment] 2024-11-19 14:49
YES
command executed under user rocketchat:

$ echo $DENO_DIR
$ /home/rocketchat/.cache/deno
$ deno -v
$ deno 2.0.6

**Comment by reetp** [comment] 2024-11-19 15:56
You didn't read the docs.

> Install Deno
> Deploying Rocket.Chat requires [Deno](https://deno.com/).  
> Only Deno versions >=1.37.1 and <2.0.0 are supported.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Closing as duplicate of #33935 

As per this:

https://github.com/RocketChat/Rocket.Chat/issues/33140#issuecomment-246895980433140

**Comment by reetp** [comment] 2024-11-19 15:57
And closing.

**Closed by reetp** 2024-11-19 15:57 UTC
Labels: duplicate
