### ISSUE TITLE
where to delete old livechat conversation

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#6346] opened 2017-03-13 14:50 UTC
Rocket.Chat Version: 0.52.0

Just played around with livechat, but I can't find a way to delete closed livechat conversations as admin nor as live chat manager.

**Comment by FibreFoX** [comment] 2017-03-18 21:07
This might be a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/6294

> It would be incredibly useful if we could delete all livechats or delete some of them.

**Comment by sampaiodiego** [comment] 2017-06-06 13:00
closing this in favor of #5481

**Closed by sampaiodiego** 2017-06-06 13:00 UTC
Labels: feat: livechat, type: support

**Comment by GetGeeks** [comment] 2018-01-29 05:06
still looking for this feature .... is there progress on this?
