### ISSUE TITLE
Error: Must pass options.rootUrl or set ROOT_URL in the server environment

### ISSUE THREAD

**Issue by mediatomcat** [RocketChat/Rocket.Chat#13054] opened 2018-12-29 17:50 UTC
Hi,

I have created a new Centos 7 box and followed the step laid out in the getting started guide, line by line.  
https://rocket.chat/docs/installation/manual-installation/centos/

When I try and run the app I get the following error.  Mongo is running, I checked the config file and the ROOT_URL is set.  Any ideas what might be wrong? 

(I should add I get no errors when setting up the server or following the steps in the guide)

    [root@rocketchat Rocket.Chat]# /usr/local/bin/node /opt/Rocket.Chat/main.js
    /opt/Rocket.Chat/programs/server/boot.js:475
     }).run();
    ^

    Error: Must pass options.rootUrl or set ROOT_URL in the server environment
        at Object.Meteor.absoluteUrl (packages/meteor.js:1448:11)
        at runWebAppServer (packages/webapp/webapp_server.js:762:18)
        at webapp_server.js (packages/webapp/webapp_server.js:1163:1)
        at fileEvaluate (packages/modules-runtime.js:336:7)
        at Module.require (packages/modules-runtime.js:238:14)
        at require (packages/modules-runtime.js:258:21)
        at /opt/Rocket.Chat/programs/server/packages/webapp.js:1579:15
        at /opt/Rocket.Chat/programs/server/packages/webapp.js:1588:3
        at /opt/Rocket.Chat/programs/server/boot.js:411:36
        at Array.forEach (<anonymous>)
        at /opt/Rocket.Chat/programs/server/boot.js:220:19
        at /opt/Rocket.Chat/programs/server/boot.js:471:5
        at Function.run (/opt/Rocket.Chat/programs/server/profile.js:510:12)
        at /opt/Rocket.Chat/programs/server/boot.js:470:11

**Comment by mediatomcat** [comment] 2018-12-29 18:02
Resolved.  Some reason you have to export the paths:

    export ROOT_URL=http://your-server_IP:3000/
    export MONGO_URL=mongodb://localhost:27017/rocketchat
    export PORT=3000

**Comment by reetp** [comment] 2019-01-04 01:22
You are trying to run rocket natively and not via a systemd unit file as per the documentation from the looks of things. You should not have to run it with 'node main.js'

Please go back and reads the section:
"Configure the Rocket.Chat service"
https://rocket.chat/docs/installation/manual-installation/centos/

If that doesn't work correctly then please tell us what happened. If it works as expected then please close this bug.

**Comment by 21let** [comment] 2019-01-09 09:33
According to the manual, I did so too, and the problem is probably at this step:

`
echo -e "[Unit]\nDescription=The Rocket.Chat server\nAfter=network.target remote-fs.target nss-lookup.target nginx.target mongod.target\n[Service]\nExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js\nStandardOutput=syslog\nStandardError=syslog\nSyslogIdentifier=rocketchat\nUser=rocketchat\nEnvironment=LD_PRELOAD=/opt/Rocket.Chat/programs/server/npm/node_modules/sharp/vendor/lib/libz.so NODE_ENV=production MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=http://your-host-name.com-as-accessed-from-internet:3000/ PORT=3000\n[Install]\nWantedBy=multi-user.target" | sudo tee /usr/lib/systemd/system/rocketchat.service
`

this will do the following:

`
[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target nginx.target mongod.target
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/bundle/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=LD_PRELOAD=/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/sharp/vendor/lib/libz.so NODE_ENV=production MONGO_URL=mongodb://localhost:27017/rocketchat ROOT_URL=http://your-host-name.com-as-accessed-from-internet:3000/ PORT=3000
[Install]
WantedBy=multi-user.target
`

**Comment by 21let** [comment] 2019-01-09 09:45
[root@komunikace ~]# /usr/local/bin/node /opt/Rocket.Chat/bundle/main.js
/opt/Rocket.Chat/bundle/programs/server/boot.js:475
}).run();
   ^

Error: Must pass options.rootUrl or set ROOT_URL in the server environment
    at Object.Meteor.absoluteUrl (packages/meteor.js:1448:11)
    at runWebAppServer (packages/webapp/webapp_server.js:762:18)
    at webapp_server.js (packages/webapp/webapp_server.js:1163:1)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /opt/Rocket.Chat/bundle/programs/server/packages/webapp.js:1579:15
    at /opt/Rocket.Chat/bundle/programs/server/packages/webapp.js:1588:3
    at /opt/Rocket.Chat/bundle/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /opt/Rocket.Chat/bundle/programs/server/boot.js:220:19
    at /opt/Rocket.Chat/bundle/programs/server/boot.js:471:5
    at Function.run (/opt/Rocket.Chat/bundle/programs/server/profile.js:510:12)
    at /opt/Rocket.Chat/bundle/programs/server/boot.js:470:11
[root@komunikace ~]# export ROOT_URL=http://192.168.2.169:3000/
[root@komunikace ~]# export PORT=3000
[root@komunikace ~]# export MONGO_URL=mongodb://localhost:27017/rocketchat
[root@komunikace ~]# service rocketchat start
Redirecting to /bin/systemctl start rocketchat.service
Warning: rocketchat.service changed on disk. Run 'systemctl daemon-reload' to reload units.
[root@komunikace ~]# systemctl daemon-reload
[root@komunikace ~]# service rocketchat start
Redirecting to /bin/systemctl start rocketchat.service
[root@komunikace ~]# service rocketchat status
Redirecting to /bin/systemctl status rocketchat.service
● rocketchat.service - The Rocket.Chat server
   Loaded: loaded (/usr/lib/systemd/system/rocketchat.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-01-09 10:42:45 CET; 1s ago
  Process: 17020 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/bundle/main.js (code=exited, status=1/FAILURE)
 Main PID: 17020 (code=exited, status=1/FAILURE)

Jan 09 10:42:45 komunikace.local systemd[1]: Started The Rocket.Chat server.
Jan 09 10:42:45 komunikace.local systemd[1]: rocketchat.service: main process exited, code=exited, status=1/FAILURE
Jan 09 10:42:45 komunikace.local systemd[1]: Unit rocketchat.service entered failed state.
Jan 09 10:42:45 komunikace.local systemd[1]: rocketchat.service failed.
[root@komunikace ~]# /usr/local/bin/node /opt/Rocket.Chat/bundle/main.js
Updating process.env.MAIL_URL
Starting Email Intercepter...
LocalStore: store created at
LocalStore: store created at
LocalStore: store created at
LocalStore: store created at
LocalStore: store created at
LocalStore: store created at
Setting default file store to GridFS
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
{"line":"121","file":"migrations.js","message":"Migrations: Not migrating, already at version 137","time":{"$date":1547027022467},"level":"info"}
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
Loaded the Apps Framework and loaded a total of 0 Apps!
Exception in callback of async function: { Error: listen EADDRINUSE 0.0.0.0:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at doListen (net.js:1505:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000 }
➔ System ➔ startup
➔ +---------------------------------------------------+
➔ |                   SERVER RUNNING                  |
➔ +---------------------------------------------------+
➔ |                                                   |
➔ |  Rocket.Chat Version: 0.73.2                      |
➔ |       NodeJS Version: 8.11.3 - x64                |
➔ |             Platform: linux                       |
➔ |         Process Port: 3000                        |
➔ |             Site URL: http://192.168.2.169:3000/  |
➔ |     ReplicaSet OpLog: Disabled                    |
➔ |          Commit Hash: 8ff0e3da16                  |
➔ |        Commit Branch: HEAD                        |
➔ |                                                   |
➔ +---------------------------------------------------+

**Comment by 21let** [comment] 2019-01-09 10:08
This is function solution:

there is still a need to add mongod.service otherwise the service does not start because of the uninstalled mongodb service.

[Unit]
Description=The Rocket.Chat server
After=network.target remote-fs.target nss-lookup.target mongod.target **mongod.service**
[Service]
ExecStart=/usr/local/bin/node /opt/Rocket.Chat/bundle/main.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=rocketchat
User=rocketchat
Environment=LD_PRELOAD=/opt/Rocket.Chat/bundle/programs/server/npm/node_modules/sharp/vendor/lib/libz.so
Environment=NODE_ENV=production
Environment=MONGO_URL=mongodb://localhost:27017/rocketchat
Environment=ROOT_URL=http://IP_CHANGE:3000/
Environment=PORT=3000
[Install]
WantedBy=multi-user.target

**Comment by reetp** [comment] 2019-02-07 12:21
@rocket-cat close

Closing on the basis of https://github.com/RocketChat/Rocket.Chat/issues/13054#issuecomment-452641856

**Closed by reetp** 2019-02-07 12:21 UTC
