### ISSUE TITLE
something happens, and then I can't hit 'enter' to submit chat messages any more.

### ISSUE THREAD

**Issue by jadeqwang** [RocketChat/Rocket.Chat#2053] opened 2016-01-27 23:27 UTC
I'm not sure what I did to trigger this but in one of my channels, I can no longer submit chat messages. When I hit Enter, Shift+Enter, or [any special key]+enter, this is what happens:

https://www.youtube.com/watch?v=2NKDAE7cJZ8

I tried leaving the room and coming back, to no avail. However, I can still chat in other rooms just fine.

Update: I eventually fixed it by closing the grain and re-opening it.

Update 2: this is on Sandstorm Oasis. I can't seem to add the label myself.

**Comment by kentonv** [comment] 2016-02-17 00:01
FWIW this is unlikely to be Sandstorm-specific.

**Comment by engelgabriel** [comment] 2016-02-17 17:54
It is not  Sandstorm-specific, and it is hard to reproduce. Happened to me before, but I didn't had the time to debug properly.

**Comment by MartinSchoeler** [comment] 2017-03-24 14:49
Hey @jadeqwang , I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Closed by MartinSchoeler** 2017-03-24 14:49 UTC
Labels: subj: ui/ux, type: bug
