### ISSUE TITLE
changing the user name changes access permissions

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#1359] opened 2015-11-09 12:18 UTC
Steps to reproduce:
- create user
- grant additional access permissions
- protect a resource to be accessible with these additional
permissions only
- change user name at /account/profile
- check access to the protected resource

Expected behavior:
- user name changes
- additional access permissions are not affected

Observed behavior:
- user name changes
- additional access permissions are removed

Additional observation:
- changing the user name back restores the additional permissions

Possible impact:
User permissions could be referenced to a value that can be modified
by the user.
Worst case: takeover of user account permissions

**Comment by rwakida** [comment] 2015-11-12 07:07
@sinteur I was not able to reproduce the observed behavior.   Can you elaborate on "grant additional access permissions".  Do you mean you added a new role to the user?  or did you assign a permission to a role assigned to the user?  

I tried to reproduce by:
1. create user, 'tu1'
2. assign new role to user via mongo
```
db.users.update({username:'tu1'}, {$push: {'roles.__global_roles__' : 'newrole'}});
```
3. create new channel (which assigns the channel "moderator" role to tu1)
4. verified in mongodb that tu1 has the moderator role for the channel.
5. change user name at /account/profile
6. Verified that tu1 can change the name of the channel created in step #3.  This means that the tu1 retained the channel "moderator" role.  
7. verified in mongodb that tu1 has  global role, "newrole" and the channel "moderator" role.

@geekgonecrazy were you able to reproduce the problem?

**Comment by sinteur** [comment] 2015-11-12 10:40
I've asked the user to reproduce and he failed to do so  - glitch? Perhaps un-activated accounts treated differently?

**Comment by rwakida** [comment] 2015-11-12 18:56
@sinteur activation shouldn't make a difference in regards to roles/permissions.  I'll close for now, but please reopen if you encounter this again.  Thanks.

**Closed by rwakida** 2015-11-12 18:56 UTC
Labels: feat: roles / permissions, type: bug
