### ISSUE TITLE
backup DB Chat from ADMIN and App Upgrade

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2736] opened 2016-04-01 15:40 UTC
I dont know what issue is open (I Probably posted this as a comment somewhere) I am opening a new issue anyways :) cause i think its really important to backing-up the entire DB from the ADMIN without going into CLI, also ability to upload the setting and DB from local file on your PC via the admin page..  

also another cool feature is to do the Rocket.Chat updates from the App itself and rolling back

**Comment by engelgabriel** [comment] 2016-04-01 18:36
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/758

**Closed by engelgabriel** 2016-04-01 18:36 UTC
