### ISSUE TITLE
there is no update available using snap

### ISSUE THREAD

**Issue by alirezaimi** [RocketChat/Rocket.Chat#10754] opened 2018-05-13 10:49 UTC
### Description:

In the site latest stable version is `rocket.chat-0.64.1.tar` but when i want to update rocket chat using snap there is no update is available.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: debian 4.9.0-6-amd64
* Deployment Method(snap/docker/tar/etc):  snap
* Number of Running Instances: 1
* DB Replicaset Oplog: ?
* Node Version: v4.8.2
* mongoDB Version: 3.2.11-2+deb9u1

### Steps to Reproduce:

    snap refresh rocketchat-server

### Expected behavior:

upgrade it to latest stable version !

### Actual behavior:

no update is available ! 

### Relevant logs:
    root@sp2lnx1chat:~# snap list
    Name               Version    Rev   Tracking  Developer   Notes
    core               16-2.32.6  4571  stable    canonical   core
    rocketchat-server  0.63.3     1254  stable    rocketchat  devmode
    root@sp2lnx1chat:~# snap refresh rocketchat-server
    snap "rocketchat-server" has no updates available

**Comment by kaiiiiiiiii** [comment] 2018-05-13 11:44
Duplicate of #10656

@TwizzyDizzy Thanks!

**Comment by TwizzyDizzy** [comment] 2018-05-13 11:46
@rocket-cat close

**Closed by TwizzyDizzy** 2018-05-13 11:46 UTC
