### ISSUE TITLE
Interface shows only 50 custom emoji

### ISSUE THREAD

**Issue by mide** [RocketChat/Rocket.Chat#15118] opened 2019-08-06 22:01 UTC
### Description:

When a Rocket.Chat installation has more than 50 custom emoji, only the first 50 show with no pagination buttons. Additionally, the search only searches those visible and not the whole set. 

### Steps to reproduce:

1. Go to administration console
1. Click "custom emoj"
1. Add at least 51 emoji. Ideally with names over the spectrum of the alphabet
1. Reload the page, you should not see all emoji. 
1. If you search for an emoji towards the end of the alphabetically sorted list you added, it will not appear. 

### Expected behavior:

I expect to see all emoji or pagination buttons

### Actual behavior:

No pagination buttons, and results capped at 50. 

<img width="1367" alt="Screen Shot 2019-08-06 at 6 00 45 PM" src="https://user-images.githubusercontent.com/546518/62580450-27811980-b874-11e9-9ac5-e1911eba8b34.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 1.2.1
- Operating System: Amazon Linux (Running official Docker Image)
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.4
- MongoDB Version: 4.0.10

**Comment by lorek123** [comment] 2019-08-07 00:47
seems to be fixed in 1.3.0

**Comment by mide** [comment] 2019-08-07 01:46
I still see this behavior, now upgraded to 1.3.0.

**Comment by lorek123** [comment] 2019-08-07 07:49
https://github.com/RocketChat/Rocket.Chat/pull/15119 maybe this will actually fix this ;)

**Comment by reetp** [comment] 2019-08-07 08:13
@rocket-cat label add duplicate

Duplicate of:
https://github.com/RocketChat/Rocket.Chat/issues/14743

Please follow this before opening an Issue:
https://rocket.chat/docs/contributing/reporting-issues

Always test on latest (and you really should not be on 1.2.1 if you check releases.....) and search thoroughly for existing issues

e.g.
https://github.com/RocketChat/Rocket.Chat/issues?utf8=%E2%9C%93&q=is%3Aissue+emoji+50

**Comment by reetp** [comment] 2019-08-07 08:13
@rocket-cat close

**Closed by reetp** 2019-08-07 08:13 UTC
Labels: duplicate

**Comment by mide** [comment] 2019-08-07 10:45
@reetp 

1) I checked the open issues prior to opening, and apparently this was a duplicate of an issue that was closed a month ago. I now see there is an open (not yet merged) PR for the fix (#15119 ), but I wouldn't consider the problem solved. 
2) Within an hour of feedback I DID test on the latest, and I DID confirm this is still happening on latest (the PR with the fix hasn't been merged, nevermind a new version minted).

I have been a user of Rocket.Chat for upwards of three years; I'm not feeling the community there once was.c

**Comment by mide** [comment] 2019-08-07 10:47
@reetp

1) I checked the open issues prior to opening, and apparently this was a duplicate of an issue that was closed a month ago. I now see there is an open (not yet merged) PR for the fix (#15119 ), but I wouldn't consider the problem solved.
1) Within an hour of feedback I DID test on the latest, and I DID confirm this is still happening on latest (the PR with the fix hasn't been merged, nevermind a new version minted).

I have been a user (and a very minor contributor at one point) of Rocket.Chat for upwards of three years; I'm not feeling the community there once was.

**Comment by mide** [comment] 2019-08-07 11:01
I agree I should have tested on latest, shame on me for that. 

But the issue I "duplicated" was closed a month ago (#14743), and the PR with the fix (#15119) was opened ten minutes AFTER I opened this issue. So when I filed, I felt it was still an active issue.

**Comment by reetp** [comment] 2019-08-07 11:24
Sorry - this is not my day job... I just try and help as my contribution back to open source.... I just try and clear duplicates and 'support' Issues so the devs can concentrate on the problematic ones.

I don't check the times on stuff - just do a search for a few key words.

I'm not quite sure what they did with this as there seems to be a a couple PRs etc. Simple answer is that there was a bug there so just follow up on the existing bug rather than create a new one.

I think if you look 14951 was the original fix to 14743 and that was amended by 15119.

That is in Develop and should be out with 1.4.x - you can do yourself a test build and see if it works (and please update to at least 1.2.3 for your own security.... !!!!!)

**Comment by mide** [comment] 2019-08-07 11:54
Thanks for the reply @reetp - It's people like you who make the open source world go 'round. I do appreciate the efforts made to reduce duplicates. 

I have updated to 1.3.0 - Thanks for the heads up :)

**Comment by whalehub** [comment] 2019-08-09 02:11
@reetp @mide I can confirm that this issue has been fixed in v1.3.1 which includes the PR #15119.

**Comment by mide** [comment] 2019-08-09 02:26
Thanks for following up, I will be upgrading shortly.
