### ISSUE TITLE
Changing username will lag everyone that has the chat open

### ISSUE THREAD

**Issue by granttoday** [RocketChat/Rocket.Chat#13498] opened 2019-02-15 21:04 UTC
### Description:

When someone changes their name or avatar it will lag everyone who has the chat open

### Steps to reproduce:

1. Have the chat open for at least 15 minutes with ~8 active people
2. Have someone change their name/avatar
3. Experience major lag

### Expected behavior:

Not to lag

### Actual behavior:

Lag

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.2
- Operating System: CentOS 7
- Deployment Method: Docker
- Number of Running Instances:  1
- DB Replicaset Oplog: Disabled
- NodeJS Version: Docker [r/rocketchat/rocket.chat]
- MongoDB Version: Docker [r/rocketchat/rocket.chat]

**Comment by granttoday** [comment] 2019-02-15 21:07
It might happen when that relevant person has said a lot between other people's messages, as it's trying to update hundreds of elements at once

**Comment by granttoday** [comment] 2019-03-20 22:02
(Bump) This is becoming a bigger issue with the community I have 😅

**Comment by ggazzo** [comment] 2019-10-17 22:19
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/12732

**Closed by ggazzo** 2019-10-17 22:19 UTC
Labels: subj: performance
