### ISSUE TITLE
RootURL pathprefix not working with reverse proxy; (resource paths not all relative)

### ISSUE THREAD

**Issue by klimkowd** [RocketChat/Rocket.Chat#2646] opened 2016-03-25 18:47 UTC
I'm hosting my rocket chat on an external server @ https://domain.com/chat

I'm using the default reverse proxy settings as listed in the instructions -- forwarding requests to http://localhost:3000

However, when I attempt to load rocket chat from https://domain.com/chat i only get a 'Unknown path" response. My ROOT_URL=https://domain.com/chat/. 

Is there any additional starting paramters that can adjust this.  I also noticed that many items like _timesync as well as the sounds and fonts and images are all absolute URLed to '/'

**Comment by engelgabriel** [comment] 2016-03-28 14:26
This depends on https://github.com/RocketChat/Rocket.Chat/pull/2624

**Comment by nobeans** [comment] 2016-04-11 07:10
I'm facing the same problem.

The internal value `__meteor_runtime_config__.ROOT_URL` re-assigned by Rocket.Chat seems wrong.
If you give `ROOT_URL=http://my-domain/foo/bar`, `__meteor_runtime_config__.ROOT_URL` should be `http://my-domain/foo/bar` and `__meteor_runtime_config__.ROOT_URL_PATH_PREFIX` should be `/foo/bar`. But currently `http://my-domain` is set to `__meteor_runtime_config__.ROOT_URL`.

See https://github.com/meteor/meteor/blob/devel/packages/meteor/url_server.js

**Comment by nobeans** [comment] 2016-04-12 04:58
It works well for me so far, though I'm not sure whether MOBILE_ROOT_URL, MOBILE_DDP_URL, etc. should be changed.
https://github.com/nobeans/Rocket.Chat/commit/25fd75375630d15a6d478702147403a2aad61e08

**Comment by nobeans** [comment] 2016-04-12 05:02
`.sandstorm-credentials`, _`timesync` and `tap-i18n/ja.json` are still on the wrong root path like `http://my-domain/.sandstorm-credentials` instead of `http://my-domain/foo/bar.sandstorm-credentials`.

This is my workaround using reverse-proxy:
```
# httpd.conf
ProxyPassMatch (^/.sandstorm-credentials|_timesync|tap-i18n/ja.json) http://my-domain/foo/bar/$1
```

**Comment by rodrigok** [comment] 2016-04-18 14:04
@klimkowd @nobeans can you follow this guide? https://rocket.chat/docs/master/user-guides-running-in-a-sub-folder

**Comment by engelgabriel** [comment] 2016-04-18 14:08
Please reopen the issue if the guide does not work.

**Comment by klimkowd** [comment] 2016-04-18 15:50
I appears the link is dead. Let me know when it's up and i'll give it a try.

**Comment by engelgabriel** [comment] 2016-04-18 16:50
URL updated

**Comment by klimkowd** [comment] 2016-04-18 17:44
Launching it does "work" now but then promptly setting the site url back
to just the domain under Admin->General doesn't make sense to me. (i set it
for the giggles, and yeah it breaks it again.)

Still fails to load _timesync and .sandstorm as expected.

**Comment by engelgabriel** [comment] 2016-04-18 17:51
this is a restriction on the order the framework initiates, so the settings must be done on the environment variables level in order to loaded in time.

**Comment by engelgabriel** [comment] 2016-04-18 17:53
@rodrigok ideas?

**Comment by rodrigok** [comment] 2016-04-18 18:26
@klimkowd is everything working if you use the environment variable and keep the Site URL as `http://your.domain/path/?

**Comment by klimkowd** [comment] 2016-04-18 18:32
For the most part, yes. except for _timesync and .sandstorm. What are the
impacts with those not working?  Also, on a side note.  Do you know what
would cause the following problems?

1.) whenever a new message is displayed is causes the whole chat view to
rerender causing a gross flicker.
2.) whenever I click on a users name to private messag them i get rerouted
to https://domain.com/chat/home

**Comment by engelgabriel** [comment] 2016-04-18 18:36
Can you please try the `develop` branch?

**Comment by rodrigok** [comment] 2016-04-18 18:36
`.sandstorm` isn't a problem.
`_timesync` isn't a problem too, but this we should try to fix, it helps to keep messages in correct order.

for 1 and 2, you should try our develop branch or wait the stable release today.

**Comment by klimkowd** [comment] 2016-04-19 14:36
Okay, I migrated to 0.27. Issue 2 resolved but Issue 1 still exists for me.
I also found that when i start to customize and load new assets the links
are not relative for assets

**Comment by klimkowd** [comment] 2016-04-19 15:14
In addition, emojis are also out of action.

**Comment by rodrigok** [comment] 2016-04-20 01:28
The problems with assets was fixed by https://github.com/RocketChat/Rocket.Chat/commit/6e9a7f7725c284707a1cb9d2fec20e2d0b131d1b

**Comment by rodrigok** [comment] 2016-04-20 01:33
The problem with emoji was fixed by https://github.com/RocketChat/Rocket.Chat/commit/7c81e6d2cbe0b8846a117151001e85ceed985362

**Comment by rodrigok** [comment] 2016-04-20 01:35
@klimkowd I still can't reproduce the view rerender, can you send us one video?

**Comment by klimkowd** [comment] 2016-04-22 14:36
Here <https://i.gyazo.com/504eeaf5976acfb0374540921a834983.gif> is a video
of the rerender
I also found another subdirectory link failure:  /file-upload

**Comment by engelgabriel** [comment] 2016-04-22 14:54
![image](https://cloud.githubusercontent.com/assets/1000217/14745252/da92c93a-0880-11e6-99fe-d8979f41fa9d.png)

Can you stop on the frame of the blink?

**Comment by engelgabriel** [comment] 2016-04-22 15:02
![image](https://cloud.githubusercontent.com/assets/1000217/14745490/f196a2a4-0881-11e6-9d93-0698f7340d31.png)

The problem seems to be that something is generating an invalid date on the client side.. maybe the offset is getting an invalid value and when applied to the date, it generates an invalid date.

**Comment by klimkowd** [comment] 2016-04-22 16:24
[image: Inline image 1]

**Comment by klimkowd** [comment] 2016-04-22 16:27
Tell me where i can set a break point and i'll let you know.

**Comment by engelgabriel** [comment] 2016-04-22 17:18
@klimkowd do you still see the _timesync error on the console?
@rodrigok how can we test this theory? How can we check the value of _timesync?

**Comment by klimkowd** [comment] 2016-04-22 17:26
yes the _timesync 404s are still present

**Comment by engelgabriel** [comment] 2016-04-22 17:39
So they are definitely related.

**Comment by rodrigok** [comment] 2016-04-22 19:50
@klimkowd can you test the latest develop version? I fixed the timesync problem as you can see here https://github.com/RocketChat/Rocket.Chat/commit/96f392c475cf013d8a6ff2cdbd0cafb0fce07ae7 and here https://github.com/RocketChat/Rocket.Chat/commit/bac8c78a4c6c3f7d846ca3dd7c793294bbacc170

**Comment by engelgabriel** [comment] 2016-04-25 22:45
Please reopen if the problem persists.

**Closed by engelgabriel** 2016-04-25 22:45 UTC

**Comment by klimkowd** [comment] 2016-05-17 16:57
I found another absolute path needing fixed.
 /file-upload

**Comment by klimkowd** [comment] 2016-05-17 17:50
Another path problem:
When receiving an invitation to a video chat and clicking "yes"
it sends me to 
`    domain.com/chat/chat/direct/user`
    instead of:
`    domain.com/chat/direct/user`

**Comment by engelgabriel** [comment] 2016-05-17 22:24
Can you help us with a PR?

**Comment by klimkowd** [comment] 2016-05-19 12:35
Yeah, I'd be happy to help.

**Comment by hemanthAppmaker** [comment] 2023-05-07 11:12
Use `docker compose` instead of 
`docker-compose` 
We use latest version of docker compose
