### ISSUE TITLE
Link in attachement open in internal browser

### ISSUE THREAD

**Issue by arthur-trt** [RocketChat/Rocket.Chat#27761] opened 2023-01-16 12:45 UTC
### Description:

We use [GitLab integration](https://docs.rocket.chat/guides/administration/admin-panel/integrations/gitlab) on our on premise instance. When there is a link, it is opened in the internal browser of the MacOs application (impossible to test on Windows)

### Steps to reproduce:

1. Wait for GitLab webhook to send information about push/commit/mr
2. Click on the link
3. Window open in the RocketChat application

### Expected behavior:

The link must open in the default browser of the machine

### Actual behavior:

![Screenshot 2023-01-16 at 13 40 50](https://user-images.githubusercontent.com/4441676/212680500-452c8e35-f600-4029-9713-5077726b9a11.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  5.4.1
- Deployment Method: [Helm](https://github.com/RocketChat/helm-charts)
- Number of Running Instances: 1
- DB Replicaset Oplog: wiredTiger (oplog Activé)
- NodeJS Version: v14.19.3
- MongoDB Version: 4.4.11

### Client Setup Information

- Desktop App or Browser Version: 3.8.19
- Operating System: MacOs (m1)

**Comment by Shubham043** [comment] 2023-01-16 13:43
I want to work on this issue. please assign me this issue.

**Comment by dudanogueira** [comment] 2023-01-17 00:08
Hi! Thanks for pointing it out.

I was not able to reproduce it on latest branch (https://github.com/RocketChat/Rocket.Chat/commit/73747ca6a as I write)

I used the example payload, and added a link, like below:

```
curl -X POST -H 'Content-Type: application/json' --data '{"text":"Example message [url](http://terra.com.br)","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"http://localhost:3000/images/integration-attachment-example.png","color":"#764FA5"}]}' http://localhost:3000/hooks......
```
Both web and desktop opened on new tabs/window.

Also. I have installed the integration, and seems to be working fine (tried the Issue Hook one)
This will certainly be fixed in new Rocket.Chat Six

I will close for now, but feel free to reopen if you don't find it fixed. THanks!

**Closed by dudanogueira** 2023-01-17 00:08 UTC
