### ISSUE TITLE
Markdown code block is not parsing correctly

### ISSUE THREAD

**Issue by kvaps** [RocketChat/Rocket.Chat#9613] opened 2018-02-06 18:36 UTC
### Description:

Code block is not parsing correctly

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): tar 
* Number of Running Instances: 1
* DB Replicaset Oplog: yes
* Node Version: v8.9.3

### Steps to Reproduce:

Send message:
<pre>
```
test code block
line2 line2 line2
```
</pre>

### Expected behavior:

Output without empty line:

```
test code block
line2 line2 line2
```

### Actual behavior:

Output with empty line:

```

test code block
line2 line2 line2
```

**Comment by graywolf336** [comment] 2018-02-06 20:25
Duplicate of #8368

**Closed by graywolf336** 2018-02-06 20:25 UTC
