### ISSUE TITLE
Error during make picture preview

### ISSUE THREAD

**Issue by zxweed** [RocketChat/Rocket.Chat#4974] opened 2016-11-18 07:32 UTC
Your Rocket.Chat version: 0.45

> Exception in callback of async function: Error: Encoding not recognized: 'undefined' (searched as: 'undefined')   at Object.getCodec (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:102:23)   at Object.getDecoder (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:118:23)   at Object.decode (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/rocketchat_oembed/node_modules/iconv-lite/lib/index.js:36:25)   at toUtf8 (/opt/Rocket.Chat/programs/server/packages/rocketchat_oembed.js:85:16)   at /opt/Rocket.Chat/programs/server/packages/rocketchat_oembed.js:153:13   at runWithEnvironment (packages/meteor.js:1176:24)

**Comment by logankoester** [comment] 2016-11-18 23:34
This looks to be a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/4779

**Comment by lucasvanhalst** [comment] 2016-11-19 12:10
This is already fixed on the develop branch 
#4881

**Closed** 2016-11-21 18:45 UTC
Labels: feat: file sharing, type: support

**Comment by zxweed** [comment] 2016-11-26 13:01
0.46 - still the same
