### ISSUE TITLE
Dragging file into channel list redirects

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#3349] opened 2016-05-25 22:06 UTC
We need to handle file input if its dragged into channel list instead of the channel body.

**Comment by reetp** [comment] 2018-10-16 10:51
Still seems to be open as of 0.70.4

**Comment by geekgonecrazy** [comment] 2018-10-16 19:49
I think the issue here is that channel list isn't a target.  We may need to make a target and just ignore?  @ggazzo 

Though surprisingly you are first to comment in 2 years :grin: so must not bug too many people

**Comment by ggazzo** [comment] 2018-10-17 04:05
sure, should be easy fix it :)

**Comment by tassoevan** [comment] 2018-10-19 16:50
I'm closing it since is not reproducible in `0.71.0-develop`. A new issue should be open if there is a feature request to enable file uploads in the room list.

**Closed by tassoevan** 2018-10-19 16:50 UTC
Labels: feat: file sharing, subj: ui/ux, type: improvement
