### ISSUE TITLE
Users being logged out even when timeout is set to default (90 days)

### ISSUE THREAD

**Issue by metalcated** [RocketChat/Rocket.Chat#8395] opened 2017-10-04 14:14 UTC
### Description:

Users are being logged out even when timeout is set to default (90 days). This is happening on the most recent stable release: 0.58.3

I am using a snap on Ubuntu. I also saw other users reporting the same issue in the #support channel. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.3
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v0.12.18

### Steps to Reproduce:

1. Login and wait, after a few hours or overnight I am logged out.

### Expected behavior:

The user accounts should stay logged in for up to 90 days before asking to login again.

### Actual behavior:

Users are being force logged out after a certain amount of time (unsure of the actual amount) 

### Relevant logs:
[site.domain.com-1507125804542.log](https://github.com/RocketChat/Rocket.Chat/files/1356040/site.domain.com-1507125804542.log)

**Comment by himbeere** [comment] 2017-10-04 14:28
Yes.

https://github.com/RocketChat/Rocket.Chat/issues/8366
https://github.com/RocketChat/Rocket.Chat/issues/8380

**Comment by MartinSchoeler** [comment] 2017-10-04 18:30
Duplicate of
#8366
#8380

**Closed by MartinSchoeler** 2017-10-04 18:30 UTC
