### ISSUE TITLE
Can't pm a user - internal server error

### ISSUE THREAD

**Issue by kiamgrebgnur** [RocketChat/Rocket.Chat#7592] opened 2017-07-28 07:59 UTC
Hi,

### Description:

one user (christian) had an Issue with his account. He wasn't able to login so I removed the user.
Since we are using ldap for authentication the user was created again after he logged in.
But after that we have some serious trouble with the user account. I'm unable to direct message him. 
If I click on the user an choose the direct message option in the menu I get "Internal Server Error".
If the user messages me I see the text in the preview popup from chrome but can't open the room.
If I open the Room everything I see is "Couldn't find room" "There is no user with the name xyz"
He can see the room. If I do **/msg @xyz foo** he gets the message.

In the logs you can see a duplicate key error. I tried already to delete all room subscriptions between us with no success. 

P.S. I've translated the error messages from german since my ui is german.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.57.2
* Operating System: Ubuntu 15.04
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v4.7.3

### Steps to Reproduce:

Open Direct Message to User.

### Expected behavior:

See the Room

### Actual behavior:

Get an internal server error.

### Relevant logs:

```
rocketchat_logger.js:377 [34mMeteor ➔ method createDirectMessage -> userId: hk9SSvJSa4fitYqGE , arguments:  { '0': 'christian' } 
[34mI20170728-07:54:40.188(0) Exception while invoking method 'createDirectMessage' MongoError: E11000 duplicate key error collection: rocketchat.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "hk9SSvJSa4fitYqGE", : "christian", : "d", : null }   at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)   at [object Object].<anonymous> (packages/meteor.js:213:24)   at [object Object].MongoConnection.(anonymous function) [as update] (/app/bundle/programs/server/packages/mongo.js:836:49)   at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)   at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)   at [object Object].update (/app/bundle/programs/server/packages/mongo.js:3899:31)   at ModelsBaseDb.update (/app/bundle/programs/server/packages/rocketchat_lib.js:10647:32)   at ModelsBaseDb.upsert (/app/bundle/programs/server/packages/rocketchat_lib.js:10722:16)   at ModelSubscriptions.upsert (/app/bundle/programs/server/packages/rocketchat_lib.js:4283:36)   at [object Object].Meteor.methods.createDirectMessage (/app/bundle/programs/server/app/app.js:6506:35)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1028:26)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1823:12)   at /app/bundle/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:876:21)   at /app/bundle/programs/server/packages/ddp-server.js:755:85      - - - - -   at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)   at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1049:67   at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18   at nextTickCallbackWith0Args (node.js:436:9)   at process._tickDomainCallback (node.js:406:13)  
[34mI20170728-07:54:41.047(0) rocketchat_logger.js:377 [34mMeteor ➔ method createDirectMessage -> userId: hk9SSvJSa4fitYqGE , arguments:  { '0': 'christian' } 
[34mI20170728-07:54:41.084(0) Exception while invoking method 'createDirectMessage' MongoError: E11000 duplicate key error collection: rocketchat.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "hk9SSvJSa4fitYqGE", : "christian", : "d", : null }   at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)   at [object Object].<anonymous> (packages/meteor.js:213:24)   at [object Object].MongoConnection.(anonymous function) [as update] (/app/bundle/programs/server/packages/mongo.js:836:49)   at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)   at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)   at [object Object].update (/app/bundle/programs/server/packages/mongo.js:3899:31)   at ModelsBaseDb.update (/app/bundle/programs/server/packages/rocketchat_lib.js:10647:32)   at ModelsBaseDb.upsert (/app/bundle/programs/server/packages/rocketchat_lib.js:10722:16)   at ModelSubscriptions.upsert (/app/bundle/programs/server/packages/rocketchat_lib.js:4283:36)   at [object Object].Meteor.methods.createDirectMessage (/app/bundle/programs/server/app/app.js:6506:35)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1028:26)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1823:12)   at /app/bundle/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:876:21)   at /app/bundle/programs/server/packages/ddp-server.js:755:85      - - - - -   at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)   at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1049:67   at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18   at nextTickCallbackWith0Args (node.js:436:9)   at process._tickDomainCallback (node.js:406:13)  
[34mI20170728-07:54:42.407(0) rocketchat_logger.js:377 [34mMeteor ➔ method createDirectMessage -> userId: hk9SSvJSa4fitYqGE , arguments:  { '0': 'christian' } 
[34mI20170728-07:54:42.439(0) Exception while invoking method 'createDirectMessage' MongoError: E11000 duplicate key error collection: rocketchat.rocketchat_subscription index: u._id_1_name_1_t_1_code_1 dup key: { : "hk9SSvJSa4fitYqGE", : "christian", : "d", : null }   at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)   at [object Object].<anonymous> (packages/meteor.js:213:24)   at [object Object].MongoConnection.(anonymous function) [as update] (/app/bundle/programs/server/packages/mongo.js:836:49)   at Object.<anonymous> (packages/matb33_collection-hooks.js:504:27)   at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:146:21)   at [object Object].update (/app/bundle/programs/server/packages/mongo.js:3899:31)   at ModelsBaseDb.update (/app/bundle/programs/server/packages/rocketchat_lib.js:10647:32)   at ModelsBaseDb.upsert (/app/bundle/programs/server/packages/rocketchat_lib.js:10722:16)   at ModelSubscriptions.upsert (/app/bundle/programs/server/packages/rocketchat_lib.js:4283:36)   at [object Object].Meteor.methods.createDirectMessage (/app/bundle/programs/server/app/app.js:6506:35)   at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)   at [object Object].methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:1028:26)   at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1823:12)   at /app/bundle/programs/server/packages/ddp-server.js:905:20   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:904:41   at [object Object]._.extend.withValue (packages/meteor.js:1122:17)   at /app/bundle/programs/server/packages/ddp-server.js:903:46   at [object Object]._.extend.protocol_handlers.method (/app/bundle/programs/server/packages/ddp-server.js:876:21)   at /app/bundle/programs/server/packages/ddp-server.js:755:85      - - - - -   at Function.MongoError.create (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)   at toError (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:114:22)   at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1049:67   at /app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18   at nextTickCallbackWith0Args (node.js:436:9)   at process._tickDomainCallback (node.js:406:13)  
```

**Comment by fmuecke** [comment] 2017-07-28 11:59
Duplicate of #6535, #7592, #7364 ?

**Comment by kiamgrebgnur** [comment] 2017-07-28 12:05
Ok if he creates a new ad account and logs in with it everything works.
So I think there is an error with the delete user account function.
Any chance to clean/repair the database?

**Comment by kiamgrebgnur** [comment] 2017-07-28 12:19
@fmuecke you are right
I did the remove from mongo db part but not the restart. Will give it a try later.

**Comment by MartinSchoeler** [comment] 2017-07-28 12:21
Yes, this is a duplicate, please continue the discussion on the original issue. Thanks!

**Closed by MartinSchoeler** 2017-07-28 12:21 UTC
