### ISSUE TITLE
Bug on changeavatar

### ISSUE THREAD

**Issue by pouleta** [RocketChat/Rocket.Chat#917] opened 2015-09-28 00:02 UTC
Hello,

After start rocketchat from docker-composer, I got this error:

```
[publish] settings
[publish] subscription
[publish] userData
[publish] activeUsers
[publish] admin-settings
[methods] hasPermission ->  arguments: { '0': 'EuFxLqgvy7cbGoP2K', '1': 'view-privileged-setting' }
[methods] getRolesForUser ->  arguments: { '0': 'EuFxLqgvy7cbGoP2K', '1': undefined }
[publish] permissions
[publish] activeUsers
[methods] setAvatarFromService ->  userId: EuFxLqgvy7cbGoP2K contentType: image/png service: gravatar

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

It came from https://chat.domain.dom/changeavatar, when using the gravatar avatar, with a front NGINX, with https and invalid certificate (valid on www.XXX not on chat.XXX).

**Comment by geekgonecrazy** [comment] 2015-09-28 00:03
duplicate of #916

**Closed by geekgonecrazy** 2015-09-28 00:03 UTC

**Comment by pouleta** [comment] 2015-09-28 00:04
sorry, network issue.

The issue also touch other avatar services:

```
[methods] resetAvatar ->  userId: EuFxLqgvy7cbGoP2K arguments: {}
[methods] setAvatarFromService ->  userId: EuFxLqgvy7cbGoP2K contentType: image/jpeg service: upload

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```
