### ISSUE TITLE
Sometimes when switching to admin view, channel is still displayed and admin text overlays channel

### ISSUE THREAD

**Issue by phutchins** [RocketChat/Rocket.Chat#4152] opened 2016-08-30 23:54 UTC
Your Rocket.Chat version: 0.37.1

Sometimes when you click the administration link on the drop down (on the desktop app), the channel view does not disappear and the admin view is rendered over it. It is not clickable. You can then click back on a channel to have it re-render then go back to admin and it usually works.

I saw something similar where I could not render some admin pages on Android. Not sure if those two are related but it felt very similar.

**Comment by graywolf336** [comment] 2016-08-31 17:53
How can we reproduce this?

**Comment by vetash** [comment] 2016-09-01 15:10
@graywolf336 #3868

**Comment by graywolf336** [comment] 2016-09-01 15:52
Thanks @vetash. Closing as this is a duplicate of #3868

**Closed by graywolf336** 2016-09-01 15:52 UTC
Labels: subj: ui/ux, type: bug

**Comment by phutchins** [comment] 2016-09-02 12:57
Great, thanks!
