### ISSUE TITLE
QA-Regression: Forgot password functionality doesn't work in Enterprise edition.

### ISSUE THREAD

**Issue by Ishrat-Manzoor** [RocketChat/Rocket.Chat#21379] opened 2021-03-31 10:31 UTC
### Description:

Forgot password functionality doesn't work in Enterprise edition.

### Steps to reproduce:

1. Launch Rocket chat Enterprise edition.
2. On the Login page, click on the Forgot password link.
3. Go to your registered email, and click on the Reset link sent in the email.
4. Enter new password.
5. It will now ask for the verification code sent in the email.
6. Enter the verification and click on the Reset button.

### Expected behavior:

Password should be changed successfully.
### Actual behavior:

System throws an error "Token expired"
![image](https://user-images.githubusercontent.com/24873115/113131542-f9b3ca00-923a-11eb-8603-c339b0c0fbb0.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

**Comment by abbluiz** [comment] 2021-07-12 11:21
Also happening in non-Enterprise installation for me. That's a huge problem, because users can get locked out. The only way to solve it is to reset user's password with a random one sent by email.

But then there's another problem: for some reason the user does not receive the 2FA code via email whilst on the process of using the temporary random password.

**Comment by abbluiz** [comment] 2021-07-13 17:08
I had to disable email 2FA to solve a user being locked out because of this.

**Comment by matheusbsilva137** [comment] 2021-08-10 19:33
We couldn't reproduce this issue in 3.17. Are you still experiencing this issue, @abbluiz ?

**Comment by abbluiz** [comment] 2021-08-10 22:32
@matheusbsilva137 yeah, I just tried it again but interesting enough, there is a twist. Steps:

1. Go to Rocket.Chat instance URL and sign out if you are already signed in.
2. Click forgot password link and enter your email.
3. Receive reset password link in email; click it.
4. Enter new password in compliance with password policy; enter 2FA code if necessary.
5. Error message received in password input: Token expired; page does update and it still shows password input. So I assume password is not changed successfully.
6. The twist: I try to login with my OLD password, the one I supposedly forgot, and it does not work. The new password works, so the password is changed successfully despite the error showed before.

Maybe the problem is on the front end validation? I think it should not have showed me the error message, and logged me in after I reset the password.

**Comment by matheusbsilva137** [comment] 2021-08-13 21:10
@abbluiz Thanks for providing new and detailed steps about this issue.
Unfortunately, I still couldn't reproduce the error (more specifically, no 'Token expired' error is being thrown in my tests) 🤔 
Could you please inform the Rocket.Chat instance's version you're using? This error might be related to the Meteor version

**Comment by abbluiz** [comment] 2021-08-13 21:11
@matheusbsilva137 it's the latest (3.17)

**Comment by matheusbsilva137** [comment] 2021-08-16 21:40
@abbluiz I still couldn't reproduce it, but I assume that the error is being thrown in [this line](https://github.com/RocketChat/Rocket.Chat/blob/fd6eb15b7f0e4bcb6fd3005398a708cf649f11d3/client/views/login/ResetPassword/ResetPassword.js#L64). Could you please specify your Meteor (`meteor --version`) and node (`meteor node -v`) versions?
I'm using node v12.22.1 in Meteor 2.2.

**Comment by abbluiz** [comment] 2021-08-17 02:25
@matheusbsilva137  I'm using the "latest" docker images from rocket chat and stuff, node is v12.22.1, but meteor I will check later and get back to you

**Comment by abbluiz** [comment] 2021-08-17 21:01
@matheusbsilva137 I'm not sure where I'm supposed to use `meteor`. Inside the docker container I can only use `node`.

**Comment by matheusbsilva137** [comment] 2023-04-18 11:24
Thank you for the reports! This has been fixed in #28938

**Closed by matheusbsilva137** 2023-04-18 11:24 UTC
