### ISSUE TITLE
Message Hide Dialog shows up as "Message_HideType_au" instead of Hide Add User

### ISSUE THREAD

**Issue by phutchins** [RocketChat/Rocket.Chat#4998] opened 2016-11-21 15:30 UTC
I upgraded to latest today to get the option to hide user add and remove messages and see that it's showing up in my settings differently than pictured on the merged PR. 

I would expect to see "Hide Add User Messages" but instead I see "Message_HideType_au". This is true for the 4 HideType config params.

**Comment by MartinSchoeler** [comment] 2016-11-21 15:42
@phutchins Strange i couldn't reproduce this bug, in which language are your rocket chat?

**Comment by marceloschmidt** [comment] 2016-11-21 19:23
@phutchins I've seen it happen sometimes as well. For me, it is usually because of some cached files in my meteor directory. Are you also running Rocket.Chat for development purposes (meteor)?

Thanks.

**Comment by phutchins** [comment] 2016-11-22 01:30
@marceloschmidt I'm running it in a docker container for production use but may have a dev setting somewhere... Any hints on what dir I might try to clear or settings to check?

**Comment by marceloschmidt** [comment] 2016-11-22 10:45
For me, it is usually the `.meteor` directory on my home dir. But, since you're on Docker, maybe you could completely remove that docker instance (keeping your database) and fire up a new one. Unless that's what you did on upgrading... Not sure if that'd help, though. I've never experienced this on Docker.

**Comment by MartinSchoeler** [comment] 2017-08-08 17:00
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open it again with updated details. Thanks

**Closed by MartinSchoeler** 2017-08-08 17:00 UTC
Labels: feat: i18n, type: support
