### ISSUE TITLE
Accessing via URL constantly redirects to `general`

### ISSUE THREAD

**Issue by taikedz** [RocketChat/Rocket.Chat#9163] opened 2017-12-18 14:05 UTC
### Description:

When accessing a URL http://rocket.local:3000/channel/foo , user gets redirected to http://rocket.local:3000/channel/general

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.4
* Commit Hash: 65e06c2832
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog: 4.8.4
* Node Version: 4.8.4

### Steps to Reproduce:

1. Create new channel `foo`
2. Go to URL http://rocket.local:3000/channel/foo (replacing hostname)
3. See `general` channel displayed

### Expected behavior:

Display the intended channel `foo`

### Actual behavior:

`general` channel is displayed - whilst checking the requests and return headers, no `300` class referers are sent, only `200` class

### Relevant logs:

Cannot connect obtain logs from the `journalctl` logs, going to end `^G` does not display the last messages (several days out of date). Cannot restart currently due to users being on and non-severity of issue

**Comment by taikedz** [comment] 2018-02-03 12:39
.... nobody ...?

**Comment by jszaszvari** [comment] 2018-02-03 12:45
Do you have this setting on 

![image](https://user-images.githubusercontent.com/872463/35767226-4bb56c36-093c-11e8-9348-0cb4b6e4fa7c.png)

**Comment by taikedz** [comment] 2018-02-03 14:20
Thanks, but not relevant. I'm not trying to set the default channel.

I am trying to provide a direct link to any arbitrary channel. All info in initial description.

**Comment by jszaszvari** [comment] 2018-02-03 16:24
Thats why i was checking to see if it was on and pointing to #general as I'm unable to reproduce your issue. 

If i browse too https://my.rocket.chat/group/groupname or https://my.rocket.chat/channel/channelname I'm taken straight to the group or channel

**Comment by taikedz** [comment] 2018-02-05 15:43
Sorry for the delay - I checked and indeed that fields was set to general

I left that field blank, and now I can direct-link to a channel.

*However* users visiting the main `/` path are not redirected to anything, instead there is an empty landing page. This is not useful either.

At this point, either we have a default channel, but no direct linking, or we have direct linking and a blank landing page.

I tried adding a script to the Layout are, for logged-in users

```js
if( window.location.href.match( /^https:\/\/rocketchat.optos.eye(\/||\/home\/?)$/ ) )
{ window.href = "https://rocketchat.optos.eye/channel/general"; }
else
{ console.log("Got different path"); }
```

but to no avail - no redirect happens.

My script notwithstanding, this seems like an awfully hacky way of having a "default channel if no channel specified" behaviour, whilst the "Home" page specification is not clear in usage...

Or am I just missing a fundamental design point here ?

**Comment by andpiazza** [comment] 2018-02-13 21:29
Having the exact same issue, and agree with @taikedz that an empty landing page is unhelpful.

**Comment by andpiazza** [comment] 2018-02-15 22:55
This issue happens for Channels and Direct Messages (DM):
http://_instance_.rocket.chat/channel/_channel_name_
http://_instance_.rocket.chat/direct/_username_
all being directed to
https://_instance_.rocket.chat/channel/general

**Comment by MartinSchoeler** [comment] 2019-11-22 14:07
I've just tested with version 2.3.0-develop and the `first channel after login` setting seems to be working as intended now. I will be closing this issue, if you experience this again, please open a new issue with updated details. Thanks!

**Closed by MartinSchoeler** 2019-11-22 14:07 UTC

**Comment by entrptaher** [comment] 2019-11-23 13:07
@MartinSchoeler , can you confirm that going to a direct link (not the **first channel after login**) doesn't take me to `general`?

**Comment by reetp** [comment] 2019-11-23 14:21
> MartinSchoeler

Please don't @ people hoping to get a response. There is no guarantee it is the right person.

> can you confirm that going to a direct link (not the **first channel after login**) doesn't take me to `general`?

Have you read his comment ?

" tested with version 2.3.0-develop...... first channel after login setting **seems to be working as intended now.** "

Try https://open.rocket.chat/channel/support
