### ISSUE TITLE
Forgot to close multiline code tag (```) freezes direct chat

### ISSUE THREAD

**Issue by tboerger** [RocketChat/Rocket.Chat#7357] opened 2017-06-28 10:19 UTC
Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Active
Node Version: v4.8.1

We found an issue if you send a direct message. Some user started the message with the multiline code block, pasted a long log line and forgot to close the code tag before hitting enter. The message gets submitted and the direct message chat freezes. On a browser you can not open the direct chat anymore and the desktop application doesn't respond at all anymore.

I personally tried to paste this into the chat to reproduce the issue:

```
```{"reqId":"5WHzozl7j0XMxCpmj82G","level":3,"time":"2017-06-27T14:10:44+00:00","remoteAddr":"172.17.0.1","user":"admin","app":"files_onedrive","method":"PROPFIND","url":"\/remote.php\/webdav\/OneDrive","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"$source should be an Iterator or array\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/data\\\/apps\\\/files_onedrive\\\/lib\\\/onedrive.php(168): Icewind\\\\Streams\\\\IteratorDirectory::wrap(NULL)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(97): OCA\\\\files_onedrive\\\\OneDrive->opendir('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(97): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(105): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(97): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->opendir('')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(97): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(97): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(97): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(346): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(397): OC\\\\Files\\\\Cache\\\\Scanner->getNewChildren('')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(377): OC\\\\Files\\\\Cache\\\\Scanner->handleChildren('', false, 3, '76', true, 0)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(311): OC\\\\Files\\\\Cache\\\\Scanner->scanChildren('', false, 3, '76', true)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1302): OC\\\\Files\\\\Cache\\\\Scanner->scan('', false)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1343): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Workflow\\\\Engine\\\\Wrapper\\\\StorageWrapper), '', 'OneDrive')\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php(169): OC\\\\Files\\\\View->getFileInfo('\\\/admin\\\/files\\\/On...')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(966): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('OneDrive')\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('OneDrive', Array, 1)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#18 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#21 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#23 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/IteratorDirectory.php\",\"Line\":116}"}
```

**Comment by geekgonecrazy** [comment] 2017-06-28 15:41
@tboerger confirmed.  Probably related to #6262 but a different variation.  

If you have any smaller chunks known to do this please let us know.  We pretty much have to break this down until we figure out what characters in this is causing the code highlighter to lock up.

**Comment by geekgonecrazy** [comment] 2017-06-28 16:06
So far got it down to: 
```
```{"reqId":"5WHzozl7j0XMxCpmj82G","level":3,"time":"2017-06-27T14:10:44+00:00","remoteAddr":"172.17.0.1","user":"admin","app":"files_onedrive","method":"PROPFIND","url":"\/remote.php\/webdav\/OneDrive","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"$source should be an Iterator or array\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/data\\\/apps\\\/files_onedrive\\\/lib\\\/onedrive.php(168): Icewind\\\\Streams\\\\IteratorDirectory::wrap(NULL)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(97): OCA\\\\files_onedrive\\\\OneDrive->opendir('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(97): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->opendir('')\\n#3
```

**Comment by geekgonecrazy** [comment] 2017-06-28 16:15
Ok so this one comes out to a couple of things. 

1) We need to add missing backticks before we try to escape the text.
2) If there is too much text to escape like in this case all of the quotation marks it locks up.

**Comment by localguru** [comment] 2017-07-16 19:41
Hmmm ... can't reproduce this with 0.57.1 Firefox and Chrome.

**Comment by tboerger** [comment] 2017-07-16 19:50
I had been able to reproduce that on latest chrome for Mac, within Alfred and within the desktop app for Mac

**Comment by MartinSchoeler** [comment] 2017-08-10 13:21
This bug has been fixed in the latest version

**Closed by MartinSchoeler** 2017-08-10 13:21 UTC
Labels: type: bug

**Comment by tboerger** [comment] 2017-08-10 20:37
Awesome, thanks!

**Comment by tylwright** [comment] 2017-11-29 20:20
I can repro this with 0.59.3.  Chrome, Firefox, and macOS desktop client all freeze.  I've even gone into the DB and changed the erroneous message to be the string "test" but this only temporarily solved it somehow.
