### ISSUE TITLE
Sign in with OAuth service for existing users doesn't join accounts, but creates new user

### ISSUE THREAD

**Issue by jemus42** [RocketChat/Rocket.Chat#6483] opened 2017-03-26 00:43 UTC
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: v4.7.3

Steps taken:

- Create admin account after initital Rocket.Chat setup
- Configure OAuth providers
- Go to my profile -> Avatars
- Log in with Facebook, sign in
-> Rocket.Chat forces me to select a new username (choosing my existing one results in conflict)
- Try the same with Twitter login, same result
- Try the same with Google login, same result

I have configured the OAuth providers according to your documentation and another user was able to use them to register successfully.

My idea: I use different email addresses for various services, could that be the reason why the accounts don't get joined?

I have searched existing issues for this problem and the only thing I found was a fix for conflicting `@gmail` addresses that consisted of *exactly what I attempted to do*, so I'm mildly confused at this point.

**Comment by christopherturner** [comment] 2017-03-29 18:29
I've tried this as well, though have been successful with accessing my initially-created Rocket.Chat admin account by using the Google OAuth login.  I did not setup the account using OAuth, but have confirmed that I am accessing the same account.  Also, the quantity of users did not change up first trying the OAuth authentication.

Is there any chance that it's some minor issue with the way email addresses are matched from the database to OAuth?  I'm not an expert on the codebase, but it seems that the OAuth does work in some cases (i.e. accounts are properly joined).

**Comment by jemus42** [comment] 2017-03-30 15:38
As I mentioned, I believe it's because of the non-matching e-mail addresses. I tried the same thing on the official demo chat and got the same result, so I assume I might just be an edge case of an otherwise functioning feature.

**Comment by rasos** [comment] 2017-08-22 09:15
Yes, the matching is with e-mail addresses.

**Comment by gdelavald** [comment] 2017-10-23 20:54
Seems like even matching with `e-mail` can make the system try and create a new account instead of merging.

**Comment by simonv3** [comment] 2018-05-30 21:20
I can confirm that I've set up an oauth provider (auth0) that logs in successfully but doesn't join an account even though the e-mail matches.

**Comment by simonv3** [comment] 2018-05-31 15:43
On further investigation, my issue was because I wasn't passing the `email` scope to the oauth provider, so we never got the e-mail in return.

**Comment by Hudell** [comment] 2018-07-03 18:23
I'll be closing this one, as #3187 is even older.

**Closed by Hudell** 2018-07-03 18:23 UTC
Labels: feat: oauth / sso, sponsored, type: bug
