### ISSUE TITLE
feature request: custom notification groups

### ISSUE THREAD

**Issue by OGFilthyCasual** [RocketChat/Rocket.Chat#1315] opened 2015-11-02 05:32 UTC
geekgonecrazy doesnt like it when I notify _@all_ in _#general_ on the demo server; I thought it might be nice to have a way to create a custom mention group, which I can populate with several folks I would otherwise want to mention all at once.  Like _@rocketDevs_ anyone in the list would get a mention notification.

![image](https://cloud.githubusercontent.com/assets/1946002/10874878/14c9159c-80e0-11e5-8f6d-6aa96fa695af.png)
##

**Comment by geekgonecrazy** [comment] 2015-11-23 04:23
:+1: this is a pretty great idea!  Maybe making use of teams?

**Comment by damienmollard** [comment] 2016-02-11 09:05
+1

**Comment by cimbalek** [comment] 2016-10-12 08:18
+1

**Comment by baldimir** [comment] 2016-10-12 08:20
+1

**Comment by engelgabriel** [comment] 2017-02-14 15:43
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2192

**Closed by engelgabriel** 2017-02-14 15:43 UTC
Labels: type: new feature
