### ISSUE TITLE
Chat Admin App

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2850] opened 2016-04-12 14:49 UTC
People may choose to run thier app on any server, AWS, digital ocean, local servers etc.. would it be possible to have an admin interface dashboard to enable loading new APP builds or rolling back, access to DB to manage?  this is really useful for quick solution and specially if you have issue running command lines.. 

Heroku has this feature

![image](https://cloud.githubusercontent.com/assets/12454319/14464258/11668330-009c-11e6-8247-0bc9191f116b.png)

![image](https://cloud.githubusercontent.com/assets/12454319/14464281/2b048166-009c-11e6-97a1-f36f76774437.png)

Your Rocket.Chat version: 0.26

**Comment by engelgabriel** [comment] 2016-04-12 15:50
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2618

**Closed by engelgabriel** 2016-04-12 15:50 UTC
