### ISSUE TITLE
Why not display the "name" rather than "username" in Channels

### ISSUE THREAD

**Issue by Laisky** [RocketChat/Rocket.Chat#2827] opened 2016-04-10 01:15 UTC
Your Rocket.Chat version: v0.25

There are two names in account profile:

  - `username`: be used to login. In my case they are synchronize from ldap account.
  - `name`: should be used to display, let another people know who you are.

![rocket](https://cloud.githubusercontent.com/assets/4532436/14407442/c223d120-fefb-11e5-87c7-a6e4bdecf2cf.jpg)

But name do not display in channel.

![srceen_shot 2016-04-10 at 09 11 55](https://cloud.githubusercontent.com/assets/4532436/14407469/708f133c-fefc-11e5-98f8-c5758b25bc7a.jpg)

**Comment by oott123** [comment] 2016-04-10 09:37
+1 for "name".

It's important when you have many non-english speaking users.

**Comment by lunitic** [comment] 2016-04-10 10:54
I rather have the username showed. since the usernames are unique.. Names are not.. How do you tag a person with when there are multiple persons with the same name?

**Comment by oott123** [comment] 2016-04-10 11:37
Normally we need two names, one for identify the speaker and another for friendly purpose. Otherwise, you shall not design the field 'name' since it's ambiguous. You allow the user to set their 'name', yet it can be seen nowhere but his very profile. Isn't it strange?

I think showing "Name" may be a good idea, optionally followed by a "@username".

**Comment by Laisky** [comment] 2016-04-10 11:38
Nobody will use same "nicknames" in one group(or one channel), so you absolutely can distinguish people by their `name`. 

By the way, many people will use an unusual `username` to avoid duplication of account, so it's much more difficult to identify people by their `username`.

**Comment by lunitic** [comment] 2016-04-10 11:49
@Laisky It depends on how many users you have. For small deployment you are right,  but when it comes  to large deployment I Forse the name will problem.  If this is changed by RC make it as an option.  Since it change the user experience.

**Comment by engelgabriel** [comment] 2016-04-10 13:15
Hi guys, this is a duplicate of #324

**Closed by engelgabriel** 2016-04-10 13:15 UTC
