### ISSUE TITLE
Verification email and password reset email

### ISSUE THREAD

**Issue by net-activities** [RocketChat/Rocket.Chat#4502] opened 2016-09-30 14:47 UTC
Your Rocket.Chat version: 0.40.1 and 0.41.0

I can edit the registration emails unter administration/layout.

But I can't edit the verification and password reset emails.

They are always in english AND the links within the emails are not clickable.

It would be nice to be able to edit the layout like the others.

**Comment by lunitic** [comment] 2016-10-02 08:12
Same as #4000

**Comment by lunitic** [comment] 2016-10-02 08:12
And I agree its a pain in the ***

**Comment by MartinSchoeler** [comment] 2016-10-03 11:19
duplicate of #4000

**Closed by MartinSchoeler** 2016-10-03 11:19 UTC
