### ISSUE TITLE
Without REST API for reply message?

### ISSUE THREAD

**Issue by chenshinan** [RocketChat/Rocket.Chat#15079] opened 2019-07-31 08:14 UTC
Without REST API for reply message?

**Comment by reetp** [comment] 2019-07-31 12:10
@rocket-cat close

Probably duplicate of https://github.com/RocketChat/Rocket.Chat/issues/13179

Github is for bugs, not support.

https://rocket.chat/docs/getting-support/

**Closed** 2019-07-31 12:10 UTC
