### ISSUE TITLE
RC 3.16.3 - redmine messenger shows "<br/>" instead of linebreaks 

### ISSUE THREAD

**Issue by kiilo** [RocketChat/Rocket.Chat#22734] opened 2021-07-22 12:59 UTC
# Description: redmine messenger shows `<br/>` instead of linebreaks

I upgraded to 3.16.3 and the unchanged redmene messenger plugin showed `<br/>` in RC
Before 3.16.1 it was working correctly

### Steps to reproduce:

1. install RC 3.16.3 (docker)
2. have a redmine 4.1 instance  (bitnami)
3. install redmine_messenger plugin - i got it here: https://github.com/alphanodes/redmine_messenger
4. create a incoming webhook / configure plugin
5. finally after all this effort 
6. `<br/>`

### Expected behavior:

same text between redmine and RC without html tags

### Actual behavior:

![screenshot-chat psychologie uzh ch-2021 07 22-14_42_42](https://user-images.githubusercontent.com/271145/126642233-73891b3f-aaa9-4e30-a36b-fc2b4b8dacc9.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: Not used

### Client Setup Information

- Desktop App or Browser Version: Vivaldi / Firefox / Chrome
- Operating System: ubuntu 20.04LTS

### additional info

my redmine instance is using CommonMarkdown (see here: https://www.redmine.org/issues/32424 ) and RC is also using markdown

**Comment by ankar84** [comment] 2021-07-23 03:09
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/22701

**Comment by phuongnguyen2311** [comment] 2021-07-26 07:33
@ankar84 
![image](https://user-images.githubusercontent.com/5517848/126950304-79d3a352-e070-4969-abb6-a0cd75d10940.png)
i have problem not show break new line
always show tag `<br/>`

**Comment by ankar84** [comment] 2021-07-26 08:22
> @ankar84
> ![image](https://user-images.githubusercontent.com/5517848/126950304-79d3a352-e070-4969-abb6-a0cd75d10940.png)
> i have problem not show break new line
> always show tag `<br/>`
> 
> Expected:
> 
> * break line
> * not show tag  `<br/>`

That bug fixed by https://github.com/RocketChat/Rocket.Chat/pull/22727 and will landing in 3.17 probably.

**Comment by johncrisp** [comment] 2021-07-26 15:13
Closing as duplicate of #22701

Thanks for picking that up Anton.

**Closed by johncrisp** 2021-07-26 15:13 UTC
