### ISSUE TITLE
Room not found after user deleted and recreated

### ISSUE THREAD

**Issue by willihelm** [RocketChat/Rocket.Chat#6666] opened 2017-04-12 08:40 UTC
Rocket.Chat Version: 54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.5.0

I had to delete a user and recreated this user using LDAP. After that some users have problems to create a direct chat with this user. Even if the recreated user starts a conversation the other users can´t see the room but get the notifications. This effects not all users. I think this is only an issue for users that hab a chat before recreating the user.
I tried to delete rooms, subscriptions and messages from MongoDB and tried to delete the chat rooms but nothing works.

In the picture you can see that there is an uread message but the exception is still present.
![2017-04-12 10_23_12- 1 rocket chat](https://cloud.githubusercontent.com/assets/16389803/24948961/56c9a994-1f6c-11e7-9951-f79c2b8b9ded.png)

**Comment by willihelm** [comment] 2017-04-12 08:42
In the RC3 of Version 55 this is still an issue

**Comment by willihelm** [comment] 2017-04-12 08:57
Exception while invoking method 'createDirectMessage'
```
TypeError: Cannot read property 'push' of undefined
  at ModelsBaseCache.processLocalJoinInserted (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_lib.js:8326:24)
  at ModelsBaseCache.target.(anonymous function) [as processLocalJoinInserted] (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_lib.js:7960:29)
  at ModelsBaseCache.<anonymous> (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_lib.js:8219:12)
  at emitOne (events.js:82:20)
  at ModelsBaseCache.emit (events.js:169:7)
  at ModelsBaseCache.insert (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_lib.js:8997:10)
  at ModelsBaseCache.target.(anonymous function) [as insert] (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_lib.js:7960:29)
  at ModelsBaseDb.<anonymous> (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_lib.js:8626:14)
  at emitOne (events.js:77:13)
  at ModelsBaseDb.emit (events.js:169:7)
  at ModelsBaseDb.update (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_lib.js:9648:13)
  at ModelsBaseDb.upsert (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_lib.js:9717:16)
  at ModelRooms.upsert (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_lib.js:4221:36)
  at [object Object].Meteor.methods.createDirectMessage (/usr/local/Rocket.Chat/programs/server/app/app.js:5988:27)
  at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at [object Object].methodsMap.(anonymous function) (/usr/local/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1069:26)
  at maybeAuditArgumentChecks (/usr/local/Rocket.Chat/programs/server/packages/ddp-server.js:1823:12)
  at /usr/local/Rocket.Chat/programs/server/packages/ddp-server.js:905:20
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /usr/local/Rocket.Chat/programs/server/packages/ddp-server.js:904:41
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /usr/local/Rocket.Chat/programs/server/packages/ddp-server.js:903:46
  at [object Object]._.extend.protocol_handlers.method (/usr/local/Rocket.Chat/programs/server/packages/ddp-server.js:876:21)
  at /usr/local/Rocket.Chat/programs/server/packages/ddp-server.js:755:85

**Comment by LifeIsAParadox** [comment] 2017-04-12 11:35
duplicate #6535 ?

**Comment by willihelm** [comment] 2017-04-12 11:59
Seems that this is the problem

**Comment by MartinSchoeler** [comment] 2017-04-12 14:20
Yes this is a duplicate of #6535

**Closed by MartinSchoeler** 2017-04-12 14:20 UTC
