### ISSUE TITLE
Permissions REST api Request header field X-Auth-Token is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by robindijkhof** [RocketChat/Rocket.Chat#10178] opened 2018-03-20 16:56 UTC
### Description:

Request header field X-Auth-Token is not allowed by Access-Control-Allow-Headers in preflight response for Permissions REST api.

### Server Setup Information:

* Server Setup Information:
* Version of Rocket.Chat Server: 0.62.2
* Operating System: Ubuntu 16.04 LTS
* Deployment Method(snap/docker/tar/etc): Manual install
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: 8.9.4

### Steps to Reproduce:

1. Get token etc. for the rest call
2. Call /api/v1/permissions

### Expected behavior:

Response with the permissions

### Actual behavior:

Browser error:
Failed to load http://otm-rc.innovatie.ml:3000/api/v1/permisssions: Request header field X-Auth-Token is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by Pratyum** [comment] 2018-03-20 17:01
Hey there! I am new to this but I think I would like to contribute to the issue. Please let me know if I can work on this?

**Comment by graywolf336** [comment] 2018-03-20 21:52
Closing as this is currently working as intended. Currently there is an option to allow/disallow the `options` endpoint:

https://github.com/RocketChat/Rocket.Chat/blob/79b4526cfc5f08fcd4a0909fe29556a06368c467/packages/rocketchat-api/server/api.js#L34-L51

**Closed by graywolf336** 2018-03-20 21:52 UTC

**Comment by robindijkhof** [comment] 2018-03-21 16:29
@graywolf336 are you sure? As I enabled CORS under General -> REST api. Also, the other endpoints are working correctly.

**Comment by robindijkhof** [comment] 2018-03-28 06:39
@graywolf336 any response please?

**Comment by hakan-erdem-temiz** [comment] 2019-02-25 10:56
res.header(
      "Access-Control-Allow-Headers",
      "x-auth-token"
    );

it needs to x-auth-token permission in your header so you should add it to your header.
