### ISSUE TITLE
Any code generates an empty error  

### ISSUE THREAD

**Issue by lobocode** [RocketChat/Rocket.Chat#3301] opened 2016-05-19 09:58 UTC
Any code (including "comments only") that I put in the code box, generates this error empty. This prevents I can generate any webhook. The version that I am using, is the most current 0.31.0:
![image](https://cloud.githubusercontent.com/assets/1684061/15389684/7ae4d0fa-1d8e-11e6-98e4-57f59b248757.png)

Example:
![image](https://cloud.githubusercontent.com/assets/1684061/15389802/1004d8b0-1d8f-11e6-9f43-bdc9d7681320.png)

**Comment by frdmn** [comment] 2016-05-19 10:00
Hi @lobocode 

Does the error say anything more descriptive?

**Comment by lobocode** [comment] 2016-05-19 12:55
@frdmn This is the problem. It does not display error anywhere. However, prevents something be added also. It would be a mistake in the API?

**Comment by frdmn** [comment] 2016-05-19 13:55
@lobocode Intressting, I just tried to create an outgoing webhook with just a comment (`// test`) and could save it just fine.

Did you try to restart your system?

**Comment by lobocode** [comment] 2016-05-19 14:00
@frdmn Yes, I tried. If I type any text in the field, gives script error (and does not describe the error is...). I've restarted an application and ...(not solved). :(

**Comment by lobocode** [comment] 2016-05-19 17:18
Probably more people that are using this version will complain about the problem ... I believe.

**Comment by graywolf336** [comment] 2016-05-19 18:05
Please look in the logs and see what the output is there. Provide a screenshot of the logs from the web interface so we can see what the issue is.

**Comment by lobocode** [comment] 2016-05-19 18:51
@graywolf336  @frdmn 
These were the only errors generated by then:
 
![image](https://cloud.githubusercontent.com/assets/1684061/15405656/2fd32800-1dd9-11e6-8f4c-cedc98769296.png)
and 
![image](https://cloud.githubusercontent.com/assets/1684061/15405674/414b8b0e-1dd9-11e6-80c4-ceca37c7663f.png)

**Comment by lobocode** [comment] 2016-05-20 12:18
For some reason unknown, any no data is validated within the script form. I will try to investigate this. However, I have no experience with javascript.

**Comment by frdmn** [comment] 2016-05-20 12:30
@lobocode Sorry, im out of ideas right now as well - we have to wait for a response by a core dev.

**Comment by lobocode** [comment] 2016-07-20 14:25
I new error in mongo:
"scriptError" : {
        "name" : "Error",
        "message" : "EACCES, permission denied '/home/rocketchat'"
    },

But, I don't have path /home/rocketchat in my application.

**Comment by lobocode** [comment] 2016-07-20 18:04
To solve problem, I created a folder on the /home/rocketchat in project and mongo. I believe it is a stopgap measure.

**Comment by MartinSchoeler** [comment] 2017-07-17 16:43
Closing this due lack of updates in a long time. If the problem persists, please reopen this. Thanks!

**Closed by MartinSchoeler** 2017-07-17 16:43 UTC
Labels: type: need more info
