### ISSUE TITLE
Can't change password.

### ISSUE THREAD

**Issue by Robert-turbo** [RocketChat/Rocket.Chat#10730] opened 2018-05-10 14:25 UTC
### Description:

As user or admin I Can't change password. This problem occurred in previous versions. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.64.1
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc):  docker
* Number of Running Instances: 1
* DB Replicaset Oplog:  
* Node Version: 
* mongoDB Version:  v3.6.4

### Steps to Reproduce:

1. I click on my avatar image
2. My Acoount
3. Profile
4. I enter new password in "New Password"
5. Save Changes
6. In screen with password confirmation I enter password once again (ctrl + v) to be sure and click ok
7. End now i see error message "Invalid password"

All users can't change password. We checked on different computers. 
But when I use Options -> Administration -> Users -> chose user -> Edit and there change password and turn on "Require password change" than user can log in with new password and change it to new needed password. 

### Expected behavior:

I would like to chage my password. 

### Actual behavior:

Error message: "Invalid password"

### Relevant logs:
When I was trying to change to "newpassword". in logs i censored "typedPassword"

```[34mI20180510-14:19:16.106(0) [34mMeteor ➔ method getAvatarSuggestion -> userId: 2fFs864dvMCKEupis , arguments:  {} 
[34mI20180510-14:19:23.997(0) [34mMeteor ➔ method saveUserProfile -> userId: 2fFs864dvMCKEupis , arguments:  { '0':     { typedPassword: '089542----------------------------------------------',      newPassword: 'newpassword' },   '1': {} } 
[34mI20180510-14:19:26.564(0) [34mMeteor ➔ method saveUserProfile -> userId: 2fFs864dvMCKEupis , arguments:  { '0':     { typedPassword: '089542----------------------------------------------',      newPassword: 'newpassword' },   '1': {} } 
[34mI20180510-14:19:34.332(0) [34mMeteor ➔ method saveSetting -> userId: 2fFs864dvMCKEupis , arguments:  { '0': 'Log_Level', '1': '1', '2': null } ```

**Comment by tassoevan** [comment] 2018-06-11 18:17
Hello, @Robert-turbo. Could you confirm that you've been requested to confirm the new password instead of the current one? I think the modal dialog you saw is like this:

![requesting the current password](https://user-images.githubusercontent.com/2263066/41249252-f7051eea-6d89-11e8-8588-ca39247a2d60.png)

We're currently requesting the old password for security reasons, but we`re working to confirm the new one too.

**Comment by Robert-turbo** [comment] 2018-06-12 10:19
OK..

Translation is bad :)

![image](https://user-images.githubusercontent.com/25224292/41284762-86eddd16-6e3a-11e8-8384-0ab1962a74d4.png)

Wprowadź hasło ponownie - Enter password once again
Dla własnego bezpieczeństwa, należy ponownie wprowadzić hasło, aby kontynuować - For your security, you must enter password to continue. 

So it implies that it should be new password :)

**Comment by tassoevan** [comment] 2018-06-12 19:46
Oh, I see. Do you want to [fix this translation](https://github.com/RocketChat/Rocket.Chat/#translations) or suggest a better one? Any help would be appreciated. :smile:

**Comment by ggazzo** [comment] 2018-06-20 18:18
@Robert-turbo I will close this issue, as its not a bug, you are welcome to contribute and help us to translate any language, if you need some help to know how to do , pls let me know..

**Closed by ggazzo** 2018-06-20 18:18 UTC
Labels: contrib: easy, feat: user settings, type: bug

**Comment by ppz8206** [comment] 2019-12-03 21:02
Hello I am new in this kind of thins but I forgot my password and user for rocket chat. It is new fresh installaction so I don't have another users...

**Comment by jbarros35** [comment] 2020-09-17 08:58
terrible interface. the user can't forgot his own password?

**Comment by thorsteinssonh** [comment] 2020-11-30 16:46
This issue is I believe still an issue -- I can log in with my new password, and reset my password via email, and as admin i can change settings, all except for the my user profile.  Something fishy.

**Comment by arg0user** [comment] 2020-12-14 18:25
Same issue here...pw change in the account profile results in a [error-invalid-password], during the "verify" step

**Comment by thorsteinssonh** [comment] 2020-12-14 18:44
Actually I found out after a while, I could as administrator change passwords under Users admin interface.  So users interface pw change works for me, but not changing as individual users, except by email update password.
