### ISSUE TITLE
Dismiss or Remove "Go Fully Featured"

### ISSUE THREAD

**Issue by billynoah** [RocketChat/Rocket.Chat#25201] opened 2022-04-15 11:50 UTC
### Description:

A large purple "Go Fully Featured" tab now appears in the admin panel.

### Steps to reproduce:

1. Go to admin panel
2. get bombarded with an ad to "Go Fully Featured"
3. Cringe

### Expected behavior:

The invitation to "Go Fully Featured" should be something I can dismiss or easily disable.

### Actual behavior:

I can't make this thing go away.

### Server Setup Information:

- Version of Rocket.Chat Server: 4.6.2
- Operating System: Ubuntu 20.04
- Deployment Method: Manual
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.18.2
- MongoDB Version: 5.0.7

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: All

### Additional context

Can someone please direct me to the code I can patch to get rid of this purple "Go Fully Featured" tab? Our organization is not currently interested and it's distracting.

**Comment by dudanogueira** [comment] 2022-04-18 17:59
Hi!

You can hide any element in Rocket.Chat using it's selector and adding display:none as a CSS attribute in Admin > Layout > Custom Css.

For instance this is the required css snippet:

`
#rocket-chat > aside > div.flex-nav > div > div > div > div > div.rc-scrollbars-view > div > div > a.rcx-box.rcx-box--full.rcx-css-pb1san.active.rcx-css-1vogl8t,
#rocket-chat > aside > div.flex-nav > div > div > div > div > div.rc-scrollbars-view > div > div > a.rcx-box.rcx-box--full.rcx-css-pb1san.rcx-css-1vogl8t{
  display:none
}
`
This is not a bug/issue, so, closing it.

Thanks.

**Closed by dudanogueira** 2022-04-18 17:59 UTC

**Comment by billynoah** [comment] 2022-04-18 18:09
Thanks, that's helpful.

Currently this project does not have any "Feature Request" issue category or I would have selected that.  It would be good to add one if you care about community input.

**Comment by fdellwing** [comment] 2022-04-21 08:34
=> https://github.com/RocketChat/feature-requests

**Comment by jfqd** [comment] 2022-06-15 13:13
https://github.com/RocketChat/Rocket.Chat/issues/25296 => "Go fully featured" is not GDPR-Compliant!

**Comment by tuxcrafter** [comment] 2022-10-25 11:56
Has there been a followup on this from rocket.chat developers? I would like to see this "feature" being removed or fixed as well.

**Comment by vladblindu** [comment] 2022-12-15 06:37
I fully understand your need to be rewarded for your work. It's a huge amount of it. But don't pretend to offer a "free" version while, in fact it's not free, it's just another "I'll annoy you till you pay" version. Put a smaller price and accept that all "free tier" users will leave.  In the end, they are annoying anyway. Like me for instance. I suspect that the user you manage to annoy by placing unaccessible features with the "only in paid version" and omnipresent "give me some money" action buttons all over the place, would rather move away and try to find some other less annoying free solution rather than upgrading to the paid version .
By the way, [this](https://github.com/RocketChat/Rocket.Chat/issues/25201#issuecomment-1101611057) doesn't work anymore.

**Comment by tuxcrafter** [comment] 2022-12-15 07:04
```
.rcx-box.rcx-box--full.rcx-css-ebq3kg {
  display: none !important;
}
.rcx-css-1vogl8t {
  display: none !important;
}
```

**Comment by ISSKsec** [comment] 2023-08-23 10:21
.rcx-box.rcx-box--full.rcx-css-ebq3kg {
  display: none !important;
}
.rcx-css-1vogl8t {
  display: none !important;
}

/* Estilos personalizados para ocultar el enlace y su contenido */
.rcx-sidebar-item--clickable[href="/admin/info"] {
  display: none;
}

/* Estilos personalizados para ocultar el enlace y su contenido */
.rcx-sidebar-item--clickable[href="/admin/upgrade/go-fully-featured-registered"] {
  display: none;
}
