### ISSUE TITLE
Members list tab scrolls horizontally.

### ISSUE THREAD

**Issue by pkgodara** [RocketChat/Rocket.Chat#7981] opened 2017-08-30 14:14 UTC
### Description:
Initially
![screenshot from 2017-08-30 19-45-11](https://user-images.githubusercontent.com/16938349/29876952-d8ee010a-8dbb-11e7-94f3-4d9a7b6f2c33.png)

Slight scroll

![screenshot from 2017-08-30 19-40-54](https://user-images.githubusercontent.com/16938349/29876835-6b0b9f08-8dbb-11e7-9d69-6376659ef338.png)

More scroll
![screenshot from 2017-08-30 19-46-22](https://user-images.githubusercontent.com/16938349/29877013-fb5689ce-8dbb-11e7-97e5-bd31f556e6ae.png)

### Server Setup Information:

Demo server.

### Steps to Reproduce:

1. open sidepane -> members list
2. try scrolling horizontally (on touchpad).

### Expected behavior:

only vertical scroll

### Actual behavior:

Scrolls horizontally & would eventually hide.

**Comment by MartinSchoeler** [comment] 2017-08-31 19:07
@pkgodara  I could not reproduce this could give us more info on your browser and if you can reproduce this on the latest develop branch? Thanks

**Comment by pkgodara** [comment] 2017-09-01 07:38
Still presists in Demo server. Browser: `Version 60.0.3112.113 (Official Build) (64-bit)` .

Scroll horizontally on **touch pad**.
Vertical scroll is fine, but accidental horizontal scroll moves it.

**Comment by rodrigok** [comment] 2017-09-25 16:18
@pkgodara Can you test it again and let me know if you can reproduce in current demo server?

**Comment by pkgodara** [comment] 2017-09-25 16:41
@rodrigok Still there in latest demo.

**Comment by pkgodara** [comment] 2017-09-25 16:46
Happens only with **scrollable** (having more members than single page i.e. needs scroll bar) Members list, not with non-scrollable. And only in Members list, not in scrollable File list or scrollable mentions.

**Comment by rodrigok** [comment] 2017-09-25 21:35
I can't reproduce, which browser are you using?

**Comment by pkgodara** [comment] 2017-09-26 03:07
Happens only on chrome (Ubuntu). Sometimes on Windows chrome also.

**Comment by TwizzyDizzy** [comment] 2018-02-15 10:28
@rocket-cat close

Closing, since I cannot reproduce this in the new UI in 0.61.1 on Chromium. If you disagree, please get back to me by mentioning me.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-02-15 10:28 UTC
Labels: stat: waiting response, subj: ui/ux
