### ISSUE TITLE
reverse proxy rocket.chat at other port

### ISSUE THREAD

**Issue by gaodoo** [RocketChat/Rocket.Chat#3044] opened 2016-04-27 02:54 UTC
Your Rocket.Chat version: 0.27
when i run a rocket.chat by docker behind nginx at other port.
there's something wrong with live-chat module .
when visitor post a message , the livechat ui echo 'token already used'

**Comment by gaodoo** [comment] 2016-04-27 06:41
the chrome-devtools console show : 'Error invoking Method 'stream-typing ':method not found.

**Comment by MartinSchoeler** [comment] 2017-03-28 13:25
@gaodoo  Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by sampaiodiego** [comment] 2017-08-03 12:38
closing this since no feedback was provided

**Closed by sampaiodiego** 2017-08-03 12:38 UTC
Labels: feat: livechat, stat: waiting response, type: bug
