### ISSUE TITLE
Remove user while invite users when creating a new channel

### ISSUE THREAD

**Issue by NIghtCell** [RocketChat/Rocket.Chat#9892] opened 2018-02-26 08:11 UTC
I experienced the issue, that always the first user of the userlist is removed, when I click on the x sign near to the username. This problem only appears when I want to create a new channel. If I just click on the username (not the x), then everything works fine and the current selected user is removed.

![issue9892](https://user-images.githubusercontent.com/30755444/36659769-dc276f9e-1ad5-11e8-8d59-afbf5597c236.gif)

Deployment Information:

Version of Rocket.Chat Server: 0.60.4
Operating System: Debian 9.3
Deployment Method(snap/docker/tar/etc): tar
Number of Running Instances: 1
DB Replicaset Oplog: -
Node Version: 8.9.4-1nodesource1
mongoDB Version: 1:3.2.11-2+deb9u1

**Comment by kaiiiiiiiii** [comment] 2018-02-26 08:12
Can you please fill out the issue report? (Version, deployment, ...)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TwizzyDizzy** [comment] 2018-02-26 12:54
@rocket-cat close

Hi @NIghtCell ... as @kaiiiiiiiii says:

I am temporarily closing this issue as you have not used our [issue template](https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/ISSUE_TEMPLATE.md) (the text that is already filled in automatically, when you open a new issue). Please understand, that in order to solve your issue as fast as possible, we need to understand your issue and your setup as good as possible to first reproduce it on our side and then fix it.

Therefore, we kindly ask you to adhere to the issue template and provide us with the information we need. For that, please edit your inital post rather than replying with the issue template. We will then have a look at your feedback and re-open the issue.

This benefits all users as we are able to understand and fix issues faster. Thank you for understanding and being kind to us and others :)

Cheers
Thomas

**Comment by NIghtCell** [comment] 2018-02-28 08:26
Sorry, I had to find out details about the deployment. I hope that this is enough information. Please open the issue again

**Comment by TwizzyDizzy** [comment] 2018-03-01 12:06
@rocket-cat open

Well your information still doesn't include everything that we asked for, yet since I could just reproduce it on 0.61.2 (no access to a 0.62.0 currently) I will reopen this issue.

Cheers
Thomas

**Comment by NIghtCell** [comment] 2018-03-26 06:45
Hello guys, sorry for my late answer. Today I found out the whole deployment information. I hope that you now have everything that you asked for.

**Comment by NIghtCell** [comment] 2018-04-09 08:26
Hey guys. I don't want to annoy you with ongoing questions about the progress, but is there anything that I can try to do in order to fix the bug? 
Thanks a lot in advance for all your effort!

**Comment by gdelavald** [comment] 2018-04-09 14:28
@theorenck can you triage this? I have a fix for it already.

**Closed** 2018-04-16 14:44 UTC
Labels: subj: ui/ux, type: bug, type: regression
