### ISSUE TITLE
Encrypted photos on rocketchat iOS app display issues 

### ISSUE THREAD

**Issue by lovekyleman** [RocketChat/Rocket.Chat#33189] opened 2024-08-30 10:34 UTC
Encrypted photos on rocketchat iOS app not friendly to users
When you receive photos which only display for 2 seconds and then go "white" (see the photo below)
![image](https://github.com/user-attachments/assets/3328a139-baa3-417b-be82-2581e8de8406)
Wanna see the photos? You have to exit the chat window and then go back to the chat window again and photos can display normally
That's really unfriendly 

rocketchat iOS APP version 4.50.1.63099 (the latest)

rocketchat 6.10.4 and above(including 6.12.0-rc.2) has the same issue 
Maybe it's rocketchat iOS app's problem because works perfectly on browsers 

_Originally posted by @lovekyleman in https://github.com/RocketChat/Rocket.Chat/issues/33143_

**Comment by reetp** [comment] 2024-08-31 10:39
Please stop opening new issues. 

Stay on one bug.

Closing as duplicate of #32963

**Closed by reetp** 2024-08-31 10:39 UTC
Labels: duplicate

**Comment by reetp** [comment] 2024-08-31 10:50
No amount of nagging will make anything move faster. This is open source, not paid support. It will get fixed on their own schedule.

FYI this had already been referred to the internal team. There is a huge mass of internal systems behind all this that you cannot see - github is just the open source end result of the internal processes - the published result.

It takes a lot of time to process this so it may not even make release in 6.12.x  - not helped by the fact that most of the team were off yesterday.

Again - such is the nature of open source. If you have paid support then you can contact them accordingly. Otherwise you can either fix it yourself, or wait for them to decide to do it.

Thanks for your patience.
