### ISSUE TITLE
Dropdown menu not closing in country selection field

### ISSUE THREAD

**Issue by Giridharan002** [RocketChat/Rocket.Chat#31200] opened 2023-12-11 03:36 UTC
## Description:
I'm experiencing an issue where the dropdown menu in the country selection field does not close automatically after selecting a country. This issue is occurring when I locally set up Rocket.Chat and run the server. It is redirected to the admin page where it asks for the admin details. In the next page, which is the organization details page, I encounter this issue. The dropdown menu remains open, making it difficult to click the 'Next' button which is located underneath the dropdown menu.

## Steps to Reproduce:
1. Clone the Rocket.Chat repository and run the server.
2. Navigate to the Admin panel and enter the necessary details.
3. Move to the next page and fill in the organization details.
4. Select a country from the dropdown menu in the country selection field.

## Expected behavior:
The dropdown menu should close automatically after selecting a country.

## Actual behavior:

https://github.com/RocketChat/Rocket.Chat/assets/123318221/dff91b48-c805-486c-9eb4-b24cab871931

## Server Setup Information:
- Rocket.Chat Version: 6.6.0-develop
- Operating System: Ubuntu
- DB Replicaset Oplog: Enabled
- Node.js Version: v14.21.4
- MongoDB Version:6.0.3
- Deployment Method: Gitpod

## Additional Information:
I have not made any changes to the default Rocket.Chat setup. I'm using the default settings and configurations.

Please let me know if you need any additional information to help diagnose this issue.

**Comment by casalsgh** [comment] 2023-12-11 14:05
@Giridharan002 qq: do you mind trying to find and select the country directly from the dropdown instead of writing on the field? 
PS: Not a fix, but should be a temporary work-around. Let us know if that unlocks you for the time being.

**Comment by casalsgh** [comment] 2023-12-11 14:25
Another option seems to write and scroll down with keyboard instead of click the country using your mouse for country selection.

**Comment by Giridharan002** [comment] 2023-12-11 15:33
Thank you for the suggestions, @casalsgh. Unfortunately, both attempting to select the country directly from the dropdown and writing and scrolling down with the keyboard didn't resolve the issue. The dropdown menu still doesn't close as expected. I appreciate your help. 😊 May I try to work on resolving this issue and submit a pull request for it?

**Comment by casalsgh** [comment] 2023-12-11 16:26
@Giridharan002 sure, please go ahead, and thanks!

**Comment by casalsgh** [comment] 2023-12-11 17:38
Also, any chance you can check with different web browsers? seems Crome is somewhat working better

**Comment by Devansht420** [comment] 2023-12-12 06:26
@casalsgh Hey, I tried this with chrome and the issue still persists.

**Comment by ItsDee19** [comment] 2023-12-12 08:56
Hi @casalsgh, I can help resolving this issue.

**Comment by casalsgh** [comment] 2023-12-13 14:45
@ItsDee19 assigned Giridharan002 as he was first reporting and mentioning he would tackle it.
Will ping tag you here for this or other issues in the future if that is ok.

**Comment by Devansht420** [comment] 2023-12-14 07:16
@casalsgh is it okay if i look into the issue as well, if it wont be solved in some time maybe i can help.

**Comment by casalsgh** [comment] 2023-12-14 19:25
Yes, sure, give it a go @Devansht420

**Comment by Giridharan002** [comment] 2023-12-16 16:57
Hi @casalsgh,
I've spent a lot of time searching for the source of a particular [issue](https://github.com/RocketChat/Rocket.Chat/issues/31200), and I believe I've identified the problem in the [SelectFiltered.tsx ](https://github.com/RocketChat/fuselage/blob/2d27a323c08e619588cedb23894b5833f0095c7f/packages/fuselage/src/components/Select/SelectFiltered.tsx)file within the "[fuselage](https://github.com/RocketChat/fuselage)" repository.
However, I'm a bit lost on how "fuselage" ties into the main repository. Could you kindly provide guidance on how I can locate and address the issue in the main repository?
Thanks in advance for your help!

**Comment by Devansht420** [comment] 2023-12-17 05:41
Hi @casalsgh @Giridharan002 I've spent some with issue in the beginning it was persisting but now I'm unable to reproduce it,
please let me know if it is still there or not.
[Screencast from 14-12-23 01:01:20 PM IST.webm](https://github.com/RocketChat/Rocket.Chat/assets/124887084/d31359a8-c2e1-4a38-a66e-6481cd5bcc2f)

**Comment by casalsgh** [comment] 2023-12-18 13:54
> Hi @casalsgh @Giridharan002 I've spent some with issue in the beginning it was persisting but now I'm unable to reproduce it, please let me know if it is still there or not. [Screencast from 14-12-23 01:01:20 PM IST.webm](https://github.com/RocketChat/Rocket.Chat/assets/124887084/d31359a8-c2e1-4a38-a66e-6481cd5bcc2f)

Problem is still happening

**Comment by casalsgh** [comment] 2023-12-18 13:54
> Hi @casalsgh, I've spent a lot of time searching for the source of a particular [issue](https://github.com/RocketChat/Rocket.Chat/issues/31200), and I believe I've identified the problem in the [SelectFiltered.tsx ](https://github.com/RocketChat/fuselage/blob/2d27a323c08e619588cedb23894b5833f0095c7f/packages/fuselage/src/components/Select/SelectFiltered.tsx)file within the "[fuselage](https://github.com/RocketChat/fuselage)" repository. However, I'm a bit lost on how "fuselage" ties into the main repository. Could you kindly provide guidance on how I can locate and address the issue in the main repository? Thanks in advance for your help!

@hugocostadev can you advise on this one?

**Comment by hugocostadev** [comment] 2023-12-18 14:25
> Hi @casalsgh, I've spent a lot of time searching for the source of a particular [issue](https://github.com/RocketChat/Rocket.Chat/issues/31200), and I believe I've identified the problem in the [SelectFiltered.tsx ](https://github.com/RocketChat/fuselage/blob/2d27a323c08e619588cedb23894b5833f0095c7f/packages/fuselage/src/components/Select/SelectFiltered.tsx)file within the "[fuselage](https://github.com/RocketChat/fuselage)" repository. However, I'm a bit lost on how "fuselage" ties into the main repository. Could you kindly provide guidance on how I can locate and address the issue in the main repository? Thanks in advance for your help!

Hey @Giridharan002 check it out our docs about that: https://developer.rocket.chat/fuselage-design-system/testing/fuselages-component-in-rc

You can start the fuselage package normally with `cd packages/fuselage` and `yarn start`, if the error happens there, you can open a PR in the fuselage repo.

**Comment by Giridharan002** [comment] 2023-12-18 15:51
@hugocostadev Thanks for sharing! I'll check out the docs! 👍

**Comment by hugocostadev** [comment] 2023-12-20 18:55
I'm working on that, the country select was using an old component, I replaced with the newest one in this PR: https://github.com/RocketChat/fuselage/pull/1250

**Comment by Sayan4444** [comment] 2023-12-24 05:30
Please close this issue if this is solved

**Closed** 2023-12-24 13:03 UTC
Labels: type: bug, squad: team-collab
