### ISSUE TITLE
File Upload: Could not get error dialog

### ISSUE THREAD

**Issue by nishimaki10** [RocketChat/Rocket.Chat#4311] opened 2016-09-15 15:09 UTC
Your Rocket.Chat version: HEAD  636f5ab0b7fa14bae72b40b0fdcc8577878329a4

I get silent abort when I try uploading over limit filesize or invalid filetype.
(I use GridFS store.)

**Comment by MartinSchoeler** [comment] 2016-09-16 13:07
this is a duplicate of #4235

**Closed by MartinSchoeler** 2016-09-16 13:07 UTC
Labels: feat: file sharing, type: bug
