### ISSUE TITLE
Turn off notifications for @all type mentions

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#1654] opened 2015-12-14 12:28 UTC
Please allow users to turn off notifications for @all  - every time my browser makes a noise I have to stop whatever I am doing, switch to the browser, hunt for the tab that made noise, find the channel that has a notification, and discover somebody just asked "how are you doing?". Right now I close the browser out of self-protection or I get nothing done at all, but I don't always remember to open the chat session again to find out how cow-orkers are doing and I miss stuff because of a feature that is initially supposed to help me  NOT miss things
##

**Comment by geekgonecrazy** [comment] 2016-01-18 04:09
Ref: #1268 possibly consolidate.

**Comment by geekgonecrazy** [comment] 2016-05-12 03:17
@sinteur 

Now that we have:

![image](https://cloud.githubusercontent.com/assets/51996/15203114/1f96e9ae-17c6-11e6-9d40-c76b6a200931.png)

Does this do the trick for you?

**Comment by gwillen** [comment] 2016-12-09 01:34
The problem is, there's no distinction in 'mentions' between "mentions of me" and "mentions of @all". So you can't disable notifications on @all without disabling them completely.

**Comment by gwillen** [comment] 2016-12-09 01:41
Here's an example of how Slack handles this (only available on paid teams, it seems, so I had a friend with a paid team screenshot it:)

https://www.dropbox.com/s/fdjh079itnwt7fk/Selection_049.png?dl=0

Notice the "mute notifications for @everyone and @here" option, which preserves notifications for real mentions.

**Comment by engelgabriel** [comment] 2017-02-14 15:26
![image](https://cloud.githubusercontent.com/assets/1000217/22935258/347bd1da-f2b9-11e6-8824-ef67e95cdf1b.png)

**Comment by engelgabriel** [comment] 2017-02-14 15:38
Refs https://github.com/RocketChat/Rocket.Chat/issues/1654

**Comment by digitalfrood** [comment] 2017-08-17 11:48
Any updates on this issue? Slack handles notification settings for `@all` and `@here` really well.

**Comment by pokapow** [comment] 2017-08-22 16:18
Yes any up ? That should be greate to choose what kind of notification a group can do in permission menu.

**Comment by gregs007** [comment] 2017-11-10 19:39
Agreed.. I personally like @all notifications, but other users hate it and they should be able to disable it. I suggest making @here and @all granular (i.e. you can disable one or both)

**Comment by geekgonecrazy** [comment] 2018-01-03 01:01
Its not so much about not liking the functionality.  Its more about not wanting just anyone to always be able to use it.

**Comment by gregs007** [comment] 2018-02-01 17:37
At the very least, a user should be able to individually configure if they get @all or @here notifications. I personally like getting them, but at least half my users hate it. At the end of the day, every user should be able to customize how they receive notifications granularly. For now, a simple idea is to make two user-configurable options in their _My Account_ page: 1. Mute all @here notifications, 2. Mute all @all notifications.

In the future, being able to configure this per channel would be awesome. But for now, the above would get a big chunk of the low hanging fruit.

**Comment by isabellarussell** [comment] 2018-03-13 11:42
This issue is now closed as the intention behind '@all' is that it does notify those concerned.

**Comment by evgeni** [comment] 2018-03-13 11:57
@isabellarussell IMHO not, as the whole point of this issue is that people don't want to be concerned ;-)

**Comment by bitbruder** [comment] 2018-03-13 14:39
Well, you could add Notification Settings for each Channel then?

![image](https://user-images.githubusercontent.com/15855432/37348502-82b1cbb6-26d4-11e8-9127-e08de28183f3.png)

It can then be enabled or disabled, if the Admin thinks that the intention behind '@ALL' is that it does notify those concerned.

**Closed** 2018-04-21 02:02 UTC
Labels: feat: channel settings, feat: notification, feat: user settings, type: improvement
