### ISSUE TITLE
npm install gc-stats 403 Forbidden

### ISSUE THREAD

**Issue by broadcast98** [RocketChat/Rocket.Chat#33363] opened 2024-09-25 18:45 UTC
**ERROR MESSAGE:**
`
> gc-stats@1.4.0 install /usr/local/src/rocket.chat/bundle/programs/server/npm/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.4.0/Release/node-v83-linux-x64.tar.gz

`
**after change "gc-stats" to 1.5.0:**
`
> gc-stats@1.5.0 install /usr/local/src/rocket.chat/bundle/programs/server/npm/node_modules/gc-stats
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install response status 403 Forbidden on https://node-binaries.s3.amazonaws.com/gcstats/v1.5.0/Release/node-v83-linux-x64.tar.gz

`

can't install gc-stats , because the file is not exists on amazonaws.

WHY THIS ISSUE existed for more than a year?

are there new users download and install the new versions of Rocket.Chat ?

why the new versions are released without any installing check?

**Comment by reetp** [comment] 2024-09-25 20:11
Closing as duplicate of

https://github.com/RocketChat/Rocket.Chat/issues/32503

Also note issues without a completed template will be ignored.

**Closed** 2024-09-25 20:11 UTC
Labels: duplicate
