### ISSUE TITLE
Message suggestions showing duplicate entries

### ISSUE THREAD

**Issue by abhithool** [RocketChat/Rocket.Chat#19651] opened 2020-11-23 09:05 UTC
### Description:

We have been using RocketChat (version 3.7.1) for the last few months. 
A few days ago we noticed that while typing in a new message, when we tried using @mentions, the RocketChat suggestions would show duplicate entries. None of our IT team members have neither made any changes to our self hosted RocketChat server nor have they changed any settings or permissions. So we are not sure how these new suggestions have started showing up all of a sudden? We also saw another user reporting the same issue - [Duplicate result when searching for an account via “@” in the RocketChat system](https://forums.rocket.chat/t/duplicate-result-when-searching-for-an-account-via-in-the-rocketchat-system/9099) But so far no one seems to have replied to him either.

### Steps to reproduce:

1.  Go to messages and type @username 
2.  A suggestions popup will show up, making it easier for the user to select the appropriate username
3.  Right now, the suggestions popup shows, the following - 
    Suggestion from recent messages
    Some more suggestions
    Suggestions which are Not in channel

### Expected behavior:
1.  Go to messages and type @username 
2.  A suggestions popup will show up, making it easier for the user to select the appropriate username
3.  The suggestions popup shows ONLY the appropriate username. 

I am not sure what how the suggestions have changed all of a sudden? These multiple suggestions are causing a lot of confusion for our users. They think that there are multiple users with the same username in rocketchat, which of course isn't true. 

We have 2 self hosted RocketChat servers. We thought that maybe upgrading our servers will solve this issue. Therefore, we decided to upgrade one server from version 3.7.1 to version 3.8.0, but the issue persisted. We have also updated the same server to version 3.8.1 but the issue still remains. 

Can someone in rocketchat team please let us know how we can go about the settings to show suggestions as before? 
**We specifically do NOT want to show Suggestion from recent messages & Suggestions which are Not in channel**
Any help is much appreciated.

### Actual behavior:

[View screenshot here](https://aws1.discourse-cdn.com/business4/uploads/rocketchat/optimized/2X/1/18fd28a943ddfa1e2c50970e2cc0c2c83dfd626e_2_877x750.jpeg)

### Server Setup Information:

Version of Rocket.Chat Server: 3.7.1
Operating System: Ubuntu 4.15.0-118-generic (64 bit)
Deployment Method:
Number of Running Instances: 1
DB Replicaset Oplog:
NodeJS Version: v12.18.4
MongoDB Version: v4.0.3

### Client Setup Information

- Desktop App or Browser Version: we are using chrome (Version 86.0.4240.198 (Official Build) (64-bit)) and firefox (83.0 (64-bit)) browser
- Operating System: Windows 10 Home version 1909

**Comment by ankar84** [comment] 2020-11-23 12:18
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/19225

**Comment by MartinSchoeler** [comment] 2020-11-23 14:34
🔝

**Closed by MartinSchoeler** 2020-11-23 14:34 UTC
