### ISSUE TITLE
Update snap stable builds to 0.64.x

### ISSUE THREAD

**Issue by tim-soft** [RocketChat/Rocket.Chat#10693] opened 2018-05-07 17:25 UTC
@rodrigok 
The latest Snap build under `stable` is 0.63.3, is there a reason v0.64.x is still under RC? 

https://snapcraft.io/rocketchat-server

![capture](https://user-images.githubusercontent.com/10257939/39714957-e5668fc8-51e8-11e8-8237-db4dc06bdb08.PNG)

**Comment by TwizzyDizzy** [comment] 2018-05-08 08:39
@rocket-cat close

Closing this. It's a duplicate of #10656.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-05-08 08:39 UTC
