### ISSUE TITLE
Renaming user results in incorrect usernames in RocketChat.models.Rooms

### ISSUE THREAD

**Issue by garychapman** [RocketChat/Rocket.Chat#9157] opened 2017-12-18 07:19 UTC
### Description:

Renaming a user doesn't get reflected properly in RocketChat.models.Rooms

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.4
* Operating System: Windows 10
* Deployment Method(snap/docker/tar/etc): meteor via Windows command shell
* Number of Running Instances:  1
* Node Version: 8.5.0

### Steps to Reproduce:

1. I have a DM between 2 users:  _jekyll_ and _gabriel_, which I can view via `meteor shell`:

\> RocketChat.models.Rooms.findOneById('HR4L8iaJAQgJCsJa2oqH54pehs5pAopoeQ')

{ _id: 'HR4L8iaJAQgJCsJa2oqH54pehs5pAopoeQ',
// deleted stuff
  **usernames: [ 'jekyll', 'gabriel' ], \<-- as expected**
  username: 'jekyll' }

2. If I rename _jekyll_'s username to _hyde_ via /admin/profile, I then see:

{ _id: 'HR4L8iaJAQgJCsJa2oqH54pehs5pAopoeQ',
// deleted stuff
  **usernames: [ 'jekyll', 'hyde' ], \<-- why is jekyll still here, and not gabriel?**
  username: 'gabriel' }
>

### Expected behavior:

I would expect to see **usernames: ['gabriel', 'hyde']** after the rename has occurred

### Actual behavior:

The original username is still stored, which then causes `room.usernames.indexOf(user.username)` in `getRoomIdByNameOrId` to return -1 when _gabriel_ tries to send a message to the newly-renamed _hyde_

**Comment by rodrigok** [comment] 2017-12-18 18:12
@garychapman I wasn't able to reproduce your but, are you able to reproduce it consistently?

How many users and rooms do you have in your instance?

Did you go to `account/profile` or `admin/users` to edit the user's data?

**Comment by wonkaba** [comment] 2019-02-01 19:50
Was any progress made on this? I am definitely still seeing the issue. When changing the user's name from the admin/users page, it breaks the rooms. Anyone who has previously been in a room with them gets an error when trying to chat with their new username

Currently using version 0.69.1

**Comment by ggazzo** [comment] 2019-02-05 15:36
@wonkaba please try the last version, I'm confident we fixed :)

**Comment by wonkaba** [comment] 2019-02-06 23:35
> @wonkaba please try the last version, I'm confident we fixed :)

Upgraded to 0.74.1 today and this is still an issue.

**Comment by ggazzo** [comment] 2019-03-12 16:41
@garychapman @wonkaba 
please I couldnt reproduce here... could you help me ?
![ezgif-2-15a821a0daa6](https://user-images.githubusercontent.com/5263975/54218414-4c8f7d00-44cc-11e9-8907-71a78e371a77.gif)

**Comment by engelgabriel** [comment] 2019-04-06 07:01
We will close this issue until we receive more information to reproduce the problem. Please reopen if it persists.

**Closed by engelgabriel** 2019-04-06 07:01 UTC
Labels: stat: need more info, type: bug
