### ISSUE TITLE
Sort user new messages or current activity on DM lists

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#4486] opened 2016-09-29 03:26 UTC
Rocket.Chat version: 0.41.0
For a quick reply of a concurrent chat from different user it should sort user new messages or current activity on DM lists.

**Comment by MartinSchoeler** [comment] 2016-11-18 14:59
duplicate of #4377

**Closed by MartinSchoeler** 2016-11-18 14:59 UTC
Labels: feat: app settings, type: improvement
