### ISSUE TITLE
Android 4.4.2 Note 2 , Rocket Chat version 2.3.1: error downloading files

### ISSUE THREAD

**Issue by vegegoku** [RocketChat/Rocket.Chat#3447] opened 2016-06-02 22:52 UTC
Your Rocket.Chat version: Android App version 2.3.1
Rocket.chat is installed in self hosted mode
i open the app then a dialog to enter the server is open, i enter the server then tap on connect,
the message validating server appear, the message downloading files appear and here is the problem
no files are downloading and then i got an error message saying error downloading files.

![screenshot_2016-06-01-19-27-00](https://cloud.githubusercontent.com/assets/5379625/15763616/b8afaf04-292d-11e6-81ac-4de04aff16cb.png)

what can i do to fix this issue?

**Comment by mashedkeyboard** [comment] 2016-06-07 06:22
Also having this issue after attempting a Cordova build for the web.

**Comment by highvoltage** [comment] 2016-07-15 08:19
I can confirm this issue on multiple Android 4.4.x devices.

**Comment by markus-wi** [comment] 2016-07-20 08:03
Same here. Connecting to the demo rocketchat server works, though

**Comment by Almax** [comment] 2016-07-20 17:45
Got same issue too.
i've deployed RC on VPS with url=myhost.com and its work when i try to access from browser
then i've compiled RocketChatCordova
when i try to run it on a device i get same error - Error downloading files..
RC version 0.35
RCCordova - latest
on the server i have self signed SSL

**Comment by MartinSchoeler** [comment] 2017-07-13 20:39
I am going to close this issue due to the lack of any update for so long and the rapid speed of changes that has happened with Rocket.Chat. If you happen to experience this with the latest version, please feel free to open a new issue with updated details. Thanks

**Closed by MartinSchoeler** 2017-07-13 20:39 UTC
