### ISSUE TITLE
No media preview for bot replies

### ISSUE THREAD

**Issue by CrystalMethod** [RocketChat/Rocket.Chat#1108] opened 2015-10-15 06:31 UTC
Is this supposed to be working?

![bildschirmfoto 2015-10-14 um 21 45 42](https://cloud.githubusercontent.com/assets/372398/10498147/559cf364-72ca-11e5-8aee-cc4a3a7be8ff.png)

**Comment by gmsecrieru** [comment] 2015-10-15 14:20
Are you running an up-to-date version? I could not reproduce this on our [Demo Server](https://demo.rocket.chat)

![screen shot 2015-10-15 at 11 19 23](https://cloud.githubusercontent.com/assets/190883/10516437/a3e0b6aa-732e-11e5-9c67-8ed00b1a2070.png)

**Comment by geekgonecrazy** [comment] 2015-10-15 15:29
Somethings for sure different.  The styling of the text from the bot is off.. This may be something from @leefaus or @sampaiodiego in relation to PR #1077 ?

https://github.com/RocketChat/Rocket.Chat/pull/1077#issuecomment-148109650

**Comment by sampaiodiego** [comment] 2015-10-15 17:02
so, the default behavior is to always show embed preview.
@CrystalMethod what are the settings on your instance on API page?

![image](https://cloud.githubusercontent.com/assets/8591547/10521275/4e218430-7345-11e5-94a5-c4c144f2296a.png)

**Comment by CrystalMethod** [comment] 2015-10-15 18:41
My test setup:

* repo cloned
* Rocket.Chat started via cmd line ``meteor``
* Rocket.Chat adapter started via Docker

My screen looks a little bit different but option *embed* is ``true``.

![bildschirmfoto 2015-10-15 um 20 35 28](https://cloud.githubusercontent.com/assets/372398/10523792/803473f6-737c-11e5-886d-182d67f8d6fe.png)

**Comment by jonbaer** [comment] 2015-10-20 18:54
I have noticed that the hubot I am running when using the Google images script tends to fail on some URLs ...

**Comment by CrystalMethod** [comment] 2015-10-20 19:16
Do you mean
```
Encountered an error :( Error: getaddrinfo ENOTFOUND ajax.googleapis.com
```
? I get this error since I pulled the latest changes yesterday or the day before. But I'm not sure if this is caused by these changes. 

Does ``bot map me`` or ``bot ship it`` work for you? Embedding images/maps/media is meant here.

**Comment by loukash** [comment] 2015-10-29 10:31
I have the same problems :(
Embed media preview doesn't show.

**Comment by marceloschmidt** [comment] 2016-02-04 18:23
Closing in favor of #1194

**Closed by marceloschmidt** 2016-02-04 18:23 UTC
Labels: type: need more info
