### ISSUE TITLE
Atualizando sozinho e limpando o database

### ISSUE THREAD

**Issue by nicolasdezena** [RocketChat/Rocket.Chat#9370] opened 2018-01-09 20:00 UTC
* Version of Rocket.Chat Server: 0.59.3
* Operating System: Cent OS 7
* Deployment Method(snap/docker/tar/etc): tar
* Node Version: v4.5.0

O Rocketchat esta atualizando sozinho e limpando o banco!! O que eu faço para isso n acontecer?

Aconteceu ontem e hoje 3x, ainda bem que fazemos o bkp a cada 1 hora

Alguem me ajuda?
Abs

**Comment by TwizzyDizzy** [comment] 2018-03-31 21:18
@rocket-cat close

Hi @nicolasdezena

I'm closing this as this is probably not a bug but rather some other error. Also: if this still persists on the latest Rocket.Chat version, please add additional logs so we can see what's going wrong.

Cheers
Twizzy

**Closed by TwizzyDizzy** 2018-03-31 21:18 UTC
