### ISSUE TITLE
Update installation failing

### ISSUE THREAD

**Issue by fbroda** [RocketChat/Rocket.Chat#23746] opened 2021-11-18 07:48 UTC
Rocket Chat desktop app alerts me almost daily that a new version is available and offers the options "Skip", "Remind" and "Install update". Selecting the "Install Update" option promises "You will be notified when the update is ready", but nothing ever happens.

I have been observing this problem since at least Rocket Chat Desktop App 3.2.x and have manually installed several updates so far. 
Currently I have Rocket Chat Desktop App 3.5.6 installed: I will now manually update to version 3.6.0. The release notes give no indication that the problem might be solved by now.

My system is Windows 10 Release 21H1 (x86_64).

**Comment by ankar84** [comment] 2021-11-18 07:56
duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1670
Closing this in favor of original issue.
You can comment there.

**Closed by ankar84** 2021-11-18 07:56 UTC
