### ISSUE TITLE
Links with double dots are not recognized as links

### ISSUE THREAD

**Issue by fracz** [RocketChat/Rocket.Chat#8479] opened 2017-10-13 12:36 UTC
### Description:

If the link contains double dot `..`, it is not recognized as a link (it is not clickable).

[Gerrit](https://www.gerritcodereview.com/) uses such links to indicate differences between two changes (e.g. http://my-gerrit.org/1234/23..45/file.java).

### Server Setup Information:

* Version of Rocket.Chat Server: 0.58.2

**Comment by TwizzyDizzy** [comment] 2018-04-16 23:17
@rocket-cat close

Very likely a duplicate of #5838.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-04-16 23:17 UTC
Labels: feat: message, type: bug
