### ISSUE TITLE
Domain Whitelist is not working

### ISSUE THREAD

**Issue by miscs** [RocketChat/Rocket.Chat#1443] opened 2015-11-19 16:11 UTC
I pulled the latest docker version. Reproduction-Steps

Admin->Accounts->Registration
Allowed Domain List: gmail.com

Still possible to register new users using yahoo.com or any other domain.

**Comment by geekgonecrazy** [comment] 2015-11-23 03:34
@miscs did you happen to restart the docker image after?  This might be one of these things that requires a restart.

**Comment by stevenmirabito** [comment] 2015-11-23 07:22
I can confirm that the whitelist doesn't appear to do anything, on a fresh install from today. I set registrations to be limited to my organization's domain and test@test.com can still register.

**Comment by miscs** [comment] 2015-11-23 08:24
yes I did a restart my docker image but still whitelist has no effect...

**Comment by geekgonecrazy** [comment] 2015-11-23 16:10
Let me see if I can replicate this, then we'll go from there.

**Comment by geekgonecrazy** [comment] 2015-11-25 17:29
@miscs I get internal server error is this what you guys get or it lets you fully register and login?

**Comment by geekgonecrazy** [comment] 2015-11-25 17:41
I didn't notice this until now but this is duplicate of #1360

**Closed by geekgonecrazy** 2015-11-25 17:41 UTC
Labels: type: need more info
