### ISSUE TITLE
Recieving push notifcations for all messages

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#2399] opened 2016-03-01 22:40 UTC
Your Rocket.Chat version: 0.20, minus one commit because that is what docker is pulling
I am having a weird issue where it seems that all messages, including my own, on public channels and private chats directed at me trigger a push notification. I have checked all the push notification settings I can find, rebooted the server, and toggled push notifications in the admin panel and nothing seems to change it. I have push notifications currently turned off in all channels too and yet still receive them.

**Comment by marceloschmidt** [comment] 2016-03-02 14:04
Do you mean the Desktop Notifications? Or Mobile Push Notifications? Are there other users on your instance, do they also experience this?

**Comment by homberger** [comment] 2016-03-02 15:50
Different instance, but we have at least to Mac users with this problem. I am one of them.
We are using Rocket.Chat 19.0, Rocket.Chat.Electron for Mac 1.1.0 and the iOS-App.
Which infos would help to identify the problem?

**Comment by ulope** [comment] 2016-03-02 15:52
I'm on the same instance as @homberger and also receive notifications (desktop and push) for each and every message (even my own in some channels!)

**Comment by marceloschmidt** [comment] 2016-03-02 16:47
@homberger and @ulope do you mean the Desktop Notifications, like this one:

![image](https://cloud.githubusercontent.com/assets/1986378/13467502/44dedce2-e07d-11e5-80e0-faf64f559208.png)

Or the mobile notification, received on your phone? Maybe on both?

Thanks

**Comment by lochiiconnectivity** [comment] 2016-03-02 16:48
I'm getting this as well , server version 0.19.0 dev branch (last pull 6 days ago)
, client is rocketchat electron 1.1.0 release , OSX El Capitan

Here is my user document:

{ "_id" : "<removed>",
"createdAt" : ISODate("2016-02-16T16:22:15.563Z"),
"services" : { "password" : { "bcrypt" : "<removed" },
"resume" : { "loginTokens" : [ { "when" : ISODate("2016-02-16T16:37:54.340Z"),
"hashedToken" : "<removed>" } ] },
"ldap" : { "id" : "<removed>",
"idAttribute" : "sAMAccountName" } },
"username" : "<removed>",
"emails" : [ { "address" : "<removed>",
"verified" : false } ],
"status" : "online",
"active" : true,
"roles" : [ "user" ],
"ldap" : true,
"lastLogin" : ISODate("2016-03-02T15:29:38.105Z"),
"statusConnection" : "online",
"utcOffset" : 0,
"avatarOrigin" : "gravatar",
"settings" : { "preferences" : { "disableNewRoomNotification" : true,
"disableNewMessageNotification" : true,
"useEmojis" : true,
"convertAsciiEmoji" : true,
"saveMobileBandwidth" : true,
"compactView" : true,
"unreadRoomsMode" : false,
"autoImageLoad" : true,
"emailNotificationMode" : "all",
"highlights" : [ "" ] } },
"statusDefault" : "online",
"name" : "<removed>" }

**Comment by ulope** [comment] 2016-03-02 16:49
@marceloschmidt: Both

**Comment by graywolf336** [comment] 2016-03-02 17:02
This is due to the word highlight. If you enter a word into the word highlight field, this should stop happening.

**Comment by ulope** [comment] 2016-03-02 17:13
@graywolf336: Indeed that seems to "fix" it. Thanks a bunch.

**Comment by lochiiconnectivity** [comment] 2016-03-02 17:14
agree, fixed for me as well,

**Comment by royalaid** [comment] 2016-03-02 19:09
Also fixed for me! Thanks so much.

**Comment by engelgabriel** [comment] 2016-03-03 22:52
OK, we need to test if the highlight is an empty string and ignore it.

**Comment by Jamie-Owen** [comment] 2016-03-04 11:36
It looks like the problem is in `notifyUsersOnMessage.js ` on line 16.

`if (!highlights || highlights.length == 0) { return false; }` should be `if (!highlights || highlights[0].length == 0) { return false; }`

I think that `highlights` is initialised when a user clicks in the highlight words text area, inserting it in to the user record like this:

```JSON
    "highlights" : [""]
```

Another approach could be to clean up if all highlight words are removed.

**Comment by marceloschmidt** [comment] 2016-03-04 17:24
Thank you very much @Jamie-Owen I'll be fixing this right away

**Comment by marceloschmidt** [comment] 2016-03-04 17:33
Fixed by 79c64fcf1417eb74c886f4890763f18684b70eb7

**Closed by marceloschmidt** 2016-03-04 17:33 UTC
Labels: type: bug
