### ISSUE TITLE
[5.4.0] Sendbutton keeps message in message field after sending

### ISSUE THREAD

**Issue by CvH** [RocketChat/Rocket.Chat#27549] opened 2022-12-15 10:59 UTC
Using the send button to send a message the text returns in the message field after switching to another channel/user and back.
When using just enter to send a message these behavior does not exist.

![rocket-message](https://user-images.githubusercontent.com/1355173/207841766-a778d355-6ba8-4d19-8875-f63fe9f38eaf.gif)

Snap RC 5.4.0
Chrome/Firefox/RC Client

**Comment by dudanogueira** [comment] 2022-12-15 20:43
Hi! Thanks for pointing it out!

I believe this was closed in https://github.com/RocketChat/Rocket.Chat/pull/27495

I was not able to reproduce this on latest development branch. 

If you want to test it, you can set rocket.chat version to `develop` as your rocket chat image tag at docker compose yml.

**Comment by CvH** [comment] 2022-12-15 21:24
I have no playground available, so I need to wait till the next version is released.
Btw isn't that something you want to backport to the bugfix release?

**Comment by whiskyboby** [comment] 2022-12-18 10:09
I have this problem too.

I have a manual install:
Debian 11
NodeJS 14.19.3
MongoDB 5.0.12
Roketchat server 5.4.0

**Comment by banderosss** [comment] 2022-12-18 23:35
I acceed with this problem.

Version of Rocket.Chat Server: 5.4.0
Operating System: Centos 7
Deployment Method: snap
Number of Running Instances: 1
NodeJS Version: v14.19.3
MongoDB Version: 4.4.15 / wiredTiger

**Comment by MaiaDereva** [comment] 2023-01-13 19:44
Hello! :)

same problem here, with Rocket.Chat Server: 5.4.1
I'm a simple user. I use the desktop app on Linux Mint.

**Comment by CvH** [comment] 2023-01-14 08:54
> same problem here, with Rocket.Chat Server: 5.4.1 using "Enter" key

the possible fix is not included at the unreleased 5.4.1 yet, so likewise we need to wait for the next major version to get it fixed

**Comment by Patrick89bvb** [comment] 2023-03-13 14:29
Hi! We have the same Problem, on installed server: 

Debian 10
NodeJS v14.21.3
MongoDB 4.2.24
Roketchat server 5.4.3

and i think the bug was updated: 
https://user-images.githubusercontent.com/33548103/224675506-aa4f1a46-a5da-455c-9ba5-7e1251831c15.mp4

Best regards! 
Patrick

**Comment by hugocostadev** [comment] 2023-06-19 18:35
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides security support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Closed by hugocostadev** 2023-06-19 18:35 UTC
