### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by Micjoyce** [RocketChat/Rocket.Chat#3485] opened 2016-06-08 06:17 UTC
When I upload a image(name is '%U$(%%8(4B6EKIOVB])CSIU.jpg'), I face a  error.

`Exception in callback of async function: URIError: URI malformed
at decodeURI (native)
at [object Object].Router.match (/Users/michaelxu/.meteor/packages/simple_json-routes/.2.1.0.qv9hq8++os+web.browser+web.cordova/npm/node_modules/connect-route/lib/connect-route.js:61:12)
at /Users/michaelxu/.meteor/packages/simple_json-routes/.2.1.0.qv9hq8++os+web.browser+web.cordova/npm/node_modules/connect-route/lib/connect-route.js:102:24
at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
Exception in callback of async function: URIError: URI malformed
at decodeURI (native)
at [object Object].Router.match (/Users/michaelxu/.meteor/packages/simple_json-routes/.2.1.0.qv9hq8++os+web.browser+web.cordova/npm/node_modules/connect-route/lib/connect-route.js:61:12)
at /Users/michaelxu/.meteor/packages/simple_json-routes/.2.1.0.qv9hq8++os+web.browser+web.cordova/npm/node_modules/connect-route/lib/connect-route.js:102:24
at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
`

**Comment by MartinSchoeler** [comment] 2017-07-13 20:03
duplicate of #6141

**Closed by MartinSchoeler** 2017-07-13 20:03 UTC
