### ISSUE TITLE
Markdown Parser Original support issues

### ISSUE THREAD

**Issue by thinkeridea** [RocketChat/Rocket.Chat#8826] opened 2017-11-09 08:27 UTC
### Description:
Recently for a period of time I upgrade from 0.56 to 0.59, found the new version has changed a lot, but there are some unpleasant, there is a problem is very affect our team's experience, hope that developers can help to solve.

markdown:
```
 [ `a8s72d` ](https://www.github.com)
```

This can be handled normally in 0.56 version, and the display effect is as follows:
![image](https://user-images.githubusercontent.com/12491807/32595298-5a00352a-c56a-11e7-9eee-841664c0f338.png)

Effect of 0.59:
![image](https://user-images.githubusercontent.com/12491807/32595275-3c77b2c6-c56a-11e7-8764-674cf74c120d.png)

I know the use of Marked Markdown Parser can solve my problem, but the Parser bring me more questions, I expect the developer can help me solve the problem of what the interpreter's support, thank you very much.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Centos 7.3
* Deployment Method(snap/docker/tar/etc):  docker
* Number of Running Instances:  1
* DB Replicaset Oplog:
* Node Version:

**Comment by MartinSchoeler** [comment] 2017-11-13 16:09
Duplicate of #8640

**Closed by MartinSchoeler** 2017-11-13 16:09 UTC
