### ISSUE TITLE
[Version 3.0.2] No valid server found at the url

### ISSUE THREAD

**Issue by kasingal** [RocketChat/Rocket.Chat#19128] opened 2020-10-04 22:30 UTC
### Description:

On Rocket.Chat APP, it says 'No valid server found' for the urls (below), though both accessible via web browser:
> http://onap-integration.eastus.cloudapp.azure.com:3000/home
> https://onap-integration.eastus.cloudapp.azure.com/home

### Steps to reproduce:

1. Install Rocket.Chat 3.0.2 using (https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/3.0.2/rocketchat-setup-3.0.2.exe)
2. Launch Rocket.Chat and put any Server URL from description above
3. Click on Connect  -> it shows No valid server found error
![image](https://user-images.githubusercontent.com/37604944/95022646-91e34480-0646-11eb-8f50-4844f8349879.png)

### Expected behavior:

I should be able to connect the server same as in version 2.17.11 and earlier.

### Actual behavior:

![image](https://user-images.githubusercontent.com/37604944/95022613-652f2d00-0646-11eb-8890-efb64a499462.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 

### Client Setup Information

- Desktop App or Browser Version: Rocket.Chat 3.0.2
- Operating System: Windows 10

**Comment by ankar84** [comment] 2020-10-05 02:24
Duplicate of https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743

**Comment by kasingal** [comment] 2020-10-05 03:53
> Duplicate of [RocketChat/Rocket.Chat.Electron#1743](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1743)

You can say it as duplicate.. but 1743 is marked closed though issue still persists... So please get it addressed..

What is it in the issue description or step which you can't replicate at your end ??

**Comment by ankar84** [comment] 2020-10-05 03:58
Oh. So you better post it in right repo then.

**Comment by kasingal** [comment] 2020-10-05 06:18
@ankar84 Which one is right repo ??

**Comment by ankar84** [comment] 2020-10-05 06:47
> @ankar84 Which one is right repo ??

https://github.com/RocketChat/Rocket.Chat.Electron/issues for sure

**Comment by kasingal** [comment] 2020-10-05 18:51
Thanks for information, I created same https://github.com/RocketChat/Rocket.Chat.Electron/issues/1787

**Closed** 2020-10-05 19:17 UTC
