### ISSUE TITLE
Symbol * in messages can't be sent. The same in the mobile app.

### ISSUE THREAD

**Issue by Anders-77** [RocketChat/Rocket.Chat#33374] opened 2024-09-26 11:27 UTC
Symbol * in messages can't be sent. The same in the mobile app.

**Comment by reetp** [comment] 2024-09-27 10:33
First you need to fill out a bug template please.

Note that `*` is used in markdown to indicate bold text. You need to you add spaces or single backticks.

`* Hello *`

Some demos:

![Screenshot_20240927_122636_RocketChat Experimental.jpg](https://github.com/user-attachments/assets/0c59eb32-9889-4056-9397-74e4af15222d)


![Screenshot_20240927_122650_RocketChat Experimental.jpg](https://github.com/user-attachments/assets/bd8c3b22-2110-496b-abd4-51941e9a28db)

Pretty sure similar has been raised before eg `~` or `_` 

Search here for 'markdown'

Probably the only way to handle this is to disable markdown entirely.

https://docs.rocket.chat/v1/docs/en/messages

**Comment by Suvendu-UI** [comment] 2024-09-28 04:09
this issue is solved right?

**Comment by Anders-77** [comment] 2024-09-28 12:25
ok, I got it! thank you.

**Comment by Anders-77** [comment] 2024-09-28 12:37
but I think it would be better to use other less often used symbols.. because this is not very obvious for ordinary users..

**Comment by reetp** [comment] 2024-09-28 15:05
It's a library. And a rough standard.

Not much you can do, apart from disable it.

https://en.m.wikipedia.org/wiki/Markdown

**Comment by abirc8010** [comment] 2024-09-28 15:39
> Not much you can do, apart from disable it.

I addressed a Markdown issue by disabling the formatter tools in PR #33288 .

**Comment by reetp** [comment] 2024-09-28 15:59
So effectively a duplicate of #33065 ?

That has already been passed to the team for review.

**Comment by abirc8010** [comment] 2024-09-28 16:36
I think yes , as these issues stem from how markdown works.

**Comment by reetp** [comment] 2024-09-28 16:53
Closing as per my previous.

Please follow up on 33065

**Closed** 2024-09-28 16:53 UTC
Labels: duplicate
