### ISSUE TITLE
.meteor-css-not-found-error on first load

### ISSUE THREAD

**Issue by dwrensha** [RocketChat/Rocket.Chat#5530] opened 2017-01-12 17:04 UTC
I'm running Rocket.Chat 0.49 on Sandstorm. Approximately 1 in every 5 times when I create a new Rocket.Chat grain, the page loads with broken css, like this:

<img width="1414" alt="rocketchat-styling" src="https://cloud.githubusercontent.com/assets/495768/21899265/a432d692-d8bd-11e6-8946-16700cd8d956.png">

The problem seems to have to do with a particular request for `/10f4a42de1fcf4b27834d5d6d2dd3c63d2e464d0.css?meteor_css_resource=true`. In the cases where the page renders wrong, that request returns a `.meteor-css-not-found-error` stylesheet:

<img width="1407" alt="rocketchat load error" src="https://cloud.githubusercontent.com/assets/495768/21899271/aaae4efc-d8bd-11e6-8f08-d99496e0c49f.png">

In cases where the page renders properly, that request returns the following content (which I've truncated to fit into this report):

```
#login-buttons-image-facebook{background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAq0lEQVQ4jWP8//8/AyWAhYGBgcEmauYZBgYGYxL1nj2yLN2ECcohVTNcDwsxKlXlhRm6yzwZRAS5GRgYGBhsombC5ZhwaUIGyJrRAVEuwGYzSS7AB/C64MiydKx8ZJfgNeDN+68MDAwIL8D4RLsgIHsJis0wPjKgOAyoE4hcnGwMGkpiBBUbacvA2TfuvaKiC759/3X23NUnOPMDtgTEwMBwloGBgYGR0uwMAGOPLJS9mkQHAAAAAElFTkSuQmCC)}#login-butt...
```

This problem is similar to https://github.com/RocketChat/Rocket.Chat/issues/4818, but does not seem to have the same root cause.

**Comment by engelgabriel** [comment] 2017-01-12 17:39
Thanks @dwrensh we will investigate that.

**Comment by karlprieb** [comment] 2017-01-13 18:54
Hey @dwrensha I tried version 0.49 on sandstorm and couldn't reproduce this bug, can you post the build log from the broked grain?

Thanks 😄

**Comment by dwrensha** [comment] 2017-01-13 23:15
Here is a grain log from a run where the problem occurred:
```
+ set -euvo pipefail

export METEOR_SETTINGS='{"public": {"sandstorm": true}}'
+ export 'METEOR_SETTINGS={"public": {"sandstorm": true}}'
+ METEOR_SETTINGS='{"public": {"sandstorm": true}}'
export NODE_ENV=production
+ export NODE_ENV=production
+ NODE_ENV=production
exec node /start.js -p 8000
+ exec node /start.js -p 8000
** Starting Mongo...
2017-01-13T23:10:37.117+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 9
child process started successfully, parent exiting
** Starting Meteor...
Will load cache for users
0 records load from users
Will load cache for rocketchat_room
0 records load from rocketchat_room
Will load cache for rocketchat_subscription
0 records load from rocketchat_subscription
Will load cache for rocketchat_settings
0 records load from rocketchat_settings
Updating process.env.MAIL_URL
Will load cache for rocketchat_permissions
0 records load from rocketchat_permissions
ufs: store created at 
Updating process.env.MAIL_URL
Using GridFS for custom emoji storage
ufs: temp directory created at "/tmp/ufs"
[Fri Jan 13 2017 23:11:03 GMT+0000 (UTC)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd.
Loaded hubot-help/src/help.coffee
Loaded hello.coffee
Loaded zen.coffee
sandstorm/sandstorm-http-bridge.c++:2250: warning: App isn't listening for TCP connections after 30 seconds. Continuing to attempt to connect; address->toString() = 127.0.0.1:8000
Using GridFS for Avatar storage
➔ System ➔ startup
➔ +---------------------------------------+
➔ |             SERVER RUNNING            |
➔ +---------------------------------------+
➔ |                                       |
➔ |       Version: 0.49.0                 |
➔ |  Process Port: 8000                   |
➔ |      Site URL: http://127.0.0.1:8000  |
➔ |         OpLog: Disabled               |
➔ |                                       |
➔ +---------------------------------------+
sandstorm/sandstorm-http-bridge.c++:2241: warning: App successfully started listening for TCP connections!
```

As far as I can tell, it is indistinguishable from logs where the problem does not occur.

**Comment by rodrigok** [comment] 2017-01-13 23:40
@dwrensha What happens when you refresh the browser?

**Comment by dwrensha** [comment] 2017-01-14 03:41
Refreshing the page makes the problem go away.

**Comment by dwrensha** [comment] 2017-01-14 03:42
I just now managed to reproduce this on v0.49.1. It took me upwards of 15 tries to get it to happen, so maybe it's more rare than I had originally feared.

**Comment by engelgabriel** [comment] 2017-01-14 19:14
More rare, but still an issue. We are working on the LESS compilation, so maybe this problem will go away once it is refactored. Let's keep this issue open to track it.

**Comment by engelgabriel** [comment] 2017-01-16 21:33
@dwrensha @kentonv how does Sandstorm gets alerted that the build has finished?

**Comment by dwrensha** [comment] 2017-01-18 14:48
@engelgabriel could you clarify what you mean by "build"?

When a grain is started up, [`sandstorm-http-bridge` repeatedly tries to `connect()`](https://github.com/sandstorm-io/sandstorm/blob/v0.199/src/sandstorm/sandstorm-http-bridge.c%2B%2B#L2226-L2256) to the [Meteor process](https://github.com/sandstorm-io/meteor-spk/blob/1f8b77f2c2dd82e42705247ea5eaa485bbb77367/start.js#L94-L100), enqueuing any incoming HTTP requests until Meteor successfully accepts a connection. 

When the Rocket.Chat SPK is built and someone with the proper signing key does `spk publish` or `vagrant-spk publish`, we get an email about there being a new candidate package in the Sandstorm App Market.

**Comment by engelgabriel** [comment] 2017-01-19 19:20
Yes, sorry.. I meant IS UP. Seems that the request for the CSS happens before Meteor had the chance to add it to static assets.

**Comment by MartinSchoeler** [comment] 2017-07-14 19:00
Since we don't have LESS files anymore the problem probably should be fixed. Please Reopen this if the problem happens again. Thanks!

**Closed by MartinSchoeler** 2017-07-14 19:00 UTC
Labels: subj: ui/ux, type: bug
