### ISSUE TITLE
Indicator/Notification of new user pending activation

### ISSUE THREAD

**Issue by rebeld** [RocketChat/Rocket.Chat#2266] opened 2016-02-17 18:06 UTC
If 'Manually Approve New Users' is enabled in Accounts: Registration, it would be nice for admins to receive some indication that there are new users pending activation. At very least an activated/not activated indicator in the Users list.

**Comment by RichardFoxworthy** [comment] 2016-03-19 03:02
Does 'manually approve' work at all? 

I have 'email confirmation' and 'manually approve' options both activated in Admin controls.
I created a new user and could activate and login from the email confirmation link - no approval step required

**Comment by marceloschmidt** [comment] 2016-05-02 18:15
Duplicate of #976. Definitely something needed.

**Closed by marceloschmidt** 2016-05-02 18:15 UTC
