### ISSUE TITLE
voice channels like discord

### ISSUE THREAD

**Issue by Majaspic** [RocketChat/Rocket.Chat#6622] opened 2017-04-06 22:01 UTC
would be an awesome feature :)

**Comment by Nemra1** [comment] 2017-04-19 12:11
make screen of that

**Comment by JohnnyKing94** [comment] 2017-07-18 22:35
There is another issue opened about that... I link it: https://github.com/RocketChat/Rocket.Chat/issues/3661

**Comment by zzzkeil** [comment] 2018-04-15 10:42
+1

**Comment by ed5avage** [comment] 2018-09-13 13:46
This would be really great 😄

**Comment by marceloschmidt** [comment] 2018-11-29 13:20
Duplicate of #3661

**Closed by marceloschmidt** 2018-11-29 13:20 UTC
Labels: Feature: Request, feat: channel settings
