### ISSUE TITLE
[BUG] The channels change itself on clicking Message box.

### ISSUE THREAD

**Issue by Rohan749** [RocketChat/Rocket.Chat#24868] opened 2022-03-18 05:00 UTC
### Description:

The Channel keeps changing every time the message box is clicked for initiating a new message.

### Steps to reproduce:

1. Go to any channel
2. Click on the message box.
3. The channel is changed automatically

### Expected behavior:

It should not change the channel

### Actual behavior:

https://user-images.githubusercontent.com/90546860/158940251-a2fb9125-f22e-41d4-beb6-1ac484bd1c2b.mp4

**Comment by MartinSchoeler** [comment] 2024-07-26 19:23
Hey, I could not reproduce this in the latest version, closing this for now, feel free to create a new issue if it happens again, thanks!

**Closed by MartinSchoeler** 2024-07-26 19:23 UTC
