### ISSUE TITLE
E2E Encryption is not working with accented words

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat#12199] opened 2018-09-28 02:39 UTC
### Steps to reproduce:

Enable E2E Encryption on a room.
Send a message with accented characters.
Characters are displayed incorrectly.

### Actual behavior:

![image](https://user-images.githubusercontent.com/1986378/46184971-68042400-c2ae-11e8-8492-bb207d85d670.png)

**Comment by localguru** [comment] 2018-09-28 10:31
I can confirm the bug. German umlauts are also not displayed correctly.

![bildschirmfoto_2018-09-28_12-29-49](https://user-images.githubusercontent.com/8544984/46203552-6ec88080-c31a-11e8-84ca-736215385398.png)

**Comment by iprok** [comment] 2018-10-03 18:32
The whole cyrillic is broken.

**Comment by edisonchen1985** [comment] 2018-10-15 09:50
Hi, we have got the same bug issue when sending message in Chinese within the encrypted channels.

**Comment by ipadmini22** [comment] 2018-10-23 16:17
I can confirm this issue based on German non-ascii chars. Please fix this issue as it is pretty annoying having these kinds of malformation inside of enterprise-level chats.

**Comment by ipadmini22** [comment] 2018-11-07 07:44
Any new information? E2E is some kind of crucial feature and this char issue is just exhausting for clients to get used to.

**Comment by Althoefer** [comment] 2019-01-22 15:32
I think this was fixed in 0.71.0. At least it works for me now.
![screenshot 2019-01-22 at 16 30 10](https://user-images.githubusercontent.com/23298361/51545884-34ec2e80-1e63-11e9-99a7-33e522566c25.png)
[Here](https://github.com/RocketChat/Rocket.Chat/pull/12398) is the pull request FYI

**Comment by moroq** [comment] 2019-01-22 16:47
Seems to be ok now. Amazing!

**Closed** 2019-08-01 19:19 UTC
Labels: feat: e2e, type: bug
