### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by clementchiew95** [RocketChat/Rocket.Chat#3055] opened 2016-04-27 16:41 UTC
Your Rocket.Chat version: (make sure you are running the latest)
0.28.0

It asks me to login from top right corner even though I am already logged in.

**Comment by mrdomino** [comment] 2016-04-27 20:33
I had a user on my (Sandstorm-based) rocket.chat mention this as well. He could log in with chrome, but not firefox. This didn't show up until after the 0.28.0 upgrade afaict.

**Comment by kiwano** [comment] 2016-04-28 14:50
I am the user mrdomino mentioned, and on iceweasel 38.7.1, I get the message:

"You must login to Sandstorm (on the top right) in order to access this chat." when already logged-in (I can see my username in the top right corner; my account for that particular sandstorm instance uses my gihub credentials).

The errors in my console at this time are (most of them seem to be repetition of the same error message followed by a giving up error):

"couldn't get /.sandstorm-login:" Error: failed [500] Error: wrong Content-Type for .sandstorm-login: application/x-sandstorm-login-token; charset=UTF-8     at packages/kenton_accounts-sandstorm/server.js:138:1     at packages/kenton_accounts-sandstorm/server.js:49:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:123:1     at packages/kenton_accounts-sandstorm/server.js:133:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:...
Stack trace:
r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:282
o.call/g.onreadystatechange@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:2628
 ac56c377f8920e788030c5dff57aff4c49de5500.js:416:1146

"couldn't get /.sandstorm-login:" Error: failed [500] Error: wrong Content-Type for .sandstorm-login: application/x-sandstorm-login-token; charset=UTF-8     at packages/kenton_accounts-sandstorm/server.js:138:1     at packages/kenton_accounts-sandstorm/server.js:49:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:123:1     at packages/kenton_accounts-sandstorm/server.js:133:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:...
Stack trace:
r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:282
o.call/g.onreadystatechange@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:2628
 ac56c377f8920e788030c5dff57aff4c49de5500.js:416:1146

"couldn't get /.sandstorm-login:" Error: failed [500] Error: wrong Content-Type for .sandstorm-login: application/x-sandstorm-login-token; charset=UTF-8     at packages/kenton_accounts-sandstorm/server.js:138:1     at packages/kenton_accounts-sandstorm/server.js:49:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:123:1     at packages/kenton_accounts-sandstorm/server.js:133:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:...
Stack trace:
r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:282
o.call/g.onreadystatechange@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:2628
 ac56c377f8920e788030c5dff57aff4c49de5500.js:416:1146

"couldn't get /.sandstorm-login:" Error: failed [500] Error: wrong Content-Type for .sandstorm-login: application/x-sandstorm-login-token; charset=UTF-8     at packages/kenton_accounts-sandstorm/server.js:138:1     at packages/kenton_accounts-sandstorm/server.js:49:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:123:1     at packages/kenton_accounts-sandstorm/server.js:133:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:...
Stack trace:
r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:282
o.call/g.onreadystatechange@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:2628
 ac56c377f8920e788030c5dff57aff4c49de5500.js:416:1146

"couldn't get /.sandstorm-login:" Error: failed [500] Error: wrong Content-Type for .sandstorm-login: application/x-sandstorm-login-token; charset=UTF-8     at packages/kenton_accounts-sandstorm/server.js:138:1     at packages/kenton_accounts-sandstorm/server.js:49:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:123:1     at packages/kenton_accounts-sandstorm/server.js:133:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:...
Stack trace:
r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:282
o.call/g.onreadystatechange@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:2628
 ac56c377f8920e788030c5dff57aff4c49de5500.js:416:1146

"couldn't get /.sandstorm-login:" Error: failed [500] Error: wrong Content-Type for .sandstorm-login: application/x-sandstorm-login-token; charset=UTF-8     at packages/kenton_accounts-sandstorm/server.js:138:1     at packages/kenton_accounts-sandstorm/server.js:49:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:123:1     at packages/kenton_accounts-sandstorm/server.js:133:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:...
Stack trace:
r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:282
o.call/g.onreadystatechange@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:2628
 ac56c377f8920e788030c5dff57aff4c49de5500.js:416:1146

"couldn't get /.sandstorm-login:" Error: failed [500] Error: wrong Content-Type for .sandstorm-login: application/x-sandstorm-login-token; charset=UTF-8     at packages/kenton_accounts-sandstorm/server.js:138:1     at packages/kenton_accounts-sandstorm/server.js:49:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:123:1     at packages/kenton_accounts-sandstorm/server.js:133:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:...
Stack trace:
r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:282
o.call/g.onreadystatechange@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:2628
 ac56c377f8920e788030c5dff57aff4c49de5500.js:416:1146

"couldn't get /.sandstorm-login:" Error: failed [500] Error: wrong Content-Type for .sandstorm-login: application/x-sandstorm-login-token; charset=UTF-8     at packages/kenton_accounts-sandstorm/server.js:138:1     at packages/kenton_accounts-sandstorm/server.js:49:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:123:1     at packages/kenton_accounts-sandstorm/server.js:133:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:...
Stack trace:
r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:282
o.call/g.onreadystatechange@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:2628
 ac56c377f8920e788030c5dff57aff4c49de5500.js:416:1146

"couldn't get /.sandstorm-login:" Error: failed [500] Error: wrong Content-Type for .sandstorm-login: application/x-sandstorm-login-token; charset=UTF-8     at packages/kenton_accounts-sandstorm/server.js:138:1     at packages/kenton_accounts-sandstorm/server.js:49:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:123:1     at packages/kenton_accounts-sandstorm/server.js:133:1     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)     at packages/meteor/dynamics_nodejs.js:...
Stack trace:
r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:282
o.call/g.onreadystatechange@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:126:2628
 ac56c377f8920e788030c5dff57aff4c49de5500.js:416:1146

"loginWithSandstorm failed:" Error: Gave up waiting for login rendezvous XHR. [timeout]
Stack trace:
e.makeErrorType/r@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:3:3334
._livedata_result@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:52:19802
u/o@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:52:6561
._launchConnection/t.socket.onmessage/<@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:52:567
A.forEach@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:1:863
._launchConnection/t.socket.onmessage@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:52:523
v</r.prototype.dispatchEvent@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:51:1119
v</C.prototype._dispatchMessage@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:51:14711
v</C.prototype._didMessage@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:51:15601
v</C.websocket/o.ws.onmessage@https://45d3c833ccfb1e73447de31111762e19.mrdomino.sandcats.io/ac56c377f8920e788030c5dff57aff4c49de5500.js?meteor_js_resource=true:51:17702
 ac56c377f8920e788030c5dff57aff4c49de5500.js

**Comment by paulproteus** [comment] 2016-04-28 23:22
Hey @jparyani does this mean something to you? :)

**Comment by paulproteus** [comment] 2016-04-28 23:22
Hey @jparyani does this mean something to you? :)

**Comment by paulproteus** [comment] 2016-04-28 23:34
Hey @jparyani does this mean something to you? :)

**Comment by paulproteus** [comment] 2016-04-28 23:47
(UPDATE: An extremely laggy connection resulted in me submitting the same thing 3 times. Sorry about that.)

**Comment by zeigerpuppy** [comment] 2016-06-09 23:52
I am having the same problem with Rocket.chat in Sandstorm.
After a period of inactivity, Rocket asks me to log in from the right corner.  Closing the grain and reopening it fixes the issue.

log in Sandstorm shows:
```
Error: Requested session that no longer exists, and timed out waiting for client to restore it. This can happen if you have opened an app's content in a new window and then closed it in the UI. If you see this error *inside* the Sandstorm UI, please report a bug and describe the circumstances of the error. [504]
    at server/proxy.js:580:24
    at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
    at packages/meteor.js:445:45
    at runWithEnvironment (packages/meteor.js:1154:24)
```

**Comment by paulproteus** [comment] 2016-06-09 23:59
Hi @zeigerpuppy ,

I think this might be a Sandstorm bug, rather than a Rocket.Chat bug. I'll file a bug in Sandstorm.

**Comment by kentonv** [comment] 2016-07-01 19:07
The Iceweasel issue reported by @kiwano should be fixed by accounts-sandstorm v0.4.1 (although I haven't been able to reproduce the issue myself; I'm only going off the error message).

Someone will need to update the package version in the Rocket.Chat manifest before the next release.

**Comment by kiwano** [comment] 2016-07-03 13:26
Noticing the existence of a new version of sandstorm this morning, is it safe to assume that my continued inability to log in to rocketchat on iceweasel is due to the lack of the enabling update in Rocket Chat, or should I go digging around for some more trouble (and my "trouble", I mean "stack traces")

**Comment by kentonv** [comment] 2016-07-08 04:34
@kiwano In this case, it's Rocket.Chat that needs an update. Also they will first need to merge #3716.

**Closed** 2016-07-08 16:54 UTC
Labels: feat: oauth / sso, type: bug

**Comment by kiwano** [comment] 2016-07-08 19:44
yaythankyou all! (assuming it works when the instance that i connect to upgrades and reloads)
