### ISSUE TITLE
Rocket.Chat Docker installation unable to render interface after 6.10.0 upgrade from 6.9.3

### ISSUE THREAD

**Issue by bonarae** [RocketChat/Rocket.Chat#32854] opened 2024-07-22 09:42 UTC
### Description:

When I start any RocketChat session with 6.10.0 installed, I cannot enter into the server at all.

### Steps to reproduce:

1. Upgrade RocketChat server using .env file (Docker) by declaring the release to be used to 6.10.0
2. docker compose down
3. docker compose up -d
4. wait 30 seconds to 1 minute to completely boot up services
5. navigate to the server either using browser or official app with any URL; the bug occurs there.

### Expected behavior:

Usual interface as configured for RocketChat appears

### Actual behavior:

Looping behavior upon navigating to the server address (root URL, or any other URL housed under the RocketChat app for that matter).

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.0
- License Type: Community
- Number of Users: 17 (3 activated, 1 bot)
- Operating System:  Debian 12
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.24 (latest 5.0 version on Bitnami's Docker Hub)

### Client Setup Information

- Desktop App or Browser Version: Windows 4.0.1, Firefox 128
- Operating System: Windows 11 23H2

### Additional context

Screenshot whenever I try to connect to the instance at 6.10.0:
![rocketchat infinite loop](https://github.com/user-attachments/assets/587d7db6-ba7a-4ab9-a2a2-abe35dfb972c)

Upon inspection of the said page in the Browser's DevTools:

There are two errors:
```Uncaught TypeError: navigator.serviceWorker is undefined```  
Stack trace:
```
[useDownloadFromServiceWorker.ts:10](meteor://%F0%9F%92%BBapp/client/hooks/useDownloadFromServiceWorker.ts)
    ts useDownloadFromServiceWorker.ts:10
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    tsx AttachmentEncryptedDownload.tsx:2
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    tsx AttachmentDownload.tsx:2
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    tsx MessageCollapsible.tsx:1
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    tsx AudioAttachment.tsx:2
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    tsx FileAttachment.tsx:1
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    tsx AttachmentsItem.tsx:2
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    tsx Attachments.tsx:3
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    tsx QuoteAttachment.tsx:2
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    tsx ForwardMessageModal.tsx:2
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    ts messageActionDefault.ts:2
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    ts index.ts:1
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    ts accounts.ts:1
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:5
    ts main.ts:1
    g 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    require 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    t 949676bf261dba48b3da60a41c67af2933e3a64b.js:3
    <anonymous> transforms.ts:24
```

Offending method:
```
navigator.serviceWorker.addEventListener('message', (event) => {
	if (event.data.type === 'attachment-download-result') {
		const { result } = event.data as { result: ArrayBuffer; id: string };

		ee.emit(event.data.id, { result, id: event.data.id });
	}
});
```

```There is no route for the path: /```  
Stack trace:
```
[949676bf261dba48b3da60a41c67af2933e3a64b.js:289:5694](http://x.x.x.x/949676bf261dba48b3da60a41c67af2933e3a64b.js?meteor_js_resource=true)
    _notfoundRoute 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    _updateCallbacks 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    middleware 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    o 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    dispatch 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    replace 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    t 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    start 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    h 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    initialize 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    js 949676bf261dba48b3da60a41c67af2933e3a64b.js:289
    i startup_client.js:26
    s startup_client.js:38
```

### Relevant logs:
```
+-------------------------------------------+
|               SERVER RUNNING              |
+-------------------------------------------+
|                                           |
|  Rocket.Chat Version: 6.10.0              |
|       NodeJS Version: 14.21.3 - x64       |
|      MongoDB Version: 5.0.24              |
|       MongoDB Engine: wiredTiger          |
|             Platform: linux               |
|         Process Port: 3000                |
|             Site URL: http://x.x.x.x  |
|     ReplicaSet OpLog: Enabled             |
|          Commit Hash: 623a265851          |
|        Commit Branch: HEAD                |
|                                           |
+-------------------------------------------+
{"level":50,"time":"2024-07-22T09:26:24.039Z","pid":1,"hostname":"d2136e7d5f17","name":"System","msg":"Failed to communicate with Rocket.Chat Cloud","url":"https://releases.rocket.chat/v2/server/supportedVersions","err":{"type":"AbortError","message":"The user aborted a request.","stack":"AbortError: The user aborted a request.\n    at abort (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/node_modules/node-fetch/lib/index.js:1401:16)\n    at AbortSignal.abortAndFinalize (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/node_modules/node-fetch/lib/index.js:1416:4)\n    at AbortSignal.dispatchEvent (/app/bundle/programs/server/npm/node_modules/event-target-shim/dist/event-target-shim.js:818:35)\n    at abortSignal (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:52:12)\n    at AbortController.abort (/app/bundle/programs/server/npm/node_modules/abort-controller/dist/abort-controller.js:91:9)\n    at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/@rocket.chat/server-fetch/dist/index.js:37:51)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/cloud/server/functions/supportedVersionsToken/supportedVersionsToken.ts:46:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","name":"AbortError"}}
{"level":40,"time":"2024-07-22T09:26:27.707Z","pid":1,"hostname":"d2136e7d5f17","name":"SyncedCron","msg":"Failed to send usage report"}
```

It's not related to #32759. I have run into this error every time I upgrade to 6.10.0 and it's stuck there unless I downgrade to 6.9.3.

We are planning to implement our internal chat system within July so I need to file this bug report. This is really a showstopper in our implementation.

**Comment by reetp** [comment] 2024-07-22 10:00
Thanks for the reprot.

> SERVER RUNNING 

So the server is up and running correctly so this is likely a duplicate of:

https://github.com/RocketChat/Rocket.Chat/issues/32826

You should be using https.

**Comment by bonarae** [comment] 2024-07-22 10:41
However, before we plan to deploy using https, we are using it in an air-gapped environment first for testing purposes.

**Comment by reetp** [comment] 2024-07-22 12:58
> There is no route for the path

So it is a duplicate of this:

https://github.com/RocketChat/Rocket.Chat/issues/32826

Please follow up there.

**Closed by reetp** 2024-07-22 12:58 UTC
Labels: duplicate
