### ISSUE TITLE
When change account will block loading page?

### ISSUE THREAD

**Issue by Micjoyce** [RocketChat/Rocket.Chat#3826] opened 2016-07-21 09:44 UTC
Your Rocket.Chat version: (make sure you are running the latest)

When I change a account login into demo.rocket.chat, it has been stuck in loading page(when I refresh the browser it will be ok!)
I find it my caused by Collection cache, and minimongo can find before account's records.

**Comment by MartinSchoeler** [comment] 2016-08-11 13:34
Thanks for the report! This is a duplicate of #3761

**Closed by MartinSchoeler** 2016-08-11 13:34 UTC
Labels: type: bug
