### ISSUE TITLE
Rocketchat S3 storage with radosgw provide by CEPH

### ISSUE THREAD

**Issue by almorel** [RocketChat/Rocket.Chat#6414] opened 2017-03-22 06:54 UTC
Hello,

Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disable
Node Version: v4.7.3

I try to configure an S3 storage provide by radosgw (CEPH). I just follow the instructions for minio or amazon and complete the amazon S3.

I apply also the CORs configuration to the bucket. When I try to upload a file from rocketchat, I get a "404 bad request" error from rocketchat and also from our radosgw. 

I think that's the problem is about the URL of the bucket, I try several way to write it:

https://s3.my.corporate.com/MYBUCKET/
https://MYBUCKET.s3.my.corporate.com/
https://s3.my.corporate.com

but unfortunately it doesn't work. 
I make a test with minio as describe in your doc, it doesn't work also. Finaly I make a little test with the amazon S3 and it works like a charm. 

I can't understand my mistakes or maybe there is a problem with the S3 storage part of rocketchat ?

Many thanks in advance, 

Best regards,

**Comment by MartinSchoeler** [comment] 2017-08-08 18:14
We aim to keep our Github issues for bugs and feature requests.  This does not fit that criteria.
Please see our [guidelines for support](https://rocket.chat/docs/getting-support).  If you feel like we are closing in error, please re-open and add additional details about the bug or feature request.

**Closed by MartinSchoeler** 2017-08-08 18:14 UTC
Labels: feat: file sharing, type: support

**Comment by mlg1** [comment] 2024-01-02 12:47
We are also trying to setup S3 storage from radosgw but without success. Our S3 storage works great with different tools as well as c3cmd. I think the problem is with Rocket Chat. After trying all kinds of things, I think there is something wrong. Even with the "Proxy Uploads" option turned on, files to the bucket are not uploaded. There aren't even any errors in the logs. It's like it just doesn't do anything.
