### ISSUE TITLE
Unread messages badge on iOS client doesn't reset

### ISSUE THREAD

**Issue by zanshin** [RocketChat/Rocket.Chat#3618] opened 2016-06-23 15:33 UTC
The unread messages badge on the app icon on iOS doesn't reset properly after all new messages have been viewed. It stays at "1" until the app is quit and reopened.

Not sure how to view the app version in the iOS client, but any time I've been asked to update I have so I believe I've got the latest (current) version installed. I'm on iOS 9.3.2.

RC is allowed to do background app refresh on my devices, for whatever that's worth.

**Comment by TheReal1604** [comment] 2016-06-23 15:35
On my iPhone the "1" is only reset if i had no more notifications in any channel unread. Then the app has no unread badge more. Can you test this?

**Comment by zanshin** [comment] 2016-06-23 17:57
I, and several of my co-workers have tested this. Even after having no unread messages I still have a badge count of "1".

**Comment by TheReal1604** [comment] 2016-06-24 04:29
Ok, after trying that again, the issue is happening at my iPhone, too.

**Comment by russcalderon** [comment] 2016-08-03 02:55
Hello, is there an update on this issue? I certainly have the same issue so all my colleages on iphone/ipads. It just shows a count of 1 and only exiting the application and relaunching will clear it.

**Comment by stefanzilske** [comment] 2016-08-08 14:11
Same here. Unread message badge will only disappear when the App is closed and relaunched.

**Comment by russcalderon** [comment] 2016-09-01 05:44
It is working fine now since Aug 22 iOS update

**Comment by RichardFoxworthy** [comment] 2017-02-15 05:50
I have a user now reporting this problem using iOS 10.2.1 on iPhone 6s. Anyone else?

Not sure if they have background app refresh enabled - should they?

**Comment by sampaiodiego** [comment] 2017-05-11 15:18
this issue should actually be related to [Rocket.Chat.Cordova](https://github.com/RocketChat/Rocket.Chat.Cordova) repo.

can you guys confirm if it's also hapenning on the iOS native app? It's called *Rocket.Chat+* on App Store.

@rafaelks are you aware os this?

**Comment by rafaelks** [comment] 2017-05-11 21:42
@sampaiodiego Yes, on the iOS native app this is also happening, but was already fixed, not released yet: https://github.com/RocketChat/Rocket.Chat.iOS/pull/460.

**Comment by Hudell** [comment] 2018-06-06 15:54
I'll be closing this since it was related to the Cordova app in the first place.

**Closed by Hudell** 2018-06-06 15:54 UTC
Labels: subj: mobile, type: bug
