### ISSUE TITLE
Embedded layout showing left side bar

### ISSUE THREAD

**Issue by oefimov** [RocketChat/Rocket.Chat#13688] opened 2019-03-13 10:51 UTC
### Description:
According to [Embedded Layout docs](https://rocket.chat/docs/developer-guides/embedded-layout/) left side bar must be hidden, but it's shown. 

### Steps to reproduce:
1. Open URL `base/channel/general?layout=embedded`

### Expected behavior:
Left side bar is hidden

### Actual behavior:
Left side bar is shown

### Server Setup Information:
- Version of Rocket.Chat Server: 0.74.3
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: v8.11.4

### Additional context
Looks like regress related to #12025

**Comment by uriesk** [comment] 2019-03-18 10:37
Can reproduce.
Same bug here.

**Comment by uriesk** [comment] 2019-03-19 16:31
Tested it with the 1.0.0-beta2 and the embedded layout is working there

**Comment by oefimov** [comment] 2019-03-25 07:11
Hope it'll be fixed by #13574, waiting for GA release.

**Comment by romannep** [comment] 2019-04-23 07:06
0.74.3 - same issue.

CSS class "embedded-view" aplied to DOM, but with no visual effect.
Can be solved localy by adding user CSS style
````
	.embedded-view .sidebar {
		display: none;
	}
````

**Comment by reetp** [comment] 2019-04-23 10:03
> 0.74.3 - same issue.
> 

As per previous comments this is probably fixed in v1.0.0.x (and the fix for 0.74.3 will be upgrading to v1.0.0)

Can you please test on latest which is currently 1.0.0-rc.3 (ONLY on a test setup, not your production machine)

Try and make sure you use the same engine versions for testing as per https://github.com/RocketChat/Rocket.Chat/releases

eg

Engine versions
Node: 8.11.4
NPM: 6.4.1
MongoDB: 3.2, 3.4, 3.6, 4.0

**Comment by sdelfi** [comment] 2019-12-03 15:50
Sometimes I have the same error in the embedded mode

Rocketchat version: 2.3.0
OS: Centos 7
Docker: no
Node Version: v8.15.1
Mongo Version: 4.0.10

**Comment by DigitalFrontiersMedia** [comment] 2020-09-24 19:57
This seems to occur intermittently for me with v. Rocketchat 3.6.2.  Seems like the first login will always load the left sidebar whereas subsequent logins don't.

**Comment by djcruz93** [comment] 2021-01-11 10:26
Even I noticed the same behavior when I tried creating a mock for my project on [JSFiddle](https://jsfiddle.net/murtaza98/y6qks45p/45/). 
Initially, when we run the code, it works fine.

**Steps to reproduce:**
Clicking on either the chat window or message input bar or attach button(+), results in breaking of embedded layout as the sidebar and room-header appear. 

Using https://open.rocket.chat/channel/general?layout=embedded as the iframe src.


https://user-images.githubusercontent.com/51796498/104169261-4b5f6c00-5425-11eb-88b2-8d6d626d6f08.mp4

**Comment by Schrammi** [comment] 2021-03-13 13:24
I've got the same issue.

**Comment by DigitalFrontiersMedia** [comment] 2021-03-17 15:55
I’ll note that this problem seemed to go away for us eventually.  I don’t think I changed any settings that did it; I think it resolved itself after we got everything completely on the right domains and https protocols and stuff.

--
Check out our mention in MIT's Technology Review!  ARticle on #augmentedreality (3rd paragraph-"Commerce and Entertainment")-- http://goo.gl/XhFvt <http://goo.gl/XhFvt>
-- 

Stephen Barker, M.A.
President
Digital Frontiers Media, Inc.

This is my kung fu, and it...is...strong.

Web:     http://digitalfrontiersmedia.com <http://digitalfrontiersmedia.com/>
Email:   ***@***.*** ***@***.***>
Cell:    941.773.2036
E-fax:   650.745.0634
Skype:   DigitalFrontiersMedia 
Twitter: DigitalFrontier

**Comment by davidecavezza** [comment] 2021-03-29 14:45
Happened to me too, just like the videos posted by @djcruz93.
The reason seems to be the user option My account > Preferences > Messages > Hide right sidebar with click.
When it is active, you see that problem.
By turning it off, it was solved for me.

Seems like a bug.

**Comment by Schrammi** [comment] 2021-03-29 22:09
@davidecavezza Thanks for the information. I will test it tomorrow. 
I also created a new issue, because this one was originally another bug.
The new issue is #21321

**Comment by gabriellsh** [comment] 2023-09-19 15:34
This has been fixed here https://github.com/RocketChat/Rocket.Chat/pull/30137

**Closed by gabriellsh** 2023-09-19 15:34 UTC
