### ISSUE TITLE
Bug: Action Menu appears on top left

### ISSUE THREAD

**Issue by christianreiss** [RocketChat/Rocket.Chat#11014] opened 2018-06-05 21:28 UTC
Description:

Seen mostly in firefox across many computers (Linux, Windows): Clicking on any action item (Channel Action, Message action) the action box appears in the upper left corner instead of where one is clicking. This does not happen always but roughly 50% of times.

Server Setup Information:

-     Version of Rocket.Chat Server: 0.65.1
-     Operating System: Centos 7.5
-     Deployment Method(snap/docker/tar/etc): Tar
-     Number of Running Instances: 1
-     DB Replicaset Oplog: False
-     Node Version: v8.9.4
-     mongoDB Version: v3.4.15

Steps to Reproduce:

-     Install Version 0.65
-     Use Firefox (checked, others might fail)
-     Click Action Item (might need several clicks)
-     Notice how the action items appears in the top left.

Expected behavior:

Action Items appear where I clicked, not somewhere else.
As seen here: https://cloud.alpha-labs.net/index.php/s/Yowgt6ybFXEGn7z/preview

**Comment by vynmera** [comment] 2018-06-05 21:39
Duplicate of #10668
I'm looking into this, it seems resizing the browser window snaps it back into place (when created, it's put at x0 y0)

**Comment by vynmera** [comment] 2018-06-05 21:40
@rocket.cat close

**Comment by TwizzyDizzy** [comment] 2018-06-06 08:04
@rocket-cat label add duplicate

**Comment by TwizzyDizzy** [comment] 2018-06-06 08:04
@rocket-cat close

**Closed by TwizzyDizzy** 2018-06-06 08:04 UTC
Labels: duplicate
