### ISSUE TITLE
first user was not made admin

### ISSUE THREAD

**Issue by alandeboer** [RocketChat/Rocket.Chat#1648] opened 2015-12-12 17:42 UTC
Hey All,

I followed one of the install tutorials for rocket.chat on ubuntu with docker and everything went super quick and great. The first user was not made admin though. I'm having some trouble figuring out how to edit the user. Any help would be great.

Alan

**Comment by graywolf336** [comment] 2015-12-12 17:43
Duplicate of #1632 and #1646, proposed fix by #1647. :smile:

**Closed by graywolf336** 2015-12-12 17:43 UTC
