### ISSUE TITLE
Archiving user chats

### ISSUE THREAD

**Issue by akashkaveti** [RocketChat/Rocket.Chat#4895] opened 2016-11-08 12:04 UTC
Is it possible to archive users chats (individual)?

**Comment by MartinSchoeler** [comment] 2016-11-08 12:36
@akashkaveti do you mean Direct Messages? You can try hide them.

**Comment by akashkaveti** [comment] 2016-11-08 13:26
@MartinSchoeler Yeah Direct messages, I want to archive/export the direct messages.

**Comment by graywolf336** [comment] 2016-11-16 23:52
Duplicate of #3348

**Closed by graywolf336** 2016-11-16 23:52 UTC
Labels: type: support
