### ISSUE TITLE
Firefox ESR does not display some UI items

### ISSUE THREAD

**Issue by etyack** [RocketChat/Rocket.Chat#8583] opened 2017-10-20 18:11 UTC
### Description:

When using Firefox ESR 52.4, certain UI objects do not display.  Example images are attached.  In the example image where you should see the icon for emojis and three vertical ".", if you click in the vicinity of where they should be displayed, they are there.  Those objects seem to match the color of the background.

The same issues occur in MS Edge browser.

### Server Setup Information:

* Version of Rocket.Chat Server: 59.1
* Operating System: OSX 10.26.6, verified in Ubuntu 16.04 also
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 
* DB Replicaset Oplog:
* Node Version:

### Steps to Reproduce:

1. Login
2. View left panel - images are missing
3. Look for three vertical . or emoji icon when mousing over a chat.
<img width="1061" alt="screen shot 2017-10-20 at 1 59 07 pm" src="https://user-images.githubusercontent.com/130788/31835643-60b2cc18-b5a0-11e7-941b-01afb60cd57d.png">

![screen shot 2017-10-20 at 1 56 25 pm](https://user-images.githubusercontent.com/130788/31835698-a1eac9a6-b5a0-11e7-8b3b-badaeeb65b1f.png)
Thank you,

Erick

**Comment by cyclops24** [comment] 2017-10-21 04:50
I can confirm this issue also on Firefox 56.0. See below image:
![01](https://user-images.githubusercontent.com/8266479/31848177-ab6ba6f6-b638-11e7-8f39-50a773a61e62.png)

**/CC:** @karlprieb

**Comment by cyclops24** [comment] 2017-10-21 04:55
Part of #8175

**Comment by cyclops24** [comment] 2017-10-21 05:01
Also a little of avatars always shows successfully: (See below image)
![02](https://user-images.githubusercontent.com/8266479/31848234-3eba87aa-b63a-11e7-8592-cc9d0de694c8.png)

**Comment by localguru** [comment] 2017-10-21 09:23
Same here

# 52.4.1 (32-Bit) on Win7

![esr](https://user-images.githubusercontent.com/8544984/31850445-02d1bb10-b652-11e7-912c-16506ba1f0da.jpg)

# 56.0 (64-Bit) on Linux

![56](https://user-images.githubusercontent.com/8544984/31850447-0da5072c-b652-11e7-9b5a-a09c4c2c40e7.jpg)

**Comment by MartinSchoeler** [comment] 2017-10-27 15:44
Duplicate of #7980

**Closed by MartinSchoeler** 2017-10-27 15:44 UTC
