### ISSUE TITLE
[BUG] Button information (read receipt) not work

### ISSUE THREAD

**Issue by guilhermecfviana** [RocketChat/Rocket.Chat#22289] opened 2021-06-08 19:38 UTC
### Description:

Button 'information' in direct messages or channel message not work

### Steps to reproduce:

1. Open direct or channel message
2. Click Information

![image](https://user-images.githubusercontent.com/17053653/121246519-a2a02600-c877-11eb-930d-6b5602de0588.png)

![image](https://user-images.githubusercontent.com/17053653/121246581-b481c900-c877-11eb-8477-00bdedfa3f00.png)

### Expected behavior:

Show infos about read receipt

### Actual behavior:

Not work

### Server Setup Information:

![image](https://user-images.githubusercontent.com/17053653/121246335-72f11e00-c877-11eb-9e68-9d6b817887b4.png)

### Client Setup Information

- Desktop App or Browser Version: Both
- Operating System: Linux

**Comment by ankar84** [comment] 2021-06-09 06:56
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/21861 and fixed by https://github.com/RocketChat/Rocket.Chat/pull/22203

**Closed** 2023-05-19 14:10 UTC
