### ISSUE TITLE
Deleted files isn't de facto deleted at all

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#2031] opened 2016-01-25 22:21 UTC
Hi,

One of my users reported the following and I double-checked it by reproducing the behaviour: the files in messages with embedded files are still visible in the "Files List" after you delete the messages.

I thought it was only a question of stale cache, not so. After clearing cache, refreshing the site and browsing the "Files List" the seemingly deleted file is still lingering there, and fully accessible.

I am running latest version found here on GitHub (branch is `develop`). Any other details needed?

**Comment by graywolf336** [comment] 2016-01-25 22:32
Thanks for reporting, however it is a duplicate of #1367.

**Closed by graywolf336** 2016-01-25 22:32 UTC
