### ISSUE TITLE
Desactive non existing LDAP users when synchronize LDAP

### ISSUE THREAD

**Issue by dsisysteme** [RocketChat/Rocket.Chat#19466] opened 2020-11-05 13:22 UTC
### Description:

This will be a important feature for us to automatically desactivate users removed in LDAP with the sync.
We have a lot of users account created and deleted over the year. So it's painfull to do it manually.

Thanx

### Steps to reproduce:

1. Sync LDAP
2. Delete entry in LDAP
3. No effect on Rocket

### Expected behavior:

Desactivate account removed in LDAP

### Actual behavior:

Account already present in Rocket

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.2
- Operating System: Linux
- Deployment Method: from source
- Number of Running Instances:  2
- DB Replicaset Oplog: 1
- NodeJS Version: v12.14.0
- MongoDB Version: 4.2.9

### Client Setup Information

- Desktop App or Browser Version: Chrome
- Operating System: Linux

**Comment by frdmn** [comment] 2020-11-09 09:30
Seems to be a duplicate of: 
- https://github.com/RocketChat/Rocket.Chat/issues/6174 (for removing)
- https://github.com/RocketChat/Rocket.Chat/issues/7235 (for disabling)

**Closed by frdmn** 2020-11-09 09:30 UTC
