### ISSUE TITLE
Can only enable encryption for DM's if have edit-room permission

### ISSUE THREAD

**Issue by grantholle** [RocketChat/Rocket.Chat#13173] opened 2019-01-17 02:23 UTC
Love E2EE capabilities.

The downside is that if I want to allow my users to enable this feature in DM's, I have to give them the `edit-room` permission. This also means they can edit private and public rooms as well 😬.

Would love perhaps a separate permission for DM room settings, or even just a permission to enable encryption in DM's.

**Comment by Perflyst** [comment] 2019-05-25 19:10
Duplicate of #12416? (@tassoevan)

**Closed** 2019-10-21 20:30 UTC
Labels: feat: e2e, type: improvement
