### ISSUE TITLE
Auto Delete doesn´t work at quoted messages

### ISSUE THREAD

**Issue by charlyrock** [RocketChat/Rocket.Chat#22904] opened 2021-08-11 13:12 UTC
### Description:

We activated the auto-delete option for all chats after 30 days. That works fine but now it doesn´t work anymore at messages, that was quoted. 
### Steps to reproduce:

1. Activate auto delete
2. Write in this channel a message
3. let it quote
4. wait for the auto delete and see that it wasn´t delete

### Expected behavior:

All messages should be delete that are older than 30 days
### Actual behavior:
Quoted messages are not deleted automated

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: Ubuntu 18
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.24 

### Client Setup Information

- Desktop App or Browser Version: Desktop App/Webbrowser
- Operating System: Windows 10

**Comment by johncrisp** [comment] 2021-08-11 18:58
Duplicate of:

https://github.com/RocketChat/Rocket.Chat/issues/22904

Also:

https://github.com/RocketChat/feature-requests/issues/464

**Closed by johncrisp** 2021-08-11 18:58 UTC
