### ISSUE TITLE
Audio and Video calls gone

### ISSUE THREAD

**Issue by ecoitsolutions** [RocketChat/Rocket.Chat#9657] opened 2018-02-09 15:04 UTC
### Description:

Upgrading to latest version i have seen that the option for Audio or Video call has dissappeared. In settings WebRTC is enabled for both DM and Groups.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61.0
* Operating System: Linux Ubuntu 14.04
* Deployment Method(snap/docker/tar/etc): TAR
* Number of Running Instances:  1
* DB Replicaset Oplog: 0
* Node Version: 8.9.3

### Steps to Reproduce:

1. Upgrade server to latest version
2. Chat with a person
3. Attempt to Call or VideoCall but no option is to be found for calling

### Expected behavior:

Clik on person profile, see the Call and VideoCall buttons

### Actual behavior:

Actions dissappeared

### Relevant logs:
Will load cache for users
29 records load from users
Will load cache for rocketchat_room
328 records load from rocketchat_room
Will load cache for rocketchat_subscription
626 records load from rocketchat_subscription
Will load cache for rocketchat_settings
617 records load from rocketchat_settings
Updating process.env.MAIL_URL
Starting Email Intercepter...
Will load cache for rocketchat_permissions
75 records load from rocketchat_permissions
Will load cache for rocketchat_roles
11 records load from rocketchat_roles
Setting default file store to GridFS
{"line":"147","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 106","time":{"$date":1518188033482},"level":"info"}
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
➔ rocketchat_logger.js:278 System ➔ startup
➔ +----------------------------------------------+
➔ |                SERVER RUNNING                |
➔ +----------------------------------------------+
➔ |                                              |
➔ |  Rocket.Chat Version: 0.61.0                 |
➔ |       NodeJS Version: 8.9.3 - x64            |
➔ |             Platform: linux                  |
➔ |         Process Port: 3000                   |
➔ |             Site URL: https://im.soteha.it/  |
➔ |     ReplicaSet OpLog: Disabled               |
➔ |          Commit Hash: 0b71e0e2fe             |
➔ |        Commit Branch: HEAD                   |
➔ |                                              |
➔ +----------------------------------------------+

**Comment by dreamzmb** [comment] 2018-02-21 10:03
Hey,
I am having the same issue in version 0.61.1.
**Server Setup Information:**

- Version of Rocket.Chat Server: 0.61.1
- Operating System: Linux 4.13.0-32-generic
- Deployment Method(snap/docker/tar/etc): docker
- Number of Running Instances: 1
- Node Version: 8.9.4

**Comment by xenithorb** [comment] 2018-02-23 20:57
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/9632

**Comment by karlprieb** [comment] 2018-02-28 22:11
We will work on the #9632 issue. @ecoitsolutions thank your for your feedback.

**Closed by karlprieb** 2018-02-28 22:11 UTC
