### ISSUE TITLE
File Uploads Not Accessible from Desktop Clients

### ISSUE THREAD

**Issue by 78c59635bdd8** [RocketChat/Rocket.Chat#4927] opened 2016-11-11 20:15 UTC
Your Rocket.Chat version: 0.45

When using Rocket Chat through a web browser, and you attempt to open/download a file (for example, a pdf document that has been uploaded), things work as expected, and your browser gives you the ability to open/download the pdf.

However, if you are using the desktop client, and click on a file that has been uploaded, you get a blank tab/page in the browser.  In this case, no PDF document is downloaded or opened.  This also happens with file uploads of other file types.

Is this a limitation of the desktop clients?  Or is this a bug?

**Comment by abulhol** [comment] 2016-11-16 11:28
+1

**Comment by mehdiyahyaoui** [comment] 2016-11-16 16:55
+1

**Comment by EvilWar** [comment] 2016-11-17 08:17
+1

**Comment by JohnDorianMD** [comment] 2016-11-18 11:09
+1

**Comment by algonza** [comment] 2016-11-22 16:29
+1

**Comment by khobbits** [comment] 2016-12-22 14:39
+1
This is really irritating, and is confusing users, and making them loose faith in the platform.
This is a dupe of #3947 and #4150

**Comment by xenithorb** [comment] 2016-12-24 23:19
@RocketChat/core this issue can be closed as it is a dupe of #4150 where I'm trying to track the main points, and the main point of this issue is about being able to download at all which is now fixed in https://github.com/RocketChat/Rocket.Chat/commit/3205250f31d5b0a2eadc1a3a6aa7e1c6c30910bf

**Comment by geekgonecrazy** [comment] 2016-12-25 03:59
Perfect closing in favor of #4150 thanks for the heads up @xenithorb

**Closed by geekgonecrazy** 2016-12-25 03:59 UTC
Labels: feat: file sharing, type: bug
