### ISSUE TITLE
#general keeps getting recreated.

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#11148] opened 2018-06-14 11:37 UTC
That's an information leak I want to get rid of since it auto-joins every user there. I keep deleting it...

**Comment by vynmera** [comment] 2018-06-14 12:31
@kaiiiiiiiii Possibly also a dupe of #7692 and #10182~

**Comment by kaiiiiiiiii** [comment] 2018-06-14 14:41
@vynmera Yipp, those are dupes as well. @TwizzyDizzy We should keep #3870 and close all the others :)

**Comment by Hudell** [comment] 2018-06-14 14:51
Duplicate of #3870

**Closed by Hudell** 2018-06-14 14:51 UTC
