### ISSUE TITLE
Stab the heart -> Hardcoded SVG in /rocketchat-ui-master/master/loading.html

### ISSUE THREAD

**Issue by lunitic** [RocketChat/Rocket.Chat#2578] opened 2016-03-21 19:48 UTC
Your Rocket.Chat version: (make sure you are running the latest)

There is a hardcoded (rocketchat loading icon) in the file
 /rocketchat-ui-master/master/loading.html

Would it possible to remove the SVG from the files and put it in the public/images/logo folder instead.
As it is now you have to remember to put the file back after a upgrade of the server.

**Comment by engelgabriel** [comment] 2016-03-22 19:43
I think we should replace the rocket for a standard loading, that uses less CPU.

**Comment by Sing-Li** [comment] 2016-03-22 19:54
I think this is a cornerstone part of  _**"The Rocket.Chat  Experience"**_

The "pumping heart"  - that gives Rocket.Chat the "soul" that so many adore.

Please consider to re-consider.

**Comment by engelgabriel** [comment] 2016-03-22 20:01
I will reconsider...

**Comment by mrplow** [comment] 2016-03-22 20:08
I think thats going a little far to say its the cornerstone part of "The Rocket.Chat Experience". That's more owning your own data, not the loading image.
The "pumping heart" is most definitely slowing down switching channels on lower end mobile devices for our team members.

**Comment by k0nsl** [comment] 2016-03-22 20:33
I say, keep it, but let us customize it, or even add the ability to disable it.

**Comment by dupree972** [comment] 2016-03-22 20:35
Yeah, it’s friendly looking and end users I think like that Rocket has that inviting look and feel as opposed to some of the less attractive options like Zulip.

**Comment by engelgabriel** [comment] 2016-03-22 20:40
Ok, my goals would be:
- Keep the logo but make it configurable via admin ASSETS panel
- Use a less CPU intensive animation

**Comment by lunitic** [comment] 2016-03-22 22:09
@engelgabriel Sound goods,

I also like the symbol, but on a customized server people just get confused of a big unknown logotype

**Comment by engelgabriel** [comment] 2016-08-24 03:41
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/613

**Closed by engelgabriel** 2016-08-24 03:41 UTC
Labels: type: improvement
