### ISSUE TITLE
unable to send massages on rocket chat giving error via rocket.cat Only you can see this message

### ISSUE THREAD

**Issue by gjetithor9** [RocketChat/Rocket.Chat#16294] opened 2020-01-20 17:30 UTC
Below is the error found in logs

server.js:204 System ➔ error Error sending message: Error: You are not authorized to change message properties     at validateUserIdentity (app/lib/server/functions/sendMessage.js:164:9)     at sendMessage (app/lib/server/functions/sendMessage.js:175:3)     at executeSendMessage (app/lib/server/methods/sendMessage.js:76:10)     at MethodInvocation.sendMessage (app/lib/server/methods/sendMessage.js:104:10)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43

**Comment by herbetom** [comment] 2020-01-20 18:12
You should take a look at #16097

What seems to helps is https://github.com/RocketChat/Rocket.Chat/issues/16097#issuecomment-569691591  (disbling the Use Real Name Option)

**Comment by sampaiodiego** [comment] 2020-01-28 21:24
closing as duplicate of https://github.com/RocketChat/Rocket.Chat/issues/16294

**Comment by sampaiodiego** [comment] 2020-01-28 21:24
https://github.com/RocketChat/Rocket.Chat/issues/16097 sorry

**Closed by sampaiodiego** 2020-01-28 21:24 UTC
