### ISSUE TITLE
Feature Request: Collapse or hide the left sidebar

### ISSUE THREAD

**Issue by mzji** [RocketChat/Rocket.Chat#5420] opened 2017-01-04 13:44 UTC
For the users which likes to split the desktop horizontally with two windows, or uses mobile devices (such as smart phones or tablets), hiding unused parts of the web page is a viable way and a common practice. I hope we could have this functionality since it will increase the usability of Rocket.Chat.

**Comment by Molle500** [comment] 2017-01-04 18:20
This one is already done actually @mzji see #4616 

Not merged tho

**Comment by engelgabriel** [comment] 2017-01-04 19:13
Duplicate of #4441

**Closed by engelgabriel** 2017-01-04 19:13 UTC
Labels: subj: ui/ux, type: new feature
