### ISSUE TITLE
"Invalid User" occurs when requesting a 1:1 conversation

### ISSUE THREAD

**Issue by Nirsa-tistory** [RocketChat/Rocket.Chat#22784] opened 2021-07-28 03:24 UTC
### Description:
"Invalid User" occurs when requesting a 1:1 conversation.

Reload or the other party must first start a 1:1 conversation before you can use it. This issue occurs intermittently.

### Steps to reproduce:
1. Search Click 
2. User selection
3. get one or more red notifications on the upper right corner wiht "invalid user".

### Expected behavior:
1:1 dialog should open

### Actual behavior:
"Invalid User" error occurred, 1:1 conversation possible after reload

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.0
- Operating System: CentOS 7
- Deployment Method: Hosted
- Number of Running Instances: 1
- DB Replicaset Oplog: Enable
- NodeJS Version: 12.18.4 - x64
- MongoDB Version: 4.0.23

### Client Setup Information

- Desktop App or Browser Version: RocketChat Desktop 3.1.1, RocketChat Desktop 3.2.3, Chrome 92
- Operating System: Windows 10

**Comment by ankar84** [comment] 2021-07-28 04:18
related to https://github.com/RocketChat/Rocket.Chat/issues/22256

**Comment by yashovardhan** [comment] 2021-07-28 10:34
Thanks @ankar84 

Closing since this is a duplicate of #22256

**Closed by yashovardhan** 2021-07-28 10:34 UTC
