### ISSUE TITLE
.bin added to dowloaded files

### ISSUE THREAD

**Issue by josep112** [RocketChat/Rocket.Chat#13585] opened 2019-02-27 20:38 UTC
### Description:

When I get a file, video or audio in Livechat and I will download it it adds .bin at the end of the file Example the file is called doc.pdf it downloads as doc.pdf.bin, I found a correction to be made in the packages /rocketchat-file-upload/server/lib/ FileUpload.js file, but I did not find this file , my version is 0.74 Does anyone have a light?

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 1
- NodeJS Version: v11.10.0
- MongoDB Version: v3.6.10

**Comment by zdumitru** [comment] 2019-02-28 08:26
duplicate of #6026

**Closed** 2019-02-28 23:42 UTC
Labels: duplicate
