### ISSUE TITLE
Jitsi fails on 49.0

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#5566] opened 2017-01-13 17:16 UTC
it was working prior upgrades, now jitsi got issue with recognizing camera and desktop sharing.. 

Your Rocket.Chat version: (49.0)

**Comment by geekgonecrazy** [comment] 2017-01-13 23:04
Is there actually an issue with the camera working?  Or is the UI messed up?  Screenshots please?  Because I've seen the UI messed up.  But still starts camera and remote end can still see me

**Comment by rasos** [comment] 2017-01-16 21:56
Jitsi frame is messed up in 0.49.1
![jitsi_rc0 49 1](https://cloud.githubusercontent.com/assets/485723/22000361/faab2a04-dc3e-11e6-9a38-fcfd3503fcae.png)

**Comment by geekgonecrazy** [comment] 2017-01-17 20:41
@rasos this should be fixed in 0.49.2 can you try it?

**Comment by rasos** [comment] 2017-01-18 08:06
Yes I can confirm that Jitsi frame integration is fixed in 0.49.2. The fix was not in the release notes, though.

**Comment by IQ2022** [comment] 2017-01-18 22:26
this is broken.. doesnt work 
![image](https://cloud.githubusercontent.com/assets/12454319/22085713/4608fbec-dda3-11e6-99eb-9c0f1eab51f6.png)

No MIc, no Camera no Desktop sharing
Rocket chat 49.2

**Comment by sampaiodiego** [comment] 2018-08-02 19:33
is this still an issue?

**Comment by rasos** [comment] 2018-08-02 19:44
Works fine, tested in 0.52, 0.56 and 0.63. Issue can be closed.

**Closed** 2018-08-02 19:46 UTC
Labels: feat: video conferencing, stat: waiting response, type: bug
