### ISSUE TITLE
"+" button works only 1time and after refresh

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat#14166] opened 2019-04-17 10:03 UTC
### Description:

Just like in the topic: "+" button for uploading files works only at first time and after refreshing page/app. Doesn't matter if it's priv or channel / app or web.

### Steps to reproduce:

1. Go to Rocketchat.
2. Start conversation and type something.
3. Upload "+" button is hidden after sending message :(
4. Refresh page/app to see and use "+" again.

### Expected behavior:

"+" button shouldn't be hidden

### Actual behavior:

"+" button is hidden:

![rocket-button-bug](https://user-images.githubusercontent.com/3985913/56279654-cbe62100-6108-11e9-9ee9-7ddb58b225e1.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0-rc.2
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: v8.15.0
- MongoDB Version: 4.0.5

**Comment by lolimay** [comment] 2019-04-17 14:53
It seems a great start for my contribution. Hi @tassoevan, could assign this issue for me? Thanks!

**Comment by reetp** [comment] 2019-04-17 16:24
Noted on open.rocket.chat today

**Comment by ggazzo** [comment] 2019-04-17 17:10
duplicate of #14105

**Closed by ggazzo** 2019-04-17 17:10 UTC
Labels: subj: ui/ux, type: bug
