### ISSUE TITLE
Automatically set username and avatar via external Custom OAuth authentication.

### ISSUE THREAD

**Issue by AndrewMontagne** [RocketChat/Rocket.Chat#3175] opened 2016-05-09 10:12 UTC
One would like the ability to set the username, display name and avatar automatically via external Custom OAuth authentication, skipping any dialogs prompting the user to choose a username or avatar.

Discovering the data to determine the username, display name and avatar might be tricky, as different APIs behave differently. Additionally, perhaps there should be a flag set to overwrite the current username, display name and avatar every time the user logs in.

**Comment by marceloschmidt** [comment] 2016-05-09 11:50
Duplicate of #1870 with the addition of setting username. I'll reference it there, closing this one.

**Closed by marceloschmidt** 2016-05-09 11:50 UTC
