### ISSUE TITLE
Add new users from Admin and download User list

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#10981] opened 2018-06-02 13:12 UTC
### Server Setup Information:

* Version of Rocket.Chat Server: 65.1
* Operating System: Linux
* Deployment Method: Dockers
* Number of Running Instances:1 
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

After upgrading to 65.1, i am unable to add or invite new users via admin section, also same for creating new rooms..

Also why is it difficult to have the ability to download user list to an excel sheet or cvs? or any export method?

**Comment by kaiiiiiiiii** [comment] 2018-06-02 13:26
Duplicate of #10951

**Comment by IQ2022** [comment] 2018-06-03 15:18
still we dont have a way to download a user list to an excel or any other format?

**Comment by TwizzyDizzy** [comment] 2018-06-04 10:08
@rocket-cat close

@IQ2022 Yes "we" have: https://github.com/frdmn/rocketchat-export-userlist

@frdmn: maybe put this somewhere in the official docs as "you can give this a shot"?

Cheers
Thomas

**Closed** 2018-06-04 10:08 UTC
