### ISSUE TITLE
the stream-room-messages 's problem

### ISSUE THREAD

**Issue by zhangsong012** [RocketChat/Rocket.Chat#7973] opened 2017-08-30 09:01 UTC
When  enter a room,then send the stream-room-messages  ,app  received the room  messages.
But Re-enter the room,also send the stream-room-messages,app will received two same messages.

-----------------
send message:
{"name":"stream-room-messages","id":"GNC297f1o7LpvdZe5VNIIwNwvqNlONJq35c9kItzIiLLjq0AuW","params":["cvojeRxzPoPRJTGbWv8RyRJQtyuRBz2Jwq",false],"msg":"sub"}

**Comment by zhangsong012** [comment] 2017-08-30 09:15
<img width="1141" alt="default" src="https://user-images.githubusercontent.com/11765163/29864913-ae02d1b0-8da6-11e7-9084-c2c33568baae.png">

**Comment by imrealashu** [comment] 2017-11-07 07:12
Calling subscription twice, listens the subscriptions twice. So if connection is open don't invoke `stream-room-messages`.

**Comment by antgel** [comment] 2017-11-08 18:38
Indeed, this looks like a feature not a bug. Closing.

**Closed by antgel** 2017-11-08 18:38 UTC
