### ISSUE TITLE
Internal Hubot issues

### ISSUE THREAD

**Issue by infinitnet** [RocketChat/Rocket.Chat#5952] opened 2017-02-08 13:47 UTC
Rocket.Chat Version: 0.51.0

Looks like Coffee scripts aren't loading with internal hubot after adding them via GUI.

```
[34mI20170208-13:40:25.480(0) [Wed Feb 08 2017 13:40:25 GMT+0000 (UTC)] WARNING A script has tried registering a HTTP route while the HTTP server is disabled with --disabled-httpd. 
[34mI20170208-13:40:25.486(0) [32mLoaded hubot-help/src/help.coffee 
[34mI20170208-13:40:25.489(0) [32mLoaded hello.coffee 
[34mI20170208-13:40:25.490(0) [32mLoaded zen.coffee 
[34mI20170208-13:40:25.548(0) [31mcan't load 9gag.coffee 
[34mI20170208-13:40:25.549(0) { [Error: Cannot find module 'soupselect'] code: 'MODULE_NOT_FOUND' } 
[34mI20170208-13:40:25.613(0) [31mcan't load remind.coffee 
[34mI20170208-13:40:25.614(0) { [Error: Cannot find module 'lodash'] code: 'MODULE_NOT_FOUND' } 
```
Ideas?

**Comment by engelgabriel** [comment] 2017-02-08 14:36
The problem is that the system is not running `npm install` on the scripts. We need a way to upload scripts to be saved on the local file system, and be able to run `npm install` on each.

**Comment by Valiantiam** [comment] 2017-03-31 16:13
Did you find a way to manually resolve this? There are a lot of scripts we would like to use and customize using the internal hubot.

**Comment by infinitnet** [comment] 2017-03-31 16:32
I didn't look into this further and kept using an external Hubot. Maybe @engelgabriel could provide the steps to manually resolve this - I'd be interested in this too. Also not sure why this got tagged as a support request when this issue actually means that the internal Hubot feature is broken. This should at least be considered a bug with low priority.

**Comment by Valiantiam** [comment] 2017-03-31 16:40
I agree. It states we should be able to use any of the scripts located in that repo, yet only a few actually work.

**Comment by gregs007** [comment] 2017-04-12 21:37
I'd also be interested in a manual workaround. Just trying to load a few scripts with dependencies. Installed via snap in ubuntu server

**Comment by timkinnane** [comment] 2018-03-20 03:43
Duplicated by #6640 - closing this one because the other has more specific history.

**Closed by timkinnane** 2018-03-20 03:43 UTC
Labels: feat: hubot, type: support
