### ISSUE TITLE
Windows desktop app turns black.

### ISSUE THREAD

**Issue by BarnumD** [RocketChat/Rocket.Chat#4968] opened 2016-11-17 16:27 UTC
We are trying out rocketchat.  I downloaded the rocketchat windows client to try out and I'm getting this black screen which I cannot get out of.  Almost the whole screen is black.  If I try to click on the red and white chat icon nothing happens.

![image](https://cloud.githubusercontent.com/assets/2438253/20397701/b63df2c6-acb8-11e6-9091-f69e1a4ed391.png)

Rocket.Chat version: 0.45.0
Client version 1.3.1

**Comment by BarnumD** [comment] 2016-11-17 16:30
If i right click on the red and white icon and select 'reload server' it brings everything back.  Perhaps that just needs to be a UX usability change.

**Comment by allytech** [comment] 2016-11-17 19:30
I would like to second this.  I never opened an issue before but we have quite a few production deploys and this is one of the biggest operational complaints we get.  It is only the windows client and has been a problem since the 0.3x days.  The electron windows client 1.3.1 has been around for some time now and is most likely the cause but I am glad someone else is bringing this up.  We have our help desk tell customers to fully exit the app, not just close the window and open it again.  It will be stable for weeks at a time sometimes and other times it will fail 10 times in an hour.  We have moved a few customers to the Franz client and so far we have not had any reported issues.

**Comment by drickerusa** [comment] 2016-11-17 21:40
We also have seen this issue. What is interesting is that on Win7 the RC client seems to be much more stable because I never had this specific issue. I then upgraded to Win10 on the same machine and now this issue crops up all the time. There are several references to the screen issue with win10. Here is one of the main ones https://github.com/RocketChat/Rocket.Chat.Electron/issues/150. Most of our users have changed over to use the browser only until the client can be fixed.

**Comment by graywolf336** [comment] 2016-11-18 18:03
Closing in favor of https://github.com/RocketChat/Rocket.Chat.Electron/issues/150

**Closed by graywolf336** 2016-11-18 18:03 UTC
Labels: type: bug
