### ISSUE TITLE
Client certificates do not work on Android

### ISSUE THREAD

**Issue by ssolidus** [RocketChat/Rocket.Chat#12450] opened 2018-10-28 17:27 UTC
### Description:

When using a client certificate to verify a client connecting to RocketChat, the RocketChat app does not use the certificate in the devices store to verify itself to the server.

### Steps to reproduce:

1. Deploy a server with a signed certificate
2. Create a reverse proxy that only allows clients with a valid client certificate to authenticate and access the RocketChat endpoint
3. Create a valid client certificate for a client
4. Convert the client certificate into a PKCS12 file
5. Import the PKCS12 file into the Android certificate store, ensuring it is trusted
6. Ensure the certificate chain for the server is trusted on the Android client
7. Attempt to connect to the endpoint through the Rocketchat app

### Expected behavior:

The Rocketchat app sees a matching client certificate for the endpoint in the certificates store, and presents it to the server. The server validates it, and authenticates the client, allowing the app the access the Rocketchat server.

### Actual behavior:

The Rocketchat app does not present any certificate, and it is denied by the server.

### Server Setup Information:

- Version of Rocket.Chat Server: 2.13.3
- Operating System:  Debian "stretch"
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: NA
- NodeJS Version: 8.12.0
- MongoDB Version: NA

### Additional context

It is important to note that when accessing the Rocketchat endpoint through through an Android browser, such as Chrome, it correctly presents the certificate, and is allowed to access the server.

**Comment by reetp** [comment] 2018-10-28 22:38
Your Rocketchat server can't be 2.13.3 Please advise the correct version from the admin panel.
This is most likely an issue with your configuration or app.
Possibly a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/1927
Please have read through there and test.
If it is an app issue please close and open in the correct section.
https://github.com/RocketChat/Rocket.Chat.Android

**Closed** 2018-10-29 05:56 UTC
