### ISSUE TITLE
User Status change

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2734] opened 2016-04-01 15:34 UTC
It would a be a cool idea to have more settings for the status change, like you can leave a message on your status on top saying away from desk or at work etc, or even don't disturb, with possible custom messages. - Message should clear once you are back

**Comment by engelgabriel** [comment] 2016-04-01 18:52
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2422

**Closed by engelgabriel** 2016-04-01 18:52 UTC
