### ISSUE TITLE
Delete DM/s

### ISSUE THREAD

**Issue by nealhamiltonjr** [RocketChat/Rocket.Chat#25812] opened 2022-06-08 20:58 UTC
Delete DM/s

Is this a possibility? We need for users to delete their own direct messages and wipe the whole conversation from the server. They should be able to do this one at a time..like click on the hamburger icon and simple hit delete. Users that get a lot of dm/s should be a able to purge them in bulk. Additionally, admins/managers should be able to delete old stale dm/s from employees that have left the company. This is a requirement in government and other sensitive operations. The admin should be able to turn this feature on or off based on business requirements. After somebody sends a DM to ask a question it should be able to be removed/deleted instead of hiding it. To be clear it should remove the message and the users name from your list until they dm you again. This is one of the only features missing in rocket chat that is a business necessity.

**Comment by ankar84** [comment] 2022-06-09 02:17
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/17927

**Closed by ankar84** 2022-06-09 02:17 UTC
