### ISSUE TITLE
Cordova image upload window displayed incorrectly on screen

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#6875] opened 2017-05-04 07:54 UTC
Rocket.Chat Version: Demo

If you try to upload a picture via the cordova app you get the following screen:

![2017-05-04 09-50-51 3902](https://cloud.githubusercontent.com/assets/5877910/25694591/9bb1486a-30af-11e7-9fc8-558e7aec3e36.png)

**Comment by teamsoo** [comment] 2017-07-03 11:04
@MartinSchoeler Is this duplicate of https://github.com/RocketChat/Rocket.Chat/issues/6676 ?
Maybe we can close one if they're the same.

**Comment by teamsoo** [comment] 2017-07-05 01:57
This should be fixed by  https://github.com/RocketChat/Rocket.Chat/pull/7404 and https://github.com/RocketChat/Rocket.Chat/pull/7376

**Comment by MartinSchoeler** [comment] 2017-07-20 18:16
Yep fixed by #7404

**Closed by MartinSchoeler** 2017-07-20 18:16 UTC
Labels: subj: mobile, subj: ui/ux, type: bug
