### ISSUE TITLE
Don't allow creation of room starting with '#'

### ISSUE THREAD

**Issue by narnaud** [RocketChat/Rocket.Chat#29464] opened 2023-06-06 08:34 UTC
### Description:

It is possible to create rooms starting with '#' in the name, but it's impossible to rename it after the fact.
The only solution is to delete and recreate.

### Steps to reproduce:

1. Create a new Channel
2. Enter "#foo" in the channel name
3. Create it, then try to rename it

### Expected behavior:

Either the user can't use '#' in the channel name (probably better), or he can rename it after the fact.

### Actual behavior:

User can't rename the channel

### Server Setup Information:

- Version of Rocket.Chat Server: latest version at the time of writing - I don't know the details

### Client Setup Information

- Desktop App or Browser Version: latest desktop and browser version at the time of writing (3.9.3)

**Comment by UtkarshM-hub** [comment] 2023-06-07 09:41
I think restricting the use of "#" in the channel name is a great option

**Comment by UtkarshM-hub** [comment] 2023-06-07 09:45
working on it

**Comment by ydv-ankit** [comment] 2023-06-08 21:42
i think its already resolved, can't reproduce now

**Comment by AyushKaithwas** [comment] 2023-06-14 08:07
I think you should close this issue now as it does not allow # in server name now.

![image](https://github.com/RocketChat/Rocket.Chat/assets/86650576/a6843f82-6c78-4f38-be79-7f220659c7d6)

**Comment by hugocostadev** [comment] 2023-06-14 14:27
Thanks for reporting this issue.

This depends on the setting `UTF8 Channel Names Validation`, but does not seems to be respected...

I could rename it here by the way... But we still need to investigate why we can create rooms with `#` when it's not specified in the regex setting

---
**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Closed** 2023-06-14 14:38 UTC
Labels: type: bug
