### ISSUE TITLE
Constant very high (200%) server cpu load

### ISSUE THREAD

**Issue by mclegrand** [RocketChat/Rocket.Chat#24923] opened 2022-03-23 16:52 UTC
### Description:

Our RC instance is on a 2vCPU 4GB server and node+mongo are filling the cpu all the time.

### Steps to reproduce:

1. Start or restart rocketchat

### Expected behavior:

Load is usually low (we have like 10 connected users)

### Actual behavior:

mongodb has a 35% CPU load, node has a 165% load, permanently

### Server Setup Information:

- Version of Rocket.Chat Server: 4.5.2
- Operating System: Ubuntu focal
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: 14.19.0
- MongoDB Version: 4.2.19

### Client Setup Information

- Desktop App or Browser Version: irrelevant
- Operating System: irrelevant

### Additional context
- node and mongo regularly both tried really hard to fill up the ram for some reason, so node has now a --max_old_space_size=2600 and mongo has a "wiredTiger: engineConfig: cacheSizeGB: 1" to prevent them from doing so
- RC regularly tried to fill the disk by writing tens of GB of data in /tmp/userData and /tmp/zipFiles

### Relevant logs:

https://paste.fulltxt.net/1,L9kX7kjW starting log

**Comment by ankar84** [comment] 2022-03-24 05:39
You need more RAM for mongo.

**Comment by fdellwing** [comment] 2022-03-24 10:09
> You need more RAM for mongo.

Not really. We are running our cluster (3.18.5) on 3 vServers with 2 vCPU and 2 GB RAM each. It needs to be restarted about once a month to fight the memory leak, but otherwise it runs perfectly fine. So this seems like a real issue here.

**Comment by ankar84** [comment] 2022-03-24 10:22
> > You need more RAM for mongo.
> 
> Not really. We are running our cluster (RC 3.18.5 + mongo 4.2) on 3 vServers with 2 vCPU and 2 GB RAM each. It needs to be restarted about once a month to fight the memory leak, but otherwise it runs perfectly fine. So this seems like a real issue here.

Yes. Here is a tons of reasons for such high load. Memory leak is one of then. Restart of all instances could help here.
But my guess was mongo not able to put necessary db data to RAM and heavily use SWAP partition.
That could be for example if for a file storage GridFS is chosen, which is not recommended at all.

**Comment by fdellwing** [comment] 2022-03-24 10:23
Yeah, if there are a lot of images or other things stored in GridFS, than the RAM could be a problem.

**Comment by mclegrand** [comment] 2022-03-24 10:43
Should I switch the file upload storage to FileSystem ?

**Comment by ankar84** [comment] 2022-03-24 10:48
> Should I switch the file upload storage to FileSystem ?

Best option would be some S3 storage server like minio. 
But for 10 users server, I guess FileSystem could be a compatible option.

**Comment by Gummikavalier** [comment] 2022-03-24 10:52
I'd be worried about this:
```RC regularly tried to fill the disk by writing tens of GB of data in /tmp/userData and /tmp/zipFiles```
because it might indicate that someone is making exports of their data constantly. Or some old export has failed and starts again and again from the scheduler of RC.

**Comment by ankar84** [comment] 2022-03-24 11:04
> I'd be worried about this: `RC regularly tried to fill the disk by writing tens of GB of data in /tmp/userData and /tmp/zipFiles` because it might indicate that someone is making exports of their data constantly. Or some old export has failed and starts again and again from the scheduler of RC. Export is quite heavy operation, both CPU and memory wise. And when memory runs out, then CPU goes even higher.

Nice catch, @Gummikavalier 
I think I missed that moment.
It could be the real root cause. And if so, it could be fixed easy.
@mclegrand 
Go to **Admin UI - Troubleshoot** and enable `Disable Data Exporter Processor` option
![image](https://user-images.githubusercontent.com/4023037/159903118-8111a1ba-8f82-4c4e-b509-f729ced4935a.png)

**Comment by mclegrand** [comment] 2022-03-24 11:09
oh, nice, the load seems to immediately go back to [2-7]%, I'll monitor it :)

**Comment by dudanogueira** [comment] 2022-03-24 16:46
Closing this issue. Please, reopen if necessary. Thanks!!

**Closed by dudanogueira** 2022-03-24 16:46 UTC

**Comment by nileshA-addweb** [comment] 2023-08-07 10:22
We are using below RC version with Docker Image and getting constant HIGH CPU usage by NODE due to which RC become unavailable and there are no such slow queries or other logs in MongoDB which cause this issue. Can anyone help look into this issue and provide solution.

```
Rocket.Chat Version: 6.2.9
NodeJS Version: 14.21.3 - x64
MongoDB Version: 5.0.18
MongoDB Engine: wiredTiger
Platform: linux
Process Port: 3000
Site URL:
ReplicaSet OpLog: Enabled
Commit Hash: abf746733b
Commit Branch: HEAD
```
