### ISSUE TITLE
Email notification to admin for new signups

### ISSUE THREAD

**Issue by stdjld34** [RocketChat/Rocket.Chat#2176] opened 2016-02-09 20:47 UTC
If this exists I apologize, but I am not able to find it. Could you add the ability to notify admins when a new user signs up. I have selected the admin approval required options, and I have to manually check periodically because I don't get notified when a new account is created.

**Comment by rchikballapur** [comment] 2016-02-10 06:19
+1

**Comment by mrplow** [comment] 2016-02-11 23:59
This would be great!

**Comment by marceloschmidt** [comment] 2016-05-02 17:25
Duplicate of #976.

**Closed by marceloschmidt** 2016-05-02 17:25 UTC
