### ISSUE TITLE
Password reset confirmed also at non-existing e-mail address

### ISSUE THREAD

**Issue by rasos** [RocketChat/Rocket.Chat#6229] opened 2017-03-03 10:16 UTC
When asking for a password reset, a notification pops up, that an e-mail has been sent with further instructions, even with non-existing e-mail addresses. We would expect saying that there is no user associated to that e-mail address.
Furthermore, if you repeat this, the "Password reset" button is duplicated (see screenshot):
![bildschirmfoto_2017-03-03_11-14-06](https://cloud.githubusercontent.com/assets/485723/23547242/c249bfc6-0002-11e7-8f75-756bc18a4840.png)

Rocket.Chat Version: 0.52

**Comment by TheReal1604** [comment] 2017-03-03 17:07
@rasos this could possibly be a "security feature". Because you can get the information is someone is registred with this email adress.. if it says at all requests "positive" you dont have this problem.

**Comment by engelgabriel** [comment] 2017-03-05 04:56
For the reasons stated by @TheReal1604 we will always do a false positive, but the button error needs to be fixed @karlprieb

**Comment by engelgabriel** [comment] 2017-03-05 05:00
Maybe we should make it more clear.. adding a "If this email is registered, we'll send instructions on how to reset your password"

**Comment by va6996** [comment] 2017-03-06 02:59
@rasos , I am unable to reproduce the bug. I'm on 0.53-develop. When I click on reset password, it takes me to the login page. when I again click forgot password, I don't see any  duplicated button.

**Comment by rasos** [comment] 2017-03-07 15:35
@va6996 the duplicated button is definitely reproducable on 0.52, I have the same issue on a test server as well as on production, both repeatedly updated since 0.36 or so. Will check again after our next upgrade cycle.

**Comment by rasos** [comment] 2017-03-07 20:27
Weird login button behaviour is duplicate of #6255 - see screencast https://vid.me/qUoP

**Comment by Hudell** [comment] 2018-06-06 19:09
The button error was fixed on 0.56 (#6741) and the behaviour reported is so by design, so I'll be closing this issue.

**Closed by Hudell** 2018-06-06 19:09 UTC
Labels: feat: email, subj: ui/ux, type: bug
