### ISSUE TITLE
Text parsed as emoji

### ISSUE THREAD

**Issue by iamdaveloper** [RocketChat/Rocket.Chat#26485] opened 2022-08-05 02:48 UTC
### Description:

Text display not properly. e.g ( 10:30 => 1😇0 )

### Steps to reproduce:

1. Type 10:30 and send

### Expected behavior:

10:30 should display properly

### Actual behavior:

1😇0

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.0
- Operating System: 
- Deployment Method: docker
- Number of Running Instances: 1

### Client Setup Information

- Desktop App or Browser Version: Windows / Web (Chrome)
- Operating System: Window 10

**Comment by kanhaiya04** [comment] 2022-08-05 19:27
Hi @iamdaveloper 
I also checked in Linux and facing the same issue.
Can anyone guide me how to resolve this issue as I am new In the Organisation.

**Comment by iamdaveloper** [comment] 2022-08-08 03:05
found another cases
e.g

- http://rocket.chat/ (OK!)
- http://test/ (Failed!) Expected : http://test/ ; Actual : http😕/test/
- http://localhost/ (OK!)

and i tried to disable emoji function in admin panel, but seems not working.

**Comment by abbluiz-userh** [comment] 2022-08-09 02:24
Same problem here

**Comment by EnCz** [comment] 2022-08-10 19:06
Yes, PLEASE fix this or at least make it optional (via administration).
This behaviour is annoying for our users but also completely breaks our automatically received messages via bots / webhooks.

**Comment by xdelatour** [comment] 2022-08-13 12:16
Even worse, composite characters are now drawn as sequence of single characters (for example, teacher is person + school)

**Comment by saschafoerster** [comment] 2022-08-15 07:17
<img width="226" alt="Bildschirmfoto 2022-08-15 um 09 14 50" src="https://user-images.githubusercontent.com/1153741/184592433-9405026a-5cd1-4be8-a890-de46e6f7d29c.png">

Same issue

**Comment by sleeplessnight2** [comment] 2022-08-17 09:59
same happened at my installation.

And the problem is, it makes rc very unpopular for chatting.
Guys, please fix this before any other bugs. This bug attacks the core function of RC: You can't use it for links anymore, for example.

@sampaiodiego

**Comment by Gummikavalier** [comment] 2022-08-22 10:59
This makes also impossible to write correct grammar in Finnish, as the language uses `:` extensively.

**Comment by kekefreedog** [comment] 2022-08-23 08:50
Same problem for me with url which doesn't have `.com` or dot something...
![image](https://user-images.githubusercontent.com/70959083/185956419-483ce199-0e3f-4fbe-b33c-09bbea27e31a.png)

**Comment by hugocostadev** [comment] 2022-09-13 16:30
Fixed by: https://github.com/RocketChat/fuselage/pull/800/files

**Closed by hugocostadev** 2022-09-13 16:30 UTC
Labels: subj: message rendering
