### ISSUE TITLE
Tab autocomplete adds mention to beginning of line, not at cursor position

### ISSUE THREAD

**Issue by peterdalydickson** [RocketChat/Rocket.Chat#3691] opened 2016-07-05 11:31 UTC
Your Rocket.Chat version: 0.35.0

This issue is difficult to describe so I recorded a 49sec jing video - http://screencast.com/t/UtzZZve7d4zs

Basically, when I press tab to autocomplete, I always expect the competition to occur where my cursor is.

But if the letter combination I'm attempting to autocomplete occurs previously in the message, that gets autocompleted instead.

**Comment by gwillen** [comment] 2016-09-23 06:34
I wonder if this is not getting attention because it's not obvious without watching the video what it is? But I just independently hit it, it's really super broken.

Example:

"Hogwarts is cool, gw<TAB>" -> "Ho@gwillen arts is cool, gw"

**Comment by geekgonecrazy** [comment] 2017-01-27 17:26
I've renamed this one to hopefully more accurately explain what it is you're wanting

**Comment by geekgonecrazy** [comment] 2018-04-04 19:25
This one should now be complete.  I've not experienced any issues with it.  Closing

**Closed by geekgonecrazy** 2018-04-04 19:25 UTC
Labels: Feature: Request, feat: autocomplete / popups

**Comment by gwillen** [comment] 2018-04-04 19:30
Thanks! Is there a PR / commit somewhere with the fix? Or is this more a case of "that code got rewritten since this bug was filed"?

**Comment by geekgonecrazy** [comment] 2018-04-05 01:56
@gwillen to be honest so much has changed since then.  I have no idea :grin: I just can't reproduce any more
