### ISSUE TITLE
Updating snap not possible if rocket.chat was stopped and restarted

### ISSUE THREAD

**Issue by d-sko** [RocketChat/Rocket.Chat#4752] opened 2016-10-27 08:48 UTC
Your Rocket.Chat version: snap rocketchat-server 0.43.0 rev. 88

Updating the snap with `snap refresh rocketchat-server` is not working after stopping and starting rocket.chat with `snap [disable/enable] rocketchat-server`:

```
# snap refresh rocketchat-server
error: cannot refresh "rocketchat-server": cannot refresh local snap "rocketchat-server"
```

**Steps to reproduce:**
1. install rocket.chat `snap install rocketchat-server`
2. stop rocket.chat `snap disable rocketchat-server`
3. start rocket.chat `snap enable rocketchat-server`
   - note that from this point on `snap list` does not show a developer for rocket.chat
4. try to update rocket.chat `snap refresh rocketchat-server`
5. you'll see the error mentioned above

Even a restart of the whole server does not fix the problem. Someone also posted this on the [Ubuntu bug tracker](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1632451).

**Comment by geekgonecrazy** [comment] 2016-11-16 17:47
@d-sko thanks for reporting.  This is definitely an issue with snapd.  I'll see if I can bump this that ticket and see where things are at.

**Comment by geekgonecrazy** [comment] 2016-11-17 21:55
Just an update on this, looks like they will have a fix for it released in 2.17.1.

Trying to find out what we can do to get you guys unstuck and upgraded.

**Comment by geekgonecrazy** [comment] 2016-11-20 01:04
@Har01d / @d-sko to fix this you are going to need to back up your data and install the snap again.

```
cp -R /var/snap/rocketchat-server/common ~/rc-backup
sudo snap remove rocketchat-server

# if you want to make sure no data is left over (i don't think there will be) you can sudo rm -rf /var/snap/rocketchat-server here

sudo snap install rocketchat-server

sudo systemctl stop snap.rocketchat-server.rocketchat-mongo
sudo systemctl stop snap.rocketchat-server.rocketchat-server

sudo cp -R ~/rc-backup/* /var/snap/rocketchat-server/common

sudo systemctl start snap.rocketchat-server.rocketchat-mongo
sudo systemctl start snap.rocketchat-server.rocketchat-server
```

**Comment by Har01d** [comment] 2016-11-26 08:50
@geekgonecrazy, thanks, that helped!

The problem is in snapd itself, it will be fixed in the 2.17.1 release

**Comment by geekgonecrazy** [comment] 2016-11-28 03:27
@Har01d correct.  This is the communication I got from the snap team as well.

**Comment by geekgonecrazy** [comment] 2016-11-28 03:41
Going to go ahead and close this as 2.18 has also already been released.  Please follow above instructions if you need to get yours unstuck

**Closed by geekgonecrazy** 2016-11-28 03:41 UTC
Labels: subj: snaps, type: bug

**Comment by GenericUK** [comment] 2017-03-21 09:15
Still the same problem

$ snap list
Name               Version  Rev   Developer  Notes
core               16-2     1512  canonical  -
rocketchat-server  0.46.0   204              -

$ snap --version
snap    2.23.5
snapd   2.23.5
series  16
ubuntu  16.04
kernel  4.4.0-66-generic

**Comment by GenericUK** [comment] 2017-03-21 11:28
The reinstall fix above hasn't worked. Probably doesn't like the jump from 0.46 to 0.53
After install rocket chat will load then after copying backup to common it will fail.

$ sudo systemctl status snap.rocketchat-server.rocketchat-server.service
● snap.rocketchat-server.rocketchat-server.service - Service for snap application rocketchat-server.rocketchat-server
   Loaded: loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-03-21 10:09:15 GMT; 2s ago
 Main PID: 21257 (node)
   CGroup: /system.slice/snap.rocketchat-server.rocketchat-server.service
           └─21257 node /snap/rocketchat-server/528/main.js

systemd[1]: Started Service for snap application rocketchat-server.rocketchat-server.
 /usr/bin/snap[21257]: cmd.go:111: DEBUG: restarting into "/snap/core/current/usr/bin/snap"

$ sudo systemctl status snap.rocketchat-server.rocketchat-mongo.service
● snap.rocketchat-server.rocketchat-mongo.service - Service for snap application rocketchat-server.rocketchat-mongo
   Loaded: loaded (/etc/systemd/system/snap.rocketchat-server.rocketchat-mongo.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2017-03-21 10:21:17 GMT; 8s ago
  Process: 26328 ExecStart=/usr/bin/snap run rocketchat-server.rocketchat-mongo (code=exited, status=100)
 Main PID: 26328 (code=exited, status=100)

systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Main process exited, code=exited, status=100/n/a
systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Unit entered failed state.
systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Failed with result 'exit-code'.
systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Service hold-off time over, scheduling restart.
systemd[1]: Stopped Service for snap application rocketchat-server.rocketchat-mongo.
systemd[1]: snap.rocketchat-server.rocketchat-mongo.service: Start request repeated too quickly.
systemd[1]: Failed to start Service for snap application rocketchat-server.rocketchat-mongo.

**Comment by jonashoechst** [comment] 2017-07-05 11:34
Is there an _easy_ fix yet? According to @GenericUK reinstall won't do it.
We've got a Rocket.Chat installation here, that just stopped to work. I guess and automatic update happened there...

```
Jul 05 13:19:47 dschat snap[1201]: 2017/07/05 13:19:47 loading Caddyfile via flag: open /var/snap/rocketchat-server/671/Caddyfile: no such file or directory```

**Comment by GenericUK** [comment] 2017-07-05 11:38
@jonashoechst You might want to take a look here https://github.com/RocketChat/Rocket.Chat/issues/7402

**Comment by geekgonecrazy** [comment] 2017-12-18 21:37
For all using above advice.. Please see docs for proper backup restore procedure https://rocket.chat/docs/installation/manual-installation/ubuntu/snaps/#how-do-i-backup-my-snap-data
