### ISSUE TITLE
UI: Message option menu hides behind sidebar

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#5510] opened 2017-01-12 01:22 UTC
![img_9449](https://cloud.githubusercontent.com/assets/193273/21873199/488d987c-d86d-11e6-9784-59dba9bfcae7.PNG)
Running 0.48.2, the menu (when hitting the gear next to a message) is placed behind the users name, therefor occasionally offscreen (mainly handheld, image shows full screen width, only cropped height). Placing it above the message would solve the problem.
I try to check, if I can fix it myself and open a pull request.

**Comment by engelgabriel** [comment] 2017-01-12 01:24
Thanks for the report. We already have plans to change this.
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/5464

**Closed by engelgabriel** 2017-01-12 01:24 UTC

**Comment by soundstorm** [comment] 2017-01-12 01:26
Ah, just missed that issue!
