### ISSUE TITLE
Pain points related to production usage so far

### ISSUE THREAD

**Issue by kajisaap** [RocketChat/Rocket.Chat#5321] opened 2016-12-23 16:35 UTC
We are running latest released version of Rocket.Chat via snap packages under Ubuntu LTS 16.04. But the issues mentioned below do not reside only to the particular version rather we have seen RC infested with these nuisances/issues at least for last 6 releases. 
<br><br>

1. **Exception while invoking method send/update**
<img width="658" alt="update message" src="https://cloud.githubusercontent.com/assets/722803/21457935/d49664e2-c900-11e6-9998-891f10576ffe.png">

<img width="649" alt="send message" src="https://cloud.githubusercontent.com/assets/722803/21457944/dc59b5ee-c900-11e6-8184-123f949e5f25.png">

This might be because single node process is getting bombarded. Do you guys have any other insights?
<br><br>

2. **too many open files**
<img width="586" alt="too many open files" src="https://cloud.githubusercontent.com/assets/722803/21458209/9e0a5440-c902-11e6-82d8-ce44c1fe8051.png">

We share visual elements a lot ( emojis, pictures, attachments etc ) while communicating with one another. This problem particularly has been a great source of frustration so far. The only solution we could come to is to restart the node process. When we started out, node application had 1024 open file limit but he had it spiked up to 30,000 but still, the problem occurs giving strong suggestion to "**FD leak**". We dug up few things and it might not be just RC
https://github.com/meteor/meteor/issues/6952
<br><br>

3. **call stack exceeded**
<img width="693" alt="maximum call stack" src="https://cloud.githubusercontent.com/assets/722803/21458213/a8fa58fa-c902-11e6-8362-c077de2df4f8.png">

We did find the problem of this nature being documented/asked about around the web but for RC, absolutely no idea on this.

**Comment by lucasvanhalst** [comment] 2016-12-23 19:03
The duplicate key error is caused by #2872

**Comment by Hudell** [comment] 2018-04-17 20:00
This issue has been open for a long time. Are those problems still happening for anybody?

**Comment by graywolf336** [comment] 2018-04-18 03:09
Thanks for following up with us @kajisaap. I'm going to go ahead and close it, should anyone else have these problems please feel free to comment with details and we'll consider opening it again.

**Closed by graywolf336** 2018-04-18 03:09 UTC
Labels: stat: waiting response, type: bug
