### ISSUE TITLE
Uploads with multiple digits in filename

### ISSUE THREAD

**Issue by geekgonecrazy** [RocketChat/Rocket.Chat#1004] opened 2015-10-05 20:00 UTC
So it appears when a filename contains multiple digits like a phone number.  This is the output:

![image](https://cloud.githubusercontent.com/assets/51996/10291903/db188298-6b71-11e5-80ce-c56c131d4f34.png)

**Comment by gmsecrieru** [comment] 2015-10-05 20:03
Related to #810

**Comment by gmsecrieru** [comment] 2015-10-09 22:39
I will close this one as the problem is not related with the uploads but with autolinked.

**Closed by gmsecrieru** 2015-10-09 22:39 UTC
