### ISSUE TITLE
Why the <br/> tag was created

### ISSUE THREAD

**Issue by Nirsa-tistory** [RocketChat/Rocket.Chat#22920] opened 2021-08-13 07:45 UTC
### Description:
I was using Rocket Chat with Zabbix, At some point, the "br" tag came into existence.
"br" tag is recognized as text, is there any way to fix this?

### Expected behavior:
**ex)**
![image](https://user-images.githubusercontent.com/60082298/129322705-6de386b3-e5f4-4b33-b0b0-657667d0266a.png)

### Actual behavior:
**ex)**
![image](https://user-images.githubusercontent.com/60082298/129322334-706e7254-3e90-4ad0-a9fa-6b1a2411b9cf.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.16.3
- Operating System: CentOS 7
- Deployment Method: Docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: Enable
- NodeJS Version: 12.22.1
- MongoDB Version: [4.0.26](url)

### Client Setup Information

- Desktop App or Browser Version: Chrome 92.0.4515.131
- Operating System: Windows 10

### Relevant logs:

![image](https://user-images.githubusercontent.com/60082298/129322526-451256d7-4376-4650-837d-4c2f47a2ddc0.png)

**Comment by ankar84** [comment] 2021-08-13 09:41
Fixed by https://github.com/RocketChat/Rocket.Chat/pull/22727
Duplicate of
#22701
#21040
#22734

**Comment by debdutdeb** [comment] 2021-08-13 09:53
Thanks Anton!!

Nirsa, to fix this you simply have to update your instace to 3.17.0 😉 

Closing since it's already fixed in 3.17.0 👋🏼

**Closed by debdutdeb** 2021-08-13 09:53 UTC
