### ISSUE TITLE
After removing custom CSS, the code is still applied

### ISSUE THREAD

**Issue by rauhmaru** [RocketChat/Rocket.Chat#5725] opened 2017-01-23 14:08 UTC
Rocket.Chat Version: 0.49.4
Running Instances: 1
DB Replicaset OpLog: no

[After removing this custom CSS](https://github.com/RocketChat/Rocket.Chat/issues/5721#issuecomment-274492689), it still continues to influence the layout.
![dropdown](https://cloud.githubusercontent.com/assets/2289237/22206967/058c04a8-e15c-11e6-9dc8-15ea26fe0581.png)
Even after removing the CSS and reloading the page, the background still looks as if the CSS was applied.

**Comment by engelgabriel** [comment] 2017-01-23 15:25
What happen if you put another CSS rule instead? Just trying to find out if the function is ignoring when the setting is empty.

**Comment by rauhmaru** [comment] 2017-01-23 17:21
@engelgabriel, I added a new CSS, applied it and then removed it, using the reset button.
The reset function did not work, leaving the previous CSS.

**Comment by MartinSchoeler** [comment] 2017-02-13 15:54
@rauhmaru This issue was fixed by #5982 , if the issue is still happening please reopen this, thanks!

**Closed by MartinSchoeler** 2017-02-13 15:54 UTC
Labels: subj: ui/ux, type: support
