### ISSUE TITLE
Closing Thread brings up 'Start video call' Video Conference window

### ISSUE THREAD

**Issue by nooblag** [RocketChat/Rocket.Chat#19080] opened 2020-09-30 12:59 UTC
### Description:
When closing a thread view, the Video Conference dialog box appears asking to start a call.

![Capture](https://user-images.githubusercontent.com/1122344/94688205-9ec71600-0370-11eb-8ac5-d5e352633dd8.PNG)

### Steps to reproduce:

1. Open a thread conversation
2. Close the thread window
3. Video Conference dialog box appears

### Expected behavior:
Thread closes without unexpectedly opening Video Conference dialog box

### Actual behavior:
Video Conference dialog box appears:

![Capture](https://user-images.githubusercontent.com/1122344/94687923-3f690600-0370-11eb-8746-594fdfa5ec8d.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.3
- Operating System: Ubuntu 18.04.5 LTS
- Deployment Method:  TAR, manual
- Number of Running Instances: 1
- DB Replicaset Oplog: ?
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App Version: 2.17.11
- Operating System: Linux Mint 19.3

### Additional context

None at the moment.

### Relevant logs:

No logs available that seem to be relevant to this problem.

**Comment by nooblag** [comment] 2020-09-30 13:03
Issue went away when refreshing Desktop app. Weird.

**Comment by ankar84** [comment] 2020-10-07 04:29
@nooblag please reopen issue - I have it on regular basis on server 3.6.3 and desktop version 3.0.2
Interesting - I get it on desktop and not get it on web version
I think that Jitsi call can somehow be involved.
I couldn't reproduce that 100%

**Comment by ankar84** [comment] 2020-10-15 10:06
Our users experienced that issue, but I still can't reproduceable method to do that.
Still investigate

**Comment by ankar84** [comment] 2020-11-02 08:41
I'm on 3.7.1 now.
Joined to Jitsi conf in one room and continue to working in RC in other chats, so, yes.
Replication method is really easy:
1. Join Jitsi call
2. Open any Thread in any chat
3. Thy to close Thread window
Here is a gif
![thread-jitsi](https://user-images.githubusercontent.com/4023037/97847205-4af97500-1d00-11eb-8360-34a9598fb0dd.gif)

**Comment by ankar84** [comment] 2021-03-19 09:13
@dougfabris Looks like that bug fixed in 3.12.1 (maybe on any previous version, I tested in 3.12.1)
![jitsi-thread](https://user-images.githubusercontent.com/4023037/111757566-85793e00-88ac-11eb-9096-3d4417d5827e.gif)

**Comment by nooblag** [comment] 2021-03-20 11:31
I haven't encountered it for a while and now using 3.12.1 so maybe you're right.

**Comment by dougfabris** [comment] 2021-04-05 20:22
You're right! Thanks @ankar84

**Closed by dougfabris** 2021-04-05 20:22 UTC
Labels: feat: video conferencing, subj: ui/ux
