### ISSUE TITLE
Messages not marked as read (after read) - Push notifications being sent on read messages

### ISSUE THREAD

**Issue by bkraul** [RocketChat/Rocket.Chat#22900] opened 2021-08-10 14:29 UTC
### Description:

Sent messages are not being marked as read when read and they remain with unread status, which leads to push notifications being sent on messages that are supposed to already have been read.

### Steps to reproduce:

1. Install latest version of develop branch
2. Send a message to user
3. Have the user check the message
4. The message is not marked as read even when it has been read.

### Expected behavior:

Message should be marked as read.

### Actual behavior:

Message is NOT marked as read:
![Ey0wBwtCVX](https://user-images.githubusercontent.com/14616851/128878927-c22656d5-4b24-4242-8e01-b92e57a76939.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.18.0-develop (bb4dbfc4b)
- Operating System: Ubuntu 20.04.2 LTS (docker)
- Deployment Method: docker 
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.22.1
- MongoDB Version: 4.0.26

### Client Setup Information

- Desktop App or Browser Version: 3.2.3 / Firefox 90.0.2
- Operating System: Windows 10 64bit 21H1

### Additional context

**Develop commit 6592d40 does not appear to have this issue, so changes after that seem to be introducing this bug.**

**Comment by ankar84** [comment] 2021-08-11 01:18
I can confirm that behavior, not always, but sometimes.

**Comment by debdutdeb** [comment] 2021-08-13 10:10
Thanks for reporting this bkraul 🙂 

I do confirm this as well. I have seen this happen on 3.17.0 as well, if I haven't confused among the many test installs that I move through each day 😶

**Comment by bkraul** [comment] 2021-08-16 13:13
@debdutdeb could we get someone to maybe triage this issue?

**Comment by bkraul** [comment] 2021-08-17 18:04
Wishing it would have been triaged first, but beggars can't be choosers...it seems this issue is corrected by commit e7649144d .

**Comment by debdutdeb** [comment] 2021-08-18 08:02
The PR you linked is a fix for another issue that surfaced yesterday on 3.18.0-develop.

I'm not 100% sure if that's going to fix this current issue as well or not since I don't know exactly what the reason behind this issue is at all. 

I'll leave this open and bring it up in one of our next meetings. 

Thank you.

**Comment by dougfabris** [comment] 2021-08-18 13:15
@bkraul The PR you mentioned is already merged, can you take a look and see if you still have the issue, please?

**Comment by bkraul** [comment] 2021-08-21 11:55
Yes, that is exactly what I stated. I tested the image with that commit and it seems to have resolved the issue. I just pointed out that I wish my issue had been triaged. Seems that is not quite there these days. This issue can be closed.

**Closed** 2021-08-21 14:40 UTC
