### ISSUE TITLE
Slack threads get imported as individual messages

### ISSUE THREAD

**Issue by lpilz** [RocketChat/Rocket.Chat#16883] opened 2020-03-14 22:10 UTC
### Description:

When importing a Slack export, the messages which were in Threads on the Slack server are being imported as individual messages, not as Threads to Rocket.Chat.

### Steps to reproduce:

1. Export Data from Slack
2. Import Data to Rocket.Chat

### Expected behavior:

When importing threaded messages from Slack one would expect them to be threaded in Rocket.Chat as well.

### Actual behavior:

These imported messages, which were threaded in Slack are not threaded in Rocket.Chat but imported as individual messages in the Channels.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.2
- Operating System: Ubuntu 18.
- Deployment Method: snap
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version:  v12.14.0
- MongoDB Version: 3.6.14

### Relevant logs:

```
Missed import types: {   thread_broadcast: {     type: 'message',     subtype: 'thread_broadcast',     text: '<CENSORED>',     user: 'UJ3U7P18V',     ts: '1580917582.059400',     thread_ts: '1580915572.058200',     root: {       client_msg_id: 'f44aa30a-f71e-4c94-9666-348b01b19d44',       type: 'message',       text: '<CENSORED>',       user: 'UNAFH2S8H',       ts: '1580915572.058200',       team: 'TFSUU7CQY',       edited: [Object],       attachments: [Array],       blocks: [Array],       thread_ts: '1580915572.058200',       reply_count: 9,       reply_users_count: 7,       latest_reply: '1580922291.062100',       reply_users: [Array],       replies: [Array],       subscribed: false     },     blocks: [ [Object] ],     client_msg_id: 'b4ad420b-ac47-4a8d-bafe-43012c3e94e1',     reactions: [ [Object], [Object] ]   },   tombstone: {     type: 'message',     subtype: 'tombstone',     text: 'This message was deleted.',     user: 'USLACKBOT',     hidden: true,     ts: '1574354941.092000',     thread_ts: '1574354941.092000',     reply_count: 3,     reply_users_count: 2,     latest_reply: '1574358992.092500',     reply_users: [ 'UKVQNNS7N', 'UPPCRCAAK' ],     replies: [ [Object], [Object], [Object] ],     subscribed: false   },   channel_archive: {     type: 'message',     subtype: 'channel_archive',     ts: '1553437862.000900',     user: 'UGMKST4QG',     text: '<CENSORED>'   },   channel_unarchive: {     type: 'message',     subtype: 'channel_unarchive',     ts: '1557826312.000300',     user: '<CENSORED>'   } } 

Setting default file store to GridFS 
```

**Comment by zdumitru** [comment] 2020-03-15 17:28
Could be a duplicate of #6833

**Comment by lpilz** [comment] 2020-03-15 17:57
It probably is. Is there any ongoing effort to implement this functionality? And/or (how) could I contribute there?

**Closed** 2020-04-13 14:48 UTC
