### ISSUE TITLE
Jitsi URL contains 'undefined'

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat#11949] opened 2018-09-04 16:07 UTC
### Description:

In short when you click to call you get a URL like this:

https://myjitsi.server.com/RocketChatundefinedJXmyQPiwGsEPtwmDagsadk424Rbw23B2BC

Seems to be missing a var and giving 'undefined'

### Steps to reproduce:

Setup Admin/ Video Conference / Jitsi
Domain myjitsi.server.com
URL Room prefix RocketChat

Select user
Click Video Chat
Unusual URL used

### Expected behavior:

The URL should be 
https://myjitsi.server.com/RocketChat

### Actual behavior:

The URL is similar to: 
https://myjitsi.server.com/RocketChatundefinedJXmyQPiwGsEPtwmDagsadk424Rbw23B2BC

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.1
- Operating System: linux
- Deployment Method: Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Disabled
- NodeJS Version: v8.11.3
- MongoDB Version: 131

**Comment by arminfelder** [comment] 2018-09-05 14:44
same as  #9419

**Comment by matt020191** [comment] 2018-09-05 16:16
I had posted in the previous issue regarding this as well. Just upgraded to 0.69.1 and am experiencing the same problem.

**Comment by kaiiiiiiiii** [comment] 2018-09-05 16:59
As @arminfelder said, it’s a duplicate of #9419

//CC: @TwizzyDizzy

**Closed** 2018-09-05 17:04 UTC
