### ISSUE TITLE
Search messages

### ISSUE THREAD

**Issue by aronrichter** [RocketChat/Rocket.Chat#15066] opened 2019-07-29 16:24 UTC
When you click to find a message from a conversation and you start to write, your input still on a new message field.

My suggestion is, when you click in search a message, the focus may be on the input find message field.

Thanks for your attention!

@aronrichter

**Comment by reetp** [comment] 2019-07-30 09:23
@rocket-cat close

Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/11482 (amongst others)

Please search thoroughly before posting new Issues. This has been opened several times before.

**Closed by reetp** 2019-07-30 09:23 UTC
