### ISSUE TITLE
Registration Screen Showing Incorrect Register Button Text

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#6695] opened 2017-04-14 19:43 UTC
Rocket.Chat Version: 0.55.0-rc.5
Running Instances: 4
DB Replicaset OpLog: Yes
Node Version: 4.5

Text of button says "LOGINREGISTER A NEW ACCOUNT".
<img width="627" alt="screen shot 2017-04-14 at 2 39 52 pm" src="https://cloud.githubusercontent.com/assets/8405384/25054062/c0e19de0-2120-11e7-9982-f1239066f075.png">

**Comment by MartinSchoeler** [comment] 2017-04-17 12:26
duplicate of #2137

**Closed by MartinSchoeler** 2017-04-17 12:26 UTC
