### ISSUE TITLE
User Roles for Rooms Not Displayed

### ISSUE THREAD

**Issue by waveyuk** [RocketChat/Rocket.Chat#7329] opened 2017-06-24 14:12 UTC
If you add a user as a moderator to a room in the Administration settings, when you view the Permissions in the back end, no users you add are displayed even though they have the Moderator permissions.

Rocket.Chat Version: 0.56.0
Running Instances: 1
DB Replicaset OpLog: Enabled
Node Version: 4.8.1

**Comment by MartinSchoeler** [comment] 2017-06-26 19:26
duplicate of #5898

**Closed by MartinSchoeler** 2017-06-26 19:26 UTC
Labels: feat: roles / permissions, type: bug
