### ISSUE TITLE
Long texts as input lag the screen

### ISSUE THREAD

**Issue by mikaelmello** [RocketChat/Rocket.Chat#11171] opened 2018-06-17 03:24 UTC
### Description:

Whenever I'm typing long messages everything starts to freeze and lagging

### Steps to reproduce:

1. Go to input text
2. Type a lot, 7+ lines

### Expected behavior:

Not lag with that much text

### Actual behavior:

I can't type without having to wait seconds for the characters to show up

### Server Setup Information:

- Version of Rocket.Chat Server: Open
- Operating System: Elementary OS 0.4 Loki

### Additional context

Using the Electron app, i5 5200u and 12GB of RAM, it has a GPU too if that is relevant

**Comment by kaiiiiiiiii** [comment] 2018-06-17 08:50
Propably a duplicate of #10583

**Comment by ggazzo** [comment] 2018-06-18 01:10
duplicated :) thanks for the feedback

**Closed by ggazzo** 2018-06-18 01:10 UTC
