### ISSUE TITLE
Localisation error in German

### ISSUE THREAD

**Issue by Zack-83** [RocketChat/Rocket.Chat#26243] opened 2022-07-13 07:58 UTC
### Description:

Hallo, the German locale translates wrongly "is writing":

### Expected behavior:

The correct verb form is "XY schreibt" (="XY writes") or "XY schreibt gerade" (="XY writes right now"): German does not have the construction with the "-ing" form.

### Actual behavior:
![grafik](https://user-images.githubusercontent.com/37865804/178681427-94968ab2-70c2-4cc5-b8a5-2bdcfe01bca2.png)

Best regards

Giacomo Lanza

**Comment by phriedrich** [comment] 2022-07-26 06:56
This has been reported before, but unfortunately has not been fixed for nearly a year:

- https://github.com/RocketChat/Rocket.Chat/issues/25045
- https://github.com/RocketChat/Rocket.Chat/issues/23593

**Comment by chotaire** [comment] 2022-09-07 16:59
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/23593

**Closed** 2022-11-22 15:20 UTC
