### ISSUE TITLE
Rest API - support setting of permissions

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/Rocket.Chat#10946] opened 2018-05-30 11:53 UTC
In the admin pannel on the RC server at `admin/permissions` it is possible to set permissions for various user types.  It would be great if the API supported that.  (I apologize if it already does, I have just not yet been able to figure out how that would work.)  Thanks!

**Comment by kaiiiiiiiii** [comment] 2018-05-30 11:58
Duplicate of #7961

**Comment by MarcosSpessatto** [comment] 2018-06-01 15:18
Closing this issue in favor of #7961.

**Closed by MarcosSpessatto** 2018-06-01 15:18 UTC
