### ISSUE TITLE
KaTeX interpretation in code blocks

### ISSUE THREAD

**Issue by IceBear2k** [RocketChat/Rocket.Chat#8676] opened 2017-10-27 07:51 UTC
### Description:

KaTeX syntax (used intentionally or unintentionally) in code blocks is interpreted and results in weird strings.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Ubuntu 16.04 - x86_64
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 3
* DB Replicaset Oplog: Enabled
* Node Version: v4.8.4

### Steps to Reproduce:

1. Send code block including KaTeX syntax (single or multi line):
`grep -A 2 "\[${TO_PROFILE}\]"` (add \`)
![image](https://user-images.githubusercontent.com/4847450/32093083-5a5c494c-bafb-11e7-9b7b-e8e115b54477.png)
2. Rendering is broken in single or multi line cases:
![image](https://user-images.githubusercontent.com/4847450/32093140-939166e8-bafb-11e7-994f-ad3ee08e696e.png)

### Expected behavior:

Don't (try) to interpret/render KaTeX in code blocks.

### Actual behavior:

KaTeX is interpreted/rendered in code blocks (incorrectly).

**Comment by MartinSchoeler** [comment] 2017-10-27 11:24
Duplicate of #8640

**Closed by MartinSchoeler** 2017-10-27 11:24 UTC
