### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by jy2008** [RocketChat/Rocket.Chat#7703] opened 2017-08-10 01:36 UTC
i did the snap install, so my RC is always auto updated to most updated version.
yesterday i was changing hubot script and then all of sudden i cannot access my rchat website, gave me error : 502 Bad Gateway. Even after i deleted whatever change i made, still couldn't access.

Interestingly, the website will always go back to normal in a couple hours, then if i started to use it in admin settings or try to restart hubot, it won't let me login hubot, and website start to shut down again. 

It just come and forth like this, it is on, then i started to use it in admin section, then it shuts down, then on again in a couple hours.

what might be the reason?

I tried to resize my droplet/server, doesn't help either

**Comment by geekgonecrazy** [comment] 2017-08-10 20:06
@jy2008 make sure you have at least a gig of ram.

Also sounds like something else might be going on.  Please hop over to [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap) so we can try to help you with this support.

Since this is not a bug more more of a support item, i'm going to go ahead and close this ticket.

**Closed by geekgonecrazy** 2017-08-10 20:06 UTC
Labels: type: support
