### ISSUE TITLE
Manually Approve New Users - how do admin know???

### ISSUE THREAD

**Issue by crsCR** [RocketChat/Rocket.Chat#9450] opened 2018-01-20 00:25 UTC
When this is switched on, how do admin know? Notifications, a way to search, anything? Unless you know the users details and so can search them under Users in Administration, I can't see how this is done. So, if there is a way can someone please tell me. If there isn't a way then obviously there needs to be. I've see other issues asking for an email notifications sent for this - that's a good option for some though I'd prefer just some notification in app/browser for admin/mods. Right now, Id settle for anything.

Manually Approve New Users: If this is set to true, new users will have to wait for a user with the view-user-administration permission to approve their account before using Rocket.Chat.

**Comment by rasos** [comment] 2018-01-20 16:48
See also #9281, duplicate of #5977.

**Comment by graywolf336** [comment] 2018-01-22 20:53
Closing as a duplicate.

**Closed by graywolf336** 2018-01-22 20:53 UTC
