### ISSUE TITLE
Help me. Files don't open in chat. How to change Site URL: http://localhost:3000 to ip address?

### ISSUE THREAD

**Issue by dkorpachev** [RocketChat/Rocket.Chat#22480] opened 2021-06-27 07:35 UTC
Can't get the server installed

Operating System Ubuntu 20.04.2 LTS
Browser Firefox 89.0.1 (64-bit)
Rocket.Chat version 3.2.2
Expected behavior Open File in Chat
Actual behavior Error, http://localhost:3000/file-upload/L2Yg9xkAJ7uWKPpWu/%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9%20%D1%82%D0%BE%D1%87%D0%B5%D1%87%D0%BD%D1%8B%D0%B9%20%D1%80%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA.bmp?download
Can the bug consistently be reproduced? Yes If so, how? Open file in chat
Relevant errors and other log output
Screenshots are necessary

### Description:

 how to change Site URL: http://localhost:3000 to ip address and DNS NAME.

### Steps to reproduce:

1.  Go to the user sent a message in the form of a file
2. Click on 'file in chat' 

### Expected behavior:

downloading a file from the server

### Actual behavior:

http://localhost:3000/file-upload/L2Yg9xkAJ7uWKPpWu/%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9%20%D1%82%D0%BE%D1%87%D0%B5%D1%87%D0%BD%D1%8B%D0%B9%20%D1%80%D0%B8%D1%81%D1%83%D0%BD%D0%BE%D0%BA.bmp?download

### Server Setup Information:

- Version of Rocket.Chat Server: 3.15
- Operating System: linu
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 12.18.4 -x64
- MongoDB Version: 4.0.2

0 Apps
SERVER RUNNING
Rocket.Chat Version 3.15
Node JS Version 12.18.4 -x64
MongoDB Version 4.0.2
MongoDB Engine mmapv
Platform: linu
Process Port: 3000
Site URL: http://localhost:3000
ReplicaSet OpLog Enabled
Commit Hash 55457025d6
Commit Branch: HEA

### Client Setup Information

-  Rocket.Chat version 3.2.2      /   Browser Version: Firefox 89.0.1 (64-bit)
- Operating System: Windows 10

### Additional context

Give me please manual, configuring transfer  file in a chat. how to change Site URL: http://localhost:3000 ?

**Comment by johncrisp** [comment] 2021-06-28 12:25
Duplicate of #22473 and this forum post

https://forums.rocket.chat/t/how-to-rename-localhost/11491

Closing as a support issue.

**Closed by johncrisp** 2021-06-28 12:25 UTC
