### ISSUE TITLE
Admin can remove user even if user is already removed from the room

### ISSUE THREAD

**Issue by shivang-16** [RocketChat/Rocket.Chat#31712] opened 2024-02-09 17:43 UTC
### Description:

When an admin removes a user from a room, the option to remove the user persists for the admin, even after the user has been successfully removed. This creates confusion and a potential for unintended actions.

### Steps to reproduce:

1. Log in to Rocket.Chat as an administrator.
2. Navigate to a specific room where multiple users are present.
3. Remove a user from the room.
4. Verify that the user has been successfully removed from the room.
5. Observe that the option to remove the same user is still available for the admin.

### Expected behavior:

The option to remove a user should not be available for the admin after the user has been successfully removed from the room. This ensures clarity and prevents unintentional actions.

### Actual behavior:

The option to remove the user persists for the admin even after successfully removing the user from the room.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.7.0
- Operating System: macOS
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0.3

### Client Setup Information

- Desktop App or Browser Version: chrome 121
- Operating System: macOs

### Pull request corresponds to this issue 
#31525 

### Additional context

https://github.com/RocketChat/Rocket.Chat/assets/125182653/71c4bf94-7e4e-484c-b734-e7488ab57e31

**Comment by shivang-16** [comment] 2024-02-09 17:57
hey @dougfabris @rique223, should I work on this issue?

**Comment by rique223** [comment] 2024-02-09 18:22
Please have at it @shivang-16, this looks like a big UX issue.

**Comment by shivang-16** [comment] 2024-02-09 18:27
okay sure, I'm working on this

**Comment by rique223** [comment] 2024-02-09 19:00
Hey @shivang-16, looks like we already have a PR that solves this issue. Could you please have a look at #31525 and close this issue if the problem is already solved?

**Comment by shivang-16** [comment] 2024-02-09 19:05
yeah @rique223 , I think the problem is solve in that pr.  Should I close this issue or you can link that issue with the pr?

**Comment by rique223** [comment] 2024-02-09 19:55
@shivang-16 Please link it to the PR, it was a little mistake on my side telling you to close it.

**Closed** 2024-08-23 03:27 UTC
