### ISSUE TITLE
[Android-ReactNative] Can't search channel when entering rocket chat app with notification

### ISSUE THREAD

**Issue by hoanff** [RocketChat/Rocket.Chat#22748] opened 2021-07-23 10:05 UTC
Step1: Open Apps
![Screenshot_2](https://user-images.githubusercontent.com/61579021/126765920-a19a57af-95c2-45bf-ae29-9f03d176d737.png)
Step2: Hide apps and click notifications
![image](https://user-images.githubusercontent.com/61579021/126765996-2bb53959-52ea-48ce-a823-fa548c1a7b39.png)
Step3: Click notifications join Channels Apps
![image](https://user-images.githubusercontent.com/61579021/126766118-9c0037d3-8016-4ec7-9881-ef3ac4311edf.png)
Step4: Back List Channels and search
![image](https://user-images.githubusercontent.com/61579021/126766413-4da4922c-15e0-466f-8f0e-65978f8c5234.png)
Step5: Search channels
![image](https://user-images.githubusercontent.com/61579021/126767089-7e13b80e-a067-4eb0-ab5a-b817e153ad6d.png)

-> Search not working, click button close search not working and crash app !

**Comment by johncrisp** [comment] 2021-07-23 13:36
Closing of duplicate of https://github.com/RocketChat/Rocket.Chat/issues/22747

Please stick to one issue.

Thanks.

**Closed by johncrisp** 2021-07-23 13:36 UTC
