### ISSUE TITLE
Crash after specific message

### ISSUE THREAD

**Issue by mboogert** [RocketChat/Rocket.Chat#12584] opened 2018-11-09 19:55 UTC
Description:

Rocket.Chat crashes when trying to send the message:

```dork@rot-sbc1-dc1:/var/log$ grep 31812334555 syslog\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28788]: INFO: <script>: 186269e35488949024645fdb7d80138c@sop.wlvaip.not - +32123456789\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28788]: INFO: <script>: 186269e35488949024645fdb7d80138c@sop.wlvaip.not - CB, Checking restrictions nr: +32123456789 block: n acc: zagnitOLD\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, handling call to: +31123456789 on account: enna02, and to: +32123456789 on account: zagnitOLD dest: +31123456789\nSep 27 00:36:21 rot-sbc1-dc1 /usr/sbin/kamailio[28779]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, accounting from +32123456789 to id: 2213\ndork@rot-sbc1-dc1:/var/log$ grep 2hdecaye0d4f0b86201f42027c546807 syslog\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - LCR, 1 Delivering to +31123456789 from +31334455667 call to GW 123.123.123.123\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, handling call to: +31123456789 on account: enna02, and to: +32123456789 on account: zagnitOLD dest: +31123456789\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, Channels 0 used out of 5 for account enna02\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, No price found in reseller table for: +31123456789\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, Price found for nr: +31123456789 ppc 0.0250000000 pps 0.0001416660\nSep 27 00:36:20 rot-sbc1-dc1 /usr/sbin/kamailio[28772]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, Prefix is ON the limitless_list\nSep 27 00:36:21 rot-sbc1-dc1 /usr/sbin/kamailio[28779]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, dialog:start\nSep 27 00:36:21 rot-sbc1-dc1 /usr/sbin/kamailio[28779]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, redirect accounting from +31334455667 to id: 1\nSep 27 00:36:21 rot-sbc1-dc1 /usr/sbin/kamailio[28779]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, accounting from +32123456789 to id: 2213\nSep 27 00:36:28 rot-sbc1-dc1 /usr/sbin/kamailio[28774]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, dialog:end\nSep 27 00:36:28 rot-sbc1-dc1 /usr/sbin/kamailio[28774]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, Booking credits 0.0259916620 from: 2213\nSep 27 00:36:28 rot-sbc1-dc1 /usr/sbin/kamailio[28774]: INFO: <script>: 2hdecaye0d4f0b86201f42027c546807@123.123.123.123:5060 - ACC, Updated end_time for internal (free) leg\ndork@rot-sbc1-dc1:/var/log$`

Server Setup Information:

    Rocket.Chat Version: 0.71.1
    NodeJS Version: 8.9.3 - x64
    Platform: linux
    Deployment Method: docker
    Number of Running Instances: 1
    mongoDB Version: 3.6

Steps to Reproduce:

    use rocketchat via the web ui or via the electron desktop app (other clients untested)
    send the message

Expected behavior:

Server accepts the message
Actual behavior:

Server becomes unresponsive for all users, node process goes into a busy loop (100% cpu)

**Comment by reetp** [comment] 2018-11-09 20:20
So you paste that entire message (which contains personal information !!) and enclose it with 3 bacticks to start and 1 backtick to end (from what I can see)?

**Comment by mboogert** [comment] 2018-11-09 21:19
The personal info is malformed ;-)
Yes, I'm trying to post a message using 3 backticks to make it a code block in RC.

**Comment by reetp** [comment] 2018-11-09 22:04
:-)
It should start and finish with 3 ticks I think??

**Comment by localguru** [comment] 2018-11-09 22:06
That could be a duplicate of #11681

**Comment by reetp** [comment] 2018-11-16 23:15
@rocket-cat label add type:bug

**Comment by reetp** [comment] 2018-11-16 23:18
Can't flag this is a bug but I could reproduce this.

Clearly something is choking in the message parsing and this needs addressing as it seems to hard stop rocket and leave the message in the db.

**Comment by reetp** [comment] 2018-11-16 23:18
Additionally I did use triple back ticks both ends of the message.

**Comment by geekgonecrazy** [comment] 2018-11-19 02:16
@RocketChat/core we should take a look at this

**Comment by fabien4455** [comment] 2018-11-20 10:11
Tested on 0.71.1 the bug is still here...

**Comment by geekgonecrazy** [comment] 2018-11-27 07:46
@rodrigok @sampaiodiego :top:

**Comment by rodrigok** [comment] 2018-11-27 11:34
@geekgonecrazy I tested it but I wasn't able to find why it happens.

**Closed** 2021-11-28 19:53 UTC
Labels: type: bug, subj: ui/ux
