### ISSUE TITLE
Minimize User List

### ISSUE THREAD

**Issue by blhuynh** [RocketChat/Rocket.Chat#10864] opened 2018-05-23 16:11 UTC
In order to view messages more efficiently
As a user
I would like to be able to have the ability to minimize the user and channel list on the left.

**Comment by TwizzyDizzy** [comment] 2018-05-23 17:20
@rocket-cat close

Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/4688.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-05-23 17:20 UTC
