### ISSUE TITLE
Private chatroom quote bug

### ISSUE THREAD

**Issue by 12test12** [RocketChat/Rocket.Chat#6626] opened 2017-04-07 09:30 UTC
Rocket.Chat Version: 0.54.2
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: 4.8.1

If you click on the quoted text twice then a new page open and the last chat history is not visible.
But if you re-login then the chat is back.

![privateroomquote](https://cloud.githubusercontent.com/assets/23378492/24793415/3d0dd6a8-1b82-11e7-95af-bde7c36eb334.gif)

**Comment by MartinSchoeler** [comment] 2017-04-07 14:06
Duplicate of #6050

**Closed by MartinSchoeler** 2017-04-07 14:06 UTC
