### ISSUE TITLE
[BUG][Permissions] post-readonly ignored when posting msg via API

### ISSUE THREAD

**Issue by soundstorm** [RocketChat/Rocket.Chat#17931] opened 2020-06-16 21:53 UTC
### Description:

While a user can't post a message to a read only channel via the web interface it is still possible via API. Only file uploads respect the permission. Seems to be related to #15303

### Expected behavior:

Error when trying to post to read-only channel without `post-readonly` permission via API.

### Actual behavior:

Can post messages via API `api/v1/chat.postMessage`, but no uploads `api/v1/rooms.upload`.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.3.3

**Comment by pierre-lehnen-rc** [comment] 2020-06-17 13:28
Duplicate of #12534, is fixed on #17709

**Closed by pierre-lehnen-rc** 2020-06-17 13:28 UTC
