### ISSUE TITLE
Some direct message channels hang after upgrade

### ISSUE THREAD

**Issue by mhkeller** [RocketChat/Rocket.Chat#1050] opened 2015-10-09 14:14 UTC
I just pulled the latest with `docker pull rocketchat/rocket.chat` and now some, but not all, direct message channels hang and don't load. On working and both working direct message channels, `websockets` is open gives a `101` status in the Network panel.

**Comment by mhkeller** [comment] 2015-10-09 15:19
"Hiding" the direct message, re-adding the person and refreshing seems to fix this.

**Comment by gmsecrieru** [comment] 2015-10-13 12:14
@mhkeller are you still experiencing this issue and/or can you provide steps to reproduce it?

**Comment by mhkeller** [comment] 2015-10-13 15:37
Ya I'm still seeing this altho it could be related to the VirtualBox situation we were discussing earlier. I've been waiting on IT to provision a server. After that switch I'll see if this issue remains. Currently it's happening only with some users but I can't pin down any pattern. If there are any logs you'd like to see in the meantime I'd be happy to send.

**Comment by gmsecrieru** [comment] 2015-10-13 15:40
[This](http://websocketstest.com/) might help identify if some of these clients are experiencing WS issues, which might be (one of) the cause(s).

**Comment by mhkeller** [comment] 2015-10-13 15:46
Getting the a-okay in FireFox Chrome and Safari but still the same hanging behavior with certain DMs. Removing and adding those message rooms again seems to fix but only temporarily.
![screen shot 2015-10-13 at 11 45 50 am](https://cloud.githubusercontent.com/assets/498744/10459926/fc36a70a-719f-11e5-996f-b994221eb423.png)

**Comment by gmsecrieru** [comment] 2015-10-13 15:56
Would you be able to ask for the other DM client to perform the same test and report the results to you/us?

**Comment by geekgonecrazy** [comment] 2015-10-13 16:52
@mhkeller did you ever manage to get a linux vm with bridged networking and install via docker inside that vm?

If not I think this is very much related to your setup.

**Comment by mhkeller** [comment] 2015-10-14 13:39
Possibly related to same issue as: https://github.com/RocketChat/Rocket.Chat/issues/1051

Restarting the server seems to have fixed this. Closing.

**Comment by mhkeller** [comment] 2015-10-23 18:17
This is still happening now using the heroku deploy process. It is sometimes fixed when you hide and re-add the room but not always. Sometimes hiding + re-adding works in combination with a refresh or restart of the electron app.

**Comment by mohamedmayla** [comment] 2015-11-02 09:51
I have the same problem when I open some direct messages, Administration/Users or channels.
The app stuck with this loading screen:
![chat-loading-bug](https://cloud.githubusercontent.com/assets/4347943/10878497/991663f6-8156-11e5-8031-0c0a061d80e1.PNG)

the solution @mhkeller provided "Hiding the direct message, re-adding the person" sometimes solve the problem.

We deployed the app using docker and an image created from the latest committed version.
I don't know how to reproduce this, as this happen for some accounts and other don't.

**Comment by flashguy22** [comment] 2015-11-17 11:46
I have to keep this one alive as well.

Some of my users experience the issue of the loading screen not disappearing  for direct messages.
This happens in the app on windows, firefox and also chrome on android. Looks like a server issue.
Groups and Channels work fine.

Rocket.Chat runs on a Ubuntu Linux Machine

**Comment by rodrigok** [comment] 2015-11-17 23:23
There are errors in console when this problem occurs?

**Comment by engelgabriel** [comment] 2015-12-03 05:22
I have a sample DM to show you @rodrigogs so we can investigate on our own server.

**Comment by marceloschmidt** [comment] 2016-02-04 18:17
@engelgabriel @rodrigok has this been addressed?

**Comment by engelgabriel** [comment] 2016-02-04 18:20
I believe so. Let's close this as it can be reopened if someone else complains about it again.

**Closed by engelgabriel** 2016-02-04 18:20 UTC
Labels: type: need more info
