### ISSUE TITLE
After upgrading to 3.9.1 from 3.8.0 apps are not working correctly

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#19781] opened 2020-12-07 19:33 UTC
### Description:

After upgrading to 3.9.1 from 3.8.0 apps are not working correctly. They are showing up as available slash commands but running the commands don't do anything. Commands that require image previews, like Giphy, shows up a loading bar as if it's waiting to load the images but nothing ever loads. Commands like /webex that output an embed after typing /webex just don't return anything back after sending.

### Steps to reproduce:

1. Have a rocket.chat server with multiple instances 
2. Install some apps and make sure they are working, like Giphy or WebEx
3. Upgrade to 3.9.1
4. Odd behavior begins

### Expected behavior:

Apps should just work

### Actual behavior:

![csRNc1TuGt](https://user-images.githubusercontent.com/6295044/101395994-f1004800-3887-11eb-9589-ab3ab968f0e1.gif)

Notice it shows "Disabled" 
![image](https://user-images.githubusercontent.com/6295044/101396081-0e351680-3888-11eb-8270-349ac6d0ec2f.png)

But still shows up as an available slash command:
![image](https://user-images.githubusercontent.com/6295044/101396104-17be7e80-3888-11eb-8a13-5f559258011f.png)

Forever stuck in no loading mode:
![re51lMf16s](https://user-images.githubusercontent.com/6295044/101396172-2b69e500-3888-11eb-8462-04dd1e85027a.gif)

### Server Setup Information:

- Version of Rocket.Chat Server: Version	3.9.1 798241b9e5a45a7b118c09cee38b6d8e9c0e53e1
- Operating System: CentOS 
- Deployment Method: 
- Number of Running Instances: 4
- DB Replicaset Oplog: 
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.21

### Client Setup Information

- Desktop App or Browser Version: 3.0.6
- Operating System: Windows 10

**Comment by wreiske** [comment] 2020-12-07 19:44
Possibly related to https://github.com/RocketChat/Rocket.Chat/pull/19763

**Comment by thassiov** [comment] 2021-03-12 13:48
Hey @wreiske , I was trying to reproduce the problem but I didn't get the same result. The commands are running as expected after the upgrade. Are you still experiencing this issue? Have you upgraded since then? And what are you using to run your cluster, is it kubernetes, docker compose?
Thank you

**Comment by d-gubert** [comment] 2021-04-01 17:44
Hey @wreiske ! Just pinging about this situation :) If you're still experiencing the problem and are able to help us reproduce, let us know! 

Just a heads up, if we don't hear from you in the next few days we'll be assuming the problem is solved and close the issue :)

**Comment by wreiske** [comment] 2021-04-01 18:14
I have an upgrade planned for this weekend upgrading from 3.11.1, so I'll let you know!

**Comment by l8com** [comment] 2021-04-06 19:53
@wreiske did you see that with a mobile device as well?  Was this an E2EE Channel? We see the same here: https://github.com/sampaiodiego/rocket.chat.app-poll/issues/67

**Comment by d-gubert** [comment] 2021-07-13 13:33
Folks! This issue is a bit old and we've had many a release since then, with no reports of a similar error. Given the inactivity, I'll be closing it for now :)

**Closed by d-gubert** 2021-07-13 13:33 UTC
Labels: feat: apps
