### ISSUE TITLE
[Bug] can't save room settings / can't delete room

### ISSUE THREAD

**Issue by JSG01** [RocketChat/Rocket.Chat#8562] opened 2017-10-20 09:06 UTC
### Description:
After updating from 0.58.4 to version 0.59.1, i'm not able to save my room settings. When i open the informations, it is possible to change them, but not to save it. As well there is no way to delete a room. The whole area looks shifted.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Ubuntu
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.4

### Steps to Reproduce:

1. Update to 0.59.1
2. Go to "administration > rooms"
3. Open room settings

### Actual behavior:

- The settings can be changed but not saved.
- No room delete available.
- UI looks buggy in the right pane.

![bildschirmfoto 2017-10-20 um 11 19 43](https://user-images.githubusercontent.com/32953933/31814011-a2b24a98-b588-11e7-91f9-5f3051ccc3c7.png)
.

**Comment by TwizzyDizzy** [comment] 2017-10-20 09:16
I can confirm this. Might be far fetched but could be related to: https://github.com/RocketChat/Rocket.Chat/issues/8546

**Comment by himbeere** [comment] 2017-10-20 11:28
Related issue. Deleting the room is not possible anymore? Or do i miss something?

**Comment by JSG01** [comment] 2017-10-20 11:30
I will add it

**Comment by Nosferous** [comment] 2017-10-20 17:24
Same issues as original poster. Same version / server deployment as well.

Can't modify/delete room in End-User interface > Room Info
Or Administration > Rooms

**Comment by MarZab** [comment] 2017-10-23 14:16
A quick fix is adding this to layout->customcss:

`.flex-tab .channel-settings .button {visibility: visible}`

**Comment by exagon** [comment] 2017-10-24 08:32
The fix work, thanks a lot.

**Comment by PhABC** [comment] 2017-10-24 15:12
You can also go in the JS console and type `document.getElementsByClassName("button primary save")[0].click()`, which will save the changes.

**Comment by TwizzyDizzy** [comment] 2017-10-28 22:02
@MartinSchoeler I think this is something that should maybe be incorporated at least into the 0.60.0 or 0.59.4 milestone (since 0.59.3 seems done)... 

Cheers
Thomas

**Comment by dstaykov** [comment] 2017-11-03 06:49
Working fine!

**Comment by rodrigok** [comment] 2017-12-01 12:50
Closed by #8753

**Closed by rodrigok** 2017-12-01 12:50 UTC
Labels: subj: ui/ux, type: bug
