### ISSUE TITLE
Applying Font Effects to Hyperlink shortcuts breaks messages

### ISSUE THREAD

**Issue by starhound** [RocketChat/Rocket.Chat#18202] opened 2020-07-07 12:59 UTC
### Description:

Adding text effects to hyperlink shortcuts seems to cause raw HTML to be displayed in the message.

### Steps to reproduce:

1. enter [ * TEST * ] ( https://google.com ) 

without the extra spacing

### Expected behavior:

A bold hyperlink

### Actual behavior:

< span class="copyonly"> * </span> <strong> TEST </strong> <span class="copyonly"> * </span>

is displayed

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: Ubuntu 20.04
- Deployment Method: snap
- Number of Running Instances: 1 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version: Browser (Chrome)
- Operating System: Win10

**Comment by MartinSchoeler** [comment] 2020-07-23 21:05
Since no server version has been reported and I cannot reproduce this error on the latest develop version (tested at open.rocket.chat). I will be closing this issue if you are still facing this issue on an updated server please reopen this. Thanks!

**Closed by MartinSchoeler** 2020-07-23 21:05 UTC
