### ISSUE TITLE
Jira notifications via WebHook - Layout broken

### ISSUE THREAD

**Issue by tars21** [RocketChat/Rocket.Chat#20560] opened 2021-02-02 12:00 UTC
### Description:
After updating from Rocket.Chat 3.10.4 -> 3.11.0 the layout of incoming messages sent via JIRA Webhooks is broken / not useful.

### Steps to reproduce:
1. Create Incoming Webhook ( see https://docs.rocket.chat/guides/administrator-guides/integrations/jira )
2. Create / Update JIRA Task
3. Read Rocketchat message

### Expected behavior:
Get a functional designed message with text and clickable links to the JIRA ticket.

### Actual behavior:
Get a message only containing the `*ACTION*[TICKET-ID](URL...`
To note here the URL is ending with "..." therefore not refered to as clickable URL in the chatwindow

![jira_webhook](https://user-images.githubusercontent.com/2291835/106597123-40948480-6556-11eb-91e9-520e43629539.png)

### Server Setup Information:
- Version of Rocket.Chat Server: 3.11.0
- Operating System: Debian 9.13
- Deployment Method: tar
- Number of Running Instances: 3
- DB Replicaset Oplog: enabled
- NodeJS Version: 3.6.21
- MongoDB Version: v12.20.1

### Client Setup Information
- Desktop App or Browser Version: all
- Operating System: all

### Additional context
The [jira-rocketchat-hook.js](https://github.com/malko/rocketchat-jira-hook/blob/master/jira-rocketchat-hook.js) worked fine for years.

### Relevant logs:
-

**Comment by Scronkfinkle** [comment] 2021-02-02 13:37
I can confirm the same behavior is happening with our gitlab webhook integration. Looks the same as the screenshot post

**Comment by yash-rajpal** [comment] 2021-02-02 16:02
I feel this is very similar to #20539. Can you check changing script as described in other issue?

**Comment by tars21** [comment] 2021-02-02 16:17
The issue looks very similar, but the "second example" script mentioned there is just for [Gitlab](https://docs.rocket.chat/guides/administrator-guides/integrations/github), not for JIRA :thinking:
My Python is bad, but the Github Webhook script doesn't look similar to the JIRA one to merge something.

**Comment by Gummikavalier** [comment] 2021-02-02 16:31
I compared GitHub example scripts and the difference between those are that the first one parses links and markdown into the text field while the latter script forms those into the attachment. So there is a markdown parsing issue, but it only affects text field.

Selected parts from the latter GitHub example script:

```
    const attachment = {
      author_icon: svg_inline_prefix + gh_pr_svg,
      author_name: '#' + request.content.pull_request.number + ' - ' + request.content.pull_request.title,
      author_link: request.content.pull_request.html_url
    };

and

return {
      content: {
        icon_url: user.avatar_url,
        alias: user.login,
        text: text,
        attachments: [attachment]
      }
```

**Comment by fdellwing** [comment] 2021-02-03 07:25
I guess this is a the same issue as #20556 and will be fixed by #20569

**Comment by danielpotthast** [comment] 2021-02-03 13:12
> I guess this is a the same issue as #20556 and will be fixed by #20569

@fdellwing That’s not correct. The `attachment.text` webhook attribute is no longer parsed (markdown to HTML).
#20569 only fixes the embedded link description.

**Comment by fdellwing** [comment] 2021-02-03 13:18
> The attachment.text webhook attribute is no longer parsed (markdown to HTML).

I dont think so. I think the reason it is not parsed is because it is cut off and thus no valid markdown.

**Comment by danielpotthast** [comment] 2021-02-03 13:22
#20569 removes CSS from HTML output but doesn’t change any rendering behavior.

**Comment by aditya-mitra** [comment] 2021-02-03 17:45
> #20569 removes CSS from HTML output but doesn’t change any rendering behavior.

Noted!
I will make another pull request for parsing markdown to html.

**Comment by yash-rajpal** [comment] 2021-02-03 18:15
@aditya-mitra I think it can be done within same pr, to keep down confusion 😅

**Comment by danielpotthast** [comment] 2021-02-04 08:55
@aditya-mitra Thank you for updating the PR, but I don't think that this will fix the JIRA notification issue.
The Jira webhook uses the `attachment.text` attribute in integrations (not the oembedUrlWidget).

Here is the sample payload from admin-panel:
```json
{
  "text": "Example message",
  "attachments": [
    {
      "title": "Rocket.Chat",
      "title_link": "https://rocket.chat",
      "text": "Rocket.Chat, the best open source chat", // this attribute is no longer parsed from markdown to html and sliced to one single line
      "image_url": "/images/integration-attachment-example.png",
      "color": "#764FA5"
    }
  ]
}
```

**Comment by fdellwing** [comment] 2021-02-04 09:18
As far as I'm aware of, the oembedUrlWidget ist the used fallback widget if nothing else like audio, video, image matches.

**Comment by aditya-mitra** [comment] 2021-02-04 09:21
Thanks for pointing it out. I will look to it now!

**Comment by fdellwing** [comment] 2021-02-04 09:26
We use a pretty similar JSON payload at that is handled by oembedUrlWidget -> https://github.com/RocketChat/Rocket.Chat/issues/20556#issuecomment-771607590

**Comment by danielpotthast** [comment] 2021-02-04 09:47
> As far as I'm aware of, the oembedUrlWidget is the used fallback widget if nothing else like audio, video, image matches.

I don't think so. The oembedUrlWidget is not used in this case.
If oembed is used, the class `message-oembed` is in DOM. In this case the class `rcx-message-attachment` is in there:
![message-attachment](https://user-images.githubusercontent.com/10034251/106874807-4add8c80-66d6-11eb-8b3e-0063584b591c.png)


In my opinion the `applyMardownFor` is not applied because the `mrkdwn_in` list is empty:
https://github.com/RocketChat/Rocket.Chat/blob/2de76ab2aa9a6f03796f57494d78e7b9590379cf/client/components/Message/Attachments/DefaultAttachment.tsx#L58

**Comment by fdellwing** [comment] 2021-02-04 09:59
Interesting find, it seems that there went something really wrong in the 3.11.0. The rcx-message-attachment also has its overflow hidden.

**Comment by yash-rajpal** [comment] 2021-02-04 10:05
> > As far as I'm aware of, the oembedUrlWidget is the used fallback widget if nothing else like audio, video, image matches.
> 
> I don't think so. The oembedUrlWidget is not used in this case.
> If oembed is used, the class `message-oembed` is in DOM. In this case the class `rcx-message-attachment` is in there:
> ![message-attachment](https://user-images.githubusercontent.com/10034251/106874807-4add8c80-66d6-11eb-8b3e-0063584b591c.png)
> 
> 
> In my opinion the `applyMardownFor` is not applied because the `mrkdwn_in` list is empty:
> https://github.com/RocketChat/Rocket.Chat/blob/2de76ab2aa9a6f03796f57494d78e7b9590379cf/client/components/Message/Attachments/DefaultAttachment.tsx#L58

@danielpotthast How to reproduce a message like that?

**Comment by danielpotthast** [comment] 2021-02-04 10:09
That’s a basic incoming webhook message (see `https://rocketchat.domain.tld/admin/integrations/webhook-incoming`):

```bash
curl -X POST -H 'Content-Type: application/json' \
    --data '{"alias":"Sample","text":"Example message","attachments":[{"title":"CRITICAL","text":"this is a sample content for Rocket.Chat issue\n\n…","color":"#764FA5"}]}' \
    https://rocketchat.domain.tld/hooks/…/…
```

**Comment by yash-rajpal** [comment] 2021-02-04 10:51
The link `https://rocketchat.domain.tld/admin/integrations/webhook-incoming` is not working for me @danielpotthast

**Comment by fdellwing** [comment] 2021-02-04 11:01
You need to setup that on your own installation:

Administration -> Integrations -> Incoming

**Comment by yash-rajpal** [comment] 2021-02-04 11:03
Okay got it. Thanks @fdellwing @danielpotthast

**Comment by aditya-mitra** [comment] 2021-02-04 15:21
**Thank you everyone** for guiding me and helping me reproduce the problem so quickly.
I opened pull request #20606 which might be able to fix the problem.
If I am missing anything, please do it point it out. I add that fix as soon as possible.

**Closed** 2021-02-18 01:54 UTC
