### ISSUE TITLE
Users status between servers with federation always "online"

### ISSUE THREAD

**Issue by Stanymanman** [RocketChat/Rocket.Chat#17201] opened 2020-04-07 13:22 UTC
### Description:

Hi,

I have two instance of Rocket.Chat with federation.
It's ok, the 2 users servers can speak between us.
But online status seems do not be updated.
On each server, users on remote servers appears always online but it's not the case.

### Steps to reproduce:

On the first server we can see the user "Test TS" (online) which is on the remote server: 

![image](https://user-images.githubusercontent.com/13351946/78673453-73dc9780-78e2-11ea-83d2-acef0a08dbf4.png)

But on the remote server we can see the user "Test TS" is not connected:

![image](https://user-images.githubusercontent.com/13351946/78673787-eb122b80-78e2-11ea-8f53-71abdf6abac8.png)

The status of users seeams to not be updated beatween server in federation mode.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.12
- Operating System: Ubuntu Server 18.04
- Deployment Method: Manual Installation
- Number of Running Instances: 2
- NodeJS Version: 12.14.0
- MongoDB Version: 4.0.17

Thanks !

**Comment by ankar84** [comment] 2020-04-11 11:46
Confirm that for 3.1.0

**Comment by Stanymanman** [comment] 2020-04-14 10:17
Hi,
yes problem is always here.

**Comment by Polyblog** [comment] 2020-05-19 10:32
I have the same problem on 3.2.2 version.

**Comment by ankar84** [comment] 2020-06-01 04:16
First issue about that is https://github.com/RocketChat/Rocket.Chat/issues/13709

**Comment by col-panic** [comment] 2020-07-30 12:07
Same behaviour on 3.4.2

**Comment by col-panic** [comment] 2020-08-20 11:20
Is this a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/13709 ?

**Comment by ankar84** [comment] 2020-08-20 11:26
> Is this a duplicate of #13709 ?

I think it is.

> First issue about that is #13709

**Comment by geekgonecrazy** [comment] 2020-09-17 00:18
Closing in favor of #13709

**Closed by geekgonecrazy** 2020-09-17 00:18 UTC
Labels: feat: federation
