### ISSUE TITLE
URL Parser does not recognise URLs with emoji in

### ISSUE THREAD

**Issue by Ultimation** [RocketChat/Rocket.Chat#8993] opened 2017-12-01 17:11 UTC
### Description:
When someone shares a URL with emoji in it, it is not clickable. 

You can still copy and paste the emoji into the url bar of a browser to access it.

Using both web interface and desktop app.
### Server Setup Information:
I do not manage this server

### Steps to Reproduce:
Paste https://😻🍕.ws/ into rocketchat

### Expected behavior:
The url should highlight and be clickable

### Actual behavior:
The url appears as normal text

**Comment by TwizzyDizzy** [comment] 2018-04-01 12:51
@rocket-cat close

Closing this. Cannot reproduce on open.rocket.chat. If this still doesn't work for you on latest stable version, please get back to me!

Cheers
Twizzy

**Closed by TwizzyDizzy** 2018-04-01 12:51 UTC
Labels: feat: message
