### ISSUE TITLE
Not possible to create new users

### ISSUE THREAD

**Issue by reinerj** [RocketChat/Rocket.Chat#11102] opened 2018-06-12 09:42 UTC
### Description:

With the latest release we are not able anymore to create users. The option to create a new user is not longer there. We tried it with the desktop and the web app. We are using 0.65.1
### Steps to reproduce:

Go to administration
click on users 

### Expected behavior:

The option to create a new user in the menu

### Server Setup Information:

Version | 0.65.1
OS Type | Linux
Node Version | v8.9.3

### Relevant logs:

 [34mI20180608-08:25:16.491(0) Will load cache for users 
[34mI20180608-08:25:16.964(0) 35 records load from users 
[34mI20180608-08:25:16.966(0) Will load cache for rocketchat_room 
[34mI20180608-08:25:16.970(0) 44 records load from rocketchat_room 
[34mI20180608-08:25:16.970(0) Will load cache for rocketchat_subscription 
[34mI20180608-08:25:16.985(0) 135 records load from rocketchat_subscription 
[34mI20180608-08:25:16.985(0) Will load cache for rocketchat_settings 
[34mI20180608-08:25:17.100(0) 715 records load from rocketchat_settings 
[34mI20180608-08:25:19.510(0) Updating process.env.MAIL_URL 
[34mI20180608-08:25:19.511(0) Starting Email Intercepter... 
[34mI20180608-08:25:26.209(0) Will load cache for rocketchat_permissions 
[34mI20180608-08:25:26.214(0) 81 records load from rocketchat_permissions 
[34mI20180608-08:25:26.234(0) Will load cache for rocketchat_roles 
[34mI20180608-08:25:26.235(0) 12 records load from rocketchat_roles 
[34mI20180608-08:25:29.759(0) LocalStore: store created at  
[34mI20180608-08:25:29.759(0) LocalStore: store created at  
[34mI20180608-08:25:29.760(0) LocalStore: store created at  
[34mI20180608-08:25:32.632(0) Setting default file store to GridFS 
[34mI20180608-08:25:32.635(0) LocalStore: store created at  
[34mI20180608-08:25:32.635(0) LocalStore: store created at  
[34mI20180608-08:25:32.635(0) LocalStore: store created at  
[34mI20180608-08:25:44.438(0) (rocketchat_migrations.js:160) Migrations: Not migrating, already at version 121
[34mI20180608-08:25:44.929(0) [32mUsing GridFS for custom sounds storage 
[34mI20180608-08:25:44.933(0) [32mUsing GridFS for custom emoji storage 
[34mI20180608-08:25:45.010(0) Updating process.env.MAIL_URL 
[34mI20180608-08:25:47.408(0) [32m➔ [32mSystem ➔ startup 
[34mI20180608-08:25:47.408(0) [32m➔ [32m+---------------------------------------------------------+ 
[34mI20180608-08:25:47.408(0) [32m➔ [32m|                      SERVER RUNNING                     | 
[34mI20180608-08:25:47.408(0) [32m➔ [32m+---------------------------------------------------------+ 
[34mI20180608-08:25:47.408(0) [32m➔ [32m|                                                         | 
[34mI20180608-08:25:47.409(0) [32m➔ [32m|  Rocket.Chat Version: 0.65.1                            | 
[34mI20180608-08:25:47.409(0) [32m➔ [32m|       NodeJS Version: 8.9.3 - x64                       | 
[34mI20180608-08:25:47.409(0) [32m➔ [32m|             Platform: linux                             | 
[34mI20180608-08:25:47.409(0) [32m➔ [32m|         Process Port: 3000                              | 
[34mI20180608-08:25:47.409(0) [32m➔ [32m|              | 
[34mI20180608-08:25:47.409(0) [32m➔ [32m|     ReplicaSet OpLog: Disabled                          | 
[34mI20180608-08:25:47.410(0) [32m➔ [32m|          Commit Hash: 8349c36de0                        | 
[34mI20180608-08:25:47.410(0) [32m➔ [32m|        Commit Branch: HEAD                              | 
[34mI20180608-08:25:47.410(0) [32m➔ [32m|                                                         | 
[34mI20180608-08:25:47.410(0) [32m➔ [32m+---------------------------------------------------------+

**Comment by kaiiiiiiiii** [comment] 2018-06-12 11:37
Duplicate of #10951, #10966, #10981 and #11077.

Will be fixed in the next release (#11049).

Work-a-round: Select an existing User and the menu will appear. After that you're able to add new Users.

**Comment by TwizzyDizzy** [comment] 2018-06-13 08:00
Closing this. @kaiiiiiiiii said it all :)

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-06-13 08:00 UTC
