### ISSUE TITLE
Empty administration sections

### ISSUE THREAD

**Issue by ostapski** [RocketChat/Rocket.Chat#17598] opened 2020-05-11 07:49 UTC
### Description:

Tried to configure rocket.chat email settings
both "Mailer"  and "Email" sections are empty 

### Steps to reproduce:

1.  Go to 'Administration' 
2.  Click on 'Mailer' - section is empty 
2.  Click on 'Email' - section is empty 

### Expected behavior:

Secton with configuration settings

### Actual behavior:

Majority of config sections are empty - no way to configure anything

![Capture1](https://user-images.githubusercontent.com/2835357/81536591-1e295e00-936c-11ea-90e9-8afc76ab2397.PNG)

### Server Setup Information:

- Version of Rocket.Chat Server: 2.17.7
- Operating System: Ubuntu 18.04
- Deployment Method: 
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

- Desktop App or Browser Version:
- Operating System: Windows 7

**Comment by ggazzo** [comment] 2020-05-12 05:00
can you open directory page or not? those pages you mentioned were written in react and are loaded by demand... do you have any error on console? thanks

**Comment by ggazzo** [comment] 2020-05-12 05:02
btw this is you desktop client version your server version is something around 3.1~3.2
> Version of Rocket.Chat Server: 2.17.7

**Comment by ostapski** [comment] 2020-05-12 07:03
@ggazzo 
issue is not persistent
but once it will happen - it stays like that - after rebooting the application - all seems to work again until next time

what I've noticed is that whole application might actually lock-up like that when switching between different sections too quickly not only admin section but the directory as well (that globe thingy)

last time it happened - i could not view the log same as many other sections - so ..no idea if there were any errors
server version is indeed 3.2.1 (just downloaded it couple of days ago)

**Comment by ggazzo** [comment] 2020-05-12 16:08
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/17546

**Closed by ggazzo** 2020-05-12 16:08 UTC
Labels: stat: need more info
