### ISSUE TITLE
user should have the ability to invite 

### ISSUE THREAD

**Issue by amitmeyraz** [RocketChat/Rocket.Chat#2627] opened 2016-03-24 07:00 UTC
Your Rocket.Chat version: (23)
hi,
i think that a user need to have a permission to invite a potential users that are not in the system.
its an important thing for the community.
maybe there is such a possibility, but i didnt find it.

**Comment by engelgabriel** [comment] 2016-03-25 00:56
Is this duplicate of #2181 ?

**Closed by engelgabriel** 2016-03-25 00:56 UTC
Labels: type: new feature
