### ISSUE TITLE
Add option to change user avatar (administration > Users > Edit)

### ISSUE THREAD

**Issue by thibaultmeyer** [RocketChat/Rocket.Chat#12312] opened 2018-10-11 06:20 UTC
**Is your feature request related to a problem? Please describe.**
It could be nice to have feature to edit user profile picture from the administration area (Admin > Users > xxxx xxxx > Edit). In corporate environment this is something handled by sysadmin, not by user itself (to avoid bad picture or not legal / accepted picture)

**Describe the solution you'd like**
When we edit an user (email, fullname), add a another field to upload an image.

**Describe alternatives you've considered**
Using the API, but not easy in our enterprise and the API is bugged, we can't edit picture of another user... In all case, only the picture of the API caller (current session) is modified

**Comment by reetp** [comment] 2018-10-23 14:50
@rocket-cat label add "Feature: Request"

**Comment by reetp** [comment] 2018-10-23 14:51
@rocket-cat label add enhancement

**Comment by knrt10** [comment] 2019-03-24 07:36
On it, would like to add this feature

**Comment by engelgabriel** [comment] 2019-04-06 06:58
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/8485

**Closed by engelgabriel** 2019-04-06 06:58 UTC
Labels: Feature: Planned, enhancement
