### ISSUE TITLE
The page admin/rooms does not find UTF-8 room(channel) name

### ISSUE THREAD

**Issue by IgorOhrimenko** [RocketChat/Rocket.Chat#26743] opened 2022-08-30 15:01 UTC
### Description:

The rocketchat can create channels with UTF-8 characters, but admin interface cannot find them.
The channel with latin characters find well: http://localhost:3000/api/v1/rooms.adminRooms?count=25&filter=general&sort=%7B%22name%22%3A1%7D&types[]=d&types[]=p&types[]=c&types[]=teams
But non-latin does not find: http://localhost:3000/api/v1/rooms.adminRooms?count=25&filter=%CE%95%CE%BB%CE%BB%CE%B7%CE%BD%CE%B9%CE%BA%CE%AC&sort=%7B%22name%22%3A1%7D&types[]=d&types[]=p&types[]=c&types[]=teams

### Steps to reproduce:

1. http://localhost:3000/admin/settings/Layout -> User Interface -> Allow Special Characters in Room Names -> [Save changes]
2. http://localhost:3000/home -> Create Channel -> Ελληνικά -> [Save]
3. http://localhost:3000/admin/rooms -> Search Rooms -> Ελληνικά -> find nothing

### Expected behavior:

Found a room with non-latin characters.

### Actual behavior:

https://user-images.githubusercontent.com/24807060/187470681-6f1219e8-7071-44b6-be3e-e96cb3fc0d17.mp4

### Server Setup Information:

- Version of Rocket.Chat Server: 5.0.5
- Operating System: ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 14.19.3 - x64
- MongoDB Version: 5.0.11

### Client Setup Information

- Desktop App or Browser Version: app 3.8.8, firefox 103
- Operating System: ubuntu 22.04

**Comment by ankar84** [comment] 2022-08-31 04:33
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/19344

**Closed** 2022-08-31 16:46 UTC
