### ISSUE TITLE
V7.1.0 Breaks RocketChat.js.SDK

### ISSUE THREAD

**Issue by mathematisse** [RocketChat/Rocket.Chat#34131] opened 2024-12-06 10:14 UTC
Here's the link to the issue present on the repo of the sdk : https://github.com/RocketChat/Rocket.Chat.js.SDK/issues/169

That issue sums up perfectly the problem, so check it out quickly !

Looking at development activity here compared to the sdk, it might be more relevant to fix that issue here instead of there, by updating the validation method for the field "bot" in https://developer.rocket.chat/v1-api/apidocs/message to match what is done on the sdk with the integration id.

**Comment by reetp** [comment] 2024-12-06 12:59
This is effectively a duplicate of the referenced bug.

You shoudl follow up there and let the developers work out what is best.

Closing as duplicate unless they want to re-open it here.

**Closed by reetp** 2024-12-06 12:59 UTC
Labels: duplicate
