### ISSUE TITLE
email notifications on DM even when disabled

### ISSUE THREAD

**Issue by sinteur** [RocketChat/Rocket.Chat#9112] opened 2017-12-13 20:10 UTC
I had a complaint from a user who told me email notifications for direct mentions were being sent despite it being disabled in profile.  I checked mongo, and here's what's in the database:

{ "_id" : "...", <snip> 
"emails" : [ { "address" : "REDACTED", "verified" : true } ], 
 "settings" : { "preferences" : { <snip> "emailNotificationMode" : "disabled",  <snip> }, 
 <snip> }

Looks like something is ignoring that preference.

**Comment by TwizzyDizzy** [comment] 2017-12-15 16:17
Hi @sinteur,

This might a duplicate of #8568

Also: please be kind and adhere to the issue template ([the text you removed when opening this bug](https://github.com/RocketChat/Rocket.Chat/issues/new)) in order to help friendly community members to help you more effectively. :)

**Comment by karlprieb** [comment] 2017-12-27 17:56
Hey @sinteur witch Rocket.Chat version are you using? I can't reproduce this error on `develop` branch.

**Comment by sinteur** [comment] 2017-12-27 18:02
It's been happening since early .56 versions, and still happens on 0.59.6. Note that it's not happening with ALL users. I'm not ruling out a database corruption of some sort, so if there's specific queries you'd like to see the results of let me know

**Comment by gabrielloberg** [comment] 2018-03-16 11:00
Still an issue on 0.62.1

**Comment by DmitryApollonov** [comment] 2018-04-02 15:36
Still an issue on 0.62.2

**Comment by gdelavald** [comment] 2018-04-19 13:06
This one seems very tricky to reproduce.
@DmitryApollonov @gabrielloberg @mddvul22 @sinteur any other details that could help us tracking down the issue?
User preference and room settings in which they were mentioned that triggered the email would help a lot, please report here if you have that information. Thanks!

**Comment by sinteur** [comment] 2018-05-23 07:57
I'm on 0.64.1 at the moment, I'll upgrade soon. I'll keep an eye out for you

**Comment by ggazzo** [comment] 2018-05-23 16:35
thanks :)

**Comment by sinteur** [comment] 2018-06-08 06:54
(runningn 0.65.1 now)

**Comment by ggazzo** [comment] 2018-06-10 04:07
we are facing some problems with notifications in general (fixed here #11024), but just for emails ... we will test again... :)

**Comment by mddvul22** [comment] 2018-07-12 15:45
We are currently running version 0.65.1.  I have users who have disabled offline notifications.  (Looking in the mongo database, I see the following for their account:

"emailNotificationMode" : "nothing"

Yet, they are getting email notifications.  But this doesn't happen for every user.  If I disable email notifications for my own account, the setting works.  So, it is only happening to some of our users.

**Comment by gabriellsh** [comment] 2020-02-06 16:43
Tested 3.0.0-develop, seems fixed. In any case please reopen this issue.

**Closed by gabriellsh** 2020-02-06 16:43 UTC
Labels: subj: ui/ux, type: bug
