### ISSUE TITLE
emoji size only 50% when enabling markdown "marked" in message

### ISSUE THREAD

**Issue by himpierre** [RocketChat/Rocket.Chat#13352] opened 2019-02-05 08:47 UTC
### Description:

Hi  Guys.

When markdown down "marked" is enabled in messages emojis are only around half the size as it would be normaly.

### Steps to reproduce:

1. Enable Markdown "Marked" in Messages
2. Enter :thumbsup: in a channel
3. Emojis is only half the size it is withoud Markdown enabled

### Expected behavior:

Emoji is the same size.

### Actual behavior:

Emoji is only half the size.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.1
- Operating System: Linux
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: No
- NodeJS Version: 8.11.4
- MongoDB Version: 3.6

**Comment by Crocmagnon** [comment] 2020-11-06 08:32
Duplicate of #11637 ?

**Closed** 2021-09-17 22:07 UTC
Labels: feat: message, subj: message rendering
