### ISSUE TITLE
Emoji One upgrade to v2.2.6

### ISSUE THREAD

**Issue by xasx** [RocketChat/Rocket.Chat#3809] opened 2016-07-19 06:16 UTC
Emoji One has recently received another update.
https://github.com/Ranks/emojione/releases

> This release includes the addition of the Gay Pride Flag (1f3f3-1f308) to the artwork, as well as the removal of asterisk, pound sign, and digit (0-9) replacement which was causing unexpected results.

Please add support for the new ones.

Your Rocket.Chat version: 0.35.0

**Comment by xasx** [comment] 2016-07-19 06:20
Instructions can be found here https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-emojione/README.md

However, I don't know whether it is also necessary to update the respective dependency.

**Comment by dwrensha** [comment] 2016-11-16 23:47
I think this can be closed. https://github.com/RocketChat/Rocket.Chat/commit/b2afdb3af21ebecf9238896dd455fb7c37b947c6 updated to emojione 2.2.6

**Comment by xasx** [comment] 2016-11-18 09:10
Well, I don't think that putting the new version alone is enough.

IIRC there was something to be done with the auto-completion/suggestion system.

**Comment by sampaiodiego** [comment] 2018-01-05 15:14
I'll close this since the issue is to upgrade it.

**Closed by sampaiodiego** 2018-01-05 15:14 UTC
Labels: feat: message, type: improvement
