### ISSUE TITLE
How to delete multi messages in a room or clear all message in a room?

### ISSUE THREAD

**Issue by nth4** [RocketChat/Rocket.Chat#6000] opened 2017-02-13 10:34 UTC
Please guide me how to delete multi message and clear all message in a room (chanell, direct message).
Thanks!
-------------------------------------
Rocket.Chat Version: 0.51.0
Running Instances: 1
DB Replicaset OpLog: 1
Node Version: v4.6.2

**Comment by Nemra1** [comment] 2017-02-13 14:03
u can only clear one by one select all not avaible

**Comment by engelgabriel** [comment] 2017-02-13 16:24
You can delete them directly form the DB if you have access to it.

**Comment by nth4** [comment] 2017-02-14 01:52
@engelgabriel I use on Rocket.Chat cloud (https://vinhlong.rocket.chat). How do I can access to Database.
Thank you so much.

**Comment by ChrisKendallVA** [comment] 2017-04-16 00:08
I would very much like to see this feature implemented! we have hundreds of notifications per day to an observance channel and its a pain to delete them all one by one...

**Comment by cs-1** [comment] 2017-05-09 06:24
I second this, this feature is absolutely essential for us. We're currently deploying Rocket.Chat in our university environment and it's gaining momentum. Having this feature would greatly support the deployment.

**Comment by bbrauns** [comment] 2017-05-09 11:38
We used the rest api for this purpose: https://rocket.chat/docs/developer-guides/rest-api/channels/cleanhistory

**Comment by cs-1** [comment] 2017-05-09 11:43
Thanks for the link! However, what I meant was that this feature should also be available to moderators of private channels and administrators and members of private conversations from within the UI. Sorry, I should've phrased that more clearly in my earlier post.

**Comment by MartinSchoeler** [comment] 2017-07-21 18:22
Duplicate of #1861

**Closed by MartinSchoeler** 2017-07-21 18:22 UTC
Labels: feat: message, type: support

**Comment by poka-IT** [comment] 2018-12-19 03:30
> We used the rest api for this purpose: https://rocket.chat/docs/developer-guides/rest-api/channels/cleanhistory

New like for this doc: https://rocket.chat/docs/developer-guides/rest-api/rooms/cleanhistory/

**Comment by chimsue245** [comment] 2019-09-04 04:51
> You can delete them directly form the DB if you have access to it.

hi sir what is the name of the table for direct message ?

**Comment by asarubbo** [comment] 2024-07-06 06:27
> You can delete them directly form the DB if you have access to it.

Hello, would you mind to share the mongodb query to do that?

I would like to delete all messages in a room called #room from a nickname that contains a string or a message content that contains a string. Thanks
