### ISSUE TITLE
Off-the-Record Conversation always results in a timeout

### ISSUE THREAD

**Issue by rmjstn** [RocketChat/Rocket.Chat#20074] opened 2021-01-06 11:27 UTC
### Description:

Off-the-Record conversation always results in a timeout

### Steps to reproduce:

When I start an Off-the-Record conversation, I've got a Timeout error.

### Expected behavior:

Starting OTR conversation

### Actual behavior:

![image](https://user-images.githubusercontent.com/24813225/103763126-af46f680-5019-11eb-925e-ed5bebd4c163.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 3.10.0
- Operating System: Linux
- Deployment Method: Docker image
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: 12.18.4
- MongoDB Version: 4.0.4

### Client Setup Information

- Desktop App : 3.0.7 or 3.1.1
- Operating System: Windows

### Relevant logs:

While using Chrome browser there're no errors in the console.

Thanks,

Rémy

**Comment by alcodevops** [comment] 2021-01-12 07:25
I got the same problem.
On version 3.9.1 it worked, and after updating to 3.10.0, OTP stopped working.
It doesn't work for version 3.10.0; 3.10.1; 3.10.2; 3.10.3 either.
A clean install does not solve this problem.
I am using nginx-proxy configured according to [Configuring SSL Reverse Proxy](https://docs.rocket.chat/installation/manual-installation/configuring-ssl-reverse-proxy).

**Comment by pjsft** [comment] 2021-01-18 11:15
We also. 3.10.4.
Overall, version 3.10. * introduced a lot of bugs.

**Comment by chaperonRose** [comment] 2021-01-18 16:15
Same problem in 3.10.4
For the user who asks for OTR, the process loops and fire timeout messages regularly. To stop it, the only way seems to refresh the page.
For the other user, nothing happens.

**Comment by bbrauns** [comment] 2021-01-20 13:21
Same here with `3.10.3`; The other user gets no request and the whole process results in a timeout.

**Comment by fcoppolani** [comment] 2021-01-21 13:29
Same here, any idea for a workaround ?

**Comment by pjsft** [comment] 2021-01-21 13:32
I think we have to wait for the update.

**Comment by rainbob5** [comment] 2021-01-26 10:43
Same here, 3.10.4 on docker with apache reverse proxy

**Comment by gcommit** [comment] 2021-01-27 10:44
Same here ...

**Comment by elektro-wolle** [comment] 2021-01-29 19:06
Same here, issue started to occur on 3.10.1 and is still (3.10.5) not working. Installation on docker with ha-proxy as reverse-proxy.

On requesting OTR, the notification is sent to the receiving party, but the other user is not notified.
```
0: "{"msg":"method","method":"stream-notify-user","params":["bv_redacted_x/otr","handshake",{"roomId":"xxx","userId":"X_redacted_c","publicKey":"{\"crv\":\"P-256\",\"ext\":true,\"key_ops\":[],\"kty\":\"EC\",\"x\":\"qzigi4_redacted_MEbjI\",\"y\":\"Um_redacted_1A\"}"}],"id":"23"}"
```

Maybe, the following log-message on the console is related (same userId):
```
29.1.2021 19:59:36(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 X_redacted_c listeners added to [Stream]. Use emitter.setMaxListeners() to increase limit
```

**Comment by didierm** [comment] 2021-01-30 10:22
Confirmed with 3.10.x and latest 3.10.5.

Nothing special in the logs (level = debug) : 
```
Jan 30 11:16:10 cp0579 rocketchat[1232529]: Meteor ➔ method loadHistory -> userId: bFeDuMqYSqTKKWmsi, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7",{},50,{}]
Jan 30 11:16:10 cp0579 rocketchat[1232529]: Meteor ➔ method canAccessRoom -> userId: bFeDuMqYSqTKKWmsi, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7","bFeDuMqYSqTKKWmsi"]
Jan 30 11:16:10 cp0579 rocketchat[1232529]: API ➔ debug GET: /api/apps/externalComponents
Jan 30 11:16:10 cp0579 rocketchat[1232529]: API ➔ debug Success { statusCode: 200, body: { externalComponents: [], success: true } }
Jan 30 11:16:10 cp0579 rocketchat[1232529]: Meteor ➔ method getRoomRoles -> userId: bFeDuMqYSqTKKWmsi, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7"]
Jan 30 11:16:11 cp0579 rocketchat[1232529]: Meteor ➔ method readMessages -> userId: bFeDuMqYSqTKKWmsi, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7"]
Jan 30 11:16:12 cp0579 rocketchat[1232529]: Meteor ➔ method readMessages -> userId: bFeDuMqYSqTKKWmsi, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7"]
Jan 30 11:16:20 cp0579 rocketchat[1232529]: Meteor ➔ method rooms/get -> userId: ssfT5ChKuyeNuqe9q, arguments: [{}]
Jan 30 11:16:24 cp0579 rocketchat[1232529]: Meteor ➔ method setUserStatus -> userId: cqrMxDRme3ZJPhyv7, arguments: ["online",{}]
Jan 30 11:16:24 cp0579 rocketchat[1232529]: Meteor ➔ method UserPresence:setDefaultStatus -> userId: cqrMxDRme3ZJPhyv7, arguments: ["online"]
Jan 30 11:16:34 cp0579 rocketchat[1232529]: Meteor ➔ method readMessages -> userId: bFeDuMqYSqTKKWmsi, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7"]
Jan 30 11:16:34 cp0579 rocketchat[1232529]: Meteor ➔ method deleteOldOTRMessages -> userId: bFeDuMqYSqTKKWmsi, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7"]
Jan 30 11:16:41 cp0579 rocketchat[1232529]: Meteor ➔ method loadHistory -> userId: cqrMxDRme3ZJPhyv7, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7",{},50,{}]
Jan 30 11:16:41 cp0579 rocketchat[1232529]: Meteor ➔ method canAccessRoom -> userId: cqrMxDRme3ZJPhyv7, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7","cqrMxDRme3ZJPhyv7"]
Jan 30 11:16:42 cp0579 rocketchat[1232529]: API ➔ debug GET: /api/apps/externalComponents
Jan 30 11:16:42 cp0579 rocketchat[1232529]: API ➔ debug Success { statusCode: 200, body: { externalComponents: [], success: true } }
Jan 30 11:16:42 cp0579 rocketchat[1232529]: Meteor ➔ method getRoomRoles -> userId: cqrMxDRme3ZJPhyv7, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7"]
Jan 30 11:16:46 cp0579 rocketchat[1232529]: Meteor ➔ method readMessages -> userId: bFeDuMqYSqTKKWmsi, arguments: ["bFeDuMqYSqTKKWmsicqrMxDRme3ZJPhyv7"]
```

**Comment by bkraul** [comment] 2021-02-01 21:07
On 3.12-develop here and the issue persists. Any news on when it will be addressed?

**Comment by danel1** [comment] 2021-02-03 10:09
@ggazzo @gabriellsh @MartinSchoeler How can you ignore such critical bugs without even giving any feedback? The 3.10.x release quality is extremly poor and instead of trying to fix these critical bugs and maybe to a bugfix release you push 3.11.x with again lots of bugs? I guess you should seriously think about your release strategy.....

**Comment by ggazzo** [comment] 2021-02-03 12:45
@danel1 last month we have merged +120 relevant PR's and handled over 200 new issues (all issues are important until we read, understand the situation, evaluate and maybe solve it).

I believe that everyone wants your problem solved and your problem is considered the most important. but since rockechat has many different features and uses, perhaps some will never have the same perception as others.

You are right and I am totally against our release process, which favors innovation (or new features) over stability and quality.

but, sentences like `extremly poor` or `again lots of bugs` will not help. if you have found/identified some bug from this huge list of bugs, please check if there is already some opened issue about (believe we spend a LOT of time with duplicated issues), if not, fell free to create and provide us all concerns you have.

And always if you fell comfortable enough, you can always open a pr fixing the problem.


thank you all for your contributions, time and reports. we will resolve them as soon as possible.

**Comment by bkraul** [comment] 2021-02-03 13:03
@ggazo While I think the mic drop moment was pretty neat, and pretty much all of us in the community agree with what you are saying, and are grateful for what you guys do, @danel1 kind of just proved a point. Regardless of whether the current release process is effective or not, what would help tremendously is better feedback from the development team. For a while I saw a more effective triage system, that would have at least have the bugs acknowledged, triaged and tagged in relation to their severity. Just my thoughts.

**Comment by didierm** [comment] 2021-02-03 13:22
@ggazzo Thank you for assigning some of your precious time to answer.

Not wanting to hijack this issue, but nevertheless : 
1. you are fully entitled to prioritize whatever you wish ;
2. bugs are to be expected, especially for new features ;
3. but : _regressions_ (and particularly high-impact ones like this issue and e.g. #19810 ) are detrimental to the trust in the product.

These issues are not exactly pixel mis-alignments of some icons, but core features suddenly misbehaving.

(that said, we are currently not paying for a commercial license, but happy to become sponsors RSN (due to a needed increase in push notifications :) )

**Comment by benedikt-wegmann** [comment] 2021-02-03 13:56
@ggazzo While the tone of @danel1 critic seems harsh it also speaks of the frustration regarding the mentioned issue and the quality of especially the 3.10.x release.

Specifically with this issue I find it concerning that it got past automated or manual testing, as it is a prominent user-orientated feature. There are numerous other features as well, such as not being able to open the user profile by clicking on a name or avatar of a message. I consider this basic UI functionality, yet it broke unnoticed and slipped into a release.

Regarding the release quality and support I share @danel1 frustration. My organization is a licensed customer of Rocket.Chat (https://rocket.chat/blog/customer-stories/how-german-universities-are-improving-their-communication-through-rocket-chat/), yet we haven't had a single, technical reply to our support requests regarding specific issues, some of which are also mentioned here in the issue tracker. By monetarily supporting the project we hope to help improve its development, but the amount of bugs in release versions is concerning.

**Comment by ggazzo** [comment] 2021-02-03 14:28
sure @benedikt-wegmann I'm totally with you both
> it also speaks of the frustration

your case is kinda different, we have a different commitment ( a commercial one). and the issue should come to us in a different way (usually a smaller / faster way)

**Comment by C1ean** [comment] 2021-02-04 18:31
3.11 issue still reproduced..

**Closed** 2021-02-08 14:32 UTC
Labels: stat: triaged

**Comment by joseluisq** [comment] 2021-02-15 14:29
The bug is not fixed on 3.11.0

**Comment by yash-rajpal** [comment] 2021-02-15 14:30
This was fixed for me, I tested it on 3.11.0
What problems are you facing @joseluisq ? :)

**Comment by joseluisq** [comment] 2021-02-15 14:42
> This was fixed for me, I tested it on 3.11.0
> What problems are you facing @joseluisq ? :)

![image](https://user-images.githubusercontent.com/1700322/107960080-76008f80-6fa4-11eb-8f9e-b16ff901b3d7.png)

**Comment by joseluisq** [comment] 2021-02-15 14:45
But the doc says that it is a beta feature. Is that feature WIP ?
https://docs.rocket.chat/guides/user-guides/messaging/off-the-record-otr-messaging-guide

**Comment by yash-rajpal** [comment] 2021-02-15 14:45
when you initiate a OTR converstation, there is a 0 seconds window where user on other side has to accept OTR. 
If the OTR request is not accepted within 10 seconds, we get this `Timeout` popup.
Are you sure the user on other end is accepting the request?

**Comment by joseluisq** [comment] 2021-02-15 14:52
My partner says it's not receiving any notification to accept.
![Bildschirmfoto 2021-02-15 um 15 49 42](https://user-images.githubusercontent.com/1700322/107961094-bb718c80-6fa5-11eb-8451-53fdf158b2f3.png)

Do I need to set up something to make this work ?

**Comment by joseluisq** [comment] 2021-02-15 14:55
Ok, I have tested with two users one in browser and the other via the desktop App and the same issue.

**Comment by joseluisq** [comment] 2021-02-15 14:57
Here the server specs (of course the OTR is enabled):

```
Version: 3.11.0
Apps Engine Version: 1.22.1
Node Version: v12.18.4
Database Migration: 215 (February 1, 2021 9:00 AM
MongoDB: 3.4.24 / mmapv1 (oplog Enabled)
```

**Comment by yash-rajpal** [comment] 2021-02-15 15:01
I don't think you have to set something up before using OTR.
I am attaching a Demo GIF to verify the steps and ensure that it is working for me.
![OTR DEMO](https://user-images.githubusercontent.com/58601732/107962155-a9571480-6fcc-11eb-8a21-8daf978e2955.gif)

Currently I tested on latest develop branch, but I have also tested on 3.11.0 and I remember it working for me.

**Comment by joseluisq** [comment] 2021-02-15 15:07
One detail it's the we come from a major upgrade (latest v2.x to v3.11) but I don't think that has something to do with this.
Anyway we will try to upgrade to latest 3.11.x when we have a chance if that helps.

**Comment by yash-rajpal** [comment] 2021-02-15 15:10
@joseluisq I think that can help. Goodluck. :)

**Comment by mddvul22** [comment] 2021-02-15 15:15
I don't know how this could possibly be fixed in 3.11.0.  The code to fix this issue wasn't merged until 7 days ago.  3.11.0 came out 15 days ago.

**Comment by yash-rajpal** [comment] 2021-02-15 15:17
@mddvul22 Yeah you are right, I was mistaken.

**Comment by joseluisq** [comment] 2021-02-15 15:19
Ok, I also don't see any mention about OTR on last two releases.

**Comment by yash-rajpal** [comment] 2021-02-15 15:26
@joseluisq You are right, I can't find OTR in any of the releases. I think this feature has yet to be released. Sorry for all the confusion.

**Comment by Bengrunt** [comment] 2021-02-15 15:35
I confirm, still not fixed in v3.11.1 ;)

**Comment by sor3si** [comment] 2021-02-16 06:46
@yash-rajpal OTR is not a "new" feature for that. I's been part of Rocketchat for years, been in the 0.X versions already. Here Developers use it to exchange Passwords, Keys or occasionally curses. What would be needed to take it out of beta into production? Or is there any thought of actually removing it?

**Comment by yash-rajpal** [comment] 2021-02-16 06:50
@sor3si I meant the PR which fixes OTR is not merged yet, would be released later.

**Comment by dougfabris** [comment] 2021-02-23 20:42
> @sor3si I meant the PR which fixes OTR is not merged yet, would be released later.

Will be present in the next release [3.12.0-rc0](https://github.com/RocketChat/Rocket.Chat/releases/tag/3.12.0-rc.0)

**Comment by rmjstn** [comment] 2021-02-28 16:50
Why this correction is not reported in branches 3.11 and 3.12?

**Comment by pjsft** [comment] 2021-03-01 08:45
I updated my test instance. The OTR issue is still not fixed in 3.12? Users still do not receive an OTR notification, which causes the Timedout to end.

**Comment by Bengrunt** [comment] 2021-03-01 08:54
> 
> 
> I updated my test instance. The OTR issue is still not fixed in 3.12? Users still do not receive an OTR notification due to the error "Timedout".

It worked a few days ago on rc1.

**Comment by Bengrunt** [comment] 2021-03-01 09:13
Just confirmed on our own test instance: it works with v3.12 ✔️

**Comment by rmjstn** [comment] 2021-03-01 09:36
I confirm it works with 3.12

**Comment by joseluisq** [comment] 2021-03-02 08:12
It works on latest v3.12.0

**Comment by vplb** [comment] 2021-05-04 20:52
We have encountered this in 3.13.3. 
Upgraded to 3.14.0; it occurred during some tests, and in others it worked.

**Comment by czqrny** [comment] 2021-05-24 04:50
Still occures in 3.14.0, 3.14.1 and 3.15.0-rc.1 versions

**Comment by dougfabris** [comment] 2021-05-24 13:14
@vplb and @czqrny We are working on that! Please follow news on this issue: #21873
