### ISSUE TITLE
Channel Delete Button Missing

### ISSUE THREAD

**Issue by bnornholm** [RocketChat/Rocket.Chat#8881] opened 2017-11-16 15:51 UTC
### Description:

Channel delete button is missing.  Using my Admin profile, I am not able to delete a channel a channel, only able to change the state to archive.

### Server Setup Information:

* Version of Rocket.Chat Server: 59.3
* Operating System: Ubuntu 17.10
* Deployment Method(snap/docker/tar/etc): Snap
* Number of Running Instances: 1
* DB Replicaset Oplog: enabled
* Node Version: 4.8.4

### Steps to Reproduce:

1. 
2. 
3. 

### Relevant logs:

![image](https://user-images.githubusercontent.com/15819233/32900616-7d361b60-cab3-11e7-9e6a-aed46fd92e1b.png)

**Comment by wargamesqcf** [comment] 2017-11-16 22:14
I have also found this to be an issue.

**Comment by DRON4eg** [comment] 2017-11-17 06:16
Sorry for the directness, but you need to learn how to use the search.
Similar questions have already been created.

https://github.com/RocketChat/Rocket.Chat/issues/8562

A quick fix is adding this to layout->customcss:
.flex-tab .channel-settings .button {visibility: visible}

**Comment by MartinSchoeler** [comment] 2017-11-17 11:11
duplicate of #8562

**Closed by MartinSchoeler** 2017-11-17 11:11 UTC
