### ISSUE TITLE
Link are not clickable if local environment

### ISSUE THREAD

**Issue by wagigi** [RocketChat/Rocket.Chat#28427] opened 2023-03-15 11:00 UTC
### Description:

When you send a link to a local server, the link is not clickable.

It appears when we updated to 6.0.0

Have a nice day :)

### Steps to reproduce:

1. Go to a chat with someone
2. Send a link to a local server (for example http://gitlab.local ) 

### Expected behavior:

The link is clickable

### Actual behavior:

The link is not clickable

### Server Setup Information:

- Version of Rocket.Chat Server: 6.0.0
- Operating System: Debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v14.21.2
- MongoDB Version: 4.4.19

### Client Setup Information

- Desktop App or Browser Version: 3.8.16
- Operating System: Win11 - Win 10

### Additional contexts

No problem when the link is public 

![image](https://user-images.githubusercontent.com/7090517/225288711-08c59fc3-88ad-4a8e-bd28-e8b2af5db64e.png)

**Comment by MAYANKpandey14** [comment] 2023-03-15 11:11
Hey, can you share a video showing how the issue is reacting.

**Comment by AdityaSingh-02** [comment] 2023-03-15 11:49
Hey @wagigi i believe that your url is invalid.. so how can you expect to work as link and redirect you to some other route ... Try pasting Rocket.chat or https://gitlab.com/users/sign_in

**Comment by wagigi** [comment] 2023-03-15 12:38
Hello @AdityaSingh-02 :)

The url is valid https://www.w3.org/TR/2011/WD-html5-20110525/urls.html 

It is a local environment. So the URL only work in the local environment. Of course, http://gitlab.local will not work on your environment. 

We have a local gitlab for the dev team and they need to send urls between them.

**Comment by wagigi** [comment] 2023-03-15 12:48
@MAYANKpandey14 

Here is a video

https://user-images.githubusercontent.com/7090517/225313322-66320252-a8ef-422f-8172-f61b6020d9fe.mp4

**Comment by IllTamer** [comment] 2023-03-16 00:19
Hi @wagigi , can you assign this bug to me ? I want to try to fix this bug and it will be done in two days 😉

**Closed** 2023-03-31 18:52 UTC
Labels: type: bug

**Comment by Celia149** [comment] 2023-05-24 15:23
Hello,
Would it be possible to allow the same functionality for local urls using server hostname or ip?
For instance https://10.154.97.5 or https://myserver
Have a nice day!

**Comment by JLammering** [comment] 2024-02-13 16:41
> Hello, Would it be possible to allow the same functionality for local urls using server hostname or ip? For instance https://10.154.97.5 or https://myserver Have a nice day!

It is possible. Just add your IP to the whitelist under _workspace -> settings -> Message_.
