### ISSUE TITLE
message context menu stops working after starring a message

### ISSUE THREAD

**Issue by Kyogre** [RocketChat/Rocket.Chat#25132] opened 2022-04-09 14:50 UTC
### Description:

Sometimes (not always) if user starred message the star mark won't appear near the message. Thus, if that happens, context menu button stops working.
As I said, that problem will not reproduced on every try, but it still easy to catch, and the indicator of the success will be not appearing of the star mark, despite you marked the message just now. You will encounter that bug after some tries of page reload.

### Steps to reproduce:

see the video

### Expected behavior:

Context menu works and star mark is here.

### Actual behavior:

Video demo: https://user-images.githubusercontent.com/2260980/162579593-b508a6f3-32f7-4369-88ec-0f607c8891c3.mp4

### Server Setup Information:

catched on https://open.rocket.chat

### Client Setup Information

\-

### Additional context

\-

### Relevant logs:

\-

**Comment by Kyogre** [comment] 2022-04-09 15:06
maybe related to https://github.com/RocketChat/Rocket.Chat/issues/24066

**Comment by MartinSchoeler** [comment] 2024-07-26 19:16
I could not reproduce this in the latest version, could you check it out if still happens? If so please create a new issue with updated details, closing this for now.

Thanks!

**Closed by MartinSchoeler** 2024-07-26 19:16 UTC
