### ISSUE TITLE
Allow unicode in Channel-Names

### ISSUE THREAD

**Issue by exhuma** [RocketChat/Rocket.Chat#10669] opened 2018-05-04 07:23 UTC
I realised today that I am not able to enter umlauts in channel names.

Would be cool if that was possible.

**Comment by iMaciaveller** [comment] 2018-05-04 08:51
im add parameters UTF-8_Names_Validation: [0-9а-яА-Яa-zA-Z-_.]+

**Comment by TwizzyDizzy** [comment] 2018-05-08 11:36
@rocket-cat close

It is possible, if you enable "Allow Special Characters in room names" (I just tested it with the name below). The problem is, that the display of the channel name is not coherent across every place it is displayed. If you disagree, please let me know exactly where I'm wrong with my assumptions.

E.g. I used "а-яА-Яaäöü" as channel name, but it is shown as "aaou" in the sidebar and in room info.

There already is an issue for that: #9738.

That's why I'm closing the issue at hand.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-05-08 11:37 UTC

**Comment by alokraj68** [comment] 2018-07-17 10:31
Please mention where this option is. that will help others who come here.

**Comment by BabyCthulhu** [comment] 2019-03-18 08:39
> Please mention where this option is. that will help others who come here.

Administration > Layout > User Interface > Allow Special Characters in Room Names
