### ISSUE TITLE
Rocket.Chat message notifications should not be case sensitive

### ISSUE THREAD

**Issue by xurizaemon** [RocketChat/Rocket.Chat#15879] opened 2019-11-28 20:34 UTC
### Description:

If a user is mentioned but the nick is incorrectly capitalised, then the notification is ignored. This is unexpected behaviour, particularly visible if the user has capitalised their own username at `/account/profile`.

### Steps to reproduce:

1. Mention a user with correct capitalisation; notification will be sent.
2. Mention a user and vary the capitalisation; no notification will be sent.

Reproduced just now on https://open.rocket.chat/ - 2.3.0-rc0

### Expected behavior:

Notify users regardless of the capitalisation used in their username.

Usernames are not case sensitive (I can't register "Xurizaemon" *and* "xurizaemon") therefore notifications should not be case sensitive.

### Actual behavior:

![rocketchat-notify-capitalisation](https://user-images.githubusercontent.com/105608/69830647-a6b6b500-128a-11ea-80e5-233d24ec483c.png)

In the screenshot above, I've typed the username identically each time except for hitting SHIFT while typing the second message. Resulting behaviour should be consistent.

### Server Setup Information:

- Version of Rocket.Chat Server: all, confirmed on https://open.rocket.chat/ today, 2.3.0-rc0
- Operating System: all
- Deployment Method: all
- Number of Running Instances: all
- DB Replicaset Oplog: idk
- NodeJS Version: all
- MongoDB Version: all

### Client Setup Information

- Desktop App or Browser Version: Firefox (but, all)
- Operating System: Linux (but, all)

**Comment by reetp** [comment] 2019-11-29 00:58
Sure there was another issue I have seen on similar but the only thing I could find was this:

https://github.com/RocketChat/Rocket.Chat/issues/1468
https://github.com/RocketChat/Rocket.Chat/issues/10004

Some other stuff on channel names.

**Comment by carpecodeum** [comment] 2019-12-04 12:00
is this issue open?

**Comment by carpecodeum** [comment] 2019-12-05 14:51
hey can i get a confirmation if this issue is still open?

**Comment by xurizaemon** [comment] 2019-12-05 18:39
Hi @carpecodeum, GitHub issue status is shown at top of the issue page, and yes this issue is open as I comment.

**Comment by carpecodeum** [comment] 2019-12-05 21:30
ohh ok thank you! i would like to work on this.

**Comment by carpecodeum** [comment] 2019-12-06 12:29
hey @xurizaemon any inputs would be highly welcome i was thinking of using regex but that would be quite inefficient another option is for the database to store a lower-case version of the username and then we search the collection with this query 
`db.collection.find({"name_lower": thename.toLowerCase()})`

**Comment by xurizaemon** [comment] 2019-12-06 18:26
Would help to see where you propose that change.

I suspect this can be handled in frontend. Under *Actual behaviour* in first comment you can see the browser has highlighted the first mention and not the second. If the list of usernames is already  in browser at this point we may be able to do that matching insensitively with a regex quite easily?

**Comment by carpecodeum** [comment] 2019-12-07 06:33
Yeah thats a good approach. On it!

**Comment by carpecodeum** [comment] 2019-12-08 20:47
hey @xurizaemon from what i have found out there seems to be a problem with the mentionsParser it does not provide a case insensitive search but doing just that does not help i couldnt find where the users get stored in the browser if you could help me on that it would be great!

**Comment by fleaz** [comment] 2020-01-02 14:11
I already reported this bug nearly one year ago. See #13374

**Comment by gabriellsh** [comment] 2020-01-27 12:54
Duplicate of #13374.

**Closed by gabriellsh** 2020-01-27 12:54 UTC
