### ISSUE TITLE
Slow downloads from everywhere

### ISSUE THREAD

**Issue by entrptaher** [RocketChat/Rocket.Chat#11073] opened 2018-06-10 01:15 UTC
I went to rocket.chat/install and clicked download. It downloaded at most 1-2Mbps speed since it's downloading from github linked to s3. 

I've tested from at least 20 different devices for **past few months** and only few managed to download it without problems. I think this is a serious issue since it actually takes a lot of time just to download the desktop version and test it out. 

Here is an image of download progress from a 500Mbps server. As you can see, it's only 136KBps which is unbearable.
![image](https://user-images.githubusercontent.com/8284972/41197390-26326ef0-6c7e-11e8-87df-53ca89850686.png)

I've wrote a post with all required screenshots here https://dev.to/entrptaher/slow-amazon-dataservers-part-2-560h. 

If this is an issue with github, I wonder if rocket.chat can be hosted on somewhere else or not.

**Comment by TwizzyDizzy** [comment] 2018-07-11 19:19
Is it possible, that your tier on Digitalocean is somehow limited? But you said you already tested different locations... it's really weird. From what I gather, we use Cloudfront and any issue YOU might have I would expect anyone else to have in your Amazon region.

I'm afraid though, that this is nothing we can fix (or even reproduce - I also tested from servers in different physical locations, in germany only though), that's why I'm closing this issue.

Mentioning @geekgonecrazy here, just in case I'm missing something profound.

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-07-11 19:19 UTC

**Comment by geekgonecrazy** [comment] 2018-07-11 22:06
yes we use cloudfront as the CDN which caches our s3 bucket.  This should already be regional.  In the past when faced with such limitations, i've used `axel` lets you parallelize and file up your pipe.  If it still won't go fast, then for sure connection bottleneck.  No clue how or why but definitely can't reproduce :(
