### ISSUE TITLE
Server "Not migrating, control is locked."

### ISSUE THREAD

**Issue by lchojnowski** [RocketChat/Rocket.Chat#11361] opened 2018-07-05 19:08 UTC
### Description:

Rocket.Chat server is not starting.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.66.1
- Operating System: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-78-generic x86_64)
- Deployment Method: snap
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Relevant logs:

```
root@chat:~# journalctl -f -u snap.rocketchat-server.rocketchat-server
-- Logs begin at Thu 2018-07-05 18:46:59 UTC. --
Jul 05 19:01:24 chat rocketchat-server.rocketchat-server[3049]: Will load cache for rocketchat_permissions
Jul 05 19:01:24 chat rocketchat-server.rocketchat-server[3049]: 80 records load from rocketchat_permissions
Jul 05 19:01:24 chat rocketchat-server.rocketchat-server[3049]: Will load cache for rocketchat_roles
Jul 05 19:01:24 chat rocketchat-server.rocketchat-server[3049]: 11 records load from rocketchat_roles
Jul 05 19:01:26 chat rocketchat-server.rocketchat-server[3049]: Warning: connect.session() MemoryStore is not
Jul 05 19:01:26 chat rocketchat-server.rocketchat-server[3049]: designed for a production environment, as it will leak
Jul 05 19:01:26 chat rocketchat-server.rocketchat-server[3049]: memory, and will not scale past a single process.
Jul 05 19:01:26 chat rocketchat-server.rocketchat-server[3049]: LocalStore: store created at
Jul 05 19:01:26 chat rocketchat-server.rocketchat-server[3049]: LocalStore: store created at
Jul 05 19:01:26 chat rocketchat-server.rocketchat-server[3049]: LocalStore: store created at
Jul 05 19:01:27 chat rocketchat-server.rocketchat-server[3049]: Setting default file store to GridFS
Jul 05 19:01:31 chat rocketchat-server.rocketchat-server[3049]: Thu, 05 Jul 2018 19:01:31 GMT connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead at npm/node_modules/connect/lib/middleware/bodyParser.js:56:20
Jul 05 19:01:31 chat rocketchat-server.rocketchat-server[3049]: Thu, 05 Jul 2018 19:01:31 GMT connect deprecated limit: Restrict request size at location of read at npm/node_modules/connect/lib/middleware/multipart.js:86:15
Jul 05 19:01:41 chat rocketchat-server.rocketchat-server[3049]: Not migrating, control is locked. Attempt 1/30. Trying again in 10 seconds.
Jul 05 19:01:51 chat rocketchat-server.rocketchat-server[3049]: Not migrating, control is locked. Attempt 2/30. Trying again in 10 seconds.
Jul 05 19:02:01 chat rocketchat-server.rocketchat-server[3049]: Not migrating, control is locked. Attempt 3/30. Trying again in 10 seconds.
Jul 05 19:02:11 chat rocketchat-server.rocketchat-server[3049]: Not migrating, control is locked. Attempt 4/30. Trying again in 10 seconds.
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: {"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Migrating from version 124 -> 129","time":{"$date":1530818080750},"level":"info"}
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: {"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Running up() on version 125","time":{"$date":1530818080754},"level":"info"}
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: +-----------------------------------------------------------------------------------------------------------------+
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                                                                                                 |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                              ERROR! SERVER STOPPED                                              |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                                                                                                 |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                         Your database migration failed:                                         |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |  cannot use the part (settings of settings.preferences.groupByType) to traverse the element ({settings: null})  |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                                                                                                 |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                        Please make sure you are running the latest version and try again.                       |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                 If the problem persists, please contact support.                                |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                                                                                                 |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                         This Rocket.Chat version: 0.66.1                                        |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                         Database locked at version: 124                                         |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                           Database target version: 129                                          |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                                                                                                 |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                 Commit: fb5257f618b22638c6b2ac4c678f76809f5a7d7e                                |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                       Date: Wed Jul 4 15:05:11 2018 -0300                                       |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                                   Branch: HEAD                                                  |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                                   Tag: 0.66.1                                                   |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: |                                                                                                                 |
Jul 05 19:14:40 chat rocketchat-server.rocketchat-server[3222]: +-----------------------------------------------------------------------------------------------------------------+
```

**Comment by andreas-bulling** [comment] 2018-07-05 19:23
Same problem here. Duplicate of #11353

**Comment by novafire99** [comment] 2018-07-05 22:38
I also have the exact same problem.  Same DB version numbers.  Snap updated and shut everything down.  Hopefully there is a fix soon.  Everything I have tried has not worked.

**Comment by rlindabury** [comment] 2018-07-05 22:56
Same here. Is there some work-around?

**Comment by JoeatMJ** [comment] 2018-07-05 23:12
Take a look at #5542.

**Comment by geekgonecrazy** [comment] 2018-07-05 23:22
closing in favor of: https://github.com/RocketChat/Rocket.Chat/issues/11353

**Closed by geekgonecrazy** 2018-07-05 23:22 UTC
