### ISSUE TITLE
[Livechat] livechat errored on agent's chat window

### ISSUE THREAD

**Issue by legendecas** [RocketChat/Rocket.Chat#7143] opened 2017-06-01 13:10 UTC
Rocket.Chat Version: 0.57.0-develop
Running Instances: 1
DB Replicaset OpLog: disabled
Node Version: 4.8.1 - x64

![image](https://cloud.githubusercontent.com/assets/8500303/26680628/c1d96a90-470c-11e7-98d6-b8e858113c6f.png)

when clicked on the live chat list item, the chat window turned blank. And here's the logs in console.

```
Exception from Tracker recompute function: undefined
Error: Syntax error, unrecognized expression: #chat-window-ziUm63f(c3ZBMN@ZWn
    at Function.t.error (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:49:22766)
    at t.tokenize (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:49:28715)
    at t.select (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:49:28980)
    at Function.t [as find] (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:49:11830)
    at ge.fn.init.find (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:49:31286)
    at ge.fn.init (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:49:31783)
    at ge (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:49:7515)
    at Object.attached (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:311:8981)
    at f._DOMRange.t.attach (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:135:4687)
    at Function.t._insert (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:135:3251) undefined
Exception in defer callback: TypeError: Cannot set property 'scrollTop' of null
    at http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:244:28470
    at e.Computation._compute (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:82:2311)
    at new e.Computation (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:82:1265)
    at Object.e.autorun (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:82:4215)
    at http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:244:27269
    at r.EnvironmentVariable.withValue (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:3:7163)
    at http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:3:2921
    at Object.<anonymous> (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:3:7421)
    at e (http://sternenstaub.local/45ca399e81eb3cba94d75e45cd6f713771db232d.js?meteor_js_resource=true:3:2174)
```

**Comment by xasx** [comment] 2017-06-14 07:28
I am seeing the same exception when switching to particular channels.

```
Exception in defer callback: TypeError: Cannot set property 'scrollTop' of null
    at https://host/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:243:28472
    at e.Computation._compute (https://host/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:81:2311)
    at new e.Computation (https://host/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:81:1265)
    at Object.e.autorun (https://host/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:81:4215)
    at https://host/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:243:27269
    at r.EnvironmentVariable.withValue (https://host/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:3:7163)
    at https://host/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:3:2921
    at Object.<anonymous> (https://host/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:3:7421)
    at e (https://host/e6940d150fa5c43bd2f4d4bc9f590f153b23b692.js?meteor_js_resource=true:3:2174)
```

Resulting in the chat room not displayed at all.
Happens in Chrome beta Version 60.0.3112.24 - so might be something to consider when this version goes final.

**Comment by furkanmustafa** [comment] 2017-08-07 15:38
I'm having the same issue since I have upgraded to `0.57.2` (note that I may have jumped some versions when upgrading), this is not just about livechat. It's happening on usual channels and DMs too.

So far I can relate this with the following scenario; I close my browser (when rocket chat tab was open). I open my browser back again and it restores my tabs, rocket.chat is not able to show the last channel I had open. All others work. Switch back to that channel; doesn't work.

Deleting local storage fixes the issue. (But might happen again)

**Comment by xasx** [comment] 2017-08-08 06:57
I have found a slightly different workaround:

Navigate to the base URL of the Rocket.Chat instance after the browser restored (to a blank page),i.e. remove any `channel/…` stuff from the navbar. Then go back to the channel.

**Comment by furkanmustafa** [comment] 2017-08-08 07:09
I can confirm that @xasx 's solution works.

**Comment by sampaiodiego** [comment] 2018-03-28 19:37
are you guys still having this issue?

**Comment by furkanmustafa** [comment] 2018-03-28 23:24
Nope, mine is okay in newer versions.

**Comment by sampaiodiego** [comment] 2018-03-29 02:11
closing then since seems to be fixed.

please let me know if someone still having this.

**Closed by sampaiodiego** 2018-03-29 02:11 UTC
Labels: feat: livechat, type: bug
