### ISSUE TITLE
 ignoring the language settings

### ISSUE THREAD

**Issue by kertiskz** [RocketChat/Rocket.Chat#31802] opened 2024-02-21 04:26 UTC
### Description:
Rocketchat ignores the language settings. By default, I have Russian installed, but when I start the chat, it loads in English. This is fixed if you reboot it ignoring the cache. But the next time you run it, the problem will repeat. This is true for both the web version and the desktop application.

### Steps to reproduce:

1. Start the chat with the Russian language settings.

### Expected behavior:

The chat will start considering the language settings.
<a href="https://ibb.co.com/L9n3X82"><img src="https://i.ibb.co.com/2cgT1yf/2024-02-21-103514.png" alt="2024-02-21-103514" border="0"></a>
### Actual behavior:

The chat ignores the language settings in the profiles and/or general server settings.
<a href="https://ibb.co.com/vjts8Fq"><img src="https://i.ibb.co.com/x74mQkL/2024-02-21-102932.png" alt="2024-02-21-102932" border="0"></a>
### Server Setup Information:

- Version of Rocket.Chat Server:  6.6.1
- Operating System:  synology
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: yes
- NodeJS Version: 14.21.3
- MongoDB Version: 6.0.13

### Client Setup Information

- Desktop App or Browser Version: Edge v121.0.2277.128, chrome v121.0.6167.185, desktop app v3.9.14. 
- Operating System: Win 11, Win 10, Win 7

**Comment by marco-websource** [comment] 2024-02-21 11:03
I can confirm this with RC 6.6.0 and 6.6.1 with Firefox 115.6.0esr. I think we noticed this problem after upgrading from 6.4.0 to 6.6.0.

The web UI stays in English ignoring a different language setting in the global server settings and/or the user profile preferences. When changing the language setting to a different language, the UI switches to the desired language (at least sometimes), but when the page is reloaded it switches back to English (see screen capture).

![Peek 2024-02-21 12-01](https://github.com/RocketChat/Rocket.Chat/assets/13545742/0e46e1ba-4474-4914-8012-db5ffc675b58)

This is a serious issue for non-English users.

**Comment by Deelight-fr** [comment] 2024-02-21 15:54
Same problem here, after an upgrade from 6.5.3 to 6.6.1 (Enterprise).

**Comment by DRKMDMZ** [comment] 2024-02-21 19:49
Same here on 6.6.1

**Comment by JoeLynnTurner1** [comment] 2024-02-22 04:07
Same here on 6.6.1

**Comment by kertiskz** [comment] 2024-03-01 16:28
Relevant for 6.6.2

**Comment by arjunrathod91** [comment] 2024-03-03 06:31
Hey @kertiskz,
Hope you are doing well. My name is Arjun and I am a mern stack developer. I wanted to participate in GSoC. I thought that I can work on this issue. Can you assign this to me?

**Comment by marco-websource** [comment] 2024-03-05 20:58
In addition to the language problem, I also noticed that email notifications stopped working at the same time, i.e. after upgrading from 6.4.0 to 6.6.0. The user email addresses are verified and the SMTP setup works (test mail is sent successfully). Also push notifications work. Therefore I wonder if the issues are related. The reasoning would be that if the language settings are ignored maybe also the notification settings are ignored?

I would like to debug this further, but I'm not sure how. With debug log enabled, I see that Outgoing Webhook and push notifications are triggered when sending a message. But no sign of any email notification activities.

**Comment by SySagar** [comment] 2024-03-10 07:09
I think this is relevant to ealr version specifically 6.6.2 or 6.6.1
With the latest version , the bug is completely fixed. I would suggest to update it to latest version . This will solve your problem.

**Comment by marco-websource** [comment] 2024-03-10 09:54
@SySagar I can't confirm that. We see the language setting issue still in 6.6.3. Can you point us to the PR/commit that should have addressed the issue, so we can verify that?

**Comment by Deelight-fr** [comment] 2024-03-10 17:24
Upgraded to 6.6.3 and the issue is still present.

**Comment by marco-websource** [comment] 2024-03-21 09:17
Unfortunately the issue is still present in 6.6.4. This is a major flaw for non-English speaking communities!

**Comment by Visbhavesh** [comment] 2024-03-22 17:26
I wanted to work in thus issue please allow me to work on this issue.

**Comment by SySagar** [comment] 2024-03-22 18:08
@Visbhavesh sure go ahead.

**Comment by marco-websource** [comment] 2024-03-23 11:32
I have a feeling that the issue might actually be in Meteor. A quick test showed that the issue might be gone in the current development branch (Meteor 2.15). And it seems that the issue was introduced when updating RC from 6.5 to 6.6, which updated Meteor from 2.13.3 to 2.14. So the problem might be in Meteor 2.14 (and hopefully resolved in 2.15).

**Comment by Deelight-fr** [comment] 2024-03-29 20:21
Issue still present in 6.6.6.

**Comment by kertiskz** [comment] 2024-04-17 10:24
Issue still present in 6.7.0

**Comment by Deelight-fr** [comment] 2024-04-17 13:40
Expected to be fixed in 6.8.0 according to support

**Closed** 2024-05-08 13:56 UTC
