### ISSUE TITLE
Fail to install at Local Mcahine

### ISSUE THREAD

**Issue by Wloa** [RocketChat/Rocket.Chat#242] opened 2015-06-28 20:39 UTC
I just clone the current git and got this error.

![error](https://cloud.githubusercontent.com/assets/12832493/8398228/42d88fce-1db4-11e5-8d1c-3747585df203.jpg)

**Comment by rodrigok** [comment] 2015-06-28 22:00
Hi @Wloa,

we are not testing this project in Windows yet.

Do you want to help us to find erros and improve the the support for Windows?

In fact, no one of the core team has Windows installed :)

**Comment by engelgabriel** [comment] 2015-06-28 22:36
@Wloa can you try
```
meteor remove rocketchat:hubot
``` 

and run meteor again

**Comment by Wloa** [comment] 2015-06-28 22:47
@engelgabriel - it works. I will do some testing and report what I found if any.

@rodrigok - I am a newbie but willing to learn. :)

**Comment by engelgabriel** [comment] 2015-06-28 23:13
OK @Wloa so the problem is probably one of the hubot scripts, probably the youtube one, by the msgs on the log. I'll close it in this case.

**Closed by engelgabriel** 2015-06-28 23:13 UTC
