### ISSUE TITLE
Don't expand threads by default

### ISSUE THREAD

**Issue by exhuma** [RocketChat/Rocket.Chat#15207] opened 2019-08-20 08:25 UTC
The new "Threads" feature is extremely useful to keep the chat less cluttered.

Expanding the threads by default defeats part of this because lengthy threads still appear in the overall chat window.

I've recently joined a Slack channel and noticed that it has the same feature, but the threads are collapsed by default. This makes it much easier to follow the main chat.

**Comment by reetp** [comment] 2019-08-20 08:37
@rocket-cat close

Duplicate of too many things to list them all, and at best it is really a feature request (ie there is no breakage) rather than a real bug.

Search like this first please:
https://github.com/RocketChat/feature-requests/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+thread


https://github.com/RocketChat/Rocket.Chat/issues/14719
https://github.com/RocketChat/feature-requests/issues/117

Etc

**Closed by reetp** 2019-08-20 08:37 UTC
