### ISSUE TITLE
Right and Left Aligned Messages

### ISSUE THREAD

**Issue by blhuynh** [RocketChat/Rocket.Chat#10863] opened 2018-05-23 16:10 UTC
In order to view messages more efficiently
As a user
I would like to be able to have the ability to have messages sent by myself to be right aligned and all messages sent by other people to be left aligned (similar to how iMessage does it)

**Comment by kaiiiiiiiii** [comment] 2018-05-23 19:13
Duplicate of #9681 and #10308

**Closed** 2018-05-23 19:35 UTC
