### ISSUE TITLE
snap: BIND_IP

### ISSUE THREAD

**Issue by indrisepos** [RocketChat/Rocket.Chat#10614] opened 2018-04-28 07:22 UTC
### Description:

I can not setup the BIND_IP parameter in the snap rocketchat-server package. It is need because to prevent the external server access.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System:  Ubuntu 16.04.4
* Deployment Method(snap/docker/tar/etc): snap

### Expected behavior:

sudo snap set rocketchat-server BIND_IP=127.0.0.1
The nmap does not show the 3000 port: 
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
443/tcp  open  https

### Actual behavior:

```
# sudo snap set rocketchat-server BIND_IP=127.0.0.1
error: cannot perform the following tasks:
- Run configure hook of "rocketchat-server" snap (snap "rocketchat-server" has no "configure" hook)
```
Currently the nmap showing the 3000 port: 
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
443/tcp  open  https
**3000/tcp open  ppp**

**Comment by TwizzyDizzy** [comment] 2018-05-03 22:34
@rocket-cat close

Closing this as it seems to be a duplicate of #7036. If that's not the case, please get back to me!

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-05-03 22:34 UTC
