### ISSUE TITLE
Offline Email Notifications setting is ignored

### ISSUE THREAD

**Issue by phidlipus** [RocketChat/Rocket.Chat#8758] opened 2017-11-02 07:12 UTC
### Description:

Offline email notifications are disabled in account preferences, but Rocket.Chat sends emails when user is offline.
This problem appeared after upgrade to version 0.59.3. In 0.58.2 it worked normally.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Linux (Debian Wheezy)
* Deployment Method: tar (manually)
* Number of Running Instances: 1
* DB Replicaset Oplog: disabled
* Node Version: 4.8.4 - x64

### Steps to Reproduce:

Disable offline email notifications in your account preferences and let somebody send you a message.

### Expected behavior:

Don't send email notifications when it's disabled in account preferences.

### Actual behavior:

Offline email notifications are disabled in account preferences, but Rocket.Chat sends email notifications when user is offline.

**Comment by maximecharron** [comment] 2017-11-02 17:31
this issue is a duplicate of #8619

**Comment by MartinSchoeler** [comment] 2017-11-03 10:43
Yes, is a duplicate

**Closed by MartinSchoeler** 2017-11-03 10:43 UTC
Labels: feat: email
