### ISSUE TITLE
need a feature to add third people when in Direct Messages scenario

### ISSUE THREAD

**Issue by mamashuodedui** [RocketChat/Rocket.Chat#12289] opened 2018-10-09 07:34 UTC
**Is your feature request related to a problem? Please describe.**
when chatting with other people in Direct Messages, the 3rd people is needed to add to provide help most often

**Describe the solution you'd like**
in one window of the direct messages , add a button to add user like the private group 

**Describe alternatives you've considered**

**Additional context**

**Comment by kaiiiiiiiii** [comment] 2018-10-09 08:11
Duplicate of ##4489

// CC: @TwizzyDizzy

**Closed** 2018-10-09 08:18 UTC

**Comment by nelsongraca** [comment] 2019-05-13 10:49
any news on this? My users are requesting this too

**Comment by reetp** [comment] 2019-05-13 12:10
> any news on this? My users are requesting this too

This Issue is closed as a duplicate. Have you actually looked at the original Issue to see progress?

**Comment by nelsongraca** [comment] 2019-05-13 12:12
Sorry commented on the wrong one
