### ISSUE TITLE
Not working on Win10/IE 11

### ISSUE THREAD

**Issue by marz71** [RocketChat/Rocket.Chat#12356] opened 2018-10-18 08:26 UTC
### Steps to reproduce:

1. Fetch develop (0.71.0) branch from github (have tried master branch too 0.70.4, the same result)
2. Run the build-run.sh script
3. Use IE 11 to go to https://url.to.server

### Expected behavior:

Chat opens

### Actual behavior:

Does not open. Hangs on the fading bubbles.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.0-develop
- Operating System: Ubuntu 18.04
- Deployment Method: Clone from github
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.9.3 - x64
- MongoDB Version: 4.01

### Additional context

HTML/Javascript-code seems OK. "lynx -source https://url.to.server" seems OK. 
Works OK in Chrome, not in IE.

### Relevant logs:

![rocket](https://user-images.githubusercontent.com/26957931/47141039-0be65b80-d2c0-11e8-8826-ee0e748892b8.jpg)

**Comment by reetp** [comment] 2018-10-18 13:18
Seems that this is an IE issue rather than anything else. Presumably it is blocking something somewhere if Chrome and Lynx work OK.

You probably need to debug IE and see where it is throwing a hissy fit. A quick search of the interwebs suggests F12 will get you the debug console. Any errors there?

Does it work with https://open.rocket.chat ?

**Comment by ggazzo** [comment] 2018-10-18 13:41
duplicate of #12226

**Closed by ggazzo** 2018-10-18 13:41 UTC

**Comment by reetp** [comment] 2018-10-18 13:46
Thanks - I just found #12226 myself and was about to comment !
