### ISSUE TITLE
Can't turn off Offline Email Notifications

### ISSUE THREAD

**Issue by Venomen** [RocketChat/Rocket.Chat#8643] opened 2017-10-25 11:57 UTC
### Description:

Turning Offline Email Notifications OFF doesn't help.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.1
* Operating System: Debian 9
* Deployment Method(snap/docker/tar/etc): tar
* Number of Running Instances: 2
* DB Replicaset Oplog: yes
* Node Version: v4.5.0

### Steps to Reproduce:

1. Go to My Account -> Preferences
2. Change Offline Email Notifications to Disabled
3. Close rocketchat and wait for mail, that should not come..

### Expected behavior:

1-2 
3. Close rocketchat and enjoy no emails :)

### Actual behavior:

Emails are comming :(

### Relevant logs:
I've turned on debug logs on rocket and I see that this option IS changing properly but it just don't work:

rocketchat_logger rocketchat_logger.js:375 Meteor ➔ method saveUserPreferences -> userId: nsjK7hB8AGm6tKKnd , arguments:  { '0':
   { newRoomNotification: 'door',
     newMessageNotification: 'droplet',
     useEmojis: '1',
     convertAsciiEmoji: '1',
     saveMobileBandwidth: '1',
     collapseMediaByDefault: '0',
     viewMode: 1,
     hideUsernames: '0',
     hideFlexTab: '0',
     hideAvatars: '0',
     mergeChannels: '1',
     sendOnEnter: 'normal',
     roomsListExhibitionMode: 'unread',
     autoImageLoad: '1',
     **emailNotificationMode: 'disabled',**
     highlights: [],
     desktopNotificationDuration: '5',
     desktopNotifications: 'default',
     mobileNotifications: 'default',
     unreadAlert: '1',
     notificationsSoundVolume: 100 } }

**Comment by phriedrich** [comment] 2017-10-25 12:07
Probably a duplicate of #8568 ?

**Comment by MartinSchoeler** [comment] 2017-10-25 12:08
Yes duplicate of #8568

**Closed by MartinSchoeler** 2017-10-25 12:08 UTC
