### ISSUE TITLE
Unable to upload extension-less files && special extension files

### ISSUE THREAD

**Issue by staticjinno** [RocketChat/Rocket.Chat#8055] opened 2017-09-06 08:20 UTC
### Description:

When trying to upload an extension-less file or special extension file (.db, .anything etc...)
you get an error saying that the media type is not accepted, although the allowed files list is empty (allow all files).

### Server Setup Information:

* Version of Rocket.Chat Server: Tried on both 0.58.2(Latest) and on 0.59.0-rc.4
* Operating System: Docker on ubuntu 14.04
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1 rocketchat, 1 mongo, 1 hubot
* DB Replicaset Oplog:
* Node Version: 4.8.4 - x64 

### Steps to Reproduce:

1. enter a chat room
2. drag/select a file with no extension or special extension (something.db for instance)

### Expected behavior:

file should upload as is and be downloaded as is with no extensions or special extension

### Actual behavior:

![capture](https://user-images.githubusercontent.com/30978297/30101506-1d496ad6-92dc-11e7-9ce6-216d1ab07470.PNG)

### Relevant logs:
no relevant logs seen

**Comment by MartinSchoeler** [comment] 2017-09-08 15:24
duplicate of #7074

**Closed by MartinSchoeler** 2017-09-08 15:24 UTC
