### ISSUE TITLE
screenshare button

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#2244] opened 2016-02-16 14:56 UTC
Having a direct screenshare button would be more convenient than making a video call and then turning off camera.

![image](https://cloud.githubusercontent.com/assets/4588562/13079686/7cc751e8-d493-11e5-81d9-874b499985d0.png)

**Comment by engelgabriel** [comment] 2016-02-16 15:29
+1

**Comment by capensisma** [comment] 2016-02-20 18:18
Duplicate of #1745 will be done soon

**Closed** 2016-02-22 22:56 UTC
Labels: feat: webrtc, subj: ui/ux
