### ISSUE TITLE
number of unread messages indicator misbehavior

### ISSUE THREAD

**Issue by rockneverdies55** [RocketChat/Rocket.Chat#811] opened 2015-09-15 15:05 UTC
Sorry if this has been filed already. Few quick searches in the issues didn't yield anything.

So the misbehavior I noticed is that when I scroll up the notification decreases the number of unread messages, however it increases the number back again while I'm scrolling down.

![unread-messages-notification](https://cloud.githubusercontent.com/assets/4588562/9880384/60aa267a-5b99-11e5-90fc-803e0c2a29d5.gif)

Maybe it actually knows that I don't read the messages really since I scroll up too fast and it marks them unread back again :smile:

**Comment by rodrigok** [comment] 2015-09-15 19:25
We don't mark each message as read, so you need to go to the first unread message like you did and keep there for 1 second, this is the actual behaviour

**Comment by marceloschmidt** [comment] 2015-09-15 19:29
It's not a bug, it's a feature :stuck_out_tongue: . Should we close this?

**Comment by geekgonecrazy** [comment] 2015-09-15 19:30
I think he means once you reach 0 it should probably go away?

**Comment by rodrigok** [comment] 2015-09-15 19:33
@geekgonecrazy yes, if you stay there for at least 1s

**Comment by rockneverdies55** [comment] 2015-09-15 19:36
When I'm going up if unread number is decreasing, how could the number increases back again when I'm scrolling down?

Once it reaches 0 or goes away because of scrolling up, it should not come back at all.

**Comment by marceloschmidt** [comment] 2015-09-15 19:37
The counter is useful for letting you know how many messages behind is the first unread message... and it will not count as read, unless you stay for at least 1s in that message.

**Comment by marceloschmidt** [comment] 2015-09-15 19:38
BTW, if you really don't care about the messages that you haven't read, just click the MARK AS READ button
![image](https://cloud.githubusercontent.com/assets/1986378/9887845/36efa736-5bc8-11e5-8fde-82a5b712ec4d.png)

**Comment by rockneverdies55** [comment] 2015-09-15 19:42
If you're semantically OK on how the current implementation works, it's fine.

But I personally think it should not increase the number back again while I'm scrolling down (even I don't wait 1 sec)

**Comment by rodrigok** [comment] 2015-09-15 19:51
I like this behaviour since the text is **N NEW MESSAGES SINCE (SOME HOUR)** and not **N UNREAD MESSAGES**

**Closed** 2015-09-17 01:41 UTC
Labels: UI / UX

**Comment by poeschko** [comment] 2016-05-02 09:28
FWIW, I agree with @rockneverdies55 that this is confusing. If the number is decreased first (while scrolling up), it shouldn't increase again (while scrolling down) – that's just unexpected. If you don't count a message as read before viewing it for >1 sec, then the counter shouldn't decrease before that either. (Although I personally wouldn't even want that 1-sec threshold – I can skim through messages faster than that.)
