### ISSUE TITLE
Need global cross platforms install counter

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#494] opened 2015-08-18 15:49 UTC
Devs love to be on the trending, winning team.

We need to capture and maintain a running count of client installs/user registrations across all mobile, desktop, web, cloud, and alternative emerging platforms ... over the Internet, Intranets, and private Internet. 

Prominently feature the exponential growth on our home page.
##

**Comment by marceloschmidt** [comment] 2015-08-18 16:29
Isn't this a duplicate of #493?

**Comment by Sing-Li** [comment] 2015-08-18 16:35
@marceloschmidt ... Inspired by #493 :smile:   I think we get client install stats from various web stores. And that is not part of #493.  This counter is a PR # ... and not necessarily an accurate engineering number.

**Comment by marceloschmidt** [comment] 2015-08-18 16:36
Nice! Let it be then :)

**Comment by louisemessage** [comment] 2018-03-13 16:07
Closing this issue as there hasn't been activity on it in over two years. We're trying to clear up our backlog of issues :)

**Closed by louisemessage** 2018-03-13 16:07 UTC
Labels: feat: statistics, type: new feature
