### ISSUE TITLE
Hide Role Tags not working after upgrade to 1.0.1

### ISSUE THREAD

**Issue by pageb018** [RocketChat/Rocket.Chat#14333] opened 2019-04-30 15:51 UTC
### Description:

After upgrading from .7x to 1.0.1 role tags are now displayed in direct message and channels where they had not been before. 
In Accounts > User Prefs "hide role" is set to true and in Layout > User Interface "display roles" is set to false. 

### Steps to reproduce:

1. upgrade to 1.0.1

### Expected behavior:

user roles should be hidden. No settings changed during upgrade process. 

### Actual behavior:

user roles are still displayed regardless of configuration. 

![Screen Shot 2019-04-30 at 11 48 29 AM](https://user-images.githubusercontent.com/26354599/56974993-ea531000-6b3d-11e9-960c-cfa552b70eee.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System:  Ubuntu 16.04.6 LTS
- Deployment Method: Docker / Docker Compose
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v8.11.4
- MongoDB Version: 3.6.9

### Relevant logs:

No errors in the log.

**Comment by tassoevan** [comment] 2019-04-30 17:09
Duplicate of #14310 and #14058.

**Closed by tassoevan** 2019-04-30 17:09 UTC
