### ISSUE TITLE
[BUG] Leaving channel as last owner is bugged

### ISSUE THREAD

**Issue by der-eismann** [RocketChat/Rocket.Chat#10027] opened 2018-03-06 13:39 UTC
### Description:

Sorry for the title, but I didn't know how to describe it better. After the update to 0.62.1 I experienced a new bug when trying to leave a channel as the last owner. Maybe you can try to reproduce it with the steps noted below.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.1
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): snap
* Number of Running Instances: 1
* Node Version: 8.8.1

### Steps to Reproduce:

1. Create a new public channel with min. 2 users
2. Now leave the newly created channel
3. You get an error, that you have to choose a new owner before you leave, but the UI offers you to join the channel:
![error1](https://user-images.githubusercontent.com/10406217/37034754-9b5ea18c-214a-11e8-9ffe-2cf7ff4da6ba.PNG)
4. The channel doesn't appear in your left sidebar nor does it appear in the search. It still appears in the directory, however you can only read. If you click `join`, nothing happens.
5. When you click "Show members" you still appear in the list, although it looks like you are not joined:
![error2](https://user-images.githubusercontent.com/10406217/37034935-36b5ddbc-214b-11e8-9cb7-201f7225e696.PNG)
6. Inside this menu you can then choose another user as the owner and remove yourself from the channel OR just reload the page OR use a browser instead of the client (or vice versa):
![error3](https://user-images.githubusercontent.com/10406217/37035103-b18188a2-214b-11e8-9b4d-ca98406159e4.PNG)

### Expected behavior:

Get a warning that you can't leave the channel as the last owner. 

### Actual behavior:

A weird interface that gives you the "join Channel" button although you are still inside.

**Comment by MartinSchoeler** [comment] 2018-03-06 14:42
Duplicate of #5358

**Closed by MartinSchoeler** 2018-03-06 14:42 UTC
