### ISSUE TITLE
PSD files upload, but do not post in channel

### ISSUE THREAD

**Issue by tostanoski** [RocketChat/Rocket.Chat#10935] opened 2018-05-29 19:26 UTC
### Description:

When uploading a PSD file, it appears to upload successfully, but doesn't become available in the channel it was uploaded to. No post occurs following the upload.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.63.3
* Operating System: MacOS 10.13.3/Windows 10
* Deployment Method(snap/docker/tar/etc): All
* Number of Running Instances: 1
* DB Replicaset Oplog: 
* Node Version: 
* mongoDB Version: 

### Steps to Reproduce:

1. Ensure that either PSD files or all files are allowed in Rocket.Chat admin.
1. Attempt to upload a PSD file to any Rocket.Chat channel. Any PSD file will do.
2. Watch it upload and not post.

### Expected behavior:

It should post like any other file, albeit without a preview as these files don't have previews.
### Actual behavior:

After the upload the file doesn't become available for download.

**Comment by kaiiiiiiiii** [comment] 2018-05-29 19:30
Maybe related to [#690](https://github.com/RocketChat/Rocket.Chat.Electron/issues/690)

**Comment by graywolf336** [comment] 2018-05-29 19:42
Yeah, it's a duplicate of #690 but since it's actually a core Rocket.Chat problem then it needs to be here and not there. Sadly, this looks like an error with the image processor we use @rodrigok

**Comment by vynmera** [comment] 2018-09-13 16:06
Seeing this too -> log gives me this:
```
Exception while invoking method 'sendFileMessage' Error: Input buffer contains unsupported image format    => awaited here:     at Function.Promise.await (/snap/rocketchat-server/1321/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at Promise.asyncApply (/snap/rocketchat-server/1321/programs/server/packages/rocketchat_file-upload.js:1747:49)     at /snap/rocketchat-server/1321/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  
```

**Comment by DukeW** [comment] 2018-09-24 09:14
It would be worth adding an exception in sendFileMessage.js so it doesn't treat PSD files as images for the moment. (Until the issue in the image processor is solved.)

**Comment by madguy02** [comment] 2018-09-24 09:41
@DukeW, Do you think https://github.com/RocketChat/Rocket.Chat/pull/11908 might help??

**Comment by DukeW** [comment] 2018-09-24 10:18
@madguy02 Not sure to be honest, bit of a noob with Meteor. But technically speaking PSD is an image format so no, it might not help.

**Closed** 2018-10-26 22:50 UTC
Labels: feat: file sharing
