### ISSUE TITLE
jitsi “Click to Join” button inside chats without any user request

### ISSUE THREAD

**Issue by legalcrm** [RocketChat/Rocket.Chat#18130] opened 2020-07-02 15:21 UTC
### Description:
 
- The system send “Click to Join” jitsi button inside chats without any user request.
- Almost every 10 / 20 minutes.
- Occurred on different users/roles (User and Admin)
- Occurred on different OS (Win/MacOS)
- Occurred on different browsers (Chrome/Firefox)
- Occurred on Desktop App
- Not yet occurred on Mobile App

### Steps to reproduce:

1. Login on RocketChat from Browser or Desktop App
2. Stay in chat active 
3. Wait for unattended "click to join" request to a random room or user

<img width="953" alt="jitsi_click_to_join" src="https://user-images.githubusercontent.com/42918046/86412116-97836400-bcbe-11ea-8b9d-f77c848f4b19.png">

### Expected behavior:

- The "click to join" button is send to a specific chat only when user click "call" button and confirm dialog.

### Actual behavior:

- If a user is online, the system send “Click to Join” jitsi button inside random recently used chats, without any user request or interaction.

### Server Setup Information:

Version of Rocket.Chat Server: 3.4.0
Operating System: linux 4.15.0-108-generic
Deployment Method: docker on Cloudron
Number of Running Instances: 1
NodeJS Version: v12.16.1
MongoDB Version: 3.6.3
Client Setup Information
Desktop App or Browser Version: Browser and Desktop
Operating System: windows/osx

**Comment by HiveMindNet** [comment] 2020-07-02 21:33
I also see this with some users since before last update to 3.4.0 - mostly with browser users, (not seen from apps). Unfortunately unable to see specific cause.

**Comment by legalcrm** [comment] 2020-07-02 21:39
It happens me first time two month ago... but it was only one time at night and only on one user.
Today every user online shows the issue!

**Comment by EnCz** [comment] 2020-07-02 22:06
Can confirm that this happend even before 3.4.0.
We have this rare effect for months now.
It always affects a random user, let's say about once or twice a week. This user then randomly sent 2 or 3 Video-Call Buttons within an hour or two. (I THINK to the last channel he was active in but that's just a guess.)

No real way for me to reproduce this tho :/ Would have opened an issue earlier if I had something on hand. Good to see that other people have the same problem, maybe this can get figured out.

The devs should be able to tell if there is some "automatic" kind of process that sends those buttons.

**Comment by legalcrm** [comment] 2020-07-02 22:14
from the forum
https://forums.rocket.chat/t/rocket-chat-keeps-sending-click-to-join-automatically/6340

**Comment by AmatorPhasma** [comment] 2020-07-02 22:14
Happens also on our server for a random user in a random channel/direct messages:

Browser: Safari, Firefox, Chrome, Edge
Apps: Mobile and Desktop

> No real way for me to reproduce this tho :/ 

Same here, we call it "Heisenberg Bug" for now.

**Comment by ggazzo** [comment] 2020-07-02 22:17
hopefully closed by https://github.com/RocketChat/Rocket.Chat/pull/18111, any problem please let me know

**Closed by ggazzo** 2020-07-02 22:17 UTC

**Comment by legalcrm** [comment] 2020-07-08 08:24
Update 3.4.1 does't solve the issue,
Same Jitsi "click to join" request in random chats without user intervention.
In this update the issue seems less frequent than previous, but it happen anyway.

**Comment by legalcrm** [comment] 2020-07-08 08:26
> hopefully closed by #18111, any problem please let me know

Update 3.4.1 does't solve the issue.
Same Jitsi "click to join" request in random chats without user intervention.
In this update the issue seems less frequent than previous, but it happen anyway.

**Comment by EnCz** [comment] 2020-07-08 08:31
Was almost expecting this since we had the same effect for months now, just very sporadic (One person every week doing random calls into the same, presumably last active, channel every ~30 mins).
Then 3.4.0 came around and there was one case where it exploded with random jitsi calls but I think those are 2 seperate bugs of which the latter was fixed in 3.4.1

@ggazzo this issue probably needs to get looked at again

**Comment by lucioalvestoledo** [comment] 2020-09-09 14:01
I updated rocketchat to version 3.6.0 and I continue with this problem.

Someone enters a conference through Jitsi via the call button and every 1 minute we receive the message "Click to Join!"

**Comment by emikolajczak** [comment] 2021-02-05 07:16
Hi why this is closed?
It still exists in 3.9.7.

**Comment by arpsyapathy** [comment] 2021-06-03 17:31
i have the same problem. On last RC version
