### ISSUE TITLE
Error Update 4.6.4 to 4.7.2 or 4.8.0

### ISSUE THREAD

**Issue by vpnwe912** [RocketChat/Rocket.Chat#25759] opened 2022-06-04 13:12 UTC
Good afternoon. I am trying to update from version 4.6.4 to version 4.7.2 or 4.8.0 after which nothing works, although all services are up and running, I provide screenshots below
- operating system:
       Debian 10
- NodeJSVersion:
        v14.19.2
-MongoDBVersion:
        v5.0.8
- NPM version:
        6.14.17
        
![0](https://user-images.githubusercontent.com/34860203/172000558-06274927-72f2-465b-857e-0b14c934c509.png)
![1](https://user-images.githubusercontent.com/34860203/172000560-37b42406-b8c6-405e-9cf7-19968d71ad3c.png)
![2](https://user-images.githubusercontent.com/34860203/172000561-c073ddd4-e1c9-4a82-b484-a171cbc1be03.png)
![3](https://user-images.githubusercontent.com/34860203/172000562-84de44c1-6b95-4268-ab99-e16633fd0239.png)

**Comment by dudanogueira** [comment] 2022-06-06 13:42
Hi!

Can you try cleaning the cache? 
Sorry to ask that, but I have seen some updates doing that, and being able to solve it clearing the cache.

Also, closing as this is probably not a bug, but a deployment struggle.

 Please, read here before opening an issue:
https://docs.rocket.chat/getting-support/asking-for-help

One last tip, try getting away from manual or snap deployments, and use docker/k8s instead.

**Closed as completed by dudanogueira** 2022-06-06 13:42 UTC
