### ISSUE TITLE
upload file and mention user function not working

### ISSUE THREAD

**Issue by santalii** [RocketChat/Rocket.Chat#32118] opened 2024-04-03 02:23 UTC
### Description:

Upload file and mention user at the same time in the message.
Username spotlight will not work.

### Steps to reproduce:

1. Upload a file and write some message , mention any user at the same time.

### Expected behavior:
mentioned user should be spotlight and notified.

### Actual behavior:

Username spotlight will not work. Get error log message.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.5.5
- Operating System: Debian
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0.18

### Relevant logs:

`Exception while invoking method 'spotlight' Error: invalid username     at Proxy.findOneByUsernameIgnoringCase (server/models/raw/Users.js:388:10)     at server/lib/spotlight.js:240:35     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at server/publications/spotlight.ts:53:21     at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40  => awaited here:     at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:781:32)     at packages/meteor.js:365:18     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)     at packages/ddp-server/livedata_server.js:791:46     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:739:23)     at packages/ddp-server/livedata_server.js:603:43 `

**Comment by SySagar** [comment] 2024-04-08 17:10
OK just let me get this clear. So bsically when you are uploading a file, in the descripton u want to mention suppose a user but on posting it it isnt getting hightlighted am I right?

**Comment by santalii** [comment] 2024-04-10 01:58
Yes, uploading a file, in the description mention user but username is not highlighted.
And error logs as above.

**Comment by reetp** [comment] 2024-06-05 15:24
Have you tested this on 6.8 or 6.9 ?

**Comment by santalii** [comment] 2024-06-27 01:54
> Have you tested this on 6.8 or 6.9 ?

Yes , I upgraded to 6.9.2
User mention still not working in file upload description and there no any error logs.
When I type @ , it used to pop up a menu to choose username, but after upgrading to 6.9.2 no menu.
Also the words after (at) mark and (at) mark itself will be dropped , not showing in the upload file descirption after submit file.

However it I edit the description of the uploaded file, somtimes it would mark the username with color.

**Comment by reetp** [comment] 2024-06-27 12:09
Yes I can reproduce this.

It definitely seems like a bug.

I think this might have been raised before but it needs a search.

I will raise it internally.

**Comment by reetp** [comment] 2024-06-27 12:17
Closing as duplicate of:

https://github.com/RocketChat/Rocket.Chat/issues/32151
https://github.com/RocketChat/Rocket.Chat/issues/28991
https://github.com/RocketChat/Rocket.Chat/issues/28852
https://github.com/RocketChat/Rocket.Chat/issues/28545
https://github.com/RocketChat/Rocket.Chat/issues/25918

I would probably follow up on 25918 or 32151

I am going to see what we can do to fix this.

**Closed by reetp** 2024-06-27 12:17 UTC
Labels: stat: waiting response
