### ISSUE TITLE
Cant upload python files 

### ISSUE THREAD

**Issue by prashanthym** [RocketChat/Rocket.Chat#14144] opened 2019-04-15 11:37 UTC
### Description:

When I try to upload the python files, it is throwing an error as media types not accepted and here are version details

### Steps to reproduce:
    Add "application/x-python,application/python,application/*.py,text/python,text/x-java,text/x-script.phyton,application/x-bytecode.python,application/octet-stream" (exact MIME type) to the list of "Accepted Media Types" (Administration --> File Upload)
    Open a channel
    Try to upload a file produced with Python(test.py)

### Expected behavior:
The file will be uploaded and a message with the attachment will be posted to the channel.

### Actual behavior:

The upload will be rejected with the note "Media Types Not Accepted".

### Version Details : 
0.72.3

**Comment by rmaksimov** [comment] 2020-10-04 22:42
Still present in the latest version (3.7.0)

![rc](https://user-images.githubusercontent.com/2904679/95028822-e2d95400-06ab-11eb-8ccc-2f10c4fa9e90.PNG)
![rc2](https://user-images.githubusercontent.com/2904679/95028824-e40a8100-06ab-11eb-9e5f-db06c7429537.PNG)

**Comment by clemoan** [comment] 2020-11-04 21:51
It's a real problem in my organization. Is there a workaround ?

**Comment by GulliblePsychologist** [comment] 2020-11-12 23:07
I have run into the same problem. I ended up emptying out the "Accepted Media Types" field under "File Uploads" in the settings, but even after repeated restarts, this does nothing.

Renaming my file to ".py.txt" allows me to upload it, but I would like to see this fixed ASAP so I don't have to use this workaround.

**Comment by xgdgsc** [comment] 2020-11-19 03:12
This is critical

**Comment by GulliblePsychologist** [comment] 2020-11-19 16:46
I wouldn't know about that, but it is pretty annoying and it seems like this would be trivial to fix for someone who is familiar with the project.

**Comment by BjoernLudwigPTB** [comment] 2020-11-25 13:12
> Still present in the latest version (3.7.0)
> 
> ![rc](https://user-images.githubusercontent.com/2904679/95028822-e2d95400-06ab-11eb-8ccc-2f10c4fa9e90.PNG)
> ![rc2](https://user-images.githubusercontent.com/2904679/95028824-e40a8100-06ab-11eb-9e5f-db06c7429537.PNG)

If we remove the block for "image/svg+xml" by clearing the "Blocked Media Types" field, then py-files can be uploaded, otherwise not. That seems to be a bug.

**Comment by xgdgsc** [comment] 2021-01-12 04:59
Also hpp file doesn' t work.

**Comment by NikoHD203** [comment] 2021-01-26 10:22
I could find out where the problem is. In the source code under [packages/meteor-jalik-ufs/ufs-mime.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/meteor-jalik-ufs/ufs-mime.js) is a list of datatypes. After some testing, I got to the conclusion that every type in there can be sent without getting blocked

**Comment by BjoernLudwigPTB** [comment] 2021-01-26 10:49
> I could find out where the problem is. In the source code under [packages/meteor-jalik-ufs/ufs-mime.js](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/meteor-jalik-ufs/ufs-mime.js) is a list of datatypes. After some testing, I got to the conclusion that every type in there can be sent without getting blocked

Well done! Does that mean, we only have to include the file-endings which we desire to share? Or is that accompanied with any undesired side-effects?

**Comment by NikoHD203** [comment] 2021-01-27 12:06
I guess so, but I cannot assure you that this will work because I'm not very experienced with javascript

**Comment by rmaksimov** [comment] 2021-02-15 07:39
It looks as if the problem has been fixed in 3.11.1 (or 3.11.0)

**Comment by noobbbbb** [comment] 2021-11-19 06:55
Not fixed in 3.18.0
https://github.com/RocketChat/Rocket.Chat/issues/23173

**Comment by jamesavery** [comment] 2022-05-15 12:51
This extremely annoying bug has been frustrating users for 3 years now. It seems that it should be trivial to fix. Is there any reason to not fix this?

**Comment by oyxnaut** [comment] 2024-03-11 10:50
This is still an issue with 6.6.2. A workaround is to suffix all rejected files with `.txt`, or `.zip`.

**Comment by heck-gd** [comment] 2024-04-05 13:43
Seems it was working fine in 6.5.x. In my chat history I successfully sent someone a `.csr` file a couple months ago. Now in (currently) 6.6.6 the chat is rejecting such files.

**Comment by oyxnaut** [comment] 2024-07-12 14:38
Just checking in to say it seems to work as expected with 6.10.0.

**Comment by noobbbbb** [comment] 2024-10-16 07:07
working as expected with v6.13.0

**Closed** 2024-10-25 08:19 UTC
