### ISSUE TITLE
I get the message "You have not verified your email." upon successful login, even though I just did it again.

### ISSUE THREAD

**Issue by stephaneeybert** [RocketChat/Rocket.Chat#6103] opened 2017-02-20 07:44 UTC
I get the message "You have not verified your email." upon successful login, even though I just did it again.

Rocket.Chat Version: 0.49 
Running Instances: 1
DB Replicaset OpLog:
Node Version: 6.8.1

**Comment by MartinSchoeler** [comment] 2017-02-20 15:42
Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by stephaneeybert** [comment] 2017-02-21 08:38
I downloaded the 0.52 release and tried installing it. But I got stuck. I was looking for some installation instructions, say an INSTALL.txt file. I saw lots of ways on how to install it on the github.com website but nothing about an installation from source. Maybe it's me :-) No worries. Also, the install.sh script has some hard coded ROOTPATH=/var/www/rocket.chat and  I want my installation to be local in my home directory /home/stephane/programs/rocket.chat I'll keep trying to install it.

**Comment by stephaneeybert** [comment] 2017-02-21 09:17
So I decided to use the latest release instead:
curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tgz
But starting the server fails, as it complains about my NodeJS version (6.8.1) of not being a 4.x.x. which is surprising considering my previous install of Rocket.Chat 0.49 was happy with my same NodeJS version. And I can't downgrade my NodeJS.

**Comment by SeanPackham** [comment] 2018-03-12 11:38
You need to click the email link to verify your account. You still will be able to login without a verified account. Please let me know if you are still having this issue. I cannot reproduce it.

**Closed by SeanPackham** 2018-03-12 11:38 UTC
Labels: feat: accounts
