### ISSUE TITLE
Custom Script for logged in users throws an exception when there are < or > symbols

### ISSUE THREAD

**Issue by catmanjan** [RocketChat/Rocket.Chat#6127] opened 2017-02-21 22:51 UTC
Probably an encoding issue, I get the following in Chrome

`VM965:4 Uncaught SyntaxError: Unexpected end of input
    at Function.t._insertNodeWithHooks (4a5503e….js?meteor_js_resource=true:83)
    at Function.t._insert (4a5503e….js?meteor_js_resource=true:83)
    at d._DOMRange.t.attach (4a5503e….js?meteor_js_resource=true:83)
    at Function.t._insert (4a5503e….js?meteor_js_resource=true:83)
    at d._DOMRange.t.attach (4a5503e….js?meteor_js_resource=true:83)
    at d._DOMRange.t.setMembers (4a5503e….js?meteor_js_resource=true:83)
    at a (4a5503e….js?meteor_js_resource=true:83)
    at Object.t.nonreactive (4a5503e….js?meteor_js_resource=true:35)
    at d.View.l (4a5503e….js?meteor_js_resource=true:83)
    at 4a5503e….js?meteor_js_resource=true:83`

And the offending line is:
`    for (var n=0; n`

But the input in the field was:

`    for (var n=0; n<nodes.length; n++) {`

Looks like it is snipping everything after the less than symbol

**Comment by debdutdeb** [comment] 2021-06-25 14:42
Hi,
We can't reproduce this error now so closing.
If it re-appears please re-open it.
thanks.

**Closed by debdutdeb** 2021-06-25 14:42 UTC
Labels: type: support
