### ISSUE TITLE
Unfollowing a thread leads to thousands of API requests

### ISSUE THREAD

**Issue by bbrauns** [RocketChat/Rocket.Chat#21359] opened 2021-03-30 07:53 UTC
### Description:

Unfollowing a thread leads to thousands of API requests

### Steps to reproduce:

![followunfollow](https://user-images.githubusercontent.com/6813310/112953153-86785e00-913d-11eb-8175-b73d62d5579b.gif)

### Expected behavior:

Do not dos the server.

### Actual behavior:

dos the server.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.0
- Operating System: ubuntu 18.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: enabled
- NodeJS Version: v12.18.4
- MongoDB Version: 3.6.21 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version: opera:74.0.3911.218, same with chrome 89.0.4389.90 (Official Build) (64-bit)
- Operating System: win10

**Comment by rcsilvadev** [comment] 2021-03-30 14:06
Same behavior here.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.12.1
- Operating System: Debian GNU/Linux 9 (stretch)
- Deployment Method: PM2
- Number of Running Instances: 1
- NodeJS Version: 12.18.3
- MongoDB Version: 3.6.19

### Client Setup Information

- Desktop App or Browser Version: Chrome 88.0.4324.182 (64-bit)
- Operating System: Ubuntu 20.04.2 LTS

It fires a lot of requests to:
`/api/v1/chat.getThreadsList?rid=fwHd[...]Zkif&type=all&text=&offset=0&count=1`

And sporadic requests to:
`/sockjs/596/xq[...]8f_/xhr_send`
`/sockjs/596/xq[...]8f_/xhr`

Over 2.5 MB of resources used in 5 minutes.

**Comment by ankar84** [comment] 2021-04-02 04:45
@sampaiodiego hey!
is there any chances that fix for that issue will land to 3.13 before it release?
Thanks!

**Comment by sampaiodiego** [comment] 2021-04-02 06:10
Oh wow, that's actually a thing for @ggazzo

**Comment by gabriellsh** [comment] 2021-04-28 21:47
This was fixed by #21384. I reproduced this in an older version (3.12.0 as cited above), but was unable to reproduce on latest develop (3.15.0-develop).

If the issue persists by any means, please, tag me here again with the additional info. Thanks!

**Closed by gabriellsh** 2021-04-28 21:47 UTC
