### ISSUE TITLE
Loading screen stuck

### ISSUE THREAD

**Issue by Akiren** [RocketChat/Rocket.Chat#4241] opened 2016-09-08 15:17 UTC
Rocket.Chat version: 39.0

When logging in to rocket.chat via Oauth, intermittently users get hung on the loading /home screen with the icon-spinner active forever. There are no console errors, in addition refreshing the page will always simply log the user in. This happens on mobile as well.

Anyone out there experience this or have any ideas.

Its a pretty vanilla rocket.chat installation that followed the AWS/Docker implementation

**Comment by Molle500** [comment] 2016-09-08 17:34
noticed this too, this bug has been there for a long time sadly :/

**Comment by TheReal1604** [comment] 2016-09-09 10:43
Got this also in my setup. Its a bit strange..

I use normal rc authentication and apache2 as my reverse proxy.. if someone needs more infos or logs, please tell me.

**Comment by joseconsuegra** [comment] 2016-09-14 12:34
Experiencing the same but authenticating through LDAP.

**Comment by paulcrick** [comment] 2016-09-20 03:06
I've had this issue too, using nginx as an SSL reverse proxy. @joseconsuegra Are you using a reverse proxy?

**Comment by joseconsuegra** [comment] 2016-09-20 06:39
@paulcrick no, I'm not using a reverse proxy...

**Comment by mmarif4u** [comment] 2016-09-30 08:05
@paulcrick same here. Using nginx SSL reverse proxy. Screen stuck on the icon spinner loading forever til hit F5 to refresh the page.

Any one have any solution for this?
Using 0.41.0.

**Comment by MartinSchoeler** [comment] 2017-03-28 14:38
@Akiren  Thanks for reporting this issue. We value your time in helping us to make Rocket.Chat great. We always try to fix confirmed problems as quickly as we can, and it appears that the issue you reported might already be fixed in the latest release. Can you please help us test it against current latest release? Much appreciated. And please remember to backup your data before upgrading, just to be safe. Cheers!

**Comment by tsuki1704** [comment] 2017-05-04 20:34
I got this error too. My case is after setting custom Oauth and it works well, then I'm in need of using REST API so I tried to change my Admin account password, then immediately it shows the "invalid user" error and now I'm stuck at the login page forever (not quite login page but it shows nothing, just a blank screen with the background color).

**Comment by Xqua** [comment] 2017-05-24 01:21
Similar issue on RC 0.56 
After setting up CAS the loading time post LogIn is extremely long (2-5 minutes) 
no error on the log or the console.
it stays stuck on ```CachedCollection rooms => Init on login
e6940d1….js?meteor_js_resource=true:243 CachedCollection subscriptions => Init on login```

**Comment by Necklaces** [comment] 2017-05-26 07:53
Getting this too, RC 0.56. Loads forever when using nginx with proxypass/reverse proxy. Can't connect to localhost:3000 at all either.

**Comment by hanselke** [comment] 2017-06-01 13:39
same issue on 0.56 release. refreshing the page does not help. using gapps auth.

anybody knows what to do to recover?

**Comment by Xqua** [comment] 2017-06-02 16:29
I'll throw the issue I opened for CAS in here #7071

**Comment by maxpen** [comment] 2017-10-10 14:45
I get this issue as well. i log in and it takes a while before the chatroom is loaded.

**Comment by chainchopper** [comment] 2018-05-06 18:41
I'm assuming this was never fixed?

**Comment by Hudell** [comment] 2018-06-06 17:28
Have you had this problem recently? I've used OAuth but never seen it happen. I'll try to replicate it in the current version, but since the issue is old it may have already been fixed.

**Comment by Hudell** [comment] 2018-06-13 20:43
I'll close this due to inactivity. If anybody runs into this problem again, the issue can be reopened.

**Comment by edward-of-clt** [comment] 2018-08-08 19:37
This definitely needs to be reopened.

**Comment by Hudell** [comment] 2018-08-08 21:27
Did you run into this issue? Which OAuth service are you using?

**Comment by edward-of-clt** [comment] 2018-08-09 12:47
We are actually using LDAP only. Only fix is deleting cookies.

Our organization at this point does not believe we can go live with
RocketChat due to the outstanding issues we have found and continue to be
open or pending work.

**Comment by jkrysakowski** [comment] 2018-09-10 06:10
Same problem on linux desktop app.

**Comment by CurtisVFX** [comment] 2018-09-11 15:43
I believe I am running into this as well, rocketchat app will sit for long periods displaying the screen shown in the image attached.
I am using LDAP login.
This happens in both the RocketChatApp and in the browser.
Refreshing does not always log the user in.
Any steps I can take to troubleshoot?

![noload](https://user-images.githubusercontent.com/43179800/45371021-774d5700-b5b7-11e8-8343-0b579f64d2f3.PNG)

**Comment by reetp** [comment] 2018-10-29 16:06
@rocket-cat close

Closing to lack of activity.
If you experience this please test on the latest available version of Rocket.Chat before opening another issue.

**Closed by reetp** 2018-10-29 16:06 UTC
Labels: feat: oauth / sso, type: bug

**Comment by beanslee2011** [comment] 2019-09-16 02:33
same problem after restart  a machine

**Comment by aamir-github** [comment] 2020-08-27 05:24
Just cloned the repository to the android studio and after a successful build, it just stuck on the login screen
