### ISSUE TITLE
Version 4.5.2 channel invitation link is not working

### ISSUE THREAD

**Issue by supportdesk-si** [RocketChat/Rocket.Chat#24853] opened 2022-03-17 04:35 UTC
This 5 or 6 update since we originally ran into the issue.  There is a developer who fixed and yet the patch is not available.  Inviting a user to the channel is a critical part of the platform and it is not functioning.  Please address ASAP!!!!!!!!!!!!!!

CentOS 8

Deployment
Version
4.5.2
Deployment ID
xxxxxxxxxxxxxxxxxxxxxxxx
Apps Engine Version
1.31.0
Node Version
v14.19.0
Database Migration
256 (March 16, 2022 22:11)
MongoDB
4.2.18 / wiredTiger (oplog Enabled)
Commit Details
HEAD: (ed2cb3fe6)
Branch: HEAD
![image](https://user-images.githubusercontent.com/51302932/158737861-6606cc56-f964-4ca4-94f8-bcdc520c1c6f.png)

**Comment by ankar84** [comment] 2022-03-17 04:52
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/24444

**Comment by supportdesk-si** [comment] 2022-03-23 01:27
Version 4.5.3 has the same problem.  It is not fixed.

**Closed** 2022-04-07 12:25 UTC
Labels: bug
