### ISSUE TITLE
Broadcasting mode toggle unresponsive in the broadcast channel room info

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#18708] opened 2020-08-28 07:23 UTC
### Description:

On broadcast channels you have an option to turn broadcast mode off. This button cannot be operated.

### Steps to reproduce:

1. Go to broadcast channel Room Info as an owner of the channel.

![Screenshot from 2020-08-28 10-08-18](https://user-images.githubusercontent.com/6958942/91533267-47b8c600-e918-11ea-977f-e80084e1af07.png)

2. Try to click toggle 'Broadcast Channel'

### Expected behavior:

Toggle switches off and broadcast channel mode is disabled.

### Actual behavior:

Nothing happens when you click on the 'Broadcast Channel' switch. It stays enabled.

### Server Setup Information:

- Version of Rocket.Chat Server: 3.5.3
- Operating System: CentOS7
- Deployment Method: tar
- Number of Running Instances: 20
- DB Replicaset Oplog: Yes
- NodeJS Version: 12.16.1
- MongoDB Version: 3.6

### Client Setup Information

- Desktop App or Browser Version: Firefox or Chromium, latest
- Operating System: Windows or Linux

### Additional context

As a workaround you can disable broadcasting mode directly in the database with the command:
`db.rocketchat_room.update( {'name': 'nameofthechannel'}, {$set: {'broadcast': false}} )`
and refreshing the browser screen.

**Comment by MartinSchoeler** [comment] 2020-10-06 18:07
By design broadcast channels should not be changed to a normal channel, and now we removed the button so I will be closing this. If you think they should be changed please open a feature request. Thanks!

**Closed by MartinSchoeler** 2020-10-06 18:07 UTC
Labels: subj: ui/ux
