### ISSUE TITLE
Cannot create incoming webhook to user channel

### ISSUE THREAD

**Issue by pombaer** [RocketChat/Rocket.Chat#13103] opened 2019-01-09 13:20 UTC
### Description:
I have set permission "manage-own-integrations" to "user" and "owner" to be able to create incoming webhooks as normal user, what works if i create a webhook for a public/private channel.
When trying to create an incoming webhook to a user channel i get "Invalid channel", i tried to set "@myusername" at "Post go channel" setting. Creating the webhook as admin works as expected.

When i set "Manage Inegrations" Permission to "user" it works too, but this is not what i want, because every user can edit all Integrations in this case.

### Steps to reproduce:

Create a inetegration four your own user:

Enabled: true
Name (optional): myPersionalIntegration
Post to Channel: @[username]

### Expected behavior:

User should be able to create Integration for his own private channel.

### Actual behavior:

Error "Invalid channel" is displayed.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2
- Ubuntu 18.0.4
- Deployment Method: docker
- Number of Running Instances:  1
- DB Replicaset Oplog: 
- NodeJS Version: v8.11.3

### Relevant logs:

No error is logged in Log Level 2.

**Comment by himpierre** [comment] 2019-01-10 07:20
This is kind of similar to my problem. https://github.com/RocketChat/Rocket.Chat/issues/13061

**Comment by knrt10** [comment] 2019-03-05 08:16
@pombaer as you can on [line77](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-integrations/server/methods/incoming/addIncomingIntegration.js#L77), you have to set both `manage-own-integrations` and `manage-integrations`. Once you do that your user will be able to add webhook on his/her own username or any other. Please do give a try. If it works, feel free to close this issue. Thanks. 👍

**Comment by gregs007** [comment] 2019-07-25 14:08
Actually this behavior has changed since previous versions and I believe it's a regression. If a user ONLY has manage-own-integrations checked they used to be able to create and manage their OWN integrations. This no longer works in the 1.x versions. manage-own-integrations was created so that you could allow users to create and manage their own integrations and not be able to interfere with anyone elses. We're experiencing this issue as well.

**Comment by hugocostadev** [comment] 2023-03-31 11:15
Closing in favor of https://github.com/RocketChat/Rocket.Chat/issues/28723

**Closed by hugocostadev** 2023-03-31 11:15 UTC
