### ISSUE TITLE
Symptom After the upgrade to 6.2.0, an error occurred in deleting files

### ISSUE THREAD

**Issue by Finnimbrun** [RocketChat/Rocket.Chat#29247] opened 2023-05-16 08:07 UTC
### Description:
An error occurs when deleting a file.

Exception while invoking method deleteMessage 

Folder permissions have been set.

![image](https://github.com/RocketChat/Rocket.Chat/assets/37408687/0a04c37b-f66a-4807-9c41-32a380ec53d1)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.0
- Operating System: CentOS Stream 9
- Deployment Method: docker
- Number of Running Instances: 1
- MongoDB Version: 5

**Comment by tintqvn** [comment] 2023-05-16 08:39
I also got the same issue, got from pre-release

**Comment by esnutd** [comment] 2023-05-20 05:41
This is the server side log. :(
```

May 20 09:09:09 node01 node[39985]: {"level":40,"time":"2023-05-20T05:39:09.303Z","pid":39985,"hostname":"node01","name":"DeprecationWarning","section":"METHOD","msg":"deleteMessage method is deprecated, and will be removed in future versions"}
May 20 09:09:09 node01 node[39985]: {"level":50,"time":"2023-05-20T05:39:09.347Z","pid":39985,"hostname":"node01","name":"System","msg":"Exception while invoking method deleteMessage","err":{"type":"Error","message":"ENOENT: no such file or directory, stat '/u01/upload/64685cf17338b29cd19aa989'","stack":"Error: ENOENT: no such file or directory, stat '/u01/upload/64685cf17338b29cd19aa989'\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/ufs/ufs-local.ts:72:20\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/ufs/ufs-store.ts:230:3\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at server/ufs/ufs-local.ts:76:5\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/file-upload/server/lib/FileUpload.ts:677:4\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/lib/server/functions/deleteMessage.ts:48:13\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/misc.ts:557:17\n    at /u01/rocketchat/r622/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","errno":-2,"code":"ENOENT","syscall":"stat","path":"/u01/upload/64685cf17338b29cd19aa989"},"msg":"ENOENT: no such file or directory, stat '/u01/upload/64685cf17338b29cd19aa989'"}

```

**Comment by jw1892626** [comment] 2023-05-21 23:21
Expereincing same issue. Probably related to https://github.com/RocketChat/Rocket.Chat/issues/29309 and https://github.com/RocketChat/Rocket.Chat/issues/29266

**Comment by jw1892626** [comment] 2023-05-21 23:49
This is also preventing pruning from working.

**Comment by debdutdeb** [comment] 2023-05-22 14:43
Duplicate of #29266

**Comment by debdutdeb** [comment] 2023-05-22 14:43
Closing in favour of that.

**Closed by debdutdeb** 2023-05-22 14:43 UTC
