### ISSUE TITLE
Cannot visit specific room before logging in, no error message. 

### ISSUE THREAD

**Issue by timbeiko** [RocketChat/Rocket.Chat#15391] opened 2019-09-17 12:05 UTC
### Description:

When trying to go directly to a room, without having logged in to Rocket.Chat, participants get a loading screen forever rather than a redirect/popup to login. 

Ideally, users clicking the link should be able to see that they are in the right room (i.e. see past conversation, perhaps with the typing box greyed out) and have the option to log in. 

### Steps to reproduce:

1. Without being logged into Rocket.Chat / on a new browser, go to: https://chat.hyperledger.org/channel/besu
2. The window only shows grey loading dots, like these: 
<img width="985" alt="Screen Shot 2019-09-17 at 8 01 02 AM" src="https://user-images.githubusercontent.com/9390255/65039946-5681b500-d921-11e9-9ca9-36d4a7507212.png">
3. To fix this issue, we have realized you can go to https://chat.hyperledger.org/home, and then to https://chat.hyperledger.org/channel/besu, and that will work, but this is cumbersome. 

### Expected behavior:

1. Go to https://chat.hyperledger.org/channel/besu
2. See the chat room, have the opportunity to log in if not logged in. 

### Actual behavior:

1.  Go to https://chat.hyperledger.org/channel/besu
2. Loading screen stays stuck:
<img width="985" alt="Screen Shot 2019-09-17 at 8 01 02 AM" src="https://user-images.githubusercontent.com/9390255/65040202-d90a7480-d921-11e9-8c3c-01193567e879.png">

### Server Setup Information:

- This is happening to everyone on our team who tries too visit  https://chat.hyperledger.org/channel/besu

### Additional context

N/A

### Relevant logs:

N/A

**Comment by ryjones** [comment] 2020-01-07 00:26
This server is running:
```

Hash | abf67ce98521b115c4c85d2ff86394098c92bbf3
-- | --
Tue Apr 30 16:58:11 2019 -0300
HEAD
1.0.2

```

**Comment by ryjones** [comment] 2020-02-19 02:04
This is not fixed in 3.0.0

**Comment by Sing-Li** [comment] 2020-03-25 11:53
@engelgabriel  fast track candidate

**Comment by geekgonecrazy** [comment] 2020-03-26 09:05
@ggazzo this seems like would be super easy to add specifically on the room to redirect?

**Comment by ggazzo** [comment] 2020-05-25 21:38
sorry I cant reproduce on any other server (open/localhost/unstable), could you update to 3.2/3.3 or test over open.rocket.chat? thanks

**Comment by timbeiko** [comment] 2020-05-26 13:05
@ryjones can you confirm the version of rocket chat that HLF is running?

**Comment by ryjones** [comment] 2020-05-26 14:22
@timbeiko we have an upgrade scheduled for next Sunday (US time): https://lists.hyperledger.org/g/tsc/message/3002 

we are running

```
Version | 1.0.2
```

**Comment by timbeiko** [comment] 2020-05-26 16:51
@ryjones will we upgrade to v.>3.3?

**Comment by ryjones** [comment] 2020-05-26 17:09
We are upgrading to 3.2.2, which has the fix. I was able to visit [this chat server](https://github.com/RocketChat/Rocket.Chat/issues/15583#issuecomment-615216158), where it works, and [check the version](https://community.serlo.org/api/info), which is `{"version":"3.2.0","success":true}`.

**Comment by ryjones** [comment] 2020-06-01 06:31
@timbeiko this looks fixed. We’re running `3.3.0` and these links work.

**Closed** 2020-06-02 14:57 UTC
Labels: stat: need more info
