### ISSUE TITLE
IRC Federation not working - Not enough SERVER parameters?

### ISSUE THREAD

**Issue by primozc** [RocketChat/Rocket.Chat#14747] opened 2019-06-05 12:11 UTC
Hello,

I am trying to connect my IRCd (UnrealIRCd v.4) to Rocket.Chat. Unfortunately it is not working. Error (log file) is attached below this post. Any idea how to solve this issue?

Kind regards,

### Steps to reproduce:

IRC Federation settings:
Enabled: True
Protocol: RFC2813
Host: irc.server.si
Port: 65520
Name: irc.server.si
Description: Chat.si IRC Bridge
Local Password: Empty
Peer Password: IRCD password I guess?

### Server Setup Information:

- Version of Rocket.Chat Server: 1.1.1
- Operating System: Debian 9
- Deployment Method: Manual Debian Installation (https://rocket.chat/docs/installation/manual-installation/debian/)
- Number of Running Instances: 1
- DB Replicaset Oplog: mmapv1
- NodeJS Version: 8.11.4
- MongoDB Version: 4.0.10

### Relevant logs:

I20190605-13:58:43.787(2) Updating process.env.MAIL_URL 
I20190605-13:58:44.070(2) [irc][server] Connecting to @irc.server.si:65520 
I20190605-13:58:44.076(2) [irc][server] Connected! Registering as server... 
I20190605-13:58:44.078(2) [irc][server] Sending Command: PASS  0210 ngircd 
I20190605-13:58:44.078(2) [irc][server] Sending Command: SERVER irc.server.si :server.si IRC Bridge 
I20190605-13:58:44.082(2) [irc][server] Unhandled peer message: {"prefix":"irc.server.si","server":"irc.server.si","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Looking up your hostname..."]} 
I20190605-13:58:44.082(2) [irc][server] Unhandled peer message: {"prefix":"irc.server.si","server":"irc.server.si","command":"NOTICE","rawCommand":"NOTICE","commandType":"normal","args":["*","*** Found your hostname (cached)"]} 
I20190605-13:58:46.226(2) [irc][server] Unhandled peer message: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Not enough SERVER parameters"]} 
I20190605-13:58:46.227(2) [irc][server] Unhandled peer message: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Closing Link: [94.130.225.252] (Not enough parameters)"]} 
I20190605-13:58:46.233(2) [irc][server] Connection Closed 
I20190605-13:58:46.657(2) ➔ server.js:207 System ➔ startup

**Comment by reetp** [comment] 2019-06-05 12:31
@rocket-cat close

Always search for errors first.

Closing as this is a duplicate of:
https://github.com/RocketChat/Rocket.Chat/issues/216

Please follow up there (I found that Issue by just doing a generic search on the interwebs for your error):

"irc server closing link not enough parameters"

**Closed by reetp** 2019-06-05 12:31 UTC
