### ISSUE TITLE
Queue Button Does not Appearing after Upgarde from 3.7.1 to 3.17.1

### ISSUE THREAD

**Issue by mojtaba-naserei** [RocketChat/Rocket.Chat#23022] opened 2021-08-24 18:31 UTC
### Steps to reproduce:

1. upgrade rocketchat version from 3.7.1 to 3.17.1 (with docker image)
2. click on Not Available Button
![Screenshot from 2021-08-24 22-50-20](https://user-images.githubusercontent.com/22507369/130670220-b236b2fe-1bdb-4c65-b7f4-8de43ed03d78.png)

### Expected behavior:

Show Queue Button and list
![Screenshot from 2021-08-24 22-58-45](https://user-images.githubusercontent.com/22507369/130670383-3c4e5656-46e3-4598-ac2a-f5ae3db09fba.png)

![Screenshot from 2021-08-24 22-58-54](https://user-images.githubusercontent.com/22507369/130670403-fa963b1b-b7d8-4ba1-b50c-47cffe6c4f00.png)

### Actual behavior:

Does not Show any thing
![Screenshot from 2021-08-24 22-50-30](https://user-images.githubusercontent.com/22507369/130670260-b265b676-8fe2-4c09-be9e-3bf37b903e5c.png)

### Server Setup Information:

- Version of Rocket.Chat Server:  3.17.1
- Operating System: Ubuntu 20.04
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog:  wiredTiger (oplog Enabled)
- NodeJS Version: v12.22.1
- MongoDB Version: 4.4.0

### Client Setup Information

- Desktop App or Browser Version: 2.17.11
- Operating System: Ubuntu 20.04

### Additional context

I Have any other bugs like admin cant click on Available button and got error Not Allowed

**Comment by debdutdeb** [comment] 2021-08-30 10:07
Hi 

It is not adviced to jump versions like that. Please read this - https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#upgrading-rocketchat

Also please read all the release notes since 3.7.1. You can find them at https://github.com/rocketchat/rocket.chat/releases

Closing since this is not a bug.

**Closed by debdutdeb** 2021-08-30 10:07 UTC
