### ISSUE TITLE
update_user Not allows

### ISSUE THREAD

**Issue by billyJack1203** [RocketChat/Rocket.Chat#11963] opened 2018-09-05 17:04 UTC
### Steps to reproduce:

1. 
2. 
3. 
3. 

### Actual behavior: error is presented update_user not allowed

![image](https://user-images.githubusercontent.com/39134559/45108329-f0edcc80-b101-11e8-8e54-c25d220626e9.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 0.69.0
- Operating System: ubuntu 17
- Deployment Method: 
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.3
- MongoDB Version: not sure

**Comment by kaiiiiiiiii** [comment] 2018-09-05 17:52
Duplicate of #11884

Fixed in PR #11955

//CC: @TwizzyDizzy

**Closed** 2018-09-05 17:53 UTC

**Comment by billyJack1203** [comment] 2018-09-05 18:02
I am still confused since I have never programmed using Linux. Is there a simplified update that could do the same as making changes to the code?  I need the commands to edit the config file for rocket chat.  The email is not helping a novice user of ubuntu and rocket chat as I.


Thank you,

Billy Jack Annis
Enterprise Server Administrator
Phone: (936) 559-2222

Etech Global Services, LLC
1903 Berry Dr., Nacogdoches, TX 75964
Etech Linked In Profile<https://www.linkedin.com/company/81008/>  Etech Twitter Account<https://twitter.com/EtechGS>
Etech Web Site<http://www.etechgs.com/>  Subscribe to Newsletter<http://www.etechgs.com/subscribe.aspx?subscribeID=1>

**Comment by billyJack1203** [comment] 2018-09-05 18:55
This fix didn’t help at all.  I need a simpler fix or a better explanation. I have searched and attempted to revert
sudo snap revert rocketchat-server
rocket chat fails completely. I end up running

sudo snap refresh rocketchat-server
to get the server running again.  I need to repair the issue for update_user not allowed and the links that continue to me email I do not understand.
This doesn’t make them correct or incorrect its I need specific directions to repair Rocket Chat passwords


Thank you,

Billy Jack Annis
Enterprise Server Administrator
Phone: (936) 559-2222

Etech Global Services, LLC
1903 Berry Dr., Nacogdoches, TX 75964
Etech Linked In Profile<https://www.linkedin.com/company/81008/>  Etech Twitter Account<https://twitter.com/EtechGS>
Etech Web Site<http://www.etechgs.com/>  Subscribe to Newsletter<http://www.etechgs.com/subscribe.aspx?subscribeID=1>

**Comment by AmShaegar13** [comment] 2018-09-07 12:44
@billyJack1203, downgrading Rocket.Chat is not easily possible. You would need to revert the database migrations manually. Looks like we have to wait for https://github.com/RocketChat/Rocket.Chat/pull/11955 to be merged and released.
