### ISSUE TITLE
Unable to upload any files

### ISSUE THREAD

**Issue by danny13-33** [RocketChat/Rocket.Chat#22945] opened 2021-08-17 02:01 UTC
Deployment Version
3.17.0

Apps Engine Version
1.27.1

Node Version
v12.22.1

Database Migration
228 (August 16, 2021 8:47 PM)

MongoDB
3.6.14 / wiredTiger (oplog Enabled)

Commit Details
HEAD: (d4ce52e09)
Branch: HEAD

OS Version:
Ubuntu 18.04.5

Hello, 

We are unable to upload any files.  In the Gui it shows 'Cannot read property '0' of null' and in the logs below is shown.  We use this in production and have a commercial license, any help quick would be appreciated.  Thank you!

I20210817-01:57:15.205(0) Exception in defer callback: TypeError: Cannot read property 'u' of undefined     at app/integrations/server/lib/triggerHandler.js:498:63     at Array.filter (<anonymous>)     at RocketChatIntegrationHandler.getTriggersToExecute (app/integrations/server/lib/triggerHandler.js:498:21)     at RocketChatIntegrationHandler.executeTriggers (app/integrations/server/lib/triggerHandler.js:563:34)     at _wrapperFunction (app/integrations/server/triggers.js:6:25)     at callbacks.runItem (app/callbacks/lib/callbacks.js:111:70)     at Object.callbacks.runItem (app/metrics/server/callbacksMetrics.js:24:20)     at app/callbacks/lib/callbacks.js:39:35     at app/callbacks/lib/callbacks.js:45:45     at callbacks.run (app/callbacks/lib/callbacks.js:127:9)     at Object.callbacks.run (app/metrics/server/callbacksMetrics.js:14:17)     at app/file-upload/server/methods/sendFileMessage.js:87:32     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)     at packages/meteor.js:550:25     at runWithEnvironment (packages/meteor.js:1286:24)

**Comment by ankar84** [comment] 2021-08-17 04:56
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/22918

**Comment by johncrisp** [comment] 2021-08-17 08:50
Hi,

> We use this in production and have a commercial license

If you have a support contract please open a ticket with support.

You can mention this bug, and 22918

In the meantime I will close this as a duplicate.

**Closed by johncrisp** 2021-08-17 08:50 UTC
