### ISSUE TITLE
login page has visual issues if fields are autofilled

### ISSUE THREAD

**Issue by jwallet** [RocketChat/Rocket.Chat#5055] opened 2016-11-26 22:50 UTC
Your Rocket.Chat version: demo.rocket.chat
![image](https://cloud.githubusercontent.com/assets/23088305/20644369/2ad1ed06-b400-11e6-97d8-11bbaf829538.png)

login page has some issues on firefox (#-2) and chrome (#-3).
I think it just needs to look like #-1 picture.
I tried on IE (I don't have Edge) it does not ask me to save my infos.

**Comment by MartinSchoeler** [comment] 2016-11-28 10:47
Hey @jwallet the second issue is a duplicate of #4965 and the third one has already been fixed in the latest develop branch version. Thanks for the feedback!

**Closed by MartinSchoeler** 2016-11-28 10:47 UTC
