### ISSUE TITLE
Special input makes channel inaccessible

### ISSUE THREAD

**Issue by Michuelnik** [RocketChat/Rocket.Chat#6262] opened 2017-03-06 08:09 UTC
Rocket.Chat Version: 0.53.0
Running Instances: 1
DB Replicaset OpLog: Disabed
Node Version: v4.8.0

When entering ` ```a) ..``` ` in a channel, my client machine's fans spin up and short time later I get a warning about an unresponsive script from my browser.
Until that magic string is deleted manually from the mongo db, nobody can access the channel without running into the same effect.
Other channels are unaffected.

**Comment by MartinSchoeler** [comment] 2017-03-06 11:10
Confirmed on Demo server too.

**Comment by localguru** [comment] 2017-03-06 12:58
can't reproduce that on 0.52.0

**Comment by geekgonecrazy** [comment] 2017-05-17 00:42
I know this one is older, but closing in favor of: #6814

**Closed by geekgonecrazy** 2017-05-17 00:42 UTC
Labels: feat: message, subj: ui/ux, type: bug
