### ISSUE TITLE
User can't send direct messages / User is stuck with blank app

### ISSUE THREAD

**Issue by flayks** [RocketChat/Rocket.Chat#4098] opened 2016-08-23 23:30 UTC
Hey there,

By any strange mystery, probably an upgrade (0.36 to 0.37 and 0.37.1, successfully), one of my users in my Rocket.Chat install can't send DM anymore to other users…
Here is what it looks like, basically the message box is… **empty**!
I tried to rename the username to find a solution/fix, but no result.

Is there any solution to "reset" the user without deleting existing messages? Or create a new user and change the author to this new one?
Any help appreciated!

Rocket.Chat version: 0.37.1

![screenbug](https://cloud.githubusercontent.com/assets/273716/17913469/6005c44e-699a-11e6-884c-5884baf779a0.png)

---

After changing the username to the first one (let's say "superuser" - it was "superuser-" just for testing), I have this home… no sidebar, nothing. What is the point?!

![bugctf](https://cloud.githubusercontent.com/assets/273716/17914963/c9fcf6e0-69a6-11e6-9e9e-47207ae0271b.png)

**Comment by Flayks** [comment] 2016-08-24 01:07
Looks like a "role" issue… it was set for a unknown reason to "null". Setting back to "user" sounds to do the trick. But why did I got a "null" role?

**Comment by SafaAlfulaij** [comment] 2016-08-24 05:49
I have the exact same issue on another site.
Channel names doesn't show up, channel links that other users send to me says that the channel doesn't exist. Nothing works except for the status and settings.
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/17919622/91df0b3c-69d7-11e6-9309-9c0926059c76.png)

You can see that I have 2 private message (in the page title and the favicon).

**Comment by Flayks** [comment] 2016-08-24 09:17
@SafaAlfulaij what did you do with the API to work then?

**Comment by SafaAlfulaij** [comment] 2016-08-24 10:25
> what did you do with the API to work then?

Just used it, check this: https://rocket.chat/docs/developer-guides/rest-api/
I mean the API url results give the correct results (My account is working). The problem is with the UI only.

**Comment by MartinSchoeler** [comment] 2016-08-24 11:36
@Flayks  Yes this was a problem with the roles system but it was probably solved in pr #4073 , and it should not happen again. Thanks for the report, and if the bug still exists now, please report to us

**Comment by sushi0x01** [comment] 2016-08-24 12:32
In 0.37.0 you can achieve same result (loss of permission) by changing another user's password.
Can fix this by adding user to users group in permission page.

**Comment by phutchins** [comment] 2016-10-04 13:05
I'm having this issue too although I'm not 100% sure what is causing it. I thought it may have to do with my slack-bridge but now curious about the password change bit. Is there an easy way to bulk add all users back to the users group (if thats not a bad idea)?

**Comment by engelgabriel** [comment] 2017-01-24 20:41
This have been fixed on later versions.

**Closed by engelgabriel** 2017-01-24 20:41 UTC
Labels: feat: roles / permissions, type: bug
