### ISSUE TITLE
Marking messages on android app does nothing

### ISSUE THREAD

**Issue by calebjacobson** [RocketChat/Rocket.Chat#32580] opened 2024-06-10 16:59 UTC
### Description:
Marking read direct messages

### Steps to reproduce:
1. Log into rocket chat app on android
2. Mark a read direct message as unread (long press and click "mark unread")

### Expected behavior:
Show that it is unread with a blue numbered bubble

### Actual behavior:
Takes you back to the messages list and does not mark it as unread

### Server Setup Information:

- Version of Rocket.Chat Server: 6.7.1
- Operating System: Ubuntu
- Deployment Method: Snap
- Number of Running Instances: 1
- NodeJS Version: v14.21.2
- MongoDB Version: 5.0.15 / wiredTiger (oplog Enabled)

### Client Setup Information

- App version: 4.49.1.61642
- Operating System: Android

**Comment by reetp** [comment] 2024-06-11 09:15
Thanks for reporting. 

This is a ReactNative regression bug so should go here:

https://github.com/RocketChat/Rocket.Chat.ReactNative/issues

I do know that this is a known bug and is being addressed but I have no specific date for a fix.

Closing this here as it is not a bug in Rocket.Chat itself. You can try opening one in the react repo above and see what the developers say.

**Closed by reetp** 2024-06-11 09:15 UTC
Labels: wontfix, stat: solved
