### ISSUE TITLE
Room Controls

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#3498] opened 2016-06-08 19:41 UTC
would be good to have room controls per each room: 
1- turn off user joining announcement it can get annoying  - as it pushes text away..
![image](https://cloud.githubusercontent.com/assets/12454319/15908322/1a48f184-2d8f-11e6-92e4-4678ffaba8a8.png)

2- have the ability to select only few ppl to type in a room, i know we have mute feature but its hard to do it for one by one. maybe have option Mute All, and then select which user to have ability to type
3-  have room to show live video going on or not so ppl can join it

Your Rocket.Chat version: (0.33)

**Comment by Syirrus** [comment] 2016-06-09 06:41
I like the idea of having a live video feed in a channel that people can all watch in a single channel.

**Comment by matzegebbe** [comment] 2016-06-09 06:57
+1 this is what we need!
1. One channel all users can join to watch a live video stream
2. all users are muted by default
3. Moderators can read users muted messages and give them the ability to chat or publish selected messages
4. Remove System Messages (XY joined the channel)

**Comment by timkinnane** [comment] 2016-06-09 07:47
Agree with the above, just remember that the 'enter' message is used to trigger some responses with Hubot scripts. It would be good to be able to hide them by default as long as the enter message event still fires, or it could have unexpected consequences for integrations that depend on that event.

**Comment by timkinnane** [comment] 2016-06-09 07:50
This issue is partially a duplicate of #3418

**Comment by IQ2022** [comment] 2016-06-09 20:15
also would be good to have audio button to enable voice chat.. maybe ppl like to talk vs typing??? similar to pal talk, moderators can control that if needed??

**Comment by rasos** [comment] 2016-06-14 13:00
An option to hide all public channels functionality completely would be great as well, including hiding the menu on the left. User groups knowing WhatsApp and Telegram do not know the concept of public channels and find them confusing.

**Comment by timkinnane** [comment] 2018-04-16 03:53
This issue is very old and recent comments are off topic to the original concern. Closing now, but if you're interested in further discussion, please post to the forum under [Feature Requests](https://forums.rocket.chat/c/feature-requests).

**Closed by timkinnane** 2018-04-16 03:53 UTC
