### ISSUE TITLE
User LOGIN to Rocket Chat from Word press Website 

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2735] opened 2016-04-01 15:36 UTC
How would we enable single login from wordpress site, without getting prompted to login again into Rocket Chat  and what if we use SSO to login to a website, do we have to login again or sign up with rocket chat?

**Comment by engelgabriel** [comment] 2016-04-01 19:47
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/322

**Closed by engelgabriel** 2016-04-01 19:47 UTC
