### ISSUE TITLE
[FEATURE REQUEST/IMPROVEMENT] Alternating Chat Bubbles

### ISSUE THREAD

**Issue by Drangleic** [RocketChat/Rocket.Chat#10308] opened 2018-04-03 14:26 UTC
### Description:

One of the features we'd like to see is to have chats (both DMs and group chats) come from alternating sides of the window based on who is sending it. As in Google Hangouts (and numerous other chat applications), a user's own chats appear on the right hand side of the window, and chats from other users appear on the left. We would highly appreciate the ability to toggle this on or off (would be great if it was a user setting), as it really improves clarity and speed when reading chats. This is especially true if you are reading back through a long conversation.

Please let us know if you would like additional description as to what we're talking about, or if this should be posted elsewhere.

Thanks!

**Comment by TwizzyDizzy** [comment] 2018-04-04 15:18
@rocket-cat close

Hi @Drangleic 

First off: thank you for takting interest in Rocket.Chat and its improvement. Unfortunately though,I am closing this issue because this is a feature request. The usual procedure for feature requests is as follows:

* feature request is incoming via [the feature requests category in the forums](https://forums.rocket.chat/c/feature-requests)
* feature request is pre-approved by Rocket.Chat team member
* feature request is discussed and refined until it is utterly clear what is to be implemented and what is to be achieved by the feature request. Technical details might be part of this discussion
* feature is approved by Rocket.Chat team member (**or not** - then it will not be done - yet might still be done as a Rocket.Chat App by the community)
* feature request is transferred to github and labelled with "Feature: Planned"

Please understand, that we do not want to clutter Github with wishes and ideas as we have decided to use the forums for that.

When you compose a feature request in the forums, please ask yourself the following questions:

* is my feature request something that benefits everybody or at least a great amount of people
* is my feature request something that is technically possible (only if you have the expertise)
* [... maybe more?...]

This is also a duplicate of: #9681

Cheers
Thomas

**Closed by TwizzyDizzy** 2018-04-04 15:18 UTC
