### ISSUE TITLE
Ability to customize the loading indicator logo

### ISSUE THREAD

**Issue by mhndm** [RocketChat/Rocket.Chat#2011] opened 2016-01-23 10:30 UTC
Ability to customize the loading indicator logo : the content of the loading.html

**Comment by k0nsl** [comment] 2016-01-27 07:32
:+1:

**Comment by RichardFoxworthy** [comment] 2016-02-14 03:29
I can't find the file containing the 'loading' animation. Does not seem to live in the /public/images/ directory?

**Comment by k0nsl** [comment] 2016-02-14 03:37
@RichardFoxworthy 
https://github.com/RocketChat/Rocket.Chat/blob/152aabd035f1befca019b8bb342274ade739fda7/public/images/logo/icon-loader.svg

**Comment by RichardFoxworthy** [comment] 2016-02-14 03:55
thanks @k0nsl - I already tried replacing that file, and I still see the RocketChat spaceship loading animation. It must live somewhere else

**Comment by mrplow** [comment] 2016-02-15 19:20
Its animated, I think it may be embedded in some js or something because I can't find it either.

**Comment by RichardFoxworthy** [comment] 2016-02-21 03:22
@mrplow @k0nsl @mhndm  I found this: #1634. Would be nice to have an Admin interface control to modify this.

**Comment by engelgabriel** [comment] 2016-02-22 23:09
This is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/613

**Closed by engelgabriel** 2016-02-22 23:09 UTC
Labels: feat: app settings, type: improvement

**Comment by wathmal** [comment] 2016-06-07 17:41
you can customize the css if want. just override the `.rocket-loader` class in custom css field.
```
.rocket-loader {
    display: none;
}
```

**Comment by yuchaozh** [comment] 2016-06-13 13:36
@wathmal Where is the css file?

**Comment by wathmal** [comment] 2016-06-13 18:22
@yuchaozh you have to add the custom css via Administration section.
`Administration -> Layout -> Custom CSS`

**Comment by yuchaozh** [comment] 2016-06-16 19:27
@wathmal It works, Thanks!

**Comment by DavePS** [comment] 2016-09-04 17:47
My solution if you want a custom url

`.rocket-loader {
	display: block;
  	-moz-box-sizing: border-box;
  	box-sizing: border-box;
  	background: url(CUSTOM_IMG_URL) no-repeat;
  	width: 180px;
  	height: 236px;
  	padding-left: 180px;
}`

**Comment by rtest12** [comment] 2021-11-18 19:29
Apparently, in the latest versions something has changed, these methods did not work for me on 4.1. Does anyone have a solution?

**Comment by rtest12** [comment] 2021-11-29 18:01
```
.loading-animation {  
  background: url(https://example.com/images/preloader.gif)
  background-repeat: no-repeat;
  background-position: 50% 50%
}

#react-root .page-loading .loading-animation .bounce {
  display: none;
  height: 0px;
}
```
What am I doing wrong?
