### ISSUE TITLE
v4.7.1 not starting

### ISSUE THREAD

**Issue by ali-alhaidary** [RocketChat/Rocket.Chat#25512] opened 2022-05-14 02:35 UTC
● rocketchat.service - The mersaal server
   Loaded: loaded (/lib/systemd/system/rocketchat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2022-05-14 02:29:53 UTC; 1min 36s ago
  Process: 801 ExecStart=/usr/local/bin/node /opt/Rocket.Chat/main.js (code=exited, status=1/FAILURE)
 Main PID: 801 (code=exited, status=1/FAILURE)

May 14 02:29:53 mersaal rocketchat[801]:     at Module.load (internal/modules/cjs/loader.js:950:32)
May 14 02:29:53 mersaal rocketchat[801]:     at Module.Mp.load (/opt/Rocket.Chat/programs/server/runtime.js:46:33)
May 14 02:29:53 mersaal rocketchat[801]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
May 14 02:29:53 mersaal rocketchat[801]:     at Module.require (internal/modules/cjs/loader.js:974:19)
May 14 02:29:53 mersaal rocketchat[801]:     at require (internal/modules/cjs/helpers.js:93:18)
May 14 02:29:53 mersaal rocketchat[801]:     at Object.<anonymous> (/opt/Rocket.Chat/programs/server/npm/node_modules/@rocket.chat/forked-matrix-sdk-crypto-nodejs/lib/napi.js:24:11) {
May 14 02:29:53 mersaal rocketchat[801]:   code: 'ERR_DLOPEN_FAILED'
May 14 02:29:53 mersaal rocketchat[801]: }
May 14 02:29:53 mersaal systemd[1]: rocketchat.service: Main process exited, code=exited, status=1/FAILURE
May 14 02:29:53 mersaal systemd[1]: rocketchat.service: Failed with result 'exit-code'.

**Comment by pajkoLH** [comment] 2022-05-14 09:12
the same problem

**Comment by ali-alhaidary** [comment] 2022-05-14 09:48
@pajkoLH  any idea of what this error is about?

**Comment by dudanogueira** [comment] 2022-05-16 11:48
plase, check if this comment helps:
https://github.com/RocketChat/Rocket.Chat/issues/25396#issuecomment-1119036136

**Comment by ali-alhaidary** [comment] 2022-05-16 13:13
> plase, check if this comment helps: [#25396 (comment)](https://github.com/RocketChat/Rocket.Chat/issues/25396#issuecomment-1119036136)

@dudanogueira No, it did not help

**Comment by ankar84** [comment] 2022-05-17 04:52
related to https://github.com/RocketChat/Rocket.Chat/issues/25460

**Comment by geekgonecrazy** [comment] 2022-05-18 19:26
Duplicate of #25396 

Trying to work on a fix for this now

**Closed by geekgonecrazy** 2022-05-18 19:26 UTC
