### ISSUE TITLE
File upload inside E2E channels / direct messages

### ISSUE THREAD

**Issue by danielpotthast** [RocketChat/Rocket.Chat#32963] opened 2024-08-02 06:12 UTC
### Description:

Since 6.10.0, file uploads no longer work inside e2e channels or direct messages.

### Steps to reproduce:

1. Open an e2e encrypted channel or direct message conversation.
2. Drag and drop or click on "Upload file."
3. Select an attachment of your choice, e.g., a PNG image.
4. Click on "Send"

### Expected behavior:

The file should be uploaded (unencrypted) to the server and sent to the recipient.

### Actual behavior:

The file upload keeps reappearing / nothing happens.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.10.2
- License Type: Starter
- Number of Users: 15
- Operating System: Debian 12
- Deployment Method: tar
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: 14.21.3
- MongoDB Version: 7.0.12

### Client Setup Information

- Desktop App or Browser Version: Brave 1.68.128 (Chromium: 127.0.6533.73)
- Operating System: macOS 14.5

### Additional context

- When E2E is temporarily disabled, the file upload works.
- Media type whitelist (/admin/settings/FileUpload): `image/*,audio/*,video/*,text/*,application/zip,application/x-rar-compressed,application/pdf,application/msword,application/vnd.openxmlformats-*,application/xml,application/json,application/vnd.apple.*,application/svg+xml`
- Storage type: GridFS

### Relevant logs:

Browser-Network Log
Request URL: "https://domain.tld/api/v1/rooms.media/Z9o42DDYLJrXFKbTkcdqxKMmTtttLFbK9J"
Status Code: 400

Response:
```
{
    "success": false,
    "error": "File type is not accepted. [error-invalid-file-type]",
    "errorType": "error-invalid-file-type"
}
```

**Comment by trossner** [comment] 2024-08-02 07:19
We have the same problem.

**Comment by reetp** [comment] 2024-08-02 10:37
Thanks for reporting.

Couple of points

> Storage type: GridFS

You should never use GridFS in production. It is really for development only.

It will start to slow your system down as it grows. Use a proper file storage as recommended.


> Since 6.10.0, file uploads no longer work inside e2e channels or direct messages.

Can you clarify - does this refer to E2E DMs or plain ones?

This is likely related to:

https://github.com/RocketChat/Rocket.Chat/issues/31906

Several duplicates or similar issues around as well eg

https://github.com/RocketChat/Rocket.Chat/issues/32357

https://github.com/RocketChat/Rocket.Chat/issues/32754

I will ask the team to look.

**Comment by trossner** [comment] 2024-08-02 11:11
E2E DMs

**Comment by danielpotthast** [comment] 2024-08-02 11:52
> You should never use GridFS in production. It is really for development only.

Thanks for this note. I've migrated the uploads to the local file system.

> Can you clarify - does this refer to E2E DMs or plain ones?

I did some more research: DMs / Channels
 - E2E enabled + Media type whitelist defined = Not working (error-invalid-file-type occures)
 - E2E enabled + Media type whitelist undefined = Working
 - E2E disabled + Media type whitelist defined = Working
 - E2E disabled + Media type whitelist undefined = Working

If E2E is enabled, the file is transferred as `application/octet-stream`
<img src="https://github.com/user-attachments/assets/e1e8ca9c-1317-49af-a6ef-5c879578183d" width="auto" height="130" />

If E2E is disabled, the file is transferred as `image/gif`
<img src="https://github.com/user-attachments/assets/64e90ca5-4479-42fb-bde0-f1b15c0478f0" width="auto" height="130" />

**Comment by reetp** [comment] 2024-08-02 12:30
> Thanks for this note. I've migrated the uploads to the local file system.

NP.

If you haven't already there is a migrate script here somewhere in the repo that should copy all the existing stuff over as well.

> I did some more research: DMs / Channels

Thanks - I think this might have a fix already coming. Someone should respond to you in due course.

**Comment by himpierre** [comment] 2024-08-02 12:30
Yeah, same here. I already opened a support ticket because we are enterprise customers. Currently the support is on it wits end. I guess the devs have to take a look.

**Comment by himpierre** [comment] 2024-08-02 12:51
> E2E enabled + Media type whitelist undefined = Working

So you're saying when you have "E2E enabled + Media type whitelist undefined = Working" file upload works for you in e2ee channels? Just took a look. Media type whitelist is already empty on my installation. So it doesn't seem to help in every case.

**Comment by danielpotthast** [comment] 2024-08-02 12:56
> If you haven't already there is a migrate script here somewhere in the repo that should copy all the existing stuff over as well.

Thank you! I've already found this repo and moved all uploads to the file system + optimized the collection.

> So you're saying when you have "E2E enabled + Media type whitelist undefined = Working" file upload works for you in e2ee channels? Just took a look. Media type whitelist is already empty on my installation. So it doesn't seem to help in every case.

In some random cases nothing happens (no request is fired) but after a reload it’s working fine here.

**Comment by reetp** [comment] 2024-08-02 13:03
> Thank you! I've already found this repo and moved all uploads to the file system + optimized the collection.

OK thanks for letting us know.

**Comment by scuciatto** [comment] 2024-08-06 17:51
Can you please add `application/octet-stream` to the `Accepted Media Types` setting? This issue is happening because we cannot check the file type where the file is encrypted. We are working on a fix for this but, this should work as a workaround.

**Comment by himpierre** [comment] 2024-08-07 06:55
> Can you please add `application/octet-stream` to the `Accepted Media Types` setting? This issue is happening because we cannot check the file type where the file is encrypted. We are working on a fix for this but, this should work as a workaround.

This seems to make it worse. I get "Media Type Not Accepted" when trying to upload a png after setting that.

**Comment by himpierre** [comment] 2024-08-07 07:01
Ok, I guess I have to *add* this to already existing entries. But that doesn't work either. Smae pictures as before.

**Comment by danielpotthast** [comment] 2024-08-21 12:12
If I use the mobile app (iOS, v4.50.1.63099) it’s not possible to upload files into encrypted channels or DMs.
I get an "Error uploading <filename> Try again"-error.

**Closed** 2024-08-23 02:34 UTC
Labels: stat: waiting response, Tasked

**Comment by reetp** [comment] 2024-08-30 10:27
It hasn't been mentioned but the previous poster tested on 6.12.rc1 and still suffered the same issue on iphone so I am not sure this is fixed? This may need to be re-opened.

His own bug was here:

https://github.com/RocketChat/Rocket.Chat/issues/33143

**Comment by himpierre** [comment] 2024-08-31 12:39
For the record. File upload in e2e encrypted channels ( backend is webdav ) works for me with 6.12.0.rc.2.

Am 30. August 2024 12:28:09 MESZ schrieb John Crisp ***@***.***>:
>It hasn't been mentioned but the previous poster tested on 6.12.rc1 and still suffered the same issue on iphone so I am not sure this is fixed? This may need to be re-opened.
>
>His own bug was here:
>
>https://github.com/RocketChat/Rocket.Chat/issues/33143
>

**Comment by reetp** [comment] 2024-08-31 13:11
> backend is webdav 

Hi ;-)

Wonder if that has any bearing on things?

**Comment by Gummikavalier** [comment] 2024-09-06 07:10
I confirm uploading anything in direct E2EE session is flaky in RC 6.12.0.

You get the modal/upload window, you type in the name of the file, and sometimes it works but mostly nothing happens.

No limitations to possible upload types under the admin settings, so it is not that streaming type issue either.

Often after pressing return or send, canceling out of the upload window and then sending a new regular message, triggers the previous file upload process.

Also sometimes when there has not been any reaction, you can still find new uploaded files under the files list on the channel.

This has been like this for us since the E2EE file uploads were introduced.

**Comment by hrabotoner** [comment] 2024-09-24 12:40
The issue is closed but we are experiencing this on a self-hosted Rocket.Chat version 6.12.1 deployed on Docker. If E2E is enabled, uploaded files cannot be downloaded (tooltip says `Download disabled`) and uploaded images display a `Retry` error text. Once you disable E2E and reupload, it works fine.

What is the solution to this?
