### ISSUE TITLE
[QUESTION] How to make colorful channel buttons?

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat#11260] opened 2018-06-26 07:41 UTC
- Version of Rocket.Chat Server:  0.65.2
- Operating System:  Debian 8
- Deployment Method:  tar
- Number of Running Instances:  1
- NodeJS Version:  v8.11.1
- MongoDB Version:  v3.2.20

From version to version, the color of the channel buttons does not change. How can I fix it and make the multicolored buttons?

![screenshot-chat tarasov co-2018 06 26-10-33-41](https://user-images.githubusercontent.com/18574776/41896395-284acc9e-792d-11e8-856d-f8db5817e627.png)

**Comment by itskenny0** [comment] 2018-06-26 14:35
I use custom CSS. This is not the optimal solution, but it works very well.

```
/* Special rooms */
[title^="production-"] { 
  background: linear-gradient(to right, rgba(173,0,0,0) 3%,rgba(173,0,0,0.39) 15%,rgba(88,83,83,0) 57%,rgba(0,168,168,0) 100%);
}
```

**Comment by vynmera** [comment] 2018-06-26 14:54
Probably a duplicate of #3582 ?

**Comment by Pitstopper** [comment] 2018-06-26 15:36
@itskenny0 Thanks for your solution, it's cool! But I meant a little not that. I would like to turn on the coloring channels avatars in different colors as on https://open.rocket.chat, but I do not know how to do it. I did't find this option in the settings.

![screenshot-open rocket chat-2018 06 26-18-30-05](https://user-images.githubusercontent.com/18574776/41923294-be826bee-796f-11e8-9cd0-7c66ee0a79cd.png)

**Comment by Pitstopper** [comment] 2018-06-26 15:46
@vynmera Hi! It does not look like a duplication in my opinion.

**Comment by vynmera** [comment] 2018-06-26 16:29
@Pitstopper That issue basically asks for the ability to set custom icons for channels, so you could add a different colored icon there. Is that what you're looking for?

**Comment by Pitstopper** [comment] 2018-06-26 16:45
@vynmera Thank you for the clarification!

**Closed** 2018-06-26 16:46 UTC
