### ISSUE TITLE
Option to Remove Users from Rooms

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#1567] opened 2015-12-03 18:40 UTC
We can Create rooms and Add users, but we can't remove them, this feature is needed.

Also this will help in issues open requesting Premium Chat rooms, i.e enable users join when they are signed up for that room specific room  (membership)

**Comment by sampaiodiego** [comment] 2015-12-03 19:34
duplicate of #1093

**Closed by sampaiodiego** 2015-12-03 19:34 UTC
Labels: feat: channel settings, type: new feature
