### ISSUE TITLE
Allow File Sharing in LiveChat

### ISSUE THREAD

**Issue by ArjunBhatt** [RocketChat/Rocket.Chat#7543] opened 2017-07-22 09:56 UTC
Is it possible in LiveChat to share files between Agent and Guest?

### Expected behavior:
I think, this feature is more important then other features.

### Actual behavior:
In version 0.56.0, I didn't find a way to share file between Agent and Guest.

**Comment by sampaiodiego** [comment] 2017-08-03 12:34
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/3686

**Closed by sampaiodiego** 2017-08-03 12:34 UTC
Labels: feat: file sharing, feat: livechat, type: new feature

**Comment by naamaan** [comment] 2018-04-10 13:47
Hi,
I'd installed the latest version using snap behind Nginx for SSL, and I'm using the livechat integrated in Drupal 7 test website.

Everything is okay But I found that the file-sharing feature is not yet implemented in the livechat widget!?

What should I do to get it working? I really need this feature in my case!

**Comment by sampaiodiego** [comment] 2018-04-10 16:06
file sharing is not done yet.. but we plan to ship on next version by april 27th

**Comment by renatobecker** [comment] 2018-04-10 16:09
Hi @naamaan, 

Just to give you an update, we're working on this feature at this moment, so I suggest you wait for the next version(0.64).

**Comment by naamaan** [comment] 2018-04-10 16:43
It's a relieve to know this, I was afraid I'm missing something. 
Thanks a lot.

**Comment by naamaan** [comment] 2018-04-29 08:05
Hi,
I'm seeing that the version(0.64) is released here in GitHub, when it's expected to be available for the snaps packages?!
OR should I refresh the installation manually ?
Best regards,

**Comment by naamaan** [comment] 2018-05-13 13:10
Hi again,

Following up with issue #10656, I updated my installation to **v 0.64.1 beta**, But still don't have the ability to attach files in the live-chat !! 

Is there any special settings for this thing?

Regards,

**Comment by renatobecker** [comment] 2018-05-14 15:03
Hi @naamaan.
The PR that provides this feature is still awaiting review.
You can take a look at PR #10514 to follow the review process.
Thanks.

**Comment by naamaan** [comment] 2018-05-15 13:00
Thanks a lot @renatobecker 
Will follow up.
Regards,
