### ISSUE TITLE
How to turn off email notifications completely for all users/channels etc

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat#8789] opened 2017-11-06 09:47 UTC
* Version of Rocket.Chat Server: 0.59.3

Is there a setting to turn off the email notifications for all users sent from either DM/Channels when mentioned in that channel etc.

**Comment by MartinSchoeler** [comment] 2017-11-06 12:42
Duplicate of #8568

**Closed by MartinSchoeler** 2017-11-06 12:42 UTC

**Comment by mmarif4u** [comment] 2017-11-08 02:28
I guess this issue is not directly related to that. That is a bug, this one is more like a question. If there is a global setting which will just turn off the whole email notifications for all and everything.

Why i am asking this, because i have blocked and deactivated users in a channel, but they still receive emails if used `@all` which somehow means DM. But if that issue(PR) fix the issue, then this issue can be remain closed.
