### ISSUE TITLE
[sandstorm] Uploading files yields broken link

### ISSUE THREAD

**Issue by maurer** [RocketChat/Rocket.Chat#1327] opened 2015-11-03 22:04 UTC
When running as a sandstorm grain, uploading files yields a broken link to the loopback device, e.g.
http://127.0.0.1:8000/ufs/rocketchat_uploads/bwaSyyEohcgxoTrCB.png

**Comment by Sing-Li** [comment] 2015-11-04 16:04
Closing this as it is a duplicate of #910

**Closed by Sing-Li** 2015-11-04 16:04 UTC
Labels: --> Sandstorm <--
