### ISSUE TITLE
Can't login with sAMAccountName with "Login Fallback: false" 

### ISSUE THREAD

**Issue by thinhnd8752** [RocketChat/Rocket.Chat#8707] opened 2017-10-30 09:59 UTC
### Description:

We can not login after setting Login Fallback: **false** in LDAP.

### Server Setup Information:

* Version of Rocket.Chat Server:  0.59.1
* Operating System: 
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances:  1
* DB Replicaset Oplog: 0
* Node Version: v4.8.4

### Steps to Reproduce:

LDAP --> Login Fallback: **false**
LDAP --> Sync User Avatar: **false**

### Expected behavior:

- Can login with username and password from Active Directory
- If user deleted in Active Directory, they can not login anymore by rocket chat local password

### Actual behavior:

- We can not login by username or mail, even with Active Directory password or local password.

### Relevant logs:

web_1  | LDAPHandler ➔ info Init LDAP login user01
web_1  | LDAP ➔ Connection.info Init setup
web_1  | LDAP ➔ Connection.info Connecting ldap://auth.example.local:389
web_1  | LDAP ➔ Connection.info LDAP connected
web_1  | LDAP ➔ Bind.info Binding UserDN cn=Administrator,cn=Users,dc=example,dc=local
web_1  | {"name":"ldapjs","component":"client","hostname":"34b4274ddc21","pid":1,"clazz":"Client","ldap_id":"2588__ldap://auth.example.local:389","level":20,"msg":"connected after 1 attempt(s)","time":"2017-10-30T09:43:39.776Z","v":0}
web_1  | LDAP ➔ Search.info Searching user user01
web_1  | rocketchat_logger rocketchat_logger.js:375 LDAPHandler ➔ error [Error: ) is invalid]
web_1  | LDAP ➔ Search.info Idle
web_1  | LDAP ➔ Connection.info Disconecting
web_1  | LDAP ➔ Search.info Closed

**Comment by Gummikavalier** [comment] 2017-11-05 09:58
We have both Login Fallback and Sync User Avatar at 'false', and LDAP and authentication works for us with sAMAccountName. We use Active Directory and our RC version is 0.59.3.

Assuming that you had Login Fallback still enabled when you first tried to synced your users, if you remove your test user account from RC, sync them again in LDAP settings and then try to login, does it succeed then?
This just in case that the problem is triggered by having old locally saved user credentials on the server.

**Comment by pierre-lehnen-rc** [comment] 2020-04-14 17:48
Closing as obsolete.

**Closed by pierre-lehnen-rc** 2020-04-14 17:48 UTC
Labels: subj:  Auth - LDAP
