### ISSUE TITLE
Display most recent direct messages

### ISSUE THREAD

**Issue by zorenleo** [RocketChat/Rocket.Chat#4821] opened 2016-11-02 03:09 UTC
Display most recent direct messages on the left sidebar navigation.

**Comment by MartinSchoeler** [comment] 2016-12-07 10:49
duplicate of #4377

**Closed by MartinSchoeler** 2016-12-07 10:49 UTC
Labels: subj: ui/ux, type: new feature

**Comment by rameshpandian26** [comment] 2017-02-14 13:40
what the files involved to fix this issue? can you help me to send the code for sort the direct recent message  at the top?
