### ISSUE TITLE
Option to Show available Emoji

### ISSUE THREAD

**Issue by IQ2022** [RocketChat/Rocket.Chat#2475] opened 2016-03-11 14:44 UTC
Is there anyway to enable have a list to pick from available Emoji, vs guessing them?

![image](https://cloud.githubusercontent.com/assets/12454319/13705235/e9bdd258-e76d-11e5-99f5-1ec2ba3fceef.png)

Your Rocket.Chat version: 0.21

**Comment by sampaiodiego** [comment] 2016-03-11 16:24
duplicate of #480

actually, #480 was prioritized and will be done in the next weeks =)

**Closed by sampaiodiego** 2016-03-11 16:24 UTC
