### ISSUE TITLE
File upload problem

### ISSUE THREAD

**Issue by Ukas9** [RocketChat/Rocket.Chat#6679] opened 2017-04-13 10:29 UTC
Hey there,

I've got problem with file upload.

Quick info:
```
Rocket.Chat Version: 0.55.0-rc.3
Running Instances: 1
DB Replicaset OpLog: Disabled
Node Version: v4.5.0
Debian 9.0
Apache v.2.4.25
```
Apache SSL Reverse Proxy conf file:
```
<VirtualHost *:443>

ServerName domain.com

SSLEngine On
SSLCertificateFile /etc/ssl/certs/domain.com.crt
SSLCertificateKeyFile /etc/ssl/private/domain.com.key

<Location /var/www/Rocket.Chat/>
        Order allow,deny
        Allow from all
</Location>

RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /chat/(.*)           ws://localhost:3000/chat/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket [NC]
RewriteRule /chat/(.*)           http://localhost:3000/chat/$1 [P,L]

ProxyPass /chat/ http://localhost:3000/chat/
ProxyPassReverse /chat/ http://localhost:3000/chat/
</VirtualHost>
```

I tried to use GridFS and FileSystem but nothing works well. All time file stucks on 0%.
I also tried to edit jalik_ufs.js file, in order to change storesPath to chat/ufs according to https://github.com/jalik/jalik-ufs/tree/v0.6.4#configuration. After that the progress bar comes to 100%, but after I receive internal server error and nothing happens.

Rocket.Chat logs with `storesPath = chat/ufs`:
```
{ [Error: ENOENT: no such file or directory, open '/tmp/ufs/naTNBxCzPkxCM8T55']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/ufs/naTNBxCzPkxCM8T55' }
[Error: FileNotFound: no file with id naTNBxCzPkxCM8T55 found]
Exception while invoking method 'ufsComplete' Error: ENOENT: no such file or directory, open '/tmp/ufs/naTNBxCzPkxCM8T55'
  at Object.Future.wait (/var/www/Rocket.Chat/programs/server/node_modules/fibers/future.js:449:15)
  at [object Object].Meteor.methods.ufsComplete (/var/www/Rocket.Chat/programs/server/packages/jalik_ufs.js:818:24)
  at [object Object].methodsMap.(anonymous function) (/var/www/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1069:26)
  at [object Object].methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
  at maybeAuditArgumentChecks (/var/www/Rocket.Chat/programs/server/packages/ddp-server.js:1823:12)
  at /var/www/Rocket.Chat/programs/server/packages/ddp-server.js:905:20
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /var/www/Rocket.Chat/programs/server/packages/ddp-server.js:904:41
  at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
  at /var/www/Rocket.Chat/programs/server/packages/ddp-server.js:903:46
  at [object Object]._.extend.protocol_handlers.method (/var/www/Rocket.Chat/programs/server/packages/ddp-server.js:876:21)
  at /var/www/Rocket.Chat/programs/server/packages/ddp-server.js:755:85

    - - - - -
  at Error (native)
```

**Comment by rodrigok** [comment] 2017-04-17 19:43
This issue was not introduced by the new version.

The problem is related with sub folder.

More info: https://github.com/jalik/jalik-ufs/issues/104

**Comment by rodrigok** [comment] 2017-04-17 19:44
The problem is relater with this line https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-lib/lib/startup/settingsOnLoadSiteUrl.coffee#L10 where we override the ROOT_URL removing the sub folder

**Comment by lostinblue** [comment] 2017-05-13 14:01
Need additional information to help, like what is the folder permissions, are you running as privileged or unprivileged, is it only affecting the file upload? Do avatar uploads work, if so, are they also GridFS?

**Comment by JohnDorien1** [comment] 2017-05-16 11:13
Same issue when running in sub dir. Any workaround or update on this?

**Comment by muus84** [comment] 2017-05-17 09:19
Same issue here with docker 0.56

**Comment by mfueser** [comment] 2017-05-18 13:23
After Update to 0.56 our upload stopped working completely. Permissions are unchanged. Both GridFS and Filesystem do not work.

**Comment by wisnutri** [comment] 2017-06-11 15:28
Same issue with 0.56 with nginx on centos. Updating to 0.57.0-rc.1 no fix for this problem.

**Comment by bmduarte** [comment] 2017-06-15 21:01
Same issue with 0.56. Upload is stuck at 0%.
Each time I tested an upload got this error at server side:
[Error: FileNotFound: no file with id TNfedy2KB5X7uy8vE found]

Changed from GridFS to FS, tested with several filesystem setup (different paths, different permissions).
Nothing works.

**Comment by marcelogomess** [comment] 2017-07-03 20:34
I'm using Nginx with multiple instances. When i put in upstream de ip_hash instead round-robin(default);
The file stay complete, but when i save de file he come without extension;
 upstream rocket{
        ip_hash;
        server 192.168.55.41:3001;
        server 192.168.55.41:3002;
        server 192.168.55.41:3003;
        server 192.168.55.41:3004;
    }

**Comment by ryoshimizu** [comment] 2017-07-04 09:55
@rodrigok kindly review

**Closed** 2017-07-14 19:27 UTC
Labels: feat: file sharing, type: support

**Comment by ledainam** [comment] 2017-09-20 10:14
i have a same issue. 
i run rocketchat instance at root folder not a sub folder.
- when upload by mobile app or sometime by web app , it stuck at 0%
workaround : run only 1 instance will solve this issue. 
- when download attachment is missing extension
i saw that it is a client bug , report at : https://github.com/RocketChat/Rocket.Chat.Electron/issues/536

**Comment by scottalanmiller** [comment] 2018-06-27 14:50
Same issue, multiple installs.  Any progress?  This seems to be a never ending, and ultimately probably pretty basic, issue to resolve?

**Comment by christophetd** [comment] 2018-07-27 08:34
Any update on this issue?

**Comment by john8647** [comment] 2018-08-09 11:17
I had this issue.   The solution for me was incorrect url still set to - ROOT_URL=http://docker:3000 which can't work with uploading images if you mapped IP address and didn't change it.      After a while the client (admin) is prompted to change the site URL 
![image](https://user-images.githubusercontent.com/26795346/43895688-0e147bea-9bce-11e8-9bd7-d6198344fc3a.png)
that fixed it by itself for me.

**Comment by farzadso** [comment] 2019-06-02 10:22
Thanks @john8647 

For me it was an admin changing `https` to `http` in Rocket Chat settings. Unfortunately this dialog wouldn't show itself on the MacOS app, and opening up the Web version revealed the error and the fix.
