### ISSUE TITLE
Saving a file to RC causes two notifications for the same file

### ISSUE THREAD

**Issue by drickerusa** [RocketChat/Rocket.Chat#5694] opened 2017-01-20 17:05 UTC
Rocket.Chat Version: 0.49.3
Running Instances: 4
DB Replicaset OpLog: yes
Node Version:

When I drag and drop or browse and save the file notification comes up with two saving notification bars instead of one. The file is only saved once and the initial save bar cleared out. The second bar just sits there until you cancel it.

![duplicate file save bar](https://cloud.githubusercontent.com/assets/21371983/22157879/dc62c614-def6-11e6-9713-2d5eb1731532.JPG)

**Comment by TheReal1604** [comment] 2017-01-20 17:11
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/5661

**Comment by rodrigok** [comment] 2017-01-20 20:45
@drickerusa Is this happening always?

**Closed** 2017-01-20 21:00 UTC
Labels: feat: file sharing
