### ISSUE TITLE
Allow to clear channel history manually und timed

### ISSUE THREAD

**Issue by cbajohr** [RocketChat/Rocket.Chat#2834] opened 2016-04-11 11:11 UTC
Your Rocket.Chat version: 0.25.0

Like Hipchat, it should be possible for administrators to clear the history of a channel and/or to set an optional and relative time limit for keeping messages, like 1 month.

**Comment by prohde** [comment] 2016-04-11 13:12
+1

**Comment by engelgabriel** [comment] 2016-04-12 12:58
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/1861
Related to https://github.com/RocketChat/Rocket.Chat/issues/2196

**Closed by engelgabriel** 2016-04-12 12:58 UTC
