### ISSUE TITLE
Expose search term filters

### ISSUE THREAD

**Issue by danieljhochman** [RocketChat/Rocket.Chat#7859] opened 2017-08-24 13:09 UTC
In #4320 some amazing search filters were added, but users do not know they exist. As proposed then, something like this should be added to show users what the possible search features are:

![image](https://user-images.githubusercontent.com/23452628/29667823-88bb4b86-88e6-11e7-8924-0fde26eb0967.png)

**Comment by alfredbez** [comment] 2018-07-27 10:57
duplicates #4406

**Comment by Hudell** [comment] 2018-08-14 14:27
Closed as duplicate of #4406

**Closed by Hudell** 2018-08-14 14:27 UTC
Labels: subj: ui/ux

**Comment by madguy02** [comment] 2018-08-15 20:19
#11789
