### ISSUE TITLE
Enhancement : Customer should not see a message that his chat was returned to Queue

### ISSUE THREAD

**Issue by nitinsonawane234** [RocketChat/Rocket.Chat#33459] opened 2024-10-04 10:31 UTC
While support agent mark return to queue on a perticular ongoing chat, it shows on client side that "xyz retured the chat to the queue". It should not see a message that his chat was returned to Queue.

**Comment by reetp** [comment] 2024-10-04 12:56
Closing as this is not a bug in Rocket.Chat

Please open in the correct repository

https://github.com/RocketChat/feature-requests

**Closed by reetp** 2024-10-04 12:56 UTC
