### ISSUE TITLE
im.messages.other REST endpoint returns "[error-endpoint-disabled]"

### ISSUE THREAD

**Issue by EnNico** [RocketChat/Rocket.Chat#18748] opened 2020-08-31 14:44 UTC
### Description:

I need to view the history of a direct message between 2 other users. As stated in the docs, `Enable Direct Message History Endpoint` setting must be true and the `view-room-administration` permission must be set. Which i have done, but when i call the API through Postman i get a 400 response:
```json
{
    "success": false,
    "error": "This endpoint is disabled [error-endpoint-disabled]",
    "errorType": "error-endpoint-disabled",
    "details": {
        "route": "/api/v1/im.messages.others"
    }
}
```

Why is the endpoint still disabled? The permission and setting is set.

### Steps to reproduce:

1. Set permission and setting to enable endpoint
2. Make http request to api/v1/im.messages.others?roomId={roomId} using personal access token as authorization

### Expected behavior:

History of the messages of the direct message

### Actual behavior:

Failing request

### Server Setup Information:

- Version of Rocket.Chat Server: 3.6.0
- Operating System: Ubuntu
- Deployment Method: Docker Compose
- Number of Running Instances: 1
- NodeJS Version: 12.16.1
- MongoDB Version: 4.0.19

### Client Setup Information

- Desktop App or Browser Version: Browser
- Operating System: Windows 10

**Comment by FelipeParreira** [comment] 2020-09-14 12:59
Hi, @EnNico! Thank you for the issue 👍 

I was not able to reproduce the supposed bug locally. :(

The error message you are getting occurs when the `API_Enable_Direct_Message_History_EndPoint` from the admin settings is not set to `true` (check out the source code [here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/api/server/v1/im.js#L253-L257), if you are interested).

I have a question for you to help us find where the issue lies:

Did you update the `Enable Direct Message History Endpoint` setting in the admin panel (in the `general` section, and `api` subsection)? You need to turn it on and then save the changed setting, by clicking the button in the top-right corner of the screen so that it takes effect.

**Comment by EnNico** [comment] 2020-09-15 06:33
Hi @FelipeParreira, oh yes that makes sense, I guess i was confused because the doc says "setting" for  and in the `permission` section there is a tab `setting` which has the meant configuration. I just saw that it is the same setting though, because the setting tab points right to `General > REST API > Enable Direct Message History Endpoint`, but there might be a problem with saving it because it was disabled when i moved to the general settings. 
Now it works, thanks!

**Comment by FelipeParreira** [comment] 2020-09-15 10:31
I am going to close this issue for now, but I have made a PR to improve our docs. Let us know if you think it is easier to understand them now (and maybe we can move the discussion [there](https://github.com/RocketChat/docs/pull/1787)).

**Closed by FelipeParreira** 2020-09-15 10:31 UTC
Labels: stat: need more info
