### ISSUE TITLE
Off-the-Record (OTR) Timeouts

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#2535] opened 2016-03-17 15:37 UTC
Your Rocket.Chat version: 0.22.0

When trying to engage a user and initiate a OTR exchange it always results in a timeout, no matter how quickly you push the "yes" button.

Does anyone else experience the same issue?

**Comment by engelgabriel** [comment] 2016-03-18 13:36
Do you see anything in the console log?

**Comment by marceloschmidt** [comment] 2016-03-18 14:06
We could increase the time limit... it's currently set at 10s. Does it timeout before that period, or does it timeout a few seconds after you push the yes button?

**Comment by k0nsl** [comment] 2016-03-18 14:10
@engelgabriel: there is nothing in the console log.

@marceloschmidt: it timeouts before the 10s period; I would say within a maximum of 5 seconds.

**Comment by marceloschmidt** [comment] 2016-03-18 14:12
@k0nsl what's your browser and version?

**Comment by k0nsl** [comment] 2016-03-18 14:14
@marceloschmidt: Chromium. Version 48.0.2564.116. Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit).

**Comment by marceloschmidt** [comment] 2016-03-18 16:47
@k0nsl do you have access to code in `develop`? I just pushed some code that makes OTR use jwk for key exchanging, instead of spki. I'm not sure that this was the cause for your bug, but I know it was causing some problems when exchanging keys between firefox and chrome... Let me know if it fixes for you. If it doesn't, please check the console for bugs.

**Comment by k0nsl** [comment] 2016-03-18 16:54
@marceloschmidt: yes, I'm using `develop`. I can probably pull the new code later, in perhaps five hours. 

I will report back whether or not it fixed my issue. Thanks!

**Comment by k0nsl** [comment] 2016-03-18 16:57
I noticed something, by the way, in my console, when trying to negotiate OTR between myself and another client. Here's the output:
`Uncaught (in promise) DOMException`

**Comment by marceloschmidt** [comment] 2016-03-18 16:58
Ahh! That's exactly the same problem I was having when testing Firefox and Chrome key exchange. I'm more convinced that the fix I pushed will solve it for you then.

**Comment by k0nsl** [comment] 2016-03-21 09:34
@marceloschmidt:

Sorry for the late reply. I upgraded my instance with the newest code in `develop` and now OTR is (seemingly) working again.

**Comment by marceloschmidt** [comment] 2016-03-21 11:54
Good to know. I'll close this issue and monitor any new problems we may have with OTR

**Closed by marceloschmidt** 2016-03-21 11:54 UTC
Labels: type: bug

**Comment by punkrock** [comment] 2016-04-12 14:24
We are using 0.25.0 and I've still problems, using OTR. If I start an OTR-conversation with an user who is online, I only get timeouts. In some cases he could accept the conversation and wrote encrypted messages to me, but I couldn't read them, because I only get timeouts. And some requests about starting an OTR-conversation end up in nirvana, means my chat partner doesn't even see the request because of the timeout.

**Comment by serphacker** [comment] 2016-05-27 16:20
same issue here with 0.31. However we managed to make it works after trying multiple times. Maybe it's due to first time key generation which may take some times?

**Comment by wtsarchive** [comment] 2016-07-23 19:12
@marceloschmidt I also get "timeout" error when trying to initiate OTR conversations, even if I click on "OK" button immediately. How can I debug this? I'm using version 0.31.0.

**Comment by wtsarchive** [comment] 2016-07-23 19:13
Btw, I'm using OSX app for Rocket Chat and the other party used Chrome.

**Comment by engelgabriel** [comment] 2016-07-24 19:38
@wtsarchive can you try using the lates version? Are both users online at the same time, and using the same browser? (just to eliminate some root causes)

**Comment by marceloschmidt** [comment] 2016-07-26 13:31
@wtsarchive please try using OTR in our demo server, so we can also eliminate some browser issues. Please join us on https://demo.rocket.chat/channel/otr and let's talk there.

**Comment by fulljackz** [comment] 2016-08-25 12:39
Same here, unable to get OTR work properly, Version: 0.37.1

On the demo too : Timeouts :disappointed:

**Comment by brady-young** [comment] 2016-10-13 21:42
I'm having this issue as well.  Time outs even after the user accepts the OTR.
![otr](https://cloud.githubusercontent.com/assets/22377631/19368083/97f8af4a-915b-11e6-879f-71ce1e11516c.png)
![redotr](https://cloud.githubusercontent.com/assets/22377631/19368084/97fcc076-915b-11e6-81f5-5e99663506ad.png)
![rocketchat timeout](https://cloud.githubusercontent.com/assets/22377631/19368085/98012972-915b-11e6-8132-bdb4dc60d525.PNG)

**Comment by punkr0ck** [comment] 2017-08-24 12:58
Why is this closed? It's still an issue. OTR doesn't work. I always get "Timeout", when trying to start it in a conversation.

**Comment by punkrock** [comment] 2017-10-25 11:59
It works for me, if my conversation partner accepts OTR request within 3 seconds. Sadly, OTR in RocketChat doesn't support sending images or editing.

**Comment by qchn** [comment] 2021-02-11 12:56
This bug is still a thing with the latest version (3.11.1)
Thanks for sharing your workaround with us, @punkrock. Sadly, this workaround is not working with our Rocket.Chat instance.
