### ISSUE TITLE
Unread count issue

### ISSUE THREAD

**Issue by KevalGajjar-1** [RocketChat/Rocket.Chat#24947] opened 2022-03-25 10:56 UTC
Hi there, I found a small issue in the rocket chat app, In the below screenshot you can see that there is showing 1 unread count in the sidebar and thread so basically the user delete the thread but I didn't see that's why it is showing. so can you please look into this? Here are the steps to produce this issue

Step 1: Person 1 send a message to Person 2
Step 2: Send a message in thread in by person 2
Step 3: Send a reply again from Person 1 but do not read from Person 2
Step 4: Delete thread from person 1 then the unread count will not remove from person 2

![Screenshot 2022-03-23 at 12 28 40 PM](https://user-images.githubusercontent.com/70438122/160107348-e72d7130-90b3-4078-a5f0-ca414616d714.jpg)

**Comment by vinzv** [comment] 2022-05-19 10:35
I can confirm that behavior at least up to RC v4.7.1.

**Comment by KevalGajjar-1** [comment] 2022-05-28 09:27
Hi, You might resolve issue for new users or new thread conversation, but it is still same for old

**Comment by Kyogre** [comment] 2022-07-01 06:25
I suppose it is duplicate of https://github.com/RocketChat/Rocket.Chat/issues/25656

**Comment by milton-rucks** [comment] 2023-01-18 17:07
Resolved on https://github.com/RocketChat/Rocket.Chat/pull/26754

**Closed** 2023-01-18 17:07 UTC
