### ISSUE TITLE
preventing mentioned people from being pulled in room where mentioned

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat#4286] opened 2016-09-13 12:42 UTC
RC 0.39.

Hello Devs.

Is it possible to deactivate that function i mentioned in the subject? Every now and then people asking for not being pulled in the room where mentioned.

thanks and keep up the good work
t.

**Comment by alexandrezia** [comment] 2016-09-26 21:09
We would like this too, every time we mention someone he is invited to the room.
It would be awesome if we could activate/deactivate this as a toggle

**Comment by alexandrezia** [comment] 2016-09-26 21:18
Even more awesome if rocketchat asks if the user being mentioned should be invited to the channel or not.

**Comment by engelgabriel** [comment] 2019-04-01 17:34
this is a duplicate of https://github.com/RocketChat/Rocket.Chat/issues/2194

**Closed by engelgabriel** 2019-04-01 17:34 UTC
Labels: Feature: Planned
