### ISSUE TITLE
Message report option can't be turned off

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [RocketChat/Rocket.Chat#22682] opened 2021-07-16 08:09 UTC
![scr](https://user-images.githubusercontent.com/76442625/125914715-3ebb9a48-0533-4dd4-9dea-104c62d7e41a.png)

**Comment by johncrisp** [comment] 2021-07-16 11:12
Hi and thanks for reporting this.

Please help us by always filling out the issue template here after you have followed the instructionson rpeorting issues

https://rocket.chat/docs/contributing/reporting-issues

https://github.com/RocketChat/Rocket.Chat/issues/new?assignees=&labels=&template=bug_report.md

Please always test this on the latest version as issues are fixed regularly.

I have a feeling that this does not have a configuration switch in which case this is a feature request, not a bug because there is no error. It just doesn't do what you want it to.

Please confirm on the latest version and I can move it to the correct repo.

**Comment by debdutdeb** [comment] 2021-07-18 08:31
Closing this since it's not a bug as John already stated. Please follow the template and create an appropriate issue on our feature-requests repository -

**https://github.com/RocketChat/feature-requests**

For community support, please consider our forum or open server -

**https://open.rocket.chat/channel/support**
**https://forums.rocket.chat**

Thanks :)

**Closed by debdutdeb** 2021-07-18 08:31 UTC
