### ISSUE TITLE
Disable Direct Message functionality for Users

### ISSUE THREAD

**Issue by mguspero** [RocketChat/Rocket.Chat#2985] opened 2016-04-21 17:05 UTC
Your Rocket.Chat version: 027.0
Hi, is possible to block direct messages from some users or to all the users and only permit the use of private groups?
Thanks & Regards!

**Comment by marceloschmidt** [comment] 2016-04-29 23:47
Yes, you may remove their permission to `view-d-room`.

**Comment by insidesmart** [comment] 2016-04-30 03:21
@marceloschmidt If a user knows the direct link to a person (https://demo.rocket.chat/direct/marcelo.schmidt) I think he can still do a direct message. Is there a way to block this and allow only private groups securely.

**Comment by marceloschmidt** [comment] 2016-04-30 09:48
Ah I see. Maybe we need to create a new permission for this then. I'll reopen the issue and work on it soon. Thank you for the feedback.

**Comment by insidesmart** [comment] 2016-05-01 03:13
Thanks @marceloschmidt . This would be super helpful if it lands in a near future release.

**Comment by MichaelSavin** [comment] 2016-05-11 13:53
Same issue: https://github.com/RocketChat/Rocket.Chat/issues/1311

**Comment by MichaelSavin** [comment] 2016-05-11 13:58
@marceloschmidt  `view-d-room` - what does it mean? Is any UI for this?

**Comment by geekgonecrazy** [comment] 2016-05-11 17:34
For sure a dupe of #1311 i'll edit the title there to make it easier to find

**Comment by insidesmart** [comment] 2016-05-13 10:05
@geekgonecrazy I think #1311 talks about blocking individual users to do direct messages while #2985 is about disabling DMs for all users. If you feel these are different, may be we should keep this issue open.

**Comment by mguspero** [comment] 2016-05-13 14:07
Hi everyone, I think that would be very good to administer the permissions of DM per groups of users and best of all would be for groups of active directory. An example would be the operators of a call center can only talk to their team leader, or some group of active directory can talk only to 
certain groups. 

Thanks!

**Comment by geekgonecrazy** [comment] 2016-05-13 23:47
@insidesmart I'm ok with that.  Renamed and re-opened.

**Comment by jbjonez** [comment] 2016-07-21 02:50
I agree - the option to disable DM's would be a very useful setting / permission for teams who use Rocket Chat for group collaboration only - how difficult would this be to implement?

**Comment by Lucky21110** [comment] 2016-09-08 23:05
Hello,

Any news for this pull request ?
Is it replaced by another feature ?

Thanks

**Comment by mguspero** [comment] 2016-09-14 22:10
Hello, any news??? 
I think it would be a big milestone a good integration with active directory to give permissions.

Thanks!

**Comment by insidesmart** [comment] 2016-11-21 13:57
@geekgonecrazy @marceloschmidt @engelgabriel  I really feel this is a critical issue if Rocket.chat has to be adopted in private contexts replacing Slack.

End user DMs should be only possible with admins and not with any other users. 

Atleast for us, this feature is blocking us from replacing Slack with Rocketchat in projects especially when there are external users / guest users are involved

Can you let us know if there will be a fix in near future.

Thanks for your continuous efforts.

**Comment by patit72** [comment] 2016-12-16 17:05
Hello, any update on this request?

**Comment by Lucky21110** [comment] 2017-02-26 22:25
Hello,

Any news when this feature will be implemented ? 

> End user DMs should be only possible with admins and not with any other users.

Regards

**Comment by StevenBegin** [comment] 2017-05-08 06:59
Also desiring this feature.

**Comment by MartinSchoeler** [comment] 2017-06-13 18:33
@mguspero @StevenBegin If a user has not yet started the direct message, you can remove his `create-d` permission, so he cant start any new direct messages. But if he has already started it, I don’t think can we can stop him from accessing the dm via url now

**Comment by miguelmota** [comment] 2017-09-15 21:32
Is this feature to disable direct messages available in the rocket.chat platform?

**Comment by patit72** [comment] 2017-12-21 09:04
Any news on this requets?

**Comment by ekpaila** [comment] 2018-04-08 19:13
Any updates in this issue. Would be really helpful

**Comment by graywolf336** [comment] 2018-04-08 20:04
We have permissions which allow disabling creating and viewing them. What else is missing?

**Comment by susankao** [comment] 2018-05-14 04:28
Although you disable creating and viewing on direct message, they still can use search function to search user and keep going a chat if another person who has the permission and start a chat.

**Comment by engelgabriel** [comment] 2018-06-07 15:22
The permission was supposed to really cover this, if there is a work around, we need to fix it.

**Comment by Hudell** [comment] 2018-07-03 21:53
If you remove an user's permission to _Create Direct Messages_ (**create-d**), they will be blocked from starting DMs with any other users, even if they have the direct link to another user. 

Users who have the permission to create DMs can do so even with users who are blocked. That is working as intended.

If you want to completely remove an user's ability to participate in direct messages, you need to also remove the permission to _View Direct Messages_ (**view-d-room**).

**Comment by Hudell** [comment] 2018-07-03 21:56
There's an issue with the **view-d-room** permission: The users that are completely blocked can still receive notifications from direct messages, as well as access the DM through the notification (or a direct link).

**Closed** 2018-08-21 00:40 UTC
Labels: Feature: Planned, feat: roles / permissions

**Comment by bishalsharma123** [comment] 2023-12-30 10:31
hi do we have an update here
