### ISSUE TITLE
Slack Import -> invalid file format

### ISSUE THREAD

**Issue by niklaswa** [RocketChat/Rocket.Chat#3978] opened 2016-08-10 21:34 UTC
Your Rocket.Chat version: 0.36.0

I'm trying to import a Slack export, but evrytime i choose the file it says that it has an invalid file format although it's a zip file.

**Comment by MartinSchoeler** [comment] 2016-08-11 13:53
Hey thanks for the report, this is a duplicate of #3963

**Closed by MartinSchoeler** 2016-08-11 13:53 UTC
Labels: feat: import, type: bug

**Comment by graywolf336** [comment] 2016-08-29 20:23
Also a duplicate of #3050.
