### ISSUE TITLE
Slack Import reports invalid import file type

### ISSUE THREAD

**Issue by twardnw** [RocketChat/Rocket.Chat#10050] opened 2018-03-07 18:31 UTC
### Description:

Import of Slack zip fails

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0
* Deployment Method(snap/docker/tar/etc): RocketChat Cloud
* Number of Running Instances: 1
* DB Replicaset Oplog: Enabled
* Node Version: v8.9.3

### Steps to Reproduce:

1. Create export from Slack
2. Upload to RocketChat

### Expected behavior:

Expecting channels and messages to be imported to RocketChat

### Actual behavior:

Import fails with message 'Invalid Import File Type'
![Imgur](https://i.imgur.com/L3M1f8wl.png)

### Relevant logs:
```
[34mI20180307-17:41:30.673(0) Exception while invoking method 'prepareImport' TypeError: require(...).native is not a function     at Function.getBSONSize (/app/bundle/programs/server/packages/rocketchat_importer.js:123:25)     at Object.keys.forEach.date (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:184:18)     at Array.forEach (<anonymous>:null:null)     at Object.keys.forEach.channel (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:177:32)     at Array.forEach (<anonymous>:null:null)     at SlackImporter.prepare (/app/bundle/programs/server/packages/rocketchat_importer-slack.js:174:31)     at MethodInvocation.prepareImport (/app/bundle/programs/server/packages/rocketchat_importer.js:806:39)     at MethodInvocation.methodsMap.(anonymous function) (/app/bundle/programs/server/packages/rocketchat_lib.js:2158:28)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (/app/bundle/programs/server/packages/ddp-server.js:1877:12)     at DDP._CurrentMethodInvocation.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:126)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)     at DDPServer._CurrentWriteFence.withValue (/app/bundle/programs/server/packages/ddp-server.js:902:98)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)     at Promise (/app/bundle/programs/server/packages/ddp-server.js:902:46)     at new Promise (<anonymous>:null:null)     at Session.method (/app/bundle/programs/server/packages/ddp-server.js:875:23)     at /app/bundle/programs/server/packages/ddp-server.js:754:85```

**Comment by twardnw** [comment] 2018-03-07 18:37
I should note, this was attempted with an export which worked but was affected by #9577, and also tried with an export made just today

**Comment by geekgonecrazy** [comment] 2018-03-07 20:10
I know this was working after the fix for #9577 landed so i'm not sure what came along behind it and broke it. 

Any idea @graywolf336 ?

**Comment by trongthanh** [comment] 2018-03-08 10:33
I think I figured out the root cause of this bug. And the error log is telling it already:

```
Exception while invoking method 'prepareImport' TypeError: require(...).native is not a function     
at Function.getBSONSize (/app/bundle/programs/server/packages/rocketchat_importer.js:123:25)
```

I removed the native() function call in packages/rocketchat-importer/server/classes/ImporterBase.js, e.g:

```
static getBSONSize(item) {
	const { BSON } = require('bson'); // removed **native()**
	const bson = new BSON();
	return bson.calculateObjectSize(item);
}
```
and it works correctly, at least at my side now.

AFAIK, the package `bson` doesn't have that `native` part anymore, and it is moved to the `bson-ext`

**Comment by twardnw** [comment] 2018-03-09 05:41
any way this could be added to a point release before the next minor?

**Comment by geekgonecrazy** [comment] 2018-03-09 05:52
@trongthanh awesome could you open a PR with this?

**Closed** 2018-03-09 19:31 UTC
Labels: feat: import, type: bug
