### ISSUE TITLE
[BUG][Redesign] Unread rooms/DMs are duplicated on left-sidebar when using the "Unread" display mode

### ISSUE THREAD

**Issue by rafaelks** [RocketChat/Rocket.Chat#7934] opened 2017-08-28 13:04 UTC
### Description:

When using the **Unread Rooms Mode** on *Sidebar channels list mode* settings on the new layout, and some message is unread, you have it duplicated on the list: both unread and channels/DMs section (screenshot).

![screen shot 2017-08-28 at 09 55 53](https://user-images.githubusercontent.com/551004/29774419-bdbd312a-8bd7-11e7-8e89-efdca003d8be.png)

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.0-rc.1

### Steps to Reproduce:

1. Change your *Sidebar channels list mode* to **Unread Rooms Mode**
2. Have one unread message

### Expected behavior:

The expected behavior would be only having one item in "Unread" section.

### Actual behavior:

It's showing twice, one in Unread section and one in the original section (Favorites/Channels/DMs)

**Comment by MartinSchoeler** [comment] 2017-08-31 18:30
We still have to decide the best way to handle this.

**Comment by gdelavald** [comment] 2017-09-04 16:50
This was fixed in the last RC. Cannot reproduce it on demo.
@MartinSchoeler @rafaelks let me know if you guys still have this issue, else I'll close the issue.

**Comment by gdelavald** [comment] 2017-09-05 21:43
Based on @engelgabriel feedback, this is the expected functionality for the unread mode, so I will close the issue.

**Closed by gdelavald** 2017-09-05 21:43 UTC
Labels: subj: UI Redesign
