### ISSUE TITLE
User panel sometimes blank

### ISSUE THREAD

**Issue by ninja-** [RocketChat/Rocket.Chat#973] opened 2015-10-02 19:04 UTC
this includes the @ all tag

**Comment by geekgonecrazy** [comment] 2015-10-02 19:05
This is an occasional bug. Seems to be related to possibly window size.

**Comment by ninja-** [comment] 2015-10-02 19:08
this happens ONLY when the tab wasn't opened at least one time before clicking the tag

**Comment by gmsecrieru** [comment] 2015-10-03 17:52
I could finally reproduce this error several times thanks to @ninja- description. Variations may occur but please follow below for an easily reproducible use-case:

1. Fully refresh Rocket.Chat tab/window
2. Click *any* `@`mentions on a given room.
3. Open Members List through right tab-bar button 

First two steps will reproduce the blank state. Third step will give another unexpected behavior that might be addressed by fixing this issue.

**Closed** 2015-10-10 12:15 UTC
Labels: type: bug
