### ISSUE TITLE
Escaped parentheses in backticks break message

### ISSUE THREAD

**Issue by reitzig** [RocketChat/Rocket.Chat#8970] opened 2017-11-29 11:23 UTC
### Description:

Escaped parentheses in backticks break horribly.

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: GNU/Linux 3.2.0-4-amd64
* Deployment Method(snap/docker/tar/etc): unknown
* Number of Running Instances: 1
* DB Replicaset Oplog: OpLog disabled
* Node Version: v4.8.6

### Steps to Reproduce:

Post message with escaped parenthesis in backticks, e.g.  

~~~
`^\s*\((\w+)\)\s*$\`
~~~

![2017-11-29_01](https://user-images.githubusercontent.com/4246780/33372640-06ff7314-d4ff-11e7-8809-5ea826806174.png)

### Expected behavior:

See message with `\( ... \)` in code formatting, that is  "`^\s*\((\w+)\)\s*$`".

### Actual behavior:

![2017-11-29_02](https://user-images.githubusercontent.com/4246780/33372650-10f093b2-d4ff-11e7-9686-fb7577866ef6.png)

The shown string (some base64?) changes with every edit, even if the message itself is not changed.

### Workaround

This is apparently some bad interaction with KaTeX; disabling "Parenthesis Syntax" returns code formatting to the expected behaviour.  
Dollar syntax does not seem to be affected in the same way.

KaTeX should be disabled inside pre-/code-formatted elements.

**Comment by MartinSchoeler** [comment] 2017-11-30 13:07
Duplicate of #8640

**Closed by MartinSchoeler** 2017-11-30 13:07 UTC
