### ISSUE TITLE
Update Emojione

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat#9342] opened 2018-01-05 13:50 UTC
We are using a newer version of Emojione on iOS for the next update (1.8.0) and it supports more emojis than the web version.

This presents the following problem:

|iOS|Web|
|-|-|
|![](https://i.imgur.com/jb9aMsj.jpg)|![](https://i.imgur.com/dyoLddd.png)|

**Comment by sampaiodiego** [comment] 2018-01-05 15:14
Closing as duplicate of #6740

**Closed by sampaiodiego** 2018-01-05 15:14 UTC
