### ISSUE TITLE
Node slamming CPU since update to 3.7

### ISSUE THREAD

**Issue by HiveMindNet** [RocketChat/Rocket.Chat#19082] opened 2020-09-30 13:41 UTC
Since updating to 3.7 from previous version the CPU utilisation has jumped from less than 5% to a constant very high average. 

### Description:

Node running away with Cpu and Mongo DB docker also high

<img width="402" alt="Screenshot 2020-09-30 at 14 36 09" src="https://user-images.githubusercontent.com/19346725/94692815-e75be080-032a-11eb-9090-7cce6f2c6afd.png">

<img width="822" alt="Screenshot 2020-09-30 at 14 38 04" src="https://user-images.githubusercontent.com/19346725/94692933-0b1f2680-032b-11eb-9548-bb046b4ece37.png">

<img width="825" alt="Screenshot 2020-09-30 at 14 38 15" src="https://user-images.githubusercontent.com/19346725/94693000-1a05d900-032b-11eb-8dc0-79d2b5a98311.png">

### Steps to reproduce:

1. restart / start rocket

### Expected behavior:

normal behaviour / ~3% CPU

### Actual behavior:

high CPU

### Server Setup Information:

- Version of Rocket.Chat Server: 
- Operating System: 
- Deployment Method: latest docker
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version:

### Client Setup Information

N/A

**Comment by Sing-Li** [comment] 2020-09-30 14:48
@HiveMindNet  Which version of RC were you upgrading from?      Also which version of MongoDB   *before* and *after* ?

**Comment by HiveMindNet** [comment] 2020-09-30 14:52
> @HiveMindNet Which version of RC were you upgrading from? Also which version of MongoDB _before_ and _after_ ?

Thanks for asking 👍 

I cam from 3.6 (I'm always up to date) and I didn't upgrade the Mongo docker. (which is and was db version v4.0.20) - could that be the issue?

Both run in individual dockers if that matters.

Thanks for any guidance :)

**Comment by xzyyyy** [comment] 2020-09-30 14:58
I updated from 3.6.3 too, a manual installation. After upgrade to 3.7.0, I met the same problem. My node is 12.14.0, npm is 6.13.4 and my mongo is 4.0.2.
Thanks for any suggestion.

**Comment by geekgonecrazy** [comment] 2020-09-30 15:57
Has this happened with any previous upgrade?  Did number of users change after the upgrade?  Does there seem to be any correlating factor with behaviour and the cpu spikes?

**Comment by xzyyyy** [comment] 2020-09-30 16:17
> Has this happened with any previous upgrade? Did number of users connected change after the upgrade? Does there seem to be any correlating factor with behaviour and the cpu spikes?

I think the answers of all your questions are no, I haven't meet that before, and only 4 users on my server. After upgrading, the usage of cpu would be down to about 1% - 3#  in 2 minutes with previous upgrade, but this time it keeps almost 100% all time.
Thanks.

**Comment by xzyyyy** [comment] 2020-09-30 16:19
> Has this happened with any previous upgrade? Did number of users connected change after the upgrade? Does there seem to be any correlating factor with behaviour and the cpu spikes?

One more question, can I downgrade to 3.6.3 by the steps of update in doc.rocket.chat? Is there any problem with it?
Thanks

**Comment by kgdemir** [comment] 2020-09-30 17:01
I have just upgraded from 3.6.2 and I can confirm this issue
![2020-09-30_19-59-39](https://user-images.githubusercontent.com/29093789/94716471-96aeac80-0357-11eb-8668-defd6e9587e1.png)
![2020-09-30_20-00-47](https://user-images.githubusercontent.com/29093789/94716540-ad550380-0357-11eb-9303-3cabfc5ead5e.png)

**Comment by wolfcreative** [comment] 2020-09-30 17:11
I have the same problem after upgrading from 3.6.3.
node: 12.14.0
mongoDB: 4.0.20

![image](https://user-images.githubusercontent.com/29209797/94717381-aafba500-0369-11eb-8c46-1821b5039f29.png)

**Comment by HiveMindNet** [comment] 2020-09-30 17:21
Male this is a red herring, but I notice I'm getting Jitsi error log entries which I wasn't before too. Sorry if this isn't relevant, but in case it was I thought I'd share. Is everyone else having these issues seeing anything like this / using Jitsi?

<img width="799" alt="Screenshot 2020-09-30 at 18 18 59" src="https://user-images.githubusercontent.com/19346725/94718460-ae7f3400-0349-11eb-9aeb-a034fee3b742.png">

**Comment by Sing-Li** [comment] 2020-09-30 17:24
Thanks everyone, all data points help.   

Anyone **not** running this on time-shared cloud vps?   (on your own dedicated machines?)

**Comment by HiveMindNet** [comment] 2020-09-30 17:28
> Thanks everyone, all data points help.
> 
> Anyone **not** running this on time-shared cloud vps? (on your own dedicated machines?)

We're on our own AWS EC2 (m5.xlarge), just running RC within docker for ease. Nothing we can't look at or adjust if needed on the main infrastructure. Let me know if you want me to look at anything. We're running sematex for monitoring everything across containers and on the main EC2 too, including logs and events.

**Comment by xzyyyy** [comment] 2020-09-30 17:30
> Maybe this is a red herring, but I notice I'm getting Jitsi error log entries which I wasn't before too. Sorry if this isn't relevant, but in case it was I thought I'd share. Is everyone else having these issues seeing anything like this / using Jitsi?
> 
> <img alt="Screenshot 2020-09-30 at 18 18 59" width="799" src="https://user-images.githubusercontent.com/19346725/94718460-ae7f3400-0349-11eb-9aeb-a034fee3b742.png">

I don't receive any error, there isn't error or warning or any other thing in my log, just like before, so I think it's not a Jitsi problem.
Thanks.

**Comment by Sing-Li** [comment] 2020-09-30 17:42
@ankar84  Have you updated to 3.7 on your cluster?   And are you seeing similar "increased DB load" behavior?

**Comment by geekgonecrazy** [comment] 2020-09-30 23:14
@HiveMindNet is jitsi something you can turn off integration for a bit and see if changes anything? Just to rule that part out.  We have the jitsi integration enabled on open with out this issue.. so doesn't seem likely.  On open we're also using our docker image.  So that aspect is also the same

But anything we use to narrow in on the case would be awesome.

**Comment by ankar84** [comment] 2020-10-01 04:23
> @ankar84 Have you updated to 3.7 on your cluster? And are you seeing similar "increased DB load" behavior?

Hi, @Sing-Li 
Yes. I have upgraded one of my test environments to 3.7.0 from 3.6.3 and all looks fluent and nice.
I have only few users in that test deployment (but @xzyyyy have trouble with 4 users [here](https://github.com/RocketChat/Rocket.Chat/issues/19082#issuecomment-701495063))

I have 3 servers with CentOS7 and 4 RC docker containers each - 12 instances
Each server have one mongoDB container version 4.0.20
Storage engine **wiredTiger** because of using of **change streams** https://github.com/RocketChat/Rocket.Chat/pull/18892
Here is a htop screens from all 3 servers
![image](https://user-images.githubusercontent.com/4023037/94767828-487cc600-03b6-11eb-8aee-633b0abde31a.png)
![image](https://user-images.githubusercontent.com/4023037/94767855-5e8a8680-03b6-11eb-9d77-2554f7469351.png)
![image](https://user-images.githubusercontent.com/4023037/94767877-6e09cf80-03b6-11eb-872b-8c440cdc742e.png)

**Comment by geekgonecrazy** [comment] 2020-10-01 04:40
You actually point to a PR I hadn’t thought about... 

@HiveMindNet would you be able to try adding: USE_NATIVE_OPLOG=true ?  I’m curious if it’s in the new change stream processing.  As this is a new bit of processing

**Comment by HiveMindNet** [comment] 2020-10-01 06:54
> @HiveMindNet is jitsi something you can turn off integration for a bit and see if changes anything? Just to rule that part out. We have the jitsi integration enabled on open with out this issue.. so doesn't seem likely. On open we're also using our docker image. So that aspect is also the same
> 
> But anything we use to narrow in on the cause would be awesome.

I have just tried turning off Jitsi integration and stopping Jitsi servers and it made no difference. Worth a try though - so that's ruled out.

**Comment by HiveMindNet** [comment] 2020-10-01 06:56
> You actually point to a PR I hadn’t thought about...
> 
> @HiveMindNet would you be able to try adding: USE_NATIVE_OPLOG=true ? I’m curious if it’s in the new change stream processing. As this is a new bit of processing

Hi - I can try - but can you tell me how please? Is this just an ENV option I add to the docker? Thanks.

**Comment by kgdemir** [comment] 2020-10-01 08:15
> You actually point to a PR I hadn’t thought about...
> 
> @HiveMindNet would you be able to try adding: USE_NATIVE_OPLOG=true ? I’m curious if it’s in the new change stream processing. As this is a new bit of processing

I can confirm USE_NATIVE_OPLOG=true fixed high cpu issue

**Comment by mranderson56** [comment] 2020-10-01 08:22
Same things on my instance, add "USE_NATIVE_OPLOG=true" on systemd service file fixed the issue.

**Comment by wolfcreative** [comment] 2020-10-01 08:32
@mranderson56 Where should I write this?

**Comment by Stoobitweet** [comment] 2020-10-01 08:34
@wolfcreative In the service file (/lib/systemd/system/rocketchat.service), in the Environment parameter.

**Comment by mranderson56** [comment] 2020-10-01 08:35
Into your systemd file (on Debian) : /etc/systemd/system/multi-user.target.wants/rocketchat.service
You can add this in "Environment".

**Comment by wolfcreative** [comment] 2020-10-01 08:47
Well, the CPU load dropped to 0.7-1.5%
Thank you all for your help!

**Comment by HiveMindNet** [comment] 2020-10-01 09:44
Can any of the main devs please let me know, is it safe for me to leave this USE_NATIVE_OPLOG=true on a production environment while you find a fix??

**Comment by rodrigok** [comment] 2020-10-01 16:20
@HiveMindNet it's safe to keep `USE_NATIVE_OPLOG` in production env, it will use the code used on all the previous versions.

**Comment by HiveMindNet** [comment] 2020-10-01 16:31
> @HiveMindNet it's safe to keep `USE_NATIVE_OPLOG` in production env, it will use the code used on all the previous versions.

Thank you :)

**Comment by rodrigok** [comment] 2020-10-01 16:45
@HiveMindNet how many users do you have online on your instance? And could you give me a screenshot or copy of the startup logs where rocket.chat prints the mongodb version, engine, etc?

**Comment by fdellwing** [comment] 2020-10-01 19:22
@rodrigok Someone in the forums posted some info: https://forums.rocket.chat/t/rocketchat-3-7-0-high-cpu-usage/8715

**Comment by netbix** [comment] 2020-10-03 10:05
I solved it by entering this on my docker-compose file

volumes:
      - ./uploads:/app/uploads
    environment:
      **- USE_NATIVE_OPLOG=true**
      - PORT=3000

**Comment by wolbernd** [comment] 2020-10-05 07:46
I had the same problem and setting `USE_NATIVE_OPLOG=true` does help a bit however the cpu load ist still siginificantly larger since the upgrade to 3.7.0. We have 1 server with 8 VCPUs with 7 Rocket.Chat instances and 1 Mongodb. At the moment we have approx. 3000 Users online and the CPU load (5 min  avg) is at about 7.5. Before the update the CPU load rarely exceeded 3.0

**Comment by ataraxus** [comment] 2020-10-05 08:19
Same Issue here: USE_NATIVE_OPLOG=true should be definitely the default! I just stumbled upon the changed load by chance!

**Comment by wolbernd** [comment] 2020-10-05 08:35
> I had the same problem and setting `USE_NATIVE_OPLOG=true` does help a bit however the cpu load ist still siginificantly larger since the upgrade to 3.7.0. We have 1 server with 8 VCPUs with 7 Rocket.Chat instances and 1 Mongodb. At the moment we have approx. 420 Users online and the CPU load (5 min avg) is at about 7.5. Before the update the CPU load rarely exceeded 3.0

Sorry, please disregard this, I found a missing index in our mongodb that caused this issue.

**Comment by benedikt-wegmann** [comment] 2020-10-05 08:50
> > I had the same problem and setting `USE_NATIVE_OPLOG=true` does help a bit however the cpu load ist still siginificantly larger since the upgrade to 3.7.0. We have 1 server with 8 VCPUs with 7 Rocket.Chat instances and 1 Mongodb. At the moment we have approx. 420 Users online and the CPU load (5 min avg) is at about 7.5. Before the update the CPU load rarely exceeded 3.0
> 
> Sorry, please disregard this, I found a missing index in our mongodb that caused this issue.

Come now, don't leave everybody hanging. What exactly did you do to fix this? :thinking:

**Comment by wolbernd** [comment] 2020-10-05 09:01
> > > I had the same problem and setting `USE_NATIVE_OPLOG=true` does help a bit however the cpu load ist still siginificantly larger since the upgrade to 3.7.0. We have 1 server with 8 VCPUs with 7 Rocket.Chat instances and 1 Mongodb. At the moment we have approx. 420 Users online and the CPU load (5 min avg) is at about 7.5. Before the update the CPU load rarely exceeded 3.0
> > 
> > 
> > Sorry, please disregard this, I found a missing index in our mongodb that caused this issue.
> 
> Come now, don't leave everybody hanging. What exactly did you do to fix this? thinking

Sorry I think it is something unrelated to this issue but I don't want to leave you hanging ;) 
In my case there was an index missing in the collection `rocketchat.rocketchat_uploads.chunks`. The missing index (compound index for fields `files_id` and `n`) causes all requests for blobs to do a full table scan. I'm not sure how this index got lost, but we did a database recovery right before the update to 3.7.0 so something might have gone wrong there.

**Comment by HiveMindNet** [comment] 2020-10-05 12:45
> @HiveMindNet how many users do you have online on your instance? And could you give me a screenshot or copy of the startup logs where rocket.chat prints the mongodb version, engine, etc?

Sorry @rodrigok we're still early in adoption so although over 1000 users, only around 20-30 concurrently active at any one time.

**Comment by dpunkturban** [comment] 2020-10-05 14:39
> Same Issue here: USE_NATIVE_OPLOG=true should be definitely the default! I just stumbled upon the changed load by chance!
> 
> EDIT: To be clear. Setting this flag, did fix the issue for us. Load is back to <5%

We have the same problem with our cluster. The workaround with `USE_NATIVE_OPLOG=true` also worked for us

**Comment by binarydad** [comment] 2020-10-06 11:57
Will this fix get merged into the 3.7.1 release?

**Comment by ankar84** [comment] 2020-10-06 12:07
I'm in opposite to majority of users here want to test change streams in test environment.
RC server version is 3.7.0
Storage engine is wiredTiger
MongoDB version is 4.0.17
No any oplog information on instance start.
```
➔ System ➔ startup
➔ +---------------------------------------------+
➔ |                SERVER RUNNING               |
➔ +---------------------------------------------+
➔ |                                             |
➔ |  Rocket.Chat Version: 3.7.0                 |
➔ |       NodeJS Version: 12.18.4 - x64         |
➔ |      MongoDB Version: 4.0.19                |
➔ |       MongoDB Engine: wiredTiger            |
➔ |             Platform: linux                 |
➔ |         Process Port: 3000                  |
➔ |             Site URL: https://rc.test.ru  |
➔ |     ReplicaSet OpLog: Enabled               |
➔ |          Commit Hash: 2c82cd9cee            |
➔ |        Commit Branch: HEAD                  |
➔ |                                             |
➔ +---------------------------------------------+

```
How to force enable change streams in deployment?

**Comment by gbouthenot** [comment] 2020-10-08 10:55
Thank you !
The `USE_NATIVE_OPLOG=true` fixed the problem !

**Closed** 2020-10-09 03:07 UTC

**Comment by rodrigok** [comment] 2020-10-09 19:16
Folks, we release the version 3.7.1 with a fix for this situation, can you all please try this new version without the `USE_NATIVE_OPLOG=true` variable?

Thanks

**Comment by Gummikavalier** [comment] 2020-10-10 07:27
We have no issues with 3.7.1, MongoDB 3.6 running WiredTiger and no USE_NATIVE_OPLOG variable present. No experience with 3.7.0, so I cannot confirm whether the issue existed for us on that.

**Comment by wolbernd** [comment] 2020-10-10 10:32
@rodrigok We applied the update and removed `USE_NATIVE_OPLOG=true` and at the moment it looks good. However we do not have many users online on weekends so we'll have to wait for monday for a definitive answer.

**Comment by ataraxus** [comment] 2020-10-10 13:07
@rodrigok We applied the update and removed USE_NATIVE_OPLOG=true and at the moment it looks good.

**Comment by codeneno** [comment] 2021-01-02 06:21
> wiredTiger

Does this only fix "mmapv1 database engine or when no admin access was granted to the database user,"?
we use 3.3.3 version,and it will have a high cpu load sometimes,does this work for wiredTiger ?thank you.

**Comment by 564064202** [comment] 2021-01-10 10:24
> @rodrigok We applied the update and removed USE_NATIVE_OPLOG=true and at the moment it looks good.

no. it didn't

**Comment by 564064202** [comment] 2021-01-10 10:26
> Folks, we release the version 3.7.1 with a fix for this situation, can you all please try this new version without the `USE_NATIVE_OPLOG=true` variable?
> 
> Thanks

it wasts too many  mongodb cpu  100%
too many getmore operations

**Comment by Gummikavalier** [comment] 2021-03-05 08:28
Because this issue discusses effect of oplog method, I'll add this here.

Here is a weekly CPU graph of one server RC Vmware instance with SSD-disks, 8 cores and 38 GB memory. DB and 20 nodes on the same box. The server is mostly idling so there is no considerable load for actual use. I thought it gives some comparison to idle loads different versions and OpLog methods have.

![Screenshot from 2021-03-05 09-56-52](https://user-images.githubusercontent.com/6958942/110085112-62716900-7d99-11eb-8a8a-f2d0d32b3bd9.png)

First and the lowest part of the CPU usage:

Before 2. March:
RC 3.9.7 with MongoDB OpLog streams, load approximately 6 %

In the evening of 1. March, upgrade from 3.9.7 to 3.10.6 -> 3.11.2 and in 2. March morning afternoon finally to 3.12.0:
RC 3.12.0 with MongoDB OpLog streams, load approximately 21 %

In the evening of 2. March, switching to native OpLog with `USE_NATIVE_OPLOG=true`:
RC 3.12.0 with native OpLog, load approximately 15 %

------------------------------------------

So all in all, just the idling load increase of RC 3.9.7 and 3.12.0 with this amount of nodes is staggering 19 %! Most of the load comes from MongoDB.

Switching to native oplog decreased the load by 6%. It does not show in the grapsh but this also considerably decreased the amount of load on the database process, and moved it towards application nodes themselves. In short, much lighter on DB, but bit heavier for nodes.
If you are clustering application nodes on different servers, native oplog seems to be the way to to spread the load to additional servers instead of them hitting single database instance really hard.

We've also tested with having as few application nodes as possible in real life scenarios with 300+ users online. It seems that when the underlying server has fast enough disk and enough memory and at least two cores, even single app node can handle those 300+ active users without any issues, as long as nothing acts or bugs up really badly.

With as few as possible nodes additional load created by oplog operations stays in minimum, which saves lots of CPU cycles in mongodb.

We read in 2017 that optimal users per application node ratio would be approx. 50 per node, and at least this does not seem to be true anymore. We estimate that one node could manage at least 500 users without issues, as long as the underlying hardware is not of the cheapest kind you get from the cloud.

Also having one core per one node rule does not seem to hold it very well with good gear; the loads of single node processes are pretty low with just 8 cores for 20 nodes + database.

**Comment by Gummikavalier** [comment] 2021-03-27 11:00
For the record, above extra load triggered by RC 3.12.0 ended eventually three weeks later. This makes me think it was an RC based background process doing something after the upgrade. Update to 3.12.3 along with restarts to all nodes also did not trigger it again. I'm also considering some kind of race condition in Mongodb.

![Screenshot from 2021-03-27 12-55-11](https://user-images.githubusercontent.com/6958942/112718475-f0a1c080-8efb-11eb-8bfe-bd4d7697b140.png)

**Comment by rodrigok** [comment] 2021-03-27 20:22
@Gummikavalier thank you for the very detailed information. It seems to be an edge case that we were not able to reproduce here yet. We will put a new round of focus to this soon and I hope we can improve the idle CPU usage more.
