### ISSUE TITLE
Bug in 1.0.0-rc.2 with file upload icon

### ISSUE THREAD

**Issue by mmgoilf** [RocketChat/Rocket.Chat#14176] opened 2019-04-17 16:50 UTC
The "+" file upload icon usually goes away when you are typing and gets replaced with the send message icon. There has been a bug in the past (before this release) that sometimes it would get stuck and the "+" icon wouldn't appear again. In the past simply refreshing the client fixed it. Just now me and someone else encountered this issue, but it would persist even after refreshing the client. We are using docker with version 1.0.0-rc.2, I am on the client version 2.15.2 and he is on a older client version, we both encountered this issue in our DMs today.

**Comment by reetp** [comment] 2019-04-17 17:25
Probably a duplicate of #14105 and #14166

**Comment by reetp** [comment] 2019-04-17 17:26
@rocket-cat close as duplicate

**Closed by reetp** 2019-04-17 17:26 UTC
