### ISSUE TITLE
Chat message stays in input field after sending

### ISSUE THREAD

**Issue by Corinari** [RocketChat/Rocket.Chat#27794] opened 2023-01-20 14:21 UTC
### Description:

after sending a message (DM or public), going to another direct chat or channel and after a while going to the original chat, the sent message is still in the input field, although the message is sent (and displayed). 

After several reloads without cache, the input field was then cleared. 
### Steps to reproduce:

1. Send a message to somebody 
2. change channel
3. return to original chat/Channel

### Expected behavior:

input field is empty

### Actual behavior:

Input field shows last message, while it was already sent

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.1 
- Operating System: Debian Bullseye
- Deployment Method: npm install from releases.rocket.chat
- Number of Running Instances: 2 affected
- DB Replicaset Oplog: yes
- NodeJS Version: 
- MongoDB Version: 5.0.6

### Client Setup Information
RocketChat Web / Google Chrome Version 109.0.5414.75 on  Windows 10 Version 21H2 (19044.2251)
RocketChat Client on Fedora

### Relevant logs:

RocketChat log did not show anything during the time span of the bug

**Comment by AdityaSingh-02** [comment] 2023-01-21 04:00
Hey I didn't faced any such issue.. There is no message being Displayed inside the Text input field

**Comment by prsck** [comment] 2023-02-10 10:48
We are investigating this issue at the moment and can confirm this behavior.

**Comment by CvH** [comment] 2023-02-18 10:35
duplicate of https://github.com/RocketChat/Rocket.Chat/issues/27549
it was stated that this might be fixed already https://github.com/RocketChat/Rocket.Chat/issues/27549#issuecomment-1353684288

**Comment by hugocostadev** [comment] 2023-06-19 18:35
Hi there, thanks for the contribution! 🚀 💯 

Sorry, this error does not happen on the latest and maintained releases.

[Rocket.Chat](https://rocket.chat/)  provides security support for, at least, 3 months for each release and 6 months to the latest releases of each major version

I would suggest you update your Rocket.Chat version to the latest stable version, which you can find in [Releases Page](https://github.com/RocketChat/Rocket.Chat/releases) and, check it [HERE](https://docs.rocket.chat/resources/get-support/enterprise-support#rocket.chat-versions) the table with versions and End of Life dates. 

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
- Feature Request: Open an issue in [Feature Request](https://github.com/RocketChat/feature-requests) repository

**Closed by hugocostadev** 2023-06-19 18:35 UTC
