### ISSUE TITLE
Slack Database import

### ISSUE THREAD

**Issue by doctorwho92** [RocketChat/Rocket.Chat#3963] opened 2016-08-09 21:46 UTC
Your Rocket.Chat version: 0.36.0
 I'm trying to import a Slack data export zip and it says "the file uploaded isn't a valid slack export file."

**Comment by MartinSchoeler** [comment] 2016-08-10 12:29
Hey we're sorry to hear that you are having issues, but can you give us more information like what is the platform you are using rocket chat and have you tried to do the importation process again?

**Comment by doctorwho92** [comment] 2016-08-10 13:14
We are running:

Runtime Environment:
OS Type Linux
OS Platform linux
OS Arch x64
OS Release 4.4.14-24.50.amzn1.x86_64
Node v0.10.45 version
OS Uptime 5 days, 2 hours, 32 minutes, 10 seconds
OS Load 0.19, 0.28, 0.21 Average
OS Total 3.86 GB Memory
OS Free 284.83 MB Memory
OS CPU 2 Count

Build Environment:
OS Platform linux
OS Arch x64
OS Release 3.13.0-40-generic
Node v0.10.40 version
Date August 2, 2016 9:46 AM

I have tried uploading a recent Slack zip file into the rocket chat OS X client, and into the web client, using Firefox, Chrome and Safari. (OS X 10.10.5).

**Comment by doctorwho92** [comment] 2016-08-10 13:15
I did try multiple times, and tried again after the last server update. No luck. Same error every time.

**Comment by teamfighter** [comment] 2016-08-29 09:06
same things at 0.37.1 there, I am unable to import slack messages to rocketchat.

**Comment by graywolf336** [comment] 2016-08-29 20:23
Duplicate of #3050.

**Closed** 2016-08-29 20:23 UTC
Labels: feat: import, stat: waiting response, type: bug
