### ISSUE TITLE
Option to disallow non-ssl image previews

### ISSUE THREAD

**Issue by localguru** [RocketChat/Rocket.Chat#7490] opened 2017-07-13 16:09 UTC
Rocket.Chat Version: 0.56.0 0.57.0

Embed Link Previews result in ssl warnings in browser if the preview content comes from a non ssl site and includes an image. If RC is running on ssl, there should be an option to turn off loading images from non ssl sites or content should be cached locally.

**Comment by geekgonecrazy** [comment] 2017-07-14 17:23
I think we've had this come up before.  These warnings are just that warnings they are safe to ignore.  

As to providing an option... Lets re-title this to be more appropriate to a feature request. :)

**Comment by localguru** [comment] 2017-07-15 18:30
@geekgonecrazy yes, those warnings are safe to ignore. But it might confuse some users and could increase tickets to local admin.

**Comment by choltkamp** [comment] 2017-07-18 11:36
I second this.

**Comment by hard2er** [comment] 2017-07-19 15:07
same here.

**Comment by localguru** [comment] 2017-07-19 20:50
See https://github.com/RocketChat/Rocket.Chat.Docs/issues/328

I think something like a proxy url, which fetches the non-ssl content could solve the problem.

**Comment by geekgonecrazy** [comment] 2017-07-20 17:17
That feature has actually been requested already #4963 

Lets keep the ask and conversation on this ticket on topic.  This ticket is about preventing non-secure previews.

**Comment by engelgabriel** [comment] 2019-01-24 13:34
Duplicate of https://github.com/RocketChat/Rocket.Chat/issues/971

**Closed by engelgabriel** 2019-01-24 13:34 UTC
Labels: Feature: Request, feat: embed
