### ISSUE TITLE
Order of Private Messages 

### ISSUE THREAD

**Issue by DalePayman** [RocketChat/Rocket.Chat#6153] opened 2017-02-24 10:52 UTC
Is it possible to implement an "order" for private messages?
Let's say i've chatting with 20 ppl.

If someone's pm'ing me it would be nice if this user is on first place under "private messages".

Maybe it'll be cool to have some "order-options" in user profile.
Something like
Show me "Most messages/Newest Messages on top"

**Comment by MartinSchoeler** [comment] 2017-02-24 15:19
Duplicate of #4377

**Closed by MartinSchoeler** 2017-02-24 15:19 UTC
