### ISSUE TITLE
Attachment link parsing is messed up []() to <a href> keeps trailing characters

### ISSUE THREAD

**Issue by wreiske** [RocketChat/Rocket.Chat#12362] opened 2018-10-18 21:44 UTC
### Description:

Attachment link parsing is messed up `[]()` to `<a href>` keeps trailing characters. For some reason the `)` is included when grabbing out the url, as well as any trailing characters before a space. 

**Example:**
Go to this **link**, and this **link**
Will result in  **href="link),"** and this **href="ink)"**

### Steps to reproduce:

I have reproduced this by including a link in a rocket.chat.app attachment using the following code.
`You can login to the server [here](https://auth.company.com/${username}/login)`

Also, in the open.rocket.chat server when you type in something like `#53` and it attaches the github links, the attachment has a trailing `)` as well as anything after it before a space. 

### Expected behavior:

Parse link correctly without trailing characters, (e.g. `"),"` or` ")"`)

### Actual behavior:

<img width="794" alt="screen shot 2018-10-18 at 5 35 21 pm" src="https://user-images.githubusercontent.com/6295044/47185732-48d04380-d2fc-11e8-8382-010c0ea89414.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 0.70.4 (dbff6ee20ff756d5654bc36da66de4999ff7cd9c)
- Operating System: CentOS 7
- Deployment Method: wget tar.gz, tar zxvf, npm install, node main.js
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: v8.9.3
- MongoDB Version: db version v2.6.12 2018-10-18T17:33:25.665-0400 git version: d73c92b1c85703828b55c2916a5dd4ad46535f6a

**Comment by Ede123** [comment] 2018-10-29 18:38
Same issue when writing plain links like
```
as seen on the website (http://link.com)
please have a look at http://link.com, where...
```
where the trailing ")" or "," respectively will be included in the link preview Rocket.Chat generates (which will also often show an error page instead of the actually linked page content).

**Comment by MartinSchoeler** [comment] 2019-10-23 16:59
This was probably fixed on the latest versions since I can't reproduce it. If you experience this issue again, please reopen this. Thanks!

**Closed by MartinSchoeler** 2019-10-23 16:59 UTC
Labels: subj: ui/ux, type: bug
