### ISSUE TITLE
How to unregister a rocketchat server

### ISSUE THREAD

**Issue by happog** [RocketChat/Rocket.Chat#23082] opened 2021-09-01 06:33 UTC
HI Guys, how to unregister rocketchat server and i want to re-setup server and re-register that . Thanks

rocketchat server setup guide: https://docs.rocket.chat/installing-and-updating/docker-containers#introduction

**Comment by debdutdeb** [comment] 2021-09-02 06:18
Hi

Can you please ask this question on our open server?

https://open.rocket.chat/channel/support

GitHub is reserved only for bugs, we're in the forum AND the open server as well. For general support questions please use those mediums :)

Closing this since it's not a bug.

**Closed by debdutdeb** 2021-09-02 06:18 UTC
