### ISSUE TITLE
Disallow role to sent, receive direct messages

### ISSUE THREAD

**Issue by akachapati** [RocketChat/Rocket.Chat#5347] opened 2016-12-27 11:46 UTC
Your Rocket.Chat version: 0.48.1

I've set up a role that only has access to 'view-joined-room'. If I remember correctly, users with this role did not have access to even see direct messages unless they had another permissions 'view-d-room' enabled. However, with 0.48.1 this doesn't seem to be the case. My users are able to see the direct message section even if they cannot initiate a conversation. 
<img width="258" alt="screen shot 2016-12-27 at 5 30 46 pm" src="https://cloud.githubusercontent.com/assets/4548294/21499035/538bdf00-cc5a-11e6-9e16-aee04e36b340.png">

**Comment by graywolf336** [comment] 2017-01-02 14:08
Confirmed

**Comment by engelgabriel** [comment] 2017-01-20 19:30
@akachapati can you please try again with `0.49.4`?

**Comment by akachapati** [comment] 2017-03-29 08:51
I am in 0.51 now and the issue still exists

**Comment by MartinSchoeler** [comment] 2017-06-14 14:09
@akachapati The view-joined-room allows a user to see direct messages, since they can still receive direct messages.  But I think users with this permissions should not be able to see the `more channels...` button

**Comment by MartinSchoeler** [comment] 2017-08-15 19:38
Closing this since #7643 changed this part of the ui. Please reopen this if the problem persists. Thanks!

**Closed by MartinSchoeler** 2017-08-15 19:38 UTC
Labels: feat: roles / permissions, subj: Ui Redesign, type: improvement
