### ISSUE TITLE
hubot-rocketchat is broken due to exception in addUserToRoom

### ISSUE THREAD

**Issue by dbussert** [RocketChat/Rocket.Chat#597] opened 2015-08-27 18:45 UTC
Using an up-to-date RocketChat and hubot-rocketchat adapter, the bot gets this exception when connecting to rocket.chat.  The bot shows up as present in rocket.chat and in the room, but cannot get any messages.  

```
I20150827-14:41:44.896(-4)? Exception while invoking method 'addUserToRoom' TypeError: Cannot read property 'username' of undefined
I20150827-14:41:44.896(-4)?     at [object Object].Meteor.methods.addUserToRoom (server/methods/addUserToRoom.coffee:9:12)
I20150827-14:41:44.896(-4)?     at [object Object].methodMap.(anonymous function) (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:164:1)
I20150827-14:41:44.896(-4)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150827-14:41:44.896(-4)?     at packages/ddp/livedata_server.js:648:1
I20150827-14:41:44.897(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150827-14:41:44.897(-4)?     at packages/ddp/livedata_server.js:647:1
I20150827-14:41:44.897(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150827-14:41:44.897(-4)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150827-14:41:44.897(-4)?     at packages/ddp/livedata_server.js:546:1
I20150827-14:41:44.897(-4)? [publish] messages -> rid: GENERAL start: 10
I20150827-14:41:44.897(-4)? [methods] canAccessRoom ->  userId: uTd3cmq7SpCJzxxcz rid: GENERAL
```

In ` addUserToRoom.coffee` there is no `u.username` object for the room, only a `usernames` object. removing this if statement makes the bot work

```
 if room.u.username isnt Meteor.user().username and room.t is 'c'
                        throw new Meteor.Error 403, '[methods] addUserToRoom -> Not allowed'
```

**Comment by Sing-Li** [comment] 2015-08-28 00:54
It is just plain broken, and appears that nobody else calls it except hubot.

Unless someone speaks up otherwise in the next 2 days, I'm just going to remove the statement and close this.

**Comment by marceloschmidt** [comment] 2015-08-28 18:51
Actually, there is a u.username in rooms where t is 'c' (channel). It's the user who created that channel.
I think the problem is that not all rooms have this information, so we should move the `room.t is 'c'` to the start of if statement. I'll do that.

**Closed** 2015-08-28 18:53 UTC
