### ISSUE TITLE
Country flags on users

### ISSUE THREAD

**Issue by RichOnPeers** [RocketChat/Rocket.Chat#708] opened 2015-09-05 22:02 UTC
For running a world wide RocketChat community this could be appreciated.
Choose flag/country in account settings to be displayed before/after the name in chat.

**Comment by marceloschmidt** [comment] 2015-09-09 21:02
That would require us to depend on geoip or asking user for their location. Maybe that could be an option under settings.

**Comment by geekgonecrazy** [comment] 2015-09-09 21:03
Probably best to ask right?  From what i'm seeing a lot of people seem to like no external dependencies.

**Comment by marceloschmidt** [comment] 2015-09-17 00:00
Duplicate of #419

**Closed by marceloschmidt** 2015-09-17 00:00 UTC
Labels: Feature Request, Settings
