### ISSUE TITLE
Slack import fails with internal server error

### ISSUE THREAD

**Issue by lc3t35** [RocketChat/Rocket.Chat#4549] opened 2016-10-05 14:45 UTC
Your Rocket.Chat version: 0.41.0

When I import the zip file exported from Slack, I have the following error message on server side : 
````
Exception while invoking method 'prepareImport' TypeError: Cannot read property 'calculateObjectSize' of undefined
    at Function.Importer.Base.Importer.Base.Base.getBSONSize (packages/rocketchat_importer/lib/importTool.coffee:3:24)
    at packages/rocketchat_importer-slack/server.coffee:70:23
    at Slack.Importer.Slack.Importer.Slack.Slack.prepare (packages/rocketchat_importer-slack/server.coffee:62:3)
    at Slack.<anonymous> (packages/rocketchat_importer-slack/server.coffee:1:1)
    at Slack.prepare (packages/rocketchat_importer/lib/importTool.coffee:3:24)
    at [object Object].Meteor.methods.prepareImport (packages/rocketchat_importer/server/methods/prepareImport.coffee:7:46)
    at [object Object].methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:17:26)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:707:46
    at Session.method (packages/ddp-server/livedata_server.js:681:23)
    at packages/ddp-server/livedata_server.js:551:43
````

**Comment by graywolf336** [comment] 2016-10-09 20:25
Duplicate of #4388

**Closed by graywolf336** 2016-10-09 20:25 UTC
Labels: feat: import, type: support

**Comment by lc3t35** [comment] 2016-10-10 12:03
update to 0.42.0 fixed the issue. thanks.
