### ISSUE TITLE
Slack-Bridge bug when migrating from 0.63.4 > 0.64.1?

### ISSUE THREAD

**Issue by ChrisKendallVA** [RocketChat/Rocket.Chat#10816] opened 2018-05-18 20:49 UTC
When migrating from 0.63.3 > 0.64.1 the instance fails to load.
According to the logs it appears to be a slackbridge bug on 0.64.1.

* Version of Rocket.Chat Server: 0.64.1
* Operating System: Ubuntu 14.04 64bit
* Deployment Method(snap/docker/tar/etc): Manual
* Number of Running Instances: 1
* DB Replicaset Oplog: rs001
* Node Version: 8.9.3
* mongoDB Version:  3.0.15

### Relevant logs:
```
root@rocket.chat~# pm2 logs rocket.chat
[TAILING] Tailing last 15 lines for [rocket.chat] process (change the value with --lines option)
/opt/rocket.chat/logs/err-0.log last 15 lines:
0|rocket.c |     at SlackBridge.RocketChat.settings.get (/opt/rocket.chat/programs/server/packages/rocketchat_slackbridge.js:191:14)
0|rocket.c |     at Object.get (/opt/rocket.chat/programs/server/packages/rocketchat_lib.js:1000:46)
0|rocket.c |     at new SlackBridge (/opt/rocket.chat/programs/server/packages/rocketchat_slackbridge.js:189:25)
0|rocket.c |     at slackbridge.js (/opt/rocket.chat/programs/server/packages/rocketchat_slackbridge.js:1735:26)
0|rocket.c |     at fileEvaluate (packages/modules-runtime.js:343:9)
0|rocket.c |     at require (packages/modules-runtime.js:238:16)
0|rocket.c |     at /opt/rocket.chat/programs/server/packages/rocketchat_slackbridge.js:1828:1
0|rocket.c |     at /opt/rocket.chat/programs/server/packages/rocketchat_slackbridge.js:1834:3
0|rocket.c |     at /opt/rocket.chat/programs/server/boot.js:411:36
0|rocket.c |     at Array.forEach (<anonymous>:null:null)
0|rocket.c |     at /opt/rocket.chat/programs/server/boot.js:220:19
0|rocket.c |     at /opt/rocket.chat/programs/server/boot.js:471:5
0|rocket.c |     at Function.run (/opt/rocket.chat/programs/server/profile.js:510:12)
0|rocket.c |     at /opt/rocket.chat/programs/server/boot.js:470:11
0|rocket.c |

/opt/rocket.chat/logs/app-0.log last 15 lines:
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_button_label_color
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Dolphin_button_color
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Drupal
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Drupal_id
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Drupal_secret
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Tokenpass
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Tokenpass_id
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Tokenpass_secret
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Tokenpass_callback_url
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Drupal_callback_url
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Facebook_callback_url
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Linkedin_callback_url
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_Twitter_callback_url
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_id
0|rocket.c | rocketchat_logger rocketchat_logger.js:278 rocketchat:lib ➔ oauth_updated Accounts_OAuth_GitHub_Enterprise_secret```

Disabling slackbridge with ```db.rocketchat_settings.update({_id:'SlackBridge_Enabled'},{$set:{value:false}});``` allows the instance to startup correctly.

**Comment by nedbase-jesse** [comment] 2018-05-22 08:46
I have the same problem on 0.64.2
`SlackBridge ➔ Connection.info Connecting via token:  xoxb-xxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx
Exception in callback of async function: TypeError: RtmClient is not a constructor
    at SlackBridge.connect (/app/bundle/programs/server/packages/rocketchat_slackbridge.js:203:18)
    at SlackBridge.RocketChat.settings.get (/app/bundle/programs/server/packages/rocketchat_slackbridge.js:191:14)
    at Object.get (/app/bundle/programs/server/packages/rocketchat_lib.js:1000:46)
    at new SlackBridge (/app/bundle/programs/server/packages/rocketchat_slackbridge.js:189:25)
    at slackbridge.js (/app/bundle/programs/server/packages/rocketchat_slackbridge.js:1735:26)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /app/bundle/programs/server/packages/rocketchat_slackbridge.js:1828:1
    at /app/bundle/programs/server/packages/rocketchat_slackbridge.js:1834:3
    at /app/bundle/programs/server/boot.js:411:36
    at Array.forEach (&lt;anonymous&gt;:null:null)
    at /app/bundle/programs/server/boot.js:220:19
    at /app/bundle/programs/server/boot.js:471:5
    at Function.run (/app/bundle/programs/server/profile.js:510:12)
    at /app/bundle/programs/server/boot.js:470:11`

**Comment by moonwolf-github** [comment] 2018-05-22 20:05
Duplicate of #10624.

**Comment by RichardFoxworthy** [comment] 2018-05-24 02:53
Same problem. This issue prevented my Ubuntu Snap from refreshing successully - it gave me a 502 Bad Gateway error, and I have to revert my snap back to 63.3 so I could disable Slackbridge and complete the upgrade. Re-enabled Slackbridge in 64.2 and get this error:

`[34mI20180524-02:15:01.533(0) [34mSlackBridge ➔ Connection.info Connecting via token:  xoxb-xxxxxxxxxxxxxxxxxxxxxxxxxxxx Exception in changed observe/observeChanges callback: TypeError: RtmClient is not a constructor     at SlackBridge.connect (/snap/rocketchat-server/1265/programs/server/packages/rocketchat_slackbridge.js:203:18)     at SlackBridge.RocketChat.settings.get (/snap/rocketchat-server/1265/programs/server/packages/rocketchat_slackbridge.js:191:14)     at RocketChat.settings.callbacks.(anonymous function).forEach.callback (/snap/rocketchat-server/1265/programs/server/packages/rocketchat_lib.js:1046:65)     at Array.forEach (<anonymous>:null:null)     at forEach.item (/snap/rocketchat-server/1265/programs/server/packages/rocketchat_lib.js:1046:45)     at Array.forEach (<anonymous>:null:null)     at Object.load (/snap/rocketchat-server/1265/programs/server/packages/rocketchat_lib.js:1044:16)     at Object.changed (/snap/rocketchat-server/1265/programs/server/packages/rocketchat_lib.js:5589:34)     at _CachingChangeObserver.changed (/snap/rocketchat-server/1265/programs/server/packages/minimongo.js:3510:28)     at applyChange.changed (/snap/rocketchat-server/1265/programs/server/packages/minimongo.js:2972:27)     at runWithEnvironment (packages/meteor.js:1238:24)     at packages/meteor.js:1251:14     at /snap/rocketchat-server/1265/programs/server/packages/mongo.js:1924:30     at Array.forEach (<anonymous>:null:null)     at Function._.each._.forEach (packages/underscore.js:139:11)     at Object.task (/snap/rocketchat-server/1265/programs/server/packages/mongo.js:1919:9)     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:869:16)     at packages/meteor.js:846:12  `

**Comment by NikKomarov** [comment] 2018-05-24 04:00
Same here, right now reverted to 63.3, because of broken slack bridge. Stack trace is exactly same as @RichardFoxworthy showed

**Closed** 2018-05-26 19:00 UTC
